Repository openhab/openhab-addons, pull requests merged in 2019-07, with the labels that each got.

#5785 [milight] Updated dead github url to alive openhab-doc url
  bundles/org.openhab.binding.milight/README.md
Labels: documentation

#5503 OSGi-ify 3rd party libraries
  bundles/org.openhab.binding.allplay/lib/tchaikovsky-sources.jar
  bundles/org.openhab.binding.allplay/lib/tchaikovsky.jar
  bundles/org.openhab.binding.allplay/pom.xml
  bundles/org.openhab.binding.allplay/src/main/feature/feature.xml
  bundles/org.openhab.binding.amazondashbutton/pom.xml
  bundles/org.openhab.binding.amazondashbutton/src/main/feature/feature.xml
  bundles/org.openhab.binding.boschindego/pom.xml
  bundles/org.openhab.binding.boschindego/src/main/feature/feature.xml
  bundles/org.openhab.binding.innogysmarthome/pom.xml
  bundles/org.openhab.binding.innogysmarthome/src/main/feature/feature.xml
  bundles/org.openhab.binding.ipp/pom.xml
  bundles/org.openhab.binding.ipp/src/main/feature/feature.xml
  bundles/org.openhab.binding.knx/pom.xml
  bundles/org.openhab.binding.knx/src/main/feature/feature.xml
  bundles/org.openhab.binding.lgwebos/pom.xml
  bundles/org.openhab.binding.lgwebos/src/main/feature/feature.xml
  bundles/org.openhab.binding.mcp23017/pom.xml
  bundles/org.openhab.binding.mcp23017/src/main/feature/feature.xml
  bundles/org.openhab.binding.minecraft/pom.xml
  bundles/org.openhab.binding.minecraft/src/main/feature/feature.xml
  bundles/org.openhab.binding.netatmo/pom.xml
  bundles/org.openhab.binding.netatmo/src/main/feature/feature.xml
  bundles/org.openhab.binding.network/pom.xml
  bundles/org.openhab.binding.network/src/main/feature/feature.xml
  bundles/org.openhab.io.azureiothub/pom.xml
  bundles/org.openhab.io.azureiothub/src/main/feature/feature.xml
  bundles/org.openhab.io.homekit/pom.xml
  bundles/org.openhab.io.homekit/src/main/feature/feature.xml
  bundles/org.openhab.io.javasound/pom.xml
  bundles/org.openhab.io.javasound/src/main/feature/feature.xml
  bundles/org.openhab.io.mqttembeddedbroker/pom.xml
  bundles/org.openhab.io.mqttembeddedbroker/src/main/feature/feature.xml
  bundles/org.openhab.io.openhabcloud/pom.xml
  bundles/org.openhab.io.openhabcloud/src/main/feature/feature.xml
  bundles/org.openhab.io.transport.modbus/pom.xml
  bundles/org.openhab.io.transport.modbus/src/main/feature/feature.xml
  bundles/org.openhab.transform.bin2json/pom.xml
  bundles/org.openhab.transform.bin2json/src/main/feature/feature.xml
  bundles/org.openhab.transform.jinja/pom.xml
  bundles/org.openhab.transform.jinja/src/main/feature/feature.xml
  bundles/org.openhab.voice.googletts/pom.xml
  bundles/org.openhab.voice.googletts/src/main/feature/feature.xml
  bundles/org.openhab.voice.pollytts/pom.xml
  bundles/org.openhab.voice.pollytts/src/main/feature/feature.xml
  pom.xml
Labels: infrastructure

#5789 Further evolution of travis build script
  .travis.yml
  buildci.sh
Labels: infrastructure

#5668 [pushbullet] Pushbullet Binding initial contribution
  CODEOWNERS
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.pushbullet/.classpath
  bundles/org.openhab.binding.pushbullet/.project
  bundles/org.openhab.binding.pushbullet/NOTICE
  bundles/org.openhab.binding.pushbullet/README.md
  bundles/org.openhab.binding.pushbullet/pom.xml
  bundles/org.openhab.binding.pushbullet/src/main/feature/feature.xml
  bundles/org.openhab.binding.pushbullet/src/main/java/org/openhab/binding/pushbullet/internal/PushbulletBindingConstants.java
  bundles/org.openhab.binding.pushbullet/src/main/java/org/openhab/binding/pushbullet/internal/PushbulletConfiguration.java
  bundles/org.openhab.binding.pushbullet/src/main/java/org/openhab/binding/pushbullet/internal/PushbulletHandlerFactory.java
  bundles/org.openhab.binding.pushbullet/src/main/java/org/openhab/binding/pushbullet/internal/action/PushbulletActions.java
  bundles/org.openhab.binding.pushbullet/src/main/java/org/openhab/binding/pushbullet/internal/handler/PushbulletHandler.java
  bundles/org.openhab.binding.pushbullet/src/main/java/org/openhab/binding/pushbullet/internal/model/Push.java
  bundles/org.openhab.binding.pushbullet/src/main/java/org/openhab/binding/pushbullet/internal/model/PushError.java
  bundles/org.openhab.binding.pushbullet/src/main/java/org/openhab/binding/pushbullet/internal/model/PushResponse.java
  bundles/org.openhab.binding.pushbullet/src/main/resources/ESH-INF/binding/binding.xml
  bundles/org.openhab.binding.pushbullet/src/main/resources/ESH-INF/i18n/pushbullet_en.properties
  bundles/org.openhab.binding.pushbullet/src/main/resources/ESH-INF/thing/thing-types.xml
  bundles/pom.xml
Labels: binding: pushbullet, new binding

#5590 [amazonechocontrol] Add support for announcement on echo show and echo spot and some other small features
  bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/AccountServlet.java
  bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/AmazonEchoControlBindingConstants.java
  bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/AmazonEchoControlHandlerFactory.java
  bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/BindingServlet.java
  bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/Connection.java
  bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/WebSocketConnection.java
  bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/channelhandler/ChannelHandler.java
  bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/channelhandler/ChannelHandlerAnnouncement.java
  bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/channelhandler/IAmazonThingHandler.java
  bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/discovery/AmazonEchoDiscovery.java
  bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/handler/AccountHandler.java
  bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/handler/EchoHandler.java
  bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/jsons/JsonBootstrapResult.java
  bundles/org.openhab.binding.amazonechocontrol/src/main/resources/ESH-INF/i18n/amazonechocontrol_de.properties
  bundles/org.openhab.binding.amazonechocontrol/src/main/resources/ESH-INF/thing/thing-types.xml
Labels: enhancement

#5700 [somfytahoma] Added recovery from "too many requests" error
  bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/SomfyTahomaBindingConstants.java
  bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/config/SomfyTahomaConfig.java
  bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/discovery/SomfyTahomaItemDiscoveryService.java
  bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/handler/SomfyTahomaBaseThingHandler.java
  bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/handler/SomfyTahomaBridgeHandler.java
  bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/handler/SomfyTahomaWindowHandler.java
  bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/model/SomfyTahomaLoginResponse.java
Labels: bug

#5591 [snmp] SNMP Binding initial contribution
  CODEOWNERS
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.snmp/.classpath
  bundles/org.openhab.binding.snmp/.project
  bundles/org.openhab.binding.snmp/NOTICE
  bundles/org.openhab.binding.snmp/README.md
  bundles/org.openhab.binding.snmp/cfg/snmp.cfg
  bundles/org.openhab.binding.snmp/pom.xml
  bundles/org.openhab.binding.snmp/src/main/feature/feature.xml
  bundles/org.openhab.binding.snmp/src/main/java/org/openhab/binding/snmp/internal/SnmpBindingConstants.java
  bundles/org.openhab.binding.snmp/src/main/java/org/openhab/binding/snmp/internal/SnmpChannelMode.java
  bundles/org.openhab.binding.snmp/src/main/java/org/openhab/binding/snmp/internal/SnmpDatatype.java
  bundles/org.openhab.binding.snmp/src/main/java/org/openhab/binding/snmp/internal/SnmpHandlerFactory.java
  bundles/org.openhab.binding.snmp/src/main/java/org/openhab/binding/snmp/internal/SnmpProtocolVersion.java
  bundles/org.openhab.binding.snmp/src/main/java/org/openhab/binding/snmp/internal/SnmpService.java
  bundles/org.openhab.binding.snmp/src/main/java/org/openhab/binding/snmp/internal/SnmpServiceImpl.java
  bundles/org.openhab.binding.snmp/src/main/java/org/openhab/binding/snmp/internal/SnmpTargetHandler.java
  bundles/org.openhab.binding.snmp/src/main/java/org/openhab/binding/snmp/internal/config/SnmpChannelConfiguration.java
  bundles/org.openhab.binding.snmp/src/main/java/org/openhab/binding/snmp/internal/config/SnmpInternalChannelConfiguration.java
  bundles/org.openhab.binding.snmp/src/main/java/org/openhab/binding/snmp/internal/config/SnmpServiceConfiguration.java
  bundles/org.openhab.binding.snmp/src/main/java/org/openhab/binding/snmp/internal/config/SnmpTargetConfiguration.java
  bundles/org.openhab.binding.snmp/src/main/resources/ESH-INF/binding/binding.xml
  bundles/org.openhab.binding.snmp/src/main/resources/ESH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.snmp/src/test/java/org/openhab/binding/snmp/internal/SnmpTargetHandlerTest.java
  bundles/pom.xml
Labels: new binding

#5806 [allplay,bluez] fix native code bundles
  bundles/org.openhab.binding.allplay/embedExternalDependency.profile
  bundles/org.openhab.binding.allplay/pom.xml
  bundles/org.openhab.binding.allplay/src/main/feature/feature.xml
  bundles/org.openhab.binding.allplay/src/main/java/org/openhab/binding/allplay/package-info.java
  bundles/org.openhab.binding.allplay/src/main/resources/lib/arm/linux/liballjoyn_java.so
  bundles/org.openhab.binding.allplay/src/main/resources/lib/x86-64/linux/liballjoyn_java.so
  bundles/org.openhab.binding.allplay/src/main/resources/lib/x86/linux/liballjoyn_java.so
  bundles/org.openhab.binding.bluetooth.bluez/.classpath
  bundles/org.openhab.binding.bluetooth.bluez/embedExternalDependency.profile
  bundles/org.openhab.binding.bluetooth.bluez/lib/tinyb-0.5.1.jar
  bundles/org.openhab.binding.bluetooth.bluez/pom.xml
  bundles/org.openhab.binding.bluetooth.bluez/src/main/java/org/openhab/binding/bluetooth/bluez/package-info.java
  pom.xml
Labels: additional testing prefered, infrastructure

#5808 [somfytahoma] fixed links to the manufacturer
  bundles/org.openhab.binding.somfytahoma/README.md
Labels: documentation

#5810 [snmp] fix thing.xml
  bundles/org.openhab.binding.snmp/src/main/resources/ESH-INF/thing/thing-types.xml
Labels: bug

#5816 [darksky] Added new channels for precipitation intensity and type
  bundles/org.openhab.binding.darksky/README.md
  bundles/org.openhab.binding.darksky/src/main/java/org/openhab/binding/darksky/internal/DarkSkyBindingConstants.java
  bundles/org.openhab.binding.darksky/src/main/java/org/openhab/binding/darksky/internal/handler/DarkSkyWeatherAndForecastHandler.java
  bundles/org.openhab.binding.darksky/src/main/resources/ESH-INF/i18n/darksky_de.properties
  bundles/org.openhab.binding.darksky/src/main/resources/ESH-INF/thing/channel-types.xml
Labels: enhancement

#5812 [airquality] Feature added: Sulfur dioxide level
  bundles/org.openhab.binding.airquality/README.md
  bundles/org.openhab.binding.airquality/src/main/java/org/openhab/binding/airquality/internal/AirQualityBindingConstants.java
  bundles/org.openhab.binding.airquality/src/main/java/org/openhab/binding/airquality/internal/handler/AirQualityHandler.java
  bundles/org.openhab.binding.airquality/src/main/java/org/openhab/binding/airquality/internal/json/AirQualityJsonIaqi.java
  bundles/org.openhab.binding.airquality/src/main/resources/ESH-INF/thing/thing-types.xml
Labels: enhancement

#4626 [vektiva] Vektiva Binding initial contribution
  CODEOWNERS
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.vektiva/.classpath
  bundles/org.openhab.binding.vektiva/.project
  bundles/org.openhab.binding.vektiva/NOTICE
  bundles/org.openhab.binding.vektiva/README.md
  bundles/org.openhab.binding.vektiva/pom.xml
  bundles/org.openhab.binding.vektiva/src/main/feature/feature.xml
  bundles/org.openhab.binding.vektiva/src/main/java/org/openhab/binding/vektiva/internal/VektivaBindingConstants.java
  bundles/org.openhab.binding.vektiva/src/main/java/org/openhab/binding/vektiva/internal/VektivaHandlerFactory.java
  bundles/org.openhab.binding.vektiva/src/main/java/org/openhab/binding/vektiva/internal/config/VektivaSmarwiConfiguration.java
  bundles/org.openhab.binding.vektiva/src/main/java/org/openhab/binding/vektiva/internal/handler/VektivaSmarwiHandler.java
  bundles/org.openhab.binding.vektiva/src/main/java/org/openhab/binding/vektiva/internal/net/VektivaSmarwiSocket.java
  bundles/org.openhab.binding.vektiva/src/main/resources/ESH-INF/binding/binding.xml
  bundles/org.openhab.binding.vektiva/src/main/resources/ESH-INF/thing/smarwi.xml
  bundles/pom.xml
Labels: cre, new binding

#5795 [rfxcom] Added support for string-commands for Lighting-5 & Lighting-1
  bundles/org.openhab.binding.rfxcom/README.md
  bundles/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/messages/RFXComLighting1Message.java
  bundles/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/messages/RFXComLighting5Message.java
  bundles/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/messages/RFXComRfyMessage.java
  bundles/org.openhab.binding.rfxcom/src/main/resources/ESH-INF/thing/lighting1.xml
  bundles/org.openhab.binding.rfxcom/src/main/resources/ESH-INF/thing/lighting5.xml
  bundles/org.openhab.binding.rfxcom/src/test/java/org/openhab/binding/rfxcom/internal/messages/RFXComLighting1MessageTest.java
  bundles/org.openhab.binding.rfxcom/src/test/java/org/openhab/binding/rfxcom/internal/messages/RFXComLighting5MessageTest.java
Labels: cre, enhancement

#5746 [network] Cleaning Speedtest start / stop process
  bundles/org.openhab.binding.network/README.md
  bundles/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/SpeedTestConfiguration.java
  bundles/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/handler/SpeedTestHandler.java
  bundles/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/utils/NetworkUtils.java
  bundles/org.openhab.binding.network/src/main/resources/ESH-INF/thing/thing-types.xml
Labels: cre

#5781 [lutron] Add support for HomeWorks QS International seeTouch keypads
  bundles/org.openhab.binding.lutron/README.md
  bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/LutronBindingConstants.java
  bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/LutronHandlerFactory.java
  bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/discovery/LutronDeviceDiscoveryService.java
  bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/discovery/project/DeviceType.java
  bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/handler/IntlKeypadHandler.java
  bundles/org.openhab.binding.lutron/src/main/resources/ESH-INF/thing/thing-types.xml
Labels: cre, enhancement

#5782 [lutron] Add support for HomeWorks QS IO Interface (QSE-IO)
  bundles/org.openhab.binding.lutron/README.md
  bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/LutronBindingConstants.java
  bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/LutronHandlerFactory.java
  bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/discovery/LutronDeviceDiscoveryService.java
  bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/discovery/project/DeviceType.java
  bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/handler/QSIOHandler.java
  bundles/org.openhab.binding.lutron/src/main/resources/ESH-INF/thing/thing-types.xml
Labels: cre, enhancement

#5824 [network] Minor tweaks of documentation
  bundles/org.openhab.binding.network/README.md
Labels: documentation

#4475 [ambientweather] Ambient Weather Binding initial contribution
  CODEOWNERS
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.ambientweather/.classpath
  bundles/org.openhab.binding.ambientweather/.project
  bundles/org.openhab.binding.ambientweather/NOTICE
  bundles/org.openhab.binding.ambientweather/README.md
  bundles/org.openhab.binding.ambientweather/pom.xml
  bundles/org.openhab.binding.ambientweather/src/main/feature/feature.xml
  bundles/org.openhab.binding.ambientweather/src/main/java/org/openhab/binding/ambientweather/internal/AmbientWeatherBindingConstants.java
  bundles/org.openhab.binding.ambientweather/src/main/java/org/openhab/binding/ambientweather/internal/AmbientWeatherHandlerFactory.java
  bundles/org.openhab.binding.ambientweather/src/main/java/org/openhab/binding/ambientweather/internal/config/BridgeConfig.java
  bundles/org.openhab.binding.ambientweather/src/main/java/org/openhab/binding/ambientweather/internal/config/StationConfig.java
  bundles/org.openhab.binding.ambientweather/src/main/java/org/openhab/binding/ambientweather/internal/handler/AmbientWeatherBridgeHandler.java
  bundles/org.openhab.binding.ambientweather/src/main/java/org/openhab/binding/ambientweather/internal/handler/AmbientWeatherEventListener.java
  bundles/org.openhab.binding.ambientweather/src/main/java/org/openhab/binding/ambientweather/internal/handler/AmbientWeatherStationHandler.java
  bundles/org.openhab.binding.ambientweather/src/main/java/org/openhab/binding/ambientweather/internal/model/DeviceJson.java
  bundles/org.openhab.binding.ambientweather/src/main/java/org/openhab/binding/ambientweather/internal/model/EventDataGenericJson.java
  bundles/org.openhab.binding.ambientweather/src/main/java/org/openhab/binding/ambientweather/internal/model/EventDataJson.java
  bundles/org.openhab.binding.ambientweather/src/main/java/org/openhab/binding/ambientweather/internal/model/EventSubscribedJson.java
  bundles/org.openhab.binding.ambientweather/src/main/java/org/openhab/binding/ambientweather/internal/model/StationInfoJson.java
  bundles/org.openhab.binding.ambientweather/src/main/java/org/openhab/binding/ambientweather/internal/processor/AbstractProcessor.java
  bundles/org.openhab.binding.ambientweather/src/main/java/org/openhab/binding/ambientweather/internal/processor/ProcessorFactory.java
  bundles/org.openhab.binding.ambientweather/src/main/java/org/openhab/binding/ambientweather/internal/processor/ProcessorInterface.java
  bundles/org.openhab.binding.ambientweather/src/main/java/org/openhab/binding/ambientweather/internal/processor/ProcessorNotFoundException.java
  bundles/org.openhab.binding.ambientweather/src/main/java/org/openhab/binding/ambientweather/internal/processor/RemoteSensor.java
  bundles/org.openhab.binding.ambientweather/src/main/java/org/openhab/binding/ambientweather/internal/processor/Ws0900ipProcessor.java
  bundles/org.openhab.binding.ambientweather/src/main/java/org/openhab/binding/ambientweather/internal/processor/Ws1400ipProcessor.java
  bundles/org.openhab.binding.ambientweather/src/main/java/org/openhab/binding/ambientweather/internal/processor/Ws2902aProcessor.java
  bundles/org.openhab.binding.ambientweather/src/main/java/org/openhab/binding/ambientweather/internal/processor/Ws8482Processor.java
  bundles/org.openhab.binding.ambientweather/src/main/java/org/openhab/binding/ambientweather/internal/util/PressureTrend.java
  bundles/org.openhab.binding.ambientweather/src/main/java/org/openhab/binding/ambientweather/internal/util/SlidingTimeWindow.java
  bundles/org.openhab.binding.ambientweather/src/main/resources/ESH-INF/binding/binding.xml
  bundles/org.openhab.binding.ambientweather/src/main/resources/ESH-INF/config/bridge-config.xml
  bundles/org.openhab.binding.ambientweather/src/main/resources/ESH-INF/config/station-config.xml
  bundles/org.openhab.binding.ambientweather/src/main/resources/ESH-INF/i18n/ambientweather.properties
  bundles/org.openhab.binding.ambientweather/src/main/resources/ESH-INF/thing/bridge.xml
  bundles/org.openhab.binding.ambientweather/src/main/resources/ESH-INF/thing/channel-group-types.xml
  bundles/org.openhab.binding.ambientweather/src/main/resources/ESH-INF/thing/channels.xml
  bundles/org.openhab.binding.ambientweather/src/main/resources/ESH-INF/thing/ws0900.xml
  bundles/org.openhab.binding.ambientweather/src/main/resources/ESH-INF/thing/ws1400ip.xml
  bundles/org.openhab.binding.ambientweather/src/main/resources/ESH-INF/thing/ws2902a.xml
  bundles/org.openhab.binding.ambientweather/src/main/resources/ESH-INF/thing/ws8482.xml
  bundles/pom.xml
Labels: cre, new binding

#5823 [lutron] Documentation update
  bundles/org.openhab.binding.lutron/README.md
  bundles/org.openhab.binding.lutron/src/main/resources/ESH-INF/binding/binding.xml
Labels: documentation

#5809 [netatmo] Recompute VPN URL
  bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/welcome/NAWelcomeCameraHandler.java
Labels: cre, enhancement

#5830 [amazonechocontrol] Bugfix for announcement channel
  bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/Connection.java
  bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/handler/EchoHandler.java
Labels: bug, critical

#5510 [kodi] New features: Audio and Subtitle and IMDB ID
  bundles/org.openhab.binding.kodi/README.md
  bundles/org.openhab.binding.kodi/src/main/java/org/openhab/binding/kodi/internal/KodiBindingConstants.java
  bundles/org.openhab.binding.kodi/src/main/java/org/openhab/binding/kodi/internal/KodiEventListener.java
  bundles/org.openhab.binding.kodi/src/main/java/org/openhab/binding/kodi/internal/handler/KodiHandler.java
  bundles/org.openhab.binding.kodi/src/main/java/org/openhab/binding/kodi/internal/model/KodiSubtitle.java
  bundles/org.openhab.binding.kodi/src/main/java/org/openhab/binding/kodi/internal/model/KodiUniqueID.java
  bundles/org.openhab.binding.kodi/src/main/java/org/openhab/binding/kodi/internal/protocol/KodiConnection.java
  bundles/org.openhab.binding.kodi/src/main/resources/ESH-INF/thing/thing-types.xml
Labels: enhancement

#5850 [skeleton] Use correct repository URL for the archetype
  bundles/archetype-settings.xml
Labels: infrastructure

#5833 [avmfritz] Reenable itests
  bundles/org.openhab.binding.avmfritz/pom.xml
  bundles/org.openhab.binding.avmfritz/src/main/feature/feature.xml
  itests/itest-common.bndrun
  itests/org.openhab.binding.avmfritz.tests/itest.bndrun
  itests/org.openhab.binding.avmfritz.tests/pom.xml
  itests/org.openhab.binding.avmfritz.tests/src/main/java/org/openhab/binding/avmfritz/internal/discovery/AVMFritzDiscoveryServiceOSGiTest.java
  itests/org.openhab.binding.nest.tests/itest.bndrun
  itests/org.openhab.binding.nest.tests/pom.xml
Labels: bug, build

#4842 [sonyprojector] Sony Projector Binding initial contribution
  CODEOWNERS
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.sonyprojector/.classpath
  bundles/org.openhab.binding.sonyprojector/.project
  bundles/org.openhab.binding.sonyprojector/NOTICE
  bundles/org.openhab.binding.sonyprojector/README.md
  bundles/org.openhab.binding.sonyprojector/pom.xml
  bundles/org.openhab.binding.sonyprojector/src/main/feature/feature.xml
  bundles/org.openhab.binding.sonyprojector/src/main/java/org/openhab/binding/sonyprojector/internal/SonyProjectorBindingConstants.java
  bundles/org.openhab.binding.sonyprojector/src/main/java/org/openhab/binding/sonyprojector/internal/SonyProjectorException.java
  bundles/org.openhab.binding.sonyprojector/src/main/java/org/openhab/binding/sonyprojector/internal/SonyProjectorHandlerFactory.java
  bundles/org.openhab.binding.sonyprojector/src/main/java/org/openhab/binding/sonyprojector/internal/SonyProjectorModel.java
  bundles/org.openhab.binding.sonyprojector/src/main/java/org/openhab/binding/sonyprojector/internal/SonyProjectorStateDescriptionOptionProvider.java
  bundles/org.openhab.binding.sonyprojector/src/main/java/org/openhab/binding/sonyprojector/internal/communication/SonyProjectorAspect.java
  bundles/org.openhab.binding.sonyprojector/src/main/java/org/openhab/binding/sonyprojector/internal/communication/SonyProjectorBlockNr.java
  bundles/org.openhab.binding.sonyprojector/src/main/java/org/openhab/binding/sonyprojector/internal/communication/SonyProjectorCalibrationPreset.java
  bundles/org.openhab.binding.sonyprojector/src/main/java/org/openhab/binding/sonyprojector/internal/communication/SonyProjectorColorSpace.java
  bundles/org.openhab.binding.sonyprojector/src/main/java/org/openhab/binding/sonyprojector/internal/communication/SonyProjectorColorTemp.java
  bundles/org.openhab.binding.sonyprojector/src/main/java/org/openhab/binding/sonyprojector/internal/communication/SonyProjectorConnector.java
  bundles/org.openhab.binding.sonyprojector/src/main/java/org/openhab/binding/sonyprojector/internal/communication/SonyProjectorContrastEnhancer.java
  bundles/org.openhab.binding.sonyprojector/src/main/java/org/openhab/binding/sonyprojector/internal/communication/SonyProjectorFilmMode.java
  bundles/org.openhab.binding.sonyprojector/src/main/java/org/openhab/binding/sonyprojector/internal/communication/SonyProjectorFilmProjection.java
  bundles/org.openhab.binding.sonyprojector/src/main/java/org/openhab/binding/sonyprojector/internal/communication/SonyProjectorGammaCorrection.java
  bundles/org.openhab.binding.sonyprojector/src/main/java/org/openhab/binding/sonyprojector/internal/communication/SonyProjectorInput.java
  bundles/org.openhab.binding.sonyprojector/src/main/java/org/openhab/binding/sonyprojector/internal/communication/SonyProjectorIrisMode.java
  bundles/org.openhab.binding.sonyprojector/src/main/java/org/openhab/binding/sonyprojector/internal/communication/SonyProjectorIrisSensitivity.java
  bundles/org.openhab.binding.sonyprojector/src/main/java/org/openhab/binding/sonyprojector/internal/communication/SonyProjectorItem.java
  bundles/org.openhab.binding.sonyprojector/src/main/java/org/openhab/binding/sonyprojector/internal/communication/SonyProjectorLampControl.java
  bundles/org.openhab.binding.sonyprojector/src/main/java/org/openhab/binding/sonyprojector/internal/communication/SonyProjectorMosquitoNr.java
  bundles/org.openhab.binding.sonyprojector/src/main/java/org/openhab/binding/sonyprojector/internal/communication/SonyProjectorMotionEnhancer.java
  bundles/org.openhab.binding.sonyprojector/src/main/java/org/openhab/binding/sonyprojector/internal/communication/SonyProjectorMpegNr.java
  bundles/org.openhab.binding.sonyprojector/src/main/java/org/openhab/binding/sonyprojector/internal/communication/SonyProjectorNr.java
  bundles/org.openhab.binding.sonyprojector/src/main/java/org/openhab/binding/sonyprojector/internal/communication/SonyProjectorPicturePosition.java
  bundles/org.openhab.binding.sonyprojector/src/main/java/org/openhab/binding/sonyprojector/internal/communication/SonyProjectorStatusPower.java
  bundles/org.openhab.binding.sonyprojector/src/main/java/org/openhab/binding/sonyprojector/internal/communication/sdcp/SonyProjectorSdcpConnector.java
  bundles/org.openhab.binding.sonyprojector/src/main/java/org/openhab/binding/sonyprojector/internal/communication/sdcp/SonyProjectorSdcpError.java
  bundles/org.openhab.binding.sonyprojector/src/main/java/org/openhab/binding/sonyprojector/internal/communication/sdcp/SonyProjectorSdcpSimuConnector.java
  bundles/org.openhab.binding.sonyprojector/src/main/java/org/openhab/binding/sonyprojector/internal/communication/serial/SonyProjectorSerialConnector.java
  bundles/org.openhab.binding.sonyprojector/src/main/java/org/openhab/binding/sonyprojector/internal/communication/serial/SonyProjectorSerialError.java
  bundles/org.openhab.binding.sonyprojector/src/main/java/org/openhab/binding/sonyprojector/internal/communication/serial/SonyProjectorSerialOverIpConnector.java
  bundles/org.openhab.binding.sonyprojector/src/main/java/org/openhab/binding/sonyprojector/internal/communication/serial/SonyProjectorSerialSimuConnector.java
  bundles/org.openhab.binding.sonyprojector/src/main/java/org/openhab/binding/sonyprojector/internal/configuration/SonyProjectorEthernetConfiguration.java
  bundles/org.openhab.binding.sonyprojector/src/main/java/org/openhab/binding/sonyprojector/internal/configuration/SonyProjectorSerialConfiguration.java
  bundles/org.openhab.binding.sonyprojector/src/main/java/org/openhab/binding/sonyprojector/internal/configuration/SonyProjectorSerialOverIpConfiguration.java
  bundles/org.openhab.binding.sonyprojector/src/main/java/org/openhab/binding/sonyprojector/internal/handler/SonyProjectorHandler.java
  bundles/org.openhab.binding.sonyprojector/src/main/resources/ESH-INF/binding/binding.xml
  bundles/org.openhab.binding.sonyprojector/src/main/resources/ESH-INF/thing/channels.xml
  bundles/org.openhab.binding.sonyprojector/src/main/resources/ESH-INF/thing/ethernet.xml
  bundles/org.openhab.binding.sonyprojector/src/main/resources/ESH-INF/thing/serial.xml
  bundles/org.openhab.binding.sonyprojector/src/main/resources/ESH-INF/thing/serialoverip.xml
  bundles/pom.xml
Labels: cre, new binding
