Repository openhab/openhab-addons, pull requests merged in 2019-05, with the labels that each got.

#5528 [spotify] Fixed deadlock causing status to stop.
  bundles/org.openhab.binding.spotify/README.md
  bundles/org.openhab.binding.spotify/src/main/java/org/openhab/binding/spotify/internal/api/SpotifyConnector.java
  bundles/org.openhab.binding.spotify/src/main/java/org/openhab/binding/spotify/internal/discovery/SpotifyDeviceDiscoveryService.java
  bundles/org.openhab.binding.spotify/src/main/java/org/openhab/binding/spotify/internal/handler/SpotifyBridgeHandler.java
  bundles/org.openhab.binding.spotify/src/main/java/org/openhab/binding/spotify/internal/handler/SpotifyDeviceHandler.java
  bundles/org.openhab.binding.spotify/src/main/java/org/openhab/binding/spotify/internal/handler/SpotifyHandleCommands.java
  bundles/org.openhab.binding.spotify/src/main/resources/ESH-INF/thing/thing-types.xml
Labels: bug

#5538 [homekit] migrate to bnd
  CODEOWNERS
  addons/io/org.openhab.io.homekit/.classpath
  addons/io/org.openhab.io.homekit/META-INF/MANIFEST.MF
  addons/io/org.openhab.io.homekit/OSGI-INF/.gitignore
  addons/io/org.openhab.io.homekit/build.properties
  addons/io/org.openhab.io.homekit/lib/com.beowulfe.hap.hap-1.1.4.jar
  addons/io/org.openhab.io.homekit/lib/com.nimbusds.srp6a-1.5.2.jar
  addons/io/org.openhab.io.homekit/lib/io.netty.netty-all-4.0.32.Final.jar
  addons/io/org.openhab.io.homekit/lib/javax.json.javax.json-api-1.0.jar
  addons/io/org.openhab.io.homekit/lib/net.i2p.crypto.eddsa-0.0.1-SNAPSHOT.jar
  addons/io/org.openhab.io.homekit/lib/org.bouncycastle.bcprov-jdk15on-1.51.jar
  addons/io/org.openhab.io.homekit/lib/org.glassfish.javax.json-1.0.4.jar
  addons/io/org.openhab.io.homekit/lib/org.zeromq.curve25519-java-0.1.0.jar
  addons/io/org.openhab.io.homekit/pom.xml
  addons/io/pom.xml
  addons/pom.xml
  bom/openhab-addons/pom.xml
  bundles/org.openhab.io.homekit/.classpath
  bundles/org.openhab.io.homekit/.project
  bundles/org.openhab.io.homekit/NOTICE
  bundles/org.openhab.io.homekit/README.md
  bundles/org.openhab.io.homekit/pom.xml
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/Homekit.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitAccessoryRegistry.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitAccessoryUpdater.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitAuthInfoImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitChangeListener.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitCharacteristicType.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitCommandExtension.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitDeviceType.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitSettings.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitTaggedItem.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/AbstractHomekitAccessoryImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/AbstractHomekitLightbulbImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/AbstractTemperatureHomekitAccessoryImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/GroupedAccessory.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitAccessoryFactory.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitColorfulLightbulbImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitContactSensorImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitDimmableLightbulbImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitHumiditySensorImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitLightbulbImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitSwitchImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitTemperatureSensorImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitThermostatImpl.java
  bundles/org.openhab.io.homekit/src/main/resources/ESH-INF/config/config.xml
  bundles/pom.xml
  features/karaf/openhab-addons/src/main/feature/feature.xml
  pom.xml
  poms/tycho/pom.xml
Labels: infrastructure

#5546 Move karaf features to features directory. Remove poms subdir.
  README.md
  bom/pom.xml
  bundles/pom.xml
  features/karaf/pom.xml
  features/openhab-addons-external/.project
  features/openhab-addons-external/pom.xml
  features/openhab-addons-external/src/main/resources/conf/cometvisu.cfg
  features/openhab-addons-external/src/main/resources/conf/openhabcloud.cfg
  features/openhab-addons-external/src/main/resources/conf/voicerss.cfg
  features/openhab-addons-external/src/main/resources/lib/libLeap.dylib
  features/openhab-addons-external/src/main/resources/lib/libLeapJava.dylib
  features/openhab-addons/.project
  features/openhab-addons/pom.xml
  features/openhab-addons/src/main/feature/feature.xml
  features/pom.xml
  features/readme.md
  itests/pom.xml
  pom.xml
  poms/bnd/pom.xml
Labels: infrastructure

#5553 Fixes #5416. Daily snapshot downloads only
  pom.xml
Labels: infrastructure

#5563 Changing 'latency' channel to be UoM Number:Time
  bundles/org.openhab.binding.network/README.md
  bundles/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/handler/NetworkHandler.java
  bundles/org.openhab.binding.network/src/main/resources/ESH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.network/src/test/java/org/openhab/binding/network/internal/handler/NetworkHandlerTest.java
Labels: enhancement

#4169 [samsungtv] Added websocket support for remote controller (2016+ models)
  bundles/org.openhab.binding.samsungtv/.classpath
  bundles/org.openhab.binding.samsungtv/README.md
  bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/SamsungTvBindingConstants.java
  bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/SamsungTvHandlerFactory.java
  bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/SamsungTvTlsTrustManagerProvider.java
  bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/WakeOnLanUtility.java
  bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/config/SamsungTvConfiguration.java
  bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/discovery/SamsungTvDiscoveryParticipant.java
  bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/handler/SamsungTvHandler.java
  bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/protocol/RemoteController.java
  bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/protocol/RemoteControllerException.java
  bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/protocol/RemoteControllerLegacy.java
  bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/protocol/RemoteControllerWebSocket.java
  bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/protocol/RemoteControllerWebsocketCallback.java
  bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/protocol/WebSocketArt.java
  bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/protocol/WebSocketBase.java
  bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/protocol/WebSocketRemote.java
  bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/protocol/WebSocketV2.java
  bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/service/DataConverters.java
  bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/service/MainTVServerService.java
  bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/service/MediaRendererService.java
  bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/service/RemoteControllerService.java
  bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/service/SamsungTvUtils.java
  bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/service/ServiceFactory.java
  bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/service/api/EventListener.java
  bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/service/api/SamsungTvService.java
  bundles/org.openhab.binding.samsungtv/src/main/resources/ESH-INF/binding/binding.xml
  bundles/org.openhab.binding.samsungtv/src/main/resources/ESH-INF/config/config.xml
  bundles/org.openhab.binding.samsungtv/src/main/resources/ESH-INF/thing/channel-types.xml
  bundles/org.openhab.binding.samsungtv/src/main/resources/ESH-INF/thing/thing-types.xml
Labels: discussion, enhancement

#5567 [spotify] Fixed typo in things example in README
  bundles/org.openhab.binding.spotify/README.md
Labels: documentation

#5570 Fix Jenkins builds
  bundles/org.openhab.binding.xmppclient/pom.xml
  bundles/org.openhab.io.javasound/src/main/feature/feature.xml
  bundles/org.openhab.io.mqttembeddedbroker/pom.xml
  bundles/org.openhab.io.mqttembeddedbroker/src/main/feature/feature.xml
Labels: infrastructure

#5578 Adjust bundle names
  bundles/org.openhab.extensionservice.marketplace.automation/pom.xml
  bundles/org.openhab.extensionservice.marketplace/pom.xml
  bundles/org.openhab.io.azureiothub/pom.xml
  bundles/org.openhab.io.homekit/pom.xml
  bundles/org.openhab.io.hueemulation/pom.xml
  bundles/org.openhab.io.imperihome/pom.xml
  bundles/org.openhab.io.javasound/pom.xml
  bundles/org.openhab.io.neeo/pom.xml
  bundles/org.openhab.io.openhabcloud/pom.xml
  bundles/org.openhab.io.transport.modbus/pom.xml
  bundles/org.openhab.io.webaudio/pom.xml
  bundles/org.openhab.persistence.mapdb/pom.xml
  bundles/org.openhab.transform.bin2json/pom.xml
  bundles/org.openhab.transform.exec/pom.xml
  bundles/org.openhab.transform.javascript/pom.xml
  bundles/org.openhab.transform.jinja/pom.xml
  bundles/org.openhab.transform.jsonpath/pom.xml
  bundles/org.openhab.transform.map/pom.xml
  bundles/org.openhab.transform.regex/pom.xml
  bundles/org.openhab.transform.scale/pom.xml
  bundles/org.openhab.transform.xpath/pom.xml
  bundles/org.openhab.transform.xslt/pom.xml
  bundles/org.openhab.voice.googletts/pom.xml
  bundles/org.openhab.voice.mactts/pom.xml
  bundles/org.openhab.voice.marytts/pom.xml
  bundles/org.openhab.voice.picotts/pom.xml
  bundles/org.openhab.voice.pollytts/pom.xml
  bundles/org.openhab.voice.voicerss/pom.xml
Labels: infrastructure

#5551 [infrastructure] auto-create addons-BOM
  bom/openhab-addons/pom.xml
  bom/pom.xml
Labels: infrastructure

#5580 fix feature verification
  bundles/pom.xml
  pom.xml
Labels: infrastructure

#5593 [squeezebox] Revert changes from #5497
  bundles/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/handler/SqueezeBoxServerHandler.java
Labels: bug

#3740 [volvooncall] Volvo On Call Binding initial contribution
  CODEOWNERS
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.volvooncall/.classpath
  bundles/org.openhab.binding.volvooncall/.project
  bundles/org.openhab.binding.volvooncall/NOTICE
  bundles/org.openhab.binding.volvooncall/README.md
  bundles/org.openhab.binding.volvooncall/pom.xml
  bundles/org.openhab.binding.volvooncall/src/main/feature/feature.xml
  bundles/org.openhab.binding.volvooncall/src/main/java/org/openhab/binding/volvooncall/internal/VolvoOnCallBindingConstants.java
  bundles/org.openhab.binding.volvooncall/src/main/java/org/openhab/binding/volvooncall/internal/VolvoOnCallHandlerFactory.java
  bundles/org.openhab.binding.volvooncall/src/main/java/org/openhab/binding/volvooncall/internal/action/VolvoOnCallActions.java
  bundles/org.openhab.binding.volvooncall/src/main/java/org/openhab/binding/volvooncall/internal/config/VehicleConfiguration.java
  bundles/org.openhab.binding.volvooncall/src/main/java/org/openhab/binding/volvooncall/internal/config/VolvoOnCallBridgeConfiguration.java
  bundles/org.openhab.binding.volvooncall/src/main/java/org/openhab/binding/volvooncall/internal/discovery/VolvoOnCallDiscoveryService.java
  bundles/org.openhab.binding.volvooncall/src/main/java/org/openhab/binding/volvooncall/internal/dto/AccountVehicleRelation.java
  bundles/org.openhab.binding.volvooncall/src/main/java/org/openhab/binding/volvooncall/internal/dto/Attributes.java
  bundles/org.openhab.binding.volvooncall/src/main/java/org/openhab/binding/volvooncall/internal/dto/CustomerAccounts.java
  bundles/org.openhab.binding.volvooncall/src/main/java/org/openhab/binding/volvooncall/internal/dto/DoorsStatus.java
  bundles/org.openhab.binding.volvooncall/src/main/java/org/openhab/binding/volvooncall/internal/dto/ERSStatus.java
  bundles/org.openhab.binding.volvooncall/src/main/java/org/openhab/binding/volvooncall/internal/dto/Position.java
  bundles/org.openhab.binding.volvooncall/src/main/java/org/openhab/binding/volvooncall/internal/dto/PositionData.java
  bundles/org.openhab.binding.volvooncall/src/main/java/org/openhab/binding/volvooncall/internal/dto/PostResponse.java
  bundles/org.openhab.binding.volvooncall/src/main/java/org/openhab/binding/volvooncall/internal/dto/Status.java
  bundles/org.openhab.binding.volvooncall/src/main/java/org/openhab/binding/volvooncall/internal/dto/Trip.java
  bundles/org.openhab.binding.volvooncall/src/main/java/org/openhab/binding/volvooncall/internal/dto/TripDetail.java
  bundles/org.openhab.binding.volvooncall/src/main/java/org/openhab/binding/volvooncall/internal/dto/Trips.java
  bundles/org.openhab.binding.volvooncall/src/main/java/org/openhab/binding/volvooncall/internal/dto/TyrePressure.java
  bundles/org.openhab.binding.volvooncall/src/main/java/org/openhab/binding/volvooncall/internal/dto/Vehicles.java
  bundles/org.openhab.binding.volvooncall/src/main/java/org/openhab/binding/volvooncall/internal/dto/WindowsStatus.java
  bundles/org.openhab.binding.volvooncall/src/main/java/org/openhab/binding/volvooncall/internal/handler/VehicleHandler.java
  bundles/org.openhab.binding.volvooncall/src/main/java/org/openhab/binding/volvooncall/internal/handler/VehicleStateDescriptionProvider.java
  bundles/org.openhab.binding.volvooncall/src/main/java/org/openhab/binding/volvooncall/internal/handler/VolvoOnCallBridgeHandler.java
  bundles/org.openhab.binding.volvooncall/src/main/java/org/openhab/binding/volvooncall/internal/wrapper/VehiclePositionWrapper.java
  bundles/org.openhab.binding.volvooncall/src/main/resources/ESH-INF/binding/binding.xml
  bundles/org.openhab.binding.volvooncall/src/main/resources/ESH-INF/config/config.xml
  bundles/org.openhab.binding.volvooncall/src/main/resources/ESH-INF/thing/bridge.xml
  bundles/org.openhab.binding.volvooncall/src/main/resources/ESH-INF/thing/vehicle.xml
  bundles/pom.xml
Labels: new binding

#5601 [openhabcloud] Reduced logging levels
  bundles/org.openhab.io.openhabcloud/src/main/java/org/openhab/io/openhabcloud/internal/CloudClient.java
Labels: io: openhabcloud

#5612 [openhabcloud] Switched to shared Jetty `HttpClient` instance
  bundles/org.openhab.io.openhabcloud/src/main/java/org/openhab/io/openhabcloud/internal/CloudClient.java
  bundles/org.openhab.io.openhabcloud/src/main/java/org/openhab/io/openhabcloud/internal/CloudService.java
Labels: io: openhabcloud

#5610 [homekit] fix wrong group tag handling
  bundles/org.openhab.io.homekit/README.md
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitAccessoryType.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitChangeListener.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitCharacteristicType.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitTaggedItem.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitAccessoryFactory.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitThermostatImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/IncompleteAccessoryException.java
Labels: bug

#5631 [openhabcloud] Do not set timeout globally
  bundles/org.openhab.io.openhabcloud/src/main/java/org/openhab/io/openhabcloud/internal/CloudClient.java
Labels: io: openhabcloud

#5621 [orvibo] fix embedded library
  bundles/org.openhab.binding.orvibo/.classpath
  bundles/org.openhab.binding.orvibo/lib/s20-sdk-0.0.6-SNAPSHOT.jar
  bundles/org.openhab.binding.orvibo/lib/s20-sdk-0.0.6-nmu1-src.zip
  bundles/org.openhab.binding.orvibo/lib/s20-sdk-0.0.6-nmu1.jar
  bundles/org.openhab.binding.orvibo/pom.xml
  bundles/org.openhab.binding.orvibo/src/main/feature/feature.xml
Labels: bug

#5626 [network] Adding speedtest
  bundles/org.openhab.binding.network/README.md
  bundles/org.openhab.binding.network/pom.xml
  bundles/org.openhab.binding.network/src/main/feature/feature.xml
  bundles/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/NetworkBindingConstants.java
  bundles/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/NetworkHandlerFactory.java
  bundles/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/SpeedTestConfiguration.java
  bundles/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/handler/SpeedTestHandler.java
  bundles/org.openhab.binding.network/src/main/resources/ESH-INF/thing/thing-types.xml
Labels: enhancement

#5640 Fix broken Markdown tables
  bundles/org.openhab.binding.lgwebos/README.md
  bundles/org.openhab.binding.neato/README.md
  bundles/org.openhab.binding.neeo/README.md
  bundles/org.openhab.binding.pentair/README.md
  bundles/org.openhab.binding.rotelra1x/README.md
  bundles/org.openhab.binding.volvooncall/README.md
  bundles/org.openhab.binding.wemo/README.md
Labels: documentation

#5642 [homekit] fix NPE on config change
  bundles/org.openhab.io.homekit/README.md
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitAccessoryRegistry.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitChangeListener.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitSettings.java
Labels: bug, io: homekit

#5627 [dsmr] Fix electricity channels in items example
  bundles/org.openhab.binding.dsmr/README.md
Labels: documentation

#5582 Inherit from openHAB Super POM
  pom.xml
Labels: infrastructure, rebuild

#5656 [mail] Added note about how to observe sub directories
  bundles/org.openhab.binding.mail/README.md
Labels: documentation

#5647 [homekit] NPE protection
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitAccessoryRegistry.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitAccessoryUpdater.java
Labels: io: homekit

#5649 [mail] Updated and fixed translations
  bundles/org.openhab.binding.mail/src/main/resources/ESH-INF/i18n/mail_de_DE.properties
Labels: translation

#5664 [mqtt] ChannelStateTests.java
  bundles/org.openhab.binding.mqtt.generic/src/test/java/org/openhab/binding/mqtt/generic/ChannelStateTests.java
Labels: binding: mqtt

#5660 Use bnd for including resources to workaround infinite Eclipse builds
  pom.xml
Labels: bug, infrastructure
