Repository openhab/openhab-addons, pull requests merged in 2019-03, with the labels that each got.

#4783 [nanoleaf] Nanoleaf Binding initial contribution
  addons/binding/org.openhab.binding.nanoleaf/.classpath
  addons/binding/org.openhab.binding.nanoleaf/.project
  addons/binding/org.openhab.binding.nanoleaf/ESH-INF/binding/binding.xml
  addons/binding/org.openhab.binding.nanoleaf/ESH-INF/config/config.xml
  addons/binding/org.openhab.binding.nanoleaf/ESH-INF/i18n/nanoleaf.properties
  addons/binding/org.openhab.binding.nanoleaf/ESH-INF/i18n/nanoleaf_de.properties
  addons/binding/org.openhab.binding.nanoleaf/ESH-INF/thing/lightpanels.xml
  addons/binding/org.openhab.binding.nanoleaf/META-INF/MANIFEST.MF
  addons/binding/org.openhab.binding.nanoleaf/NOTICE
  addons/binding/org.openhab.binding.nanoleaf/OSGI-INF/.gitignore
  addons/binding/org.openhab.binding.nanoleaf/README.md
  addons/binding/org.openhab.binding.nanoleaf/build.properties
  addons/binding/org.openhab.binding.nanoleaf/doc/LightPanels2.jpg
  addons/binding/org.openhab.binding.nanoleaf/doc/Nanoleaf.jpg
  addons/binding/org.openhab.binding.nanoleaf/pom.xml
  addons/binding/org.openhab.binding.nanoleaf/src/main/java/org/openhab/binding/nanoleaf/internal/NanoleafBindingConstants.java
  addons/binding/org.openhab.binding.nanoleaf/src/main/java/org/openhab/binding/nanoleaf/internal/NanoleafControllerListener.java
  addons/binding/org.openhab.binding.nanoleaf/src/main/java/org/openhab/binding/nanoleaf/internal/NanoleafException.java
  addons/binding/org.openhab.binding.nanoleaf/src/main/java/org/openhab/binding/nanoleaf/internal/NanoleafHandlerFactory.java
  addons/binding/org.openhab.binding.nanoleaf/src/main/java/org/openhab/binding/nanoleaf/internal/NanoleafUnauthorizedException.java
  addons/binding/org.openhab.binding.nanoleaf/src/main/java/org/openhab/binding/nanoleaf/internal/OpenAPIUtils.java
  addons/binding/org.openhab.binding.nanoleaf/src/main/java/org/openhab/binding/nanoleaf/internal/config/NanoleafControllerConfig.java
  addons/binding/org.openhab.binding.nanoleaf/src/main/java/org/openhab/binding/nanoleaf/internal/config/NanoleafPanelConfig.java
  addons/binding/org.openhab.binding.nanoleaf/src/main/java/org/openhab/binding/nanoleaf/internal/discovery/NanoleafMDNSDiscoveryParticipant.java
  addons/binding/org.openhab.binding.nanoleaf/src/main/java/org/openhab/binding/nanoleaf/internal/discovery/NanoleafPanelsDiscoveryService.java
  addons/binding/org.openhab.binding.nanoleaf/src/main/java/org/openhab/binding/nanoleaf/internal/handler/NanoleafControllerHandler.java
  addons/binding/org.openhab.binding.nanoleaf/src/main/java/org/openhab/binding/nanoleaf/internal/handler/NanoleafPanelHandler.java
  addons/binding/org.openhab.binding.nanoleaf/src/main/java/org/openhab/binding/nanoleaf/internal/model/AuthToken.java
  addons/binding/org.openhab.binding.nanoleaf/src/main/java/org/openhab/binding/nanoleaf/internal/model/BooleanState.java
  addons/binding/org.openhab.binding.nanoleaf/src/main/java/org/openhab/binding/nanoleaf/internal/model/Brightness.java
  addons/binding/org.openhab.binding.nanoleaf/src/main/java/org/openhab/binding/nanoleaf/internal/model/Command.java
  addons/binding/org.openhab.binding.nanoleaf/src/main/java/org/openhab/binding/nanoleaf/internal/model/ControllerInfo.java
  addons/binding/org.openhab.binding.nanoleaf/src/main/java/org/openhab/binding/nanoleaf/internal/model/Ct.java
  addons/binding/org.openhab.binding.nanoleaf/src/main/java/org/openhab/binding/nanoleaf/internal/model/Effects.java
  addons/binding/org.openhab.binding.nanoleaf/src/main/java/org/openhab/binding/nanoleaf/internal/model/GlobalOrientation.java
  addons/binding/org.openhab.binding.nanoleaf/src/main/java/org/openhab/binding/nanoleaf/internal/model/Hue.java
  addons/binding/org.openhab.binding.nanoleaf/src/main/java/org/openhab/binding/nanoleaf/internal/model/IntegerState.java
  addons/binding/org.openhab.binding.nanoleaf/src/main/java/org/openhab/binding/nanoleaf/internal/model/Layout.java
  addons/binding/org.openhab.binding.nanoleaf/src/main/java/org/openhab/binding/nanoleaf/internal/model/On.java
  addons/binding/org.openhab.binding.nanoleaf/src/main/java/org/openhab/binding/nanoleaf/internal/model/Palette.java
  addons/binding/org.openhab.binding.nanoleaf/src/main/java/org/openhab/binding/nanoleaf/internal/model/PanelLayout.java
  addons/binding/org.openhab.binding.nanoleaf/src/main/java/org/openhab/binding/nanoleaf/internal/model/PositionDatum.java
  addons/binding/org.openhab.binding.nanoleaf/src/main/java/org/openhab/binding/nanoleaf/internal/model/Rhythm.java
  addons/binding/org.openhab.binding.nanoleaf/src/main/java/org/openhab/binding/nanoleaf/internal/model/RhythmPos.java
  addons/binding/org.openhab.binding.nanoleaf/src/main/java/org/openhab/binding/nanoleaf/internal/model/Sat.java
  addons/binding/org.openhab.binding.nanoleaf/src/main/java/org/openhab/binding/nanoleaf/internal/model/State.java
  addons/binding/org.openhab.binding.nanoleaf/src/main/java/org/openhab/binding/nanoleaf/internal/model/Write.java
  addons/binding/pom.xml
  features/openhab-addons/src/main/feature/feature.xml
Labels: new binding

#5029 [onkyo] Add support for Onkyo TX-NR545
  addons/binding/org.openhab.binding.onkyo/ESH-INF/thing/tx-nr545.xml
  addons/binding/org.openhab.binding.onkyo/README.md
  addons/binding/org.openhab.binding.onkyo/src/main/java/org/openhab/binding/onkyo/internal/OnkyoBindingConstants.java
Labels: enhancement

#5033 [tradfri] Fixed rounding, cast result to 'int'
  addons/binding/org.openhab.binding.tradfri/src/main/java/org/openhab/binding/tradfri/internal/model/TradfriLightData.java
Labels: bug

#3222 [pollytts] Polly Text-to-Speech initial contribution
  CODEOWNERS
  addons/voice/org.openhab.voice.pollytts/.classpath
  addons/voice/org.openhab.voice.pollytts/.project
  addons/voice/org.openhab.voice.pollytts/ESH-INF/config/config.xml
  addons/voice/org.openhab.voice.pollytts/META-INF/MANIFEST.MF
  addons/voice/org.openhab.voice.pollytts/NOTICE
  addons/voice/org.openhab.voice.pollytts/OSGI-INF/.gitignore
  addons/voice/org.openhab.voice.pollytts/README.md
  addons/voice/org.openhab.voice.pollytts/build.properties
  addons/voice/org.openhab.voice.pollytts/lib/aws-java-sdk-core-1.11.490.jar
  addons/voice/org.openhab.voice.pollytts/lib/aws-java-sdk-polly-1.11.490.jar
  addons/voice/org.openhab.voice.pollytts/lib/commons-logging-1.1.3.jar
  addons/voice/org.openhab.voice.pollytts/lib/httpclient-4.5.5.jar
  addons/voice/org.openhab.voice.pollytts/lib/httpcore-4.4.9.jar
  addons/voice/org.openhab.voice.pollytts/lib/jackson-annotations-2.6.0.jar
  addons/voice/org.openhab.voice.pollytts/lib/jackson-core-2.6.7.jar
  addons/voice/org.openhab.voice.pollytts/lib/jackson-databind-2.6.7.2.jar
  addons/voice/org.openhab.voice.pollytts/lib/joda-time-2.8.1.jar
  addons/voice/org.openhab.voice.pollytts/pom.xml
  addons/voice/org.openhab.voice.pollytts/src/main/java/org/openhab/voice/pollytts/internal/PollyTTSAudioStream.java
  addons/voice/org.openhab.voice.pollytts/src/main/java/org/openhab/voice/pollytts/internal/PollyTTSService.java
  addons/voice/org.openhab.voice.pollytts/src/main/java/org/openhab/voice/pollytts/internal/PollyTTSVoice.java
  addons/voice/org.openhab.voice.pollytts/src/main/java/org/openhab/voice/pollytts/internal/cloudapi/CachedPollyTTSCloudImpl.java
  addons/voice/org.openhab.voice.pollytts/src/main/java/org/openhab/voice/pollytts/internal/cloudapi/PollyTTSCloudImpl.java
  addons/voice/org.openhab.voice.pollytts/src/main/java/org/openhab/voice/pollytts/internal/cloudapi/PollyTTSConfig.java
  addons/voice/pom.xml
  features/openhab-addons/src/main/feature/feature.xml
Labels: new voice

#5034 [modbus] Improve migration documentation
  addons/binding/org.openhab.binding.modbus/README.md
Labels: documentation

#5038 [mqtt] Update README.md
  addons/binding/org.openhab.binding.mqtt.generic/README.md
Labels: documentation, mqtt

#5022 [jinja] Readme: Use VuePress escaping in example
  addons/transform/org.openhab.transform.jinja/README.md
Labels: documentation

#4845 [unifi] Added feature to be able to block and unblock clients
  addons/binding/org.openhab.binding.unifi/ESH-INF/thing/thing-types.xml
  addons/binding/org.openhab.binding.unifi/README.md
  addons/binding/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/UniFiBindingConstants.java
  addons/binding/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/UniFiClientThingConfig.java
  addons/binding/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/UniFiControllerThingConfig.java
  addons/binding/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/UniFiThingHandlerFactory.java
  addons/binding/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/api/UniFiController.java
  addons/binding/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/api/UniFiNotAuthorizedException.java
  addons/binding/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/api/cache/UniFiCache.java
  addons/binding/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/api/cache/UniFiClientCache.java
  addons/binding/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/api/cache/UniFiDeviceCache.java
  addons/binding/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/api/cache/UniFiSiteCache.java
  addons/binding/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/api/model/UniFiClient.java
  addons/binding/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/api/model/UniFiController.java
  addons/binding/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/api/model/UniFiControllerRequest.java
  addons/binding/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/api/model/UniFiDevice.java
  addons/binding/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/api/model/UniFiSite.java
  addons/binding/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/api/model/UniFiUnknownClient.java
  addons/binding/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/api/model/UniFiWiredClient.java
  addons/binding/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/api/model/UniFiWirelessClient.java
  addons/binding/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/api/util/UniFiClientInstanceCreator.java
  addons/binding/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/api/util/UniFiDeviceInstanceCreator.java
  addons/binding/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/api/util/UniFiSiteInstanceCreator.java
  addons/binding/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/handler/UniFiBaseThingHandler.java
  addons/binding/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/handler/UniFiClientThingHandler.java
  addons/binding/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/handler/UniFiControllerThingHandler.java
Labels: cre, enhancement

#4946 [chromecast] Manual Thing Configuration, Port of chromecast audio group is necessary
  addons/binding/org.openhab.binding.chromecast/README.md
Labels: documentation

#5068 [systeminfo] Add Item labels and icons to Readme
  addons/binding/org.openhab.binding.systeminfo/README.md
Labels: documentation

#5043 [gpstracker] Update the README.md
  addons/binding/org.openhab.binding.gpstracker/README.md
  addons/binding/org.openhab.binding.gpstracker/doc/gpslogger_1.png
  addons/binding/org.openhab.binding.gpstracker/doc/gpslogger_2.png
  addons/binding/org.openhab.binding.gpstracker/doc/gpslogger_3.png
  addons/binding/org.openhab.binding.gpstracker/doc/owntracks_setup.png
Labels: documentation

#4882 [zway] Update README.md
  addons/binding/org.openhab.binding.zway/README.md
Labels: documentation

#4913 [bluetooth.ruuvitag] New binding for Ruuvi Tag Bluetooth Environmental Sensor
  CODEOWNERS
  addons/binding/org.openhab.binding.bluetooth.ruuvitag/.classpath
  addons/binding/org.openhab.binding.bluetooth.ruuvitag/.project
  addons/binding/org.openhab.binding.bluetooth.ruuvitag/ESH-INF/thing/ruuvitag.xml
  addons/binding/org.openhab.binding.bluetooth.ruuvitag/META-INF/MANIFEST.MF
  addons/binding/org.openhab.binding.bluetooth.ruuvitag/NOTICE
  addons/binding/org.openhab.binding.bluetooth.ruuvitag/OSGI-INF/.gitignore
  addons/binding/org.openhab.binding.bluetooth.ruuvitag/README.md
  addons/binding/org.openhab.binding.bluetooth.ruuvitag/build.properties
  addons/binding/org.openhab.binding.bluetooth.ruuvitag/lib/ruuvitag-common-1.0.0.jar
  addons/binding/org.openhab.binding.bluetooth.ruuvitag/pom.xml
  addons/binding/org.openhab.binding.bluetooth.ruuvitag/src/main/java/org/openhab/binding/bluetooth/ruuvitag/RuuviTagBindingConstants.java
  addons/binding/org.openhab.binding.bluetooth.ruuvitag/src/main/java/org/openhab/binding/bluetooth/ruuvitag/handler/RuuviTagHandler.java
  addons/binding/org.openhab.binding.bluetooth.ruuvitag/src/main/java/org/openhab/binding/bluetooth/ruuvitag/internal/RuuviTagDiscoveryParticipant.java
  addons/binding/org.openhab.binding.bluetooth.ruuvitag/src/main/java/org/openhab/binding/bluetooth/ruuvitag/internal/RuuviTagHandlerFactory.java
  addons/binding/pom.xml
  features/karaf/openhab-addons/src/main/feature/feature.xml
Labels: new binding

#4506 [dwdunwetter] DWD Unwetter Binding initial contribution
  CODEOWNERS
  addons/binding/org.openhab.binding.dwdunwetter.test/.classpath
  addons/binding/org.openhab.binding.dwdunwetter.test/.project
  addons/binding/org.openhab.binding.dwdunwetter.test/META-INF/MANIFEST.MF
  addons/binding/org.openhab.binding.dwdunwetter.test/NOTICE
  addons/binding/org.openhab.binding.dwdunwetter.test/build.properties
  addons/binding/org.openhab.binding.dwdunwetter.test/org.openhab.binding.dwdunwetter.test.launch
  addons/binding/org.openhab.binding.dwdunwetter.test/pom.xml
  addons/binding/org.openhab.binding.dwdunwetter.test/src/test/java/org/openhab/binding/dwdunwetter/DwdUnwetterHandlerTest.java
  addons/binding/org.openhab.binding.dwdunwetter.test/src/test/java/org/openhab/binding/dwdunwetter/internal/data/DwdWarningCacheTest.java
  addons/binding/org.openhab.binding.dwdunwetter.test/src/test/java/org/openhab/binding/dwdunwetter/internal/data/DwdWarningsDataTest.java
  addons/binding/org.openhab.binding.dwdunwetter.test/src/test/resources/org/openhab/binding/dwdunwetter/internal/data/warnings.xml
  addons/binding/org.openhab.binding.dwdunwetter/.classpath
  addons/binding/org.openhab.binding.dwdunwetter/.project
  addons/binding/org.openhab.binding.dwdunwetter/ESH-INF/binding/binding.xml
  addons/binding/org.openhab.binding.dwdunwetter/ESH-INF/i18n/dwdunwetter_de.properties
  addons/binding/org.openhab.binding.dwdunwetter/ESH-INF/thing/thing-types.xml
  addons/binding/org.openhab.binding.dwdunwetter/META-INF/MANIFEST.MF
  addons/binding/org.openhab.binding.dwdunwetter/NOTICE
  addons/binding/org.openhab.binding.dwdunwetter/OSGI-INF/.gitignore
  addons/binding/org.openhab.binding.dwdunwetter/README.md
  addons/binding/org.openhab.binding.dwdunwetter/README_de.md
  addons/binding/org.openhab.binding.dwdunwetter/build.properties
  addons/binding/org.openhab.binding.dwdunwetter/pom.xml
  addons/binding/org.openhab.binding.dwdunwetter/src/main/java/org/openhab/binding/dwdunwetter/internal/DwdUnwetterBindingConstants.java
  addons/binding/org.openhab.binding.dwdunwetter/src/main/java/org/openhab/binding/dwdunwetter/internal/DwdUnwetterConfiguration.java
  addons/binding/org.openhab.binding.dwdunwetter/src/main/java/org/openhab/binding/dwdunwetter/internal/DwdUnwetterHandler.java
  addons/binding/org.openhab.binding.dwdunwetter/src/main/java/org/openhab/binding/dwdunwetter/internal/DwdUnwetterHandlerFactory.java
  addons/binding/org.openhab.binding.dwdunwetter/src/main/java/org/openhab/binding/dwdunwetter/internal/data/DwdWarningCache.java
  addons/binding/org.openhab.binding.dwdunwetter/src/main/java/org/openhab/binding/dwdunwetter/internal/data/DwdWarningData.java
  addons/binding/org.openhab.binding.dwdunwetter/src/main/java/org/openhab/binding/dwdunwetter/internal/data/DwdWarningDataAccess.java
  addons/binding/org.openhab.binding.dwdunwetter/src/main/java/org/openhab/binding/dwdunwetter/internal/data/DwdWarningsData.java
  addons/binding/org.openhab.binding.dwdunwetter/src/main/java/org/openhab/binding/dwdunwetter/internal/data/DwdXmlTag.java
  addons/binding/org.openhab.binding.dwdunwetter/src/main/java/org/openhab/binding/dwdunwetter/internal/data/Severity.java
  addons/binding/org.openhab.binding.dwdunwetter/src/main/java/org/openhab/binding/dwdunwetter/internal/data/SeverityComparator.java
  addons/binding/org.openhab.binding.dwdunwetter/src/main/java/org/openhab/binding/dwdunwetter/internal/data/Urgency.java
  addons/binding/pom.xml
  features/karaf/openhab-addons/src/main/feature/feature.xml
Labels: cre, new binding

#5080 Travis configuration improvements
  .travis.yml
Labels: infrastructure

#5040 [yeelight] Added command channel
  addons/binding/org.openhab.binding.yeelight/ESH-INF/thing/ceiling.xml
  addons/binding/org.openhab.binding.yeelight/ESH-INF/thing/channels.xml
  addons/binding/org.openhab.binding.yeelight/ESH-INF/thing/ct_bulb.xml
  addons/binding/org.openhab.binding.yeelight/ESH-INF/thing/desklamp.xml
  addons/binding/org.openhab.binding.yeelight/ESH-INF/thing/dolphin.xml
  addons/binding/org.openhab.binding.yeelight/ESH-INF/thing/stripe.xml
  addons/binding/org.openhab.binding.yeelight/ESH-INF/thing/wonder.xml
  addons/binding/org.openhab.binding.yeelight/README.md
  addons/binding/org.openhab.binding.yeelight/src/main/java/org/openhab/binding/yeelight/internal/YeelightBindingConstants.java
  addons/binding/org.openhab.binding.yeelight/src/main/java/org/openhab/binding/yeelight/internal/handler/YeelightHandlerBase.java
  addons/binding/org.openhab.binding.yeelight/src/main/java/org/openhab/binding/yeelight/internal/lib/device/DeviceBase.java
  addons/binding/org.openhab.binding.yeelight/src/main/java/org/openhab/binding/yeelight/internal/lib/device/DeviceMethod.java
  addons/binding/org.openhab.binding.yeelight/src/main/java/org/openhab/binding/yeelight/internal/lib/device/connection/ConnectionBase.java
  addons/binding/org.openhab.binding.yeelight/src/main/java/org/openhab/binding/yeelight/internal/lib/device/connection/WifiConnection.java
  addons/binding/org.openhab.binding.yeelight/src/main/java/org/openhab/binding/yeelight/internal/lib/services/DeviceManager.java
Labels: enhancement

#5070 [openweathermap] Consider "1h" property for precipitation
  addons/binding/org.openhab.binding.openweathermap/ESH-INF/i18n/openweathermap_de.properties
  addons/binding/org.openhab.binding.openweathermap/ESH-INF/i18n/openweathermap_fr.properties
  addons/binding/org.openhab.binding.openweathermap/ESH-INF/thing/channel-types.xml
  addons/binding/org.openhab.binding.openweathermap/README.md
  addons/binding/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/connection/OpenWeatherMapConnection.java
  addons/binding/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/handler/OpenWeatherMapWeatherAndForecastHandler.java
  addons/binding/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/model/base/Rain.java
  addons/binding/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/model/base/Snow.java
Labels: enhancement

#5085 add addons bom
  bom/openhab-addons/.project
  bom/openhab-addons/.settings/org.eclipse.core.resources.prefs
  bom/openhab-addons/.settings/org.eclipse.m2e.core.prefs
  bom/openhab-addons/pom.xml
  bom/pom.xml
Labels: infrastructure

#4632 [kostalinverter] Add support for 3rd generation: PIKO IQ & PLENTICORE plus
  addons/binding/org.openhab.binding.kostalinverter/ESH-INF/config/ThirdGeneration.xml
  addons/binding/org.openhab.binding.kostalinverter/ESH-INF/thing/Channels.xml
  addons/binding/org.openhab.binding.kostalinverter/ESH-INF/thing/PIKOIQ100.xml
  addons/binding/org.openhab.binding.kostalinverter/ESH-INF/thing/PIKOIQ42.xml
  addons/binding/org.openhab.binding.kostalinverter/ESH-INF/thing/PIKOIQ55.xml
  addons/binding/org.openhab.binding.kostalinverter/ESH-INF/thing/PIKOIQ70.xml
  addons/binding/org.openhab.binding.kostalinverter/ESH-INF/thing/PIKOIQ85.xml
  addons/binding/org.openhab.binding.kostalinverter/ESH-INF/thing/PLENTICOREPLUS100WITHBATTERY.xml
  addons/binding/org.openhab.binding.kostalinverter/ESH-INF/thing/PLENTICOREPLUS100WITHOUTBATTERY.xml
  addons/binding/org.openhab.binding.kostalinverter/ESH-INF/thing/PLENTICOREPLUS42WITHBATTERY.xml
  addons/binding/org.openhab.binding.kostalinverter/ESH-INF/thing/PLENTICOREPLUS42WITHOUTBATTERY.xml
  addons/binding/org.openhab.binding.kostalinverter/ESH-INF/thing/PLENTICOREPLUS55WITHBATTERY.xml
  addons/binding/org.openhab.binding.kostalinverter/ESH-INF/thing/PLENTICOREPLUS55WITHOUTBATTERY.xml
  addons/binding/org.openhab.binding.kostalinverter/ESH-INF/thing/PLENTICOREPLUS70WITHBATTERY.xml
  addons/binding/org.openhab.binding.kostalinverter/ESH-INF/thing/PLENTICOREPLUS70WITHOUTBATTERY.xml
  addons/binding/org.openhab.binding.kostalinverter/ESH-INF/thing/PLENTICOREPLUS85WITHBATTERY.xml
  addons/binding/org.openhab.binding.kostalinverter/ESH-INF/thing/PLENTICOREPLUS85WITHOUTBATTERY.xml
  addons/binding/org.openhab.binding.kostalinverter/ESH-INF/thing/thing-types.xml
  addons/binding/org.openhab.binding.kostalinverter/META-INF/MANIFEST.MF
  addons/binding/org.openhab.binding.kostalinverter/README.md
  addons/binding/org.openhab.binding.kostalinverter/src/main/java/org/openhab/binding/internal/kostal/inverter/KostalInverterFactory.java
  addons/binding/org.openhab.binding.kostalinverter/src/main/java/org/openhab/binding/internal/kostal/inverter/WebscrapeHandlerFactory.java
  addons/binding/org.openhab.binding.kostalinverter/src/main/java/org/openhab/binding/internal/kostal/inverter/firstgeneration/ChannelConfig.java
  addons/binding/org.openhab.binding.kostalinverter/src/main/java/org/openhab/binding/internal/kostal/inverter/firstgeneration/SourceConfig.java
  addons/binding/org.openhab.binding.kostalinverter/src/main/java/org/openhab/binding/internal/kostal/inverter/firstgeneration/WebscrapeHandler.java
  addons/binding/org.openhab.binding.kostalinverter/src/main/java/org/openhab/binding/internal/kostal/inverter/thirdgeneration/ThirdGenerationBindingConstants.java
  addons/binding/org.openhab.binding.kostalinverter/src/main/java/org/openhab/binding/internal/kostal/inverter/thirdgeneration/ThirdGenerationChannelDatatypes.java
  addons/binding/org.openhab.binding.kostalinverter/src/main/java/org/openhab/binding/internal/kostal/inverter/thirdgeneration/ThirdGenerationChannelMappingToWebApi.java
  addons/binding/org.openhab.binding.kostalinverter/src/main/java/org/openhab/binding/internal/kostal/inverter/thirdgeneration/ThirdGenerationConfiguration.java
  addons/binding/org.openhab.binding.kostalinverter/src/main/java/org/openhab/binding/internal/kostal/inverter/thirdgeneration/ThirdGenerationEncryptionHelper.java
  addons/binding/org.openhab.binding.kostalinverter/src/main/java/org/openhab/binding/internal/kostal/inverter/thirdgeneration/ThirdGenerationHandler.java
  addons/binding/org.openhab.binding.kostalinverter/src/main/java/org/openhab/binding/internal/kostal/inverter/thirdgeneration/ThirdGenerationHttpHelper.java
  addons/binding/org.openhab.binding.kostalinverter/src/main/java/org/openhab/binding/internal/kostal/inverter/thirdgeneration/ThirdGenerationInverterTypes.java
  addons/binding/org.openhab.binding.kostalinverter/src/main/java/org/openhab/binding/internal/kostal/inverter/thirdgeneration/ThirdGenerationMappingInverterToChannel.java
Labels: cre, enhancement

#5088 [homekit] Add links to HomeKit Add-on integration guide
  addons/io/org.openhab.io.homekit/README.md
Labels: documentation

#4980 [homematic] Update README.md
  addons/binding/org.openhab.binding.homematic/README.md
Labels: documentation, homematic

#5094 [openweathermap] Moved binding to new build system
  CODEOWNERS
  addons/binding/org.openhab.binding.openweathermap/.classpath
  addons/binding/org.openhab.binding.openweathermap/META-INF/MANIFEST.MF
  addons/binding/org.openhab.binding.openweathermap/OSGI-INF/.gitignore
  addons/binding/org.openhab.binding.openweathermap/build.properties
  addons/binding/org.openhab.binding.openweathermap/pom.xml
  addons/binding/pom.xml
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.openweathermap/.classpath
  bundles/org.openhab.binding.openweathermap/.project
  bundles/org.openhab.binding.openweathermap/.settings/org.eclipse.core.resources.prefs
  bundles/org.openhab.binding.openweathermap/.settings/org.eclipse.m2e.core.prefs
  bundles/org.openhab.binding.openweathermap/NOTICE
  bundles/org.openhab.binding.openweathermap/README.md
  bundles/org.openhab.binding.openweathermap/pom.xml
  bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/OpenWeatherMapBindingConstants.java
  bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/config/OpenWeatherMapAPIConfiguration.java
  bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/config/OpenWeatherMapLocationConfiguration.java
  bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/config/OpenWeatherMapUVIndexConfiguration.java
  bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/config/OpenWeatherMapWeatherAndForecastConfiguration.java
  bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/connection/OpenWeatherMapCommunicationException.java
  bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/connection/OpenWeatherMapConfigurationException.java
  bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/connection/OpenWeatherMapConnection.java
  bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/discovery/OpenWeatherMapDiscoveryService.java
  bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/factory/OpenWeatherMapHandlerFactory.java
  bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/handler/AbstractOpenWeatherMapHandler.java
  bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/handler/OpenWeatherMapAPIHandler.java
  bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/handler/OpenWeatherMapUVIndexHandler.java
  bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/handler/OpenWeatherMapWeatherAndForecastHandler.java
  bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/model/OpenWeatherMapJsonDailyForecastData.java
  bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/model/OpenWeatherMapJsonHourlyForecastData.java
  bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/model/OpenWeatherMapJsonUVIndexData.java
  bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/model/OpenWeatherMapJsonWeatherData.java
  bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/model/base/City.java
  bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/model/base/Clouds.java
  bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/model/base/Coord.java
  bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/model/base/Rain.java
  bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/model/base/Snow.java
  bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/model/base/Weather.java
  bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/model/base/Wind.java
  bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/model/forecast/daily/List.java
  bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/model/forecast/daily/Temp.java
  bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/model/forecast/hourly/List.java
  bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/model/forecast/hourly/Main.java
  bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/model/forecast/hourly/Sys.java
  bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/model/weather/Main.java
  bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/model/weather/Sys.java
  bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/utils/ByteArrayFileCache.java
  bundles/org.openhab.binding.openweathermap/src/main/resources/ESH-INF/binding/binding.xml
  bundles/org.openhab.binding.openweathermap/src/main/resources/ESH-INF/config/config.xml
  bundles/org.openhab.binding.openweathermap/src/main/resources/ESH-INF/i18n/openweathermap.properties
  bundles/org.openhab.binding.openweathermap/src/main/resources/ESH-INF/i18n/openweathermap_de.properties
  bundles/org.openhab.binding.openweathermap/src/main/resources/ESH-INF/i18n/openweathermap_fr.properties
  bundles/org.openhab.binding.openweathermap/src/main/resources/ESH-INF/thing/bridge-types.xml
  bundles/org.openhab.binding.openweathermap/src/main/resources/ESH-INF/thing/channel-types.xml
  bundles/org.openhab.binding.openweathermap/src/main/resources/ESH-INF/thing/thing-types.xml
  bundles/pom.xml
  features/karaf/openhab-addons/src/main/feature/feature.xml
Labels: infrastructure

#3044 [daikin] Daikin Binding initial contribution
  CODEOWNERS
  addons/binding/org.openhab.binding.daikin/.classpath
  addons/binding/org.openhab.binding.daikin/.project
  addons/binding/org.openhab.binding.daikin/ESH-INF/binding/binding.xml
  addons/binding/org.openhab.binding.daikin/ESH-INF/thing/thing-types.xml
  addons/binding/org.openhab.binding.daikin/META-INF/MANIFEST.MF
  addons/binding/org.openhab.binding.daikin/NOTICE
  addons/binding/org.openhab.binding.daikin/OSGI-INF/.gitignore
  addons/binding/org.openhab.binding.daikin/README.md
  addons/binding/org.openhab.binding.daikin/build.properties
  addons/binding/org.openhab.binding.daikin/pom.xml
  addons/binding/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/DaikinBindingConstants.java
  addons/binding/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/DaikinCommunicationException.java
  addons/binding/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/DaikinHandlerFactory.java
  addons/binding/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/DaikinWebTargets.java
  addons/binding/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/api/ControlInfo.java
  addons/binding/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/api/Enums.java
  addons/binding/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/api/SensorInfo.java
  addons/binding/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/config/DaikinConfiguration.java
  addons/binding/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/discovery/DaikinACUnitDiscoveryService.java
  addons/binding/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/handler/DaikinAcUnitHandler.java
  addons/binding/pom.xml
  features/karaf/openhab-addons/src/main/feature/feature.xml
Labels: cre, new binding

#5065 [mqtt] Add support for abbreviations and '~' expansion in home assistant auto discovery
  addons/binding/org.openhab.binding.mqtt.generic.test/src/test/java/org/openhab/binding/mqtt/generic/HomeAssistantMQTTImplementationTests.java
  addons/binding/org.openhab.binding.mqtt.generic.test/src/test/java/org/openhab/binding/mqtt/generic/internal/convention/homeassistant/DiscoverComponentsTests.java
  addons/binding/org.openhab.binding.mqtt.generic.test/src/test/java/org/openhab/binding/mqtt/generic/internal/convention/homeassistant/HAConfigurationTests.java
  addons/binding/org.openhab.binding.mqtt.generic/META-INF/MANIFEST.MF
  addons/binding/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/internal/convention/homeassistant/AbstractComponent.java
  addons/binding/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/internal/convention/homeassistant/BaseChannelConfiguration.java
  addons/binding/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/internal/convention/homeassistant/CChannel.java
  addons/binding/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/internal/convention/homeassistant/CFactory.java
  addons/binding/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/internal/convention/homeassistant/ChannelConfigurationTypeAdapterFactory.java
  addons/binding/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/internal/convention/homeassistant/ComponentAlarmControlPanel.java
  addons/binding/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/internal/convention/homeassistant/ComponentBinarySensor.java
  addons/binding/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/internal/convention/homeassistant/ComponentCamera.java
  addons/binding/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/internal/convention/homeassistant/ComponentClimate.java
  addons/binding/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/internal/convention/homeassistant/ComponentCover.java
  addons/binding/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/internal/convention/homeassistant/ComponentFan.java
  addons/binding/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/internal/convention/homeassistant/ComponentLight.java
  addons/binding/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/internal/convention/homeassistant/ComponentLock.java
  addons/binding/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/internal/convention/homeassistant/ComponentSensor.java
  addons/binding/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/internal/convention/homeassistant/ComponentSwitch.java
  addons/binding/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/internal/convention/homeassistant/MappingJsonReader.java
  addons/binding/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/internal/discovery/HomeAssistantDiscovery.java
  addons/binding/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/internal/handler/HomeAssistantThingHandler.java
  addons/binding/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/internal/tools/JsonReaderDelegate.java
Labels: mqtt

#5106 [KOSTALINVERTER] Add product image for 3. generation
  addons/binding/org.openhab.binding.kostalinverter/README.md
  addons/binding/org.openhab.binding.kostalinverter/doc/plenticore.jpg
Labels: documentation

#5064 [mqtt] issue 5027: the smaller version
  addons/binding/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/internal/convention/homeassistant/ComponentSwitch.java
  addons/binding/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/internal/values/OnOffValue.java
Labels: mqtt

#5113 migrate sonos binding
  CODEOWNERS
  addons/binding/org.openhab.binding.sonos/.classpath
  addons/binding/org.openhab.binding.sonos/META-INF/MANIFEST.MF
  addons/binding/org.openhab.binding.sonos/OSGI-INF/.gitignore
  addons/binding/org.openhab.binding.sonos/build.properties
  addons/binding/pom.xml
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.sonos/.classpath
  bundles/org.openhab.binding.sonos/.project
  bundles/org.openhab.binding.sonos/.settings/org.eclipse.core.resources.prefs
  bundles/org.openhab.binding.sonos/.settings/org.eclipse.m2e.core.prefs
  bundles/org.openhab.binding.sonos/NOTICE
  bundles/org.openhab.binding.sonos/README.md
  bundles/org.openhab.binding.sonos/pom.xml
  bundles/org.openhab.binding.sonos/src/main/java/org/openhab/binding/sonos/internal/SonosAlarm.java
  bundles/org.openhab.binding.sonos/src/main/java/org/openhab/binding/sonos/internal/SonosAudioSink.java
  bundles/org.openhab.binding.sonos/src/main/java/org/openhab/binding/sonos/internal/SonosBindingConstants.java
  bundles/org.openhab.binding.sonos/src/main/java/org/openhab/binding/sonos/internal/SonosEntry.java
  bundles/org.openhab.binding.sonos/src/main/java/org/openhab/binding/sonos/internal/SonosHandlerFactory.java
  bundles/org.openhab.binding.sonos/src/main/java/org/openhab/binding/sonos/internal/SonosMetaData.java
  bundles/org.openhab.binding.sonos/src/main/java/org/openhab/binding/sonos/internal/SonosMusicService.java
  bundles/org.openhab.binding.sonos/src/main/java/org/openhab/binding/sonos/internal/SonosResourceMetaData.java
  bundles/org.openhab.binding.sonos/src/main/java/org/openhab/binding/sonos/internal/SonosStateDescriptionOptionProvider.java
  bundles/org.openhab.binding.sonos/src/main/java/org/openhab/binding/sonos/internal/SonosXMLParser.java
  bundles/org.openhab.binding.sonos/src/main/java/org/openhab/binding/sonos/internal/SonosZoneGroup.java
  bundles/org.openhab.binding.sonos/src/main/java/org/openhab/binding/sonos/internal/SonosZonePlayerState.java
  bundles/org.openhab.binding.sonos/src/main/java/org/openhab/binding/sonos/internal/config/ZonePlayerConfiguration.java
  bundles/org.openhab.binding.sonos/src/main/java/org/openhab/binding/sonos/internal/discovery/ZonePlayerDiscoveryParticipant.java
  bundles/org.openhab.binding.sonos/src/main/java/org/openhab/binding/sonos/internal/handler/ZonePlayerHandler.java
  bundles/org.openhab.binding.sonos/src/main/resources/ESH-INF/binding/binding.xml
  bundles/org.openhab.binding.sonos/src/main/resources/ESH-INF/config/config.xml
  bundles/org.openhab.binding.sonos/src/main/resources/ESH-INF/i18n/sonos.properties
  bundles/org.openhab.binding.sonos/src/main/resources/ESH-INF/i18n/sonos_de.properties
  bundles/org.openhab.binding.sonos/src/main/resources/ESH-INF/i18n/sonos_fr.properties
  bundles/org.openhab.binding.sonos/src/main/resources/ESH-INF/thing/Beam.xml
  bundles/org.openhab.binding.sonos/src/main/resources/ESH-INF/thing/CONNECT.xml
  bundles/org.openhab.binding.sonos/src/main/resources/ESH-INF/thing/CONNECTAMP.xml
  bundles/org.openhab.binding.sonos/src/main/resources/ESH-INF/thing/One.xml
  bundles/org.openhab.binding.sonos/src/main/resources/ESH-INF/thing/PLAY1.xml
  bundles/org.openhab.binding.sonos/src/main/resources/ESH-INF/thing/PLAY3.xml
  bundles/org.openhab.binding.sonos/src/main/resources/ESH-INF/thing/PLAY5.xml
  bundles/org.openhab.binding.sonos/src/main/resources/ESH-INF/thing/PLAYBAR.xml
  bundles/org.openhab.binding.sonos/src/main/resources/ESH-INF/thing/PLAYBASE.xml
  bundles/org.openhab.binding.sonos/src/main/resources/ESH-INF/thing/ZonePlayer.xml
  bundles/org.openhab.binding.sonos/src/main/resources/ESH-INF/thing/channels.xml
  bundles/pom.xml
  features/karaf/openhab-addons/src/main/feature/feature.xml
Labels: infrastructure

#5115 [infrastructure] migrate airquality and airvisualnode to bnd
  CODEOWNERS
  addons/binding/org.openhab.binding.airquality/.classpath
  addons/binding/org.openhab.binding.airquality/META-INF/MANIFEST.MF
  addons/binding/org.openhab.binding.airquality/OSGI-INF/.gitignore
  addons/binding/org.openhab.binding.airquality/build.properties
  addons/binding/org.openhab.binding.airquality/pom.xml
  addons/binding/org.openhab.binding.airvisualnode/.classpath
  addons/binding/org.openhab.binding.airvisualnode/META-INF/MANIFEST.MF
  addons/binding/org.openhab.binding.airvisualnode/OSGI-INF/.gitignore
  addons/binding/org.openhab.binding.airvisualnode/build.properties
  addons/binding/org.openhab.binding.airvisualnode/lib/jcifs-1.3.18.jar
  addons/binding/org.openhab.binding.airvisualnode/pom.xml
  addons/binding/pom.xml
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.airquality/.classpath
  bundles/org.openhab.binding.airquality/.project
  bundles/org.openhab.binding.airquality/.settings/org.eclipse.core.resources.prefs
  bundles/org.openhab.binding.airquality/.settings/org.eclipse.m2e.core.prefs
  bundles/org.openhab.binding.airquality/NOTICE
  bundles/org.openhab.binding.airquality/README.md
  bundles/org.openhab.binding.airquality/pom.xml
  bundles/org.openhab.binding.airquality/src/main/java/org/openhab/binding/airquality/internal/AirQualityBindingConstants.java
  bundles/org.openhab.binding.airquality/src/main/java/org/openhab/binding/airquality/internal/AirQualityConfiguration.java
  bundles/org.openhab.binding.airquality/src/main/java/org/openhab/binding/airquality/internal/AirQualityHandlerFactory.java
  bundles/org.openhab.binding.airquality/src/main/java/org/openhab/binding/airquality/internal/discovery/AirQualityDiscoveryService.java
  bundles/org.openhab.binding.airquality/src/main/java/org/openhab/binding/airquality/internal/handler/AirQualityHandler.java
  bundles/org.openhab.binding.airquality/src/main/java/org/openhab/binding/airquality/internal/json/AirQualityJsonCity.java
  bundles/org.openhab.binding.airquality/src/main/java/org/openhab/binding/airquality/internal/json/AirQualityJsonData.java
  bundles/org.openhab.binding.airquality/src/main/java/org/openhab/binding/airquality/internal/json/AirQualityJsonIaqi.java
  bundles/org.openhab.binding.airquality/src/main/java/org/openhab/binding/airquality/internal/json/AirQualityJsonResponse.java
  bundles/org.openhab.binding.airquality/src/main/java/org/openhab/binding/airquality/internal/json/AirQualityJsonTime.java
  bundles/org.openhab.binding.airquality/src/main/java/org/openhab/binding/airquality/internal/json/AirQualityValue.java
  bundles/org.openhab.binding.airquality/src/main/java/org/openhab/binding/airquality/internal/json/Attribute.java
  bundles/org.openhab.binding.airquality/src/main/resources/ESH-INF/binding/binding.xml
  bundles/org.openhab.binding.airquality/src/main/resources/ESH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.airvisualnode/.classpath
  bundles/org.openhab.binding.airvisualnode/.project
  bundles/org.openhab.binding.airvisualnode/.settings/org.eclipse.core.resources.prefs
  bundles/org.openhab.binding.airvisualnode/.settings/org.eclipse.m2e.core.prefs
  bundles/org.openhab.binding.airvisualnode/NOTICE
  bundles/org.openhab.binding.airvisualnode/README.md
  bundles/org.openhab.binding.airvisualnode/pom.xml
  bundles/org.openhab.binding.airvisualnode/src/main/java/org/openhab/binding/airvisualnode/internal/AirVisualNodeBindingConstants.java
  bundles/org.openhab.binding.airvisualnode/src/main/java/org/openhab/binding/airvisualnode/internal/AirVisualNodeHandlerFactory.java
  bundles/org.openhab.binding.airvisualnode/src/main/java/org/openhab/binding/airvisualnode/internal/config/AirVisualNodeConfig.java
  bundles/org.openhab.binding.airvisualnode/src/main/java/org/openhab/binding/airvisualnode/internal/discovery/AirVisualNodeDiscoveryService.java
  bundles/org.openhab.binding.airvisualnode/src/main/java/org/openhab/binding/airvisualnode/internal/handler/AirVisualNodeHandler.java
  bundles/org.openhab.binding.airvisualnode/src/main/java/org/openhab/binding/airvisualnode/internal/json/DateAndTime.java
  bundles/org.openhab.binding.airvisualnode/src/main/java/org/openhab/binding/airvisualnode/internal/json/Measurements.java
  bundles/org.openhab.binding.airvisualnode/src/main/java/org/openhab/binding/airvisualnode/internal/json/NodeData.java
  bundles/org.openhab.binding.airvisualnode/src/main/java/org/openhab/binding/airvisualnode/internal/json/PowerSaving.java
  bundles/org.openhab.binding.airvisualnode/src/main/java/org/openhab/binding/airvisualnode/internal/json/PowerSavingTime.java
  bundles/org.openhab.binding.airvisualnode/src/main/java/org/openhab/binding/airvisualnode/internal/json/PowerSavingTimeSlot.java
  bundles/org.openhab.binding.airvisualnode/src/main/java/org/openhab/binding/airvisualnode/internal/json/Settings.java
  bundles/org.openhab.binding.airvisualnode/src/main/java/org/openhab/binding/airvisualnode/internal/json/Status.java
  bundles/org.openhab.binding.airvisualnode/src/main/resources/ESH-INF/binding/binding.xml
  bundles/org.openhab.binding.airvisualnode/src/main/resources/ESH-INF/thing/thing-types.xml
  bundles/pom.xml
  features/karaf/openhab-addons/src/main/feature/feature.xml
Labels: infrastructure

#5120 [infrastructure] Migrate bigassfan to bnd
  CODEOWNERS
  addons/binding/org.openhab.binding.bigassfan/.classpath
  addons/binding/org.openhab.binding.bigassfan/META-INF/MANIFEST.MF
  addons/binding/org.openhab.binding.bigassfan/OSGI-INF/.gitignore
  addons/binding/org.openhab.binding.bigassfan/build.properties
  addons/binding/org.openhab.binding.bigassfan/pom.xml
  addons/binding/pom.xml
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.bigassfan/.classpath
  bundles/org.openhab.binding.bigassfan/.project
  bundles/org.openhab.binding.bigassfan/.settings/org.eclipse.core.resources.prefs
  bundles/org.openhab.binding.bigassfan/.settings/org.eclipse.m2e.core.prefs
  bundles/org.openhab.binding.bigassfan/NOTICE
  bundles/org.openhab.binding.bigassfan/README.md
  bundles/org.openhab.binding.bigassfan/pom.xml
  bundles/org.openhab.binding.bigassfan/src/main/java/org/openhab/binding/bigassfan/internal/BigAssFanBindingConstants.java
  bundles/org.openhab.binding.bigassfan/src/main/java/org/openhab/binding/bigassfan/internal/BigAssFanConfig.java
  bundles/org.openhab.binding.bigassfan/src/main/java/org/openhab/binding/bigassfan/internal/BigAssFanHandlerFactory.java
  bundles/org.openhab.binding.bigassfan/src/main/java/org/openhab/binding/bigassfan/internal/discovery/BigAssFanDevice.java
  bundles/org.openhab.binding.bigassfan/src/main/java/org/openhab/binding/bigassfan/internal/discovery/BigAssFanDiscoveryService.java
  bundles/org.openhab.binding.bigassfan/src/main/java/org/openhab/binding/bigassfan/internal/discovery/DiscoveryListener.java
  bundles/org.openhab.binding.bigassfan/src/main/java/org/openhab/binding/bigassfan/internal/handler/BigAssFanHandler.java
  bundles/org.openhab.binding.bigassfan/src/main/java/org/openhab/binding/bigassfan/internal/utils/BigAssFanConverter.java
  bundles/org.openhab.binding.bigassfan/src/main/resources/ESH-INF/binding/binding.xml
  bundles/org.openhab.binding.bigassfan/src/main/resources/ESH-INF/config/config.xml
  bundles/org.openhab.binding.bigassfan/src/main/resources/ESH-INF/thing/thing-types.xml
  bundles/pom.xml
  features/karaf/openhab-addons/src/main/feature/feature.xml
Labels: infrastructure

#5116 [onkyo] Add support for Onkyo HT-RC560.
  addons/binding/org.openhab.binding.onkyo/ESH-INF/thing/ht-rc560.xml
  addons/binding/org.openhab.binding.onkyo/README.md
  addons/binding/org.openhab.binding.onkyo/src/main/java/org/openhab/binding/onkyo/internal/OnkyoBindingConstants.java
Labels: enhancement

#5079 [squeezebox] Add callback url and fix SAT issues
  addons/binding/org.openhab.binding.squeezebox/ESH-INF/binding/binding.xml
  addons/binding/org.openhab.binding.squeezebox/META-INF/MANIFEST.MF
  addons/binding/org.openhab.binding.squeezebox/README.md
  addons/binding/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/SqueezeBoxAudioSink.java
  addons/binding/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/SqueezeBoxHandlerFactory.java
  addons/binding/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/config/SqueezeBoxPlayerConfig.java
  addons/binding/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/config/SqueezeBoxServerConfig.java
  addons/binding/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/discovery/SqueezeBoxPlayerDiscoveryParticipant.java
  addons/binding/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/discovery/SqueezeBoxServerDiscoveryParticipant.java
  addons/binding/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/handler/SqueezeBoxNotificationListener.java
  addons/binding/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/handler/SqueezeBoxNotificationPlayer.java
  addons/binding/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/handler/SqueezeBoxPlayer.java
  addons/binding/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/handler/SqueezeBoxPlayerEventListener.java
  addons/binding/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/handler/SqueezeBoxPlayerPlayState.java
  addons/binding/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/handler/SqueezeBoxPlayerState.java
  addons/binding/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/handler/SqueezeBoxServerHandler.java
  addons/binding/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/utils/HttpUtils.java
  addons/binding/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/utils/SqueezeBoxTimeoutException.java
Labels: enhancement

#5130 [mqtt] Update the Readme part about sychronizing two intances
  addons/binding/org.openhab.binding.mqtt.generic/README.md
Labels: binding: mqtt, documentation

#5075 [valloxmv] Added channels re. filter change date
  addons/binding/org.openhab.binding.valloxmv/ESH-INF/i18n/valloxmv_de.properties
  addons/binding/org.openhab.binding.valloxmv/ESH-INF/thing/thing-types.xml
  addons/binding/org.openhab.binding.valloxmv/README.md
  addons/binding/org.openhab.binding.valloxmv/README_DEV.md
  addons/binding/org.openhab.binding.valloxmv/src/main/java/org/openhab/binding/valloxmv/internal/ValloxMVBindingConstants.java
  addons/binding/org.openhab.binding.valloxmv/src/main/java/org/openhab/binding/valloxmv/internal/ValloxMVWebSocket.java
Labels: enhancement

#5138 [spotify] Update README.md, Replaces #5105
  addons/binding/org.openhab.binding.spotify/README.md
Labels: documentation

#5132 [mqtt] change the 1st rule for synchronizing instances
  addons/binding/org.openhab.binding.mqtt.generic/README.md
Labels: binding: mqtt, documentation

#5152 [ihc] Replaced usage of 'DatatypeConverter'
  addons/binding/org.openhab.binding.ihc/src/main/java/org/openhab/binding/ihc/internal/ws/IhcClient.java
Labels: infrastructure

#5123 [googletts] Added additional null check to prevent NPE
  addons/voice/org.openhab.voice.googletts/src/main/java/org/openhab/voice/googletts/internal/GoogleCloudAPI.java
  addons/voice/org.openhab.voice.googletts/src/main/java/org/openhab/voice/googletts/internal/protocol/ListVoicesResponse.java
Labels: bug

#5124 [infrastructure] Migrate globalcache to bnd
  CODEOWNERS
  addons/binding/org.openhab.binding.globalcache/.classpath
  addons/binding/org.openhab.binding.globalcache/.project
  addons/binding/org.openhab.binding.globalcache/META-INF/MANIFEST.MF
  addons/binding/org.openhab.binding.globalcache/OSGI-INF/.gitignore
  addons/binding/org.openhab.binding.globalcache/build.properties
  addons/binding/org.openhab.binding.globalcache/pom.xml
  addons/binding/pom.xml
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.globalcache/.classpath
  bundles/org.openhab.binding.globalcache/.project
  bundles/org.openhab.binding.globalcache/.settings/org.eclipse.core.resources.prefs
  bundles/org.openhab.binding.globalcache/.settings/org.eclipse.m2e.core.prefs
  bundles/org.openhab.binding.globalcache/NOTICE
  bundles/org.openhab.binding.globalcache/README.md
  bundles/org.openhab.binding.globalcache/pom.xml
  bundles/org.openhab.binding.globalcache/src/main/java/org/openhab/binding/globalcache/internal/GlobalCacheBindingConstants.java
  bundles/org.openhab.binding.globalcache/src/main/java/org/openhab/binding/globalcache/internal/GlobalCacheHandlerFactory.java
  bundles/org.openhab.binding.globalcache/src/main/java/org/openhab/binding/globalcache/internal/command/AbstractCommand.java
  bundles/org.openhab.binding.globalcache/src/main/java/org/openhab/binding/globalcache/internal/command/CommandGetdevices.java
  bundles/org.openhab.binding.globalcache/src/main/java/org/openhab/binding/globalcache/internal/command/CommandGetserial.java
  bundles/org.openhab.binding.globalcache/src/main/java/org/openhab/binding/globalcache/internal/command/CommandGetstate.java
  bundles/org.openhab.binding.globalcache/src/main/java/org/openhab/binding/globalcache/internal/command/CommandGetversion.java
  bundles/org.openhab.binding.globalcache/src/main/java/org/openhab/binding/globalcache/internal/command/CommandInterface.java
  bundles/org.openhab.binding.globalcache/src/main/java/org/openhab/binding/globalcache/internal/command/CommandSendir.java
  bundles/org.openhab.binding.globalcache/src/main/java/org/openhab/binding/globalcache/internal/command/CommandSendserial.java
  bundles/org.openhab.binding.globalcache/src/main/java/org/openhab/binding/globalcache/internal/command/CommandSetserial.java
  bundles/org.openhab.binding.globalcache/src/main/java/org/openhab/binding/globalcache/internal/command/CommandSetstate.java
  bundles/org.openhab.binding.globalcache/src/main/java/org/openhab/binding/globalcache/internal/command/RequestMessage.java
  bundles/org.openhab.binding.globalcache/src/main/java/org/openhab/binding/globalcache/internal/command/ResponseMessage.java
  bundles/org.openhab.binding.globalcache/src/main/java/org/openhab/binding/globalcache/internal/discovery/GlobalCacheDiscoveryService.java
  bundles/org.openhab.binding.globalcache/src/main/java/org/openhab/binding/globalcache/internal/discovery/MulticastListener.java
  bundles/org.openhab.binding.globalcache/src/main/java/org/openhab/binding/globalcache/internal/handler/GlobalCacheHandler.java
  bundles/org.openhab.binding.globalcache/src/main/resources/ESH-INF/binding/binding.xml
  bundles/org.openhab.binding.globalcache/src/main/resources/ESH-INF/thing/channel-types.xml
  bundles/org.openhab.binding.globalcache/src/main/resources/ESH-INF/thing/channels.xml
  bundles/org.openhab.binding.globalcache/src/main/resources/ESH-INF/thing/gc-100-06.xml
  bundles/org.openhab.binding.globalcache/src/main/resources/ESH-INF/thing/gc-100-12.xml
  bundles/org.openhab.binding.globalcache/src/main/resources/ESH-INF/thing/itach-cc.xml
  bundles/org.openhab.binding.globalcache/src/main/resources/ESH-INF/thing/itach-flex.xml
  bundles/org.openhab.binding.globalcache/src/main/resources/ESH-INF/thing/itach-ir.xml
  bundles/org.openhab.binding.globalcache/src/main/resources/ESH-INF/thing/itach-sl.xml
  bundles/org.openhab.binding.globalcache/src/main/resources/ESH-INF/thing/zmote.xml
  bundles/pom.xml
  features/karaf/openhab-addons/src/main/feature/feature.xml
Labels: infrastructure

#5145 [infrastructure] move unit tests to base bundles (onewire+dmx)
  bundles/org.openhab.binding.dmx/src/test/java/org/openhab/binding/dmx/internal/handler/ArtnetBridgeHandlerTest.java
  bundles/org.openhab.binding.dmx/src/test/java/org/openhab/binding/dmx/internal/handler/ChaserThingHandlerTest.java
  bundles/org.openhab.binding.dmx/src/test/java/org/openhab/binding/dmx/internal/handler/ColorThingHandlerTest.java
  bundles/org.openhab.binding.dmx/src/test/java/org/openhab/binding/dmx/internal/handler/DimmerThingHandlerTest.java
  bundles/org.openhab.binding.dmx/src/test/java/org/openhab/binding/dmx/internal/handler/DmxBridgeHandlerTest.java
  bundles/org.openhab.binding.dmx/src/test/java/org/openhab/binding/dmx/internal/handler/Lib485BridgeHandlerTest.java
  bundles/org.openhab.binding.dmx/src/test/java/org/openhab/binding/dmx/internal/handler/SacnBridgeHandlerTest.java
  bundles/org.openhab.binding.dmx/src/test/java/org/openhab/binding/dmx/internal/handler/TunableWhiteThingHandlerTest.java
  bundles/org.openhab.binding.dmx/src/test/java/org/openhab/binding/dmx/test/AbstractDmxThingTestParent.java
  bundles/org.openhab.binding.dmx/src/test/java/org/openhab/binding/dmx/test/TestBridgeHandler.java
  bundles/org.openhab.binding.onewire/src/test/java/org/openhab/binding/onewire/internal/BasicThingHandlerTest.java
  bundles/org.openhab.binding.onewire/src/test/java/org/openhab/binding/onewire/internal/EDSSensorThingHandlerTest.java
  bundles/org.openhab.binding.onewire/src/test/java/org/openhab/binding/onewire/internal/MultisensorThingHandlerTest.java
  bundles/org.openhab.binding.onewire/src/test/java/org/openhab/binding/onewire/internal/OwserverBridgeHandlerTest.java
  bundles/org.openhab.binding.onewire/src/test/java/org/openhab/binding/onewire/owserver/OwserverConnectionTest.java
  bundles/org.openhab.binding.onewire/src/test/java/org/openhab/binding/onewire/test/AbstractThingHandlerTest.java
  bundles/org.openhab.binding.onewire/src/test/java/org/openhab/binding/onewire/test/OwserverTestServer.java
  itests/org.openhab.binding.dmx.tests/.classpath
  itests/org.openhab.binding.dmx.tests/.project
  itests/org.openhab.binding.dmx.tests/.settings/org.eclipse.core.resources.prefs
  itests/org.openhab.binding.dmx.tests/.settings/org.eclipse.m2e.core.prefs
  itests/org.openhab.binding.dmx.tests/NOTICE
  itests/org.openhab.binding.dmx.tests/itest.bndrun
  itests/org.openhab.binding.dmx.tests/pom.xml
  itests/org.openhab.binding.dmx.tests/src/main/java/org/openhab/binding/dmx/test/DmxTestHandlerFactory.java
  itests/org.openhab.binding.dmx.tests/src/main/resources/ESH-INF/thing/test-bridge.xml
  itests/org.openhab.binding.onewire.tests/.classpath
  itests/org.openhab.binding.onewire.tests/.project
  itests/org.openhab.binding.onewire.tests/.settings/org.eclipse.core.resources.prefs
  itests/org.openhab.binding.onewire.tests/.settings/org.eclipse.m2e.core.prefs
  itests/org.openhab.binding.onewire.tests/NOTICE
  itests/org.openhab.binding.onewire.tests/itest.bndrun
  itests/org.openhab.binding.onewire.tests/pom.xml
  itests/pom.xml
Labels: infrastructure

#5140 [openweathermap] Update the French translation
  bundles/org.openhab.binding.openweathermap/src/main/resources/ESH-INF/i18n/openweathermap_fr.properties
Labels: translation

#5127 migrate network binding to bnd
  CODEOWNERS
  addons/binding/org.openhab.binding.network.test/.classpath
  addons/binding/org.openhab.binding.network.test/META-INF/MANIFEST.MF
  addons/binding/org.openhab.binding.network.test/build.properties
  addons/binding/org.openhab.binding.network.test/org.openhab.binding.network.test.launch
  addons/binding/org.openhab.binding.network.test/pom.xml
  addons/binding/org.openhab.binding.network/.classpath
  addons/binding/org.openhab.binding.network/.project
  addons/binding/org.openhab.binding.network/META-INF/MANIFEST.MF
  addons/binding/org.openhab.binding.network/NOTICE
  addons/binding/org.openhab.binding.network/OSGI-INF/.gitignore
  addons/binding/org.openhab.binding.network/build.properties
  addons/binding/org.openhab.binding.network/pom.xml
  addons/binding/pom.xml
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.network/.classpath
  bundles/org.openhab.binding.network/.project
  bundles/org.openhab.binding.network/.settings/org.eclipse.core.resources.prefs
  bundles/org.openhab.binding.network/.settings/org.eclipse.m2e.core.prefs
  bundles/org.openhab.binding.network/NOTICE
  bundles/org.openhab.binding.network/README.md
  bundles/org.openhab.binding.network/pom.xml
  bundles/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/NetworkBindingConfiguration.java
  bundles/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/NetworkBindingConstants.java
  bundles/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/NetworkHandlerConfiguration.java
  bundles/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/NetworkHandlerFactory.java
  bundles/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/PresenceDetection.java
  bundles/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/PresenceDetectionListener.java
  bundles/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/PresenceDetectionType.java
  bundles/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/PresenceDetectionValue.java
  bundles/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/dhcp/DHCPListenService.java
  bundles/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/dhcp/DHCPPacket.java
  bundles/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/dhcp/DHCPPacketListenerServer.java
  bundles/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/dhcp/IPRequestReceivedCallback.java
  bundles/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/discovery/NetworkDiscoveryService.java
  bundles/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/handler/NetworkHandler.java
  bundles/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/toberemoved/cache/ExpiringCacheAsync.java
  bundles/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/utils/NetworkUtils.java
  bundles/org.openhab.binding.network/src/main/resources/ESH-INF/binding/binding.xml
  bundles/org.openhab.binding.network/src/main/resources/ESH-INF/i18n/network_de.properties
  bundles/org.openhab.binding.network/src/main/resources/ESH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.network/src/test/java/org/openhab/binding/network/internal/PresenceDetectionTest.java
  bundles/org.openhab.binding.network/src/test/java/org/openhab/binding/network/internal/PresenceDetectionValuesTest.java
  bundles/org.openhab.binding.network/src/test/java/org/openhab/binding/network/internal/dhcp/DHCPTest.java
  bundles/org.openhab.binding.network/src/test/java/org/openhab/binding/network/internal/discovery/DiscoveryTest.java
  bundles/org.openhab.binding.network/src/test/java/org/openhab/binding/network/internal/handler/NetworkHandlerTest.java
  bundles/org.openhab.binding.network/src/test/java/org/openhab/binding/network/internal/toberemoved/cache/ExpiringCacheAsyncTest.java
  bundles/org.openhab.binding.network/src/test/java/org/openhab/binding/network/internal/toberemoved/cache/ExpiringCacheHelper.java
  bundles/pom.xml
  features/karaf/openhab-addons/src/main/feature/feature.xml
Labels: infrastructure

#5158 Update README.md
  README.md
Labels: documentation

#5151 migrate unifi binding to bnd
  CODEOWNERS
  addons/binding/org.openhab.binding.unifi/.classpath
  addons/binding/org.openhab.binding.unifi/META-INF/MANIFEST.MF
  addons/binding/org.openhab.binding.unifi/OSGI-INF/.gitignore
  addons/binding/org.openhab.binding.unifi/build.properties
  addons/binding/org.openhab.binding.unifi/pom.xml
  addons/binding/pom.xml
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.unifi/.classpath
  bundles/org.openhab.binding.unifi/.project
  bundles/org.openhab.binding.unifi/.settings/org.eclipse.core.resources.prefs
  bundles/org.openhab.binding.unifi/.settings/org.eclipse.m2e.core.prefs
  bundles/org.openhab.binding.unifi/NOTICE
  bundles/org.openhab.binding.unifi/README.md
  bundles/org.openhab.binding.unifi/pom.xml
  bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/UniFiBindingConstants.java
  bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/UniFiClientThingConfig.java
  bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/UniFiControllerThingConfig.java
  bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/UniFiThingHandlerFactory.java
  bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/api/UniFiCommunicationException.java
  bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/api/UniFiException.java
  bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/api/UniFiExpiredSessionException.java
  bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/api/UniFiInvalidCredentialsException.java
  bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/api/UniFiInvalidHostException.java
  bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/api/UniFiNotAuthorizedException.java
  bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/api/UniFiSSLException.java
  bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/api/cache/UniFiCache.java
  bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/api/cache/UniFiClientCache.java
  bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/api/cache/UniFiDeviceCache.java
  bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/api/cache/UniFiSiteCache.java
  bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/api/model/UniFiClient.java
  bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/api/model/UniFiController.java
  bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/api/model/UniFiControllerRequest.java
  bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/api/model/UniFiDevice.java
  bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/api/model/UniFiSite.java
  bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/api/model/UniFiUnknownClient.java
  bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/api/model/UniFiWiredClient.java
  bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/api/model/UniFiWirelessClient.java
  bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/api/util/UniFiClientDeserializer.java
  bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/api/util/UniFiClientInstanceCreator.java
  bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/api/util/UniFiDeviceInstanceCreator.java
  bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/api/util/UniFiSiteInstanceCreator.java
  bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/api/util/UniFiTidyLowerCaseStringDeserializer.java
  bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/api/util/UniFiTimestampDeserializer.java
  bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/handler/UniFiBaseThingHandler.java
  bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/handler/UniFiClientThingHandler.java
  bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/handler/UniFiControllerThingHandler.java
  bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/ssl/UniFiTrustManager.java
  bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/ssl/UniFiTrustManagerProvider.java
  bundles/org.openhab.binding.unifi/src/main/resources/ESH-INF/binding/binding.xml
  bundles/org.openhab.binding.unifi/src/main/resources/ESH-INF/thing/thing-types.xml
  bundles/pom.xml
  features/karaf/openhab-addons/src/main/feature/feature.xml
Labels: infrastructure

#5143 [meteoblue] Add French translation
  addons/binding/org.openhab.binding.meteoblue/ESH-INF/i18n/meteoblue_fr.properties
Labels: translation

#5153 migrate atlona to bnd
  CODEOWNERS
  addons/binding/org.openhab.binding.atlona/.classpath
  addons/binding/org.openhab.binding.atlona/META-INF/MANIFEST.MF
  addons/binding/org.openhab.binding.atlona/OSGI-INF/.gitignore
  addons/binding/org.openhab.binding.atlona/build.properties
  addons/binding/org.openhab.binding.atlona/pom.xml
  addons/binding/pom.xml
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.atlona/.classpath
  bundles/org.openhab.binding.atlona/.project
  bundles/org.openhab.binding.atlona/.settings/org.eclipse.core.resources.prefs
  bundles/org.openhab.binding.atlona/.settings/org.eclipse.m2e.core.prefs
  bundles/org.openhab.binding.atlona/NOTICE
  bundles/org.openhab.binding.atlona/README.md
  bundles/org.openhab.binding.atlona/pom.xml
  bundles/org.openhab.binding.atlona/src/main/java/org/openhab/binding/atlona/internal/AtlonaBindingConstants.java
  bundles/org.openhab.binding.atlona/src/main/java/org/openhab/binding/atlona/internal/AtlonaHandlerCallback.java
  bundles/org.openhab.binding.atlona/src/main/java/org/openhab/binding/atlona/internal/AtlonaHandlerFactory.java
  bundles/org.openhab.binding.atlona/src/main/java/org/openhab/binding/atlona/internal/StatefulHandlerCallback.java
  bundles/org.openhab.binding.atlona/src/main/java/org/openhab/binding/atlona/internal/discovery/AtlonaDiscovery.java
  bundles/org.openhab.binding.atlona/src/main/java/org/openhab/binding/atlona/internal/handler/AtlonaCapabilities.java
  bundles/org.openhab.binding.atlona/src/main/java/org/openhab/binding/atlona/internal/handler/AtlonaHandler.java
  bundles/org.openhab.binding.atlona/src/main/java/org/openhab/binding/atlona/internal/net/SocketChannelSession.java
  bundles/org.openhab.binding.atlona/src/main/java/org/openhab/binding/atlona/internal/net/SocketSession.java
  bundles/org.openhab.binding.atlona/src/main/java/org/openhab/binding/atlona/internal/net/SocketSessionListener.java
  bundles/org.openhab.binding.atlona/src/main/java/org/openhab/binding/atlona/internal/pro3/AtlonaPro3Capabilities.java
  bundles/org.openhab.binding.atlona/src/main/java/org/openhab/binding/atlona/internal/pro3/AtlonaPro3Config.java
  bundles/org.openhab.binding.atlona/src/main/java/org/openhab/binding/atlona/internal/pro3/AtlonaPro3Constants.java
  bundles/org.openhab.binding.atlona/src/main/java/org/openhab/binding/atlona/internal/pro3/AtlonaPro3Handler.java
  bundles/org.openhab.binding.atlona/src/main/java/org/openhab/binding/atlona/internal/pro3/AtlonaPro3PortocolHandler.java
  bundles/org.openhab.binding.atlona/src/main/java/org/openhab/binding/atlona/internal/pro3/AtlonaPro3Utilities.java
  bundles/org.openhab.binding.atlona/src/main/resources/ESH-INF/binding/binding.xml
  bundles/org.openhab.binding.atlona/src/main/resources/ESH-INF/thing/thing-types.xml
  bundles/pom.xml
  features/karaf/openhab-addons/src/main/feature/feature.xml
Labels: infrastructure

#5160 [dwdunwetter] Migrate to bnd build
  CODEOWNERS
  addons/binding/org.openhab.binding.dwdunwetter.test/.classpath
  addons/binding/org.openhab.binding.dwdunwetter.test/META-INF/MANIFEST.MF
  addons/binding/org.openhab.binding.dwdunwetter.test/build.properties
  addons/binding/org.openhab.binding.dwdunwetter.test/org.openhab.binding.dwdunwetter.test.launch
  addons/binding/org.openhab.binding.dwdunwetter.test/pom.xml
  addons/binding/org.openhab.binding.dwdunwetter/.classpath
  addons/binding/org.openhab.binding.dwdunwetter/.project
  addons/binding/org.openhab.binding.dwdunwetter/META-INF/MANIFEST.MF
  addons/binding/org.openhab.binding.dwdunwetter/NOTICE
  addons/binding/org.openhab.binding.dwdunwetter/OSGI-INF/.gitignore
  addons/binding/org.openhab.binding.dwdunwetter/build.properties
  addons/binding/org.openhab.binding.dwdunwetter/pom.xml
  addons/binding/pom.xml
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.dwdunwetter/.classpath
  bundles/org.openhab.binding.dwdunwetter/.project
  bundles/org.openhab.binding.dwdunwetter/.settings/org.eclipse.core.resources.prefs
  bundles/org.openhab.binding.dwdunwetter/.settings/org.eclipse.m2e.core.prefs
  bundles/org.openhab.binding.dwdunwetter/NOTICE
  bundles/org.openhab.binding.dwdunwetter/README.md
  bundles/org.openhab.binding.dwdunwetter/README_de.md
  bundles/org.openhab.binding.dwdunwetter/pom.xml
  bundles/org.openhab.binding.dwdunwetter/src/main/java/org/openhab/binding/dwdunwetter/internal/DwdUnwetterBindingConstants.java
  bundles/org.openhab.binding.dwdunwetter/src/main/java/org/openhab/binding/dwdunwetter/internal/DwdUnwetterConfiguration.java
  bundles/org.openhab.binding.dwdunwetter/src/main/java/org/openhab/binding/dwdunwetter/internal/DwdUnwetterHandler.java
  bundles/org.openhab.binding.dwdunwetter/src/main/java/org/openhab/binding/dwdunwetter/internal/DwdUnwetterHandlerFactory.java
  bundles/org.openhab.binding.dwdunwetter/src/main/java/org/openhab/binding/dwdunwetter/internal/data/DwdWarningCache.java
  bundles/org.openhab.binding.dwdunwetter/src/main/java/org/openhab/binding/dwdunwetter/internal/data/DwdWarningData.java
  bundles/org.openhab.binding.dwdunwetter/src/main/java/org/openhab/binding/dwdunwetter/internal/data/DwdWarningDataAccess.java
  bundles/org.openhab.binding.dwdunwetter/src/main/java/org/openhab/binding/dwdunwetter/internal/data/DwdWarningsData.java
  bundles/org.openhab.binding.dwdunwetter/src/main/java/org/openhab/binding/dwdunwetter/internal/data/DwdXmlTag.java
  bundles/org.openhab.binding.dwdunwetter/src/main/java/org/openhab/binding/dwdunwetter/internal/data/Severity.java
  bundles/org.openhab.binding.dwdunwetter/src/main/java/org/openhab/binding/dwdunwetter/internal/data/SeverityComparator.java
  bundles/org.openhab.binding.dwdunwetter/src/main/java/org/openhab/binding/dwdunwetter/internal/data/Urgency.java
  bundles/org.openhab.binding.dwdunwetter/src/main/resources/ESH-INF/binding/binding.xml
  bundles/org.openhab.binding.dwdunwetter/src/main/resources/ESH-INF/i18n/dwdunwetter_de.properties
  bundles/org.openhab.binding.dwdunwetter/src/main/resources/ESH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.dwdunwetter/src/test/java/org/openhab/binding/dwdunwetter/DwdUnwetterHandlerTest.java
  bundles/org.openhab.binding.dwdunwetter/src/test/java/org/openhab/binding/dwdunwetter/internal/data/DwdWarningCacheTest.java
  bundles/org.openhab.binding.dwdunwetter/src/test/java/org/openhab/binding/dwdunwetter/internal/data/DwdWarningsDataTest.java
  bundles/org.openhab.binding.dwdunwetter/src/test/resources/org/openhab/binding/dwdunwetter/internal/data/warnings.xml
  bundles/pom.xml
  features/karaf/openhab-addons/src/main/feature/feature.xml
Labels: infrastructure

#5175 [pulseaudio] Migrate to bnd build
  CODEOWNERS
  addons/binding/org.openhab.binding.pulseaudio/.classpath
  addons/binding/org.openhab.binding.pulseaudio/META-INF/MANIFEST.MF
  addons/binding/org.openhab.binding.pulseaudio/OSGI-INF/.gitignore
  addons/binding/org.openhab.binding.pulseaudio/build.properties
  addons/binding/org.openhab.binding.pulseaudio/pom.xml
  addons/binding/pom.xml
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.pulseaudio/.classpath
  bundles/org.openhab.binding.pulseaudio/.project
  bundles/org.openhab.binding.pulseaudio/.settings/org.eclipse.core.resources.prefs
  bundles/org.openhab.binding.pulseaudio/.settings/org.eclipse.m2e.core.prefs
  bundles/org.openhab.binding.pulseaudio/NOTICE
  bundles/org.openhab.binding.pulseaudio/README.md
  bundles/org.openhab.binding.pulseaudio/pom.xml
  bundles/org.openhab.binding.pulseaudio/src/main/java/org/openhab/binding/pulseaudio/internal/PulseaudioBindingConstants.java
  bundles/org.openhab.binding.pulseaudio/src/main/java/org/openhab/binding/pulseaudio/internal/PulseaudioClient.java
  bundles/org.openhab.binding.pulseaudio/src/main/java/org/openhab/binding/pulseaudio/internal/PulseaudioHandlerFactory.java
  bundles/org.openhab.binding.pulseaudio/src/main/java/org/openhab/binding/pulseaudio/internal/cli/Parser.java
  bundles/org.openhab.binding.pulseaudio/src/main/java/org/openhab/binding/pulseaudio/internal/discovery/PulseaudioDeviceDiscoveryService.java
  bundles/org.openhab.binding.pulseaudio/src/main/java/org/openhab/binding/pulseaudio/internal/discovery/PulseaudioDiscoveryParticipant.java
  bundles/org.openhab.binding.pulseaudio/src/main/java/org/openhab/binding/pulseaudio/internal/handler/DeviceStatusListener.java
  bundles/org.openhab.binding.pulseaudio/src/main/java/org/openhab/binding/pulseaudio/internal/handler/PulseaudioBridgeHandler.java
  bundles/org.openhab.binding.pulseaudio/src/main/java/org/openhab/binding/pulseaudio/internal/handler/PulseaudioHandler.java
  bundles/org.openhab.binding.pulseaudio/src/main/java/org/openhab/binding/pulseaudio/internal/items/AbstractAudioDeviceConfig.java
  bundles/org.openhab.binding.pulseaudio/src/main/java/org/openhab/binding/pulseaudio/internal/items/AbstractDeviceConfig.java
  bundles/org.openhab.binding.pulseaudio/src/main/java/org/openhab/binding/pulseaudio/internal/items/Module.java
  bundles/org.openhab.binding.pulseaudio/src/main/java/org/openhab/binding/pulseaudio/internal/items/Sink.java
  bundles/org.openhab.binding.pulseaudio/src/main/java/org/openhab/binding/pulseaudio/internal/items/SinkInput.java
  bundles/org.openhab.binding.pulseaudio/src/main/java/org/openhab/binding/pulseaudio/internal/items/Source.java
  bundles/org.openhab.binding.pulseaudio/src/main/java/org/openhab/binding/pulseaudio/internal/items/SourceOutput.java
  bundles/org.openhab.binding.pulseaudio/src/main/resources/ESH-INF/binding/binding.xml
  bundles/org.openhab.binding.pulseaudio/src/main/resources/ESH-INF/config/config.xml
  bundles/org.openhab.binding.pulseaudio/src/main/resources/ESH-INF/thing/bridge.xml
  bundles/org.openhab.binding.pulseaudio/src/main/resources/ESH-INF/thing/channels.xml
  bundles/org.openhab.binding.pulseaudio/src/main/resources/ESH-INF/thing/combined-sink.xml
  bundles/org.openhab.binding.pulseaudio/src/main/resources/ESH-INF/thing/sink-input.xml
  bundles/org.openhab.binding.pulseaudio/src/main/resources/ESH-INF/thing/sink.xml
  bundles/org.openhab.binding.pulseaudio/src/main/resources/ESH-INF/thing/source-output.xml
  bundles/org.openhab.binding.pulseaudio/src/main/resources/ESH-INF/thing/source.xml
  bundles/pom.xml
  features/karaf/openhab-addons/src/main/feature/feature.xml
Labels: infrastructure

#5176 [folding] Migrate to bnd build
  CODEOWNERS
  addons/binding/org.openhab.binding.folding/.classpath
  addons/binding/org.openhab.binding.folding/META-INF/MANIFEST.MF
  addons/binding/org.openhab.binding.folding/OSGI-INF/.gitignore
  addons/binding/org.openhab.binding.folding/build.properties
  addons/binding/org.openhab.binding.folding/pom.xml
  addons/binding/pom.xml
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.folding/.classpath
  bundles/org.openhab.binding.folding/.project
  bundles/org.openhab.binding.folding/.settings/org.eclipse.core.resources.prefs
  bundles/org.openhab.binding.folding/.settings/org.eclipse.m2e.core.prefs
  bundles/org.openhab.binding.folding/NOTICE
  bundles/org.openhab.binding.folding/README.md
  bundles/org.openhab.binding.folding/pom.xml
  bundles/org.openhab.binding.folding/src/main/java/org/openhab/binding/folding/internal/FoldingBindingConstants.java
  bundles/org.openhab.binding.folding/src/main/java/org/openhab/binding/folding/internal/FoldingHandlerFactory.java
  bundles/org.openhab.binding.folding/src/main/java/org/openhab/binding/folding/internal/discovery/FoldingDiscoveryProxy.java
  bundles/org.openhab.binding.folding/src/main/java/org/openhab/binding/folding/internal/discovery/FoldingSlotDiscoveryService.java
  bundles/org.openhab.binding.folding/src/main/java/org/openhab/binding/folding/internal/handler/FoldingClientHandler.java
  bundles/org.openhab.binding.folding/src/main/java/org/openhab/binding/folding/internal/handler/SlotHandler.java
  bundles/org.openhab.binding.folding/src/main/java/org/openhab/binding/folding/internal/handler/SlotInfo.java
  bundles/org.openhab.binding.folding/src/main/java/org/openhab/binding/folding/internal/handler/SlotUpdateListener.java
  bundles/org.openhab.binding.folding/src/main/resources/ESH-INF/binding/binding.xml
  bundles/org.openhab.binding.folding/src/main/resources/ESH-INF/thing/thing-types.xml
  bundles/pom.xml
  features/karaf/openhab-addons/src/main/feature/feature.xml
Labels: infrastructure

#5177 [coolmasternet] Migrate to bnd build
  CODEOWNERS
  addons/binding/org.openhab.binding.coolmasternet/.classpath
  addons/binding/org.openhab.binding.coolmasternet/META-INF/MANIFEST.MF
  addons/binding/org.openhab.binding.coolmasternet/OSGI-INF/.gitignore
  addons/binding/org.openhab.binding.coolmasternet/build.properties
  addons/binding/org.openhab.binding.coolmasternet/pom.xml
  addons/binding/pom.xml
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.coolmasternet/.classpath
  bundles/org.openhab.binding.coolmasternet/.project
  bundles/org.openhab.binding.coolmasternet/.settings/org.eclipse.core.resources.prefs
  bundles/org.openhab.binding.coolmasternet/.settings/org.eclipse.m2e.core.prefs
  bundles/org.openhab.binding.coolmasternet/NOTICE
  bundles/org.openhab.binding.coolmasternet/README.md
  bundles/org.openhab.binding.coolmasternet/pom.xml
  bundles/org.openhab.binding.coolmasternet/src/main/java/org/openhab/binding/coolmasternet/internal/ControllerHandler.java
  bundles/org.openhab.binding.coolmasternet/src/main/java/org/openhab/binding/coolmasternet/internal/CoolMasterNetBindingConstants.java
  bundles/org.openhab.binding.coolmasternet/src/main/java/org/openhab/binding/coolmasternet/internal/CoolMasterNetHandlerFactory.java
  bundles/org.openhab.binding.coolmasternet/src/main/java/org/openhab/binding/coolmasternet/internal/config/ControllerConfiguration.java
  bundles/org.openhab.binding.coolmasternet/src/main/java/org/openhab/binding/coolmasternet/internal/config/HVACConfiguration.java
  bundles/org.openhab.binding.coolmasternet/src/main/java/org/openhab/binding/coolmasternet/internal/handler/HVACHandler.java
  bundles/org.openhab.binding.coolmasternet/src/main/resources/ESH-INF/binding/binding.xml
  bundles/org.openhab.binding.coolmasternet/src/main/resources/ESH-INF/thing/thing-types.xml
  bundles/pom.xml
  features/karaf/openhab-addons/src/main/feature/feature.xml
Labels: infrastructure

#5178 [bosesoundtouch] Migrate to bnd build
  CODEOWNERS
  addons/binding/org.openhab.binding.bosesoundtouch/.classpath
  addons/binding/org.openhab.binding.bosesoundtouch/META-INF/MANIFEST.MF
  addons/binding/org.openhab.binding.bosesoundtouch/OSGI-INF/.gitignore
  addons/binding/org.openhab.binding.bosesoundtouch/build.properties
  addons/binding/pom.xml
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.bosesoundtouch/.classpath
  bundles/org.openhab.binding.bosesoundtouch/.project
  bundles/org.openhab.binding.bosesoundtouch/.settings/org.eclipse.core.resources.prefs
  bundles/org.openhab.binding.bosesoundtouch/.settings/org.eclipse.m2e.core.prefs
  bundles/org.openhab.binding.bosesoundtouch/NOTICE
  bundles/org.openhab.binding.bosesoundtouch/README.md
  bundles/org.openhab.binding.bosesoundtouch/pom.xml
  bundles/org.openhab.binding.bosesoundtouch/src/main/java/org/openhab/binding/bosesoundtouch/internal/APIRequest.java
  bundles/org.openhab.binding.bosesoundtouch/src/main/java/org/openhab/binding/bosesoundtouch/internal/AvailableSources.java
  bundles/org.openhab.binding.bosesoundtouch/src/main/java/org/openhab/binding/bosesoundtouch/internal/BoseSoundTouchBindingConstants.java
  bundles/org.openhab.binding.bosesoundtouch/src/main/java/org/openhab/binding/bosesoundtouch/internal/BoseSoundTouchConfiguration.java
  bundles/org.openhab.binding.bosesoundtouch/src/main/java/org/openhab/binding/bosesoundtouch/internal/BoseSoundTouchHandlerFactory.java
  bundles/org.openhab.binding.bosesoundtouch/src/main/java/org/openhab/binding/bosesoundtouch/internal/BoseSoundTouchNotFoundException.java
  bundles/org.openhab.binding.bosesoundtouch/src/main/java/org/openhab/binding/bosesoundtouch/internal/BoseSoundTouchNotificationChannelConfiguration.java
  bundles/org.openhab.binding.bosesoundtouch/src/main/java/org/openhab/binding/bosesoundtouch/internal/BoseStateDescriptionOptionProvider.java
  bundles/org.openhab.binding.bosesoundtouch/src/main/java/org/openhab/binding/bosesoundtouch/internal/CommandExecutor.java
  bundles/org.openhab.binding.bosesoundtouch/src/main/java/org/openhab/binding/bosesoundtouch/internal/ContentItem.java
  bundles/org.openhab.binding.bosesoundtouch/src/main/java/org/openhab/binding/bosesoundtouch/internal/ContentItemMaker.java
  bundles/org.openhab.binding.bosesoundtouch/src/main/java/org/openhab/binding/bosesoundtouch/internal/ContentItemNotPresetableException.java
  bundles/org.openhab.binding.bosesoundtouch/src/main/java/org/openhab/binding/bosesoundtouch/internal/NoInternetRadioPresetFoundException.java
  bundles/org.openhab.binding.bosesoundtouch/src/main/java/org/openhab/binding/bosesoundtouch/internal/NoPresetFoundException.java
  bundles/org.openhab.binding.bosesoundtouch/src/main/java/org/openhab/binding/bosesoundtouch/internal/NoStoredMusicPresetFoundException.java
  bundles/org.openhab.binding.bosesoundtouch/src/main/java/org/openhab/binding/bosesoundtouch/internal/OperationModeNotAvailableException.java
  bundles/org.openhab.binding.bosesoundtouch/src/main/java/org/openhab/binding/bosesoundtouch/internal/OperationModeType.java
  bundles/org.openhab.binding.bosesoundtouch/src/main/java/org/openhab/binding/bosesoundtouch/internal/PresetContainer.java
  bundles/org.openhab.binding.bosesoundtouch/src/main/java/org/openhab/binding/bosesoundtouch/internal/RemoteKeyType.java
  bundles/org.openhab.binding.bosesoundtouch/src/main/java/org/openhab/binding/bosesoundtouch/internal/XMLHandlerState.java
  bundles/org.openhab.binding.bosesoundtouch/src/main/java/org/openhab/binding/bosesoundtouch/internal/XMLResponseHandler.java
  bundles/org.openhab.binding.bosesoundtouch/src/main/java/org/openhab/binding/bosesoundtouch/internal/XMLResponseProcessor.java
  bundles/org.openhab.binding.bosesoundtouch/src/main/java/org/openhab/binding/bosesoundtouch/internal/discovery/DiscoveryUtil.java
  bundles/org.openhab.binding.bosesoundtouch/src/main/java/org/openhab/binding/bosesoundtouch/internal/discovery/SoundTouchDiscoveryParticipant.java
  bundles/org.openhab.binding.bosesoundtouch/src/main/java/org/openhab/binding/bosesoundtouch/internal/handler/BoseSoundTouchHandler.java
  bundles/org.openhab.binding.bosesoundtouch/src/main/resources/ESH-INF/binding/binding.xml
  bundles/org.openhab.binding.bosesoundtouch/src/main/resources/ESH-INF/config/config.xml
  bundles/org.openhab.binding.bosesoundtouch/src/main/resources/ESH-INF/thing/SoundTouch10.xml
  bundles/org.openhab.binding.bosesoundtouch/src/main/resources/ESH-INF/thing/SoundTouch20.xml
  bundles/org.openhab.binding.bosesoundtouch/src/main/resources/ESH-INF/thing/SoundTouch30.xml
  bundles/org.openhab.binding.bosesoundtouch/src/main/resources/ESH-INF/thing/SoundTouch300.xml
  bundles/org.openhab.binding.bosesoundtouch/src/main/resources/ESH-INF/thing/SoundTouchSA5Amplifier.xml
  bundles/org.openhab.binding.bosesoundtouch/src/main/resources/ESH-INF/thing/SoundTouchWirelessLinkAdapter.xml
  bundles/org.openhab.binding.bosesoundtouch/src/main/resources/ESH-INF/thing/UnknownSoundTouch.xml
  bundles/org.openhab.binding.bosesoundtouch/src/main/resources/ESH-INF/thing/WaveSoundTouchMusicSystemIV.xml
  bundles/org.openhab.binding.bosesoundtouch/src/main/resources/ESH-INF/thing/channels.xml
  bundles/pom.xml
  features/karaf/openhab-addons/src/main/feature/feature.xml
Labels: infrastructure

#5185 [OpenUV] Migrate binding to bnd build
  CODEOWNERS
  addons/binding/org.openhab.binding.openuv/.classpath
  addons/binding/org.openhab.binding.openuv/META-INF/MANIFEST.MF
  addons/binding/org.openhab.binding.openuv/OSGI-INF/.gitignore
  addons/binding/org.openhab.binding.openuv/build.properties
  addons/binding/org.openhab.binding.openuv/pom.xml
  addons/binding/pom.xml
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.openuv/.classpath
  bundles/org.openhab.binding.openuv/.project
  bundles/org.openhab.binding.openuv/.settings/org.eclipse.core.resources.prefs
  bundles/org.openhab.binding.openuv/.settings/org.eclipse.jdt.core.prefs
  bundles/org.openhab.binding.openuv/.settings/org.eclipse.m2e.core.prefs
  bundles/org.openhab.binding.openuv/NOTICE
  bundles/org.openhab.binding.openuv/README.md
  bundles/org.openhab.binding.openuv/pom.xml
  bundles/org.openhab.binding.openuv/src/main/java/org/openhab/binding/openuv/internal/OpenUVBindingConstants.java
  bundles/org.openhab.binding.openuv/src/main/java/org/openhab/binding/openuv/internal/OpenUVConfiguration.java
  bundles/org.openhab.binding.openuv/src/main/java/org/openhab/binding/openuv/internal/OpenUVHandlerFactory.java
  bundles/org.openhab.binding.openuv/src/main/java/org/openhab/binding/openuv/internal/discovery/OpenUVDiscoveryService.java
  bundles/org.openhab.binding.openuv/src/main/java/org/openhab/binding/openuv/internal/handler/OpenUVBridgeHandler.java
  bundles/org.openhab.binding.openuv/src/main/java/org/openhab/binding/openuv/internal/handler/OpenUVReportHandler.java
  bundles/org.openhab.binding.openuv/src/main/java/org/openhab/binding/openuv/internal/json/OpenUVJsonResponse.java
  bundles/org.openhab.binding.openuv/src/main/java/org/openhab/binding/openuv/internal/json/OpenUVJsonResult.java
  bundles/org.openhab.binding.openuv/src/main/java/org/openhab/binding/openuv/internal/json/OpenUVSafeExposureTime.java
  bundles/org.openhab.binding.openuv/src/main/resources/ESH-INF/binding/binding.xml
  bundles/org.openhab.binding.openuv/src/main/resources/ESH-INF/thing/thing-types.xml
  bundles/pom.xml
  features/karaf/openhab-addons/src/main/feature/feature.xml
Labels: infrastructure

#5183 [feican] Migrate binding to bnd build
  CODEOWNERS
  addons/binding/org.openhab.binding.feican/.classpath
  addons/binding/org.openhab.binding.feican/.project
  addons/binding/org.openhab.binding.feican/META-INF/MANIFEST.MF
  addons/binding/pom.xml
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.feican/.classpath
  bundles/org.openhab.binding.feican/.project
  bundles/org.openhab.binding.feican/.settings/org.eclipse.core.resources.prefs
  bundles/org.openhab.binding.feican/.settings/org.eclipse.m2e.core.prefs
  bundles/org.openhab.binding.feican/ESH-INF/binding/binding.xml
  bundles/org.openhab.binding.feican/ESH-INF/thing/channels.xml
  bundles/org.openhab.binding.feican/ESH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.feican/NOTICE
  bundles/org.openhab.binding.feican/OSGI-INF/.gitignore
  bundles/org.openhab.binding.feican/README.md
  bundles/org.openhab.binding.feican/build.properties
  bundles/org.openhab.binding.feican/pom.xml
  bundles/org.openhab.binding.feican/src/main/java/org/openhab/binding/feican/internal/Commands.java
  bundles/org.openhab.binding.feican/src/main/java/org/openhab/binding/feican/internal/Connection.java
  bundles/org.openhab.binding.feican/src/main/java/org/openhab/binding/feican/internal/FeicanBindingConstants.java
  bundles/org.openhab.binding.feican/src/main/java/org/openhab/binding/feican/internal/FeicanConfiguration.java
  bundles/org.openhab.binding.feican/src/main/java/org/openhab/binding/feican/internal/FeicanDiscoveryService.java
  bundles/org.openhab.binding.feican/src/main/java/org/openhab/binding/feican/internal/FeicanHandlerFactory.java
  bundles/org.openhab.binding.feican/src/main/java/org/openhab/binding/feican/internal/handler/FeicanHandler.java
  bundles/pom.xml
  features/karaf/openhab-addons/src/main/feature/feature.xml
Labels: infrastructure

#5181 [hyperion] Migrate to bnd build
  CODEOWNERS
  addons/binding/org.openhab.binding.hyperion/.classpath
  addons/binding/org.openhab.binding.hyperion/META-INF/MANIFEST.MF
  addons/binding/org.openhab.binding.hyperion/OSGI-INF/.gitignore
  addons/binding/org.openhab.binding.hyperion/build.properties
  addons/binding/org.openhab.binding.hyperion/pom.xml
  addons/binding/pom.xml
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.hyperion/.classpath
  bundles/org.openhab.binding.hyperion/.project
  bundles/org.openhab.binding.hyperion/.settings/org.eclipse.core.resources.prefs
  bundles/org.openhab.binding.hyperion/.settings/org.eclipse.m2e.core.prefs
  bundles/org.openhab.binding.hyperion/NOTICE
  bundles/org.openhab.binding.hyperion/README.md
  bundles/org.openhab.binding.hyperion/pom.xml
  bundles/org.openhab.binding.hyperion/src/main/java/org/openhab/binding/hyperion/internal/HyperionBindingConstants.java
  bundles/org.openhab.binding.hyperion/src/main/java/org/openhab/binding/hyperion/internal/HyperionDiscoveryParticipant.java
  bundles/org.openhab.binding.hyperion/src/main/java/org/openhab/binding/hyperion/internal/HyperionHandlerFactory.java
  bundles/org.openhab.binding.hyperion/src/main/java/org/openhab/binding/hyperion/internal/HyperionStateDescriptionProvider.java
  bundles/org.openhab.binding.hyperion/src/main/java/org/openhab/binding/hyperion/internal/connection/JsonTcpConnection.java
  bundles/org.openhab.binding.hyperion/src/main/java/org/openhab/binding/hyperion/internal/handler/HyperionHandler.java
  bundles/org.openhab.binding.hyperion/src/main/java/org/openhab/binding/hyperion/internal/handler/HyperionNgHandler.java
  bundles/org.openhab.binding.hyperion/src/main/java/org/openhab/binding/hyperion/internal/protocol/ColorCommand.java
  bundles/org.openhab.binding.hyperion/src/main/java/org/openhab/binding/hyperion/internal/protocol/CommandUnsuccessfulException.java
  bundles/org.openhab.binding.hyperion/src/main/java/org/openhab/binding/hyperion/internal/protocol/EffectCommand.java
  bundles/org.openhab.binding.hyperion/src/main/java/org/openhab/binding/hyperion/internal/protocol/HyperionCommand.java
  bundles/org.openhab.binding.hyperion/src/main/java/org/openhab/binding/hyperion/internal/protocol/ServerInfoCommand.java
  bundles/org.openhab.binding.hyperion/src/main/java/org/openhab/binding/hyperion/internal/protocol/ng/Adjustment.java
  bundles/org.openhab.binding.hyperion/src/main/java/org/openhab/binding/hyperion/internal/protocol/ng/AdjustmentCommand.java
  bundles/org.openhab.binding.hyperion/src/main/java/org/openhab/binding/hyperion/internal/protocol/ng/Component.java
  bundles/org.openhab.binding.hyperion/src/main/java/org/openhab/binding/hyperion/internal/protocol/ng/ComponentState.java
  bundles/org.openhab.binding.hyperion/src/main/java/org/openhab/binding/hyperion/internal/protocol/ng/ComponentStateCommand.java
  bundles/org.openhab.binding.hyperion/src/main/java/org/openhab/binding/hyperion/internal/protocol/ng/Hyperion.java
  bundles/org.openhab.binding.hyperion/src/main/java/org/openhab/binding/hyperion/internal/protocol/ng/NgInfo.java
  bundles/org.openhab.binding.hyperion/src/main/java/org/openhab/binding/hyperion/internal/protocol/ng/NgResponse.java
  bundles/org.openhab.binding.hyperion/src/main/java/org/openhab/binding/hyperion/internal/protocol/ng/Priority.java
  bundles/org.openhab.binding.hyperion/src/main/java/org/openhab/binding/hyperion/internal/protocol/ng/Session.java
  bundles/org.openhab.binding.hyperion/src/main/java/org/openhab/binding/hyperion/internal/protocol/ng/Value.java
  bundles/org.openhab.binding.hyperion/src/main/java/org/openhab/binding/hyperion/internal/protocol/v1/ActiveEffect.java
  bundles/org.openhab.binding.hyperion/src/main/java/org/openhab/binding/hyperion/internal/protocol/v1/ActiveLedColor.java
  bundles/org.openhab.binding.hyperion/src/main/java/org/openhab/binding/hyperion/internal/protocol/v1/ClearAllCommand.java
  bundles/org.openhab.binding.hyperion/src/main/java/org/openhab/binding/hyperion/internal/protocol/v1/ClearCommand.java
  bundles/org.openhab.binding.hyperion/src/main/java/org/openhab/binding/hyperion/internal/protocol/v1/Correction.java
  bundles/org.openhab.binding.hyperion/src/main/java/org/openhab/binding/hyperion/internal/protocol/v1/Effect.java
  bundles/org.openhab.binding.hyperion/src/main/java/org/openhab/binding/hyperion/internal/protocol/v1/HyperionBuild.java
  bundles/org.openhab.binding.hyperion/src/main/java/org/openhab/binding/hyperion/internal/protocol/v1/Priority.java
  bundles/org.openhab.binding.hyperion/src/main/java/org/openhab/binding/hyperion/internal/protocol/v1/Temperature.java
  bundles/org.openhab.binding.hyperion/src/main/java/org/openhab/binding/hyperion/internal/protocol/v1/Transform.java
  bundles/org.openhab.binding.hyperion/src/main/java/org/openhab/binding/hyperion/internal/protocol/v1/TransformCommand.java
  bundles/org.openhab.binding.hyperion/src/main/java/org/openhab/binding/hyperion/internal/protocol/v1/V1Info.java
  bundles/org.openhab.binding.hyperion/src/main/java/org/openhab/binding/hyperion/internal/protocol/v1/V1Response.java
  bundles/org.openhab.binding.hyperion/src/main/resources/ESH-INF/binding/binding.xml
  bundles/org.openhab.binding.hyperion/src/main/resources/ESH-INF/thing/thing-types.xml
  bundles/pom.xml
  features/karaf/openhab-addons/src/main/feature/feature.xml
Labels: infrastructure

#5103 [nibeuplink] Increase NIBE_ID_THRESHOLD
  addons/binding/org.openhab.binding.nibeuplink/src/main/java/org/openhab/binding/nibeuplink/internal/connector/UplinkWebInterface.java
Labels: enhancement

#5165 [homematic] fixed ClassCastException when parsing XMLResponse from Lightify-Devices (#5164)
  addons/binding/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/communicator/parser/GetParamsetParser.java
Labels: binding: homematic

#5170 [meteoblue] Add french translation for the weather conditions
  addons/binding/org.openhab.binding.meteoblue/ESH-INF/i18n/meteoblue_fr.properties
Labels: translation

#5121 [plclogo] Fix some timing issues in Pulse thing
  addons/binding/org.openhab.binding.plclogo/src/main/java/org/openhab/binding/plclogo/internal/PLCLogoBindingConstants.java
  addons/binding/org.openhab.binding.plclogo/src/main/java/org/openhab/binding/plclogo/internal/PLCLogoClient.java
  addons/binding/org.openhab.binding.plclogo/src/main/java/org/openhab/binding/plclogo/internal/config/PLCCommonConfiguration.java
  addons/binding/org.openhab.binding.plclogo/src/main/java/org/openhab/binding/plclogo/internal/config/PLCDigitalConfiguration.java
  addons/binding/org.openhab.binding.plclogo/src/main/java/org/openhab/binding/plclogo/internal/config/PLCLogoBridgeConfiguration.java
  addons/binding/org.openhab.binding.plclogo/src/main/java/org/openhab/binding/plclogo/internal/config/PLCMemoryConfiguration.java
  addons/binding/org.openhab.binding.plclogo/src/main/java/org/openhab/binding/plclogo/internal/config/PLCPulseConfiguration.java
  addons/binding/org.openhab.binding.plclogo/src/main/java/org/openhab/binding/plclogo/internal/handler/PLCAnalogHandler.java
  addons/binding/org.openhab.binding.plclogo/src/main/java/org/openhab/binding/plclogo/internal/handler/PLCBridgeHandler.java
  addons/binding/org.openhab.binding.plclogo/src/main/java/org/openhab/binding/plclogo/internal/handler/PLCCommonHandler.java
  addons/binding/org.openhab.binding.plclogo/src/main/java/org/openhab/binding/plclogo/internal/handler/PLCDateTimeHandler.java
  addons/binding/org.openhab.binding.plclogo/src/main/java/org/openhab/binding/plclogo/internal/handler/PLCDigitalHandler.java
  addons/binding/org.openhab.binding.plclogo/src/main/java/org/openhab/binding/plclogo/internal/handler/PLCMemoryHandler.java
  addons/binding/org.openhab.binding.plclogo/src/main/java/org/openhab/binding/plclogo/internal/handler/PLCPulseHandler.java
Labels: bug

#5071 [deconz] Added support for ZHAAlarm sensors and optional channel 'tampered'
  addons/binding/org.openhab.binding.deconz/ESH-INF/thing/thing-types.xml
  addons/binding/org.openhab.binding.deconz/README.md
  addons/binding/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/BindingConstants.java
  addons/binding/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/HandlerFactory.java
  addons/binding/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/discovery/ThingDiscoveryService.java
  addons/binding/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/dto/SensorState.java
  addons/binding/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/handler/SensorThingHandler.java
Labels: enhancement

#5198 [sensebox] Migration to bnd
  CODEOWNERS
  addons/binding/org.openhab.binding.sensebox/.classpath
  addons/binding/org.openhab.binding.sensebox/META-INF/MANIFEST.MF
  addons/binding/org.openhab.binding.sensebox/OSGI-INF/.gitignore
  addons/binding/org.openhab.binding.sensebox/build.properties
  addons/binding/pom.xml
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.sensebox/.classpath
  bundles/org.openhab.binding.sensebox/.project
  bundles/org.openhab.binding.sensebox/.settings/org.eclipse.core.resources.prefs
  bundles/org.openhab.binding.sensebox/.settings/org.eclipse.m2e.core.prefs
  bundles/org.openhab.binding.sensebox/NOTICE
  bundles/org.openhab.binding.sensebox/README.md
  bundles/org.openhab.binding.sensebox/pom.xml
  bundles/org.openhab.binding.sensebox/src/main/java/org/openhab/binding/sensebox/internal/SenseBoxAPIConnection.java
  bundles/org.openhab.binding.sensebox/src/main/java/org/openhab/binding/sensebox/internal/SenseBoxBindingConstants.java
  bundles/org.openhab.binding.sensebox/src/main/java/org/openhab/binding/sensebox/internal/SenseBoxHandlerFactory.java
  bundles/org.openhab.binding.sensebox/src/main/java/org/openhab/binding/sensebox/internal/config/SenseBoxConfiguration.java
  bundles/org.openhab.binding.sensebox/src/main/java/org/openhab/binding/sensebox/internal/handler/SenseBoxHandler.java
  bundles/org.openhab.binding.sensebox/src/main/java/org/openhab/binding/sensebox/internal/model/SenseBoxData.java
  bundles/org.openhab.binding.sensebox/src/main/java/org/openhab/binding/sensebox/internal/model/SenseBoxDescriptor.java
  bundles/org.openhab.binding.sensebox/src/main/java/org/openhab/binding/sensebox/internal/model/SenseBoxGeometry.java
  bundles/org.openhab.binding.sensebox/src/main/java/org/openhab/binding/sensebox/internal/model/SenseBoxLoc.java
  bundles/org.openhab.binding.sensebox/src/main/java/org/openhab/binding/sensebox/internal/model/SenseBoxLocation.java
  bundles/org.openhab.binding.sensebox/src/main/java/org/openhab/binding/sensebox/internal/model/SenseBoxMeasurement.java
  bundles/org.openhab.binding.sensebox/src/main/java/org/openhab/binding/sensebox/internal/model/SenseBoxSensor.java
  bundles/org.openhab.binding.sensebox/src/main/resources/ESH-INF/binding/binding.xml
  bundles/org.openhab.binding.sensebox/src/main/resources/ESH-INF/config/config-description.xml
  bundles/org.openhab.binding.sensebox/src/main/resources/ESH-INF/thing/box.xml
  bundles/org.openhab.binding.sensebox/src/main/resources/ESH-INF/thing/channels.xml
  bundles/pom.xml
  features/karaf/openhab-addons/src/main/feature/feature.xml
Labels: infrastructure

#5171 Update .travis.yml
  .travis.yml
Labels: infrastructure

#5137 [onkyo] Added explanation about usage of callback URL
  addons/binding/org.openhab.binding.onkyo/README.md
Labels: documentation

#5156 [mqtt] Have a working Group Id
  addons/binding/org.openhab.binding.mqtt.generic.test/src/test/java/org/openhab/binding/mqtt/generic/HomeAssistantMQTTImplementationTests.java
  addons/binding/org.openhab.binding.mqtt.generic.test/src/test/java/org/openhab/binding/mqtt/generic/internal/convention/homeassistant/DiscoverComponentsTests.java
  addons/binding/org.openhab.binding.mqtt.generic.test/src/test/java/org/openhab/binding/mqtt/generic/internal/convention/homeassistant/HaIDTests.java
  addons/binding/org.openhab.binding.mqtt.generic/ESH-INF/config/homeassistant-channel-config.xml
  addons/binding/org.openhab.binding.mqtt.generic/README.md
  addons/binding/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/internal/convention/homeassistant/AbstractComponent.java
  addons/binding/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/internal/convention/homeassistant/CChannel.java
  addons/binding/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/internal/convention/homeassistant/CFactory.java
  addons/binding/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/internal/convention/homeassistant/DiscoverComponents.java
  addons/binding/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/internal/convention/homeassistant/HaID.java
  addons/binding/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/internal/convention/homeassistant/HandlerConfiguration.java
  addons/binding/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/internal/discovery/HomeAssistantDiscovery.java
  addons/binding/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/internal/handler/HomeAssistantThingHandler.java
Labels: binding: mqtt

#5187 [valloxmv] Migration to bnd
  CODEOWNERS
  addons/binding/org.openhab.binding.valloxmv/.classpath
  addons/binding/org.openhab.binding.valloxmv/META-INF/MANIFEST.MF
  addons/binding/org.openhab.binding.valloxmv/OSGI-INF/.gitignore
  addons/binding/pom.xml
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.valloxmv/.classpath
  bundles/org.openhab.binding.valloxmv/.project
  bundles/org.openhab.binding.valloxmv/.settings/org.eclipse.core.resources.prefs
  bundles/org.openhab.binding.valloxmv/.settings/org.eclipse.m2e.core.prefs
  bundles/org.openhab.binding.valloxmv/NOTICE
  bundles/org.openhab.binding.valloxmv/README.md
  bundles/org.openhab.binding.valloxmv/README_DEV.md
  bundles/org.openhab.binding.valloxmv/build.properties
  bundles/org.openhab.binding.valloxmv/pom.xml
  bundles/org.openhab.binding.valloxmv/src/main/java/org/openhab/binding/valloxmv/internal/ValloxMVBindingConstants.java
  bundles/org.openhab.binding.valloxmv/src/main/java/org/openhab/binding/valloxmv/internal/ValloxMVConfig.java
  bundles/org.openhab.binding.valloxmv/src/main/java/org/openhab/binding/valloxmv/internal/ValloxMVHandler.java
  bundles/org.openhab.binding.valloxmv/src/main/java/org/openhab/binding/valloxmv/internal/ValloxMVHandlerFactory.java
  bundles/org.openhab.binding.valloxmv/src/main/java/org/openhab/binding/valloxmv/internal/ValloxMVWebSocket.java
  bundles/org.openhab.binding.valloxmv/src/main/ressources/ESH-INF/binding/binding.xml
  bundles/org.openhab.binding.valloxmv/src/main/ressources/ESH-INF/i18n/valloxmv_de.properties
  bundles/org.openhab.binding.valloxmv/src/main/ressources/ESH-INF/thing/thing-types.xml
  bundles/pom.xml
  features/karaf/openhab-addons/src/main/feature/feature.xml
Labels: infrastructure

#5179 [hdanywhere] Migrate to bnd build
  CODEOWNERS
  addons/binding/org.openhab.binding.hdanywhere/.classpath
  addons/binding/org.openhab.binding.hdanywhere/META-INF/MANIFEST.MF
  addons/binding/org.openhab.binding.hdanywhere/OSGI-INF/.gitignore
  addons/binding/org.openhab.binding.hdanywhere/build.properties
  addons/binding/org.openhab.binding.hdanywhere/pom.xml
  addons/binding/pom.xml
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.hdanywhere/.classpath
  bundles/org.openhab.binding.hdanywhere/.project
  bundles/org.openhab.binding.hdanywhere/.settings/org.eclipse.core.resources.prefs
  bundles/org.openhab.binding.hdanywhere/.settings/org.eclipse.m2e.core.prefs
  bundles/org.openhab.binding.hdanywhere/NOTICE
  bundles/org.openhab.binding.hdanywhere/README.md
  bundles/org.openhab.binding.hdanywhere/pom.xml
  bundles/org.openhab.binding.hdanywhere/src/main/java/org/openhab/binding/hdanywhere/internal/HDanywhereBindingConstants.java
  bundles/org.openhab.binding.hdanywhere/src/main/java/org/openhab/binding/hdanywhere/internal/HDanywhereHandlerFactory.java
  bundles/org.openhab.binding.hdanywhere/src/main/java/org/openhab/binding/hdanywhere/internal/handler/Mhub4K431Handler.java
  bundles/org.openhab.binding.hdanywhere/src/main/java/org/openhab/binding/hdanywhere/internal/handler/MultiroomPlusHandler.java
  bundles/org.openhab.binding.hdanywhere/src/main/resources/ESH-INF/binding/binding.xml
  bundles/org.openhab.binding.hdanywhere/src/main/resources/ESH-INF/thing/mhub4k431.xml
  bundles/org.openhab.binding.hdanywhere/src/main/resources/ESH-INF/thing/multiroomplus.xml
  bundles/pom.xml
  features/karaf/openhab-addons/src/main/feature/feature.xml
Labels: infrastructure

#5117 [allplay] migrate to bnd
  CODEOWNERS
  addons/binding/org.openhab.binding.allplay/.classpath
  addons/binding/org.openhab.binding.allplay/META-INF/MANIFEST.MF
  addons/binding/org.openhab.binding.allplay/OSGI-INF/.gitignore
  addons/binding/org.openhab.binding.allplay/build.properties
  addons/binding/org.openhab.binding.allplay/lib/x86-64/win/alljoyn_java.dll
  addons/binding/org.openhab.binding.allplay/lib/x86/win/alljoyn_java.dll
  addons/binding/org.openhab.binding.allplay/pom.xml
  addons/binding/pom.xml
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.allplay/.classpath
  bundles/org.openhab.binding.allplay/.project
  bundles/org.openhab.binding.allplay/.settings/org.eclipse.core.resources.prefs
  bundles/org.openhab.binding.allplay/.settings/org.eclipse.m2e.core.prefs
  bundles/org.openhab.binding.allplay/NOTICE
  bundles/org.openhab.binding.allplay/README.md
  bundles/org.openhab.binding.allplay/lib/tchaikovsky-sources.jar
  bundles/org.openhab.binding.allplay/lib/tchaikovsky.jar
  bundles/org.openhab.binding.allplay/pom.xml
  bundles/org.openhab.binding.allplay/src/main/java/org/openhab/binding/allplay/internal/AllPlayAudioSink.java
  bundles/org.openhab.binding.allplay/src/main/java/org/openhab/binding/allplay/internal/AllPlayBindingConstants.java
  bundles/org.openhab.binding.allplay/src/main/java/org/openhab/binding/allplay/internal/AllPlayBindingProperties.java
  bundles/org.openhab.binding.allplay/src/main/java/org/openhab/binding/allplay/internal/AllPlayHandlerFactory.java
  bundles/org.openhab.binding.allplay/src/main/java/org/openhab/binding/allplay/internal/discovery/AllPlaySpeakerDiscoveryService.java
  bundles/org.openhab.binding.allplay/src/main/java/org/openhab/binding/allplay/internal/handler/AllPlayHandler.java
  bundles/org.openhab.binding.allplay/src/main/resources/ESH-INF/binding/binding.xml
  bundles/org.openhab.binding.allplay/src/main/resources/ESH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.allplay/src/main/resources/lib/arm/linux/liballjoyn_java.so
  bundles/org.openhab.binding.allplay/src/main/resources/lib/x86-64/linux/liballjoyn_java.so
  bundles/org.openhab.binding.allplay/src/main/resources/lib/x86/linux/liballjoyn_java.so
  bundles/pom.xml
  features/karaf/openhab-addons/src/main/feature/feature.xml
Labels: infrastructure

#5211 Rework add-libraries profile for CLI and Eclipse
  poms/bnd/pom.xml
Labels: bug, infrastructure

#5197 Moved Kodi Binding to bnd
  CODEOWNERS
  addons/binding/org.openhab.binding.kodi/.classpath
  addons/binding/org.openhab.binding.kodi/META-INF/MANIFEST.MF
  addons/binding/org.openhab.binding.kodi/OSGI-INF/.gitignore
  addons/binding/org.openhab.binding.kodi/build.properties
  addons/binding/pom.xml
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.kodi/.classpath
  bundles/org.openhab.binding.kodi/.project
  bundles/org.openhab.binding.kodi/.settings/org.eclipse.core.resources.prefs
  bundles/org.openhab.binding.kodi/.settings/org.eclipse.m2e.core.prefs
  bundles/org.openhab.binding.kodi/NOTICE
  bundles/org.openhab.binding.kodi/README.md
  bundles/org.openhab.binding.kodi/pom.xml
  bundles/org.openhab.binding.kodi/src/main/java/org/openhab/binding/kodi/internal/KodiAudioSink.java
  bundles/org.openhab.binding.kodi/src/main/java/org/openhab/binding/kodi/internal/KodiBindingConstants.java
  bundles/org.openhab.binding.kodi/src/main/java/org/openhab/binding/kodi/internal/KodiDynamicStateDescriptionProvider.java
  bundles/org.openhab.binding.kodi/src/main/java/org/openhab/binding/kodi/internal/KodiEventListener.java
  bundles/org.openhab.binding.kodi/src/main/java/org/openhab/binding/kodi/internal/KodiHandlerFactory.java
  bundles/org.openhab.binding.kodi/src/main/java/org/openhab/binding/kodi/internal/KodiPlayerState.java
  bundles/org.openhab.binding.kodi/src/main/java/org/openhab/binding/kodi/internal/config/KodiChannelConfig.java
  bundles/org.openhab.binding.kodi/src/main/java/org/openhab/binding/kodi/internal/config/KodiConfig.java
  bundles/org.openhab.binding.kodi/src/main/java/org/openhab/binding/kodi/internal/discovery/KodiUpnpDiscoveryParticipant.java
  bundles/org.openhab.binding.kodi/src/main/java/org/openhab/binding/kodi/internal/handler/KodiHandler.java
  bundles/org.openhab.binding.kodi/src/main/java/org/openhab/binding/kodi/internal/model/KodiAudioStream.java
  bundles/org.openhab.binding.kodi/src/main/java/org/openhab/binding/kodi/internal/model/KodiBaseItem.java
  bundles/org.openhab.binding.kodi/src/main/java/org/openhab/binding/kodi/internal/model/KodiDuration.java
  bundles/org.openhab.binding.kodi/src/main/java/org/openhab/binding/kodi/internal/model/KodiFavorite.java
  bundles/org.openhab.binding.kodi/src/main/java/org/openhab/binding/kodi/internal/model/KodiPVRChannel.java
  bundles/org.openhab.binding.kodi/src/main/java/org/openhab/binding/kodi/internal/model/KodiPVRChannelGroup.java
  bundles/org.openhab.binding.kodi/src/main/java/org/openhab/binding/kodi/internal/model/KodiSystemProperties.java
  bundles/org.openhab.binding.kodi/src/main/java/org/openhab/binding/kodi/internal/model/KodiVideoStream.java
  bundles/org.openhab.binding.kodi/src/main/java/org/openhab/binding/kodi/internal/protocol/KodiClientSocket.java
  bundles/org.openhab.binding.kodi/src/main/java/org/openhab/binding/kodi/internal/protocol/KodiClientSocketEventListener.java
  bundles/org.openhab.binding.kodi/src/main/java/org/openhab/binding/kodi/internal/protocol/KodiConnection.java
  bundles/org.openhab.binding.kodi/src/main/java/org/openhab/binding/kodi/internal/utils/ByteArrayFileCache.java
  bundles/org.openhab.binding.kodi/src/main/resources/ESH-INF/binding/binding.xml
  bundles/org.openhab.binding.kodi/src/main/resources/ESH-INF/config/config.xml
  bundles/org.openhab.binding.kodi/src/main/resources/ESH-INF/i18n/kodi_de.properties
  bundles/org.openhab.binding.kodi/src/main/resources/ESH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.kodi/src/test/java/org/openhab/binding/kodi/internal/utils/ByteArrayFileCacheTest.java
  bundles/org.openhab.binding.kodi/src/test/resources/sounds/doorbell.mp3
  bundles/pom.xml
  features/karaf/openhab-addons/src/main/feature/feature.xml
Labels: infrastructure

#5220 [lifx] Fix discovery possibly blocked after exception
  bundles/org.openhab.binding.lifx/src/main/java/org/openhab/binding/lifx/internal/LifxLightDiscovery.java
Labels: bug

#5216 Update .gitignore
  .gitignore
Labels: infrastructure

#5223 Moved deCONZ Binding to new build system
  CODEOWNERS
  addons/binding/org.openhab.binding.deconz/.classpath
  addons/binding/org.openhab.binding.deconz/ESH-INF/i18n/deconz_de.properties
  addons/binding/org.openhab.binding.deconz/META-INF/MANIFEST.MF
  addons/binding/org.openhab.binding.deconz/OSGI-INF/.gitignore
  addons/binding/org.openhab.binding.deconz/build.properties
  addons/binding/pom.xml
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.deconz/.classpath
  bundles/org.openhab.binding.deconz/.project
  bundles/org.openhab.binding.deconz/.settings/org.eclipse.core.resources.prefs
  bundles/org.openhab.binding.deconz/.settings/org.eclipse.m2e.core.prefs
  bundles/org.openhab.binding.deconz/NOTICE
  bundles/org.openhab.binding.deconz/README.md
  bundles/org.openhab.binding.deconz/pom.xml
  bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/BindingConstants.java
  bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/HandlerFactory.java
  bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/discovery/BridgeDiscoveryParticipant.java
  bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/discovery/ThingDiscoveryService.java
  bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/dto/ApiKeyMessage.java
  bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/dto/BridgeFullState.java
  bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/dto/SensorConfig.java
  bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/dto/SensorMessage.java
  bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/dto/SensorState.java
  bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/handler/DeconzBridgeConfig.java
  bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/handler/DeconzBridgeHandler.java
  bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/handler/SensorThingConfig.java
  bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/handler/SensorThingHandler.java
  bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/netutils/AsyncHttpClient.java
  bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/netutils/ValueUpdateListener.java
  bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/netutils/WebSocketConnection.java
  bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/netutils/WebSocketConnectionListener.java
  bundles/org.openhab.binding.deconz/src/main/resources/ESH-INF/binding/binding.xml
  bundles/org.openhab.binding.deconz/src/main/resources/ESH-INF/i18n/deconz_de.properties
  bundles/org.openhab.binding.deconz/src/main/resources/ESH-INF/thing/thing-types.xml
  bundles/pom.xml
  features/karaf/openhab-addons/src/main/feature/feature.xml
Labels: infrastructure

#5219 [googletts] Migrate to bnd build
  CODEOWNERS
  addons/voice/org.openhab.voice.googletts/.classpath
  addons/voice/org.openhab.voice.googletts/META-INF/MANIFEST.MF
  addons/voice/org.openhab.voice.googletts/OSGI-INF/.gitignore
  addons/voice/org.openhab.voice.googletts/build.properties
  addons/voice/org.openhab.voice.googletts/lib/api-common-1.7.0.jar
  addons/voice/org.openhab.voice.googletts/lib/gax-1.32.0.jar
  addons/voice/org.openhab.voice.googletts/lib/google-auth-library-credentials-0.11.0.jar
  addons/voice/org.openhab.voice.googletts/lib/google-auth-library-oauth2-http-0.11.0.jar
  addons/voice/org.openhab.voice.googletts/lib/google-http-client-1.24.1.jar
  addons/voice/org.openhab.voice.googletts/lib/google-http-client-jackson2-1.24.1.jar
  addons/voice/org.openhab.voice.googletts/lib/guava-20.0.jar
  addons/voice/org.openhab.voice.googletts/lib/jackson-core-2.9.2.jar
  addons/voice/org.openhab.voice.googletts/lib/threetenbp-1.3.3.jar
  addons/voice/org.openhab.voice.googletts/pom.xml
  addons/voice/pom.xml
  bom/openhab-addons/pom.xml
  bundles/org.openhab.voice.googletts/.classpath
  bundles/org.openhab.voice.googletts/.project
  bundles/org.openhab.voice.googletts/.settings/org.eclipse.core.resources.prefs
  bundles/org.openhab.voice.googletts/.settings/org.eclipse.m2e.core.prefs
  bundles/org.openhab.voice.googletts/NOTICE
  bundles/org.openhab.voice.googletts/README.md
  bundles/org.openhab.voice.googletts/pom.xml
  bundles/org.openhab.voice.googletts/src/main/java/org/openhab/voice/googletts/internal/GoogleCloudAPI.java
  bundles/org.openhab.voice.googletts/src/main/java/org/openhab/voice/googletts/internal/GoogleTTSConfig.java
  bundles/org.openhab.voice.googletts/src/main/java/org/openhab/voice/googletts/internal/GoogleTTSService.java
  bundles/org.openhab.voice.googletts/src/main/java/org/openhab/voice/googletts/internal/GoogleTTSVoice.java
  bundles/org.openhab.voice.googletts/src/main/java/org/openhab/voice/googletts/internal/protocol/AudioConfig.java
  bundles/org.openhab.voice.googletts/src/main/java/org/openhab/voice/googletts/internal/protocol/AudioEncoding.java
  bundles/org.openhab.voice.googletts/src/main/java/org/openhab/voice/googletts/internal/protocol/ListVoicesResponse.java
  bundles/org.openhab.voice.googletts/src/main/java/org/openhab/voice/googletts/internal/protocol/SsmlVoiceGender.java
  bundles/org.openhab.voice.googletts/src/main/java/org/openhab/voice/googletts/internal/protocol/SynthesisInput.java
  bundles/org.openhab.voice.googletts/src/main/java/org/openhab/voice/googletts/internal/protocol/SynthesizeSpeechRequest.java
  bundles/org.openhab.voice.googletts/src/main/java/org/openhab/voice/googletts/internal/protocol/SynthesizeSpeechResponse.java
  bundles/org.openhab.voice.googletts/src/main/java/org/openhab/voice/googletts/internal/protocol/Voice.java
  bundles/org.openhab.voice.googletts/src/main/java/org/openhab/voice/googletts/internal/protocol/VoiceSelectionParams.java
  bundles/org.openhab.voice.googletts/src/main/resources/ESH-INF/config/config.xml
  bundles/pom.xml
  features/karaf/openhab-addons/src/main/feature/feature.xml
Labels: infrastructure

#5129 migrate amazondashbutton to bnd
  addons/binding/org.openhab.binding.amazondashbutton/.classpath
  addons/binding/org.openhab.binding.amazondashbutton/META-INF/MANIFEST.MF
  addons/binding/org.openhab.binding.amazondashbutton/OSGI-INF/.gitignore
  addons/binding/org.openhab.binding.amazondashbutton/build.properties
  addons/binding/org.openhab.binding.amazondashbutton/lib/jna-4.2.1.jar
  addons/binding/org.openhab.binding.amazondashbutton/lib/pcap4j-core-1.6.6.jar
  addons/binding/org.openhab.binding.amazondashbutton/lib/pcap4j-packetfactory-static-1.6.6.jar
  addons/binding/org.openhab.binding.amazondashbutton/pom.xml
  addons/binding/pom.xml
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.amazondashbutton/.classpath
  bundles/org.openhab.binding.amazondashbutton/.project
  bundles/org.openhab.binding.amazondashbutton/.settings/org.eclipse.core.resources.prefs
  bundles/org.openhab.binding.amazondashbutton/.settings/org.eclipse.m2e.core.prefs
  bundles/org.openhab.binding.amazondashbutton/NOTICE
  bundles/org.openhab.binding.amazondashbutton/README.md
  bundles/org.openhab.binding.amazondashbutton/pom.xml
  bundles/org.openhab.binding.amazondashbutton/src/main/java/org/openhab/binding/amazondashbutton/internal/AmazonDashButtonBindingConstants.java
  bundles/org.openhab.binding.amazondashbutton/src/main/java/org/openhab/binding/amazondashbutton/internal/AmazonDashButtonHandlerFactory.java
  bundles/org.openhab.binding.amazondashbutton/src/main/java/org/openhab/binding/amazondashbutton/internal/capturing/PacketCapturingHandler.java
  bundles/org.openhab.binding.amazondashbutton/src/main/java/org/openhab/binding/amazondashbutton/internal/capturing/PacketCapturingService.java
  bundles/org.openhab.binding.amazondashbutton/src/main/java/org/openhab/binding/amazondashbutton/internal/config/AmazonDashButtonConfig.java
  bundles/org.openhab.binding.amazondashbutton/src/main/java/org/openhab/binding/amazondashbutton/internal/config/AmazonDashButtonConfigOptionProvider.java
  bundles/org.openhab.binding.amazondashbutton/src/main/java/org/openhab/binding/amazondashbutton/internal/discovery/AmazonDashButtonDiscoveryService.java
  bundles/org.openhab.binding.amazondashbutton/src/main/java/org/openhab/binding/amazondashbutton/internal/handler/AmazonDashButtonHandler.java
  bundles/org.openhab.binding.amazondashbutton/src/main/java/org/openhab/binding/amazondashbutton/internal/pcap/PcapNetworkInterfaceListener.java
  bundles/org.openhab.binding.amazondashbutton/src/main/java/org/openhab/binding/amazondashbutton/internal/pcap/PcapNetworkInterfaceService.java
  bundles/org.openhab.binding.amazondashbutton/src/main/java/org/openhab/binding/amazondashbutton/internal/pcap/PcapNetworkInterfaceWrapper.java
  bundles/org.openhab.binding.amazondashbutton/src/main/java/org/openhab/binding/amazondashbutton/internal/pcap/PcapUtil.java
  bundles/org.openhab.binding.amazondashbutton/src/main/resources/ESH-INF/binding/binding.xml
  bundles/org.openhab.binding.amazondashbutton/src/main/resources/ESH-INF/i18n/amazondashbutton.properties
  bundles/org.openhab.binding.amazondashbutton/src/main/resources/ESH-INF/i18n/amazondashbutton_de.properties
  bundles/org.openhab.binding.amazondashbutton/src/main/resources/ESH-INF/thing/thing-types.xml
  bundles/pom.xml
  features/karaf/openhab-addons/src/main/feature/feature.xml
Labels: discussion, infrastructure

#5060 Fix running mvn license:format on tycho pom.
  licenses/epl-2.0/header.txt
  licenses/epl-2.0/xml-header-style.xml
  poms/tycho/pom.xml
Labels: infrastructure, work in progress

#5225 [deconz] Added support for ZHAVibration sensors
  bundles/org.openhab.binding.deconz/README.md
  bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/BindingConstants.java
  bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/HandlerFactory.java
  bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/discovery/ThingDiscoveryService.java
  bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/handler/SensorThingHandler.java
  bundles/org.openhab.binding.deconz/src/main/resources/ESH-INF/config/config.xml
  bundles/org.openhab.binding.deconz/src/main/resources/ESH-INF/thing/thing-types.xml
Labels: enhancement

#5163 [dlinksmarthome] migrate to bnd
  CODEOWNERS
  addons/binding/org.openhab.binding.dlinksmarthome/.classpath
  addons/binding/org.openhab.binding.dlinksmarthome/META-INF/MANIFEST.MF
  addons/binding/org.openhab.binding.dlinksmarthome/OSGI-INF/.gitignore
  addons/binding/org.openhab.binding.dlinksmarthome/build.properties
  addons/binding/org.openhab.binding.dlinksmarthome/pom.xml
  addons/binding/pom.xml
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.dlinksmarthome/.classpath
  bundles/org.openhab.binding.dlinksmarthome/.project
  bundles/org.openhab.binding.dlinksmarthome/.settings/org.eclipse.core.resources.prefs
  bundles/org.openhab.binding.dlinksmarthome/.settings/org.eclipse.m2e.core.prefs
  bundles/org.openhab.binding.dlinksmarthome/NOTICE
  bundles/org.openhab.binding.dlinksmarthome/README.md
  bundles/org.openhab.binding.dlinksmarthome/pom.xml
  bundles/org.openhab.binding.dlinksmarthome/src/main/java/org/openhab/binding/dlinksmarthome/internal/DLinkHNAPCommunication.java
  bundles/org.openhab.binding.dlinksmarthome/src/main/java/org/openhab/binding/dlinksmarthome/internal/DLinkSmartHomeBindingConstants.java
  bundles/org.openhab.binding.dlinksmarthome/src/main/java/org/openhab/binding/dlinksmarthome/internal/DLinkSmartHomeDiscoveryParticipant.java
  bundles/org.openhab.binding.dlinksmarthome/src/main/java/org/openhab/binding/dlinksmarthome/internal/DLinkSmartHomeHandlerFactory.java
  bundles/org.openhab.binding.dlinksmarthome/src/main/java/org/openhab/binding/dlinksmarthome/internal/handler/DLinkMotionSensorHandler.java
  bundles/org.openhab.binding.dlinksmarthome/src/main/java/org/openhab/binding/dlinksmarthome/internal/motionsensor/DLinkMotionSensorCommunication.java
  bundles/org.openhab.binding.dlinksmarthome/src/main/java/org/openhab/binding/dlinksmarthome/internal/motionsensor/DLinkMotionSensorConfig.java
  bundles/org.openhab.binding.dlinksmarthome/src/main/java/org/openhab/binding/dlinksmarthome/internal/motionsensor/DLinkMotionSensorListener.java
  bundles/org.openhab.binding.dlinksmarthome/src/main/resources/ESH-INF/binding/binding.xml
  bundles/org.openhab.binding.dlinksmarthome/src/main/resources/ESH-INF/thing/thing-types.xml
  bundles/pom.xml
  features/karaf/openhab-addons/src/main/feature/feature.xml
Labels: infrastructure

#4920 [homekit] Fix Eclipse warnings and reduce bogus logger ERRORs to DEBUGs.
  addons/io/org.openhab.io.homekit/META-INF/MANIFEST.MF
  addons/io/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitAccessoryRegistry.java
  addons/io/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitAccessoryUpdater.java
Labels: io: homekit

#3722 [mcp23017] New Feature "active_low" or "invert logic"
  addons/binding/org.openhab.binding.mcp23017/README.md
  addons/binding/org.openhab.binding.mcp23017/src/main/java/org/openhab/binding/mcp23017/internal/Mcp23017BindingConstants.java
  addons/binding/org.openhab.binding.mcp23017/src/main/java/org/openhab/binding/mcp23017/internal/handler/Mcp23017Handler.java
Labels: awaiting feedback

#5256 enable SAT for bindings using BND build
  poms/bnd/pom.xml
  tools/checkstyle/ruleset.properties
  tools/checkstyle/suppressions.xml
Labels: infrastructure

#5254 Moved Daikin Binding to bnd
  CODEOWNERS
  addons/binding/org.openhab.binding.daikin/.classpath
  addons/binding/org.openhab.binding.daikin/META-INF/MANIFEST.MF
  addons/binding/org.openhab.binding.daikin/OSGI-INF/.gitignore
  addons/binding/org.openhab.binding.daikin/build.properties
  addons/binding/pom.xml
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.daikin/.classpath
  bundles/org.openhab.binding.daikin/.project
  bundles/org.openhab.binding.daikin/NOTICE
  bundles/org.openhab.binding.daikin/README.md
  bundles/org.openhab.binding.daikin/pom.xml
  bundles/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/DaikinBindingConstants.java
  bundles/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/DaikinCommunicationException.java
  bundles/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/DaikinHandlerFactory.java
  bundles/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/DaikinWebTargets.java
  bundles/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/api/ControlInfo.java
  bundles/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/api/Enums.java
  bundles/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/api/SensorInfo.java
  bundles/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/config/DaikinConfiguration.java
  bundles/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/discovery/DaikinACUnitDiscoveryService.java
  bundles/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/handler/DaikinAcUnitHandler.java
  bundles/org.openhab.binding.daikin/src/main/resources/ESH-INF/binding/binding.xml
  bundles/org.openhab.binding.daikin/src/main/resources/ESH-INF/thing/thing-types.xml
  bundles/pom.xml
  features/karaf/openhab-addons/src/main/feature/feature.xml
Labels: infrastructure

#5118 [ihc] bug fix related to pulse command
  addons/binding/org.openhab.binding.ihc.test/src/test/java/org/openhab/binding/ihc/internal/converters/DateTimeTypeWSDateValueConverterTest.java
  addons/binding/org.openhab.binding.ihc.test/src/test/java/org/openhab/binding/ihc/internal/converters/DateTimeTypeWSTimeValueConverterTest.java
  addons/binding/org.openhab.binding.ihc.test/src/test/java/org/openhab/binding/ihc/internal/converters/DecimalTypeWSBooleanValueConverterTest.java
  addons/binding/org.openhab.binding.ihc.test/src/test/java/org/openhab/binding/ihc/internal/converters/DecimalTypeWSEnumValueConverterTest.java
  addons/binding/org.openhab.binding.ihc.test/src/test/java/org/openhab/binding/ihc/internal/converters/DecimalTypeWSFloatingPointValueConverterTest.java
  addons/binding/org.openhab.binding.ihc.test/src/test/java/org/openhab/binding/ihc/internal/converters/DecimalTypeWSIntegerValueConverterTest.java
  addons/binding/org.openhab.binding.ihc.test/src/test/java/org/openhab/binding/ihc/internal/converters/DecimalTypeWSTimerValueConverterTest.java
  addons/binding/org.openhab.binding.ihc.test/src/test/java/org/openhab/binding/ihc/internal/converters/DecimalTypeWSWeekdayValueConverterTest.java
  addons/binding/org.openhab.binding.ihc.test/src/test/java/org/openhab/binding/ihc/internal/converters/OnOffTypeWSBooleanValueConverterTest.java
  addons/binding/org.openhab.binding.ihc.test/src/test/java/org/openhab/binding/ihc/internal/converters/OnOffTypeWSIntegerValueConverterTest.java
  addons/binding/org.openhab.binding.ihc.test/src/test/java/org/openhab/binding/ihc/internal/converters/OpenClosedTypeWSBooleanValueConverterTest.java
  addons/binding/org.openhab.binding.ihc.test/src/test/java/org/openhab/binding/ihc/internal/converters/OpenClosedTypeWSIntegerValueConverterTest.java
  addons/binding/org.openhab.binding.ihc.test/src/test/java/org/openhab/binding/ihc/internal/converters/PercentTypeWSIntegerValueConverterTest.java
  addons/binding/org.openhab.binding.ihc.test/src/test/java/org/openhab/binding/ihc/internal/converters/StringTypeWSEnumValueConverterTest.java
  addons/binding/org.openhab.binding.ihc.test/src/test/java/org/openhab/binding/ihc/internal/converters/UpDownTypeWSBooleanValueConverterTest.java
  addons/binding/org.openhab.binding.ihc.test/src/test/java/org/openhab/binding/ihc/internal/converters/UpDownTypeWSIntegerValueConverterTest.java
  addons/binding/org.openhab.binding.ihc.test/src/test/java/org/openhab/binding/ihc/internal/ws/services/IhcResourceInteractionServiceTest.java
  addons/binding/org.openhab.binding.ihc/src/main/java/org/openhab/binding/ihc/internal/converters/DateTimeTypeWSDateValueConverter.java
  addons/binding/org.openhab.binding.ihc/src/main/java/org/openhab/binding/ihc/internal/converters/DateTimeTypeWSTimeValueConverter.java
  addons/binding/org.openhab.binding.ihc/src/main/java/org/openhab/binding/ihc/internal/converters/DecimalTypeWSBooleanValueConverter.java
  addons/binding/org.openhab.binding.ihc/src/main/java/org/openhab/binding/ihc/internal/converters/DecimalTypeWSEnumValueConverter.java
  addons/binding/org.openhab.binding.ihc/src/main/java/org/openhab/binding/ihc/internal/converters/DecimalTypeWSFloatingPointValueConverter.java
  addons/binding/org.openhab.binding.ihc/src/main/java/org/openhab/binding/ihc/internal/converters/DecimalTypeWSIntegerValueConverter.java
  addons/binding/org.openhab.binding.ihc/src/main/java/org/openhab/binding/ihc/internal/converters/DecimalTypeWSTimerValueConverter.java
  addons/binding/org.openhab.binding.ihc/src/main/java/org/openhab/binding/ihc/internal/converters/DecimalTypeWSWeekdayValueConverter.java
  addons/binding/org.openhab.binding.ihc/src/main/java/org/openhab/binding/ihc/internal/converters/OnOffTypeWSBooleanValueConverter.java
  addons/binding/org.openhab.binding.ihc/src/main/java/org/openhab/binding/ihc/internal/converters/OnOffTypeWSIntegerValueConverter.java
  addons/binding/org.openhab.binding.ihc/src/main/java/org/openhab/binding/ihc/internal/converters/OpenClosedTypeWSBooleanValueConverter.java
  addons/binding/org.openhab.binding.ihc/src/main/java/org/openhab/binding/ihc/internal/converters/OpenClosedTypeWSIntegerValueConverter.java
  addons/binding/org.openhab.binding.ihc/src/main/java/org/openhab/binding/ihc/internal/converters/PercentTypeWSIntegerValueConverter.java
  addons/binding/org.openhab.binding.ihc/src/main/java/org/openhab/binding/ihc/internal/converters/StringTypeWSEnumValueConverter.java
  addons/binding/org.openhab.binding.ihc/src/main/java/org/openhab/binding/ihc/internal/converters/UpDownTypeWSBooleanValueConverter.java
  addons/binding/org.openhab.binding.ihc/src/main/java/org/openhab/binding/ihc/internal/converters/UpDownTypeWSIntegerValueConverter.java
  addons/binding/org.openhab.binding.ihc/src/main/java/org/openhab/binding/ihc/internal/handler/IhcHandler.java
  addons/binding/org.openhab.binding.ihc/src/main/java/org/openhab/binding/ihc/internal/ws/IhcClient.java
  addons/binding/org.openhab.binding.ihc/src/main/java/org/openhab/binding/ihc/internal/ws/resourcevalues/WSBooleanValue.java
  addons/binding/org.openhab.binding.ihc/src/main/java/org/openhab/binding/ihc/internal/ws/resourcevalues/WSDateValue.java
  addons/binding/org.openhab.binding.ihc/src/main/java/org/openhab/binding/ihc/internal/ws/resourcevalues/WSEnumValue.java
  addons/binding/org.openhab.binding.ihc/src/main/java/org/openhab/binding/ihc/internal/ws/resourcevalues/WSFloatingPointValue.java
  addons/binding/org.openhab.binding.ihc/src/main/java/org/openhab/binding/ihc/internal/ws/resourcevalues/WSIntegerValue.java
  addons/binding/org.openhab.binding.ihc/src/main/java/org/openhab/binding/ihc/internal/ws/resourcevalues/WSPhoneNumberValue.java
  addons/binding/org.openhab.binding.ihc/src/main/java/org/openhab/binding/ihc/internal/ws/resourcevalues/WSResourceValue.java
  addons/binding/org.openhab.binding.ihc/src/main/java/org/openhab/binding/ihc/internal/ws/resourcevalues/WSSceneDimmerValue.java
  addons/binding/org.openhab.binding.ihc/src/main/java/org/openhab/binding/ihc/internal/ws/resourcevalues/WSSceneRelayValue.java
  addons/binding/org.openhab.binding.ihc/src/main/java/org/openhab/binding/ihc/internal/ws/resourcevalues/WSSceneShutterSimpleValue.java
  addons/binding/org.openhab.binding.ihc/src/main/java/org/openhab/binding/ihc/internal/ws/resourcevalues/WSTimeValue.java
  addons/binding/org.openhab.binding.ihc/src/main/java/org/openhab/binding/ihc/internal/ws/resourcevalues/WSTimerValue.java
  addons/binding/org.openhab.binding.ihc/src/main/java/org/openhab/binding/ihc/internal/ws/resourcevalues/WSWeekdayValue.java
  addons/binding/org.openhab.binding.ihc/src/main/java/org/openhab/binding/ihc/internal/ws/services/IhcResourceInteractionService.java
Labels: bug, work in progress

#5182 migrate helios binding to bnd
  CODEOWNERS
  addons/binding/org.openhab.binding.helios/.classpath
  addons/binding/org.openhab.binding.helios/META-INF/MANIFEST.MF
  addons/binding/org.openhab.binding.helios/OSGI-INF/.gitignore
  addons/binding/org.openhab.binding.helios/build.properties
  addons/binding/org.openhab.binding.helios/lib/cxf-core-3.1.0-SNAPSHOT.jar
  addons/binding/org.openhab.binding.helios/lib/cxf-services-wsn-api-3.1.0-SNAPSHOT.jar
  addons/binding/org.openhab.binding.helios/lib/cxf-services-wsn-core-3.1.0-SNAPSHOT.jar
  addons/binding/org.openhab.binding.helios/pom.xml
  addons/binding/pom.xml
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.helios/.classpath
  bundles/org.openhab.binding.helios/.project
  bundles/org.openhab.binding.helios/.settings/org.eclipse.core.resources.prefs
  bundles/org.openhab.binding.helios/.settings/org.eclipse.m2e.core.prefs
  bundles/org.openhab.binding.helios/NOTICE
  bundles/org.openhab.binding.helios/README.md
  bundles/org.openhab.binding.helios/pom.xml
  bundles/org.openhab.binding.helios/src/main/java/org/openhab/binding/helios/internal/HeliosBindingConstants.java
  bundles/org.openhab.binding.helios/src/main/java/org/openhab/binding/helios/internal/HeliosHandlerFactory.java
  bundles/org.openhab.binding.helios/src/main/java/org/openhab/binding/helios/internal/handler/HeliosHandler221.java
  bundles/org.openhab.binding.helios/src/main/java/org/openhab/binding/helios/internal/handler/HeliosHandler27.java
  bundles/org.openhab.binding.helios/src/main/java/org/openhab/binding/helios/internal/ws/rest/RESTError.java
  bundles/org.openhab.binding.helios/src/main/java/org/openhab/binding/helios/internal/ws/rest/RESTEvent.java
  bundles/org.openhab.binding.helios/src/main/java/org/openhab/binding/helios/internal/ws/rest/RESTPort.java
  bundles/org.openhab.binding.helios/src/main/java/org/openhab/binding/helios/internal/ws/rest/RESTSubscribeResponse.java
  bundles/org.openhab.binding.helios/src/main/java/org/openhab/binding/helios/internal/ws/rest/RESTSwitch.java
  bundles/org.openhab.binding.helios/src/main/java/org/openhab/binding/helios/internal/ws/rest/RESTSystemInfo.java
  bundles/org.openhab.binding.helios/src/main/java/org/openhab/binding/helios/internal/ws/soap/SOAPActionHandler.java
  bundles/org.openhab.binding.helios/src/main/java/org/openhab/binding/helios/internal/ws/soap/SOAPCallStateChanged.java
  bundles/org.openhab.binding.helios/src/main/java/org/openhab/binding/helios/internal/ws/soap/SOAPCardEntered.java
  bundles/org.openhab.binding.helios/src/main/java/org/openhab/binding/helios/internal/ws/soap/SOAPCodeEntered.java
  bundles/org.openhab.binding.helios/src/main/java/org/openhab/binding/helios/internal/ws/soap/SOAPDataField.java
  bundles/org.openhab.binding.helios/src/main/java/org/openhab/binding/helios/internal/ws/soap/SOAPDataFieldAdapter.java
  bundles/org.openhab.binding.helios/src/main/java/org/openhab/binding/helios/internal/ws/soap/SOAPDeviceState.java
  bundles/org.openhab.binding.helios/src/main/java/org/openhab/binding/helios/internal/ws/soap/SOAPEvent.java
  bundles/org.openhab.binding.helios/src/main/java/org/openhab/binding/helios/internal/ws/soap/SOAPKeyPressed.java
  bundles/org.openhab.binding.helios/src/main/java/org/openhab/binding/helios/internal/ws/soap/SOAPObjectFactory.java
  bundles/org.openhab.binding.helios/src/main/java/org/openhab/binding/helios/internal/ws/soap/SOAPSubscriptionActionHandler.java
  bundles/org.openhab.binding.helios/src/main/resources/ESH-INF/binding/binding.xml
  bundles/org.openhab.binding.helios/src/main/resources/ESH-INF/thing/channel-types.xml
  bundles/org.openhab.binding.helios/src/main/resources/ESH-INF/thing/ipvario221.xml
  bundles/org.openhab.binding.helios/src/main/resources/ESH-INF/thing/ipvario27.xml
  bundles/pom.xml
  features/karaf/openhab-addons/src/main/feature/feature.xml
Labels: infrastructure

#5280 [infrastructure] Migrate squeezebox to bnd
  CODEOWNERS
  addons/binding/org.openhab.binding.squeezebox/.classpath
  addons/binding/org.openhab.binding.squeezebox/.project
  addons/binding/org.openhab.binding.squeezebox/META-INF/MANIFEST.MF
  addons/binding/org.openhab.binding.squeezebox/OSGI-INF/.gitignore
  addons/binding/org.openhab.binding.squeezebox/build.properties
  addons/binding/org.openhab.binding.squeezebox/pom.xml
  addons/binding/pom.xml
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.squeezebox/.classpath
  bundles/org.openhab.binding.squeezebox/.project
  bundles/org.openhab.binding.squeezebox/NOTICE
  bundles/org.openhab.binding.squeezebox/README.md
  bundles/org.openhab.binding.squeezebox/pom.xml
  bundles/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/SqueezeBoxAudioSink.java
  bundles/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/SqueezeBoxBindingConstants.java
  bundles/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/SqueezeBoxHandlerFactory.java
  bundles/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/SqueezeBoxStateDescriptionOptionsProvider.java
  bundles/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/config/SqueezeBoxPlayerConfig.java
  bundles/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/config/SqueezeBoxServerConfig.java
  bundles/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/discovery/SqueezeBoxPlayerDiscoveryParticipant.java
  bundles/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/discovery/SqueezeBoxServerDiscoveryParticipant.java
  bundles/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/handler/SqueezeBoxNotificationListener.java
  bundles/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/handler/SqueezeBoxNotificationPlayer.java
  bundles/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/handler/SqueezeBoxPlayer.java
  bundles/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/handler/SqueezeBoxPlayerEventListener.java
  bundles/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/handler/SqueezeBoxPlayerHandler.java
  bundles/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/handler/SqueezeBoxPlayerPlayState.java
  bundles/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/handler/SqueezeBoxPlayerState.java
  bundles/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/handler/SqueezeBoxServerHandler.java
  bundles/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/model/Favorite.java
  bundles/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/utils/HttpUtils.java
  bundles/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/utils/SqueezeBoxCommunicationException.java
  bundles/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/utils/SqueezeBoxNotAuthorizedException.java
  bundles/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/utils/SqueezeBoxTimeoutException.java
  bundles/org.openhab.binding.squeezebox/src/main/resources/ESH-INF/binding/binding.xml
  bundles/org.openhab.binding.squeezebox/src/main/resources/ESH-INF/thing/thing-types.xml
  bundles/pom.xml
  features/karaf/openhab-addons/src/main/feature/feature.xml
Labels: infrastructure

#5283 [phc] Migrate to bnd build.
  CODEOWNERS
  addons/binding/org.openhab.binding.phc/.classpath
  addons/binding/org.openhab.binding.phc/META-INF/MANIFEST.MF
  addons/binding/org.openhab.binding.phc/OSGI-INF/.gitignore
  addons/binding/org.openhab.binding.phc/build.properties
  addons/binding/pom.xml
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.phc/.classpath
  bundles/org.openhab.binding.phc/.project
  bundles/org.openhab.binding.phc/NOTICE
  bundles/org.openhab.binding.phc/README.md
  bundles/org.openhab.binding.phc/pom.xml
  bundles/org.openhab.binding.phc/src/main/java/org/openhab/binding/phc/internal/PHCBindingConstants.java
  bundles/org.openhab.binding.phc/src/main/java/org/openhab/binding/phc/internal/PHCHandlerFactory.java
  bundles/org.openhab.binding.phc/src/main/java/org/openhab/binding/phc/internal/PHCHelper.java
  bundles/org.openhab.binding.phc/src/main/java/org/openhab/binding/phc/internal/handler/PHCBridgeHandler.java
  bundles/org.openhab.binding.phc/src/main/java/org/openhab/binding/phc/internal/handler/PHCHandler.java
  bundles/org.openhab.binding.phc/src/main/java/org/openhab/binding/phc/internal/handler/QueueObject.java
  bundles/org.openhab.binding.phc/src/main/resources/ESH-INF/binding/binding.xml
  bundles/org.openhab.binding.phc/src/main/resources/ESH-INF/thing/channel-types.xml
  bundles/org.openhab.binding.phc/src/main/resources/ESH-INF/thing/thing-types.xml
  bundles/pom.xml
  features/karaf/openhab-addons/src/main/feature/feature.xml
Labels: infrastructure

#5296 [velbus] Migrate to bnd build
  CODEOWNERS
  addons/binding/org.openhab.binding.velbus/.classpath
  addons/binding/org.openhab.binding.velbus/META-INF/MANIFEST.MF
  addons/binding/org.openhab.binding.velbus/OSGI-INF/.gitignore
  addons/binding/org.openhab.binding.velbus/build.properties
  addons/binding/pom.xml
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.velbus/.classpath
  bundles/org.openhab.binding.velbus/.project
  bundles/org.openhab.binding.velbus/NOTICE
  bundles/org.openhab.binding.velbus/README.md
  bundles/org.openhab.binding.velbus/pom.xml
  bundles/org.openhab.binding.velbus/src/main/java/org/openhab/binding/velbus/internal/VelbusBindingConstants.java
  bundles/org.openhab.binding.velbus/src/main/java/org/openhab/binding/velbus/internal/VelbusChannelIdentifier.java
  bundles/org.openhab.binding.velbus/src/main/java/org/openhab/binding/velbus/internal/VelbusHandlerFactory.java
  bundles/org.openhab.binding.velbus/src/main/java/org/openhab/binding/velbus/internal/VelbusModule.java
  bundles/org.openhab.binding.velbus/src/main/java/org/openhab/binding/velbus/internal/VelbusModuleAddress.java
  bundles/org.openhab.binding.velbus/src/main/java/org/openhab/binding/velbus/internal/VelbusPacketInputStream.java
  bundles/org.openhab.binding.velbus/src/main/java/org/openhab/binding/velbus/internal/VelbusPacketListener.java
  bundles/org.openhab.binding.velbus/src/main/java/org/openhab/binding/velbus/internal/discovery/VelbusThingDiscoveryService.java
  bundles/org.openhab.binding.velbus/src/main/java/org/openhab/binding/velbus/internal/handler/VelbusBlindsHandler.java
  bundles/org.openhab.binding.velbus/src/main/java/org/openhab/binding/velbus/internal/handler/VelbusBridgeHandler.java
  bundles/org.openhab.binding.velbus/src/main/java/org/openhab/binding/velbus/internal/handler/VelbusDimmerHandler.java
  bundles/org.openhab.binding.velbus/src/main/java/org/openhab/binding/velbus/internal/handler/VelbusRelayHandler.java
  bundles/org.openhab.binding.velbus/src/main/java/org/openhab/binding/velbus/internal/handler/VelbusSensorHandler.java
  bundles/org.openhab.binding.velbus/src/main/java/org/openhab/binding/velbus/internal/handler/VelbusTemperatureSensorHandler.java
  bundles/org.openhab.binding.velbus/src/main/java/org/openhab/binding/velbus/internal/handler/VelbusThingHandler.java
  bundles/org.openhab.binding.velbus/src/main/java/org/openhab/binding/velbus/internal/handler/VelbusVMBGPHandler.java
  bundles/org.openhab.binding.velbus/src/main/java/org/openhab/binding/velbus/internal/handler/VelbusVMBGPOHandler.java
  bundles/org.openhab.binding.velbus/src/main/java/org/openhab/binding/velbus/internal/handler/VelbusVMBPIROHandler.java
  bundles/org.openhab.binding.velbus/src/main/java/org/openhab/binding/velbus/internal/packets/VelbusBlindOffPacket.java
  bundles/org.openhab.binding.velbus/src/main/java/org/openhab/binding/velbus/internal/packets/VelbusBlindPositionPacket.java
  bundles/org.openhab.binding.velbus/src/main/java/org/openhab/binding/velbus/internal/packets/VelbusBlindUpDownPacket.java
  bundles/org.openhab.binding.velbus/src/main/java/org/openhab/binding/velbus/internal/packets/VelbusChannelNameRequestPacket.java
  bundles/org.openhab.binding.velbus/src/main/java/org/openhab/binding/velbus/internal/packets/VelbusDimmerPacket.java
  bundles/org.openhab.binding.velbus/src/main/java/org/openhab/binding/velbus/internal/packets/VelbusPacket.java
  bundles/org.openhab.binding.velbus/src/main/java/org/openhab/binding/velbus/internal/packets/VelbusRelayPacket.java
  bundles/org.openhab.binding.velbus/src/main/java/org/openhab/binding/velbus/internal/packets/VelbusScanPacket.java
  bundles/org.openhab.binding.velbus/src/main/java/org/openhab/binding/velbus/internal/packets/VelbusSensorTemperatureRequestPacket.java
  bundles/org.openhab.binding.velbus/src/main/java/org/openhab/binding/velbus/internal/packets/VelbusStatusRequestPacket.java
  bundles/org.openhab.binding.velbus/src/main/resources/ESH-INF/binding/binding.xml
  bundles/org.openhab.binding.velbus/src/main/resources/ESH-INF/config/config.xml
  bundles/org.openhab.binding.velbus/src/main/resources/ESH-INF/thing/thing-types.xml
  bundles/pom.xml
  features/karaf/openhab-addons/src/main/feature/feature.xml
Labels: infrastructure

#5288 [konnected] Migrate to bnd build
  CODEOWNERS
  addons/binding/org.openhab.binding.konnected/.classpath
  addons/binding/org.openhab.binding.konnected/META-INF/MANIFEST.MF
  addons/binding/org.openhab.binding.konnected/OSGI-INF/.gitignore
  addons/binding/org.openhab.binding.konnected/build.properties
  addons/binding/pom.xml
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.konnected/.classpath
  bundles/org.openhab.binding.konnected/.project
  bundles/org.openhab.binding.konnected/NOTICE
  bundles/org.openhab.binding.konnected/README.md
  bundles/org.openhab.binding.konnected/pom.xml
  bundles/org.openhab.binding.konnected/src/main/java/org/openhab/binding/konnected/internal/KonnectedBindingConstants.java
  bundles/org.openhab.binding.konnected/src/main/java/org/openhab/binding/konnected/internal/KonnectedConfiguration.java
  bundles/org.openhab.binding.konnected/src/main/java/org/openhab/binding/konnected/internal/KonnectedHTTPUtils.java
  bundles/org.openhab.binding.konnected/src/main/java/org/openhab/binding/konnected/internal/KonnectedHandlerFactory.java
  bundles/org.openhab.binding.konnected/src/main/java/org/openhab/binding/konnected/internal/KonnectedHttpRetryExceeded.java
  bundles/org.openhab.binding.konnected/src/main/java/org/openhab/binding/konnected/internal/discovery/KonnectedUPnPServer.java
  bundles/org.openhab.binding.konnected/src/main/java/org/openhab/binding/konnected/internal/gson/KonnectedModuleGson.java
  bundles/org.openhab.binding.konnected/src/main/java/org/openhab/binding/konnected/internal/gson/KonnectedModulePayload.java
  bundles/org.openhab.binding.konnected/src/main/java/org/openhab/binding/konnected/internal/handler/KonnectedHandler.java
  bundles/org.openhab.binding.konnected/src/main/java/org/openhab/binding/konnected/internal/servlet/KonnectedHTTPServlet.java
  bundles/org.openhab.binding.konnected/src/main/java/org/openhab/binding/konnected/internal/servlet/KonnectedWebHookFail.java
  bundles/org.openhab.binding.konnected/src/main/resources/ESH-INF/binding/binding.xml
  bundles/org.openhab.binding.konnected/src/main/resources/ESH-INF/config/config.xml
  bundles/org.openhab.binding.konnected/src/main/resources/ESH-INF/thing/thing-types.xml
  bundles/pom.xml
  features/karaf/openhab-addons/src/main/feature/feature.xml
Labels: infrastructure

#5324 [km200] Removed dependency on google guava library.
  addons/binding/org.openhab.binding.km200/META-INF/MANIFEST.MF
  addons/binding/org.openhab.binding.km200/src/main/java/org/openhab/binding/km200/internal/handler/KM200GatewayHandler.java
Labels: infrastructure

#5291 [regoheatpump] Migrate to bnd build
  CODEOWNERS
  addons/binding/org.openhab.binding.regoheatpump/.classpath
  addons/binding/org.openhab.binding.regoheatpump/META-INF/MANIFEST.MF
  addons/binding/org.openhab.binding.regoheatpump/OSGI-INF/.gitignore
  addons/binding/org.openhab.binding.regoheatpump/build.properties
  addons/binding/pom.xml
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.regoheatpump/.classpath
  bundles/org.openhab.binding.regoheatpump/.project
  bundles/org.openhab.binding.regoheatpump/NOTICE
  bundles/org.openhab.binding.regoheatpump/README.md
  bundles/org.openhab.binding.regoheatpump/doc/board.png
  bundles/org.openhab.binding.regoheatpump/pom.xml
  bundles/org.openhab.binding.regoheatpump/src/main/java/org/openhab/binding/regoheatpump/internal/RegoHeatPumpBindingConstants.java
  bundles/org.openhab.binding.regoheatpump/src/main/java/org/openhab/binding/regoheatpump/internal/RegoHeatPumpHandlerFactory.java
  bundles/org.openhab.binding.regoheatpump/src/main/java/org/openhab/binding/regoheatpump/internal/handler/HusdataHandler.java
  bundles/org.openhab.binding.regoheatpump/src/main/java/org/openhab/binding/regoheatpump/internal/handler/IpHusdataHandler.java
  bundles/org.openhab.binding.regoheatpump/src/main/java/org/openhab/binding/regoheatpump/internal/handler/IpRego6xxHeatPumpHandler.java
  bundles/org.openhab.binding.regoheatpump/src/main/java/org/openhab/binding/regoheatpump/internal/handler/Rego6xxHeatPumpHandler.java
  bundles/org.openhab.binding.regoheatpump/src/main/java/org/openhab/binding/regoheatpump/internal/handler/SerialHusdataHandler.java
  bundles/org.openhab.binding.regoheatpump/src/main/java/org/openhab/binding/regoheatpump/internal/handler/SerialRego6xxHeatPumpHandler.java
  bundles/org.openhab.binding.regoheatpump/src/main/java/org/openhab/binding/regoheatpump/internal/protocol/IpRegoConnection.java
  bundles/org.openhab.binding.regoheatpump/src/main/java/org/openhab/binding/regoheatpump/internal/protocol/RegoConnection.java
  bundles/org.openhab.binding.regoheatpump/src/main/java/org/openhab/binding/regoheatpump/internal/protocol/SerialRegoConnection.java
  bundles/org.openhab.binding.regoheatpump/src/main/java/org/openhab/binding/regoheatpump/internal/rego6xx/AbstractLongResponseParser.java
  bundles/org.openhab.binding.regoheatpump/src/main/java/org/openhab/binding/regoheatpump/internal/rego6xx/AbstractResponseParser.java
  bundles/org.openhab.binding.regoheatpump/src/main/java/org/openhab/binding/regoheatpump/internal/rego6xx/Checksum.java
  bundles/org.openhab.binding.regoheatpump/src/main/java/org/openhab/binding/regoheatpump/internal/rego6xx/CommandFactory.java
  bundles/org.openhab.binding.regoheatpump/src/main/java/org/openhab/binding/regoheatpump/internal/rego6xx/ErrorLine.java
  bundles/org.openhab.binding.regoheatpump/src/main/java/org/openhab/binding/regoheatpump/internal/rego6xx/ErrorLineResponseParser.java
  bundles/org.openhab.binding.regoheatpump/src/main/java/org/openhab/binding/regoheatpump/internal/rego6xx/Rego6xxProtocolException.java
  bundles/org.openhab.binding.regoheatpump/src/main/java/org/openhab/binding/regoheatpump/internal/rego6xx/RegoRegisterMapper.java
  bundles/org.openhab.binding.regoheatpump/src/main/java/org/openhab/binding/regoheatpump/internal/rego6xx/ResponseParser.java
  bundles/org.openhab.binding.regoheatpump/src/main/java/org/openhab/binding/regoheatpump/internal/rego6xx/ResponseParserFactory.java
  bundles/org.openhab.binding.regoheatpump/src/main/java/org/openhab/binding/regoheatpump/internal/rego6xx/ShortResponseParser.java
  bundles/org.openhab.binding.regoheatpump/src/main/java/org/openhab/binding/regoheatpump/internal/rego6xx/StringResponseParser.java
  bundles/org.openhab.binding.regoheatpump/src/main/java/org/openhab/binding/regoheatpump/internal/rego6xx/ValueConverter.java
  bundles/org.openhab.binding.regoheatpump/src/main/java/org/openhab/binding/regoheatpump/internal/rego6xx/WriteResponse.java
  bundles/org.openhab.binding.regoheatpump/src/main/resources/ESH-INF/binding/binding.xml
  bundles/org.openhab.binding.regoheatpump/src/main/resources/ESH-INF/thing/thing-types.xml
  bundles/pom.xml
  features/karaf/openhab-addons/src/main/feature/feature.xml
Labels: infrastructure

#5294 [solarlog] Migrate to bnd build
  CODEOWNERS
  addons/binding/org.openhab.binding.solarlog/.classpath
  addons/binding/org.openhab.binding.solarlog/META-INF/MANIFEST.MF
  addons/binding/org.openhab.binding.solarlog/OSGI-INF/.gitignore
  addons/binding/org.openhab.binding.solarlog/build.properties
  addons/binding/pom.xml
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.solarlog/.classpath
  bundles/org.openhab.binding.solarlog/.project
  bundles/org.openhab.binding.solarlog/NOTICE
  bundles/org.openhab.binding.solarlog/README.md
  bundles/org.openhab.binding.solarlog/pom.xml
  bundles/org.openhab.binding.solarlog/src/main/java/org/openhab/binding/solarlog/internal/SolarLogBindingConstants.java
  bundles/org.openhab.binding.solarlog/src/main/java/org/openhab/binding/solarlog/internal/SolarLogChannel.java
  bundles/org.openhab.binding.solarlog/src/main/java/org/openhab/binding/solarlog/internal/SolarLogConfig.java
  bundles/org.openhab.binding.solarlog/src/main/java/org/openhab/binding/solarlog/internal/SolarLogHandlerFactory.java
  bundles/org.openhab.binding.solarlog/src/main/java/org/openhab/binding/solarlog/internal/handler/SolarLogHandler.java
  bundles/org.openhab.binding.solarlog/src/main/resources/ESH-INF/binding/binding.xml
  bundles/org.openhab.binding.solarlog/src/main/resources/ESH-INF/thing/thing-types.xml
  bundles/pom.xml
  features/karaf/openhab-addons/src/main/feature/feature.xml
Labels: infrastructure

#5295 [toon] Migrate to bnd build
  CODEOWNERS
  addons/binding/org.openhab.binding.toon/.classpath
  addons/binding/org.openhab.binding.toon/META-INF/MANIFEST.MF
  addons/binding/org.openhab.binding.toon/OSGI-INF/.gitignore
  addons/binding/org.openhab.binding.toon/build.properties
  addons/binding/pom.xml
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.toon/.classpath
  bundles/org.openhab.binding.toon/.project
  bundles/org.openhab.binding.toon/NOTICE
  bundles/org.openhab.binding.toon/README.md
  bundles/org.openhab.binding.toon/pom.xml
  bundles/org.openhab.binding.toon/src/main/java/org/openhab/binding/toon/internal/ToonApiClient.java
  bundles/org.openhab.binding.toon/src/main/java/org/openhab/binding/toon/internal/ToonBindingConstants.java
  bundles/org.openhab.binding.toon/src/main/java/org/openhab/binding/toon/internal/ToonHandlerFactory.java
  bundles/org.openhab.binding.toon/src/main/java/org/openhab/binding/toon/internal/api/Agreement.java
  bundles/org.openhab.binding.toon/src/main/java/org/openhab/binding/toon/internal/api/DeviceConfig.java
  bundles/org.openhab.binding.toon/src/main/java/org/openhab/binding/toon/internal/api/DeviceConfigInfo.java
  bundles/org.openhab.binding.toon/src/main/java/org/openhab/binding/toon/internal/api/DeviceStatusInfo.java
  bundles/org.openhab.binding.toon/src/main/java/org/openhab/binding/toon/internal/api/GasUsage.java
  bundles/org.openhab.binding.toon/src/main/java/org/openhab/binding/toon/internal/api/PowerUsage.java
  bundles/org.openhab.binding.toon/src/main/java/org/openhab/binding/toon/internal/api/ThermostatInfo.java
  bundles/org.openhab.binding.toon/src/main/java/org/openhab/binding/toon/internal/api/ToonConnectionException.java
  bundles/org.openhab.binding.toon/src/main/java/org/openhab/binding/toon/internal/api/ToonState.java
  bundles/org.openhab.binding.toon/src/main/java/org/openhab/binding/toon/internal/config/ToonBridgeConfiguration.java
  bundles/org.openhab.binding.toon/src/main/java/org/openhab/binding/toon/internal/discovery/ToonDiscoveryService.java
  bundles/org.openhab.binding.toon/src/main/java/org/openhab/binding/toon/internal/handler/AbstractToonHandler.java
  bundles/org.openhab.binding.toon/src/main/java/org/openhab/binding/toon/internal/handler/ToonBridgeHandler.java
  bundles/org.openhab.binding.toon/src/main/java/org/openhab/binding/toon/internal/handler/ToonDisplayHandler.java
  bundles/org.openhab.binding.toon/src/main/java/org/openhab/binding/toon/internal/handler/ToonPlugHandler.java
  bundles/org.openhab.binding.toon/src/main/resources/ESH-INF/binding/binding.xml
  bundles/org.openhab.binding.toon/src/main/resources/ESH-INF/thing/bridge.xml
  bundles/org.openhab.binding.toon/src/main/resources/ESH-INF/thing/channels.xml
  bundles/org.openhab.binding.toon/src/main/resources/ESH-INF/thing/thing-types.xml
  bundles/pom.xml
  features/karaf/openhab-addons/src/main/feature/feature.xml
Labels: infrastructure

#5297 [yeelight] Migrate to bnd build
  CODEOWNERS
  addons/binding/org.openhab.binding.yeelight/.classpath
  addons/binding/org.openhab.binding.yeelight/META-INF/MANIFEST.MF
  addons/binding/org.openhab.binding.yeelight/OSGI-INF/.gitignore
  addons/binding/org.openhab.binding.yeelight/build.properties
  addons/binding/pom.xml
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.yeelight/.classpath
  bundles/org.openhab.binding.yeelight/.project
  bundles/org.openhab.binding.yeelight/NOTICE
  bundles/org.openhab.binding.yeelight/README.md
  bundles/org.openhab.binding.yeelight/about_files/LICENSE
  bundles/org.openhab.binding.yeelight/pom.xml
  bundles/org.openhab.binding.yeelight/src/main/java/org/openhab/binding/yeelight/internal/YeelightBindingConstants.java
  bundles/org.openhab.binding.yeelight/src/main/java/org/openhab/binding/yeelight/internal/YeelightHandlerFactory.java
  bundles/org.openhab.binding.yeelight/src/main/java/org/openhab/binding/yeelight/internal/discovery/YeelightDiscoveryService.java
  bundles/org.openhab.binding.yeelight/src/main/java/org/openhab/binding/yeelight/internal/handler/YeelightCeilingHandler.java
  bundles/org.openhab.binding.yeelight/src/main/java/org/openhab/binding/yeelight/internal/handler/YeelightColorHandler.java
  bundles/org.openhab.binding.yeelight/src/main/java/org/openhab/binding/yeelight/internal/handler/YeelightHandlerBase.java
  bundles/org.openhab.binding.yeelight/src/main/java/org/openhab/binding/yeelight/internal/handler/YeelightStripeHandler.java
  bundles/org.openhab.binding.yeelight/src/main/java/org/openhab/binding/yeelight/internal/handler/YeelightWhiteHandler.java
  bundles/org.openhab.binding.yeelight/src/main/java/org/openhab/binding/yeelight/internal/lib/CommonLogger.java
  bundles/org.openhab.binding.yeelight/src/main/java/org/openhab/binding/yeelight/internal/lib/device/CeilingDevice.java
  bundles/org.openhab.binding.yeelight/src/main/java/org/openhab/binding/yeelight/internal/lib/device/ColorFlowItem.java
  bundles/org.openhab.binding.yeelight/src/main/java/org/openhab/binding/yeelight/internal/lib/device/ConnectState.java
  bundles/org.openhab.binding.yeelight/src/main/java/org/openhab/binding/yeelight/internal/lib/device/CtBulbDevice.java
  bundles/org.openhab.binding.yeelight/src/main/java/org/openhab/binding/yeelight/internal/lib/device/DesklampDevice.java
  bundles/org.openhab.binding.yeelight/src/main/java/org/openhab/binding/yeelight/internal/lib/device/DeviceBase.java
  bundles/org.openhab.binding.yeelight/src/main/java/org/openhab/binding/yeelight/internal/lib/device/DeviceFactory.java
  bundles/org.openhab.binding.yeelight/src/main/java/org/openhab/binding/yeelight/internal/lib/device/DeviceMethod.java
  bundles/org.openhab.binding.yeelight/src/main/java/org/openhab/binding/yeelight/internal/lib/device/DeviceStatus.java
  bundles/org.openhab.binding.yeelight/src/main/java/org/openhab/binding/yeelight/internal/lib/device/MethodFactory.java
  bundles/org.openhab.binding.yeelight/src/main/java/org/openhab/binding/yeelight/internal/lib/device/MonoDevice.java
  bundles/org.openhab.binding.yeelight/src/main/java/org/openhab/binding/yeelight/internal/lib/device/PitayaDevice.java
  bundles/org.openhab.binding.yeelight/src/main/java/org/openhab/binding/yeelight/internal/lib/device/WonderDevice.java
  bundles/org.openhab.binding.yeelight/src/main/java/org/openhab/binding/yeelight/internal/lib/device/connection/ConnectionBase.java
  bundles/org.openhab.binding.yeelight/src/main/java/org/openhab/binding/yeelight/internal/lib/device/connection/WifiConnection.java
  bundles/org.openhab.binding.yeelight/src/main/java/org/openhab/binding/yeelight/internal/lib/enums/DeviceAction.java
  bundles/org.openhab.binding.yeelight/src/main/java/org/openhab/binding/yeelight/internal/lib/enums/DeviceMode.java
  bundles/org.openhab.binding.yeelight/src/main/java/org/openhab/binding/yeelight/internal/lib/enums/DeviceType.java
  bundles/org.openhab.binding.yeelight/src/main/java/org/openhab/binding/yeelight/internal/lib/enums/MethodAction.java
  bundles/org.openhab.binding.yeelight/src/main/java/org/openhab/binding/yeelight/internal/lib/listeners/DeviceConnectionStateListener.java
  bundles/org.openhab.binding.yeelight/src/main/java/org/openhab/binding/yeelight/internal/lib/listeners/DeviceListener.java
  bundles/org.openhab.binding.yeelight/src/main/java/org/openhab/binding/yeelight/internal/lib/listeners/DeviceStatusChangeListener.java
  bundles/org.openhab.binding.yeelight/src/main/java/org/openhab/binding/yeelight/internal/lib/services/DeviceManager.java
  bundles/org.openhab.binding.yeelight/src/main/resources/ESH-INF/binding/binding.xml
  bundles/org.openhab.binding.yeelight/src/main/resources/ESH-INF/config/config.xml
  bundles/org.openhab.binding.yeelight/src/main/resources/ESH-INF/thing/ceiling.xml
  bundles/org.openhab.binding.yeelight/src/main/resources/ESH-INF/thing/channels.xml
  bundles/org.openhab.binding.yeelight/src/main/resources/ESH-INF/thing/ct_bulb.xml
  bundles/org.openhab.binding.yeelight/src/main/resources/ESH-INF/thing/desklamp.xml
  bundles/org.openhab.binding.yeelight/src/main/resources/ESH-INF/thing/dolphin.xml
  bundles/org.openhab.binding.yeelight/src/main/resources/ESH-INF/thing/stripe.xml
  bundles/org.openhab.binding.yeelight/src/main/resources/ESH-INF/thing/wonder.xml
  bundles/pom.xml
  features/karaf/openhab-addons/src/main/feature/feature.xml
Labels: infrastructure

#5302 [seneye] Migrate to bnd build
  CODEOWNERS
  addons/binding/org.openhab.binding.seneye/.classpath
  addons/binding/org.openhab.binding.seneye/META-INF/MANIFEST.MF
  addons/binding/org.openhab.binding.seneye/OSGI-INF/.gitignore
  addons/binding/org.openhab.binding.seneye/build.properties
  addons/binding/pom.xml
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.seneye/.classpath
  bundles/org.openhab.binding.seneye/.project
  bundles/org.openhab.binding.seneye/NOTICE
  bundles/org.openhab.binding.seneye/README.md
  bundles/org.openhab.binding.seneye/pom.xml
  bundles/org.openhab.binding.seneye/src/main/java/org/openhab/binding/seneye/internal/CommunicationException.java
  bundles/org.openhab.binding.seneye/src/main/java/org/openhab/binding/seneye/internal/InvalidConfigurationException.java
  bundles/org.openhab.binding.seneye/src/main/java/org/openhab/binding/seneye/internal/ReadingsUpdate.java
  bundles/org.openhab.binding.seneye/src/main/java/org/openhab/binding/seneye/internal/Seneye.java
  bundles/org.openhab.binding.seneye/src/main/java/org/openhab/binding/seneye/internal/SeneyeBindingConstants.java
  bundles/org.openhab.binding.seneye/src/main/java/org/openhab/binding/seneye/internal/SeneyeConfigurationParameters.java
  bundles/org.openhab.binding.seneye/src/main/java/org/openhab/binding/seneye/internal/SeneyeDeviceReading.java
  bundles/org.openhab.binding.seneye/src/main/java/org/openhab/binding/seneye/internal/SeneyeDeviceReadingAdvice.java
  bundles/org.openhab.binding.seneye/src/main/java/org/openhab/binding/seneye/internal/SeneyeDeviceReadingKelvin.java
  bundles/org.openhab.binding.seneye/src/main/java/org/openhab/binding/seneye/internal/SeneyeDeviceReadingLux.java
  bundles/org.openhab.binding.seneye/src/main/java/org/openhab/binding/seneye/internal/SeneyeDeviceReadingNh3.java
  bundles/org.openhab.binding.seneye/src/main/java/org/openhab/binding/seneye/internal/SeneyeDeviceReadingNh4.java
  bundles/org.openhab.binding.seneye/src/main/java/org/openhab/binding/seneye/internal/SeneyeDeviceReadingO2.java
  bundles/org.openhab.binding.seneye/src/main/java/org/openhab/binding/seneye/internal/SeneyeDeviceReadingPar.java
  bundles/org.openhab.binding.seneye/src/main/java/org/openhab/binding/seneye/internal/SeneyeDeviceReadingPh.java
  bundles/org.openhab.binding.seneye/src/main/java/org/openhab/binding/seneye/internal/SeneyeDeviceReadingTemperature.java
  bundles/org.openhab.binding.seneye/src/main/java/org/openhab/binding/seneye/internal/SeneyeHandlerFactory.java
  bundles/org.openhab.binding.seneye/src/main/java/org/openhab/binding/seneye/internal/SeneyeService.java
  bundles/org.openhab.binding.seneye/src/main/java/org/openhab/binding/seneye/internal/SeneyeStatus.java
  bundles/org.openhab.binding.seneye/src/main/java/org/openhab/binding/seneye/internal/handler/SeneyeHandler.java
  bundles/org.openhab.binding.seneye/src/main/resources/ESH-INF/binding/binding.xml
  bundles/org.openhab.binding.seneye/src/main/resources/ESH-INF/thing/thing-types.xml
  bundles/pom.xml
  features/karaf/openhab-addons/src/main/feature/feature.xml
Labels: infrastructure

#5317 [dscalarm] Migrate to bnd build
  CODEOWNERS
  addons/binding/org.openhab.binding.dscalarm/.classpath
  addons/binding/org.openhab.binding.dscalarm/META-INF/MANIFEST.MF
  addons/binding/org.openhab.binding.dscalarm/OSGI-INF/.gitignore
  addons/binding/org.openhab.binding.dscalarm/build.properties
  addons/binding/pom.xml
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.dscalarm/.classpath
  bundles/org.openhab.binding.dscalarm/.project
  bundles/org.openhab.binding.dscalarm/NOTICE
  bundles/org.openhab.binding.dscalarm/README.md
  bundles/org.openhab.binding.dscalarm/pom.xml
  bundles/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/internal/DSCAlarmBindingConstants.java
  bundles/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/internal/DSCAlarmCode.java
  bundles/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/internal/DSCAlarmEvent.java
  bundles/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/internal/DSCAlarmMessage.java
  bundles/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/internal/config/DSCAlarmPanelConfiguration.java
  bundles/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/internal/config/DSCAlarmPartitionConfiguration.java
  bundles/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/internal/config/DSCAlarmZoneConfiguration.java
  bundles/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/internal/config/EnvisalinkBridgeConfiguration.java
  bundles/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/internal/config/IT100BridgeConfiguration.java
  bundles/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/internal/config/TCPServerBridgeConfiguration.java
  bundles/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/internal/discovery/DSCAlarmBridgeDiscovery.java
  bundles/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/internal/discovery/DSCAlarmDiscoveryService.java
  bundles/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/internal/discovery/EnvisalinkBridgeDiscovery.java
  bundles/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/internal/discovery/IT100BridgeDiscovery.java
  bundles/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/internal/factory/DSCAlarmHandlerFactory.java
  bundles/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/internal/handler/DSCAlarmBaseBridgeHandler.java
  bundles/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/internal/handler/DSCAlarmBaseThingHandler.java
  bundles/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/internal/handler/DSCAlarmBridgeType.java
  bundles/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/internal/handler/DSCAlarmProtocol.java
  bundles/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/internal/handler/DSCAlarmThingType.java
  bundles/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/internal/handler/EnvisalinkBridgeHandler.java
  bundles/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/internal/handler/IT100BridgeHandler.java
  bundles/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/internal/handler/KeypadThingHandler.java
  bundles/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/internal/handler/PanelThingHandler.java
  bundles/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/internal/handler/PartitionThingHandler.java
  bundles/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/internal/handler/TCPServerBridgeHandler.java
  bundles/org.openhab.binding.dscalarm/src/main/java/org/openhab/binding/dscalarm/internal/handler/ZoneThingHandler.java
  bundles/org.openhab.binding.dscalarm/src/main/resources/ESH-INF/binding/binding.xml
  bundles/org.openhab.binding.dscalarm/src/main/resources/ESH-INF/thing/channels.xml
  bundles/org.openhab.binding.dscalarm/src/main/resources/ESH-INF/thing/envisalinkbridge.xml
  bundles/org.openhab.binding.dscalarm/src/main/resources/ESH-INF/thing/it100bridge.xml
  bundles/org.openhab.binding.dscalarm/src/main/resources/ESH-INF/thing/keypad.xml
  bundles/org.openhab.binding.dscalarm/src/main/resources/ESH-INF/thing/panel.xml
  bundles/org.openhab.binding.dscalarm/src/main/resources/ESH-INF/thing/partition.xml
  bundles/org.openhab.binding.dscalarm/src/main/resources/ESH-INF/thing/tcpserverbridge.xml
  bundles/org.openhab.binding.dscalarm/src/main/resources/ESH-INF/thing/zone.xml
  bundles/pom.xml
  features/karaf/openhab-addons/src/main/feature/feature.xml
Labels: infrastructure

#5298 [vitotronic] Migrate to bnd build
  CODEOWNERS
  addons/binding/org.openhab.binding.vitotronic/.classpath
  addons/binding/org.openhab.binding.vitotronic/META-INF/MANIFEST.MF
  addons/binding/org.openhab.binding.vitotronic/OSGI-INF/.gitignore
  addons/binding/org.openhab.binding.vitotronic/build.properties
  addons/binding/pom.xml
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.vitotronic/.classpath
  bundles/org.openhab.binding.vitotronic/.project
  bundles/org.openhab.binding.vitotronic/NOTICE
  bundles/org.openhab.binding.vitotronic/README.md
  bundles/org.openhab.binding.vitotronic/doc/architecture_vitotronic.jpg
  bundles/org.openhab.binding.vitotronic/pom.xml
  bundles/org.openhab.binding.vitotronic/src/main/java/org/openhab/binding/vitotronic/internal/VitotronicBindingConfiguration.java
  bundles/org.openhab.binding.vitotronic/src/main/java/org/openhab/binding/vitotronic/internal/VitotronicBindingConstants.java
  bundles/org.openhab.binding.vitotronic/src/main/java/org/openhab/binding/vitotronic/internal/VitotronicHandlerFactory.java
  bundles/org.openhab.binding.vitotronic/src/main/java/org/openhab/binding/vitotronic/internal/discovery/VitotronicBridgeDiscovery.java
  bundles/org.openhab.binding.vitotronic/src/main/java/org/openhab/binding/vitotronic/internal/discovery/VitotronicDiscoveryService.java
  bundles/org.openhab.binding.vitotronic/src/main/java/org/openhab/binding/vitotronic/internal/handler/VitotronicBridgeHandler.java
  bundles/org.openhab.binding.vitotronic/src/main/java/org/openhab/binding/vitotronic/internal/handler/VitotronicThingHandler.java
  bundles/org.openhab.binding.vitotronic/src/main/resources/ESH-INF/binding/binding.xml
  bundles/org.openhab.binding.vitotronic/src/main/resources/ESH-INF/thing/bridge.xml
  bundles/org.openhab.binding.vitotronic/src/main/resources/ESH-INF/thing/thing-types.xml
  bundles/pom.xml
  features/karaf/openhab-addons/src/main/feature/feature.xml
Labels: infrastructure

#5300 [sonyaudio] Migrate to bnd build
  CODEOWNERS
  addons/binding/org.openhab.binding.sonyaudio/.classpath
  addons/binding/org.openhab.binding.sonyaudio/META-INF/MANIFEST.MF
  addons/binding/org.openhab.binding.sonyaudio/OSGI-INF/.gitignore
  addons/binding/org.openhab.binding.sonyaudio/build.properties
  addons/binding/pom.xml
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.sonyaudio/.classpath
  bundles/org.openhab.binding.sonyaudio/.project
  bundles/org.openhab.binding.sonyaudio/NOTICE
  bundles/org.openhab.binding.sonyaudio/README.md
  bundles/org.openhab.binding.sonyaudio/pom.xml
  bundles/org.openhab.binding.sonyaudio/src/main/java/org/openhab/binding/sonyaudio/internal/SonyAudioBindingConstants.java
  bundles/org.openhab.binding.sonyaudio/src/main/java/org/openhab/binding/sonyaudio/internal/SonyAudioEventListener.java
  bundles/org.openhab.binding.sonyaudio/src/main/java/org/openhab/binding/sonyaudio/internal/SonyAudioHandlerFactory.java
  bundles/org.openhab.binding.sonyaudio/src/main/java/org/openhab/binding/sonyaudio/internal/discovery/SonyAudioDiscoveryParticipant.java
  bundles/org.openhab.binding.sonyaudio/src/main/java/org/openhab/binding/sonyaudio/internal/handler/HtCt800Handler.java
  bundles/org.openhab.binding.sonyaudio/src/main/java/org/openhab/binding/sonyaudio/internal/handler/HtMt500Handler.java
  bundles/org.openhab.binding.sonyaudio/src/main/java/org/openhab/binding/sonyaudio/internal/handler/HtSt5000Handler.java
  bundles/org.openhab.binding.sonyaudio/src/main/java/org/openhab/binding/sonyaudio/internal/handler/HtZ9fHandler.java
  bundles/org.openhab.binding.sonyaudio/src/main/java/org/openhab/binding/sonyaudio/internal/handler/HtZf9Handler.java
  bundles/org.openhab.binding.sonyaudio/src/main/java/org/openhab/binding/sonyaudio/internal/handler/SonyAudioHandler.java
  bundles/org.openhab.binding.sonyaudio/src/main/java/org/openhab/binding/sonyaudio/internal/handler/SrsZr5Handler.java
  bundles/org.openhab.binding.sonyaudio/src/main/java/org/openhab/binding/sonyaudio/internal/handler/StrDn1080Handler.java
  bundles/org.openhab.binding.sonyaudio/src/main/java/org/openhab/binding/sonyaudio/internal/protocol/SonyAudioClientSocket.java
  bundles/org.openhab.binding.sonyaudio/src/main/java/org/openhab/binding/sonyaudio/internal/protocol/SonyAudioClientSocketEventListener.java
  bundles/org.openhab.binding.sonyaudio/src/main/java/org/openhab/binding/sonyaudio/internal/protocol/SonyAudioConnection.java
  bundles/org.openhab.binding.sonyaudio/src/main/java/org/openhab/binding/sonyaudio/internal/protocol/SonyAudioMethod.java
  bundles/org.openhab.binding.sonyaudio/src/main/resources/ESH-INF/binding/binding.xml
  bundles/org.openhab.binding.sonyaudio/src/main/resources/ESH-INF/config/config.xml
  bundles/org.openhab.binding.sonyaudio/src/main/resources/ESH-INF/thing/ht-ct800.xml
  bundles/org.openhab.binding.sonyaudio/src/main/resources/ESH-INF/thing/ht-mt500.xml
  bundles/org.openhab.binding.sonyaudio/src/main/resources/ESH-INF/thing/ht-st5000.xml
  bundles/org.openhab.binding.sonyaudio/src/main/resources/ESH-INF/thing/ht-z9f-zf9.xml
  bundles/org.openhab.binding.sonyaudio/src/main/resources/ESH-INF/thing/srs-zr5.xml
  bundles/org.openhab.binding.sonyaudio/src/main/resources/ESH-INF/thing/str-dn1080.xml
  bundles/org.openhab.binding.sonyaudio/src/main/resources/ESH-INF/thing/thing-types.xml
  bundles/pom.xml
  features/karaf/openhab-addons/src/main/feature/feature.xml
Labels: infrastructure

#5301 [smaenergymeter] Migrate to bnd build
  CODEOWNERS
  addons/binding/org.openhab.binding.smaenergymeter/.classpath
  addons/binding/org.openhab.binding.smaenergymeter/META-INF/MANIFEST.MF
  addons/binding/org.openhab.binding.smaenergymeter/OSGI-INF/.gitignore
  addons/binding/org.openhab.binding.smaenergymeter/build.properties
  addons/binding/pom.xml
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.smaenergymeter/.classpath
  bundles/org.openhab.binding.smaenergymeter/.project
  bundles/org.openhab.binding.smaenergymeter/NOTICE
  bundles/org.openhab.binding.smaenergymeter/README.md
  bundles/org.openhab.binding.smaenergymeter/pom.xml
  bundles/org.openhab.binding.smaenergymeter/src/main/java/org/openhab/binding/smaenergymeter/internal/SMAEnergyMeterBindingConstants.java
  bundles/org.openhab.binding.smaenergymeter/src/main/java/org/openhab/binding/smaenergymeter/internal/SMAEnergyMeterHandlerFactory.java
  bundles/org.openhab.binding.smaenergymeter/src/main/java/org/openhab/binding/smaenergymeter/internal/configuration/EnergyMeterConfig.java
  bundles/org.openhab.binding.smaenergymeter/src/main/java/org/openhab/binding/smaenergymeter/internal/discovery/SMAEnergyMeterDiscoveryService.java
  bundles/org.openhab.binding.smaenergymeter/src/main/java/org/openhab/binding/smaenergymeter/internal/handler/EnergyMeter.java
  bundles/org.openhab.binding.smaenergymeter/src/main/java/org/openhab/binding/smaenergymeter/internal/handler/FieldDTO.java
  bundles/org.openhab.binding.smaenergymeter/src/main/java/org/openhab/binding/smaenergymeter/internal/handler/SMAEnergyMeterHandler.java
  bundles/org.openhab.binding.smaenergymeter/src/main/resources/ESH-INF/binding/binding.xml
  bundles/org.openhab.binding.smaenergymeter/src/main/resources/ESH-INF/i18n/smaenergymeter_de.properties
  bundles/org.openhab.binding.smaenergymeter/src/main/resources/ESH-INF/thing/energyMeter.xml
  bundles/pom.xml
  features/karaf/openhab-addons/src/main/feature/feature.xml
Labels: infrastructure

#5306 [pentair] Migrate to bnd build
  CODEOWNERS
  addons/binding/org.openhab.binding.pentair/.classpath
  addons/binding/org.openhab.binding.pentair/META-INF/MANIFEST.MF
  addons/binding/org.openhab.binding.pentair/OSGI-INF/.gitignore
  addons/binding/org.openhab.binding.pentair/build.properties
  addons/binding/pom.xml
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.pentair/.classpath
  bundles/org.openhab.binding.pentair/.project
  bundles/org.openhab.binding.pentair/NOTICE
  bundles/org.openhab.binding.pentair/README.md
  bundles/org.openhab.binding.pentair/pom.xml
  bundles/org.openhab.binding.pentair/src/main/java/org/openhab/binding/pentair/internal/PentairBindingConstants.java
  bundles/org.openhab.binding.pentair/src/main/java/org/openhab/binding/pentair/internal/PentairHandlerFactory.java
  bundles/org.openhab.binding.pentair/src/main/java/org/openhab/binding/pentair/internal/PentairPacket.java
  bundles/org.openhab.binding.pentair/src/main/java/org/openhab/binding/pentair/internal/PentairPacketHeatSetPoint.java
  bundles/org.openhab.binding.pentair/src/main/java/org/openhab/binding/pentair/internal/PentairPacketIntellichlor.java
  bundles/org.openhab.binding.pentair/src/main/java/org/openhab/binding/pentair/internal/PentairPacketPumpStatus.java
  bundles/org.openhab.binding.pentair/src/main/java/org/openhab/binding/pentair/internal/PentairPacketStatus.java
  bundles/org.openhab.binding.pentair/src/main/java/org/openhab/binding/pentair/internal/config/PentairIPBridgeConfig.java
  bundles/org.openhab.binding.pentair/src/main/java/org/openhab/binding/pentair/internal/config/PentairSerialBridgeConfig.java
  bundles/org.openhab.binding.pentair/src/main/java/org/openhab/binding/pentair/internal/handler/PentairBaseBridgeHandler.java
  bundles/org.openhab.binding.pentair/src/main/java/org/openhab/binding/pentair/internal/handler/PentairBaseThingHandler.java
  bundles/org.openhab.binding.pentair/src/main/java/org/openhab/binding/pentair/internal/handler/PentairEasyTouchHandler.java
  bundles/org.openhab.binding.pentair/src/main/java/org/openhab/binding/pentair/internal/handler/PentairIPBridgeHandler.java
  bundles/org.openhab.binding.pentair/src/main/java/org/openhab/binding/pentair/internal/handler/PentairIntelliChlorHandler.java
  bundles/org.openhab.binding.pentair/src/main/java/org/openhab/binding/pentair/internal/handler/PentairIntelliFloHandler.java
  bundles/org.openhab.binding.pentair/src/main/java/org/openhab/binding/pentair/internal/handler/PentairSerialBridgeHandler.java
  bundles/org.openhab.binding.pentair/src/main/resources/ESH-INF/binding/binding.xml
  bundles/org.openhab.binding.pentair/src/main/resources/ESH-INF/thing/easytouch.xml
  bundles/org.openhab.binding.pentair/src/main/resources/ESH-INF/thing/intellichlor.xml
  bundles/org.openhab.binding.pentair/src/main/resources/ESH-INF/thing/intelliflo.xml
  bundles/org.openhab.binding.pentair/src/main/resources/ESH-INF/thing/ip_bridge.xml
  bundles/org.openhab.binding.pentair/src/main/resources/ESH-INF/thing/serial_bridge.xml
  bundles/pom.xml
  features/karaf/openhab-addons/src/main/feature/feature.xml
Labels: infrastructure

#5308 [oceanic] Migrate to bnd build
  CODEOWNERS
  addons/binding/org.openhab.binding.oceanic/.classpath
  addons/binding/org.openhab.binding.oceanic/META-INF/MANIFEST.MF
  addons/binding/org.openhab.binding.oceanic/OSGI-INF/.gitignore
  addons/binding/org.openhab.binding.oceanic/build.properties
  addons/binding/pom.xml
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.oceanic/.classpath
  bundles/org.openhab.binding.oceanic/.project
  bundles/org.openhab.binding.oceanic/NOTICE
  bundles/org.openhab.binding.oceanic/README.md
  bundles/org.openhab.binding.oceanic/pom.xml
  bundles/org.openhab.binding.oceanic/src/main/java/org/openhab/binding/oceanic/internal/NetworkOceanicBindingConfiguration.java
  bundles/org.openhab.binding.oceanic/src/main/java/org/openhab/binding/oceanic/internal/OceanicBindingConstants.java
  bundles/org.openhab.binding.oceanic/src/main/java/org/openhab/binding/oceanic/internal/OceanicHandlerFactory.java
  bundles/org.openhab.binding.oceanic/src/main/java/org/openhab/binding/oceanic/internal/SerialOceanicBindingConfiguration.java
  bundles/org.openhab.binding.oceanic/src/main/java/org/openhab/binding/oceanic/internal/Throttler.java
  bundles/org.openhab.binding.oceanic/src/main/java/org/openhab/binding/oceanic/internal/handler/NetworkOceanicThingHandler.java
  bundles/org.openhab.binding.oceanic/src/main/java/org/openhab/binding/oceanic/internal/handler/OceanicThingHandler.java
  bundles/org.openhab.binding.oceanic/src/main/java/org/openhab/binding/oceanic/internal/handler/SerialOceanicThingHandler.java
  bundles/org.openhab.binding.oceanic/src/main/resources/ESH-INF/binding/binding.xml
  bundles/org.openhab.binding.oceanic/src/main/resources/ESH-INF/thing/channel-types.xml
  bundles/org.openhab.binding.oceanic/src/main/resources/ESH-INF/thing/network.xml
  bundles/org.openhab.binding.oceanic/src/main/resources/ESH-INF/thing/serial.xml
  bundles/pom.xml
  features/karaf/openhab-addons/src/main/feature/feature.xml
Labels: infrastructure

#5314 [icloud] Migrate to bnd build
  CODEOWNERS
  addons/binding/org.openhab.binding.icloud/.classpath
  addons/binding/org.openhab.binding.icloud/META-INF/MANIFEST.MF
  addons/binding/org.openhab.binding.icloud/OSGI-INF/.gitignore
  addons/binding/org.openhab.binding.icloud/build.properties
  addons/binding/pom.xml
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.icloud/.classpath
  bundles/org.openhab.binding.icloud/.project
  bundles/org.openhab.binding.icloud/NOTICE
  bundles/org.openhab.binding.icloud/README.md
  bundles/org.openhab.binding.icloud/pom.xml
  bundles/org.openhab.binding.icloud/src/main/java/org/openhab/binding/icloud/internal/ICloudBindingConstants.java
  bundles/org.openhab.binding.icloud/src/main/java/org/openhab/binding/icloud/internal/ICloudConnection.java
  bundles/org.openhab.binding.icloud/src/main/java/org/openhab/binding/icloud/internal/ICloudDeviceInformationListener.java
  bundles/org.openhab.binding.icloud/src/main/java/org/openhab/binding/icloud/internal/ICloudDeviceInformationParser.java
  bundles/org.openhab.binding.icloud/src/main/java/org/openhab/binding/icloud/internal/ICloudHandlerFactory.java
  bundles/org.openhab.binding.icloud/src/main/java/org/openhab/binding/icloud/internal/ICloudTlsCertificateProvider.java
  bundles/org.openhab.binding.icloud/src/main/java/org/openhab/binding/icloud/internal/configuration/ICloudAccountThingConfiguration.java
  bundles/org.openhab.binding.icloud/src/main/java/org/openhab/binding/icloud/internal/configuration/ICloudDeviceThingConfiguration.java
  bundles/org.openhab.binding.icloud/src/main/java/org/openhab/binding/icloud/internal/discovery/ICloudDeviceDiscovery.java
  bundles/org.openhab.binding.icloud/src/main/java/org/openhab/binding/icloud/internal/handler/ICloudAccountBridgeHandler.java
  bundles/org.openhab.binding.icloud/src/main/java/org/openhab/binding/icloud/internal/handler/ICloudDeviceHandler.java
  bundles/org.openhab.binding.icloud/src/main/java/org/openhab/binding/icloud/internal/json/request/ICloudAccountDataRequest.java
  bundles/org.openhab.binding.icloud/src/main/java/org/openhab/binding/icloud/internal/json/request/ICloudFindMyDeviceRequest.java
  bundles/org.openhab.binding.icloud/src/main/java/org/openhab/binding/icloud/internal/json/response/ICloudAccountDataResponse.java
  bundles/org.openhab.binding.icloud/src/main/java/org/openhab/binding/icloud/internal/json/response/ICloudAccountUserInfo.java
  bundles/org.openhab.binding.icloud/src/main/java/org/openhab/binding/icloud/internal/json/response/ICloudDeviceFeatures.java
  bundles/org.openhab.binding.icloud/src/main/java/org/openhab/binding/icloud/internal/json/response/ICloudDeviceInformation.java
  bundles/org.openhab.binding.icloud/src/main/java/org/openhab/binding/icloud/internal/json/response/ICloudDeviceLocation.java
  bundles/org.openhab.binding.icloud/src/main/java/org/openhab/binding/icloud/internal/json/response/ICloudServerContext.java
  bundles/org.openhab.binding.icloud/src/main/java/org/openhab/binding/icloud/internal/json/response/ICloudServerContextTimezone.java
  bundles/org.openhab.binding.icloud/src/main/java/org/openhab/binding/icloud/internal/utilities/ICloudTextTranslator.java
  bundles/org.openhab.binding.icloud/src/main/resources/ESH-INF/binding/binding.xml
  bundles/org.openhab.binding.icloud/src/main/resources/ESH-INF/i18n/iCloud.properties
  bundles/org.openhab.binding.icloud/src/main/resources/ESH-INF/i18n/iCloud_fr.properties
  bundles/org.openhab.binding.icloud/src/main/resources/ESH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.icloud/src/main/resources/fmipmobile.crt
  bundles/pom.xml
  features/karaf/openhab-addons/src/main/feature/feature.xml
Labels: infrastructure

#5319 [autelis] Migrate to bnd build
  CODEOWNERS
  addons/binding/org.openhab.binding.autelis/.classpath
  addons/binding/org.openhab.binding.autelis/META-INF/MANIFEST.MF
  addons/binding/org.openhab.binding.autelis/OSGI-INF/.gitignore
  addons/binding/org.openhab.binding.autelis/build.properties
  addons/binding/pom.xml
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.autelis/.classpath
  bundles/org.openhab.binding.autelis/.project
  bundles/org.openhab.binding.autelis/NOTICE
  bundles/org.openhab.binding.autelis/README.md
  bundles/org.openhab.binding.autelis/pom.xml
  bundles/org.openhab.binding.autelis/src/main/java/org/openhab/binding/autelis/internal/AutelisBindingConstants.java
  bundles/org.openhab.binding.autelis/src/main/java/org/openhab/binding/autelis/internal/AutelisHandlerFactory.java
  bundles/org.openhab.binding.autelis/src/main/java/org/openhab/binding/autelis/internal/config/AutelisConfiguration.java
  bundles/org.openhab.binding.autelis/src/main/java/org/openhab/binding/autelis/internal/discovery/AutelisDiscoveryParticipant.java
  bundles/org.openhab.binding.autelis/src/main/java/org/openhab/binding/autelis/internal/handler/AutelisHandler.java
  bundles/org.openhab.binding.autelis/src/main/resources/ESH-INF/binding/binding.xml
  bundles/org.openhab.binding.autelis/src/main/resources/ESH-INF/thing/jandy.xml
  bundles/org.openhab.binding.autelis/src/main/resources/ESH-INF/thing/pentair.xml
  bundles/pom.xml
  features/karaf/openhab-addons/src/main/feature/feature.xml
Labels: infrastructure

#5328 [lutron] Remove dependency on google guava library.
  addons/binding/org.openhab.binding.lutron/META-INF/MANIFEST.MF
  addons/binding/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/LutronHandlerFactory.java
  addons/binding/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/handler/BaseKeypadHandler.java
Labels: infrastructure

#5286 [km200] Migrate to bnd build
  CODEOWNERS
  addons/binding/org.openhab.binding.km200/.classpath
  addons/binding/org.openhab.binding.km200/META-INF/MANIFEST.MF
  addons/binding/org.openhab.binding.km200/OSGI-INF/.gitignore
  addons/binding/org.openhab.binding.km200/build.properties
  addons/binding/pom.xml
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.km200/.classpath
  bundles/org.openhab.binding.km200/.project
  bundles/org.openhab.binding.km200/NOTICE
  bundles/org.openhab.binding.km200/README.md
  bundles/org.openhab.binding.km200/pom.xml
  bundles/org.openhab.binding.km200/src/main/java/org/openhab/binding/km200/internal/KM200BindingConstants.java
  bundles/org.openhab.binding.km200/src/main/java/org/openhab/binding/km200/internal/KM200ChannelTypeProvider.java
  bundles/org.openhab.binding.km200/src/main/java/org/openhab/binding/km200/internal/KM200Comm.java
  bundles/org.openhab.binding.km200/src/main/java/org/openhab/binding/km200/internal/KM200Cryption.java
  bundles/org.openhab.binding.km200/src/main/java/org/openhab/binding/km200/internal/KM200Device.java
  bundles/org.openhab.binding.km200/src/main/java/org/openhab/binding/km200/internal/KM200HandlerFactory.java
  bundles/org.openhab.binding.km200/src/main/java/org/openhab/binding/km200/internal/KM200ServiceObject.java
  bundles/org.openhab.binding.km200/src/main/java/org/openhab/binding/km200/internal/KM200ThingType.java
  bundles/org.openhab.binding.km200/src/main/java/org/openhab/binding/km200/internal/KM200Utils.java
  bundles/org.openhab.binding.km200/src/main/java/org/openhab/binding/km200/internal/discovery/KM200GatewayDiscoveryParticipant.java
  bundles/org.openhab.binding.km200/src/main/java/org/openhab/binding/km200/internal/discovery/KM200GatewayDiscoveryService.java
  bundles/org.openhab.binding.km200/src/main/java/org/openhab/binding/km200/internal/handler/KM200DataHandler.java
  bundles/org.openhab.binding.km200/src/main/java/org/openhab/binding/km200/internal/handler/KM200ErrorServiceHandler.java
  bundles/org.openhab.binding.km200/src/main/java/org/openhab/binding/km200/internal/handler/KM200GatewayHandler.java
  bundles/org.openhab.binding.km200/src/main/java/org/openhab/binding/km200/internal/handler/KM200GatewayStatusListener.java
  bundles/org.openhab.binding.km200/src/main/java/org/openhab/binding/km200/internal/handler/KM200ServiceHandler.java
  bundles/org.openhab.binding.km200/src/main/java/org/openhab/binding/km200/internal/handler/KM200SwitchProgramServiceHandler.java
  bundles/org.openhab.binding.km200/src/main/java/org/openhab/binding/km200/internal/handler/KM200ThingHandler.java
  bundles/org.openhab.binding.km200/src/main/java/org/openhab/binding/km200/internal/handler/KM200VirtualServiceHandler.java
  bundles/org.openhab.binding.km200/src/main/resources/ESH-INF/binding/binding.xml
  bundles/org.openhab.binding.km200/src/main/resources/ESH-INF/thing/appliance.xml
  bundles/org.openhab.binding.km200/src/main/resources/ESH-INF/thing/device.xml
  bundles/org.openhab.binding.km200/src/main/resources/ESH-INF/thing/dhwCircuit.xml
  bundles/org.openhab.binding.km200/src/main/resources/ESH-INF/thing/gateway.xml
  bundles/org.openhab.binding.km200/src/main/resources/ESH-INF/thing/heatSource.xml
  bundles/org.openhab.binding.km200/src/main/resources/ESH-INF/thing/heatingCircuit.xml
  bundles/org.openhab.binding.km200/src/main/resources/ESH-INF/thing/holidayMode.xml
  bundles/org.openhab.binding.km200/src/main/resources/ESH-INF/thing/notification.xml
  bundles/org.openhab.binding.km200/src/main/resources/ESH-INF/thing/sensor.xml
  bundles/org.openhab.binding.km200/src/main/resources/ESH-INF/thing/solarCircuit.xml
  bundles/org.openhab.binding.km200/src/main/resources/ESH-INF/thing/switchProgram.xml
  bundles/org.openhab.binding.km200/src/main/resources/ESH-INF/thing/system.xml
  bundles/pom.xml
  features/karaf/openhab-addons/src/main/feature/feature.xml
Labels: infrastructure

#5310 [milight] Migrate to bnd build
  CODEOWNERS
  addons/binding/org.openhab.binding.milight/.classpath
  addons/binding/org.openhab.binding.milight/META-INF/MANIFEST.MF
  addons/binding/org.openhab.binding.milight/OSGI-INF/.gitignore
  addons/binding/org.openhab.binding.milight/build.properties
  addons/binding/pom.xml
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.milight/.classpath
  bundles/org.openhab.binding.milight/.gitignore
  bundles/org.openhab.binding.milight/.project
  bundles/org.openhab.binding.milight/NOTICE
  bundles/org.openhab.binding.milight/README.md
  bundles/org.openhab.binding.milight/pom.xml
  bundles/org.openhab.binding.milight/src/main/java/org/openhab/binding/milight/internal/MilightBindingConstants.java
  bundles/org.openhab.binding.milight/src/main/java/org/openhab/binding/milight/internal/MilightHandlerFactory.java
  bundles/org.openhab.binding.milight/src/main/java/org/openhab/binding/milight/internal/MilightThingState.java
  bundles/org.openhab.binding.milight/src/main/java/org/openhab/binding/milight/internal/discovery/DiscoveryResultListener.java
  bundles/org.openhab.binding.milight/src/main/java/org/openhab/binding/milight/internal/discovery/MilightBridgeDiscovery.java
  bundles/org.openhab.binding.milight/src/main/java/org/openhab/binding/milight/internal/handler/AbstractBridgeHandler.java
  bundles/org.openhab.binding.milight/src/main/java/org/openhab/binding/milight/internal/handler/AbstractLedHandler.java
  bundles/org.openhab.binding.milight/src/main/java/org/openhab/binding/milight/internal/handler/AbstractLedV3Handler.java
  bundles/org.openhab.binding.milight/src/main/java/org/openhab/binding/milight/internal/handler/AbstractLedV6Handler.java
  bundles/org.openhab.binding.milight/src/main/java/org/openhab/binding/milight/internal/handler/BridgeHandlerConfig.java
  bundles/org.openhab.binding.milight/src/main/java/org/openhab/binding/milight/internal/handler/BridgeV3Handler.java
  bundles/org.openhab.binding.milight/src/main/java/org/openhab/binding/milight/internal/handler/BridgeV6Handler.java
  bundles/org.openhab.binding.milight/src/main/java/org/openhab/binding/milight/internal/handler/LedHandlerConfig.java
  bundles/org.openhab.binding.milight/src/main/java/org/openhab/binding/milight/internal/handler/LedHandlerInterface.java
  bundles/org.openhab.binding.milight/src/main/java/org/openhab/binding/milight/internal/handler/MilightV2RGBHandler.java
  bundles/org.openhab.binding.milight/src/main/java/org/openhab/binding/milight/internal/handler/MilightV3RGBWHandler.java
  bundles/org.openhab.binding.milight/src/main/java/org/openhab/binding/milight/internal/handler/MilightV3WhiteHandler.java
  bundles/org.openhab.binding.milight/src/main/java/org/openhab/binding/milight/internal/handler/MilightV6RGBCWWWHandler.java
  bundles/org.openhab.binding.milight/src/main/java/org/openhab/binding/milight/internal/handler/MilightV6RGBIBOXHandler.java
  bundles/org.openhab.binding.milight/src/main/java/org/openhab/binding/milight/internal/handler/MilightV6RGBWHandler.java
  bundles/org.openhab.binding.milight/src/main/java/org/openhab/binding/milight/internal/protocol/MilightV6SessionManager.java
  bundles/org.openhab.binding.milight/src/main/java/org/openhab/binding/milight/internal/protocol/ProtocolConstants.java
  bundles/org.openhab.binding.milight/src/main/java/org/openhab/binding/milight/internal/protocol/QueueItem.java
  bundles/org.openhab.binding.milight/src/main/java/org/openhab/binding/milight/internal/protocol/QueuedSend.java
  bundles/org.openhab.binding.milight/src/main/java/org/openhab/binding/milight/internal/test/EmulatedV6Bridge.java
  bundles/org.openhab.binding.milight/src/main/java/org/openhab/binding/milight/internal/test/TestDiscovery.java
  bundles/org.openhab.binding.milight/src/main/resources/ESH-INF/binding/binding.xml
  bundles/org.openhab.binding.milight/src/main/resources/ESH-INF/thing/channels.xml
  bundles/org.openhab.binding.milight/src/main/resources/ESH-INF/thing/v2.xml
  bundles/org.openhab.binding.milight/src/main/resources/ESH-INF/thing/v3.xml
  bundles/org.openhab.binding.milight/src/main/resources/ESH-INF/thing/v6.xml
  bundles/pom.xml
  features/karaf/openhab-addons/src/main/feature/feature.xml
Labels: infrastructure

#5304 [russound] Migrate to bnd build
  CODEOWNERS
  addons/binding/org.openhab.binding.russound/.classpath
  addons/binding/org.openhab.binding.russound/META-INF/MANIFEST.MF
  addons/binding/org.openhab.binding.russound/OSGI-INF/.gitignore
  addons/binding/org.openhab.binding.russound/build.properties
  addons/binding/pom.xml
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.russound/.classpath
  bundles/org.openhab.binding.russound/.project
  bundles/org.openhab.binding.russound/NOTICE
  bundles/org.openhab.binding.russound/README.md
  bundles/org.openhab.binding.russound/pom.xml
  bundles/org.openhab.binding.russound/src/main/java/org/openhab/binding/russound/internal/RussoundBindingConstants.java
  bundles/org.openhab.binding.russound/src/main/java/org/openhab/binding/russound/internal/RussoundHandlerFactory.java
  bundles/org.openhab.binding.russound/src/main/java/org/openhab/binding/russound/internal/discovery/RioSystemDeviceDiscoveryService.java
  bundles/org.openhab.binding.russound/src/main/java/org/openhab/binding/russound/internal/discovery/RioSystemDiscovery.java
  bundles/org.openhab.binding.russound/src/main/java/org/openhab/binding/russound/internal/net/SocketChannelSession.java
  bundles/org.openhab.binding.russound/src/main/java/org/openhab/binding/russound/internal/net/SocketSession.java
  bundles/org.openhab.binding.russound/src/main/java/org/openhab/binding/russound/internal/net/SocketSessionListener.java
  bundles/org.openhab.binding.russound/src/main/java/org/openhab/binding/russound/internal/net/WaitingSessionListener.java
  bundles/org.openhab.binding.russound/src/main/java/org/openhab/binding/russound/internal/rio/AbstractBridgeHandler.java
  bundles/org.openhab.binding.russound/src/main/java/org/openhab/binding/russound/internal/rio/AbstractRioHandlerCallback.java
  bundles/org.openhab.binding.russound/src/main/java/org/openhab/binding/russound/internal/rio/AbstractRioProtocol.java
  bundles/org.openhab.binding.russound/src/main/java/org/openhab/binding/russound/internal/rio/AbstractThingHandler.java
  bundles/org.openhab.binding.russound/src/main/java/org/openhab/binding/russound/internal/rio/RioCallbackHandler.java
  bundles/org.openhab.binding.russound/src/main/java/org/openhab/binding/russound/internal/rio/RioConstants.java
  bundles/org.openhab.binding.russound/src/main/java/org/openhab/binding/russound/internal/rio/RioHandlerCallback.java
  bundles/org.openhab.binding.russound/src/main/java/org/openhab/binding/russound/internal/rio/RioHandlerCallbackListener.java
  bundles/org.openhab.binding.russound/src/main/java/org/openhab/binding/russound/internal/rio/RioNamedHandler.java
  bundles/org.openhab.binding.russound/src/main/java/org/openhab/binding/russound/internal/rio/RioPresetsProtocol.java
  bundles/org.openhab.binding.russound/src/main/java/org/openhab/binding/russound/internal/rio/RioSystemFavoritesProtocol.java
  bundles/org.openhab.binding.russound/src/main/java/org/openhab/binding/russound/internal/rio/StatefulHandlerCallback.java
  bundles/org.openhab.binding.russound/src/main/java/org/openhab/binding/russound/internal/rio/controller/RioControllerConfig.java
  bundles/org.openhab.binding.russound/src/main/java/org/openhab/binding/russound/internal/rio/controller/RioControllerHandler.java
  bundles/org.openhab.binding.russound/src/main/java/org/openhab/binding/russound/internal/rio/controller/RioControllerProtocol.java
  bundles/org.openhab.binding.russound/src/main/java/org/openhab/binding/russound/internal/rio/models/AtomicStringTypeAdapter.java
  bundles/org.openhab.binding.russound/src/main/java/org/openhab/binding/russound/internal/rio/models/GsonUtilities.java
  bundles/org.openhab.binding.russound/src/main/java/org/openhab/binding/russound/internal/rio/models/RioBank.java
  bundles/org.openhab.binding.russound/src/main/java/org/openhab/binding/russound/internal/rio/models/RioBankSerializer.java
  bundles/org.openhab.binding.russound/src/main/java/org/openhab/binding/russound/internal/rio/models/RioFavorite.java
  bundles/org.openhab.binding.russound/src/main/java/org/openhab/binding/russound/internal/rio/models/RioFavoriteSerializer.java
  bundles/org.openhab.binding.russound/src/main/java/org/openhab/binding/russound/internal/rio/models/RioPreset.java
  bundles/org.openhab.binding.russound/src/main/java/org/openhab/binding/russound/internal/rio/models/RioPresetSerializer.java
  bundles/org.openhab.binding.russound/src/main/java/org/openhab/binding/russound/internal/rio/source/RioSourceConfig.java
  bundles/org.openhab.binding.russound/src/main/java/org/openhab/binding/russound/internal/rio/source/RioSourceHandler.java
  bundles/org.openhab.binding.russound/src/main/java/org/openhab/binding/russound/internal/rio/source/RioSourceProtocol.java
  bundles/org.openhab.binding.russound/src/main/java/org/openhab/binding/russound/internal/rio/system/RioSystemConfig.java
  bundles/org.openhab.binding.russound/src/main/java/org/openhab/binding/russound/internal/rio/system/RioSystemHandler.java
  bundles/org.openhab.binding.russound/src/main/java/org/openhab/binding/russound/internal/rio/system/RioSystemProtocol.java
  bundles/org.openhab.binding.russound/src/main/java/org/openhab/binding/russound/internal/rio/zone/RioZoneConfig.java
  bundles/org.openhab.binding.russound/src/main/java/org/openhab/binding/russound/internal/rio/zone/RioZoneHandler.java
  bundles/org.openhab.binding.russound/src/main/java/org/openhab/binding/russound/internal/rio/zone/RioZoneProtocol.java
  bundles/org.openhab.binding.russound/src/main/resources/ESH-INF/binding/binding.xml
  bundles/org.openhab.binding.russound/src/main/resources/ESH-INF/thing/thing-types.xml
  bundles/pom.xml
  features/karaf/openhab-addons/src/main/feature/feature.xml
Labels: infrastructure

#5311 [meteostick] Migrate to bnd build
  CODEOWNERS
  addons/binding/org.openhab.binding.meteostick/.classpath
  addons/binding/org.openhab.binding.meteostick/META-INF/MANIFEST.MF
  addons/binding/org.openhab.binding.meteostick/OSGI-INF/.gitignore
  addons/binding/org.openhab.binding.meteostick/build.properties
  addons/binding/pom.xml
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.meteostick/.classpath
  bundles/org.openhab.binding.meteostick/.project
  bundles/org.openhab.binding.meteostick/NOTICE
  bundles/org.openhab.binding.meteostick/README.md
  bundles/org.openhab.binding.meteostick/pom.xml
  bundles/org.openhab.binding.meteostick/src/main/java/org/openhab/binding/meteostick/internal/MeteostickBindingConstants.java
  bundles/org.openhab.binding.meteostick/src/main/java/org/openhab/binding/meteostick/internal/MeteostickHandlerFactory.java
  bundles/org.openhab.binding.meteostick/src/main/java/org/openhab/binding/meteostick/internal/handler/MeteostickBridgeHandler.java
  bundles/org.openhab.binding.meteostick/src/main/java/org/openhab/binding/meteostick/internal/handler/MeteostickEventListener.java
  bundles/org.openhab.binding.meteostick/src/main/java/org/openhab/binding/meteostick/internal/handler/MeteostickSensorHandler.java
  bundles/org.openhab.binding.meteostick/src/main/resources/ESH-INF/binding/binding.xml
  bundles/org.openhab.binding.meteostick/src/main/resources/ESH-INF/thing/thing-types.xml
  bundles/pom.xml
  features/karaf/openhab-addons/src/main/feature/feature.xml
Labels: infrastructure

#5315 [fronius] Migrate to bnd build
  CODEOWNERS
  addons/binding/org.openhab.binding.fronius/.classpath
  addons/binding/org.openhab.binding.fronius/META-INF/MANIFEST.MF
  addons/binding/org.openhab.binding.fronius/OSGI-INF/.gitignore
  addons/binding/org.openhab.binding.fronius/build.properties
  addons/binding/pom.xml
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.fronius/.classpath
  bundles/org.openhab.binding.fronius/.project
  bundles/org.openhab.binding.fronius/NOTICE
  bundles/org.openhab.binding.fronius/README.md
  bundles/org.openhab.binding.fronius/pom.xml
  bundles/org.openhab.binding.fronius/src/main/java/org/openhab/binding/fronius/internal/FroniusBaseDeviceConfiguration.java
  bundles/org.openhab.binding.fronius/src/main/java/org/openhab/binding/fronius/internal/FroniusBindingConstants.java
  bundles/org.openhab.binding.fronius/src/main/java/org/openhab/binding/fronius/internal/FroniusBridgeConfiguration.java
  bundles/org.openhab.binding.fronius/src/main/java/org/openhab/binding/fronius/internal/FroniusHandlerFactory.java
  bundles/org.openhab.binding.fronius/src/main/java/org/openhab/binding/fronius/internal/api/BaseFroniusResponse.java
  bundles/org.openhab.binding.fronius/src/main/java/org/openhab/binding/fronius/internal/api/DeviceStatus.java
  bundles/org.openhab.binding.fronius/src/main/java/org/openhab/binding/fronius/internal/api/Head.java
  bundles/org.openhab.binding.fronius/src/main/java/org/openhab/binding/fronius/internal/api/HeadRequestArguments.java
  bundles/org.openhab.binding.fronius/src/main/java/org/openhab/binding/fronius/internal/api/HeadStatus.java
  bundles/org.openhab.binding.fronius/src/main/java/org/openhab/binding/fronius/internal/api/InverterRealtimeBody.java
  bundles/org.openhab.binding.fronius/src/main/java/org/openhab/binding/fronius/internal/api/InverterRealtimeBodyData.java
  bundles/org.openhab.binding.fronius/src/main/java/org/openhab/binding/fronius/internal/api/InverterRealtimeResponse.java
  bundles/org.openhab.binding.fronius/src/main/java/org/openhab/binding/fronius/internal/api/PowerFlowRealtimeBody.java
  bundles/org.openhab.binding.fronius/src/main/java/org/openhab/binding/fronius/internal/api/PowerFlowRealtimeBodyData.java
  bundles/org.openhab.binding.fronius/src/main/java/org/openhab/binding/fronius/internal/api/PowerFlowRealtimeInverter.java
  bundles/org.openhab.binding.fronius/src/main/java/org/openhab/binding/fronius/internal/api/PowerFlowRealtimeResponse.java
  bundles/org.openhab.binding.fronius/src/main/java/org/openhab/binding/fronius/internal/api/PowerFlowRealtimeSite.java
  bundles/org.openhab.binding.fronius/src/main/java/org/openhab/binding/fronius/internal/api/ValueUnit.java
  bundles/org.openhab.binding.fronius/src/main/java/org/openhab/binding/fronius/internal/handler/FroniusBaseThingHandler.java
  bundles/org.openhab.binding.fronius/src/main/java/org/openhab/binding/fronius/internal/handler/FroniusBridgeHandler.java
  bundles/org.openhab.binding.fronius/src/main/java/org/openhab/binding/fronius/internal/handler/FroniusSymoInverterHandler.java
  bundles/org.openhab.binding.fronius/src/main/java/org/openhab/binding/fronius/internal/math/KilowattConverter.java
  bundles/org.openhab.binding.fronius/src/main/java/org/openhab/binding/fronius/internal/math/SiPrefixFactors.java
  bundles/org.openhab.binding.fronius/src/main/resources/ESH-INF/binding/binding.xml
  bundles/org.openhab.binding.fronius/src/main/resources/ESH-INF/thing/bridge.xml
  bundles/org.openhab.binding.fronius/src/main/resources/ESH-INF/thing/thing-types.xml
  bundles/pom.xml
  features/karaf/openhab-addons/src/main/feature/feature.xml
Labels: infrastructure

#5293 [silvercrestwifisocket] Migrate to bnd build
  CODEOWNERS
  addons/binding/org.openhab.binding.silvercrestwifisocket/.classpath
  addons/binding/org.openhab.binding.silvercrestwifisocket/META-INF/MANIFEST.MF
  addons/binding/org.openhab.binding.silvercrestwifisocket/OSGI-INF/.gitignore
  addons/binding/org.openhab.binding.silvercrestwifisocket/build.properties
  addons/binding/pom.xml
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.silvercrestwifisocket/.classpath
  bundles/org.openhab.binding.silvercrestwifisocket/.project
  bundles/org.openhab.binding.silvercrestwifisocket/NOTICE
  bundles/org.openhab.binding.silvercrestwifisocket/README.md
  bundles/org.openhab.binding.silvercrestwifisocket/pom.xml
  bundles/org.openhab.binding.silvercrestwifisocket/src/main/java/org/openhab/binding/silvercrestwifisocket/internal/SilvercrestWifiSocketBindingConstants.java
  bundles/org.openhab.binding.silvercrestwifisocket/src/main/java/org/openhab/binding/silvercrestwifisocket/internal/SilvercrestWifiSocketHandlerFactory.java
  bundles/org.openhab.binding.silvercrestwifisocket/src/main/java/org/openhab/binding/silvercrestwifisocket/internal/discovery/SilvercrestWifiSocketDiscoveryService.java
  bundles/org.openhab.binding.silvercrestwifisocket/src/main/java/org/openhab/binding/silvercrestwifisocket/internal/entities/SilvercrestWifiSocketRequest.java
  bundles/org.openhab.binding.silvercrestwifisocket/src/main/java/org/openhab/binding/silvercrestwifisocket/internal/entities/SilvercrestWifiSocketResponse.java
  bundles/org.openhab.binding.silvercrestwifisocket/src/main/java/org/openhab/binding/silvercrestwifisocket/internal/enums/SilvercrestWifiSocketRequestType.java
  bundles/org.openhab.binding.silvercrestwifisocket/src/main/java/org/openhab/binding/silvercrestwifisocket/internal/enums/SilvercrestWifiSocketResponseType.java
  bundles/org.openhab.binding.silvercrestwifisocket/src/main/java/org/openhab/binding/silvercrestwifisocket/internal/enums/SilvercrestWifiSocketVendor.java
  bundles/org.openhab.binding.silvercrestwifisocket/src/main/java/org/openhab/binding/silvercrestwifisocket/internal/exceptions/MacAddressNotValidException.java
  bundles/org.openhab.binding.silvercrestwifisocket/src/main/java/org/openhab/binding/silvercrestwifisocket/internal/exceptions/NotOneResponsePacketException.java
  bundles/org.openhab.binding.silvercrestwifisocket/src/main/java/org/openhab/binding/silvercrestwifisocket/internal/exceptions/PacketIntegrityErrorException.java
  bundles/org.openhab.binding.silvercrestwifisocket/src/main/java/org/openhab/binding/silvercrestwifisocket/internal/handler/SilvercrestWifiSocketHandler.java
  bundles/org.openhab.binding.silvercrestwifisocket/src/main/java/org/openhab/binding/silvercrestwifisocket/internal/handler/SilvercrestWifiSocketMediator.java
  bundles/org.openhab.binding.silvercrestwifisocket/src/main/java/org/openhab/binding/silvercrestwifisocket/internal/handler/SilvercrestWifiSocketMediatorImpl.java
  bundles/org.openhab.binding.silvercrestwifisocket/src/main/java/org/openhab/binding/silvercrestwifisocket/internal/runnable/SilvercrestWifiSocketUpdateReceiverRunnable.java
  bundles/org.openhab.binding.silvercrestwifisocket/src/main/java/org/openhab/binding/silvercrestwifisocket/internal/utils/NetworkUtils.java
  bundles/org.openhab.binding.silvercrestwifisocket/src/main/java/org/openhab/binding/silvercrestwifisocket/internal/utils/ValidationUtils.java
  bundles/org.openhab.binding.silvercrestwifisocket/src/main/java/org/openhab/binding/silvercrestwifisocket/internal/utils/WifiSocketPacketConverter.java
  bundles/org.openhab.binding.silvercrestwifisocket/src/main/resources/ESH-INF/binding/binding.xml
  bundles/org.openhab.binding.silvercrestwifisocket/src/main/resources/ESH-INF/thing/thing-types.xml
  bundles/pom.xml
  features/karaf/openhab-addons/src/main/feature/feature.xml
Labels: infrastructure

#5309 [nuki] Migrate to bnd build
  CODEOWNERS
  addons/binding/org.openhab.binding.nuki/.classpath
  addons/binding/org.openhab.binding.nuki/META-INF/MANIFEST.MF
  addons/binding/org.openhab.binding.nuki/OSGI-INF/.gitignore
  addons/binding/org.openhab.binding.nuki/build.properties
  addons/binding/pom.xml
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.nuki/.classpath
  bundles/org.openhab.binding.nuki/.project
  bundles/org.openhab.binding.nuki/NOTICE
  bundles/org.openhab.binding.nuki/README.md
  bundles/org.openhab.binding.nuki/pom.xml
  bundles/org.openhab.binding.nuki/src/main/java/org/openhab/binding/nuki/internal/NukiBindingConstants.java
  bundles/org.openhab.binding.nuki/src/main/java/org/openhab/binding/nuki/internal/NukiHandlerFactory.java
  bundles/org.openhab.binding.nuki/src/main/java/org/openhab/binding/nuki/internal/converter/LockActionConverter.java
  bundles/org.openhab.binding.nuki/src/main/java/org/openhab/binding/nuki/internal/dataexchange/BridgeCallbackAddResponse.java
  bundles/org.openhab.binding.nuki/src/main/java/org/openhab/binding/nuki/internal/dataexchange/BridgeCallbackListResponse.java
  bundles/org.openhab.binding.nuki/src/main/java/org/openhab/binding/nuki/internal/dataexchange/BridgeCallbackRemoveResponse.java
  bundles/org.openhab.binding.nuki/src/main/java/org/openhab/binding/nuki/internal/dataexchange/BridgeInfoResponse.java
  bundles/org.openhab.binding.nuki/src/main/java/org/openhab/binding/nuki/internal/dataexchange/BridgeLockActionResponse.java
  bundles/org.openhab.binding.nuki/src/main/java/org/openhab/binding/nuki/internal/dataexchange/BridgeLockStateResponse.java
  bundles/org.openhab.binding.nuki/src/main/java/org/openhab/binding/nuki/internal/dataexchange/NukiApiServlet.java
  bundles/org.openhab.binding.nuki/src/main/java/org/openhab/binding/nuki/internal/dataexchange/NukiBaseResponse.java
  bundles/org.openhab.binding.nuki/src/main/java/org/openhab/binding/nuki/internal/dataexchange/NukiHttpClient.java
  bundles/org.openhab.binding.nuki/src/main/java/org/openhab/binding/nuki/internal/dto/BridgeApiCallbackAddDto.java
  bundles/org.openhab.binding.nuki/src/main/java/org/openhab/binding/nuki/internal/dto/BridgeApiCallbackListCallbackDto.java
  bundles/org.openhab.binding.nuki/src/main/java/org/openhab/binding/nuki/internal/dto/BridgeApiCallbackListDto.java
  bundles/org.openhab.binding.nuki/src/main/java/org/openhab/binding/nuki/internal/dto/BridgeApiCallbackRemoveDto.java
  bundles/org.openhab.binding.nuki/src/main/java/org/openhab/binding/nuki/internal/dto/BridgeApiInfoDto.java
  bundles/org.openhab.binding.nuki/src/main/java/org/openhab/binding/nuki/internal/dto/BridgeApiInfoIdDto.java
  bundles/org.openhab.binding.nuki/src/main/java/org/openhab/binding/nuki/internal/dto/BridgeApiInfoScanResultDto.java
  bundles/org.openhab.binding.nuki/src/main/java/org/openhab/binding/nuki/internal/dto/BridgeApiInfoVersionDto.java
  bundles/org.openhab.binding.nuki/src/main/java/org/openhab/binding/nuki/internal/dto/BridgeApiLockActionDto.java
  bundles/org.openhab.binding.nuki/src/main/java/org/openhab/binding/nuki/internal/dto/BridgeApiLockStateDto.java
  bundles/org.openhab.binding.nuki/src/main/java/org/openhab/binding/nuki/internal/dto/BridgeApiLockStateRequestDto.java
  bundles/org.openhab.binding.nuki/src/main/java/org/openhab/binding/nuki/internal/dto/NukiHttpServerStatusResponseDto.java
  bundles/org.openhab.binding.nuki/src/main/java/org/openhab/binding/nuki/internal/handler/NukiBridgeHandler.java
  bundles/org.openhab.binding.nuki/src/main/java/org/openhab/binding/nuki/internal/handler/NukiSmartLockHandler.java
  bundles/org.openhab.binding.nuki/src/main/resources/ESH-INF/binding/binding.xml
  bundles/org.openhab.binding.nuki/src/main/resources/ESH-INF/thing/thing-types.xml
  bundles/pom.xml
  features/karaf/openhab-addons/src/main/feature/feature.xml
Labels: infrastructure

#5318 [cm11a] Migrate to bnd build
  CODEOWNERS
  addons/binding/org.openhab.binding.cm11a/.classpath
  addons/binding/org.openhab.binding.cm11a/META-INF/MANIFEST.MF
  addons/binding/org.openhab.binding.cm11a/OSGI-INF/.gitignore
  addons/binding/org.openhab.binding.cm11a/build.properties
  addons/binding/pom.xml
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.cm11a/.classpath
  bundles/org.openhab.binding.cm11a/.project
  bundles/org.openhab.binding.cm11a/NOTICE
  bundles/org.openhab.binding.cm11a/README.md
  bundles/org.openhab.binding.cm11a/pom.xml
  bundles/org.openhab.binding.cm11a/src/main/java/org/openhab/binding/cm11a/internal/CM11ABindingConstants.java
  bundles/org.openhab.binding.cm11a/src/main/java/org/openhab/binding/cm11a/internal/Cm11aHandlerFactory.java
  bundles/org.openhab.binding.cm11a/src/main/java/org/openhab/binding/cm11a/internal/InvalidAddressException.java
  bundles/org.openhab.binding.cm11a/src/main/java/org/openhab/binding/cm11a/internal/X10Interface.java
  bundles/org.openhab.binding.cm11a/src/main/java/org/openhab/binding/cm11a/internal/X10ReceivedData.java
  bundles/org.openhab.binding.cm11a/src/main/java/org/openhab/binding/cm11a/internal/config/Cm11aConfig.java
  bundles/org.openhab.binding.cm11a/src/main/java/org/openhab/binding/cm11a/internal/handler/Cm11aAbstractHandler.java
  bundles/org.openhab.binding.cm11a/src/main/java/org/openhab/binding/cm11a/internal/handler/Cm11aApplianceHandler.java
  bundles/org.openhab.binding.cm11a/src/main/java/org/openhab/binding/cm11a/internal/handler/Cm11aBridgeHandler.java
  bundles/org.openhab.binding.cm11a/src/main/java/org/openhab/binding/cm11a/internal/handler/Cm11aLampHandler.java
  bundles/org.openhab.binding.cm11a/src/main/java/org/openhab/binding/cm11a/internal/handler/ReceivedDataListener.java
  bundles/org.openhab.binding.cm11a/src/main/resources/ESH-INF/binding/binding.xml
  bundles/org.openhab.binding.cm11a/src/main/resources/ESH-INF/thing/thing-types.xml
  bundles/pom.xml
  features/karaf/openhab-addons/src/main/feature/feature.xml
Labels: infrastructure

#5316 [elerotransmitterstick] Migrate to bnd build
  CODEOWNERS
  addons/binding/org.openhab.binding.elerotransmitterstick/.classpath
  addons/binding/org.openhab.binding.elerotransmitterstick/META-INF/MANIFEST.MF
  addons/binding/org.openhab.binding.elerotransmitterstick/OSGI-INF/.gitignore
  addons/binding/org.openhab.binding.elerotransmitterstick/build.properties
  addons/binding/pom.xml
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.elerotransmitterstick/.classpath
  bundles/org.openhab.binding.elerotransmitterstick/.project
  bundles/org.openhab.binding.elerotransmitterstick/NOTICE
  bundles/org.openhab.binding.elerotransmitterstick/README.md
  bundles/org.openhab.binding.elerotransmitterstick/pom.xml
  bundles/org.openhab.binding.elerotransmitterstick/src/main/java/org/openhab/binding/elerotransmitterstick/internal/EleroTransmitterStickBindingConstants.java
  bundles/org.openhab.binding.elerotransmitterstick/src/main/java/org/openhab/binding/elerotransmitterstick/internal/EleroTransmitterStickHandlerFactory.java
  bundles/org.openhab.binding.elerotransmitterstick/src/main/java/org/openhab/binding/elerotransmitterstick/internal/config/EleroChannelConfig.java
  bundles/org.openhab.binding.elerotransmitterstick/src/main/java/org/openhab/binding/elerotransmitterstick/internal/config/EleroTransmitterStickConfig.java
  bundles/org.openhab.binding.elerotransmitterstick/src/main/java/org/openhab/binding/elerotransmitterstick/internal/discovery/EleroChannelDiscoveryService.java
  bundles/org.openhab.binding.elerotransmitterstick/src/main/java/org/openhab/binding/elerotransmitterstick/internal/handler/EleroChannelHandler.java
  bundles/org.openhab.binding.elerotransmitterstick/src/main/java/org/openhab/binding/elerotransmitterstick/internal/handler/EleroTransmitterStickHandler.java
  bundles/org.openhab.binding.elerotransmitterstick/src/main/java/org/openhab/binding/elerotransmitterstick/internal/handler/StatusListener.java
  bundles/org.openhab.binding.elerotransmitterstick/src/main/java/org/openhab/binding/elerotransmitterstick/internal/stick/Command.java
  bundles/org.openhab.binding.elerotransmitterstick/src/main/java/org/openhab/binding/elerotransmitterstick/internal/stick/CommandPacket.java
  bundles/org.openhab.binding.elerotransmitterstick/src/main/java/org/openhab/binding/elerotransmitterstick/internal/stick/CommandType.java
  bundles/org.openhab.binding.elerotransmitterstick/src/main/java/org/openhab/binding/elerotransmitterstick/internal/stick/CommandUtil.java
  bundles/org.openhab.binding.elerotransmitterstick/src/main/java/org/openhab/binding/elerotransmitterstick/internal/stick/ConnectException.java
  bundles/org.openhab.binding.elerotransmitterstick/src/main/java/org/openhab/binding/elerotransmitterstick/internal/stick/DelayedCommand.java
  bundles/org.openhab.binding.elerotransmitterstick/src/main/java/org/openhab/binding/elerotransmitterstick/internal/stick/Response.java
  bundles/org.openhab.binding.elerotransmitterstick/src/main/java/org/openhab/binding/elerotransmitterstick/internal/stick/ResponseStatus.java
  bundles/org.openhab.binding.elerotransmitterstick/src/main/java/org/openhab/binding/elerotransmitterstick/internal/stick/ResponseUtil.java
  bundles/org.openhab.binding.elerotransmitterstick/src/main/java/org/openhab/binding/elerotransmitterstick/internal/stick/SerialConnection.java
  bundles/org.openhab.binding.elerotransmitterstick/src/main/java/org/openhab/binding/elerotransmitterstick/internal/stick/TimedCommand.java
  bundles/org.openhab.binding.elerotransmitterstick/src/main/java/org/openhab/binding/elerotransmitterstick/internal/stick/TransmitterStick.java
  bundles/org.openhab.binding.elerotransmitterstick/src/main/resources/ESH-INF/binding/binding.xml
  bundles/org.openhab.binding.elerotransmitterstick/src/main/resources/ESH-INF/thing/thing-types.xml
  bundles/pom.xml
  features/karaf/openhab-addons/src/main/feature/feature.xml
Labels: infrastructure

#5323 [pioneeravr] Removed dependency on google guava library
  addons/binding/org.openhab.binding.pioneeravr/META-INF/MANIFEST.MF
  addons/binding/org.openhab.binding.pioneeravr/src/main/java/org/openhab/binding/pioneeravr/internal/PioneerAvrBindingConstants.java
  addons/binding/org.openhab.binding.pioneeravr/src/main/java/org/openhab/binding/pioneeravr/internal/discovery/PioneerAvrDiscoveryParticipant.java
  addons/binding/org.openhab.binding.pioneeravr/src/main/java/org/openhab/binding/pioneeravr/internal/handler/AvrHandlerFactory.java
Labels: infrastructure

#5330 [onebusaway] Remove dependency on google guava library.
  addons/binding/org.openhab.binding.onebusaway/META-INF/MANIFEST.MF
  addons/binding/org.openhab.binding.onebusaway/src/main/java/org/openhab/binding/onebusaway/internal/OneBusAwayHandlerFactory.java
  addons/binding/org.openhab.binding.onebusaway/src/main/java/org/openhab/binding/onebusaway/internal/handler/RouteHandler.java
  addons/binding/org.openhab.binding.onebusaway/src/main/java/org/openhab/binding/onebusaway/internal/handler/StopHandler.java
Labels: infrastructure

#5284 [pioneeravr] Migrate to bnd build
  CODEOWNERS
  addons/binding/org.openhab.binding.pioneeravr/.classpath
  addons/binding/org.openhab.binding.pioneeravr/META-INF/MANIFEST.MF
  addons/binding/org.openhab.binding.pioneeravr/OSGI-INF/.gitignore
  addons/binding/org.openhab.binding.pioneeravr/build.properties
  addons/binding/pom.xml
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.pioneeravr/.classpath
  bundles/org.openhab.binding.pioneeravr/.project
  bundles/org.openhab.binding.pioneeravr/NOTICE
  bundles/org.openhab.binding.pioneeravr/README.md
  bundles/org.openhab.binding.pioneeravr/pom.xml
  bundles/org.openhab.binding.pioneeravr/src/main/java/org/openhab/binding/pioneeravr/internal/PioneerAvrBindingConstants.java
  bundles/org.openhab.binding.pioneeravr/src/main/java/org/openhab/binding/pioneeravr/internal/discovery/PioneerAvrDiscoveryParticipant.java
  bundles/org.openhab.binding.pioneeravr/src/main/java/org/openhab/binding/pioneeravr/internal/handler/AbstractAvrHandler.java
  bundles/org.openhab.binding.pioneeravr/src/main/java/org/openhab/binding/pioneeravr/internal/handler/AvrHandlerFactory.java
  bundles/org.openhab.binding.pioneeravr/src/main/java/org/openhab/binding/pioneeravr/internal/handler/IpAvrHandler.java
  bundles/org.openhab.binding.pioneeravr/src/main/java/org/openhab/binding/pioneeravr/internal/handler/SerialAvrHandler.java
  bundles/org.openhab.binding.pioneeravr/src/main/java/org/openhab/binding/pioneeravr/internal/protocol/DisplayInformation.java
  bundles/org.openhab.binding.pioneeravr/src/main/java/org/openhab/binding/pioneeravr/internal/protocol/ParameterizedCommand.java
  bundles/org.openhab.binding.pioneeravr/src/main/java/org/openhab/binding/pioneeravr/internal/protocol/RequestResponseFactory.java
  bundles/org.openhab.binding.pioneeravr/src/main/java/org/openhab/binding/pioneeravr/internal/protocol/Response.java
  bundles/org.openhab.binding.pioneeravr/src/main/java/org/openhab/binding/pioneeravr/internal/protocol/SimpleCommand.java
  bundles/org.openhab.binding.pioneeravr/src/main/java/org/openhab/binding/pioneeravr/internal/protocol/StreamAvrConnection.java
  bundles/org.openhab.binding.pioneeravr/src/main/java/org/openhab/binding/pioneeravr/internal/protocol/avr/AvrCommand.java
  bundles/org.openhab.binding.pioneeravr/src/main/java/org/openhab/binding/pioneeravr/internal/protocol/avr/AvrConnection.java
  bundles/org.openhab.binding.pioneeravr/src/main/java/org/openhab/binding/pioneeravr/internal/protocol/avr/AvrConnectionException.java
  bundles/org.openhab.binding.pioneeravr/src/main/java/org/openhab/binding/pioneeravr/internal/protocol/avr/AvrResponse.java
  bundles/org.openhab.binding.pioneeravr/src/main/java/org/openhab/binding/pioneeravr/internal/protocol/avr/CommandTypeNotSupportedException.java
  bundles/org.openhab.binding.pioneeravr/src/main/java/org/openhab/binding/pioneeravr/internal/protocol/event/AvrDisconnectionEvent.java
  bundles/org.openhab.binding.pioneeravr/src/main/java/org/openhab/binding/pioneeravr/internal/protocol/event/AvrDisconnectionListener.java
  bundles/org.openhab.binding.pioneeravr/src/main/java/org/openhab/binding/pioneeravr/internal/protocol/event/AvrStatusUpdateEvent.java
  bundles/org.openhab.binding.pioneeravr/src/main/java/org/openhab/binding/pioneeravr/internal/protocol/event/AvrUpdateListener.java
  bundles/org.openhab.binding.pioneeravr/src/main/java/org/openhab/binding/pioneeravr/internal/protocol/ip/IpAvrConnection.java
  bundles/org.openhab.binding.pioneeravr/src/main/java/org/openhab/binding/pioneeravr/internal/protocol/serial/SerialAvrConnection.java
  bundles/org.openhab.binding.pioneeravr/src/main/java/org/openhab/binding/pioneeravr/internal/protocol/states/MuteStateValues.java
  bundles/org.openhab.binding.pioneeravr/src/main/java/org/openhab/binding/pioneeravr/internal/protocol/states/PowerStateValues.java
  bundles/org.openhab.binding.pioneeravr/src/main/java/org/openhab/binding/pioneeravr/internal/protocol/utils/DisplayInformationConverter.java
  bundles/org.openhab.binding.pioneeravr/src/main/java/org/openhab/binding/pioneeravr/internal/protocol/utils/VolumeConverter.java
  bundles/org.openhab.binding.pioneeravr/src/main/resources/ESH-INF/binding/binding.xml
  bundles/org.openhab.binding.pioneeravr/src/main/resources/ESH-INF/thing/thing-types.xml
  bundles/pom.xml
  features/karaf/openhab-addons/src/main/feature/feature.xml
Labels: infrastructure

#5332 [mqtt] karaf start levels for mqtt
  features/karaf/openhab-addons/src/main/feature/feature.xml
Labels: bug

#5329 [urtsi] Remove dependency on google guava library.
  addons/binding/org.openhab.binding.urtsi/META-INF/MANIFEST.MF
  addons/binding/org.openhab.binding.urtsi/src/main/java/org/openhab/binding/urtsi/internal/UrtsiHandlerFactory.java
  addons/binding/org.openhab.binding.urtsi/src/main/java/org/openhab/binding/urtsi/internal/handler/UrtsiDeviceHandler.java
Labels: infrastructure

#5338 Require successful Travis CI Java 8 and 11 builds
  .travis.yml
Labels: infrastructure

#5334 [fsinternetradio] Migrate to bnd build
  CODEOWNERS
  addons/binding/org.openhab.binding.fsinternetradio.test/.classpath
  addons/binding/org.openhab.binding.fsinternetradio.test/.project
  addons/binding/org.openhab.binding.fsinternetradio.test/META-INF/MANIFEST.MF
  addons/binding/org.openhab.binding.fsinternetradio.test/build.properties
  addons/binding/org.openhab.binding.fsinternetradio.test/org.openhab.binding.fsinternetradio.test.launch
  addons/binding/org.openhab.binding.fsinternetradio.test/pom.xml
  addons/binding/org.openhab.binding.fsinternetradio/.classpath
  addons/binding/org.openhab.binding.fsinternetradio/META-INF/MANIFEST.MF
  addons/binding/org.openhab.binding.fsinternetradio/NOTICE
  addons/binding/org.openhab.binding.fsinternetradio/OSGI-INF/.gitignore
  addons/binding/org.openhab.binding.fsinternetradio/build.properties
  addons/binding/pom.xml
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.fsinternetradio/.classpath
  bundles/org.openhab.binding.fsinternetradio/.project
  bundles/org.openhab.binding.fsinternetradio/NOTICE
  bundles/org.openhab.binding.fsinternetradio/README.md
  bundles/org.openhab.binding.fsinternetradio/pom.xml
  bundles/org.openhab.binding.fsinternetradio/src/main/java/org/openhab/binding/fsinternetradio/internal/FSInternetRadioBindingConstants.java
  bundles/org.openhab.binding.fsinternetradio/src/main/java/org/openhab/binding/fsinternetradio/internal/FSInternetRadioDiscoveryParticipant.java
  bundles/org.openhab.binding.fsinternetradio/src/main/java/org/openhab/binding/fsinternetradio/internal/FSInternetRadioHandlerFactory.java
  bundles/org.openhab.binding.fsinternetradio/src/main/java/org/openhab/binding/fsinternetradio/internal/handler/FSInternetRadioHandler.java
  bundles/org.openhab.binding.fsinternetradio/src/main/java/org/openhab/binding/fsinternetradio/internal/radio/FrontierSiliconRadio.java
  bundles/org.openhab.binding.fsinternetradio/src/main/java/org/openhab/binding/fsinternetradio/internal/radio/FrontierSiliconRadioApiResult.java
  bundles/org.openhab.binding.fsinternetradio/src/main/java/org/openhab/binding/fsinternetradio/internal/radio/FrontierSiliconRadioConnection.java
  bundles/org.openhab.binding.fsinternetradio/src/main/java/org/openhab/binding/fsinternetradio/internal/radio/FrontierSiliconRadioConstants.java
  bundles/org.openhab.binding.fsinternetradio/src/main/resources/ESH-INF/binding/binding.xml
  bundles/org.openhab.binding.fsinternetradio/src/main/resources/ESH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.fsinternetradio/src/test/java/org/openhab/binding/fsinternetradio/internal/handler/HandlerUtils.java
  bundles/org.openhab.binding.fsinternetradio/src/test/java/org/openhab/binding/fsinternetradio/test/FSInternetRadioDiscoveryParticipantJavaTest.java
  bundles/org.openhab.binding.fsinternetradio/src/test/java/org/openhab/binding/fsinternetradio/test/FSInternetRadioHandlerJavaTest.java
  bundles/org.openhab.binding.fsinternetradio/src/test/java/org/openhab/binding/fsinternetradio/test/MockedRadioHandler.java
  bundles/org.openhab.binding.fsinternetradio/src/test/java/org/openhab/binding/fsinternetradio/test/RadioServiceDummy.java
  bundles/org.openhab.binding.fsinternetradio/src/test/resources/invalidXml.xml
  bundles/org.openhab.binding.fsinternetradio/src/test/resources/validXml.xml
  bundles/pom.xml
  features/karaf/openhab-addons/src/main/feature/feature.xml
Labels: infrastructure

#5307 [onebusaway] Migrate to bnd build
  CODEOWNERS
  addons/binding/org.openhab.binding.onebusaway/.classpath
  addons/binding/org.openhab.binding.onebusaway/META-INF/MANIFEST.MF
  addons/binding/org.openhab.binding.onebusaway/OSGI-INF/.gitignore
  addons/binding/org.openhab.binding.onebusaway/build.properties
  addons/binding/pom.xml
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.onebusaway/.classpath
  bundles/org.openhab.binding.onebusaway/.project
  bundles/org.openhab.binding.onebusaway/NOTICE
  bundles/org.openhab.binding.onebusaway/README.md
  bundles/org.openhab.binding.onebusaway/pom.xml
  bundles/org.openhab.binding.onebusaway/src/main/java/org/openhab/binding/onebusaway/internal/OneBusAwayBindingConstants.java
  bundles/org.openhab.binding.onebusaway/src/main/java/org/openhab/binding/onebusaway/internal/OneBusAwayHandlerFactory.java
  bundles/org.openhab.binding.onebusaway/src/main/java/org/openhab/binding/onebusaway/internal/config/ApiConfiguration.java
  bundles/org.openhab.binding.onebusaway/src/main/java/org/openhab/binding/onebusaway/internal/config/ChannelConfig.java
  bundles/org.openhab.binding.onebusaway/src/main/java/org/openhab/binding/onebusaway/internal/config/RouteConfiguration.java
  bundles/org.openhab.binding.onebusaway/src/main/java/org/openhab/binding/onebusaway/internal/config/StopConfiguration.java
  bundles/org.openhab.binding.onebusaway/src/main/java/org/openhab/binding/onebusaway/internal/handler/ApiHandler.java
  bundles/org.openhab.binding.onebusaway/src/main/java/org/openhab/binding/onebusaway/internal/handler/ObaStopArrivalResponse.java
  bundles/org.openhab.binding.onebusaway/src/main/java/org/openhab/binding/onebusaway/internal/handler/RouteDataListener.java
  bundles/org.openhab.binding.onebusaway/src/main/java/org/openhab/binding/onebusaway/internal/handler/RouteHandler.java
  bundles/org.openhab.binding.onebusaway/src/main/java/org/openhab/binding/onebusaway/internal/handler/StopHandler.java
  bundles/org.openhab.binding.onebusaway/src/main/resources/ESH-INF/binding/binding.xml
  bundles/org.openhab.binding.onebusaway/src/main/resources/ESH-INF/config/config.xml
  bundles/org.openhab.binding.onebusaway/src/main/resources/ESH-INF/thing/api.xml
  bundles/org.openhab.binding.onebusaway/src/main/resources/ESH-INF/thing/channels.xml
  bundles/org.openhab.binding.onebusaway/src/main/resources/ESH-INF/thing/route.xml
  bundles/org.openhab.binding.onebusaway/src/main/resources/ESH-INF/thing/stop.xml
  bundles/pom.xml
  features/karaf/openhab-addons/src/main/feature/feature.xml
Labels: infrastructure

#5292 [rotelra1x] Migrate to bnd build
  CODEOWNERS
  addons/binding/org.openhab.binding.rotelra1x/.classpath
  addons/binding/org.openhab.binding.rotelra1x/META-INF/MANIFEST.MF
  addons/binding/org.openhab.binding.rotelra1x/OSGI-INF/.gitignore
  addons/binding/org.openhab.binding.rotelra1x/build.properties
  addons/binding/pom.xml
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.rotelra1x/.classpath
  bundles/org.openhab.binding.rotelra1x/.project
  bundles/org.openhab.binding.rotelra1x/NOTICE
  bundles/org.openhab.binding.rotelra1x/README.md
  bundles/org.openhab.binding.rotelra1x/pom.xml
  bundles/org.openhab.binding.rotelra1x/src/main/java/org/openhab/binding/rotelra1x/internal/ConfigurationError.java
  bundles/org.openhab.binding.rotelra1x/src/main/java/org/openhab/binding/rotelra1x/internal/RotelRa1xBindingConstants.java
  bundles/org.openhab.binding.rotelra1x/src/main/java/org/openhab/binding/rotelra1x/internal/RotelRa1xHandlerFactory.java
  bundles/org.openhab.binding.rotelra1x/src/main/java/org/openhab/binding/rotelra1x/internal/handler/RotelRa1xHandler.java
  bundles/org.openhab.binding.rotelra1x/src/main/resources/ESH-INF/binding/binding.xml
  bundles/org.openhab.binding.rotelra1x/src/main/resources/ESH-INF/thing/thing-types.xml
  bundles/pom.xml
  features/karaf/openhab-addons/src/main/feature/feature.xml
Labels: infrastructure

#5342 [synopanalyzer] fix group ID of synopanalyzer in BOM
  bom/openhab-addons/pom.xml
Labels: infrastructure

#5305 [rme] Migrate to bnd build
  CODEOWNERS
  addons/binding/org.openhab.binding.rme/.classpath
  addons/binding/org.openhab.binding.rme/META-INF/MANIFEST.MF
  addons/binding/org.openhab.binding.rme/OSGI-INF/.gitignore
  addons/binding/org.openhab.binding.rme/build.properties
  addons/binding/pom.xml
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.rme/.classpath
  bundles/org.openhab.binding.rme/.project
  bundles/org.openhab.binding.rme/NOTICE
  bundles/org.openhab.binding.rme/README.md
  bundles/org.openhab.binding.rme/pom.xml
  bundles/org.openhab.binding.rme/src/main/java/org/openhab/binding/rme/internal/RMEBindingConstants.java
  bundles/org.openhab.binding.rme/src/main/java/org/openhab/binding/rme/internal/RMEHandlerFactory.java
  bundles/org.openhab.binding.rme/src/main/java/org/openhab/binding/rme/internal/handler/RMEThingHandler.java
  bundles/org.openhab.binding.rme/src/main/java/org/openhab/binding/rme/internal/handler/SerialThingHandler.java
  bundles/org.openhab.binding.rme/src/main/resources/ESH-INF/binding/binding.xml
  bundles/org.openhab.binding.rme/src/main/resources/ESH-INF/thing/rme.xml
  bundles/pom.xml
  features/karaf/openhab-addons/src/main/feature/feature.xml
Labels: infrastructure

#5299 [urtsi] Migrate to bnd build
  CODEOWNERS
  addons/binding/org.openhab.binding.urtsi/.classpath
  addons/binding/org.openhab.binding.urtsi/META-INF/MANIFEST.MF
  addons/binding/org.openhab.binding.urtsi/OSGI-INF/.gitignore
  addons/binding/org.openhab.binding.urtsi/build.properties
  addons/binding/pom.xml
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.urtsi/.classpath
  bundles/org.openhab.binding.urtsi/.gitignore
  bundles/org.openhab.binding.urtsi/.project
  bundles/org.openhab.binding.urtsi/NOTICE
  bundles/org.openhab.binding.urtsi/README.md
  bundles/org.openhab.binding.urtsi/pom.xml
  bundles/org.openhab.binding.urtsi/src/main/java/org/openhab/binding/urtsi/internal/UrtsiBindingConstants.java
  bundles/org.openhab.binding.urtsi/src/main/java/org/openhab/binding/urtsi/internal/UrtsiHandlerFactory.java
  bundles/org.openhab.binding.urtsi/src/main/java/org/openhab/binding/urtsi/internal/config/RtsDeviceConfig.java
  bundles/org.openhab.binding.urtsi/src/main/java/org/openhab/binding/urtsi/internal/config/UrtsiDeviceConfig.java
  bundles/org.openhab.binding.urtsi/src/main/java/org/openhab/binding/urtsi/internal/handler/RtsCommand.java
  bundles/org.openhab.binding.urtsi/src/main/java/org/openhab/binding/urtsi/internal/handler/RtsDeviceHandler.java
  bundles/org.openhab.binding.urtsi/src/main/java/org/openhab/binding/urtsi/internal/handler/UrtsiDeviceHandler.java
  bundles/org.openhab.binding.urtsi/src/main/java/org/openhab/binding/urtsi/internal/mapping/UrtsiChannelMapping.java
  bundles/org.openhab.binding.urtsi/src/main/resources/ESH-INF/binding/binding.xml
  bundles/org.openhab.binding.urtsi/src/main/resources/ESH-INF/i18n/urtsi_de.properties
  bundles/org.openhab.binding.urtsi/src/main/resources/ESH-INF/i18n/urtsi_en.properties
  bundles/org.openhab.binding.urtsi/src/main/resources/ESH-INF/thing/thing-types.xml
  bundles/pom.xml
  features/karaf/openhab-addons/src/main/feature/feature.xml
Labels: infrastructure

#5344 [mqtt] Fixed projekt name
  bundles/org.openhab.binding.mqtt/.project
Labels: infrastructure

#5345 Remove non-existing fsinternetradio.tests from CODEOWNERS
  CODEOWNERS
Labels: infrastructure

#5229 [transform.javascript] Migrate to bnd build
  CODEOWNERS
  addons/transform/org.openhab.transform.javascript/.classpath
  addons/transform/org.openhab.transform.javascript/META-INF/MANIFEST.MF
  addons/transform/org.openhab.transform.javascript/OSGI-INF/.gitignore
  addons/transform/org.openhab.transform.javascript/build.properties
  addons/transform/pom.xml
  bom/openhab-addons/pom.xml
  bundles/org.openhab.transform.javascript/.classpath
  bundles/org.openhab.transform.javascript/.project
  bundles/org.openhab.transform.javascript/NOTICE
  bundles/org.openhab.transform.javascript/README.md
  bundles/org.openhab.transform.javascript/pom.xml
  bundles/org.openhab.transform.javascript/src/main/java/org/openhab/transform/javascript/internal/JavaScriptEngineManager.java
  bundles/org.openhab.transform.javascript/src/main/java/org/openhab/transform/javascript/internal/JavaScriptTransformationService.java
  bundles/org.openhab.transform.javascript/src/main/java/org/openhab/transform/javascript/internal/TransformationScriptWatcher.java
  bundles/org.openhab.transform.javascript/src/main/java/org/openhab/transform/javascript/internal/profiles/JavascriptTransformationProfile.java
  bundles/org.openhab.transform.javascript/src/main/java/org/openhab/transform/javascript/internal/profiles/JavascriptTransformationProfileFactory.java
  bundles/org.openhab.transform.javascript/src/main/resources/ESH-INF/config/javascriptProfile.xml
  bundles/org.openhab.transform.javascript/src/main/resources/readme.txt
  bundles/pom.xml
  features/karaf/openhab-addons/src/main/feature/feature.xml
Labels: infrastructure
