Repository openhab/openhab-addons, pull requests merged in 2019-11, with the labels that each got.

#6322 [nest] Add note about WWN retirement
  bundles/org.openhab.binding.nest/README.md
Labels: documentation

#6316 [bluetooth][bluez] add x86-64 native code
  bundles/org.openhab.binding.bluetooth.bluez/src/main/java/org/openhab/binding/bluetooth/bluez/package-info.java
Labels: additional testing prefered, bug

#6318 [darksky] Fixed check for minimum value of config parameter 'refreshInterval'
  bundles/org.openhab.binding.darksky/README.md
  bundles/org.openhab.binding.darksky/src/main/java/org/openhab/binding/darksky/internal/config/DarkSkyAPIConfiguration.java
  bundles/org.openhab.binding.darksky/src/main/java/org/openhab/binding/darksky/internal/connection/DarkSkyConnection.java
  bundles/org.openhab.binding.darksky/src/main/java/org/openhab/binding/darksky/internal/handler/DarkSkyAPIHandler.java
  bundles/org.openhab.binding.darksky/src/main/resources/ESH-INF/config/config.xml
  bundles/org.openhab.binding.darksky/src/main/resources/ESH-INF/i18n/darksky_de.properties
Labels: bug

#6315 [openweathermap] Added additional check for extracting error message from response
  bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/connection/OpenWeatherMapConnection.java
Labels: bug

#6325 [miele] Fixed bridge status handling upon initialization
  bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/discovery/MieleMDNSDiscoveryParticipant.java
  bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/MieleBridgeHandler.java
Labels: bug

#6289 [infrastructure] change scopes where necessary
  bundles/org.openhab.binding.doorbird/pom.xml
  bundles/org.openhab.binding.doorbird/src/main/feature/feature.xml
  bundles/org.openhab.binding.heos/pom.xml
Labels: infrastructure

#6228 [infrastructure] Added spotless maven code formatter config
  pom.xml
Labels: infrastructure

#6254 [mqtt] fix compilation error
  bundles/org.openhab.binding.mqtt.generic/README.md
  bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/ChannelState.java
Labels: binding: mqtt, bug

#5677 [telegram] Telegram Binding initial contribution
  CODEOWNERS
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.telegram/.classpath
  bundles/org.openhab.binding.telegram/.project
  bundles/org.openhab.binding.telegram/NOTICE
  bundles/org.openhab.binding.telegram/README.md
  bundles/org.openhab.binding.telegram/doc/queryExample.png
  bundles/org.openhab.binding.telegram/pom.xml
  bundles/org.openhab.binding.telegram/src/main/feature/feature.xml
  bundles/org.openhab.binding.telegram/src/main/java/org/openhab/binding/telegram/bot/TelegramActions.java
  bundles/org.openhab.binding.telegram/src/main/java/org/openhab/binding/telegram/internal/TelegramBindingConstants.java
  bundles/org.openhab.binding.telegram/src/main/java/org/openhab/binding/telegram/internal/TelegramConfiguration.java
  bundles/org.openhab.binding.telegram/src/main/java/org/openhab/binding/telegram/internal/TelegramHandler.java
  bundles/org.openhab.binding.telegram/src/main/java/org/openhab/binding/telegram/internal/TelegramHandlerFactory.java
  bundles/org.openhab.binding.telegram/src/main/resources/ESH-INF/binding/binding.xml
  bundles/org.openhab.binding.telegram/src/main/resources/ESH-INF/thing/thing-types.xml
  bundles/pom.xml
Labels: new binding, oh1 migration

#6242 [mqtt] adjust documentation for keepAlive to code
  bundles/org.openhab.binding.mqtt/README.md
  bundles/org.openhab.binding.mqtt/src/main/resources/ESH-INF/thing/thing-types.xml
Labels: binding: mqtt, documentation

#6357 [tplinksmarthome] Clarified documentation
  bundles/org.openhab.binding.tplinksmarthome/README.md
Labels: documentation

#6214 [hdpowerview] simplify polling initialization; downgrade and improve some error logging
  bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/HDPowerViewWebTargets.java
  bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/discovery/HDPowerViewShadeDiscoveryService.java
  bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/handler/HDPowerViewHubHandler.java
  bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/handler/HDPowerViewShadeHandler.java
Labels: bug, enhancement

#6225 [irtrans] Update README.md
  bundles/org.openhab.binding.irtrans/README.md
Labels: documentation

#6369 [bluez] fix version check
  bundles/org.openhab.binding.bluetooth.bluez/src/main/java/org/openhab/binding/bluetooth/bluez/internal/discovery/BlueZDiscoveryService.java
  bundles/org.openhab.binding.bluetooth.bluez/src/main/java/org/openhab/binding/bluetooth/bluez/package-info.java
Labels: bug, critical

#6368 Upgrade to Karaf 4.2.7
  bundles/org.openhab.binding.amazondashbutton/src/main/feature/feature.xml
  bundles/org.openhab.binding.doorbird/src/main/feature/feature.xml
  bundles/org.openhab.binding.systeminfo/src/main/feature/feature.xml
  bundles/org.openhab.binding.tellstick/pom.xml
  bundles/org.openhab.binding.tellstick/src/main/feature/feature.xml
  features/pom.xml
  pom.xml
Labels: awaiting other PR

#6370 [sonos] improve docs, commands for control channel
  bundles/org.openhab.binding.sonos/README.md
Labels: documentation

#6378 [dsmr] integer parsing errors should be catched
  bundles/org.openhab.binding.dsmr/src/main/java/org/openhab/binding/dsmr/internal/device/cosem/CosemHexString.java
Labels: enhancement

#6180 [lifx] Added support for LIFX Tile and Tile Effects
  bundles/org.openhab.binding.lifx/README.md
  bundles/org.openhab.binding.lifx/src/main/java/org/openhab/binding/lifx/internal/LifxBindingConstants.java
  bundles/org.openhab.binding.lifx/src/main/java/org/openhab/binding/lifx/internal/LifxLightCurrentStateUpdater.java
  bundles/org.openhab.binding.lifx/src/main/java/org/openhab/binding/lifx/internal/LifxLightState.java
  bundles/org.openhab.binding.lifx/src/main/java/org/openhab/binding/lifx/internal/LifxLightStateChanger.java
  bundles/org.openhab.binding.lifx/src/main/java/org/openhab/binding/lifx/internal/handler/LifxLightHandler.java
  bundles/org.openhab.binding.lifx/src/main/java/org/openhab/binding/lifx/internal/listener/LifxLightStateListener.java
  bundles/org.openhab.binding.lifx/src/main/java/org/openhab/binding/lifx/internal/protocol/Effect.java
  bundles/org.openhab.binding.lifx/src/main/java/org/openhab/binding/lifx/internal/protocol/GetTileEffectRequest.java
  bundles/org.openhab.binding.lifx/src/main/java/org/openhab/binding/lifx/internal/protocol/PacketFactory.java
  bundles/org.openhab.binding.lifx/src/main/java/org/openhab/binding/lifx/internal/protocol/Product.java
  bundles/org.openhab.binding.lifx/src/main/java/org/openhab/binding/lifx/internal/protocol/SetTileEffectRequest.java
  bundles/org.openhab.binding.lifx/src/main/java/org/openhab/binding/lifx/internal/protocol/StateTileEffectResponse.java
  bundles/org.openhab.binding.lifx/src/main/resources/ESH-INF/config/config.xml
  bundles/org.openhab.binding.lifx/src/main/resources/ESH-INF/i18n/lifx.properties
  bundles/org.openhab.binding.lifx/src/main/resources/ESH-INF/i18n/lifx_nl.properties
  bundles/org.openhab.binding.lifx/src/main/resources/ESH-INF/thing/channel.xml
  bundles/org.openhab.binding.lifx/src/main/resources/ESH-INF/thing/tilelight.xml
Labels: enhancement

#6203 [mqtt] fix refresh/restoreOnStartup
  bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/AbstractMQTTThingHandler.java
Labels: binding: mqtt

#6384 [lifx] Add support for LIFX Candle
  bundles/org.openhab.binding.lifx/README.md
  bundles/org.openhab.binding.lifx/src/main/java/org/openhab/binding/lifx/internal/protocol/Product.java
Labels: enhancement

#6183 [infrastructure] move /lib to remote
  bundles/org.openhab.binding.leapmotion/.classpath
  bundles/org.openhab.binding.leapmotion/lib/LeapJava.jar
  bundles/org.openhab.binding.leapmotion/pom.xml
  bundles/org.openhab.binding.netatmo/.classpath
  bundles/org.openhab.binding.netatmo/lib/netatmo-java-retrofit-1.1.3.jar
  bundles/org.openhab.binding.netatmo/noEmbedDependencies.profile
  bundles/org.openhab.binding.netatmo/pom.xml
  bundles/org.openhab.binding.orvibo/.classpath
  bundles/org.openhab.binding.orvibo/lib/s20-sdk-0.0.6-nmu1-src.zip
  bundles/org.openhab.binding.orvibo/lib/s20-sdk-0.0.6-nmu1.jar
  bundles/org.openhab.binding.orvibo/noEmbedDependencies.profile
  bundles/org.openhab.binding.orvibo/pom.xml
  bundles/org.openhab.binding.tado/.classpath
  bundles/org.openhab.binding.tado/lib/tado-api-client-1.3.jar
  bundles/org.openhab.binding.tado/pom.xml
  bundles/org.openhab.binding.tellstick/.classpath
  bundles/org.openhab.binding.tellstick/lib/async-http-client-2.0.19.jar
  bundles/org.openhab.binding.tellstick/lib/async-http-client-netty-utils-2.0.19.jar
  bundles/org.openhab.binding.tellstick/lib/javatellstick-1.1.jar
  bundles/org.openhab.binding.tellstick/lib/netty-all-4.0.42.Final.jar
  bundles/org.openhab.binding.tellstick/lib/netty-reactive-streams-1.0.8.jar
  bundles/org.openhab.binding.tellstick/lib/netty-resolver-2.0.19.jar
  bundles/org.openhab.binding.tellstick/lib/netty-resolver-dns-2.0.19.jar
  bundles/org.openhab.binding.tellstick/lib/reactive-streams-1.0.0.jar
  bundles/org.openhab.binding.tellstick/pom.xml
  bundles/org.openhab.binding.tellstick/src/main/feature/feature.xml
  bundles/org.openhab.binding.zoneminder/lib/zoneminder4j-0.9.7.jar
  bundles/org.openhab.binding.zoneminder/pom.xml
  bundles/org.openhab.binding.zway/.classpath
  bundles/org.openhab.binding.zway/lib/zway-lib-0.2.9-SNAPSHOT.jar
  bundles/org.openhab.binding.zway/noEmbedDependencies.profile
  bundles/org.openhab.binding.zway/pom.xml
  bundles/org.openhab.io.homekit/.classpath
  bundles/org.openhab.io.homekit/lib/hap-1.1.5-SNAPSHOT-sources.jar
  bundles/org.openhab.io.homekit/lib/hap-1.1.5-SNAPSHOT.jar
  bundles/org.openhab.io.homekit/noEmbedDependencies.profile
  bundles/org.openhab.io.homekit/pom.xml
Labels: infrastructure

#6381 [networkupstools] Fix typo and misc log
  bundles/org.openhab.binding.networkupstools/src/main/java/org/openhab/binding/networkupstools/internal/NUTBindingConstants.java
  bundles/org.openhab.binding.networkupstools/src/main/java/org/openhab/binding/networkupstools/internal/NUTHandler.java
  bundles/org.openhab.binding.networkupstools/src/main/java/org/openhab/binding/networkupstools/internal/nut/NutConnector.java
  bundles/org.openhab.binding.networkupstools/src/main/java/org/openhab/binding/networkupstools/internal/nut/NutResponseReader.java
Labels: bug

#6355 [spotify] Improve performance of handling data
  bundles/org.openhab.binding.spotify/src/main/java/org/openhab/binding/spotify/internal/handler/SpotifyBridgeHandler.java
  bundles/org.openhab.binding.spotify/src/main/java/org/openhab/binding/spotify/internal/handler/SpotifyDeviceHandler.java
  bundles/org.openhab.binding.spotify/src/main/java/org/openhab/binding/spotify/internal/handler/SpotifyHandleCommands.java
  bundles/org.openhab.binding.spotify/src/main/resources/ESH-INF/thing/thing-types.xml
Labels: enhancement

#6390 [yamahareceiver] There is no unit dB
  bundles/org.openhab.binding.yamahareceiver/src/main/resources/ESH-INF/thing/thing-types.xml
Labels: critical

#6324 [lutron] Add support for Palladiom keypads
  bundles/org.openhab.binding.lutron/README.md
  bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/LutronBindingConstants.java
  bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/LutronHandlerFactory.java
  bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/discovery/LutronDeviceDiscoveryService.java
  bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/discovery/project/DeviceType.java
  bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/handler/PalladiomKeypadHandler.java
  bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/keypadconfig/KeypadConfig.java
  bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/keypadconfig/KeypadConfigPalladiom.java
  bundles/org.openhab.binding.lutron/src/main/resources/ESH-INF/thing/thing-types.xml
Labels: enhancement

#6383 Fixed wrong port range
  bundles/org.openhab.binding.autelis/src/main/resources/ESH-INF/thing/jandy.xml
  bundles/org.openhab.binding.autelis/src/main/resources/ESH-INF/thing/pentair.xml
  bundles/org.openhab.binding.avmfritz/README.md
  bundles/org.openhab.binding.avmfritz/src/main/resources/ESH-INF/binding/binding.xml
  bundles/org.openhab.binding.avmfritz/src/main/resources/ESH-INF/config/config.xml
  bundles/org.openhab.binding.deconz/src/main/resources/ESH-INF/config/config.xml
  bundles/org.openhab.binding.ftpupload/src/main/resources/ESH-INF/binding/binding.xml
  bundles/org.openhab.binding.hue/src/main/resources/ESH-INF/thing/bridge.xml
  bundles/org.openhab.binding.kodi/src/main/resources/ESH-INF/config/config.xml
  bundles/org.openhab.binding.lirc/src/main/resources/ESH-INF/thing/bridge.xml
  bundles/org.openhab.binding.loxone/src/main/resources/ESH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.max/src/main/resources/ESH-INF/thing/bridge.xml
  bundles/org.openhab.binding.nanoleaf/src/main/resources/ESH-INF/config/config.xml
  bundles/org.openhab.binding.onkyo/src/main/resources/ESH-INF/config/config.xml
  bundles/org.openhab.binding.opengarage/src/main/resources/ESH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.opensprinkler/src/main/resources/ESH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.pjlinkdevice/src/main/resources/ESH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.powermax/src/main/resources/ESH-INF/thing/ip.xml
  bundles/org.openhab.binding.samsungtv/src/main/resources/ESH-INF/config/config.xml
  bundles/org.openhab.binding.satel/src/main/resources/ESH-INF/thing/ethm-1.xml
  bundles/org.openhab.binding.sonyaudio/src/main/resources/ESH-INF/config/config.xml
  bundles/org.openhab.binding.squeezebox/src/main/resources/ESH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.zoneminder/src/main/resources/ESH-INF/config/monitor-channels.xml
  bundles/org.openhab.binding.zoneminder/src/main/resources/ESH-INF/config/zoneminderserver.xml
  bundles/org.openhab.binding.zway/README.md
  bundles/org.openhab.binding.zway/src/main/resources/ESH-INF/config/bridge-config.xml
Labels: documentation

#6097 [amazonechocontrol] Announcement volume
  bundles/org.openhab.binding.amazonechocontrol/README.md
  bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/Connection.java
  bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/channelhandler/ChannelHandlerAnnouncement.java
  bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/channelhandler/IEchoThingHandler.java
  bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/handler/EchoHandler.java
Labels: enhancement

#6404 [amazondashbutton] Fix ServiceLoader
  bundles/org.openhab.binding.amazondashbutton/src/main/java/org/openhab/binding/amazondashbutton/package-info.java
Labels: bug, community approved

#6407 Resolve itests runbundles
  itests/org.openhab.binding.avmfritz.tests/itest.bndrun
  itests/org.openhab.binding.feed.tests/itest.bndrun
  itests/org.openhab.binding.hue.tests/itest.bndrun
  itests/org.openhab.binding.max.tests/itest.bndrun
  itests/org.openhab.binding.nest.tests/itest.bndrun
  itests/org.openhab.binding.ntp.tests/itest.bndrun
  itests/org.openhab.binding.systeminfo.tests/itest.bndrun
  itests/org.openhab.binding.tradfri.tests/itest.bndrun
  itests/org.openhab.binding.wemo.tests/itest.bndrun
  itests/org.openhab.io.hueemulation.tests/itest.bndrun
  itests/org.openhab.persistence.mapdb.tests/itest.bndrun
Labels: awaiting other PR

#6409 [kodi] Added more details and example of configuration for 'shownotifiation' channel
  bundles/org.openhab.binding.kodi/README.md
Labels: documentation

#6244 [mqtt] make rollershutter symmetric
  bundles/org.openhab.binding.mqtt.generic/README.md
  bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/values/RollershutterValue.java
  bundles/org.openhab.binding.mqtt.generic/src/test/java/org/openhab/binding/mqtt/generic/values/ValueTests.java
Labels: binding: mqtt, bug

#6402 [hueemulation] Fix Amazon Echo device discovery
  bundles/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/HueEmulationService.java
Labels: bug

#6246 [mqtt] add QoS to channel config
  bundles/org.openhab.binding.mqtt.generic/README.md
  bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/ChannelConfig.java
  bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/ChannelState.java
  bundles/org.openhab.binding.mqtt.generic/src/main/resources/ESH-INF/config/color-channel-config.xml
  bundles/org.openhab.binding.mqtt.generic/src/main/resources/ESH-INF/config/dimmer-channel-config.xml
  bundles/org.openhab.binding.mqtt.generic/src/main/resources/ESH-INF/config/number-channel-config.xml
  bundles/org.openhab.binding.mqtt.generic/src/main/resources/ESH-INF/config/rollershutter-channel-config.xml
  bundles/org.openhab.binding.mqtt.generic/src/main/resources/ESH-INF/config/string-channel-config.xml
  bundles/org.openhab.binding.mqtt.generic/src/main/resources/ESH-INF/config/switch-channel-config.xml
Labels: binding: mqtt, enhancement

#6223 [homekit] upgrade hap to 1.2.0
  bundles/org.openhab.io.homekit/pom.xml
  bundles/org.openhab.io.homekit/src/main/feature/feature.xml
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitAccessoryRegistry.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitAccessoryUpdater.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitAuthInfoImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitChangeListener.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/AbstractHomekitAccessoryImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/AbstractHomekitLightbulbImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/AbstractTemperatureHomekitAccessoryImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/GroupedAccessory.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitAccessoryFactory.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitCarbonMonoxideSensorImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitColorfulLightbulbImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitContactSensorImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitDimmableLightbulbImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitHumiditySensorImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitLeakSensorImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitMotionSensorImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitOccupancySensorImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitSmokeSensorImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitSwitchImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitTemperatureSensorImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitThermostatImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitValveImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitWindowCoveringImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/battery/BatteryLevelStatus.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/battery/BatteryLowStatus.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/battery/BatteryStatus.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/battery/NoBatteryStatus.java
Labels: bug, community approved, io: homekit

#6432 [kodi] Fixed NPE if no profile is returned in response
  bundles/org.openhab.binding.kodi/src/main/java/org/openhab/binding/kodi/internal/handler/KodiHandler.java
  bundles/org.openhab.binding.kodi/src/main/java/org/openhab/binding/kodi/internal/protocol/KodiConnection.java
Labels: bug

#6382 [enturno] Documentation update
  bundles/org.openhab.binding.enturno/README.md
Labels: documentation

#5877 [hydrawise] Hydrawise Binding initial contribution
  CODEOWNERS
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.hydrawise/.classpath
  bundles/org.openhab.binding.hydrawise/.project
  bundles/org.openhab.binding.hydrawise/NOTICE
  bundles/org.openhab.binding.hydrawise/README.md
  bundles/org.openhab.binding.hydrawise/doc/apikey.png
  bundles/org.openhab.binding.hydrawise/doc/logo.png
  bundles/org.openhab.binding.hydrawise/doc/settings.png
  bundles/org.openhab.binding.hydrawise/pom.xml
  bundles/org.openhab.binding.hydrawise/src/main/feature/feature.xml
  bundles/org.openhab.binding.hydrawise/src/main/java/org/openhab/binding/hydrawise/internal/HydrawiseBindingConstants.java
  bundles/org.openhab.binding.hydrawise/src/main/java/org/openhab/binding/hydrawise/internal/HydrawiseCloudConfiguration.java
  bundles/org.openhab.binding.hydrawise/src/main/java/org/openhab/binding/hydrawise/internal/HydrawiseCloudHandler.java
  bundles/org.openhab.binding.hydrawise/src/main/java/org/openhab/binding/hydrawise/internal/HydrawiseHandler.java
  bundles/org.openhab.binding.hydrawise/src/main/java/org/openhab/binding/hydrawise/internal/HydrawiseHandlerFactory.java
  bundles/org.openhab.binding.hydrawise/src/main/java/org/openhab/binding/hydrawise/internal/HydrawiseLocalConfiguration.java
  bundles/org.openhab.binding.hydrawise/src/main/java/org/openhab/binding/hydrawise/internal/HydrawiseLocalHandler.java
  bundles/org.openhab.binding.hydrawise/src/main/java/org/openhab/binding/hydrawise/internal/api/HydrawiseAuthenticationException.java
  bundles/org.openhab.binding.hydrawise/src/main/java/org/openhab/binding/hydrawise/internal/api/HydrawiseCloudApiClient.java
  bundles/org.openhab.binding.hydrawise/src/main/java/org/openhab/binding/hydrawise/internal/api/HydrawiseCommandException.java
  bundles/org.openhab.binding.hydrawise/src/main/java/org/openhab/binding/hydrawise/internal/api/HydrawiseConnectionException.java
  bundles/org.openhab.binding.hydrawise/src/main/java/org/openhab/binding/hydrawise/internal/api/HydrawiseLocalApiClient.java
  bundles/org.openhab.binding.hydrawise/src/main/java/org/openhab/binding/hydrawise/internal/api/HydrawiseZoneCommandBuilder.java
  bundles/org.openhab.binding.hydrawise/src/main/java/org/openhab/binding/hydrawise/internal/api/model/BocTopologyActual.java
  bundles/org.openhab.binding.hydrawise/src/main/java/org/openhab/binding/hydrawise/internal/api/model/BocTopologyDesired.java
  bundles/org.openhab.binding.hydrawise/src/main/java/org/openhab/binding/hydrawise/internal/api/model/Controller.java
  bundles/org.openhab.binding.hydrawise/src/main/java/org/openhab/binding/hydrawise/internal/api/model/CustomerDetailsResponse.java
  bundles/org.openhab.binding.hydrawise/src/main/java/org/openhab/binding/hydrawise/internal/api/model/Features.java
  bundles/org.openhab.binding.hydrawise/src/main/java/org/openhab/binding/hydrawise/internal/api/model/Forecast.java
  bundles/org.openhab.binding.hydrawise/src/main/java/org/openhab/binding/hydrawise/internal/api/model/LocalScheduleResponse.java
  bundles/org.openhab.binding.hydrawise/src/main/java/org/openhab/binding/hydrawise/internal/api/model/PlanArray.java
  bundles/org.openhab.binding.hydrawise/src/main/java/org/openhab/binding/hydrawise/internal/api/model/Relay.java
  bundles/org.openhab.binding.hydrawise/src/main/java/org/openhab/binding/hydrawise/internal/api/model/Response.java
  bundles/org.openhab.binding.hydrawise/src/main/java/org/openhab/binding/hydrawise/internal/api/model/Running.java
  bundles/org.openhab.binding.hydrawise/src/main/java/org/openhab/binding/hydrawise/internal/api/model/Sensor.java
  bundles/org.openhab.binding.hydrawise/src/main/java/org/openhab/binding/hydrawise/internal/api/model/SetControllerResponse.java
  bundles/org.openhab.binding.hydrawise/src/main/java/org/openhab/binding/hydrawise/internal/api/model/SetZoneResponse.java
  bundles/org.openhab.binding.hydrawise/src/main/java/org/openhab/binding/hydrawise/internal/api/model/StatusScheduleResponse.java
  bundles/org.openhab.binding.hydrawise/src/main/resources/ESH-INF/binding/binding.xml
  bundles/org.openhab.binding.hydrawise/src/main/resources/ESH-INF/thing/channel-types.xml
  bundles/org.openhab.binding.hydrawise/src/main/resources/ESH-INF/thing/things.xml
  bundles/pom.xml
Labels: cre, new binding

#4162 [pixometer] Pixometer Binding initial contribution
  CODEOWNERS
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.pixometer/.classpath
  bundles/org.openhab.binding.pixometer/.project
  bundles/org.openhab.binding.pixometer/NOTICE
  bundles/org.openhab.binding.pixometer/README.md
  bundles/org.openhab.binding.pixometer/pom.xml
  bundles/org.openhab.binding.pixometer/src/main/feature/feature.xml
  bundles/org.openhab.binding.pixometer/src/main/java/org/openhab/binding/pixometer/handler/AccountHandler.java
  bundles/org.openhab.binding.pixometer/src/main/java/org/openhab/binding/pixometer/handler/MeterHandler.java
  bundles/org.openhab.binding.pixometer/src/main/java/org/openhab/binding/pixometer/internal/PixometerBindingConstants.java
  bundles/org.openhab.binding.pixometer/src/main/java/org/openhab/binding/pixometer/internal/PixometerHandlerFactory.java
  bundles/org.openhab.binding.pixometer/src/main/java/org/openhab/binding/pixometer/internal/config/Annotation.java
  bundles/org.openhab.binding.pixometer/src/main/java/org/openhab/binding/pixometer/internal/config/ImageMeta.java
  bundles/org.openhab.binding.pixometer/src/main/java/org/openhab/binding/pixometer/internal/config/MeterInstance.java
  bundles/org.openhab.binding.pixometer/src/main/java/org/openhab/binding/pixometer/internal/config/PixometerAccountConfiguration.java
  bundles/org.openhab.binding.pixometer/src/main/java/org/openhab/binding/pixometer/internal/config/PixometerMeterConfiguration.java
  bundles/org.openhab.binding.pixometer/src/main/java/org/openhab/binding/pixometer/internal/config/ReadingInstance.java
  bundles/org.openhab.binding.pixometer/src/main/java/org/openhab/binding/pixometer/internal/data/MeterState.java
  bundles/org.openhab.binding.pixometer/src/main/java/org/openhab/binding/pixometer/internal/serializer/CustomReadingInstanceDeserializer.java
  bundles/org.openhab.binding.pixometer/src/main/resources/ESH-INF/binding/binding.xml
  bundles/org.openhab.binding.pixometer/src/main/resources/ESH-INF/i18n/pixometer_de_DE.properties
  bundles/org.openhab.binding.pixometer/src/main/resources/ESH-INF/i18n/pixometer_en_US.properties
  bundles/org.openhab.binding.pixometer/src/main/resources/ESH-INF/thing/account.xml
  bundles/org.openhab.binding.pixometer/src/main/resources/ESH-INF/thing/channels.xml
  bundles/org.openhab.binding.pixometer/src/main/resources/ESH-INF/thing/energymeter.xml
  bundles/org.openhab.binding.pixometer/src/main/resources/ESH-INF/thing/gasmeter.xml
  bundles/org.openhab.binding.pixometer/src/main/resources/ESH-INF/thing/watermeter.xml
  bundles/pom.xml
Labels: new binding

#4181 [lghombot] LG HomBot Binding initial contribution
  CODEOWNERS
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.lghombot/.classpath
  bundles/org.openhab.binding.lghombot/.project
  bundles/org.openhab.binding.lghombot/NOTICE
  bundles/org.openhab.binding.lghombot/README.md
  bundles/org.openhab.binding.lghombot/pom.xml
  bundles/org.openhab.binding.lghombot/src/main/feature/feature.xml
  bundles/org.openhab.binding.lghombot/src/main/java/org/openhab/binding/lghombot/internal/CameraUtil.java
  bundles/org.openhab.binding.lghombot/src/main/java/org/openhab/binding/lghombot/internal/LGHomBotBindingConstants.java
  bundles/org.openhab.binding.lghombot/src/main/java/org/openhab/binding/lghombot/internal/LGHomBotConfiguration.java
  bundles/org.openhab.binding.lghombot/src/main/java/org/openhab/binding/lghombot/internal/LGHomBotHandler.java
  bundles/org.openhab.binding.lghombot/src/main/java/org/openhab/binding/lghombot/internal/LGHomBotHandlerFactory.java
  bundles/org.openhab.binding.lghombot/src/main/java/org/openhab/binding/lghombot/internal/discovery/LGHomBotDiscovery.java
  bundles/org.openhab.binding.lghombot/src/main/resources/ESH-INF/binding/binding.xml
  bundles/org.openhab.binding.lghombot/src/main/resources/ESH-INF/i18n/lghombot_en.properties
  bundles/org.openhab.binding.lghombot/src/main/resources/ESH-INF/i18n/lghombot_sv.properties
  bundles/org.openhab.binding.lghombot/src/main/resources/ESH-INF/thing/thing-types.xml
  bundles/pom.xml
Labels: cre, new binding

#5741 [enocean] Support EEP A5-13 for environmental sensors
  bundles/org.openhab.binding.enocean/README.md
  bundles/org.openhab.binding.enocean/src/main/java/org/openhab/binding/enocean/internal/EnOceanBindingConstants.java
  bundles/org.openhab.binding.enocean/src/main/java/org/openhab/binding/enocean/internal/eep/A5_13/A5_13.java
  bundles/org.openhab.binding.enocean/src/main/java/org/openhab/binding/enocean/internal/eep/A5_13/A5_13_01.java
  bundles/org.openhab.binding.enocean/src/main/java/org/openhab/binding/enocean/internal/eep/EEPType.java
  bundles/org.openhab.binding.enocean/src/main/java/org/openhab/binding/enocean/internal/handler/EnOceanBaseSensorHandler.java
  bundles/org.openhab.binding.enocean/src/main/resources/ESH-INF/thing/EnvironmentalSensor.xml
  bundles/org.openhab.binding.enocean/src/main/resources/ESH-INF/thing/channels.xml
Labels: cre, enhancement

#6443 [lgwebos] README updated to reflect that connectsdk library was removed
  bundles/org.openhab.binding.lgwebos/README.md
Labels: documentation

#6468 [kodi] Added German translations for 'shownotification' channel configuration
  bundles/org.openhab.binding.kodi/src/main/resources/ESH-INF/config/config.xml
  bundles/org.openhab.binding.kodi/src/main/resources/ESH-INF/i18n/kodi_de.properties
  bundles/org.openhab.binding.kodi/src/main/resources/ESH-INF/thing/thing-types.xml
Labels: translation

#6456 [lutron] Doc update
  bundles/org.openhab.binding.lutron/README.md
  bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/LutronHandlerFactory.java
  bundles/org.openhab.binding.lutron/src/main/resources/ESH-INF/binding/binding.xml
Labels: documentation
