Repository openhab/openhab-addons, pull requests merged in 2019-04, with the labels that each got.

#5248 [enocean] Add two new channel config parameters "eltakoDimmer" and "storeValue".
  addons/binding/org.openhab.binding.enocean/ESH-INF/thing/channels.xml
  addons/binding/org.openhab.binding.enocean/README.md
  addons/binding/org.openhab.binding.enocean/src/main/java/org/openhab/binding/enocean/internal/config/EnOceanChannelDimmerConfig.java
  addons/binding/org.openhab.binding.enocean/src/main/java/org/openhab/binding/enocean/internal/eep/A5_38/A5_38_08_Dimming.java
Labels: enhancement

#5355 [hdpowerview] Migrate to bnd build
  CODEOWNERS
  addons/binding/org.openhab.binding.hdpowerview/.classpath
  addons/binding/org.openhab.binding.hdpowerview/META-INF/MANIFEST.MF
  addons/binding/org.openhab.binding.hdpowerview/OSGI-INF/.gitignore
  addons/binding/org.openhab.binding.hdpowerview/build.properties
  addons/binding/org.openhab.binding.hdpowerview/lib/jcifs-1.3.18.jar
  addons/binding/pom.xml
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.hdpowerview/.classpath
  bundles/org.openhab.binding.hdpowerview/.project
  bundles/org.openhab.binding.hdpowerview/NOTICE
  bundles/org.openhab.binding.hdpowerview/README.md
  bundles/org.openhab.binding.hdpowerview/pom.xml
  bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/HDPowerViewBindingConstants.java
  bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/HDPowerViewHandlerFactory.java
  bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/HDPowerViewWebTargets.java
  bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/api/ShadePosition.java
  bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/api/ShadePositionKind.java
  bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/api/requests/ShadeIdPosition.java
  bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/api/requests/ShadeMove.java
  bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/api/responses/Scenes.java
  bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/api/responses/Shades.java
  bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/config/HDPowerViewHubConfiguration.java
  bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/config/HDPowerViewSceneConfiguration.java
  bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/config/HDPowerViewShadeConfiguration.java
  bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/discovery/HDPowerViewHubDiscoveryService.java
  bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/discovery/HDPowerViewShadeDiscoveryService.java
  bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/handler/AbstractHubbedThingHandler.java
  bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/handler/HDPowerViewHubHandler.java
  bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/handler/HDPowerViewShadeHandler.java
  bundles/org.openhab.binding.hdpowerview/src/main/resources/ESH-INF/binding/binding.xml
  bundles/org.openhab.binding.hdpowerview/src/main/resources/ESH-INF/thing/thing-types.xml
  bundles/pom.xml
  features/karaf/openhab-addons/src/main/feature/feature.xml
Labels: infrastructure

#5359 [mcp23017] Removed dependency on google guava library.
  addons/binding/org.openhab.binding.mcp23017/META-INF/MANIFEST.MF
  addons/binding/org.openhab.binding.mcp23017/src/main/java/org/openhab/binding/mcp23017/internal/Mcp23017BindingConstants.java
  addons/binding/org.openhab.binding.mcp23017/src/main/java/org/openhab/binding/mcp23017/internal/Mcp23017HandlerFactory.java
Labels: infrastructure

#5358 [kostalinverter] Migrate to bnd build
  CODEOWNERS
  addons/binding/org.openhab.binding.kostalinverter/.classpath
  addons/binding/org.openhab.binding.kostalinverter/META-INF/MANIFEST.MF
  addons/binding/org.openhab.binding.kostalinverter/OSGI-INF/.gitignore
  addons/binding/org.openhab.binding.kostalinverter/build.properties
  addons/binding/org.openhab.binding.kostalinverter/lib/jsoup-1.8.3.jar
  addons/binding/pom.xml
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.kostalinverter/.classpath
  bundles/org.openhab.binding.kostalinverter/.project
  bundles/org.openhab.binding.kostalinverter/NOTICE
  bundles/org.openhab.binding.kostalinverter/README.md
  bundles/org.openhab.binding.kostalinverter/doc/kostalpico.jpg
  bundles/org.openhab.binding.kostalinverter/doc/plenticore.jpg
  bundles/org.openhab.binding.kostalinverter/pom.xml
  bundles/org.openhab.binding.kostalinverter/src/main/java/org/openhab/binding/internal/kostal/inverter/KostalInverterFactory.java
  bundles/org.openhab.binding.kostalinverter/src/main/java/org/openhab/binding/internal/kostal/inverter/firstgeneration/ChannelConfig.java
  bundles/org.openhab.binding.kostalinverter/src/main/java/org/openhab/binding/internal/kostal/inverter/firstgeneration/SourceConfig.java
  bundles/org.openhab.binding.kostalinverter/src/main/java/org/openhab/binding/internal/kostal/inverter/firstgeneration/WebscrapeHandler.java
  bundles/org.openhab.binding.kostalinverter/src/main/java/org/openhab/binding/internal/kostal/inverter/thirdgeneration/ThirdGenerationBindingConstants.java
  bundles/org.openhab.binding.kostalinverter/src/main/java/org/openhab/binding/internal/kostal/inverter/thirdgeneration/ThirdGenerationChannelDatatypes.java
  bundles/org.openhab.binding.kostalinverter/src/main/java/org/openhab/binding/internal/kostal/inverter/thirdgeneration/ThirdGenerationChannelMappingToWebApi.java
  bundles/org.openhab.binding.kostalinverter/src/main/java/org/openhab/binding/internal/kostal/inverter/thirdgeneration/ThirdGenerationConfiguration.java
  bundles/org.openhab.binding.kostalinverter/src/main/java/org/openhab/binding/internal/kostal/inverter/thirdgeneration/ThirdGenerationEncryptionHelper.java
  bundles/org.openhab.binding.kostalinverter/src/main/java/org/openhab/binding/internal/kostal/inverter/thirdgeneration/ThirdGenerationHandler.java
  bundles/org.openhab.binding.kostalinverter/src/main/java/org/openhab/binding/internal/kostal/inverter/thirdgeneration/ThirdGenerationHttpHelper.java
  bundles/org.openhab.binding.kostalinverter/src/main/java/org/openhab/binding/internal/kostal/inverter/thirdgeneration/ThirdGenerationInverterTypes.java
  bundles/org.openhab.binding.kostalinverter/src/main/java/org/openhab/binding/internal/kostal/inverter/thirdgeneration/ThirdGenerationMappingInverterToChannel.java
  bundles/org.openhab.binding.kostalinverter/src/main/resources/ESH-INF/binding/binding.xml
  bundles/org.openhab.binding.kostalinverter/src/main/resources/ESH-INF/config/ThirdGeneration.xml
  bundles/org.openhab.binding.kostalinverter/src/main/resources/ESH-INF/i18n/kostalinverter_de.properties
  bundles/org.openhab.binding.kostalinverter/src/main/resources/ESH-INF/thing/Channels.xml
  bundles/org.openhab.binding.kostalinverter/src/main/resources/ESH-INF/thing/PIKOIQ100.xml
  bundles/org.openhab.binding.kostalinverter/src/main/resources/ESH-INF/thing/PIKOIQ42.xml
  bundles/org.openhab.binding.kostalinverter/src/main/resources/ESH-INF/thing/PIKOIQ55.xml
  bundles/org.openhab.binding.kostalinverter/src/main/resources/ESH-INF/thing/PIKOIQ70.xml
  bundles/org.openhab.binding.kostalinverter/src/main/resources/ESH-INF/thing/PIKOIQ85.xml
  bundles/org.openhab.binding.kostalinverter/src/main/resources/ESH-INF/thing/PLENTICOREPLUS100WITHBATTERY.xml
  bundles/org.openhab.binding.kostalinverter/src/main/resources/ESH-INF/thing/PLENTICOREPLUS100WITHOUTBATTERY.xml
  bundles/org.openhab.binding.kostalinverter/src/main/resources/ESH-INF/thing/PLENTICOREPLUS42WITHBATTERY.xml
  bundles/org.openhab.binding.kostalinverter/src/main/resources/ESH-INF/thing/PLENTICOREPLUS42WITHOUTBATTERY.xml
  bundles/org.openhab.binding.kostalinverter/src/main/resources/ESH-INF/thing/PLENTICOREPLUS55WITHBATTERY.xml
  bundles/org.openhab.binding.kostalinverter/src/main/resources/ESH-INF/thing/PLENTICOREPLUS55WITHOUTBATTERY.xml
  bundles/org.openhab.binding.kostalinverter/src/main/resources/ESH-INF/thing/PLENTICOREPLUS70WITHBATTERY.xml
  bundles/org.openhab.binding.kostalinverter/src/main/resources/ESH-INF/thing/PLENTICOREPLUS70WITHOUTBATTERY.xml
  bundles/org.openhab.binding.kostalinverter/src/main/resources/ESH-INF/thing/PLENTICOREPLUS85WITHBATTERY.xml
  bundles/org.openhab.binding.kostalinverter/src/main/resources/ESH-INF/thing/PLENTICOREPLUS85WITHOUTBATTERY.xml
  bundles/org.openhab.binding.kostalinverter/src/main/resources/ESH-INF/thing/thing-types.xml
  bundles/pom.xml
  features/karaf/openhab-addons/src/main/feature/feature.xml
Labels: infrastructure

#5360 [opensprinkler] Migrate to bnd build
  CODEOWNERS
  addons/binding/org.openhab.binding.opensprinkler/.classpath
  addons/binding/org.openhab.binding.opensprinkler/.project
  addons/binding/org.openhab.binding.opensprinkler/META-INF/MANIFEST.MF
  addons/binding/org.openhab.binding.opensprinkler/OSGI-INF/.gitignore
  addons/binding/org.openhab.binding.opensprinkler/build.properties
  addons/binding/org.openhab.binding.opensprinkler/lib/pi4j-core.jar
  addons/binding/pom.xml
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.opensprinkler/.classpath
  bundles/org.openhab.binding.opensprinkler/.project
  bundles/org.openhab.binding.opensprinkler/NOTICE
  bundles/org.openhab.binding.opensprinkler/README.md
  bundles/org.openhab.binding.opensprinkler/pom.xml
  bundles/org.openhab.binding.opensprinkler/src/main/java/org/openhab/binding/opensprinkler/internal/OpenSprinklerBindingConstants.java
  bundles/org.openhab.binding.opensprinkler/src/main/java/org/openhab/binding/opensprinkler/internal/OpenSprinklerHandlerFactory.java
  bundles/org.openhab.binding.opensprinkler/src/main/java/org/openhab/binding/opensprinkler/internal/api/OpenSprinklerApi.java
  bundles/org.openhab.binding.opensprinkler/src/main/java/org/openhab/binding/opensprinkler/internal/api/OpenSprinklerApiConstants.java
  bundles/org.openhab.binding.opensprinkler/src/main/java/org/openhab/binding/opensprinkler/internal/api/OpenSprinklerApiFactory.java
  bundles/org.openhab.binding.opensprinkler/src/main/java/org/openhab/binding/opensprinkler/internal/api/OpenSprinklerGpioApi.java
  bundles/org.openhab.binding.opensprinkler/src/main/java/org/openhab/binding/opensprinkler/internal/api/OpenSprinklerHttpApiV100.java
  bundles/org.openhab.binding.opensprinkler/src/main/java/org/openhab/binding/opensprinkler/internal/api/OpenSprinklerHttpApiV210.java
  bundles/org.openhab.binding.opensprinkler/src/main/java/org/openhab/binding/opensprinkler/internal/api/OpenSprinklerHttpApiV213.java
  bundles/org.openhab.binding.opensprinkler/src/main/java/org/openhab/binding/opensprinkler/internal/api/exception/CommunicationApiException.java
  bundles/org.openhab.binding.opensprinkler/src/main/java/org/openhab/binding/opensprinkler/internal/api/exception/DataFormatErrorApiException.java
  bundles/org.openhab.binding.opensprinkler/src/main/java/org/openhab/binding/opensprinkler/internal/api/exception/DataMissingApiException.java
  bundles/org.openhab.binding.opensprinkler/src/main/java/org/openhab/binding/opensprinkler/internal/api/exception/GeneralApiException.java
  bundles/org.openhab.binding.opensprinkler/src/main/java/org/openhab/binding/opensprinkler/internal/api/exception/MismatchApiException.java
  bundles/org.openhab.binding.opensprinkler/src/main/java/org/openhab/binding/opensprinkler/internal/api/exception/NotPermittedApiException.java
  bundles/org.openhab.binding.opensprinkler/src/main/java/org/openhab/binding/opensprinkler/internal/api/exception/OutOfRangeApiException.java
  bundles/org.openhab.binding.opensprinkler/src/main/java/org/openhab/binding/opensprinkler/internal/api/exception/PageNotFoundApiException.java
  bundles/org.openhab.binding.opensprinkler/src/main/java/org/openhab/binding/opensprinkler/internal/api/exception/UnauthorizedApiException.java
  bundles/org.openhab.binding.opensprinkler/src/main/java/org/openhab/binding/opensprinkler/internal/api/exception/UnknownApiException.java
  bundles/org.openhab.binding.opensprinkler/src/main/java/org/openhab/binding/opensprinkler/internal/config/OpenSprinklerConfig.java
  bundles/org.openhab.binding.opensprinkler/src/main/java/org/openhab/binding/opensprinkler/internal/config/OpenSprinklerPiConfig.java
  bundles/org.openhab.binding.opensprinkler/src/main/java/org/openhab/binding/opensprinkler/internal/discovery/OpenSprinklerDiscoveryJob.java
  bundles/org.openhab.binding.opensprinkler/src/main/java/org/openhab/binding/opensprinkler/internal/discovery/OpenSprinklerDiscoveryService.java
  bundles/org.openhab.binding.opensprinkler/src/main/java/org/openhab/binding/opensprinkler/internal/handler/OpenSprinklerHTTPHandler.java
  bundles/org.openhab.binding.opensprinkler/src/main/java/org/openhab/binding/opensprinkler/internal/handler/OpenSprinklerHandler.java
  bundles/org.openhab.binding.opensprinkler/src/main/java/org/openhab/binding/opensprinkler/internal/handler/OpenSprinklerPiHandler.java
  bundles/org.openhab.binding.opensprinkler/src/main/java/org/openhab/binding/opensprinkler/internal/util/Hash.java
  bundles/org.openhab.binding.opensprinkler/src/main/java/org/openhab/binding/opensprinkler/internal/util/Http.java
  bundles/org.openhab.binding.opensprinkler/src/main/java/org/openhab/binding/opensprinkler/internal/util/Parse.java
  bundles/org.openhab.binding.opensprinkler/src/main/resources/ESH-INF/binding/binding.xml
  bundles/org.openhab.binding.opensprinkler/src/main/resources/ESH-INF/thing/thing-types.xml
  bundles/pom.xml
  features/karaf/openhab-addons/src/main/feature/feature.xml
Labels: infrastructure

#5348 [bin2json] Initial commit
  bundles/org.openhab.transform.bin2json/.classpath
  bundles/org.openhab.transform.bin2json/.project
  bundles/org.openhab.transform.bin2json/NOTICE
  bundles/org.openhab.transform.bin2json/README.md
  bundles/org.openhab.transform.bin2json/pom.xml
  bundles/org.openhab.transform.bin2json/src/main/java/org/openhab/transform/bin2json/internal/Bin2Json.java
  bundles/org.openhab.transform.bin2json/src/main/java/org/openhab/transform/bin2json/internal/Bin2JsonTransformationService.java
  bundles/org.openhab.transform.bin2json/src/main/java/org/openhab/transform/bin2json/internal/ConversionException.java
  bundles/pom.xml
  features/karaf/openhab-addons/src/main/feature/feature.xml
Labels: new transform

#5349 [avmfritz] Downgrade JAXB to 2.2
  bundles/org.openhab.binding.avmfritz/pom.xml
  features/karaf/openhab-addons/src/main/feature/feature.xml
Labels: infrastructure

#5354 [marytts] Migrate to bnd build
  .gitignore
  CODEOWNERS
  addons/voice/org.openhab.voice.marytts/.classpath
  addons/voice/org.openhab.voice.marytts/META-INF/MANIFEST.MF
  addons/voice/org.openhab.voice.marytts/OSGI-INF/.gitignore
  addons/voice/org.openhab.voice.marytts/build.properties
  addons/voice/org.openhab.voice.marytts/lib/log4j-over-slf4j-1.7.21.jar
  addons/voice/pom.xml
  bom/openhab-addons/pom.xml
  bundles/org.openhab.voice.marytts/.classpath
  bundles/org.openhab.voice.marytts/.project
  bundles/org.openhab.voice.marytts/NOTICE
  bundles/org.openhab.voice.marytts/README-DEV.txt
  bundles/org.openhab.voice.marytts/README.md
  bundles/org.openhab.voice.marytts/lib/.gitignore
  bundles/org.openhab.voice.marytts/lib/marytts-common-5.1-SNAPSHOT.jar
  bundles/org.openhab.voice.marytts/lib/marytts-runtime-5.1-SNAPSHOT.jar
  bundles/org.openhab.voice.marytts/lib/marytts-server-5.1-SNAPSHOT.jar
  bundles/org.openhab.voice.marytts/lib/marytts-signalproc-5.1-SNAPSHOT.jar
  bundles/org.openhab.voice.marytts/pom.xml
  bundles/org.openhab.voice.marytts/src/main/java/org/openhab/voice/marytts/internal/MaryTTSAudioStream.java
  bundles/org.openhab.voice.marytts/src/main/java/org/openhab/voice/marytts/internal/MaryTTSService.java
  bundles/org.openhab.voice.marytts/src/main/java/org/openhab/voice/marytts/internal/MaryTTSVoice.java
  bundles/pom.xml
  features/karaf/openhab-addons/src/main/feature/feature.xml
Labels: infrastructure

#5370 Added missing wrap prerequisite in feature.xml
  features/karaf/openhab-addons/src/main/feature/feature.xml
Labels: infrastructure

#4527 [digiplex] Digiplex/EVO Binding initial contribution
  CODEOWNERS
  addons/binding/org.openhab.binding.digiplex/.project
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.digiplex/.classpath
  bundles/org.openhab.binding.digiplex/.project
  bundles/org.openhab.binding.digiplex/NOTICE
  bundles/org.openhab.binding.digiplex/README.md
  bundles/org.openhab.binding.digiplex/pom.xml
  bundles/org.openhab.binding.digiplex/src/main/java/org/openhab/binding/digiplex/DigiplexBindingConstants.java
  bundles/org.openhab.binding.digiplex/src/main/java/org/openhab/binding/digiplex/communication/AbstractResponse.java
  bundles/org.openhab.binding.digiplex/src/main/java/org/openhab/binding/digiplex/communication/AreaArmDisarmResponse.java
  bundles/org.openhab.binding.digiplex/src/main/java/org/openhab/binding/digiplex/communication/AreaArmRequest.java
  bundles/org.openhab.binding.digiplex/src/main/java/org/openhab/binding/digiplex/communication/AreaDisarmRequest.java
  bundles/org.openhab.binding.digiplex/src/main/java/org/openhab/binding/digiplex/communication/AreaLabelRequest.java
  bundles/org.openhab.binding.digiplex/src/main/java/org/openhab/binding/digiplex/communication/AreaLabelResponse.java
  bundles/org.openhab.binding.digiplex/src/main/java/org/openhab/binding/digiplex/communication/AreaQuickArmRequest.java
  bundles/org.openhab.binding.digiplex/src/main/java/org/openhab/binding/digiplex/communication/AreaStatus.java
  bundles/org.openhab.binding.digiplex/src/main/java/org/openhab/binding/digiplex/communication/AreaStatusRequest.java
  bundles/org.openhab.binding.digiplex/src/main/java/org/openhab/binding/digiplex/communication/AreaStatusResponse.java
  bundles/org.openhab.binding.digiplex/src/main/java/org/openhab/binding/digiplex/communication/ArmDisarmType.java
  bundles/org.openhab.binding.digiplex/src/main/java/org/openhab/binding/digiplex/communication/ArmType.java
  bundles/org.openhab.binding.digiplex/src/main/java/org/openhab/binding/digiplex/communication/CommunicationStatus.java
  bundles/org.openhab.binding.digiplex/src/main/java/org/openhab/binding/digiplex/communication/DigiplexMessage.java
  bundles/org.openhab.binding.digiplex/src/main/java/org/openhab/binding/digiplex/communication/DigiplexMessageHandler.java
  bundles/org.openhab.binding.digiplex/src/main/java/org/openhab/binding/digiplex/communication/DigiplexRequest.java
  bundles/org.openhab.binding.digiplex/src/main/java/org/openhab/binding/digiplex/communication/DigiplexResponse.java
  bundles/org.openhab.binding.digiplex/src/main/java/org/openhab/binding/digiplex/communication/DigiplexResponseResolver.java
  bundles/org.openhab.binding.digiplex/src/main/java/org/openhab/binding/digiplex/communication/UnknownResponse.java
  bundles/org.openhab.binding.digiplex/src/main/java/org/openhab/binding/digiplex/communication/ZoneLabelRequest.java
  bundles/org.openhab.binding.digiplex/src/main/java/org/openhab/binding/digiplex/communication/ZoneLabelResponse.java
  bundles/org.openhab.binding.digiplex/src/main/java/org/openhab/binding/digiplex/communication/ZoneStatus.java
  bundles/org.openhab.binding.digiplex/src/main/java/org/openhab/binding/digiplex/communication/ZoneStatusRequest.java
  bundles/org.openhab.binding.digiplex/src/main/java/org/openhab/binding/digiplex/communication/ZoneStatusResponse.java
  bundles/org.openhab.binding.digiplex/src/main/java/org/openhab/binding/digiplex/communication/events/AbstractEvent.java
  bundles/org.openhab.binding.digiplex/src/main/java/org/openhab/binding/digiplex/communication/events/AreaEvent.java
  bundles/org.openhab.binding.digiplex/src/main/java/org/openhab/binding/digiplex/communication/events/AreaEventType.java
  bundles/org.openhab.binding.digiplex/src/main/java/org/openhab/binding/digiplex/communication/events/GenericEvent.java
  bundles/org.openhab.binding.digiplex/src/main/java/org/openhab/binding/digiplex/communication/events/SpecialAlarmEvent.java
  bundles/org.openhab.binding.digiplex/src/main/java/org/openhab/binding/digiplex/communication/events/SpecialAlarmType.java
  bundles/org.openhab.binding.digiplex/src/main/java/org/openhab/binding/digiplex/communication/events/ZoneEvent.java
  bundles/org.openhab.binding.digiplex/src/main/java/org/openhab/binding/digiplex/communication/events/ZoneEventType.java
  bundles/org.openhab.binding.digiplex/src/main/java/org/openhab/binding/digiplex/communication/events/ZoneStatusEvent.java
  bundles/org.openhab.binding.digiplex/src/main/java/org/openhab/binding/digiplex/discovery/DigiplexDiscoveryService.java
  bundles/org.openhab.binding.digiplex/src/main/java/org/openhab/binding/digiplex/handler/DigiplexAreaHandler.java
  bundles/org.openhab.binding.digiplex/src/main/java/org/openhab/binding/digiplex/handler/DigiplexBridgeHandler.java
  bundles/org.openhab.binding.digiplex/src/main/java/org/openhab/binding/digiplex/handler/DigiplexZoneHandler.java
  bundles/org.openhab.binding.digiplex/src/main/java/org/openhab/binding/digiplex/handler/TypeUtils.java
  bundles/org.openhab.binding.digiplex/src/main/java/org/openhab/binding/digiplex/internal/DigiplexAreaConfiguration.java
  bundles/org.openhab.binding.digiplex/src/main/java/org/openhab/binding/digiplex/internal/DigiplexBridgeConfiguration.java
  bundles/org.openhab.binding.digiplex/src/main/java/org/openhab/binding/digiplex/internal/DigiplexHandlerFactory.java
  bundles/org.openhab.binding.digiplex/src/main/resources/ESH-INF/binding/binding.xml
  bundles/org.openhab.binding.digiplex/src/main/resources/ESH-INF/i18n/digiplex_xx_XX.properties
  bundles/org.openhab.binding.digiplex/src/main/resources/ESH-INF/thing/area.xml
  bundles/org.openhab.binding.digiplex/src/main/resources/ESH-INF/thing/bridge.xml
  bundles/org.openhab.binding.digiplex/src/main/resources/ESH-INF/thing/zone.xml
  bundles/pom.xml
  features/karaf/openhab-addons/src/main/feature/feature.xml
Labels: new binding

#5380 [tado] Migrate to bnd build
  CODEOWNERS
  addons/binding/org.openhab.binding.tado/.classpath
  addons/binding/org.openhab.binding.tado/META-INF/MANIFEST.MF
  addons/binding/org.openhab.binding.tado/OSGI-INF/.gitignore
  addons/binding/org.openhab.binding.tado/build.properties
  addons/binding/pom.xml
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.tado/.classpath
  bundles/org.openhab.binding.tado/.project
  bundles/org.openhab.binding.tado/NOTICE
  bundles/org.openhab.binding.tado/README.md
  bundles/org.openhab.binding.tado/lib/tado-api-client-1.2.jar
  bundles/org.openhab.binding.tado/pom.xml
  bundles/org.openhab.binding.tado/src/main/api/pom.xml
  bundles/org.openhab.binding.tado/src/main/api/tado-api.yaml
  bundles/org.openhab.binding.tado/src/main/java/org/openhab/binding/tado/internal/TadoBindingConstants.java
  bundles/org.openhab.binding.tado/src/main/java/org/openhab/binding/tado/internal/TadoHvacChange.java
  bundles/org.openhab.binding.tado/src/main/java/org/openhab/binding/tado/internal/adapter/TadoZoneStateAdapter.java
  bundles/org.openhab.binding.tado/src/main/java/org/openhab/binding/tado/internal/api/HomeApiFactory.java
  bundles/org.openhab.binding.tado/src/main/java/org/openhab/binding/tado/internal/api/TadoApiTypeUtils.java
  bundles/org.openhab.binding.tado/src/main/java/org/openhab/binding/tado/internal/builder/AirConditioningZoneSettingsBuilder.java
  bundles/org.openhab.binding.tado/src/main/java/org/openhab/binding/tado/internal/builder/HeatingZoneSettingsBuilder.java
  bundles/org.openhab.binding.tado/src/main/java/org/openhab/binding/tado/internal/builder/HotWaterZoneSettingsBuilder.java
  bundles/org.openhab.binding.tado/src/main/java/org/openhab/binding/tado/internal/builder/TerminationConditionBuilder.java
  bundles/org.openhab.binding.tado/src/main/java/org/openhab/binding/tado/internal/builder/ZoneSettingsBuilder.java
  bundles/org.openhab.binding.tado/src/main/java/org/openhab/binding/tado/internal/builder/ZoneStateProvider.java
  bundles/org.openhab.binding.tado/src/main/java/org/openhab/binding/tado/internal/config/TadoHomeConfig.java
  bundles/org.openhab.binding.tado/src/main/java/org/openhab/binding/tado/internal/config/TadoMobileDeviceConfig.java
  bundles/org.openhab.binding.tado/src/main/java/org/openhab/binding/tado/internal/config/TadoZoneConfig.java
  bundles/org.openhab.binding.tado/src/main/java/org/openhab/binding/tado/internal/discovery/TadoDiscoveryService.java
  bundles/org.openhab.binding.tado/src/main/java/org/openhab/binding/tado/internal/handler/BaseHomeThingHandler.java
  bundles/org.openhab.binding.tado/src/main/java/org/openhab/binding/tado/internal/handler/TadoHandlerFactory.java
  bundles/org.openhab.binding.tado/src/main/java/org/openhab/binding/tado/internal/handler/TadoHomeHandler.java
  bundles/org.openhab.binding.tado/src/main/java/org/openhab/binding/tado/internal/handler/TadoMobileDeviceHandler.java
  bundles/org.openhab.binding.tado/src/main/java/org/openhab/binding/tado/internal/handler/TadoZoneHandler.java
  bundles/org.openhab.binding.tado/src/main/resources/ESH-INF/binding/binding.xml
  bundles/org.openhab.binding.tado/src/main/resources/ESH-INF/thing/thing-types.xml
  bundles/pom.xml
  features/karaf/openhab-addons/src/main/feature/feature.xml
Labels: infrastructure

#5290 [neato] Migrate to bnd build
  CODEOWNERS
  addons/binding/org.openhab.binding.neato/.classpath
  addons/binding/org.openhab.binding.neato/META-INF/MANIFEST.MF
  addons/binding/org.openhab.binding.neato/OSGI-INF/.gitignore
  addons/binding/org.openhab.binding.neato/build.properties
  addons/binding/pom.xml
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.neato/.classpath
  bundles/org.openhab.binding.neato/.project
  bundles/org.openhab.binding.neato/NOTICE
  bundles/org.openhab.binding.neato/README.md
  bundles/org.openhab.binding.neato/pom.xml
  bundles/org.openhab.binding.neato/src/main/java/org/openhab/binding/neato/internal/CouldNotFindRobotException.java
  bundles/org.openhab.binding.neato/src/main/java/org/openhab/binding/neato/internal/NeatoBindingConstants.java
  bundles/org.openhab.binding.neato/src/main/java/org/openhab/binding/neato/internal/NeatoCommunicationException.java
  bundles/org.openhab.binding.neato/src/main/java/org/openhab/binding/neato/internal/NeatoHandlerFactory.java
  bundles/org.openhab.binding.neato/src/main/java/org/openhab/binding/neato/internal/NeatoRobot.java
  bundles/org.openhab.binding.neato/src/main/java/org/openhab/binding/neato/internal/classes/AvailableCommands.java
  bundles/org.openhab.binding.neato/src/main/java/org/openhab/binding/neato/internal/classes/AvailableServices.java
  bundles/org.openhab.binding.neato/src/main/java/org/openhab/binding/neato/internal/classes/Battery.java
  bundles/org.openhab.binding.neato/src/main/java/org/openhab/binding/neato/internal/classes/BeehiveAuthentication.java
  bundles/org.openhab.binding.neato/src/main/java/org/openhab/binding/neato/internal/classes/Cleaning.java
  bundles/org.openhab.binding.neato/src/main/java/org/openhab/binding/neato/internal/classes/Details.java
  bundles/org.openhab.binding.neato/src/main/java/org/openhab/binding/neato/internal/classes/ErrorMessage.java
  bundles/org.openhab.binding.neato/src/main/java/org/openhab/binding/neato/internal/classes/Meta.java
  bundles/org.openhab.binding.neato/src/main/java/org/openhab/binding/neato/internal/classes/NeatoAccountInformation.java
  bundles/org.openhab.binding.neato/src/main/java/org/openhab/binding/neato/internal/classes/NeatoGeneralInfo.java
  bundles/org.openhab.binding.neato/src/main/java/org/openhab/binding/neato/internal/classes/NeatoRobotInfo.java
  bundles/org.openhab.binding.neato/src/main/java/org/openhab/binding/neato/internal/classes/NeatoState.java
  bundles/org.openhab.binding.neato/src/main/java/org/openhab/binding/neato/internal/classes/RecentFirmwares.java
  bundles/org.openhab.binding.neato/src/main/java/org/openhab/binding/neato/internal/classes/Robot.java
  bundles/org.openhab.binding.neato/src/main/java/org/openhab/binding/neato/internal/classes/RobotInfoData.java
  bundles/org.openhab.binding.neato/src/main/java/org/openhab/binding/neato/internal/config/NeatoAccountConfig.java
  bundles/org.openhab.binding.neato/src/main/java/org/openhab/binding/neato/internal/config/NeatoRobotConfig.java
  bundles/org.openhab.binding.neato/src/main/java/org/openhab/binding/neato/internal/discovery/NeatoAccountDiscoveryService.java
  bundles/org.openhab.binding.neato/src/main/java/org/openhab/binding/neato/internal/handler/NeatoAccountHandler.java
  bundles/org.openhab.binding.neato/src/main/java/org/openhab/binding/neato/internal/handler/NeatoHandler.java
  bundles/org.openhab.binding.neato/src/main/resources/ESH-INF/binding/binding.xml
  bundles/org.openhab.binding.neato/src/main/resources/ESH-INF/thing/vacuumcleaner.xml
  bundles/pom.xml
  features/karaf/openhab-addons/src/main/feature/feature.xml
Labels: infrastructure

#5377 [wemo] Migrate to bnd build
  CODEOWNERS
  addons/binding/org.openhab.binding.wemo.test/.classpath
  addons/binding/org.openhab.binding.wemo.test/META-INF/MANIFEST.MF
  addons/binding/org.openhab.binding.wemo.test/build.properties
  addons/binding/org.openhab.binding.wemo.test/org.openhab.binding.wemo.tests.launch
  addons/binding/org.openhab.binding.wemo.test/pom.xml
  addons/binding/org.openhab.binding.wemo/.classpath
  addons/binding/org.openhab.binding.wemo/META-INF/MANIFEST.MF
  addons/binding/org.openhab.binding.wemo/OSGI-INF/.gitignore
  addons/binding/org.openhab.binding.wemo/build.properties
  addons/binding/pom.xml
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.wemo/.classpath
  bundles/org.openhab.binding.wemo/.project
  bundles/org.openhab.binding.wemo/NOTICE
  bundles/org.openhab.binding.wemo/README.md
  bundles/org.openhab.binding.wemo/pom.xml
  bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/WemoBindingConstants.java
  bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/WemoHandlerFactory.java
  bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/discovery/WemoDiscoveryParticipant.java
  bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/discovery/WemoDiscoveryService.java
  bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/discovery/WemoLinkDiscoveryService.java
  bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/handler/AbstractWemoHandler.java
  bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/handler/WemoBridgeHandler.java
  bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/handler/WemoCoffeeHandler.java
  bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/handler/WemoHandler.java
  bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/handler/WemoLightHandler.java
  bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/handler/WemoMakerHandler.java
  bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/http/WemoHttpCall.java
  bundles/org.openhab.binding.wemo/src/main/resources/ESH-INF/binding/binding.xml
  bundles/org.openhab.binding.wemo/src/main/resources/ESH-INF/thing/bridge.xml
  bundles/org.openhab.binding.wemo/src/main/resources/ESH-INF/thing/thing-types.xml
  bundles/pom.xml
  features/karaf/openhab-addons/src/main/feature/feature.xml
  itests/org.openhab.binding.wemo.tests/.classpath
  itests/org.openhab.binding.wemo.tests/.project
  itests/org.openhab.binding.wemo.tests/NOTICE
  itests/org.openhab.binding.wemo.tests/itest.bndrun
  itests/org.openhab.binding.wemo.tests/pom.xml
  itests/org.openhab.binding.wemo.tests/src/main/java/org/openhab/binding/wemo/internal/discovery/test/WemoDiscoveryOSGiTest.java
  itests/org.openhab.binding.wemo.tests/src/main/java/org/openhab/binding/wemo/internal/discovery/test/WemoDiscoveryParticipantTest.java
  itests/org.openhab.binding.wemo.tests/src/main/java/org/openhab/binding/wemo/internal/discovery/test/WemoLinkDiscoveryServiceOSGiTest.java
  itests/org.openhab.binding.wemo.tests/src/main/java/org/openhab/binding/wemo/internal/handler/test/WemoHandlerOSGiTest.java
  itests/org.openhab.binding.wemo.tests/src/main/java/org/openhab/binding/wemo/internal/handler/test/WemoHandlerTest.java
  itests/org.openhab.binding.wemo.tests/src/main/java/org/openhab/binding/wemo/internal/handler/test/WemoLightHandlerOSGiTest.java
  itests/org.openhab.binding.wemo.tests/src/main/java/org/openhab/binding/wemo/internal/handler/test/WemoMakerHandlerOSGiTest.java
  itests/org.openhab.binding.wemo.tests/src/main/java/org/openhab/binding/wemo/internal/test/GenericWemoLightOSGiTestParent.java
  itests/org.openhab.binding.wemo.tests/src/main/java/org/openhab/binding/wemo/internal/test/GenericWemoOSGiTest.java
  itests/pom.xml
Labels: infrastructure

#5385 use provided scope (not transitive) for addjars
  poms/bnd/pom.xml
Labels: critical, infrastructure

#5383 [logreader] Migrate to bnd build
  CODEOWNERS
  addons/binding/org.openhab.binding.logreader/.classpath
  addons/binding/org.openhab.binding.logreader/META-INF/MANIFEST.MF
  addons/binding/org.openhab.binding.logreader/OSGI-INF/.gitignore
  addons/binding/org.openhab.binding.logreader/build.properties
  addons/binding/pom.xml
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.logreader/.classpath
  bundles/org.openhab.binding.logreader/.project
  bundles/org.openhab.binding.logreader/NOTICE
  bundles/org.openhab.binding.logreader/README.md
  bundles/org.openhab.binding.logreader/lib/commons-io-2.7-20180506.jar
  bundles/org.openhab.binding.logreader/pom.xml
  bundles/org.openhab.binding.logreader/src/main/java/org/openhab/binding/logreader/internal/LogReaderBindingConstants.java
  bundles/org.openhab.binding.logreader/src/main/java/org/openhab/binding/logreader/internal/LogReaderHandlerFactory.java
  bundles/org.openhab.binding.logreader/src/main/java/org/openhab/binding/logreader/internal/config/LogReaderConfiguration.java
  bundles/org.openhab.binding.logreader/src/main/java/org/openhab/binding/logreader/internal/filereader/AbstractLogFileReader.java
  bundles/org.openhab.binding.logreader/src/main/java/org/openhab/binding/logreader/internal/filereader/FileTailer.java
  bundles/org.openhab.binding.logreader/src/main/java/org/openhab/binding/logreader/internal/filereader/api/FileReaderException.java
  bundles/org.openhab.binding.logreader/src/main/java/org/openhab/binding/logreader/internal/filereader/api/FileReaderListener.java
  bundles/org.openhab.binding.logreader/src/main/java/org/openhab/binding/logreader/internal/filereader/api/LogFileReader.java
  bundles/org.openhab.binding.logreader/src/main/java/org/openhab/binding/logreader/internal/handler/LogHandler.java
  bundles/org.openhab.binding.logreader/src/main/java/org/openhab/binding/logreader/internal/searchengine/SearchEngine.java
  bundles/org.openhab.binding.logreader/src/main/resources/ESH-INF/binding/binding.xml
  bundles/org.openhab.binding.logreader/src/main/resources/ESH-INF/thing/channels.xml
  bundles/org.openhab.binding.logreader/src/main/resources/ESH-INF/thing/reader.xml
  bundles/pom.xml
  features/karaf/openhab-addons/src/main/feature/feature.xml
Labels: infrastructure

#5384 [hue] Splitted tests into unit / integration tests
  bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/discovery/BridgeJsonParameters.java
  bundles/org.openhab.binding.hue/src/test/java/org/openhab/binding/hue/internal/ApiVersionTest.java
  bundles/org.openhab.binding.hue/src/test/java/org/openhab/binding/hue/internal/LightStateConverterTest.java
  bundles/org.openhab.binding.hue/src/test/java/org/openhab/binding/hue/internal/handler/HueLightHandlerTest.java
  bundles/org.openhab.binding.hue/src/test/java/org/openhab/binding/hue/internal/handler/HueLightState.java
  itests/org.openhab.binding.hue.tests/src/main/java/org/openhab/binding/hue/internal/AbstractHueOSGiTestParent.java
  itests/org.openhab.binding.hue.tests/src/main/java/org/openhab/binding/hue/internal/HueLightDiscoveryServiceOSGiTest.java
  itests/org.openhab.binding.hue.tests/src/main/java/org/openhab/binding/hue/internal/MockedHttpClient.java
  itests/org.openhab.binding.hue.tests/src/main/java/org/openhab/binding/hue/internal/discovery/HueBridgeDiscoveryParticipantOSGITest.java
  itests/org.openhab.binding.hue.tests/src/main/java/org/openhab/binding/hue/internal/handler/HueBridgeHandlerOSGiTest.java
Labels: infrastructure

#5388 [minecraft] Migrate to bnd build
  CODEOWNERS
  addons/binding/org.openhab.binding.minecraft/.classpath
  addons/binding/org.openhab.binding.minecraft/META-INF/MANIFEST.MF
  addons/binding/org.openhab.binding.minecraft/OSGI-INF/.gitignore
  addons/binding/org.openhab.binding.minecraft/build.properties
  addons/binding/org.openhab.binding.minecraft/lib/rxjava-1.1.7.jar
  addons/binding/org.openhab.binding.minecraft/lib/tubesock-0.0.1.jar
  addons/binding/org.openhab.binding.minecraft/pom.xml
  addons/binding/pom.xml
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.minecraft/.classpath
  bundles/org.openhab.binding.minecraft/.project
  bundles/org.openhab.binding.minecraft/NOTICE
  bundles/org.openhab.binding.minecraft/README.md
  bundles/org.openhab.binding.minecraft/pom.xml
  bundles/org.openhab.binding.minecraft/src/main/java/org/openhab/binding/minecraft/internal/MinecraftBindingConstants.java
  bundles/org.openhab.binding.minecraft/src/main/java/org/openhab/binding/minecraft/internal/MinecraftHandlerFactory.java
  bundles/org.openhab.binding.minecraft/src/main/java/org/openhab/binding/minecraft/internal/config/PlayerConfig.java
  bundles/org.openhab.binding.minecraft/src/main/java/org/openhab/binding/minecraft/internal/config/ServerConfig.java
  bundles/org.openhab.binding.minecraft/src/main/java/org/openhab/binding/minecraft/internal/config/SignConfig.java
  bundles/org.openhab.binding.minecraft/src/main/java/org/openhab/binding/minecraft/internal/discovery/MinecraftDiscoveryService.java
  bundles/org.openhab.binding.minecraft/src/main/java/org/openhab/binding/minecraft/internal/discovery/MinecraftMDNSDiscoveryParticipant.java
  bundles/org.openhab.binding.minecraft/src/main/java/org/openhab/binding/minecraft/internal/handler/MinecraftPlayerHandler.java
  bundles/org.openhab.binding.minecraft/src/main/java/org/openhab/binding/minecraft/internal/handler/MinecraftServerHandler.java
  bundles/org.openhab.binding.minecraft/src/main/java/org/openhab/binding/minecraft/internal/handler/MinecraftSignHandler.java
  bundles/org.openhab.binding.minecraft/src/main/java/org/openhab/binding/minecraft/internal/message/OHMessage.java
  bundles/org.openhab.binding.minecraft/src/main/java/org/openhab/binding/minecraft/internal/message/data/LocationData.java
  bundles/org.openhab.binding.minecraft/src/main/java/org/openhab/binding/minecraft/internal/message/data/PlayerData.java
  bundles/org.openhab.binding.minecraft/src/main/java/org/openhab/binding/minecraft/internal/message/data/ServerData.java
  bundles/org.openhab.binding.minecraft/src/main/java/org/openhab/binding/minecraft/internal/message/data/SignData.java
  bundles/org.openhab.binding.minecraft/src/main/java/org/openhab/binding/minecraft/internal/message/data/commands/PlayerCommandData.java
  bundles/org.openhab.binding.minecraft/src/main/java/org/openhab/binding/minecraft/internal/message/data/commands/SignCommandData.java
  bundles/org.openhab.binding.minecraft/src/main/java/org/openhab/binding/minecraft/internal/server/MinecraftSocketHandler.java
  bundles/org.openhab.binding.minecraft/src/main/java/org/openhab/binding/minecraft/internal/server/ServerConnection.java
  bundles/org.openhab.binding.minecraft/src/main/java/org/openhab/binding/minecraft/internal/util/Pair.java
  bundles/org.openhab.binding.minecraft/src/main/java/org/openhab/binding/minecraft/internal/util/RetryWithDelay.java
  bundles/org.openhab.binding.minecraft/src/main/resources/ESH-INF/binding/binding.xml
  bundles/org.openhab.binding.minecraft/src/main/resources/ESH-INF/thing/thing-types.xml
  bundles/pom.xml
  features/karaf/openhab-addons/src/main/feature/feature.xml
Labels: infrastructure

#5246 [modbus] Added discovery service
  addons/binding/org.openhab.binding.modbus/DEVELOPERS.md
  addons/binding/org.openhab.binding.modbus/ESH-INF/thing/bridge-serial.xml
  addons/binding/org.openhab.binding.modbus/ESH-INF/thing/bridge-tcp.xml
  addons/binding/org.openhab.binding.modbus/META-INF/MANIFEST.MF
  addons/binding/org.openhab.binding.modbus/README.md
  addons/binding/org.openhab.binding.modbus/doc/images/DiscoveryProcess.png
  addons/binding/org.openhab.binding.modbus/doc/images/ModbusExtensibleDiscovery.png
  addons/binding/org.openhab.binding.modbus/src/main/java/org/openhab/binding/modbus/discovery/ModbusDiscoveryListener.java
  addons/binding/org.openhab.binding.modbus/src/main/java/org/openhab/binding/modbus/discovery/ModbusDiscoveryParticipant.java
  addons/binding/org.openhab.binding.modbus/src/main/java/org/openhab/binding/modbus/discovery/internal/ModbusDiscoveryService.java
  addons/binding/org.openhab.binding.modbus/src/main/java/org/openhab/binding/modbus/discovery/internal/ModbusEndpointDiscoveryService.java
  addons/binding/org.openhab.binding.modbus/src/main/java/org/openhab/binding/modbus/discovery/internal/ModbusThingHandlerDiscoveryService.java
  addons/binding/org.openhab.binding.modbus/src/main/java/org/openhab/binding/modbus/handler/ModbusEndpointThingHandler.java
  addons/binding/org.openhab.binding.modbus/src/main/java/org/openhab/binding/modbus/internal/ModbusHandlerFactory.java
  addons/binding/org.openhab.binding.modbus/src/main/java/org/openhab/binding/modbus/internal/config/ModbusSerialConfiguration.java
  addons/binding/org.openhab.binding.modbus/src/main/java/org/openhab/binding/modbus/internal/config/ModbusTcpConfiguration.java
  addons/binding/org.openhab.binding.modbus/src/main/java/org/openhab/binding/modbus/internal/handler/ModbusSerialThingHandler.java
  addons/binding/org.openhab.binding.modbus/src/main/java/org/openhab/binding/modbus/internal/handler/ModbusTcpThingHandler.java
Labels: enhancement

#5382 [jinja] Migrate to bnd
  CODEOWNERS
  addons/pom.xml
  addons/transform/org.openhab.transform.jinja.test/.classpath
  addons/transform/org.openhab.transform.jinja.test/.project
  addons/transform/org.openhab.transform.jinja.test/META-INF/MANIFEST.MF
  addons/transform/org.openhab.transform.jinja.test/NOTICE
  addons/transform/org.openhab.transform.jinja.test/build.properties
  addons/transform/org.openhab.transform.jinja.test/org.openhab.transform.jinja.test.launch
  addons/transform/org.openhab.transform.jinja.test/pom.xml
  addons/transform/org.openhab.transform.jinja/.classpath
  addons/transform/org.openhab.transform.jinja/META-INF/MANIFEST.MF
  addons/transform/org.openhab.transform.jinja/OSGI-INF/.gitignore
  addons/transform/org.openhab.transform.jinja/build.properties
  addons/transform/org.openhab.transform.jinja/lib/commons-lang3-3.8.1.jar
  addons/transform/org.openhab.transform.jinja/lib/jackson-annotations-2.9.8.jar
  addons/transform/org.openhab.transform.jinja/lib/jackson-core-2.9.8.jar
  addons/transform/org.openhab.transform.jinja/lib/jackson-databind-2.9.8.jar
  addons/transform/org.openhab.transform.jinja/lib/jinjava-2.4.12.jar
  addons/transform/org.openhab.transform.jinja/lib/jsoup-1.11.3.jar
  addons/transform/org.openhab.transform.jinja/lib/re2j-1.2.jar
  addons/transform/org.openhab.transform.jinja/pom.xml
  addons/transform/pom.xml
  bom/openhab-addons/pom.xml
  bundles/org.openhab.transform.jinja/.classpath
  bundles/org.openhab.transform.jinja/.project
  bundles/org.openhab.transform.jinja/NOTICE
  bundles/org.openhab.transform.jinja/README.md
  bundles/org.openhab.transform.jinja/pom.xml
  bundles/org.openhab.transform.jinja/src/main/java/org/openhab/transform/jinja/internal/JinjaTransformationService.java
  bundles/org.openhab.transform.jinja/src/main/java/org/openhab/transform/jinja/internal/profiles/JinjaTransformationProfile.java
  bundles/org.openhab.transform.jinja/src/main/java/org/openhab/transform/jinja/internal/profiles/JinjaTransformationProfileFactory.java
  bundles/org.openhab.transform.jinja/src/main/resources/ESH-INF/config/jinjaProfile.xml
  bundles/org.openhab.transform.jinja/src/test/java/org/openhab/transform/jinja/internal/JinjaTransformationServiceTest.java
  bundles/pom.xml
  features/karaf/openhab-addons/src/main/feature/feature.xml
Labels: infrastructure

#5400 [zway] Removed dependency on google guava library.
  addons/binding/org.openhab.binding.zway/META-INF/MANIFEST.MF
  addons/binding/org.openhab.binding.zway/src/main/java/org/openhab/binding/zway/internal/ZWayBindingConstants.java
  addons/binding/org.openhab.binding.zway/src/main/java/org/openhab/binding/zway/internal/ZWayHandlerFactory.java
Labels: infrastructure

#5405 [lifx] Improved error message
  bundles/org.openhab.binding.lifx/src/main/java/org/openhab/binding/lifx/internal/LifxLightStateChanger.java
Labels: enhancement

#5412 Add required bundles to itests for successful Java 11 build
  itests/itest-common.bndrun
  itests/org.openhab.binding.astro.tests/itest.bndrun
  itests/org.openhab.binding.avmfritz.tests/itest.bndrun
  itests/org.openhab.binding.hue.tests/itest.bndrun
  itests/org.openhab.binding.max.tests/itest.bndrun
  itests/org.openhab.binding.tradfri.tests/itest.bndrun
  itests/org.openhab.binding.wemo.tests/itest.bndrun
  itests/org.openhab.persistence.mapdb.tests/itest.bndrun
Labels: bug

#5398 [ihc] Introduced onLevel channel parameter to dimmer channel
  addons/binding/org.openhab.binding.ihc.test/src/test/java/org/openhab/binding/ihc/internal/converters/DecimalTypeWSBooleanValueConverterTest.java
  addons/binding/org.openhab.binding.ihc.test/src/test/java/org/openhab/binding/ihc/internal/converters/DecimalTypeWSEnumValueConverterTest.java
  addons/binding/org.openhab.binding.ihc.test/src/test/java/org/openhab/binding/ihc/internal/converters/DecimalTypeWSFloatingPointValueConverterTest.java
  addons/binding/org.openhab.binding.ihc.test/src/test/java/org/openhab/binding/ihc/internal/converters/DecimalTypeWSIntegerValueConverterTest.java
  addons/binding/org.openhab.binding.ihc.test/src/test/java/org/openhab/binding/ihc/internal/converters/DecimalTypeWSTimerValueConverterTest.java
  addons/binding/org.openhab.binding.ihc.test/src/test/java/org/openhab/binding/ihc/internal/converters/DecimalTypeWSWeekdayValueConverterTest.java
  addons/binding/org.openhab.binding.ihc.test/src/test/java/org/openhab/binding/ihc/internal/converters/OnOffTypeWSBooleanValueConverterTest.java
  addons/binding/org.openhab.binding.ihc.test/src/test/java/org/openhab/binding/ihc/internal/converters/OnOffTypeWSIntegerValueConverterTest.java
  addons/binding/org.openhab.binding.ihc.test/src/test/java/org/openhab/binding/ihc/internal/converters/OpenClosedTypeWSBooleanValueConverterTest.java
  addons/binding/org.openhab.binding.ihc.test/src/test/java/org/openhab/binding/ihc/internal/converters/OpenClosedTypeWSIntegerValueConverterTest.java
  addons/binding/org.openhab.binding.ihc.test/src/test/java/org/openhab/binding/ihc/internal/converters/PercentTypeWSIntegerValueConverterTest.java
  addons/binding/org.openhab.binding.ihc.test/src/test/java/org/openhab/binding/ihc/internal/converters/StringTypeWSEnumValueConverterTest.java
  addons/binding/org.openhab.binding.ihc.test/src/test/java/org/openhab/binding/ihc/internal/converters/UpDownTypeWSBooleanValueConverterTest.java
  addons/binding/org.openhab.binding.ihc.test/src/test/java/org/openhab/binding/ihc/internal/converters/UpDownTypeWSIntegerValueConverterTest.java
  addons/binding/org.openhab.binding.ihc/ESH-INF/thing/channels.xml
  addons/binding/org.openhab.binding.ihc/src/main/java/org/openhab/binding/ihc/internal/IhcBindingConstants.java
  addons/binding/org.openhab.binding.ihc/src/main/java/org/openhab/binding/ihc/internal/config/ChannelParams.java
  addons/binding/org.openhab.binding.ihc/src/main/java/org/openhab/binding/ihc/internal/converters/ConverterAdditionalInfo.java
  addons/binding/org.openhab.binding.ihc/src/main/java/org/openhab/binding/ihc/internal/converters/OnOffTypeWSIntegerValueConverter.java
  addons/binding/org.openhab.binding.ihc/src/main/java/org/openhab/binding/ihc/internal/handler/IhcHandler.java
  addons/binding/org.openhab.binding.ihc/src/main/java/org/openhab/binding/ihc/internal/ws/IhcClient.java
Labels: enhancement

#5403 downgrade jaxb/jaxws to 2.2
  bundles/org.openhab.binding.denonmarantz/pom.xml
  bundles/org.openhab.binding.dlinksmarthome/pom.xml
  bundles/org.openhab.binding.tellstick/pom.xml
  features/karaf/openhab-addons/src/main/feature/feature.xml
Labels: bug

#5427 Fixed .classpath files.
  bundles/org.openhab.binding.darksky/.classpath
  bundles/org.openhab.binding.fsinternetradio/.classpath
  bundles/org.openhab.binding.logreader/.classpath
  bundles/org.openhab.binding.robonect/.classpath
  bundles/org.openhab.binding.tado/.classpath
  bundles/org.openhab.transform.bin2json/.classpath
  bundles/org.openhab.voice.marytts/.classpath
Labels: infrastructure

#5429 Removed obsolete files
  bundles/org.openhab.binding.max/MAINTAINERS
  bundles/org.openhab.binding.valloxmv/build.properties
Labels: infrastructure

#5399 [orvibo] Migrate to bnd build
  CODEOWNERS
  addons/binding/org.openhab.binding.orvibo/.classpath
  addons/binding/org.openhab.binding.orvibo/META-INF/MANIFEST.MF
  addons/binding/org.openhab.binding.orvibo/OSGI-INF/.gitignore
  addons/binding/org.openhab.binding.orvibo/build.properties
  addons/binding/org.openhab.binding.orvibo/pom.xml
  addons/binding/pom.xml
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.orvibo/.classpath
  bundles/org.openhab.binding.orvibo/.project
  bundles/org.openhab.binding.orvibo/NOTICE
  bundles/org.openhab.binding.orvibo/README.md
  bundles/org.openhab.binding.orvibo/lib/s20-sdk-0.0.6-SNAPSHOT.jar
  bundles/org.openhab.binding.orvibo/pom.xml
  bundles/org.openhab.binding.orvibo/src/main/java/org/openhab/binding/orvibo/internal/OrviboActivator.java
  bundles/org.openhab.binding.orvibo/src/main/java/org/openhab/binding/orvibo/internal/OrviboBindingConstants.java
  bundles/org.openhab.binding.orvibo/src/main/java/org/openhab/binding/orvibo/internal/OrviboHandlerFactory.java
  bundles/org.openhab.binding.orvibo/src/main/java/org/openhab/binding/orvibo/internal/discovery/SocketDiscoveryService.java
  bundles/org.openhab.binding.orvibo/src/main/java/org/openhab/binding/orvibo/internal/handler/S20Handler.java
  bundles/org.openhab.binding.orvibo/src/main/resources/ESH-INF/binding/binding.xml
  bundles/org.openhab.binding.orvibo/src/main/resources/ESH-INF/thing/thing-types.xml
  bundles/pom.xml
  features/karaf/openhab-addons/src/main/feature/feature.xml
Labels: infrastructure

#5393 [keba] Ignore values if the curr hw commands sends 0
  bundles/org.openhab.binding.keba/src/main/java/org/openhab/binding/keba/internal/handler/KeContactHandler.java
Labels: bug

#4917 [onewire] Add support for BAE091x
  CODEOWNERS
  bundles/org.openhab.binding.onewire/README.md
  bundles/org.openhab.binding.onewire/src/main/java/org/openhab/binding/onewire/internal/OwBindingConstants.java
  bundles/org.openhab.binding.onewire/src/main/java/org/openhab/binding/onewire/internal/OwHandlerFactory.java
  bundles/org.openhab.binding.onewire/src/main/java/org/openhab/binding/onewire/internal/config/BAE091xAnalogConfiguration.java
  bundles/org.openhab.binding.onewire/src/main/java/org/openhab/binding/onewire/internal/config/BAE091xHandlerConfiguration.java
  bundles/org.openhab.binding.onewire/src/main/java/org/openhab/binding/onewire/internal/config/BAE091xPIOConfiguration.java
  bundles/org.openhab.binding.onewire/src/main/java/org/openhab/binding/onewire/internal/config/BAE091xPWMConfiguration.java
  bundles/org.openhab.binding.onewire/src/main/java/org/openhab/binding/onewire/internal/config/BaseHandlerConfiguration.java
  bundles/org.openhab.binding.onewire/src/main/java/org/openhab/binding/onewire/internal/device/BAE0910.java
  bundles/org.openhab.binding.onewire/src/main/java/org/openhab/binding/onewire/internal/device/OwSensorType.java
  bundles/org.openhab.binding.onewire/src/main/java/org/openhab/binding/onewire/internal/handler/BAE091xSensorThingHandler.java
  bundles/org.openhab.binding.onewire/src/main/java/org/openhab/binding/onewire/internal/owserver/OwserverDeviceParameter.java
  bundles/org.openhab.binding.onewire/src/main/resources/ESH-INF/thing/bae09x.xml
  bundles/org.openhab.binding.onewire/src/main/resources/accepted_itemtypes.properties
  bundles/org.openhab.binding.onewire/src/main/resources/sensor.properties
  bundles/org.openhab.binding.onewire/src/test/java/org/openhab/binding/onewire/CompletenessTest.java
  bundles/org.openhab.binding.onewire/src/test/java/org/openhab/binding/onewire/device/BAE0910Test.java
  bundles/org.openhab.binding.onewire/src/test/java/org/openhab/binding/onewire/device/DeviceTestParent.java
Labels: enhancement

#5451 [lgwebos] migrate binding to bnd
  CODEOWNERS
  addons/binding/org.openhab.binding.lgwebos/.classpath
  addons/binding/org.openhab.binding.lgwebos/META-INF/MANIFEST.MF
  addons/binding/org.openhab.binding.lgwebos/OSGI-INF/.gitignore
  addons/binding/org.openhab.binding.lgwebos/build.properties
  addons/binding/org.openhab.binding.lgwebos/lib/java-websocket-1.3.2.jar
  addons/binding/org.openhab.binding.lgwebos/lib/json-20140107.jar
  addons/binding/org.openhab.binding.lgwebos/lib/xpp3-1.1.4c.jar
  addons/binding/org.openhab.binding.lgwebos/pom.xml
  addons/binding/pom.xml
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.lgwebos/.classpath
  bundles/org.openhab.binding.lgwebos/.project
  bundles/org.openhab.binding.lgwebos/NOTICE
  bundles/org.openhab.binding.lgwebos/README.md
  bundles/org.openhab.binding.lgwebos/lib/Connect-SDK-Java-Core-1.0.jar
  bundles/org.openhab.binding.lgwebos/pom.xml
  bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/action/Application.java
  bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/action/LGWebOSActions.java
  bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/BaseChannelHandler.java
  bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/ChannelHandler.java
  bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/LGWebOSBindingConstants.java
  bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/LGWebOSHandlerFactory.java
  bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/LauncherApplication.java
  bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/MediaControlPlayer.java
  bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/MediaControlStop.java
  bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/PowerControlPower.java
  bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/TVControlChannel.java
  bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/TVControlChannelName.java
  bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/ToastControlToast.java
  bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/VolumeControlMute.java
  bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/VolumeControlVolume.java
  bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/discovery/LGWebOSDiscovery.java
  bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/handler/LGWebOSHandler.java
  bundles/org.openhab.binding.lgwebos/src/main/resources/ESH-INF/binding/binding.xml
  bundles/org.openhab.binding.lgwebos/src/main/resources/ESH-INF/config/config.xml
  bundles/org.openhab.binding.lgwebos/src/main/resources/ESH-INF/i18n/lgwebos.properties
  bundles/org.openhab.binding.lgwebos/src/main/resources/ESH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.lgwebos/src/main/resources/openhab-logo-square.png
  bundles/pom.xml
  features/karaf/openhab-addons/src/main/feature/feature.xml
Labels: infrastructure

#5449 [openhabcloud] Updated readme clarifying keys gen
  addons/io/org.openhab.io.openhabcloud/README.md
Labels: documentation

#5452 [onewiregpio] Migrate to bnd build
  CODEOWNERS
  addons/binding/org.openhab.binding.onewiregpio/.classpath
  addons/binding/org.openhab.binding.onewiregpio/META-INF/MANIFEST.MF
  addons/binding/org.openhab.binding.onewiregpio/OSGI-INF/.gitignore
  addons/binding/org.openhab.binding.onewiregpio/build.properties
  addons/binding/pom.xml
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.onewiregpio/.classpath
  bundles/org.openhab.binding.onewiregpio/.project
  bundles/org.openhab.binding.onewiregpio/NOTICE
  bundles/org.openhab.binding.onewiregpio/README.md
  bundles/org.openhab.binding.onewiregpio/pom.xml
  bundles/org.openhab.binding.onewiregpio/src/main/java/org/openhab/binding/onewiregpio/internal/OneWireGPIOBindingConstants.java
  bundles/org.openhab.binding.onewiregpio/src/main/java/org/openhab/binding/onewiregpio/internal/OneWireGPIOHandlerFactory.java
  bundles/org.openhab.binding.onewiregpio/src/main/java/org/openhab/binding/onewiregpio/internal/handler/OneWireGPIOHandler.java
  bundles/org.openhab.binding.onewiregpio/src/main/resources/ESH-INF/binding/binding.xml
  bundles/org.openhab.binding.onewiregpio/src/main/resources/ESH-INF/thing/thing-types.xml
  bundles/pom.xml
  features/karaf/openhab-addons/src/main/feature/feature.xml
Labels: infrastructure

#3688 [xmltv] XmlTV Binding initial contribution
  CODEOWNERS
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.xmltv/.classpath
  bundles/org.openhab.binding.xmltv/.project
  bundles/org.openhab.binding.xmltv/NOTICE
  bundles/org.openhab.binding.xmltv/README.md
  bundles/org.openhab.binding.xmltv/pom.xml
  bundles/org.openhab.binding.xmltv/src/main/java/org/openhab/binding/xmltv/internal/XmlTVBindingConstants.java
  bundles/org.openhab.binding.xmltv/src/main/java/org/openhab/binding/xmltv/internal/XmlTVHandlerFactory.java
  bundles/org.openhab.binding.xmltv/src/main/java/org/openhab/binding/xmltv/internal/configuration/XmlChannelConfiguration.java
  bundles/org.openhab.binding.xmltv/src/main/java/org/openhab/binding/xmltv/internal/configuration/XmlTVConfiguration.java
  bundles/org.openhab.binding.xmltv/src/main/java/org/openhab/binding/xmltv/internal/discovery/XmlTVDiscoveryService.java
  bundles/org.openhab.binding.xmltv/src/main/java/org/openhab/binding/xmltv/internal/handler/ChannelHandler.java
  bundles/org.openhab.binding.xmltv/src/main/java/org/openhab/binding/xmltv/internal/handler/XmlTVHandler.java
  bundles/org.openhab.binding.xmltv/src/main/java/org/openhab/binding/xmltv/internal/jaxb/Icon.java
  bundles/org.openhab.binding.xmltv/src/main/java/org/openhab/binding/xmltv/internal/jaxb/MediaChannel.java
  bundles/org.openhab.binding.xmltv/src/main/java/org/openhab/binding/xmltv/internal/jaxb/ObjectFactory.java
  bundles/org.openhab.binding.xmltv/src/main/java/org/openhab/binding/xmltv/internal/jaxb/Programme.java
  bundles/org.openhab.binding.xmltv/src/main/java/org/openhab/binding/xmltv/internal/jaxb/Tv.java
  bundles/org.openhab.binding.xmltv/src/main/java/org/openhab/binding/xmltv/internal/jaxb/WithLangType.java
  bundles/org.openhab.binding.xmltv/src/main/java/org/openhab/binding/xmltv/internal/jaxb/package-info.java
  bundles/org.openhab.binding.xmltv/src/main/resources/ESH-INF/binding/binding.xml
  bundles/org.openhab.binding.xmltv/src/main/resources/ESH-INF/thing/thing-types.xml
  bundles/pom.xml
  features/karaf/openhab-addons/src/main/feature/feature.xml
Labels: cre, new binding

#5458 Some small clean up changes
  bundles/org.openhab.binding.digiplex/src/main/resources/ESH-INF/binding/binding.xml
  bundles/org.openhab.binding.digiplex/src/main/resources/ESH-INF/thing/area.xml
  bundles/org.openhab.binding.digiplex/src/main/resources/ESH-INF/thing/bridge.xml
  bundles/org.openhab.binding.digiplex/src/main/resources/ESH-INF/thing/zone.xml
  bundles/org.openhab.binding.onewire/src/main/resources/ESH-INF/thing/bae09x.xml
  bundles/org.openhab.binding.synopanalyzer/src/main/resources/ESH-INF/binding/binding.xml
  bundles/org.openhab.binding.synopanalyzer/src/main/resources/ESH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.xmppclient/src/main/resources/ESH-INF/binding/binding.xml
  bundles/org.openhab.binding.xmppclient/src/main/resources/ESH-INF/thing/thing-types.xml
  bundles/pom.xml
  features/karaf/openhab-addons/src/main/feature/feature.xml
Labels: infrastructure

#5453 [boschindego] migrate binding to bnd
  CODEOWNERS
  addons/binding/org.openhab.binding.boschindego/.classpath
  addons/binding/org.openhab.binding.boschindego/.gitignore
  addons/binding/org.openhab.binding.boschindego/META-INF/MANIFEST.MF
  addons/binding/org.openhab.binding.boschindego/OSGI-INF/.gitignore
  addons/binding/org.openhab.binding.boschindego/build.properties
  addons/binding/org.openhab.binding.boschindego/lib/bosch-indego-controller-lib-0.8.jar
  addons/binding/org.openhab.binding.boschindego/lib/httpclient-4.5.2.jar
  addons/binding/org.openhab.binding.boschindego/lib/httpcore-4.4.4.jar
  addons/binding/org.openhab.binding.boschindego/lib/jackson-annotations-2.8.6.jar
  addons/binding/org.openhab.binding.boschindego/lib/jackson-core-2.8.6.jar
  addons/binding/org.openhab.binding.boschindego/lib/jackson-databind-2.8.6.jar
  addons/binding/org.openhab.binding.boschindego/pom.xml
  addons/binding/pom.xml
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.boschindego/.classpath
  bundles/org.openhab.binding.boschindego/.project
  bundles/org.openhab.binding.boschindego/NOTICE
  bundles/org.openhab.binding.boschindego/README.md
  bundles/org.openhab.binding.boschindego/pom.xml
  bundles/org.openhab.binding.boschindego/src/main/java/org/openhab/binding/boschindego/internal/BoschIndegoBindingConstants.java
  bundles/org.openhab.binding.boschindego/src/main/java/org/openhab/binding/boschindego/internal/BoschIndegoHandlerFactory.java
  bundles/org.openhab.binding.boschindego/src/main/java/org/openhab/binding/boschindego/internal/IndegoStateConstants.java
  bundles/org.openhab.binding.boschindego/src/main/java/org/openhab/binding/boschindego/internal/handler/BoschIndegoHandler.java
  bundles/org.openhab.binding.boschindego/src/main/resources/ESH-INF/binding/binding.xml
  bundles/org.openhab.binding.boschindego/src/main/resources/ESH-INF/thing/thing-types.xml
  bundles/pom.xml
  features/karaf/openhab-addons/src/main/feature/feature.xml
Labels: infrastructure

#5434 [spotify] Changed deviceName and playlists channels
  bundles/org.openhab.binding.spotify/README.md
  bundles/org.openhab.binding.spotify/src/main/java/org/openhab/binding/spotify/internal/SpotifyBindingConstants.java
  bundles/org.openhab.binding.spotify/src/main/java/org/openhab/binding/spotify/internal/api/SpotifyConnector.java
  bundles/org.openhab.binding.spotify/src/main/java/org/openhab/binding/spotify/internal/discovery/SpotifyDeviceDiscoveryService.java
  bundles/org.openhab.binding.spotify/src/main/java/org/openhab/binding/spotify/internal/handler/SpotifyBridgeHandler.java
  bundles/org.openhab.binding.spotify/src/main/java/org/openhab/binding/spotify/internal/handler/SpotifyDeviceHandler.java
  bundles/org.openhab.binding.spotify/src/main/java/org/openhab/binding/spotify/internal/handler/SpotifyDynamicStateDescriptionProvider.java
  bundles/org.openhab.binding.spotify/src/main/java/org/openhab/binding/spotify/internal/handler/SpotifyHandleCommands.java
  bundles/org.openhab.binding.spotify/src/main/resources/ESH-INF/thing/thing-types.xml
Labels: enhancement

#5459 Upgrade to Karaf 4.2.4
  features/karaf/openhab-addons/src/main/feature/feature.xml
  poms/bnd/pom.xml
Labels: infrastructure

#5454 [ftpupload] Migrate to bnd build
  CODEOWNERS
  addons/binding/org.openhab.binding.ftpupload/.classpath
  addons/binding/org.openhab.binding.ftpupload/META-INF/MANIFEST.MF
  addons/binding/org.openhab.binding.ftpupload/OSGI-INF/.gitignore
  addons/binding/org.openhab.binding.ftpupload/build.properties
  addons/binding/org.openhab.binding.ftpupload/lib/ftplet-api-1.1.0.jar
  addons/binding/org.openhab.binding.ftpupload/lib/ftpserver-core-1.1.0.jar
  addons/binding/org.openhab.binding.ftpupload/lib/mina-core-2.0.16.jar
  addons/binding/org.openhab.binding.ftpupload/pom.xml
  addons/binding/pom.xml
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.ftpupload/.classpath
  bundles/org.openhab.binding.ftpupload/.project
  bundles/org.openhab.binding.ftpupload/NOTICE
  bundles/org.openhab.binding.ftpupload/README.md
  bundles/org.openhab.binding.ftpupload/pom.xml
  bundles/org.openhab.binding.ftpupload/src/main/java/org/openhab/binding/ftpupload/internal/FtpUploadBindingConstants.java
  bundles/org.openhab.binding.ftpupload/src/main/java/org/openhab/binding/ftpupload/internal/FtpUploadHandlerFactory.java
  bundles/org.openhab.binding.ftpupload/src/main/java/org/openhab/binding/ftpupload/internal/config/FtpUploadConfig.java
  bundles/org.openhab.binding.ftpupload/src/main/java/org/openhab/binding/ftpupload/internal/ftp/FTPUser.java
  bundles/org.openhab.binding.ftpupload/src/main/java/org/openhab/binding/ftpupload/internal/ftp/FTPUserManager.java
  bundles/org.openhab.binding.ftpupload/src/main/java/org/openhab/binding/ftpupload/internal/ftp/FtpServer.java
  bundles/org.openhab.binding.ftpupload/src/main/java/org/openhab/binding/ftpupload/internal/ftp/FtpServerEventListener.java
  bundles/org.openhab.binding.ftpupload/src/main/java/org/openhab/binding/ftpupload/internal/ftp/SimpleFileSystemView.java
  bundles/org.openhab.binding.ftpupload/src/main/java/org/openhab/binding/ftpupload/internal/ftp/SimpleFtpFile.java
  bundles/org.openhab.binding.ftpupload/src/main/java/org/openhab/binding/ftpupload/internal/ftp/UsernamePassword.java
  bundles/org.openhab.binding.ftpupload/src/main/java/org/openhab/binding/ftpupload/internal/handler/FtpUploadHandler.java
  bundles/org.openhab.binding.ftpupload/src/main/resources/ESH-INF/binding/binding.xml
  bundles/org.openhab.binding.ftpupload/src/main/resources/ESH-INF/thing/thing-types.xml
  bundles/pom.xml
  features/karaf/openhab-addons/src/main/feature/feature.xml
Labels: infrastructure

#5470 [lgwebos] Binding fails to install due to invalid bundle version
  features/karaf/openhab-addons/src/main/feature/feature.xml
Labels: critical, infrastructure

#5471 [homekit] Fix NoClassDefFoundError by adding missing javax.jmdns package import
  addons/io/org.openhab.io.homekit/META-INF/MANIFEST.MF
Labels: bug, io: homekit

#5463 [tankerkoenig] Fixed link to 'Tankstellen Finder'
  bundles/org.openhab.binding.tankerkoenig/README.md
  bundles/org.openhab.binding.tankerkoenig/src/main/resources/ESH-INF/i18n/tankerkoenig_de.properties
  bundles/org.openhab.binding.tankerkoenig/src/main/resources/ESH-INF/thing/station.xml
  bundles/org.openhab.binding.tankerkoenig/src/main/resources/ESH-INF/thing/webservice.xml
Labels: documentation

#5455 [systeminfo] Migrate to BND
  CODEOWNERS
  addons/binding/org.openhab.binding.systeminfo.test/.classpath
  addons/binding/org.openhab.binding.systeminfo.test/META-INF/MANIFEST.MF
  addons/binding/org.openhab.binding.systeminfo.test/build.properties
  addons/binding/org.openhab.binding.systeminfo.test/org.openhab.binding.systeminfo.test.launch
  addons/binding/org.openhab.binding.systeminfo.test/pom.xml
  addons/binding/org.openhab.binding.systeminfo/.classpath
  addons/binding/org.openhab.binding.systeminfo/ESH-INF/binding/binding.xml
  addons/binding/org.openhab.binding.systeminfo/META-INF/MANIFEST.MF
  addons/binding/org.openhab.binding.systeminfo/OSGI-INF/.gitignore
  addons/binding/org.openhab.binding.systeminfo/build.properties
  addons/binding/org.openhab.binding.systeminfo/lib/jna-5.2.0.jar
  addons/binding/org.openhab.binding.systeminfo/lib/jna-platform-5.2.0.jar
  addons/binding/org.openhab.binding.systeminfo/lib/oshi-core-3.13.0.jar
  addons/binding/org.openhab.binding.systeminfo/pom.xml
  addons/binding/pom.xml
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.systeminfo/.classpath
  bundles/org.openhab.binding.systeminfo/.project
  bundles/org.openhab.binding.systeminfo/NOTICE
  bundles/org.openhab.binding.systeminfo/README.md
  bundles/org.openhab.binding.systeminfo/pom.xml
  bundles/org.openhab.binding.systeminfo/src/main/java/org/openhab/binding/systeminfo/internal/SysteminfoBindingConstants.java
  bundles/org.openhab.binding.systeminfo/src/main/java/org/openhab/binding/systeminfo/internal/SysteminfoHandlerFactory.java
  bundles/org.openhab.binding.systeminfo/src/main/java/org/openhab/binding/systeminfo/internal/discovery/SysteminfoDiscoveryService.java
  bundles/org.openhab.binding.systeminfo/src/main/java/org/openhab/binding/systeminfo/internal/handler/SysteminfoHandler.java
  bundles/org.openhab.binding.systeminfo/src/main/java/org/openhab/binding/systeminfo/internal/model/DeviceNotFoundException.java
  bundles/org.openhab.binding.systeminfo/src/main/java/org/openhab/binding/systeminfo/internal/model/OSHISysteminfo.java
  bundles/org.openhab.binding.systeminfo/src/main/java/org/openhab/binding/systeminfo/internal/model/SysteminfoInterface.java
  bundles/org.openhab.binding.systeminfo/src/main/resources/ESH-INF/binding/binding.xml
  bundles/org.openhab.binding.systeminfo/src/main/resources/ESH-INF/config/channelConfig.xml
  bundles/org.openhab.binding.systeminfo/src/main/resources/ESH-INF/config/computerConfig.xml
  bundles/org.openhab.binding.systeminfo/src/main/resources/ESH-INF/thing/channels.xml
  bundles/org.openhab.binding.systeminfo/src/main/resources/ESH-INF/thing/computer.xml
  bundles/pom.xml
  features/karaf/openhab-addons/src/main/feature/feature.xml
  itests/org.openhab.binding.systeminfo.tests/.classpath
  itests/org.openhab.binding.systeminfo.tests/.project
  itests/org.openhab.binding.systeminfo.tests/NOTICE
  itests/org.openhab.binding.systeminfo.tests/itest.bndrun
  itests/org.openhab.binding.systeminfo.tests/pom.xml
  itests/org.openhab.binding.systeminfo.tests/src/main/java/org/openhab/binding/systeminfo/test/SysteminfoOSGiTest.java
  itests/pom.xml
Labels: infrastructure

#4226 [nikohomecontrol] Implement Niko Home Control II
  addons/binding/org.openhab.binding.nikohomecontrol/ESH-INF/binding/binding.xml
  addons/binding/org.openhab.binding.nikohomecontrol/ESH-INF/thing/thing-types.xml
  addons/binding/org.openhab.binding.nikohomecontrol/META-INF/MANIFEST.MF
  addons/binding/org.openhab.binding.nikohomecontrol/README.md
  addons/binding/org.openhab.binding.nikohomecontrol/pom.xml
  addons/binding/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/NikoHomeControlBindingConstants.java
  addons/binding/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/NikoHomeControlHandlerFactory.java
  addons/binding/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/discovery/NikoHomeControlBridgeDiscoveryService.java
  addons/binding/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/discovery/NikoHomeControlDiscoveryService.java
  addons/binding/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/handler/NikoHomeControlActionConfig.java
  addons/binding/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/handler/NikoHomeControlActionDimmerConfig.java
  addons/binding/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/handler/NikoHomeControlActionHandler.java
  addons/binding/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/handler/NikoHomeControlBridgeConfig.java
  addons/binding/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/handler/NikoHomeControlBridgeConfig2.java
  addons/binding/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/handler/NikoHomeControlBridgeHandler.java
  addons/binding/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/handler/NikoHomeControlBridgeHandler1.java
  addons/binding/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/handler/NikoHomeControlBridgeHandler2.java
  addons/binding/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/handler/NikoHomeControlThermostatConfig.java
  addons/binding/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/handler/NikoHomeControlThermostatHandler.java
  addons/binding/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/protocol/NhcAction.java
  addons/binding/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/protocol/NhcActionEvent.java
  addons/binding/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/protocol/NhcControllerEvent.java
  addons/binding/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/protocol/NhcThermostat.java
  addons/binding/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/protocol/NhcThermostatEvent.java
  addons/binding/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/protocol/NikoHomeControlCommunication.java
  addons/binding/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/protocol/NikoHomeControlConstants.java
  addons/binding/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/protocol/NikoHomeControlDiscover.java
  addons/binding/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/protocol/nhc1/NhcAction1.java
  addons/binding/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/protocol/nhc1/NhcLocation1.java
  addons/binding/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/protocol/nhc1/NhcMessageBase1.java
  addons/binding/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/protocol/nhc1/NhcMessageCmd1.java
  addons/binding/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/protocol/nhc1/NhcMessageListMap1.java
  addons/binding/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/protocol/nhc1/NhcMessageMap1.java
  addons/binding/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/protocol/nhc1/NhcSystemInfo1.java
  addons/binding/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/protocol/nhc1/NhcThermostat1.java
  addons/binding/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/protocol/nhc1/NikoHomeControlCommunication1.java
  addons/binding/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/protocol/nhc1/NikoHomeControlMessageDeserializer1.java
  addons/binding/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/protocol/nhc2/NhcAction2.java
  addons/binding/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/protocol/nhc2/NhcDevice2.java
  addons/binding/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/protocol/nhc2/NhcLocation2.java
  addons/binding/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/protocol/nhc2/NhcMessage2.java
  addons/binding/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/protocol/nhc2/NhcMqttConnection2.java
  addons/binding/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/protocol/nhc2/NhcNotification2.java
  addons/binding/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/protocol/nhc2/NhcProfile2.java
  addons/binding/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/protocol/nhc2/NhcSSLContextProvider2.java
  addons/binding/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/protocol/nhc2/NhcService2.java
  addons/binding/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/protocol/nhc2/NhcSystemInfo2.java
  addons/binding/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/protocol/nhc2/NhcThermostat2.java
  addons/binding/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/protocol/nhc2/NhcTimeInfo2.java
  addons/binding/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/protocol/nhc2/NikoHomeControlCommunication2.java
  addons/binding/org.openhab.binding.nikohomecontrol/src/main/resources/nikohomecontrol/certificates.properties
  features/karaf/openhab-addons/src/main/feature/feature.xml
Labels: enhancement

#5478 [exec] Migrate to bnd build
  CODEOWNERS
  addons/binding/org.openhab.binding.exec/.classpath
  addons/binding/org.openhab.binding.exec/META-INF/MANIFEST.MF
  addons/binding/org.openhab.binding.exec/OSGI-INF/.gitignore
  addons/binding/org.openhab.binding.exec/build.properties
  addons/binding/pom.xml
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.exec/.classpath
  bundles/org.openhab.binding.exec/.project
  bundles/org.openhab.binding.exec/NOTICE
  bundles/org.openhab.binding.exec/README.md
  bundles/org.openhab.binding.exec/pom.xml
  bundles/org.openhab.binding.exec/src/main/java/org/openhab/binding/exec/internal/ExecBindingConstants.java
  bundles/org.openhab.binding.exec/src/main/java/org/openhab/binding/exec/internal/ExecHandlerFactory.java
  bundles/org.openhab.binding.exec/src/main/java/org/openhab/binding/exec/internal/handler/ExecHandler.java
  bundles/org.openhab.binding.exec/src/main/resources/ESH-INF/binding/binding.xml
  bundles/org.openhab.binding.exec/src/main/resources/ESH-INF/i18n/exec_de.properties
  bundles/org.openhab.binding.exec/src/main/resources/ESH-INF/thing/thing-types.xml
  bundles/pom.xml
  features/karaf/openhab-addons/src/main/feature/feature.xml
Labels: awaiting other PR, infrastructure

#4989 [mail] Email Binding initial contribution
  CODEOWNERS
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.mail/.classpath
  bundles/org.openhab.binding.mail/.project
  bundles/org.openhab.binding.mail/NOTICE
  bundles/org.openhab.binding.mail/README.md
  bundles/org.openhab.binding.mail/pom.xml
  bundles/org.openhab.binding.mail/src/main/java/org/openhab/binding/mail/action/SendMailActions.java
  bundles/org.openhab.binding.mail/src/main/java/org/openhab/binding/mail/internal/MailBindingConstants.java
  bundles/org.openhab.binding.mail/src/main/java/org/openhab/binding/mail/internal/MailBuilder.java
  bundles/org.openhab.binding.mail/src/main/java/org/openhab/binding/mail/internal/MailCountChannelType.java
  bundles/org.openhab.binding.mail/src/main/java/org/openhab/binding/mail/internal/MailHandlerFactory.java
  bundles/org.openhab.binding.mail/src/main/java/org/openhab/binding/mail/internal/POP3IMAPHandler.java
  bundles/org.openhab.binding.mail/src/main/java/org/openhab/binding/mail/internal/SMTPHandler.java
  bundles/org.openhab.binding.mail/src/main/java/org/openhab/binding/mail/internal/ServerSecurity.java
  bundles/org.openhab.binding.mail/src/main/java/org/openhab/binding/mail/internal/config/BaseConfig.java
  bundles/org.openhab.binding.mail/src/main/java/org/openhab/binding/mail/internal/config/POP3IMAPChannelConfig.java
  bundles/org.openhab.binding.mail/src/main/java/org/openhab/binding/mail/internal/config/POP3IMAPConfig.java
  bundles/org.openhab.binding.mail/src/main/java/org/openhab/binding/mail/internal/config/SMTPConfig.java
  bundles/org.openhab.binding.mail/src/main/resources/ESH-INF/binding/binding.xml
  bundles/org.openhab.binding.mail/src/main/resources/ESH-INF/i18n/mail_de_DE.properties
  bundles/org.openhab.binding.mail/src/main/resources/ESH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.mail/src/test/java/org/openhab/binding/mail/MailBuilderTest.java
  bundles/pom.xml
  features/karaf/openhab-addons/src/main/feature/feature.xml
Labels: new binding

#5499 [azureiothub] migrate binding
  CODEOWNERS
  addons/io/org.openhab.io.azureiothub/.classpath
  addons/io/org.openhab.io.azureiothub/META-INF/MANIFEST.MF
  addons/io/org.openhab.io.azureiothub/OSGI-INF/.gitignore
  addons/io/org.openhab.io.azureiothub/build.properties
  addons/io/org.openhab.io.azureiothub/lib/azure-eventhubs-0.14.0.jar
  addons/io/org.openhab.io.azureiothub/lib/iot-device-client-1.2.27.jar
  addons/io/org.openhab.io.azureiothub/lib/iot-service-client-1.4.20.jar
  addons/io/org.openhab.io.azureiothub/lib/javax.json-api-1.0.jar
  addons/io/org.openhab.io.azureiothub/pom.xml
  addons/io/pom.xml
  bom/openhab-addons/pom.xml
  bundles/org.openhab.io.azureiothub/.classpath
  bundles/org.openhab.io.azureiothub/.project
  bundles/org.openhab.io.azureiothub/NOTICE
  bundles/org.openhab.io.azureiothub/README.md
  bundles/org.openhab.io.azureiothub/pom.xml
  bundles/org.openhab.io.azureiothub/src/main/java/org/openhab/io/internal/azureiothub/AzureDevice.java
  bundles/org.openhab.io.azureiothub/src/main/java/org/openhab/io/internal/azureiothub/AzureDevices.java
  bundles/org.openhab.io.azureiothub/src/main/java/org/openhab/io/internal/azureiothub/AzureEventCallback.java
  bundles/org.openhab.io.azureiothub/src/main/java/org/openhab/io/internal/azureiothub/CloudClient.java
  bundles/org.openhab.io.azureiothub/src/main/java/org/openhab/io/internal/azureiothub/CloudService.java
  bundles/org.openhab.io.azureiothub/src/main/resources/ESH-INF/config/config.xml
  bundles/pom.xml
  features/karaf/openhab-addons/src/main/feature/feature.xml
Labels: infrastructure

#5467 [zoneminder] migrate binding to bnd
  addons/binding/org.openhab.binding.zoneminder/.classpath
  addons/binding/org.openhab.binding.zoneminder/META-INF/MANIFEST.MF
  addons/binding/org.openhab.binding.zoneminder/OSGI-INF/.gitignore
  addons/binding/org.openhab.binding.zoneminder/build.properties
  addons/binding/org.openhab.binding.zoneminder/lib/gson-2.7.jar
  addons/binding/org.openhab.binding.zoneminder/lib/guava-17.0.jar
  addons/binding/org.openhab.binding.zoneminder/lib/javax.ws.rs-api-2.0.1.jar
  addons/binding/org.openhab.binding.zoneminder/lib/jersey-common-2.4.1.jar
  addons/binding/org.openhab.binding.zoneminder/lib/jsoup-1.10.1.jar
  addons/binding/org.openhab.binding.zoneminder/pom.xml
  addons/binding/pom.xml
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.zoneminder/.classpath
  bundles/org.openhab.binding.zoneminder/.project
  bundles/org.openhab.binding.zoneminder/NOTICE
  bundles/org.openhab.binding.zoneminder/README.md
  bundles/org.openhab.binding.zoneminder/lib/zoneminder4j-0.9.7.jar
  bundles/org.openhab.binding.zoneminder/pom.xml
  bundles/org.openhab.binding.zoneminder/src/main/java/org/openhab/binding/zoneminder/internal/DataRefreshPriorityEnum.java
  bundles/org.openhab.binding.zoneminder/src/main/java/org/openhab/binding/zoneminder/internal/ZoneMinderConstants.java
  bundles/org.openhab.binding.zoneminder/src/main/java/org/openhab/binding/zoneminder/internal/ZoneMinderHandlerFactory.java
  bundles/org.openhab.binding.zoneminder/src/main/java/org/openhab/binding/zoneminder/internal/ZoneMinderProperties.java
  bundles/org.openhab.binding.zoneminder/src/main/java/org/openhab/binding/zoneminder/internal/config/ZoneMinderBridgeServerConfig.java
  bundles/org.openhab.binding.zoneminder/src/main/java/org/openhab/binding/zoneminder/internal/config/ZoneMinderConfig.java
  bundles/org.openhab.binding.zoneminder/src/main/java/org/openhab/binding/zoneminder/internal/config/ZoneMinderThingConfig.java
  bundles/org.openhab.binding.zoneminder/src/main/java/org/openhab/binding/zoneminder/internal/config/ZoneMinderThingMonitorConfig.java
  bundles/org.openhab.binding.zoneminder/src/main/java/org/openhab/binding/zoneminder/internal/discovery/ZoneMinderDiscoveryService.java
  bundles/org.openhab.binding.zoneminder/src/main/java/org/openhab/binding/zoneminder/internal/handler/ZoneMinderBaseThingHandler.java
  bundles/org.openhab.binding.zoneminder/src/main/java/org/openhab/binding/zoneminder/internal/handler/ZoneMinderHandler.java
  bundles/org.openhab.binding.zoneminder/src/main/java/org/openhab/binding/zoneminder/internal/handler/ZoneMinderServerBridgeHandler.java
  bundles/org.openhab.binding.zoneminder/src/main/java/org/openhab/binding/zoneminder/internal/handler/ZoneMinderThingMonitorHandler.java
  bundles/org.openhab.binding.zoneminder/src/main/java/org/openhab/binding/zoneminder/internal/handler/ZoneMinderThingType.java
  bundles/org.openhab.binding.zoneminder/src/main/resources/ESH-INF/binding/binding.xml
  bundles/org.openhab.binding.zoneminder/src/main/resources/ESH-INF/config/monitor-channels.xml
  bundles/org.openhab.binding.zoneminder/src/main/resources/ESH-INF/config/zoneminderserver.xml
  bundles/org.openhab.binding.zoneminder/src/main/resources/ESH-INF/thing/monitor-thing.xml
  bundles/org.openhab.binding.zoneminder/src/main/resources/ESH-INF/thing/server-bridge.xml
  bundles/pom.xml
  features/karaf/openhab-addons/src/main/feature/feature.xml
Labels: infrastructure

#5501 [pollytts] migrate voice to bnd
  addons/pom.xml
  addons/voice/org.openhab.voice.pollytts/.classpath
  addons/voice/org.openhab.voice.pollytts/META-INF/MANIFEST.MF
  addons/voice/org.openhab.voice.pollytts/OSGI-INF/.gitignore
  addons/voice/org.openhab.voice.pollytts/build.properties
  addons/voice/org.openhab.voice.pollytts/lib/aws-java-sdk-core-1.11.490.jar
  addons/voice/org.openhab.voice.pollytts/lib/aws-java-sdk-polly-1.11.490.jar
  addons/voice/org.openhab.voice.pollytts/lib/commons-logging-1.1.3.jar
  addons/voice/org.openhab.voice.pollytts/lib/httpclient-4.5.5.jar
  addons/voice/org.openhab.voice.pollytts/lib/httpcore-4.4.9.jar
  addons/voice/org.openhab.voice.pollytts/lib/jackson-annotations-2.6.0.jar
  addons/voice/org.openhab.voice.pollytts/lib/jackson-core-2.6.7.jar
  addons/voice/org.openhab.voice.pollytts/lib/jackson-databind-2.6.7.2.jar
  addons/voice/org.openhab.voice.pollytts/lib/joda-time-2.8.1.jar
  addons/voice/org.openhab.voice.pollytts/pom.xml
  addons/voice/pom.xml
  bom/openhab-addons/pom.xml
  bundles/org.openhab.voice.pollytts/.classpath
  bundles/org.openhab.voice.pollytts/.project
  bundles/org.openhab.voice.pollytts/NOTICE
  bundles/org.openhab.voice.pollytts/README.md
  bundles/org.openhab.voice.pollytts/pom.xml
  bundles/org.openhab.voice.pollytts/src/main/java/org/openhab/voice/pollytts/internal/PollyTTSAudioStream.java
  bundles/org.openhab.voice.pollytts/src/main/java/org/openhab/voice/pollytts/internal/PollyTTSService.java
  bundles/org.openhab.voice.pollytts/src/main/java/org/openhab/voice/pollytts/internal/PollyTTSVoice.java
  bundles/org.openhab.voice.pollytts/src/main/java/org/openhab/voice/pollytts/internal/cloudapi/CachedPollyTTSCloudImpl.java
  bundles/org.openhab.voice.pollytts/src/main/java/org/openhab/voice/pollytts/internal/cloudapi/PollyTTSCloudImpl.java
  bundles/org.openhab.voice.pollytts/src/main/java/org/openhab/voice/pollytts/internal/cloudapi/PollyTTSConfig.java
  bundles/org.openhab.voice.pollytts/src/main/resources/ESH-INF/config/config.xml
  bundles/pom.xml
  features/karaf/openhab-addons/src/main/feature/feature.xml
Labels: infrastructure

#5500 [openhabcloud] migrate cloud service to bnd
  CODEOWNERS
  addons/io/org.openhab.io.openhabcloud/.classpath
  addons/io/org.openhab.io.openhabcloud/META-INF/MANIFEST.MF
  addons/io/org.openhab.io.openhabcloud/OSGI-INF/.gitignore
  addons/io/org.openhab.io.openhabcloud/build.properties
  addons/io/org.openhab.io.openhabcloud/lib/engine.io-client-1.0.0.jar
  addons/io/org.openhab.io.openhabcloud/lib/json-20180813.jar
  addons/io/org.openhab.io.openhabcloud/lib/okhttp-3.12.1.jar
  addons/io/org.openhab.io.openhabcloud/lib/okio-1.15.0.jar
  addons/io/org.openhab.io.openhabcloud/lib/socket.io-client-1.0.0.jar
  addons/io/org.openhab.io.openhabcloud/pom.xml
  addons/io/pom.xml
  bom/openhab-addons/pom.xml
  bundles/org.openhab.io.openhabcloud/.classpath
  bundles/org.openhab.io.openhabcloud/.project
  bundles/org.openhab.io.openhabcloud/NOTICE
  bundles/org.openhab.io.openhabcloud/README.md
  bundles/org.openhab.io.openhabcloud/contrib/doc/cfg.png
  bundles/org.openhab.io.openhabcloud/pom.xml
  bundles/org.openhab.io.openhabcloud/src/main/java/org/openhab/io/openhabcloud/NotificationAction.java
  bundles/org.openhab.io.openhabcloud/src/main/java/org/openhab/io/openhabcloud/internal/CloudClient.java
  bundles/org.openhab.io.openhabcloud/src/main/java/org/openhab/io/openhabcloud/internal/CloudClientListener.java
  bundles/org.openhab.io.openhabcloud/src/main/java/org/openhab/io/openhabcloud/internal/CloudService.java
  bundles/org.openhab.io.openhabcloud/src/main/resources/ESH-INF/config/config.xml
  bundles/pom.xml
  features/karaf/openhab-addons/src/main/feature/feature.xml
Labels: infrastructure

#5482 [samsungtv] Migrate to bnd build
  CODEOWNERS
  addons/binding/org.openhab.binding.samsungtv/.classpath
  addons/binding/org.openhab.binding.samsungtv/META-INF/MANIFEST.MF
  addons/binding/org.openhab.binding.samsungtv/OSGI-INF/.gitignore
  addons/binding/org.openhab.binding.samsungtv/build.properties
  addons/binding/pom.xml
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.samsungtv/.classpath
  bundles/org.openhab.binding.samsungtv/.project
  bundles/org.openhab.binding.samsungtv/NOTICE
  bundles/org.openhab.binding.samsungtv/README.md
  bundles/org.openhab.binding.samsungtv/pom.xml
  bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/SamsungTvBindingConstants.java
  bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/SamsungTvHandlerFactory.java
  bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/config/SamsungTvConfiguration.java
  bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/discovery/SamsungTvDiscoveryParticipant.java
  bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/handler/SamsungTvHandler.java
  bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/protocol/KeyCode.java
  bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/protocol/RemoteController.java
  bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/protocol/RemoteControllerException.java
  bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/service/DataConverters.java
  bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/service/MainTVServerService.java
  bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/service/MediaRendererService.java
  bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/service/RemoteControllerService.java
  bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/service/SamsungTvUtils.java
  bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/service/ServiceFactory.java
  bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/service/api/EventListener.java
  bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/service/api/SamsungTvService.java
  bundles/org.openhab.binding.samsungtv/src/main/resources/ESH-INF/binding/binding.xml
  bundles/org.openhab.binding.samsungtv/src/main/resources/ESH-INF/config/config.xml
  bundles/org.openhab.binding.samsungtv/src/main/resources/ESH-INF/i18n/samsung_de.properties
  bundles/org.openhab.binding.samsungtv/src/main/resources/ESH-INF/thing/channel-types.xml
  bundles/org.openhab.binding.samsungtv/src/main/resources/ESH-INF/thing/thing-types.xml
  bundles/pom.xml
  features/karaf/openhab-addons/src/main/feature/feature.xml
Labels: awaiting other PR, infrastructure

#5460 [feed] migrate to bnd
  CODEOWNERS
  addons/binding/org.openhab.binding.feed.test/.classpath
  addons/binding/org.openhab.binding.feed.test/META-INF/MANIFEST.MF
  addons/binding/org.openhab.binding.feed.test/build.properties
  addons/binding/org.openhab.binding.feed.test/org.openhab.binding.feed.test.launch
  addons/binding/org.openhab.binding.feed.test/pom.xml
  addons/binding/org.openhab.binding.feed/.classpath
  addons/binding/org.openhab.binding.feed/META-INF/MANIFEST.MF
  addons/binding/org.openhab.binding.feed/OSGI-INF/.gitignore
  addons/binding/org.openhab.binding.feed/build.properties
  addons/binding/org.openhab.binding.feed/pom.xml
  addons/binding/pom.xml
  addons/io/org.openhab.io.transport.feed/.classpath
  addons/io/org.openhab.io.transport.feed/.project
  addons/io/org.openhab.io.transport.feed/META-INF/MANIFEST.MF
  addons/io/org.openhab.io.transport.feed/NOTICE
  addons/io/org.openhab.io.transport.feed/README.md
  addons/io/org.openhab.io.transport.feed/build.properties
  addons/io/org.openhab.io.transport.feed/lib/jdom2-2.0.6.jar
  addons/io/org.openhab.io.transport.feed/lib/rome-1.7.0.jar
  addons/io/org.openhab.io.transport.feed/lib/rome-utils-1.7.0.jar
  addons/io/org.openhab.io.transport.feed/pom.xml
  addons/io/pom.xml
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.feed/.classpath
  bundles/org.openhab.binding.feed/.project
  bundles/org.openhab.binding.feed/NOTICE
  bundles/org.openhab.binding.feed/README.md
  bundles/org.openhab.binding.feed/pom.xml
  bundles/org.openhab.binding.feed/src/main/java/org/openhab/binding/feed/internal/FeedBindingConstants.java
  bundles/org.openhab.binding.feed/src/main/java/org/openhab/binding/feed/internal/FeedHandlerFactory.java
  bundles/org.openhab.binding.feed/src/main/java/org/openhab/binding/feed/internal/handler/FeedHandler.java
  bundles/org.openhab.binding.feed/src/main/resources/ESH-INF/binding/binding.xml
  bundles/org.openhab.binding.feed/src/main/resources/ESH-INF/thing/thing-types.xml
  bundles/pom.xml
  features/karaf/openhab-addons/src/main/feature/feature.xml
  itests/org.openhab.binding.feed.tests/.classpath
  itests/org.openhab.binding.feed.tests/.project
  itests/org.openhab.binding.feed.tests/NOTICE
  itests/org.openhab.binding.feed.tests/itest.bndrun
  itests/org.openhab.binding.feed.tests/pom.xml
  itests/org.openhab.binding.feed.tests/src/main/java/org/openhab/binding/feed/test/FeedHandlerTest.java
  itests/org.openhab.binding.feed.tests/src/main/java/org/openhab/binding/feed/test/SlowTests.java
  itests/org.openhab.binding.feed.tests/src/main/resources/input/rss_2.0.xml
  itests/org.openhab.binding.feed.tests/src/main/resources/input/rss_2.0_changed.xml
  itests/pom.xml
Labels: infrastructure

#5514 Clean up CODEOWNERS for missed migration changes.
  CODEOWNERS
Labels: infrastructure

#5518 [amazonechocontrol] Fix nullerrors
  bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/statedescription/AmazonEchoDynamicStateDescriptionProvider.java
Labels: critical

#5462 Moved and updated new bindings skeleton creation scripts
  addons/binding/create_openhab_binding_skeleton.cmd
  addons/binding/create_openhab_binding_skeleton.sh
  addons/binding/create_openhab_binding_test_skeleton.cmd
  addons/binding/create_openhab_binding_test_skeleton.sh
  bundles/archetype-settings.xml
  bundles/create_openhab_binding_skeleton.cmd
  bundles/create_openhab_binding_skeleton.sh
Labels: infrastructure

#5509 [darksky] Minor tweak for 'sunrise-event'
  bundles/org.openhab.binding.darksky/README.md
  bundles/org.openhab.binding.darksky/src/main/resources/ESH-INF/thing/channel-types.xml
Labels: documentation

#5131 [buienradar] Buienradar Binding initial contribution
  CODEOWNERS
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.buienradar/.classpath
  bundles/org.openhab.binding.buienradar/.project
  bundles/org.openhab.binding.buienradar/NOTICE
  bundles/org.openhab.binding.buienradar/README.md
  bundles/org.openhab.binding.buienradar/pom.xml
  bundles/org.openhab.binding.buienradar/src/main/java/org/openhab/binding/buienradar/internal/BuienradarBindingConstants.java
  bundles/org.openhab.binding.buienradar/src/main/java/org/openhab/binding/buienradar/internal/BuienradarConfiguration.java
  bundles/org.openhab.binding.buienradar/src/main/java/org/openhab/binding/buienradar/internal/BuienradarHandler.java
  bundles/org.openhab.binding.buienradar/src/main/java/org/openhab/binding/buienradar/internal/BuienradarHandlerFactory.java
  bundles/org.openhab.binding.buienradar/src/main/java/org/openhab/binding/buienradar/internal/buienradarapi/BuienradarParseException.java
  bundles/org.openhab.binding.buienradar/src/main/java/org/openhab/binding/buienradar/internal/buienradarapi/BuienradarPredictionAPI.java
  bundles/org.openhab.binding.buienradar/src/main/java/org/openhab/binding/buienradar/internal/buienradarapi/Prediction.java
  bundles/org.openhab.binding.buienradar/src/main/java/org/openhab/binding/buienradar/internal/buienradarapi/PredictionAPI.java
  bundles/org.openhab.binding.buienradar/src/main/resources/ESH-INF/binding/binding.xml
  bundles/org.openhab.binding.buienradar/src/main/resources/ESH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.buienradar/src/test/java/org/openhab/binding/buienradar/BuienradarPredictionAPITest.java
  bundles/pom.xml
  features/karaf/openhab-addons/src/main/feature/feature.xml
Labels: new binding

#5525 [innogysmarthome] fix dependencies
  bundles/org.openhab.binding.innogysmarthome/pom.xml
  bundles/org.openhab.binding.innogysmarthome/src/main/java/org/openhab/binding/innogysmarthome/internal/client/InnogyClient.java
  features/karaf/openhab-addons/src/main/feature/feature.xml
Labels: bug
