Repository openhab/openhab-addons, pull requests merged in 2019-06, with the labels that each got.

#5671 [evohome] Amend typo in display supported values on README
  bundles/org.openhab.binding.evohome/README.md
Labels: documentation

#5673 [miio] Add support for Roborock S6
  bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/MiIoDevices.java
Labels: enhancement

#5684 [transform.scale] Update README.md
  bundles/org.openhab.transform.scale/README.md
Labels: documentation

#5667 [mqtt] Fix restructure mqtt package names for integration tests
  itests/org.openhab.binding.mqtt.homeassistant.tests/pom.xml
  itests/org.openhab.binding.mqtt.homeassistant.tests/src/main/java/org/openhab/binding/mqtt/DiscoverComponentsTests.java
  itests/org.openhab.binding.mqtt.homeassistant.tests/src/main/java/org/openhab/binding/mqtt/HomeAssistantMQTTImplementationTests.java
  itests/org.openhab.binding.mqtt.homeassistant.tests/src/main/java/org/openhab/binding/mqtt/ThingChannelConstants.java
  itests/org.openhab.binding.mqtt.homie.tests/pom.xml
  itests/org.openhab.binding.mqtt.homie.tests/src/main/java/org/openhab/binding/mqtt/generic/HomieImplementationTests.java
  itests/org.openhab.binding.mqtt.homie.tests/src/main/java/org/openhab/binding/mqtt/generic/ThingChannelConstants.java
  itests/org.openhab.binding.mqtt.homie.tests/src/main/java/org/openhab/binding/mqtt/homie/internal/homie300/PropertyHelper.java
Labels: binding: mqtt

#5698 [homekit] update documentation
  bundles/org.openhab.io.homekit/README.md
Labels: documentation, io: homekit

#5697 [deconz] Fixed rule with Channel trigger example
  bundles/org.openhab.binding.deconz/README.md
Labels: documentation

#5692 [astro] Fixed handling of division by 0 for new moon
  bundles/org.openhab.binding.astro/src/main/java/org/openhab/binding/astro/internal/calc/MoonCalc.java
Labels: bug

#5665 [enocean] Fix A5-38-08 Dimmer reset to 0
  bundles/org.openhab.binding.enocean/src/main/java/org/openhab/binding/enocean/internal/eep/A5_38/A5_38_08_Dimming.java
Labels: bug

#5696 [miele] fixed bullet point list and link to source repo
  bundles/org.openhab.binding.miele/README.md
Labels: documentation

#5701 unwrap some features
  bundles/org.openhab.binding.avmfritz/src/main/feature/feature.xml
  bundles/org.openhab.binding.denonmarantz/src/main/feature/feature.xml
  bundles/org.openhab.binding.dlinksmarthome/src/main/feature/feature.xml
  bundles/org.openhab.binding.lgwebos/src/main/feature/feature.xml
  bundles/org.openhab.binding.tellstick/src/main/feature/feature.xml
  bundles/org.openhab.binding.xmltv/src/main/feature/feature.xml
  bundles/org.openhab.io.mqttembeddedbroker/src/main/feature/feature.xml
  bundles/org.openhab.io.openhabcloud/src/main/feature/feature.xml
Labels: infrastructure

#5705 [enocean] Enable discovery of occupancy sensors using EEP A5-07-03
  bundles/org.openhab.binding.enocean/src/main/java/org/openhab/binding/enocean/internal/eep/EEPType.java
Labels: bug

#5703 [enocean] Improve incoming message handling for Eltako rollershutters
  bundles/org.openhab.binding.enocean/src/main/java/org/openhab/binding/enocean/internal/config/EnOceanChannelRollershutterConfig.java
  bundles/org.openhab.binding.enocean/src/main/java/org/openhab/binding/enocean/internal/eep/A5_3F/A5_3F_7F_EltakoFSB.java
  bundles/org.openhab.binding.enocean/src/main/java/org/openhab/binding/enocean/internal/handler/EnOceanBaseSensorHandler.java
  bundles/org.openhab.binding.enocean/src/main/resources/ESH-INF/thing/Rollershutter.xml
Labels: enhancement

#5707 [xmppclient] remove wrapping and force dependency install
  bundles/org.openhab.binding.xmppclient/src/main/feature/feature.xml
Labels: bug, infrastructure

#5686 [dmx] fix documentation typo
  bundles/org.openhab.binding.dmx/README.md
Labels: documentation

#5595 [keba] Add setenergy command
  bundles/org.openhab.binding.keba/README.md
  bundles/org.openhab.binding.keba/src/main/java/org/openhab/binding/keba/internal/KebaBindingConstants.java
  bundles/org.openhab.binding.keba/src/main/java/org/openhab/binding/keba/internal/handler/KeContactHandler.java
  bundles/org.openhab.binding.keba/src/main/resources/ESH-INF/thing/kecontact.xml
Labels: enhancement

#5727 [hueemulation] seperate ipv4 / ipv6
  bundles/org.openhab.io.hueemulation/src/main/java/org/glassfish/jersey/servlet/init/JerseyServletContainerInitializer.java
  bundles/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/HueEmulationService.java
  bundles/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/automation/TimerTriggerHandler.java
  bundles/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/rest/ConfigurationAccess.java
  bundles/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/rest/Rules.java
  bundles/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/rest/Scenes.java
  bundles/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/rest/Schedules.java
  bundles/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/upnp/UpnpServer.java
  bundles/org.openhab.io.hueemulation/src/test/java/org/openhab/io/hueemulation/internal/automation/RuleConditionHandlerTests.java
  bundles/org.openhab.io.hueemulation/src/test/java/org/openhab/io/hueemulation/internal/rest/LightsAndGroupsTests.java
  bundles/org.openhab.io.hueemulation/src/test/java/org/openhab/io/hueemulation/internal/rest/SensorTests.java
  bundles/org.openhab.io.hueemulation/src/test/java/org/openhab/io/hueemulation/internal/rest/UsersAndConfigTests.java
  bundles/org.openhab.io.hueemulation/src/test/java/org/openhab/io/hueemulation/internal/rest/mocks/DummyItemRegistry.java
Labels: build

#5695 [knx] improve connection handling on reconnect
  bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/client/AbstractKNXClient.java
  bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/config/BridgeConfiguration.java
  bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/handler/IPBridgeThingHandler.java
  bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/handler/SerialBridgeThingHandler.java
  bundles/org.openhab.binding.knx/src/main/resources/ESH-INF/thing/ip.xml
Labels: binding: knx, bug

#5722 [xmppclient] Improved readme file
  bundles/org.openhab.binding.xmppclient/README.md
Labels: documentation

#5743 [openhabcloud] partly revert unwrapping
  bundles/org.openhab.io.openhabcloud/src/main/feature/feature.xml
Labels: critical, infrastructure

#5728 [wip] fix build errors
  itests/org.openhab.binding.astro.tests/itest.bndrun
  itests/org.openhab.binding.avmfritz.tests/itest.bndrun
  itests/org.openhab.binding.avmfritz.tests/src/main/java/org/openhab/binding/avmfritz/internal/discovery/AVMFritzDiscoveryServiceTest.java
  itests/org.openhab.binding.feed.tests/itest.bndrun
  itests/org.openhab.binding.mqtt.homeassistant.tests/src/main/java/org/openhab/binding/mqtt/DiscoverComponentsTests.java
  itests/org.openhab.binding.mqtt.homeassistant.tests/src/main/java/org/openhab/binding/mqtt/HomeAssistantMQTTImplementationTests.java
  itests/org.openhab.binding.mqtt.homeassistant.tests/src/main/java/org/openhab/binding/mqtt/ThingChannelConstants.java
  itests/org.openhab.binding.mqtt.homie.tests/src/main/java/org/openhab/binding/mqtt/generic/EmbeddedBrokerTools.java
  itests/org.openhab.binding.mqtt.homie.tests/src/main/java/org/openhab/binding/mqtt/generic/HomieImplementationTests.java
  itests/org.openhab.binding.mqtt.homie.tests/src/main/java/org/openhab/binding/mqtt/generic/ThingChannelConstants.java
  itests/org.openhab.binding.nest.tests/src/main/java/org/openhab/binding/nest/internal/data/GsonParsingTest.java
  itests/org.openhab.binding.tradfri.tests/itest.bndrun
  itests/org.openhab.binding.tradfri.tests/src/main/java/org/openhab/binding/tradfri/internal/discovery/TradfriDiscoveryParticipantOSGITest.java
  itests/org.openhab.binding.tradfri.tests/src/main/java/org/openhab/binding/tradfri/internal/handler/TradfriHandlerOSGiTest.java
  itests/org.openhab.io.hueemulation.tests/itest.bndrun
  itests/org.openhab.io.hueemulation.tests/src/main/java/org/openhab/io/hueemulation/internal/HueEmulationServiceOSGiTest.java
Labels: build, work in progress

#5720 [astro] Fix astro #5006
  bundles/org.openhab.binding.astro/src/main/java/org/openhab/binding/astro/internal/model/Sun.java
  bundles/org.openhab.binding.astro/src/test/java/org/openhab/binding/astro/internal/calc/SunCalcTest.java
  bundles/org.openhab.binding.astro/src/test/java/org/openhab/binding/astro/internal/model/SunTest.java
Labels: bug

#5706 [bluetooth/bluez] fix dependencies
  bundles/org.openhab.binding.bluetooth.bluez/lib/tinyb-0.5.1.jar
  bundles/org.openhab.binding.bluetooth.bluez/pom.xml
  bundles/org.openhab.binding.bluetooth.bluez/src/main/feature/feature.xml
  bundles/org.openhab.binding.bluetooth.bluez/src/main/java/org/openhab/binding/bluetooth/bluez/handler/BlueZBridgeHandler.java
  bundles/org.openhab.binding.bluetooth.bluez/src/main/java/org/openhab/binding/bluetooth/bluez/package-info.java
  bundles/org.openhab.binding.bluetooth.bluez/src/main/resources/lib/armv6hf/libjavatinyb.so
  bundles/org.openhab.binding.bluetooth.bluez/src/main/resources/lib/armv6hf/libtinyb.so
  bundles/org.openhab.binding.bluetooth.bluez/src/main/resources/lib/x86-64/libjavatinyb.so
  bundles/org.openhab.binding.bluetooth.bluez/src/main/resources/lib/x86-64/libtinyb.so
Labels: bug

#5738 [samsungtv] Fix minor bugs introduced with #4169
  bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/SamsungTvTlsTrustManagerProvider.java
  bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/WakeOnLanUtility.java
  bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/discovery/SamsungTvDiscoveryParticipant.java
  bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/handler/SamsungTvHandler.java
  bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/protocol/RemoteControllerWebSocket.java
  bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/protocol/WebSocketBase.java
  bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/protocol/WebSocketRemote.java
  bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/service/MainTVServerService.java
  bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/service/MediaRendererService.java
  bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/service/RemoteControllerService.java
  bundles/org.openhab.binding.samsungtv/src/main/resources/ESH-INF/config/config.xml
Labels: bug

#5769 [onkyo] fix missing closing tag
  bundles/org.openhab.binding.onkyo/src/main/resources/ESH-INF/thing/ht-rc560.xml
  bundles/org.openhab.binding.onkyo/src/main/resources/ESH-INF/thing/onkyoAVR.xml
  bundles/org.openhab.binding.onkyo/src/main/resources/ESH-INF/thing/tx-nr414.xml
  bundles/org.openhab.binding.onkyo/src/main/resources/ESH-INF/thing/tx-nr474.xml
  bundles/org.openhab.binding.onkyo/src/main/resources/ESH-INF/thing/tx-nr509.xml
  bundles/org.openhab.binding.onkyo/src/main/resources/ESH-INF/thing/tx-nr515.xml
  bundles/org.openhab.binding.onkyo/src/main/resources/ESH-INF/thing/tx-nr525.xml
  bundles/org.openhab.binding.onkyo/src/main/resources/ESH-INF/thing/tx-nr535.xml
  bundles/org.openhab.binding.onkyo/src/main/resources/ESH-INF/thing/tx-nr545.xml
  bundles/org.openhab.binding.onkyo/src/main/resources/ESH-INF/thing/tx-nr555.xml
  bundles/org.openhab.binding.onkyo/src/main/resources/ESH-INF/thing/tx-nr575.xml
  bundles/org.openhab.binding.onkyo/src/main/resources/ESH-INF/thing/tx-nr575e.xml
  bundles/org.openhab.binding.onkyo/src/main/resources/ESH-INF/thing/tx-nr616.xml
  bundles/org.openhab.binding.onkyo/src/main/resources/ESH-INF/thing/tx-nr626.xml
  bundles/org.openhab.binding.onkyo/src/main/resources/ESH-INF/thing/tx-nr636.xml
  bundles/org.openhab.binding.onkyo/src/main/resources/ESH-INF/thing/tx-nr646.xml
  bundles/org.openhab.binding.onkyo/src/main/resources/ESH-INF/thing/tx-nr656.xml
  bundles/org.openhab.binding.onkyo/src/main/resources/ESH-INF/thing/tx-nr676.xml
  bundles/org.openhab.binding.onkyo/src/main/resources/ESH-INF/thing/tx-nr686.xml
  bundles/org.openhab.binding.onkyo/src/main/resources/ESH-INF/thing/tx-nr708.xml
  bundles/org.openhab.binding.onkyo/src/main/resources/ESH-INF/thing/tx-nr717.xml
  bundles/org.openhab.binding.onkyo/src/main/resources/ESH-INF/thing/tx-nr727.xml
  bundles/org.openhab.binding.onkyo/src/main/resources/ESH-INF/thing/tx-nr737.xml
  bundles/org.openhab.binding.onkyo/src/main/resources/ESH-INF/thing/tx-nr747.xml
  bundles/org.openhab.binding.onkyo/src/main/resources/ESH-INF/thing/tx-nr818.xml
  bundles/org.openhab.binding.onkyo/src/main/resources/ESH-INF/thing/tx-nr828.xml
  bundles/org.openhab.binding.onkyo/src/main/resources/ESH-INF/thing/tx-nr838.xml
Labels: bug

#5389 Travis: Build new binding pull requests with tests
  .gitignore
  .travis.yml
  buildci.sh
  travis-buddy-failure-template.md
  travis-buddy-success-template.md
Labels: infrastructure
