Repository openhab/openhab-addons, pull requests merged in 2019-02, with the labels that each got.

#4795 [Impovement]fix typo in documentation
  addons/binding/org.openhab.binding.bluetooth/README.md
Labels: documentation

#4464 [homekit] Augment README with some debugging help, links, and other help
  addons/io/org.openhab.io.homekit/README.md
Labels: documentation, homekit

#4798 Fixed URL to Owntracks in Google Play Store.
  addons/binding/org.openhab.binding.gpstracker/README.md
Labels: documentation

#4803 [openweathermap] Fixed spelling of channel id in example
  addons/binding/org.openhab.binding.openweathermap/README.md
Labels: documentation

#4823 Fix mixed content
  addons/binding/org.openhab.binding.milight/README.md
  addons/binding/org.openhab.binding.minecraft/README.md
Labels: documentation

#4861 [mqtt] Update README.md
  addons/binding/org.openhab.binding.mqtt/README.md
Labels: documentation

#4785 [max] Cube data backup
  addons/binding/org.openhab.binding.max/META-INF/MANIFEST.MF
  addons/binding/org.openhab.binding.max/src/main/java/org/openhab/binding/max/internal/MaxBackupUtils.java
  addons/binding/org.openhab.binding.max/src/main/java/org/openhab/binding/max/internal/MaxConsoleCommandExtension.java
  addons/binding/org.openhab.binding.max/src/main/java/org/openhab/binding/max/internal/command/UdpCubeCommand.java
  addons/binding/org.openhab.binding.max/src/main/java/org/openhab/binding/max/internal/handler/MaxCubeBridgeHandler.java
Labels: rebuild

#4862 [airquality] Update README.md
  addons/binding/org.openhab.binding.airquality/README.md
Labels: documentation

#4876 [milight] Update README.md
  addons/binding/org.openhab.binding.milight/README.md
Labels: documentation

#4866 [dscalarm] Update README.md
  addons/binding/org.openhab.binding.dscalarm/README.md
Labels: documentation

#4880 [wifiled] Update README.md
  addons/binding/org.openhab.binding.wifiled/README.md
Labels: documentation

#4867 [elerotransmitterstick] Update README.md
  addons/binding/org.openhab.binding.elerotransmitterstick/README.md
Labels: documentation

#4780 [miio] update readme
  addons/binding/org.openhab.binding.miio/README.md
Labels: documentation

#4868 [evohome] Changed README.md
  addons/binding/org.openhab.binding.evohome/README.md
Labels: documentation

#4869 [gardena] Update README.md
  addons/binding/org.openhab.binding.gardena/README.md
Labels: documentation

#4871 [globalcache] Update README.md
  addons/binding/org.openhab.binding.globalcache/README.md
Labels: documentation

#4872 [homematic] Update README.md
  addons/binding/org.openhab.binding.homematic/README.md
Labels: documentation

#4873 [lametrictime] Update README.md
  addons/binding/org.openhab.binding.lametrictime/README.md
Labels: documentation

#4874 [lgwebos] Update README.md
  addons/binding/org.openhab.binding.lgwebos/README.md
Labels: documentation

#4875 [lirc] Update README.md
  addons/binding/org.openhab.binding.lirc/README.md
Labels: documentation

#4877 [neato] Update README.md
  addons/binding/org.openhab.binding.neato/README.md
Labels: documentation

#4878 [pentair] Update README.md
  addons/binding/org.openhab.binding.pentair/README.md
Labels: documentation

#4879 [tellstick] Update README.md
  addons/binding/org.openhab.binding.tellstick/README.md
Labels: documentation

#4881 [mihome] Update README.md
  addons/binding/org.openhab.binding.mihome/README.md
Labels: documentation

#4883 [zoneminder] Update README.md
  addons/binding/org.openhab.binding.zoneminder/README.md
Labels: documentation

#1647 [homekit] Update README.md
  addons/io/org.openhab.io.homekit/README.md
Labels: documentation, homekit

#4887 [yeelight] Fix typo in readme and add example for switch on color cha…
  addons/binding/org.openhab.binding.yeelight/README.md
Labels: documentation

#4910 [jsonpath] Updated README.md (fixed typo)
  addons/transform/org.openhab.transform.jsonpath/README.md
Labels: documentation

#4919 [modbus] docs: refer to general serial port configuration instructions
  addons/binding/org.openhab.binding.modbus/README.md
Labels: documentation

#4936 [mqtt][Docu] Finish "Synchronise two instances"
  addons/binding/org.openhab.binding.mqtt.generic/README.md
Labels: documentation, mqtt

#4950 [amazonechocontrol] Documentation update
  addons/binding/org.openhab.binding.amazonechocontrol/README.md
Labels: documentation

#4964 Readme update
  README.md
Labels: documentation

#4959 [modbus] Readme
  addons/io/org.openhab.io.transport.modbus/README.md
Labels: documentation

#4958 [feed] Readme
  addons/io/org.openhab.io.transport.feed/README.md
Labels: documentation

#4960 [webaudio] Readme
  addons/io/org.openhab.io.webaudio/README.md
Labels: documentation

#4961 [javasound] Readme
  addons/io/org.openhab.io.javasound/README.md
Labels: documentation

#4962 [kaldi] Readme
  addons/voice/org.openhab.voice.kaldi/README.md
Labels: documentation

#4963 [eclipsemarketplace] Readme
  addons/extensionservice/org.openhab.extensionservice.marketplace/README.md
Labels: documentation

#4828 [modbus] Minor text updates
  addons/binding/org.openhab.binding.modbus/README.md
Labels: documentation

#4790 [samsungtv] Update tested device list (UN50J5200)
  addons/binding/org.openhab.binding.samsungtv/README.md
Labels: awaiting feedback, documentation

#4825 [samsungtv] Update Tested Tv Models
  addons/binding/org.openhab.binding.samsungtv/README.md
Labels: documentation

#4967 [modbus] Readme
  addons/binding/org.openhab.binding.modbus/README.md
Labels: documentation

#4943 [jinja] Jinja Transform initial contribution
  addons/transform/org.openhab.transform.jinja.test/.classpath
  addons/transform/org.openhab.transform.jinja.test/.project
  addons/transform/org.openhab.transform.jinja.test/META-INF/MANIFEST.MF
  addons/transform/org.openhab.transform.jinja.test/NOTICE
  addons/transform/org.openhab.transform.jinja.test/build.properties
  addons/transform/org.openhab.transform.jinja.test/org.openhab.transform.jinja.test.launch
  addons/transform/org.openhab.transform.jinja.test/pom.xml
  addons/transform/org.openhab.transform.jinja.test/src/test/java/org/openhab/transform/jinja/internal/JinjaTransformationServiceTest.java
  addons/transform/org.openhab.transform.jinja/.classpath
  addons/transform/org.openhab.transform.jinja/.project
  addons/transform/org.openhab.transform.jinja/ESH-INF/config/jinjaProfile.xml
  addons/transform/org.openhab.transform.jinja/META-INF/MANIFEST.MF
  addons/transform/org.openhab.transform.jinja/NOTICE
  addons/transform/org.openhab.transform.jinja/OSGI-INF/.gitignore
  addons/transform/org.openhab.transform.jinja/README.md
  addons/transform/org.openhab.transform.jinja/build.properties
  addons/transform/org.openhab.transform.jinja/lib/commons-lang3-3.8.1.jar
  addons/transform/org.openhab.transform.jinja/lib/jackson-annotations-2.9.8.jar
  addons/transform/org.openhab.transform.jinja/lib/jackson-core-2.9.8.jar
  addons/transform/org.openhab.transform.jinja/lib/jackson-databind-2.9.8.jar
  addons/transform/org.openhab.transform.jinja/lib/jinjava-2.4.12.jar
  addons/transform/org.openhab.transform.jinja/lib/jsoup-1.11.3.jar
  addons/transform/org.openhab.transform.jinja/lib/re2j-1.2.jar
  addons/transform/org.openhab.transform.jinja/pom.xml
  addons/transform/org.openhab.transform.jinja/src/main/java/org/openhab/transform/jinja/internal/JinjaTransformationService.java
  addons/transform/org.openhab.transform.jinja/src/main/java/org/openhab/transform/jinja/internal/profiles/JinjaTransformationProfile.java
  addons/transform/org.openhab.transform.jinja/src/main/java/org/openhab/transform/jinja/internal/profiles/JinjaTransformationProfileFactory.java
  addons/transform/pom.xml
Labels: new transform

#4977 [Nibeuplink] extended available channels for different models
  addons/binding/org.openhab.binding.nibeuplink/ESH-INF/thing/base-channel-groups.xml
  addons/binding/org.openhab.binding.nibeuplink/ESH-INF/thing/base-channel-types.xml
  addons/binding/org.openhab.binding.nibeuplink/ESH-INF/thing/f1145-channel-groups.xml
  addons/binding/org.openhab.binding.nibeuplink/ESH-INF/thing/f1145-channel-types.xml
  addons/binding/org.openhab.binding.nibeuplink/ESH-INF/thing/f1155-channel-groups.xml
  addons/binding/org.openhab.binding.nibeuplink/ESH-INF/thing/f1155-channel-types.xml
  addons/binding/org.openhab.binding.nibeuplink/ESH-INF/thing/vvm310-channel-groups.xml
  addons/binding/org.openhab.binding.nibeuplink/ESH-INF/thing/vvm310-channel-types.xml
  addons/binding/org.openhab.binding.nibeuplink/ESH-INF/thing/vvm320-channel-groups.xml
  addons/binding/org.openhab.binding.nibeuplink/ESH-INF/thing/vvm320-channel-types.xml
  addons/binding/org.openhab.binding.nibeuplink/README.md
  addons/binding/org.openhab.binding.nibeuplink/src/main/java/org/openhab/binding/nibeuplink/internal/model/BaseChannels.java
  addons/binding/org.openhab.binding.nibeuplink/src/main/java/org/openhab/binding/nibeuplink/internal/model/F1145Channels.java
  addons/binding/org.openhab.binding.nibeuplink/src/main/java/org/openhab/binding/nibeuplink/internal/model/F1155Channels.java
  addons/binding/org.openhab.binding.nibeuplink/src/main/java/org/openhab/binding/nibeuplink/internal/model/VVM310Channels.java
  addons/binding/org.openhab.binding.nibeuplink/src/main/java/org/openhab/binding/nibeuplink/internal/model/VVM320Channels.java
Labels: enhancement

#4983 [Lutron] Add new model support and button hold fix to keypad handler
  addons/binding/org.openhab.binding.lutron/ESH-INF/thing/thing-types.xml
  addons/binding/org.openhab.binding.lutron/README.md
  addons/binding/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/handler/BaseKeypadHandler.java
  addons/binding/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/handler/KeypadHandler.java
Labels: enhancement

#4973 [yeelight] Fix UI not updating from status for Color bulb
  addons/binding/org.openhab.binding.yeelight/src/main/java/org/openhab/binding/yeelight/internal/handler/YeelightCeilingHandler.java
  addons/binding/org.openhab.binding.yeelight/src/main/java/org/openhab/binding/yeelight/internal/handler/YeelightHandlerBase.java
  addons/binding/org.openhab.binding.yeelight/src/main/java/org/openhab/binding/yeelight/internal/handler/YeelightWhiteHandler.java
Labels: bug

#4897 [knx] Update README.md
  addons/binding/org.openhab.binding.knx/README.md
Labels: documentation, knx

#4985 [mqtt] CFactory: don't repeat yourself
  addons/binding/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/internal/convention/homeassistant/CFactory.java
Labels: mqtt

#4955 [Onkyo] Thing action to send raw eISCP commands
  addons/binding/org.openhab.binding.onkyo/META-INF/MANIFEST.MF
  addons/binding/org.openhab.binding.onkyo/README.md
  addons/binding/org.openhab.binding.onkyo/src/main/java/org/openhab/binding/onkyo/internal/automation/modules/OnkyoThingActionsService.java
  addons/binding/org.openhab.binding.onkyo/src/main/java/org/openhab/binding/onkyo/internal/handler/OnkyoHandler.java
Labels: enhancement

#5000 [mcp23017] Added hint to the wiringPi library
  addons/binding/org.openhab.binding.mcp23017/README.md
Labels: documentation

#4986 [mqtt] HA discovery: move common configuration to base class
  addons/binding/org.openhab.binding.mqtt.generic.test/META-INF/MANIFEST.MF
  addons/binding/org.openhab.binding.mqtt.generic.test/src/test/java/org/openhab/binding/mqtt/generic/HomeAssistantMQTTImplementationTests.java
  addons/binding/org.openhab.binding.mqtt.generic.test/src/test/java/org/openhab/binding/mqtt/generic/internal/convention/homeassistant/HAConfigurationTests.java
  addons/binding/org.openhab.binding.mqtt.generic/META-INF/MANIFEST.MF
  addons/binding/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/internal/convention/homeassistant/AbstractComponent.java
  addons/binding/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/internal/convention/homeassistant/CChannel.java
  addons/binding/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/internal/convention/homeassistant/CFactory.java
  addons/binding/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/internal/convention/homeassistant/ComponentAlarmControlPanel.java
  addons/binding/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/internal/convention/homeassistant/ComponentBinarySensor.java
  addons/binding/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/internal/convention/homeassistant/ComponentCamera.java
  addons/binding/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/internal/convention/homeassistant/ComponentClimate.java
  addons/binding/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/internal/convention/homeassistant/ComponentCover.java
  addons/binding/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/internal/convention/homeassistant/ComponentFan.java
  addons/binding/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/internal/convention/homeassistant/ComponentLight.java
  addons/binding/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/internal/convention/homeassistant/ComponentLock.java
  addons/binding/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/internal/convention/homeassistant/ComponentSensor.java
  addons/binding/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/internal/convention/homeassistant/ComponentSwitch.java
  addons/binding/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/internal/convention/homeassistant/DiscoverComponents.java
  addons/binding/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/internal/convention/homeassistant/HAConfiguration.java
  addons/binding/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/internal/discovery/HomeAssistantDiscovery.java
  addons/binding/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/internal/handler/HomeAssistantThingHandler.java
  addons/binding/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/internal/handler/HomieThingHandler.java
  addons/binding/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/internal/mapping/AbstractMqttAttributeClass.java
  addons/binding/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/internal/tools/ChildMap.java
  addons/binding/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/internal/tools/DelayedBatchProcessing.java
Labels: mqtt

#2295 [spotify] Spotify Binding initial contribution
  addons/binding/org.openhab.binding.spotify/.classpath
  addons/binding/org.openhab.binding.spotify/.project
  addons/binding/org.openhab.binding.spotify/ESH-INF/binding/binding.xml
  addons/binding/org.openhab.binding.spotify/ESH-INF/thing/thing-types.xml
  addons/binding/org.openhab.binding.spotify/META-INF/MANIFEST.MF
  addons/binding/org.openhab.binding.spotify/NOTICE
  addons/binding/org.openhab.binding.spotify/OSGI-INF/.gitignore
  addons/binding/org.openhab.binding.spotify/README.md
  addons/binding/org.openhab.binding.spotify/build.properties
  addons/binding/org.openhab.binding.spotify/pom.xml
  addons/binding/org.openhab.binding.spotify/src/main/java/org/openhab/binding/spotify/internal/SpotifyAccountHandler.java
  addons/binding/org.openhab.binding.spotify/src/main/java/org/openhab/binding/spotify/internal/SpotifyAuthService.java
  addons/binding/org.openhab.binding.spotify/src/main/java/org/openhab/binding/spotify/internal/SpotifyAuthServlet.java
  addons/binding/org.openhab.binding.spotify/src/main/java/org/openhab/binding/spotify/internal/SpotifyBindingConstants.java
  addons/binding/org.openhab.binding.spotify/src/main/java/org/openhab/binding/spotify/internal/SpotifyBridgeConfiguration.java
  addons/binding/org.openhab.binding.spotify/src/main/java/org/openhab/binding/spotify/internal/SpotifyHandlerFactory.java
  addons/binding/org.openhab.binding.spotify/src/main/java/org/openhab/binding/spotify/internal/api/SpotifyApi.java
  addons/binding/org.openhab.binding.spotify/src/main/java/org/openhab/binding/spotify/internal/api/SpotifyConnector.java
  addons/binding/org.openhab.binding.spotify/src/main/java/org/openhab/binding/spotify/internal/api/exception/SpotifyAuthorizationException.java
  addons/binding/org.openhab.binding.spotify/src/main/java/org/openhab/binding/spotify/internal/api/exception/SpotifyException.java
  addons/binding/org.openhab.binding.spotify/src/main/java/org/openhab/binding/spotify/internal/api/exception/SpotifyTokenExpiredException.java
  addons/binding/org.openhab.binding.spotify/src/main/java/org/openhab/binding/spotify/internal/api/model/Album.java
  addons/binding/org.openhab.binding.spotify/src/main/java/org/openhab/binding/spotify/internal/api/model/Artist.java
  addons/binding/org.openhab.binding.spotify/src/main/java/org/openhab/binding/spotify/internal/api/model/Context.java
  addons/binding/org.openhab.binding.spotify/src/main/java/org/openhab/binding/spotify/internal/api/model/CurrentlyPlayingContext.java
  addons/binding/org.openhab.binding.spotify/src/main/java/org/openhab/binding/spotify/internal/api/model/Device.java
  addons/binding/org.openhab.binding.spotify/src/main/java/org/openhab/binding/spotify/internal/api/model/Devices.java
  addons/binding/org.openhab.binding.spotify/src/main/java/org/openhab/binding/spotify/internal/api/model/ExternalIds.java
  addons/binding/org.openhab.binding.spotify/src/main/java/org/openhab/binding/spotify/internal/api/model/ExternalUrl.java
  addons/binding/org.openhab.binding.spotify/src/main/java/org/openhab/binding/spotify/internal/api/model/Image.java
  addons/binding/org.openhab.binding.spotify/src/main/java/org/openhab/binding/spotify/internal/api/model/Item.java
  addons/binding/org.openhab.binding.spotify/src/main/java/org/openhab/binding/spotify/internal/api/model/Me.java
  addons/binding/org.openhab.binding.spotify/src/main/java/org/openhab/binding/spotify/internal/api/model/ModelUtil.java
  addons/binding/org.openhab.binding.spotify/src/main/java/org/openhab/binding/spotify/internal/api/model/Paging.java
  addons/binding/org.openhab.binding.spotify/src/main/java/org/openhab/binding/spotify/internal/api/model/Playlist.java
  addons/binding/org.openhab.binding.spotify/src/main/java/org/openhab/binding/spotify/internal/api/model/Playlists.java
  addons/binding/org.openhab.binding.spotify/src/main/java/org/openhab/binding/spotify/internal/discovery/SpotifyDeviceDiscoveryService.java
  addons/binding/org.openhab.binding.spotify/src/main/java/org/openhab/binding/spotify/internal/handler/SpotifyBridgeHandler.java
  addons/binding/org.openhab.binding.spotify/src/main/java/org/openhab/binding/spotify/internal/handler/SpotifyDeviceHandler.java
  addons/binding/org.openhab.binding.spotify/src/main/java/org/openhab/binding/spotify/internal/handler/SpotifyDynamicStateDescriptionProvider.java
  addons/binding/org.openhab.binding.spotify/src/main/java/org/openhab/binding/spotify/internal/handler/SpotifyHandleCommands.java
  addons/binding/org.openhab.binding.spotify/templates/index.html
  addons/binding/org.openhab.binding.spotify/templates/player.html
  addons/binding/org.openhab.binding.spotify/web/favicon.ico
  addons/binding/pom.xml
  features/openhab-addons/src/main/feature/feature.xml
Labels: new binding

#5009 [hue] setTransitionTime() not for ON/OFF commands
  addons/binding/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/HueLightHandler.java
Labels: bug
