Repository openhab/openhab-addons, pull requests merged in 2019-01, with the labels that each got.

#4471 [smartmeter] Update readme.md
  addons/binding/org.openhab.binding.smartmeter/README.md
Labels: documentation

#4425 [hueemulation] Mention that groups need a base type
  addons/io/org.openhab.io.hueemulation/README.md
Labels: documentation

#4463 [pentair] Support for Feature circuits 1-8
  addons/binding/org.openhab.binding.pentair/ESH-INF/thing/easytouch.xml
  addons/binding/org.openhab.binding.pentair/README.md
  addons/binding/org.openhab.binding.pentair/src/main/java/org/openhab/binding/pentair/internal/PentairBindingConstants.java
  addons/binding/org.openhab.binding.pentair/src/main/java/org/openhab/binding/pentair/internal/PentairPacketStatus.java
  addons/binding/org.openhab.binding.pentair/src/main/java/org/openhab/binding/pentair/internal/handler/PentairEasyTouchHandler.java
Labels: enhancement

#4501 [ONKYO] Add support for device TX-NR686
  addons/binding/org.openhab.binding.onkyo/ESH-INF/thing/tx-nr686.xml
  addons/binding/org.openhab.binding.onkyo/README.md
  addons/binding/org.openhab.binding.onkyo/src/main/java/org/openhab/binding/onkyo/internal/OnkyoBindingConstants.java
Labels: enhancement

#4449 [modbus] Update README.md
  addons/binding/org.openhab.binding.modbus/README.md
Labels: documentation

#4532 [exec] State default setting for interval
  addons/binding/org.openhab.binding.exec/README.md
Labels: documentation

#4540 [iCloud] Update readme for Mapview usage in applications (Android/iOS)
  addons/binding/org.openhab.binding.icloud/README.md
Labels: documentation

#4561 [onkyo] Add support for Onkyo TX-NR474.
  addons/binding/org.openhab.binding.onkyo/ESH-INF/thing/tx-nr474.xml
  addons/binding/org.openhab.binding.onkyo/README.md
  addons/binding/org.openhab.binding.onkyo/src/main/java/org/openhab/binding/onkyo/internal/OnkyoBindingConstants.java
Labels: enhancement

#4565 [onkyo] Add support for Onkyo TX-NR636.
  addons/binding/org.openhab.binding.onkyo/ESH-INF/thing/tx-nr636.xml
  addons/binding/org.openhab.binding.onkyo/src/main/java/org/openhab/binding/onkyo/internal/OnkyoBindingConstants.java
Labels: enhancement

#4512 [mihome] Added Support for Xiaomi Aqara Smart Wall Socket (86plug)
  addons/binding/org.openhab.binding.mihome/src/main/java/org/openhab/binding/mihome/internal/ModelMapper.java
Labels: enhancement

#4507 [sensebox] [uom] Unit of Measurement Support
  addons/binding/org.openhab.binding.sensebox/ESH-INF/binding/binding.xml
  addons/binding/org.openhab.binding.sensebox/ESH-INF/thing/channels.xml
  addons/binding/org.openhab.binding.sensebox/META-INF/MANIFEST.MF
  addons/binding/org.openhab.binding.sensebox/README.md
  addons/binding/org.openhab.binding.sensebox/src/main/java/org/openhab/binding/sensebox/internal/SenseBoxAPIConnection.java
  addons/binding/org.openhab.binding.sensebox/src/main/java/org/openhab/binding/sensebox/internal/SenseBoxBindingConstants.java
  addons/binding/org.openhab.binding.sensebox/src/main/java/org/openhab/binding/sensebox/internal/SenseBoxHandlerFactory.java
  addons/binding/org.openhab.binding.sensebox/src/main/java/org/openhab/binding/sensebox/internal/handler/SenseBoxHandler.java
Labels: awaiting other PR

#4566 [deconz] adding sensors for pressure and consumption, fixing unit of Power
  addons/binding/org.openhab.binding.deconz/ESH-INF/thing/thing-types.xml
  addons/binding/org.openhab.binding.deconz/README.md
  addons/binding/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/BindingConstants.java
  addons/binding/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/HandlerFactory.java
  addons/binding/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/discovery/ThingDiscoveryService.java
  addons/binding/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/dto/SensorState.java
  addons/binding/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/handler/SensorThingHandler.java
Labels: awaiting other PR, enhancement

#4545 [deconz] Added util channels (e.g. 'battery')
  addons/binding/org.openhab.binding.deconz/ESH-INF/thing/thing-types.xml
  addons/binding/org.openhab.binding.deconz/README.md
  addons/binding/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/BindingConstants.java
  addons/binding/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/dto/SensorState.java
  addons/binding/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/handler/SensorThingHandler.java
Labels: enhancement

#2659 [elerotransmitterstick] Elero Transmitter Stick Binding initial contribution
  addons/binding/org.openhab.binding.elerotransmitterstick/.classpath
  addons/binding/org.openhab.binding.elerotransmitterstick/.project
  addons/binding/org.openhab.binding.elerotransmitterstick/ESH-INF/binding/binding.xml
  addons/binding/org.openhab.binding.elerotransmitterstick/ESH-INF/thing/thing-types.xml
  addons/binding/org.openhab.binding.elerotransmitterstick/META-INF/MANIFEST.MF
  addons/binding/org.openhab.binding.elerotransmitterstick/OSGI-INF/.gitignore
  addons/binding/org.openhab.binding.elerotransmitterstick/README.md
  addons/binding/org.openhab.binding.elerotransmitterstick/about.html
  addons/binding/org.openhab.binding.elerotransmitterstick/build.properties
  addons/binding/org.openhab.binding.elerotransmitterstick/pom.xml
  addons/binding/org.openhab.binding.elerotransmitterstick/src/main/java/org/openhab/binding/elerotransmitterstick/internal/EleroTransmitterStickBindingConstants.java
  addons/binding/org.openhab.binding.elerotransmitterstick/src/main/java/org/openhab/binding/elerotransmitterstick/internal/EleroTransmitterStickHandlerFactory.java
  addons/binding/org.openhab.binding.elerotransmitterstick/src/main/java/org/openhab/binding/elerotransmitterstick/internal/config/EleroChannelConfig.java
  addons/binding/org.openhab.binding.elerotransmitterstick/src/main/java/org/openhab/binding/elerotransmitterstick/internal/config/EleroTransmitterStickConfig.java
  addons/binding/org.openhab.binding.elerotransmitterstick/src/main/java/org/openhab/binding/elerotransmitterstick/internal/discovery/EleroChannelDiscoveryService.java
  addons/binding/org.openhab.binding.elerotransmitterstick/src/main/java/org/openhab/binding/elerotransmitterstick/internal/handler/EleroChannelHandler.java
  addons/binding/org.openhab.binding.elerotransmitterstick/src/main/java/org/openhab/binding/elerotransmitterstick/internal/handler/EleroTransmitterStickHandler.java
  addons/binding/org.openhab.binding.elerotransmitterstick/src/main/java/org/openhab/binding/elerotransmitterstick/internal/handler/StatusListener.java
  addons/binding/org.openhab.binding.elerotransmitterstick/src/main/java/org/openhab/binding/elerotransmitterstick/internal/stick/Command.java
  addons/binding/org.openhab.binding.elerotransmitterstick/src/main/java/org/openhab/binding/elerotransmitterstick/internal/stick/CommandPacket.java
  addons/binding/org.openhab.binding.elerotransmitterstick/src/main/java/org/openhab/binding/elerotransmitterstick/internal/stick/CommandType.java
  addons/binding/org.openhab.binding.elerotransmitterstick/src/main/java/org/openhab/binding/elerotransmitterstick/internal/stick/CommandUtil.java
  addons/binding/org.openhab.binding.elerotransmitterstick/src/main/java/org/openhab/binding/elerotransmitterstick/internal/stick/ConnectException.java
  addons/binding/org.openhab.binding.elerotransmitterstick/src/main/java/org/openhab/binding/elerotransmitterstick/internal/stick/DelayedCommand.java
  addons/binding/org.openhab.binding.elerotransmitterstick/src/main/java/org/openhab/binding/elerotransmitterstick/internal/stick/Response.java
  addons/binding/org.openhab.binding.elerotransmitterstick/src/main/java/org/openhab/binding/elerotransmitterstick/internal/stick/ResponseStatus.java
  addons/binding/org.openhab.binding.elerotransmitterstick/src/main/java/org/openhab/binding/elerotransmitterstick/internal/stick/ResponseUtil.java
  addons/binding/org.openhab.binding.elerotransmitterstick/src/main/java/org/openhab/binding/elerotransmitterstick/internal/stick/SerialConnection.java
  addons/binding/org.openhab.binding.elerotransmitterstick/src/main/java/org/openhab/binding/elerotransmitterstick/internal/stick/TimedCommand.java
  addons/binding/org.openhab.binding.elerotransmitterstick/src/main/java/org/openhab/binding/elerotransmitterstick/internal/stick/TransmitterStick.java
  addons/binding/pom.xml
  features/openhab-addons/src/main/feature/feature.xml
Labels: new binding

#4535 [homekit] Update beowulfe/HAP-Java library to version 1.1.4
  addons/io/org.openhab.io.homekit/META-INF/MANIFEST.MF
  addons/io/org.openhab.io.homekit/build.properties
  addons/io/org.openhab.io.homekit/lib/com.beowulfe.hap.hap-1.1.3.jar
  addons/io/org.openhab.io.homekit/lib/com.beowulfe.hap.hap-1.1.4.jar
Labels: homekit

#4601 [smartmeter] Added Landis+Gyr E650 as working hardware
  addons/binding/org.openhab.binding.smartmeter/README.md
Labels: documentation

#4612 [max] Improve German translations slightly, resolve ambiguities
  addons/binding/org.openhab.binding.max/ESH-INF/i18n/max_de.properties
Labels: translation

#4635 [miio] Reflect deviceId being required as in the actual implementation
  addons/binding/org.openhab.binding.miio/README.md
Labels: documentation

#4508 [neato] Updated the readme with the correct channel configuration for items
  addons/binding/org.openhab.binding.neato/README.md
Labels: documentation

#4111 [loxone] Removed Guava dependency
  addons/binding/org.openhab.binding.loxone/META-INF/MANIFEST.MF
  addons/binding/org.openhab.binding.loxone/src/main/java/org/openhab/binding/loxone/internal/LoxoneHandlerFactory.java
Labels: awaiting other PR

#4659 [mqtt] Fix the description of the secure parameter
  addons/binding/org.openhab.binding.mqtt/README.md
Labels: documentation

#4666 [hue] Updated README with fixed example and some clarifications
  addons/binding/org.openhab.binding.hue/README.md
Labels: documentation

#4665 [bosesoundtouch] Fixed an issue with async. websocket requests
  addons/binding/org.openhab.binding.bosesoundtouch/src/main/java/org/openhab/binding/bosesoundtouch/internal/CommandExecutor.java
Labels: bug

#3382 [zoneminder] Use DS annotations, fix static code analysis findings
  addons/binding/org.openhab.binding.zoneminder/META-INF/MANIFEST.MF
  addons/binding/org.openhab.binding.zoneminder/OSGI-INF/.gitignore
  addons/binding/org.openhab.binding.zoneminder/OSGI-INF/ZoneMinderHandlerFactory.xml
  addons/binding/org.openhab.binding.zoneminder/src/main/java/org/openhab/binding/zoneminder/ZoneMinderConstants.java
  addons/binding/org.openhab.binding.zoneminder/src/main/java/org/openhab/binding/zoneminder/handler/ZoneMinderBaseThingHandler.java
  addons/binding/org.openhab.binding.zoneminder/src/main/java/org/openhab/binding/zoneminder/handler/ZoneMinderHandler.java
  addons/binding/org.openhab.binding.zoneminder/src/main/java/org/openhab/binding/zoneminder/handler/ZoneMinderServerBridgeHandler.java
  addons/binding/org.openhab.binding.zoneminder/src/main/java/org/openhab/binding/zoneminder/handler/ZoneMinderThingMonitorHandler.java
  addons/binding/org.openhab.binding.zoneminder/src/main/java/org/openhab/binding/zoneminder/handler/ZoneMinderThingType.java
  addons/binding/org.openhab.binding.zoneminder/src/main/java/org/openhab/binding/zoneminder/internal/ZoneMinderHandlerFactory.java
  addons/binding/org.openhab.binding.zoneminder/src/main/java/org/openhab/binding/zoneminder/internal/config/ZoneMinderBridgeServerConfig.java
  addons/binding/org.openhab.binding.zoneminder/src/main/java/org/openhab/binding/zoneminder/internal/config/ZoneMinderConfig.java
  addons/binding/org.openhab.binding.zoneminder/src/main/java/org/openhab/binding/zoneminder/internal/discovery/ZoneMinderDiscoveryService.java
Labels: awaiting other PR

#4634 [airquality] Added how to find the stationId to the documentation
  addons/binding/org.openhab.binding.airquality/README.md
Labels: documentation

#3933 [exec] Made constants and handler packages internal
  addons/binding/org.openhab.binding.exec/META-INF/MANIFEST.MF
  addons/binding/org.openhab.binding.exec/src/main/java/org/openhab/binding/exec/internal/ExecBindingConstants.java
  addons/binding/org.openhab.binding.exec/src/main/java/org/openhab/binding/exec/internal/ExecHandlerFactory.java
  addons/binding/org.openhab.binding.exec/src/main/java/org/openhab/binding/exec/internal/handler/ExecHandler.java
Labels: awaiting other PR

#3977 [mcp23017] Made constants and handler packages internal
  addons/binding/org.openhab.binding.mcp23017/META-INF/MANIFEST.MF
  addons/binding/org.openhab.binding.mcp23017/src/main/java/org/openhab/binding/mcp23017/internal/Mcp23017BindingConstants.java
  addons/binding/org.openhab.binding.mcp23017/src/main/java/org/openhab/binding/mcp23017/internal/Mcp23017HandlerFactory.java
  addons/binding/org.openhab.binding.mcp23017/src/main/java/org/openhab/binding/mcp23017/internal/PinMapper.java
  addons/binding/org.openhab.binding.mcp23017/src/main/java/org/openhab/binding/mcp23017/internal/handler/Mcp23017Handler.java
  addons/binding/org.openhab.binding.mcp23017/src/main/java/org/openhab/binding/mcp23017/internal/handler/Mcp23017PinStateHolder.java
Labels: awaiting other PR

#4042 [rfxcom] Made constants and handler packages internal
  addons/binding/org.openhab.binding.rfxcom.test/META-INF/MANIFEST.MF
  addons/binding/org.openhab.binding.rfxcom.test/src/test/java/org/openhab/binding/rfxcom/internal/messages/RFXComDateTimeMessageTest.java
  addons/binding/org.openhab.binding.rfxcom.test/src/test/java/org/openhab/binding/rfxcom/internal/messages/RFXComLighting4MessageTest.java
  addons/binding/org.openhab.binding.rfxcom.test/src/test/java/org/openhab/binding/rfxcom/internal/messages/RFXComLighting5MessageTest.java
  addons/binding/org.openhab.binding.rfxcom/META-INF/MANIFEST.MF
  addons/binding/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/RFXComBindingConstants.java
  addons/binding/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/RFXComHandlerFactory.java
  addons/binding/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/discovery/RFXComBridgeDiscovery.java
  addons/binding/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/discovery/RFXComDeviceDiscoveryService.java
  addons/binding/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/handler/RFXComBridgeHandler.java
  addons/binding/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/handler/RFXComHandler.java
  addons/binding/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/messages/RFXComBBQTemperatureMessage.java
  addons/binding/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/messages/RFXComBatteryDeviceMessage.java
  addons/binding/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/messages/RFXComBlinds1Message.java
  addons/binding/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/messages/RFXComChimeMessage.java
  addons/binding/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/messages/RFXComCurrentEnergyMessage.java
  addons/binding/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/messages/RFXComCurrentMessage.java
  addons/binding/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/messages/RFXComCurtain1Message.java
  addons/binding/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/messages/RFXComDateTimeMessage.java
  addons/binding/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/messages/RFXComDeviceMessageImpl.java
  addons/binding/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/messages/RFXComEnergyMessage.java
  addons/binding/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/messages/RFXComHomeConfortMessage.java
  addons/binding/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/messages/RFXComHumidityMessage.java
  addons/binding/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/messages/RFXComLighting1Message.java
  addons/binding/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/messages/RFXComLighting2Message.java
  addons/binding/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/messages/RFXComLighting4Message.java
  addons/binding/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/messages/RFXComLighting5Message.java
  addons/binding/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/messages/RFXComLighting6Message.java
  addons/binding/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/messages/RFXComRainMessage.java
  addons/binding/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/messages/RFXComRfyMessage.java
  addons/binding/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/messages/RFXComSecurity1Message.java
  addons/binding/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/messages/RFXComSecurity2Message.java
  addons/binding/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/messages/RFXComTemperatureHumidityBarometricMessage.java
  addons/binding/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/messages/RFXComTemperatureHumidityMessage.java
  addons/binding/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/messages/RFXComTemperatureMessage.java
  addons/binding/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/messages/RFXComTemperatureRainMessage.java
  addons/binding/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/messages/RFXComThermostat1Message.java
  addons/binding/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/messages/RFXComThermostat3Message.java
  addons/binding/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/messages/RFXComUVMessage.java
  addons/binding/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/messages/RFXComUndecodedRFMessage.java
  addons/binding/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/messages/RFXComWindMessage.java
Labels: awaiting other PR

#4048 [knx] Made constants and handler packages internal
  addons/binding/org.openhab.binding.knx.test/META-INF/MANIFEST.MF
  addons/binding/org.openhab.binding.knx/META-INF/MANIFEST.MF
  addons/binding/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/KNXBindingConstants.java
  addons/binding/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/KNXTypeMapper.java
  addons/binding/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/channel/AbstractSpec.java
  addons/binding/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/channel/KNXChannelType.java
  addons/binding/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/channel/ListenSpecImpl.java
  addons/binding/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/channel/ReadRequestSpecImpl.java
  addons/binding/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/channel/ReadResponseSpecImpl.java
  addons/binding/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/channel/TypeColor.java
  addons/binding/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/channel/TypeContact.java
  addons/binding/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/channel/TypeDateTime.java
  addons/binding/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/channel/TypeDimmer.java
  addons/binding/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/channel/TypeNumber.java
  addons/binding/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/channel/TypeRollershutter.java
  addons/binding/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/channel/TypeString.java
  addons/binding/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/channel/TypeSwitch.java
  addons/binding/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/channel/WriteSpecImpl.java
  addons/binding/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/client/AbstractKNXClient.java
  addons/binding/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/client/DeviceInfoClient.java
  addons/binding/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/client/DeviceInfoClientImpl.java
  addons/binding/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/client/DeviceInspector.java
  addons/binding/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/client/IPClient.java
  addons/binding/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/client/InboundSpec.java
  addons/binding/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/client/KNXClient.java
  addons/binding/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/client/NoOpClient.java
  addons/binding/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/client/OutboundSpec.java
  addons/binding/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/client/SerialClient.java
  addons/binding/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/client/StatusUpdateCallback.java
  addons/binding/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/config/BridgeConfiguration.java
  addons/binding/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/dpt/KNXCoreTypeMapper.java
  addons/binding/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/factory/KNXHandlerFactory.java
  addons/binding/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/handler/AbstractKNXThingHandler.java
  addons/binding/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/handler/DeviceThingHandler.java
  addons/binding/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/handler/GroupAddressListener.java
  addons/binding/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/handler/IPBridgeThingHandler.java
  addons/binding/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/handler/KNXBridgeBaseThingHandler.java
  addons/binding/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/handler/SerialBridgeThingHandler.java
  addons/binding/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/profiles/KNXProfileAdvisor.java
Labels: awaiting other PR, knx

#4725 Corrected startRoutine Item type
  addons/binding/org.openhab.binding.amazonechocontrol/README.md
Labels: documentation

#4726 [amazonechocontrol] Fix tiny spelling mistake
  addons/binding/org.openhab.binding.amazonechocontrol/README.md
Labels: documentation

#4539 [plclogo] Added documentation for pulse - thing
  addons/binding/org.openhab.binding.plclogo/README.md
Labels: documentation

#4504 [amazondashbutton] Update README.md
  addons/binding/org.openhab.binding.amazondashbutton/README.md
Labels: documentation

#4660 [hue] Add support for TransitionTime
  addons/binding/org.openhab.binding.hue.test/src/test/java/org/openhab/binding/hue/internal/handler/HueLightHandlerTest.java
  addons/binding/org.openhab.binding.hue/ESH-INF/i18n/hue.properties
  addons/binding/org.openhab.binding.hue/ESH-INF/thing/ColorLight.xml
  addons/binding/org.openhab.binding.hue/ESH-INF/thing/ColorTemperatureLight.xml
  addons/binding/org.openhab.binding.hue/ESH-INF/thing/DimmableLight.xml
  addons/binding/org.openhab.binding.hue/ESH-INF/thing/DimmablePlug.xml
  addons/binding/org.openhab.binding.hue/ESH-INF/thing/ExtendedColorLight.xml
  addons/binding/org.openhab.binding.hue/META-INF/MANIFEST.MF
  addons/binding/org.openhab.binding.hue/README.md
  addons/binding/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/FullLight.java
  addons/binding/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/HueBindingConstants.java
  addons/binding/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/StateUpdate.java
  addons/binding/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/action/LightActions.java
  addons/binding/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/HueLightHandler.java
Labels: enhancement

#4453 [yeelight] Add basic support for yeelight desklamp
  addons/binding/org.openhab.binding.yeelight/ESH-INF/thing/desklamp.xml
  addons/binding/org.openhab.binding.yeelight/src/main/java/org/openhab/binding/yeelight/internal/YeelightBindingConstants.java
  addons/binding/org.openhab.binding.yeelight/src/main/java/org/openhab/binding/yeelight/internal/YeelightHandlerFactory.java
  addons/binding/org.openhab.binding.yeelight/src/main/java/org/openhab/binding/yeelight/internal/discovery/YeelightDiscoveryService.java
  addons/binding/org.openhab.binding.yeelight/src/main/java/org/openhab/binding/yeelight/internal/handler/YeelightHandlerBase.java
  addons/binding/org.openhab.binding.yeelight/src/main/java/org/openhab/binding/yeelight/internal/lib/device/DesklampDevice.java
  addons/binding/org.openhab.binding.yeelight/src/main/java/org/openhab/binding/yeelight/internal/lib/device/DeviceFactory.java
  addons/binding/org.openhab.binding.yeelight/src/main/java/org/openhab/binding/yeelight/internal/lib/device/MethodFactory.java
  addons/binding/org.openhab.binding.yeelight/src/main/java/org/openhab/binding/yeelight/internal/lib/enums/DeviceType.java
  addons/binding/org.openhab.binding.yeelight/src/main/java/org/openhab/binding/yeelight/internal/lib/services/DeviceManager.java
Labels: enhancement

#4749 [MQTT Generic]Update documentation
  addons/binding/org.openhab.binding.mqtt.generic/README.md
Labels: documentation

#4727 [solaredge] Update README.md
  addons/binding/org.openhab.binding.solaredge/README.md
Labels: documentation

#4521 [homekit] Added support for contact sensors
  addons/io/org.openhab.io.homekit/README.md
  addons/io/org.openhab.io.homekit/build.properties
  addons/io/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitDeviceType.java
  addons/io/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitAccessoryFactory.java
  addons/io/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitContactSensorImpl.java
Labels: homekit

#4768 [hue] improved readme
  addons/binding/org.openhab.binding.hue/README.md
Labels: documentation

#4766 [MQTT Generic] update documentation
  addons/binding/org.openhab.binding.mqtt.generic/README.md
Labels: documentation
