Repository openhab/openhab-addons, pull requests merged in 2020-02, with the labels that each got.

#6893 [rfxcom] LIVOLO_APPLIANCE fix
  bundles/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/messages/RFXComLighting5Message.java
Labels: bug

#6947 [airquality] Fix wrong channel name in documentation
  bundles/org.openhab.binding.airquality/README.md
Labels: documentation

#6445 [wemo] Add new devices and update Readme
  bundles/org.openhab.binding.wemo/README.md
  bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/WemoBindingConstants.java
  bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/WemoHandlerFactory.java
  bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/discovery/WemoDiscoveryParticipant.java
  bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/handler/WemoCrockpotHandler.java
  bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/handler/WemoHolmesHandler.java
  bundles/org.openhab.binding.wemo/src/main/resources/ESH-INF/thing/thing-types.xml
Labels: enhancement

#6872 [freebox] Adding Fiber optic and support of Delta bridge
  bundles/org.openhab.binding.freebox/README.md
  bundles/org.openhab.binding.freebox/src/main/java/org/openhab/binding/freebox/internal/FreeboxBindingConstants.java
  bundles/org.openhab.binding.freebox/src/main/java/org/openhab/binding/freebox/internal/api/FreeboxApiManager.java
  bundles/org.openhab.binding.freebox/src/main/java/org/openhab/binding/freebox/internal/api/model/FreeboxFtthStatus.java
  bundles/org.openhab.binding.freebox/src/main/java/org/openhab/binding/freebox/internal/api/model/FreeboxFtthStatusResponse.java
  bundles/org.openhab.binding.freebox/src/main/java/org/openhab/binding/freebox/internal/handler/FreeboxHandler.java
  bundles/org.openhab.binding.freebox/src/main/resources/ESH-INF/binding/binding.xml
  bundles/org.openhab.binding.freebox/src/main/resources/ESH-INF/thing/thing-types.xml
Labels: enhancement

#6764 [shelly]Enhancements and bug fixes
  bundles/org.openhab.binding.shelly/README.md
  bundles/org.openhab.binding.shelly/doc/DEVNOTES - API JSON Samples.md
  bundles/org.openhab.binding.shelly/pom.xml
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/ShellyBindingConstants.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api/ShellyApiJsonDTO.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api/ShellyDeviceProfile.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api/ShellyHttpApi.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/coap/ShellyCoapHandler.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/coap/ShellyCoapJSonDTO.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/config/ShellyThingConfiguration.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/discovery/ShellyThingCreator.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/handler/ShellyBaseHandler.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/handler/ShellyColorUtils.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/handler/ShellyComponents.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/handler/ShellyLightHandler.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/handler/ShellyProtectedHandler.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/handler/ShellyRelayHandler.java
  bundles/org.openhab.binding.shelly/src/main/resources/ESH-INF/config/config.xml
  bundles/org.openhab.binding.shelly/src/main/resources/ESH-INF/i18n/shelly.properties
  bundles/org.openhab.binding.shelly/src/main/resources/ESH-INF/i18n/shelly_de.properties
  bundles/org.openhab.binding.shelly/src/main/resources/ESH-INF/thing/channels.xml
  bundles/org.openhab.binding.shelly/src/main/resources/ESH-INF/thing/lights.xml
  bundles/org.openhab.binding.shelly/src/main/resources/ESH-INF/thing/relay.xml
Labels: bug, enhancement

#6931 [opengarage] Fixes README.md with correct config value
  bundles/org.openhab.binding.opengarage/README.md
Labels: documentation

#6909 [hueemulation] Fixes to prevent Alexa errors when using voice commands and the app (#6690)
  bundles/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/StateUtils.java
  bundles/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/dto/HueLightEntry.java
  bundles/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/dto/HueStateBulb.java
  bundles/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/dto/HueStateColorBulb.java
  bundles/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/rest/LightsAndGroups.java
  bundles/org.openhab.io.hueemulation/src/test/java/org/openhab/io/hueemulation/internal/rest/LightsAndGroupsTests.java
Labels: bug

#6991 [darksky] Fixed examples of alert channels
  bundles/org.openhab.binding.darksky/README.md
  bundles/org.openhab.binding.darksky/src/main/java/org/openhab/binding/darksky/internal/handler/DarkSkyWeatherAndForecastHandler.java
Labels: documentation

#6851 [network] Issue 6495
  bundles/org.openhab.binding.network/README.md
  bundles/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/PresenceDetection.java
  bundles/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/SpeedTestConfiguration.java
  bundles/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/handler/SpeedTestHandler.java
  bundles/org.openhab.binding.network/src/main/resources/ESH-INF/thing/thing-types.xml
Labels: bug

#6977 [tradfri] Added basic support for IKEA blinds FYRTUR and KADRILJ
  bundles/org.openhab.binding.tradfri/README.md
  bundles/org.openhab.binding.tradfri/pom.xml
  bundles/org.openhab.binding.tradfri/src/main/java/org/openhab/binding/tradfri/internal/DeviceUpdateListener.java
  bundles/org.openhab.binding.tradfri/src/main/java/org/openhab/binding/tradfri/internal/TradfriBindingConstants.java
  bundles/org.openhab.binding.tradfri/src/main/java/org/openhab/binding/tradfri/internal/TradfriColor.java
  bundles/org.openhab.binding.tradfri/src/main/java/org/openhab/binding/tradfri/internal/TradfriHandlerFactory.java
  bundles/org.openhab.binding.tradfri/src/main/java/org/openhab/binding/tradfri/internal/discovery/TradfriDiscoveryParticipant.java
  bundles/org.openhab.binding.tradfri/src/main/java/org/openhab/binding/tradfri/internal/discovery/TradfriDiscoveryService.java
  bundles/org.openhab.binding.tradfri/src/main/java/org/openhab/binding/tradfri/internal/handler/TradfriBlindHandler.java
  bundles/org.openhab.binding.tradfri/src/main/java/org/openhab/binding/tradfri/internal/handler/TradfriControllerHandler.java
  bundles/org.openhab.binding.tradfri/src/main/java/org/openhab/binding/tradfri/internal/handler/TradfriGatewayHandler.java
  bundles/org.openhab.binding.tradfri/src/main/java/org/openhab/binding/tradfri/internal/handler/TradfriSensorHandler.java
  bundles/org.openhab.binding.tradfri/src/main/java/org/openhab/binding/tradfri/internal/model/TradfriBlindData.java
  bundles/org.openhab.binding.tradfri/src/main/java/org/openhab/binding/tradfri/internal/model/TradfriDeviceData.java
  bundles/org.openhab.binding.tradfri/src/main/resources/ESH-INF/config/config.xml
  bundles/org.openhab.binding.tradfri/src/main/resources/ESH-INF/i18n/tradfri_de.properties
  bundles/org.openhab.binding.tradfri/src/main/resources/ESH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.tradfri/src/test/java/org/openhab/binding/tradfri/internal/TradfriColorTest.java
  bundles/org.openhab.binding.tradfri/src/test/java/org/openhab/binding/tradfri/internal/discovery/TradfriDiscoveryServiceTest.java
  bundles/org.openhab.binding.tradfri/src/test/java/org/openhab/binding/tradfri/internal/model/TradfriVersionTest.java
Labels: enhancement

#6986 [infrastructure] exclude feature-templates from spotless formatter
  pom.xml
Labels: infrastructure

#6877 [modbus] Fix for data things not initializing properly in some cases.
  bundles/org.openhab.binding.modbus/src/main/java/org/openhab/binding/modbus/internal/handler/ModbusPollerThingHandlerImpl.java
Labels: bug

#6904 [JsonPath transform] Improve/clarify README
  bundles/org.openhab.transform.jsonpath/README.md
Labels: documentation

#6568 [miio] Add support for Air Quality Monitor S1 (cgllc.airmonitor.s1)
  bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/MiIoCommand.java
  bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/MiIoDevices.java
  bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/basic/DeviceMapping.java
  bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/handler/MiIoBasicHandler.java
  bundles/org.openhab.binding.miio/src/main/resources/ESH-INF/thing/commonChannels.xml
  bundles/org.openhab.binding.miio/src/main/resources/database/cgllc.airmonitor.b1.json
  bundles/org.openhab.binding.miio/src/main/resources/database/cgllc.airmonitor.s1.json
  bundles/org.openhab.binding.miio/src/main/resources/database/zhimi.airmonitor.v1.json
Labels: enhancement

#7028 [tplinksmarthome] fix dimmer not turning on via brightness value
  bundles/org.openhab.binding.tplinksmarthome/src/main/java/org/openhab/binding/tplinksmarthome/internal/device/DimmerDevice.java
  bundles/org.openhab.binding.tplinksmarthome/src/test/java/org/openhab/binding/tplinksmarthome/internal/device/DimmerDeviceTest.java
Labels: bug

#6063 [pjlinkdevice] Improvement: Projector lamp states as channels
  bundles/org.openhab.binding.pjlinkdevice/README.md
  bundles/org.openhab.binding.pjlinkdevice/src/main/java/org/openhab/binding/pjlinkdevice/internal/PJLinkDeviceBindingConstants.java
  bundles/org.openhab.binding.pjlinkdevice/src/main/java/org/openhab/binding/pjlinkdevice/internal/PJLinkDeviceConfiguration.java
  bundles/org.openhab.binding.pjlinkdevice/src/main/java/org/openhab/binding/pjlinkdevice/internal/PJLinkDeviceHandler.java
  bundles/org.openhab.binding.pjlinkdevice/src/main/java/org/openhab/binding/pjlinkdevice/internal/device/PJLinkDevice.java
  bundles/org.openhab.binding.pjlinkdevice/src/main/java/org/openhab/binding/pjlinkdevice/internal/device/command/CacheException.java
  bundles/org.openhab.binding.pjlinkdevice/src/main/java/org/openhab/binding/pjlinkdevice/internal/device/command/CachedCommand.java
  bundles/org.openhab.binding.pjlinkdevice/src/main/java/org/openhab/binding/pjlinkdevice/internal/device/command/lampstatus/LampStatesCommand.java
  bundles/org.openhab.binding.pjlinkdevice/src/main/java/org/openhab/binding/pjlinkdevice/internal/device/command/lampstatus/LampStatesRequest.java
  bundles/org.openhab.binding.pjlinkdevice/src/main/java/org/openhab/binding/pjlinkdevice/internal/device/command/lampstatus/LampStatesResponse.java
  bundles/org.openhab.binding.pjlinkdevice/src/main/java/org/openhab/binding/pjlinkdevice/internal/discovery/AbstractDiscoveryParticipant.java
  bundles/org.openhab.binding.pjlinkdevice/src/main/resources/ESH-INF/thing/thing-types.xml
Labels: cre, enhancement

#6051 [exec] Update README.md
  bundles/org.openhab.binding.exec/README.md
Labels: documentation

#7037 update Telegram binding docs
  bundles/org.openhab.binding.telegram/README.md
Labels: documentation

#6521 [enocean] Added support for SIG-Messages (battery level indication)
  bundles/org.openhab.binding.enocean/README.md
  bundles/org.openhab.binding.enocean/src/main/java/org/openhab/binding/enocean/internal/config/EnOceanBaseConfig.java
  bundles/org.openhab.binding.enocean/src/main/java/org/openhab/binding/enocean/internal/eep/Base/_SIGMessage.java
  bundles/org.openhab.binding.enocean/src/main/java/org/openhab/binding/enocean/internal/eep/D0/D0_06.java
  bundles/org.openhab.binding.enocean/src/main/java/org/openhab/binding/enocean/internal/eep/EEPFactory.java
  bundles/org.openhab.binding.enocean/src/main/java/org/openhab/binding/enocean/internal/eep/EEPType.java
  bundles/org.openhab.binding.enocean/src/main/java/org/openhab/binding/enocean/internal/handler/EnOceanBaseSensorHandler.java
  bundles/org.openhab.binding.enocean/src/main/java/org/openhab/binding/enocean/internal/messages/ERP1Message.java
  bundles/org.openhab.binding.enocean/src/main/resources/ESH-INF/thing/Contact.xml
  bundles/org.openhab.binding.enocean/src/main/resources/ESH-INF/thing/LightSensor.xml
  bundles/org.openhab.binding.enocean/src/main/resources/ESH-INF/thing/LightTemperatureOccupancySensor.xml
  bundles/org.openhab.binding.enocean/src/main/resources/ESH-INF/thing/MechanicalHandle.xml
  bundles/org.openhab.binding.enocean/src/main/resources/ESH-INF/thing/OccupancySensor.xml
  bundles/org.openhab.binding.enocean/src/main/resources/ESH-INF/thing/TemperatureHumiditySensor.xml
  bundles/org.openhab.binding.enocean/src/main/resources/ESH-INF/thing/TemperatureSensor.xml
Labels: cre, enhancement

#6998 [innogysmarthome][doc] update documentation for manually configured Bridge
  bundles/org.openhab.binding.innogysmarthome/README.md
Labels: documentation

#7049 [exec] read whitelist on startup
  bundles/org.openhab.binding.exec/src/main/java/org/openhab/binding/exec/internal/ExecWhitelistWatchService.java
  bundles/org.openhab.transform.exec/src/main/java/org/openhab/transform/exec/internal/ExecTransformationWhitelistWatchService.java
Labels: bug

#7059 [exec] fix loggers for whitelist-service
  bundles/org.openhab.binding.exec/src/main/java/org/openhab/binding/exec/internal/ExecWhitelistWatchService.java
  bundles/org.openhab.transform.exec/src/main/java/org/openhab/transform/exec/internal/ExecTransformationWhitelistWatchService.java
Labels: bug

#7050 [onewire] fix updating presence channel
  bundles/org.openhab.binding.onewire/src/main/java/org/openhab/binding/onewire/internal/handler/OwBaseThingHandler.java
Labels: bug

#7027 [satel] Event log improvements
  bundles/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/command/ReadEventCommand.java
  bundles/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/handler/SatelEventLogHandler.java
Labels: enhancement
