Repository openhab/openhab-addons, pull requests merged in 2020-04, with the labels that each got.

#7253 [bluetooth] Fix for AM43 and Airthings devices not being discovered.
  bundles/org.openhab.binding.bluetooth.am43/README.md
  features/openhab-addons/src/main/resources/footer.xml
Labels: bug

#7267 [pulseaudio] Fix documentation to use 'host' instead of 'ipAddress'
  bundles/org.openhab.binding.pulseaudio/README.md
Labels: documentation

#7257 [checkstyle] Treat packages containing .dto. the same way as java classes ending in DTO
  tools/static-code-analysis/checkstyle/suppressions.xml
Labels: infrastructure

#7272 [rfxcom] EOF fix
  bundles/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/connector/RFXComStreamReader.java
Labels: bug

#7251 [insteon] add console commands to help with troubleshooting
  bundles/org.openhab.binding.insteon/README.md
  bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/InsteonBinding.java
  bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/InsteonHandlerFactory.java
  bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/command/InsteonCommandExtension.java
  bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/driver/Port.java
  bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/handler/InsteonDeviceHandler.java
  bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/handler/InsteonNetworkHandler.java
Labels: enhancement

#7268 [Jeelink] Declaration of Bridges in Items Files
  bundles/org.openhab.binding.jeelink/README.md
Labels: documentation

#5634 [etherrain] EtherRain Binding initial contribution
  CODEOWNERS
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.etherrain/.classpath
  bundles/org.openhab.binding.etherrain/.project
  bundles/org.openhab.binding.etherrain/NOTICE
  bundles/org.openhab.binding.etherrain/README.md
  bundles/org.openhab.binding.etherrain/pom.xml
  bundles/org.openhab.binding.etherrain/src/main/feature/feature.xml
  bundles/org.openhab.binding.etherrain/src/main/java/org/openhab/binding/etherrain/internal/EtherRainBindingConstants.java
  bundles/org.openhab.binding.etherrain/src/main/java/org/openhab/binding/etherrain/internal/EtherRainException.java
  bundles/org.openhab.binding.etherrain/src/main/java/org/openhab/binding/etherrain/internal/EtherRainHandlerFactory.java
  bundles/org.openhab.binding.etherrain/src/main/java/org/openhab/binding/etherrain/internal/api/EtherRainCommandResult.java
  bundles/org.openhab.binding.etherrain/src/main/java/org/openhab/binding/etherrain/internal/api/EtherRainCommandStatus.java
  bundles/org.openhab.binding.etherrain/src/main/java/org/openhab/binding/etherrain/internal/api/EtherRainCommunication.java
  bundles/org.openhab.binding.etherrain/src/main/java/org/openhab/binding/etherrain/internal/api/EtherRainOperatingStatus.java
  bundles/org.openhab.binding.etherrain/src/main/java/org/openhab/binding/etherrain/internal/api/EtherRainStatusResponse.java
  bundles/org.openhab.binding.etherrain/src/main/java/org/openhab/binding/etherrain/internal/api/EtherRainUdpResponse.java
  bundles/org.openhab.binding.etherrain/src/main/java/org/openhab/binding/etherrain/internal/config/EtherRainConfiguration.java
  bundles/org.openhab.binding.etherrain/src/main/java/org/openhab/binding/etherrain/internal/discovery/EtherrainDiscoveryService.java
  bundles/org.openhab.binding.etherrain/src/main/java/org/openhab/binding/etherrain/internal/handler/EtherRainHandler.java
  bundles/org.openhab.binding.etherrain/src/main/resources/ESH-INF/binding/binding.xml
  bundles/org.openhab.binding.etherrain/src/main/resources/ESH-INF/thing/thing-types.xml
  bundles/pom.xml
Labels: new binding

#7129 [bluetooth] Refactor and unify BluetoothAdapter implementation logic
  bundles/org.openhab.binding.bluetooth.bluegiga/src/main/java/org/openhab/binding/bluetooth/bluegiga/BlueGigaBluetoothDevice.java
  bundles/org.openhab.binding.bluetooth.bluegiga/src/main/java/org/openhab/binding/bluetooth/bluegiga/handler/BlueGigaBridgeHandler.java
  bundles/org.openhab.binding.bluetooth.bluegiga/src/main/java/org/openhab/binding/bluetooth/bluegiga/internal/BlueGigaConfiguration.java
  bundles/org.openhab.binding.bluetooth.bluegiga/src/main/resources/ESH-INF/thing/bluegiga.xml
  bundles/org.openhab.binding.bluetooth.bluez/src/main/java/org/openhab/binding/bluetooth/bluez/BlueZBluetoothDevice.java
  bundles/org.openhab.binding.bluetooth.bluez/src/main/java/org/openhab/binding/bluetooth/bluez/handler/BlueZAdapterConfiguration.java
  bundles/org.openhab.binding.bluetooth.bluez/src/main/java/org/openhab/binding/bluetooth/bluez/handler/BlueZBridgeHandler.java
  bundles/org.openhab.binding.bluetooth.bluez/src/main/resources/ESH-INF/thing/bluez.xml
  bundles/org.openhab.binding.bluetooth/src/main/java/org/openhab/binding/bluetooth/AbstractBluetoothBridgeHandler.java
  bundles/org.openhab.binding.bluetooth/src/main/java/org/openhab/binding/bluetooth/BaseBluetoothBridgeHandlerConfiguration.java
  bundles/org.openhab.binding.bluetooth/src/main/java/org/openhab/binding/bluetooth/BeaconBluetoothHandler.java
  bundles/org.openhab.binding.bluetooth/src/main/java/org/openhab/binding/bluetooth/BluetoothAdapter.java
  bundles/org.openhab.binding.bluetooth/src/main/java/org/openhab/binding/bluetooth/BluetoothDevice.java
  bundles/org.openhab.binding.bluetooth/src/main/java/org/openhab/binding/bluetooth/discovery/internal/BluetoothAddressLocker.java
  bundles/org.openhab.binding.bluetooth/src/main/java/org/openhab/binding/bluetooth/discovery/internal/BluetoothDiscoveryProcess.java
  bundles/org.openhab.binding.bluetooth/src/test/java/org/openhab/binding/bluetooth/MockBluetoothAdapter.java
Labels: bug, enhancement

#7247 [fronius] Add new channels and fix documentation
  bundles/org.openhab.binding.fronius/README.md
  bundles/org.openhab.binding.fronius/src/main/java/org/openhab/binding/fronius/internal/FroniusBindingConstants.java
  bundles/org.openhab.binding.fronius/src/main/java/org/openhab/binding/fronius/internal/handler/FroniusSymoInverterHandler.java
  bundles/org.openhab.binding.fronius/src/main/resources/ESH-INF/thing/thing-types.xml
Labels: enhancement

#7284 [marytts] Fix java.lang.NoClassDefFoundError: Jama/Matrix
  bundles/org.openhab.voice.marytts/pom.xml
Labels: bug

#7288 [boschindego] Fix dependency version for indego library
  bundles/org.openhab.binding.boschindego/pom.xml
Labels: bug, community approved

#7293 [doorbird] Minor documentation updates
  bundles/org.openhab.binding.doorbird/README.md
  bundles/org.openhab.binding.doorbird/src/main/resources/ESH-INF/thing/thing-types.xml
Labels: documentation

#7287 [bluetooth] Increase timeout to account for slower machines.
  bundles/org.openhab.binding.bluetooth/src/test/java/org/openhab/binding/bluetooth/discovery/internal/BluetoothDiscoveryServiceTest.java
Labels: test

#7281 [mihome] Update README.md
  bundles/org.openhab.binding.mihome/README.md
Labels: documentation

#7303 [pjlink] enhanced logging (show byte array in addition to string)
  bundles/org.openhab.binding.pjlinkdevice/src/main/java/org/openhab/binding/pjlinkdevice/internal/device/PJLinkDevice.java
  bundles/org.openhab.binding.pjlinkdevice/src/main/java/org/openhab/binding/pjlinkdevice/internal/device/command/AcknowledgeResponseValue.java
  bundles/org.openhab.binding.pjlinkdevice/src/main/java/org/openhab/binding/pjlinkdevice/internal/device/command/PrefixedResponse.java
  bundles/org.openhab.binding.pjlinkdevice/src/main/java/org/openhab/binding/pjlinkdevice/internal/device/command/errorstatus/ErrorStatusQueryResponse.java
  bundles/org.openhab.binding.pjlinkdevice/src/main/java/org/openhab/binding/pjlinkdevice/internal/device/command/mute/MuteQueryResponse.java
  bundles/org.openhab.binding.pjlinkdevice/src/main/java/org/openhab/binding/pjlinkdevice/internal/device/command/power/PowerQueryResponse.java
Labels: enhancement

#7292 [mail] Correctly named STARTTLS and a few small improvements
  bundles/org.openhab.binding.mail/README.md
  bundles/org.openhab.binding.mail/src/main/java/org/openhab/binding/mail/action/SendMailActions.java
  bundles/org.openhab.binding.mail/src/main/java/org/openhab/binding/mail/internal/SMTPHandler.java
  bundles/org.openhab.binding.mail/src/main/java/org/openhab/binding/mail/internal/ServerSecurity.java
  bundles/org.openhab.binding.mail/src/main/resources/ESH-INF/binding/binding.xml
  bundles/org.openhab.binding.mail/src/main/resources/ESH-INF/i18n/mail_de.properties
  bundles/org.openhab.binding.mail/src/main/resources/ESH-INF/thing/thing-types.xml
Labels: enhancement

#7282 [satel] Action for reading the event log added
  bundles/org.openhab.binding.satel/README.md
  bundles/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/action/SatelEventLogActions.java
  bundles/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/handler/SatelEventLogHandler.java
  bundles/org.openhab.binding.satel/src/main/resources/ESH-INF/i18n/satel.properties
Labels: enhancement

#4754 [sagercaster] Sager Weather Caster Binding initial contribution
  CODEOWNERS
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.sagercaster/.classpath
  bundles/org.openhab.binding.sagercaster/.project
  bundles/org.openhab.binding.sagercaster/NOTICE
  bundles/org.openhab.binding.sagercaster/README.md
  bundles/org.openhab.binding.sagercaster/pom.xml
  bundles/org.openhab.binding.sagercaster/src/main/feature/feature.xml
  bundles/org.openhab.binding.sagercaster/src/main/java/org/openhab/binding/sagercaster/internal/SagerCasterBindingConstants.java
  bundles/org.openhab.binding.sagercaster/src/main/java/org/openhab/binding/sagercaster/internal/SagerCasterHandlerFactory.java
  bundles/org.openhab.binding.sagercaster/src/main/java/org/openhab/binding/sagercaster/internal/SagerWeatherCaster.java
  bundles/org.openhab.binding.sagercaster/src/main/java/org/openhab/binding/sagercaster/internal/WindDirectionStateDescriptionProvider.java
  bundles/org.openhab.binding.sagercaster/src/main/java/org/openhab/binding/sagercaster/internal/discovery/SagerCasterDiscoveryService.java
  bundles/org.openhab.binding.sagercaster/src/main/java/org/openhab/binding/sagercaster/internal/handler/ExpiringMap.java
  bundles/org.openhab.binding.sagercaster/src/main/java/org/openhab/binding/sagercaster/internal/handler/SagerCasterHandler.java
  bundles/org.openhab.binding.sagercaster/src/main/resources/ESH-INF/binding/binding.xml
  bundles/org.openhab.binding.sagercaster/src/main/resources/ESH-INF/i18n/sagercaster_fr.properties
  bundles/org.openhab.binding.sagercaster/src/main/resources/ESH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.sagercaster/src/main/resources/sagerForecaster.properties
  bundles/pom.xml
Labels: cre, new binding, oh1 migration

#7300 [lgwebos] Ignore power off command when the TV is already off
  bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/PowerControlPower.java
Labels: community approved

#7295 [insteon] Add support for Beep and LED on/off features to Dimmer Modules(2457D2), On/Off Modules(2635-222), and On/Off Outdoor Modules(2634-222)
  bundles/org.openhab.binding.insteon/src/main/resources/device_types.xml
Labels: enhancement

#7311 [nikohomecontrol] Small README updates.
  bundles/org.openhab.binding.nikohomecontrol/README.md
Labels: documentation

#7323 [neohub] bug fix for new hub firmware
  bundles/org.openhab.binding.neohub/src/main/java/org/openhab/binding/neohub/internal/NeoHubInfoResponse.java
  bundles/org.openhab.binding.neohub/src/main/java/org/openhab/binding/neohub/internal/NeohubBool.java
  bundles/org.openhab.binding.neohub/src/main/java/org/openhab/binding/neohub/internal/NeohubBoolDeserializer.java
  bundles/org.openhab.binding.neohub/src/test/java/org/openhab/binding/neohub/test/NeoHubTestData.java
Labels: bug

#7327 [chromecast] Update API lib to 0.11.3
  bundles/org.openhab.binding.chromecast/pom.xml
Labels: bug

#7330 [nikohomecontrol] Small README update.
  bundles/org.openhab.binding.nikohomecontrol/README.md
Labels: documentation

#7335 [openweathermap] Added apparent temperature channel
  bundles/org.openhab.binding.openweathermap/README.md
  bundles/org.openhab.binding.openweathermap/pom.xml
  bundles/org.openhab.binding.openweathermap/src/main/feature/feature.xml
  bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/OpenWeatherMapBindingConstants.java
  bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/connection/OpenWeatherMapConnection.java
  bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/dto/OpenWeatherMapJsonDailyForecastData.java
  bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/dto/OpenWeatherMapJsonHourlyForecastData.java
  bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/dto/OpenWeatherMapJsonUVIndexData.java
  bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/dto/OpenWeatherMapJsonWeatherData.java
  bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/dto/base/City.java
  bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/dto/base/Clouds.java
  bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/dto/base/Coord.java
  bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/dto/base/Rain.java
  bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/dto/base/Snow.java
  bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/dto/base/Weather.java
  bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/dto/base/Wind.java
  bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/dto/forecast/daily/FeelsLikeTemp.java
  bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/dto/forecast/daily/List.java
  bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/dto/forecast/daily/Temp.java
  bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/dto/forecast/hourly/List.java
  bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/dto/forecast/hourly/Main.java
  bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/dto/forecast/hourly/Sys.java
  bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/dto/weather/Main.java
  bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/dto/weather/Sys.java
  bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/handler/OpenWeatherMapUVIndexHandler.java
  bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/handler/OpenWeatherMapWeatherAndForecastHandler.java
  bundles/org.openhab.binding.openweathermap/src/main/resources/ESH-INF/i18n/openweathermap_de.properties
  bundles/org.openhab.binding.openweathermap/src/main/resources/ESH-INF/thing/channel-types.xml
Labels: enhancement

#7340 [daikin] Support AUTO fan mode with Airbase
  bundles/org.openhab.binding.daikin/README.md
  bundles/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/api/airbase/AirbaseEnums.java
  bundles/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/handler/DaikinAirbaseUnitHandler.java
Labels: enhancement

#7341 [daikin] Update doc to include fandir channel previously omitted
  bundles/org.openhab.binding.daikin/README.md
Labels: documentation

#7235 [influxdb] Added support for InfluxDB 2.0
  CODEOWNERS
  bundles/org.openhab.persistence.influxdb/.classpath
  bundles/org.openhab.persistence.influxdb/README.md
  bundles/org.openhab.persistence.influxdb/pom.xml
  bundles/org.openhab.persistence.influxdb/src/main/feature/feature.xml
  bundles/org.openhab.persistence.influxdb/src/main/java/org/openhab/persistence/influxdb/InfluxDBPersistenceService.java
  bundles/org.openhab.persistence.influxdb/src/main/java/org/openhab/persistence/influxdb/internal/FilterCriteriaQueryCreator.java
  bundles/org.openhab.persistence.influxdb/src/main/java/org/openhab/persistence/influxdb/internal/InfluxDBConfiguration.java
  bundles/org.openhab.persistence.influxdb/src/main/java/org/openhab/persistence/influxdb/internal/InfluxDBConstants.java
  bundles/org.openhab.persistence.influxdb/src/main/java/org/openhab/persistence/influxdb/internal/InfluxDBHistoricItem.java
  bundles/org.openhab.persistence.influxdb/src/main/java/org/openhab/persistence/influxdb/internal/InfluxDBPersistenceService.java
  bundles/org.openhab.persistence.influxdb/src/main/java/org/openhab/persistence/influxdb/internal/InfluxDBPersistentItemInfo.java
  bundles/org.openhab.persistence.influxdb/src/main/java/org/openhab/persistence/influxdb/internal/InfluxDBRepository.java
  bundles/org.openhab.persistence.influxdb/src/main/java/org/openhab/persistence/influxdb/internal/InfluxDBStateConvertUtils.java
  bundles/org.openhab.persistence.influxdb/src/main/java/org/openhab/persistence/influxdb/internal/InfluxDBVersion.java
  bundles/org.openhab.persistence.influxdb/src/main/java/org/openhab/persistence/influxdb/internal/InfluxPoint.java
  bundles/org.openhab.persistence.influxdb/src/main/java/org/openhab/persistence/influxdb/internal/InfluxRow.java
  bundles/org.openhab.persistence.influxdb/src/main/java/org/openhab/persistence/influxdb/internal/ItemToStorePointCreator.java
  bundles/org.openhab.persistence.influxdb/src/main/java/org/openhab/persistence/influxdb/internal/RepositoryFactory.java
  bundles/org.openhab.persistence.influxdb/src/main/java/org/openhab/persistence/influxdb/internal/UnnexpectedConditionException.java
  bundles/org.openhab.persistence.influxdb/src/main/java/org/openhab/persistence/influxdb/internal/influx1/Influx1FilterCriteriaQueryCreatorImpl.java
  bundles/org.openhab.persistence.influxdb/src/main/java/org/openhab/persistence/influxdb/internal/influx1/InfluxDB1RepositoryImpl.java
  bundles/org.openhab.persistence.influxdb/src/main/java/org/openhab/persistence/influxdb/internal/influx2/Influx2FilterCriteriaQueryCreatorImpl.java
  bundles/org.openhab.persistence.influxdb/src/main/java/org/openhab/persistence/influxdb/internal/influx2/InfluxDB2RepositoryImpl.java
  bundles/org.openhab.persistence.influxdb/src/main/resources/ESH-INF/config/config.xml
  bundles/org.openhab.persistence.influxdb/src/test/java/org/openhab/persistence/influxdb/internal/ConfigurationTestHelper.java
  bundles/org.openhab.persistence.influxdb/src/test/java/org/openhab/persistence/influxdb/internal/InfluxDBPersistenceServiceTest.java
  bundles/org.openhab.persistence.influxdb/src/test/java/org/openhab/persistence/influxdb/internal/InfluxDBStateConvertUtilsTest.java
  bundles/org.openhab.persistence.influxdb/src/test/java/org/openhab/persistence/influxdb/internal/InfluxFilterCriteriaQueryCreatorImplTest.java
  bundles/org.openhab.persistence.influxdb/src/test/java/org/openhab/persistence/influxdb/internal/ItemTestHelper.java
  bundles/org.openhab.persistence.influxdb/src/test/java/org/openhab/persistence/influxdb/internal/ItemToStorePointCreatorTest.java
Labels: new persistence, oh3

#6489 [googletts] Refactored to use openHAB Core OAuth2
  bom/openhab-addons/pom.xml
  bundles/org.openhab.voice.googletts/.classpath
  bundles/org.openhab.voice.googletts/.project
  bundles/org.openhab.voice.googletts/NOTICE
  bundles/org.openhab.voice.googletts/README.md
  bundles/org.openhab.voice.googletts/pom.xml
  bundles/org.openhab.voice.googletts/src/main/feature/feature.xml
  bundles/org.openhab.voice.googletts/src/main/java/org/openhab/voice/googletts/internal/AuthenticationException.java
  bundles/org.openhab.voice.googletts/src/main/java/org/openhab/voice/googletts/internal/GoogleCloudAPI.java
  bundles/org.openhab.voice.googletts/src/main/java/org/openhab/voice/googletts/internal/GoogleTTSConfig.java
  bundles/org.openhab.voice.googletts/src/main/java/org/openhab/voice/googletts/internal/GoogleTTSService.java
  bundles/org.openhab.voice.googletts/src/main/java/org/openhab/voice/googletts/internal/GoogleTTSVoice.java
  bundles/org.openhab.voice.googletts/src/main/java/org/openhab/voice/googletts/internal/protocol/AudioConfig.java
  bundles/org.openhab.voice.googletts/src/main/java/org/openhab/voice/googletts/internal/protocol/AudioEncoding.java
  bundles/org.openhab.voice.googletts/src/main/java/org/openhab/voice/googletts/internal/protocol/ListVoicesResponse.java
  bundles/org.openhab.voice.googletts/src/main/java/org/openhab/voice/googletts/internal/protocol/SsmlVoiceGender.java
  bundles/org.openhab.voice.googletts/src/main/java/org/openhab/voice/googletts/internal/protocol/SynthesisInput.java
  bundles/org.openhab.voice.googletts/src/main/java/org/openhab/voice/googletts/internal/protocol/SynthesizeSpeechRequest.java
  bundles/org.openhab.voice.googletts/src/main/java/org/openhab/voice/googletts/internal/protocol/SynthesizeSpeechResponse.java
  bundles/org.openhab.voice.googletts/src/main/java/org/openhab/voice/googletts/internal/protocol/Voice.java
  bundles/org.openhab.voice.googletts/src/main/java/org/openhab/voice/googletts/internal/protocol/VoiceSelectionParams.java
  bundles/org.openhab.voice.googletts/src/main/resources/OH-INF/config/config.xml
  bundles/pom.xml
Labels: enhancement, oh3

#7339 [insteon] Added Fast On/Off and Manual change support for Insteon 2334 Keypad Dimmer - 6 and 8 button varients and added all support Insteon 2487S Keypad Switch - 8 button varient
  bundles/org.openhab.binding.insteon/README.md
  bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/InsteonBindingConstants.java
  bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/handler/InsteonDeviceHandler.java
  bundles/org.openhab.binding.insteon/src/main/resources/ESH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.insteon/src/main/resources/device_types.xml
Labels: enhancement

#7298 [dwdpollenflug] Initial Contribution
  CODEOWNERS
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.dwdpollenflug/.classpath
  bundles/org.openhab.binding.dwdpollenflug/.project
  bundles/org.openhab.binding.dwdpollenflug/NOTICE
  bundles/org.openhab.binding.dwdpollenflug/README.md
  bundles/org.openhab.binding.dwdpollenflug/pom.xml
  bundles/org.openhab.binding.dwdpollenflug/src/main/feature/feature.xml
  bundles/org.openhab.binding.dwdpollenflug/src/main/java/org/openhab/binding/dwdpollenflug/internal/DWDPollenflugBindingConstants.java
  bundles/org.openhab.binding.dwdpollenflug/src/main/java/org/openhab/binding/dwdpollenflug/internal/DWDPollenflugHandlerFactory.java
  bundles/org.openhab.binding.dwdpollenflug/src/main/java/org/openhab/binding/dwdpollenflug/internal/DWDPollingException.java
  bundles/org.openhab.binding.dwdpollenflug/src/main/java/org/openhab/binding/dwdpollenflug/internal/config/DWDPollenflugBridgeConfiguration.java
  bundles/org.openhab.binding.dwdpollenflug/src/main/java/org/openhab/binding/dwdpollenflug/internal/config/DWDPollenflugRegionConfiguration.java
  bundles/org.openhab.binding.dwdpollenflug/src/main/java/org/openhab/binding/dwdpollenflug/internal/dto/DWDPollenflug.java
  bundles/org.openhab.binding.dwdpollenflug/src/main/java/org/openhab/binding/dwdpollenflug/internal/dto/DWDPollenflugPollen.java
  bundles/org.openhab.binding.dwdpollenflug/src/main/java/org/openhab/binding/dwdpollenflug/internal/dto/DWDPollentypeJSON.java
  bundles/org.openhab.binding.dwdpollenflug/src/main/java/org/openhab/binding/dwdpollenflug/internal/dto/DWDRegion.java
  bundles/org.openhab.binding.dwdpollenflug/src/main/java/org/openhab/binding/dwdpollenflug/internal/handler/DWDPollenflugBridgeHandler.java
  bundles/org.openhab.binding.dwdpollenflug/src/main/java/org/openhab/binding/dwdpollenflug/internal/handler/DWDPollenflugRegionHandler.java
  bundles/org.openhab.binding.dwdpollenflug/src/main/resources/ESH-INF/binding/binding.xml
  bundles/org.openhab.binding.dwdpollenflug/src/main/resources/ESH-INF/i18n/dwdpollenflug_de.properties
  bundles/org.openhab.binding.dwdpollenflug/src/main/resources/ESH-INF/thing/bridge.xml
  bundles/org.openhab.binding.dwdpollenflug/src/main/resources/ESH-INF/thing/region.xml
  bundles/pom.xml
Labels: new binding

#7347 [insteon] Improve hub message processing
  bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/driver/Port.java
  bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/driver/hub/HubIOStream.java
  bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/message/MsgFactory.java
  bundles/org.openhab.binding.insteon/src/main/resources/msg_definitions.xml
Labels: enhancement

#7357 [weathercompany] Fix language in thing example
  bundles/org.openhab.binding.weathercompany/README.md
Labels: documentation

#7345 [netatmo] Added day, week, and month measurements to the weather station and indoor, outdoor, and rain modules
  bundles/org.openhab.binding.netatmo/README.md
  bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/ChannelTypeUtils.java
  bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/NetatmoBindingConstants.java
  bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/AbstractNetatmoThingHandler.java
  bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/NetatmoBridgeHandler.java
  bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/station/NAMainHandler.java
  bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/station/NAModule1Handler.java
  bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/station/NAModule3Handler.java
  bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/station/NAModule4Handler.java
  bundles/org.openhab.binding.netatmo/src/main/resources/ESH-INF/thing/channels.xml
  bundles/org.openhab.binding.netatmo/src/main/resources/ESH-INF/thing/station.xml
Labels: enhancement

#7360 [netatmo] fix calculation for heat index
  bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/WeatherUtils.java
Labels: bug

#7362 [lutron] Add discovery support for RA2 Select repeater
  bundles/org.openhab.binding.lutron/README.md
  bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/discovery/LutronMdnsBridgeDiscoveryService.java
Labels: enhancement

#7363 [minecraft] Added information for defining things for Minecraft plugin
  bundles/org.openhab.binding.minecraft/README.md
Labels: documentation

#7376 [bluetooth] Fix for concurrent modification exception during shutdown.
  bundles/org.openhab.binding.bluetooth/src/main/java/org/openhab/binding/bluetooth/AbstractBluetoothBridgeHandler.java
Labels: bug

#7346 [pioneeravr] Add models up until year 2020
  bundles/org.openhab.binding.pioneeravr/src/main/java/org/openhab/binding/pioneeravr/internal/PioneerAvrBindingConstants.java
  bundles/org.openhab.binding.pioneeravr/src/main/java/org/openhab/binding/pioneeravr/internal/discovery/PioneerAvrDiscoveryParticipant.java
  bundles/org.openhab.binding.pioneeravr/src/main/java/org/openhab/binding/pioneeravr/internal/handler/AvrHandlerFactory.java
  bundles/org.openhab.binding.pioneeravr/src/main/resources/ESH-INF/thing/thing-types.xml
Labels: enhancement

#7388 [Spotify] Added channel to display if track is explicit
  bundles/org.openhab.binding.spotify/src/main/java/org/openhab/binding/spotify/internal/SpotifyBindingConstants.java
  bundles/org.openhab.binding.spotify/src/main/java/org/openhab/binding/spotify/internal/api/model/Item.java
  bundles/org.openhab.binding.spotify/src/main/java/org/openhab/binding/spotify/internal/handler/SpotifyBridgeHandler.java
  bundles/org.openhab.binding.spotify/src/main/resources/ESH-INF/thing/thing-types.xml
Labels: enhancement

#7387 [insteon] Add OnLevel support for Insteon 2334-232 (6 and 8 button varients)
  bundles/org.openhab.binding.insteon/src/main/resources/device_types.xml
Labels: enhancement

#7392 [spotify] Updated readme related to new explicit channel
  bundles/org.openhab.binding.spotify/README.md
Labels: documentation

#7389 [tplinksmarthome] Added Kl50 and kl60 light bulbs.
  bundles/org.openhab.binding.tplinksmarthome/README.md
  bundles/org.openhab.binding.tplinksmarthome/src/main/java/org/openhab/binding/tplinksmarthome/internal/TPLinkSmartHomeThingType.java
  bundles/org.openhab.binding.tplinksmarthome/src/main/resources/ESH-INF/thing/KL50.xml
  bundles/org.openhab.binding.tplinksmarthome/src/main/resources/ESH-INF/thing/KL60.xml
Labels: enhancement

#7355 [lgwebos] Fix missing update of power channel state
  bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/LauncherApplication.java
  bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/PowerControlPower.java
  bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/handler/LGWebOSHandler.java
  bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/handler/LGWebOSTVSocket.java
Labels: bug

#7101 [linky] Linky binding
  CODEOWNERS
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.linky/.classpath
  bundles/org.openhab.binding.linky/.project
  bundles/org.openhab.binding.linky/NOTICE
  bundles/org.openhab.binding.linky/README.md
  bundles/org.openhab.binding.linky/pom.xml
  bundles/org.openhab.binding.linky/src/main/feature/feature.xml
  bundles/org.openhab.binding.linky/src/main/java/org/openhab/binding/linky/internal/ExpiringDayCache.java
  bundles/org.openhab.binding.linky/src/main/java/org/openhab/binding/linky/internal/LinkyBindingConstants.java
  bundles/org.openhab.binding.linky/src/main/java/org/openhab/binding/linky/internal/LinkyConfiguration.java
  bundles/org.openhab.binding.linky/src/main/java/org/openhab/binding/linky/internal/LinkyHandlerFactory.java
  bundles/org.openhab.binding.linky/src/main/java/org/openhab/binding/linky/internal/console/LinkyCommandExtension.java
  bundles/org.openhab.binding.linky/src/main/java/org/openhab/binding/linky/internal/handler/LinkyCookieJar.java
  bundles/org.openhab.binding.linky/src/main/java/org/openhab/binding/linky/internal/handler/LinkyHandler.java
  bundles/org.openhab.binding.linky/src/main/java/org/openhab/binding/linky/internal/model/LinkyConsumptionData.java
  bundles/org.openhab.binding.linky/src/main/java/org/openhab/binding/linky/internal/model/LinkyTimeScale.java
  bundles/org.openhab.binding.linky/src/main/resources/ESH-INF/binding/binding.xml
  bundles/org.openhab.binding.linky/src/main/resources/ESH-INF/thing/thing-types.xml
  bundles/pom.xml
Labels: cre, new binding

#6314 [bsblan] BSB LAN Binding initial contribution
  CODEOWNERS
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.bsblan/.classpath
  bundles/org.openhab.binding.bsblan/.project
  bundles/org.openhab.binding.bsblan/NOTICE
  bundles/org.openhab.binding.bsblan/README.md
  bundles/org.openhab.binding.bsblan/pom.xml
  bundles/org.openhab.binding.bsblan/src/main/feature/feature.xml
  bundles/org.openhab.binding.bsblan/src/main/java/org/openhab/binding/bsblan/internal/BsbLanBindingConstants.java
  bundles/org.openhab.binding.bsblan/src/main/java/org/openhab/binding/bsblan/internal/BsbLanHandlerFactory.java
  bundles/org.openhab.binding.bsblan/src/main/java/org/openhab/binding/bsblan/internal/api/BsbLanApiCaller.java
  bundles/org.openhab.binding.bsblan/src/main/java/org/openhab/binding/bsblan/internal/api/BsbLanApiContentConverter.java
  bundles/org.openhab.binding.bsblan/src/main/java/org/openhab/binding/bsblan/internal/api/dto/BsbLanApiContentDTO.java
  bundles/org.openhab.binding.bsblan/src/main/java/org/openhab/binding/bsblan/internal/api/dto/BsbLanApiParameterDTO.java
  bundles/org.openhab.binding.bsblan/src/main/java/org/openhab/binding/bsblan/internal/api/dto/BsbLanApiParameterQueryResponseDTO.java
  bundles/org.openhab.binding.bsblan/src/main/java/org/openhab/binding/bsblan/internal/api/dto/BsbLanApiParameterSetRequestDTO.java
  bundles/org.openhab.binding.bsblan/src/main/java/org/openhab/binding/bsblan/internal/api/dto/BsbLanApiParameterSetResponseDTO.java
  bundles/org.openhab.binding.bsblan/src/main/java/org/openhab/binding/bsblan/internal/api/dto/BsbLanApiParameterSetResultDTO.java
  bundles/org.openhab.binding.bsblan/src/main/java/org/openhab/binding/bsblan/internal/configuration/BsbLanBridgeConfiguration.java
  bundles/org.openhab.binding.bsblan/src/main/java/org/openhab/binding/bsblan/internal/configuration/BsbLanParameterConfiguration.java
  bundles/org.openhab.binding.bsblan/src/main/java/org/openhab/binding/bsblan/internal/handler/BsbLanBaseThingHandler.java
  bundles/org.openhab.binding.bsblan/src/main/java/org/openhab/binding/bsblan/internal/handler/BsbLanBridgeHandler.java
  bundles/org.openhab.binding.bsblan/src/main/java/org/openhab/binding/bsblan/internal/handler/BsbLanParameterHandler.java
  bundles/org.openhab.binding.bsblan/src/main/java/org/openhab/binding/bsblan/internal/helper/BsbLanParameterConverter.java
  bundles/org.openhab.binding.bsblan/src/main/resources/ESH-INF/binding/binding.xml
  bundles/org.openhab.binding.bsblan/src/main/resources/ESH-INF/thing/bridge.xml
  bundles/org.openhab.binding.bsblan/src/main/resources/ESH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.bsblan/src/test/java/org/openhab/binding/bsblan/internal/BsbLanHandlerFactoryTests.java
  bundles/org.openhab.binding.bsblan/src/test/java/org/openhab/binding/bsblan/internal/api/BsbLanApiContentConverterTests.java
  bundles/org.openhab.binding.bsblan/src/test/java/org/openhab/binding/bsblan/internal/helper/BsbLanParameterConverterTests.java
  bundles/pom.xml
Labels: cre, new binding

#7358 [CoronaStats] Initial contribution
  CODEOWNERS
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.coronastats/.classpath
  bundles/org.openhab.binding.coronastats/.project
  bundles/org.openhab.binding.coronastats/NOTICE
  bundles/org.openhab.binding.coronastats/README.md
  bundles/org.openhab.binding.coronastats/pom.xml
  bundles/org.openhab.binding.coronastats/src/main/feature/feature.xml
  bundles/org.openhab.binding.coronastats/src/main/java/org/openhab/binding/coronastats/internal/CoronaStatsBindingConstants.java
  bundles/org.openhab.binding.coronastats/src/main/java/org/openhab/binding/coronastats/internal/CoronaStatsHandlerFactory.java
  bundles/org.openhab.binding.coronastats/src/main/java/org/openhab/binding/coronastats/internal/CoronaStatsPollingException.java
  bundles/org.openhab.binding.coronastats/src/main/java/org/openhab/binding/coronastats/internal/config/CoronaStatsCountryConfiguration.java
  bundles/org.openhab.binding.coronastats/src/main/java/org/openhab/binding/coronastats/internal/config/CoronaStatsWorldConfiguration.java
  bundles/org.openhab.binding.coronastats/src/main/java/org/openhab/binding/coronastats/internal/discovery/CoronaStatsDiscoveryService.java
  bundles/org.openhab.binding.coronastats/src/main/java/org/openhab/binding/coronastats/internal/dto/CoronaStats.java
  bundles/org.openhab.binding.coronastats/src/main/java/org/openhab/binding/coronastats/internal/dto/CoronaStatsCases.java
  bundles/org.openhab.binding.coronastats/src/main/java/org/openhab/binding/coronastats/internal/dto/CoronaStatsCountry.java
  bundles/org.openhab.binding.coronastats/src/main/java/org/openhab/binding/coronastats/internal/dto/CoronaStatsWorld.java
  bundles/org.openhab.binding.coronastats/src/main/java/org/openhab/binding/coronastats/internal/handler/CoronaStatsCountryHandler.java
  bundles/org.openhab.binding.coronastats/src/main/java/org/openhab/binding/coronastats/internal/handler/CoronaStatsWorldHandler.java
  bundles/org.openhab.binding.coronastats/src/main/resources/ESH-INF/binding/binding.xml
  bundles/org.openhab.binding.coronastats/src/main/resources/ESH-INF/thing/channel-type.xml
  bundles/org.openhab.binding.coronastats/src/main/resources/ESH-INF/thing/country.xml
  bundles/org.openhab.binding.coronastats/src/main/resources/ESH-INF/thing/world.xml
  bundles/pom.xml
Labels: new binding

#7395 [DWDPollenflug] Small code improvments
  bundles/org.openhab.binding.dwdpollenflug/README.md
  bundles/org.openhab.binding.dwdpollenflug/src/main/java/org/openhab/binding/dwdpollenflug/internal/DWDPollenflugBindingConstants.java
  bundles/org.openhab.binding.dwdpollenflug/src/main/java/org/openhab/binding/dwdpollenflug/internal/DWDPollenflugHandlerFactory.java
  bundles/org.openhab.binding.dwdpollenflug/src/main/java/org/openhab/binding/dwdpollenflug/internal/discovery/DWDPollenflugDiscoveryService.java
  bundles/org.openhab.binding.dwdpollenflug/src/main/java/org/openhab/binding/dwdpollenflug/internal/handler/DWDPollenflugBridgeHandler.java
  bundles/org.openhab.binding.dwdpollenflug/src/main/java/org/openhab/binding/dwdpollenflug/internal/handler/DWDPollenflugRegionHandler.java
  bundles/org.openhab.binding.dwdpollenflug/src/main/resources/ESH-INF/i18n/dwdpollenflug_de.properties
  bundles/org.openhab.binding.dwdpollenflug/src/main/resources/ESH-INF/thing/bridge.xml
  bundles/org.openhab.binding.dwdpollenflug/src/main/resources/ESH-INF/thing/region.xml
Labels: enhancement

#7384 [sensebox] Added German translations
  bundles/org.openhab.binding.sensebox/src/main/resources/ESH-INF/binding/binding.xml
  bundles/org.openhab.binding.sensebox/src/main/resources/ESH-INF/config/config-description.xml
  bundles/org.openhab.binding.sensebox/src/main/resources/ESH-INF/i18n/sensebox_de.properties
  bundles/org.openhab.binding.sensebox/src/main/resources/ESH-INF/thing/box.xml
  bundles/org.openhab.binding.sensebox/src/main/resources/ESH-INF/thing/channels.xml
Labels: translation

#6845 [mqtt.homie] Add Dimmer functionality
  bundles/org.openhab.binding.mqtt.homie/src/main/java/org/openhab/binding/mqtt/homie/internal/homie300/Property.java
Labels: enhancement

#7397 [nikohomecontrol] Update to README.
  bundles/org.openhab.binding.nikohomecontrol/README.md
Labels: documentation

#7401 [lgwebos] Delay subscription of channel
  bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/handler/LGWebOSHandler.java
Labels: bug

#6331 [sunspec] Modbus: SunSpec bundle basic version initial contribution
  CODEOWNERS
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.modbus.sunspec/.classpath
  bundles/org.openhab.binding.modbus.sunspec/.project
  bundles/org.openhab.binding.modbus.sunspec/NOTICE
  bundles/org.openhab.binding.modbus.sunspec/README.md
  bundles/org.openhab.binding.modbus.sunspec/pom.xml
  bundles/org.openhab.binding.modbus.sunspec/src/main/feature/feature.xml
  bundles/org.openhab.binding.modbus.sunspec/src/main/java/org/openhab/binding/modbus/sunspec/internal/InverterStatus.java
  bundles/org.openhab.binding.modbus.sunspec/src/main/java/org/openhab/binding/modbus/sunspec/internal/SunSpecConfiguration.java
  bundles/org.openhab.binding.modbus.sunspec/src/main/java/org/openhab/binding/modbus/sunspec/internal/SunSpecConstants.java
  bundles/org.openhab.binding.modbus.sunspec/src/main/java/org/openhab/binding/modbus/sunspec/internal/SunSpecHandlerFactory.java
  bundles/org.openhab.binding.modbus.sunspec/src/main/java/org/openhab/binding/modbus/sunspec/internal/dto/InverterModelBlock.java
  bundles/org.openhab.binding.modbus.sunspec/src/main/java/org/openhab/binding/modbus/sunspec/internal/dto/ModelBlock.java
  bundles/org.openhab.binding.modbus.sunspec/src/main/java/org/openhab/binding/modbus/sunspec/internal/handler/AbstractSunSpecHandler.java
  bundles/org.openhab.binding.modbus.sunspec/src/main/java/org/openhab/binding/modbus/sunspec/internal/handler/InverterHandler.java
  bundles/org.openhab.binding.modbus.sunspec/src/main/java/org/openhab/binding/modbus/sunspec/internal/parser/AbstractBaseParser.java
  bundles/org.openhab.binding.modbus.sunspec/src/main/java/org/openhab/binding/modbus/sunspec/internal/parser/InverterModelParser.java
  bundles/org.openhab.binding.modbus.sunspec/src/main/java/org/openhab/binding/modbus/sunspec/internal/parser/SunspecParser.java
  bundles/org.openhab.binding.modbus.sunspec/src/main/resources/ESH-INF/config/config-descriptions.xml
  bundles/org.openhab.binding.modbus.sunspec/src/main/resources/ESH-INF/thing/inverter-channel-groups.xml
  bundles/org.openhab.binding.modbus.sunspec/src/main/resources/ESH-INF/thing/inverter-channel-types.xml
  bundles/org.openhab.binding.modbus.sunspec/src/main/resources/ESH-INF/thing/inverter-types.xml
  bundles/pom.xml
Labels: cre, new binding

#7405 [bluetooth] Removed usage of deprecated method in tests
  bundles/org.openhab.binding.bluetooth/src/test/java/org/openhab/binding/bluetooth/discovery/internal/BluetoothDiscoveryServiceTest.java
Labels: test

#6457 [tibber] Tibber Binding initial contribution
  CODEOWNERS
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.tibber/.classpath
  bundles/org.openhab.binding.tibber/.project
  bundles/org.openhab.binding.tibber/NOTICE
  bundles/org.openhab.binding.tibber/README.md
  bundles/org.openhab.binding.tibber/pom.xml
  bundles/org.openhab.binding.tibber/src/main/feature/feature.xml
  bundles/org.openhab.binding.tibber/src/main/java/org/openhab/binding/tibber/internal/TibberBindingConstants.java
  bundles/org.openhab.binding.tibber/src/main/java/org/openhab/binding/tibber/internal/TibberHandlerFactory.java
  bundles/org.openhab.binding.tibber/src/main/java/org/openhab/binding/tibber/internal/config/TibberConfiguration.java
  bundles/org.openhab.binding.tibber/src/main/java/org/openhab/binding/tibber/internal/handler/TibberHandler.java
  bundles/org.openhab.binding.tibber/src/main/java/org/openhab/binding/tibber/internal/handler/TibberPriceConsumptionHandler.java
  bundles/org.openhab.binding.tibber/src/main/resources/ESH-INF/binding/binding.xml
  bundles/org.openhab.binding.tibber/src/main/resources/ESH-INF/thing/thing-types.xml
  bundles/pom.xml
Labels: bounty, cre, new binding

#7404 [miio] add miot protocol & conditions
  bundles/org.openhab.binding.miio/README.md
  bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/MiIoCommand.java
  bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/MiIoDevices.java
  bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/basic/ActionConditions.java
  bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/basic/MiIoBasicChannel.java
  bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/basic/MiIoDeviceAction.java
  bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/basic/MiIoDeviceActionCondition.java
  bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/cloud/CloudConnector.java
  bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/handler/MiIoAbstractHandler.java
  bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/handler/MiIoBasicHandler.java
  bundles/org.openhab.binding.miio/src/main/resources/ESH-INF/thing/commonChannels.xml
  bundles/org.openhab.binding.miio/src/main/resources/database/philips.light.bulb.json
  bundles/org.openhab.binding.miio/src/main/resources/database/philips.light.candle.json
  bundles/org.openhab.binding.miio/src/main/resources/database/philips.light.ceiling.json
  bundles/org.openhab.binding.miio/src/main/resources/database/philips.light.mono.json
  bundles/org.openhab.binding.miio/src/main/resources/database/philips.light.moonlight.json
  bundles/org.openhab.binding.miio/src/main/resources/database/philips.light.sread1.json
  bundles/org.openhab.binding.miio/src/main/resources/database/yeelink.light.ceiling.json
  bundles/org.openhab.binding.miio/src/main/resources/database/yeelink.light.ceiling2.json
  bundles/org.openhab.binding.miio/src/main/resources/database/yeelink.light.ceiling4.json
  bundles/org.openhab.binding.miio/src/main/resources/database/yeelink.light.color1.json
  bundles/org.openhab.binding.miio/src/main/resources/database/yeelink.light.lamp1.json
  bundles/org.openhab.binding.miio/src/main/resources/database/zhimi.airpurifier.m1.json
  bundles/org.openhab.binding.miio/src/main/resources/database/zhimi.airpurifier.ma4-miot.json
  bundles/org.openhab.binding.miio/src/main/resources/database/zhimi.airpurifier.mb3-miot.json
Labels: enhancement

#7399 [lgwebos] Use system properties when available
  bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/LGWebOSBindingConstants.java
  bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/discovery/LGWebOSUpnpDiscoveryParticipant.java
  bundles/org.openhab.binding.lgwebos/src/main/resources/ESH-INF/thing/thing-types.xml
Labels: enhancement

#7103 [lgwebos] Wake-on-Lan Integration
  bundles/org.openhab.binding.lgwebos/README.md
  bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/action/LGWebOSActions.java
  bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/LGWebOSBindingConstants.java
  bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/PowerControlPower.java
  bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/WakeOnLanUtility.java
  bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/discovery/LGWebOSUpnpDiscoverySearch.java
  bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/handler/LGWebOSConfiguration.java
  bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/handler/LGWebOSHandler.java
  bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/handler/LGWebOSTVSocket.java
  bundles/org.openhab.binding.lgwebos/src/main/resources/ESH-INF/config/config.xml
Labels: enhancement

#7393 [km200] bugfixing and optimization
  bundles/org.openhab.binding.km200/src/main/java/org/openhab/binding/km200/internal/KM200BindingConstants.java
  bundles/org.openhab.binding.km200/src/main/java/org/openhab/binding/km200/internal/KM200Comm.java
  bundles/org.openhab.binding.km200/src/main/java/org/openhab/binding/km200/internal/KM200Cryption.java
  bundles/org.openhab.binding.km200/src/main/java/org/openhab/binding/km200/internal/KM200Device.java
  bundles/org.openhab.binding.km200/src/main/java/org/openhab/binding/km200/internal/KM200HandlerFactory.java
  bundles/org.openhab.binding.km200/src/main/java/org/openhab/binding/km200/internal/KM200ServiceObject.java
  bundles/org.openhab.binding.km200/src/main/java/org/openhab/binding/km200/internal/KM200Utils.java
  bundles/org.openhab.binding.km200/src/main/java/org/openhab/binding/km200/internal/discovery/KM200GatewayDiscoveryParticipant.java
  bundles/org.openhab.binding.km200/src/main/java/org/openhab/binding/km200/internal/discovery/KM200GatewayDiscoveryService.java
  bundles/org.openhab.binding.km200/src/main/java/org/openhab/binding/km200/internal/handler/KM200DataHandler.java
  bundles/org.openhab.binding.km200/src/main/java/org/openhab/binding/km200/internal/handler/KM200ErrorServiceHandler.java
  bundles/org.openhab.binding.km200/src/main/java/org/openhab/binding/km200/internal/handler/KM200GatewayHandler.java
  bundles/org.openhab.binding.km200/src/main/java/org/openhab/binding/km200/internal/handler/KM200GatewayStatusListener.java
  bundles/org.openhab.binding.km200/src/main/java/org/openhab/binding/km200/internal/handler/KM200ServiceHandler.java
  bundles/org.openhab.binding.km200/src/main/java/org/openhab/binding/km200/internal/handler/KM200SwitchProgramServiceHandler.java
  bundles/org.openhab.binding.km200/src/main/java/org/openhab/binding/km200/internal/handler/KM200ThingHandler.java
  bundles/org.openhab.binding.km200/src/main/java/org/openhab/binding/km200/internal/handler/KM200VirtualServiceHandler.java
Labels: bug

#6985 [shelly] Support for Duo, EM3, DW, Smoke, Addon; new CoAP-based updates; bug fixes
  bundles/org.openhab.binding.shelly/README.md
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/ShellyBindingConstants.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/ShellyHandlerFactory.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api/ShellyApiException.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api/ShellyApiJsonDTO.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api/ShellyApiResult.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api/ShellyDeviceProfile.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api/ShellyEventServlet.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api/ShellyHttpApi.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/coap/ShellyCoapHandler.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/coap/ShellyCoapJSonDTO.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/coap/ShellyCoapServer.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/config/ShellyBindingConfiguration.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/config/ShellyThingConfiguration.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/discovery/ShellyDiscoveryParticipant.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/discovery/ShellyThingCreator.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/handler/ShellyBaseHandler.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/handler/ShellyChannelDefinitionsDTO.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/handler/ShellyColorUtils.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/handler/ShellyComponents.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/handler/ShellyDeviceListener.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/handler/ShellyLightHandler.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/handler/ShellyProtectedHandler.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/handler/ShellyRelayHandler.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/util/ShellyChannelCache.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/util/ShellyTranslationProvider.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/util/ShellyUtils.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/util/ShellyVersionDTO.java
  bundles/org.openhab.binding.shelly/src/main/resources/ESH-INF/binding/binding.xml
  bundles/org.openhab.binding.shelly/src/main/resources/ESH-INF/config/config.xml
  bundles/org.openhab.binding.shelly/src/main/resources/ESH-INF/i18n/shelly.properties
  bundles/org.openhab.binding.shelly/src/main/resources/ESH-INF/i18n/shelly_de.properties
  bundles/org.openhab.binding.shelly/src/main/resources/ESH-INF/thing/channels.xml
  bundles/org.openhab.binding.shelly/src/main/resources/ESH-INF/thing/device.xml
  bundles/org.openhab.binding.shelly/src/main/resources/ESH-INF/thing/lights.xml
  bundles/org.openhab.binding.shelly/src/main/resources/ESH-INF/thing/relay.xml
  bundles/org.openhab.binding.shelly/src/main/resources/ESH-INF/thing/sensor.xml
Labels: bug, enhancement

#5648 [cbus] CBus Binding initial contribution
  bundles/org.openhab.binding.cbus/.classpath
  bundles/org.openhab.binding.cbus/.project
  bundles/org.openhab.binding.cbus/NOTICE
  bundles/org.openhab.binding.cbus/README.md
  bundles/org.openhab.binding.cbus/lib/cgateinterface-1.1.0-JH-dev.jar
  bundles/org.openhab.binding.cbus/pom.xml
  bundles/org.openhab.binding.cbus/src/main/feature/feature.xml
  bundles/org.openhab.binding.cbus/src/main/java/org/openhab/binding/cbus/CBusBindingConstants.java
  bundles/org.openhab.binding.cbus/src/main/java/org/openhab/binding/cbus/handler/CBusCGateHandler.java
  bundles/org.openhab.binding.cbus/src/main/java/org/openhab/binding/cbus/handler/CBusDaliHandler.java
  bundles/org.openhab.binding.cbus/src/main/java/org/openhab/binding/cbus/handler/CBusGroupHandler.java
  bundles/org.openhab.binding.cbus/src/main/java/org/openhab/binding/cbus/handler/CBusLightHandler.java
  bundles/org.openhab.binding.cbus/src/main/java/org/openhab/binding/cbus/handler/CBusNetworkHandler.java
  bundles/org.openhab.binding.cbus/src/main/java/org/openhab/binding/cbus/handler/CBusTemperatureHandler.java
  bundles/org.openhab.binding.cbus/src/main/java/org/openhab/binding/cbus/handler/CBusTriggerHandler.java
  bundles/org.openhab.binding.cbus/src/main/java/org/openhab/binding/cbus/internal/CBusCGateConfiguration.java
  bundles/org.openhab.binding.cbus/src/main/java/org/openhab/binding/cbus/internal/CBusGroupConfiguration.java
  bundles/org.openhab.binding.cbus/src/main/java/org/openhab/binding/cbus/internal/CBusHandlerFactory.java
  bundles/org.openhab.binding.cbus/src/main/java/org/openhab/binding/cbus/internal/CBusNetworkConfiguration.java
  bundles/org.openhab.binding.cbus/src/main/java/org/openhab/binding/cbus/internal/CBusThreadPool.java
  bundles/org.openhab.binding.cbus/src/main/java/org/openhab/binding/cbus/internal/discovery/CBusGroupDiscovery.java
  bundles/org.openhab.binding.cbus/src/main/java/org/openhab/binding/cbus/internal/discovery/CBusNetworkDiscovery.java
  bundles/org.openhab.binding.cbus/src/main/resources/ESH-INF/binding/binding.xml
  bundles/org.openhab.binding.cbus/src/main/resources/ESH-INF/thing/bridge.xml
  bundles/org.openhab.binding.cbus/src/main/resources/ESH-INF/thing/thing-types.xml
  bundles/pom.xml
Labels: cre, new binding

#7416 [shelly] Don't auto-initialize when thing is removing
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api/ShellyHttpApi.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/handler/ShellyBaseHandler.java
Labels: bug

#7429 [ambientweather] Fix ws8482 indoor sensor
  bundles/org.openhab.binding.ambientweather/src/main/java/org/openhab/binding/ambientweather/internal/processor/Ws8482Processor.java
Labels: bug

#7431 [miio] Improve Yeelight Color channel
  bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/MiIoCommand.java
  bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/basic/ActionConditions.java
  bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/handler/MiIoBasicHandler.java
  bundles/org.openhab.binding.miio/src/main/resources/database/yeelink.light.color1.json
  bundles/org.openhab.binding.miio/src/test/java/org/openhab/binding/miio/internal/ActionConditionTest.java
Labels: enhancement

#7432 [modbus][sunspec] full inverter support
  bundles/org.openhab.binding.modbus.sunspec/src/main/java/org/openhab/binding/modbus/sunspec/internal/SunSpecConstants.java
  bundles/org.openhab.binding.modbus.sunspec/src/main/java/org/openhab/binding/modbus/sunspec/internal/SunSpecHandlerFactory.java
  bundles/org.openhab.binding.modbus.sunspec/src/main/java/org/openhab/binding/modbus/sunspec/internal/dto/InverterModelBlock.java
  bundles/org.openhab.binding.modbus.sunspec/src/main/java/org/openhab/binding/modbus/sunspec/internal/handler/AbstractSunSpecHandler.java
  bundles/org.openhab.binding.modbus.sunspec/src/main/java/org/openhab/binding/modbus/sunspec/internal/handler/InverterHandler.java
  bundles/org.openhab.binding.modbus.sunspec/src/main/java/org/openhab/binding/modbus/sunspec/internal/parser/InverterModelParser.java
  bundles/org.openhab.binding.modbus.sunspec/src/main/resources/ESH-INF/thing/inverter-channel-groups.xml
  bundles/org.openhab.binding.modbus.sunspec/src/main/resources/ESH-INF/thing/inverter-channel-types.xml
  bundles/org.openhab.binding.modbus.sunspec/src/main/resources/ESH-INF/thing/inverter-types.xml
Labels: enhancement

#7443 [sagercaster] Adding German translation
  bundles/org.openhab.binding.sagercaster/src/main/resources/ESH-INF/i18n/sagercaster_de.properties
  bundles/org.openhab.binding.sagercaster/src/main/resources/ESH-INF/i18n/sagercaster_fr.properties
Labels: translation

#7452 [miio] add gosund plug & Vacuum 1C STYTJ01ZHM
  bundles/org.openhab.binding.miio/README.md
  bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/MiIoDevices.java
  bundles/org.openhab.binding.miio/src/main/resources/database/cuco.plug.cp1-miot.json
  bundles/org.openhab.binding.miio/src/main/resources/database/dreame.vacuum.mc1808-miot.json
Labels: enhancement

#7456 [miio] fix parsing issue
  bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/MiIoInfoDTO.java
Labels: bug

#7457 [lutron] Add Caseta model option to virtualkeypad
  bundles/org.openhab.binding.lutron/README.md
  bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/handler/VirtualKeypadHandler.java
  bundles/org.openhab.binding.lutron/src/main/resources/ESH-INF/thing/thing-types.xml
Labels: enhancement

#7460 Removed dependency on 'org.apache.commons.codec'
  bundles/org.openhab.binding.freebox/src/main/java/org/openhab/binding/freebox/internal/api/FreeboxApiManager.java
  bundles/org.openhab.binding.loxone/src/main/java/org/openhab/binding/loxone/internal/security/LxWsSecurity.java
  bundles/org.openhab.binding.millheat/src/main/java/org/openhab/binding/millheat/internal/handler/MillheatAccountHandler.java
  itests/org.openhab.binding.mqtt.homeassistant.tests/itest.bndrun
  itests/org.openhab.binding.mqtt.homie.tests/itest.bndrun
  itests/org.openhab.io.mqttembeddedbroker.tests/itest.bndrun
Labels: infrastructure

#7462 [pjlink] Null characters fix
  bundles/org.openhab.binding.pjlinkdevice/src/main/java/org/openhab/binding/pjlinkdevice/internal/device/PJLinkDevice.java
Labels: external bug

#7441 [modbus][sunspec] Support for SunSpec meters
  bundles/org.openhab.binding.modbus.sunspec/src/main/java/org/openhab/binding/modbus/sunspec/internal/SunSpecConstants.java
  bundles/org.openhab.binding.modbus.sunspec/src/main/java/org/openhab/binding/modbus/sunspec/internal/SunSpecHandlerFactory.java
  bundles/org.openhab.binding.modbus.sunspec/src/main/java/org/openhab/binding/modbus/sunspec/internal/dto/MeterModelBlock.java
  bundles/org.openhab.binding.modbus.sunspec/src/main/java/org/openhab/binding/modbus/sunspec/internal/handler/AbstractSunSpecHandler.java
  bundles/org.openhab.binding.modbus.sunspec/src/main/java/org/openhab/binding/modbus/sunspec/internal/handler/MeterHandler.java
  bundles/org.openhab.binding.modbus.sunspec/src/main/java/org/openhab/binding/modbus/sunspec/internal/parser/MeterModelParser.java
  bundles/org.openhab.binding.modbus.sunspec/src/main/resources/ESH-INF/thing/meter-channel-groups.xml
  bundles/org.openhab.binding.modbus.sunspec/src/main/resources/ESH-INF/thing/meter-channel-types.xml
  bundles/org.openhab.binding.modbus.sunspec/src/main/resources/ESH-INF/thing/meter-types.xml
Labels: enhancement

#7418 [rfxcom] Added Cherubini blinds support
  bundles/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/messages/RFXComBlinds1Message.java
Labels: enhancement

#7465 [jdbc] Improve rebuildTableNames behavior
  bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/db/JdbcBaseDAO.java
  bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/JdbcMapper.java
Labels: bug

#7474 [mihome] Fix NPE, add null annotations and name threads
  bundles/org.openhab.binding.mihome/src/main/java/org/openhab/binding/mihome/internal/discovery/XiaomiBridgeDiscoveryService.java
  bundles/org.openhab.binding.mihome/src/main/java/org/openhab/binding/mihome/internal/handler/XiaomiBridgeHandler.java
  bundles/org.openhab.binding.mihome/src/main/java/org/openhab/binding/mihome/internal/socket/XiaomiBridgeSocket.java
  bundles/org.openhab.binding.mihome/src/main/java/org/openhab/binding/mihome/internal/socket/XiaomiDiscoverySocket.java
  bundles/org.openhab.binding.mihome/src/main/java/org/openhab/binding/mihome/internal/socket/XiaomiSocket.java
  bundles/org.openhab.binding.mihome/src/main/java/org/openhab/binding/mihome/internal/socket/XiaomiSocketListener.java
Labels: bug, community approved

#7178 [opensprinkler] Add current draw channel
  bundles/org.openhab.binding.opensprinkler/README.md
  bundles/org.openhab.binding.opensprinkler/src/main/java/org/openhab/binding/opensprinkler/internal/OpenSprinklerBindingConstants.java
  bundles/org.openhab.binding.opensprinkler/src/main/java/org/openhab/binding/opensprinkler/internal/api/OpenSprinklerApi.java
  bundles/org.openhab.binding.opensprinkler/src/main/java/org/openhab/binding/opensprinkler/internal/api/OpenSprinklerHttpApiV100.java
  bundles/org.openhab.binding.opensprinkler/src/main/java/org/openhab/binding/opensprinkler/internal/handler/OpenSprinklerDeviceHandler.java
  bundles/org.openhab.binding.opensprinkler/src/main/java/org/openhab/binding/opensprinkler/internal/model/NoCurrentDrawSensorException.java
Labels: enhancement

#7477 [coronastats] Use QuantityType instead of plain DecimalType
  bundles/org.openhab.binding.coronastats/src/main/java/org/openhab/binding/coronastats/internal/dto/CoronaStatsCases.java
  bundles/org.openhab.binding.coronastats/src/main/resources/ESH-INF/thing/channel-type.xml
Labels: enhancement

#7411 [hueemulation] Fixes HueEmulation DiscoveryIp not used
  bundles/org.openhab.io.hueemulation/README.md
  bundles/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/ConfigStore.java
  bundles/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/HueEmulationConfig.java
  bundles/org.openhab.io.hueemulation/src/main/resources/ESH-INF/config/config.xml
Labels: bug

#7472 [pjlink] use parameter-groups for better structure of thing parameters
  bundles/org.openhab.binding.pjlinkdevice/src/main/resources/ESH-INF/thing/thing-types.xml
Labels: enhancement

#7490 [insteon] Added support to 2472D OutletLinc Dimmer for LED On/Off, LED Brightness, Local Ramp Rate and Beep
  bundles/org.openhab.binding.insteon/src/main/resources/ESH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.insteon/src/main/resources/device_types.xml
Labels: enhancement

#7498 [ecobee] Improve initial setup instructions
  bundles/org.openhab.binding.ecobee/README.md
Labels: documentation

#7189 [alarmdecoder] Initial contribution
  CODEOWNERS
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.alarmdecoder/.classpath
  bundles/org.openhab.binding.alarmdecoder/.project
  bundles/org.openhab.binding.alarmdecoder/NOTICE
  bundles/org.openhab.binding.alarmdecoder/README.md
  bundles/org.openhab.binding.alarmdecoder/pom.xml
  bundles/org.openhab.binding.alarmdecoder/src/main/feature/feature.xml
  bundles/org.openhab.binding.alarmdecoder/src/main/java/org/openhab/binding/alarmdecoder/internal/AlarmDecoderBindingConstants.java
  bundles/org.openhab.binding.alarmdecoder/src/main/java/org/openhab/binding/alarmdecoder/internal/AlarmDecoderDiscoveryService.java
  bundles/org.openhab.binding.alarmdecoder/src/main/java/org/openhab/binding/alarmdecoder/internal/AlarmDecoderHandlerFactory.java
  bundles/org.openhab.binding.alarmdecoder/src/main/java/org/openhab/binding/alarmdecoder/internal/actions/BridgeActions.java
  bundles/org.openhab.binding.alarmdecoder/src/main/java/org/openhab/binding/alarmdecoder/internal/config/IPBridgeConfig.java
  bundles/org.openhab.binding.alarmdecoder/src/main/java/org/openhab/binding/alarmdecoder/internal/config/KeypadConfig.java
  bundles/org.openhab.binding.alarmdecoder/src/main/java/org/openhab/binding/alarmdecoder/internal/config/LRRConfig.java
  bundles/org.openhab.binding.alarmdecoder/src/main/java/org/openhab/binding/alarmdecoder/internal/config/RFZoneConfig.java
  bundles/org.openhab.binding.alarmdecoder/src/main/java/org/openhab/binding/alarmdecoder/internal/config/SerialBridgeConfig.java
  bundles/org.openhab.binding.alarmdecoder/src/main/java/org/openhab/binding/alarmdecoder/internal/config/ZoneConfig.java
  bundles/org.openhab.binding.alarmdecoder/src/main/java/org/openhab/binding/alarmdecoder/internal/handler/ADBridgeHandler.java
  bundles/org.openhab.binding.alarmdecoder/src/main/java/org/openhab/binding/alarmdecoder/internal/handler/ADThingHandler.java
  bundles/org.openhab.binding.alarmdecoder/src/main/java/org/openhab/binding/alarmdecoder/internal/handler/IPBridgeHandler.java
  bundles/org.openhab.binding.alarmdecoder/src/main/java/org/openhab/binding/alarmdecoder/internal/handler/KeypadHandler.java
  bundles/org.openhab.binding.alarmdecoder/src/main/java/org/openhab/binding/alarmdecoder/internal/handler/LRRHandler.java
  bundles/org.openhab.binding.alarmdecoder/src/main/java/org/openhab/binding/alarmdecoder/internal/handler/RFZoneHandler.java
  bundles/org.openhab.binding.alarmdecoder/src/main/java/org/openhab/binding/alarmdecoder/internal/handler/SerialBridgeHandler.java
  bundles/org.openhab.binding.alarmdecoder/src/main/java/org/openhab/binding/alarmdecoder/internal/handler/ZoneHandler.java
  bundles/org.openhab.binding.alarmdecoder/src/main/java/org/openhab/binding/alarmdecoder/internal/protocol/ADCommand.java
  bundles/org.openhab.binding.alarmdecoder/src/main/java/org/openhab/binding/alarmdecoder/internal/protocol/ADMessage.java
  bundles/org.openhab.binding.alarmdecoder/src/main/java/org/openhab/binding/alarmdecoder/internal/protocol/ADMsgType.java
  bundles/org.openhab.binding.alarmdecoder/src/main/java/org/openhab/binding/alarmdecoder/internal/protocol/EXPMessage.java
  bundles/org.openhab.binding.alarmdecoder/src/main/java/org/openhab/binding/alarmdecoder/internal/protocol/IntCommandMap.java
  bundles/org.openhab.binding.alarmdecoder/src/main/java/org/openhab/binding/alarmdecoder/internal/protocol/KeypadMessage.java
  bundles/org.openhab.binding.alarmdecoder/src/main/java/org/openhab/binding/alarmdecoder/internal/protocol/LRRMessage.java
  bundles/org.openhab.binding.alarmdecoder/src/main/java/org/openhab/binding/alarmdecoder/internal/protocol/RFXMessage.java
  bundles/org.openhab.binding.alarmdecoder/src/main/java/org/openhab/binding/alarmdecoder/internal/protocol/VersionMessage.java
  bundles/org.openhab.binding.alarmdecoder/src/main/resources/ESH-INF/binding/binding.xml
  bundles/org.openhab.binding.alarmdecoder/src/main/resources/ESH-INF/thing/thing-types.xml
  bundles/pom.xml
Labels: new binding, oh1 migration

#7506 [ecobee] Improve handling of access token expiration
  bundles/org.openhab.binding.ecobee/src/main/java/org/openhab/binding/ecobee/internal/api/EcobeeApi.java
Labels: bug
