Repository openhab/openhab-addons, pull requests merged in 2020-09, with the labels that each got.

#7656 [mqtt.homeassistant] Create trigger channels for stateless sensors
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/CChannel.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/ComponentSensor.java
Labels: enhancement

#8339 [Miio] Miio vacuum model extensions
  bundles/org.openhab.binding.miio/README.base.md
  bundles/org.openhab.binding.miio/README.md
  bundles/org.openhab.binding.miio/doc/miioBindingConfig.jpg
  bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/MiIoCommand.java
  bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/MiIoHandlerFactory.java
  bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/handler/MiIoVacuumHandler.java
  bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/robot/RobotCababilities.java
  bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/robot/StatusDTO.java
  bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/robot/StatusType.java
  bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/robot/VacuumErrorType.java
  bundles/org.openhab.binding.miio/src/main/resources/ESH-INF/thing/vacuumThing.xml
Labels: enhancement

#8381 [miio] Add support for viomi.vacuum.v8
  bundles/org.openhab.binding.miio/README.md
  bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/MiIoDevices.java
  bundles/org.openhab.binding.miio/src/main/resources/ESH-INF/thing/commonChannels.xml
  bundles/org.openhab.binding.miio/src/main/resources/database/viomi.vacuum.v8.json
Labels: enhancement

#8378 [Airquality] Binding update
  bundles/org.openhab.binding.airquality/README.md
  bundles/org.openhab.binding.airquality/src/main/java/org/openhab/binding/airquality/internal/AirQualityBindingConstants.java
  bundles/org.openhab.binding.airquality/src/main/java/org/openhab/binding/airquality/internal/AirQualityConfiguration.java
  bundles/org.openhab.binding.airquality/src/main/java/org/openhab/binding/airquality/internal/AirQualityHandlerFactory.java
  bundles/org.openhab.binding.airquality/src/main/java/org/openhab/binding/airquality/internal/discovery/AirQualityDiscoveryService.java
  bundles/org.openhab.binding.airquality/src/main/java/org/openhab/binding/airquality/internal/handler/AirQualityHandler.java
  bundles/org.openhab.binding.airquality/src/main/java/org/openhab/binding/airquality/internal/json/AirQualityJsonCity.java
  bundles/org.openhab.binding.airquality/src/main/java/org/openhab/binding/airquality/internal/json/AirQualityJsonData.java
  bundles/org.openhab.binding.airquality/src/main/java/org/openhab/binding/airquality/internal/json/AirQualityJsonIaqi.java
  bundles/org.openhab.binding.airquality/src/main/java/org/openhab/binding/airquality/internal/json/AirQualityJsonResponse.java
  bundles/org.openhab.binding.airquality/src/main/java/org/openhab/binding/airquality/internal/json/AirQualityJsonTime.java
  bundles/org.openhab.binding.airquality/src/main/java/org/openhab/binding/airquality/internal/json/AirQualityValue.java
  bundles/org.openhab.binding.airquality/src/main/java/org/openhab/binding/airquality/internal/json/Attribute.java
  bundles/org.openhab.binding.airquality/src/main/resources/ESH-INF/i18n/airquality_fr.properties
  bundles/org.openhab.binding.airquality/src/main/resources/ESH-INF/thing/thing-types.xml
Labels: enhancement

#8353 [innogysmarthome] Reconnect fixes (#8182)
  bundles/org.openhab.binding.innogysmarthome/src/main/java/org/openhab/binding/innogysmarthome/internal/InnogyBindingConstants.java
  bundles/org.openhab.binding.innogysmarthome/src/main/java/org/openhab/binding/innogysmarthome/internal/InnogyWebSocket.java
  bundles/org.openhab.binding.innogysmarthome/src/main/java/org/openhab/binding/innogysmarthome/internal/handler/InnogyBridgeHandler.java
  bundles/org.openhab.binding.innogysmarthome/src/main/java/org/openhab/binding/innogysmarthome/internal/handler/InnogyDeviceHandler.java
  bundles/org.openhab.binding.innogysmarthome/src/test/java/org/openhab/binding/innogysmarthome/internal/InnogyWebSocketTest.java
  bundles/org.openhab.binding.innogysmarthome/src/test/java/org/openhab/binding/innogysmarthome/internal/handler/InnogyBridgeHandlerTest.java
Labels: bug

#8222 [avmfritz] Added ThingActions to handle Boost and Window-Open modes for heating devices / groups
  bundles/org.openhab.binding.avmfritz/README.md
  bundles/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/actions/AVMFritzHeatingActions.java
  bundles/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/AVMFritzBindingConstants.java
  bundles/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/AVMFritzHandlerFactory.java
  bundles/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/actions/IAVMFritzHeatingActions.java
  bundles/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/discovery/AVMFritzDiscoveryService.java
  bundles/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/dto/AVMFritzBaseModel.java
  bundles/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/dto/HeatingModel.java
  bundles/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/handler/AVMFritzBaseBridgeHandler.java
  bundles/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/handler/AVMFritzBaseThingHandler.java
  bundles/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/handler/AVMFritzHeatingActionsHandler.java
  bundles/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/handler/AVMFritzHeatingDeviceHandler.java
  bundles/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/handler/AVMFritzHeatingGroupHandler.java
  bundles/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/handler/DeviceHandler.java
  bundles/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/handler/GroupHandler.java
  bundles/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/hardware/FritzAhaWebInterface.java
  bundles/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/hardware/callbacks/FritzAhaSetHeatingModeCallback.java
  bundles/org.openhab.binding.avmfritz/src/main/resources/ESH-INF/i18n/avmfritz.properties
  bundles/org.openhab.binding.avmfritz/src/main/resources/ESH-INF/i18n/avmfritz_de.properties
  bundles/org.openhab.binding.avmfritz/src/main/resources/ESH-INF/thing/channel-types.xml
  bundles/org.openhab.binding.avmfritz/src/main/resources/ESH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.avmfritz/src/test/java/org/openhab/binding/avmfritz/actions/AVMFritzHeatingActionsTest.java
  bundles/org.openhab.binding.avmfritz/src/test/java/org/openhab/binding/avmfritz/internal/dto/AVMFritzDeviceListModelTest.java
Labels: enhancement

#7651 [nuvo] Nuvo Whole House Audio Binding - initial contribution
  CODEOWNERS
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.nuvo/.classpath
  bundles/org.openhab.binding.nuvo/.project
  bundles/org.openhab.binding.nuvo/NOTICE
  bundles/org.openhab.binding.nuvo/README.md
  bundles/org.openhab.binding.nuvo/doc/nuvo_logo.png
  bundles/org.openhab.binding.nuvo/pom.xml
  bundles/org.openhab.binding.nuvo/src/main/feature/feature.xml
  bundles/org.openhab.binding.nuvo/src/main/java/org/openhab/binding/nuvo/internal/INuvoThingActions.java
  bundles/org.openhab.binding.nuvo/src/main/java/org/openhab/binding/nuvo/internal/NuvoBindingConstants.java
  bundles/org.openhab.binding.nuvo/src/main/java/org/openhab/binding/nuvo/internal/NuvoException.java
  bundles/org.openhab.binding.nuvo/src/main/java/org/openhab/binding/nuvo/internal/NuvoHandlerFactory.java
  bundles/org.openhab.binding.nuvo/src/main/java/org/openhab/binding/nuvo/internal/NuvoStateDescriptionOptionProvider.java
  bundles/org.openhab.binding.nuvo/src/main/java/org/openhab/binding/nuvo/internal/NuvoThingActions.java
  bundles/org.openhab.binding.nuvo/src/main/java/org/openhab/binding/nuvo/internal/communication/NuvoCommand.java
  bundles/org.openhab.binding.nuvo/src/main/java/org/openhab/binding/nuvo/internal/communication/NuvoConnector.java
  bundles/org.openhab.binding.nuvo/src/main/java/org/openhab/binding/nuvo/internal/communication/NuvoDefaultConnector.java
  bundles/org.openhab.binding.nuvo/src/main/java/org/openhab/binding/nuvo/internal/communication/NuvoEnum.java
  bundles/org.openhab.binding.nuvo/src/main/java/org/openhab/binding/nuvo/internal/communication/NuvoIpConnector.java
  bundles/org.openhab.binding.nuvo/src/main/java/org/openhab/binding/nuvo/internal/communication/NuvoMessageEvent.java
  bundles/org.openhab.binding.nuvo/src/main/java/org/openhab/binding/nuvo/internal/communication/NuvoMessageEventListener.java
  bundles/org.openhab.binding.nuvo/src/main/java/org/openhab/binding/nuvo/internal/communication/NuvoReaderThread.java
  bundles/org.openhab.binding.nuvo/src/main/java/org/openhab/binding/nuvo/internal/communication/NuvoSerialConnector.java
  bundles/org.openhab.binding.nuvo/src/main/java/org/openhab/binding/nuvo/internal/communication/NuvoStatusCodes.java
  bundles/org.openhab.binding.nuvo/src/main/java/org/openhab/binding/nuvo/internal/configuration/NuvoThingConfiguration.java
  bundles/org.openhab.binding.nuvo/src/main/java/org/openhab/binding/nuvo/internal/handler/NuvoHandler.java
  bundles/org.openhab.binding.nuvo/src/main/resources/ESH-INF/binding/binding.xml
  bundles/org.openhab.binding.nuvo/src/main/resources/ESH-INF/thing/channels.xml
  bundles/pom.xml
Labels: cre, new binding

#8368 [modbus] Some logging adjustments for data thing
  bundles/org.openhab.binding.modbus/src/main/java/org/openhab/binding/modbus/internal/handler/ModbusDataThingHandler.java
Labels: enhancement

#8367 [modbus] Modbus write types explanation
  bundles/org.openhab.binding.modbus/src/main/resources/ESH-INF/thing/thing-data.xml
  bundles/org.openhab.io.transport.modbus/src/test/java/org/openhab/io/transport/modbus/test/BitUtilitiesCommandToRegistersTest.java
Labels: enhancement

#7535 [pentair] Some improvements to the pentair documentation.
  bundles/org.openhab.binding.pentair/README.md
Labels: documentation

#7371 [monopriceaudio] Monoprice Whole House Amplifier Binding - initial contribution
  CODEOWNERS
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.monopriceaudio/.classpath
  bundles/org.openhab.binding.monopriceaudio/.project
  bundles/org.openhab.binding.monopriceaudio/NOTICE
  bundles/org.openhab.binding.monopriceaudio/README.md
  bundles/org.openhab.binding.monopriceaudio/pom.xml
  bundles/org.openhab.binding.monopriceaudio/src/main/feature/feature.xml
  bundles/org.openhab.binding.monopriceaudio/src/main/java/org/openhab/binding/monopriceaudio/internal/MonopriceAudioBindingConstants.java
  bundles/org.openhab.binding.monopriceaudio/src/main/java/org/openhab/binding/monopriceaudio/internal/MonopriceAudioException.java
  bundles/org.openhab.binding.monopriceaudio/src/main/java/org/openhab/binding/monopriceaudio/internal/MonopriceAudioHandlerFactory.java
  bundles/org.openhab.binding.monopriceaudio/src/main/java/org/openhab/binding/monopriceaudio/internal/MonopriceAudioStateDescriptionOptionProvider.java
  bundles/org.openhab.binding.monopriceaudio/src/main/java/org/openhab/binding/monopriceaudio/internal/communication/MonopriceAudioCommand.java
  bundles/org.openhab.binding.monopriceaudio/src/main/java/org/openhab/binding/monopriceaudio/internal/communication/MonopriceAudioConnector.java
  bundles/org.openhab.binding.monopriceaudio/src/main/java/org/openhab/binding/monopriceaudio/internal/communication/MonopriceAudioDefaultConnector.java
  bundles/org.openhab.binding.monopriceaudio/src/main/java/org/openhab/binding/monopriceaudio/internal/communication/MonopriceAudioIpConnector.java
  bundles/org.openhab.binding.monopriceaudio/src/main/java/org/openhab/binding/monopriceaudio/internal/communication/MonopriceAudioMessageEvent.java
  bundles/org.openhab.binding.monopriceaudio/src/main/java/org/openhab/binding/monopriceaudio/internal/communication/MonopriceAudioMessageEventListener.java
  bundles/org.openhab.binding.monopriceaudio/src/main/java/org/openhab/binding/monopriceaudio/internal/communication/MonopriceAudioReaderThread.java
  bundles/org.openhab.binding.monopriceaudio/src/main/java/org/openhab/binding/monopriceaudio/internal/communication/MonopriceAudioSerialConnector.java
  bundles/org.openhab.binding.monopriceaudio/src/main/java/org/openhab/binding/monopriceaudio/internal/communication/MonopriceAudioZone.java
  bundles/org.openhab.binding.monopriceaudio/src/main/java/org/openhab/binding/monopriceaudio/internal/configuration/MonopriceAudioThingConfiguration.java
  bundles/org.openhab.binding.monopriceaudio/src/main/java/org/openhab/binding/monopriceaudio/internal/dto/MonopriceAudioZoneDTO.java
  bundles/org.openhab.binding.monopriceaudio/src/main/java/org/openhab/binding/monopriceaudio/internal/handler/MonopriceAudioHandler.java
  bundles/org.openhab.binding.monopriceaudio/src/main/resources/ESH-INF/binding/binding.xml
  bundles/org.openhab.binding.monopriceaudio/src/main/resources/ESH-INF/thing/channels.xml
  bundles/pom.xml
Labels: cre, new binding

#8386 [modbus] Fix indentation in thing-data.xml breaking the build
  bundles/org.openhab.binding.modbus/src/main/resources/ESH-INF/thing/thing-data.xml
Labels: critical

#8246 [mqtt][homie] Implement non-retained and non-settable properties
  bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/values/OnOffValue.java
  bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/values/TextValue.java
  bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/values/Value.java
  bundles/org.openhab.binding.mqtt.homie/src/main/java/org/openhab/binding/mqtt/homie/internal/homie300/Property.java
Labels: bug

#8391 [nikohomecontrol] Fix Digital Black thermostat.
  bundles/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/protocol/nhc2/NikoHomeControlCommunication2.java
Labels: bug

#8354 [modbus] Add hints to potential problems on Modbus readout
  bundles/org.openhab.binding.modbus/README.md
Labels: documentation

#8392 [comfoair] documentation fixes and german i18n
  bundles/org.openhab.binding.comfoair/README.md
  bundles/org.openhab.binding.comfoair/src/main/resources/ESH-INF/i18n/comfoair_de.properties
Labels: documentation

#8383 [dsmr] Handle cosem values that a have a unit or not, related to smarty meters
  bundles/org.openhab.binding.dsmr/src/main/java/org/openhab/binding/dsmr/internal/device/SmartyDecrypter.java
  bundles/org.openhab.binding.dsmr/src/main/java/org/openhab/binding/dsmr/internal/device/cosem/CosemDecimal.java
  bundles/org.openhab.binding.dsmr/src/main/java/org/openhab/binding/dsmr/internal/device/cosem/CosemObjectType.java
  bundles/org.openhab.binding.dsmr/src/main/resources/ESH-INF/i18n/dsmr_nl.properties
  bundles/org.openhab.binding.dsmr/src/test/java/org/openhab/binding/dsmr/internal/device/p1telegram/P1TelegramParserTest.java
  bundles/org.openhab.binding.dsmr/src/test/java/org/openhab/binding/dsmr/internal/discovery/DSMRMeterDetectorTest.java
  bundles/org.openhab.binding.dsmr/src/test/resources/org/openhab/binding/dsmr/internal/.gitattributes
  bundles/org.openhab.binding.dsmr/src/test/resources/org/openhab/binding/dsmr/internal/smarty_with_units.telegram
Labels: bug

#8387 [miio] support for miot action commands
  bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/basic/ActionConditions.java
  bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/basic/MiIoDeviceAction.java
  bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/handler/MiIoBasicHandler.java
  bundles/org.openhab.binding.miio/src/main/resources/database/dreame.vacuum.mc1808-miot.json
Labels: enhancement

#8399 [miio] Fix for $value$ wrong at 2nd time
  bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/handler/MiIoBasicHandler.java
Labels: bug

#8408 [hue] Alert channel available for group thing
  bundles/org.openhab.binding.hue/README.md
Labels: documentation

#8410 [onkyo] Add support for TX-RZ900
  bundles/org.openhab.binding.onkyo/README.md
  bundles/org.openhab.binding.onkyo/src/main/java/org/openhab/binding/onkyo/internal/OnkyoModel.java
  bundles/org.openhab.binding.onkyo/src/main/resources/ESH-INF/thing/tx-rz900.xml
Labels: enhancement

#8405 [miio] add viomi vaccum v6 & v7
  bundles/org.openhab.binding.miio/README.md
  bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/MiIoDevices.java
  bundles/org.openhab.binding.miio/src/main/resources/ESH-INF/thing/commonChannels.xml
  bundles/org.openhab.binding.miio/src/main/resources/database/viomi.vacuum.v8.json
Labels: enhancement

#8414 [phc] Correct README
  bundles/org.openhab.binding.phc/README.md
Labels: documentation

#8252 [iammeter] Iammeter Binding initial contribution
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.iammeter/.classpath
  bundles/org.openhab.binding.iammeter/.project
  bundles/org.openhab.binding.iammeter/NOTICE
  bundles/org.openhab.binding.iammeter/README.md
  bundles/org.openhab.binding.iammeter/pom.xml
  bundles/org.openhab.binding.iammeter/src/main/feature/feature.xml
  bundles/org.openhab.binding.iammeter/src/main/java/org/openhab/binding/iammeter/internal/Iammeter3080THandler.java
  bundles/org.openhab.binding.iammeter/src/main/java/org/openhab/binding/iammeter/internal/IammeterBaseHandler.java
  bundles/org.openhab.binding.iammeter/src/main/java/org/openhab/binding/iammeter/internal/IammeterBindingConstants.java
  bundles/org.openhab.binding.iammeter/src/main/java/org/openhab/binding/iammeter/internal/IammeterConfiguration.java
  bundles/org.openhab.binding.iammeter/src/main/java/org/openhab/binding/iammeter/internal/IammeterHandler.java
  bundles/org.openhab.binding.iammeter/src/main/java/org/openhab/binding/iammeter/internal/IammeterHandlerFactory.java
  bundles/org.openhab.binding.iammeter/src/main/java/org/openhab/binding/iammeter/internal/IammeterWEM3080Channel.java
  bundles/org.openhab.binding.iammeter/src/main/java/org/openhab/binding/iammeter/internal/IammeterWEM3080TChannel.java
  bundles/org.openhab.binding.iammeter/src/main/resources/ESH-INF/binding/binding.xml
  bundles/org.openhab.binding.iammeter/src/main/resources/ESH-INF/config/config.xml
  bundles/org.openhab.binding.iammeter/src/main/resources/ESH-INF/thing/3080.xml
  bundles/org.openhab.binding.iammeter/src/main/resources/ESH-INF/thing/3080T.xml
  bundles/pom.xml
Labels: cre, new binding

#8362 [myStrom] Initial Contribution
  CODEOWNERS
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.mystrom/.classpath
  bundles/org.openhab.binding.mystrom/.project
  bundles/org.openhab.binding.mystrom/NOTICE
  bundles/org.openhab.binding.mystrom/README.md
  bundles/org.openhab.binding.mystrom/pom.xml
  bundles/org.openhab.binding.mystrom/src/main/feature/feature.xml
  bundles/org.openhab.binding.mystrom/src/main/java/org/openhab/binding/mystrom/internal/MyStromBindingConstants.java
  bundles/org.openhab.binding.mystrom/src/main/java/org/openhab/binding/mystrom/internal/MyStromConfiguration.java
  bundles/org.openhab.binding.mystrom/src/main/java/org/openhab/binding/mystrom/internal/MyStromException.java
  bundles/org.openhab.binding.mystrom/src/main/java/org/openhab/binding/mystrom/internal/MyStromHandler.java
  bundles/org.openhab.binding.mystrom/src/main/java/org/openhab/binding/mystrom/internal/MyStromHandlerFactory.java
  bundles/org.openhab.binding.mystrom/src/main/resources/ESH-INF/binding/binding.xml
  bundles/org.openhab.binding.mystrom/src/main/resources/ESH-INF/thing/thing-types.xml
  bundles/pom.xml
Labels: cre, new binding

#8163 [studer] Initial contribution
  CODEOWNERS
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.modbus.studer/.classpath
  bundles/org.openhab.binding.modbus.studer/.project
  bundles/org.openhab.binding.modbus.studer/NOTICE
  bundles/org.openhab.binding.modbus.studer/README.md
  bundles/org.openhab.binding.modbus.studer/doc/bsp.png
  bundles/org.openhab.binding.modbus.studer/doc/variostring.png
  bundles/org.openhab.binding.modbus.studer/doc/variotrack.png
  bundles/org.openhab.binding.modbus.studer/doc/xtender.png
  bundles/org.openhab.binding.modbus.studer/pom.xml
  bundles/org.openhab.binding.modbus.studer/src/main/feature/feature.xml
  bundles/org.openhab.binding.modbus.studer/src/main/java/org/openhab/binding/modbus/studer/internal/StuderBindingConstants.java
  bundles/org.openhab.binding.modbus.studer/src/main/java/org/openhab/binding/modbus/studer/internal/StuderConfiguration.java
  bundles/org.openhab.binding.modbus.studer/src/main/java/org/openhab/binding/modbus/studer/internal/StuderHandler.java
  bundles/org.openhab.binding.modbus.studer/src/main/java/org/openhab/binding/modbus/studer/internal/StuderHandlerFactory.java
  bundles/org.openhab.binding.modbus.studer/src/main/java/org/openhab/binding/modbus/studer/internal/StuderParser.java
  bundles/org.openhab.binding.modbus.studer/src/main/resources/ESH-INF/thing/BSP-channel-types.xml
  bundles/org.openhab.binding.modbus.studer/src/main/resources/ESH-INF/thing/Common-channel-types.xml
  bundles/org.openhab.binding.modbus.studer/src/main/resources/ESH-INF/thing/VarioTrack-channel-types.xml
  bundles/org.openhab.binding.modbus.studer/src/main/resources/ESH-INF/thing/VariotString-channel-types.xml
  bundles/org.openhab.binding.modbus.studer/src/main/resources/ESH-INF/thing/Xtender-channel-types.xml
  bundles/org.openhab.binding.modbus.studer/src/main/resources/ESH-INF/thing/thing-types.xml
  bundles/pom.xml
Labels: cre, new binding

#8416 Use renamed FilterCriteria methods
  bundles/org.openhab.persistence.dynamodb/src/main/java/org/openhab/persistence/dynamodb/internal/DynamoDBQueryUtils.java
  bundles/org.openhab.persistence.influxdb/src/main/java/org/openhab/persistence/influxdb/InfluxDBPersistenceService.java
  bundles/org.openhab.persistence.influxdb/src/main/java/org/openhab/persistence/influxdb/internal/influx1/Influx1FilterCriteriaQueryCreatorImpl.java
  bundles/org.openhab.persistence.influxdb/src/main/java/org/openhab/persistence/influxdb/internal/influx2/Influx2FilterCriteriaQueryCreatorImpl.java
  bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/db/JdbcBaseDAO.java
  bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/db/JdbcDerbyDAO.java
  bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/db/JdbcPostgresqlDAO.java
  bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/utils/StringUtilsExt.java
  bundles/org.openhab.persistence.jpa/src/main/java/org/openhab/persistence/jpa/internal/JpaPersistenceService.java
  bundles/org.openhab.persistence.mongodb/src/main/java/org/openhab/persistence/mongodb/internal/MongoDBPersistenceService.java
  bundles/org.openhab.persistence.rrd4j/src/main/java/org/openhab/persistence/rrd4j/internal/RRD4jPersistenceService.java
Labels: oh3

#8423 [max] Revert of #8418 and move standard max tests to binding
  bundles/org.openhab.binding.max/src/main/java/org/openhab/binding/max/internal/command/MCommand.java
  bundles/org.openhab.binding.max/src/main/java/org/openhab/binding/max/internal/command/SCommand.java
  bundles/org.openhab.binding.max/src/main/java/org/openhab/binding/max/internal/command/SConfigCommand.java
  bundles/org.openhab.binding.max/src/main/java/org/openhab/binding/max/internal/command/TCommand.java
  bundles/org.openhab.binding.max/src/main/java/org/openhab/binding/max/internal/message/CMessage.java
  bundles/org.openhab.binding.max/src/main/java/org/openhab/binding/max/internal/message/LMessage.java
  bundles/org.openhab.binding.max/src/main/java/org/openhab/binding/max/internal/message/MMessage.java
  bundles/org.openhab.binding.max/src/main/java/org/openhab/binding/max/internal/message/NMessage.java
  bundles/org.openhab.binding.max/src/test/java/org/openhab/binding/max/internal/command/FCommandTest.java
  bundles/org.openhab.binding.max/src/test/java/org/openhab/binding/max/internal/command/MCommandTest.java
  bundles/org.openhab.binding.max/src/test/java/org/openhab/binding/max/internal/command/SCommandTest.java
  bundles/org.openhab.binding.max/src/test/java/org/openhab/binding/max/internal/command/SConfigCommandTest.java
  bundles/org.openhab.binding.max/src/test/java/org/openhab/binding/max/internal/command/TCommandTest.java
  bundles/org.openhab.binding.max/src/test/java/org/openhab/binding/max/internal/command/ZCommandTest.java
  bundles/org.openhab.binding.max/src/test/java/org/openhab/binding/max/internal/message/CMessageTest.java
  bundles/org.openhab.binding.max/src/test/java/org/openhab/binding/max/internal/message/ConfigurationTest.java
  bundles/org.openhab.binding.max/src/test/java/org/openhab/binding/max/internal/message/FMessageTest.java
  bundles/org.openhab.binding.max/src/test/java/org/openhab/binding/max/internal/message/HMessageTest.java
  bundles/org.openhab.binding.max/src/test/java/org/openhab/binding/max/internal/message/LMessageTest.java
  bundles/org.openhab.binding.max/src/test/java/org/openhab/binding/max/internal/message/MMessageTest.java
  bundles/org.openhab.binding.max/src/test/java/org/openhab/binding/max/internal/message/MessageProcessorTest.java
  bundles/org.openhab.binding.max/src/test/java/org/openhab/binding/max/internal/message/NMessageTest.java
  bundles/org.openhab.binding.max/src/test/java/org/openhab/binding/max/internal/message/SMessageTest.java
  bundles/org.openhab.binding.max/src/test/java/org/openhab/binding/max/internal/message/UtilsTest.java
Labels: critical

#7899 [nzwateralerts] New Zealand Water Alerts Binding initial contribution
  CODEOWNERS
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.nzwateralerts/.classpath
  bundles/org.openhab.binding.nzwateralerts/.project
  bundles/org.openhab.binding.nzwateralerts/NOTICE
  bundles/org.openhab.binding.nzwateralerts/README.md
  bundles/org.openhab.binding.nzwateralerts/pom.xml
  bundles/org.openhab.binding.nzwateralerts/src/main/feature/feature.xml
  bundles/org.openhab.binding.nzwateralerts/src/main/java/org/openhab/binding/nzwateralerts/internal/NZWaterAlertsBindingConstants.java
  bundles/org.openhab.binding.nzwateralerts/src/main/java/org/openhab/binding/nzwateralerts/internal/NZWaterAlertsConfiguration.java
  bundles/org.openhab.binding.nzwateralerts/src/main/java/org/openhab/binding/nzwateralerts/internal/api/BeWaterWise.java
  bundles/org.openhab.binding.nzwateralerts/src/main/java/org/openhab/binding/nzwateralerts/internal/api/NapierCityCouncil.java
  bundles/org.openhab.binding.nzwateralerts/src/main/java/org/openhab/binding/nzwateralerts/internal/api/SmartWater.java
  bundles/org.openhab.binding.nzwateralerts/src/main/java/org/openhab/binding/nzwateralerts/internal/api/TaupoDistrictCouncil.java
  bundles/org.openhab.binding.nzwateralerts/src/main/java/org/openhab/binding/nzwateralerts/internal/api/WaterAlertWebClient.java
  bundles/org.openhab.binding.nzwateralerts/src/main/java/org/openhab/binding/nzwateralerts/internal/api/WaterWebService.java
  bundles/org.openhab.binding.nzwateralerts/src/main/java/org/openhab/binding/nzwateralerts/internal/binder/NZWaterAlertsBinder.java
  bundles/org.openhab.binding.nzwateralerts/src/main/java/org/openhab/binding/nzwateralerts/internal/binder/NZWaterAlertsBinderListener.java
  bundles/org.openhab.binding.nzwateralerts/src/main/java/org/openhab/binding/nzwateralerts/internal/handler/NZWaterAlertsHandler.java
  bundles/org.openhab.binding.nzwateralerts/src/main/java/org/openhab/binding/nzwateralerts/internal/handler/NZWaterAlertsHandlerFactory.java
  bundles/org.openhab.binding.nzwateralerts/src/main/resources/ESH-INF/binding/binding.xml
  bundles/org.openhab.binding.nzwateralerts/src/main/resources/ESH-INF/thing/thing-types.xml
  bundles/pom.xml
Labels: cre, new binding

#8424 [max] improve setchannel definition
  bundles/org.openhab.binding.max/src/main/resources/ESH-INF/thing/thing-types.xml
Labels: enhancement

#8422 Improve feature file aggregation
  features/openhab-addons/src/main/resources/footer.xml
  pom.xml
Labels: infrastructure

#8426 [smhi][OH3] Fix bug running on OH3
  bundles/org.openhab.binding.smhi/src/main/java/org/openhab/binding/smhi/internal/SmhiConnector.java
Labels: bug

#8428 [nikohomecontrol] Check bridge status when thing ready to go online.
  bundles/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/handler/NikoHomeControlActionHandler.java
  bundles/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/handler/NikoHomeControlEnergyMeterHandler.java
  bundles/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/handler/NikoHomeControlThermostatHandler.java
Labels: bug

#8393 [radiothermostat] Added Absolute Setpoint Mode
  bundles/org.openhab.binding.radiothermostat/README.md
  bundles/org.openhab.binding.radiothermostat/src/main/java/org/openhab/binding/radiothermostat/internal/RadioThermostatConfiguration.java
  bundles/org.openhab.binding.radiothermostat/src/main/java/org/openhab/binding/radiothermostat/internal/RadioThermostatStateDescriptionProvider.java
  bundles/org.openhab.binding.radiothermostat/src/main/java/org/openhab/binding/radiothermostat/internal/handler/RadioThermostatHandler.java
  bundles/org.openhab.binding.radiothermostat/src/main/resources/ESH-INF/thing/thing-types.xml
Labels: enhancement

#8442 Upgrade Travis CI to use Ubuntu 18.04 and fix warnings/caching (2.5.x)
  .travis.yml
Labels: infrastructure

#8432 [smaenergymeter] Add per-phase channels
  bundles/org.openhab.binding.smaenergymeter/README.md
  bundles/org.openhab.binding.smaenergymeter/src/main/java/org/openhab/binding/smaenergymeter/internal/SMAEnergyMeterBindingConstants.java
  bundles/org.openhab.binding.smaenergymeter/src/main/java/org/openhab/binding/smaenergymeter/internal/handler/EnergyMeter.java
  bundles/org.openhab.binding.smaenergymeter/src/main/java/org/openhab/binding/smaenergymeter/internal/handler/SMAEnergyMeterHandler.java
  bundles/org.openhab.binding.smaenergymeter/src/main/resources/ESH-INF/thing/energyMeter.xml
Labels: enhancement

#8444 [satel] Add support for event type 32
  bundles/org.openhab.binding.satel/README.md
  bundles/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/handler/SatelEventLogHandler.java
Labels: enhancement

#8303 [gree] Add channel for temperature sensor
  bundles/org.openhab.binding.gree/README.md
  bundles/org.openhab.binding.gree/src/main/java/org/openhab/binding/gree/internal/GreeBindingConstants.java
  bundles/org.openhab.binding.gree/src/main/java/org/openhab/binding/gree/internal/GreeConfiguration.java
  bundles/org.openhab.binding.gree/src/main/java/org/openhab/binding/gree/internal/handler/GreeAirDevice.java
  bundles/org.openhab.binding.gree/src/main/java/org/openhab/binding/gree/internal/handler/GreeHandler.java
  bundles/org.openhab.binding.gree/src/main/resources/ESH-INF/i18n/gree.properties
  bundles/org.openhab.binding.gree/src/main/resources/ESH-INF/i18n/gree_DE.properties
  bundles/org.openhab.binding.gree/src/main/resources/ESH-INF/thing/thing-types.xml
Labels: enhancement

#7768 [tacmi] Initial push of OpenHAB 2 ported tacmi binding
  CODEOWNERS
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.tacmi/.classpath
  bundles/org.openhab.binding.tacmi/.project
  bundles/org.openhab.binding.tacmi/NOTICE
  bundles/org.openhab.binding.tacmi/README.md
  bundles/org.openhab.binding.tacmi/doc/images/channel-object-details.png
  bundles/org.openhab.binding.tacmi/doc/images/operation-mode-values.png
  bundles/org.openhab.binding.tacmi/doc/images/sample-with-heating-circuit.png
  bundles/org.openhab.binding.tacmi/pom.xml
  bundles/org.openhab.binding.tacmi/src/main/feature/feature.xml
  bundles/org.openhab.binding.tacmi/src/main/java/org/openhab/binding/tacmi/internal/TACmiBindingConstants.java
  bundles/org.openhab.binding.tacmi/src/main/java/org/openhab/binding/tacmi/internal/TACmiChannelTypeProvider.java
  bundles/org.openhab.binding.tacmi/src/main/java/org/openhab/binding/tacmi/internal/TACmiHandlerFactory.java
  bundles/org.openhab.binding.tacmi/src/main/java/org/openhab/binding/tacmi/internal/TACmiMeasureType.java
  bundles/org.openhab.binding.tacmi/src/main/java/org/openhab/binding/tacmi/internal/coe/PodData.java
  bundles/org.openhab.binding.tacmi/src/main/java/org/openhab/binding/tacmi/internal/coe/PodDataOutgoing.java
  bundles/org.openhab.binding.tacmi/src/main/java/org/openhab/binding/tacmi/internal/coe/PodIdentifier.java
  bundles/org.openhab.binding.tacmi/src/main/java/org/openhab/binding/tacmi/internal/coe/TACmiChannelConfiguration.java
  bundles/org.openhab.binding.tacmi/src/main/java/org/openhab/binding/tacmi/internal/coe/TACmiChannelConfigurationAnalog.java
  bundles/org.openhab.binding.tacmi/src/main/java/org/openhab/binding/tacmi/internal/coe/TACmiChannelConfigurationDigital.java
  bundles/org.openhab.binding.tacmi/src/main/java/org/openhab/binding/tacmi/internal/coe/TACmiCoEBridgeHandler.java
  bundles/org.openhab.binding.tacmi/src/main/java/org/openhab/binding/tacmi/internal/coe/TACmiConfiguration.java
  bundles/org.openhab.binding.tacmi/src/main/java/org/openhab/binding/tacmi/internal/coe/TACmiHandler.java
  bundles/org.openhab.binding.tacmi/src/main/java/org/openhab/binding/tacmi/internal/message/AnalogMessage.java
  bundles/org.openhab.binding.tacmi/src/main/java/org/openhab/binding/tacmi/internal/message/AnalogValue.java
  bundles/org.openhab.binding.tacmi/src/main/java/org/openhab/binding/tacmi/internal/message/DigitalMessage.java
  bundles/org.openhab.binding.tacmi/src/main/java/org/openhab/binding/tacmi/internal/message/Message.java
  bundles/org.openhab.binding.tacmi/src/main/java/org/openhab/binding/tacmi/internal/message/MessageType.java
  bundles/org.openhab.binding.tacmi/src/main/java/org/openhab/binding/tacmi/internal/schema/ApiPageEntry.java
  bundles/org.openhab.binding.tacmi/src/main/java/org/openhab/binding/tacmi/internal/schema/ApiPageParser.java
  bundles/org.openhab.binding.tacmi/src/main/java/org/openhab/binding/tacmi/internal/schema/ChangerX2Entry.java
  bundles/org.openhab.binding.tacmi/src/main/java/org/openhab/binding/tacmi/internal/schema/ChangerX2Parser.java
  bundles/org.openhab.binding.tacmi/src/main/java/org/openhab/binding/tacmi/internal/schema/TACmiSchemaConfiguration.java
  bundles/org.openhab.binding.tacmi/src/main/java/org/openhab/binding/tacmi/internal/schema/TACmiSchemaHandler.java
  bundles/org.openhab.binding.tacmi/src/main/resources/ESH-INF/binding/binding.xml
  bundles/org.openhab.binding.tacmi/src/main/resources/ESH-INF/thing/bridge.xml
  bundles/org.openhab.binding.tacmi/src/main/resources/ESH-INF/thing/thing-types.xml
  bundles/pom.xml
Labels: cre, new binding, oh1 migration

#8453 Fixes missing bindings from bom pom.xml
  bom/openhab-addons/pom.xml
Labels: infrastructure

#8459 [evohome] Minor clarification to the README.md
  bundles/org.openhab.binding.evohome/README.md
Labels: documentation

#8461 [modbus] Fix for polling that stops
  bundles/org.openhab.io.transport.modbus/src/main/java/org/openhab/io/transport/modbus/internal/ModbusPoolConfig.java
Labels: bug

#8440 [nuki] Add smart lock door sensor state as new channel (#8438)
  bundles/org.openhab.binding.nuki/README.md
  bundles/org.openhab.binding.nuki/src/main/java/org/openhab/binding/nuki/internal/NukiBindingConstants.java
  bundles/org.openhab.binding.nuki/src/main/java/org/openhab/binding/nuki/internal/dataexchange/BridgeLockStateResponse.java
  bundles/org.openhab.binding.nuki/src/main/java/org/openhab/binding/nuki/internal/dataexchange/NukiApiServlet.java
  bundles/org.openhab.binding.nuki/src/main/java/org/openhab/binding/nuki/internal/dto/BridgeApiLockStateDto.java
  bundles/org.openhab.binding.nuki/src/main/java/org/openhab/binding/nuki/internal/dto/BridgeApiLockStateRequestDto.java
  bundles/org.openhab.binding.nuki/src/main/java/org/openhab/binding/nuki/internal/handler/NukiSmartLockHandler.java
  bundles/org.openhab.binding.nuki/src/main/resources/ESH-INF/thing/thing-types.xml
Labels: enhancement

#6990 [jablotron] Jablotron binding initial contribution
  CODEOWNERS
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.jablotron/.classpath
  bundles/org.openhab.binding.jablotron/.project
  bundles/org.openhab.binding.jablotron/NOTICE
  bundles/org.openhab.binding.jablotron/README.md
  bundles/org.openhab.binding.jablotron/pom.xml
  bundles/org.openhab.binding.jablotron/src/main/feature/feature.xml
  bundles/org.openhab.binding.jablotron/src/main/java/org/openhab/binding/jablotron/JablotronBindingConstants.java
  bundles/org.openhab.binding.jablotron/src/main/java/org/openhab/binding/jablotron/internal/JablotronHandlerFactory.java
  bundles/org.openhab.binding.jablotron/src/main/java/org/openhab/binding/jablotron/internal/config/JablotronBridgeConfig.java
  bundles/org.openhab.binding.jablotron/src/main/java/org/openhab/binding/jablotron/internal/config/JablotronDeviceConfig.java
  bundles/org.openhab.binding.jablotron/src/main/java/org/openhab/binding/jablotron/internal/discovery/JablotronDiscoveryService.java
  bundles/org.openhab.binding.jablotron/src/main/java/org/openhab/binding/jablotron/internal/handler/JablotronAlarmHandler.java
  bundles/org.openhab.binding.jablotron/src/main/java/org/openhab/binding/jablotron/internal/handler/JablotronBridgeHandler.java
  bundles/org.openhab.binding.jablotron/src/main/java/org/openhab/binding/jablotron/internal/handler/JablotronJa100FHandler.java
  bundles/org.openhab.binding.jablotron/src/main/java/org/openhab/binding/jablotron/internal/handler/JablotronJa100Handler.java
  bundles/org.openhab.binding.jablotron/src/main/java/org/openhab/binding/jablotron/internal/handler/JablotronOasisHandler.java
  bundles/org.openhab.binding.jablotron/src/main/java/org/openhab/binding/jablotron/internal/model/JablotronControlResponse.java
  bundles/org.openhab.binding.jablotron/src/main/java/org/openhab/binding/jablotron/internal/model/JablotronData.java
  bundles/org.openhab.binding.jablotron/src/main/java/org/openhab/binding/jablotron/internal/model/JablotronDataUpdateResponse.java
  bundles/org.openhab.binding.jablotron/src/main/java/org/openhab/binding/jablotron/internal/model/JablotronDiscoveredService.java
  bundles/org.openhab.binding.jablotron/src/main/java/org/openhab/binding/jablotron/internal/model/JablotronGetEventHistoryResponse.java
  bundles/org.openhab.binding.jablotron/src/main/java/org/openhab/binding/jablotron/internal/model/JablotronGetServiceData.java
  bundles/org.openhab.binding.jablotron/src/main/java/org/openhab/binding/jablotron/internal/model/JablotronGetServiceResponse.java
  bundles/org.openhab.binding.jablotron/src/main/java/org/openhab/binding/jablotron/internal/model/JablotronHistoryData.java
  bundles/org.openhab.binding.jablotron/src/main/java/org/openhab/binding/jablotron/internal/model/JablotronHistoryDataEvent.java
  bundles/org.openhab.binding.jablotron/src/main/java/org/openhab/binding/jablotron/internal/model/JablotronLoginResponse.java
  bundles/org.openhab.binding.jablotron/src/main/java/org/openhab/binding/jablotron/internal/model/JablotronService.java
  bundles/org.openhab.binding.jablotron/src/main/java/org/openhab/binding/jablotron/internal/model/JablotronServiceData.java
  bundles/org.openhab.binding.jablotron/src/main/java/org/openhab/binding/jablotron/internal/model/JablotronServiceDetail.java
  bundles/org.openhab.binding.jablotron/src/main/java/org/openhab/binding/jablotron/internal/model/JablotronServiceDetailSegment.java
  bundles/org.openhab.binding.jablotron/src/main/java/org/openhab/binding/jablotron/internal/model/JablotronServiceDetailSegmentInfo.java
  bundles/org.openhab.binding.jablotron/src/main/java/org/openhab/binding/jablotron/internal/model/ja100f/JablotronGetPGData.java
  bundles/org.openhab.binding.jablotron/src/main/java/org/openhab/binding/jablotron/internal/model/ja100f/JablotronGetPGResponse.java
  bundles/org.openhab.binding.jablotron/src/main/java/org/openhab/binding/jablotron/internal/model/ja100f/JablotronGetSectionsData.java
  bundles/org.openhab.binding.jablotron/src/main/java/org/openhab/binding/jablotron/internal/model/ja100f/JablotronGetSectionsResponse.java
  bundles/org.openhab.binding.jablotron/src/main/java/org/openhab/binding/jablotron/internal/model/ja100f/JablotronSection.java
  bundles/org.openhab.binding.jablotron/src/main/java/org/openhab/binding/jablotron/internal/model/ja100f/JablotronState.java
  bundles/org.openhab.binding.jablotron/src/main/resources/ESH-INF/binding/binding.xml
  bundles/org.openhab.binding.jablotron/src/main/resources/ESH-INF/config/config.xml
  bundles/org.openhab.binding.jablotron/src/main/resources/ESH-INF/thing/bridge.xml
  bundles/org.openhab.binding.jablotron/src/main/resources/ESH-INF/thing/channels.xml
  bundles/org.openhab.binding.jablotron/src/main/resources/ESH-INF/thing/ja100.xml
  bundles/org.openhab.binding.jablotron/src/main/resources/ESH-INF/thing/ja100f.xml
  bundles/org.openhab.binding.jablotron/src/main/resources/ESH-INF/thing/oasis.xml
  bundles/pom.xml
Labels: new binding

#8228 [modbus] Update README.md
  bundles/org.openhab.binding.modbus/README.md
Labels: documentation

#5457 [gce] GCE Binding initial contribution
  CODEOWNERS
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.gce/.classpath
  bundles/org.openhab.binding.gce/.project
  bundles/org.openhab.binding.gce/NOTICE
  bundles/org.openhab.binding.gce/README.md
  bundles/org.openhab.binding.gce/pom.xml
  bundles/org.openhab.binding.gce/src/main/feature/feature.xml
  bundles/org.openhab.binding.gce/src/main/java/org/openhab/binding/gce/internal/GCEBindingConstants.java
  bundles/org.openhab.binding.gce/src/main/java/org/openhab/binding/gce/internal/GCEHandlerFactory.java
  bundles/org.openhab.binding.gce/src/main/java/org/openhab/binding/gce/internal/action/IIpx800Actions.java
  bundles/org.openhab.binding.gce/src/main/java/org/openhab/binding/gce/internal/action/Ipx800Actions.java
  bundles/org.openhab.binding.gce/src/main/java/org/openhab/binding/gce/internal/config/AnalogInputConfiguration.java
  bundles/org.openhab.binding.gce/src/main/java/org/openhab/binding/gce/internal/config/DigitalInputConfiguration.java
  bundles/org.openhab.binding.gce/src/main/java/org/openhab/binding/gce/internal/config/Ipx800Configuration.java
  bundles/org.openhab.binding.gce/src/main/java/org/openhab/binding/gce/internal/config/RelayOutputConfiguration.java
  bundles/org.openhab.binding.gce/src/main/java/org/openhab/binding/gce/internal/handler/Ipx800DeviceConnector.java
  bundles/org.openhab.binding.gce/src/main/java/org/openhab/binding/gce/internal/handler/Ipx800EventListener.java
  bundles/org.openhab.binding.gce/src/main/java/org/openhab/binding/gce/internal/handler/Ipx800v3Handler.java
  bundles/org.openhab.binding.gce/src/main/java/org/openhab/binding/gce/internal/model/M2MMessageParser.java
  bundles/org.openhab.binding.gce/src/main/java/org/openhab/binding/gce/internal/model/PortData.java
  bundles/org.openhab.binding.gce/src/main/java/org/openhab/binding/gce/internal/model/PortDefinition.java
  bundles/org.openhab.binding.gce/src/main/java/org/openhab/binding/gce/internal/model/StatusFileInterpreter.java
  bundles/org.openhab.binding.gce/src/main/resources/ESH-INF/binding/binding.xml
  bundles/org.openhab.binding.gce/src/main/resources/ESH-INF/config/gceConfig.xml
  bundles/org.openhab.binding.gce/src/main/resources/ESH-INF/thing/channels.xml
  bundles/org.openhab.binding.gce/src/main/resources/ESH-INF/thing/ipx800v3.xml
  bundles/pom.xml
Labels: cre, new binding, oh1 migration

#7568 [kaleidescape] Kaleidescape Movie Player Binding - initial contribution
  CODEOWNERS
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.kaleidescape/.classpath
  bundles/org.openhab.binding.kaleidescape/.project
  bundles/org.openhab.binding.kaleidescape/NOTICE
  bundles/org.openhab.binding.kaleidescape/README.md
  bundles/org.openhab.binding.kaleidescape/doc/Kaleidescape_Logo.png
  bundles/org.openhab.binding.kaleidescape/pom.xml
  bundles/org.openhab.binding.kaleidescape/src/main/feature/feature.xml
  bundles/org.openhab.binding.kaleidescape/src/main/java/org/openhab/binding/kaleidescape/internal/IKaleidescapeThingActions.java
  bundles/org.openhab.binding.kaleidescape/src/main/java/org/openhab/binding/kaleidescape/internal/KaleidescapeBindingConstants.java
  bundles/org.openhab.binding.kaleidescape/src/main/java/org/openhab/binding/kaleidescape/internal/KaleidescapeException.java
  bundles/org.openhab.binding.kaleidescape/src/main/java/org/openhab/binding/kaleidescape/internal/KaleidescapeHandlerFactory.java
  bundles/org.openhab.binding.kaleidescape/src/main/java/org/openhab/binding/kaleidescape/internal/KaleidescapeThingActions.java
  bundles/org.openhab.binding.kaleidescape/src/main/java/org/openhab/binding/kaleidescape/internal/communication/KaleidescapeConnector.java
  bundles/org.openhab.binding.kaleidescape/src/main/java/org/openhab/binding/kaleidescape/internal/communication/KaleidescapeDefaultConnector.java
  bundles/org.openhab.binding.kaleidescape/src/main/java/org/openhab/binding/kaleidescape/internal/communication/KaleidescapeFormatter.java
  bundles/org.openhab.binding.kaleidescape/src/main/java/org/openhab/binding/kaleidescape/internal/communication/KaleidescapeIpConnector.java
  bundles/org.openhab.binding.kaleidescape/src/main/java/org/openhab/binding/kaleidescape/internal/communication/KaleidescapeMessageEvent.java
  bundles/org.openhab.binding.kaleidescape/src/main/java/org/openhab/binding/kaleidescape/internal/communication/KaleidescapeMessageEventListener.java
  bundles/org.openhab.binding.kaleidescape/src/main/java/org/openhab/binding/kaleidescape/internal/communication/KaleidescapeReaderThread.java
  bundles/org.openhab.binding.kaleidescape/src/main/java/org/openhab/binding/kaleidescape/internal/communication/KaleidescapeSerialConnector.java
  bundles/org.openhab.binding.kaleidescape/src/main/java/org/openhab/binding/kaleidescape/internal/communication/KaleidescapeStatusCodes.java
  bundles/org.openhab.binding.kaleidescape/src/main/java/org/openhab/binding/kaleidescape/internal/configuration/KaleidescapeThingConfiguration.java
  bundles/org.openhab.binding.kaleidescape/src/main/java/org/openhab/binding/kaleidescape/internal/discovery/KaleidescapeDiscoveryJob.java
  bundles/org.openhab.binding.kaleidescape/src/main/java/org/openhab/binding/kaleidescape/internal/discovery/KaleidescapeDiscoveryService.java
  bundles/org.openhab.binding.kaleidescape/src/main/java/org/openhab/binding/kaleidescape/internal/handler/KaleidescapeHandler.java
  bundles/org.openhab.binding.kaleidescape/src/main/java/org/openhab/binding/kaleidescape/internal/handler/KaleidescapeMessageHandler.java
  bundles/org.openhab.binding.kaleidescape/src/main/resources/ESH-INF/binding/binding.xml
  bundles/org.openhab.binding.kaleidescape/src/main/resources/ESH-INF/config/config.xml
  bundles/org.openhab.binding.kaleidescape/src/main/resources/ESH-INF/thing/channels.xml
  bundles/pom.xml
Labels: cre, new binding

#8471 [shelly] Bug Fixes for Sensor Action events and EM3's accumulatedTotalKWH channel
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api/ShellyDeviceProfile.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api/ShellyHttpApi.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/handler/ShellyBaseHandler.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/handler/ShellyComponents.java
Labels: bug

#7864 [magentatv] Initial contribution (aka EntertainTV)
  CODEOWNERS
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.magentatv/.classpath
  bundles/org.openhab.binding.magentatv/.project
  bundles/org.openhab.binding.magentatv/NOTICE
  bundles/org.openhab.binding.magentatv/README.md
  bundles/org.openhab.binding.magentatv/pom.xml
  bundles/org.openhab.binding.magentatv/src/main/feature/feature.xml
  bundles/org.openhab.binding.magentatv/src/main/java/org/openhab/binding/magentatv/internal/MagentaTVBindingConstants.java
  bundles/org.openhab.binding.magentatv/src/main/java/org/openhab/binding/magentatv/internal/MagentaTVConsoleHandler.java
  bundles/org.openhab.binding.magentatv/src/main/java/org/openhab/binding/magentatv/internal/MagentaTVDeviceManager.java
  bundles/org.openhab.binding.magentatv/src/main/java/org/openhab/binding/magentatv/internal/MagentaTVException.java
  bundles/org.openhab.binding.magentatv/src/main/java/org/openhab/binding/magentatv/internal/MagentaTVGsonDTO.java
  bundles/org.openhab.binding.magentatv/src/main/java/org/openhab/binding/magentatv/internal/MagentaTVHandlerFactory.java
  bundles/org.openhab.binding.magentatv/src/main/java/org/openhab/binding/magentatv/internal/MagentaTVUtil.java
  bundles/org.openhab.binding.magentatv/src/main/java/org/openhab/binding/magentatv/internal/config/MagentaTVDynamicConfig.java
  bundles/org.openhab.binding.magentatv/src/main/java/org/openhab/binding/magentatv/internal/config/MagentaTVThingConfiguration.java
  bundles/org.openhab.binding.magentatv/src/main/java/org/openhab/binding/magentatv/internal/discovery/MagentaTVDiscoveryParticipant.java
  bundles/org.openhab.binding.magentatv/src/main/java/org/openhab/binding/magentatv/internal/handler/MagentaTVControl.java
  bundles/org.openhab.binding.magentatv/src/main/java/org/openhab/binding/magentatv/internal/handler/MagentaTVHandler.java
  bundles/org.openhab.binding.magentatv/src/main/java/org/openhab/binding/magentatv/internal/handler/MagentaTVListener.java
  bundles/org.openhab.binding.magentatv/src/main/java/org/openhab/binding/magentatv/internal/network/MagentaTVHttp.java
  bundles/org.openhab.binding.magentatv/src/main/java/org/openhab/binding/magentatv/internal/network/MagentaTVNetwork.java
  bundles/org.openhab.binding.magentatv/src/main/java/org/openhab/binding/magentatv/internal/network/MagentaTVNotifyServlet.java
  bundles/org.openhab.binding.magentatv/src/main/java/org/openhab/binding/magentatv/internal/network/MagentaTVOAuth.java
  bundles/org.openhab.binding.magentatv/src/main/java/org/openhab/binding/magentatv/internal/network/MagentaTVPoweroffListener.java
  bundles/org.openhab.binding.magentatv/src/main/resources/ESH-INF/binding/binding.xml
  bundles/org.openhab.binding.magentatv/src/main/resources/ESH-INF/i18n/magentatv_de.properties
  bundles/org.openhab.binding.magentatv/src/main/resources/ESH-INF/thing/thing-types.xml
  bundles/pom.xml
Labels: new binding

#8472 [gree] Minor improvements
  bundles/org.openhab.binding.gree/README.md
  bundles/org.openhab.binding.gree/src/main/java/org/openhab/binding/gree/internal/GreeBindingConstants.java
  bundles/org.openhab.binding.gree/src/main/java/org/openhab/binding/gree/internal/handler/GreeAirDevice.java
  bundles/org.openhab.binding.gree/src/main/java/org/openhab/binding/gree/internal/handler/GreeHandler.java
  bundles/org.openhab.binding.gree/src/main/resources/ESH-INF/i18n/gree.properties
  bundles/org.openhab.binding.gree/src/main/resources/ESH-INF/i18n/gree_DE.properties
Labels: enhancement

#8481 [gree] Fix endless loop in command handler (previous PR)
  bundles/org.openhab.binding.gree/src/main/java/org/openhab/binding/gree/internal/handler/GreeAirDevice.java
  bundles/org.openhab.binding.gree/src/main/java/org/openhab/binding/gree/internal/handler/GreeHandler.java
Labels: bug

#8480 [kaleidescape] update README.md for multiple thing types implementation
  bundles/org.openhab.binding.kaleidescape/README.md
Labels: documentation

#8463 [miio] add automatic tokens to miio MDNSDiscoveryParticipant
  bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/discovery/MiIoDiscoveryParticipant.java
  bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/handler/MiIoBasicHandler.java
Labels: enhancement

#8477 [miio] control channel for Vacuum 1C STYTJ01ZHM (dreame.vacuum.mc1808)
  bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/handler/MiIoBasicHandler.java
  bundles/org.openhab.binding.miio/src/main/resources/ESH-INF/thing/commonChannels.xml
  bundles/org.openhab.binding.miio/src/main/resources/database/dreame.vacuum.mc1808-miot.json
Labels: bug

#7526 [max] Added 'ThingActions' to handle reboot and other Cube actions
  bundles/org.openhab.binding.max/README.md
  bundles/org.openhab.binding.max/src/main/java/org/openhab/binding/max/actions/MaxCubeActions.java
  bundles/org.openhab.binding.max/src/main/java/org/openhab/binding/max/actions/MaxDevicesActions.java
  bundles/org.openhab.binding.max/src/main/java/org/openhab/binding/max/internal/actions/IMaxCubeActions.java
  bundles/org.openhab.binding.max/src/main/java/org/openhab/binding/max/internal/actions/IMaxDevicesActions.java
  bundles/org.openhab.binding.max/src/main/java/org/openhab/binding/max/internal/discovery/MaxDeviceDiscoveryService.java
  bundles/org.openhab.binding.max/src/main/java/org/openhab/binding/max/internal/factory/MaxCubeHandlerFactory.java
  bundles/org.openhab.binding.max/src/main/java/org/openhab/binding/max/internal/handler/DeviceStatusListener.java
  bundles/org.openhab.binding.max/src/main/java/org/openhab/binding/max/internal/handler/MaxCubeBridgeHandler.java
  bundles/org.openhab.binding.max/src/main/java/org/openhab/binding/max/internal/handler/MaxDevicesHandler.java
  bundles/org.openhab.binding.max/src/main/resources/ESH-INF/thing/bridge.xml
Labels: enhancement, rebuild

#8489 [miio] Offline mapviewer fix command formatting
  bundles/org.openhab.binding.miio/src/test/java/org/openhab/binding/miio/internal/RoboMapViewer.java
Labels: bug

#8490 [miio] Fix maven warning for dynamic channel
  bundles/org.openhab.binding.miio/README.md
  bundles/org.openhab.binding.miio/src/main/resources/ESH-INF/thing/vacuumThing.xml
  bundles/org.openhab.binding.miio/src/main/resources/database/dreame.vacuum.mc1808-miot.json
Labels: bug

#6742 [upb] UPB Binding initial contribution
  CODEOWNERS
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.upb/.classpath
  bundles/org.openhab.binding.upb/.project
  bundles/org.openhab.binding.upb/NOTICE
  bundles/org.openhab.binding.upb/README.md
  bundles/org.openhab.binding.upb/pom.xml
  bundles/org.openhab.binding.upb/src/main/feature/feature.xml
  bundles/org.openhab.binding.upb/src/main/java/org/openhab/binding/upb/internal/Constants.java
  bundles/org.openhab.binding.upb/src/main/java/org/openhab/binding/upb/internal/UPBController.java
  bundles/org.openhab.binding.upb/src/main/java/org/openhab/binding/upb/internal/UPBDevice.java
  bundles/org.openhab.binding.upb/src/main/java/org/openhab/binding/upb/internal/UPBHandlerFactory.java
  bundles/org.openhab.binding.upb/src/main/java/org/openhab/binding/upb/internal/handler/MessageListener.java
  bundles/org.openhab.binding.upb/src/main/java/org/openhab/binding/upb/internal/handler/PIMHandler.java
  bundles/org.openhab.binding.upb/src/main/java/org/openhab/binding/upb/internal/handler/SerialIoThread.java
  bundles/org.openhab.binding.upb/src/main/java/org/openhab/binding/upb/internal/handler/SerialPIMHandler.java
  bundles/org.openhab.binding.upb/src/main/java/org/openhab/binding/upb/internal/handler/UPBIoHandler.java
  bundles/org.openhab.binding.upb/src/main/java/org/openhab/binding/upb/internal/handler/UPBThingHandler.java
  bundles/org.openhab.binding.upb/src/main/java/org/openhab/binding/upb/internal/handler/VirtualThingHandler.java
  bundles/org.openhab.binding.upb/src/main/java/org/openhab/binding/upb/internal/message/Command.java
  bundles/org.openhab.binding.upb/src/main/java/org/openhab/binding/upb/internal/message/ControlWord.java
  bundles/org.openhab.binding.upb/src/main/java/org/openhab/binding/upb/internal/message/MessageBuilder.java
  bundles/org.openhab.binding.upb/src/main/java/org/openhab/binding/upb/internal/message/MessageParseException.java
  bundles/org.openhab.binding.upb/src/main/java/org/openhab/binding/upb/internal/message/UPBMessage.java
  bundles/org.openhab.binding.upb/src/main/resources/ESH-INF/binding/binding.xml
  bundles/org.openhab.binding.upb/src/main/resources/ESH-INF/config/config.xml
  bundles/org.openhab.binding.upb/src/main/resources/ESH-INF/i18n/thingstate.properties
  bundles/org.openhab.binding.upb/src/main/resources/ESH-INF/thing/channels.xml
  bundles/org.openhab.binding.upb/src/main/resources/ESH-INF/thing/leviton/38A00-1.xml
  bundles/org.openhab.binding.upb/src/main/resources/ESH-INF/thing/pim.xml
  bundles/org.openhab.binding.upb/src/main/resources/ESH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.upb/src/main/resources/ESH-INF/thing/virtual.xml
  bundles/org.openhab.binding.upb/src/test/java/org/openhab/binding/upb/internal/message/MessageBuilderTest.java
  bundles/pom.xml
Labels: cre, new binding, oh1 migration

#6076 [senechome] Senec Home Batteries Binding initial contribution
  CODEOWNERS
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.senechome/.classpath
  bundles/org.openhab.binding.senechome/.project
  bundles/org.openhab.binding.senechome/NOTICE
  bundles/org.openhab.binding.senechome/README.md
  bundles/org.openhab.binding.senechome/pom.xml
  bundles/org.openhab.binding.senechome/src/main/feature/feature.xml
  bundles/org.openhab.binding.senechome/src/main/java/org/openhab/binding/senechome/internal/PowerLimitationStatusDTO.java
  bundles/org.openhab.binding.senechome/src/main/java/org/openhab/binding/senechome/internal/SenecBatteryStatus.java
  bundles/org.openhab.binding.senechome/src/main/java/org/openhab/binding/senechome/internal/SenecHomeApi.java
  bundles/org.openhab.binding.senechome/src/main/java/org/openhab/binding/senechome/internal/SenecHomeBindingConstants.java
  bundles/org.openhab.binding.senechome/src/main/java/org/openhab/binding/senechome/internal/SenecHomeConfigurationDTO.java
  bundles/org.openhab.binding.senechome/src/main/java/org/openhab/binding/senechome/internal/SenecHomeHandler.java
  bundles/org.openhab.binding.senechome/src/main/java/org/openhab/binding/senechome/internal/SenecHomeHandlerFactory.java
  bundles/org.openhab.binding.senechome/src/main/java/org/openhab/binding/senechome/internal/json/SenecHomeEnergy.java
  bundles/org.openhab.binding.senechome/src/main/java/org/openhab/binding/senechome/internal/json/SenecHomeGrid.java
  bundles/org.openhab.binding.senechome/src/main/java/org/openhab/binding/senechome/internal/json/SenecHomeLimitation.java
  bundles/org.openhab.binding.senechome/src/main/java/org/openhab/binding/senechome/internal/json/SenecHomeResponse.java
  bundles/org.openhab.binding.senechome/src/main/resources/ESH-INF/binding/binding.xml
  bundles/org.openhab.binding.senechome/src/main/resources/ESH-INF/thing/thing-types.xml
  bundles/pom.xml
Labels: new binding

#7199 [bluetooth] Add support for devices jumping between adapters.
  CODEOWNERS
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.bluetooth.airthings/src/main/resources/ESH-INF/thing/airthings.xml
  bundles/org.openhab.binding.bluetooth.am43/src/main/resources/ESH-INF/thing/am43.xml
  bundles/org.openhab.binding.bluetooth.bluegiga/README.md
  bundles/org.openhab.binding.bluetooth.bluegiga/src/main/java/org/openhab/binding/bluetooth/bluegiga/handler/BlueGigaBridgeHandler.java
  bundles/org.openhab.binding.bluetooth.bluez/README.md
  bundles/org.openhab.binding.bluetooth.bluez/src/main/java/org/openhab/binding/bluetooth/bluez/handler/BlueZBridgeHandler.java
  bundles/org.openhab.binding.bluetooth.blukii/src/main/resources/ESH-INF/thing/blukii.xml
  bundles/org.openhab.binding.bluetooth.roaming/.classpath
  bundles/org.openhab.binding.bluetooth.roaming/.project
  bundles/org.openhab.binding.bluetooth.roaming/NOTICE
  bundles/org.openhab.binding.bluetooth.roaming/README.md
  bundles/org.openhab.binding.bluetooth.roaming/pom.xml
  bundles/org.openhab.binding.bluetooth.roaming/src/main/feature/feature.xml
  bundles/org.openhab.binding.bluetooth.roaming/src/main/java/org/openhab/binding/bluetooth/roaming/internal/RoamingBindingConstants.java
  bundles/org.openhab.binding.bluetooth.roaming/src/main/java/org/openhab/binding/bluetooth/roaming/internal/RoamingBluetoothAdapter.java
  bundles/org.openhab.binding.bluetooth.roaming/src/main/java/org/openhab/binding/bluetooth/roaming/internal/RoamingBluetoothDevice.java
  bundles/org.openhab.binding.bluetooth.roaming/src/main/java/org/openhab/binding/bluetooth/roaming/internal/RoamingBluetoothDiscoveryParticipant.java
  bundles/org.openhab.binding.bluetooth.roaming/src/main/java/org/openhab/binding/bluetooth/roaming/internal/RoamingBridgeHandler.java
  bundles/org.openhab.binding.bluetooth.roaming/src/main/java/org/openhab/binding/bluetooth/roaming/internal/RoamingHandlerFactory.java
  bundles/org.openhab.binding.bluetooth.roaming/src/main/resources/ESH-INF/thing/roaming.xml
  bundles/org.openhab.binding.bluetooth.ruuvitag/src/main/resources/ESH-INF/thing/ruuvitag.xml
  bundles/org.openhab.binding.bluetooth/README.md
  bundles/org.openhab.binding.bluetooth/src/main/java/org/openhab/binding/bluetooth/AbstractBluetoothBridgeHandler.java
  bundles/org.openhab.binding.bluetooth/src/main/java/org/openhab/binding/bluetooth/BaseBluetoothDevice.java
  bundles/org.openhab.binding.bluetooth/src/main/java/org/openhab/binding/bluetooth/BeaconBluetoothHandler.java
  bundles/org.openhab.binding.bluetooth/src/main/java/org/openhab/binding/bluetooth/BluetoothAdapter.java
  bundles/org.openhab.binding.bluetooth/src/main/java/org/openhab/binding/bluetooth/BluetoothBindingConstants.java
  bundles/org.openhab.binding.bluetooth/src/main/java/org/openhab/binding/bluetooth/BluetoothDevice.java
  bundles/org.openhab.binding.bluetooth/src/main/java/org/openhab/binding/bluetooth/BluetoothDeviceListener.java
  bundles/org.openhab.binding.bluetooth/src/main/java/org/openhab/binding/bluetooth/ConnectedBluetoothHandler.java
  bundles/org.openhab.binding.bluetooth/src/main/java/org/openhab/binding/bluetooth/DelegateBluetoothDevice.java
  bundles/org.openhab.binding.bluetooth/src/main/java/org/openhab/binding/bluetooth/discovery/BluetoothDiscoveryDevice.java
  bundles/org.openhab.binding.bluetooth/src/main/java/org/openhab/binding/bluetooth/discovery/BluetoothDiscoveryParticipant.java
  bundles/org.openhab.binding.bluetooth/src/main/java/org/openhab/binding/bluetooth/discovery/internal/BluetoothDiscoveryProcess.java
  bundles/org.openhab.binding.bluetooth/src/main/java/org/openhab/binding/bluetooth/discovery/internal/BluetoothDiscoveryService.java
  bundles/org.openhab.binding.bluetooth/src/main/java/org/openhab/binding/bluetooth/internal/BluetoothHandlerFactory.java
  bundles/org.openhab.binding.bluetooth/src/main/resources/ESH-INF/thing/channels.xml
  bundles/org.openhab.binding.bluetooth/src/main/resources/ESH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.bluetooth/src/test/java/org/openhab/binding/bluetooth/MockBluetoothAdapter.java
  bundles/org.openhab.binding.bluetooth/src/test/java/org/openhab/binding/bluetooth/MockBluetoothDevice.java
  bundles/org.openhab.binding.bluetooth/src/test/java/org/openhab/binding/bluetooth/discovery/internal/BluetoothDiscoveryServiceTest.java
  bundles/pom.xml
  features/openhab-addons/src/main/resources/footer.xml
Labels: enhancement

#8231 [intesis] New Binding for Intesis WiFi adapters used in various AC systems
  CODEOWNERS
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.intesis/.classpath
  bundles/org.openhab.binding.intesis/.project
  bundles/org.openhab.binding.intesis/NOTICE
  bundles/org.openhab.binding.intesis/README.md
  bundles/org.openhab.binding.intesis/pom.xml
  bundles/org.openhab.binding.intesis/src/main/feature/feature.xml
  bundles/org.openhab.binding.intesis/src/main/java/org/openhab/binding/intesis/internal/IntesisBindingConstants.java
  bundles/org.openhab.binding.intesis/src/main/java/org/openhab/binding/intesis/internal/IntesisConfiguration.java
  bundles/org.openhab.binding.intesis/src/main/java/org/openhab/binding/intesis/internal/IntesisDynamicStateDescriptionProvider.java
  bundles/org.openhab.binding.intesis/src/main/java/org/openhab/binding/intesis/internal/IntesisHandlerFactory.java
  bundles/org.openhab.binding.intesis/src/main/java/org/openhab/binding/intesis/internal/IntesisHomeModeEnum.java
  bundles/org.openhab.binding.intesis/src/main/java/org/openhab/binding/intesis/internal/api/IntesisHomeHttpApi.java
  bundles/org.openhab.binding.intesis/src/main/java/org/openhab/binding/intesis/internal/gson/IntesisHomeJSonDTO.java
  bundles/org.openhab.binding.intesis/src/main/java/org/openhab/binding/intesis/internal/handler/IntesisHomeHandler.java
  bundles/org.openhab.binding.intesis/src/main/resources/ESH-INF/binding/binding.xml
  bundles/org.openhab.binding.intesis/src/main/resources/ESH-INF/i18n/intesis.properties
  bundles/org.openhab.binding.intesis/src/main/resources/ESH-INF/i18n/intesis_de.properties
  bundles/org.openhab.binding.intesis/src/main/resources/ESH-INF/thing/dynamic-channels.xml
  bundles/org.openhab.binding.intesis/src/main/resources/ESH-INF/thing/thing-types.xml
  bundles/pom.xml
Labels: cre, new binding

#8209 [WlanThermo] Initial contribution
  CODEOWNERS
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.wlanthermo/.classpath
  bundles/org.openhab.binding.wlanthermo/.project
  bundles/org.openhab.binding.wlanthermo/NOTICE
  bundles/org.openhab.binding.wlanthermo/README.md
  bundles/org.openhab.binding.wlanthermo/doc/mini.jpg
  bundles/org.openhab.binding.wlanthermo/doc/nano.jpg
  bundles/org.openhab.binding.wlanthermo/pom.xml
  bundles/org.openhab.binding.wlanthermo/src/main/feature/feature.xml
  bundles/org.openhab.binding.wlanthermo/src/main/java/org/openhab/binding/wlanthermo/internal/WlanThermoBindingConstants.java
  bundles/org.openhab.binding.wlanthermo/src/main/java/org/openhab/binding/wlanthermo/internal/WlanThermoHandlerFactory.java
  bundles/org.openhab.binding.wlanthermo/src/main/java/org/openhab/binding/wlanthermo/internal/WlanThermoMiniConfiguration.java
  bundles/org.openhab.binding.wlanthermo/src/main/java/org/openhab/binding/wlanthermo/internal/WlanThermoMiniHandler.java
  bundles/org.openhab.binding.wlanthermo/src/main/java/org/openhab/binding/wlanthermo/internal/WlanThermoNanoConfiguration.java
  bundles/org.openhab.binding.wlanthermo/src/main/java/org/openhab/binding/wlanthermo/internal/WlanThermoNanoHandler.java
  bundles/org.openhab.binding.wlanthermo/src/main/java/org/openhab/binding/wlanthermo/internal/api/mini/builtin/App.java
  bundles/org.openhab.binding.wlanthermo/src/main/java/org/openhab/binding/wlanthermo/internal/api/mini/builtin/Channel.java
  bundles/org.openhab.binding.wlanthermo/src/main/java/org/openhab/binding/wlanthermo/internal/api/mini/builtin/Data.java
  bundles/org.openhab.binding.wlanthermo/src/main/java/org/openhab/binding/wlanthermo/internal/api/mini/builtin/Pit.java
  bundles/org.openhab.binding.wlanthermo/src/main/java/org/openhab/binding/wlanthermo/internal/api/mini/builtin/UtilMini.java
  bundles/org.openhab.binding.wlanthermo/src/main/java/org/openhab/binding/wlanthermo/internal/api/mini/builtin/WlanThermoMiniCommandHandler.java
  bundles/org.openhab.binding.wlanthermo/src/main/java/org/openhab/binding/wlanthermo/internal/api/nano/UtilNano.java
  bundles/org.openhab.binding.wlanthermo/src/main/java/org/openhab/binding/wlanthermo/internal/api/nano/WlanThermoNanoCommandHandler.java
  bundles/org.openhab.binding.wlanthermo/src/main/java/org/openhab/binding/wlanthermo/internal/api/nano/data/Channel.java
  bundles/org.openhab.binding.wlanthermo/src/main/java/org/openhab/binding/wlanthermo/internal/api/nano/data/Data.java
  bundles/org.openhab.binding.wlanthermo/src/main/java/org/openhab/binding/wlanthermo/internal/api/nano/data/Pitmaster.java
  bundles/org.openhab.binding.wlanthermo/src/main/java/org/openhab/binding/wlanthermo/internal/api/nano/data/Pm.java
  bundles/org.openhab.binding.wlanthermo/src/main/java/org/openhab/binding/wlanthermo/internal/api/nano/data/System.java
  bundles/org.openhab.binding.wlanthermo/src/main/java/org/openhab/binding/wlanthermo/internal/api/nano/settings/Api.java
  bundles/org.openhab.binding.wlanthermo/src/main/java/org/openhab/binding/wlanthermo/internal/api/nano/settings/Device.java
  bundles/org.openhab.binding.wlanthermo/src/main/java/org/openhab/binding/wlanthermo/internal/api/nano/settings/Ext.java
  bundles/org.openhab.binding.wlanthermo/src/main/java/org/openhab/binding/wlanthermo/internal/api/nano/settings/Iot.java
  bundles/org.openhab.binding.wlanthermo/src/main/java/org/openhab/binding/wlanthermo/internal/api/nano/settings/Notes.java
  bundles/org.openhab.binding.wlanthermo/src/main/java/org/openhab/binding/wlanthermo/internal/api/nano/settings/Pid.java
  bundles/org.openhab.binding.wlanthermo/src/main/java/org/openhab/binding/wlanthermo/internal/api/nano/settings/Settings.java
  bundles/org.openhab.binding.wlanthermo/src/main/java/org/openhab/binding/wlanthermo/internal/api/nano/settings/System.java
  bundles/org.openhab.binding.wlanthermo/src/main/resources/ESH-INF/binding/binding.xml
  bundles/org.openhab.binding.wlanthermo/src/main/resources/ESH-INF/thing/thing-types.xml
  bundles/pom.xml
Labels: cre, new binding

#8250 [helioseasycontrols] Modbus: HeliosEasyControls - Initial Contribution
  CODEOWNERS
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.modbus.helioseasycontrols/.classpath
  bundles/org.openhab.binding.modbus.helioseasycontrols/.gitignore
  bundles/org.openhab.binding.modbus.helioseasycontrols/.project
  bundles/org.openhab.binding.modbus.helioseasycontrols/NOTICE
  bundles/org.openhab.binding.modbus.helioseasycontrols/README.md
  bundles/org.openhab.binding.modbus.helioseasycontrols/pom.xml
  bundles/org.openhab.binding.modbus.helioseasycontrols/src/main/feature/feature.xml
  bundles/org.openhab.binding.modbus.helioseasycontrols/src/main/java/org/openhab/binding/modbus/helioseasycontrols/internal/HeliosEasyControlsActions.java
  bundles/org.openhab.binding.modbus.helioseasycontrols/src/main/java/org/openhab/binding/modbus/helioseasycontrols/internal/HeliosEasyControlsBindingConstants.java
  bundles/org.openhab.binding.modbus.helioseasycontrols/src/main/java/org/openhab/binding/modbus/helioseasycontrols/internal/HeliosEasyControlsConfiguration.java
  bundles/org.openhab.binding.modbus.helioseasycontrols/src/main/java/org/openhab/binding/modbus/helioseasycontrols/internal/HeliosEasyControlsHandler.java
  bundles/org.openhab.binding.modbus.helioseasycontrols/src/main/java/org/openhab/binding/modbus/helioseasycontrols/internal/HeliosEasyControlsHandlerFactory.java
  bundles/org.openhab.binding.modbus.helioseasycontrols/src/main/java/org/openhab/binding/modbus/helioseasycontrols/internal/HeliosException.java
  bundles/org.openhab.binding.modbus.helioseasycontrols/src/main/java/org/openhab/binding/modbus/helioseasycontrols/internal/HeliosVariable.java
  bundles/org.openhab.binding.modbus.helioseasycontrols/src/main/resources/ESH-INF/binding/binding.xml
  bundles/org.openhab.binding.modbus.helioseasycontrols/src/main/resources/ESH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.modbus.helioseasycontrols/src/main/resources/org/openhab/binding/modbus/helioseasycontrols/internal/variables.json
  bundles/pom.xml
Labels: cre, new binding

#6336 [ISM8] New binding for Wolf heating systems using an ISM8 interface
  CODEOWNERS
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.ism8/.classpath
  bundles/org.openhab.binding.ism8/.project
  bundles/org.openhab.binding.ism8/NOTICE
  bundles/org.openhab.binding.ism8/README.md
  bundles/org.openhab.binding.ism8/doc/Sitemap-Example.png
  bundles/org.openhab.binding.ism8/pom.xml
  bundles/org.openhab.binding.ism8/src/main/feature/feature.xml
  bundles/org.openhab.binding.ism8/src/main/java/org/openhab/binding/ism8/internal/Ism8BindingConstants.java
  bundles/org.openhab.binding.ism8/src/main/java/org/openhab/binding/ism8/internal/Ism8Configuration.java
  bundles/org.openhab.binding.ism8/src/main/java/org/openhab/binding/ism8/internal/Ism8Handler.java
  bundles/org.openhab.binding.ism8/src/main/java/org/openhab/binding/ism8/internal/Ism8HandlerFactory.java
  bundles/org.openhab.binding.ism8/src/main/java/org/openhab/binding/ism8/server/DataPointBase.java
  bundles/org.openhab.binding.ism8/src/main/java/org/openhab/binding/ism8/server/DataPointBool.java
  bundles/org.openhab.binding.ism8/src/main/java/org/openhab/binding/ism8/server/DataPointByteValue.java
  bundles/org.openhab.binding.ism8/src/main/java/org/openhab/binding/ism8/server/DataPointChangedEvent.java
  bundles/org.openhab.binding.ism8/src/main/java/org/openhab/binding/ism8/server/DataPointFactory.java
  bundles/org.openhab.binding.ism8/src/main/java/org/openhab/binding/ism8/server/DataPointLongValue.java
  bundles/org.openhab.binding.ism8/src/main/java/org/openhab/binding/ism8/server/DataPointScaling.java
  bundles/org.openhab.binding.ism8/src/main/java/org/openhab/binding/ism8/server/DataPointValue.java
  bundles/org.openhab.binding.ism8/src/main/java/org/openhab/binding/ism8/server/IDataPoint.java
  bundles/org.openhab.binding.ism8/src/main/java/org/openhab/binding/ism8/server/IDataPointChangeListener.java
  bundles/org.openhab.binding.ism8/src/main/java/org/openhab/binding/ism8/server/KnxNetFrame.java
  bundles/org.openhab.binding.ism8/src/main/java/org/openhab/binding/ism8/server/Server.java
  bundles/org.openhab.binding.ism8/src/main/java/org/openhab/binding/ism8/server/SetDatapointValueMessage.java
  bundles/org.openhab.binding.ism8/src/main/java/org/openhab/binding/ism8/server/SubServiceType.java
  bundles/org.openhab.binding.ism8/src/main/resources/ESH-INF/binding/binding.xml
  bundles/org.openhab.binding.ism8/src/main/resources/ESH-INF/thing/thing-types.xml
  bundles/pom.xml
Labels: cre, new binding

#7914 [luftdateninfo] new binding
  CODEOWNERS
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.luftdateninfo/.classpath
  bundles/org.openhab.binding.luftdateninfo/.project
  bundles/org.openhab.binding.luftdateninfo/NOTICE
  bundles/org.openhab.binding.luftdateninfo/README.md
  bundles/org.openhab.binding.luftdateninfo/doc/LuftdatenInfo-Map.png
  bundles/org.openhab.binding.luftdateninfo/doc/logo-rund.png
  bundles/org.openhab.binding.luftdateninfo/pom.xml
  bundles/org.openhab.binding.luftdateninfo/src/main/feature/feature.xml
  bundles/org.openhab.binding.luftdateninfo/src/main/java/org/openhab/binding/luftdateninfo/internal/LuftdatenInfoBindingConstants.java
  bundles/org.openhab.binding.luftdateninfo/src/main/java/org/openhab/binding/luftdateninfo/internal/LuftdatenInfoConfiguration.java
  bundles/org.openhab.binding.luftdateninfo/src/main/java/org/openhab/binding/luftdateninfo/internal/LuftdatenInfoHandlerFactory.java
  bundles/org.openhab.binding.luftdateninfo/src/main/java/org/openhab/binding/luftdateninfo/internal/dto/Location.java
  bundles/org.openhab.binding.luftdateninfo/src/main/java/org/openhab/binding/luftdateninfo/internal/dto/Sensor.java
  bundles/org.openhab.binding.luftdateninfo/src/main/java/org/openhab/binding/luftdateninfo/internal/dto/SensorData.java
  bundles/org.openhab.binding.luftdateninfo/src/main/java/org/openhab/binding/luftdateninfo/internal/dto/SensorDataValue.java
  bundles/org.openhab.binding.luftdateninfo/src/main/java/org/openhab/binding/luftdateninfo/internal/dto/SensorType.java
  bundles/org.openhab.binding.luftdateninfo/src/main/java/org/openhab/binding/luftdateninfo/internal/handler/BaseSensorHandler.java
  bundles/org.openhab.binding.luftdateninfo/src/main/java/org/openhab/binding/luftdateninfo/internal/handler/ConditionHandler.java
  bundles/org.openhab.binding.luftdateninfo/src/main/java/org/openhab/binding/luftdateninfo/internal/handler/HTTPHandler.java
  bundles/org.openhab.binding.luftdateninfo/src/main/java/org/openhab/binding/luftdateninfo/internal/handler/NoiseHandler.java
  bundles/org.openhab.binding.luftdateninfo/src/main/java/org/openhab/binding/luftdateninfo/internal/handler/PMHandler.java
  bundles/org.openhab.binding.luftdateninfo/src/main/java/org/openhab/binding/luftdateninfo/internal/utils/DateTimeUtils.java
  bundles/org.openhab.binding.luftdateninfo/src/main/java/org/openhab/binding/luftdateninfo/internal/utils/NumberUtils.java
  bundles/org.openhab.binding.luftdateninfo/src/main/resources/ESH-INF/binding/binding.xml
  bundles/org.openhab.binding.luftdateninfo/src/main/resources/ESH-INF/i18n/luftdateninfo_de.properties
  bundles/org.openhab.binding.luftdateninfo/src/main/resources/ESH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.luftdateninfo/src/test/java/org/openhab/binding/luftdateninfo/internal/ConditionHandlerTest.java
  bundles/org.openhab.binding.luftdateninfo/src/test/java/org/openhab/binding/luftdateninfo/internal/DTOTest.java
  bundles/org.openhab.binding.luftdateninfo/src/test/java/org/openhab/binding/luftdateninfo/internal/HTTPHandlerEvalTest.java
  bundles/org.openhab.binding.luftdateninfo/src/test/java/org/openhab/binding/luftdateninfo/internal/HTTPHandlerValueTest.java
  bundles/org.openhab.binding.luftdateninfo/src/test/java/org/openhab/binding/luftdateninfo/internal/NoiseHandlerTest.java
  bundles/org.openhab.binding.luftdateninfo/src/test/java/org/openhab/binding/luftdateninfo/internal/NumberTest.java
  bundles/org.openhab.binding.luftdateninfo/src/test/java/org/openhab/binding/luftdateninfo/internal/PMHandlerTest.java
  bundles/org.openhab.binding.luftdateninfo/src/test/java/org/openhab/binding/luftdateninfo/internal/mock/ConditionHandlerExtension.java
  bundles/org.openhab.binding.luftdateninfo/src/test/java/org/openhab/binding/luftdateninfo/internal/mock/NoiseHandlerExtension.java
  bundles/org.openhab.binding.luftdateninfo/src/test/java/org/openhab/binding/luftdateninfo/internal/mock/PMHandlerExtension.java
  bundles/org.openhab.binding.luftdateninfo/src/test/java/org/openhab/binding/luftdateninfo/internal/mock/ThingMock.java
  bundles/org.openhab.binding.luftdateninfo/src/test/java/org/openhab/binding/luftdateninfo/internal/util/DateTimeTest.java
  bundles/org.openhab.binding.luftdateninfo/src/test/java/org/openhab/binding/luftdateninfo/internal/util/FileReader.java
  bundles/org.openhab.binding.luftdateninfo/src/test/resources/condition-result-no-pressure-flipped-values.json
  bundles/org.openhab.binding.luftdateninfo/src/test/resources/condition-result-no-pressure.json
  bundles/org.openhab.binding.luftdateninfo/src/test/resources/condition-result-plus-pressure.json
  bundles/org.openhab.binding.luftdateninfo/src/test/resources/noise-result.json
  bundles/org.openhab.binding.luftdateninfo/src/test/resources/pm-result.json
  bundles/pom.xml
Labels: cre, new binding

#7054 [venstarthermostat] Initial contribution: Venstar thermostats with Local API support
  bundles/org.openhab.binding.venstarthermostat/.classpath
  bundles/org.openhab.binding.venstarthermostat/.project
  bundles/org.openhab.binding.venstarthermostat/README.md
  bundles/org.openhab.binding.venstarthermostat/pom.xml
  bundles/org.openhab.binding.venstarthermostat/src/main/feature/feature.xml
  bundles/org.openhab.binding.venstarthermostat/src/main/java/org/openhab/binding/venstarthermostat/internal/VenstarThermostatBindingConstants.java
  bundles/org.openhab.binding.venstarthermostat/src/main/java/org/openhab/binding/venstarthermostat/internal/VenstarThermostatConfiguration.java
  bundles/org.openhab.binding.venstarthermostat/src/main/java/org/openhab/binding/venstarthermostat/internal/VenstarThermostatHandlerFactory.java
  bundles/org.openhab.binding.venstarthermostat/src/main/java/org/openhab/binding/venstarthermostat/internal/discovery/VenstarThermostatDiscoveryService.java
  bundles/org.openhab.binding.venstarthermostat/src/main/java/org/openhab/binding/venstarthermostat/internal/handler/VenstarThermostatHandler.java
  bundles/org.openhab.binding.venstarthermostat/src/main/java/org/openhab/binding/venstarthermostat/internal/model/VenstarInfoData.java
  bundles/org.openhab.binding.venstarthermostat/src/main/java/org/openhab/binding/venstarthermostat/internal/model/VenstarResponse.java
  bundles/org.openhab.binding.venstarthermostat/src/main/java/org/openhab/binding/venstarthermostat/internal/model/VenstarSensor.java
  bundles/org.openhab.binding.venstarthermostat/src/main/java/org/openhab/binding/venstarthermostat/internal/model/VenstarSensorData.java
  bundles/org.openhab.binding.venstarthermostat/src/main/java/org/openhab/binding/venstarthermostat/internal/model/VenstarSystemMode.java
  bundles/org.openhab.binding.venstarthermostat/src/main/java/org/openhab/binding/venstarthermostat/internal/model/VenstarSystemModeSerializer.java
  bundles/org.openhab.binding.venstarthermostat/src/main/java/org/openhab/binding/venstarthermostat/internal/model/VenstarSystemState.java
  bundles/org.openhab.binding.venstarthermostat/src/main/java/org/openhab/binding/venstarthermostat/internal/model/VenstarSystemStateSerializer.java
  bundles/org.openhab.binding.venstarthermostat/src/main/resources/ESH-INF/binding/binding.xml
  bundles/org.openhab.binding.venstarthermostat/src/main/resources/ESH-INF/thing/thing-types.xml
  bundles/pom.xml
Labels: new binding

#8496 [teleinfo] Add rfc2217 support
  bundles/org.openhab.binding.teleinfo/src/main/java/org/openhab/binding/teleinfo/internal/serial/TeleinfoSerialControllerHandler.java
Labels: enhancement

#8261 [alarmdecoder] allow keypad messages with !KPM:
  bundles/org.openhab.binding.alarmdecoder/src/main/java/org/openhab/binding/alarmdecoder/internal/protocol/ADMsgType.java
  bundles/org.openhab.binding.alarmdecoder/src/main/java/org/openhab/binding/alarmdecoder/internal/protocol/KeypadMessage.java
Labels: enhancement

#8050 [automower] Initial contribution of the automower binding
  CODEOWNERS
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.automower/.classpath
  bundles/org.openhab.binding.automower/.project
  bundles/org.openhab.binding.automower/NOTICE
  bundles/org.openhab.binding.automower/README.md
  bundles/org.openhab.binding.automower/pom.xml
  bundles/org.openhab.binding.automower/src/main/feature/feature.xml
  bundles/org.openhab.binding.automower/src/main/java/org/openhab/binding/automower/internal/AutomowerBindingConstants.java
  bundles/org.openhab.binding.automower/src/main/java/org/openhab/binding/automower/internal/AutomowerHandlerFactory.java
  bundles/org.openhab.binding.automower/src/main/java/org/openhab/binding/automower/internal/actions/AutomowerActions.java
  bundles/org.openhab.binding.automower/src/main/java/org/openhab/binding/automower/internal/actions/IAutomowerActions.java
  bundles/org.openhab.binding.automower/src/main/java/org/openhab/binding/automower/internal/bridge/AutomowerBridge.java
  bundles/org.openhab.binding.automower/src/main/java/org/openhab/binding/automower/internal/bridge/AutomowerBridgeConfiguration.java
  bundles/org.openhab.binding.automower/src/main/java/org/openhab/binding/automower/internal/bridge/AutomowerBridgeHandler.java
  bundles/org.openhab.binding.automower/src/main/java/org/openhab/binding/automower/internal/discovery/AutomowerDiscoveryService.java
  bundles/org.openhab.binding.automower/src/main/java/org/openhab/binding/automower/internal/rest/api/HusqvarnaApi.java
  bundles/org.openhab.binding.automower/src/main/java/org/openhab/binding/automower/internal/rest/api/automowerconnect/AutomowerConnectApi.java
  bundles/org.openhab.binding.automower/src/main/java/org/openhab/binding/automower/internal/rest/api/automowerconnect/dto/Activity.java
  bundles/org.openhab.binding.automower/src/main/java/org/openhab/binding/automower/internal/rest/api/automowerconnect/dto/Battery.java
  bundles/org.openhab.binding.automower/src/main/java/org/openhab/binding/automower/internal/rest/api/automowerconnect/dto/Calendar.java
  bundles/org.openhab.binding.automower/src/main/java/org/openhab/binding/automower/internal/rest/api/automowerconnect/dto/Metadata.java
  bundles/org.openhab.binding.automower/src/main/java/org/openhab/binding/automower/internal/rest/api/automowerconnect/dto/Mode.java
  bundles/org.openhab.binding.automower/src/main/java/org/openhab/binding/automower/internal/rest/api/automowerconnect/dto/Mower.java
  bundles/org.openhab.binding.automower/src/main/java/org/openhab/binding/automower/internal/rest/api/automowerconnect/dto/MowerApp.java
  bundles/org.openhab.binding.automower/src/main/java/org/openhab/binding/automower/internal/rest/api/automowerconnect/dto/MowerCommand.java
  bundles/org.openhab.binding.automower/src/main/java/org/openhab/binding/automower/internal/rest/api/automowerconnect/dto/MowerCommandAttributes.java
  bundles/org.openhab.binding.automower/src/main/java/org/openhab/binding/automower/internal/rest/api/automowerconnect/dto/MowerCommandRequest.java
  bundles/org.openhab.binding.automower/src/main/java/org/openhab/binding/automower/internal/rest/api/automowerconnect/dto/MowerData.java
  bundles/org.openhab.binding.automower/src/main/java/org/openhab/binding/automower/internal/rest/api/automowerconnect/dto/MowerListResult.java
  bundles/org.openhab.binding.automower/src/main/java/org/openhab/binding/automower/internal/rest/api/automowerconnect/dto/MowerResult.java
  bundles/org.openhab.binding.automower/src/main/java/org/openhab/binding/automower/internal/rest/api/automowerconnect/dto/Planner.java
  bundles/org.openhab.binding.automower/src/main/java/org/openhab/binding/automower/internal/rest/api/automowerconnect/dto/State.java
  bundles/org.openhab.binding.automower/src/main/java/org/openhab/binding/automower/internal/rest/api/automowerconnect/dto/System.java
  bundles/org.openhab.binding.automower/src/main/java/org/openhab/binding/automower/internal/rest/exceptions/AutomowerCommunicationException.java
  bundles/org.openhab.binding.automower/src/main/java/org/openhab/binding/automower/internal/rest/exceptions/UnauthorizedException.java
  bundles/org.openhab.binding.automower/src/main/java/org/openhab/binding/automower/internal/rest/exceptions/UnavailableException.java
  bundles/org.openhab.binding.automower/src/main/java/org/openhab/binding/automower/internal/things/AutomowerCommand.java
  bundles/org.openhab.binding.automower/src/main/java/org/openhab/binding/automower/internal/things/AutomowerConfiguration.java
  bundles/org.openhab.binding.automower/src/main/java/org/openhab/binding/automower/internal/things/AutomowerHandler.java
  bundles/org.openhab.binding.automower/src/main/resources/ESH-INF/binding/binding.xml
  bundles/org.openhab.binding.automower/src/main/resources/ESH-INF/i18n/automower.properties
  bundles/org.openhab.binding.automower/src/main/resources/ESH-INF/i18n/automower_de.properties
  bundles/org.openhab.binding.automower/src/main/resources/ESH-INF/thing/thing-types.xml
  bundles/pom.xml
Labels: awaiting feedback, cre, new binding

#7550 [smartthings] Initial contribution
  CODEOWNERS
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.smartthings/.classpath
  bundles/org.openhab.binding.smartthings/.project
  bundles/org.openhab.binding.smartthings/NOTICE
  bundles/org.openhab.binding.smartthings/README.md
  bundles/org.openhab.binding.smartthings/contrib/smartthings/DeviceHandlers/OpenHabDeviceHandler.groovy
  bundles/org.openhab.binding.smartthings/contrib/smartthings/SmartApps/OpenHabAppV2.groovy
  bundles/org.openhab.binding.smartthings/doc/SmartthingsInstallation.md
  bundles/org.openhab.binding.smartthings/doc/Troubleshooting.md
  bundles/org.openhab.binding.smartthings/pom.xml
  bundles/org.openhab.binding.smartthings/src/main/feature/feature.xml
  bundles/org.openhab.binding.smartthings/src/main/java/org/openhab/binding/smartthings/internal/SmartthingsBindingConstants.java
  bundles/org.openhab.binding.smartthings/src/main/java/org/openhab/binding/smartthings/internal/SmartthingsHandlerFactory.java
  bundles/org.openhab.binding.smartthings/src/main/java/org/openhab/binding/smartthings/internal/SmartthingsServlet.java
  bundles/org.openhab.binding.smartthings/src/main/java/org/openhab/binding/smartthings/internal/converter/SmartthingsColor100Converter.java
  bundles/org.openhab.binding.smartthings/src/main/java/org/openhab/binding/smartthings/internal/converter/SmartthingsColorConverter.java
  bundles/org.openhab.binding.smartthings/src/main/java/org/openhab/binding/smartthings/internal/converter/SmartthingsConverter.java
  bundles/org.openhab.binding.smartthings/src/main/java/org/openhab/binding/smartthings/internal/converter/SmartthingsDefaultConverter.java
  bundles/org.openhab.binding.smartthings/src/main/java/org/openhab/binding/smartthings/internal/converter/SmartthingsHue100Converter.java
  bundles/org.openhab.binding.smartthings/src/main/java/org/openhab/binding/smartthings/internal/converter/SmartthingsOpenCloseControlConverter.java
  bundles/org.openhab.binding.smartthings/src/main/java/org/openhab/binding/smartthings/internal/discovery/SmartthingsDiscoveryService.java
  bundles/org.openhab.binding.smartthings/src/main/java/org/openhab/binding/smartthings/internal/dto/SmartthingsDeviceData.java
  bundles/org.openhab.binding.smartthings/src/main/java/org/openhab/binding/smartthings/internal/dto/SmartthingsStateData.java
  bundles/org.openhab.binding.smartthings/src/main/java/org/openhab/binding/smartthings/internal/handler/SmartthingsBridgeConfig.java
  bundles/org.openhab.binding.smartthings/src/main/java/org/openhab/binding/smartthings/internal/handler/SmartthingsBridgeConfigStatusMessage.java
  bundles/org.openhab.binding.smartthings/src/main/java/org/openhab/binding/smartthings/internal/handler/SmartthingsBridgeHandler.java
  bundles/org.openhab.binding.smartthings/src/main/java/org/openhab/binding/smartthings/internal/handler/SmartthingsThingConfig.java
  bundles/org.openhab.binding.smartthings/src/main/java/org/openhab/binding/smartthings/internal/handler/SmartthingsThingConfigStatusMessage.java
  bundles/org.openhab.binding.smartthings/src/main/java/org/openhab/binding/smartthings/internal/handler/SmartthingsThingHandler.java
  bundles/org.openhab.binding.smartthings/src/main/resources/ESH-INF/binding/binding.xml
  bundles/org.openhab.binding.smartthings/src/main/resources/ESH-INF/config/smartthings-config-description.xml
  bundles/org.openhab.binding.smartthings/src/main/resources/ESH-INF/i18n/smartthings.properties
  bundles/org.openhab.binding.smartthings/src/main/resources/ESH-INF/thing/thing-types.xml
  bundles/pom.xml
Labels: cre, new binding

#6484 [kvv] KVV Binding initial contribution
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.kvv/.classpath
  bundles/org.openhab.binding.kvv/.project
  bundles/org.openhab.binding.kvv/NOTICE
  bundles/org.openhab.binding.kvv/README.md
  bundles/org.openhab.binding.kvv/pom.xml
  bundles/org.openhab.binding.kvv/src/main/feature/feature.xml
  bundles/org.openhab.binding.kvv/src/main/java/org/openhab/binding/kvv/internal/DepartureResult.java
  bundles/org.openhab.binding.kvv/src/main/java/org/openhab/binding/kvv/internal/KVVBindingConstants.java
  bundles/org.openhab.binding.kvv/src/main/java/org/openhab/binding/kvv/internal/KVVBridgeConfig.java
  bundles/org.openhab.binding.kvv/src/main/java/org/openhab/binding/kvv/internal/KVVBridgeHandler.java
  bundles/org.openhab.binding.kvv/src/main/java/org/openhab/binding/kvv/internal/KVVHandlerFactory.java
  bundles/org.openhab.binding.kvv/src/main/java/org/openhab/binding/kvv/internal/KVVStopConfig.java
  bundles/org.openhab.binding.kvv/src/main/java/org/openhab/binding/kvv/internal/KVVStopHandler.java
  bundles/org.openhab.binding.kvv/src/main/resources/ESH-INF/binding/binding.xml
  bundles/org.openhab.binding.kvv/src/main/resources/ESH-INF/thing/bridge.xml
  bundles/org.openhab.binding.kvv/src/main/resources/ESH-INF/thing/stop.xml
  bundles/pom.xml
Labels: cre, new binding

#8329 [IpCamera] New binding for cameras - Initial Contribution
  CODEOWNERS
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.ipcamera/.classpath
  bundles/org.openhab.binding.ipcamera/.project
  bundles/org.openhab.binding.ipcamera/NOTICE
  bundles/org.openhab.binding.ipcamera/README.md
  bundles/org.openhab.binding.ipcamera/pom.xml
  bundles/org.openhab.binding.ipcamera/src/main/feature/feature.xml
  bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/AmcrestHandler.java
  bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/CameraConfig.java
  bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/ChannelTracking.java
  bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/DahuaHandler.java
  bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/DoorBirdHandler.java
  bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/Ffmpeg.java
  bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/FoscamHandler.java
  bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/GroupConfig.java
  bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/GroupTracker.java
  bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/Helper.java
  bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/HikvisionHandler.java
  bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/HttpOnlyHandler.java
  bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/InstarHandler.java
  bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/IpCameraActions.java
  bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/IpCameraBindingConstants.java
  bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/IpCameraDiscoveryService.java
  bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/IpCameraHandlerFactory.java
  bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/MyNettyAuthHandler.java
  bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/StreamServerGroupHandler.java
  bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/StreamServerHandler.java
  bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/handler/IpCameraGroupHandler.java
  bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/handler/IpCameraHandler.java
  bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/onvif/OnvifCodec.java
  bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/onvif/OnvifConnection.java
  bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/onvif/OnvifDiscovery.java
  bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/rtsp/NettyRtspHandler.java
  bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/rtsp/RtspConnection.java
  bundles/org.openhab.binding.ipcamera/src/main/resources/ESH-INF/binding/binding.xml
  bundles/org.openhab.binding.ipcamera/src/main/resources/ESH-INF/thing/thing-types.xml
  bundles/pom.xml
Labels: cre, new binding

#8390 [mqtt][homie] Improve Homie initialization process for big devices
  bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/ChannelState.java
  bundles/org.openhab.binding.mqtt.homie/src/main/java/org/openhab/binding/mqtt/homie/generic/internal/MqttBindingConstants.java
  bundles/org.openhab.binding.mqtt.homie/src/main/java/org/openhab/binding/mqtt/homie/internal/handler/HomieThingHandler.java
  itests/org.openhab.binding.mqtt.homie.tests/pom.xml
  itests/org.openhab.binding.mqtt.homie.tests/src/main/java/org/openhab/binding/mqtt/EmbeddedBrokerTools.java
  itests/org.openhab.binding.mqtt.homie.tests/src/main/java/org/openhab/binding/mqtt/HomieImplementationTest.java
Labels: bug

#8515 [amazonechocontrol] Remove unused version which no longer parses due to type change
  bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/jsons/JsonPlaylists.java
Labels: bug

#8542 [venstarthermostat] Fix venstarthermostat feature.xml
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.venstarthermostat/src/main/feature/feature.xml
Labels: bug

#8557 [somfytahoma] fixed detection of roller shutters
  bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/discovery/SomfyTahomaItemDiscoveryService.java
  bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/handler/SomfyTahomaBaseThingHandler.java
Labels: bug

#8560 [hueemulation] Listing hue lights fails
  bundles/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/StateUtils.java
Labels: bug

#8564 [feed] Reenable itest
  itests/org.openhab.binding.feed.tests/itest.bndrun
  itests/pom.xml
Labels: test

#8565 [ntp] Reenable itest
  itests/org.openhab.binding.ntp.tests/src/main/java/org/openhab/binding/ntp/test/NtpOSGiTest.java
  itests/pom.xml
Labels: awaiting other PR, test

#8567 [avmfritz] Reenable itest
  itests/org.openhab.binding.avmfritz.tests/itest.bndrun
  itests/pom.xml
Labels: awaiting other PR, test

#8555 [insteon] remove optional from the description of network parameters
  bundles/org.openhab.binding.insteon/README.md
  bundles/org.openhab.binding.insteon/src/main/resources/OH-INF/thing/thing-types.xml
Labels: documentation

#8587 [miio] avoid IndexOutOfBoundsException exception
  bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/handler/MiIoBasicHandler.java
Labels: bug

#8520 [velux] fix concurrency bugs, other minor issues, update readme.md (replaces #8493)
  bundles/org.openhab.binding.velux/README.md
  bundles/org.openhab.binding.velux/doc/veluxlogo.jpg
  bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/VeluxBindingConstants.java
  bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/bridge/json/JClogin.java
  bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/bridge/json/JsonBridgeAPI.java
  bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/bridge/slip/SlipBridgeAPI.java
  bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/bridge/slip/SlipVeluxBridge.java
  bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/bridge/slip/io/Connection.java
  bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/bridge/slip/io/SSLconnection.java
  bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/bridge/slip/utils/KLF200Response.java
  bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/bridge/slip/utils/SlipEncoding.java
  bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/discovery/VeluxDiscoveryService.java
  bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/factory/VeluxHandlerFactory.java
  bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/handler/ChannelBridgeWLANconfig.java
  bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/handler/VeluxBindingHandler.java
  bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/handler/VeluxBridgeHandler.java
  bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/things/VeluxKLFAPI.java
  bundles/org.openhab.binding.velux/src/main/resources/OH-INF/i18n/velux.properties
  bundles/org.openhab.binding.velux/src/main/resources/OH-INF/i18n/velux_de.properties
  bundles/org.openhab.binding.velux/src/main/resources/OH-INF/i18n/velux_dk.properties
  bundles/org.openhab.binding.velux/src/main/resources/OH-INF/i18n/velux_nl.properties
  bundles/pom.xml
  features/openhab-addons/pom.xml
Labels: bug

#8588 [avmfritz] Added support for DECT440 device
  bundles/org.openhab.binding.avmfritz/README.md
  bundles/org.openhab.binding.avmfritz/doc/AVM_FRITZDECT_200_301_500_freigestellt.png
  bundles/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/AVMFritzBindingConstants.java
  bundles/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/dto/AVMFritzBaseModel.java
  bundles/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/handler/AVMFritzButtonHandler.java
  bundles/org.openhab.binding.avmfritz/src/main/resources/OH-INF/i18n/avmfritz_de.properties
  bundles/org.openhab.binding.avmfritz/src/main/resources/OH-INF/thing/channel-types.xml
  bundles/org.openhab.binding.avmfritz/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.avmfritz/src/test/java/org/openhab/binding/avmfritz/internal/dto/AVMFritzDeviceListModelTest.java
  itests/org.openhab.binding.avmfritz.tests/src/main/java/org/openhab/binding/avmfritz/internal/discovery/AVMFritzDiscoveryServiceOSGiTest.java
Labels: enhancement

#8606 [velux] eliminate mvn compiler warnings
  bundles/org.openhab.binding.velux/README.md
  bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/VeluxBinding.java
  bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/bridge/VeluxBridgeActuators.java
  bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/bridge/VeluxBridgeDeviceStatus.java
  bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/bridge/VeluxBridgeGetFirmware.java
  bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/bridge/VeluxBridgeLANConfig.java
  bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/bridge/VeluxBridgeScenes.java
  bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/bridge/VeluxBridgeWLANConfig.java
  bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/bridge/json/JCgetDeviceStatus.java
  bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/bridge/json/JCgetFirmware.java
  bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/bridge/json/JCgetLANConfig.java
  bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/bridge/json/JCgetProducts.java
  bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/bridge/json/JCgetScenes.java
  bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/bridge/json/JCgetWLANConfig.java
  bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/bridge/json/JClogin.java
  bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/bridge/json/JClogout.java
  bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/bridge/json/JCrunProductDiscovery.java
  bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/bridge/json/JCrunProductIdentification.java
  bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/bridge/json/JCrunProductSearch.java
  bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/bridge/json/JCrunScene.java
  bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/bridge/json/JCsetSceneVelocity.java
  bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/bridge/json/JsonVeluxBridge.java
  bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/bridge/slip/utils/SlipEncoding.java
  bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/factory/VeluxHandlerFactory.java
  bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/handler/VeluxBridgeHandler.java
  bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/things/VeluxKLFAPI.java
  bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/things/VeluxProduct.java
  bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/things/VeluxProductState.java
  bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/things/VeluxScene.java
  bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/utils/Localization.java
Labels: enhancement

#8609 Fix disabled integration tests
  bundles/org.openhab.binding.mqtt.homie/src/test/java/org/openhab/binding/mqtt/homie/internal/handler/HomieThingHandlerTests.java
  itests/org.openhab.binding.mqtt.homeassistant.tests/itest.bndrun
  itests/org.openhab.binding.mqtt.homeassistant.tests/pom.xml
  itests/org.openhab.binding.mqtt.homeassistant.tests/src/main/java/org/openhab/binding/mqtt/DiscoverComponentsTest.java
  itests/org.openhab.binding.mqtt.homeassistant.tests/src/main/java/org/openhab/binding/mqtt/EmbeddedBrokerTools.java
  itests/org.openhab.binding.mqtt.homeassistant.tests/src/main/java/org/openhab/binding/mqtt/HomeAssistantMQTTImplementationTest.java
  itests/org.openhab.binding.mqtt.homeassistant.tests/src/main/java/org/openhab/binding/mqtt/ThingChannelConstants.java
  itests/org.openhab.binding.mqtt.homie.tests/itest.bndrun
  itests/org.openhab.binding.mqtt.homie.tests/src/main/java/org/openhab/binding/mqtt/EmbeddedBrokerTools.java
  itests/org.openhab.binding.mqtt.homie.tests/src/main/java/org/openhab/binding/mqtt/HomieImplementationTest.java
  itests/org.openhab.binding.mqtt.homie.tests/src/main/java/org/openhab/binding/mqtt/ThingChannelConstants.java
  itests/org.openhab.io.mqttembeddedbroker.tests/itest.bndrun
  itests/org.openhab.io.mqttembeddedbroker.tests/src/main/java/org/openhab/io/mqttembeddedbroker/EmbeddedBrokerTools.java
  itests/org.openhab.io.mqttembeddedbroker.tests/src/main/java/org/openhab/io/mqttembeddedbroker/MoquetteTest.java
  itests/pom.xml
Labels: test

#8617 Fix parallel MQTT itests execution
  bundles/org.openhab.io.mqttembeddedbroker/pom.xml
  bundles/org.openhab.io.mqttembeddedbroker/src/main/java/org/openhab/io/mqttembeddedbroker/Constants.java
  bundles/org.openhab.io.mqttembeddedbroker/src/main/java/org/openhab/io/mqttembeddedbroker/internal/EmbeddedBrokerService.java
  itests/org.openhab.binding.mqtt.homeassistant.tests/itest.bndrun
  itests/org.openhab.binding.mqtt.homeassistant.tests/pom.xml
  itests/org.openhab.binding.mqtt.homeassistant.tests/src/main/java/org/openhab/binding/mqtt/EmbeddedBrokerTools.java
  itests/org.openhab.binding.mqtt.homeassistant.tests/src/main/java/org/openhab/binding/mqtt/HomeAssistantMQTTImplementationTest.java
  itests/org.openhab.binding.mqtt.homie.tests/itest.bndrun
  itests/org.openhab.binding.mqtt.homie.tests/pom.xml
  itests/org.openhab.binding.mqtt.homie.tests/src/main/java/org/openhab/binding/mqtt/EmbeddedBrokerTools.java
  itests/org.openhab.binding.mqtt.homie.tests/src/main/java/org/openhab/binding/mqtt/HomieImplementationTest.java
  itests/org.openhab.io.mqttembeddedbroker.tests/itest.bndrun
  itests/org.openhab.io.mqttembeddedbroker.tests/pom.xml
  itests/org.openhab.io.mqttembeddedbroker.tests/src/main/java/org/openhab/io/mqttembeddedbroker/EmbeddedBrokerTools.java
  itests/org.openhab.io.mqttembeddedbroker.tests/src/main/java/org/openhab/io/mqttembeddedbroker/MoquetteTest.java
Labels: test
