Repository openhab/openhab-addons, pull requests merged in 2021-12, with the labels that each got.

#11676 [kaleidescape] Fix incorrect word in player ui documentation.
  bundles/org.openhab.binding.kaleidescape/README.md
Labels: documentation

#11680 [tplinksmarthome] Fixed invalid channels in KL125/KL135 definition.
  bundles/org.openhab.binding.tplinksmarthome/src/main/resources/OH-INF/thing/KL125.xml
  bundles/org.openhab.binding.tplinksmarthome/src/main/resources/OH-INF/thing/KL135.xml
Labels: bug

#11679 [wemo] Fix receiving empty binary state during poll
  bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/handler/WemoHandler.java
Labels: bug

#11673 [tivo] Minor update and cleanup README.md
  bundles/org.openhab.binding.tivo/README.md
Labels: documentation

#11648 Add i18n-maven-plugin dependency
  pom.xml
Labels: infrastructure

#11666 [homewizard] Fix issue with missing gas values
  bundles/org.openhab.binding.homewizard/src/main/java/org/openhab/binding/homewizard/internal/HomeWizardHandler.java
  bundles/org.openhab.binding.homewizard/src/main/java/org/openhab/binding/homewizard/internal/P1Payload.java
Labels: bug

#11682 [avmfritz] Exclude other Powerline products from discovery
  bundles/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/AVMFritzBindingConstants.java
  bundles/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/AVMFritzHandlerFactory.java
  bundles/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/discovery/AVMFritzUpnpDiscoveryParticipant.java
  bundles/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/handler/Powerline546EHandler.java
  itests/org.openhab.binding.avmfritz.tests/src/main/java/org/openhab/binding/avmfritz/internal/discovery/AVMFritzDiscoveryServiceOSGiTest.java
Labels: enhancement

#11576 [miio] i18n translation handling for basic channels
  bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/MiIoBindingConstants.java
  bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/MiIoHandlerFactory.java
  bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/handler/MiIoAbstractHandler.java
  bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/handler/MiIoBasicHandler.java
  bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/handler/MiIoGenericHandler.java
  bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/handler/MiIoUnsupportedHandler.java
  bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/handler/MiIoVacuumHandler.java
  bundles/org.openhab.binding.miio/src/main/resources/OH-INF/i18n/basic.properties
  bundles/org.openhab.binding.miio/src/test/java/org/openhab/binding/miio/internal/ReadmeHelper.java
Labels: enhancement, translation

#11681 [logreader] Added pattern for DateTime channel types
  bundles/org.openhab.binding.logreader/src/main/resources/OH-INF/thing/channels.xml
Labels: translation

#11689 [chromecast] Added configuration flag to disable background discovery
  bundles/org.openhab.binding.chromecast/README.md
  bundles/org.openhab.binding.chromecast/src/main/java/org/openhab/binding/chromecast/internal/discovery/ChromecastDiscoveryParticipant.java
Labels: enhancement

#11687 [miio] add support for Mi Smart Humidifer S (deerma.humidifier.jsqs)
  bundles/org.openhab.binding.miio/README.md
  bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/MiIoDevices.java
  bundles/org.openhab.binding.miio/src/main/resources/database/deerma.humidifier.jsq5.json
Labels: enhancement

#11690 [miio] Improve binding description
  bundles/org.openhab.binding.miio/README.base.md
  bundles/org.openhab.binding.miio/README.md
  bundles/org.openhab.binding.miio/pom.xml
  bundles/org.openhab.binding.miio/src/main/feature/feature.xml
  bundles/org.openhab.binding.miio/src/main/resources/OH-INF/binding/binding.xml
  bundles/org.openhab.binding.miio/src/main/resources/OH-INF/i18n/miio.properties
Labels: documentation

#11694 [chromecast] Added pattern for DateTime channel types
  bundles/org.openhab.binding.chromecast/src/main/resources/OH-INF/thing/thing-types.xml
Labels: translation

#11699 [miio/ntp] Fix wrong "Date" channel category
  bundles/org.openhab.binding.miio/src/main/resources/OH-INF/thing/vacuumThing.xml
  bundles/org.openhab.binding.ntp/src/main/resources/OH-INF/thing/thing-types.xml
Labels: bug

#11607 [SNCF] A binding to get French railways arrivals and departures
  CODEOWNERS
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.sncf/NOTICE
  bundles/org.openhab.binding.sncf/README.md
  bundles/org.openhab.binding.sncf/pom.xml
  bundles/org.openhab.binding.sncf/src/main/feature/feature.xml
  bundles/org.openhab.binding.sncf/src/main/java/org/openhab/binding/sncf/internal/SncfBindingConstants.java
  bundles/org.openhab.binding.sncf/src/main/java/org/openhab/binding/sncf/internal/SncfException.java
  bundles/org.openhab.binding.sncf/src/main/java/org/openhab/binding/sncf/internal/SncfHandlerFactory.java
  bundles/org.openhab.binding.sncf/src/main/java/org/openhab/binding/sncf/internal/discovery/SncfDiscoveryService.java
  bundles/org.openhab.binding.sncf/src/main/java/org/openhab/binding/sncf/internal/dto/Coord.java
  bundles/org.openhab.binding.sncf/src/main/java/org/openhab/binding/sncf/internal/dto/NavitiaObject.java
  bundles/org.openhab.binding.sncf/src/main/java/org/openhab/binding/sncf/internal/dto/Passage.java
  bundles/org.openhab.binding.sncf/src/main/java/org/openhab/binding/sncf/internal/dto/Passages.java
  bundles/org.openhab.binding.sncf/src/main/java/org/openhab/binding/sncf/internal/dto/PlaceNearby.java
  bundles/org.openhab.binding.sncf/src/main/java/org/openhab/binding/sncf/internal/dto/PlacesNearby.java
  bundles/org.openhab.binding.sncf/src/main/java/org/openhab/binding/sncf/internal/dto/SncfAnswer.java
  bundles/org.openhab.binding.sncf/src/main/java/org/openhab/binding/sncf/internal/dto/StopArea.java
  bundles/org.openhab.binding.sncf/src/main/java/org/openhab/binding/sncf/internal/dto/StopDateTime.java
  bundles/org.openhab.binding.sncf/src/main/java/org/openhab/binding/sncf/internal/dto/StopPoint.java
  bundles/org.openhab.binding.sncf/src/main/java/org/openhab/binding/sncf/internal/dto/StopPoints.java
  bundles/org.openhab.binding.sncf/src/main/java/org/openhab/binding/sncf/internal/dto/VJDisplayInformation.java
  bundles/org.openhab.binding.sncf/src/main/java/org/openhab/binding/sncf/internal/handler/SncfBridgeHandler.java
  bundles/org.openhab.binding.sncf/src/main/java/org/openhab/binding/sncf/internal/handler/StationHandler.java
  bundles/org.openhab.binding.sncf/src/main/resources/OH-INF/binding/binding.xml
  bundles/org.openhab.binding.sncf/src/main/resources/OH-INF/config/config.xml
  bundles/org.openhab.binding.sncf/src/main/resources/OH-INF/i18n/sncf.properties
  bundles/org.openhab.binding.sncf/src/main/resources/OH-INF/thing/bridge.xml
  bundles/org.openhab.binding.sncf/src/main/resources/OH-INF/thing/station.xml
  bundles/pom.xml
Labels: new binding

#11467 [renault] Initial Contribution
  CODEOWNERS
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.renault/NOTICE
  bundles/org.openhab.binding.renault/README.md
  bundles/org.openhab.binding.renault/pom.xml
  bundles/org.openhab.binding.renault/src/main/feature/feature.xml
  bundles/org.openhab.binding.renault/src/main/java/org/openhab/binding/renault/internal/RenaultBindingConstants.java
  bundles/org.openhab.binding.renault/src/main/java/org/openhab/binding/renault/internal/RenaultConfiguration.java
  bundles/org.openhab.binding.renault/src/main/java/org/openhab/binding/renault/internal/RenaultHandlerFactory.java
  bundles/org.openhab.binding.renault/src/main/java/org/openhab/binding/renault/internal/api/Car.java
  bundles/org.openhab.binding.renault/src/main/java/org/openhab/binding/renault/internal/api/Constants.java
  bundles/org.openhab.binding.renault/src/main/java/org/openhab/binding/renault/internal/api/MyRenaultHttpSession.java
  bundles/org.openhab.binding.renault/src/main/java/org/openhab/binding/renault/internal/api/exceptions/RenaultException.java
  bundles/org.openhab.binding.renault/src/main/java/org/openhab/binding/renault/internal/api/exceptions/RenaultForbiddenException.java
  bundles/org.openhab.binding.renault/src/main/java/org/openhab/binding/renault/internal/api/exceptions/RenaultNotImplementedException.java
  bundles/org.openhab.binding.renault/src/main/java/org/openhab/binding/renault/internal/api/exceptions/RenaultUpdateException.java
  bundles/org.openhab.binding.renault/src/main/java/org/openhab/binding/renault/internal/handler/RenaultHandler.java
  bundles/org.openhab.binding.renault/src/main/resources/OH-INF/binding/binding.xml
  bundles/org.openhab.binding.renault/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/pom.xml
Labels: new binding

#11500 [openuv] Fix internationalization of discovery result
  bundles/org.openhab.binding.openuv/src/main/java/org/openhab/binding/openuv/internal/OpenUVHandlerFactory.java
  bundles/org.openhab.binding.openuv/src/main/java/org/openhab/binding/openuv/internal/discovery/OpenUVDiscoveryService.java
  bundles/org.openhab.binding.openuv/src/main/java/org/openhab/binding/openuv/internal/handler/OpenUVBridgeHandler.java
Labels: translation

#11700 [sleepiq] Use constructor injection for ClientBuilder
  bundles/org.openhab.binding.sleepiq/src/3rdparty/java/org/openhab/binding/sleepiq/api/SleepIQ.java
  bundles/org.openhab.binding.sleepiq/src/3rdparty/java/org/openhab/binding/sleepiq/api/impl/SleepIQImpl.java
  bundles/org.openhab.binding.sleepiq/src/3rdparty/java/org/openhab/binding/sleepiq/api/model/TimeSince.java
  bundles/org.openhab.binding.sleepiq/src/main/java/org/openhab/binding/sleepiq/internal/SleepIQHandlerFactory.java
  bundles/org.openhab.binding.sleepiq/src/main/java/org/openhab/binding/sleepiq/internal/handler/SleepIQCloudHandler.java
Labels: bug

#11644 [openwebnet] Fixes discovery of devices on local bus. Added it translation
  bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/discovery/OpenWebNetDeviceDiscoveryService.java
  bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/handler/OpenWebNetBridgeHandler.java
  bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/i18n/openwebnet.properties
  bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/i18n/openwebnet_hu.properties
  bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/i18n/openwebnet_it.properties
Labels: bug

#11707 [hdpowerview] Fix initialization of shade handler
  bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/handler/HDPowerViewHubHandler.java
  bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/handler/HDPowerViewShadeHandler.java
  bundles/org.openhab.binding.hdpowerview/src/main/resources/OH-INF/i18n/hdpowerview.properties
Labels: bug

#11708 [systeminfo] Fix Thing and Sitemap example
  bundles/org.openhab.binding.systeminfo/README.md
Labels: documentation

#11709 Rename English i18n properties to follow Crowdin naming conventions
  bundles/org.openhab.binding.digitalstrom/src/main/resources/OH-INF/i18n/digitalstrom.properties
  bundles/org.openhab.binding.dsmr/src/main/resources/OH-INF/i18n/dsmr.properties
  bundles/org.openhab.binding.enphase/src/main/resources/OH-INF/i18n/enphase.properties
  bundles/org.openhab.binding.lghombot/src/main/resources/OH-INF/i18n/lghombot.properties
  bundles/org.openhab.binding.mqtt/src/main/resources/OH-INF/i18n/mqttbroker.properties
  bundles/org.openhab.binding.playstation/src/main/resources/OH-INF/i18n/playstation.properties
  bundles/org.openhab.binding.pushbullet/src/main/resources/OH-INF/i18n/pushbullet.properties
  bundles/org.openhab.binding.spotify/src/main/resources/OH-INF/i18n/spotify.properties
  bundles/org.openhab.binding.urtsi/src/main/resources/OH-INF/i18n/urtsi.properties
Labels: translation

#11714 [mqtt] Add missing English translations
  bundles/org.openhab.binding.mqtt/src/main/resources/OH-INF/i18n/mqttbroker.properties
Labels: translation

#11713 [dsmr] Add missing English translations
  bundles/org.openhab.binding.dsmr/src/main/resources/OH-INF/i18n/dsmr.properties
Labels: translation

#11721 [chromecast/kodi/logreader] Rerun latest i18n tool version to add missing translations
  bundles/org.openhab.binding.chromecast/src/main/resources/OH-INF/i18n/chromecast.properties
  bundles/org.openhab.binding.kodi/src/main/resources/OH-INF/i18n/kodi.properties
  bundles/org.openhab.binding.logreader/src/main/resources/OH-INF/i18n/logreader.properties
  bundles/org.openhab.io.openhabcloud/src/main/resources/OH-INF/i18n/openhabcloud.properties
  bundles/org.openhab.voice.googletts/src/main/resources/OH-INF/i18n/googletts.properties
Labels: translation

#11720 [homekit] restart HomeKit bridge on network changes
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitImpl.java
Labels: bug

#11723 [avmfritz] Added support for HAN-FUN Color and Dimmable bulbs
  bundles/org.openhab.binding.avmfritz/README.md
  bundles/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/AVMFritzBindingConstants.java
  bundles/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/dto/ColorControlModel.java
  bundles/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/dto/HeatingModel.java
  bundles/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/handler/AVMFritzBaseBridgeHandler.java
  bundles/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/handler/AVMFritzBaseThingHandler.java
  bundles/org.openhab.binding.avmfritz/src/main/resources/OH-INF/i18n/avmfritz.properties
  bundles/org.openhab.binding.avmfritz/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.avmfritz/src/test/java/org/openhab/binding/avmfritz/internal/dto/ColorControlModelTest.java
  itests/org.openhab.binding.avmfritz.tests/src/main/java/org/openhab/binding/avmfritz/internal/discovery/AVMFritzDiscoveryServiceOSGiTest.java
Labels: enhancement

#11722 [miio] Fix zhimi.airpurifier.vb2 channel unit
  bundles/org.openhab.binding.miio/README.md
  bundles/org.openhab.binding.miio/src/main/resources/database/zhimi.airpurifier.vb2-miot.json
Labels: bug

#11728 [pollytts] Add default translations properties file
  bundles/org.openhab.voice.pollytts/src/main/resources/OH-INF/i18n/pollytts.properties
Labels: translation

#11726 [lutron] Explicitly enable proper monitoring types for HomeWorks connections
  bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/handler/IPBridgeHandler.java
  bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/protocol/lip/Monitoring.java
Labels: enhancement

#11731 [homekit] add setting to block homekit user/pairing deletion
  bundles/org.openhab.io.homekit/README.md
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitAuthInfoImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitSettings.java
  bundles/org.openhab.io.homekit/src/main/resources/OH-INF/config/config.xml
Labels: bug

#11739 [hpprinter] Change status channel from hash map values to state description options.
  bundles/org.openhab.binding.hpprinter/src/main/java/org/openhab/binding/hpprinter/internal/api/HPProductUsageFeatures.java
  bundles/org.openhab.binding.hpprinter/src/main/java/org/openhab/binding/hpprinter/internal/api/HPStatus.java
  bundles/org.openhab.binding.hpprinter/src/main/resources/OH-INF/thing/channel-types.xml
Labels: enhancement

#11734 [nzwateralerts] Fix smart water alert level.
  bundles/org.openhab.binding.nzwateralerts/src/main/java/org/openhab/binding/nzwateralerts/internal/api/SmartWater.java
Labels: bug

#11737 [nikohomecontrol] Fix dimmer control sequence
  bundles/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/protocol/nhc2/NikoHomeControlCommunication2.java
Labels: bug

#11717 [homekit] make min/max values for Color Temperature configurable
  bundles/org.openhab.io.homekit/README.md
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitTaggedItem.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitCharacteristicFactory.java
Labels: bug

#11746 [plugwise] Fix 'power' channel not correctly updated with power production
  bundles/org.openhab.binding.plugwise/src/main/java/org/openhab/binding/plugwise/internal/protocol/PowerInformationResponseMessage.java
Labels: bug, community approved

#11693 [jsscripting] Added simple Shared Cache into scope
  bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/scope/SharedCache.java
Labels: enhancement

#10692 Hueemulation: Fix xy change response
  bundles/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/dto/response/HueSuccessResponseStateChanged.java
  bundles/org.openhab.io.hueemulation/src/test/java/org/openhab/io/hueemulation/internal/rest/LightsAndGroupsTests.java
Labels: bug

#11585 [dominoswiss] Initial contribution
  CODEOWNERS
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.dominoswiss/NOTICE
  bundles/org.openhab.binding.dominoswiss/README.md
  bundles/org.openhab.binding.dominoswiss/pom.xml
  bundles/org.openhab.binding.dominoswiss/src/main/feature/feature.xml
  bundles/org.openhab.binding.dominoswiss/src/main/java/org/openhab/binding/dominoswiss/internal/BlindConfig.java
  bundles/org.openhab.binding.dominoswiss/src/main/java/org/openhab/binding/dominoswiss/internal/BlindHandler.java
  bundles/org.openhab.binding.dominoswiss/src/main/java/org/openhab/binding/dominoswiss/internal/DominoswissBindingConstants.java
  bundles/org.openhab.binding.dominoswiss/src/main/java/org/openhab/binding/dominoswiss/internal/DominoswissConfiguration.java
  bundles/org.openhab.binding.dominoswiss/src/main/java/org/openhab/binding/dominoswiss/internal/DominoswissHandlerFactory.java
  bundles/org.openhab.binding.dominoswiss/src/main/java/org/openhab/binding/dominoswiss/internal/EGateHandler.java
  bundles/org.openhab.binding.dominoswiss/src/main/resources/OH-INF/binding/binding.xml
  bundles/org.openhab.binding.dominoswiss/src/main/resources/OH-INF/i18n/dominoswiss_de_DE.properties
  bundles/org.openhab.binding.dominoswiss/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/pom.xml
Labels: new binding

#11631 [pulseaudio] Add reencoding to play more audio formats (#11630)
  bundles/org.openhab.binding.pulseaudio/src/main/java/org/openhab/binding/pulseaudio/internal/ConvertedInputStream.java
  bundles/org.openhab.binding.pulseaudio/src/main/java/org/openhab/binding/pulseaudio/internal/PulseAudioAudioSink.java
Labels: enhancement

#11493 [Homematic] Fix "Channel not found for Datapoint"-Errors
  bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/handler/HomematicThingHandler.java
Labels: bug

#11637 [hdpowerview] Add support for enabling/disabling automations
  bundles/org.openhab.binding.hdpowerview/README.md
  bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/HDPowerViewBindingConstants.java
  bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/HDPowerViewTranslationProvider.java
  bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/HDPowerViewWebTargets.java
  bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/api/responses/SceneCollections.java
  bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/api/responses/Scenes.java
  bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/api/responses/ScheduledEvents.java
  bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/handler/HDPowerViewHubHandler.java
  bundles/org.openhab.binding.hdpowerview/src/main/resources/OH-INF/i18n/hdpowerview.properties
  bundles/org.openhab.binding.hdpowerview/src/main/resources/OH-INF/i18n/hdpowerview_da.properties
  bundles/org.openhab.binding.hdpowerview/src/main/resources/OH-INF/thing/thing-types.xml
Labels: enhancement

#11643 Bump jsoup from 1.8.3 to 1.14.3
  bundles/org.openhab.binding.ahawastecollection/pom.xml
  bundles/org.openhab.binding.ahawastecollection/src/main/feature/feature.xml
  bundles/org.openhab.binding.ipobserver/pom.xml
  bundles/org.openhab.binding.ipobserver/src/main/feature/feature.xml
  bundles/org.openhab.binding.kostalinverter/pom.xml
  bundles/org.openhab.binding.kostalinverter/src/main/feature/feature.xml
  bundles/org.openhab.binding.linky/pom.xml
  bundles/org.openhab.binding.linky/src/main/feature/feature.xml
  bundles/org.openhab.binding.myq/pom.xml
  bundles/org.openhab.binding.myq/src/main/feature/feature.xml
  bundles/org.openhab.binding.tesla/pom.xml
  bundles/org.openhab.binding.tesla/src/main/feature/feature.xml
  bundles/org.openhab.binding.verisure/pom.xml
  bundles/org.openhab.binding.verisure/src/main/feature/feature.xml
  bundles/org.openhab.transform.jinja/pom.xml
  bundles/org.openhab.transform.jinja/src/main/feature/feature.xml
Labels: bug, security, additional testing preferred

#11091 [jdbc] Add support for TimescaleDB (#11090)
  bundles/org.openhab.persistence.jdbc/README.md
  bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/db/JdbcBaseDAO.java
  bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/db/JdbcTimescaledbDAO.java
  bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/JdbcConfiguration.java
Labels: enhancement

#9851 [mqtt] Fix availability topics subscription after Brige Restart
  bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/AbstractMQTTThingHandler.java
  bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/internal/handler/GenericMQTTThingHandler.java
  bundles/org.openhab.binding.mqtt.generic/src/test/java/org/openhab/binding/mqtt/generic/internal/handler/GenericThingHandlerTests.java
Labels: bug, awaiting feedback

#11755 Add default translations for transform add-ons
  bundles/org.openhab.transform.exec/src/main/resources/OH-INF/config/execProfile.xml
  bundles/org.openhab.transform.exec/src/main/resources/OH-INF/i18n/exec.properties
  bundles/org.openhab.transform.javascript/src/main/resources/OH-INF/config/javascriptProfile.xml
  bundles/org.openhab.transform.javascript/src/main/resources/OH-INF/i18n/js.properties
  bundles/org.openhab.transform.jinja/src/main/resources/OH-INF/config/jinjaProfile.xml
  bundles/org.openhab.transform.jinja/src/main/resources/OH-INF/i18n/jinja.properties
  bundles/org.openhab.transform.jsonpath/src/main/resources/OH-INF/config/jsonpathProfile.xml
  bundles/org.openhab.transform.jsonpath/src/main/resources/OH-INF/i18n/jsonpath.properties
  bundles/org.openhab.transform.regex/src/main/resources/OH-INF/config/regexProfile.xml
  bundles/org.openhab.transform.regex/src/main/resources/OH-INF/i18n/regex.properties
  bundles/org.openhab.transform.scale/src/main/resources/OH-INF/config/scaleProfile.xml
  bundles/org.openhab.transform.scale/src/main/resources/OH-INF/i18n/scale.properties
  bundles/org.openhab.transform.xpath/src/main/resources/OH-INF/config/xpathProfile.xml
  bundles/org.openhab.transform.xpath/src/main/resources/OH-INF/i18n/xpath.properties
  bundles/org.openhab.transform.xslt/src/main/resources/OH-INF/config/xsltProfile.xml
  bundles/org.openhab.transform.xslt/src/main/resources/OH-INF/i18n/xslt.properties
Labels: translation

#11754 Add default translations for persistence add-ons
  bundles/org.openhab.persistence.dynamodb/src/main/resources/OH-INF/i18n/dynamodb.properties
  bundles/org.openhab.persistence.influxdb/src/main/resources/OH-INF/i18n/influxdb.properties
  bundles/org.openhab.persistence.jdbc/src/main/resources/OH-INF/i18n/jdbc.properties
Labels: translation

#11429 [homematic] Improve (re)connect handling to Homematic gateways
  bundles/org.openhab.binding.homematic/README.md
  bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/HomematicBindingConstants.java
  bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/common/HomematicConfig.java
  bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/communicator/AbstractHomematicGateway.java
  bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/communicator/client/BinRpcClient.java
  bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/communicator/client/RpcClient.java
  bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/communicator/client/XmlRpcClient.java
  bundles/org.openhab.binding.homematic/src/main/resources/OH-INF/thing/bridge.xml
Labels: enhancement

#11372 Extend .gitignore
  .gitignore
Labels: infrastructure

#11748 [ipcamera] Add new channel lastEventData for detailed extra data on alarms
  bundles/org.openhab.binding.ipcamera/README.md
  bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/DahuaHandler.java
  bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/Ffmpeg.java
  bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/Helper.java
  bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/HikvisionHandler.java
  bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/IpCameraBindingConstants.java
  bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/handler/IpCameraHandler.java
  bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/onvif/OnvifConnection.java
  bundles/org.openhab.binding.ipcamera/src/main/resources/OH-INF/thing/thing-types.xml
Labels: enhancement

#11757 [urtsi] Fixed leading spaces in translations
  bundles/org.openhab.binding.urtsi/src/main/resources/OH-INF/binding/binding.xml
  bundles/org.openhab.binding.urtsi/src/main/resources/OH-INF/i18n/urtsi.properties
Labels: translation

#11705 [openwebnet] reduced log messages during UPnP bridge discovery
  bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/discovery/BusGatewayUpnpDiscovery.java
Labels: bug, cre

#11753 Add default translations for io add-ons
  bundles/org.openhab.io.homekit/src/main/resources/OH-INF/i18n/homekit.properties
  bundles/org.openhab.io.hueemulation/src/main/resources/OH-INF/i18n/hueemulation.properties
  bundles/org.openhab.io.metrics/src/main/java/org/openhab/io/metrics/MetricsRestController.java
  bundles/org.openhab.io.metrics/src/main/resources/OH-INF/i18n/metrics.properties
  bundles/org.openhab.io.neeo/src/main/java/org/openhab/io/neeo/NeeoService.java
  bundles/org.openhab.io.neeo/src/main/resources/OH-INF/i18n/neeo.properties
Labels: translation

#11473 [js-transform] inline java script support
  bundles/org.openhab.transform.javascript/README.md
  bundles/org.openhab.transform.javascript/src/main/java/org/openhab/transform/javascript/internal/JavaScriptEngineManager.java
  bundles/org.openhab.transform.javascript/src/main/java/org/openhab/transform/javascript/internal/JavaScriptTransformationService.java
  bundles/org.openhab.transform.javascript/src/main/resources/OH-INF/config/javascriptProfile.xml
  bundles/org.openhab.transform.javascript/src/test/java/org/openhab/transform/javascript/internal/JavaScriptTransformationServiceTest.java
Labels: enhancement

#11763 [miio] Improve Viomi vacuums, add docking and route channel & mapping
  bundles/org.openhab.binding.miio/README.md
  bundles/org.openhab.binding.miio/src/main/resources/OH-INF/i18n/basic.properties
  bundles/org.openhab.binding.miio/src/main/resources/database/viomi.vacuum.v8.json
Labels: enhancement, community approved

#11727 [miio] Add support for Roidmi EVE roidmi.vacuum.v60
  bundles/org.openhab.binding.miio/README.md
  bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/MiIoDevices.java
  bundles/org.openhab.binding.miio/src/main/resources/OH-INF/i18n/basic.properties
  bundles/org.openhab.binding.miio/src/main/resources/database/roidmi.vacuum.v60-miot.json
Labels: enhancement

#11715 [miio] add BT Devices channel to chuangmi plug
  bundles/org.openhab.binding.miio/README.md
  bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/MiIoSendCommand.java
  bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/basic/Conversions.java
  bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/basic/MiIoBasicChannel.java
  bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/handler/MiIoBasicHandler.java
  bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/transport/MiIoAsyncCommunication.java
  bundles/org.openhab.binding.miio/src/main/resources/OH-INF/i18n/basic.properties
  bundles/org.openhab.binding.miio/src/main/resources/database/chuangmi.plug.212a01-miot.json
  bundles/org.openhab.binding.miio/src/test/java/org/openhab/binding/miio/internal/ConversionsTest.java
Labels: enhancement

#11719 GraalJS now uses automation/js
  bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/GraalJSScriptEngineFactory.java
  bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/OpenhabGraalJSScriptEngine.java
  bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/fs/watch/JSDependencyTracker.java
  bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/fs/watch/JSScriptFileWatcher.java
Labels: enhancement

#11656 [jsscripting] openhab-js integration
  bundles/org.openhab.automation.jsscripting/pom.xml
  bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/GraalJSScriptEngineFactory.java
  bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/OpenhabGraalJSScriptEngine.java
  bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/fs/ReadOnlySeekableByteArrayChannel.java
  bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/scope/AbstractScriptExtensionProvider.java
  bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/scope/ClassExtender.java
  bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/scope/Lifecycle.java
  bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/scope/OSGiScriptExtensionProvider.java
  bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/scope/ScriptDisposalAware.java
  bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/scope/ScriptDisposalAwareScriptExtensionProvider.java
  bundles/org.openhab.automation.jsscripting/src/main/resources/OH-INF/config/config.xml
  bundles/org.openhab.automation.jsscripting/src/main/resources/node_modules/@jsscripting-globals.js
Labels: enhancement

#11782 [miele] Reduce log level to TRACE for request/response logging
  bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/MieleBridgeHandler.java
Labels: bug, enhancement

#11645 [omnikinverter] feature: Add channels for voltage and current
  bundles/org.openhab.binding.omnikinverter/README.md
  bundles/org.openhab.binding.omnikinverter/src/main/java/org/openhab/binding/omnikinverter/internal/OmnikInverterBindingConstants.java
  bundles/org.openhab.binding.omnikinverter/src/main/java/org/openhab/binding/omnikinverter/internal/OmnikInverterMessage.java
  bundles/org.openhab.binding.omnikinverter/src/main/java/org/openhab/binding/omnikinverter/internal/handler/OmnikInverterHandler.java
  bundles/org.openhab.binding.omnikinverter/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.omnikinverter/src/test/java/org/openhab/binding/omnikinverter/internal/test/OmnikInverterMessageTest.java
Labels: enhancement

#11786 [wled] Fix two events being logged when light is off.
  bundles/org.openhab.binding.wled/src/main/java/org/openhab/binding/wled/internal/api/WledApiV084.java
Labels: bug

#11773 [avmfritz] Fixed update of data for blinds
  bundles/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/handler/AVMFritzBaseThingHandler.java
  bundles/org.openhab.binding.avmfritz/src/test/java/org/openhab/binding/avmfritz/internal/dto/AVMFritzDeviceListModelTest.java
Labels: bug

#11783 iRobot zone support added
  bundles/org.openhab.binding.irobot/README.md
  bundles/org.openhab.binding.irobot/src/main/java/org/openhab/binding/irobot/internal/dto/MQTTProtocol.java
  bundles/org.openhab.binding.irobot/src/main/java/org/openhab/binding/irobot/internal/handler/RoombaHandler.java
Labels: enhancement

#11794 [miio] fix action channel miot for empty input with parameters
  bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/handler/MiIoBasicHandler.java
Labels: bug

#11799 [samsungtv] Rename German translations file
  bundles/org.openhab.binding.samsungtv/src/main/resources/OH-INF/i18n/samsungtv_de.properties
Labels: translation

#11798 [jsscripting] Add default translations
  bundles/org.openhab.automation.jsscripting/src/main/resources/OH-INF/i18n/jsscripting.properties
Labels: translation

#11788 [miio] Cleanup devices section of readme
  bundles/org.openhab.binding.miio/README.md
  bundles/org.openhab.binding.miio/src/main/resources/OH-INF/i18n/basic.properties
  bundles/org.openhab.binding.miio/src/main/resources/database/careli.fryer.maf01-miot.json
  bundles/org.openhab.binding.miio/src/main/resources/database/careli.fryer.maf02-miot.json
  bundles/org.openhab.binding.miio/src/main/resources/database/cgllc.airm.cgdn1-miot.json
  bundles/org.openhab.binding.miio/src/main/resources/database/dmaker.fan.p18-miot.json
  bundles/org.openhab.binding.miio/src/main/resources/database/dmaker.fan.p8-miot.json
  bundles/org.openhab.binding.miio/src/main/resources/database/dreame.vacuum.mc1808-miot.json
  bundles/org.openhab.binding.miio/src/main/resources/database/dreame.vacuum.p2008-miot.json
  bundles/org.openhab.binding.miio/src/main/resources/database/dreame.vacuum.p2009-miot.json
  bundles/org.openhab.binding.miio/src/main/resources/database/viomi.vacuum.v18-miot.json
  bundles/org.openhab.binding.miio/src/main/resources/database/zhimi.airfresh.ua1-miot.json
  bundles/org.openhab.binding.miio/src/main/resources/database/zhimi.airpurifier.ma4-miot.json
  bundles/org.openhab.binding.miio/src/main/resources/database/zhimi.airpurifier.mb3-miot.json
  bundles/org.openhab.binding.miio/src/main/resources/database/zhimi.airpurifier.mb4-miot.json
  bundles/org.openhab.binding.miio/src/main/resources/database/zhimi.heater.ma3-miot.json
Labels: documentation

#11510 [chromecast] Added support for next command
  bundles/org.openhab.binding.chromecast/README.md
  bundles/org.openhab.binding.chromecast/src/main/java/org/openhab/binding/chromecast/internal/ChromecastCommander.java
  bundles/org.openhab.binding.chromecast/src/main/java/org/openhab/binding/chromecast/internal/ChromecastStatusUpdater.java
Labels: enhancement

#11821 [touchwand] Secure url's for the readme
  bundles/org.openhab.binding.touchwand/README.md
Labels: documentation

#11817 [map] Rename transform.properties to map.properties
  bundles/org.openhab.transform.map/src/main/resources/OH-INF/i18n/map.properties
  bundles/org.openhab.transform.map/src/main/resources/OH-INF/i18n/map_de.properties
  bundles/org.openhab.transform.map/src/main/resources/OH-INF/i18n/map_fr.properties
Labels: translation

#11823 [jrubyscripting] Update version to 9.3.2 in README.md
  bundles/org.openhab.automation.jrubyscripting/README.md
Labels: documentation

#11771 [tplinksmarthome] Added new devices ES20, KP125, KP405 and KS230
  bundles/org.openhab.binding.tplinksmarthome/README.md
  bundles/org.openhab.binding.tplinksmarthome/src/main/java/org/openhab/binding/tplinksmarthome/internal/TPLinkSmartHomeThingType.java
  bundles/org.openhab.binding.tplinksmarthome/src/main/resources/OH-INF/i18n/tplinksmarthome.properties
  bundles/org.openhab.binding.tplinksmarthome/src/main/resources/OH-INF/thing/ES20M.xml
  bundles/org.openhab.binding.tplinksmarthome/src/main/resources/OH-INF/thing/KP125.xml
  bundles/org.openhab.binding.tplinksmarthome/src/main/resources/OH-INF/thing/KP405.xml
  bundles/org.openhab.binding.tplinksmarthome/src/main/resources/OH-INF/thing/KS230.xml
Labels: enhancement

#11806 [wled] Fix Global OFF not turning lights/segments off.
  bundles/org.openhab.binding.wled/src/main/java/org/openhab/binding/wled/internal/api/WledApiV084.java
Labels: bug

#11813 [onkyo] Add channels for media info
  bundles/org.openhab.binding.onkyo/README.md
  bundles/org.openhab.binding.onkyo/src/main/java/org/openhab/binding/onkyo/internal/OnkyoBindingConstants.java
  bundles/org.openhab.binding.onkyo/src/main/java/org/openhab/binding/onkyo/internal/OnkyoParserHelper.java
  bundles/org.openhab.binding.onkyo/src/main/java/org/openhab/binding/onkyo/internal/eiscp/EiscpCommand.java
  bundles/org.openhab.binding.onkyo/src/main/java/org/openhab/binding/onkyo/internal/handler/OnkyoHandler.java
  bundles/org.openhab.binding.onkyo/src/main/resources/OH-INF/i18n/onkyo.properties
  bundles/org.openhab.binding.onkyo/src/main/resources/OH-INF/thing/channel-groups.xml
  bundles/org.openhab.binding.onkyo/src/main/resources/OH-INF/thing/channels.xml
  bundles/org.openhab.binding.onkyo/src/main/resources/OH-INF/thing/ht-rc560.xml
  bundles/org.openhab.binding.onkyo/src/main/resources/OH-INF/thing/onkyoAVR.xml
  bundles/org.openhab.binding.onkyo/src/main/resources/OH-INF/thing/onkyoUnsupported.xml
  bundles/org.openhab.binding.onkyo/src/main/resources/OH-INF/thing/tx-nr3007.xml
  bundles/org.openhab.binding.onkyo/src/main/resources/OH-INF/thing/tx-nr414.xml
  bundles/org.openhab.binding.onkyo/src/main/resources/OH-INF/thing/tx-nr474.xml
  bundles/org.openhab.binding.onkyo/src/main/resources/OH-INF/thing/tx-nr509.xml
  bundles/org.openhab.binding.onkyo/src/main/resources/OH-INF/thing/tx-nr515.xml
  bundles/org.openhab.binding.onkyo/src/main/resources/OH-INF/thing/tx-nr525.xml
  bundles/org.openhab.binding.onkyo/src/main/resources/OH-INF/thing/tx-nr535.xml
  bundles/org.openhab.binding.onkyo/src/main/resources/OH-INF/thing/tx-nr545.xml
  bundles/org.openhab.binding.onkyo/src/main/resources/OH-INF/thing/tx-nr555.xml
  bundles/org.openhab.binding.onkyo/src/main/resources/OH-INF/thing/tx-nr575.xml
  bundles/org.openhab.binding.onkyo/src/main/resources/OH-INF/thing/tx-nr575e.xml
  bundles/org.openhab.binding.onkyo/src/main/resources/OH-INF/thing/tx-nr616.xml
  bundles/org.openhab.binding.onkyo/src/main/resources/OH-INF/thing/tx-nr626.xml
  bundles/org.openhab.binding.onkyo/src/main/resources/OH-INF/thing/tx-nr636.xml
  bundles/org.openhab.binding.onkyo/src/main/resources/OH-INF/thing/tx-nr646.xml
  bundles/org.openhab.binding.onkyo/src/main/resources/OH-INF/thing/tx-nr656.xml
  bundles/org.openhab.binding.onkyo/src/main/resources/OH-INF/thing/tx-nr676.xml
  bundles/org.openhab.binding.onkyo/src/main/resources/OH-INF/thing/tx-nr686.xml
  bundles/org.openhab.binding.onkyo/src/main/resources/OH-INF/thing/tx-nr708.xml
  bundles/org.openhab.binding.onkyo/src/main/resources/OH-INF/thing/tx-nr717.xml
  bundles/org.openhab.binding.onkyo/src/main/resources/OH-INF/thing/tx-nr727.xml
  bundles/org.openhab.binding.onkyo/src/main/resources/OH-INF/thing/tx-nr737.xml
  bundles/org.openhab.binding.onkyo/src/main/resources/OH-INF/thing/tx-nr747.xml
  bundles/org.openhab.binding.onkyo/src/main/resources/OH-INF/thing/tx-nr809.xml
  bundles/org.openhab.binding.onkyo/src/main/resources/OH-INF/thing/tx-nr818.xml
  bundles/org.openhab.binding.onkyo/src/main/resources/OH-INF/thing/tx-nr828.xml
  bundles/org.openhab.binding.onkyo/src/main/resources/OH-INF/thing/tx-nr838.xml
  bundles/org.openhab.binding.onkyo/src/main/resources/OH-INF/thing/tx-rz900.xml
Labels: enhancement

#11792 [ventaair] Add Air quality and service time channels
  bundles/org.openhab.binding.ventaair/src/main/java/org/openhab/binding/ventaair/internal/VentaAirBindingConstants.java
  bundles/org.openhab.binding.ventaair/src/main/java/org/openhab/binding/ventaair/internal/VentaThingHandler.java
  bundles/org.openhab.binding.ventaair/src/main/java/org/openhab/binding/ventaair/internal/message/dto/Info.java
  bundles/org.openhab.binding.ventaair/src/main/java/org/openhab/binding/ventaair/internal/message/dto/Measurements.java
  bundles/org.openhab.binding.ventaair/src/main/resources/OH-INF/i18n/ventaair.properties
  bundles/org.openhab.binding.ventaair/src/main/resources/OH-INF/thing/channels.xml
  bundles/org.openhab.binding.ventaair/src/main/resources/OH-INF/thing/thing-types.xml
Labels: enhancement

#11836 Example fixed
  bundles/org.openhab.automation.jsscripting/README.md
Labels: documentation

#11839 [tplinksmarthome] KP405 channel in xml should be dimmer not switch
  bundles/org.openhab.binding.tplinksmarthome/src/main/resources/OH-INF/thing/KP405.xml
Labels: bug

#11840 [tradfri] Fix UTF-8 characters in i18n properties file
  bundles/org.openhab.binding.tradfri/src/main/resources/OH-INF/config/config.xml
  bundles/org.openhab.binding.tradfri/src/main/resources/OH-INF/i18n/tradfri.properties
Labels: translation

#11826 Bump netty to 4.1.72.Final for log4j2 2.15.0 fix
  pom.xml
Labels: awaiting other PR

#11850 Fix pom http://maven.apache.org/xsd/maven-v4_0_0.xsd entries
  bundles/org.openhab.binding.adorne/pom.xml
  bundles/org.openhab.binding.amazondashbutton/pom.xml
  bundles/org.openhab.binding.broadlinkthermostat/pom.xml
  bundles/org.openhab.binding.caddx/pom.xml
  bundles/org.openhab.binding.cbus/pom.xml
  bundles/org.openhab.binding.dlinksmarthome/pom.xml
  bundles/org.openhab.binding.dmx/pom.xml
  bundles/org.openhab.binding.doorbird/pom.xml
  bundles/org.openhab.binding.etherrain/pom.xml
  bundles/org.openhab.binding.gce/pom.xml
  bundles/org.openhab.binding.haywardomnilogic/pom.xml
  bundles/org.openhab.binding.homeconnect/pom.xml
  bundles/org.openhab.binding.hydrawise/pom.xml
  bundles/org.openhab.binding.icalendar/pom.xml
  bundles/org.openhab.binding.ipcamera/pom.xml
  bundles/org.openhab.binding.jablotron/pom.xml
  bundles/org.openhab.binding.kvv/pom.xml
  bundles/org.openhab.binding.lghombot/pom.xml
  bundles/org.openhab.binding.mecmeter/pom.xml
  bundles/org.openhab.binding.melcloud/pom.xml
  bundles/org.openhab.binding.millheat/pom.xml
  bundles/org.openhab.binding.network/pom.xml
  bundles/org.openhab.binding.nibeheatpump/pom.xml
  bundles/org.openhab.binding.nzwateralerts/pom.xml
  bundles/org.openhab.binding.onewire/pom.xml
  bundles/org.openhab.binding.pixometer/pom.xml
  bundles/org.openhab.binding.playstation/pom.xml
  bundles/org.openhab.binding.sagercaster/pom.xml
  bundles/org.openhab.binding.senechome/pom.xml
  bundles/org.openhab.binding.sensibo/pom.xml
  bundles/org.openhab.binding.smartthings/pom.xml
  bundles/org.openhab.binding.somfymylink/pom.xml
  bundles/org.openhab.binding.telegram/pom.xml
  bundles/org.openhab.binding.teleinfo/pom.xml
  bundles/org.openhab.binding.tr064/pom.xml
  bundles/org.openhab.binding.unifi/pom.xml
  bundles/org.openhab.binding.upnpcontrol/pom.xml
  bundles/org.openhab.binding.verisure/pom.xml
  bundles/org.openhab.binding.weathercompany/pom.xml
  bundles/org.openhab.binding.wled/pom.xml
  bundles/org.openhab.persistence.dynamodb/pom.xml
  bundles/org.openhab.persistence.influxdb/pom.xml
  bundles/org.openhab.persistence.jdbc/pom.xml
  bundles/org.openhab.persistence.jpa/pom.xml
  bundles/org.openhab.persistence.mongodb/pom.xml
  bundles/org.openhab.persistence.rrd4j/pom.xml
Labels: bug

#11849 [MQTT] Add additional logging information
  bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/ChannelState.java
Labels: enhancement

#11809 [amazonechocontrol] Remove duplicate items in the example
  bundles/org.openhab.binding.amazonechocontrol/README.md
Labels: documentation

#8540 [publictransportswitzerland] Public Transport Switzerland Initial contribution
  CODEOWNERS
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.publictransportswitzerland/NOTICE
  bundles/org.openhab.binding.publictransportswitzerland/README.md
  bundles/org.openhab.binding.publictransportswitzerland/doc/departure_board_habpanel.png
  bundles/org.openhab.binding.publictransportswitzerland/pom.xml
  bundles/org.openhab.binding.publictransportswitzerland/src/main/feature/feature.xml
  bundles/org.openhab.binding.publictransportswitzerland/src/main/java/org/openhab/binding/publictransportswitzerland/internal/PublicTransportSwitzerlandBindingConstants.java
  bundles/org.openhab.binding.publictransportswitzerland/src/main/java/org/openhab/binding/publictransportswitzerland/internal/PublicTransportSwitzerlandHandlerFactory.java
  bundles/org.openhab.binding.publictransportswitzerland/src/main/java/org/openhab/binding/publictransportswitzerland/internal/stationboard/PublicTransportSwitzerlandStationboardConfiguration.java
  bundles/org.openhab.binding.publictransportswitzerland/src/main/java/org/openhab/binding/publictransportswitzerland/internal/stationboard/PublicTransportSwitzerlandStationboardHandler.java
  bundles/org.openhab.binding.publictransportswitzerland/src/main/resources/OH-INF/binding/binding.xml
  bundles/org.openhab.binding.publictransportswitzerland/src/main/resources/OH-INF/thing/stationboard.xml
  bundles/pom.xml
Labels: new binding

#11851 [boschshc] Add default translations
  bundles/org.openhab.binding.boschshc/src/main/resources/OH-INF/i18n/boschshc.properties
Labels: translation

#11834 [miele] Fix mDNS issue where hub repeatedly disappears from, resp. reappears in, the Inbox.
  bundles/org.openhab.binding.miele/README.md
  bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/MieleBindingConstants.java
  bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/discovery/MieleMDNSDiscoveryParticipant.java
Labels: bug

#11872 [nanoleaf] Reduce to debug logging in case of communication problems
  bundles/org.openhab.binding.nanoleaf/src/main/java/org/openhab/binding/nanoleaf/internal/OpenAPIUtils.java
Labels: bug

#11873 [miele] Refactor mDNS discovery
  bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/discovery/MieleMDNSDiscoveryParticipant.java
  bundles/org.openhab.binding.miele/src/main/resources/OH-INF/i18n/miele.properties
Labels: enhancement

#11870 [irobot] fixes typo in channel description
  bundles/org.openhab.binding.irobot/src/main/resources/OH-INF/i18n/irobot.properties
  bundles/org.openhab.binding.irobot/src/main/resources/OH-INF/thing/thing.xml
Labels: translation

#11803 [homekit] return min value of characteristic instead of 0
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitCharacteristicFactory.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitHeaterCoolerImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitLightSensorImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitTemperatureSensorImpl.java
Labels: bug

#11854 [myStrom] Request info is not supported by the first generation of plug
  bundles/org.openhab.binding.mystrom/src/main/java/org/openhab/binding/mystrom/internal/AbstractMyStromHandler.java
  bundles/org.openhab.binding.mystrom/src/main/java/org/openhab/binding/mystrom/internal/MyStromBulbHandler.java
Labels: bug

#11874 [nanoleaf] Various small enhancements
  bundles/org.openhab.binding.nanoleaf/src/main/java/org/openhab/binding/nanoleaf/internal/handler/NanoleafControllerHandler.java
  bundles/org.openhab.binding.nanoleaf/src/main/java/org/openhab/binding/nanoleaf/internal/handler/NanoleafPanelHandler.java
  bundles/org.openhab.binding.nanoleaf/src/main/resources/OH-INF/i18n/nanoleaf.properties
  bundles/org.openhab.binding.nanoleaf/src/main/resources/OH-INF/i18n/nanoleaf_de.properties
Labels: enhancement

#11876 [yeelight] Fixed ceiling3 device being recognized as device without night mode
  bundles/org.openhab.binding.yeelight/src/main/java/org/openhab/binding/yeelight/internal/YeelightHandlerFactory.java
  bundles/org.openhab.binding.yeelight/src/main/java/org/openhab/binding/yeelight/internal/lib/device/DeviceFactory.java
  bundles/org.openhab.binding.yeelight/src/main/java/org/openhab/binding/yeelight/internal/lib/services/DeviceManager.java
  bundles/org.openhab.binding.yeelight/src/test/java/org/openhab/binding/yeelight/internal/YeelightHandlerFactoryTest.java
Labels: bug

#11884 [shelly] Fix comment in translations file
  bundles/org.openhab.binding.shelly/src/main/resources/OH-INF/i18n/shelly.properties
  bundles/org.openhab.binding.shelly/src/main/resources/OH-INF/i18n/shelly_de.properties
Labels: translation

#11860 [LuxtronikHeatpump] Adds additional channels
  bundles/org.openhab.binding.luxtronikheatpump/README.md
  bundles/org.openhab.binding.luxtronikheatpump/src/main/java/org/openhab/binding/luxtronikheatpump/internal/ChannelUpdaterJob.java
  bundles/org.openhab.binding.luxtronikheatpump/src/main/java/org/openhab/binding/luxtronikheatpump/internal/enums/HeatpumpChannel.java
  bundles/org.openhab.binding.luxtronikheatpump/src/main/resources/OH-INF/i18n/luxtronikheatpump.properties
  bundles/org.openhab.binding.luxtronikheatpump/src/main/resources/OH-INF/thing/channels.xml
  bundles/org.openhab.binding.luxtronikheatpump/src/main/resources/OH-INF/thing/thing-types.xml
Labels: enhancement

#11887 [shelly] Small patch to avoid ClassCastException
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api/ShellyHttpApi.java
Labels: bug

#11889 [astro] Fixed timeLeft calculation at the end of the year
  bundles/org.openhab.binding.astro/src/main/java/org/openhab/binding/astro/internal/model/Season.java
  bundles/org.openhab.binding.astro/src/main/java/org/openhab/binding/astro/internal/util/DateTimeUtils.java
  bundles/org.openhab.binding.astro/src/test/java/org/openhab/binding/astro/internal/util/DateTimeUtilsTest.java
Labels: bug

#11893 [chromecast] Prevent errors in log when URI host is null
  bundles/org.openhab.binding.chromecast/src/main/java/org/openhab/binding/chromecast/internal/ChromecastStatusUpdater.java
Labels: bug

#11866 [iCalendar] Fix httpclient getting stuck with broken requests
  bundles/org.openhab.binding.icalendar/src/main/java/org/openhab/binding/icalendar/internal/handler/PullJob.java
Labels: bug

#11908 [Yeelight] Add color4 bulb
  bundles/org.openhab.binding.yeelight/src/main/java/org/openhab/binding/yeelight/internal/discovery/YeelightDiscoveryService.java
  bundles/org.openhab.binding.yeelight/src/main/java/org/openhab/binding/yeelight/internal/lib/device/DeviceFactory.java
  bundles/org.openhab.binding.yeelight/src/main/java/org/openhab/binding/yeelight/internal/lib/enums/DeviceType.java
  bundles/org.openhab.binding.yeelight/src/main/java/org/openhab/binding/yeelight/internal/lib/services/DeviceManager.java
Labels: enhancement
