Repository openhab/openhab-addons, pull requests merged in 2021-05, with the labels that each got.

#10577 [enocean] Fix discovery of D2-50 devices
  bundles/org.openhab.binding.enocean/src/main/java/org/openhab/binding/enocean/internal/eep/D2_50/D2_50.java
Labels: bug

#10444 [digitalSTROM] Shade angle support for GR things
  bundles/org.openhab.binding.digitalstrom/src/main/java/org/openhab/binding/digitalstrom/internal/discovery/SceneDiscoveryService.java
  bundles/org.openhab.binding.digitalstrom/src/main/java/org/openhab/binding/digitalstrom/internal/handler/DeviceHandler.java
  bundles/org.openhab.binding.digitalstrom/src/main/java/org/openhab/binding/digitalstrom/internal/handler/ZoneTemperatureControlHandler.java
  bundles/org.openhab.binding.digitalstrom/src/main/java/org/openhab/binding/digitalstrom/internal/lib/manager/impl/TemperatureControlManager.java
  bundles/org.openhab.binding.digitalstrom/src/main/java/org/openhab/binding/digitalstrom/internal/lib/serverconnection/constants/JSONApiResponseKeysEnum.java
  bundles/org.openhab.binding.digitalstrom/src/main/java/org/openhab/binding/digitalstrom/internal/lib/structure/devices/Device.java
  bundles/org.openhab.binding.digitalstrom/src/main/java/org/openhab/binding/digitalstrom/internal/lib/structure/devices/deviceparameters/constants/ApplicationGroup.java
  bundles/org.openhab.binding.digitalstrom/src/main/java/org/openhab/binding/digitalstrom/internal/lib/structure/devices/deviceparameters/constants/FuncNameAndColorGroupEnum.java
  bundles/org.openhab.binding.digitalstrom/src/main/java/org/openhab/binding/digitalstrom/internal/lib/structure/devices/deviceparameters/constants/FunctionalColorGroupEnum.java
  bundles/org.openhab.binding.digitalstrom/src/main/java/org/openhab/binding/digitalstrom/internal/lib/structure/devices/deviceparameters/constants/OutputChannelEnum.java
  bundles/org.openhab.binding.digitalstrom/src/main/java/org/openhab/binding/digitalstrom/internal/lib/structure/devices/impl/DeviceImpl.java
  bundles/org.openhab.binding.digitalstrom/src/main/java/org/openhab/binding/digitalstrom/internal/lib/structure/scene/SceneDiscovery.java
  bundles/org.openhab.binding.digitalstrom/src/main/java/org/openhab/binding/digitalstrom/internal/lib/util/DSJsonParser.java
  bundles/org.openhab.binding.digitalstrom/src/main/java/org/openhab/binding/digitalstrom/internal/providers/DsChannelTypeProvider.java
  bundles/org.openhab.binding.digitalstrom/src/test/java/org/openhab/binding/digitalstrom/internal/lib/structure/devices/deviceparameters/constants/ApplicationGroupTest.java
  bundles/org.openhab.binding.digitalstrom/src/test/java/org/openhab/binding/digitalstrom/internal/lib/structure/devices/deviceparameters/constants/OutputChannelEnumTest.java
  bundles/org.openhab.binding.digitalstrom/src/test/java/org/openhab/binding/digitalstrom/internal/lib/structure/devices/impl/DeviceImplTest.java
  bundles/org.openhab.binding.digitalstrom/src/test/java/org/openhab/binding/digitalstrom/internal/lib/util/DSJsonParserTest.java
  bundles/org.openhab.binding.digitalstrom/src/test/java/org/openhab/binding/digitalstrom/internal/lib/util/JsonModel.java
  bundles/org.openhab.binding.digitalstrom/src/test/java/org/openhab/binding/digitalstrom/internal/lib/util/OutputChannel.java
Labels: enhancement

#10610 [miio] update & improve readability value mappings for readme
  bundles/org.openhab.binding.miio/README.md
  bundles/org.openhab.binding.miio/src/main/resources/database/cgllc.airm.cgdn1-miot.json
  bundles/org.openhab.binding.miio/src/main/resources/database/deerma.humidifier.jsq1.json
  bundles/org.openhab.binding.miio/src/main/resources/database/deerma.humidifier.mjjsq.json
  bundles/org.openhab.binding.miio/src/main/resources/database/dreame.vacuum.mc1808-miot.json
  bundles/org.openhab.binding.miio/src/main/resources/database/dreame.vacuum.p2008-miot.json
  bundles/org.openhab.binding.miio/src/main/resources/database/dreame.vacuum.p2009-miot.json
  bundles/org.openhab.binding.miio/src/main/resources/database/dreame.vacuum.p2156o-miot.json
  bundles/org.openhab.binding.miio/src/main/resources/database/huayi.light.fanwy-miot.json
  bundles/org.openhab.binding.miio/src/main/resources/database/huayi.light.fanwy2-miot.json
  bundles/org.openhab.binding.miio/src/main/resources/database/huayi.light.wyheat-miot.json
  bundles/org.openhab.binding.miio/src/main/resources/database/lumi.curtain.hagl05-miot.json
  bundles/org.openhab.binding.miio/src/main/resources/database/mijia.vacuum.v2-miot.json
  bundles/org.openhab.binding.miio/src/main/resources/database/mmgg.pet_waterer.s1-miot.json
  bundles/org.openhab.binding.miio/src/main/resources/database/mmgg.pet_waterer.s2-miot.json
  bundles/org.openhab.binding.miio/src/main/resources/database/viomi.vacuum.v18-miot.json
  bundles/org.openhab.binding.miio/src/main/resources/database/xiaomi.aircondition.ma1-miot.json
  bundles/org.openhab.binding.miio/src/main/resources/database/xiaomi.aircondition.mc1-miot.json
  bundles/org.openhab.binding.miio/src/main/resources/database/yeelink.light.ceiling.json
  bundles/org.openhab.binding.miio/src/main/resources/database/yeelink.light.ceiling2.json
  bundles/org.openhab.binding.miio/src/main/resources/database/yeelink.light.ceiling4.json
  bundles/org.openhab.binding.miio/src/main/resources/database/yeelink.light.color1.json
  bundles/org.openhab.binding.miio/src/main/resources/database/yeelink.light.lamp1.json
  bundles/org.openhab.binding.miio/src/main/resources/database/yeelink.light.light15.json
  bundles/org.openhab.binding.miio/src/main/resources/database/yeelink.switch.sw1-miot.json
  bundles/org.openhab.binding.miio/src/main/resources/database/yunmi.waterpurifier.json
  bundles/org.openhab.binding.miio/src/main/resources/database/yunmi.waterpurifier.lx8.json
  bundles/org.openhab.binding.miio/src/main/resources/database/zhimi.airpurifier.m1.json
  bundles/org.openhab.binding.miio/src/main/resources/database/zhimi.airpurifier.ma4-miot.json
  bundles/org.openhab.binding.miio/src/main/resources/database/zhimi.airpurifier.mb3-miot.json
  bundles/org.openhab.binding.miio/src/main/resources/database/zhimi.airpurifier.mb4-miot.json
  bundles/org.openhab.binding.miio/src/main/resources/database/zhimi.airpurifier.vb2-miot.json
  bundles/org.openhab.binding.miio/src/main/resources/database/zhimi.airpurifier.za1-miot.json
  bundles/org.openhab.binding.miio/src/main/resources/database/zhimi.fan.za5-miot.json
  bundles/org.openhab.binding.miio/src/main/resources/database/zhimi.heater.ma2-miot.json
  bundles/org.openhab.binding.miio/src/main/resources/database/zhimi.heater.ma3-miot.json
  bundles/org.openhab.binding.miio/src/main/resources/database/zhimi.heater.mc2-miot.json
  bundles/org.openhab.binding.miio/src/main/resources/database/zhimi.heater.na1-miot.json
  bundles/org.openhab.binding.miio/src/main/resources/database/zhimi.heater.nb1-miot.json
  bundles/org.openhab.binding.miio/src/main/resources/database/zhimi.heater.za2-miot.json
  bundles/org.openhab.binding.miio/src/main/resources/database/zhimi.heater.zb1-miot.json
  bundles/org.openhab.binding.miio/src/main/resources/database/zhimi.humidifier.ca4.json
  bundles/org.openhab.binding.miio/src/test/java/org/openhab/binding/miio/internal/ReadmeHelper.java
Labels: documentation

#10638 Fixed location of additional documentation folder so that it is picked up for the website
  bundles/org.openhab.binding.keba/.gitignore
  bundles/org.openhab.binding.webthing/README.md
  bundles/org.openhab.binding.webthing/doc/channels.png
  bundles/org.openhab.binding.webthing/doc/discovery.png
  bundles/org.openhab.binding.webthing/doc/sitemap.png
  bundles/org.openhab.binding.webthing/doc/speedmonitor.png
  bundles/org.openhab.binding.webthing/doc/webthing_description.png
  bundles/org.openhab.io.metrics/README.md
  bundles/org.openhab.io.metrics/doc/dashboard.json
  bundles/org.openhab.io.metrics/doc/grafana-1.png
  bundles/org.openhab.io.metrics/doc/grafana-2.png
  bundles/org.openhab.io.metrics/doc/grafana-3.png
Labels: documentation

#10633 [openweathermap] updated string formatting example for UVindex
  bundles/org.openhab.binding.openweathermap/README.md
Labels: documentation

#10644 [io.metrics] Fix MetricsService breaking REST API #10640
  bundles/org.openhab.io.metrics/README.md
  bundles/org.openhab.io.metrics/pom.xml
  bundles/org.openhab.io.metrics/src/main/java/org/openhab/io/metrics/MetricsRestController.java
  bundles/org.openhab.io.metrics/src/main/java/org/openhab/io/metrics/MetricsService.java
Labels: bug

#10646 Use activation-api 1.2.1_3
  bundles/org.openhab.binding.lametrictime/pom.xml
  bundles/org.openhab.binding.tellstick/src/main/feature/feature.xml
Labels: bug

#10580 [verisure] Add channel for low battery warning for supported thing types
  bundles/org.openhab.binding.verisure/README.md
  bundles/org.openhab.binding.verisure/src/main/java/org/openhab/binding/verisure/internal/VerisureBindingConstants.java
  bundles/org.openhab.binding.verisure/src/main/java/org/openhab/binding/verisure/internal/VerisureSession.java
  bundles/org.openhab.binding.verisure/src/main/java/org/openhab/binding/verisure/internal/dto/VerisureBaseThingDTO.java
  bundles/org.openhab.binding.verisure/src/main/java/org/openhab/binding/verisure/internal/dto/VerisureBatteryStatusDTO.java
  bundles/org.openhab.binding.verisure/src/main/java/org/openhab/binding/verisure/internal/dto/VerisureClimatesDTO.java
  bundles/org.openhab.binding.verisure/src/main/java/org/openhab/binding/verisure/internal/dto/VerisureDoorWindowsDTO.java
  bundles/org.openhab.binding.verisure/src/main/java/org/openhab/binding/verisure/internal/handler/VerisureClimateDeviceThingHandler.java
  bundles/org.openhab.binding.verisure/src/main/java/org/openhab/binding/verisure/internal/handler/VerisureDoorWindowThingHandler.java
  bundles/org.openhab.binding.verisure/src/main/resources/OH-INF/thing/thing-types.xml
Labels: enhancement

#10599 [sonos] Play notification while playing virtual line-in
  bundles/org.openhab.binding.sonos/src/main/java/org/openhab/binding/sonos/internal/handler/ZonePlayerHandler.java
Labels: bug, community approved

#10634 [linuxinput] fixes to thing properties
  bundles/org.openhab.binding.linuxinput/src/main/java/org/openhab/binding/linuxinput/internal/LinuxInputDiscoveryService.java
Labels: bug

#8516 [jsscripting] ES6+ Support
  CODEOWNERS
  bom/openhab-addons/pom.xml
  bundles/org.openhab.automation.jsscripting/NOTICE
  bundles/org.openhab.automation.jsscripting/README.md
  bundles/org.openhab.automation.jsscripting/bnd.bnd
  bundles/org.openhab.automation.jsscripting/pom.xml
  bundles/org.openhab.automation.jsscripting/src/main/feature/feature.xml
  bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/ClassExtender.java
  bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/DebuggingGraalScriptEngine.java
  bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/GraalJSScriptEngineFactory.java
  bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/ModuleLocator.java
  bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/OpenhabGraalJSScriptEngine.java
  bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/ScriptExtensionModuleProvider.java
  bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/fs/DelegatingFileSystem.java
  bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/fs/PrefixedSeekableByteChannel.java
  bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/scriptengine/DelegatingScriptEngineWithInvocable.java
  bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/scriptengine/InvocationInterceptingScriptEngineWithInvocable.java
  bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/threading/ThreadsafeSimpleRuleDelegate.java
  bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/threading/ThreadsafeWrappingScriptedAutomationManagerDelegate.java
  bundles/org.openhab.automation.jsscripting/src/main/resources/META-INF/services/com.oracle.truffle.api.TruffleLanguage$Provider
  bundles/pom.xml
Labels: new automation

#10639 [harmonyhub] Update README.md
  bundles/org.openhab.binding.harmonyhub/README.md
Labels: documentation

#10637 Update remaining Paper UI and HABmin references
  bundles/org.openhab.binding.atlona/README.md
  bundles/org.openhab.binding.bigassfan/README.md
  bundles/org.openhab.binding.bticinosmarther/README.md
  bundles/org.openhab.binding.buienradar/README.md
  bundles/org.openhab.binding.cbus/README.md
  bundles/org.openhab.binding.denonmarantz/src/main/java/org/openhab/binding/denonmarantz/internal/handler/DenonMarantzHandler.java
  bundles/org.openhab.binding.dscalarm/README.md
  bundles/org.openhab.binding.dsmr/README.md
  bundles/org.openhab.binding.enocean/README.md
  bundles/org.openhab.binding.folding/README.md
  bundles/org.openhab.binding.globalcache/README.md
  bundles/org.openhab.binding.heos/README.md
  bundles/org.openhab.binding.hue/README.md
  bundles/org.openhab.binding.icloud/README.md
  bundles/org.openhab.binding.innogysmarthome/README.md
  bundles/org.openhab.binding.km200/README.md
  bundles/org.openhab.binding.lametrictime/README.md
  bundles/org.openhab.binding.lgtvserial/README.md
  bundles/org.openhab.binding.loxone/README.md
  bundles/org.openhab.binding.max/src/main/resources/OH-INF/thing/bridge.xml
  bundles/org.openhab.binding.max/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.mihome/README.md
  bundles/org.openhab.binding.onewire/README.md
  bundles/org.openhab.binding.robonect/README.md
  bundles/org.openhab.binding.squeezebox/README.md
  bundles/org.openhab.binding.surepetcare/README.md
  bundles/org.openhab.binding.yamahareceiver/README.md
  bundles/org.openhab.binding.zway/README.md
  bundles/org.openhab.binding.zway/doc/GETTING_STARTED.md
  bundles/org.openhab.binding.zway/doc/images/getting-started/01-openHAB-Home.png
  bundles/org.openhab.binding.zway/doc/images/getting-started/02-Inbox.png
  bundles/org.openhab.binding.zway/doc/images/getting-started/03-Create-bridge.png
  bundles/org.openhab.binding.zway/doc/images/getting-started/04-Open-bridge-details.png
  bundles/org.openhab.binding.zway/doc/images/getting-started/05-Bridge-details.png
  bundles/org.openhab.binding.zway/doc/images/getting-started/06-Bridge-settings.png
  bundles/org.openhab.binding.zway/doc/images/getting-started/07-Device-discovery.png
  bundles/org.openhab.binding.zway/doc/images/getting-started/08-Device-discovery.png
  bundles/org.openhab.binding.zway/doc/images/getting-started/09-Create-device.png
  bundles/org.openhab.binding.zway/doc/images/getting-started/10-Z-Way-device.png
  bundles/org.openhab.binding.zway/doc/images/getting-started/11-Z-Way-device.png
  bundles/org.openhab.io.imperihome/README.md
  bundles/org.openhab.io.neeo/README.md
  bundles/org.openhab.io.neeo/doc/cfg.png
  bundles/org.openhab.voice.pollytts/README.md
  features/openhab-addons-external/src/main/resources/conf/dynamodb.cfg
Labels: documentation

#10579 [WebThing] binding bugfix: If WebThing network connection is crashed, WebThing will not be reconnected.
  bundles/org.openhab.binding.webthing/src/main/java/org/openhab/binding/webthing/internal/WebThingHandler.java
  bundles/org.openhab.binding.webthing/src/main/java/org/openhab/binding/webthing/internal/client/WebSocketConnectionImpl.java
  bundles/org.openhab.binding.webthing/src/test/java/org/openhab/binding/webthing/internal/client/WebthingTest.java
Labels: bug

#10608 [hue] Changed default color mode for color commands to XY
  bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/LightStateConverter.java
  bundles/org.openhab.binding.hue/src/test/java/org/openhab/binding/hue/internal/LightStateConverterTest.java
Labels: bug

#10609 [hue] Fixed ColorTemperature set to UNDEF
  bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/ApiVersion.java
  bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/Config.java
  bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/Group.java
  bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/HueBridge.java
  bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/State.java
  bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/HueBridgeHandler.java
  bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/HueGroupHandler.java
  bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/HueLightHandler.java
  bundles/org.openhab.binding.hue/src/test/java/org/openhab/binding/hue/internal/handler/HueLightHandlerTest.java
Labels: bug

#10611 [somfytahoma] Open to other portals
  bundles/org.openhab.binding.somfytahoma/README.md
  bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/SomfyTahomaBindingConstants.java
  bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/config/SomfyTahomaConfig.java
  bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/handler/SomfyTahomaBridgeHandler.java
  bundles/org.openhab.binding.somfytahoma/src/main/resources/OH-INF/binding/binding.xml
  bundles/org.openhab.binding.somfytahoma/src/main/resources/OH-INF/config/config.xml
  bundles/org.openhab.binding.somfytahoma/src/main/resources/OH-INF/thing/bridge.xml
Labels: enhancement

#10620 [insteon] delay setting state of network to UNKNOWN
  bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/handler/InsteonNetworkHandler.java
Labels: bug

#10659 [avmfritz] Fixed wrong dial code in status info
  bundles/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/callmonitor/CallMonitor.java
Labels: bug

#10660 [tr064] Fixed wrong pattern to normalize phone numbers
  bundles/org.openhab.binding.tr064/src/main/java/org/openhab/binding/tr064/internal/phonebook/Tr064PhonebookImpl.java
Labels: bug

#10648 [luxtronikheatpump] Update channel descriptions in README.md
  bundles/org.openhab.binding.luxtronikheatpump/README.md
  bundles/org.openhab.binding.luxtronikheatpump/src/main/resources/OH-INF/thing/channels.xml
Labels: documentation

#10645 [lcn] shorten labels
  bundles/org.openhab.binding.lcn/src/main/resources/OH-INF/thing/thing-types.xml
Labels: enhancement

#10565 [openwebnet] Energy meter returns always zero power if no other device has subscribed to power measures
  bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/handler/OpenWebNetEnergyHandler.java
Labels: bug, enhancement

#8562 [warmup] Initial contribution
  CODEOWNERS
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.warmup/NOTICE
  bundles/org.openhab.binding.warmup/README.md
  bundles/org.openhab.binding.warmup/pom.xml
  bundles/org.openhab.binding.warmup/src/main/feature/feature.xml
  bundles/org.openhab.binding.warmup/src/main/java/org/openhab/binding/warmup/internal/WarmupBindingConstants.java
  bundles/org.openhab.binding.warmup/src/main/java/org/openhab/binding/warmup/internal/api/MyWarmupApi.java
  bundles/org.openhab.binding.warmup/src/main/java/org/openhab/binding/warmup/internal/api/MyWarmupApiException.java
  bundles/org.openhab.binding.warmup/src/main/java/org/openhab/binding/warmup/internal/discovery/WarmupDiscoveryService.java
  bundles/org.openhab.binding.warmup/src/main/java/org/openhab/binding/warmup/internal/handler/MyWarmupAccountHandler.java
  bundles/org.openhab.binding.warmup/src/main/java/org/openhab/binding/warmup/internal/handler/MyWarmupConfigurationDTO.java
  bundles/org.openhab.binding.warmup/src/main/java/org/openhab/binding/warmup/internal/handler/RoomConfigurationDTO.java
  bundles/org.openhab.binding.warmup/src/main/java/org/openhab/binding/warmup/internal/handler/RoomHandler.java
  bundles/org.openhab.binding.warmup/src/main/java/org/openhab/binding/warmup/internal/handler/WarmupHandlerFactory.java
  bundles/org.openhab.binding.warmup/src/main/java/org/openhab/binding/warmup/internal/handler/WarmupRefreshListener.java
  bundles/org.openhab.binding.warmup/src/main/java/org/openhab/binding/warmup/internal/handler/WarmupThingHandler.java
  bundles/org.openhab.binding.warmup/src/main/java/org/openhab/binding/warmup/internal/model/auth/AuthRequestDTO.java
  bundles/org.openhab.binding.warmup/src/main/java/org/openhab/binding/warmup/internal/model/auth/AuthRequestDataDTO.java
  bundles/org.openhab.binding.warmup/src/main/java/org/openhab/binding/warmup/internal/model/auth/AuthResponseDTO.java
  bundles/org.openhab.binding.warmup/src/main/java/org/openhab/binding/warmup/internal/model/auth/AuthResponseDataDTO.java
  bundles/org.openhab.binding.warmup/src/main/java/org/openhab/binding/warmup/internal/model/auth/AuthResponseStatusDTO.java
  bundles/org.openhab.binding.warmup/src/main/java/org/openhab/binding/warmup/internal/model/query/DeviceDTO.java
  bundles/org.openhab.binding.warmup/src/main/java/org/openhab/binding/warmup/internal/model/query/LocationDTO.java
  bundles/org.openhab.binding.warmup/src/main/java/org/openhab/binding/warmup/internal/model/query/QueryDataDTO.java
  bundles/org.openhab.binding.warmup/src/main/java/org/openhab/binding/warmup/internal/model/query/QueryResponseDTO.java
  bundles/org.openhab.binding.warmup/src/main/java/org/openhab/binding/warmup/internal/model/query/RoomDTO.java
  bundles/org.openhab.binding.warmup/src/main/java/org/openhab/binding/warmup/internal/model/query/UserDTO.java
  bundles/org.openhab.binding.warmup/src/main/resources/OH-INF/binding/binding.xml
  bundles/org.openhab.binding.warmup/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/pom.xml
Labels: awaiting feedback, cre, new binding

#10643 [luftdateninfo] Add internal sensor support
  bundles/org.openhab.binding.luftdateninfo/README.md
  bundles/org.openhab.binding.luftdateninfo/doc/local-sensor.png
  bundles/org.openhab.binding.luftdateninfo/doc/logo-rund.png
  bundles/org.openhab.binding.luftdateninfo/src/main/java/org/openhab/binding/luftdateninfo/internal/LuftdatenInfoConfiguration.java
  bundles/org.openhab.binding.luftdateninfo/src/main/java/org/openhab/binding/luftdateninfo/internal/LuftdatenInfoHandlerFactory.java
  bundles/org.openhab.binding.luftdateninfo/src/main/java/org/openhab/binding/luftdateninfo/internal/handler/BaseSensorHandler.java
  bundles/org.openhab.binding.luftdateninfo/src/main/java/org/openhab/binding/luftdateninfo/internal/handler/ConditionHandler.java
  bundles/org.openhab.binding.luftdateninfo/src/main/java/org/openhab/binding/luftdateninfo/internal/handler/HTTPHandler.java
  bundles/org.openhab.binding.luftdateninfo/src/main/java/org/openhab/binding/luftdateninfo/internal/handler/NoiseHandler.java
  bundles/org.openhab.binding.luftdateninfo/src/main/java/org/openhab/binding/luftdateninfo/internal/handler/PMHandler.java
  bundles/org.openhab.binding.luftdateninfo/src/main/java/org/openhab/binding/luftdateninfo/internal/utils/Constants.java
  bundles/org.openhab.binding.luftdateninfo/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.luftdateninfo/src/test/java/org/openhab/binding/luftdateninfo/internal/ConditionHandlerTest.java
  bundles/org.openhab.binding.luftdateninfo/src/test/java/org/openhab/binding/luftdateninfo/internal/DTOTest.java
  bundles/org.openhab.binding.luftdateninfo/src/test/java/org/openhab/binding/luftdateninfo/internal/HTTPHandlerValueTest.java
  bundles/org.openhab.binding.luftdateninfo/src/test/java/org/openhab/binding/luftdateninfo/internal/PMHandlerTest.java
  bundles/org.openhab.binding.luftdateninfo/src/test/resources/internal-data.json
Labels: enhancement

#10680 [influxdb] Fix issue #10464 Problem querying old historical data
  bundles/org.openhab.persistence.influxdb/src/main/java/org/openhab/persistence/influxdb/internal/InfluxDBConfiguration.java
  bundles/org.openhab.persistence.influxdb/src/main/java/org/openhab/persistence/influxdb/internal/InfluxDBStateConvertUtils.java
  bundles/org.openhab.persistence.influxdb/src/main/java/org/openhab/persistence/influxdb/internal/InfluxDBVersion.java
  bundles/org.openhab.persistence.influxdb/src/main/java/org/openhab/persistence/influxdb/internal/InfluxRow.java
  bundles/org.openhab.persistence.influxdb/src/main/java/org/openhab/persistence/influxdb/internal/influx1/InfluxDB1RepositoryImpl.java
Labels: bug

#10708 [insteon] add a read timeout when getting data from the Insteon 2245-222 hub
  bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/driver/hub/HubIOStream.java
Labels: bug

#9504 [plugwiseha] Initial contribution
  CODEOWNERS
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.plugwiseha/NOTICE
  bundles/org.openhab.binding.plugwiseha/README.md
  bundles/org.openhab.binding.plugwiseha/pom.xml
  bundles/org.openhab.binding.plugwiseha/src/main/feature/feature.xml
  bundles/org.openhab.binding.plugwiseha/src/main/java/org/openhab/binding/plugwiseha/internal/PlugwiseHABindingConstants.java
  bundles/org.openhab.binding.plugwiseha/src/main/java/org/openhab/binding/plugwiseha/internal/PlugwiseHAHandlerFactory.java
  bundles/org.openhab.binding.plugwiseha/src/main/java/org/openhab/binding/plugwiseha/internal/api/exception/PlugwiseHABadRequestException.java
  bundles/org.openhab.binding.plugwiseha/src/main/java/org/openhab/binding/plugwiseha/internal/api/exception/PlugwiseHACommunicationException.java
  bundles/org.openhab.binding.plugwiseha/src/main/java/org/openhab/binding/plugwiseha/internal/api/exception/PlugwiseHAException.java
  bundles/org.openhab.binding.plugwiseha/src/main/java/org/openhab/binding/plugwiseha/internal/api/exception/PlugwiseHAForbiddenException.java
  bundles/org.openhab.binding.plugwiseha/src/main/java/org/openhab/binding/plugwiseha/internal/api/exception/PlugwiseHAInvalidHostException.java
  bundles/org.openhab.binding.plugwiseha/src/main/java/org/openhab/binding/plugwiseha/internal/api/exception/PlugwiseHANotAuthorizedException.java
  bundles/org.openhab.binding.plugwiseha/src/main/java/org/openhab/binding/plugwiseha/internal/api/exception/PlugwiseHATimeoutException.java
  bundles/org.openhab.binding.plugwiseha/src/main/java/org/openhab/binding/plugwiseha/internal/api/exception/PlugwiseHAUnauthorizedException.java
  bundles/org.openhab.binding.plugwiseha/src/main/java/org/openhab/binding/plugwiseha/internal/api/model/PlugwiseHAController.java
  bundles/org.openhab.binding.plugwiseha/src/main/java/org/openhab/binding/plugwiseha/internal/api/model/PlugwiseHAControllerRequest.java
  bundles/org.openhab.binding.plugwiseha/src/main/java/org/openhab/binding/plugwiseha/internal/api/model/PlugwiseHAModel.java
  bundles/org.openhab.binding.plugwiseha/src/main/java/org/openhab/binding/plugwiseha/internal/api/model/converter/DateTimeConverter.java
  bundles/org.openhab.binding.plugwiseha/src/main/java/org/openhab/binding/plugwiseha/internal/api/model/dto/ActuatorFunctionalities.java
  bundles/org.openhab.binding.plugwiseha/src/main/java/org/openhab/binding/plugwiseha/internal/api/model/dto/ActuatorFunctionality.java
  bundles/org.openhab.binding.plugwiseha/src/main/java/org/openhab/binding/plugwiseha/internal/api/model/dto/ActuatorFunctionalityOffsetTemperature.java
  bundles/org.openhab.binding.plugwiseha/src/main/java/org/openhab/binding/plugwiseha/internal/api/model/dto/ActuatorFunctionalityRelay.java
  bundles/org.openhab.binding.plugwiseha/src/main/java/org/openhab/binding/plugwiseha/internal/api/model/dto/ActuatorFunctionalityThermostat.java
  bundles/org.openhab.binding.plugwiseha/src/main/java/org/openhab/binding/plugwiseha/internal/api/model/dto/ActuatorFunctionalityThreshold.java
  bundles/org.openhab.binding.plugwiseha/src/main/java/org/openhab/binding/plugwiseha/internal/api/model/dto/ActuatorFunctionalityTimer.java
  bundles/org.openhab.binding.plugwiseha/src/main/java/org/openhab/binding/plugwiseha/internal/api/model/dto/ActuatorFunctionalityToggle.java
  bundles/org.openhab.binding.plugwiseha/src/main/java/org/openhab/binding/plugwiseha/internal/api/model/dto/Appliance.java
  bundles/org.openhab.binding.plugwiseha/src/main/java/org/openhab/binding/plugwiseha/internal/api/model/dto/Appliances.java
  bundles/org.openhab.binding.plugwiseha/src/main/java/org/openhab/binding/plugwiseha/internal/api/model/dto/DomainObjects.java
  bundles/org.openhab.binding.plugwiseha/src/main/java/org/openhab/binding/plugwiseha/internal/api/model/dto/GatewayEnvironment.java
  bundles/org.openhab.binding.plugwiseha/src/main/java/org/openhab/binding/plugwiseha/internal/api/model/dto/GatewayInfo.java
  bundles/org.openhab.binding.plugwiseha/src/main/java/org/openhab/binding/plugwiseha/internal/api/model/dto/Location.java
  bundles/org.openhab.binding.plugwiseha/src/main/java/org/openhab/binding/plugwiseha/internal/api/model/dto/Locations.java
  bundles/org.openhab.binding.plugwiseha/src/main/java/org/openhab/binding/plugwiseha/internal/api/model/dto/Log.java
  bundles/org.openhab.binding.plugwiseha/src/main/java/org/openhab/binding/plugwiseha/internal/api/model/dto/Logs.java
  bundles/org.openhab.binding.plugwiseha/src/main/java/org/openhab/binding/plugwiseha/internal/api/model/dto/Module.java
  bundles/org.openhab.binding.plugwiseha/src/main/java/org/openhab/binding/plugwiseha/internal/api/model/dto/Modules.java
  bundles/org.openhab.binding.plugwiseha/src/main/java/org/openhab/binding/plugwiseha/internal/api/model/dto/PlugwiseBaseModel.java
  bundles/org.openhab.binding.plugwiseha/src/main/java/org/openhab/binding/plugwiseha/internal/api/model/dto/PlugwiseComparableDate.java
  bundles/org.openhab.binding.plugwiseha/src/main/java/org/openhab/binding/plugwiseha/internal/api/model/dto/PlugwiseHACollection.java
  bundles/org.openhab.binding.plugwiseha/src/main/java/org/openhab/binding/plugwiseha/internal/api/model/dto/Service.java
  bundles/org.openhab.binding.plugwiseha/src/main/java/org/openhab/binding/plugwiseha/internal/api/model/dto/Services.java
  bundles/org.openhab.binding.plugwiseha/src/main/java/org/openhab/binding/plugwiseha/internal/api/model/dto/ZigBeeNode.java
  bundles/org.openhab.binding.plugwiseha/src/main/java/org/openhab/binding/plugwiseha/internal/api/xml/PlugwiseHAXStream.java
  bundles/org.openhab.binding.plugwiseha/src/main/java/org/openhab/binding/plugwiseha/internal/config/PlugwiseHABridgeThingConfig.java
  bundles/org.openhab.binding.plugwiseha/src/main/java/org/openhab/binding/plugwiseha/internal/config/PlugwiseHAThingConfig.java
  bundles/org.openhab.binding.plugwiseha/src/main/java/org/openhab/binding/plugwiseha/internal/discovery/PlugwiseHADiscoveryService.java
  bundles/org.openhab.binding.plugwiseha/src/main/java/org/openhab/binding/plugwiseha/internal/handler/PlugwiseHAApplianceHandler.java
  bundles/org.openhab.binding.plugwiseha/src/main/java/org/openhab/binding/plugwiseha/internal/handler/PlugwiseHABaseHandler.java
  bundles/org.openhab.binding.plugwiseha/src/main/java/org/openhab/binding/plugwiseha/internal/handler/PlugwiseHABridgeHandler.java
  bundles/org.openhab.binding.plugwiseha/src/main/java/org/openhab/binding/plugwiseha/internal/handler/PlugwiseHAZoneHandler.java
  bundles/org.openhab.binding.plugwiseha/src/main/resources/OH-INF/binding/binding.xml
  bundles/org.openhab.binding.plugwiseha/src/main/resources/OH-INF/config/config.xml
  bundles/org.openhab.binding.plugwiseha/src/main/resources/OH-INF/thing/channels.xml
  bundles/org.openhab.binding.plugwiseha/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.plugwiseha/src/main/resources/domain_objects.xslt
  bundles/pom.xml
Labels: new binding

#10725 [voice-pollytts] Update README.md
  bundles/org.openhab.voice.pollytts/README.md
Labels: documentation

#10721 [groovyscripting] Update Groovy to 3.0.8
  bundles/org.openhab.automation.groovyscripting/README.md
  bundles/org.openhab.automation.groovyscripting/pom.xml
Labels: enhancement

#10729 [deconz] make lightgroup switch off if brightness is set to 0
  bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/handler/GroupThingHandler.java
Labels: bug

#10739 [openweathermap] Add correct default parameter to Readme
  bundles/org.openhab.binding.openweathermap/README.md
Labels: documentation

#10694 [homeconnect] Returns an empty list of options for an unsupported program
  bundles/org.openhab.binding.homeconnect/src/main/java/org/openhab/binding/homeconnect/internal/client/HomeConnectApiClient.java
  bundles/org.openhab.binding.homeconnect/src/main/java/org/openhab/binding/homeconnect/internal/handler/HomeConnectHoodHandler.java
Labels: enhancement

#10749 [homeconnect] Let the binding update item state when handling a command
  bundles/org.openhab.binding.homeconnect/src/main/resources/OH-INF/thing/thing-types.xml
Labels: bug

#10100 [semsportal] initial contribution
  CODEOWNERS
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.semsportal/NOTICE
  bundles/org.openhab.binding.semsportal/README.md
  bundles/org.openhab.binding.semsportal/pom.xml
  bundles/org.openhab.binding.semsportal/src/main/feature/feature.xml
  bundles/org.openhab.binding.semsportal/src/main/java/org/openhab/binding/semsportal/internal/CommunicationException.java
  bundles/org.openhab.binding.semsportal/src/main/java/org/openhab/binding/semsportal/internal/ConfigurationException.java
  bundles/org.openhab.binding.semsportal/src/main/java/org/openhab/binding/semsportal/internal/PortalHandler.java
  bundles/org.openhab.binding.semsportal/src/main/java/org/openhab/binding/semsportal/internal/SEMSPortalBindingConstants.java
  bundles/org.openhab.binding.semsportal/src/main/java/org/openhab/binding/semsportal/internal/SEMSPortalConfiguration.java
  bundles/org.openhab.binding.semsportal/src/main/java/org/openhab/binding/semsportal/internal/SEMSPortalHandlerFactory.java
  bundles/org.openhab.binding.semsportal/src/main/java/org/openhab/binding/semsportal/internal/StateHelper.java
  bundles/org.openhab.binding.semsportal/src/main/java/org/openhab/binding/semsportal/internal/StationHandler.java
  bundles/org.openhab.binding.semsportal/src/main/java/org/openhab/binding/semsportal/internal/discovery/StationDiscoveryService.java
  bundles/org.openhab.binding.semsportal/src/main/java/org/openhab/binding/semsportal/internal/dto/BaseResponse.java
  bundles/org.openhab.binding.semsportal/src/main/java/org/openhab/binding/semsportal/internal/dto/InverterDetails.java
  bundles/org.openhab.binding.semsportal/src/main/java/org/openhab/binding/semsportal/internal/dto/KeyPerformanceIndicators.java
  bundles/org.openhab.binding.semsportal/src/main/java/org/openhab/binding/semsportal/internal/dto/LoginRequest.java
  bundles/org.openhab.binding.semsportal/src/main/java/org/openhab/binding/semsportal/internal/dto/LoginResponse.java
  bundles/org.openhab.binding.semsportal/src/main/java/org/openhab/binding/semsportal/internal/dto/SEMSToken.java
  bundles/org.openhab.binding.semsportal/src/main/java/org/openhab/binding/semsportal/internal/dto/Station.java
  bundles/org.openhab.binding.semsportal/src/main/java/org/openhab/binding/semsportal/internal/dto/StationListRequest.java
  bundles/org.openhab.binding.semsportal/src/main/java/org/openhab/binding/semsportal/internal/dto/StationListResponse.java
  bundles/org.openhab.binding.semsportal/src/main/java/org/openhab/binding/semsportal/internal/dto/StationStatus.java
  bundles/org.openhab.binding.semsportal/src/main/java/org/openhab/binding/semsportal/internal/dto/StatusRequest.java
  bundles/org.openhab.binding.semsportal/src/main/java/org/openhab/binding/semsportal/internal/dto/StatusResponse.java
  bundles/org.openhab.binding.semsportal/src/main/resources/OH-INF/binding/binding.xml
  bundles/org.openhab.binding.semsportal/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.semsportal/src/test/java/org/openhab/binding/semsportal/internal/SEMSJsonParserTest.java
  bundles/org.openhab.binding.semsportal/src/test/resources/error_login.json
  bundles/org.openhab.binding.semsportal/src/test/resources/error_status.json
  bundles/org.openhab.binding.semsportal/src/test/resources/success_list.json
  bundles/org.openhab.binding.semsportal/src/test/resources/success_login.json
  bundles/org.openhab.binding.semsportal/src/test/resources/success_status.json
  bundles/pom.xml
Labels: new binding

#10747 [homeconnect] Factorize handling of power command
  bundles/org.openhab.binding.homeconnect/src/main/java/org/openhab/binding/homeconnect/internal/handler/AbstractHomeConnectThingHandler.java
  bundles/org.openhab.binding.homeconnect/src/main/java/org/openhab/binding/homeconnect/internal/handler/HomeConnectCoffeeMakerHandler.java
  bundles/org.openhab.binding.homeconnect/src/main/java/org/openhab/binding/homeconnect/internal/handler/HomeConnectCooktopHandler.java
  bundles/org.openhab.binding.homeconnect/src/main/java/org/openhab/binding/homeconnect/internal/handler/HomeConnectDishwasherHandler.java
  bundles/org.openhab.binding.homeconnect/src/main/java/org/openhab/binding/homeconnect/internal/handler/HomeConnectHoodHandler.java
  bundles/org.openhab.binding.homeconnect/src/main/java/org/openhab/binding/homeconnect/internal/handler/HomeConnectOvenHandler.java
Labels: enhancement

#10754 [homeconnect] Build state options with a unique item for unsupported programs
  bundles/org.openhab.binding.homeconnect/src/main/java/org/openhab/binding/homeconnect/internal/handler/AbstractHomeConnectThingHandler.java
Labels: enhancement

#10745 [homeconnect] Don't reset washer temp / spin speed when exiting from active program
  bundles/org.openhab.binding.homeconnect/src/main/java/org/openhab/binding/homeconnect/internal/HomeConnectBindingConstants.java
  bundles/org.openhab.binding.homeconnect/src/main/java/org/openhab/binding/homeconnect/internal/handler/AbstractHomeConnectThingHandler.java
  bundles/org.openhab.binding.homeconnect/src/main/java/org/openhab/binding/homeconnect/internal/handler/HomeConnectCoffeeMakerHandler.java
  bundles/org.openhab.binding.homeconnect/src/main/java/org/openhab/binding/homeconnect/internal/handler/HomeConnectCooktopHandler.java
  bundles/org.openhab.binding.homeconnect/src/main/java/org/openhab/binding/homeconnect/internal/handler/HomeConnectDishwasherHandler.java
  bundles/org.openhab.binding.homeconnect/src/main/java/org/openhab/binding/homeconnect/internal/handler/HomeConnectDryerHandler.java
  bundles/org.openhab.binding.homeconnect/src/main/java/org/openhab/binding/homeconnect/internal/handler/HomeConnectHoodHandler.java
  bundles/org.openhab.binding.homeconnect/src/main/java/org/openhab/binding/homeconnect/internal/handler/HomeConnectOvenHandler.java
  bundles/org.openhab.binding.homeconnect/src/main/java/org/openhab/binding/homeconnect/internal/handler/HomeConnectWasherDryerHandler.java
  bundles/org.openhab.binding.homeconnect/src/main/java/org/openhab/binding/homeconnect/internal/handler/HomeConnectWasherHandler.java
Labels: bug

#10759 [sonos] Add new channel heightlevel for Sonos ARC / ARC SL
  bundles/org.openhab.binding.sonos/README.md
  bundles/org.openhab.binding.sonos/src/main/java/org/openhab/binding/sonos/internal/SonosBindingConstants.java
  bundles/org.openhab.binding.sonos/src/main/java/org/openhab/binding/sonos/internal/SonosXMLParser.java
  bundles/org.openhab.binding.sonos/src/main/java/org/openhab/binding/sonos/internal/handler/ZonePlayerHandler.java
  bundles/org.openhab.binding.sonos/src/main/resources/OH-INF/thing/Arc.xml
  bundles/org.openhab.binding.sonos/src/main/resources/OH-INF/thing/ArcSL.xml
  bundles/org.openhab.binding.sonos/src/main/resources/OH-INF/thing/channels.xml
Labels: enhancement

#10763 [miio] add support for Yeelight 1S (mono4)
  bundles/org.openhab.binding.miio/README.md
  bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/MiIoDevices.java
  bundles/org.openhab.binding.miio/src/main/resources/database/yeelink.light.lamp1.json
Labels: enhancement

#10770 [lcn] Improve readme; Allow special module IDs <5
  bundles/org.openhab.binding.lcn/README.md
  bundles/org.openhab.binding.lcn/src/main/resources/OH-INF/config/config.xml
Labels: documentation, enhancement

#10760 [avmfritz] Added support for HAN-FUN outlets / simple on-off devices
  bundles/org.openhab.binding.avmfritz/README.md
  bundles/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/AVMFritzBindingConstants.java
  bundles/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/dto/AVMFritzBaseModel.java
  bundles/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/dto/DeviceModel.java
  bundles/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/dto/SimpleOnOffModel.java
  bundles/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/handler/AVMFritzBaseBridgeHandler.java
  bundles/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/handler/AVMFritzBaseThingHandler.java
  bundles/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/handler/Powerline546EHandler.java
  bundles/org.openhab.binding.avmfritz/src/main/resources/OH-INF/i18n/avmfritz_de.properties
  bundles/org.openhab.binding.avmfritz/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.avmfritz/src/test/java/org/openhab/binding/avmfritz/internal/dto/AVMFritzDeviceListModelTest.java
  itests/org.openhab.binding.avmfritz.tests/src/main/java/org/openhab/binding/avmfritz/internal/discovery/AVMFritzDiscoveryServiceOSGiTest.java
Labels: enhancement

#10664 [velbus] Add new functionality PRESSED and LONG PRESSED
  bundles/org.openhab.binding.velbus/README.md
  bundles/org.openhab.binding.velbus/src/main/java/org/openhab/binding/velbus/internal/VelbusHandlerFactory.java
  bundles/org.openhab.binding.velbus/src/main/java/org/openhab/binding/velbus/internal/VelbusModule.java
  bundles/org.openhab.binding.velbus/src/main/java/org/openhab/binding/velbus/internal/discovery/VelbusThingDiscoveryService.java
  bundles/org.openhab.binding.velbus/src/main/java/org/openhab/binding/velbus/internal/handler/VelbusRelayHandler.java
  bundles/org.openhab.binding.velbus/src/main/java/org/openhab/binding/velbus/internal/handler/VelbusRelayWithInputHandler.java
  bundles/org.openhab.binding.velbus/src/main/java/org/openhab/binding/velbus/internal/handler/VelbusSensorHandler.java
  bundles/org.openhab.binding.velbus/src/main/java/org/openhab/binding/velbus/internal/packets/VelbusButtonPacket.java
  bundles/org.openhab.binding.velbus/src/main/resources/OH-INF/thing/thing-types.xml
Labels: enhancement

#10773 [homeconnect] Retrieve list of programs when an appliance becomes available
  bundles/org.openhab.binding.homeconnect/src/main/java/org/openhab/binding/homeconnect/internal/client/HomeConnectApiClient.java
  bundles/org.openhab.binding.homeconnect/src/main/java/org/openhab/binding/homeconnect/internal/handler/AbstractHomeConnectThingHandler.java
Labels: bug
