Repository openhab/openhab-addons, pull requests merged in 2021-01, with the labels that each got.

#9585 [dwdunwetter] documentation for binding updated
  bundles/org.openhab.binding.dwdunwetter/README.md
Labels: documentation

#9631 [atlona] Volume level should be a whole number
  bundles/org.openhab.binding.atlona/src/main/java/org/openhab/binding/atlona/internal/StatefulHandlerCallback.java
  bundles/org.openhab.binding.atlona/src/main/java/org/openhab/binding/atlona/internal/pro3/AtlonaPro3Handler.java
  bundles/org.openhab.binding.atlona/src/main/java/org/openhab/binding/atlona/internal/pro3/AtlonaPro3PortocolHandler.java
Labels: bug

#9653 [modbus] Disable unstable ModbusDataHandlerTest#testRefreshOnData itest
  itests/org.openhab.binding.modbus.tests/src/main/java/org/openhab/binding/modbus/tests/ModbusDataHandlerTest.java
Labels: test

#9632 [ecobee] Fixed actions broken by recent PR
  bundles/org.openhab.binding.ecobee/src/main/java/org/openhab/binding/ecobee/internal/handler/EcobeeThermostatBridgeHandler.java
Labels: bug, critical

#9525 [samsungtv] UPnP devices discovery refactored
  bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/SamsungTvHandlerFactory.java
  bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/handler/SamsungTvHandler.java
  bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/service/RemoteControllerService.java
Labels: bug

#9656 [onewire] update documentation
  bundles/org.openhab.binding.onewire/README.md
Labels: documentation

#9648 [tr064] improve documentation and add textual config example
  bundles/org.openhab.binding.tr064/README.md
Labels: documentation

#9550 [hueemulation] Fix nginx example configuration
  bundles/org.openhab.io.hueemulation/README.md
Labels: documentation

#9638 [remoteopenhab] Handle IllegalArgumentException when building channels
  bundles/org.openhab.binding.remoteopenhab/src/main/java/org/openhab/binding/remoteopenhab/internal/handler/RemoteopenhabBridgeHandler.java
Labels: bug

#9655 [tr064] fix wanBlockByIP channel and improvements to paramater handling
  bundles/org.openhab.binding.tr064/README.md
  bundles/org.openhab.binding.tr064/src/main/java/org/openhab/binding/tr064/internal/config/Tr064RootConfiguration.java
  bundles/org.openhab.binding.tr064/src/main/java/org/openhab/binding/tr064/internal/phonebook/PhonebookProfileFactory.java
  bundles/org.openhab.binding.tr064/src/main/java/org/openhab/binding/tr064/internal/soap/SOAPValueConverter.java
  bundles/org.openhab.binding.tr064/src/main/java/org/openhab/binding/tr064/internal/util/Util.java
Labels: bug, enhancement

#9624 [loxone] Fix for #8693 - removed deadlock
  bundles/org.openhab.binding.loxone/src/main/java/org/openhab/binding/loxone/internal/LxServerHandler.java
Labels: bug

#9302 [tivo] Update tivo binding for OH3
  CODEOWNERS
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.tivo/NOTICE
  bundles/org.openhab.binding.tivo/README.md
  bundles/org.openhab.binding.tivo/doc/TiVo_lockup_BLK.png
  bundles/org.openhab.binding.tivo/pom.xml
  bundles/org.openhab.binding.tivo/src/main/feature/feature.xml
  bundles/org.openhab.binding.tivo/src/main/java/org/openhab/binding/tivo/internal/TiVoBindingConstants.java
  bundles/org.openhab.binding.tivo/src/main/java/org/openhab/binding/tivo/internal/TiVoHandlerFactory.java
  bundles/org.openhab.binding.tivo/src/main/java/org/openhab/binding/tivo/internal/discovery/TiVoDiscoveryParticipant.java
  bundles/org.openhab.binding.tivo/src/main/java/org/openhab/binding/tivo/internal/handler/TiVoHandler.java
  bundles/org.openhab.binding.tivo/src/main/java/org/openhab/binding/tivo/internal/service/TivoConfigData.java
  bundles/org.openhab.binding.tivo/src/main/java/org/openhab/binding/tivo/internal/service/TivoStatusData.java
  bundles/org.openhab.binding.tivo/src/main/java/org/openhab/binding/tivo/internal/service/TivoStatusProvider.java
  bundles/org.openhab.binding.tivo/src/main/resources/OH-INF/binding/binding.xml
  bundles/org.openhab.binding.tivo/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/pom.xml
Labels: cre, new binding, oh1 migration

#1334 [gpio] GPIO Binding initial contribution
  CODEOWNERS
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.gpio/NOTICE
  bundles/org.openhab.binding.gpio/README.md
  bundles/org.openhab.binding.gpio/pom.xml
  bundles/org.openhab.binding.gpio/src/main/feature/feature.xml
  bundles/org.openhab.binding.gpio/src/main/java/org/openhab/binding/gpio/internal/GPIOBindingConstants.java
  bundles/org.openhab.binding.gpio/src/main/java/org/openhab/binding/gpio/internal/GPIOHandlerFactory.java
  bundles/org.openhab.binding.gpio/src/main/java/org/openhab/binding/gpio/internal/NoGpioIdException.java
  bundles/org.openhab.binding.gpio/src/main/java/org/openhab/binding/gpio/internal/configuration/GPIOConfiguration.java
  bundles/org.openhab.binding.gpio/src/main/java/org/openhab/binding/gpio/internal/configuration/GPIOInputConfiguration.java
  bundles/org.openhab.binding.gpio/src/main/java/org/openhab/binding/gpio/internal/configuration/GPIOOutputConfiguration.java
  bundles/org.openhab.binding.gpio/src/main/java/org/openhab/binding/gpio/internal/configuration/PigpioConfiguration.java
  bundles/org.openhab.binding.gpio/src/main/java/org/openhab/binding/gpio/internal/handler/ChannelHandler.java
  bundles/org.openhab.binding.gpio/src/main/java/org/openhab/binding/gpio/internal/handler/PigpioDigitalInputHandler.java
  bundles/org.openhab.binding.gpio/src/main/java/org/openhab/binding/gpio/internal/handler/PigpioDigitalOutputHandler.java
  bundles/org.openhab.binding.gpio/src/main/java/org/openhab/binding/gpio/internal/handler/PigpioRemoteHandler.java
  bundles/org.openhab.binding.gpio/src/main/resources/OH-INF/binding/binding.xml
  bundles/org.openhab.binding.gpio/src/main/resources/OH-INF/thing/pigpio-remote.xml
  bundles/pom.xml
Labels: cre, new binding, oh1 migration

#9644 [Amazonechocontrol] fix SmartHomeDevice channels
  bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/Connection.java
  bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/handler/AccountHandler.java
  bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/jsons/JsonSmartHomeDevices.java
  bundles/org.openhab.binding.amazonechocontrol/src/main/resources/OH-INF/thing/thing-types.xml
Labels: bug

#9626 [http] fix initial refresh
  bundles/org.openhab.binding.http/src/main/java/org/openhab/binding/http/internal/http/RefreshingUrlCache.java
Labels: bug

#9640 [scale] Added 'ConfigOptionProvider' to provide filenames ending with '.scale' in Profile configuration
  bundles/org.openhab.transform.scale/src/main/java/org/openhab/transform/scale/internal/ScaleTransformationService.java
  bundles/org.openhab.transform.scale/src/main/java/org/openhab/transform/scale/internal/profiles/ScaleTransformationProfile.java
  bundles/org.openhab.transform.scale/src/main/java/org/openhab/transform/scale/internal/profiles/ScaleTransformationProfileFactory.java
  bundles/org.openhab.transform.scale/src/main/resources/OH-INF/config/scaleProfile.xml
  bundles/org.openhab.transform.scale/src/main/resources/readme.txt
Labels: enhancement

#9641 [map] Added 'ConfigOptionProvider' to provide filenames ending with '.map' in Profile configuration
  bundles/org.openhab.transform.map/src/main/java/org/openhab/transform/map/internal/MapTransformationService.java
  bundles/org.openhab.transform.map/src/main/java/org/openhab/transform/map/internal/profiles/MapTransformationProfile.java
  bundles/org.openhab.transform.map/src/main/java/org/openhab/transform/map/internal/profiles/MapTransformationProfileFactory.java
  bundles/org.openhab.transform.map/src/main/resources/OH-INF/config/mapProfile.xml
  bundles/org.openhab.transform.map/src/main/resources/readme.txt
Labels: enhancement

#9426 [jdbc] Return QuantityTypes for number items with dimension
  bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/db/JdbcBaseDAO.java
  bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/db/JdbcDerbyDAO.java
  bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/db/JdbcMariadbDAO.java
  bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/db/JdbcMysqlDAO.java
  bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/db/JdbcPostgresqlDAO.java
  bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/JdbcMapper.java
  bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/JdbcPersistenceService.java
Labels: enhancement

#9672 [zoneminder] Fixed most recent event query
  bundles/org.openhab.binding.zoneminder/README.md
  bundles/org.openhab.binding.zoneminder/src/main/java/org/openhab/binding/zoneminder/internal/handler/Monitor.java
  bundles/org.openhab.binding.zoneminder/src/main/java/org/openhab/binding/zoneminder/internal/handler/ZmBridgeHandler.java
  bundles/org.openhab.binding.zoneminder/src/main/java/org/openhab/binding/zoneminder/internal/handler/ZmMonitorHandler.java
Labels: bug

#9671 [tr064] fix comment in SOAP request
  bundles/org.openhab.binding.tr064/src/main/java/org/openhab/binding/tr064/internal/util/Util.java
  bundles/org.openhab.binding.tr064/src/main/resources/channels.xml
Labels: bug, community approved

#9657 [remoteopenhab] Consider the remote item pattern formatter
  bundles/org.openhab.binding.remoteopenhab/src/main/java/org/openhab/binding/remoteopenhab/internal/RemoteopenhabChannelTypeProvider.java
  bundles/org.openhab.binding.remoteopenhab/src/main/java/org/openhab/binding/remoteopenhab/internal/handler/RemoteopenhabBridgeHandler.java
Labels: enhancement

#9678 [icalendar] Fixed issues with moved events and wrong displayed events
  bundles/org.openhab.binding.icalendar/src/main/java/org/openhab/binding/icalendar/internal/handler/EventFilterHandler.java
  bundles/org.openhab.binding.icalendar/src/main/java/org/openhab/binding/icalendar/internal/logic/BiweeklyPresentableCalendar.java
  bundles/org.openhab.binding.icalendar/src/test/java/org/openhab/binding/icalendar/internal/logic/BiweeklyPresentableCalendarTest.java
  bundles/org.openhab.binding.icalendar/src/test/resources/test-issue9647.ics
Labels: bug

#9679 [openhabcloud] APT Installation path update for openHAB 3
  bundles/org.openhab.io.openhabcloud/README.md
Labels: documentation

#9603 [nikobus] open connection on refresh even if no modules exist
  bundles/org.openhab.binding.nikobus/src/main/java/org/openhab/binding/nikobus/internal/handler/NikobusPcLinkHandler.java
Labels: bug

#9687 [hue] Fixed German translations for motion sensor
  bundles/org.openhab.binding.hue/src/main/resources/OH-INF/config/config.xml
  bundles/org.openhab.binding.hue/src/main/resources/OH-INF/i18n/hue_de.properties
Labels: bug, translation

#9685 [hue] Fixed configuration update for parameter 'ledindication'
  bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/sensors/PresenceHandler.java
Labels: bug

#9646 [js] Added 'ConfigOptionProvider' to provide filenames ending with '.js' in Profile configuration
  bundles/org.openhab.transform.javascript/README.md
  bundles/org.openhab.transform.javascript/src/main/java/org/openhab/transform/javascript/internal/JavaScriptEngineManager.java
  bundles/org.openhab.transform.javascript/src/main/java/org/openhab/transform/javascript/internal/JavaScriptTransformationService.java
  bundles/org.openhab.transform.javascript/src/main/java/org/openhab/transform/javascript/internal/TransformationScriptWatcher.java
  bundles/org.openhab.transform.javascript/src/main/java/org/openhab/transform/javascript/internal/profiles/JavaScriptTransformationProfile.java
  bundles/org.openhab.transform.javascript/src/main/java/org/openhab/transform/javascript/internal/profiles/JavaScriptTransformationProfileFactory.java
  bundles/org.openhab.transform.javascript/src/main/resources/OH-INF/config/javascriptProfile.xml
  bundles/org.openhab.transform.javascript/src/main/resources/readme.txt
Labels: enhancement

#9683 [homekit] Introduce Info box with redirect url
  bundles/org.openhab.io.homekit/README.md
Labels: documentation

#9708 [groovyscripting] Update Groovy to 3.0.7 and add more docs
  bundles/org.openhab.automation.groovyscripting/README.md
  bundles/org.openhab.automation.groovyscripting/pom.xml
Labels: enhancement

#9667 [tr064] improve documentation
  bundles/org.openhab.binding.tr064/README.md
Labels: documentation

#9716 [nikobus] refresh impacted modules on simulated button press
  bundles/org.openhab.binding.nikobus/src/main/java/org/openhab/binding/nikobus/internal/handler/NikobusPushButtonHandler.java
Labels: bug

#9627 [WiFi LED] Expanded example
  bundles/org.openhab.binding.wifiled/README.md
Labels: documentation

#9652 [remoteopenhab] Fix Remote openHAB Readme typos
  bundles/org.openhab.binding.remoteopenhab/README.md
Labels: documentation

#9643 [xmppclient] Update README.md's example rules for OH3
  bundles/org.openhab.binding.xmppclient/README.md
Labels: documentation

#9601 [http] enable UoM for number channels
  bundles/org.openhab.binding.http/README.md
  bundles/org.openhab.binding.http/src/main/java/org/openhab/binding/http/internal/HttpThingHandler.java
  bundles/org.openhab.binding.http/src/main/java/org/openhab/binding/http/internal/config/HttpChannelConfig.java
  bundles/org.openhab.binding.http/src/main/java/org/openhab/binding/http/internal/converter/NumberItemConverter.java
  bundles/org.openhab.binding.http/src/main/resources/OH-INF/config/config.xml
  bundles/org.openhab.binding.http/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.http/src/test/java/org/openhab/binding/http/internal/converter/ConverterTest.java
Labels: community approved, enhancement

#9717 [openweathermap] Added new supported languages
  bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/config/OpenWeatherMapAPIConfiguration.java
  bundles/org.openhab.binding.openweathermap/src/main/resources/OH-INF/config/config.xml
  bundles/org.openhab.binding.openweathermap/src/main/resources/OH-INF/i18n/openweathermap_de.properties
Labels: enhancement

#9706 [draytonwiser] Expose Smart Plug Power Metering, Improve null handling
  bundles/org.openhab.binding.draytonwiser/README.md
  bundles/org.openhab.binding.draytonwiser/src/main/java/org/openhab/binding/draytonwiser/internal/DraytonWiserBindingConstants.java
  bundles/org.openhab.binding.draytonwiser/src/main/java/org/openhab/binding/draytonwiser/internal/handler/RoomStatHandler.java
  bundles/org.openhab.binding.draytonwiser/src/main/java/org/openhab/binding/draytonwiser/internal/handler/SmartPlugHandler.java
  bundles/org.openhab.binding.draytonwiser/src/main/java/org/openhab/binding/draytonwiser/internal/handler/TRVHandler.java
  bundles/org.openhab.binding.draytonwiser/src/main/java/org/openhab/binding/draytonwiser/internal/model/DeviceDTO.java
  bundles/org.openhab.binding.draytonwiser/src/main/java/org/openhab/binding/draytonwiser/internal/model/SmartPlugDTO.java
  bundles/org.openhab.binding.draytonwiser/src/main/resources/OH-INF/thing/thing-types.xml
Labels: enhancement

#9714 [icalendar] Update README.md
  bundles/org.openhab.binding.icalendar/README.md
Labels: documentation

#9733 [tr064] Normalize numbers in phone book entries.
  bundles/org.openhab.binding.tr064/README.md
  bundles/org.openhab.binding.tr064/src/main/java/org/openhab/binding/tr064/internal/phonebook/Tr064PhonebookImpl.java
Labels: enhancement

#9475 [homekit] add support for QR code based pairing
  bundles/org.openhab.io.homekit/README.md
  bundles/org.openhab.io.homekit/doc/add_homekit_tag.png
  bundles/org.openhab.io.homekit/doc/ios_add_accessory.png
  bundles/org.openhab.io.homekit/doc/ios_add_accessory_wizard.png
  bundles/org.openhab.io.homekit/doc/ios_add_anyway.png
  bundles/org.openhab.io.homekit/doc/ios_add_new_home.png
  bundles/org.openhab.io.homekit/doc/ios_scan_qrcode.png
  bundles/org.openhab.io.homekit/doc/item_add_metadata_button.png
  bundles/org.openhab.io.homekit/doc/select_homekit_accessory_type.png
  bundles/org.openhab.io.homekit/doc/select_homekit_namespace.png
  bundles/org.openhab.io.homekit/doc/settings_qrcode.png
  bundles/org.openhab.io.homekit/pom.xml
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitAuthInfoImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitSettings.java
  bundles/org.openhab.io.homekit/src/main/resources/OH-INF/config/config.xml
Labels: enhancement

#9677 [innogysmarthome] NullPointerException fixed which could occur when no device state is available (#9660)
  bundles/org.openhab.binding.innogysmarthome/src/main/java/org/openhab/binding/innogysmarthome/internal/client/InnogyClient.java
  bundles/org.openhab.binding.innogysmarthome/src/main/java/org/openhab/binding/innogysmarthome/internal/client/entity/device/Device.java
  bundles/org.openhab.binding.innogysmarthome/src/main/java/org/openhab/binding/innogysmarthome/internal/handler/InnogyBridgeHandler.java
  bundles/org.openhab.binding.innogysmarthome/src/main/java/org/openhab/binding/innogysmarthome/internal/handler/InnogyDeviceHandler.java
  bundles/org.openhab.binding.innogysmarthome/src/main/java/org/openhab/binding/innogysmarthome/internal/manager/DeviceStructureManager.java
  bundles/org.openhab.binding.innogysmarthome/src/main/java/org/openhab/binding/innogysmarthome/internal/manager/FullDeviceManager.java
  bundles/org.openhab.binding.innogysmarthome/src/test/java/org/openhab/binding/innogysmarthome/internal/client/entity/device/DeviceTest.java
  bundles/org.openhab.binding.innogysmarthome/src/test/java/org/openhab/binding/innogysmarthome/internal/handler/InnogyBridgeHandlerTest.java
Labels: bug

#9749 [tr064] fix parameter patterns
  bundles/org.openhab.binding.tr064/src/main/resources/channels.xml
Labels: bug

#9693 [tr064] reduce network load and improve XML handling
  bundles/org.openhab.binding.tr064/src/main/java/org/openhab/binding/tr064/internal/Tr064RootHandler.java
  bundles/org.openhab.binding.tr064/src/main/java/org/openhab/binding/tr064/internal/soap/SOAPConnector.java
  bundles/org.openhab.binding.tr064/src/main/java/org/openhab/binding/tr064/internal/soap/SOAPRequest.java
  bundles/org.openhab.binding.tr064/src/main/java/org/openhab/binding/tr064/internal/util/Util.java
Labels: additional testing preferred, bug

#9686 [deconz] Added channel to enable / disable motion sensor
  bundles/org.openhab.binding.deconz/README.md
  bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/BindingConstants.java
  bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/dto/SensorConfig.java
  bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/dto/SensorUpdateConfig.java
  bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/dto/ThermostatUpdateConfig.java
  bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/handler/DeconzBaseThingHandler.java
  bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/handler/SensorBaseThingHandler.java
  bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/handler/SensorThermostatThingHandler.java
  bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/handler/SensorThingHandler.java
  bundles/org.openhab.binding.deconz/src/main/resources/OH-INF/config/config.xml
  bundles/org.openhab.binding.deconz/src/main/resources/OH-INF/i18n/deconz_de.properties
  bundles/org.openhab.binding.deconz/src/main/resources/OH-INF/thing/sensor-thing-types.xml
Labels: enhancement

#9769 [homekit] fix pairing after addon update
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitImpl.java
Labels: bug

#9758 [mqtt] Only unsubscribe if we subscribed before
  bundles/org.openhab.binding.mqtt/src/main/java/org/openhab/binding/mqtt/discovery/TopicSubscribe.java
Labels: bug

#9785 Update bnd to 5.2.0
  pom.xml
Labels: infrastructure

#9761 [lcn] Fix displaying of "not enough licenses" message
  bundles/org.openhab.binding.lcn/src/main/java/org/openhab/binding/lcn/internal/connection/AbstractConnectionState.java
  bundles/org.openhab.binding.lcn/src/main/java/org/openhab/binding/lcn/internal/connection/AbstractConnectionStateSendCredentials.java
  bundles/org.openhab.binding.lcn/src/main/java/org/openhab/binding/lcn/internal/connection/ConnectionStateConnecting.java
  bundles/org.openhab.binding.lcn/src/main/java/org/openhab/binding/lcn/internal/connection/ConnectionStateGracePeriodBeforeReconnect.java
  bundles/org.openhab.binding.lcn/src/main/java/org/openhab/binding/lcn/internal/connection/ConnectionStateMachine.java
  bundles/org.openhab.binding.lcn/src/main/java/org/openhab/binding/lcn/internal/connection/ConnectionStateShutdown.java
  bundles/org.openhab.binding.lcn/src/main/java/org/openhab/binding/lcn/internal/connection/ConnectionStateWaitForLcnBusConnected.java
Labels: bug

#9692 [homematic] Fix for two (re)connection problems
  bundles/org.openhab.binding.homematic/README.md
  bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/common/HomematicConfig.java
  bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/communicator/AbstractHomematicGateway.java
  bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/communicator/client/RpcClient.java
  bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/communicator/client/XmlRpcClient.java
  bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/communicator/message/BinRpcMessage.java
  bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/communicator/message/XmlRpcResponse.java
  bundles/org.openhab.binding.homematic/src/main/resources/OH-INF/thing/bridge.xml
Labels: bug

#9564 [neato] Fixed NPE in discovery service
  bundles/org.openhab.binding.neato/src/main/java/org/openhab/binding/neato/internal/discovery/NeatoAccountDiscoveryService.java
Labels: bug

#9774 [linky] Set channel to UNDEF when data not yet available
  bundles/org.openhab.binding.linky/src/main/java/org/openhab/binding/linky/internal/handler/LinkyHandler.java
Labels: enhancement

#9786 [nanoleaf] Fixed color temperature setting
  bundles/org.openhab.binding.nanoleaf/src/main/java/org/openhab/binding/nanoleaf/internal/handler/NanoleafControllerHandler.java
Labels: bug

#9633 Updated the openhab-cloud readme for OH3
  bundles/org.openhab.io.openhabcloud/README.md
  bundles/org.openhab.io.openhabcloud/contrib/doc/cfg.png
Labels: documentation

#9806 [draytonwiser] MDNS Fixes
  bundles/org.openhab.binding.draytonwiser/src/main/java/org/openhab/binding/draytonwiser/internal/discovery/DraytonWiserMDNSDiscoveryParticipant.java
Labels: bug

#9800 [tplinksmarthome] Add suppport for the TP-Link Kasa KP115 Smart WiFi Plug with Energy Monitoring
  bundles/org.openhab.binding.tplinksmarthome/README.md
  bundles/org.openhab.binding.tplinksmarthome/src/main/java/org/openhab/binding/tplinksmarthome/internal/TPLinkSmartHomeHandlerFactory.java
  bundles/org.openhab.binding.tplinksmarthome/src/main/java/org/openhab/binding/tplinksmarthome/internal/TPLinkSmartHomeThingType.java
  bundles/org.openhab.binding.tplinksmarthome/src/main/resources/OH-INF/thing/KP115.xml
Labels: enhancement, rebuild

#9801 [tado] Hide already instantiated Things in the InBox
  bundles/org.openhab.binding.tado/src/main/java/org/openhab/binding/tado/internal/discovery/TadoDiscoveryService.java
  bundles/org.openhab.binding.tado/src/main/resources/OH-INF/thing/thing-types.xml
Labels: enhancement

#9724 [teleinfo] Fix memory leak
  bundles/org.openhab.binding.teleinfo/src/main/java/org/openhab/binding/teleinfo/internal/handler/TeleinfoAbstractControllerHandler.java
  bundles/org.openhab.binding.teleinfo/src/main/java/org/openhab/binding/teleinfo/internal/handler/TeleinfoAbstractElectricityMeterHandler.java
Labels: bug

#9795 [miio] add support for chungmiplug 212a01
  bundles/org.openhab.binding.miio/README.md
  bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/MiIoDevices.java
  bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/MiIoQuantiyTypes.java
  bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/basic/Conversions.java
  bundles/org.openhab.binding.miio/src/main/resources/database/chuangmi.plug.212a01-miot.json
Labels: enhancement

#9802 [tesla] Correctly handle floating point numbers for estimatedbatteryrange channel
  bundles/org.openhab.binding.tesla/src/main/resources/OH-INF/thing/channels.xml
Labels: bug

#9797 [miio] update readme maker - fix item names
  bundles/org.openhab.binding.miio/README.md
  bundles/org.openhab.binding.miio/src/test/java/org/openhab/binding/miio/internal/ReadmeHelper.java
Labels: documentation

#9809 [jablotron] fixed programmable gates channels are not visible in the O…
  bundles/org.openhab.binding.jablotron/src/main/java/org/openhab/binding/jablotron/JablotronBindingConstants.java
  bundles/org.openhab.binding.jablotron/src/main/java/org/openhab/binding/jablotron/internal/handler/JablotronJa100FHandler.java
  bundles/org.openhab.binding.jablotron/src/main/java/org/openhab/binding/jablotron/internal/handler/JablotronJa100Handler.java
  bundles/org.openhab.binding.jablotron/src/main/resources/OH-INF/thing/channels.xml
Labels: bug

#9808 [siemensrds] Hide already instantiated Things in the InBox
  bundles/org.openhab.binding.siemensrds/src/main/java/org/openhab/binding/siemensrds/internal/RdsDataPoints.java
  bundles/org.openhab.binding.siemensrds/src/main/resources/OH-INF/thing/thing-types.xml
Labels: enhancement

#9766 [ipcamera] Fixes for Instar and HLS.
  bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/Ffmpeg.java
  bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/InstarHandler.java
  bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/handler/IpCameraHandler.java
Labels: bug, enhancement

#9718 [satel] Thing discovery fix
  bundles/org.openhab.binding.satel/README.md
  bundles/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/SatelHandlerFactory.java
  bundles/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/discovery/SatelDeviceDiscoveryService.java
Labels: bug

#9794 [velux] Fixed a couple of bugs if the Bridge contains one or more Scenes
  bundles/org.openhab.binding.velux/org.openhab.binding.velux-3.1.0-SNAPSHOT.jar
  bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/VeluxBindingConstants.java
  bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/discovery/VeluxDiscoveryService.java
  bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/handler/ChannelBridgeCheck.java
  bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/handler/VeluxBridgeHandler.java
  bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/handler/utils/Thing2VeluxActuator.java
Labels: bug

#9778 [avmfritz] Added warning if temperature command cannot be converted to Celsius
  bundles/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/handler/AVMFritzBaseThingHandler.java
Labels: bug

#9753 [avmfritz] Fixed channel update for DECT440 rocker
  bundles/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/AVMFritzBindingConstants.java
  bundles/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/dto/DeviceModel.java
  bundles/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/handler/AVMFritzBaseThingHandler.java
  bundles/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/handler/AVMFritzButtonHandler.java
Labels: bug

#9812 [amazonechocontrol] fix thermostat handler
  bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/smarthome/Constants.java
  bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/smarthome/HandlerThermostatController.java
Labels: bug

#9814 [tibber] Enhancement, added channel and channel corrections due to API changes
  bundles/org.openhab.binding.tibber/README.md
  bundles/org.openhab.binding.tibber/src/main/java/org/openhab/binding/tibber/internal/TibberBindingConstants.java
  bundles/org.openhab.binding.tibber/src/main/java/org/openhab/binding/tibber/internal/handler/TibberHandler.java
  bundles/org.openhab.binding.tibber/src/main/java/org/openhab/binding/tibber/internal/handler/TibberPriceConsumptionHandler.java
  bundles/org.openhab.binding.tibber/src/main/resources/OH-INF/thing/thing-types.xml
Labels: enhancement

#9822 [velux] Remove jar from prior PR
  bundles/org.openhab.binding.velux/org.openhab.binding.velux-3.1.0-SNAPSHOT.jar
Labels: infrastructure

#9819 [influxdb] Add path of the configuration file to Readme
  bundles/org.openhab.persistence.influxdb/README.md
Labels: documentation

#9572 [mqtt-homeassistant] Add JOSNPath and JINJA as requirements for MQTT HA
  bundles/org.openhab.binding.mqtt.homeassistant/README.md
Labels: documentation

#9770 [epsonprojector] Fix "projector-tcp"-Thing gets stuck after Power-off via TCP
  bundles/org.openhab.binding.epsonprojector/src/main/java/org/openhab/binding/epsonprojector/internal/EpsonProjectorDevice.java
Labels: bug

#9798 [miio] add support for viomi.waterheater.e1
  bundles/org.openhab.binding.miio/README.md
  bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/MiIoDevices.java
  bundles/org.openhab.binding.miio/src/main/resources/database/viomi.waterheater.e1.json
Labels: enhancement

#9828 Resolve itests for BOM changes
  itests/org.openhab.binding.astro.tests/itest.bndrun
  itests/org.openhab.binding.avmfritz.tests/itest.bndrun
  itests/org.openhab.binding.feed.tests/itest.bndrun
  itests/org.openhab.binding.hue.tests/itest.bndrun
  itests/org.openhab.binding.max.tests/itest.bndrun
  itests/org.openhab.binding.modbus.tests/itest.bndrun
  itests/org.openhab.binding.nest.tests/itest.bndrun
  itests/org.openhab.binding.ntp.tests/itest.bndrun
  itests/org.openhab.binding.systeminfo.tests/itest.bndrun
  itests/org.openhab.binding.tradfri.tests/itest.bndrun
  itests/org.openhab.binding.wemo.tests/itest.bndrun
  itests/org.openhab.persistence.mapdb.tests/itest.bndrun
Labels: infrastructure

#9833 [onewire] fix absolute humidity channel type
  bundles/org.openhab.binding.onewire/src/main/resources/OH-INF/thing/common.xml
Labels: bug

#9834 [digitalstrom] fix concurrency issue
  bundles/org.openhab.binding.digitalstrom/src/main/java/org/openhab/binding/digitalstrom/internal/DigitalSTROMHandlerFactory.java
  bundles/org.openhab.binding.digitalstrom/src/main/java/org/openhab/binding/digitalstrom/internal/lib/manager/impl/DeviceStatusManagerImpl.java
  bundles/org.openhab.binding.digitalstrom/src/main/java/org/openhab/binding/digitalstrom/internal/lib/manager/impl/SceneManagerImpl.java
Labels: bug

#9756 [miio] Improve Airpurifiers
  bundles/org.openhab.binding.miio/README.md
  bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/MiIoQuantiyTypes.java
  bundles/org.openhab.binding.miio/src/main/resources/database/zhimi.airpurifier.m1.json
  bundles/org.openhab.binding.miio/src/main/resources/database/zhimi.airpurifier.ma4-miot.json
  bundles/org.openhab.binding.miio/src/main/resources/database/zhimi.airpurifier.mb3-miot.json
Labels: (potentially) not backward compatible, enhancement

#9849 [icalendar] Ensure DecimalType will be used if no unit given
  bundles/org.openhab.binding.icalendar/src/main/java/org/openhab/binding/icalendar/internal/logic/CommandTag.java
  bundles/org.openhab.binding.icalendar/src/test/java/org/openhab/binding/icalendar/internal/logic/BiweeklyPresentableCalendarTest.java
Labels: bug

#9734 [avmfritz] Added initial refresh of Call Monitor channels and improved thread handling
  bundles/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/callmonitor/CallEvent.java
  bundles/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/callmonitor/CallMonitor.java
  bundles/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/handler/BoxHandler.java
Labels: bug

#9804 [buienradar] Avoid to much log noise
  bundles/org.openhab.binding.buienradar/src/main/java/org/openhab/binding/buienradar/internal/BuienradarHandler.java
  bundles/org.openhab.binding.buienradar/src/main/java/org/openhab/binding/buienradar/internal/buienradarapi/BuienradarPredictionAPI.java
  bundles/org.openhab.binding.buienradar/src/main/resources/OH-INF/thing/thing-types.xml
Labels: bug

#9865 [miio] fix printed zone clean command
  bundles/org.openhab.binding.miio/src/test/java/org/openhab/binding/miio/internal/RoboMapViewer.java
Labels: bug

#9858 [miio] readme update
  bundles/org.openhab.binding.miio/README.base.md
  bundles/org.openhab.binding.miio/doc/miioBindingConfig.jpg
  bundles/org.openhab.binding.miio/doc/miioBindingConfig2.jpg
  bundles/org.openhab.binding.miio/src/main/resources/misc/device_names.json
Labels: documentation

#9859 [miio] add support for dreame vacuum d9
  bundles/org.openhab.binding.miio/README.md
  bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/MiIoDevices.java
  bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/MiIoQuantiyTypes.java
  bundles/org.openhab.binding.miio/src/main/resources/database/dreame.vacuum.mc1808-miot.json
  bundles/org.openhab.binding.miio/src/main/resources/database/dreame.vacuum.p2009-miot.json
Labels: enhancement

#9787 [miio] add support for nwt.derh.wdh318efw1 Internet Dehumidifier
  bundles/org.openhab.binding.miio/README.md
  bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/MiIoDevices.java
  bundles/org.openhab.binding.miio/src/main/resources/database/nwt.derh.wdh318efw1.json
Labels: enhancement

#9860 Fix links and NOTICE files
  bundles/org.openhab.binding.bluetooth.bluegiga/NOTICE
  bundles/org.openhab.binding.fsinternetradio/README.md
  bundles/org.openhab.binding.miele/README.md
  bundles/org.openhab.binding.mqtt.generic/NOTICE
  bundles/org.openhab.binding.mqtt.homeassistant/NOTICE
  bundles/org.openhab.binding.mqtt.homie/NOTICE
  bundles/org.openhab.binding.nibeheatpump/README.md
  bundles/org.openhab.voice.mactts/NOTICE
Labels: documentation

#9571 [roku] binding - initial implementation
  CODEOWNERS
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.roku/NOTICE
  bundles/org.openhab.binding.roku/README.md
  bundles/org.openhab.binding.roku/pom.xml
  bundles/org.openhab.binding.roku/src/main/feature/feature.xml
  bundles/org.openhab.binding.roku/src/main/java/org/openhab/binding/roku/internal/RokuBindingConstants.java
  bundles/org.openhab.binding.roku/src/main/java/org/openhab/binding/roku/internal/RokuConfiguration.java
  bundles/org.openhab.binding.roku/src/main/java/org/openhab/binding/roku/internal/RokuHandlerFactory.java
  bundles/org.openhab.binding.roku/src/main/java/org/openhab/binding/roku/internal/RokuHttpException.java
  bundles/org.openhab.binding.roku/src/main/java/org/openhab/binding/roku/internal/RokuStateDescriptionOptionProvider.java
  bundles/org.openhab.binding.roku/src/main/java/org/openhab/binding/roku/internal/communication/JAXBUtils.java
  bundles/org.openhab.binding.roku/src/main/java/org/openhab/binding/roku/internal/communication/RokuCommunicator.java
  bundles/org.openhab.binding.roku/src/main/java/org/openhab/binding/roku/internal/discovery/RokuDiscoveryService.java
  bundles/org.openhab.binding.roku/src/main/java/org/openhab/binding/roku/internal/dto/ActiveApp.java
  bundles/org.openhab.binding.roku/src/main/java/org/openhab/binding/roku/internal/dto/Apps.java
  bundles/org.openhab.binding.roku/src/main/java/org/openhab/binding/roku/internal/dto/DeviceInfo.java
  bundles/org.openhab.binding.roku/src/main/java/org/openhab/binding/roku/internal/dto/Player.java
  bundles/org.openhab.binding.roku/src/main/java/org/openhab/binding/roku/internal/handler/RokuHandler.java
  bundles/org.openhab.binding.roku/src/main/resources/OH-INF/binding/binding.xml
  bundles/org.openhab.binding.roku/src/main/resources/OH-INF/config/config.xml
  bundles/org.openhab.binding.roku/src/main/resources/OH-INF/thing/roku.xml
  bundles/pom.xml
Labels: cre, new binding

#9861 [miio] add support for Mijia Smart Pet Water Dispensers
  bundles/org.openhab.binding.miio/README.md
  bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/MiIoDevices.java
  bundles/org.openhab.binding.miio/src/main/resources/database/mmgg.pet_waterer.s1-miot.json
  bundles/org.openhab.binding.miio/src/main/resources/database/mmgg.pet_waterer.s2-miot.json
Labels: enhancement

#9856 [hue] Use system default channel types for lights
  bundles/org.openhab.binding.hue/src/main/resources/OH-INF/i18n/hue_de.properties
  bundles/org.openhab.binding.hue/src/main/resources/OH-INF/i18n/hue_fr.properties
  bundles/org.openhab.binding.hue/src/main/resources/OH-INF/thing/ColorLight.xml
  bundles/org.openhab.binding.hue/src/main/resources/OH-INF/thing/ColorTemperatureLight.xml
  bundles/org.openhab.binding.hue/src/main/resources/OH-INF/thing/DimmableLight.xml
  bundles/org.openhab.binding.hue/src/main/resources/OH-INF/thing/DimmablePlug.xml
  bundles/org.openhab.binding.hue/src/main/resources/OH-INF/thing/ExtendedColorLight.xml
  bundles/org.openhab.binding.hue/src/main/resources/OH-INF/thing/Group.xml
  bundles/org.openhab.binding.hue/src/main/resources/OH-INF/thing/OnOffLight.xml
  bundles/org.openhab.binding.hue/src/main/resources/OH-INF/thing/OnOffPlug.xml
  bundles/org.openhab.binding.hue/src/main/resources/OH-INF/thing/channels.xml
Labels: enhancement

#9842 [pidcontroller] Fix for handling trigger input in action
  bundles/org.openhab.automation.pidcontroller/src/main/java/org/openhab/automation/pidcontroller/internal/handler/PIDControllerActionHandler.java
  bundles/org.openhab.automation.pidcontroller/src/main/java/org/openhab/automation/pidcontroller/internal/handler/PIDControllerTriggerHandler.java
Labels: bug

#8922 [OmniLink] Binding Initial Contribution
  CODEOWNERS
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.omnilink/NOTICE
  bundles/org.openhab.binding.omnilink/README.md
  bundles/org.openhab.binding.omnilink/pom.xml
  bundles/org.openhab.binding.omnilink/src/main/feature/feature.xml
  bundles/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/internal/AreaAlarm.java
  bundles/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/internal/AudioPlayer.java
  bundles/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/internal/OmnilinkBindingConstants.java
  bundles/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/internal/OmnilinkHandlerFactory.java
  bundles/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/internal/SystemType.java
  bundles/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/internal/config/OmnilinkBridgeConfig.java
  bundles/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/internal/discovery/ObjectPropertyRequest.java
  bundles/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/internal/discovery/ObjectPropertyRequests.java
  bundles/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/internal/discovery/OmnilinkDiscoveryService.java
  bundles/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/internal/handler/AbstractAreaHandler.java
  bundles/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/internal/handler/AbstractOmnilinkHandler.java
  bundles/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/internal/handler/AbstractOmnilinkStatusHandler.java
  bundles/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/internal/handler/AudioSourceHandler.java
  bundles/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/internal/handler/AudioZoneHandler.java
  bundles/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/internal/handler/BridgeOfflineException.java
  bundles/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/internal/handler/ButtonHandler.java
  bundles/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/internal/handler/ConsoleHandler.java
  bundles/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/internal/handler/HumiditySensorHandler.java
  bundles/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/internal/handler/LockHandler.java
  bundles/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/internal/handler/LuminaAreaHandler.java
  bundles/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/internal/handler/OmniAreaHandler.java
  bundles/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/internal/handler/OmniLinkCmd.java
  bundles/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/internal/handler/OmnilinkBridgeHandler.java
  bundles/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/internal/handler/TempSensorHandler.java
  bundles/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/internal/handler/TemperatureFormat.java
  bundles/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/internal/handler/ThermostatHandler.java
  bundles/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/internal/handler/UnitHandler.java
  bundles/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/internal/handler/ZoneHandler.java
  bundles/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/internal/handler/units/DimmableUnitHandler.java
  bundles/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/internal/handler/units/FlagHandler.java
  bundles/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/internal/handler/units/OutputHandler.java
  bundles/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/internal/handler/units/UpbRoomHandler.java
  bundles/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/internal/handler/units/dimmable/UpbUnitHandler.java
  bundles/org.openhab.binding.omnilink/src/main/resources/OH-INF/binding/binding.xml
  bundles/org.openhab.binding.omnilink/src/main/resources/OH-INF/thing/area.xml
  bundles/org.openhab.binding.omnilink/src/main/resources/OH-INF/thing/audio-source.xml
  bundles/org.openhab.binding.omnilink/src/main/resources/OH-INF/thing/audio-zone.xml
  bundles/org.openhab.binding.omnilink/src/main/resources/OH-INF/thing/bridge.xml
  bundles/org.openhab.binding.omnilink/src/main/resources/OH-INF/thing/button.xml
  bundles/org.openhab.binding.omnilink/src/main/resources/OH-INF/thing/console.xml
  bundles/org.openhab.binding.omnilink/src/main/resources/OH-INF/thing/humidity-sensor.xml
  bundles/org.openhab.binding.omnilink/src/main/resources/OH-INF/thing/lock.xml
  bundles/org.openhab.binding.omnilink/src/main/resources/OH-INF/thing/temp-sensor.xml
  bundles/org.openhab.binding.omnilink/src/main/resources/OH-INF/thing/thermostat.xml
  bundles/org.openhab.binding.omnilink/src/main/resources/OH-INF/thing/unit.xml
  bundles/org.openhab.binding.omnilink/src/main/resources/OH-INF/thing/zone.xml
  bundles/pom.xml
Labels: cre, new binding, oh1 migration

#9634 [tellstick] Fixes a NoClassDefFoundError that caused the Tellstick addon to not work properly
  CODEOWNERS
  bundles/org.openhab.binding.tellstick/pom.xml
  bundles/org.openhab.binding.tellstick/src/main/feature/feature.xml
Labels: bug

#9879 [tr064] Update docs: Manual scan
  bundles/org.openhab.binding.tr064/README.md
Labels: documentation

#9854 [tr064] Improve PHONEBOOK profile documentation
  bundles/org.openhab.binding.tr064/README.md
Labels: documentation

#9259 [androiddebugbridge] initial contribution
  CODEOWNERS
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.androiddebugbridge/NOTICE
  bundles/org.openhab.binding.androiddebugbridge/README.md
  bundles/org.openhab.binding.androiddebugbridge/pom.xml
  bundles/org.openhab.binding.androiddebugbridge/src/main/feature/feature.xml
  bundles/org.openhab.binding.androiddebugbridge/src/main/java/org/openhab/binding/androiddebugbridge/internal/AndroidDebugBridgeBindingConfiguration.java
  bundles/org.openhab.binding.androiddebugbridge/src/main/java/org/openhab/binding/androiddebugbridge/internal/AndroidDebugBridgeBindingConstants.java
  bundles/org.openhab.binding.androiddebugbridge/src/main/java/org/openhab/binding/androiddebugbridge/internal/AndroidDebugBridgeConfiguration.java
  bundles/org.openhab.binding.androiddebugbridge/src/main/java/org/openhab/binding/androiddebugbridge/internal/AndroidDebugBridgeDevice.java
  bundles/org.openhab.binding.androiddebugbridge/src/main/java/org/openhab/binding/androiddebugbridge/internal/AndroidDebugBridgeDeviceException.java
  bundles/org.openhab.binding.androiddebugbridge/src/main/java/org/openhab/binding/androiddebugbridge/internal/AndroidDebugBridgeDeviceReadException.java
  bundles/org.openhab.binding.androiddebugbridge/src/main/java/org/openhab/binding/androiddebugbridge/internal/AndroidDebugBridgeDiscoveryService.java
  bundles/org.openhab.binding.androiddebugbridge/src/main/java/org/openhab/binding/androiddebugbridge/internal/AndroidDebugBridgeHandler.java
  bundles/org.openhab.binding.androiddebugbridge/src/main/java/org/openhab/binding/androiddebugbridge/internal/AndroidDebugBridgeHandlerFactory.java
  bundles/org.openhab.binding.androiddebugbridge/src/main/resources/OH-INF/binding/binding.xml
  bundles/org.openhab.binding.androiddebugbridge/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/pom.xml
Labels: new binding

#9900 [dsmr] Fix test after openhab-core change #2126
  bundles/org.openhab.binding.dsmr/src/test/java/org/openhab/binding/dsmr/internal/device/DSMRSerialAutoDeviceTest.java
Labels: critical

#9887 [miio] reorganise the device list
  bundles/org.openhab.binding.miio/README.md
  bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/MiIoDevices.java
Labels: documentation

#9888 [miio] fix channels with invalid names
  bundles/org.openhab.binding.miio/src/main/resources/database/yunmi.waterpurifier.json
  bundles/org.openhab.binding.miio/src/main/resources/database/yunmi.waterpurifier.lx8.json
  bundles/org.openhab.binding.miio/src/main/resources/database/zhimi.airpurifier.ma4-miot.json
  bundles/org.openhab.binding.miio/src/main/resources/database/zhimi.airpurifier.mb3-miot.json
Labels: bug

#9901 [miio] Fix double status update
  bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/handler/MiIoBasicHandler.java
Labels: bug

#9904 [jdbc] Do not define bundle related versions in OH feature file
  bundles/org.openhab.persistence.jdbc/src/main/feature/feature.xml
  features/pom.xml
Labels: bug

#8685 [haywardomnilogic] Replacement for Hayward Omnilogic Pool Automation Binding
  CODEOWNERS
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.haywardomnilogic/NOTICE
  bundles/org.openhab.binding.haywardomnilogic/README.md
  bundles/org.openhab.binding.haywardomnilogic/pom.xml
  bundles/org.openhab.binding.haywardomnilogic/src/main/java/org/openhab/binding/haywardomnilogic/internal/HaywardAccount.java
  bundles/org.openhab.binding.haywardomnilogic/src/main/java/org/openhab/binding/haywardomnilogic/internal/HaywardBindingConstants.java
  bundles/org.openhab.binding.haywardomnilogic/src/main/java/org/openhab/binding/haywardomnilogic/internal/HaywardException.java
  bundles/org.openhab.binding.haywardomnilogic/src/main/java/org/openhab/binding/haywardomnilogic/internal/HaywardHandlerFactory.java
  bundles/org.openhab.binding.haywardomnilogic/src/main/java/org/openhab/binding/haywardomnilogic/internal/HaywardThingHandler.java
  bundles/org.openhab.binding.haywardomnilogic/src/main/java/org/openhab/binding/haywardomnilogic/internal/HaywardThingProperties.java
  bundles/org.openhab.binding.haywardomnilogic/src/main/java/org/openhab/binding/haywardomnilogic/internal/HaywardTypeToRequest.java
  bundles/org.openhab.binding.haywardomnilogic/src/main/java/org/openhab/binding/haywardomnilogic/internal/config/HaywardConfig.java
  bundles/org.openhab.binding.haywardomnilogic/src/main/java/org/openhab/binding/haywardomnilogic/internal/discovery/HaywardDiscoveryService.java
  bundles/org.openhab.binding.haywardomnilogic/src/main/java/org/openhab/binding/haywardomnilogic/internal/handler/HaywardBackyardHandler.java
  bundles/org.openhab.binding.haywardomnilogic/src/main/java/org/openhab/binding/haywardomnilogic/internal/handler/HaywardBowHandler.java
  bundles/org.openhab.binding.haywardomnilogic/src/main/java/org/openhab/binding/haywardomnilogic/internal/handler/HaywardBridgeHandler.java
  bundles/org.openhab.binding.haywardomnilogic/src/main/java/org/openhab/binding/haywardomnilogic/internal/handler/HaywardChlorinatorHandler.java
  bundles/org.openhab.binding.haywardomnilogic/src/main/java/org/openhab/binding/haywardomnilogic/internal/handler/HaywardColorLogicHandler.java
  bundles/org.openhab.binding.haywardomnilogic/src/main/java/org/openhab/binding/haywardomnilogic/internal/handler/HaywardFilterHandler.java
  bundles/org.openhab.binding.haywardomnilogic/src/main/java/org/openhab/binding/haywardomnilogic/internal/handler/HaywardHeaterHandler.java
  bundles/org.openhab.binding.haywardomnilogic/src/main/java/org/openhab/binding/haywardomnilogic/internal/handler/HaywardRelayHandler.java
  bundles/org.openhab.binding.haywardomnilogic/src/main/java/org/openhab/binding/haywardomnilogic/internal/handler/HaywardSensorHandler.java
  bundles/org.openhab.binding.haywardomnilogic/src/main/java/org/openhab/binding/haywardomnilogic/internal/handler/HaywardVirtualHeaterHandler.java
  bundles/org.openhab.binding.haywardomnilogic/src/main/resources/OH-INF/binding/binding.xml
  bundles/org.openhab.binding.haywardomnilogic/src/main/resources/OH-INF/thing/backyard.xml
  bundles/org.openhab.binding.haywardomnilogic/src/main/resources/OH-INF/thing/bow.xml
  bundles/org.openhab.binding.haywardomnilogic/src/main/resources/OH-INF/thing/bridge.xml
  bundles/org.openhab.binding.haywardomnilogic/src/main/resources/OH-INF/thing/chlorinator.xml
  bundles/org.openhab.binding.haywardomnilogic/src/main/resources/OH-INF/thing/colorlogic.xml
  bundles/org.openhab.binding.haywardomnilogic/src/main/resources/OH-INF/thing/filter.xml
  bundles/org.openhab.binding.haywardomnilogic/src/main/resources/OH-INF/thing/heater.xml
  bundles/org.openhab.binding.haywardomnilogic/src/main/resources/OH-INF/thing/pump.xml
  bundles/org.openhab.binding.haywardomnilogic/src/main/resources/OH-INF/thing/relay.xml
  bundles/org.openhab.binding.haywardomnilogic/src/main/resources/OH-INF/thing/sensor.xml
  bundles/org.openhab.binding.haywardomnilogic/src/main/resources/OH-INF/thing/virtualHeater.xml
  bundles/pom.xml
Labels: cre, new binding

#9885 [miio] add support for zhimi airpurifier 3C (mb4)
  bundles/org.openhab.binding.miio/README.md
  bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/MiIoDevices.java
  bundles/org.openhab.binding.miio/src/main/resources/database/zhimi.airpurifier.mb4-miot.json
Labels: enhancement

#9915 [deconz] fix loglevel
  bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/handler/LightThingHandler.java
Labels: bug

#9760 [mqtt] Remove default for contact/switch alternate on/off message
  bundles/org.openhab.binding.mqtt.generic/src/main/resources/OH-INF/config/switch-channel-config.xml
Labels: bug

#9927 [mqtt.generic] Fix trigger channel definition
  bundles/org.openhab.binding.mqtt.generic/src/main/resources/OH-INF/thing/channels.xml
Labels: bug

#9924 [http] add note on escaping URLs
  bundles/org.openhab.binding.http/README.md
Labels: documentation

#9928 [hue] Fix rule example
  bundles/org.openhab.binding.hue/README.md
Labels: documentation

#9832 [openweathermap] Fixed UV-Index Channel Group Creation
  bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/OpenWeatherMapBindingConstants.java
  bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/handler/OpenWeatherMapUVIndexHandler.java
Labels: bug

#9864 [tradfri] Use system default channel types for lights
  bundles/org.openhab.binding.tradfri/src/main/resources/OH-INF/i18n/tradfri_de.properties
  bundles/org.openhab.binding.tradfri/src/main/resources/OH-INF/thing/thing-types.xml
Labels: enhancement

#9881 [mqtt.generic] Update README.md
  bundles/org.openhab.binding.mqtt.generic/README.md
Labels: documentation

#9886 [MAP transformation] Update README.md
  bundles/org.openhab.transform.map/README.md
Labels: documentation

#9916 [sonos] Add support for Sonos Arc/Arc SL + new controls for sub/surround speakers
  bundles/org.openhab.binding.sonos/README.md
  bundles/org.openhab.binding.sonos/src/main/java/org/openhab/binding/sonos/internal/SonosBindingConstants.java
  bundles/org.openhab.binding.sonos/src/main/java/org/openhab/binding/sonos/internal/discovery/ZonePlayerDiscoveryParticipant.java
  bundles/org.openhab.binding.sonos/src/main/java/org/openhab/binding/sonos/internal/handler/ZonePlayerHandler.java
  bundles/org.openhab.binding.sonos/src/main/resources/OH-INF/thing/Arc.xml
  bundles/org.openhab.binding.sonos/src/main/resources/OH-INF/thing/ArcSL.xml
  bundles/org.openhab.binding.sonos/src/main/resources/OH-INF/thing/channels.xml
Labels: enhancement

#9914 [deconz] add ontime feature
  bundles/org.openhab.binding.deconz/README.md
  bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/BindingConstants.java
  bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/dto/LightState.java
  bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/handler/LightThingHandler.java
  bundles/org.openhab.binding.deconz/src/main/resources/OH-INF/thing/light-thing-types.xml
Labels: enhancement

#9929 [neeo] fix forwardActionServlet and code improvements
  bundles/org.openhab.binding.neeo/src/main/java/org/openhab/binding/neeo/internal/NeeoBrainConfig.java
  bundles/org.openhab.binding.neeo/src/main/java/org/openhab/binding/neeo/internal/NeeoDeviceConfig.java
  bundles/org.openhab.binding.neeo/src/main/java/org/openhab/binding/neeo/internal/NeeoHandlerCallback.java
  bundles/org.openhab.binding.neeo/src/main/java/org/openhab/binding/neeo/internal/NeeoRoomConfig.java
  bundles/org.openhab.binding.neeo/src/main/java/org/openhab/binding/neeo/internal/handler/NeeoBrainHandler.java
  bundles/org.openhab.binding.neeo/src/main/java/org/openhab/binding/neeo/internal/handler/NeeoForwardActionsServlet.java
Labels: bug

#9912 [fronius] fix invalid json error on meter data
  bundles/org.openhab.binding.fronius/src/main/java/org/openhab/binding/fronius/internal/api/MeterRealtimeBodyDataDTO.java
  bundles/org.openhab.binding.fronius/src/main/java/org/openhab/binding/fronius/internal/handler/FroniusBaseThingHandler.java
Labels: bug

#9911 [icalendar] Use cache folder to store calendar file
  bundles/org.openhab.binding.icalendar/src/main/java/org/openhab/binding/icalendar/internal/handler/ICalendarHandler.java
Labels: enhancement

#8610 [bluetooth.govee] Govee Bluetooth Binding initial contribution
  CODEOWNERS
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.bluetooth.govee/NOTICE
  bundles/org.openhab.binding.bluetooth.govee/README.md
  bundles/org.openhab.binding.bluetooth.govee/pom.xml
  bundles/org.openhab.binding.bluetooth.govee/src/main/feature/feature.xml
  bundles/org.openhab.binding.bluetooth.govee/src/main/java/org/openhab/binding/bluetooth/gattserial/GattMessage.java
  bundles/org.openhab.binding.bluetooth.govee/src/main/java/org/openhab/binding/bluetooth/gattserial/GattSocket.java
  bundles/org.openhab.binding.bluetooth.govee/src/main/java/org/openhab/binding/bluetooth/gattserial/MessageHandler.java
  bundles/org.openhab.binding.bluetooth.govee/src/main/java/org/openhab/binding/bluetooth/gattserial/MessageServicer.java
  bundles/org.openhab.binding.bluetooth.govee/src/main/java/org/openhab/binding/bluetooth/gattserial/MessageSupplier.java
  bundles/org.openhab.binding.bluetooth.govee/src/main/java/org/openhab/binding/bluetooth/gattserial/SimpleGattSocket.java
  bundles/org.openhab.binding.bluetooth.govee/src/main/java/org/openhab/binding/bluetooth/gattserial/SimpleMessage.java
  bundles/org.openhab.binding.bluetooth.govee/src/main/java/org/openhab/binding/bluetooth/gattserial/SimpleMessageHandler.java
  bundles/org.openhab.binding.bluetooth.govee/src/main/java/org/openhab/binding/bluetooth/gattserial/SimpleMessageServicer.java
  bundles/org.openhab.binding.bluetooth.govee/src/main/java/org/openhab/binding/bluetooth/govee/internal/ConnectedBluetoothHandler.java
  bundles/org.openhab.binding.bluetooth.govee/src/main/java/org/openhab/binding/bluetooth/govee/internal/GoveeBindingConstants.java
  bundles/org.openhab.binding.bluetooth.govee/src/main/java/org/openhab/binding/bluetooth/govee/internal/GoveeDiscoveryParticipant.java
  bundles/org.openhab.binding.bluetooth.govee/src/main/java/org/openhab/binding/bluetooth/govee/internal/GoveeHandlerFactory.java
  bundles/org.openhab.binding.bluetooth.govee/src/main/java/org/openhab/binding/bluetooth/govee/internal/GoveeHygrometerConfiguration.java
  bundles/org.openhab.binding.bluetooth.govee/src/main/java/org/openhab/binding/bluetooth/govee/internal/GoveeHygrometerHandler.java
  bundles/org.openhab.binding.bluetooth.govee/src/main/java/org/openhab/binding/bluetooth/govee/internal/GoveeModel.java
  bundles/org.openhab.binding.bluetooth.govee/src/main/java/org/openhab/binding/bluetooth/govee/internal/command/hygrometer/GetBatteryCommand.java
  bundles/org.openhab.binding.bluetooth.govee/src/main/java/org/openhab/binding/bluetooth/govee/internal/command/hygrometer/GetCommand.java
  bundles/org.openhab.binding.bluetooth.govee/src/main/java/org/openhab/binding/bluetooth/govee/internal/command/hygrometer/GetOrSetHumCaliCommand.java
  bundles/org.openhab.binding.bluetooth.govee/src/main/java/org/openhab/binding/bluetooth/govee/internal/command/hygrometer/GetOrSetHumWarningCommand.java
  bundles/org.openhab.binding.bluetooth.govee/src/main/java/org/openhab/binding/bluetooth/govee/internal/command/hygrometer/GetOrSetTemCaliCommand.java
  bundles/org.openhab.binding.bluetooth.govee/src/main/java/org/openhab/binding/bluetooth/govee/internal/command/hygrometer/GetOrSetTemWarningCommand.java
  bundles/org.openhab.binding.bluetooth.govee/src/main/java/org/openhab/binding/bluetooth/govee/internal/command/hygrometer/GetTemHumCommand.java
  bundles/org.openhab.binding.bluetooth.govee/src/main/java/org/openhab/binding/bluetooth/govee/internal/command/hygrometer/GoveeCommand.java
  bundles/org.openhab.binding.bluetooth.govee/src/main/java/org/openhab/binding/bluetooth/govee/internal/command/hygrometer/GoveeMessage.java
  bundles/org.openhab.binding.bluetooth.govee/src/main/java/org/openhab/binding/bluetooth/govee/internal/command/hygrometer/SetCommand.java
  bundles/org.openhab.binding.bluetooth.govee/src/main/java/org/openhab/binding/bluetooth/govee/internal/command/hygrometer/TemHumDTO.java
  bundles/org.openhab.binding.bluetooth.govee/src/main/java/org/openhab/binding/bluetooth/govee/internal/command/hygrometer/WarningSettingsDTO.java
  bundles/org.openhab.binding.bluetooth.govee/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.bluetooth.govee/src/test/java/org/openhab/binding/bluetooth/govee/internal/GoveeModelTest.java
  bundles/org.openhab.binding.bluetooth.govee/src/test/java/org/openhab/binding/bluetooth/govee/internal/readme/ThingTypeTableGenerator.java
  bundles/org.openhab.binding.bluetooth/pom.xml
  bundles/pom.xml
  features/openhab-addons/src/main/resources/footer.xml
Labels: cre, new binding

#9940 Add POM and feature dependencies for commons-net
  bundles/org.openhab.binding.dscalarm/pom.xml
  bundles/org.openhab.binding.heos/pom.xml
  bundles/org.openhab.binding.heos/src/main/feature/feature.xml
  bundles/org.openhab.binding.kaleidescape/pom.xml
  bundles/org.openhab.binding.lutron/pom.xml
  bundles/org.openhab.binding.magentatv/pom.xml
  bundles/org.openhab.binding.magentatv/src/main/feature/feature.xml
  bundles/org.openhab.binding.network/pom.xml
  bundles/org.openhab.binding.network/src/main/feature/feature.xml
  bundles/org.openhab.binding.ntp/pom.xml
  bundles/org.openhab.binding.ntp/src/main/feature/feature.xml
  bundles/org.openhab.binding.opensprinkler/pom.xml
  bundles/org.openhab.binding.opensprinkler/src/main/feature/feature.xml
  bundles/org.openhab.binding.pjlinkdevice/pom.xml
  bundles/org.openhab.binding.pjlinkdevice/src/main/feature/feature.xml
  bundles/org.openhab.binding.plclogo/pom.xml
  bundles/org.openhab.binding.plclogo/src/main/feature/feature.xml
  bundles/org.openhab.binding.russound/pom.xml
  bundles/org.openhab.binding.russound/src/main/feature/feature.xml
  bundles/org.openhab.binding.zway/pom.xml
  bundles/org.openhab.binding.zway/src/main/feature/feature.xml
  bundles/pom.xml
  pom.xml
Labels: infrastructure

#9918 [sonos] Add bass/treble/loudness controls
  bundles/org.openhab.binding.sonos/README.md
  bundles/org.openhab.binding.sonos/src/main/java/org/openhab/binding/sonos/internal/SonosBindingConstants.java
  bundles/org.openhab.binding.sonos/src/main/java/org/openhab/binding/sonos/internal/handler/ZonePlayerHandler.java
  bundles/org.openhab.binding.sonos/src/main/resources/OH-INF/thing/Amp.xml
  bundles/org.openhab.binding.sonos/src/main/resources/OH-INF/thing/Arc.xml
  bundles/org.openhab.binding.sonos/src/main/resources/OH-INF/thing/ArcSL.xml
  bundles/org.openhab.binding.sonos/src/main/resources/OH-INF/thing/Beam.xml
  bundles/org.openhab.binding.sonos/src/main/resources/OH-INF/thing/CONNECT.xml
  bundles/org.openhab.binding.sonos/src/main/resources/OH-INF/thing/CONNECTAMP.xml
  bundles/org.openhab.binding.sonos/src/main/resources/OH-INF/thing/One.xml
  bundles/org.openhab.binding.sonos/src/main/resources/OH-INF/thing/OneSL.xml
  bundles/org.openhab.binding.sonos/src/main/resources/OH-INF/thing/PLAY1.xml
  bundles/org.openhab.binding.sonos/src/main/resources/OH-INF/thing/PLAY3.xml
  bundles/org.openhab.binding.sonos/src/main/resources/OH-INF/thing/PLAY5.xml
  bundles/org.openhab.binding.sonos/src/main/resources/OH-INF/thing/PLAYBAR.xml
  bundles/org.openhab.binding.sonos/src/main/resources/OH-INF/thing/PLAYBASE.xml
  bundles/org.openhab.binding.sonos/src/main/resources/OH-INF/thing/Port.xml
  bundles/org.openhab.binding.sonos/src/main/resources/OH-INF/thing/SYMFONISK.xml
  bundles/org.openhab.binding.sonos/src/main/resources/OH-INF/thing/ZonePlayer.xml
  bundles/org.openhab.binding.sonos/src/main/resources/OH-INF/thing/channels.xml
Labels: enhancement

#9949 [serial] Correct config examples
  bundles/org.openhab.binding.serial/README.md
Labels: documentation

#9882 Add issue template config
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/documentation_issue.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/usage_question.md
Labels: infrastructure

#9954 [tr064] fix wrong unit in TotalBytes
  bundles/org.openhab.binding.tr064/README.md
  bundles/org.openhab.binding.tr064/src/main/resources/channels.xml
Labels: bug, documentation

#9952 [sonos] Add sub/surround controls to Beam, Playbar and Playbase
  bundles/org.openhab.binding.sonos/src/main/resources/OH-INF/thing/Beam.xml
  bundles/org.openhab.binding.sonos/src/main/resources/OH-INF/thing/PLAYBAR.xml
  bundles/org.openhab.binding.sonos/src/main/resources/OH-INF/thing/PLAYBASE.xml
Labels: enhancement

#9955 [deconz] fix missing re-connect if first request timed out
  bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/handler/DeconzBridgeHandler.java
Labels: bug, community approved

#9941 [HEOS] Update pause/stop handling
  bundles/org.openhab.binding.heos/src/main/java/org/openhab/binding/heos/internal/handler/HeosBridgeHandler.java
  bundles/org.openhab.binding.heos/src/main/java/org/openhab/binding/heos/internal/handler/HeosChannelHandlerControl.java
  bundles/org.openhab.binding.heos/src/main/java/org/openhab/binding/heos/internal/json/payload/Media.java
  bundles/org.openhab.binding.heos/src/main/java/org/openhab/binding/heos/internal/resources/HeosEventListener.java
  bundles/org.openhab.binding.heos/src/main/java/org/openhab/binding/heos/internal/resources/HeosMediaEventListener.java
  bundles/org.openhab.binding.heos/src/main/java/org/openhab/binding/heos/internal/resources/HeosSystemEventListener.java
Labels: enhancement

#9923 [samsungtv] Fix WebSocket TVs stay UNKNOWN until first power-on
  bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/handler/SamsungTvHandler.java
Labels: bug

#9959 [miio] allow all quantitytypes and units
  bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/handler/MiIoBasicHandler.java
Labels: enhancement

#9775 [irobot] Add command "cleanRegions" to clean specific regions only
  bundles/org.openhab.binding.irobot/README.md
  bundles/org.openhab.binding.irobot/src/main/java/org/openhab/binding/irobot/internal/IRobotBindingConstants.java
  bundles/org.openhab.binding.irobot/src/main/java/org/openhab/binding/irobot/internal/dto/MQTTProtocol.java
  bundles/org.openhab.binding.irobot/src/main/java/org/openhab/binding/irobot/internal/handler/RoombaHandler.java
  bundles/org.openhab.binding.irobot/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.irobot/src/test/java/org/openhab/binding/irobot/internal/handler/RoombaHandlerTest.java
Labels: enhancement

#9939 [hue] Added support for different color temperature capabilities and added Channel to set value in Kelvin
  bundles/org.openhab.binding.hue/README.md
  bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/FullLight.java
  bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/HttpClient.java
  bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/HueBindingConstants.java
  bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/HueThingHandlerFactory.java
  bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/State.java
  bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/StateUpdate.java
  bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/dto/Capabilities.java
  bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/dto/ColorTemperature.java
  bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/dto/Control.java
  bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/HueGroupHandler.java
  bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/HueLightHandler.java
  bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/HueStateDescriptionOptionProvider.java
  bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/LightStateConverter.java
  bundles/org.openhab.binding.hue/src/main/resources/OH-INF/thing/ColorTemperatureLight.xml
  bundles/org.openhab.binding.hue/src/main/resources/OH-INF/thing/ExtendedColorLight.xml
  bundles/org.openhab.binding.hue/src/main/resources/OH-INF/thing/Group.xml
  bundles/org.openhab.binding.hue/src/test/java/org/openhab/binding/hue/internal/LightStateConverterTest.java
  bundles/org.openhab.binding.hue/src/test/java/org/openhab/binding/hue/internal/handler/HueLightHandlerTest.java
Labels: enhancement

#9962 [sonos] Add support for Sonos Move
  bundles/org.openhab.binding.sonos/README.md
  bundles/org.openhab.binding.sonos/src/main/java/org/openhab/binding/sonos/internal/SonosBindingConstants.java
  bundles/org.openhab.binding.sonos/src/main/resources/OH-INF/thing/Move.xml
Labels: enhancement

#9968 [miio] add support for zhimi.humidifier.cb2 Smartmi Evaporative Humidifier
  bundles/org.openhab.binding.miio/README.md
  bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/MiIoDevices.java
  bundles/org.openhab.binding.miio/src/main/resources/database/zhimi.humidifier.cb1.json
  bundles/org.openhab.binding.miio/src/test/java/org/openhab/binding/miio/internal/ReadmeHelper.java
Labels: enhancement

#9935 [heos] Fix runtime error; Support for new Denon "Home" speaker added
  bundles/org.openhab.binding.heos/src/main/java/org/openhab/binding/heos/internal/discovery/HeosDiscoveryParticipant.java
  bundles/org.openhab.binding.heos/src/main/java/org/openhab/binding/heos/internal/handler/HeosPlayerHandler.java
Labels: bug, enhancement

#9981 [http] fix duplicate commands on PlayerItemConverter
  bundles/org.openhab.binding.http/src/main/java/org/openhab/binding/http/internal/converter/PlayerItemConverter.java
Labels: bug

#9970 [miio] remove unit from color temperature
  bundles/org.openhab.binding.miio/README.md
  bundles/org.openhab.binding.miio/src/main/resources/database/yeelink.light.ceiling.json
  bundles/org.openhab.binding.miio/src/main/resources/database/yeelink.light.ceiling2.json
  bundles/org.openhab.binding.miio/src/main/resources/database/yeelink.light.ceiling4.json
  bundles/org.openhab.binding.miio/src/main/resources/database/yeelink.light.color1.json
  bundles/org.openhab.binding.miio/src/main/resources/database/yeelink.light.lamp1.json
Labels: bug

#9982 [amazonechocontrol] fix routines
  bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/Connection.java
Labels: bug, community approved

#9983 [amazonechocontrol] fix routines (backport)
  bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/Connection.java
Labels: bug, oh25x

#9218 [espmilighthub] Initial contribution
  CODEOWNERS
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.mqtt.espmilighthub/NOTICE
  bundles/org.openhab.binding.mqtt.espmilighthub/README.md
  bundles/org.openhab.binding.mqtt.espmilighthub/pom.xml
  bundles/org.openhab.binding.mqtt.espmilighthub/src/main/feature/feature.xml
  bundles/org.openhab.binding.mqtt.espmilighthub/src/main/java/org/openhab/binding/mqtt/espmilighthub/internal/ConfigOptions.java
  bundles/org.openhab.binding.mqtt.espmilighthub/src/main/java/org/openhab/binding/mqtt/espmilighthub/internal/EspMilightHubBindingConstants.java
  bundles/org.openhab.binding.mqtt.espmilighthub/src/main/java/org/openhab/binding/mqtt/espmilighthub/internal/EspMilightHubHandlerFactory.java
  bundles/org.openhab.binding.mqtt.espmilighthub/src/main/java/org/openhab/binding/mqtt/espmilighthub/internal/Helper.java
  bundles/org.openhab.binding.mqtt.espmilighthub/src/main/java/org/openhab/binding/mqtt/espmilighthub/internal/discovery/EspMilightHubDiscoveryService.java
  bundles/org.openhab.binding.mqtt.espmilighthub/src/main/java/org/openhab/binding/mqtt/espmilighthub/internal/handler/EspMilightHubHandler.java
  bundles/org.openhab.binding.mqtt.espmilighthub/src/main/resources/OH-INF/config/config.xml
  bundles/org.openhab.binding.mqtt.espmilighthub/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.mqtt/src/main/java/org/openhab/binding/mqtt/MqttBindingConstants.java
  bundles/pom.xml
  features/openhab-addons/src/main/resources/footer.xml
Labels: cre, new binding

#9989 [influxdb] FIX: Documentation Grammar
  bundles/org.openhab.persistence.influxdb/README.md
Labels: documentation

#9966 [miio] validate response id matching command id
  bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/transport/MiIoAsyncCommunication.java
Labels: bug

#9988 [amazondashbutton] fix representation property
  bundles/org.openhab.binding.amazondashbutton/src/main/java/org/openhab/binding/amazondashbutton/internal/AmazonDashButtonBindingConstants.java
  bundles/org.openhab.binding.amazondashbutton/src/main/java/org/openhab/binding/amazondashbutton/internal/discovery/AmazonDashButtonDiscoveryService.java
Labels: bug

#9992 [pidcontroller] Reset command Item; Fix read-only states of config parameters
  bundles/org.openhab.automation.pidcontroller/src/main/java/org/openhab/automation/pidcontroller/internal/handler/PIDControllerTriggerHandler.java
  bundles/org.openhab.automation.pidcontroller/src/main/java/org/openhab/automation/pidcontroller/internal/type/PIDControllerTriggerType.java
Labels: bug

#9998 [sonos] Add new channels for battery (Sonos Move)
  bundles/org.openhab.binding.sonos/README.md
  bundles/org.openhab.binding.sonos/src/main/java/org/openhab/binding/sonos/internal/SonosBindingConstants.java
  bundles/org.openhab.binding.sonos/src/main/java/org/openhab/binding/sonos/internal/handler/ZonePlayerHandler.java
  bundles/org.openhab.binding.sonos/src/main/resources/OH-INF/thing/Move.xml
  bundles/org.openhab.binding.sonos/src/main/resources/OH-INF/thing/channels.xml
Labels: enhancement

#10007 [smartmeter] Fix NPE while trying to get ChannelType
  bundles/org.openhab.binding.smartmeter/src/main/java/org/openhab/binding/smartmeter/internal/SmartMeterChannelTypeProvider.java
Labels: bug

#10009 [amazonechocontrol] fix missing time (backport from 3.0)
  bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/handler/EchoHandler.java
Labels: bug, oh25x

#9999 [sonos] Add new channel for microphone (Arc, Beam, Move, One)
  bundles/org.openhab.binding.sonos/README.md
  bundles/org.openhab.binding.sonos/src/main/java/org/openhab/binding/sonos/internal/SonosBindingConstants.java
  bundles/org.openhab.binding.sonos/src/main/java/org/openhab/binding/sonos/internal/handler/ZonePlayerHandler.java
  bundles/org.openhab.binding.sonos/src/main/resources/OH-INF/thing/Arc.xml
  bundles/org.openhab.binding.sonos/src/main/resources/OH-INF/thing/Beam.xml
  bundles/org.openhab.binding.sonos/src/main/resources/OH-INF/thing/Move.xml
  bundles/org.openhab.binding.sonos/src/main/resources/OH-INF/thing/One.xml
  bundles/org.openhab.binding.sonos/src/main/resources/OH-INF/thing/channels.xml
Labels: enhancement
