Repository openhab/openhab-addons, pull requests merged in 2021-11, with the labels that each got.

#11485 [openuv] Internationalization of discovery result
  bundles/org.openhab.binding.openuv/src/main/java/org/openhab/binding/openuv/internal/discovery/OpenUVDiscoveryService.java
Labels: translation

#11484 [openweathermap] Internationalization of discovery results
  bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/discovery/OpenWeatherMapDiscoveryService.java
  bundles/org.openhab.binding.openweathermap/src/main/resources/OH-INF/i18n/openweathermap.properties
  bundles/org.openhab.binding.openweathermap/src/main/resources/OH-INF/i18n/openweathermap_de.properties
  bundles/org.openhab.binding.openweathermap/src/main/resources/OH-INF/i18n/openweathermap_fr.properties
Labels: translation

#11486 [weathercompany] Internationalization of discovery result
  bundles/org.openhab.binding.weathercompany/src/main/java/org/openhab/binding/weathercompany/internal/discovery/WeatherCompanyDiscoveryService.java
  bundles/org.openhab.binding.weathercompany/src/main/resources/OH-INF/i18n/weathercompany.properties
Labels: translation

#11495 [vigicrues] Add default translations to properties file
  bundles/org.openhab.binding.vigicrues/src/main/resources/OH-INF/i18n/vigicrues.properties
  bundles/org.openhab.binding.vigicrues/src/main/resources/OH-INF/i18n/vigicrues_fr.properties
  bundles/org.openhab.binding.vigicrues/src/main/resources/OH-INF/thing/thing-types.xml
Labels: translation

#11505 Configure default timeout of 15 minutes for all testable and lifecycle methods
  pom.xml
Labels: test

#11498 [tradfri] Internationalization of discovery results
  bundles/org.openhab.binding.tradfri/src/main/java/org/openhab/binding/tradfri/internal/discovery/TradfriDiscoveryParticipant.java
  bundles/org.openhab.binding.tradfri/src/main/resources/OH-INF/i18n/tradfri.properties
Labels: translation

#11507 GitHub Actions workflow improvements
  .github/scripts/maven-build
  .github/workflows/ci-build.yml
Labels: infrastructure

#11492 [miio] Add support 3 yeelights
  bundles/org.openhab.binding.miio/README.md
  bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/MiIoDevices.java
  bundles/org.openhab.binding.miio/src/main/resources/database/dreame.vacuum.mc1808-miot.json
  bundles/org.openhab.binding.miio/src/main/resources/database/yeelink.light.lamp1.json
Labels: enhancement

#11512 [dwdunwetter] Fixed broken link in documentation
  bundles/org.openhab.binding.dwdunwetter/README.md
Labels: documentation

#11499 [weathercompany] Fix internationalization of discovery service
  bundles/org.openhab.binding.weathercompany/src/main/java/org/openhab/binding/weathercompany/internal/WeatherCompanyHandlerFactory.java
  bundles/org.openhab.binding.weathercompany/src/main/java/org/openhab/binding/weathercompany/internal/discovery/WeatherCompanyDiscoveryService.java
Labels: translation

#11513 Suppress bnd warnings for unused imports/exports
  pom.xml
Labels: infrastructure

#11519 [hue] Fixed unicode character in translation
  bundles/org.openhab.binding.hue/src/main/resources/OH-INF/i18n/hue.properties
  bundles/org.openhab.binding.hue/src/main/resources/OH-INF/thing/LightLevelSensor.xml
Labels: bug, translation

#11522 Fix wrong build result when single add-on build fails
  .github/scripts/maven-build
Labels: infrastructure

#11528 [twitter] Extend properties file with all default translations
  bundles/org.openhab.binding.twitter/src/main/resources/OH-INF/i18n/twitter.properties
Labels: translation

#11530 [mail] Extend properties file with all default translations
  bundles/org.openhab.binding.mail/src/main/resources/OH-INF/i18n/mail.properties
  bundles/org.openhab.binding.mail/src/main/resources/OH-INF/thing/thing-types.xml
Labels: translation

#11523 Always run OSGi HTTP service on random port in itests
  itests/itest-common.bndrun
  itests/org.openhab.binding.feed.tests/itest.bndrun
  itests/org.openhab.binding.feed.tests/pom.xml
  itests/org.openhab.binding.mielecloud.tests/itest.bndrun
  itests/org.openhab.binding.mielecloud.tests/pom.xml
  itests/pom.xml
Labels: infrastructure, test

#11216 [mqtt.homeassistant] Implement Vacuum discovery for Homeassistant MQTT
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/ComponentChannel.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/ComponentFactory.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/Vacuum.java
Labels: enhancement

#11540 [openuv] Add missing entries to the default properties file
  bundles/org.openhab.binding.openuv/src/main/resources/OH-INF/i18n/openuv.properties
Labels: translation

#11541 [weathercompany] Add missing entries to the default properties file
  bundles/org.openhab.binding.weathercompany/src/main/resources/OH-INF/i18n/weathercompany.properties
Labels: translation

#11542 [kodi] Add missing entries to the default properties file
  bundles/org.openhab.binding.kodi/src/main/resources/OH-INF/i18n/kodi.properties
Labels: translation

#11545 [avmfritz] Add missing entries to the default properties file
  bundles/org.openhab.binding.avmfritz/src/main/resources/OH-INF/i18n/avmfritz.properties
  bundles/org.openhab.binding.avmfritz/src/main/resources/OH-INF/i18n/avmfritz_de.properties
  bundles/org.openhab.binding.avmfritz/src/main/resources/OH-INF/thing/channel-types.xml
Labels: translation

#11546 [deconz] Added default i18n properties file
  bundles/org.openhab.binding.deconz/src/main/resources/OH-INF/i18n/deconz.properties
  bundles/org.openhab.binding.deconz/src/main/resources/OH-INF/i18n/deconz_de.properties
Labels: translation

#11547 [openhabcloud] Added default i18n properties file
  bundles/org.openhab.io.openhabcloud/src/main/java/org/openhab/io/openhabcloud/internal/CloudService.java
  bundles/org.openhab.io.openhabcloud/src/main/resources/OH-INF/config/config.xml
  bundles/org.openhab.io.openhabcloud/src/main/resources/OH-INF/i18n/openhabcloud.properties
Labels: translation

#11501 [hue] Internationalization of discovery results
  bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/HueThingHandlerFactory.java
  bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/discovery/HueDeviceDiscoveryService.java
  bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/HueBridgeHandler.java
  bundles/org.openhab.binding.hue/src/main/resources/OH-INF/i18n/hue.properties
Labels: translation

#11535 [hue] Factorize thing configurations
  bundles/org.openhab.binding.hue/src/main/resources/OH-INF/config/config.xml
  bundles/org.openhab.binding.hue/src/main/resources/OH-INF/i18n/hue.properties
  bundles/org.openhab.binding.hue/src/main/resources/OH-INF/i18n/hue_de.properties
  bundles/org.openhab.binding.hue/src/main/resources/OH-INF/i18n/hue_fr.properties
  bundles/org.openhab.binding.hue/src/main/resources/OH-INF/thing/CLIPGenericFlagSensor.xml
  bundles/org.openhab.binding.hue/src/main/resources/OH-INF/thing/CLIPGenericStatusSensor.xml
  bundles/org.openhab.binding.hue/src/main/resources/OH-INF/thing/ColorLight.xml
  bundles/org.openhab.binding.hue/src/main/resources/OH-INF/thing/ColorTemperatureLight.xml
  bundles/org.openhab.binding.hue/src/main/resources/OH-INF/thing/DimmableLight.xml
  bundles/org.openhab.binding.hue/src/main/resources/OH-INF/thing/DimmablePlug.xml
  bundles/org.openhab.binding.hue/src/main/resources/OH-INF/thing/DimmerSwitch.xml
  bundles/org.openhab.binding.hue/src/main/resources/OH-INF/thing/ExtendedColorLight.xml
  bundles/org.openhab.binding.hue/src/main/resources/OH-INF/thing/GeofenceSensor.xml
  bundles/org.openhab.binding.hue/src/main/resources/OH-INF/thing/Group.xml
  bundles/org.openhab.binding.hue/src/main/resources/OH-INF/thing/LightLevelSensor.xml
  bundles/org.openhab.binding.hue/src/main/resources/OH-INF/thing/OnOffLight.xml
  bundles/org.openhab.binding.hue/src/main/resources/OH-INF/thing/OnOffPlug.xml
  bundles/org.openhab.binding.hue/src/main/resources/OH-INF/thing/TapSwitch.xml
  bundles/org.openhab.binding.hue/src/main/resources/OH-INF/thing/TemperatureSensor.xml
Labels: enhancement, translation

#11511 [nuvo] Fixes protocol errors when connecting via an MPS4
  bundles/org.openhab.binding.nuvo/README.md
  bundles/org.openhab.binding.nuvo/src/main/java/org/openhab/binding/nuvo/internal/NuvoBindingConstants.java
  bundles/org.openhab.binding.nuvo/src/main/java/org/openhab/binding/nuvo/internal/communication/NuvoConnector.java
  bundles/org.openhab.binding.nuvo/src/main/java/org/openhab/binding/nuvo/internal/handler/NuvoHandler.java
Labels: bug

#11564 [deconz] Added missing translations for command options
  bundles/org.openhab.binding.deconz/src/main/resources/OH-INF/i18n/deconz.properties
Labels: translation

#11566 [feed] Added default i18n properties file
  bundles/org.openhab.binding.feed/src/main/resources/OH-INF/i18n/feed.properties
Labels: translation

#11567 [logreader] Added default i18n properties file
  bundles/org.openhab.binding.logreader/src/main/resources/OH-INF/i18n/logreader.properties
Labels: translation

#11570 [icalendar] Added default i18n properties file
  bundles/org.openhab.binding.icalendar/src/main/resources/OH-INF/i18n/icalendar.properties
Labels: translation

#11565 [chromecast] Added default i18n properties file
  bundles/org.openhab.binding.chromecast/src/main/resources/OH-INF/i18n/chromecast.properties
Labels: translation

#11563 [miio] Initial i18n properties file for Xiaomi miio binding
  bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/handler/MiIoAbstractHandler.java
  bundles/org.openhab.binding.miio/src/main/resources/OH-INF/binding/binding.xml
  bundles/org.openhab.binding.miio/src/main/resources/OH-INF/config/config.xml
  bundles/org.openhab.binding.miio/src/main/resources/OH-INF/i18n/miio.properties
Labels: translation

#11554 [phc] Fix OH3 bug and add support for multible commands
  bundles/org.openhab.binding.phc/src/main/java/org/openhab/binding/phc/internal/handler/PHCBridgeHandler.java
  bundles/org.openhab.binding.phc/src/main/resources/OH-INF/thing/channel-types.xml
Labels: bug

#11552 [hdpowerview] Secondary shade position was inverted
  bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/api/ShadePosition.java
  bundles/org.openhab.binding.hdpowerview/src/test/java/org/openhab/binding/hdpowerview/HDPowerViewJUnitTests.java
Labels: bug

#11569 [googletts] Added default i18n properties file
  bundles/org.openhab.voice.googletts/src/main/resources/OH-INF/i18n/googletts.properties
Labels: translation

#11574 [transform][map] Added default i18n properties file
  bundles/org.openhab.transform.map/src/main/resources/OH-INF/i18n/transform.properties
Labels: translation

#11532 [rfxcom] Add default translations to properties file
  bundles/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/discovery/RFXComBridgeDiscovery.java
  bundles/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/handler/RFXComBridgeHandler.java
  bundles/org.openhab.binding.rfxcom/src/main/resources/OH-INF/i18n/rfxcom.properties
  bundles/org.openhab.binding.rfxcom/src/main/resources/OH-INF/thing/RFXrec433.xml
  bundles/org.openhab.binding.rfxcom/src/main/resources/OH-INF/thing/RFXtrx315.xml
  bundles/org.openhab.binding.rfxcom/src/main/resources/OH-INF/thing/RFXtrx433.xml
  bundles/org.openhab.binding.rfxcom/src/main/resources/OH-INF/thing/bbqtemperature.xml
  bundles/org.openhab.binding.rfxcom/src/main/resources/OH-INF/thing/blinds1.xml
  bundles/org.openhab.binding.rfxcom/src/main/resources/OH-INF/thing/bridge.xml
  bundles/org.openhab.binding.rfxcom/src/main/resources/OH-INF/thing/chime.xml
  bundles/org.openhab.binding.rfxcom/src/main/resources/OH-INF/thing/current.xml
  bundles/org.openhab.binding.rfxcom/src/main/resources/OH-INF/thing/currentenergy.xml
  bundles/org.openhab.binding.rfxcom/src/main/resources/OH-INF/thing/curtain1.xml
  bundles/org.openhab.binding.rfxcom/src/main/resources/OH-INF/thing/datetime.xml
  bundles/org.openhab.binding.rfxcom/src/main/resources/OH-INF/thing/energy.xml
  bundles/org.openhab.binding.rfxcom/src/main/resources/OH-INF/thing/fan.xml
  bundles/org.openhab.binding.rfxcom/src/main/resources/OH-INF/thing/fan_falmec.xml
  bundles/org.openhab.binding.rfxcom/src/main/resources/OH-INF/thing/fan_lucci_dc.xml
  bundles/org.openhab.binding.rfxcom/src/main/resources/OH-INF/thing/fan_lucci_dc_ii.xml
  bundles/org.openhab.binding.rfxcom/src/main/resources/OH-INF/thing/fan_novy.xml
  bundles/org.openhab.binding.rfxcom/src/main/resources/OH-INF/thing/homeconfort.xml
  bundles/org.openhab.binding.rfxcom/src/main/resources/OH-INF/thing/humidity.xml
  bundles/org.openhab.binding.rfxcom/src/main/resources/OH-INF/thing/lighting1.xml
  bundles/org.openhab.binding.rfxcom/src/main/resources/OH-INF/thing/lighting2.xml
  bundles/org.openhab.binding.rfxcom/src/main/resources/OH-INF/thing/lighting4.xml
  bundles/org.openhab.binding.rfxcom/src/main/resources/OH-INF/thing/lighting5.xml
  bundles/org.openhab.binding.rfxcom/src/main/resources/OH-INF/thing/lighting6.xml
  bundles/org.openhab.binding.rfxcom/src/main/resources/OH-INF/thing/rain.xml
  bundles/org.openhab.binding.rfxcom/src/main/resources/OH-INF/thing/raw.xml
  bundles/org.openhab.binding.rfxcom/src/main/resources/OH-INF/thing/rfxsensor.xml
  bundles/org.openhab.binding.rfxcom/src/main/resources/OH-INF/thing/rfy.xml
  bundles/org.openhab.binding.rfxcom/src/main/resources/OH-INF/thing/security1.xml
  bundles/org.openhab.binding.rfxcom/src/main/resources/OH-INF/thing/security2.xml
  bundles/org.openhab.binding.rfxcom/src/main/resources/OH-INF/thing/tcpbridge.xml
  bundles/org.openhab.binding.rfxcom/src/main/resources/OH-INF/thing/temperature.xml
  bundles/org.openhab.binding.rfxcom/src/main/resources/OH-INF/thing/temperaturehumidity.xml
  bundles/org.openhab.binding.rfxcom/src/main/resources/OH-INF/thing/temperaturehumiditybarometric.xml
  bundles/org.openhab.binding.rfxcom/src/main/resources/OH-INF/thing/temperaturerain.xml
  bundles/org.openhab.binding.rfxcom/src/main/resources/OH-INF/thing/thermostat1.xml
  bundles/org.openhab.binding.rfxcom/src/main/resources/OH-INF/thing/thermostat3.xml
  bundles/org.openhab.binding.rfxcom/src/main/resources/OH-INF/thing/undecoded.xml
  bundles/org.openhab.binding.rfxcom/src/main/resources/OH-INF/thing/uv.xml
  bundles/org.openhab.binding.rfxcom/src/main/resources/OH-INF/thing/wind.xml
Labels: translation

#11153 [openhabcloud] reconnect on connection errors
  bundles/org.openhab.io.openhabcloud/pom.xml
  bundles/org.openhab.io.openhabcloud/src/main/feature/feature.xml
  bundles/org.openhab.io.openhabcloud/src/main/java/org/openhab/io/openhabcloud/internal/CloudClient.java
Labels: bug

#11575 [voicerss] Add default translations to properties file
  bundles/org.openhab.voice.voicerss/src/main/resources/OH-INF/i18n/voicerss.properties
Labels: translation

#11561 [meteoblue] Add default translations to properties file
  bundles/org.openhab.binding.meteoblue/src/main/resources/OH-INF/i18n/meteoblue.properties
  bundles/org.openhab.binding.meteoblue/src/main/resources/OH-INF/i18n/meteoblue_fr.properties
  bundles/org.openhab.binding.meteoblue/src/main/resources/OH-INF/thing/thing-types.xml
Labels: translation

#11556 [nuvo] minor README edit and move logo to openhab-docs
  bundles/org.openhab.binding.nuvo/README.md
  bundles/org.openhab.binding.nuvo/doc/nuvo_logo.png
Labels: documentation

#11373 [remoteopenhab] Add all default translations to properties file
  bundles/org.openhab.binding.remoteopenhab/src/main/java/org/openhab/binding/remoteopenhab/internal/RemoteopenhabHandlerFactory.java
  bundles/org.openhab.binding.remoteopenhab/src/main/java/org/openhab/binding/remoteopenhab/internal/discovery/RemoteopenhabDiscoveryParticipant.java
  bundles/org.openhab.binding.remoteopenhab/src/main/java/org/openhab/binding/remoteopenhab/internal/discovery/RemoteopenhabDiscoveryService.java
  bundles/org.openhab.binding.remoteopenhab/src/main/java/org/openhab/binding/remoteopenhab/internal/exceptions/RemoteopenhabException.java
  bundles/org.openhab.binding.remoteopenhab/src/main/java/org/openhab/binding/remoteopenhab/internal/handler/RemoteopenhabBridgeHandler.java
  bundles/org.openhab.binding.remoteopenhab/src/main/java/org/openhab/binding/remoteopenhab/internal/handler/RemoteopenhabThingHandler.java
  bundles/org.openhab.binding.remoteopenhab/src/main/java/org/openhab/binding/remoteopenhab/internal/rest/RemoteopenhabRestClient.java
  bundles/org.openhab.binding.remoteopenhab/src/main/resources/OH-INF/i18n/remoteopenhab.properties
Labels: translation

#11392 [sonyprojector] Allow translation of exception messages that can be d…
  bundles/org.openhab.binding.sonyprojector/src/main/java/org/openhab/binding/sonyprojector/internal/SonyProjectorException.java
  bundles/org.openhab.binding.sonyprojector/src/main/java/org/openhab/binding/sonyprojector/internal/SonyProjectorHandlerFactory.java
  bundles/org.openhab.binding.sonyprojector/src/main/java/org/openhab/binding/sonyprojector/internal/communication/SonyProjectorConnector.java
  bundles/org.openhab.binding.sonyprojector/src/main/java/org/openhab/binding/sonyprojector/internal/communication/sdcp/SonyProjectorSdcpConnector.java
  bundles/org.openhab.binding.sonyprojector/src/main/java/org/openhab/binding/sonyprojector/internal/communication/sdcp/SonyProjectorSdcpError.java
  bundles/org.openhab.binding.sonyprojector/src/main/java/org/openhab/binding/sonyprojector/internal/communication/sdcp/SonyProjectorSdcpSimuConnector.java
  bundles/org.openhab.binding.sonyprojector/src/main/java/org/openhab/binding/sonyprojector/internal/communication/serial/SonyProjectorSerialConnector.java
  bundles/org.openhab.binding.sonyprojector/src/main/java/org/openhab/binding/sonyprojector/internal/communication/serial/SonyProjectorSerialError.java
  bundles/org.openhab.binding.sonyprojector/src/main/java/org/openhab/binding/sonyprojector/internal/communication/serial/SonyProjectorSerialOverIpConnector.java
  bundles/org.openhab.binding.sonyprojector/src/main/java/org/openhab/binding/sonyprojector/internal/communication/serial/SonyProjectorSerialSimuConnector.java
  bundles/org.openhab.binding.sonyprojector/src/main/java/org/openhab/binding/sonyprojector/internal/handler/SonyProjectorHandler.java
  bundles/org.openhab.binding.sonyprojector/src/main/resources/OH-INF/i18n/sonyprojector.properties
  bundles/org.openhab.binding.sonyprojector/src/main/resources/OH-INF/i18n/sonyprojector_fr.properties
Labels: translation

#11520 Use POM packaging with index BOMs
  bom/openhab-core-index/pom.xml
  bom/runtime-index/pom.xml
  bom/test-index/pom.xml
Labels: infrastructure

#11580 [danfossairunit] Add default i18n properties file
  bundles/org.openhab.binding.danfossairunit/src/main/java/org/openhab/binding/danfossairunit/internal/Channel.java
  bundles/org.openhab.binding.danfossairunit/src/main/java/org/openhab/binding/danfossairunit/internal/DanfossAirUnitHandlerFactory.java
  bundles/org.openhab.binding.danfossairunit/src/main/java/org/openhab/binding/danfossairunit/internal/handler/DanfossAirUnitHandler.java
  bundles/org.openhab.binding.danfossairunit/src/main/resources/OH-INF/i18n/danfossairunit.properties
  bundles/org.openhab.binding.danfossairunit/src/main/resources/OH-INF/thing/thing-types.xml
Labels: translation

#11548 [nikobus] added option to set rollershutter position
  bundles/org.openhab.binding.nikobus/src/main/java/org/openhab/binding/nikobus/internal/handler/NikobusRollershutterModuleHandler.java
Labels: enhancement

#11581 [miio] support sending openclose commands
  bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/basic/CommandParameterType.java
  bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/handler/MiIoBasicHandler.java
Labels: enhancement

#11538 [jrubyscripting] JRuby scripting initial contribution
  CODEOWNERS
  bom/openhab-addons/pom.xml
  bundles/org.openhab.automation.jrubyscripting/NOTICE
  bundles/org.openhab.automation.jrubyscripting/README.md
  bundles/org.openhab.automation.jrubyscripting/pom.xml
  bundles/org.openhab.automation.jrubyscripting/src/main/feature/feature.xml
  bundles/org.openhab.automation.jrubyscripting/src/main/java/org/openhab/automation/jrubyscripting/internal/JRubyScriptEngineConfiguration.java
  bundles/org.openhab.automation.jrubyscripting/src/main/java/org/openhab/automation/jrubyscripting/internal/JRubyScriptEngineFactory.java
  bundles/org.openhab.automation.jrubyscripting/src/main/java/org/openhab/automation/jrubyscripting/internal/package-info.java
  bundles/org.openhab.automation.jrubyscripting/src/main/resources/OH-INF/config/config.xml
  bundles/org.openhab.automation.jrubyscripting/src/main/resources/OH-INF/i18n/jruby.properties
  bundles/pom.xml
Labels: new automation

#11487 [samsungtv] Fix reconnect after first connection to TV is lost
  bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/handler/SamsungTvHandler.java
  bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/service/MainTVServerService.java
  bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/service/RemoteControllerService.java
Labels: bug

#11596 [windcentrale] Add default translations
  bundles/org.openhab.binding.windcentrale/src/main/java/org/openhab/binding/windcentrale/internal/config/MillConfig.java
  bundles/org.openhab.binding.windcentrale/src/main/java/org/openhab/binding/windcentrale/internal/handler/WindcentraleHandler.java
  bundles/org.openhab.binding.windcentrale/src/main/resources/OH-INF/i18n/windcentrale.properties
  bundles/org.openhab.binding.windcentrale/src/main/resources/OH-INF/i18n/windcentrale_nl.properties
Labels: translation

#11270 [loxone] Sauna controller implementation
  bundles/org.openhab.binding.loxone/src/main/java/org/openhab/binding/loxone/internal/controls/LxControl.java
  bundles/org.openhab.binding.loxone/src/main/java/org/openhab/binding/loxone/internal/controls/LxControlFactory.java
  bundles/org.openhab.binding.loxone/src/main/java/org/openhab/binding/loxone/internal/controls/LxControlSauna.java
  bundles/org.openhab.binding.loxone/src/test/java/org/openhab/binding/loxone/internal/controls/LxControlSaunaDoorTest.java
  bundles/org.openhab.binding.loxone/src/test/java/org/openhab/binding/loxone/internal/controls/LxControlSaunaDoorVaporizerTest.java
  bundles/org.openhab.binding.loxone/src/test/java/org/openhab/binding/loxone/internal/controls/LxControlSaunaTest.java
  bundles/org.openhab.binding.loxone/src/test/java/org/openhab/binding/loxone/internal/controls/LxControlTest.java
  bundles/org.openhab.binding.loxone/src/test/resources/org/openhab/binding/loxone/internal/controls/LoxAPP3.json
Labels: enhancement

#11600 [icloud] iCloud response invalid: null (second time)
  bundles/org.openhab.binding.icloud/src/main/java/org/openhab/binding/icloud/internal/json/request/ICloudAccountDataRequest.java
Labels: bug, community approved

#11601 [myq] Fixes breaking API changes to the MyQ binding
  bundles/org.openhab.binding.myq/src/main/java/org/openhab/binding/myq/internal/MyQDiscoveryService.java
  bundles/org.openhab.binding.myq/src/main/java/org/openhab/binding/myq/internal/dto/AccountDTO.java
  bundles/org.openhab.binding.myq/src/main/java/org/openhab/binding/myq/internal/dto/AccountsDTO.java
  bundles/org.openhab.binding.myq/src/main/java/org/openhab/binding/myq/internal/dto/ActionDTO.java
  bundles/org.openhab.binding.myq/src/main/java/org/openhab/binding/myq/internal/dto/AddressDTO.java
  bundles/org.openhab.binding.myq/src/main/java/org/openhab/binding/myq/internal/dto/CountryDTO.java
  bundles/org.openhab.binding.myq/src/main/java/org/openhab/binding/myq/internal/dto/DeviceDTO.java
  bundles/org.openhab.binding.myq/src/main/java/org/openhab/binding/myq/internal/dto/DeviceStateDTO.java
  bundles/org.openhab.binding.myq/src/main/java/org/openhab/binding/myq/internal/dto/TimeZoneDTO.java
  bundles/org.openhab.binding.myq/src/main/java/org/openhab/binding/myq/internal/dto/UsersDTO.java
  bundles/org.openhab.binding.myq/src/main/java/org/openhab/binding/myq/internal/handler/MyQAccountHandler.java
  bundles/org.openhab.binding.myq/src/main/java/org/openhab/binding/myq/internal/handler/MyQGarageDoorHandler.java
  bundles/org.openhab.binding.myq/src/main/java/org/openhab/binding/myq/internal/handler/MyQLampHandler.java
Labels: bug, community approved

#11568 [miio] Move (remaining) channel details to json files
  bundles/org.openhab.binding.miio/README.md
  bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/basic/MiIoBasicChannel.java
  bundles/org.openhab.binding.miio/src/main/resources/OH-INF/thing/commonChannels.xml
  bundles/org.openhab.binding.miio/src/main/resources/database/cgllc.airmonitor.b1.json
  bundles/org.openhab.binding.miio/src/main/resources/database/cgllc.airmonitor.s1.json
  bundles/org.openhab.binding.miio/src/main/resources/database/chuangmi.plug.m1.json
  bundles/org.openhab.binding.miio/src/main/resources/database/chuangmi.plug.v1.json
  bundles/org.openhab.binding.miio/src/main/resources/database/chuangmi.plug.v2.json
  bundles/org.openhab.binding.miio/src/main/resources/database/chuangmi.plug.v3.json
  bundles/org.openhab.binding.miio/src/main/resources/database/cuco.plug.cp1-miot.json
  bundles/org.openhab.binding.miio/src/main/resources/database/dmaker.airfresh.a1.json
  bundles/org.openhab.binding.miio/src/main/resources/database/dmaker.airfresh.t2017.json
  bundles/org.openhab.binding.miio/src/main/resources/database/dmaker.fan.p5.json
  bundles/org.openhab.binding.miio/src/main/resources/database/lumi.curtain.hagl05-miot.json
  bundles/org.openhab.binding.miio/src/main/resources/database/philips.light.bceiling1.json
  bundles/org.openhab.binding.miio/src/main/resources/database/philips.light.bulb.json
  bundles/org.openhab.binding.miio/src/main/resources/database/philips.light.candle.json
  bundles/org.openhab.binding.miio/src/main/resources/database/philips.light.cbulb.json
  bundles/org.openhab.binding.miio/src/main/resources/database/philips.light.ceil-miot.json
  bundles/org.openhab.binding.miio/src/main/resources/database/philips.light.ceiling.json
  bundles/org.openhab.binding.miio/src/main/resources/database/philips.light.mono.json
  bundles/org.openhab.binding.miio/src/main/resources/database/philips.light.moonlight.json
  bundles/org.openhab.binding.miio/src/main/resources/database/philips.light.rwread.json
  bundles/org.openhab.binding.miio/src/main/resources/database/philips.light.sread1.json
  bundles/org.openhab.binding.miio/src/main/resources/database/qmi.powerstrip.v1.json
  bundles/org.openhab.binding.miio/src/main/resources/database/scishare.coffee.s1102.json
  bundles/org.openhab.binding.miio/src/main/resources/database/viomi.vacuum.v18-miot.json
  bundles/org.openhab.binding.miio/src/main/resources/database/viomi.vacuum.v8.json
  bundles/org.openhab.binding.miio/src/main/resources/database/xiaomi.aircondition.mc1-miot.json
  bundles/org.openhab.binding.miio/src/main/resources/database/yeelink.bhf1.json
  bundles/org.openhab.binding.miio/src/main/resources/database/yeelink.light.ceiling.json
  bundles/org.openhab.binding.miio/src/main/resources/database/yeelink.light.ceiling2.json
  bundles/org.openhab.binding.miio/src/main/resources/database/yeelink.light.ceiling4.json
  bundles/org.openhab.binding.miio/src/main/resources/database/yeelink.light.light15.json
  bundles/org.openhab.binding.miio/src/main/resources/database/zhimi.airmonitor.v1.json
  bundles/org.openhab.binding.miio/src/main/resources/database/zhimi.airpurifier.m1.json
  bundles/org.openhab.binding.miio/src/main/resources/database/zhimi.airpurifier.v1.json
  bundles/org.openhab.binding.miio/src/main/resources/database/zhimi.airpurifier.v6.json
  bundles/org.openhab.binding.miio/src/main/resources/database/zhimi.airpurifier.v7.json
  bundles/org.openhab.binding.miio/src/main/resources/database/zhimi.fan.za4.json
  bundles/org.openhab.binding.miio/src/main/resources/database/zhimi.humidifier.v1.json
  bundles/org.openhab.binding.miio/src/main/resources/database/zimi.powerstrip.v2.json
Labels: enhancement

#11577 [miio] add support Mi Smart Humidifier deerma.humidifier.jsq5
  bundles/org.openhab.binding.miio/README.md
  bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/MiIoDevices.java
  bundles/org.openhab.binding.miio/src/main/resources/database/deerma.humidifier.jsq5.json
Labels: enhancement

#11509 [wled] Abstract json api for better segment support
  bundles/org.openhab.binding.wled/README.md
  bundles/org.openhab.binding.wled/src/main/java/org/openhab/binding/wled/internal/WLedActions.java
  bundles/org.openhab.binding.wled/src/main/java/org/openhab/binding/wled/internal/WLedBindingConstants.java
  bundles/org.openhab.binding.wled/src/main/java/org/openhab/binding/wled/internal/WLedDiscoveryService.java
  bundles/org.openhab.binding.wled/src/main/java/org/openhab/binding/wled/internal/WLedHandler.java
  bundles/org.openhab.binding.wled/src/main/java/org/openhab/binding/wled/internal/WLedHandlerFactory.java
  bundles/org.openhab.binding.wled/src/main/java/org/openhab/binding/wled/internal/WLedHelper.java
  bundles/org.openhab.binding.wled/src/main/java/org/openhab/binding/wled/internal/WledState.java
  bundles/org.openhab.binding.wled/src/main/java/org/openhab/binding/wled/internal/api/ApiException.java
  bundles/org.openhab.binding.wled/src/main/java/org/openhab/binding/wled/internal/api/WledApi.java
  bundles/org.openhab.binding.wled/src/main/java/org/openhab/binding/wled/internal/api/WledApiFactory.java
  bundles/org.openhab.binding.wled/src/main/java/org/openhab/binding/wled/internal/api/WledApiV0110.java
  bundles/org.openhab.binding.wled/src/main/java/org/openhab/binding/wled/internal/api/WledApiV0130.java
  bundles/org.openhab.binding.wled/src/main/java/org/openhab/binding/wled/internal/api/WledApiV084.java
  bundles/org.openhab.binding.wled/src/main/resources/OH-INF/thing/thing-types.xml
Labels: enhancement

#11562 [MQTT.Homeassistant] make the mqtt.vacuum compliant
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/Vacuum.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/component/VacuumTests.java
Labels: enhancement

#11614 [Souliss] Fix T14 Typical
  bundles/org.openhab.binding.souliss/src/main/resources/OH-INF/thing/thing-types.xml
Labels: bug

#11619 [tr064] Added default i18n properties file
  bundles/org.openhab.binding.tr064/src/main/java/org/openhab/binding/tr064/internal/phonebook/PhonebookActions.java
  bundles/org.openhab.binding.tr064/src/main/resources/OH-INF/config/phonebookProfile.xml
  bundles/org.openhab.binding.tr064/src/main/resources/OH-INF/i18n/tr064.properties
  bundles/org.openhab.binding.tr064/src/main/resources/OH-INF/thing/thing-types.xml
Labels: translation

#11618 [feed] Changed pattern for DateTime channel types to be considered by i18n-tool
  bundles/org.openhab.binding.feed/src/main/resources/OH-INF/i18n/feed.properties
  bundles/org.openhab.binding.feed/src/main/resources/OH-INF/thing/thing-types.xml
Labels: translation

#11623 [googletts] Fix place holders issue
  bundles/org.openhab.voice.googletts/README.md
Labels: documentation

#11622 [nest] Fix place holders issue
  bundles/org.openhab.binding.nest/README.md
Labels: documentation

#11626 [max] Add default translation properties file for MAX!
  bundles/org.openhab.binding.max/src/main/resources/OH-INF/i18n/max.properties
Labels: translation

#11586 [amplipi] Add discovery and PA support
  bundles/org.openhab.binding.amplipi/README.md
  bundles/org.openhab.binding.amplipi/amplipi-api.yml
  bundles/org.openhab.binding.amplipi/src/gen/java/org/openhab/binding/amplipi/internal/model/Announcement.java
  bundles/org.openhab.binding.amplipi/src/gen/java/org/openhab/binding/amplipi/internal/model/GroupUpdateWithId.java
  bundles/org.openhab.binding.amplipi/src/gen/java/org/openhab/binding/amplipi/internal/model/MultiZoneUpdate.java
  bundles/org.openhab.binding.amplipi/src/gen/java/org/openhab/binding/amplipi/internal/model/SourceInfo.java
  bundles/org.openhab.binding.amplipi/src/gen/java/org/openhab/binding/amplipi/internal/model/SourceUpdateWithId.java
  bundles/org.openhab.binding.amplipi/src/gen/java/org/openhab/binding/amplipi/internal/model/ZoneUpdateWithId.java
  bundles/org.openhab.binding.amplipi/src/main/java/org/openhab/binding/amplipi/internal/AmpliPiConfiguration.java
  bundles/org.openhab.binding.amplipi/src/main/java/org/openhab/binding/amplipi/internal/AmpliPiGroupHandler.java
  bundles/org.openhab.binding.amplipi/src/main/java/org/openhab/binding/amplipi/internal/AmpliPiHandler.java
  bundles/org.openhab.binding.amplipi/src/main/java/org/openhab/binding/amplipi/internal/AmpliPiHandlerFactory.java
  bundles/org.openhab.binding.amplipi/src/main/java/org/openhab/binding/amplipi/internal/AmpliPiZoneHandler.java
  bundles/org.openhab.binding.amplipi/src/main/java/org/openhab/binding/amplipi/internal/audio/PAAudioSink.java
  bundles/org.openhab.binding.amplipi/src/main/java/org/openhab/binding/amplipi/internal/discovery/AmpliPiMDNSDiscoveryParticipant.java
  bundles/org.openhab.binding.amplipi/src/main/java/org/openhab/binding/amplipi/internal/discovery/AmpliPiZoneAndGroupDiscoveryService.java
Labels: enhancement

#11640 [avmfritz] Add representation-property to bridge type definitions
  bundles/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/discovery/AVMFritzUpnpDiscoveryParticipant.java
  bundles/org.openhab.binding.avmfritz/src/main/resources/OH-INF/thing/bridge-types.xml
Labels: bug

#11647 [linky] Few debug logs added
  bundles/org.openhab.binding.linky/src/main/java/org/openhab/binding/linky/internal/api/EnedisHttpApi.java
  bundles/org.openhab.binding.linky/src/main/java/org/openhab/binding/linky/internal/handler/LinkyHandler.java
Labels: enhancement

#11646 [transform][map] Fixed wrong i18n properties and added label of Profile
  bundles/org.openhab.transform.map/src/main/resources/OH-INF/i18n/transform.properties
Labels: translation

#11111 [Tapocontrol] Binding to control Tapo (by TP-Link) Devices
  CODEOWNERS
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.tapocontrol/NOTICE
  bundles/org.openhab.binding.tapocontrol/README.md
  bundles/org.openhab.binding.tapocontrol/pom.xml
  bundles/org.openhab.binding.tapocontrol/src/main/feature/feature.xml
  bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/TapoControlHandlerFactory.java
  bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/TapoDiscoveryService.java
  bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/api/TapoCloudConnector.java
  bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/api/TapoDeviceConnector.java
  bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/api/TapoDeviceHttpApi.java
  bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/constants/TapoBindingSettings.java
  bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/constants/TapoErrorConstants.java
  bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/constants/TapoThingConstants.java
  bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/device/TapoBridgeHandler.java
  bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/device/TapoDevice.java
  bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/device/TapoLightStrip.java
  bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/device/TapoSmartBulb.java
  bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/device/TapoSmartPlug.java
  bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/device/TapoUniversalDevice.java
  bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/helpers/MimeEncode.java
  bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/helpers/PayloadBuilder.java
  bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/helpers/TapoCipher.java
  bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/helpers/TapoCredentials.java
  bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/helpers/TapoErrorHandler.java
  bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/helpers/TapoUtils.java
  bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/structures/TapoBridgeConfiguration.java
  bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/structures/TapoDeviceConfiguration.java
  bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/structures/TapoDeviceInfo.java
  bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/structures/TapoLightEffect.java
  bundles/org.openhab.binding.tapocontrol/src/main/resources/OH-INF/binding/binding.xml
  bundles/org.openhab.binding.tapocontrol/src/main/resources/OH-INF/config/config.xml
  bundles/org.openhab.binding.tapocontrol/src/main/resources/OH-INF/thing/L510_Series.xml
  bundles/org.openhab.binding.tapocontrol/src/main/resources/OH-INF/thing/L530_Series.xml
  bundles/org.openhab.binding.tapocontrol/src/main/resources/OH-INF/thing/L900.xml
  bundles/org.openhab.binding.tapocontrol/src/main/resources/OH-INF/thing/P100.xml
  bundles/org.openhab.binding.tapocontrol/src/main/resources/OH-INF/thing/P105.xml
  bundles/org.openhab.binding.tapocontrol/src/main/resources/OH-INF/thing/bridge.xml
  bundles/org.openhab.binding.tapocontrol/src/main/resources/OH-INF/thing/channels.xml
  bundles/org.openhab.binding.tapocontrol/src/test/java/org/openhab/binding/tapocontrol/internal/api/TapoUDP.java
  bundles/org.openhab.binding.tapocontrol/src/test/java/org/openhab/binding/tapocontrol/internal/device/TapoBridgeHandler.java
  bundles/org.openhab.binding.tapocontrol/src/test/java/org/openhab/binding/tapocontrol/internal/device/TapoUniversalDevice.java
  bundles/org.openhab.binding.tapocontrol/src/test/java/org/openhab/binding/tapocontrol/internal/structures/TapoBridgeConfiguration.java
  bundles/org.openhab.binding.tapocontrol/src/test/java/org/openhab/binding/tapocontrol/internal/structures/TapoDeviceInfo.java
  bundles/org.openhab.binding.tapocontrol/src/test/java/org/openhab/binding/tapocontrol/internal/structures/TapoLightEffect.java
  bundles/org.openhab.binding.tapocontrol/src/test/resources/OH-INF/config/config.xml
  bundles/org.openhab.binding.tapocontrol/src/test/resources/OH-INF/thing/testdevice.xml
  bundles/pom.xml
Labels: new binding

#11653 [lifx] Improve InterruptedException handling
  bundles/org.openhab.binding.lifx/src/main/java/org/openhab/binding/lifx/internal/util/LifxThrottlingUtil.java
Labels: bug

#11652 Report SAT Errors with GHA Annotations
  .github/openhab-compile-problems.json
  .github/workflows/ci-build.yml
Labels: infrastructure

#11649 Use Maven 3.8.4 in GHA CI builds
  .github/workflows/ci-build.yml
Labels: infrastructure

#11650 Update bnd to 6.1.0
  itests/org.openhab.binding.astro.tests/itest.bndrun
  itests/org.openhab.binding.avmfritz.tests/itest.bndrun
  itests/org.openhab.binding.feed.tests/itest.bndrun
  itests/org.openhab.binding.hue.tests/itest.bndrun
  itests/org.openhab.binding.max.tests/itest.bndrun
  itests/org.openhab.binding.mielecloud.tests/itest.bndrun
  itests/org.openhab.binding.modbus.tests/itest.bndrun
  itests/org.openhab.binding.nest.tests/itest.bndrun
  itests/org.openhab.binding.ntp.tests/itest.bndrun
  itests/org.openhab.binding.systeminfo.tests/itest.bndrun
  itests/org.openhab.binding.tradfri.tests/itest.bndrun
  itests/org.openhab.binding.wemo.tests/itest.bndrun
  itests/org.openhab.persistence.mapdb.tests/itest.bndrun
  pom.xml
Labels: infrastructure

#11659 [miio] add new vacuum status codes
  bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/robot/StatusType.java
Labels: enhancement

#11603 [miele] Localization of state, program and phase
  bundles/org.openhab.binding.miele/README.md
  bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/DeviceMetaData.java
  bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/DeviceUtil.java
  bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/MieleBindingConstants.java
  bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/MieleHandlerFactory.java
  bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/MieleTranslationProvider.java
  bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/ApplianceChannelSelector.java
  bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/CoffeeMachineChannelSelector.java
  bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/CoffeeMachineHandler.java
  bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/DishWasherHandler.java
  bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/DishwasherChannelSelector.java
  bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/ExtendedDeviceStateListener.java
  bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/FridgeChannelSelector.java
  bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/FridgeFreezerChannelSelector.java
  bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/FridgeFreezerHandler.java
  bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/FridgeHandler.java
  bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/HobChannelSelector.java
  bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/HobHandler.java
  bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/HoodChannelSelector.java
  bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/HoodHandler.java
  bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/MieleApplianceHandler.java
  bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/MieleBridgeHandler.java
  bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/OvenChannelSelector.java
  bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/OvenHandler.java
  bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/TumbleDryerChannelSelector.java
  bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/TumbleDryerHandler.java
  bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/WashingMachineChannelSelector.java
  bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/WashingMachineHandler.java
  bundles/org.openhab.binding.miele/src/main/resources/OH-INF/i18n/miele.properties
  bundles/org.openhab.binding.miele/src/main/resources/OH-INF/i18n/miele_da.properties
  bundles/org.openhab.binding.miele/src/main/resources/OH-INF/i18n/miele_de.properties
  bundles/org.openhab.binding.miele/src/main/resources/OH-INF/i18n/miele_fr.properties
  bundles/org.openhab.binding.miele/src/main/resources/OH-INF/i18n/miele_nl.properties
  bundles/org.openhab.binding.miele/src/main/resources/OH-INF/thing/washingmachine.xml
  bundles/org.openhab.binding.miele/src/main/resources/OH-INF/thing/xgw3000.xml
  bundles/org.openhab.binding.miele/src/test/java/org/openhab/binding/miele/internal/DeviceUtilTest.java
Labels: enhancement, translation

#11624 [jsscripting] Improve docs with Actions
  bundles/org.openhab.automation.jsscripting/README.md
Labels: documentation

#10952 [anel] Initial contribution of the Anel NET-PwrCtrl binding for OH3
  CODEOWNERS
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.anel/NOTICE
  bundles/org.openhab.binding.anel/README.md
  bundles/org.openhab.binding.anel/pom.xml
  bundles/org.openhab.binding.anel/src/main/feature/feature.xml
  bundles/org.openhab.binding.anel/src/main/java/org/openhab/binding/anel/internal/AnelConfiguration.java
  bundles/org.openhab.binding.anel/src/main/java/org/openhab/binding/anel/internal/AnelHandler.java
  bundles/org.openhab.binding.anel/src/main/java/org/openhab/binding/anel/internal/AnelHandlerFactory.java
  bundles/org.openhab.binding.anel/src/main/java/org/openhab/binding/anel/internal/AnelUdpConnector.java
  bundles/org.openhab.binding.anel/src/main/java/org/openhab/binding/anel/internal/IAnelConstants.java
  bundles/org.openhab.binding.anel/src/main/java/org/openhab/binding/anel/internal/auth/AnelAuthentication.java
  bundles/org.openhab.binding.anel/src/main/java/org/openhab/binding/anel/internal/discovery/AnelDiscoveryService.java
  bundles/org.openhab.binding.anel/src/main/java/org/openhab/binding/anel/internal/state/AnelCommandHandler.java
  bundles/org.openhab.binding.anel/src/main/java/org/openhab/binding/anel/internal/state/AnelState.java
  bundles/org.openhab.binding.anel/src/main/java/org/openhab/binding/anel/internal/state/AnelStateUpdater.java
  bundles/org.openhab.binding.anel/src/main/resources/OH-INF/binding/binding.xml
  bundles/org.openhab.binding.anel/src/main/resources/OH-INF/config/config.xml
  bundles/org.openhab.binding.anel/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.anel/src/test/java/org/openhab/binding/anel/internal/AnelAuthenticationTest.java
  bundles/org.openhab.binding.anel/src/test/java/org/openhab/binding/anel/internal/AnelCommandHandlerTest.java
  bundles/org.openhab.binding.anel/src/test/java/org/openhab/binding/anel/internal/AnelStateTest.java
  bundles/org.openhab.binding.anel/src/test/java/org/openhab/binding/anel/internal/AnelStateUpdaterTest.java
  bundles/org.openhab.binding.anel/src/test/java/org/openhab/binding/anel/internal/AnelUdpConnectorTest.java
  bundles/org.openhab.binding.anel/src/test/java/org/openhab/binding/anel/internal/IAnelTestStatus.java
  bundles/pom.xml
Labels: new binding, oh1 migration

#11658 [miio] fix Error parsing miot data null for new miot devices
  bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/miot/MiotParser.java
Labels: bug

#11579 [miio] Add support Mi Fresh Air Ventilator C1-80 zhimi.airfresh.ua1
  bundles/org.openhab.binding.miio/README.md
  bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/MiIoDevices.java
  bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/miot/MiotParser.java
  bundles/org.openhab.binding.miio/src/main/resources/database/careli.fryer.maf01-miot.json
  bundles/org.openhab.binding.miio/src/main/resources/database/careli.fryer.maf02-miot.json
  bundles/org.openhab.binding.miio/src/main/resources/database/cgllc.airm.cgdn1-miot.json
  bundles/org.openhab.binding.miio/src/main/resources/database/dmaker.fan.p15-miot.json
  bundles/org.openhab.binding.miio/src/main/resources/database/dmaker.fan.p18-miot.json
  bundles/org.openhab.binding.miio/src/main/resources/database/dmaker.fan.p8-miot.json
  bundles/org.openhab.binding.miio/src/main/resources/database/dreame.vacuum.mc1808-miot.json
  bundles/org.openhab.binding.miio/src/main/resources/database/dreame.vacuum.p2008-miot.json
  bundles/org.openhab.binding.miio/src/main/resources/database/dreame.vacuum.p2156o-miot.json
  bundles/org.openhab.binding.miio/src/main/resources/database/mmgg.pet_waterer.s1-miot.json
  bundles/org.openhab.binding.miio/src/main/resources/database/mmgg.pet_waterer.s2-miot.json
  bundles/org.openhab.binding.miio/src/main/resources/database/viomi.vacuum.v18-miot.json
  bundles/org.openhab.binding.miio/src/main/resources/database/zhimi.airfresh.ua1-miot.json
  bundles/org.openhab.binding.miio/src/main/resources/database/zhimi.airpurifier.ma4-miot.json
  bundles/org.openhab.binding.miio/src/main/resources/database/zhimi.airpurifier.mb3-miot.json
  bundles/org.openhab.binding.miio/src/main/resources/database/zhimi.heater.ma3-miot.json
Labels: enhancement

#11657 [miio] add support for BT Gateway switch on chuangmi.plug.212a01
  bundles/org.openhab.binding.miio/README.md
  bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/basic/Conversions.java
  bundles/org.openhab.binding.miio/src/main/resources/database/chuangmi.plug.212a01-miot.json
  bundles/org.openhab.binding.miio/src/test/java/org/openhab/binding/miio/internal/ConversionsTest.java
Labels: enhancement
