Repository openhab/openhab-addons, pull requests merged in 2022-02, with the labels that each got.

#12182 [hue] Fixed setting wrong values for ledindication configuration
  bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/sensors/LightLevelHandler.java
  bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/sensors/TemperatureHandler.java
Labels: bug

#12157 [mqtt] Remove MQTT System Broker
  bundles/org.openhab.binding.mqtt/README.md
  bundles/org.openhab.binding.mqtt/src/main/java/org/openhab/binding/mqtt/MqttBindingConstants.java
  bundles/org.openhab.binding.mqtt/src/main/java/org/openhab/binding/mqtt/handler/SystemBrokerHandler.java
  bundles/org.openhab.binding.mqtt/src/main/java/org/openhab/binding/mqtt/internal/MqttBrokerHandlerFactory.java
  bundles/org.openhab.binding.mqtt/src/main/java/org/openhab/binding/mqtt/internal/MqttThingID.java
  bundles/org.openhab.binding.mqtt/src/main/java/org/openhab/binding/mqtt/internal/discovery/MqttServiceDiscoveryService.java
  bundles/org.openhab.binding.mqtt/src/main/resources/OH-INF/i18n/mqttbroker.properties
  bundles/org.openhab.binding.mqtt/src/main/resources/OH-INF/i18n/mqttbroker_hu.properties
  bundles/org.openhab.binding.mqtt/src/main/resources/OH-INF/i18n/mqttbroker_it.properties
  bundles/org.openhab.binding.mqtt/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.mqtt/src/test/java/org/openhab/binding/mqtt/handler/AbstractBrokerHandlerTest.java
  bundles/org.openhab.binding.mqtt/src/test/java/org/openhab/binding/mqtt/internal/discovery/ServiceDiscoveryServiceTest.java
Labels: enhancement

#12165 [daikin] Fix NPE when setting Airbase zones on startup
  bundles/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/handler/DaikinAcUnitHandler.java
  bundles/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/handler/DaikinAirbaseUnitHandler.java
Labels: bug

#12155 [voicerss] Fix and enhance the external tool to prefill the cache
  bundles/org.openhab.voice.voicerss/README.md
  bundles/org.openhab.voice.voicerss/src/main/java/org/openhab/voice/voicerss/internal/VoiceRSSAudioStream.java
  bundles/org.openhab.voice.voicerss/src/main/java/org/openhab/voice/voicerss/internal/VoiceRSSTTSService.java
  bundles/org.openhab.voice.voicerss/src/main/java/org/openhab/voice/voicerss/internal/VoiceRSSVoice.java
  bundles/org.openhab.voice.voicerss/src/main/java/org/openhab/voice/voicerss/internal/cloudapi/CachedVoiceRSSCloudImpl.java
  bundles/org.openhab.voice.voicerss/src/main/java/org/openhab/voice/voicerss/internal/cloudapi/VoiceRSSCloudAPI.java
  bundles/org.openhab.voice.voicerss/src/main/java/org/openhab/voice/voicerss/internal/cloudapi/VoiceRSSCloudImpl.java
  bundles/org.openhab.voice.voicerss/src/main/java/org/openhab/voice/voicerss/tool/CreateTTSCache.java
Labels: bug

#12184 [tesla] Introduce "allowWakeUpForCommands" option
  bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/TeslaBindingConstants.java
  bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/handler/TeslaAccountHandler.java
  bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/handler/TeslaVehicleHandler.java
  bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/throttler/ScheduledChannelThrottler.java
  bundles/org.openhab.binding.tesla/src/main/resources/OH-INF/i18n/tesla.properties
  bundles/org.openhab.binding.tesla/src/main/resources/OH-INF/thing/model3.xml
  bundles/org.openhab.binding.tesla/src/main/resources/OH-INF/thing/models.xml
  bundles/org.openhab.binding.tesla/src/main/resources/OH-INF/thing/modelx.xml
  bundles/org.openhab.binding.tesla/src/main/resources/OH-INF/thing/modely.xml
Labels: enhancement

#12152 [mqtt] Add birth and shutdown message
  bundles/org.openhab.binding.mqtt/README.md
  bundles/org.openhab.binding.mqtt/src/main/java/org/openhab/binding/mqtt/handler/BrokerHandler.java
  bundles/org.openhab.binding.mqtt/src/main/java/org/openhab/binding/mqtt/handler/BrokerHandlerConfig.java
  bundles/org.openhab.binding.mqtt/src/main/resources/OH-INF/thing/thing-types.xml
Labels: enhancement

#12194 [playstation] Clarified the part to obtain configuration info
  bundles/org.openhab.binding.playstation/README.md
Labels: documentation

#12190 [voicerss] Null annotations added on the main service class
  bundles/org.openhab.voice.voicerss/src/main/java/org/openhab/voice/voicerss/internal/VoiceRSSTTSService.java
  bundles/org.openhab.voice.voicerss/src/main/java/org/openhab/voice/voicerss/tool/CreateTTSCache.java
Labels: enhancement

#12181 [hdpowerview] Improve error handling for unknown shades and timeouts
  bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/HDPowerViewWebTargets.java
  bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/exceptions/HubShadeTimeoutException.java
  bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/handler/HDPowerViewHubHandler.java
  bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/handler/HDPowerViewShadeHandler.java
  bundles/org.openhab.binding.hdpowerview/src/main/resources/OH-INF/i18n/hdpowerview.properties
Labels: enhancement

#12205 [homekit] make network onChange method synchronized
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitImpl.java
Labels: enhancement

#12173 [hdpowerview] Update README after latest changes
  bundles/org.openhab.binding.hdpowerview/README.md
Labels: documentation

#12191 [tibber] Enhancement for websocket re-econnectivity & fix item/channel response
  bundles/org.openhab.binding.tibber/src/main/java/org/openhab/binding/tibber/internal/handler/TibberHandler.java
Labels: bug

#12148 [wemo] Improve GENA subscription reliability and error handling
  bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/discovery/WemoLinkDiscoveryService.java
  bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/handler/WemoBaseThingHandler.java
  bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/handler/WemoCoffeeHandler.java
  bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/handler/WemoCrockpotHandler.java
  bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/handler/WemoDimmerHandler.java
  bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/handler/WemoHandler.java
  bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/handler/WemoHolmesHandler.java
  bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/handler/WemoInsightHandler.java
  bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/handler/WemoLightHandler.java
  bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/handler/WemoMakerHandler.java
  bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/http/WemoHttpCall.java
  itests/org.openhab.binding.wemo.tests/src/main/java/org/openhab/binding/wemo/internal/discovery/test/WemoLinkDiscoveryServiceOSGiTest.java
  itests/org.openhab.binding.wemo.tests/src/main/java/org/openhab/binding/wemo/internal/handler/test/WemoHandlerOSGiTest.java
  itests/org.openhab.binding.wemo.tests/src/main/java/org/openhab/binding/wemo/internal/handler/test/WemoLightHandlerOSGiTest.java
  itests/org.openhab.binding.wemo.tests/src/main/java/org/openhab/binding/wemo/internal/handler/test/WemoMakerHandlerOSGiTest.java
Labels: enhancement

#9327 [herzborg] Herzborg binding
  CODEOWNERS
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.herzborg/NOTICE
  bundles/org.openhab.binding.herzborg/README.md
  bundles/org.openhab.binding.herzborg/pom.xml
  bundles/org.openhab.binding.herzborg/src/main/feature/feature.xml
  bundles/org.openhab.binding.herzborg/src/main/java/org/openhab/binding/herzborg/internal/Bus.java
  bundles/org.openhab.binding.herzborg/src/main/java/org/openhab/binding/herzborg/internal/BusHandler.java
  bundles/org.openhab.binding.herzborg/src/main/java/org/openhab/binding/herzborg/internal/CurtainConfiguration.java
  bundles/org.openhab.binding.herzborg/src/main/java/org/openhab/binding/herzborg/internal/CurtainHandler.java
  bundles/org.openhab.binding.herzborg/src/main/java/org/openhab/binding/herzborg/internal/HerzborgBindingConstants.java
  bundles/org.openhab.binding.herzborg/src/main/java/org/openhab/binding/herzborg/internal/HerzborgHandlerFactory.java
  bundles/org.openhab.binding.herzborg/src/main/java/org/openhab/binding/herzborg/internal/SerialBus.java
  bundles/org.openhab.binding.herzborg/src/main/java/org/openhab/binding/herzborg/internal/SerialBusConfiguration.java
  bundles/org.openhab.binding.herzborg/src/main/java/org/openhab/binding/herzborg/internal/SerialBusHandler.java
  bundles/org.openhab.binding.herzborg/src/main/java/org/openhab/binding/herzborg/internal/dto/HerzborgProtocol.java
  bundles/org.openhab.binding.herzborg/src/main/resources/OH-INF/binding/binding.xml
  bundles/org.openhab.binding.herzborg/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/pom.xml
Labels: new binding

#12212 [siemenrds] Update in ReadMe about getting an API key
  bundles/org.openhab.binding.siemensrds/README.md
Labels: documentation

#12168 [jinja] Update README.md
  bundles/org.openhab.transform.jinja/README.md
Labels: documentation

#12211 [ojelectronics] Fixing Issue if server returns not 200 while signing in
  bundles/org.openhab.binding.ojelectronics/src/main/java/org/openhab/binding/ojelectronics/internal/services/SignInService.java
Labels: bug

#12214 [hdpowerview] Eliminate risk of bad firmware response breaking shade/scene updates
  bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/handler/HDPowerViewHubHandler.java
Labels: enhancement

#12215 [wemo] Fix already configured devices in inbox
  bundles/org.openhab.binding.wemo/src/main/resources/OH-INF/config/config.xml
  bundles/org.openhab.binding.wemo/src/main/resources/OH-INF/i18n/wemo.properties
  bundles/org.openhab.binding.wemo/src/main/resources/OH-INF/thing/thing-types.xml
Labels: enhancement

#12167 [mqtt.generic] Support transformationPattern for thing's availabilityTopic
  bundles/org.openhab.binding.mqtt.generic/README.md
  bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/AbstractMQTTThingHandler.java
  bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/ChannelState.java
  bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/internal/handler/GenericMQTTThingHandler.java
  bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/internal/handler/GenericThingConfiguration.java
  bundles/org.openhab.binding.mqtt.generic/src/main/resources/OH-INF/thing/generic-thing.xml
Labels: enhancement

#12124 [kostalinverter] Fix to, prevent randomly stops of binding.
  bundles/org.openhab.binding.kostalinverter/README.md
  bundles/org.openhab.binding.kostalinverter/src/main/java/org/openhab/binding/kostalinverter/internal/secondgeneration/SecondGenerationHandler.java
  bundles/org.openhab.binding.kostalinverter/src/main/java/org/openhab/binding/kostalinverter/internal/secondgeneration/SecondGenerationInverterConfig.java
  bundles/org.openhab.binding.kostalinverter/src/main/resources/OH-INF/config/SecondGeneration.xml
  bundles/org.openhab.binding.kostalinverter/src/main/resources/OH-INF/thing/Channels.xml
Labels: bug

#12217 [danfossairunit] Fix already configured units in inbox
  bundles/org.openhab.binding.danfossairunit/src/main/resources/OH-INF/thing/thing-types.xml
Labels: bug

#12223 [deconz] Prevent Null Pointer Exception if socket connection is broken
  bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/netutils/WebSocketConnection.java
Labels: bug

#12225 [jdbc] Fixed ClassCastException for ColorItem / HSBType
  bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/db/JdbcBaseDAO.java
  bundles/org.openhab.persistence.jdbc/src/test/java/org/openhab/persistence/jdbc/db/JdbcBaseDAOTest.java
Labels: bug

#12192 [homematic] Remove state description step size handling
  bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/communicator/virtual/DisplayTextVirtualDatapoint.java
  bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/model/HmDatapoint.java
  bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/type/HomematicTypeGeneratorImpl.java
Labels: bug

#12047 [jrubyscripting] convert presets from java class to ruby class
  bundles/org.openhab.automation.jrubyscripting/src/main/java/org/openhab/automation/jrubyscripting/internal/JRubyScriptEngineFactory.java
Labels: bug

#12204 [teleinfo] Refactor channel config files for Linky standard mode
  bundles/org.openhab.binding.teleinfo/src/main/resources/OH-INF/thing/common-cbemm-evo-icc-channel-types.xml
  bundles/org.openhab.binding.teleinfo/src/main/resources/OH-INF/thing/common-lsm-prod-channel-group.xml
  bundles/org.openhab.binding.teleinfo/src/main/resources/OH-INF/thing/common-lsm-three-phase-channel-group.xml
  bundles/org.openhab.binding.teleinfo/src/main/resources/OH-INF/thing/lsm-channel-group-types.xml
  bundles/org.openhab.binding.teleinfo/src/main/resources/OH-INF/thing/lsm-channel-types.xml
Labels: enhancement

#12234 [porcupineks] fix file bundle extraction on Windows and null pointer exception
  bundles/org.openhab.voice.porcupineks/src/main/java/org/openhab/voice/porcupineks/internal/PorcupineKSService.java
Labels: bug

#12237 [hdpowerview] Fix for capabilities:1 shades
  bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/database/ShadeCapabilitiesDatabase.java
  bundles/org.openhab.binding.hdpowerview/src/test/java/org/openhab/binding/hdpowerview/ShadePositionTest.java
Labels: bug

#10972 [openweathermap] Semantics added to channel types
  bundles/org.openhab.binding.openweathermap/src/main/resources/OH-INF/thing/channel-types.xml
Labels: enhancement

#12161 [watsonstt] initial contribution
  CODEOWNERS
  bom/openhab-addons/pom.xml
  bundles/org.openhab.voice.watsonstt/NOTICE
  bundles/org.openhab.voice.watsonstt/README.md
  bundles/org.openhab.voice.watsonstt/pom.xml
  bundles/org.openhab.voice.watsonstt/src/main/feature/feature.xml
  bundles/org.openhab.voice.watsonstt/src/main/java/org/openhab/voice/watsonstt/internal/WatsonSTTConfiguration.java
  bundles/org.openhab.voice.watsonstt/src/main/java/org/openhab/voice/watsonstt/internal/WatsonSTTConstants.java
  bundles/org.openhab.voice.watsonstt/src/main/java/org/openhab/voice/watsonstt/internal/WatsonSTTService.java
  bundles/org.openhab.voice.watsonstt/src/main/resources/OH-INF/config/config.xml
  bundles/org.openhab.voice.watsonstt/src/main/resources/OH-INF/i18n/watsonstt.properties
  bundles/pom.xml
Labels: new voice

#12242 [mqtt.homie] remove unused constants in tests
  bundles/org.openhab.binding.mqtt.homie/src/test/java/org/openhab/binding/mqtt/homie/internal/handler/ThingChannelConstants.java
Labels: enhancement

#12243 [insteon] Prevent null values from being inferred when printing to console
  bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/handler/InsteonNetworkHandler.java
Labels: enhancement

#11100 [OmniLink] Add semantic tags to channels
  bundles/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/internal/OmnilinkBindingConstants.java
  bundles/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/internal/handler/OmnilinkBridgeHandler.java
  bundles/org.openhab.binding.omnilink/src/main/resources/OH-INF/i18n/omnilink.properties
  bundles/org.openhab.binding.omnilink/src/main/resources/OH-INF/thing/area.xml
  bundles/org.openhab.binding.omnilink/src/main/resources/OH-INF/thing/audio-source.xml
  bundles/org.openhab.binding.omnilink/src/main/resources/OH-INF/thing/audio-zone.xml
  bundles/org.openhab.binding.omnilink/src/main/resources/OH-INF/thing/bridge.xml
  bundles/org.openhab.binding.omnilink/src/main/resources/OH-INF/thing/button.xml
  bundles/org.openhab.binding.omnilink/src/main/resources/OH-INF/thing/humidity-sensor.xml
  bundles/org.openhab.binding.omnilink/src/main/resources/OH-INF/thing/lock.xml
  bundles/org.openhab.binding.omnilink/src/main/resources/OH-INF/thing/temp-sensor.xml
  bundles/org.openhab.binding.omnilink/src/main/resources/OH-INF/thing/thermostat.xml
  bundles/org.openhab.binding.omnilink/src/main/resources/OH-INF/thing/unit.xml
  bundles/org.openhab.binding.omnilink/src/main/resources/OH-INF/thing/zone.xml
Labels: enhancement, (potentially) not backward compatible

#10977 [hue] Semantics added to channel types
  bundles/org.openhab.binding.hue/src/main/resources/OH-INF/thing/channels.xml
Labels: enhancement

#11835 [fronius] Added Ohmpilot thing and channel realpowersum for thing meter
  bundles/org.openhab.binding.fronius/README.md
  bundles/org.openhab.binding.fronius/src/main/java/org/openhab/binding/fronius/internal/FroniusBindingConstants.java
  bundles/org.openhab.binding.fronius/src/main/java/org/openhab/binding/fronius/internal/FroniusHandlerFactory.java
  bundles/org.openhab.binding.fronius/src/main/java/org/openhab/binding/fronius/internal/api/OhmpilotRealtimeBodyDTO.java
  bundles/org.openhab.binding.fronius/src/main/java/org/openhab/binding/fronius/internal/api/OhmpilotRealtimeBodyDataDTO.java
  bundles/org.openhab.binding.fronius/src/main/java/org/openhab/binding/fronius/internal/api/OhmpilotRealtimeDetailsDTO.java
  bundles/org.openhab.binding.fronius/src/main/java/org/openhab/binding/fronius/internal/api/OhmpilotRealtimeResponseDTO.java
  bundles/org.openhab.binding.fronius/src/main/java/org/openhab/binding/fronius/internal/handler/FroniusMeterHandler.java
  bundles/org.openhab.binding.fronius/src/main/java/org/openhab/binding/fronius/internal/handler/FroniusOhmpilotHandler.java
  bundles/org.openhab.binding.fronius/src/main/resources/OH-INF/i18n/fronius.properties
  bundles/org.openhab.binding.fronius/src/main/resources/OH-INF/thing/thing-types.xml
Labels: enhancement

#12248 [deconz] Reduce log level for messages received for unconfigured devices
  bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/netutils/WebSocketConnection.java
Labels: enhancement

#12246 [OmniLink] Refactor parts of code
  bundles/org.openhab.binding.omnilink/README.md
  bundles/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/internal/OmnilinkBindingConstants.java
  bundles/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/internal/handler/AudioSourceHandler.java
  bundles/org.openhab.binding.omnilink/src/main/resources/OH-INF/thing/bridge.xml
Labels: enhancement, (potentially) not backward compatible

#12245 [deconz] Fix unreachable lights and sensors being marked as GONE
  bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/handler/LightThingHandler.java
  bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/handler/SensorBaseThingHandler.java
  bundles/org.openhab.binding.deconz/src/main/resources/OH-INF/i18n/deconz.properties
Labels: bug

#12146 [guntamatic] Added 'biosmart' and 'generic' thingtype, robustness improvements on control interface
  bundles/org.openhab.binding.guntamatic/README.md
  bundles/org.openhab.binding.guntamatic/src/main/java/org/openhab/binding/guntamatic/internal/GuntamaticBindingConstants.java
  bundles/org.openhab.binding.guntamatic/src/main/java/org/openhab/binding/guntamatic/internal/GuntamaticHandler.java
  bundles/org.openhab.binding.guntamatic/src/main/java/org/openhab/binding/guntamatic/internal/GuntamaticHandlerFactory.java
  bundles/org.openhab.binding.guntamatic/src/main/resources/OH-INF/i18n/guntamatic.properties
  bundles/org.openhab.binding.guntamatic/src/main/resources/OH-INF/thing/thing-types.xml
Labels: enhancement

#12259 [hdpowerview] Fix regression when bridge is offline while initializing child things
  bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/handler/HDPowerViewRepeaterHandler.java
  bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/handler/HDPowerViewShadeHandler.java
Labels: bug

#12151 [ipobserver] Add support for WiFi version and push based method.
  bundles/org.openhab.binding.ipobserver/README.md
  bundles/org.openhab.binding.ipobserver/src/main/java/org/openhab/binding/ipobserver/internal/IpObserverBindingConstants.java
  bundles/org.openhab.binding.ipobserver/src/main/java/org/openhab/binding/ipobserver/internal/IpObserverConfiguration.java
  bundles/org.openhab.binding.ipobserver/src/main/java/org/openhab/binding/ipobserver/internal/IpObserverHandler.java
  bundles/org.openhab.binding.ipobserver/src/main/java/org/openhab/binding/ipobserver/internal/IpObserverHandlerFactory.java
  bundles/org.openhab.binding.ipobserver/src/main/java/org/openhab/binding/ipobserver/internal/IpObserverUpdateReceiver.java
  bundles/org.openhab.binding.ipobserver/src/main/resources/OH-INF/i18n/ipobserver.properties
  bundles/org.openhab.binding.ipobserver/src/main/resources/OH-INF/thing/thing-types.xml
Labels: enhancement

#12272 [feican] Add semantic tags on channel color_temperature
  bundles/org.openhab.binding.feican/src/main/resources/OH-INF/thing/channels.xml
Labels: enhancement

#12266 [shelly] Category added to channel type sensorHumidity
  bundles/org.openhab.binding.shelly/src/main/resources/OH-INF/thing/sensor.xml
Labels: enhancement

#12268 [max] Use defined semantic tags
  bundles/org.openhab.binding.max/src/main/resources/OH-INF/thing/thing-types.xml
Labels: bug

#12275 [hydrawise] Support unused zones
  bundles/org.openhab.binding.hydrawise/src/main/java/org/openhab/binding/hydrawise/internal/handler/HydrawiseControllerHandler.java
Labels: bug

#12264 Replace unknown category DimmableLight by Light
  bundles/org.openhab.binding.bigassfan/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.cbus/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.cm11a/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.dmx/src/main/resources/OH-INF/thing/channels.xml
  bundles/org.openhab.binding.enocean/src/main/resources/OH-INF/thing/channels.xml
  bundles/org.openhab.binding.enocean/src/main/resources/OH-INF/thing/gernericChannels.xml
  bundles/org.openhab.binding.freebox/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.innogysmarthome/src/main/resources/OH-INF/thing/channels.xml
  bundles/org.openhab.binding.lifx/src/main/resources/OH-INF/thing/channel.xml
  bundles/org.openhab.binding.lutron/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.mihome/src/main/resources/OH-INF/thing/channel.xml
  bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/thing/channels.xml
  bundles/org.openhab.binding.shelly/src/main/resources/OH-INF/thing/lights.xml
  bundles/org.openhab.binding.shelly/src/main/resources/OH-INF/thing/relay.xml
  bundles/org.openhab.binding.smartthings/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.souliss/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.velbus/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.wemo/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.wled/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.yeelight/src/main/resources/OH-INF/thing/channels.xml
Labels: bug

#12274 [lifx] Cleanup semantic tags
  bundles/org.openhab.binding.lifx/src/main/resources/OH-INF/thing/channel.xml
Labels: bug

#12265 [dmx] Fix tags for channel color_temperature
  bundles/org.openhab.binding.dmx/src/main/resources/OH-INF/thing/channels.xml
Labels: bug

#12269 [souliss] Fix semantic tags
  bundles/org.openhab.binding.souliss/src/main/resources/OH-INF/thing/thing-types.xml
Labels: bug

#12277 [danfossairunit] Use system channel types for humidity and outdoor temperature
  bundles/org.openhab.binding.danfossairunit/src/main/resources/OH-INF/i18n/danfossairunit.properties
  bundles/org.openhab.binding.danfossairunit/src/main/resources/OH-INF/thing/thing-types.xml
Labels: enhancement

#12282 [souliss] Remove tags from channel type power
  bundles/org.openhab.binding.souliss/src/main/resources/OH-INF/thing/thing-types.xml
Labels: bug

#12284 [sagercaster] Cleanup semantic tags
  bundles/org.openhab.binding.sagercaster/src/main/resources/OH-INF/thing/thing-types.xml
Labels: bug

#12283 [sonyprojector] Fix tags for channel type powerstate
  bundles/org.openhab.binding.sonyprojector/src/main/resources/OH-INF/thing/channels.xml
Labels: enhancement

#12285 [openweathermap] Cleanup semantic tags
  bundles/org.openhab.binding.openweathermap/src/main/resources/OH-INF/thing/channel-types.xml
Labels: bug

#12286 [vigicrues] Cleanup semantic tags
  bundles/org.openhab.binding.vigicrues/src/main/resources/OH-INF/thing/thing-types.xml
Labels: bug

#12287 [deconz] Cleanup semantic tags
  bundles/org.openhab.binding.deconz/src/main/resources/OH-INF/thing/group-thing-types.xml
  bundles/org.openhab.binding.deconz/src/main/resources/OH-INF/thing/light-thing-types.xml
Labels: bug

#12289 [millheat] Cleanup semantic tags
  bundles/org.openhab.binding.millheat/src/main/resources/OH-INF/thing/channels.xml
Labels: bug

#12290 [airquality] Cleanup semantic tags
  bundles/org.openhab.binding.airquality/src/main/resources/OH-INF/thing/thing-types.xml
Labels: bug

#12288 [omnilink] Removed tags from channel type lock_switch
  bundles/org.openhab.binding.omnilink/src/main/resources/OH-INF/thing/lock.xml
Labels: bug

#12292 Fixed modbus integration tests
  itests/org.openhab.binding.modbus.tests/src/main/java/org/openhab/binding/modbus/tests/ModbusDataHandlerTest.java
Labels: test

#12255 [fronius] Fix communication errors by retrying failed http requests
  bundles/org.openhab.binding.fronius/pom.xml
  bundles/org.openhab.binding.fronius/src/main/java/org/openhab/binding/fronius/internal/FroniusCommunicationException.java
  bundles/org.openhab.binding.fronius/src/main/java/org/openhab/binding/fronius/internal/FroniusHandlerFactory.java
  bundles/org.openhab.binding.fronius/src/main/java/org/openhab/binding/fronius/internal/FroniusHttpUtil.java
  bundles/org.openhab.binding.fronius/src/main/java/org/openhab/binding/fronius/internal/handler/FroniusBaseThingHandler.java
  bundles/org.openhab.binding.fronius/src/main/java/org/openhab/binding/fronius/internal/handler/FroniusBridgeHandler.java
  bundles/org.openhab.binding.fronius/src/main/java/org/openhab/binding/fronius/internal/handler/FroniusMeterHandler.java
  bundles/org.openhab.binding.fronius/src/main/java/org/openhab/binding/fronius/internal/handler/FroniusOhmpilotHandler.java
  bundles/org.openhab.binding.fronius/src/main/java/org/openhab/binding/fronius/internal/handler/FroniusSymoInverterHandler.java
  bundles/org.openhab.binding.fronius/src/main/resources/OH-INF/thing/bridge.xml
Labels: bug

#12261 [bluetooth.airthings] Catch all exceptions in a scheduled task to prevent future executions from being suppressed
  bundles/org.openhab.binding.bluetooth.airthings/src/main/java/org/openhab/binding/bluetooth/airthings/internal/AbstractAirthingsHandler.java
Labels: bug

#12239 [daikin] Fix communication errors by retrying failed http requests
  bundles/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/DaikinWebTargets.java
  bundles/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/api/BasicInfo.java
  bundles/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/api/ControlInfo.java
  bundles/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/api/EnergyInfoDayAndWeek.java
  bundles/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/api/EnergyInfoYear.java
  bundles/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/api/InfoParser.java
  bundles/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/api/SensorInfo.java
  bundles/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/api/airbase/AirbaseBasicInfo.java
  bundles/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/api/airbase/AirbaseControlInfo.java
  bundles/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/api/airbase/AirbaseModelInfo.java
  bundles/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/api/airbase/AirbaseZoneInfo.java
  bundles/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/discovery/DaikinACUnitDiscoveryService.java
  bundles/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/handler/DaikinAcUnitHandler.java
  bundles/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/handler/DaikinAirbaseUnitHandler.java
  bundles/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/handler/DaikinBaseHandler.java
Labels: enhancement

#12297 [amplipi] Add support for incremental volume control
  bundles/org.openhab.binding.amplipi/src/main/java/org/openhab/binding/amplipi/internal/AmpliPiBindingConstants.java
  bundles/org.openhab.binding.amplipi/src/main/java/org/openhab/binding/amplipi/internal/AmpliPiGroupHandler.java
  bundles/org.openhab.binding.amplipi/src/main/java/org/openhab/binding/amplipi/internal/AmpliPiUtils.java
  bundles/org.openhab.binding.amplipi/src/main/java/org/openhab/binding/amplipi/internal/AmpliPiZoneHandler.java
  bundles/org.openhab.binding.amplipi/src/main/resources/OH-INF/thing/thing-types.xml
Labels: enhancement

#12293 [homekit] mark item dirty only if it has homekit metadata
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitChangeListener.java
Labels: bug

#12322 Update README.md
  bundles/org.openhab.binding.goecharger/README.md
Labels: documentation

#12313 [jdbc] Catch exception in case of connection to database failed during activation of service
  bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/JdbcMapper.java
Labels: bug

#12308 [hdpowerview] Add support for setting repeater LED color and brightness
  bundles/org.openhab.binding.hdpowerview/README.md
  bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/HDPowerViewBindingConstants.java
  bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/HDPowerViewWebTargets.java
  bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/api/Color.java
  bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/api/requests/RepeaterColor.java
  bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/api/responses/RepeaterData.java
  bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/handler/HDPowerViewRepeaterHandler.java
  bundles/org.openhab.binding.hdpowerview/src/main/resources/OH-INF/i18n/hdpowerview.properties
  bundles/org.openhab.binding.hdpowerview/src/main/resources/OH-INF/thing/thing-types.xml
Labels: enhancement

#12300 [daikin] Add the ability to disable background discovery
  bundles/org.openhab.binding.daikin/README.md
  bundles/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/discovery/DaikinACUnitDiscoveryService.java
Labels: enhancement

#12249 [voskstt] initial contribution
  CODEOWNERS
  bom/openhab-addons/pom.xml
  bundles/org.openhab.voice.voskstt/NOTICE
  bundles/org.openhab.voice.voskstt/README.md
  bundles/org.openhab.voice.voskstt/pom.xml
  bundles/org.openhab.voice.voskstt/src/main/feature/feature.xml
  bundles/org.openhab.voice.voskstt/src/main/java/org/openhab/voice/voskstt/internal/VoskSTTConfiguration.java
  bundles/org.openhab.voice.voskstt/src/main/java/org/openhab/voice/voskstt/internal/VoskSTTConstants.java
  bundles/org.openhab.voice.voskstt/src/main/java/org/openhab/voice/voskstt/internal/VoskSTTService.java
  bundles/org.openhab.voice.voskstt/src/main/resources/OH-INF/config/config.xml
  bundles/org.openhab.voice.voskstt/src/main/resources/OH-INF/i18n/voskstt.properties
  bundles/pom.xml
Labels: new voice

#12314 [openweathermap] Call Thread.currentThread().interrupt() on InterruptedException
  bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/connection/OpenWeatherMapConnection.java
  bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/handler/AbstractOpenWeatherMapHandler.java
Labels: bug

#12318 [watsonstt] lazy abort
  bundles/org.openhab.voice.watsonstt/src/main/java/org/openhab/voice/watsonstt/internal/WatsonSTTService.java
Labels: enhancement

#12328 [mqtt] Add default translations
  bundles/org.openhab.binding.mqtt.espmilighthub/src/main/resources/OH-INF/i18n/mqtt.properties
  bundles/org.openhab.binding.mqtt.generic/src/main/resources/OH-INF/i18n/mqtt.properties
  bundles/org.openhab.binding.mqtt.generic/src/main/resources/OH-INF/i18n/mqttbroker_de.properties
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/resources/OH-INF/i18n/mqtt.properties
  bundles/org.openhab.binding.mqtt.homie/src/main/resources/OH-INF/i18n/mqtt.properties
  bundles/org.openhab.binding.mqtt/src/main/resources/OH-INF/i18n/mqtt.properties
Labels: translation

#12329 [bluetooth] Add missing default translations
  bundles/org.openhab.binding.bluetooth.airthings/src/main/resources/OH-INF/i18n/bluetooth.properties
  bundles/org.openhab.binding.bluetooth.am43/src/main/resources/OH-INF/i18n/bluetooth.properties
  bundles/org.openhab.binding.bluetooth.bluegiga/src/main/resources/OH-INF/i18n/bluetooth.properties
  bundles/org.openhab.binding.bluetooth.bluez/src/main/resources/OH-INF/i18n/bluetooth.properties
  bundles/org.openhab.binding.bluetooth.blukii/src/main/resources/OH-INF/i18n/bluetooth.properties
  bundles/org.openhab.binding.bluetooth.daikinmadoka/src/main/resources/OH-INF/i18n/bluetooth.properties
  bundles/org.openhab.binding.bluetooth.enoceanble/src/main/resources/OH-INF/i18n/bluetooth.properties
  bundles/org.openhab.binding.bluetooth.generic/src/main/resources/OH-INF/i18n/bluetooth.properties
  bundles/org.openhab.binding.bluetooth.govee/src/main/resources/OH-INF/i18n/bluetooth.properties
  bundles/org.openhab.binding.bluetooth.roaming/src/main/resources/OH-INF/i18n/bluetooth.properties
  bundles/org.openhab.binding.bluetooth.ruuvitag/src/main/resources/OH-INF/i18n/bluetooth.properties
Labels: translation

#9234 [flicbutton] Initial contribution FlicButton Binding
  CODEOWNERS
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.flicbutton/NOTICE
  bundles/org.openhab.binding.flicbutton/README.md
  bundles/org.openhab.binding.flicbutton/pom.xml
  bundles/org.openhab.binding.flicbutton/src/3rdparty/LICENSE
  bundles/org.openhab.binding.flicbutton/src/3rdparty/java/io/flic/fliclib/javaclient/BatteryStatusListener.java
  bundles/org.openhab.binding.flicbutton/src/3rdparty/java/io/flic/fliclib/javaclient/Bdaddr.java
  bundles/org.openhab.binding.flicbutton/src/3rdparty/java/io/flic/fliclib/javaclient/ButtonConnectionChannel.java
  bundles/org.openhab.binding.flicbutton/src/3rdparty/java/io/flic/fliclib/javaclient/ButtonScanner.java
  bundles/org.openhab.binding.flicbutton/src/3rdparty/java/io/flic/fliclib/javaclient/FlicClient.java
  bundles/org.openhab.binding.flicbutton/src/3rdparty/java/io/flic/fliclib/javaclient/GeneralCallbacks.java
  bundles/org.openhab.binding.flicbutton/src/3rdparty/java/io/flic/fliclib/javaclient/GetButtonInfoResponseCallback.java
  bundles/org.openhab.binding.flicbutton/src/3rdparty/java/io/flic/fliclib/javaclient/GetInfoResponseCallback.java
  bundles/org.openhab.binding.flicbutton/src/3rdparty/java/io/flic/fliclib/javaclient/Packets.java
  bundles/org.openhab.binding.flicbutton/src/3rdparty/java/io/flic/fliclib/javaclient/ScanWizard.java
  bundles/org.openhab.binding.flicbutton/src/3rdparty/java/io/flic/fliclib/javaclient/StreamUtils.java
  bundles/org.openhab.binding.flicbutton/src/3rdparty/java/io/flic/fliclib/javaclient/TimerTask.java
  bundles/org.openhab.binding.flicbutton/src/3rdparty/java/io/flic/fliclib/javaclient/enums/BdAddrType.java
  bundles/org.openhab.binding.flicbutton/src/3rdparty/java/io/flic/fliclib/javaclient/enums/BluetoothControllerState.java
  bundles/org.openhab.binding.flicbutton/src/3rdparty/java/io/flic/fliclib/javaclient/enums/ClickType.java
  bundles/org.openhab.binding.flicbutton/src/3rdparty/java/io/flic/fliclib/javaclient/enums/ConnectionStatus.java
  bundles/org.openhab.binding.flicbutton/src/3rdparty/java/io/flic/fliclib/javaclient/enums/CreateConnectionChannelError.java
  bundles/org.openhab.binding.flicbutton/src/3rdparty/java/io/flic/fliclib/javaclient/enums/DisconnectReason.java
  bundles/org.openhab.binding.flicbutton/src/3rdparty/java/io/flic/fliclib/javaclient/enums/LatencyMode.java
  bundles/org.openhab.binding.flicbutton/src/3rdparty/java/io/flic/fliclib/javaclient/enums/RemovedReason.java
  bundles/org.openhab.binding.flicbutton/src/3rdparty/java/io/flic/fliclib/javaclient/enums/ScanWizardResult.java
  bundles/org.openhab.binding.flicbutton/src/main/feature/feature.xml
  bundles/org.openhab.binding.flicbutton/src/main/java/org/openhab/binding/flicbutton/internal/FlicButtonBindingConstants.java
  bundles/org.openhab.binding.flicbutton/src/main/java/org/openhab/binding/flicbutton/internal/FlicButtonHandlerFactory.java
  bundles/org.openhab.binding.flicbutton/src/main/java/org/openhab/binding/flicbutton/internal/discovery/FlicButtonDiscoveryService.java
  bundles/org.openhab.binding.flicbutton/src/main/java/org/openhab/binding/flicbutton/internal/discovery/FlicSimpleclientDiscoveryServiceImpl.java
  bundles/org.openhab.binding.flicbutton/src/main/java/org/openhab/binding/flicbutton/internal/handler/ChildThingHandler.java
  bundles/org.openhab.binding.flicbutton/src/main/java/org/openhab/binding/flicbutton/internal/handler/FlicButtonBatteryLevelListener.java
  bundles/org.openhab.binding.flicbutton/src/main/java/org/openhab/binding/flicbutton/internal/handler/FlicButtonEventListener.java
  bundles/org.openhab.binding.flicbutton/src/main/java/org/openhab/binding/flicbutton/internal/handler/FlicButtonHandler.java
  bundles/org.openhab.binding.flicbutton/src/main/java/org/openhab/binding/flicbutton/internal/handler/FlicDaemonBridgeConfiguration.java
  bundles/org.openhab.binding.flicbutton/src/main/java/org/openhab/binding/flicbutton/internal/handler/FlicDaemonBridgeHandler.java
  bundles/org.openhab.binding.flicbutton/src/main/java/org/openhab/binding/flicbutton/internal/util/FlicButtonUtils.java
  bundles/org.openhab.binding.flicbutton/src/main/resources/OH-INF/binding/binding.xml
  bundles/org.openhab.binding.flicbutton/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/pom.xml
Labels: new binding

#12333 [flicbutton] Add missing i18n translations properties
  bundles/org.openhab.binding.flicbutton/src/main/resources/OH-INF/i18n/flicbutton.properties
Labels: translation

#12332 Remove some of the empty XML tag "description"
  bundles/org.openhab.binding.boschindego/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.digiplex/src/main/resources/OH-INF/thing/bridge.xml
  bundles/org.openhab.binding.folding/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.ihc/src/main/resources/OH-INF/thing/channels.xml
  bundles/org.openhab.binding.ihc/src/main/resources/OH-INF/thing/controller.xml
  bundles/org.openhab.binding.mqtt.generic/src/main/resources/OH-INF/thing/channels.xml
  bundles/org.openhab.binding.nibeheatpump/src/main/resources/OH-INF/thing/SMO40.xml
  bundles/org.openhab.binding.nibeheatpump/src/main/resources/OH-INF/thing/f1x45.xml
  bundles/org.openhab.binding.nibeheatpump/src/main/resources/OH-INF/thing/f1x55.xml
  bundles/org.openhab.binding.nibeheatpump/src/main/resources/OH-INF/thing/f470.xml
  bundles/org.openhab.binding.nibeheatpump/src/main/resources/OH-INF/thing/f750.xml
  bundles/org.openhab.binding.satel/src/main/resources/OH-INF/thing/partition.xml
  bundles/org.openhab.binding.shelly/src/main/resources/OH-INF/thing/relay.xml
  bundles/org.openhab.binding.spotify/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.venstarthermostat/src/main/resources/OH-INF/thing/thing-types.xml
Labels: enhancement

#12316 [network] Adressing issue #11503
  bundles/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/NetworkBindingConfiguration.java
  bundles/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/NetworkBindingConfigurationListener.java
  bundles/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/PresenceDetection.java
  bundles/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/SpeedTestConfiguration.java
  bundles/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/WakeOnLanPacketSender.java
  bundles/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/dhcp/DHCPPacketListenerServer.java
  bundles/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/handler/SpeedTestHandler.java
  bundles/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/utils/LatencyParser.java
  bundles/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/utils/NetworkUtils.java
  bundles/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/utils/PingResult.java
  bundles/org.openhab.binding.network/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.network/src/test/java/org/openhab/binding/network/internal/PresenceDetectionTest.java
  bundles/org.openhab.binding.network/src/test/java/org/openhab/binding/network/internal/WakeOnLanPacketSenderTest.java
  bundles/org.openhab.binding.network/src/test/java/org/openhab/binding/network/internal/dhcp/DHCPTest.java
  bundles/org.openhab.binding.network/src/test/java/org/openhab/binding/network/internal/toberemoved/cache/ExpiringCacheAsyncTest.java
  bundles/org.openhab.binding.network/src/test/java/org/openhab/binding/network/internal/toberemoved/cache/ExpiringCacheHelper.java
  bundles/org.openhab.binding.network/src/test/java/org/openhab/binding/network/internal/utils/LatencyParserTest.java
Labels: bug

#12305 [homekit] fix "No Response" issue due missing pairing information
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitChangeListener.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitImpl.java
Labels: bug

#12345 [plugwiseha] Improve cache and timeout handling
  bundles/org.openhab.binding.plugwiseha/src/main/java/org/openhab/binding/plugwiseha/internal/api/model/PlugwiseHAController.java
  bundles/org.openhab.binding.plugwiseha/src/main/java/org/openhab/binding/plugwiseha/internal/api/model/PlugwiseHAControllerRequest.java
  bundles/org.openhab.binding.plugwiseha/src/main/java/org/openhab/binding/plugwiseha/internal/api/model/dto/Locations.java
  bundles/org.openhab.binding.plugwiseha/src/main/java/org/openhab/binding/plugwiseha/internal/handler/PlugwiseHAApplianceHandler.java
  bundles/org.openhab.binding.plugwiseha/src/main/java/org/openhab/binding/plugwiseha/internal/handler/PlugwiseHABaseHandler.java
  bundles/org.openhab.binding.plugwiseha/src/main/java/org/openhab/binding/plugwiseha/internal/handler/PlugwiseHABridgeHandler.java
  bundles/org.openhab.binding.plugwiseha/src/main/java/org/openhab/binding/plugwiseha/internal/handler/PlugwiseHAZoneHandler.java
Labels: enhancement

#12348 [zoneminder] Properly handle when zm installed on root directory
  bundles/org.openhab.binding.zoneminder/README.md
  bundles/org.openhab.binding.zoneminder/src/main/java/org/openhab/binding/zoneminder/internal/handler/ZmBridgeHandler.java
Labels: bug

#12324 [daikin] Fix Special Mode and Streamer support
  bundles/org.openhab.binding.daikin/README.md
  bundles/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/DaikinBindingConstants.java
  bundles/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/DaikinWebTargets.java
  bundles/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/api/ControlInfo.java
  bundles/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/api/Enums.java
  bundles/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/handler/DaikinAcUnitHandler.java
  bundles/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/handler/DaikinBaseHandler.java
  bundles/org.openhab.binding.daikin/src/main/resources/OH-INF/i18n/daikin.properties
  bundles/org.openhab.binding.daikin/src/main/resources/OH-INF/thing/thing-types.xml
Labels: enhancement, (potentially) not backward compatible

#12302 [somfytahoma] Added support for the Hitachi Yutaki devices
  bundles/org.openhab.binding.somfytahoma/README.md
  bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/SomfyTahomaBindingConstants.java
  bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/SomfyTahomaHandlerFactory.java
  bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/discovery/SomfyTahomaItemDiscoveryService.java
  bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/handler/SomfyTahomaHitachiATWHZHandler.java
  bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/handler/SomfyTahomaHitachiATWMCHandler.java
  bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/handler/SomfyTahomaHitachiDHWHandler.java
  bundles/org.openhab.binding.somfytahoma/src/main/resources/OH-INF/i18n/somfytahoma.properties
  bundles/org.openhab.binding.somfytahoma/src/main/resources/OH-INF/thing/channels.xml
  bundles/org.openhab.binding.somfytahoma/src/main/resources/OH-INF/thing/hitachiatwhz.xml
  bundles/org.openhab.binding.somfytahoma/src/main/resources/OH-INF/thing/hitachiatwmc.xml
  bundles/org.openhab.binding.somfytahoma/src/main/resources/OH-INF/thing/hitachidhw.xml
Labels: enhancement

#12254 [mqtt.homie] handle exceptions parsing attributes
  bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/ChannelState.java
  bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/mapping/SubscribeFieldToMQTTtopic.java
  bundles/org.openhab.binding.mqtt.generic/src/test/java/org/openhab/binding/mqtt/generic/mapping/MqttTopicClassMapperTests.java
  bundles/org.openhab.binding.mqtt.homie/src/main/java/org/openhab/binding/mqtt/homie/internal/handler/HomieThingHandler.java
Labels: enhancement

#12303 [danfossairunit] Fix null annotation issues
  bundles/org.openhab.binding.danfossairunit/src/main/java/org/openhab/binding/danfossairunit/internal/discovery/DanfossAirUnitDiscoveryService.java
  bundles/org.openhab.binding.danfossairunit/src/test/java/org/openhab/binding/danfossairunit/internal/DanfossAirUnitTest.java
Labels: enhancement

#12349 [plugwiseha] Add and enhance channels
  bundles/org.openhab.binding.plugwiseha/README.md
  bundles/org.openhab.binding.plugwiseha/src/main/java/org/openhab/binding/plugwiseha/internal/PlugwiseHABindingConstants.java
  bundles/org.openhab.binding.plugwiseha/src/main/java/org/openhab/binding/plugwiseha/internal/api/model/PlugwiseHAController.java
  bundles/org.openhab.binding.plugwiseha/src/main/java/org/openhab/binding/plugwiseha/internal/api/model/dto/ActuatorFunctionalities.java
  bundles/org.openhab.binding.plugwiseha/src/main/java/org/openhab/binding/plugwiseha/internal/api/model/dto/ActuatorFunctionality.java
  bundles/org.openhab.binding.plugwiseha/src/main/java/org/openhab/binding/plugwiseha/internal/api/model/dto/ActuatorFunctionalityThermostat.java
  bundles/org.openhab.binding.plugwiseha/src/main/java/org/openhab/binding/plugwiseha/internal/api/model/dto/Location.java
  bundles/org.openhab.binding.plugwiseha/src/main/java/org/openhab/binding/plugwiseha/internal/handler/PlugwiseHAApplianceHandler.java
  bundles/org.openhab.binding.plugwiseha/src/main/java/org/openhab/binding/plugwiseha/internal/handler/PlugwiseHAZoneHandler.java
  bundles/org.openhab.binding.plugwiseha/src/main/resources/OH-INF/i18n/plugwiseha.properties
  bundles/org.openhab.binding.plugwiseha/src/main/resources/OH-INF/thing/channels.xml
  bundles/org.openhab.binding.plugwiseha/src/main/resources/OH-INF/thing/thing-types.xml
Labels: enhancement

#12360 Add Java 17 to GHA CI build matrix
  .github/workflows/ci-build.yml
  pom.xml
Labels: infrastructure

#12370 [novafinedust] Fix RFC2217 serial port in configuration
  bundles/org.openhab.binding.novafinedust/src/main/resources/OH-INF/thing/thing-types.xml
Labels: bug

#12368 [somfytahoma] added support for the Rain sensor thing
  bundles/org.openhab.binding.somfytahoma/README.md
  bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/SomfyTahomaBindingConstants.java
  bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/SomfyTahomaHandlerFactory.java
  bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/discovery/SomfyTahomaItemDiscoveryService.java
  bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/handler/SomfyTahomaRainSensorHandler.java
  bundles/org.openhab.binding.somfytahoma/src/main/resources/OH-INF/i18n/somfytahoma.properties
  bundles/org.openhab.binding.somfytahoma/src/main/resources/OH-INF/thing/rainsensor.xml
Labels: enhancement

#12366 [plugwiseha] Fix bug introduced with #12349
  bundles/org.openhab.binding.plugwiseha/src/main/java/org/openhab/binding/plugwiseha/internal/api/model/dto/ActuatorFunctionalities.java
  bundles/org.openhab.binding.plugwiseha/src/main/java/org/openhab/binding/plugwiseha/internal/api/model/dto/ActuatorFunctionality.java
  bundles/org.openhab.binding.plugwiseha/src/main/java/org/openhab/binding/plugwiseha/internal/api/model/dto/Location.java
  bundles/org.openhab.binding.plugwiseha/src/main/java/org/openhab/binding/plugwiseha/internal/handler/PlugwiseHABridgeHandler.java
  bundles/org.openhab.binding.plugwiseha/src/main/java/org/openhab/binding/plugwiseha/internal/handler/PlugwiseHAZoneHandler.java
Labels: bug

#12252 [souliss] fix t31 fire and system statuses
  bundles/org.openhab.binding.souliss/src/main/java/org/openhab/binding/souliss/internal/handler/SoulissT31Handler.java
  bundles/org.openhab.binding.souliss/src/main/resources/OH-INF/thing/thing-types.xml
Labels: enhancement, (potentially) not backward compatible

#12373 [govee] fix Govee H5102 detection
  bundles/org.openhab.binding.bluetooth.govee/src/main/java/org/openhab/binding/bluetooth/govee/internal/GoveeModel.java
  bundles/org.openhab.binding.bluetooth.govee/src/test/java/org/openhab/binding/bluetooth/govee/internal/GoveeModelTest.java
Labels: bug

#11975 [openwebnet] Fix Things synchronization at boot / reconnect
  bundles/org.openhab.binding.openwebnet/README.md
  bundles/org.openhab.binding.openwebnet/pom.xml
  bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/OpenWebNetBindingConstants.java
  bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/OpenWebNetHandlerFactory.java
  bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/handler/OpenWebNetAutomationHandler.java
  bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/handler/OpenWebNetBridgeHandler.java
  bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/handler/OpenWebNetEnergyHandler.java
  bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/handler/OpenWebNetLightingHandler.java
  bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/handler/OpenWebNetScenarioHandler.java
  bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/handler/OpenWebNetThermoregulationHandler.java
  bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/handler/OpenWebNetThingHandler.java
  bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/i18n/openwebnet.properties
Labels: bug

#12378 [openuv] Update README.md
  bundles/org.openhab.binding.openuv/README.md
Labels: documentation

#12377 [modbus] Add workaround to fix itests
  itests/org.openhab.binding.modbus.tests/src/main/java/org/openhab/binding/modbus/tests/AbstractModbusOSGiTest.java
Labels: test

#12372 [somfytahoma] changed the severity of unsuported devices logging
  bundles/org.openhab.binding.somfytahoma/README.md
  bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/discovery/SomfyTahomaItemDiscoveryService.java
Labels: enhancement

#12062 [openwebnet] adding support for central unit
  bundles/org.openhab.binding.openwebnet/README.md
  bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/OpenWebNetBindingConstants.java
  bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/discovery/OpenWebNetDeviceDiscoveryService.java
  bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/handler/OpenWebNetThermoregulationHandler.java
  bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/handler/OpenWebNetThingHandler.java
  bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/thing/BusThermoCentralUnit.xml
  bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/thing/BusThermoZone.xml
  bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/thing/channels.xml
Labels: enhancement

#12276 [nuki] Fixed configuration reload on initialization
  bundles/org.openhab.binding.nuki/src/main/java/org/openhab/binding/nuki/internal/NukiHandlerFactory.java
  bundles/org.openhab.binding.nuki/src/main/java/org/openhab/binding/nuki/internal/dataexchange/NukiApiServlet.java
  bundles/org.openhab.binding.nuki/src/main/java/org/openhab/binding/nuki/internal/handler/AbstractNukiDeviceHandler.java
  bundles/org.openhab.binding.nuki/src/main/java/org/openhab/binding/nuki/internal/handler/NukiOpenerHandler.java
  bundles/org.openhab.binding.nuki/src/main/java/org/openhab/binding/nuki/internal/handler/NukiSmartLockHandler.java
Labels: bug

#12380 [wemo] Refactor Insight Switch parser
  bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/InsightParser.java
  bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/handler/WemoInsightHandler.java
  bundles/org.openhab.binding.wemo/src/test/java/org/openhab/binding/wemo/InsightParserTest.java
Labels: enhancement

#12389 [tradfri] use serial as discovery representation property instead of host
  bundles/org.openhab.binding.tradfri/src/main/java/org/openhab/binding/tradfri/internal/discovery/TradfriDiscoveryParticipant.java
  bundles/org.openhab.binding.tradfri/src/main/resources/OH-INF/thing/thing-types.xml
  itests/org.openhab.binding.tradfri.tests/src/main/java/org/openhab/binding/tradfri/internal/discovery/TradfriDiscoveryParticipantOSGITest.java
Labels: bug

#12331 [hdpowerview] Remove unnecessary init checks and fix Thing status detail
  bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/handler/HDPowerViewHubHandler.java
  bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/handler/HDPowerViewRepeaterHandler.java
  bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/handler/HDPowerViewShadeHandler.java
  bundles/org.openhab.binding.hdpowerview/src/main/resources/OH-INF/i18n/hdpowerview.properties
Labels: enhancement
