Repository openhab/openhab-addons, pull requests merged in 2022-07, with the labels that each got.

#12955 [dali] Implement DT8 (single-channel RGB & color temperature) device type
  bundles/org.openhab.binding.dali/README.md
  bundles/org.openhab.binding.dali/src/main/java/org/openhab/binding/dali/internal/DaliBindingConstants.java
  bundles/org.openhab.binding.dali/src/main/java/org/openhab/binding/dali/internal/DaliHandlerFactory.java
  bundles/org.openhab.binding.dali/src/main/java/org/openhab/binding/dali/internal/handler/DaliDeviceHandler.java
  bundles/org.openhab.binding.dali/src/main/java/org/openhab/binding/dali/internal/handler/DaliDt8DeviceHandler.java
  bundles/org.openhab.binding.dali/src/main/java/org/openhab/binding/dali/internal/handler/DaliserverBridgeHandler.java
  bundles/org.openhab.binding.dali/src/main/java/org/openhab/binding/dali/internal/protocol/DaliAddress.java
  bundles/org.openhab.binding.dali/src/main/java/org/openhab/binding/dali/internal/protocol/DaliStandardCommand.java
  bundles/org.openhab.binding.dali/src/main/resources/OH-INF/i18n/dali.properties
  bundles/org.openhab.binding.dali/src/main/resources/OH-INF/thing/thing-types.xml
Labels: enhancement

#12989 [boschindego] Add channels for last/next cutting time
  bundles/org.openhab.binding.boschindego/README.md
  bundles/org.openhab.binding.boschindego/src/main/java/org/openhab/binding/boschindego/internal/BoschIndegoBindingConstants.java
  bundles/org.openhab.binding.boschindego/src/main/java/org/openhab/binding/boschindego/internal/BoschIndegoHandlerFactory.java
  bundles/org.openhab.binding.boschindego/src/main/java/org/openhab/binding/boschindego/internal/IndegoController.java
  bundles/org.openhab.binding.boschindego/src/main/java/org/openhab/binding/boschindego/internal/config/BoschIndegoConfiguration.java
  bundles/org.openhab.binding.boschindego/src/main/java/org/openhab/binding/boschindego/internal/dto/response/PredictiveLastCuttingResponse.java
  bundles/org.openhab.binding.boschindego/src/main/java/org/openhab/binding/boschindego/internal/dto/response/PredictiveNextCuttingResponse.java
  bundles/org.openhab.binding.boschindego/src/main/java/org/openhab/binding/boschindego/internal/handler/BoschIndegoHandler.java
  bundles/org.openhab.binding.boschindego/src/main/resources/OH-INF/i18n/boschindego.properties
  bundles/org.openhab.binding.boschindego/src/main/resources/OH-INF/thing/thing-types.xml
Labels: enhancement

#13003 [pidcontroller] Implement previous state recovery on startup
  bundles/org.openhab.automation.pidcontroller/README.md
  bundles/org.openhab.automation.pidcontroller/src/main/java/org/openhab/automation/pidcontroller/internal/handler/PIDController.java
  bundles/org.openhab.automation.pidcontroller/src/main/java/org/openhab/automation/pidcontroller/internal/handler/PIDControllerTriggerHandler.java
Labels: enhancement

#13057 Update i18n command version number
  README.md
Labels: documentation

#13060 [rotel] Add support for models M8 and S5 (Michi)
  bundles/org.openhab.binding.rotel/README.md
  bundles/org.openhab.binding.rotel/src/main/java/org/openhab/binding/rotel/internal/RotelBindingConstants.java
  bundles/org.openhab.binding.rotel/src/main/java/org/openhab/binding/rotel/internal/RotelHandlerFactory.java
  bundles/org.openhab.binding.rotel/src/main/java/org/openhab/binding/rotel/internal/RotelModel.java
  bundles/org.openhab.binding.rotel/src/main/java/org/openhab/binding/rotel/internal/handler/RotelHandler.java
  bundles/org.openhab.binding.rotel/src/main/resources/OH-INF/i18n/rotel.properties
  bundles/org.openhab.binding.rotel/src/main/resources/OH-INF/thing/m8.xml
  bundles/org.openhab.binding.rotel/src/main/resources/OH-INF/thing/s5.xml
Labels: enhancement

#13065 [boschindego] Add support for SpotMow status code
  bundles/org.openhab.binding.boschindego/README.md
  bundles/org.openhab.binding.boschindego/src/main/java/org/openhab/binding/boschindego/internal/DeviceStatus.java
  bundles/org.openhab.binding.boschindego/src/main/resources/OH-INF/i18n/boschindego.properties
  bundles/org.openhab.binding.boschindego/src/main/resources/OH-INF/thing/thing-types.xml
Labels: enhancement

#13075 [enigma2] Remove FIXMEs from translations
  bundles/org.openhab.binding.enigma2/src/main/resources/OH-INF/i18n/enigma2.properties
Labels: translation

#13073 [iaqualink] Fix to work with recent API changes to the iAqualink cloud service
  bundles/org.openhab.binding.iaqualink/src/main/java/org/openhab/binding/iaqualink/internal/api/IAqualinkClient.java
Labels: bug

#13076 [dsmr] Fix incorrect deriving of sub channel names when updating channels
  bundles/org.openhab.binding.dsmr/src/main/java/org/openhab/binding/dsmr/internal/handler/DSMRMeterHandler.java
Labels: bug

#13081 [boschindego] Optimize coexistence with mobile app/other clients
  bundles/org.openhab.binding.boschindego/src/main/java/org/openhab/binding/boschindego/internal/IndegoController.java
  bundles/org.openhab.binding.boschindego/src/main/java/org/openhab/binding/boschindego/internal/handler/BoschIndegoHandler.java
Labels: enhancement

#13071 [miele] Fix auto-update for stop channel and synchronize switch channel with appliance state
  bundles/org.openhab.binding.miele/README.md
  bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/MieleBindingConstants.java
  bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/CoffeeMachineHandler.java
  bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/DishWasherHandler.java
  bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/MieleApplianceHandler.java
  bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/OvenChannelSelector.java
  bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/OvenHandler.java
  bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/TumbleDryerHandler.java
  bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/WashingMachineHandler.java
  bundles/org.openhab.binding.miele/src/main/resources/OH-INF/thing/channeltypes.xml
Labels: enhancement

#13083 [groupepsa] Handle 'JsonSyntaxException' when parsing error messages
  bundles/org.openhab.binding.groupepsa/src/main/java/org/openhab/binding/groupepsa/internal/rest/api/GroupePSAConnectApi.java
Labels: bug

#13086 [boschindego] Fix duplicated calls during initialization
  bundles/org.openhab.binding.boschindego/src/main/java/org/openhab/binding/boschindego/internal/IndegoController.java
  bundles/org.openhab.binding.boschindego/src/main/java/org/openhab/binding/boschindego/internal/handler/BoschIndegoHandler.java
Labels: bug

#13052 [goecharger] fix data type for energy (nrg)
  bundles/org.openhab.binding.goecharger/README.md
  bundles/org.openhab.binding.goecharger/src/main/java/org/openhab/binding/goecharger/internal/api/GoEStatusResponseBaseDTO.java
  bundles/org.openhab.binding.goecharger/src/main/java/org/openhab/binding/goecharger/internal/api/GoEStatusResponseDTO.java
  bundles/org.openhab.binding.goecharger/src/main/java/org/openhab/binding/goecharger/internal/api/GoEStatusResponseV2DTO.java
  bundles/org.openhab.binding.goecharger/src/main/java/org/openhab/binding/goecharger/internal/handler/GoEChargerBaseHandler.java
  bundles/org.openhab.binding.goecharger/src/main/java/org/openhab/binding/goecharger/internal/handler/GoEChargerHandler.java
  bundles/org.openhab.binding.goecharger/src/main/java/org/openhab/binding/goecharger/internal/handler/GoEChargerV2Handler.java
Labels: bug

#13093 [mybmw] Add home-distance channel
  bundles/org.openhab.binding.mybmw/README.md
  bundles/org.openhab.binding.mybmw/src/main/java/org/openhab/binding/mybmw/internal/MyBMWConstants.java
  bundles/org.openhab.binding.mybmw/src/main/java/org/openhab/binding/mybmw/internal/MyBMWHandlerFactory.java
  bundles/org.openhab.binding.mybmw/src/main/java/org/openhab/binding/mybmw/internal/dto/properties/Coordinates.java
  bundles/org.openhab.binding.mybmw/src/main/java/org/openhab/binding/mybmw/internal/dto/properties/Location.java
  bundles/org.openhab.binding.mybmw/src/main/java/org/openhab/binding/mybmw/internal/handler/VehicleChannelHandler.java
  bundles/org.openhab.binding.mybmw/src/main/java/org/openhab/binding/mybmw/internal/handler/VehicleHandler.java
  bundles/org.openhab.binding.mybmw/src/main/java/org/openhab/binding/mybmw/internal/utils/Converter.java
  bundles/org.openhab.binding.mybmw/src/main/resources/OH-INF/i18n/mybmw.properties
  bundles/org.openhab.binding.mybmw/src/main/resources/OH-INF/thing/location-channel-group.xml
  bundles/org.openhab.binding.mybmw/src/main/resources/OH-INF/thing/location-channel-types.xml
  bundles/org.openhab.binding.mybmw/src/test/java/org/openhab/binding/mybmw/internal/dto/StatusWrapper.java
  bundles/org.openhab.binding.mybmw/src/test/java/org/openhab/binding/mybmw/internal/dto/VehicleStatusTest.java
  bundles/org.openhab.binding.mybmw/src/test/java/org/openhab/binding/mybmw/internal/handler/ChargeStatisticsTest.java
  bundles/org.openhab.binding.mybmw/src/test/java/org/openhab/binding/mybmw/internal/handler/ErrorResponseTest.java
  bundles/org.openhab.binding.mybmw/src/test/java/org/openhab/binding/mybmw/internal/handler/VehicleTests.java
  bundles/org.openhab.binding.mybmw/src/test/resources/responses/I01_REX/vehicles.json
Labels: enhancement

#13102 [hueemulation] Add default translations for module types
  bundles/org.openhab.io.hueemulation/src/main/resources/OH-INF/i18n/hueemulation.properties
Labels: translation

#13100 Hide compiler warnings for generated code
  pom.xml
Labels: infrastructure

#13098 Move Eclipse m2e configuration to a profile
  pom.xml
Labels: infrastructure

#13108 [mail] Fix sending HTML/Multipart mails
  bundles/org.openhab.binding.mail/src/main/java/org/openhab/binding/mail/internal/SMTPHandler.java
Labels: bug

#13110 [hdpowerview] Add support for shade types 31 and 33
  bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/database/ShadeCapabilitiesDatabase.java
Labels: enhancement

#13051 [mcd] Initial contribution
  CODEOWNERS
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.mcd/NOTICE
  bundles/org.openhab.binding.mcd/README.md
  bundles/org.openhab.binding.mcd/pom.xml
  bundles/org.openhab.binding.mcd/src/main/feature/feature.xml
  bundles/org.openhab.binding.mcd/src/main/java/org/openhab/binding/mcd/internal/McdBindingConstants.java
  bundles/org.openhab.binding.mcd/src/main/java/org/openhab/binding/mcd/internal/McdHandlerFactory.java
  bundles/org.openhab.binding.mcd/src/main/java/org/openhab/binding/mcd/internal/handler/McdBridgeConfiguration.java
  bundles/org.openhab.binding.mcd/src/main/java/org/openhab/binding/mcd/internal/handler/McdBridgeHandler.java
  bundles/org.openhab.binding.mcd/src/main/java/org/openhab/binding/mcd/internal/handler/SensorThingConfiguration.java
  bundles/org.openhab.binding.mcd/src/main/java/org/openhab/binding/mcd/internal/handler/SensorThingHandler.java
  bundles/org.openhab.binding.mcd/src/main/java/org/openhab/binding/mcd/internal/util/Callback.java
  bundles/org.openhab.binding.mcd/src/main/java/org/openhab/binding/mcd/internal/util/Listener.java
  bundles/org.openhab.binding.mcd/src/main/java/org/openhab/binding/mcd/internal/util/SensorEventDef.java
  bundles/org.openhab.binding.mcd/src/main/resources/OH-INF/binding/binding.xml
  bundles/org.openhab.binding.mcd/src/main/resources/OH-INF/i18n/mcd.properties
  bundles/org.openhab.binding.mcd/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.mcd/src/test/java/org/openhab/binding/mcd/internal/handler/SensorThingHandlerTest.java
  bundles/org.openhab.binding.mcd/src/test/java/org/openhab/binding/mcd/internal/util/SensorEventDefTest.java
  bundles/pom.xml
Labels: new binding

#13056 [lcn] Add shutter positioning/angle, operating hours counters, tunable white, regulator mode, beeping
  bundles/org.openhab.binding.lcn/README.md
  bundles/org.openhab.binding.lcn/src/main/java/org/openhab/binding/lcn/internal/LcnBindingConstants.java
  bundles/org.openhab.binding.lcn/src/main/java/org/openhab/binding/lcn/internal/LcnModuleActions.java
  bundles/org.openhab.binding.lcn/src/main/java/org/openhab/binding/lcn/internal/LcnModuleHandler.java
  bundles/org.openhab.binding.lcn/src/main/java/org/openhab/binding/lcn/internal/PckGatewayHandler.java
  bundles/org.openhab.binding.lcn/src/main/java/org/openhab/binding/lcn/internal/common/LcnChannelGroup.java
  bundles/org.openhab.binding.lcn/src/main/java/org/openhab/binding/lcn/internal/common/LcnDefs.java
  bundles/org.openhab.binding.lcn/src/main/java/org/openhab/binding/lcn/internal/common/PckGenerator.java
  bundles/org.openhab.binding.lcn/src/main/java/org/openhab/binding/lcn/internal/connection/AbstractConnectionState.java
  bundles/org.openhab.binding.lcn/src/main/java/org/openhab/binding/lcn/internal/connection/ConnectionStateMachine.java
  bundles/org.openhab.binding.lcn/src/main/java/org/openhab/binding/lcn/internal/connection/ConnectionStateWaitForLcnBusConnected.java
  bundles/org.openhab.binding.lcn/src/main/java/org/openhab/binding/lcn/internal/subhandler/AbstractLcnModuleRollershutterRelaySubHandler.java
  bundles/org.openhab.binding.lcn/src/main/java/org/openhab/binding/lcn/internal/subhandler/AbstractLcnModuleSubHandler.java
  bundles/org.openhab.binding.lcn/src/main/java/org/openhab/binding/lcn/internal/subhandler/LcnModuleOperatingHoursCounterSubHandler.java
  bundles/org.openhab.binding.lcn/src/main/java/org/openhab/binding/lcn/internal/subhandler/LcnModuleOutputSubHandler.java
  bundles/org.openhab.binding.lcn/src/main/java/org/openhab/binding/lcn/internal/subhandler/LcnModuleRollershutterRelayPositionSubHandler.java
  bundles/org.openhab.binding.lcn/src/main/java/org/openhab/binding/lcn/internal/subhandler/LcnModuleRollershutterRelaySlatAngleSubHandler.java
  bundles/org.openhab.binding.lcn/src/main/java/org/openhab/binding/lcn/internal/subhandler/LcnModuleRvarModeSubHandler.java
  bundles/org.openhab.binding.lcn/src/main/resources/OH-INF/i18n/lcn.properties
  bundles/org.openhab.binding.lcn/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.lcn/src/test/java/org/openhab/binding/lcn/internal/ModuleActionsTest.java
  bundles/org.openhab.binding.lcn/src/test/java/org/openhab/binding/lcn/internal/subhandler/AbstractLcnModuleRollershutterRelaySubHandlerTest.java
  bundles/org.openhab.binding.lcn/src/test/java/org/openhab/binding/lcn/internal/subhandler/AbstractTestLcnModuleSubHandler.java
  bundles/org.openhab.binding.lcn/src/test/java/org/openhab/binding/lcn/internal/subhandler/LcnModuleBinarySensorSubHandlerTest.java
  bundles/org.openhab.binding.lcn/src/test/java/org/openhab/binding/lcn/internal/subhandler/LcnModuleHostCommandSubHandlerTest.java
  bundles/org.openhab.binding.lcn/src/test/java/org/openhab/binding/lcn/internal/subhandler/LcnModuleKeyLockTableSubHandlerTest.java
  bundles/org.openhab.binding.lcn/src/test/java/org/openhab/binding/lcn/internal/subhandler/LcnModuleLogicSubHandlerTest.java
  bundles/org.openhab.binding.lcn/src/test/java/org/openhab/binding/lcn/internal/subhandler/LcnModuleOperatingHoursCounterSubHandlerTest.java
  bundles/org.openhab.binding.lcn/src/test/java/org/openhab/binding/lcn/internal/subhandler/LcnModuleOutputSubHandlerTest.java
  bundles/org.openhab.binding.lcn/src/test/java/org/openhab/binding/lcn/internal/subhandler/LcnModuleRelaySubHandlerTest.java
  bundles/org.openhab.binding.lcn/src/test/java/org/openhab/binding/lcn/internal/subhandler/LcnModuleRollershutterRelayPositionSubHandlerTest.java
  bundles/org.openhab.binding.lcn/src/test/java/org/openhab/binding/lcn/internal/subhandler/LcnModuleRollershutterRelaySlatAngleSubHandlerTest.java
  bundles/org.openhab.binding.lcn/src/test/java/org/openhab/binding/lcn/internal/subhandler/LcnModuleRvarModeSubHandlerTest.java
  bundles/org.openhab.binding.lcn/src/test/java/org/openhab/binding/lcn/internal/subhandler/LcnModuleRvarSetpointSubHandlerTest.java
  bundles/org.openhab.binding.lcn/src/test/java/org/openhab/binding/lcn/internal/subhandler/LcnModuleS0CounterSubHandlerTest.java
  bundles/org.openhab.binding.lcn/src/test/java/org/openhab/binding/lcn/internal/subhandler/LcnModuleThresholdSubHandlerTest.java
  bundles/org.openhab.binding.lcn/src/test/java/org/openhab/binding/lcn/internal/subhandler/LcnModuleVariableSubHandlerTest.java
Labels: enhancement

#13045 [mimictts] Initial contribution
  CODEOWNERS
  bom/openhab-addons/pom.xml
  bundles/org.openhab.voice.mimictts/NOTICE
  bundles/org.openhab.voice.mimictts/README.md
  bundles/org.openhab.voice.mimictts/pom.xml
  bundles/org.openhab.voice.mimictts/src/main/feature/feature.xml
  bundles/org.openhab.voice.mimictts/src/main/java/org/openhab/voice/mimic/internal/MimicConfiguration.java
  bundles/org.openhab.voice.mimictts/src/main/java/org/openhab/voice/mimic/internal/MimicTTSService.java
  bundles/org.openhab.voice.mimictts/src/main/java/org/openhab/voice/mimic/internal/MimicVoice.java
  bundles/org.openhab.voice.mimictts/src/main/java/org/openhab/voice/mimic/internal/dto/VoiceDto.java
  bundles/org.openhab.voice.mimictts/src/main/resources/OH-INF/config/config.xml
  bundles/org.openhab.voice.mimictts/src/main/resources/OH-INF/i18n/mimictts.properties
  bundles/org.openhab.voice.mimictts/src/main/resources/OH-INF/i18n/mimictts_fr.properties
  bundles/pom.xml
Labels: new voice

#13122 [homekit] fix potential null pointer exceptions
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitAccessoryFactory.java
Labels: bug

#13117 [icloud] Fixes COMMUNICATION_ERROR iCloud response invalid: null (Jul…
  bundles/org.openhab.binding.icloud/src/main/java/org/openhab/binding/icloud/internal/json/request/ICloudAccountDataRequest.java
Labels: bug

#13118 [dali] Use correct command argument to query current color temperature
  bundles/org.openhab.binding.dali/src/main/java/org/openhab/binding/dali/internal/handler/DaliDt8DeviceHandler.java
Labels: bug

#13133 [rotel] Fix handling of balance command feedback
  bundles/org.openhab.binding.rotel/src/main/java/org/openhab/binding/rotel/internal/handler/RotelHandler.java
Labels: bug

#13125 [nibeheatpump] Added new channels for F1x45 heat pumps
  bundles/org.openhab.binding.nibeheatpump/README.md
  bundles/org.openhab.binding.nibeheatpump/src/main/java/org/openhab/binding/nibeheatpump/internal/models/F1X45.java
  bundles/org.openhab.binding.nibeheatpump/src/main/resources/OH-INF/i18n/nibeheatpump.properties
  bundles/org.openhab.binding.nibeheatpump/src/main/resources/OH-INF/thing/f1x45-channel-groups.xml
  bundles/org.openhab.binding.nibeheatpump/src/main/resources/OH-INF/thing/f1x45-types.xml
Labels: enhancement

#13082 [onkyo] HT-RC440 added
  bundles/org.openhab.binding.onkyo/README.md
  bundles/org.openhab.binding.onkyo/src/main/java/org/openhab/binding/onkyo/internal/OnkyoModel.java
  bundles/org.openhab.binding.onkyo/src/main/resources/OH-INF/i18n/onkyo.properties
  bundles/org.openhab.binding.onkyo/src/main/resources/OH-INF/thing/ht-rc440.xml
Labels: enhancement

#13148 [rotel] Fix syntax of few ASCII commands
  bundles/org.openhab.binding.rotel/src/main/java/org/openhab/binding/rotel/internal/communication/RotelCommand.java
Labels: bug

#13146 [haywardomnilogic] Empty XML Response Handling
  bundles/org.openhab.binding.haywardomnilogic/src/main/java/org/openhab/binding/haywardomnilogic/internal/handler/HaywardBridgeHandler.java
Labels: bug

#13101 [homematic] Update README.md
  bundles/org.openhab.binding.homematic/README.md
Labels: documentation

#13155 [hdpowerview] Fix excessive firmware version updates
  bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/handler/HDPowerViewHubHandler.java
Labels: bug

#13159 [homematic] Update README.md
  bundles/org.openhab.binding.homematic/README.md
Labels: documentation

#13046 [venstarthermostat] Split away and schedule settings calls (resolves bug exiting away mode)
  bundles/org.openhab.binding.venstarthermostat/src/main/java/org/openhab/binding/venstarthermostat/internal/handler/VenstarThermostatHandler.java
Labels: bug

#13136 [rotel] Add support of multiple zones (ASCII protocol)
  bundles/org.openhab.binding.rotel/src/main/java/org/openhab/binding/rotel/internal/RotelBindingConstants.java
  bundles/org.openhab.binding.rotel/src/main/java/org/openhab/binding/rotel/internal/RotelHandlerFactory.java
  bundles/org.openhab.binding.rotel/src/main/java/org/openhab/binding/rotel/internal/RotelModel.java
  bundles/org.openhab.binding.rotel/src/main/java/org/openhab/binding/rotel/internal/communication/RotelCommand.java
  bundles/org.openhab.binding.rotel/src/main/java/org/openhab/binding/rotel/internal/communication/RotelSimuConnector.java
  bundles/org.openhab.binding.rotel/src/main/java/org/openhab/binding/rotel/internal/communication/RotelSource.java
  bundles/org.openhab.binding.rotel/src/main/java/org/openhab/binding/rotel/internal/handler/RotelHandler.java
  bundles/org.openhab.binding.rotel/src/main/java/org/openhab/binding/rotel/internal/protocol/ascii/RotelAsciiV2ProtocolHandler.java
  bundles/org.openhab.binding.rotel/src/main/java/org/openhab/binding/rotel/internal/protocol/hex/RotelHexProtocolHandler.java
  bundles/org.openhab.binding.rotel/src/main/resources/OH-INF/i18n/rotel.properties
  bundles/org.openhab.binding.rotel/src/main/resources/OH-INF/thing/c8.xml
  bundles/org.openhab.binding.rotel/src/main/resources/OH-INF/thing/channels.xml
Labels: enhancement

#13165 [rotel] New channels to control random mode and repeat mode (CD players)
  bundles/org.openhab.binding.rotel/README.md
  bundles/org.openhab.binding.rotel/src/main/java/org/openhab/binding/rotel/internal/RotelBindingConstants.java
  bundles/org.openhab.binding.rotel/src/main/java/org/openhab/binding/rotel/internal/RotelRepeatMode.java
  bundles/org.openhab.binding.rotel/src/main/java/org/openhab/binding/rotel/internal/communication/RotelCommand.java
  bundles/org.openhab.binding.rotel/src/main/java/org/openhab/binding/rotel/internal/communication/RotelSimuConnector.java
  bundles/org.openhab.binding.rotel/src/main/java/org/openhab/binding/rotel/internal/handler/RotelHandler.java
  bundles/org.openhab.binding.rotel/src/main/resources/OH-INF/i18n/rotel.properties
  bundles/org.openhab.binding.rotel/src/main/resources/OH-INF/thing/cd11.xml
  bundles/org.openhab.binding.rotel/src/main/resources/OH-INF/thing/cd14.xml
  bundles/org.openhab.binding.rotel/src/main/resources/OH-INF/thing/channels.xml
  bundles/org.openhab.binding.rotel/src/main/resources/OH-INF/thing/rcd1572.xml
Labels: enhancement

#13169 [hdpowerview] Fix tilt support for vertical slats
  bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/database/ShadeCapabilitiesDatabase.java
Labels: bug

#13167 [boschindego] Fix communication error when smart mowing is disabled
  bundles/org.openhab.binding.boschindego/src/main/java/org/openhab/binding/boschindego/internal/IndegoController.java
  bundles/org.openhab.binding.boschindego/src/main/java/org/openhab/binding/boschindego/internal/exceptions/IndegoInvalidResponseException.java
Labels: community approved

#13168 [homematic] Allow default value that is less than allowed minimum
  bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/type/HomematicTypeGeneratorImpl.java
Labels: bug

#13096 [hdpowerview] Add shade RF RSSI channels for hub/repeater
  bundles/org.openhab.binding.hdpowerview/README.md
  bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/HDPowerViewBindingConstants.java
  bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/handler/HDPowerViewShadeHandler.java
  bundles/org.openhab.binding.hdpowerview/src/main/resources/OH-INF/i18n/hdpowerview.properties
  bundles/org.openhab.binding.hdpowerview/src/main/resources/OH-INF/thing/channels.xml
  bundles/org.openhab.binding.hdpowerview/src/main/resources/OH-INF/thing/shade.xml
Labels: enhancement

#13170 [radiothermostat] minor readme updates
  bundles/org.openhab.binding.radiothermostat/README.md
Labels: documentation

#12985 [homekit] Target Fan state - add support for Switch Item
  bundles/org.openhab.io.homekit/README.md
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitCharacteristicFactory.java
Labels: enhancement

#13030 [insteon] set network to ONLINE after driver is initialized
  bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/InsteonBinding.java
  bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/handler/InsteonNetworkHandler.java
Labels: bug

#13164 [haywardomnilogic] Add http timeout retry
  bundles/org.openhab.binding.haywardomnilogic/src/main/java/org/openhab/binding/haywardomnilogic/internal/handler/HaywardBridgeHandler.java
Labels: enhancement

#12321 [somneo] Initial contribution
  CODEOWNERS
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.somneo/NOTICE
  bundles/org.openhab.binding.somneo/README.md
  bundles/org.openhab.binding.somneo/pom.xml
  bundles/org.openhab.binding.somneo/src/main/feature/feature.xml
  bundles/org.openhab.binding.somneo/src/main/java/org/openhab/binding/somneo/internal/HttpClientProvider.java
  bundles/org.openhab.binding.somneo/src/main/java/org/openhab/binding/somneo/internal/SomneoBindingConstants.java
  bundles/org.openhab.binding.somneo/src/main/java/org/openhab/binding/somneo/internal/SomneoConfiguration.java
  bundles/org.openhab.binding.somneo/src/main/java/org/openhab/binding/somneo/internal/SomneoHandler.java
  bundles/org.openhab.binding.somneo/src/main/java/org/openhab/binding/somneo/internal/SomneoHandlerFactory.java
  bundles/org.openhab.binding.somneo/src/main/java/org/openhab/binding/somneo/internal/SomneoHttpConnector.java
  bundles/org.openhab.binding.somneo/src/main/java/org/openhab/binding/somneo/internal/SomneoPresetStateDescriptionProvider.java
  bundles/org.openhab.binding.somneo/src/main/java/org/openhab/binding/somneo/internal/model/AudioData.java
  bundles/org.openhab.binding.somneo/src/main/java/org/openhab/binding/somneo/internal/model/DeviceData.java
  bundles/org.openhab.binding.somneo/src/main/java/org/openhab/binding/somneo/internal/model/FirmwareData.java
  bundles/org.openhab.binding.somneo/src/main/java/org/openhab/binding/somneo/internal/model/LightData.java
  bundles/org.openhab.binding.somneo/src/main/java/org/openhab/binding/somneo/internal/model/PresetData.java
  bundles/org.openhab.binding.somneo/src/main/java/org/openhab/binding/somneo/internal/model/RadioData.java
  bundles/org.openhab.binding.somneo/src/main/java/org/openhab/binding/somneo/internal/model/RelaxData.java
  bundles/org.openhab.binding.somneo/src/main/java/org/openhab/binding/somneo/internal/model/SensorData.java
  bundles/org.openhab.binding.somneo/src/main/java/org/openhab/binding/somneo/internal/model/SunsetData.java
  bundles/org.openhab.binding.somneo/src/main/java/org/openhab/binding/somneo/internal/model/TimerData.java
  bundles/org.openhab.binding.somneo/src/main/java/org/openhab/binding/somneo/internal/model/WifiData.java
  bundles/org.openhab.binding.somneo/src/main/resources/OH-INF/binding/binding.xml
  bundles/org.openhab.binding.somneo/src/main/resources/OH-INF/i18n/somneo.properties
  bundles/org.openhab.binding.somneo/src/main/resources/OH-INF/i18n/somneo_de.properties
  bundles/org.openhab.binding.somneo/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/pom.xml
Labels: new binding

#13179 [boschindego] Plot location on map
  bundles/org.openhab.binding.boschindego/README.md
  bundles/org.openhab.binding.boschindego/src/main/java/org/openhab/binding/boschindego/internal/DeviceStatus.java
  bundles/org.openhab.binding.boschindego/src/main/java/org/openhab/binding/boschindego/internal/config/BoschIndegoConfiguration.java
  bundles/org.openhab.binding.boschindego/src/main/java/org/openhab/binding/boschindego/internal/handler/BoschIndegoHandler.java
  bundles/org.openhab.binding.boschindego/src/main/resources/OH-INF/i18n/boschindego.properties
  bundles/org.openhab.binding.boschindego/src/main/resources/OH-INF/thing/thing-types.xml
Labels: enhancement

#13189 [myq] Catch json parsing errors when getting login token.
  bundles/org.openhab.binding.myq/src/main/java/org/openhab/binding/myq/internal/handler/MyQAccountHandler.java
Labels: bug

#13176 [shelly]Restructuriing to prepare Plus/Pro support integration
  bundles/org.openhab.binding.shelly/README.md
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/ShellyBindingConstants.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/ShellyHandlerFactory.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api/ShellyApiInterface.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api/ShellyApiResult.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api/ShellyDeviceProfile.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api/ShellyHttpClient.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api1/Shelly1ApiJsonDTO.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api1/Shelly1CoIoTInterface.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api1/Shelly1CoIoTProtocol.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api1/Shelly1CoIoTVersion1.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api1/Shelly1CoIoTVersion2.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api1/Shelly1CoapHandler.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api1/Shelly1CoapJSonDTO.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api1/Shelly1CoapListener.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api1/Shelly1CoapServer.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api1/Shelly1HttpApi.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/discovery/ShellyDiscoveryParticipant.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/discovery/ShellyThingCreator.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/handler/ShellyBaseHandler.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/handler/ShellyColorUtils.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/handler/ShellyComponents.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/handler/ShellyLightHandler.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/handler/ShellyProtectedHandler.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/handler/ShellyRelayHandler.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/handler/ShellyThingInterface.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/manager/ShellyManagerActionPage.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/manager/ShellyManagerOtaPage.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/manager/ShellyManagerPage.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/manager/ShellyManagerServlet.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/provider/ShellyChannelDefinitions.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/util/ShellyUtils.java
  bundles/org.openhab.binding.shelly/src/main/resources/OH-INF/binding/binding.xml
  bundles/org.openhab.binding.shelly/src/main/resources/OH-INF/i18n/shelly.properties
Labels: enhancement

#13193 [rotel] Updated doc for c8 and c8+ models
  bundles/org.openhab.binding.rotel/README.md
Labels: documentation

#13175 [hdpowerview] Refactor tests
  bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/handler/HDPowerViewHubHandler.java
  bundles/org.openhab.binding.hdpowerview/src/test/java/org/openhab/binding/hdpowerview/AutomationChannelBuilderTest.java
  bundles/org.openhab.binding.hdpowerview/src/test/java/org/openhab/binding/hdpowerview/HDPowerViewJUnitTests.java
  bundles/org.openhab.binding.hdpowerview/src/test/java/org/openhab/binding/hdpowerview/OnlineCommunicationTest.java
  bundles/org.openhab.binding.hdpowerview/src/test/java/org/openhab/binding/hdpowerview/SceneChannelBuilderTest.java
  bundles/org.openhab.binding.hdpowerview/src/test/java/org/openhab/binding/hdpowerview/SceneGroupChannelBuilderTest.java
  bundles/org.openhab.binding.hdpowerview/src/test/java/org/openhab/binding/hdpowerview/providers/MockedLocaleProvider.java
  bundles/org.openhab.binding.hdpowerview/src/test/java/org/openhab/binding/hdpowerview/providers/MockedTranslationProvider.java
  bundles/org.openhab.binding.hdpowerview/src/test/resources/org/openhab/binding/hdpowerview/duette.json
  bundles/org.openhab.binding.hdpowerview/src/test/resources/org/openhab/binding/hdpowerview/sceneCollections.json
  bundles/org.openhab.binding.hdpowerview/src/test/resources/org/openhab/binding/hdpowerview/scenes.json
  bundles/org.openhab.binding.hdpowerview/src/test/resources/org/openhab/binding/hdpowerview/shades.json
Labels: test

#13183 [rotel] New channel for other commands provided by the API
  bundles/org.openhab.binding.rotel/README.md
  bundles/org.openhab.binding.rotel/src/main/java/org/openhab/binding/rotel/internal/RotelBindingConstants.java
  bundles/org.openhab.binding.rotel/src/main/java/org/openhab/binding/rotel/internal/RotelCommandDescriptionOptionProvider.java
  bundles/org.openhab.binding.rotel/src/main/java/org/openhab/binding/rotel/internal/RotelHandlerFactory.java
  bundles/org.openhab.binding.rotel/src/main/java/org/openhab/binding/rotel/internal/RotelModel.java
  bundles/org.openhab.binding.rotel/src/main/java/org/openhab/binding/rotel/internal/communication/RotelCommand.java
  bundles/org.openhab.binding.rotel/src/main/java/org/openhab/binding/rotel/internal/communication/RotelConnector.java
  bundles/org.openhab.binding.rotel/src/main/java/org/openhab/binding/rotel/internal/communication/RotelDsp.java
  bundles/org.openhab.binding.rotel/src/main/java/org/openhab/binding/rotel/internal/communication/RotelSimuConnector.java
  bundles/org.openhab.binding.rotel/src/main/java/org/openhab/binding/rotel/internal/communication/RotelSource.java
  bundles/org.openhab.binding.rotel/src/main/java/org/openhab/binding/rotel/internal/handler/RotelHandler.java
  bundles/org.openhab.binding.rotel/src/main/java/org/openhab/binding/rotel/internal/protocol/ascii/RotelAsciiV1ProtocolHandler.java
  bundles/org.openhab.binding.rotel/src/main/java/org/openhab/binding/rotel/internal/protocol/ascii/RotelAsciiV2ProtocolHandler.java
  bundles/org.openhab.binding.rotel/src/main/java/org/openhab/binding/rotel/internal/protocol/hex/RotelHexProtocolHandler.java
  bundles/org.openhab.binding.rotel/src/main/resources/OH-INF/i18n/rotel.properties
  bundles/org.openhab.binding.rotel/src/main/resources/OH-INF/thing/a11.xml
  bundles/org.openhab.binding.rotel/src/main/resources/OH-INF/thing/a12.xml
  bundles/org.openhab.binding.rotel/src/main/resources/OH-INF/thing/a14.xml
  bundles/org.openhab.binding.rotel/src/main/resources/OH-INF/thing/cd11.xml
  bundles/org.openhab.binding.rotel/src/main/resources/OH-INF/thing/cd14.xml
  bundles/org.openhab.binding.rotel/src/main/resources/OH-INF/thing/channels.xml
  bundles/org.openhab.binding.rotel/src/main/resources/OH-INF/thing/p5.xml
  bundles/org.openhab.binding.rotel/src/main/resources/OH-INF/thing/ra11.xml
  bundles/org.openhab.binding.rotel/src/main/resources/OH-INF/thing/ra12.xml
  bundles/org.openhab.binding.rotel/src/main/resources/OH-INF/thing/ra1570.xml
  bundles/org.openhab.binding.rotel/src/main/resources/OH-INF/thing/ra1572.xml
  bundles/org.openhab.binding.rotel/src/main/resources/OH-INF/thing/rc1570.xml
  bundles/org.openhab.binding.rotel/src/main/resources/OH-INF/thing/rc1572.xml
  bundles/org.openhab.binding.rotel/src/main/resources/OH-INF/thing/rcd1572.xml
  bundles/org.openhab.binding.rotel/src/main/resources/OH-INF/thing/x3.xml
  bundles/org.openhab.binding.rotel/src/main/resources/OH-INF/thing/x5.xml
Labels: enhancement

#12618 [velux] Add support for vane/slat position
  bundles/org.openhab.binding.velux/README.md
  bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/VeluxBindingConstants.java
  bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/VeluxItemType.java
  bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/bridge/VeluxBridgeRunProductCommand.java
  bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/bridge/common/BridgeAPI.java
  bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/bridge/common/RunProductCommand.java
  bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/bridge/json/JsonBridgeAPI.java
  bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/bridge/slip/FunctionalParameters.java
  bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/bridge/slip/SCgetHouseStatus.java
  bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/bridge/slip/SCgetProduct.java
  bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/bridge/slip/SCgetProductStatus.java
  bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/bridge/slip/SCgetProducts.java
  bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/bridge/slip/SCrunProductCommand.java
  bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/bridge/slip/SlipBridgeAPI.java
  bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/bridge/slip/SlipVeluxBridge.java
  bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/bridge/slip/io/DataInputStreamWithTimeout.java
  bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/bridge/slip/utils/KLF200Response.java
  bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/discovery/VeluxDiscoveryService.java
  bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/factory/VeluxHandlerFactory.java
  bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/handler/ChannelActuatorPosition.java
  bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/handler/ChannelVShutterPosition.java
  bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/handler/VeluxBridgeHandler.java
  bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/handler/utils/Thing2VeluxActuator.java
  bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/things/VeluxExistingProducts.java
  bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/things/VeluxKLFAPI.java
  bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/things/VeluxProduct.java
  bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/things/VeluxProductPosition.java
  bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/things/VeluxProductType.java
  bundles/org.openhab.binding.velux/src/main/resources/OH-INF/i18n/velux.properties
  bundles/org.openhab.binding.velux/src/main/resources/OH-INF/thing/channels.xml
  bundles/org.openhab.binding.velux/src/main/resources/OH-INF/thing/rollershutter.xml
  bundles/org.openhab.binding.velux/src/test/java/org/openhab/binding/velux/test/TestNotificationsAndDatabase.java
Labels: enhancement
