Repository openhab/openhab-addons, pull requests merged in 2022-12, with the labels that each got.

#13327 [wundergroundupdatereceiver] Bugfixes: Regenerate trigger channel with proper type and more metadata. Normalize channel names. It might be easiest to delete and allow recreation of channels.
  bundles/org.openhab.binding.wundergroundupdatereceiver/README.md
  bundles/org.openhab.binding.wundergroundupdatereceiver/src/main/java/org/openhab/binding/wundergroundupdatereceiver/internal/WundergroundUpdateReceiverBindingConstants.java
  bundles/org.openhab.binding.wundergroundupdatereceiver/src/main/java/org/openhab/binding/wundergroundupdatereceiver/internal/WundergroundUpdateReceiverDiscoveryService.java
  bundles/org.openhab.binding.wundergroundupdatereceiver/src/main/java/org/openhab/binding/wundergroundupdatereceiver/internal/WundergroundUpdateReceiverHandler.java
  bundles/org.openhab.binding.wundergroundupdatereceiver/src/main/java/org/openhab/binding/wundergroundupdatereceiver/internal/WundergroundUpdateReceiverParameterMapping.java
  bundles/org.openhab.binding.wundergroundupdatereceiver/src/main/java/org/openhab/binding/wundergroundupdatereceiver/internal/WundergroundUpdateReceiverServlet.java
  bundles/org.openhab.binding.wundergroundupdatereceiver/src/main/java/org/openhab/binding/wundergroundupdatereceiver/internal/WundergroundUpdateReceiverUnknownChannelTypeProvider.java
  bundles/org.openhab.binding.wundergroundupdatereceiver/src/main/resources/OH-INF/i18n/wundergroundupdatereceiver.properties
  bundles/org.openhab.binding.wundergroundupdatereceiver/src/test/java/org/openhab/binding/wundergroundupdatereceiver/internal/WundergroundUpdateReceiverDiscoveryServiceTest.java
Labels: bug

#13818 [tplinksmarthome] Add support for TP-Link KP401 Smart WiFi Outdoor Plug
  bundles/org.openhab.binding.tplinksmarthome/README.md
  bundles/org.openhab.binding.tplinksmarthome/src/main/java/org/openhab/binding/tplinksmarthome/internal/TPLinkSmartHomeThingType.java
  bundles/org.openhab.binding.tplinksmarthome/src/main/resources/OH-INF/i18n/tplinksmarthome.properties
  bundles/org.openhab.binding.tplinksmarthome/src/main/resources/OH-INF/thing/KP401.xml
Labels: enhancement

#13752 [nibeheatpump] Support 16-bit addressing
  bundles/org.openhab.binding.nibeheatpump/contrib/NibeGW/Arduino/NibeGW/NibeGW.ino
  bundles/org.openhab.binding.nibeheatpump/contrib/NibeGW/Arduino/NibeGW/NibeGw.cpp
  bundles/org.openhab.binding.nibeheatpump/contrib/NibeGW/Arduino/NibeGW/NibeGw.h
  bundles/org.openhab.binding.nibeheatpump/contrib/NibeGW/RasPi/nibegw.c
  bundles/org.openhab.binding.nibeheatpump/src/main/java/org/openhab/binding/nibeheatpump/internal/protocol/NibeHeatPumpProtocolStates.java
  bundles/org.openhab.binding.nibeheatpump/src/test/java/org/openhab/binding/nibeheatpump/internal/message/NibeHeatPumpProtocolTest.java
Labels: bug

#13817 [jdbc] Fix Derby/H2/HSQLDB/SQLite queries for storing timestamps
  bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/db/JdbcDerbyDAO.java
  bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/db/JdbcH2DAO.java
  bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/db/JdbcHsqldbDAO.java
  bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/db/JdbcSqliteDAO.java
Labels: bug

#13820 [plugwiseha] Fix typos in README examples
  bundles/org.openhab.binding.plugwiseha/README.md
Labels: documentation

#13822 [groovyscripting] Update Groovy to 3.0.13
  bundles/org.openhab.automation.groovyscripting/README.md
  bundles/org.openhab.automation.groovyscripting/pom.xml
Labels: enhancement

#13824 [jsscripting] Fix memory leak that crashes openHAB
  bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/OpenhabGraalJSScriptEngine.java
Labels: bug

#13805 [ipcamera] Instar API updates for new 2k+ range
  bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/InstarHandler.java
  bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/handler/IpCameraHandler.java
  bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/onvif/OnvifConnection.java
Labels: enhancement

#13827 [unifi] Migrate uptime channels to Number:Time
  bundles/org.openhab.binding.unifi/README.md
  bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/handler/UniFiClientThingHandler.java
  bundles/org.openhab.binding.unifi/src/main/resources/OH-INF/thing/thing-types.xml
Labels: enhancement, (potentially) not backward compatible

#13821 [homematic] Fix min/max values for rollershutters
  bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/type/HomematicTypeGeneratorImpl.java
Labels: bug

#13753 [resol] Fix handling of WeekTime fields on vbus
  bundles/org.openhab.binding.resol/pom.xml
  bundles/org.openhab.binding.resol/src/main/java/org/openhab/binding/resol/handler/ResolThingHandler.java
  bundles/org.openhab.binding.resol/src/main/resources/OH-INF/thing/thing-types.xml
Labels: bug, (potentially) not backward compatible

#13828 [androiddebugbridge] Fix volume channel for android 11/12
  bundles/org.openhab.binding.androiddebugbridge/README.md
  bundles/org.openhab.binding.androiddebugbridge/src/main/java/org/openhab/binding/androiddebugbridge/internal/AndroidDebugBridgeConfiguration.java
  bundles/org.openhab.binding.androiddebugbridge/src/main/java/org/openhab/binding/androiddebugbridge/internal/AndroidDebugBridgeDevice.java
  bundles/org.openhab.binding.androiddebugbridge/src/main/java/org/openhab/binding/androiddebugbridge/internal/AndroidDebugBridgeHandler.java
  bundles/org.openhab.binding.androiddebugbridge/src/main/java/org/openhab/binding/androiddebugbridge/internal/discovery/AndroidDebugBridgeDiscoveryService.java
  bundles/org.openhab.binding.androiddebugbridge/src/main/java/org/openhab/binding/androiddebugbridge/internal/discovery/AndroidTVMDNSDiscoveryParticipant.java
  bundles/org.openhab.binding.androiddebugbridge/src/main/resources/OH-INF/i18n/androiddebugbridge.properties
  bundles/org.openhab.binding.androiddebugbridge/src/main/resources/OH-INF/thing/thing-types.xml
Labels: bug

#12250 [smsmodem] Initial contribution
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.smsmodem/NOTICE
  bundles/org.openhab.binding.smsmodem/README.md
  bundles/org.openhab.binding.smsmodem/pom.xml
  bundles/org.openhab.binding.smsmodem/src/3rdparty/java/org/smslib/Capabilities.java
  bundles/org.openhab.binding.smsmodem/src/3rdparty/java/org/smslib/CommunicationException.java
  bundles/org.openhab.binding.smsmodem/src/3rdparty/java/org/smslib/DeviceInformation.java
  bundles/org.openhab.binding.smsmodem/src/3rdparty/java/org/smslib/MessageReader.java
  bundles/org.openhab.binding.smsmodem/src/3rdparty/java/org/smslib/MessageSender.java
  bundles/org.openhab.binding.smsmodem/src/3rdparty/java/org/smslib/Modem.java
  bundles/org.openhab.binding.smsmodem/src/3rdparty/java/org/smslib/ModemResponse.java
  bundles/org.openhab.binding.smsmodem/src/3rdparty/java/org/smslib/UnrecoverableSmslibException.java
  bundles/org.openhab.binding.smsmodem/src/3rdparty/java/org/smslib/callback/IDeviceInformationListener.java
  bundles/org.openhab.binding.smsmodem/src/3rdparty/java/org/smslib/callback/IInboundOutboundMessageListener.java
  bundles/org.openhab.binding.smsmodem/src/3rdparty/java/org/smslib/callback/IModemStatusListener.java
  bundles/org.openhab.binding.smsmodem/src/3rdparty/java/org/smslib/driver/AbstractModemDriver.java
  bundles/org.openhab.binding.smsmodem/src/3rdparty/java/org/smslib/driver/IPModemDriver.java
  bundles/org.openhab.binding.smsmodem/src/3rdparty/java/org/smslib/driver/JSerialModemDriver.java
  bundles/org.openhab.binding.smsmodem/src/3rdparty/java/org/smslib/driver/PollReader.java
  bundles/org.openhab.binding.smsmodem/src/3rdparty/java/org/smslib/message/AbstractMessage.java
  bundles/org.openhab.binding.smsmodem/src/3rdparty/java/org/smslib/message/DeliveryReportMessage.java
  bundles/org.openhab.binding.smsmodem/src/3rdparty/java/org/smslib/message/InboundBinaryMessage.java
  bundles/org.openhab.binding.smsmodem/src/3rdparty/java/org/smslib/message/InboundMessage.java
  bundles/org.openhab.binding.smsmodem/src/3rdparty/java/org/smslib/message/MsIsdn.java
  bundles/org.openhab.binding.smsmodem/src/3rdparty/java/org/smslib/message/OutboundBinaryMessage.java
  bundles/org.openhab.binding.smsmodem/src/3rdparty/java/org/smslib/message/OutboundMessage.java
  bundles/org.openhab.binding.smsmodem/src/3rdparty/java/org/smslib/message/Payload.java
  bundles/org.openhab.binding.smsmodem/src/3rdparty/java/org/smslib/pduUtils/gsm3040/Pdu.java
  bundles/org.openhab.binding.smsmodem/src/3rdparty/java/org/smslib/pduUtils/gsm3040/PduFactory.java
  bundles/org.openhab.binding.smsmodem/src/3rdparty/java/org/smslib/pduUtils/gsm3040/PduGenerator.java
  bundles/org.openhab.binding.smsmodem/src/3rdparty/java/org/smslib/pduUtils/gsm3040/PduParser.java
  bundles/org.openhab.binding.smsmodem/src/3rdparty/java/org/smslib/pduUtils/gsm3040/PduUtils.java
  bundles/org.openhab.binding.smsmodem/src/3rdparty/java/org/smslib/pduUtils/gsm3040/SmsDeliveryPdu.java
  bundles/org.openhab.binding.smsmodem/src/3rdparty/java/org/smslib/pduUtils/gsm3040/SmsStatusReportPdu.java
  bundles/org.openhab.binding.smsmodem/src/3rdparty/java/org/smslib/pduUtils/gsm3040/SmsSubmitPdu.java
  bundles/org.openhab.binding.smsmodem/src/3rdparty/java/org/smslib/pduUtils/gsm3040/ie/ConcatInformationElement.java
  bundles/org.openhab.binding.smsmodem/src/3rdparty/java/org/smslib/pduUtils/gsm3040/ie/InformationElement.java
  bundles/org.openhab.binding.smsmodem/src/3rdparty/java/org/smslib/pduUtils/gsm3040/ie/InformationElementFactory.java
  bundles/org.openhab.binding.smsmodem/src/3rdparty/java/org/smslib/pduUtils/gsm3040/ie/PortInformationElement.java
  bundles/org.openhab.binding.smsmodem/src/main/feature/feature.xml
  bundles/org.openhab.binding.smsmodem/src/main/java/org/openhab/binding/smsmodem/internal/SMSConversationConfiguration.java
  bundles/org.openhab.binding.smsmodem/src/main/java/org/openhab/binding/smsmodem/internal/SMSConversationDiscoveryService.java
  bundles/org.openhab.binding.smsmodem/src/main/java/org/openhab/binding/smsmodem/internal/SMSModemBindingConstants.java
  bundles/org.openhab.binding.smsmodem/src/main/java/org/openhab/binding/smsmodem/internal/SMSModemBridgeConfiguration.java
  bundles/org.openhab.binding.smsmodem/src/main/java/org/openhab/binding/smsmodem/internal/SMSModemHandlerFactory.java
  bundles/org.openhab.binding.smsmodem/src/main/java/org/openhab/binding/smsmodem/internal/SMSModemRemoteBridgeConfiguration.java
  bundles/org.openhab.binding.smsmodem/src/main/java/org/openhab/binding/smsmodem/internal/actions/SMSModemActions.java
  bundles/org.openhab.binding.smsmodem/src/main/java/org/openhab/binding/smsmodem/internal/handler/DeliveryStatus.java
  bundles/org.openhab.binding.smsmodem/src/main/java/org/openhab/binding/smsmodem/internal/handler/ModemConfigurationException.java
  bundles/org.openhab.binding.smsmodem/src/main/java/org/openhab/binding/smsmodem/internal/handler/SMSConversationHandler.java
  bundles/org.openhab.binding.smsmodem/src/main/java/org/openhab/binding/smsmodem/internal/handler/SMSModemBridgeHandler.java
  bundles/org.openhab.binding.smsmodem/src/main/resources/OH-INF/binding/binding.xml
  bundles/org.openhab.binding.smsmodem/src/main/resources/OH-INF/i18n/smsmodem.properties
  bundles/org.openhab.binding.smsmodem/src/main/resources/OH-INF/i18n/smsmodem_fr.properties
  bundles/org.openhab.binding.smsmodem/src/main/resources/OH-INF/thing/smsconversation.xml
  bundles/org.openhab.binding.smsmodem/src/main/resources/OH-INF/thing/smsmodem.xml
  bundles/org.openhab.binding.smsmodem/src/main/resources/modem.properties
  bundles/pom.xml
Labels: new binding

#13831 [wundergroundupdatereceiver] Use html entities in normal body otherwise they are parsed as tags
  bundles/org.openhab.binding.wundergroundupdatereceiver/README.md
Labels: documentation

#13787 [nibeheatpump] Readme for NibeGW for Arduino with Hardware and compilation hints
  bundles/org.openhab.binding.nibeheatpump/contrib/NibeGW/Arduino/README.md
Labels: documentation

#13492 [webexteams] Initial contribution
  CODEOWNERS
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.webexteams/NOTICE
  bundles/org.openhab.binding.webexteams/README.md
  bundles/org.openhab.binding.webexteams/pom.xml
  bundles/org.openhab.binding.webexteams/src/main/feature/feature.xml
  bundles/org.openhab.binding.webexteams/src/main/java/org/openhab/binding/webexteams/internal/WebexAuthService.java
  bundles/org.openhab.binding.webexteams/src/main/java/org/openhab/binding/webexteams/internal/WebexAuthServlet.java
  bundles/org.openhab.binding.webexteams/src/main/java/org/openhab/binding/webexteams/internal/WebexAuthenticationException.java
  bundles/org.openhab.binding.webexteams/src/main/java/org/openhab/binding/webexteams/internal/WebexTeamsActions.java
  bundles/org.openhab.binding.webexteams/src/main/java/org/openhab/binding/webexteams/internal/WebexTeamsBindingConstants.java
  bundles/org.openhab.binding.webexteams/src/main/java/org/openhab/binding/webexteams/internal/WebexTeamsConfiguration.java
  bundles/org.openhab.binding.webexteams/src/main/java/org/openhab/binding/webexteams/internal/WebexTeamsException.java
  bundles/org.openhab.binding.webexteams/src/main/java/org/openhab/binding/webexteams/internal/WebexTeamsHandler.java
  bundles/org.openhab.binding.webexteams/src/main/java/org/openhab/binding/webexteams/internal/WebexTeamsHandlerFactory.java
  bundles/org.openhab.binding.webexteams/src/main/java/org/openhab/binding/webexteams/internal/api/Message.java
  bundles/org.openhab.binding.webexteams/src/main/java/org/openhab/binding/webexteams/internal/api/Person.java
  bundles/org.openhab.binding.webexteams/src/main/java/org/openhab/binding/webexteams/internal/api/WebexTeamsApi.java
  bundles/org.openhab.binding.webexteams/src/main/java/org/openhab/binding/webexteams/internal/api/WebexTeamsApiException.java
  bundles/org.openhab.binding.webexteams/src/main/resources/OH-INF/binding/binding.xml
  bundles/org.openhab.binding.webexteams/src/main/resources/OH-INF/i18n/webexteams.properties
  bundles/org.openhab.binding.webexteams/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.webexteams/src/main/resources/templates/account.html
  bundles/org.openhab.binding.webexteams/src/main/resources/templates/index.html
  bundles/org.openhab.binding.webexteams/src/main/resources/web/css/custom.css
  bundles/org.openhab.binding.webexteams/src/main/resources/web/css/normalize.css
  bundles/org.openhab.binding.webexteams/src/main/resources/web/css/skeleton.css
  bundles/org.openhab.binding.webexteams/src/main/resources/web/images/favicon.ico
  bundles/pom.xml
Labels: new binding

#13823 [ecowatt] Add channels for Day+2 and Day+3
  bundles/org.openhab.binding.ecowatt/src/main/java/org/openhab/binding/ecowatt/internal/EcowattBindingConstants.java
  bundles/org.openhab.binding.ecowatt/src/main/java/org/openhab/binding/ecowatt/internal/handler/EcowattHandler.java
  bundles/org.openhab.binding.ecowatt/src/main/resources/OH-INF/i18n/ecowatt.properties
  bundles/org.openhab.binding.ecowatt/src/main/resources/OH-INF/thing/thing-types.xml
Labels: enhancement

#13843 [jdbc] Fix date filter to be inclusive (PostgreSQL)
  bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/db/JdbcPostgresqlDAO.java
Labels: bug

#13810 [jrubyscripting] implement dependency tracking
  bundles/org.openhab.automation.jrubyscripting/README.md
  bundles/org.openhab.automation.jrubyscripting/src/main/java/org/openhab/automation/jrubyscripting/internal/JRubyScriptEngineConfiguration.java
  bundles/org.openhab.automation.jrubyscripting/src/main/java/org/openhab/automation/jrubyscripting/internal/JRubyScriptEngineFactory.java
  bundles/org.openhab.automation.jrubyscripting/src/main/java/org/openhab/automation/jrubyscripting/internal/watch/BidiSetBag.java
  bundles/org.openhab.automation.jrubyscripting/src/main/java/org/openhab/automation/jrubyscripting/internal/watch/JRubyDependencyTracker.java
  bundles/org.openhab.automation.jrubyscripting/src/main/java/org/openhab/automation/jrubyscripting/internal/watch/JRubyGemWatchService.java
  bundles/org.openhab.automation.jrubyscripting/src/main/java/org/openhab/automation/jrubyscripting/internal/watch/JRubyLibWatchService.java
  bundles/org.openhab.automation.jrubyscripting/src/main/java/org/openhab/automation/jrubyscripting/internal/watch/JRubyScriptFileWatcher.java
  bundles/org.openhab.automation.jrubyscripting/src/main/resources/OH-INF/config/config.xml
  bundles/org.openhab.automation.jrubyscripting/src/main/resources/OH-INF/i18n/jruby.properties
Labels: enhancement, (potentially) not backward compatible

#13520 [shelly] Plus 1/1PM Add-On support; fix roller pos on open/close state
  bundles/org.openhab.binding.shelly/README.md
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/ShellyBindingConstants.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api/ShellyApiException.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api/ShellyDeviceProfile.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api1/Shelly1ApiJsonDTO.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api1/Shelly1CoapServer.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api1/Shelly1HttpApi.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api2/Shelly2ApiClient.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api2/Shelly2ApiJsonDTO.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/discovery/ShellyDiscoveryParticipant.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/discovery/ShellyThingCreator.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/handler/ShellyBaseHandler.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/handler/ShellyComponents.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/provider/ShellyChannelDefinitions.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/util/ShellyUtils.java
  bundles/org.openhab.binding.shelly/src/main/resources/OH-INF/i18n/shelly.properties
  bundles/org.openhab.binding.shelly/src/main/resources/OH-INF/thing/shellyGen1_relay.xml
  bundles/org.openhab.binding.shelly/src/main/resources/OH-INF/thing/shellyGen1_sensor.xml
Labels: enhancement

#13744 [lifx] Set tagged flag accordingly for unicast and broadcast messages
  bundles/org.openhab.binding.lifx/src/main/java/org/openhab/binding/lifx/internal/dto/GetColorZonesRequest.java
  bundles/org.openhab.binding.lifx/src/main/java/org/openhab/binding/lifx/internal/dto/GetEchoRequest.java
  bundles/org.openhab.binding.lifx/src/main/java/org/openhab/binding/lifx/internal/dto/GetGroupRequest.java
  bundles/org.openhab.binding.lifx/src/main/java/org/openhab/binding/lifx/internal/dto/GetHevCycleConfigurationRequest.java
  bundles/org.openhab.binding.lifx/src/main/java/org/openhab/binding/lifx/internal/dto/GetHevCycleRequest.java
  bundles/org.openhab.binding.lifx/src/main/java/org/openhab/binding/lifx/internal/dto/GetHostFirmwareRequest.java
  bundles/org.openhab.binding.lifx/src/main/java/org/openhab/binding/lifx/internal/dto/GetHostInfoRequest.java
  bundles/org.openhab.binding.lifx/src/main/java/org/openhab/binding/lifx/internal/dto/GetInfoRequest.java
  bundles/org.openhab.binding.lifx/src/main/java/org/openhab/binding/lifx/internal/dto/GetLabelRequest.java
  bundles/org.openhab.binding.lifx/src/main/java/org/openhab/binding/lifx/internal/dto/GetLastHevCycleResultRequest.java
  bundles/org.openhab.binding.lifx/src/main/java/org/openhab/binding/lifx/internal/dto/GetLightInfraredRequest.java
  bundles/org.openhab.binding.lifx/src/main/java/org/openhab/binding/lifx/internal/dto/GetLightPowerRequest.java
  bundles/org.openhab.binding.lifx/src/main/java/org/openhab/binding/lifx/internal/dto/GetLocationRequest.java
  bundles/org.openhab.binding.lifx/src/main/java/org/openhab/binding/lifx/internal/dto/GetPowerRequest.java
  bundles/org.openhab.binding.lifx/src/main/java/org/openhab/binding/lifx/internal/dto/GetRequest.java
  bundles/org.openhab.binding.lifx/src/main/java/org/openhab/binding/lifx/internal/dto/GetServiceRequest.java
  bundles/org.openhab.binding.lifx/src/main/java/org/openhab/binding/lifx/internal/dto/GetTileEffectRequest.java
  bundles/org.openhab.binding.lifx/src/main/java/org/openhab/binding/lifx/internal/dto/GetVersionRequest.java
  bundles/org.openhab.binding.lifx/src/main/java/org/openhab/binding/lifx/internal/dto/GetWifiFirmwareRequest.java
  bundles/org.openhab.binding.lifx/src/main/java/org/openhab/binding/lifx/internal/dto/GetWifiInfoRequest.java
  bundles/org.openhab.binding.lifx/src/main/java/org/openhab/binding/lifx/internal/dto/SetColorRequest.java
  bundles/org.openhab.binding.lifx/src/main/java/org/openhab/binding/lifx/internal/dto/SetColorZonesRequest.java
  bundles/org.openhab.binding.lifx/src/main/java/org/openhab/binding/lifx/internal/dto/SetHevCycleConfigurationRequest.java
  bundles/org.openhab.binding.lifx/src/main/java/org/openhab/binding/lifx/internal/dto/SetHevCycleRequest.java
  bundles/org.openhab.binding.lifx/src/main/java/org/openhab/binding/lifx/internal/dto/SetLabelRequest.java
  bundles/org.openhab.binding.lifx/src/main/java/org/openhab/binding/lifx/internal/dto/SetLightInfraredRequest.java
  bundles/org.openhab.binding.lifx/src/main/java/org/openhab/binding/lifx/internal/dto/SetLightPowerRequest.java
  bundles/org.openhab.binding.lifx/src/main/java/org/openhab/binding/lifx/internal/dto/SetPowerRequest.java
  bundles/org.openhab.binding.lifx/src/main/java/org/openhab/binding/lifx/internal/dto/SetTileEffectRequest.java
  bundles/org.openhab.binding.lifx/src/main/java/org/openhab/binding/lifx/internal/dto/StateHostFirmwareResponse.java
  bundles/org.openhab.binding.lifx/src/main/java/org/openhab/binding/lifx/internal/dto/StateHostInfoResponse.java
  bundles/org.openhab.binding.lifx/src/main/java/org/openhab/binding/lifx/internal/dto/StateInfoResponse.java
  bundles/org.openhab.binding.lifx/src/main/java/org/openhab/binding/lifx/internal/dto/StateVersionResponse.java
  bundles/org.openhab.binding.lifx/src/main/java/org/openhab/binding/lifx/internal/dto/StateWifiFirmwareResponse.java
  bundles/org.openhab.binding.lifx/src/main/java/org/openhab/binding/lifx/internal/util/LifxSelectorUtil.java
Labels: bug

#13694 [openwebnet] Add support for Alarm (WHO=5)
  bundles/org.openhab.binding.openwebnet/README.md
  bundles/org.openhab.binding.openwebnet/pom.xml
  bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/OpenWebNetBindingConstants.java
  bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/OpenWebNetHandlerFactory.java
  bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/discovery/OpenWebNetDeviceDiscoveryService.java
  bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/handler/OpenWebNetAlarmHandler.java
  bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/handler/OpenWebNetBridgeHandler.java
  bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/i18n/openwebnet.properties
  bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/thing/BusAlarmSystem.xml
  bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/thing/BusAlarmZone.xml
  bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/thing/channels.xml
  bundles/org.openhab.binding.openwebnet/src/test/java/org/openhab/binding/openwebnet/internal/handler/OwnIdTest.java
Labels: enhancement

#13851 [jsscripting] Add an alternative MIME type/alias
  bundles/org.openhab.automation.jsscripting/bnd.bnd
  bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/GraalJSScriptEngineFactory.java
  bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/OpenhabGraalJSScriptEngine.java
Labels: enhancement

#13845 [keba] Correct item type for state item in readme.md
  bundles/org.openhab.binding.keba/README.md
Labels: documentation

#13844 [jsscripting] Refactor log formatting & Respect toString polyfills
  bundles/org.openhab.automation.jsscripting/src/main/resources/node_modules/@jsscripting-globals.js
Labels: enhancement

#13854 [netatmo] Improve bridge status messages in case of service outage
  bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/ApiBridgeHandler.java
Labels: bug

#13621 [mqtt] Avoid parallel streams with common thread pool to avoid deadlocks
  bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/AbstractMQTTThingHandler.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/DiscoverComponents.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/AbstractComponent.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/handler/HomeAssistantThingHandler.java
Labels: bug

#13865 [nanoleaf] add LONG_PRESSED tap detection
  bundles/org.openhab.binding.nanoleaf/README.md
  bundles/org.openhab.binding.nanoleaf/src/main/java/org/openhab/binding/nanoleaf/internal/handler/NanoleafPanelHandler.java
Labels: enhancement

#13864 [ahawastecollection] Fixed unstable test
  bundles/org.openhab.binding.ahawastecollection/src/main/java/org/openhab/binding/ahawastecollection/internal/AhaWasteCollectionHandler.java
  bundles/org.openhab.binding.ahawastecollection/src/main/java/org/openhab/binding/ahawastecollection/internal/AhaWasteCollectionHandlerFactory.java
  bundles/org.openhab.binding.ahawastecollection/src/test/java/org/openhab/binding/ahawastecollection/internal/AhaWasteCollectionHandlerTest.java
Labels: bug

#13867 [atlona] Update README
  CODEOWNERS
  bundles/org.openhab.binding.atlona/README.md
Labels: documentation

#13484 [homekit] persist all known accessories, to prevent loss of homekit information
  bundles/org.openhab.io.homekit/README.md
  bundles/org.openhab.io.homekit/pom.xml
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/Homekit.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/Debouncer.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitAccessoryRegistry.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitAuthInfoImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitChangeListener.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitCommandExtension.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitSettings.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitTaggedItem.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/AbstractHomekitAccessoryImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/BooleanItemReader.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/DummyHomekitAccessory.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitAccessoryFactory.java
  bundles/org.openhab.io.homekit/src/main/resources/OH-INF/config/config.xml
  bundles/org.openhab.io.homekit/src/main/resources/OH-INF/i18n/homekit.properties
Labels: enhancement

#13811 [insteon] Binding Documentation: Updated I/O Linc Section
  bundles/org.openhab.binding.insteon/README.md
Labels: documentation

#13878 [homekit] implement basic command completion
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitCommandExtension.java
Labels: enhancement

#13884 [astro] Fix IllegalArgumentException in debug message
  bundles/org.openhab.binding.astro/src/main/java/org/openhab/binding/astro/internal/handler/AstroThingHandler.java
Labels: bug

#13868 [kaleidescape] Update README
  bundles/org.openhab.binding.kaleidescape/README.md
Labels: documentation

#13832 [plugwiseha] Fix set the scene for a zone
  bundles/org.openhab.binding.plugwiseha/src/main/java/org/openhab/binding/plugwiseha/internal/api/model/PlugwiseHAController.java
  bundles/org.openhab.binding.plugwiseha/src/main/java/org/openhab/binding/plugwiseha/internal/api/model/PlugwiseHAControllerRequest.java
  bundles/org.openhab.binding.plugwiseha/src/main/java/org/openhab/binding/plugwiseha/internal/api/model/dto/Location.java
  bundles/org.openhab.binding.plugwiseha/src/main/java/org/openhab/binding/plugwiseha/internal/api/model/dto/LocationsArray.java
  bundles/org.openhab.binding.plugwiseha/src/main/java/org/openhab/binding/plugwiseha/internal/api/model/dto/PlugwiseBaseModel.java
  bundles/org.openhab.binding.plugwiseha/src/main/java/org/openhab/binding/plugwiseha/internal/api/xml/PlugwiseHAXStream.java
Labels: bug

#13833 [plugwiseha] Add channel return temp
  bundles/org.openhab.binding.plugwiseha/README.md
  bundles/org.openhab.binding.plugwiseha/src/main/java/org/openhab/binding/plugwiseha/internal/PlugwiseHABindingConstants.java
  bundles/org.openhab.binding.plugwiseha/src/main/java/org/openhab/binding/plugwiseha/internal/api/model/dto/Appliance.java
  bundles/org.openhab.binding.plugwiseha/src/main/java/org/openhab/binding/plugwiseha/internal/api/model/dto/Logs.java
  bundles/org.openhab.binding.plugwiseha/src/main/java/org/openhab/binding/plugwiseha/internal/handler/PlugwiseHAApplianceHandler.java
  bundles/org.openhab.binding.plugwiseha/src/main/resources/OH-INF/i18n/plugwiseha.properties
  bundles/org.openhab.binding.plugwiseha/src/main/resources/OH-INF/thing/channels.xml
  bundles/org.openhab.binding.plugwiseha/src/main/resources/OH-INF/thing/thing-types.xml
Labels: enhancement

#13894 [TR064] Fix pattern excluding some valid ip-addresses
  bundles/org.openhab.binding.tr064/src/main/java/org/openhab/binding/tr064/internal/soap/SOAPValueConverter.java
  bundles/org.openhab.binding.tr064/src/main/resources/channels.xml
Labels: bug

#13888 [siemensrds] Binding no longer fails if thermostat does not use optional features
  bundles/org.openhab.binding.siemensrds/src/main/java/org/openhab/binding/siemensrds/internal/RdsDataPoints.java
  bundles/org.openhab.binding.siemensrds/src/main/java/org/openhab/binding/siemensrds/internal/RdsHandler.java
  bundles/org.openhab.binding.siemensrds/src/main/java/org/openhab/binding/siemensrds/points/BasePoint.java
  bundles/org.openhab.binding.siemensrds/src/test/java/org/openhab/binding/siemensrds/test/TestRdsData.java
  bundles/org.openhab.binding.siemensrds/src/test/resources/datapoints_full_set.json
  bundles/org.openhab.binding.siemensrds/src/test/resources/datapoints_full_set_new.json
Labels: bug

#13875 [mielecloud] Integration test fixes: remove things after each integration test
  itests/org.openhab.binding.mielecloud.tests/src/main/java/org/openhab/binding/mielecloud/internal/handler/AbstractMieleThingHandlerTest.java
Labels: test

#13739 [vitotronic] Add channel "currentmode" to thing "circuit"
  bundles/org.openhab.binding.vitotronic/README.md
  bundles/org.openhab.binding.vitotronic/src/main/resources/OH-INF/i18n/vitotronic.properties
  bundles/org.openhab.binding.vitotronic/src/main/resources/OH-INF/thing/thing-types.xml
Labels: enhancement

#13896 [ipcamera] Add a check to see if FFmpeg is frozen for mjpeg creation
  bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/Ffmpeg.java
  bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/InstarHandler.java
  bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/handler/IpCameraHandler.java
Labels: bug

#13898 [vitotronic] Fix few thing/channel labels/descriptions
  bundles/org.openhab.binding.vitotronic/src/main/resources/OH-INF/i18n/vitotronic.properties
  bundles/org.openhab.binding.vitotronic/src/main/resources/OH-INF/thing/bridge.xml
  bundles/org.openhab.binding.vitotronic/src/main/resources/OH-INF/thing/thing-types.xml
Labels: enhancement

#13841 [miele] Migrate time channels from DateTime to Number:Time
  bundles/org.openhab.binding.miele/README.md
  bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/DishwasherChannelSelector.java
  bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/MieleApplianceHandler.java
  bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/OvenChannelSelector.java
  bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/TumbleDryerChannelSelector.java
  bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/WashingMachineChannelSelector.java
  bundles/org.openhab.binding.miele/src/main/resources/OH-INF/thing/channeltypes.xml
Labels: enhancement, (potentially) not backward compatible

#13804 [systeminfo] QuantityTypes and state descriptions cleanup
  bundles/org.openhab.binding.systeminfo/README.md
  bundles/org.openhab.binding.systeminfo/src/main/java/org/openhab/binding/systeminfo/internal/handler/SysteminfoHandler.java
  bundles/org.openhab.binding.systeminfo/src/main/java/org/openhab/binding/systeminfo/internal/model/OSHISysteminfo.java
  bundles/org.openhab.binding.systeminfo/src/main/java/org/openhab/binding/systeminfo/internal/model/SysteminfoInterface.java
  bundles/org.openhab.binding.systeminfo/src/main/resources/OH-INF/i18n/systeminfo.properties
  bundles/org.openhab.binding.systeminfo/src/main/resources/OH-INF/thing/channels.xml
  itests/org.openhab.binding.systeminfo.tests/src/main/java/org/openhab/binding/systeminfo/test/SysteminfoOSGiTest.java
Labels: enhancement, (potentially) not backward compatible

#13905 [nanoleaf] Don't set read only temp file in test
  bundles/org.openhab.binding.nanoleaf/src/test/java/org/openhab/binding/nanoleaf/internal/layout/NanoleafLayoutTest.java
Labels: test

#13910 [transform/scale] Make unit tests compatible with Windows
  bundles/org.openhab.transform.scale/src/test/java/org/openhab/transform/scale/internal/ScaleTransformServiceTest.java
Labels: test

#13897 [knx] Improve handling of serial gateways
  bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/config/BridgeConfiguration.java
  bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/config/DeviceConfig.java
  bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/config/IPBridgeConfiguration.java
  bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/handler/AbstractKNXThingHandler.java
  bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/handler/DeviceThingHandler.java
  bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/handler/IPBridgeThingHandler.java
  bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/handler/SerialBridgeThingHandler.java
Labels: bug

#13908 [jsscripting] Upgrade openhab-js & Remove SharedCache
  bundles/org.openhab.automation.jsscripting/README.md
  bundles/org.openhab.automation.jsscripting/pom.xml
  bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/scope/SharedCache.java
Labels: enhancement

#13913 [siemensrds] Update to documentation
  bundles/org.openhab.binding.siemensrds/README.md
  bundles/org.openhab.binding.siemensrds/src/main/java/org/openhab/binding/siemensrds/internal/RdsAccessToken.java
Labels: bug, documentation

#13917 [Nanoleaf] Fix wrong image and website build (again)
  bundles/org.openhab.binding.nanoleaf/README.md
Labels: documentation

#13916 [jdbc] Fix console command 'tables clean'
  bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/JdbcPersistenceService.java
Labels: bug

#13919 [somfytahoma] fix the smoke sensor's documentation
  bundles/org.openhab.binding.somfytahoma/README.md
  bundles/org.openhab.binding.somfytahoma/src/main/resources/OH-INF/i18n/somfytahoma.properties
  bundles/org.openhab.binding.somfytahoma/src/main/resources/OH-INF/thing/channels.xml
Labels: documentation

#13927 [goecharger] Consider correct channel ID (maxCurrentTemp)
  bundles/org.openhab.binding.goecharger/src/main/java/org/openhab/binding/goecharger/internal/GoEChargerBindingConstants.java
Labels: bug

#13930 [miele] Fix dimension for powerConsumption channel
  bundles/org.openhab.binding.miele/README.md
  bundles/org.openhab.binding.miele/src/main/resources/OH-INF/thing/channeltypes.xml
Labels: bug, (potentially) not backward compatible

#13931 [nest] Add missing enable SDM API configuration step to README.md
  bundles/org.openhab.binding.nest/README.md
Labels: documentation

#13933 [miele] Fix examples after migration of time channels
  bundles/org.openhab.binding.miele/README.md
Labels: documentation

#13937 [airq] fix table in readme that broke rendering markup
  bundles/org.openhab.binding.airq/README.md
Labels: documentation

#13935 [mielecloud] Fix integration tests
  itests/org.openhab.binding.mielecloud.tests/src/main/java/org/openhab/binding/mielecloud/internal/config/servlet/ForwardToLoginServletTest.java
Labels: test

#13947 [jrubyscripting] remove some development logging that crept in
  bundles/org.openhab.automation.jrubyscripting/src/main/java/org/openhab/automation/jrubyscripting/internal/watch/JRubyScriptFileWatcher.java
Labels: bug

#13861 [mqtt.generic] Change color example
  bundles/org.openhab.binding.mqtt.generic/README.md
Labels: documentation

#13924 [jsscripting] Extend synchronization to common ScriptEngine methods
  bundles/org.openhab.automation.jsscripting/pom.xml
  bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/DebuggingGraalScriptEngine.java
  bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/GraalJSScriptEngineFactory.java
  bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/JSRuntimeFeatures.java
  bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/JSScriptServiceUtil.java
  bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/OpenhabGraalJSScriptEngine.java
  bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/ScriptExtensionModuleProvider.java
  bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/scope/AbstractScriptExtensionProvider.java
  bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/scope/ScriptDisposalAwareScriptExtensionProvider.java
  bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/scriptengine/DelegatingScriptEngineWithInvocableAndAutocloseable.java
  bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/scriptengine/InvocationInterceptingScriptEngineWithInvocableAndAutoCloseable.java
  bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/threading/ThreadsafeSimpleRuleDelegate.java
  bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/threading/ThreadsafeTimers.java
  bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/threading/ThreadsafeWrappingScriptedAutomationManagerDelegate.java
  bundles/org.openhab.automation.jsscripting/suppressions.properties
Labels: bug

#13951 [nanoleaf] Bugfix: Handle non-integer panel ids
  bundles/org.openhab.binding.nanoleaf/src/main/java/org/openhab/binding/nanoleaf/internal/handler/NanoleafPanelHandler.java
Labels: bug

#13952 [jsscripting] Fix broken event object table
  bundles/org.openhab.automation.jsscripting/README.md
Labels: documentation

#13691 [icloud] Rework authentication to reflect changes in iCloud API
  bundles/org.openhab.binding.icloud/README.md
  bundles/org.openhab.binding.icloud/src/main/java/org/openhab/binding/icloud/internal/FindMyIPhoneServiceManager.java
  bundles/org.openhab.binding.icloud/src/main/java/org/openhab/binding/icloud/internal/ICloudApiResponseException.java
  bundles/org.openhab.binding.icloud/src/main/java/org/openhab/binding/icloud/internal/ICloudBindingConstants.java
  bundles/org.openhab.binding.icloud/src/main/java/org/openhab/binding/icloud/internal/ICloudConnection.java
  bundles/org.openhab.binding.icloud/src/main/java/org/openhab/binding/icloud/internal/ICloudDeviceInformationListener.java
  bundles/org.openhab.binding.icloud/src/main/java/org/openhab/binding/icloud/internal/ICloudDeviceInformationParser.java
  bundles/org.openhab.binding.icloud/src/main/java/org/openhab/binding/icloud/internal/ICloudHandlerFactory.java
  bundles/org.openhab.binding.icloud/src/main/java/org/openhab/binding/icloud/internal/ICloudService.java
  bundles/org.openhab.binding.icloud/src/main/java/org/openhab/binding/icloud/internal/ICloudSession.java
  bundles/org.openhab.binding.icloud/src/main/java/org/openhab/binding/icloud/internal/RetryException.java
  bundles/org.openhab.binding.icloud/src/main/java/org/openhab/binding/icloud/internal/configuration/ICloudAccountThingConfiguration.java
  bundles/org.openhab.binding.icloud/src/main/java/org/openhab/binding/icloud/internal/discovery/ICloudDeviceDiscovery.java
  bundles/org.openhab.binding.icloud/src/main/java/org/openhab/binding/icloud/internal/handler/AuthState.java
  bundles/org.openhab.binding.icloud/src/main/java/org/openhab/binding/icloud/internal/handler/ICloudAccountBridgeHandler.java
  bundles/org.openhab.binding.icloud/src/main/java/org/openhab/binding/icloud/internal/handler/ICloudDeviceHandler.java
  bundles/org.openhab.binding.icloud/src/main/java/org/openhab/binding/icloud/internal/handler/dto/json/response/ICloudAccountDataResponse.java
  bundles/org.openhab.binding.icloud/src/main/java/org/openhab/binding/icloud/internal/handler/dto/json/response/ICloudAccountUserInfo.java
  bundles/org.openhab.binding.icloud/src/main/java/org/openhab/binding/icloud/internal/handler/dto/json/response/ICloudDeviceFeatures.java
  bundles/org.openhab.binding.icloud/src/main/java/org/openhab/binding/icloud/internal/handler/dto/json/response/ICloudDeviceInformation.java
  bundles/org.openhab.binding.icloud/src/main/java/org/openhab/binding/icloud/internal/handler/dto/json/response/ICloudDeviceLocation.java
  bundles/org.openhab.binding.icloud/src/main/java/org/openhab/binding/icloud/internal/handler/dto/json/response/ICloudServerContext.java
  bundles/org.openhab.binding.icloud/src/main/java/org/openhab/binding/icloud/internal/handler/dto/json/response/ICloudServerContextTimezone.java
  bundles/org.openhab.binding.icloud/src/main/java/org/openhab/binding/icloud/internal/json/request/ICloudAccountDataRequest.java
  bundles/org.openhab.binding.icloud/src/main/java/org/openhab/binding/icloud/internal/json/request/ICloudFindMyDeviceRequest.java
  bundles/org.openhab.binding.icloud/src/main/java/org/openhab/binding/icloud/internal/json/response/ICloudDeviceFeatures.java
  bundles/org.openhab.binding.icloud/src/main/java/org/openhab/binding/icloud/internal/utilities/CustomCookieStore.java
  bundles/org.openhab.binding.icloud/src/main/java/org/openhab/binding/icloud/internal/utilities/ICloudTextTranslator.java
  bundles/org.openhab.binding.icloud/src/main/java/org/openhab/binding/icloud/internal/utilities/JsonUtils.java
  bundles/org.openhab.binding.icloud/src/main/java/org/openhab/binding/icloud/internal/utilities/ListUtil.java
  bundles/org.openhab.binding.icloud/src/main/java/org/openhab/binding/icloud/internal/utilities/Pair.java
  bundles/org.openhab.binding.icloud/src/main/resources/OH-INF/i18n/iCloud.properties
  bundles/org.openhab.binding.icloud/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.icloud/src/test/java/org/openhab/binding/icloud/TestICloud.java
Labels: bug

#13955 [rrd4j] Error handling for broken rrd4j files
  bundles/org.openhab.persistence.rrd4j/src/main/java/org/openhab/persistence/rrd4j/internal/RRD4jPersistenceService.java
Labels: bug

#13958 Prevent Markdown rendering issues in Main UI
  bundles/org.openhab.binding.weatherunderground/README.md
  bundles/org.openhab.persistence.rrd4j/README.md
Labels: documentation

#13918 [knx] Minor documentation update
  bundles/org.openhab.binding.knx/README.md
  bundles/org.openhab.binding.knx/src/main/resources/OH-INF/i18n/knx.properties
  bundles/org.openhab.binding.knx/src/main/resources/OH-INF/thing/ip.xml
Labels: documentation

#13963 [wundergroundupdatereceiver] Prevent 😕 showing in documentation
  bundles/org.openhab.binding.wundergroundupdatereceiver/README.md
Labels: documentation

#13964 [mapdb] Add some documentation
  bundles/org.openhab.persistence.mapdb/README.md
Labels: documentation

#13965 [hydrawise] fixes null pointer error for some sprinkler controllers
  bundles/org.openhab.binding.hydrawise/src/main/java/org/openhab/binding/hydrawise/internal/handler/HydrawiseControllerHandler.java
Labels: bug

#13966 [mapdb] Fix "a" typo and use "-" for bullets in docs
  bundles/org.openhab.persistence.mapdb/README.md
Labels: documentation

#13984 [jsscripting] Update add-on name in default translation
  bundles/org.openhab.automation.jsscripting/src/main/resources/OH-INF/i18n/jsscripting.properties
Labels: translation

#13985 [yamaha] README: Recommend correct binding for specific model
  bundles/org.openhab.binding.yamahamusiccast/README.md
  bundles/org.openhab.binding.yamahareceiver/README.md
Labels: documentation

#13954 Fix Zigbee name stylization
  bundles/org.openhab.binding.draytonwiser/src/main/resources/OH-INF/i18n/draytonwiser.properties
  bundles/org.openhab.binding.draytonwiser/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.hue/README.md
  bundles/org.openhab.binding.miele/README.md
  bundles/org.openhab.binding.mielecloud/README.md
  bundles/org.openhab.binding.mihome/README.md
  bundles/org.openhab.binding.openwebnet/README.md
  bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/OpenWebNetBindingConstants.java
  bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/discovery/OpenWebNetDeviceDiscoveryService.java
  bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/discovery/UsbGatewayDiscoveryService.java
  bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/handler/OpenWebNetBridgeHandler.java
  bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/handler/config/OpenWebNetZigBeeBridgeConfig.java
  bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/binding/binding.xml
  bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/i18n/openwebnet.properties
  bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/thing/ZBAutomation.xml
  bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/thing/ZBDimmer.xml
  bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/thing/ZBGateway.xml
  bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/thing/ZBOnOffSwitch.xml
  bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/thing/ZBOnOffSwitch2Units.xml
  bundles/org.openhab.binding.plugwise/README.md
  bundles/org.openhab.binding.plugwise/src/main/java/org/openhab/binding/plugwise/internal/handler/PlugwiseStickHandler.java
  bundles/org.openhab.binding.plugwise/src/main/resources/OH-INF/binding/binding.xml
  bundles/org.openhab.binding.plugwise/src/main/resources/OH-INF/config/config.xml
  bundles/org.openhab.binding.plugwise/src/main/resources/OH-INF/i18n/plugwise.properties
  bundles/org.openhab.binding.plugwise/src/main/resources/OH-INF/thing/circleplus.xml
  bundles/org.openhab.binding.plugwise/src/main/resources/OH-INF/thing/stick.xml
  bundles/org.openhab.binding.plugwiseha/README.md
  bundles/org.openhab.binding.tacmi/README.md
  bundles/org.openhab.binding.tradfri/README.md
  bundles/org.openhab.binding.wemo/README.md
Labels: documentation, translation

#13992 Show add-on intros in Main UI
  bundles/org.openhab.binding.pioneeravr/README.md
  bundles/org.openhab.voice.mactts/README.md
  bundles/org.openhab.voice.marytts/README.md
  bundles/org.openhab.voice.picotts/README.md
  bundles/org.openhab.voice.voicerss/README.md
Labels: documentation

#13994 Fix alignment/indentation in documentation
  bundles/org.openhab.binding.flicbutton/README.md
  bundles/org.openhab.binding.foobot/README.md
  bundles/org.openhab.binding.fsinternetradio/README.md
  bundles/org.openhab.binding.haywardomnilogic/README.md
  bundles/org.openhab.binding.hdpowerview/README.md
  bundles/org.openhab.binding.heos/README.md
  bundles/org.openhab.binding.http/README.md
  bundles/org.openhab.binding.jellyfin/README.md
Labels: documentation

#13996 [wolfsmartset] Fix link to external documentation
  bundles/org.openhab.binding.wolfsmartset/README.md
Labels: documentation

#14000 [airq] StringIndexOutOfBoundsException on empty usercalib
  bundles/org.openhab.binding.airq/src/main/java/org/openhab/binding/airq/internal/AirqHandler.java
Labels: bug

#13997 typos: success, successful
  bundles/org.openhab.binding.bluetooth.bluegiga/src/main/java/org/openhab/binding/bluetooth/bluegiga/handler/BlueGigaBridgeHandler.java
  bundles/org.openhab.binding.etherrain/src/main/java/org/openhab/binding/etherrain/internal/handler/EtherRainHandler.java
  bundles/org.openhab.binding.gree/src/main/java/org/openhab/binding/gree/internal/handler/GreeAirDevice.java
  bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/InstarHandler.java
  bundles/org.openhab.binding.juicenet/src/main/java/org/openhab/binding/juicenet/internal/api/JuiceNetApi.java
  bundles/org.openhab.binding.loxone/README.md
  bundles/org.openhab.binding.loxone/src/main/java/org/openhab/binding/loxone/internal/LxWebSocket.java
  bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/cloud/MiCloudConnector.java
  bundles/org.openhab.binding.ojelectronics/README.md
  bundles/org.openhab.binding.onewire/src/main/java/org/openhab/binding/onewire/internal/handler/OwserverBridgeHandler.java
  bundles/org.openhab.binding.onewire/src/test/java/org/openhab/binding/onewire/owserver/OwserverConnectionTest.java
  bundles/org.openhab.binding.tankerkoenig/src/main/java/org/openhab/binding/tankerkoenig/internal/TankerkoenigBindingConstants.java
  bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/api/TapoDeviceConnector.java
  bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/api/TapoDeviceHttpApi.java
  bundles/org.openhab.binding.velux/README.md
  bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/handler/VeluxBridgeHandler.java
  bundles/org.openhab.binding.verisure/src/main/java/org/openhab/binding/verisure/internal/handler/VerisureSmartLockThingHandler.java
  bundles/org.openhab.persistence.dynamodb/src/main/java/org/openhab/persistence/dynamodb/internal/TableCreatingPutItem.java
Labels: documentation

#14003 [jdbc] Update org.xerial/sqlite-jdbc to 3.40.0.0
  bundles/org.openhab.persistence.jdbc/pom.xml
  bundles/org.openhab.persistence.jdbc/src/main/feature/feature.xml
  bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/JdbcConfiguration.java
Labels: bug

#14010 [shelly] Fix NullPointerException
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/provider/ShellyChannelDefinitions.java
Labels: bug

#13276 Raise minimum JDK version to 17
  CODEOWNERS
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.enocean/src/main/java/org/openhab/binding/enocean/internal/discovery/EnOceanDeviceDiscoveryService.java
  bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/handler/ChannelSceneSilentmode.java
  bundles/org.openhab.transform.javascript/NOTICE
  bundles/org.openhab.transform.javascript/README.md
  bundles/org.openhab.transform.javascript/conf/transform/js/readme/readme.js
  bundles/org.openhab.transform.javascript/conf/transform/readme.js
  bundles/org.openhab.transform.javascript/conf/transform/returntest.js
  bundles/org.openhab.transform.javascript/conf/transform/scale.js
  bundles/org.openhab.transform.javascript/conf/transform/sum.js
  bundles/org.openhab.transform.javascript/src/main/feature/feature.xml
  bundles/org.openhab.transform.javascript/src/main/java/org/openhab/transform/javascript/internal/JavaScriptEngineManager.java
  bundles/org.openhab.transform.javascript/src/main/java/org/openhab/transform/javascript/internal/JavaScriptTransformationService.java
  bundles/org.openhab.transform.javascript/src/main/java/org/openhab/transform/javascript/internal/TransformationScriptWatcher.java
  bundles/org.openhab.transform.javascript/src/main/java/org/openhab/transform/javascript/internal/profiles/JavaScriptTransformationProfile.java
  bundles/org.openhab.transform.javascript/src/main/java/org/openhab/transform/javascript/internal/profiles/JavaScriptTransformationProfileFactory.java
  bundles/org.openhab.transform.javascript/src/main/resources/OH-INF/config/javascriptProfile.xml
  bundles/org.openhab.transform.javascript/src/main/resources/OH-INF/i18n/js.properties
  bundles/org.openhab.transform.javascript/src/main/resources/OH-INF/i18n/js_de.properties
  bundles/org.openhab.transform.javascript/src/main/resources/OH-INF/i18n/js_fi.properties
  bundles/org.openhab.transform.javascript/src/main/resources/OH-INF/i18n/js_fr.properties
  bundles/org.openhab.transform.javascript/src/main/resources/OH-INF/i18n/js_hu.properties
  bundles/org.openhab.transform.javascript/src/test/java/org/openhab/transform/javascript/internal/JavaScriptTransformationServiceTest.java
  bundles/pom.xml
  itests/itest-common.bndrun
  pom.xml
Labels: (potentially) not backward compatible, infrastructure

#14015 [knx] Upgrade Calimero library to release 2.5.1
  bundles/org.openhab.binding.knx/pom.xml
  bundles/org.openhab.binding.knx/src/test/java/org/openhab/binding/knx/internal/dpt/KNXCoreTypeMapperTest.java
Labels: enhancement

#13956 [rrd4j] Upgrade base library from 3.8.1 to 3.8.2
  bundles/org.openhab.persistence.rrd4j/pom.xml
Labels: enhancement

#13991 [jdbc] Upgrade MySQL Connector/J to 8.0.31
  bundles/org.openhab.persistence.jdbc/README.md
  bundles/org.openhab.persistence.jdbc/pom.xml
  bundles/org.openhab.persistence.jdbc/src/main/feature/feature.xml
  bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/JdbcConfiguration.java
Labels: enhancement

#13037 [darksky] Remove DarkSky binding due to EOL of their API
  CODEOWNERS
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.darksky/NOTICE
  bundles/org.openhab.binding.darksky/README.md
  bundles/org.openhab.binding.darksky/pom.xml
  bundles/org.openhab.binding.darksky/src/main/feature/feature.xml
  bundles/org.openhab.binding.darksky/src/main/java/org/openhab/binding/darksky/internal/DarkSkyBindingConstants.java
  bundles/org.openhab.binding.darksky/src/main/java/org/openhab/binding/darksky/internal/config/DarkSkyAPIConfiguration.java
  bundles/org.openhab.binding.darksky/src/main/java/org/openhab/binding/darksky/internal/config/DarkSkyChannelConfiguration.java
  bundles/org.openhab.binding.darksky/src/main/java/org/openhab/binding/darksky/internal/config/DarkSkyWeatherAndForecastConfiguration.java
  bundles/org.openhab.binding.darksky/src/main/java/org/openhab/binding/darksky/internal/connection/DarkSkyCommunicationException.java
  bundles/org.openhab.binding.darksky/src/main/java/org/openhab/binding/darksky/internal/connection/DarkSkyConfigurationException.java
  bundles/org.openhab.binding.darksky/src/main/java/org/openhab/binding/darksky/internal/connection/DarkSkyConnection.java
  bundles/org.openhab.binding.darksky/src/main/java/org/openhab/binding/darksky/internal/discovery/DarkSkyDiscoveryService.java
  bundles/org.openhab.binding.darksky/src/main/java/org/openhab/binding/darksky/internal/factory/DarkSkyHandlerFactory.java
  bundles/org.openhab.binding.darksky/src/main/java/org/openhab/binding/darksky/internal/handler/DarkSkyAPIHandler.java
  bundles/org.openhab.binding.darksky/src/main/java/org/openhab/binding/darksky/internal/handler/DarkSkyWeatherAndForecastHandler.java
  bundles/org.openhab.binding.darksky/src/main/java/org/openhab/binding/darksky/internal/model/DarkSkyCurrentlyData.java
  bundles/org.openhab.binding.darksky/src/main/java/org/openhab/binding/darksky/internal/model/DarkSkyDailyData.java
  bundles/org.openhab.binding.darksky/src/main/java/org/openhab/binding/darksky/internal/model/DarkSkyHourlyData.java
  bundles/org.openhab.binding.darksky/src/main/java/org/openhab/binding/darksky/internal/model/DarkSkyJsonWeatherData.java
  bundles/org.openhab.binding.darksky/src/main/resources/OH-INF/binding/binding.xml
  bundles/org.openhab.binding.darksky/src/main/resources/OH-INF/config/config.xml
  bundles/org.openhab.binding.darksky/src/main/resources/OH-INF/i18n/darksky.properties
  bundles/org.openhab.binding.darksky/src/main/resources/OH-INF/i18n/darksky_de.properties
  bundles/org.openhab.binding.darksky/src/main/resources/OH-INF/i18n/darksky_hu.properties
  bundles/org.openhab.binding.darksky/src/main/resources/OH-INF/thing/bridge-types.xml
  bundles/org.openhab.binding.darksky/src/main/resources/OH-INF/thing/channel-types.xml
  bundles/org.openhab.binding.darksky/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/pom.xml
Labels: enhancement

#14024 [hue] Allow handling of QuantityType for color temperature channel
  bundles/org.openhab.binding.hue/README.md
  bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/HueGroupHandler.java
  bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/HueLightHandler.java
  bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/LightStateConverter.java
  bundles/org.openhab.binding.hue/src/test/java/org/openhab/binding/hue/internal/handler/HueLightHandlerTest.java
Labels: bug, patch

#14029 [dali] tweak color temperature abs QuantityType fix
  bundles/org.openhab.binding.dali/README.md
  bundles/org.openhab.binding.dali/src/main/java/org/openhab/binding/dali/internal/handler/DaliDt8DeviceHandler.java
Labels: bug, additional testing preferred, patch

#14026 [nanoleaf] Handle and provide QuantityType for color-temperature-abs channel
  bundles/org.openhab.binding.nanoleaf/README.md
  bundles/org.openhab.binding.nanoleaf/src/main/java/org/openhab/binding/nanoleaf/internal/handler/NanoleafControllerHandler.java
Labels: bug, additional testing preferred, patch

#14031 [keba] Fix unit in example for power channel
  bundles/org.openhab.binding.keba/README.md
Labels: documentation

#14039 [fineoffsetweatherstation] Fix QuantityType for rain-rate
  bundles/org.openhab.binding.fineoffsetweatherstation/README.md
  bundles/org.openhab.binding.fineoffsetweatherstation/src/main/resources/OH-INF/thing/gateway.xml
Labels: bug, documentation

#13982 [homekit] implement List-Pairings method
  bundles/org.openhab.io.homekit/pom.xml
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitAuthInfoImpl.java
Labels: bug, patch

#14025 [lifx] Handle and provide QuantityType for color-temperature-abs channel
  bundles/org.openhab.binding.lifx/README.md
  bundles/org.openhab.binding.lifx/src/main/java/org/openhab/binding/lifx/internal/handler/LifxLightHandler.java
  bundles/org.openhab.binding.lifx/src/main/java/org/openhab/binding/lifx/internal/util/LifxMessageUtil.java
Labels: bug, additional testing preferred, patch

#13998 [nanoleaf] More robust caching of layout
  bundles/org.openhab.binding.nanoleaf/src/main/java/org/openhab/binding/nanoleaf/internal/handler/NanoleafControllerHandler.java
Labels: bug

#14013 [jsscriptingnashorn] JavaScript Scripting Nashorn Automation
  CODEOWNERS
  bom/openhab-addons/pom.xml
  bundles/org.openhab.automation.jsscriptingnashorn/NOTICE
  bundles/org.openhab.automation.jsscriptingnashorn/README.md
  bundles/org.openhab.automation.jsscriptingnashorn/pom.xml
  bundles/org.openhab.automation.jsscriptingnashorn/src/main/feature/feature.xml
  bundles/org.openhab.automation.jsscriptingnashorn/src/main/java/org/openhab/automation/jsscriptingnashorn/internal/NashornScriptEngineFactory.java
  bundles/org.openhab.automation.jsscriptingnashorn/src/main/java/org/openhab/automation/jsscriptingnashorn/internal/package-info.java
  bundles/org.openhab.automation.jsscriptingnashorn/src/test/java/org/openhab/automation/jsscriptingnashorn/NashornScriptEngineFactoryTest.java
  bundles/pom.xml
  itests/org.openhab.automation.jsscriptingnashorn.tests/NOTICE
  itests/org.openhab.automation.jsscriptingnashorn.tests/itest.bndrun
  itests/org.openhab.automation.jsscriptingnashorn.tests/pom.xml
  itests/org.openhab.automation.jsscriptingnashorn.tests/src/main/java/org/openhab/automation/jsscriptingnashorn/ScriptScopeOSGiTest.java
  itests/org.openhab.automation.jsscriptingnashorn.tests/src/main/resources/OH-INF/automation/jsr223/scopeFailure.nashornjs
  itests/org.openhab.automation.jsscriptingnashorn.tests/src/main/resources/OH-INF/automation/jsr223/scopeWorking.nashornjs
  itests/pom.xml
Labels: new automation

#14062 [tplinksmarthome] Document sending raw commands to devices
  bundles/org.openhab.binding.tplinksmarthome/README.md
Labels: documentation

#14068 [rrd4j] Improve logging of exceptions thrown by getDB
  bundles/org.openhab.persistence.rrd4j/src/main/java/org/openhab/persistence/rrd4j/internal/RRD4jPersistenceService.java
Labels: enhancement

#14054 [jdbc] Fix IllegalArgumentException on service activation
  bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/JdbcMapper.java
Labels: bug, patch

#14045 [homekit] support Rollershutter items for HoldPosition
  bundles/org.openhab.io.homekit/README.md
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitCharacteristicFactory.java
Labels: enhancement

#14012 [nuvo] Auto update source channel for grouped zones
  bundles/org.openhab.binding.nuvo/README.md
  bundles/org.openhab.binding.nuvo/src/main/java/org/openhab/binding/nuvo/internal/communication/NuvoCommand.java
  bundles/org.openhab.binding.nuvo/src/main/java/org/openhab/binding/nuvo/internal/handler/NuvoHandler.java
Labels: enhancement

#14067 [astro] Added moon phase precision
  bundles/org.openhab.binding.astro/src/main/java/org/openhab/binding/astro/internal/calc/MoonCalc.java
  bundles/org.openhab.binding.astro/src/main/java/org/openhab/binding/astro/internal/model/MoonPhase.java
Labels: bug

#14009 [velux] Updated Discovery instructions for scenes and actuators
  bundles/org.openhab.binding.velux/README.md
Labels: documentation

#14033 [hdpowerview] Remove deprecated scene channels
  bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/handler/HDPowerViewHubHandler.java
  bundles/org.openhab.binding.hdpowerview/src/main/resources/OH-INF/i18n/hdpowerview.properties
Labels: enhancement

#13923 [hueemulation] Fix for Alexa failing to discover all devices.
  bundles/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/ConfigStore.java
  bundles/org.openhab.io.hueemulation/src/test/java/org/openhab/io/hueemulation/internal/rest/CommonSetup.java
  bundles/org.openhab.io.hueemulation/src/test/java/org/openhab/io/hueemulation/internal/rest/ItemUIDtoHueIDMappingTests.java
  bundles/org.openhab.io.hueemulation/src/test/java/org/openhab/io/hueemulation/internal/upnp/UpnpTests.java
Labels: bug

#14077 Update i18n command version number
  README.md
Labels: documentation

#14030 [danfossairunit] Remove deprecated channel 'manual_fan_speed'
  bundles/org.openhab.binding.danfossairunit/src/main/java/org/openhab/binding/danfossairunit/internal/Channel.java
  bundles/org.openhab.binding.danfossairunit/src/main/java/org/openhab/binding/danfossairunit/internal/handler/DanfossAirUnitHandler.java
  bundles/org.openhab.binding.danfossairunit/src/main/resources/OH-INF/i18n/danfossairunit.properties
  bundles/org.openhab.binding.danfossairunit/src/main/resources/OH-INF/thing/thing-types.xml
Labels: enhancement

#14108 [daikin] Add support for Alira X
  bundles/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/api/ControlInfo.java
  bundles/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/api/InfoParser.java
  bundles/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/api/airbase/AirbaseControlInfo.java
  bundles/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/api/airbase/AirbaseModelInfo.java
  bundles/org.openhab.binding.daikin/src/test/java/org/openhab/binding/daikin/internal/api/ControlInfoTest.java
Labels: enhancement

#14109 Add Stale configuration
  .github/stale.yml
Labels: infrastructure

#14115 [groovyscripting] Update Groovy to 4.0.7
  bundles/org.openhab.automation.groovyscripting/README.md
  bundles/org.openhab.automation.groovyscripting/pom.xml
Labels: enhancement

#14103 [bondhome] Fix fatal Null Pointer errors
  bundles/org.openhab.binding.bondhome/src/main/java/org/openhab/binding/bondhome/internal/api/BondDeviceType.java
  bundles/org.openhab.binding.bondhome/src/main/java/org/openhab/binding/bondhome/internal/api/BondHttpApi.java
  bundles/org.openhab.binding.bondhome/src/main/java/org/openhab/binding/bondhome/internal/discovery/BondDiscoveryService.java
  bundles/org.openhab.binding.bondhome/src/main/resources/OH-INF/i18n/bondhome.properties
Labels: bug

#14099 [mqtt] Fix shutdownRetain default value
  bundles/org.openhab.binding.mqtt/src/main/resources/OH-INF/thing/thing-types.xml
Labels: bug

#14097 [bosesoundtouch] Fix regression and add tests
  bundles/org.openhab.binding.bosesoundtouch/src/main/java/org/openhab/binding/bosesoundtouch/internal/CommandExecutor.java
  bundles/org.openhab.binding.bosesoundtouch/src/main/java/org/openhab/binding/bosesoundtouch/internal/XMLResponseHandler.java
  bundles/org.openhab.binding.bosesoundtouch/src/main/java/org/openhab/binding/bosesoundtouch/internal/XMLResponseProcessor.java
  bundles/org.openhab.binding.bosesoundtouch/src/main/java/org/openhab/binding/bosesoundtouch/internal/handler/BoseSoundTouchHandler.java
  bundles/org.openhab.binding.bosesoundtouch/src/test/java/org/openhab/binding/bosesoundtouch/internal/SoundTouch20Tests.java
  bundles/org.openhab.binding.bosesoundtouch/src/test/java/org/openhab/binding/bosesoundtouch/internal/handler/InMemmoryContentStorage.java
Labels: bug, patch

#14114 [knx] Add color channel to knx binding docu
  bundles/org.openhab.binding.knx/README.md
Labels: documentation

#14116 Update Jackson version to 2.14.1
  itests/org.openhab.binding.mqtt.homeassistant.tests/itest.bndrun
  itests/org.openhab.binding.mqtt.homie.tests/itest.bndrun
  itests/org.openhab.binding.nest.tests/itest.bndrun
  pom.xml
Labels: awaiting other PR

#14093 [jsscripting] Upgrade to ECMAScript 2022 & Dependency improvements
  bundles/org.openhab.automation.jsscripting/pom.xml
  bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/OpenhabGraalJSScriptEngine.java
Labels: enhancement

#14113 [jsscripting] Improve performance & reduce memory usage
  bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/OpenhabGraalJSScriptEngine.java
Labels: enhancement

#14080 [atlona] Add support for AT-PRO3HD44M
  bundles/org.openhab.binding.atlona/README.md
  bundles/org.openhab.binding.atlona/src/main/feature/feature.xml
  bundles/org.openhab.binding.atlona/src/main/java/org/openhab/binding/atlona/internal/AtlonaBindingConstants.java
  bundles/org.openhab.binding.atlona/src/main/java/org/openhab/binding/atlona/internal/AtlonaHandlerFactory.java
  bundles/org.openhab.binding.atlona/src/main/resources/OH-INF/binding/binding.xml
  bundles/org.openhab.binding.atlona/src/main/resources/OH-INF/i18n/atlona.properties
  bundles/org.openhab.binding.atlona/src/main/resources/OH-INF/thing/thing-types.xml
Labels: enhancement

#14070 [tesla] Fix discovery of Tesla vehicles from account
  bundles/org.openhab.binding.tesla/README.md
  bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/TeslaBindingConstants.java
  bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/TeslaHandlerFactory.java
  bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/discovery/TeslaVehicleDiscoveryService.java
  bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/handler/TeslaAccountHandler.java
  bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/handler/VehicleListener.java
  bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/protocol/VehicleConfig.java
  bundles/org.openhab.binding.tesla/src/main/resources/OH-INF/i18n/tesla.properties
  bundles/org.openhab.binding.tesla/src/main/resources/OH-INF/thing/channels.xml
  bundles/org.openhab.binding.tesla/src/main/resources/OH-INF/thing/vehicle.xml
Labels: bug

#14060 [unifi] Fix PoE bug with combination of other data/ports
  bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/api/UniFiController.java
  bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/api/UniFiControllerRequest.java
  bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/api/cache/UniFiCache.java
  bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/api/cache/UniFiControllerCache.java
  bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/api/cache/UniFiDeviceCache.java
  bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/api/dto/UnfiPortOverrideJsonObject.java
  bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/api/dto/UniFiDevice.java
  bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/api/dto/UniFiPortTuple.java
  bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/api/dto/UniFiSwitchPorts.java
  bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/api/util/UnfiPortOverrideJsonElementDeserializer.java
  bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/handler/UniFiBaseThingHandler.java
  bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/handler/UniFiControllerThingHandler.java
  bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/handler/UniFiPoePortThingHandler.java
  bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/handler/UniFiThingDiscoveryService.java
  bundles/org.openhab.binding.unifi/src/main/resources/OH-INF/i18n/unifi.properties
Labels: bug

#14078 [astro] Fix returning wrong sun phase name
  bundles/org.openhab.binding.astro/src/main/java/org/openhab/binding/astro/internal/calc/SunCalc.java
  bundles/org.openhab.binding.astro/src/main/java/org/openhab/binding/astro/internal/calc/SunZodiacCalc.java
  bundles/org.openhab.binding.astro/src/main/java/org/openhab/binding/astro/internal/job/Job.java
  bundles/org.openhab.binding.astro/src/main/java/org/openhab/binding/astro/internal/model/MoonPhase.java
  bundles/org.openhab.binding.astro/src/main/java/org/openhab/binding/astro/internal/model/Range.java
  bundles/org.openhab.binding.astro/src/test/java/org/openhab/binding/astro/internal/calc/SunCalcTest.java
  bundles/org.openhab.binding.astro/src/test/java/org/openhab/binding/astro/internal/model/SunTest.java
Labels: bug

#13940 [miio] add support ROIDMI EVA - roidmi.vacuum.v66
  bundles/org.openhab.binding.miio/README.md
  bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/MiIoDevices.java
  bundles/org.openhab.binding.miio/src/main/resources/OH-INF/i18n/basic.properties
  bundles/org.openhab.binding.miio/src/main/resources/database/roidmi.vacuum.v66-moit.json
Labels: enhancement

#13939 [velbus] Add modules VMBKP, VMBIN, VMB4PB
  bundles/org.openhab.binding.velbus/src/main/java/org/openhab/binding/velbus/internal/VelbusBindingConstants.java
  bundles/org.openhab.binding.velbus/src/main/java/org/openhab/binding/velbus/internal/discovery/VelbusThingDiscoveryService.java
  bundles/org.openhab.binding.velbus/src/main/java/org/openhab/binding/velbus/internal/handler/VelbusSensorWithAlarmClockHandler.java
  bundles/org.openhab.binding.velbus/src/main/resources/OH-INF/i18n/velbus.properties
  bundles/org.openhab.binding.velbus/src/main/resources/OH-INF/thing/thing-types.xml
Labels: enhancement
