Repository openhab/openhab-addons, pull requests merged in 2022-09, with the labels that each got.

#13239 [mimictts] Use http method POST instead of GET
  bundles/org.openhab.voice.mimictts/src/main/java/org/openhab/voice/mimic/internal/InputStreamAudioStream.java
  bundles/org.openhab.voice.mimictts/src/main/java/org/openhab/voice/mimic/internal/MimicTTSService.java
  bundles/org.openhab.voice.mimictts/src/main/java/org/openhab/voice/mimic/internal/dto/VoiceDto.java
Labels: enhancement

#13306 [hccrubbishcollection] Update API URL
  bundles/org.openhab.binding.hccrubbishcollection/src/main/java/org/openhab/binding/hccrubbishcollection/internal/API.java
Labels: bug

#13317 [avmfritz] Allow to set every userdefined color
  bundles/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/dto/ColorControlModel.java
  bundles/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/dto/HeatingModel.java
  bundles/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/handler/AVMFritzBaseThingHandler.java
  bundles/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/hardware/FritzAhaWebInterface.java
  bundles/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/hardware/callbacks/FritzAhaSetColorCallback.java
  bundles/org.openhab.binding.avmfritz/src/test/java/org/openhab/binding/avmfritz/internal/dto/AVMFritzDeviceListModelTest.java
  bundles/org.openhab.binding.avmfritz/src/test/java/org/openhab/binding/avmfritz/internal/dto/ColorControlModelTest.java
  bundles/org.openhab.binding.avmfritz/src/test/java/org/openhab/binding/avmfritz/internal/dto/HeatingModelTest.java
Labels: bug

#13345 [nuvo] Fix MPS4 flag and online status reporting
  bundles/org.openhab.binding.nuvo/src/main/java/org/openhab/binding/nuvo/internal/communication/NuvoStatusCodes.java
  bundles/org.openhab.binding.nuvo/src/main/java/org/openhab/binding/nuvo/internal/handler/NuvoHandler.java
Labels: bug

#13350 [remoteopenhab] Handle REFRESH command as any command
  bundles/org.openhab.binding.remoteopenhab/src/main/java/org/openhab/binding/remoteopenhab/internal/handler/RemoteopenhabBridgeHandler.java
Labels: bug

#13349 [remoteopenhab] Fix the pattern to parse DateTime
  bundles/org.openhab.binding.remoteopenhab/src/main/java/org/openhab/binding/remoteopenhab/internal/handler/RemoteopenhabBridgeHandler.java
Labels: bug

#13363 [Konnected] Fixed example thing. Made names less ambiguous
  bundles/org.openhab.binding.konnected/README.md
Labels: documentation

#13360 [Konnected] Taking configured onValue into account when sending status to actuator
  bundles/org.openhab.binding.konnected/README.md
  bundles/org.openhab.binding.konnected/src/main/java/org/openhab/binding/konnected/internal/handler/KonnectedHandler.java
Labels: bug

#13330 [hdpowerview] Correct shade capabilities information
  bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/database/ShadeCapabilitiesDatabase.java
  bundles/org.openhab.binding.hdpowerview/src/test/java/org/openhab/binding/hdpowerview/ShadePositionTest.java
Labels: enhancement

#12954 [Easee] Initial contribution
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.easee/NOTICE
  bundles/org.openhab.binding.easee/README.md
  bundles/org.openhab.binding.easee/pom.xml
  bundles/org.openhab.binding.easee/src/main/feature/feature.xml
  bundles/org.openhab.binding.easee/src/main/java/org/openhab/binding/easee/internal/AtomicReferenceTrait.java
  bundles/org.openhab.binding.easee/src/main/java/org/openhab/binding/easee/internal/EaseeBindingConstants.java
  bundles/org.openhab.binding.easee/src/main/java/org/openhab/binding/easee/internal/EaseeHandlerFactory.java
  bundles/org.openhab.binding.easee/src/main/java/org/openhab/binding/easee/internal/Utils.java
  bundles/org.openhab.binding.easee/src/main/java/org/openhab/binding/easee/internal/command/AbstractCommand.java
  bundles/org.openhab.binding.easee/src/main/java/org/openhab/binding/easee/internal/command/AbstractWriteCommand.java
  bundles/org.openhab.binding.easee/src/main/java/org/openhab/binding/easee/internal/command/EaseeCommand.java
  bundles/org.openhab.binding.easee/src/main/java/org/openhab/binding/easee/internal/command/JsonResultProcessor.java
  bundles/org.openhab.binding.easee/src/main/java/org/openhab/binding/easee/internal/command/account/Login.java
  bundles/org.openhab.binding.easee/src/main/java/org/openhab/binding/easee/internal/command/account/RefreshToken.java
  bundles/org.openhab.binding.easee/src/main/java/org/openhab/binding/easee/internal/command/charger/ChangeConfiguration.java
  bundles/org.openhab.binding.easee/src/main/java/org/openhab/binding/easee/internal/command/charger/Charger.java
  bundles/org.openhab.binding.easee/src/main/java/org/openhab/binding/easee/internal/command/charger/ChargerState.java
  bundles/org.openhab.binding.easee/src/main/java/org/openhab/binding/easee/internal/command/charger/GetConfiguration.java
  bundles/org.openhab.binding.easee/src/main/java/org/openhab/binding/easee/internal/command/charger/LatestChargingSession.java
  bundles/org.openhab.binding.easee/src/main/java/org/openhab/binding/easee/internal/command/charger/SendCommand.java
  bundles/org.openhab.binding.easee/src/main/java/org/openhab/binding/easee/internal/command/charger/SendCommandPauseResume.java
  bundles/org.openhab.binding.easee/src/main/java/org/openhab/binding/easee/internal/command/charger/SendCommandStartStop.java
  bundles/org.openhab.binding.easee/src/main/java/org/openhab/binding/easee/internal/command/circuit/CircuitSettings.java
  bundles/org.openhab.binding.easee/src/main/java/org/openhab/binding/easee/internal/command/circuit/DynamicCircuitCurrent.java
  bundles/org.openhab.binding.easee/src/main/java/org/openhab/binding/easee/internal/command/circuit/SetCircuitSettings.java
  bundles/org.openhab.binding.easee/src/main/java/org/openhab/binding/easee/internal/command/circuit/SetDynamicCircuitCurrents.java
  bundles/org.openhab.binding.easee/src/main/java/org/openhab/binding/easee/internal/command/circuit/SetMaxCircuitCurrents.java
  bundles/org.openhab.binding.easee/src/main/java/org/openhab/binding/easee/internal/command/circuit/SetOfflineMaxCircuitCurrents.java
  bundles/org.openhab.binding.easee/src/main/java/org/openhab/binding/easee/internal/command/site/GetSite.java
  bundles/org.openhab.binding.easee/src/main/java/org/openhab/binding/easee/internal/config/EaseeConfiguration.java
  bundles/org.openhab.binding.easee/src/main/java/org/openhab/binding/easee/internal/connector/CommunicationStatus.java
  bundles/org.openhab.binding.easee/src/main/java/org/openhab/binding/easee/internal/connector/WebInterface.java
  bundles/org.openhab.binding.easee/src/main/java/org/openhab/binding/easee/internal/discovery/EaseeSiteDiscoveryService.java
  bundles/org.openhab.binding.easee/src/main/java/org/openhab/binding/easee/internal/handler/ChannelProvider.java
  bundles/org.openhab.binding.easee/src/main/java/org/openhab/binding/easee/internal/handler/EaseeBridgeHandler.java
  bundles/org.openhab.binding.easee/src/main/java/org/openhab/binding/easee/internal/handler/EaseeChargerHandler.java
  bundles/org.openhab.binding.easee/src/main/java/org/openhab/binding/easee/internal/handler/EaseeMasterChargerHandler.java
  bundles/org.openhab.binding.easee/src/main/java/org/openhab/binding/easee/internal/handler/EaseeSiteHandler.java
  bundles/org.openhab.binding.easee/src/main/java/org/openhab/binding/easee/internal/handler/EaseeThingHandler.java
  bundles/org.openhab.binding.easee/src/main/java/org/openhab/binding/easee/internal/handler/StatusHandler.java
  bundles/org.openhab.binding.easee/src/main/java/org/openhab/binding/easee/internal/model/ConfigurationException.java
  bundles/org.openhab.binding.easee/src/main/java/org/openhab/binding/easee/internal/model/CustomResponseTransformer.java
  bundles/org.openhab.binding.easee/src/main/java/org/openhab/binding/easee/internal/model/GenericResponseTransformer.java
  bundles/org.openhab.binding.easee/src/main/java/org/openhab/binding/easee/internal/model/ValidationException.java
  bundles/org.openhab.binding.easee/src/main/resources/OH-INF/binding/binding.xml
  bundles/org.openhab.binding.easee/src/main/resources/OH-INF/config/config.xml
  bundles/org.openhab.binding.easee/src/main/resources/OH-INF/i18n/easee.properties
  bundles/org.openhab.binding.easee/src/main/resources/OH-INF/thing/charger-channel-groups.xml
  bundles/org.openhab.binding.easee/src/main/resources/OH-INF/thing/circuit-channel-groups.xml
  bundles/org.openhab.binding.easee/src/main/resources/OH-INF/thing/easee-readonly-channel-types.xml
  bundles/org.openhab.binding.easee/src/main/resources/OH-INF/thing/easee-readwrite-channel-types.xml
  bundles/org.openhab.binding.easee/src/main/resources/OH-INF/thing/things.xml
  bundles/pom.xml
Labels: new binding

#13362 [unifi] Fix portoverride to not remove any other data
  bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/api/UniFiController.java
  bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/api/UniFiControllerRequest.java
  bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/api/cache/UniFiControllerCache.java
  bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/api/dto/UnfiPortOverride.java
  bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/api/dto/UnfiPortOverrideJsonElement.java
  bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/api/dto/UniFiDevice.java
  bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/api/dto/UniFiPortOverrides.java
  bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/api/dto/UniFiPortTable.java
  bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/api/dto/UniFiPortTuple.java
  bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/api/util/UnfiPortOverrideJsonElementDeserializer.java
  bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/handler/UniFiPoePortThingHandler.java
  bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/handler/UniFiThingDiscoveryService.java
  bundles/org.openhab.binding.unifi/src/main/resources/OH-INF/i18n/unifi.properties
Labels: bug

#13348 [linky] Docker specificities
  bundles/org.openhab.binding.linky/README.md
Labels: documentation

#13285 [rotel] New channel to select FM/DAB/iRadio preset
  bundles/org.openhab.binding.rotel/README.md
  bundles/org.openhab.binding.rotel/src/main/java/org/openhab/binding/rotel/internal/RotelBindingConstants.java
  bundles/org.openhab.binding.rotel/src/main/java/org/openhab/binding/rotel/internal/communication/RotelCommand.java
  bundles/org.openhab.binding.rotel/src/main/java/org/openhab/binding/rotel/internal/communication/RotelSimuConnector.java
  bundles/org.openhab.binding.rotel/src/main/java/org/openhab/binding/rotel/internal/handler/RotelHandler.java
  bundles/org.openhab.binding.rotel/src/main/java/org/openhab/binding/rotel/internal/protocol/ascii/RotelAsciiV1ProtocolHandler.java
  bundles/org.openhab.binding.rotel/src/main/java/org/openhab/binding/rotel/internal/protocol/ascii/RotelAsciiV2ProtocolHandler.java
  bundles/org.openhab.binding.rotel/src/main/resources/OH-INF/i18n/rotel.properties
  bundles/org.openhab.binding.rotel/src/main/resources/OH-INF/thing/channels.xml
  bundles/org.openhab.binding.rotel/src/main/resources/OH-INF/thing/rcx1500.xml
  bundles/org.openhab.binding.rotel/src/main/resources/OH-INF/thing/rdg1520.xml
  bundles/org.openhab.binding.rotel/src/main/resources/OH-INF/thing/rt11.xml
  bundles/org.openhab.binding.rotel/src/main/resources/OH-INF/thing/rt1570.xml
  bundles/org.openhab.binding.rotel/src/main/resources/OH-INF/thing/t11.xml
  bundles/org.openhab.binding.rotel/src/main/resources/OH-INF/thing/t14.xml
Labels: enhancement

#13292 [systeminfo] Add CPU load channel, update dependencies
  bundles/org.openhab.binding.systeminfo/README.md
  bundles/org.openhab.binding.systeminfo/pom.xml
  bundles/org.openhab.binding.systeminfo/src/main/feature/feature.xml
  bundles/org.openhab.binding.systeminfo/src/main/java/org/openhab/binding/systeminfo/internal/handler/SysteminfoHandler.java
  bundles/org.openhab.binding.systeminfo/src/main/java/org/openhab/binding/systeminfo/internal/model/OSHISysteminfo.java
  bundles/org.openhab.binding.systeminfo/src/main/java/org/openhab/binding/systeminfo/internal/model/SysteminfoInterface.java
  bundles/org.openhab.binding.systeminfo/src/main/resources/OH-INF/i18n/systeminfo.properties
  bundles/org.openhab.binding.systeminfo/src/main/resources/OH-INF/thing/channels.xml
  itests/org.openhab.binding.systeminfo.tests/itest.bndrun
  itests/org.openhab.binding.systeminfo.tests/pom.xml
  itests/org.openhab.binding.systeminfo.tests/src/main/java/org/openhab/binding/systeminfo/test/SysteminfoOSGiTest.java
Labels: enhancement

#13271 [velux] Vane position channel is visible when required
  bundles/org.openhab.binding.velux/README.md
  bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/handler/VeluxBridgeHandler.java
  bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/handler/VeluxHandler.java
  bundles/org.openhab.binding.velux/src/main/resources/OH-INF/i18n/velux.properties
  bundles/org.openhab.binding.velux/src/main/resources/OH-INF/thing/channels.xml
  bundles/org.openhab.binding.velux/src/main/resources/OH-INF/thing/rollershutter.xml
  bundles/org.openhab.binding.velux/src/main/resources/OH-INF/thing/window.xml
Labels: enhancement, (potentially) not backward compatible

#13379 [velux] Correction to channel label
  bundles/org.openhab.binding.velux/src/main/resources/OH-INF/i18n/velux.properties
Labels: enhancement

#13381 [fineoffsetweatherstation] Fix measurands
  bundles/org.openhab.binding.fineoffsetweatherstation/src/main/java/org/openhab/binding/fineoffsetweatherstation/internal/domain/Measurand.java
Labels: bug

#13382 [jdbc] Fix date cast exception
  bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/db/JdbcBaseDAO.java
Labels: bug

#13387 [easee] fix special characters in README.md
  bundles/org.openhab.binding.easee/README.md
Labels: documentation

#13386 [groupepsa] Consider TimeZoneProvider to build states for time-stamp channels
  bundles/org.openhab.binding.groupepsa/README.md
  bundles/org.openhab.binding.groupepsa/src/main/java/org/openhab/binding/groupepsa/internal/GroupePSAHandlerFactory.java
  bundles/org.openhab.binding.groupepsa/src/main/java/org/openhab/binding/groupepsa/internal/things/GroupePSAHandler.java
  bundles/org.openhab.binding.groupepsa/src/test/java/org/openhab/binding/groupepsa/internal/things/GroupePSAHandlerTest.java
Labels: enhancement

#13391 [vosk] Upgrade sdk and handle UnsatisfiedLinkError exceptions
  bundles/org.openhab.voice.voskstt/pom.xml
  bundles/org.openhab.voice.voskstt/src/main/java/org/openhab/voice/voskstt/internal/VoskSTTService.java
Labels: enhancement

#13396 [ipcamera] Fix ONVIF fails to reconnect
  bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/handler/IpCameraHandler.java
  bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/onvif/OnvifConnection.java
  bundles/org.openhab.binding.ipcamera/src/main/resources/OH-INF/thing/thing-types.xml
Labels: bug

#13380 [Konnected] Configure zone on panel even if the channel is not yet linked
  bundles/org.openhab.binding.konnected/src/main/java/org/openhab/binding/konnected/internal/handler/KonnectedHandler.java
Labels: bug

#13394 [radiothermostat] Ignore updates if thermostat data is invalid
  bundles/org.openhab.binding.radiothermostat/src/main/java/org/openhab/binding/radiothermostat/internal/handler/RadioThermostatHandler.java
Labels: bug

#13408 [openwebnet] improved README for AUX and ENERGY
  bundles/org.openhab.binding.openwebnet/README.md
Labels: documentation

#13390 [androiddebugbridge] Fix get current package and get MAC address.
  bundles/org.openhab.binding.androiddebugbridge/src/main/java/org/openhab/binding/androiddebugbridge/internal/AndroidDebugBridgeDevice.java
  bundles/org.openhab.binding.androiddebugbridge/src/main/java/org/openhab/binding/androiddebugbridge/internal/AndroidDebugBridgeHandler.java
Labels: bug

#13404 [ecowatt] Initial contribution
  CODEOWNERS
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.ecowatt/NOTICE
  bundles/org.openhab.binding.ecowatt/README.md
  bundles/org.openhab.binding.ecowatt/pom.xml
  bundles/org.openhab.binding.ecowatt/src/main/feature/feature.xml
  bundles/org.openhab.binding.ecowatt/src/main/java/org/openhab/binding/ecowatt/internal/EcowattBindingConstants.java
  bundles/org.openhab.binding.ecowatt/src/main/java/org/openhab/binding/ecowatt/internal/EcowattHandlerFactory.java
  bundles/org.openhab.binding.ecowatt/src/main/java/org/openhab/binding/ecowatt/internal/configuration/EcowattConfiguration.java
  bundles/org.openhab.binding.ecowatt/src/main/java/org/openhab/binding/ecowatt/internal/exception/EcowattApiLimitException.java
  bundles/org.openhab.binding.ecowatt/src/main/java/org/openhab/binding/ecowatt/internal/handler/EcowattHandler.java
  bundles/org.openhab.binding.ecowatt/src/main/java/org/openhab/binding/ecowatt/internal/restapi/EcowattApiResponse.java
  bundles/org.openhab.binding.ecowatt/src/main/java/org/openhab/binding/ecowatt/internal/restapi/EcowattDaySignals.java
  bundles/org.openhab.binding.ecowatt/src/main/java/org/openhab/binding/ecowatt/internal/restapi/EcowattHourSignal.java
  bundles/org.openhab.binding.ecowatt/src/main/java/org/openhab/binding/ecowatt/internal/restapi/EcowattRestApi.java
  bundles/org.openhab.binding.ecowatt/src/main/resources/OH-INF/binding/binding.xml
  bundles/org.openhab.binding.ecowatt/src/main/resources/OH-INF/i18n/ecowatt.properties
  bundles/org.openhab.binding.ecowatt/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/pom.xml
Labels: new binding

#13398 [mqtt.homeassistant] sensors with a state_class are numeric
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/Sensor.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/component/SensorTests.java
Labels: bug

#13402 [mqtt.homeassistant] More readable label for discovered things
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/discovery/HomeAssistantDiscovery.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/discovery/HomeAssistantDiscoveryTests.java
Labels: enhancement

#13410 [mercedesme] Fix typo in readme: callbackIP config parameter
  bundles/org.openhab.binding.mercedesme/README.md
Labels: documentation

#12042 [nuvo] Add NuvoNet source communication capabilities
  bundles/org.openhab.binding.nuvo/README.md
  bundles/org.openhab.binding.nuvo/doc/NuvoMenu.xsd
  bundles/org.openhab.binding.nuvo/src/main/java/org/openhab/binding/nuvo/internal/NuvoBindingConstants.java
  bundles/org.openhab.binding.nuvo/src/main/java/org/openhab/binding/nuvo/internal/NuvoHandlerFactory.java
  bundles/org.openhab.binding.nuvo/src/main/java/org/openhab/binding/nuvo/internal/communication/NuvoConnector.java
  bundles/org.openhab.binding.nuvo/src/main/java/org/openhab/binding/nuvo/internal/communication/NuvoImageResizer.java
  bundles/org.openhab.binding.nuvo/src/main/java/org/openhab/binding/nuvo/internal/communication/NuvoStatusCodes.java
  bundles/org.openhab.binding.nuvo/src/main/java/org/openhab/binding/nuvo/internal/configuration/NuvoThingConfiguration.java
  bundles/org.openhab.binding.nuvo/src/main/java/org/openhab/binding/nuvo/internal/dto/JAXBUtils.java
  bundles/org.openhab.binding.nuvo/src/main/java/org/openhab/binding/nuvo/internal/dto/NuvoMenu.java
  bundles/org.openhab.binding.nuvo/src/main/java/org/openhab/binding/nuvo/internal/handler/NuvoHandler.java
  bundles/org.openhab.binding.nuvo/src/main/resources/OH-INF/i18n/nuvo.properties
  bundles/org.openhab.binding.nuvo/src/main/resources/OH-INF/thing/channels.xml
Labels: enhancement

#12430 [openhabcloud] improved logging for troubleshooting purposes
  bundles/org.openhab.io.openhabcloud/src/main/java/org/openhab/io/openhabcloud/internal/CloudClient.java
  bundles/org.openhab.io.openhabcloud/src/main/java/org/openhab/io/openhabcloud/internal/CloudService.java
Labels: enhancement

#13397 [mqtt.homeassistant] support availability_templates
  bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/AbstractMQTTThingHandler.java
  bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/AvailabilityTracker.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/AbstractComponent.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/config/dto/AbstractChannelConfiguration.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/config/dto/Availability.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/component/AbstractComponentTests.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/component/SensorTests.java
Labels: enhancement

#13407 Update Shelly and Tradfri bindings for upgrade to Californium 2.7.3
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api1/Shelly1CoapServer.java
  bundles/org.openhab.binding.tradfri/src/main/java/org/openhab/binding/tradfri/internal/handler/TradfriGatewayHandler.java
  itests/org.openhab.binding.tradfri.tests/itest.bndrun
  itests/org.openhab.binding.tradfri.tests/src/main/java/org/openhab/binding/tradfri/internal/handler/TradfriHandlerOSGiTest.java
Labels: enhancement

#13425 [jdbc] Fix date cast exception
  bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/db/JdbcBaseDAO.java
  bundles/org.openhab.persistence.jdbc/src/test/java/org/openhab/persistence/jdbc/db/JdbcBaseDAOTest.java
Labels: bug

#13116 [Tesla] Add event stream & handling post new authentication process
  bundles/org.openhab.binding.tesla/README.md
  bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/TeslaBindingConstants.java
  bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/TeslaHandlerFactory.java
  bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/handler/TeslaAccountHandler.java
  bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/handler/TeslaEventEndpoint.java
  bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/handler/TeslaVehicleHandler.java
  bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/protocol/Event.java
  bundles/org.openhab.binding.tesla/src/main/resources/OH-INF/thing/model3.xml
  bundles/org.openhab.binding.tesla/src/main/resources/OH-INF/thing/models.xml
  bundles/org.openhab.binding.tesla/src/main/resources/OH-INF/thing/modelx.xml
  bundles/org.openhab.binding.tesla/src/main/resources/OH-INF/thing/modely.xml
Labels: enhancement

#13419 [ecowatt] Unit tests for methods getting channel state from API response
  bundles/org.openhab.binding.ecowatt/src/main/java/org/openhab/binding/ecowatt/internal/handler/EcowattHandler.java
  bundles/org.openhab.binding.ecowatt/src/main/java/org/openhab/binding/ecowatt/internal/restapi/EcowattRestApi.java
  bundles/org.openhab.binding.ecowatt/src/test/java/org/openhab/binding/ecowatt/internal/EcowattApiResponseTest.java
  bundles/org.openhab.binding.ecowatt/src/test/resources/ApiResponse.json
Labels: test

#13325 [fsinternetradio] Add Ruark R5 to tested devices & mode list
  bundles/org.openhab.binding.fsinternetradio/README.md
Labels: documentation

#13414 [openweathermap] onecall api version - property for setting API version to use.
  bundles/org.openhab.binding.openweathermap/README.md
  bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/config/OpenWeatherMapAPIConfiguration.java
  bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/connection/OpenWeatherMapConnection.java
  bundles/org.openhab.binding.openweathermap/src/main/resources/OH-INF/config/config.xml
  bundles/org.openhab.binding.openweathermap/src/main/resources/OH-INF/i18n/openweathermap.properties
Labels: enhancement

#13427 [touchwand] Fix thermostat target temperature command
  bundles/org.openhab.binding.touchwand/src/main/java/org/openhab/binding/touchwand/internal/TouchWandRestClient.java
  bundles/org.openhab.binding.touchwand/src/main/java/org/openhab/binding/touchwand/internal/TouchWandThermostatHandler.java
  bundles/org.openhab.binding.touchwand/src/main/java/org/openhab/binding/touchwand/internal/TouchWandWebSockets.java
Labels: bug

#13393 [miele] Migrate start channel to full DateTime channel and add end channel
  bundles/org.openhab.binding.miele/README.md
  bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/MieleBindingConstants.java
  bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/MieleHandlerFactory.java
  bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/TimeStabilizer.java
  bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/CoffeeMachineHandler.java
  bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/DishWasherHandler.java
  bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/DishwasherChannelSelector.java
  bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/FridgeFreezerHandler.java
  bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/FridgeHandler.java
  bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/HobHandler.java
  bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/HoodHandler.java
  bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/MieleApplianceHandler.java
  bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/OvenChannelSelector.java
  bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/OvenHandler.java
  bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/TumbleDryerChannelSelector.java
  bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/TumbleDryerHandler.java
  bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/WashingMachineChannelSelector.java
  bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/WashingMachineHandler.java
  bundles/org.openhab.binding.miele/src/main/resources/OH-INF/i18n/miele.properties
  bundles/org.openhab.binding.miele/src/main/resources/OH-INF/thing/channeltypes.xml
  bundles/org.openhab.binding.miele/src/main/resources/OH-INF/thing/dishwasher.xml
  bundles/org.openhab.binding.miele/src/main/resources/OH-INF/thing/oven.xml
  bundles/org.openhab.binding.miele/src/main/resources/OH-INF/thing/tumbledryer.xml
  bundles/org.openhab.binding.miele/src/main/resources/OH-INF/thing/washingmachine.xml
  bundles/org.openhab.binding.miele/src/test/java/org/openhab/binding/miele/internal/TimeStabilizerTest.java
Labels: enhancement, (potentially) not backward compatible

#13338 [pulseaudio] Apply real disconnection when needed
  bundles/org.openhab.binding.pulseaudio/src/main/java/org/openhab/binding/pulseaudio/internal/PulseAudioAudioSink.java
  bundles/org.openhab.binding.pulseaudio/src/main/java/org/openhab/binding/pulseaudio/internal/PulseAudioAudioSource.java
  bundles/org.openhab.binding.pulseaudio/src/main/java/org/openhab/binding/pulseaudio/internal/PulseaudioSimpleProtocolStream.java
  bundles/org.openhab.binding.pulseaudio/src/main/java/org/openhab/binding/pulseaudio/internal/cli/Parser.java
  bundles/org.openhab.binding.pulseaudio/src/main/java/org/openhab/binding/pulseaudio/internal/handler/PulseaudioHandler.java
Labels: bug

#13406 [velux] Bridge status shows offline when communication fails
  bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/handler/VeluxBridgeHandler.java
Labels: enhancement

#13186 [KVV] Replace underlying API
  bundles/org.openhab.binding.kvv/README.md
  bundles/org.openhab.binding.kvv/src/main/java/org/openhab/binding/kvv/internal/DepartureResult.java
  bundles/org.openhab.binding.kvv/src/main/java/org/openhab/binding/kvv/internal/KVVBindingConstants.java
  bundles/org.openhab.binding.kvv/src/main/java/org/openhab/binding/kvv/internal/KVVBridgeConfig.java
  bundles/org.openhab.binding.kvv/src/main/java/org/openhab/binding/kvv/internal/KVVBridgeHandler.java
  bundles/org.openhab.binding.kvv/src/main/java/org/openhab/binding/kvv/internal/KVVStopHandler.java
  bundles/org.openhab.binding.kvv/src/main/resources/OH-INF/i18n/kvv.properties
  bundles/org.openhab.binding.kvv/src/main/resources/OH-INF/thing/bridge.xml
Labels: bug, awaiting feedback

#13438 [ecowatt] Shorter labels for channel options
  bundles/org.openhab.binding.ecowatt/README.md
  bundles/org.openhab.binding.ecowatt/src/main/resources/OH-INF/i18n/ecowatt.properties
  bundles/org.openhab.binding.ecowatt/src/main/resources/OH-INF/thing/thing-types.xml
Labels: enhancement

#13236 [homekit] allow group items of the correct type anywhere that type is needed
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitOHItemProxy.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitTaggedItem.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/AbstractHomekitPositionAccessoryImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/BooleanItemReader.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitCharacteristicFactory.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitGarageDoorOpenerImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitLightbulbImpl.java
Labels: enhancement

#13426 [mqtt.generic] fix range of RGB values
  bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/values/ColorValue.java
  bundles/org.openhab.binding.mqtt.generic/src/test/java/org/openhab/binding/mqtt/generic/ChannelStateTests.java
Labels: bug

#13440 [touchwand] Add port configuration to websocket
  bundles/org.openhab.binding.touchwand/src/main/java/org/openhab/binding/touchwand/internal/TouchWandBridgeHandler.java
  bundles/org.openhab.binding.touchwand/src/main/java/org/openhab/binding/touchwand/internal/TouchWandWebSockets.java
Labels: enhancement

#10414 [solarmax] Initial contribution
  CODEOWNERS
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.solarmax/NOTICE
  bundles/org.openhab.binding.solarmax/README.md
  bundles/org.openhab.binding.solarmax/pom.xml
  bundles/org.openhab.binding.solarmax/src/main/feature/feature.xml
  bundles/org.openhab.binding.solarmax/src/main/java/org/openhab/binding/solarmax/internal/SolarMaxBindingConstants.java
  bundles/org.openhab.binding.solarmax/src/main/java/org/openhab/binding/solarmax/internal/SolarMaxChannel.java
  bundles/org.openhab.binding.solarmax/src/main/java/org/openhab/binding/solarmax/internal/SolarMaxConfiguration.java
  bundles/org.openhab.binding.solarmax/src/main/java/org/openhab/binding/solarmax/internal/SolarMaxHandler.java
  bundles/org.openhab.binding.solarmax/src/main/java/org/openhab/binding/solarmax/internal/SolarMaxHandlerFactory.java
  bundles/org.openhab.binding.solarmax/src/main/java/org/openhab/binding/solarmax/internal/SolarMaxProperty.java
  bundles/org.openhab.binding.solarmax/src/main/java/org/openhab/binding/solarmax/internal/connector/SolarMaxCommandKey.java
  bundles/org.openhab.binding.solarmax/src/main/java/org/openhab/binding/solarmax/internal/connector/SolarMaxConnectionException.java
  bundles/org.openhab.binding.solarmax/src/main/java/org/openhab/binding/solarmax/internal/connector/SolarMaxConnector.java
  bundles/org.openhab.binding.solarmax/src/main/java/org/openhab/binding/solarmax/internal/connector/SolarMaxData.java
  bundles/org.openhab.binding.solarmax/src/main/java/org/openhab/binding/solarmax/internal/connector/SolarMaxException.java
  bundles/org.openhab.binding.solarmax/src/main/resources/OH-INF/binding/binding.xml
  bundles/org.openhab.binding.solarmax/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.solarmax/src/test/java/org/openhab/binding/solarmax/internal/connector/SolarMaxDataTest.java
  bundles/org.openhab.binding.solarmax/src/test/java/org/openhab/binding/solarmax/internal/connector/SolarmaxConnectorFindCommands.java
  bundles/pom.xml
Labels: new binding

#13452 [solarmax] Add default translations
  bundles/org.openhab.binding.solarmax/src/main/resources/OH-INF/i18n/solarmax.properties
Labels: translation

#13432 [remoteopenhab] Optimize filtering of ALIVE events
  bundles/org.openhab.binding.remoteopenhab/src/main/java/org/openhab/binding/remoteopenhab/internal/rest/RemoteopenhabRestClient.java
Labels: enhancement

#13441 [nuki] updated example to match frontdoor_lockstates
  bundles/org.openhab.binding.nuki/README.md
Labels: documentation

#11999 [echonetlite] Initial contribution
  CODEOWNERS
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.echonetlite/NOTICE
  bundles/org.openhab.binding.echonetlite/README.md
  bundles/org.openhab.binding.echonetlite/pom.xml
  bundles/org.openhab.binding.echonetlite/src/main/feature/feature.xml
  bundles/org.openhab.binding.echonetlite/src/main/java/org/openhab/binding/echonetlite/internal/EchonetBridgeConfig.java
  bundles/org.openhab.binding.echonetlite/src/main/java/org/openhab/binding/echonetlite/internal/EchonetChannel.java
  bundles/org.openhab.binding.echonetlite/src/main/java/org/openhab/binding/echonetlite/internal/EchonetClass.java
  bundles/org.openhab.binding.echonetlite/src/main/java/org/openhab/binding/echonetlite/internal/EchonetClassIndex.java
  bundles/org.openhab.binding.echonetlite/src/main/java/org/openhab/binding/echonetlite/internal/EchonetDevice.java
  bundles/org.openhab.binding.echonetlite/src/main/java/org/openhab/binding/echonetlite/internal/EchonetDeviceConfig.java
  bundles/org.openhab.binding.echonetlite/src/main/java/org/openhab/binding/echonetlite/internal/EchonetDeviceListener.java
  bundles/org.openhab.binding.echonetlite/src/main/java/org/openhab/binding/echonetlite/internal/EchonetDiscoveryListener.java
  bundles/org.openhab.binding.echonetlite/src/main/java/org/openhab/binding/echonetlite/internal/EchonetDiscoveryService.java
  bundles/org.openhab.binding.echonetlite/src/main/java/org/openhab/binding/echonetlite/internal/EchonetLiteBindingConstants.java
  bundles/org.openhab.binding.echonetlite/src/main/java/org/openhab/binding/echonetlite/internal/EchonetLiteBridgeHandler.java
  bundles/org.openhab.binding.echonetlite/src/main/java/org/openhab/binding/echonetlite/internal/EchonetLiteHandler.java
  bundles/org.openhab.binding.echonetlite/src/main/java/org/openhab/binding/echonetlite/internal/EchonetLiteHandlerFactory.java
  bundles/org.openhab.binding.echonetlite/src/main/java/org/openhab/binding/echonetlite/internal/EchonetMessage.java
  bundles/org.openhab.binding.echonetlite/src/main/java/org/openhab/binding/echonetlite/internal/EchonetMessageBuilder.java
  bundles/org.openhab.binding.echonetlite/src/main/java/org/openhab/binding/echonetlite/internal/EchonetObject.java
  bundles/org.openhab.binding.echonetlite/src/main/java/org/openhab/binding/echonetlite/internal/EchonetProfileNode.java
  bundles/org.openhab.binding.echonetlite/src/main/java/org/openhab/binding/echonetlite/internal/EchonetPropertyMap.java
  bundles/org.openhab.binding.echonetlite/src/main/java/org/openhab/binding/echonetlite/internal/Epc.java
  bundles/org.openhab.binding.echonetlite/src/main/java/org/openhab/binding/echonetlite/internal/EpcLookupTable.java
  bundles/org.openhab.binding.echonetlite/src/main/java/org/openhab/binding/echonetlite/internal/Esv.java
  bundles/org.openhab.binding.echonetlite/src/main/java/org/openhab/binding/echonetlite/internal/HexUtil.java
  bundles/org.openhab.binding.echonetlite/src/main/java/org/openhab/binding/echonetlite/internal/InstanceKey.java
  bundles/org.openhab.binding.echonetlite/src/main/java/org/openhab/binding/echonetlite/internal/LangUtil.java
  bundles/org.openhab.binding.echonetlite/src/main/java/org/openhab/binding/echonetlite/internal/MonotonicClock.java
  bundles/org.openhab.binding.echonetlite/src/main/java/org/openhab/binding/echonetlite/internal/ShortSupplier.java
  bundles/org.openhab.binding.echonetlite/src/main/java/org/openhab/binding/echonetlite/internal/StateCodec.java
  bundles/org.openhab.binding.echonetlite/src/main/java/org/openhab/binding/echonetlite/internal/StateDecode.java
  bundles/org.openhab.binding.echonetlite/src/main/java/org/openhab/binding/echonetlite/internal/StateEncode.java
  bundles/org.openhab.binding.echonetlite/src/main/resources/OH-INF/binding/binding.xml
  bundles/org.openhab.binding.echonetlite/src/main/resources/OH-INF/i18n/echonetlite.properties
  bundles/org.openhab.binding.echonetlite/src/main/resources/OH-INF/thing/channel-types.xml
  bundles/org.openhab.binding.echonetlite/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.echonetlite/src/test/java/org/openhab/binding/echonetlite/internal/EpcTest.java
  bundles/org.openhab.binding.echonetlite/src/test/java/org/openhab/binding/echonetlite/internal/protocol/LangUtilTest.java
  bundles/org.openhab.binding.echonetlite/src/test/java/org/openhab/binding/echonetlite/internal/protocol/StateCodecTest.java
  bundles/pom.xml
Labels: new binding

#13460 [lcn] Improve logging
  bundles/org.openhab.binding.lcn/src/main/java/org/openhab/binding/lcn/internal/LcnModuleHandler.java
  bundles/org.openhab.binding.lcn/src/main/java/org/openhab/binding/lcn/internal/common/VariableValue.java
  bundles/org.openhab.binding.lcn/src/main/java/org/openhab/binding/lcn/internal/converter/Converter.java
  bundles/org.openhab.binding.lcn/src/main/java/org/openhab/binding/lcn/internal/converter/ValueConverter.java
  bundles/org.openhab.binding.lcn/src/test/java/org/openhab/binding/lcn/internal/subhandler/LcnModuleRvarSetpointSubHandlerTest.java
  bundles/org.openhab.binding.lcn/src/test/java/org/openhab/binding/lcn/internal/subhandler/LcnModuleVariableSubHandlerTest.java
Labels: enhancement
