Repository openhab/openhab-addons, pull requests merged in 2022-03, with the labels that each got.

#12399 [ipcamera] Fix Digest bug and Doorbird fixes.
  bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/handler/IpCameraHandler.java
Labels: bug

#12376 [pulseaudio] register audio sources in openhab
  bundles/org.openhab.binding.pulseaudio/README.md
  bundles/org.openhab.binding.pulseaudio/src/main/java/org/openhab/binding/pulseaudio/internal/PulseAudioAudioSink.java
  bundles/org.openhab.binding.pulseaudio/src/main/java/org/openhab/binding/pulseaudio/internal/PulseAudioAudioSource.java
  bundles/org.openhab.binding.pulseaudio/src/main/java/org/openhab/binding/pulseaudio/internal/PulseAudioBindingConfiguration.java
  bundles/org.openhab.binding.pulseaudio/src/main/java/org/openhab/binding/pulseaudio/internal/PulseaudioBindingConstants.java
  bundles/org.openhab.binding.pulseaudio/src/main/java/org/openhab/binding/pulseaudio/internal/PulseaudioClient.java
  bundles/org.openhab.binding.pulseaudio/src/main/java/org/openhab/binding/pulseaudio/internal/PulseaudioSimpleProtocolStream.java
  bundles/org.openhab.binding.pulseaudio/src/main/java/org/openhab/binding/pulseaudio/internal/handler/DeviceStatusListener.java
  bundles/org.openhab.binding.pulseaudio/src/main/java/org/openhab/binding/pulseaudio/internal/handler/PulseaudioHandler.java
  bundles/org.openhab.binding.pulseaudio/src/main/resources/OH-INF/binding/binding.xml
  bundles/org.openhab.binding.pulseaudio/src/main/resources/OH-INF/i18n/pulseaudio.properties
  bundles/org.openhab.binding.pulseaudio/src/main/resources/OH-INF/thing/sink.xml
  bundles/org.openhab.binding.pulseaudio/src/main/resources/OH-INF/thing/source.xml
Labels: enhancement

#12371 [fronius] Fix DecimalType constructor change
  bundles/org.openhab.binding.fronius/src/main/java/org/openhab/binding/fronius/internal/handler/FroniusBaseThingHandler.java
Labels: enhancement

#12411 [wemo] Add missing channel categories and semantic tags
  bundles/org.openhab.binding.wemo/src/main/resources/OH-INF/i18n/wemo.properties
  bundles/org.openhab.binding.wemo/src/main/resources/OH-INF/thing/channels.xml
  bundles/org.openhab.binding.wemo/src/main/resources/OH-INF/thing/coffeemaker.xml
  bundles/org.openhab.binding.wemo/src/main/resources/OH-INF/thing/crockpot.xml
  bundles/org.openhab.binding.wemo/src/main/resources/OH-INF/thing/dimmer.xml
  bundles/org.openhab.binding.wemo/src/main/resources/OH-INF/thing/heater.xml
  bundles/org.openhab.binding.wemo/src/main/resources/OH-INF/thing/humidifier.xml
  bundles/org.openhab.binding.wemo/src/main/resources/OH-INF/thing/insight.xml
  bundles/org.openhab.binding.wemo/src/main/resources/OH-INF/thing/lightswitch.xml
  bundles/org.openhab.binding.wemo/src/main/resources/OH-INF/thing/maker.xml
  bundles/org.openhab.binding.wemo/src/main/resources/OH-INF/thing/motion.xml
  bundles/org.openhab.binding.wemo/src/main/resources/OH-INF/thing/mz100.xml
  bundles/org.openhab.binding.wemo/src/main/resources/OH-INF/thing/purifier.xml
  bundles/org.openhab.binding.wemo/src/main/resources/OH-INF/thing/socket.xml
Labels: enhancement

#12341 [network] Removed last references to org.apache...
  bundles/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/NetworkBindingConstants.java
  bundles/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/PresenceDetection.java
  bundles/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/WakeOnLanPacketSender.java
  bundles/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/dhcp/DHCPListenService.java
  bundles/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/dhcp/DHCPPacket.java
  bundles/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/dhcp/DHCPPacketListenerServer.java
  bundles/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/toberemoved/cache/ExpiringCacheAsync.java
  bundles/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/utils/NetworkUtils.java
Labels: enhancement

#12404 [deutschebahn] Fixed timing issue in test case
  bundles/org.openhab.binding.deutschebahn/src/main/java/org/openhab/binding/deutschebahn/internal/DeutscheBahnHandlerFactory.java
  bundles/org.openhab.binding.deutschebahn/src/main/java/org/openhab/binding/deutschebahn/internal/DeutscheBahnTimetableHandler.java
  bundles/org.openhab.binding.deutschebahn/src/test/java/org/openhab/binding/deutschebahn/internal/DeutscheBahnTimetableHandlerTest.java
Labels: test

#12406 [deutschebahn] Fixed order of stops
  bundles/org.openhab.binding.deutschebahn/src/main/java/org/openhab/binding/deutschebahn/internal/DeutscheBahnTimetableHandler.java
  bundles/org.openhab.binding.deutschebahn/src/test/java/org/openhab/binding/deutschebahn/internal/DeutscheBahnTimetableHandlerTest.java
  bundles/org.openhab.binding.deutschebahn/src/test/java/org/openhab/binding/deutschebahn/internal/timetable/TimetablesV1ImplTestHelper.java
  bundles/org.openhab.binding.deutschebahn/src/test/resources/timetablesDataDifferentOrder/plan/8000226/210816/09.xml
Labels: bug

#12416 [wemo] Fix thing status transitions
  bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/handler/WemoCoffeeHandler.java
  bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/handler/WemoCrockpotHandler.java
  bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/handler/WemoDimmerHandler.java
  bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/handler/WemoHandler.java
  bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/handler/WemoHolmesHandler.java
  bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/handler/WemoLightHandler.java
  bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/handler/WemoMakerHandler.java
  itests/org.openhab.binding.wemo.tests/src/main/java/org/openhab/binding/wemo/internal/handler/test/WemoHandlerOSGiTest.java
  itests/org.openhab.binding.wemo.tests/src/main/java/org/openhab/binding/wemo/internal/handler/test/WemoLightHandlerOSGiTest.java
  itests/org.openhab.binding.wemo.tests/src/main/java/org/openhab/binding/wemo/internal/handler/test/WemoMakerHandlerOSGiTest.java
Labels: enhancement

#12038 [rfxcom] Support for Lucciair DC Speed
  bundles/org.openhab.binding.rfxcom/README.md
  bundles/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/messages/RFXComFanMessage.java
  bundles/org.openhab.binding.rfxcom/src/main/resources/OH-INF/thing/fan_lucci_dc.xml
  bundles/org.openhab.binding.rfxcom/src/main/resources/OH-INF/thing/fan_novy.xml
Labels: enhancement, (potentially) not backward compatible

#12394 [fronius] Add the new channels to the documentation
  bundles/org.openhab.binding.fronius/README.md
Labels: documentation

#12425 GHA CI build workflow improvements
  .github/workflows/ci-build.yml
  README.md
Labels: infrastructure

#12413 [millheat] Possibly wrong use of isHoliday instead of canChangeTemp
  bundles/org.openhab.binding.millheat/src/main/java/org/openhab/binding/millheat/internal/model/Heater.java
Labels: bug

#12437 [homematic] Fix invalid default values ending up in the thing type
  bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/type/HomematicTypeGeneratorImpl.java
Labels: bug

#12436 [homematic] Prevent the use of exponential notation
  bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/communicator/CcuGateway.java
Labels: bug

#12423 [pulseaudio] Fix exception handling when connecting
  bundles/org.openhab.binding.pulseaudio/src/main/java/org/openhab/binding/pulseaudio/internal/PulseaudioClient.java
  bundles/org.openhab.binding.pulseaudio/src/main/java/org/openhab/binding/pulseaudio/internal/handler/PulseaudioBridgeHandler.java
  bundles/org.openhab.binding.pulseaudio/src/main/java/org/openhab/binding/pulseaudio/internal/handler/PulseaudioHandler.java
Labels: bug

#12454 [andoiddebugbridge] Update README
  bundles/org.openhab.binding.androiddebugbridge/README.md
Labels: documentation

#11926 [mihome] Update README.md
  bundles/org.openhab.binding.mihome/README.md
Labels: documentation

#12452 [pushover] Add featured integration paragraph
  bundles/org.openhab.binding.pushover/README.md
Labels: documentation

#12459 [somfytahoma] improved compatibility with Somfy Connectivity Kit
  bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/SomfyTahomaBindingConstants.java
  bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/discovery/SomfyTahomaItemDiscoveryService.java
  bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/handler/SomfyTahomaAwningHandler.java
  bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/handler/SomfyTahomaVenetianBlindHandler.java
Labels: enhancement

#12463 [fronius] Add a note about enabling Night Mode on the device
  bundles/org.openhab.binding.fronius/README.md
Labels: documentation

#12453 STT service improvements
  bundles/org.openhab.voice.googlestt/src/main/java/org/openhab/voice/googlestt/internal/GoogleSTTConfiguration.java
  bundles/org.openhab.voice.googlestt/src/main/resources/OH-INF/config/config.xml
  bundles/org.openhab.voice.voskstt/src/main/java/org/openhab/voice/voskstt/internal/VoskSTTConfiguration.java
  bundles/org.openhab.voice.voskstt/src/main/resources/OH-INF/config/config.xml
  bundles/org.openhab.voice.watsonstt/README.md
  bundles/org.openhab.voice.watsonstt/pom.xml
  bundles/org.openhab.voice.watsonstt/src/main/java/org/openhab/voice/watsonstt/internal/WatsonSTTConfiguration.java
  bundles/org.openhab.voice.watsonstt/src/main/java/org/openhab/voice/watsonstt/internal/WatsonSTTService.java
  bundles/org.openhab.voice.watsonstt/src/main/resources/OH-INF/config/config.xml
  bundles/org.openhab.voice.watsonstt/src/main/resources/OH-INF/i18n/watsonstt.properties
Labels: enhancement

#12443 [ipp] Update cups4j and dependencies
  bundles/org.openhab.binding.ipp/pom.xml
  bundles/org.openhab.binding.ipp/src/main/java/org/openhab/binding/ipp/internal/handler/IppPrinterHandler.java
Labels: enhancement

#12466 [avmfritz] Add support for DECT 302
  bundles/org.openhab.binding.avmfritz/README.md
  bundles/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/AVMFritzBindingConstants.java
  bundles/org.openhab.binding.avmfritz/src/main/resources/OH-INF/i18n/avmfritz.properties
  bundles/org.openhab.binding.avmfritz/src/main/resources/OH-INF/thing/thing-types.xml
  itests/org.openhab.binding.avmfritz.tests/src/main/java/org/openhab/binding/avmfritz/internal/discovery/AVMFritzDiscoveryServiceOSGiTest.java
Labels: enhancement

#12467 [jdbc] Fixed parameter ordering while storing values
  bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/db/JdbcBaseDAO.java
  bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/utils/StringUtilsExt.java
Labels: bug

#10967 [prowl] Initial contribution
  CODEOWNERS
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.prowl/NOTICE
  bundles/org.openhab.binding.prowl/README.md
  bundles/org.openhab.binding.prowl/pom.xml
  bundles/org.openhab.binding.prowl/src/main/feature/feature.xml
  bundles/org.openhab.binding.prowl/src/main/java/org/openhab/binding/prowl/internal/ProwlBindingConstants.java
  bundles/org.openhab.binding.prowl/src/main/java/org/openhab/binding/prowl/internal/ProwlConfiguration.java
  bundles/org.openhab.binding.prowl/src/main/java/org/openhab/binding/prowl/internal/ProwlHandler.java
  bundles/org.openhab.binding.prowl/src/main/java/org/openhab/binding/prowl/internal/ProwlHandlerFactory.java
  bundles/org.openhab.binding.prowl/src/main/java/org/openhab/binding/prowl/internal/action/ProwlActions.java
  bundles/org.openhab.binding.prowl/src/main/resources/OH-INF/binding/binding.xml
  bundles/org.openhab.binding.prowl/src/main/resources/OH-INF/i18n/prowl.properties
  bundles/org.openhab.binding.prowl/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/pom.xml
Labels: new binding

#12471 [mail] Fix unstable MailBuilderTest
  bundles/org.openhab.binding.mail/src/test/java/org/openhab/binding/mail/MailBuilderTest.java
  bundles/org.openhab.binding.mail/src/test/resources/attachment.txt
Labels: test

#12483 [openwebnet] added channel "function" for Central Unit
  bundles/org.openhab.binding.openwebnet/README.md
  bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/handler/OpenWebNetThermoregulationHandler.java
  bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/thing/BusThermoCentralUnit.xml
  bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/thing/channels.xml
Labels: enhancement

#12441 [pulseaudio] source: use thread safe collection and force reconnection
  bundles/org.openhab.binding.pulseaudio/src/main/java/org/openhab/binding/pulseaudio/internal/PulseAudioAudioSource.java
Labels: bug

#12487 [renault] API key update.
  bundles/org.openhab.binding.renault/src/main/java/org/openhab/binding/renault/internal/api/Constants.java
Labels: bug

#12485 [openwebnet] handle Thermo Central Unit monitoring messages
  bundles/org.openhab.binding.openwebnet/README.md
  bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/OpenWebNetBindingConstants.java
  bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/handler/OpenWebNetThermoregulationHandler.java
  bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/thing/BusThermoCentralUnit.xml
  bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/thing/channels.xml
Labels: enhancement

#12493 [danfossairunit] Minor value cache tweaks
  bundles/org.openhab.binding.danfossairunit/src/main/java/org/openhab/binding/danfossairunit/internal/ValueCache.java
Labels: enhancement

#12482 [icalendar] Adding ability to handle events without DTEND
  bundles/org.openhab.binding.icalendar/src/main/java/org/openhab/binding/icalendar/internal/logic/BiweeklyPresentableCalendar.java
Labels: enhancement

#12356 [velux] Improve shutdown exception handling
  bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/bridge/slip/io/Connection.java
  bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/bridge/slip/io/DataInputStreamWithTimeout.java
  bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/bridge/slip/io/Poller.java
  bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/handler/VeluxBridgeHandler.java
Labels: enhancement

#12491 [androiddebugbridge] Added DynamicCommandOptionsProvider to populate 'start-package' Channel
  bundles/org.openhab.binding.androiddebugbridge/README.md
  bundles/org.openhab.binding.androiddebugbridge/src/main/java/org/openhab/binding/androiddebugbridge/internal/AndroidDebugBridgeDynamicCommandDescriptionProvider.java
  bundles/org.openhab.binding.androiddebugbridge/src/main/java/org/openhab/binding/androiddebugbridge/internal/AndroidDebugBridgeHandler.java
  bundles/org.openhab.binding.androiddebugbridge/src/main/java/org/openhab/binding/androiddebugbridge/internal/AndroidDebugBridgeHandlerFactory.java
Labels: enhancement

#12489 [openwebnet] fixed generic_device thing-type, improved refresh at boot
  bundles/org.openhab.binding.openwebnet/README.md
  bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/handler/OpenWebNetBridgeHandler.java
  bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/thing/GenericDevice.xml
Labels: bug, (potentially) not backward compatible

#11189 [elroconnects] New binding for Elro Connects
  CODEOWNERS
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.elroconnects/NOTICE
  bundles/org.openhab.binding.elroconnects/README.md
  bundles/org.openhab.binding.elroconnects/pom.xml
  bundles/org.openhab.binding.elroconnects/src/main/feature/feature.xml
  bundles/org.openhab.binding.elroconnects/src/main/java/org/openhab/binding/elroconnects/internal/ElroConnectsBindingConstants.java
  bundles/org.openhab.binding.elroconnects/src/main/java/org/openhab/binding/elroconnects/internal/ElroConnectsDynamicStateDescriptionProvider.java
  bundles/org.openhab.binding.elroconnects/src/main/java/org/openhab/binding/elroconnects/internal/ElroConnectsHandlerFactory.java
  bundles/org.openhab.binding.elroconnects/src/main/java/org/openhab/binding/elroconnects/internal/ElroConnectsMessage.java
  bundles/org.openhab.binding.elroconnects/src/main/java/org/openhab/binding/elroconnects/internal/devices/ElroConnectsDevice.java
  bundles/org.openhab.binding.elroconnects/src/main/java/org/openhab/binding/elroconnects/internal/devices/ElroConnectsDeviceCxsmAlarm.java
  bundles/org.openhab.binding.elroconnects/src/main/java/org/openhab/binding/elroconnects/internal/devices/ElroConnectsDeviceEntrySensor.java
  bundles/org.openhab.binding.elroconnects/src/main/java/org/openhab/binding/elroconnects/internal/devices/ElroConnectsDeviceGenericAlarm.java
  bundles/org.openhab.binding.elroconnects/src/main/java/org/openhab/binding/elroconnects/internal/devices/ElroConnectsDeviceMotionSensor.java
  bundles/org.openhab.binding.elroconnects/src/main/java/org/openhab/binding/elroconnects/internal/devices/ElroConnectsDevicePowerSocket.java
  bundles/org.openhab.binding.elroconnects/src/main/java/org/openhab/binding/elroconnects/internal/devices/ElroConnectsDeviceTemperatureSensor.java
  bundles/org.openhab.binding.elroconnects/src/main/java/org/openhab/binding/elroconnects/internal/discovery/ElroConnectsDiscoveryService.java
  bundles/org.openhab.binding.elroconnects/src/main/java/org/openhab/binding/elroconnects/internal/handler/ElroConnectsBridgeConfiguration.java
  bundles/org.openhab.binding.elroconnects/src/main/java/org/openhab/binding/elroconnects/internal/handler/ElroConnectsBridgeHandler.java
  bundles/org.openhab.binding.elroconnects/src/main/java/org/openhab/binding/elroconnects/internal/handler/ElroConnectsCOAlarmHandler.java
  bundles/org.openhab.binding.elroconnects/src/main/java/org/openhab/binding/elroconnects/internal/handler/ElroConnectsDeviceConfiguration.java
  bundles/org.openhab.binding.elroconnects/src/main/java/org/openhab/binding/elroconnects/internal/handler/ElroConnectsDeviceHandler.java
  bundles/org.openhab.binding.elroconnects/src/main/java/org/openhab/binding/elroconnects/internal/handler/ElroConnectsEntrySensorHandler.java
  bundles/org.openhab.binding.elroconnects/src/main/java/org/openhab/binding/elroconnects/internal/handler/ElroConnectsHeatAlarmHandler.java
  bundles/org.openhab.binding.elroconnects/src/main/java/org/openhab/binding/elroconnects/internal/handler/ElroConnectsMotionSensorHandler.java
  bundles/org.openhab.binding.elroconnects/src/main/java/org/openhab/binding/elroconnects/internal/handler/ElroConnectsPowerSocketHandler.java
  bundles/org.openhab.binding.elroconnects/src/main/java/org/openhab/binding/elroconnects/internal/handler/ElroConnectsSmokeAlarmHandler.java
  bundles/org.openhab.binding.elroconnects/src/main/java/org/openhab/binding/elroconnects/internal/handler/ElroConnectsWaterAlarmHandler.java
  bundles/org.openhab.binding.elroconnects/src/main/java/org/openhab/binding/elroconnects/internal/util/ElroConnectsUtil.java
  bundles/org.openhab.binding.elroconnects/src/main/resources/OH-INF/binding/binding.xml
  bundles/org.openhab.binding.elroconnects/src/main/resources/OH-INF/i18n/elroconnects.properties
  bundles/org.openhab.binding.elroconnects/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/pom.xml
Labels: new binding

#12447 [rotel] Extension of amplifier A14's channel list
  bundles/org.openhab.binding.rotel/README.md
  bundles/org.openhab.binding.rotel/src/main/java/org/openhab/binding/rotel/internal/RotelBindingConstants.java
  bundles/org.openhab.binding.rotel/src/main/java/org/openhab/binding/rotel/internal/RotelModel.java
  bundles/org.openhab.binding.rotel/src/main/java/org/openhab/binding/rotel/internal/communication/RotelCommand.java
  bundles/org.openhab.binding.rotel/src/main/java/org/openhab/binding/rotel/internal/communication/RotelConnector.java
  bundles/org.openhab.binding.rotel/src/main/java/org/openhab/binding/rotel/internal/handler/RotelHandler.java
  bundles/org.openhab.binding.rotel/src/main/resources/OH-INF/config/config.xml
  bundles/org.openhab.binding.rotel/src/main/resources/OH-INF/i18n/rotel.properties
  bundles/org.openhab.binding.rotel/src/main/resources/OH-INF/thing/a11.xml
  bundles/org.openhab.binding.rotel/src/main/resources/OH-INF/thing/a12.xml
  bundles/org.openhab.binding.rotel/src/main/resources/OH-INF/thing/a14.xml
  bundles/org.openhab.binding.rotel/src/main/resources/OH-INF/thing/channels.xml
  bundles/org.openhab.binding.rotel/src/main/resources/OH-INF/thing/ra11.xml
  bundles/org.openhab.binding.rotel/src/main/resources/OH-INF/thing/ra12.xml
  bundles/org.openhab.binding.rotel/src/main/resources/OH-INF/thing/ra1570.xml
  bundles/org.openhab.binding.rotel/src/main/resources/OH-INF/thing/ra1572.xml
  bundles/org.openhab.binding.rotel/src/main/resources/OH-INF/thing/ra1592.xml
  bundles/org.openhab.binding.rotel/src/main/resources/OH-INF/thing/rc1570.xml
  bundles/org.openhab.binding.rotel/src/main/resources/OH-INF/thing/rc1572.xml
  bundles/org.openhab.binding.rotel/src/main/resources/OH-INF/thing/rc1590.xml
Labels: enhancement

#12509 [plugwiseha] Fix Zone thermostat not updating
  bundles/org.openhab.binding.plugwiseha/src/main/java/org/openhab/binding/plugwiseha/internal/api/model/dto/Locations.java
Labels: bug

#12515 [modbus] Fixed minor spelling mistake
  bundles/org.openhab.binding.modbus/src/main/resources/OH-INF/i18n/modbus.properties
  bundles/org.openhab.binding.modbus/src/main/resources/OH-INF/thing/thing-data.xml
Labels: translation

#12514 [openwebnet] fixing support for central unit
  bundles/org.openhab.binding.openwebnet/pom.xml
  bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/handler/OpenWebNetThermoregulationHandler.java
Labels: bug

#12524 [rotel] Support added for Michi models (P5, X3 and X5)
  bundles/org.openhab.binding.rotel/README.md
  bundles/org.openhab.binding.rotel/src/main/java/org/openhab/binding/rotel/internal/RotelBindingConstants.java
  bundles/org.openhab.binding.rotel/src/main/java/org/openhab/binding/rotel/internal/RotelHandlerFactory.java
  bundles/org.openhab.binding.rotel/src/main/java/org/openhab/binding/rotel/internal/RotelModel.java
  bundles/org.openhab.binding.rotel/src/main/java/org/openhab/binding/rotel/internal/communication/RotelCommand.java
  bundles/org.openhab.binding.rotel/src/main/java/org/openhab/binding/rotel/internal/communication/RotelConnector.java
  bundles/org.openhab.binding.rotel/src/main/java/org/openhab/binding/rotel/internal/communication/RotelSource.java
  bundles/org.openhab.binding.rotel/src/main/java/org/openhab/binding/rotel/internal/handler/RotelHandler.java
  bundles/org.openhab.binding.rotel/src/main/resources/OH-INF/i18n/rotel.properties
  bundles/org.openhab.binding.rotel/src/main/resources/OH-INF/thing/p5.xml
  bundles/org.openhab.binding.rotel/src/main/resources/OH-INF/thing/x3.xml
  bundles/org.openhab.binding.rotel/src/main/resources/OH-INF/thing/x5.xml
Labels: bug, enhancement

#12530 [tesla] Adapt access token handling to changes in Tesla API
  bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/handler/TeslaSSOHandler.java
Labels: bug

#12522 [rotel] Support of MKII models
  bundles/org.openhab.binding.rotel/README.md
  bundles/org.openhab.binding.rotel/src/main/resources/OH-INF/i18n/rotel.properties
  bundles/org.openhab.binding.rotel/src/main/resources/OH-INF/thing/a12.xml
  bundles/org.openhab.binding.rotel/src/main/resources/OH-INF/thing/a14.xml
  bundles/org.openhab.binding.rotel/src/main/resources/OH-INF/thing/cd14.xml
  bundles/org.openhab.binding.rotel/src/main/resources/OH-INF/thing/ra1572.xml
  bundles/org.openhab.binding.rotel/src/main/resources/OH-INF/thing/ra1592.xml
  bundles/org.openhab.binding.rotel/src/main/resources/OH-INF/thing/rap1580.xml
  bundles/org.openhab.binding.rotel/src/main/resources/OH-INF/thing/rc1572.xml
  bundles/org.openhab.binding.rotel/src/main/resources/OH-INF/thing/rc1590.xml
  bundles/org.openhab.binding.rotel/src/main/resources/OH-INF/thing/rcd1572.xml
  bundles/org.openhab.binding.rotel/src/main/resources/OH-INF/thing/rsp1576.xml
Labels: documentation

#12518 [knx] Reduce compiler warnings
  bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/KNXBindingConstants.java
  bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/KNXTypeMapper.java
  bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/channel/AbstractSpec.java
  bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/channel/ListenSpecImpl.java
  bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/client/AbstractKNXClient.java
  bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/client/CustomKNXNetworkLinkIP.java
  bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/client/DeviceInspector.java
  bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/client/SerialClient.java
  bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/config/BridgeConfiguration.java
  bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/config/DeviceConfig.java
  bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/config/IPBridgeConfiguration.java
  bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/config/SerialBridgeConfiguration.java
  bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/factory/KNXHandlerFactory.java
  bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/handler/AbstractKNXThingHandler.java
  bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/handler/DeviceConstants.java
  bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/handler/DeviceThingHandler.java
  bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/handler/IPBridgeThingHandler.java
  bundles/org.openhab.binding.knx/src/test/java/org/openhab/binding/knx/internal/channel/KNXChannelTypeTest.java
  bundles/org.openhab.binding.knx/src/test/java/org/openhab/binding/knx/internal/dpt/KNXCoreTypeMapperTest.java
Labels: enhancement

#12528 [yamahamusiccast] Update README.md
  bundles/org.openhab.binding.yamahamusiccast/README.md
Labels: documentation

#12495 [somfytahoma] added support for the Shutter thing
  bundles/org.openhab.binding.somfytahoma/README.md
  bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/SomfyTahomaBindingConstants.java
  bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/SomfyTahomaHandlerFactory.java
  bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/discovery/SomfyTahomaItemDiscoveryService.java
  bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/handler/SomfyTahomaShutterHandler.java
  bundles/org.openhab.binding.somfytahoma/src/main/resources/OH-INF/i18n/somfytahoma.properties
  bundles/org.openhab.binding.somfytahoma/src/main/resources/OH-INF/thing/shutter.xml
Labels: enhancement

#12420 [fronius] Add Autonomy and Self Consumption channels
  bundles/org.openhab.binding.fronius/README.md
  bundles/org.openhab.binding.fronius/src/main/java/org/openhab/binding/fronius/internal/FroniusBindingConstants.java
  bundles/org.openhab.binding.fronius/src/main/java/org/openhab/binding/fronius/internal/api/ValueUnit.java
  bundles/org.openhab.binding.fronius/src/main/java/org/openhab/binding/fronius/internal/handler/FroniusBaseThingHandler.java
  bundles/org.openhab.binding.fronius/src/main/java/org/openhab/binding/fronius/internal/handler/FroniusMeterHandler.java
  bundles/org.openhab.binding.fronius/src/main/java/org/openhab/binding/fronius/internal/handler/FroniusOhmpilotHandler.java
  bundles/org.openhab.binding.fronius/src/main/java/org/openhab/binding/fronius/internal/handler/FroniusSymoInverterHandler.java
  bundles/org.openhab.binding.fronius/src/main/java/org/openhab/binding/fronius/internal/math/KilowattConverter.java
  bundles/org.openhab.binding.fronius/src/main/java/org/openhab/binding/fronius/internal/math/SiPrefixFactors.java
  bundles/org.openhab.binding.fronius/src/main/resources/OH-INF/i18n/fronius.properties
  bundles/org.openhab.binding.fronius/src/main/resources/OH-INF/thing/thing-types.xml
Labels: enhancement

#12532 [somfytahoma] Improved compatibility with the Somfy Connectivity Kit
  bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/discovery/SomfyTahomaItemDiscoveryService.java
Labels: enhancement

#12390 [velbus] New module VMBELPIR + Improvement clock alarms management
  bundles/org.openhab.binding.velbus/README.md
  bundles/org.openhab.binding.velbus/src/main/java/org/openhab/binding/velbus/internal/VelbusBindingConstants.java
  bundles/org.openhab.binding.velbus/src/main/java/org/openhab/binding/velbus/internal/discovery/VelbusThingDiscoveryService.java
  bundles/org.openhab.binding.velbus/src/main/java/org/openhab/binding/velbus/internal/handler/VelbusBridgeHandler.java
  bundles/org.openhab.binding.velbus/src/main/java/org/openhab/binding/velbus/internal/handler/VelbusSensorWithAlarmClockHandler.java
  bundles/org.openhab.binding.velbus/src/main/java/org/openhab/binding/velbus/internal/handler/VelbusVMBELHandler.java
  bundles/org.openhab.binding.velbus/src/main/resources/OH-INF/i18n/velbus.properties
  bundles/org.openhab.binding.velbus/src/main/resources/OH-INF/thing/thing-types.xml
Labels: enhancement

#12346 [homekit] add support for complex accessories
  bundles/org.openhab.io.homekit/README.md
  bundles/org.openhab.io.homekit/doc/ios_complex_accessory_detail_screen.png
  bundles/org.openhab.io.homekit/doc/ios_fan_and_light_home_screen.png
  bundles/org.openhab.io.homekit/doc/ios_fan_with_light_details.png
  bundles/org.openhab.io.homekit/doc/ios_fan_with_light_home_screen.png
  bundles/org.openhab.io.homekit/doc/ui_fan_with_light_group_code.png
  bundles/org.openhab.io.homekit/doc/ui_fan_with_light_group_config.png
  bundles/org.openhab.io.homekit/doc/ui_fan_with_light_group_view.png
  bundles/org.openhab.io.homekit/doc/ui_fan_with_light_primary.png
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitChangeListener.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitTaggedItem.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitAccessoryFactory.java
Labels: enhancement

#12510 [miele] Fix configuration validation and optimize performance
  bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/DeviceUtil.java
  bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/MieleGatewayCommunicationController.java
  bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/discovery/MieleApplianceDiscoveryService.java
  bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/ApplianceChannelSelector.java
  bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/ApplianceStatusListener.java
  bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/CoffeeMachineChannelSelector.java
  bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/CoffeeMachineHandler.java
  bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/DiscoveryListener.java
  bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/DishWasherHandler.java
  bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/DishwasherChannelSelector.java
  bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/FridgeChannelSelector.java
  bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/FridgeFreezerChannelSelector.java
  bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/FridgeFreezerHandler.java
  bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/FridgeHandler.java
  bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/HobChannelSelector.java
  bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/HoodChannelSelector.java
  bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/HoodHandler.java
  bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/MieleApplianceHandler.java
  bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/MieleBridgeHandler.java
  bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/OvenChannelSelector.java
  bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/OvenHandler.java
  bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/TumbleDryerChannelSelector.java
  bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/TumbleDryerHandler.java
  bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/WashingMachineChannelSelector.java
  bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/WashingMachineHandler.java
  bundles/org.openhab.binding.miele/src/main/resources/OH-INF/i18n/miele.properties
Labels: enhancement

#12519 [yamahamusiccast] New channel for volume in decibel
  bundles/org.openhab.binding.yamahamusiccast/README.md
  bundles/org.openhab.binding.yamahamusiccast/src/main/java/org/openhab/binding/yamahamusiccast/internal/YamahaMusiccastBindingConstants.java
  bundles/org.openhab.binding.yamahamusiccast/src/main/java/org/openhab/binding/yamahamusiccast/internal/YamahaMusiccastConfiguration.java
  bundles/org.openhab.binding.yamahamusiccast/src/main/java/org/openhab/binding/yamahamusiccast/internal/YamahaMusiccastHandler.java
  bundles/org.openhab.binding.yamahamusiccast/src/main/java/org/openhab/binding/yamahamusiccast/internal/dto/ActualVolume.java
  bundles/org.openhab.binding.yamahamusiccast/src/main/java/org/openhab/binding/yamahamusiccast/internal/dto/Status.java
  bundles/org.openhab.binding.yamahamusiccast/src/main/java/org/openhab/binding/yamahamusiccast/internal/dto/UdpMessage.java
  bundles/org.openhab.binding.yamahamusiccast/src/main/resources/OH-INF/i18n/yamahamusiccast.properties
  bundles/org.openhab.binding.yamahamusiccast/src/main/resources/OH-INF/thing/thing-types.xml
Labels: enhancement

#12507 [openthermgateway] Various improvements
  bundles/org.openhab.binding.openthermgateway/src/main/java/org/openhab/binding/openthermgateway/handler/OpenThermGatewayHandler.java
  bundles/org.openhab.binding.openthermgateway/src/main/java/org/openhab/binding/openthermgateway/internal/OpenThermGatewayCallback.java
  bundles/org.openhab.binding.openthermgateway/src/main/java/org/openhab/binding/openthermgateway/internal/OpenThermGatewaySocketConnector.java
  bundles/org.openhab.binding.openthermgateway/src/main/resources/OH-INF/thing/openthermgateway.xml
Labels: enhancement

#12543 [novafinedust] Fix measurement parsing overflow
  bundles/org.openhab.binding.novafinedust/src/main/java/org/openhab/binding/novafinedust/internal/sds011protocol/SDS011Communicator.java
  bundles/org.openhab.binding.novafinedust/src/main/java/org/openhab/binding/novafinedust/internal/sds011protocol/messages/SensorMeasuredDataReply.java
Labels: bug

#12540 [homekit] fix Fan Rotation Speed. add support for dimmer
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitCharacteristicFactory.java
Labels: bug

#12545 [miele] Use framework's HTTP client
  bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/MieleGatewayCommunicationController.java
  bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/MieleHandlerFactory.java
  bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/MieleApplianceHandler.java
  bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/MieleBridgeHandler.java
Labels: enhancement

#12537 [tesla] Remove (broken) options to obtain refresh token through credentials
  bundles/org.openhab.binding.tesla/README.md
  bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/TeslaBindingConstants.java
  bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/command/TeslaCommandExtension.java
  bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/discovery/TeslaAccountDiscoveryService.java
  bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/handler/TeslaAccountHandler.java
  bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/handler/TeslaSSOHandler.java
  bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/handler/TeslaVehicleHandler.java
  bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/protocol/sso/TokenResponse.java
  bundles/org.openhab.binding.tesla/src/main/resources/OH-INF/i18n/tesla.properties
  bundles/org.openhab.binding.tesla/src/main/resources/OH-INF/thing/account.xml
Labels: enhancement
