Repository openhab/openhab-addons, pull requests merged in 2023-10, with the labels that each got.

#15624 [jrubyscripting] Update README.md
  bundles/org.openhab.automation.jrubyscripting/README.md
Labels: documentation

#15676 [miio] Add support "Mi Smart Antibacterial Humidifier" -
  bundles/org.openhab.binding.miio/README.md
  bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/MiIoDevices.java
  bundles/org.openhab.binding.miio/src/main/resources/OH-INF/i18n/basic.properties
  bundles/org.openhab.binding.miio/src/main/resources/database/deerma.humidifier.jsq2w.json
Labels: enhancement

#15694 Upgrade Netty dependencies to 4.1.99.Final
  itests/org.openhab.binding.mqtt.homeassistant.tests/itest.bndrun
  itests/org.openhab.binding.mqtt.homie.tests/itest.bndrun
  itests/org.openhab.binding.mqtt.ruuvigateway.tests/itest.bndrun
  pom.xml
Labels: enhancement

#15077 [enphase] Add Entrez/JWT support for newer software versions of Envoy
  bundles/org.openhab.binding.enphase/NOTICE
  bundles/org.openhab.binding.enphase/README.md
  bundles/org.openhab.binding.enphase/pom.xml
  bundles/org.openhab.binding.enphase/src/main/feature/feature.xml
  bundles/org.openhab.binding.enphase/src/main/java/org/openhab/binding/enphase/internal/EnphaseHandlerFactory.java
  bundles/org.openhab.binding.enphase/src/main/java/org/openhab/binding/enphase/internal/EnvoyConfiguration.java
  bundles/org.openhab.binding.enphase/src/main/java/org/openhab/binding/enphase/internal/discovery/EnphaseDevicesDiscoveryService.java
  bundles/org.openhab.binding.enphase/src/main/java/org/openhab/binding/enphase/internal/discovery/EnvoyDiscoveryParticipant.java
  bundles/org.openhab.binding.enphase/src/main/java/org/openhab/binding/enphase/internal/dto/EntrezJwtDTO.java
  bundles/org.openhab.binding.enphase/src/main/java/org/openhab/binding/enphase/internal/exception/EnphaseException.java
  bundles/org.openhab.binding.enphase/src/main/java/org/openhab/binding/enphase/internal/exception/EntrezConnectionException.java
  bundles/org.openhab.binding.enphase/src/main/java/org/openhab/binding/enphase/internal/exception/EntrezJwtInvalidException.java
  bundles/org.openhab.binding.enphase/src/main/java/org/openhab/binding/enphase/internal/exception/EnvoyConnectionException.java
  bundles/org.openhab.binding.enphase/src/main/java/org/openhab/binding/enphase/internal/exception/EnvoyNoHostnameException.java
  bundles/org.openhab.binding.enphase/src/main/java/org/openhab/binding/enphase/internal/handler/EntrezConnector.java
  bundles/org.openhab.binding.enphase/src/main/java/org/openhab/binding/enphase/internal/handler/EnvoyBridgeHandler.java
  bundles/org.openhab.binding.enphase/src/main/java/org/openhab/binding/enphase/internal/handler/EnvoyConnector.java
  bundles/org.openhab.binding.enphase/src/main/java/org/openhab/binding/enphase/internal/handler/EnvoyConnectorWrapper.java
  bundles/org.openhab.binding.enphase/src/main/java/org/openhab/binding/enphase/internal/handler/EnvoyEntrezConnector.java
  bundles/org.openhab.binding.enphase/src/main/resources/OH-INF/addon/addon.xml
  bundles/org.openhab.binding.enphase/src/main/resources/OH-INF/i18n/enphase.properties
  bundles/org.openhab.binding.enphase/src/main/resources/OH-INF/thing/thing-types.xml
Labels: enhancement, external bug

#15699 [tesla] fix small typo in documentation
  bundles/org.openhab.binding.tesla/README.md
Labels: documentation

#15675 [miio] new gen vacuums cleaning map and rooms
  bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/MiIoBindingConstants.java
  bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/cloud/CloudConnector.java
  bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/cloud/HomeDTO.java
  bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/cloud/HomeListDTO.java
  bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/cloud/HomeRoomDTO.java
  bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/cloud/MiCloudConnector.java
  bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/handler/MiIoVacuumHandler.java
  bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/robot/HistoryRecordDTO.java
  bundles/org.openhab.binding.miio/src/main/resources/OH-INF/thing/vacuumThing.xml
Labels: enhancement

#15637 [Google TTS] Update README.md
  bundles/org.openhab.voice.googletts/README.md
Labels: documentation

#15709 Update bnd to 7.0.0
  itests/org.openhab.automation.groovyscripting.tests/itest.bndrun
  itests/org.openhab.automation.jsscriptingnashorn.tests/itest.bndrun
  itests/org.openhab.binding.astro.tests/itest.bndrun
  itests/org.openhab.binding.avmfritz.tests/itest.bndrun
  itests/org.openhab.binding.feed.tests/itest.bndrun
  itests/org.openhab.binding.hue.tests/itest.bndrun
  itests/org.openhab.binding.max.tests/itest.bndrun
  itests/org.openhab.binding.mielecloud.tests/itest.bndrun
  itests/org.openhab.binding.modbus.tests/itest.bndrun
  itests/org.openhab.binding.mqtt.homeassistant.tests/itest.bndrun
  itests/org.openhab.binding.mqtt.homie.tests/itest.bndrun
  itests/org.openhab.binding.mqtt.ruuvigateway.tests/itest.bndrun
  itests/org.openhab.binding.ntp.tests/itest.bndrun
  itests/org.openhab.binding.systeminfo.tests/itest.bndrun
  itests/org.openhab.binding.tradfri.tests/itest.bndrun
  itests/org.openhab.binding.wemo.tests/itest.bndrun
  itests/org.openhab.persistence.mapdb.tests/itest.bndrun
  pom.xml
Labels: infrastructure

#15712 [sonos] Add Dolby Digital Plus 2.0 and fix Dolby Digital 2.0
  bundles/org.openhab.binding.sonos/src/main/java/org/openhab/binding/sonos/internal/handler/ZonePlayerHandler.java
  bundles/org.openhab.binding.sonos/src/main/resources/OH-INF/thing/channels.xml
Labels: enhancement

#15706 [sonos] Add support for Move 2
  bundles/org.openhab.binding.sonos/README.md
  bundles/org.openhab.binding.sonos/src/main/java/org/openhab/binding/sonos/internal/SonosBindingConstants.java
  bundles/org.openhab.binding.sonos/src/main/resources/OH-INF/i18n/sonos.properties
  bundles/org.openhab.binding.sonos/src/main/resources/OH-INF/thing/Move2.xml
Labels: enhancement

#15686 [Netatmo] Avoid double refresh of weather channels
  bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/capability/Capability.java
  bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/capability/MeasureCapability.java
  bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/channelhelper/HumidityChannelHelper.java
  bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/utils/ChannelTypeUtils.java
Labels: bug

#15571 [neeo] Convert to OH jetty HttpClient
  bundles/org.openhab.binding.neeo/src/main/java/org/openhab/binding/neeo/internal/NeeoBrainApi.java
  bundles/org.openhab.binding.neeo/src/main/java/org/openhab/binding/neeo/internal/handler/NeeoBrainHandler.java
  bundles/org.openhab.binding.neeo/src/main/java/org/openhab/binding/neeo/internal/handler/NeeoForwardActionsServlet.java
  bundles/org.openhab.binding.neeo/src/main/java/org/openhab/binding/neeo/internal/handler/NeeoHandlerFactory.java
  bundles/org.openhab.binding.neeo/src/main/java/org/openhab/binding/neeo/internal/net/HttpRequest.java
  bundles/org.openhab.binding.neeo/src/main/java/org/openhab/binding/neeo/internal/net/HttpResponse.java
  bundles/org.openhab.io.neeo/src/main/java/org/openhab/io/neeo/NeeoService.java
  bundles/org.openhab.io.neeo/src/main/java/org/openhab/io/neeo/internal/NeeoApi.java
  bundles/org.openhab.io.neeo/src/main/java/org/openhab/io/neeo/internal/NeeoBrainServlet.java
  bundles/org.openhab.io.neeo/src/main/java/org/openhab/io/neeo/internal/NeeoConstants.java
  bundles/org.openhab.io.neeo/src/main/java/org/openhab/io/neeo/internal/NeeoDeviceKeys.java
  bundles/org.openhab.io.neeo/src/main/java/org/openhab/io/neeo/internal/discovery/MdnsBrainDiscovery.java
  bundles/org.openhab.io.neeo/src/main/java/org/openhab/io/neeo/internal/net/HttpRequest.java
  bundles/org.openhab.io.neeo/src/main/java/org/openhab/io/neeo/internal/net/HttpResponse.java
  bundles/org.openhab.io.neeo/src/main/java/org/openhab/io/neeo/internal/servletservices/NeeoBrainService.java
Labels: bug

#15719 [shelly] Always try to stop WebSocketClient
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api2/Shelly2ApiRpc.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api2/Shelly2RpcSocket.java
Labels: bug

#15623 [jythonscripting] Add a note not to use jython
  bundles/org.openhab.automation.jythonscripting/README.md
  bundles/org.openhab.automation.jythonscripting/src/main/resources/OH-INF/addon/addon.xml
Labels: documentation

#15720 [shelly] Revert "Always try to stop WebSocketClient"
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api2/Shelly2ApiRpc.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api2/Shelly2RpcSocket.java
Labels: bug, regression

#15722 [jdbc] Fix logging not working
  bundles/org.openhab.persistence.jdbc/pom.xml
Labels: bug, regression

#15530 [shelly] Fix UNI support up to three DS18B20 sensors
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api/ShellyDeviceProfile.java
Labels: bug

#15721 [shelly] Always try to stop WebSocketClient
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api2/Shelly2ApiRpc.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api2/Shelly2RpcSocket.java
Labels: bug

#15723 [knx] Bugfix problem with DPT 251.600
  bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/dpt/ValueEncoder.java
Labels: bug

#15726 [jdbc] Upgrade H2 to 2.2.224
  bundles/org.openhab.persistence.jdbc/README.md
  bundles/org.openhab.persistence.jdbc/pom.xml
  bundles/org.openhab.persistence.jdbc/src/main/feature/feature.xml
  bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/JdbcConfiguration.java
  bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/db/JdbcH2DAO.java
  bundles/org.openhab.persistence.jdbc/src/main/resources/OH-INF/config/config.xml
  bundles/org.openhab.persistence.jdbc/src/main/resources/OH-INF/i18n/jdbc.properties
  features/openhab-addons-external/src/main/resources/conf/jdbc.cfg
Labels: enhancement, (potentially) not backward compatible

#15618 [jrubyscripting] Inject script context as global
  bundles/org.openhab.automation.jrubyscripting/src/main/java/org/openhab/automation/jrubyscripting/internal/JRubyEngineWrapper.java
  bundles/org.openhab.automation.jrubyscripting/src/main/java/org/openhab/automation/jrubyscripting/internal/JRubyScriptEngineFactory.java
Labels: enhancement

#15732 [hue] Support additional effect types
  bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/dto/clip2/enums/EffectType.java
Labels: enhancement

#15711 [tesla] Remove the minimum 5A charge current limit
  bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/handler/TeslaVehicleHandler.java
Labels: enhancement

#15737 [energidataservice] Add discount tariffs for Aal Elnet, Dinel, Sunds Net and Tarm Elværk Net
  bundles/org.openhab.binding.energidataservice/src/main/java/org/openhab/binding/energidataservice/internal/api/DatahubTariffFilterFactory.java
Labels: enhancement

#15705 [tesla] Add channels for active routing
  bundles/org.openhab.binding.tesla/README.md
  bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/TeslaChannelSelectorProxy.java
  bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/protocol/DriveState.java
  bundles/org.openhab.binding.tesla/src/main/resources/OH-INF/i18n/tesla.properties
  bundles/org.openhab.binding.tesla/src/main/resources/OH-INF/thing/channels.xml
  bundles/org.openhab.binding.tesla/src/main/resources/OH-INF/thing/model3.xml
  bundles/org.openhab.binding.tesla/src/main/resources/OH-INF/thing/models.xml
  bundles/org.openhab.binding.tesla/src/main/resources/OH-INF/thing/modelx.xml
  bundles/org.openhab.binding.tesla/src/main/resources/OH-INF/thing/modely.xml
  bundles/org.openhab.binding.tesla/src/main/resources/OH-INF/update/instructions.xml
Labels: enhancement

#15755 [myq] Fix broken authentication due to changes in the myQ Cloud API
  bundles/org.openhab.binding.myq/src/main/java/org/openhab/binding/myq/internal/handler/MyQAccountHandler.java
Labels: enhancement

#15736 [hue] Fix channel refresh (API v2)
  bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/Clip2ThingHandler.java
Labels: bug

#15408 [hue] Support timed effects
  bundles/org.openhab.binding.hue/doc/readme_v2.md
  bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/HueBindingConstants.java
  bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/dto/clip2/Resource.java
  bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/dto/clip2/TimedEffects.java
  bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/dto/clip2/helper/Setters.java
  bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/Clip2ThingHandler.java
  bundles/org.openhab.binding.hue/src/test/java/org/openhab/binding/hue/internal/clip2/Clip2DtoTest.java
Labels: enhancement

#15656 [hue] Update readme_v2.md
  bundles/org.openhab.binding.hue/doc/readme_v2.md
Labels: documentation

#15541 [lutron] initial submission for RA3 support
  bundles/org.openhab.binding.lutron/README.md
  bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/discovery/LeapDeviceDiscoveryService.java
  bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/handler/LeapBridgeHandler.java
  bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/protocol/leap/LeapMessageParser.java
  bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/protocol/leap/LeapMessageParserCallbacks.java
  bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/protocol/leap/Request.java
  bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/protocol/leap/dto/Device.java
  bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/protocol/leap/dto/Project.java
  bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/protocol/leap/dto/ProjectTimestamp.java
Labels: enhancement

#15751 [http] Fix brightness
  bundles/org.openhab.binding.http/src/main/java/org/openhab/binding/http/internal/converter/ColorItemConverter.java
Labels: bug

#15747 [googletts] Fix authentication after communication error
  bundles/org.openhab.voice.googletts/src/main/java/org/openhab/voice/googletts/internal/GoogleCloudAPI.java
Labels: bug

#15756 [tesla] Fix update timestamp and null exception for offline state
  bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/TeslaBindingConstants.java
  bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/handler/TeslaVehicleHandler.java
Labels: bug

#15388 [hue] Support smart scenes
  bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/dto/clip2/Recall.java
  bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/dto/clip2/Resource.java
  bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/dto/clip2/enums/ResourceType.java
  bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/dto/clip2/enums/SceneRecallAction.java
  bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/dto/clip2/enums/SmartSceneRecallAction.java
  bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/dto/clip2/enums/SmartSceneState.java
  bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/Clip2BridgeHandler.java
  bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/Clip2ThingHandler.java
  bundles/org.openhab.binding.hue/src/test/java/org/openhab/binding/hue/internal/clip2/Clip2DtoTest.java
  bundles/org.openhab.binding.hue/src/test/resources/smart_scene.json
Labels: enhancement

#15764 [boschindego] Add note that batteryVoltage is not populated correctly
  bundles/org.openhab.binding.boschindego/README.md
Labels: documentation

#15542 [roku] Add power, powerState, player, and activeAppName
  bundles/org.openhab.binding.roku/README.md
  bundles/org.openhab.binding.roku/src/main/java/org/openhab/binding/roku/internal/RokuBindingConstants.java
  bundles/org.openhab.binding.roku/src/main/java/org/openhab/binding/roku/internal/handler/RokuHandler.java
  bundles/org.openhab.binding.roku/src/main/resources/OH-INF/config/config.xml
  bundles/org.openhab.binding.roku/src/main/resources/OH-INF/i18n/roku.properties
  bundles/org.openhab.binding.roku/src/main/resources/OH-INF/thing/roku.xml
  bundles/org.openhab.binding.roku/src/main/resources/OH-INF/update/update.xml
Labels: enhancement

#15636 [energidataservice] Add support for reduced electricity tax
  bundles/org.openhab.binding.energidataservice/README.md
  bundles/org.openhab.binding.energidataservice/src/main/java/org/openhab/binding/energidataservice/internal/DatahubTariff.java
  bundles/org.openhab.binding.energidataservice/src/main/java/org/openhab/binding/energidataservice/internal/EnergiDataServiceBindingConstants.java
  bundles/org.openhab.binding.energidataservice/src/main/java/org/openhab/binding/energidataservice/internal/action/EnergiDataServiceActions.java
  bundles/org.openhab.binding.energidataservice/src/main/java/org/openhab/binding/energidataservice/internal/api/DatahubTariffFilterFactory.java
  bundles/org.openhab.binding.energidataservice/src/main/java/org/openhab/binding/energidataservice/internal/config/EnergiDataServiceConfiguration.java
  bundles/org.openhab.binding.energidataservice/src/main/java/org/openhab/binding/energidataservice/internal/handler/EnergiDataServiceHandler.java
  bundles/org.openhab.binding.energidataservice/src/main/resources/OH-INF/config/config.xml
  bundles/org.openhab.binding.energidataservice/src/main/resources/OH-INF/i18n/energidataservice.properties
  bundles/org.openhab.binding.energidataservice/src/main/resources/OH-INF/thing/channel-groups.xml
  bundles/org.openhab.binding.energidataservice/src/main/resources/OH-INF/thing/thing-service.xml
  bundles/org.openhab.binding.energidataservice/src/main/resources/OH-INF/update/instructions.xml
  bundles/org.openhab.binding.energidataservice/src/test/java/org/openhab/binding/energidataservice/internal/action/EnergiDataServiceActionsTest.java
  bundles/org.openhab.binding.energidataservice/src/test/resources/org/openhab/binding/energidataservice/internal/action/ElectricityTaxes.json
  bundles/org.openhab.binding.energidataservice/src/test/resources/org/openhab/binding/energidataservice/internal/action/NetTariffs.json
  bundles/org.openhab.binding.energidataservice/src/test/resources/org/openhab/binding/energidataservice/internal/action/ReducedElectricityTaxes.json
  bundles/org.openhab.binding.energidataservice/src/test/resources/org/openhab/binding/energidataservice/internal/action/SpotPrices20231003.json
Labels: enhancement

#15774 [miele] Rename channel `powerConsumption` to `energyConsumption` and set display unit to litres for `waterConsumption`
  bundles/org.openhab.binding.miele/README.md
  bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/MieleBindingConstants.java
  bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/DishwasherChannelSelector.java
  bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/DishwasherHandler.java
  bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/MieleBridgeHandler.java
  bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/WashingMachineChannelSelector.java
  bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/WashingMachineHandler.java
  bundles/org.openhab.binding.miele/src/main/resources/OH-INF/i18n/miele.properties
  bundles/org.openhab.binding.miele/src/main/resources/OH-INF/thing/channeltypes.xml
  bundles/org.openhab.binding.miele/src/main/resources/OH-INF/thing/dishwasher.xml
  bundles/org.openhab.binding.miele/src/main/resources/OH-INF/thing/washingmachine.xml
  bundles/org.openhab.binding.miele/src/main/resources/OH-INF/update/instructions.xml
Labels: bug, (potentially) not backward compatible

#15641 [homematic] Expansion of virtual data channel for all window/door contacts
  bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/communicator/virtual/StateContactVirtualDatapointHandler.java
Labels: enhancement

#15734 [pushover] Clarify priority message documentation
  bundles/org.openhab.binding.pushover/README.md
Labels: documentation

#14618 [paradoxalarm] Implement detailed partition state
  bundles/org.openhab.binding.paradoxalarm/README.md
  bundles/org.openhab.binding.paradoxalarm/src/main/java/org/openhab/binding/paradoxalarm/internal/handlers/ParadoxAlarmBindingConstants.java
  bundles/org.openhab.binding.paradoxalarm/src/main/java/org/openhab/binding/paradoxalarm/internal/handlers/ParadoxPartitionHandler.java
  bundles/org.openhab.binding.paradoxalarm/src/main/java/org/openhab/binding/paradoxalarm/internal/model/Partition.java
  bundles/org.openhab.binding.paradoxalarm/src/main/java/org/openhab/binding/paradoxalarm/internal/model/PartitionState.java
  bundles/org.openhab.binding.paradoxalarm/src/main/resources/OH-INF/i18n/paradoxalarm.properties
  bundles/org.openhab.binding.paradoxalarm/src/main/resources/OH-INF/thing/partition.xml
  bundles/org.openhab.binding.paradoxalarm/src/main/resources/OH-INF/update/partition_type_update.xml
Labels: enhancement, community approved

#15431 [fronius] Support multiple inverters in powerflow data
  bundles/org.openhab.binding.fronius/README.md
  bundles/org.openhab.binding.fronius/src/main/java/org/openhab/binding/fronius/internal/FroniusBindingConstants.java
  bundles/org.openhab.binding.fronius/src/main/java/org/openhab/binding/fronius/internal/handler/FroniusSymoInverterHandler.java
  bundles/org.openhab.binding.fronius/src/main/resources/OH-INF/i18n/fronius.properties
  bundles/org.openhab.binding.fronius/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.fronius/src/main/resources/OH-INF/update/update.xml
Labels: enhancement

#15278 [speedtest] Add timestamp and result image channel, update thing description
  bundles/org.openhab.binding.speedtest/README.md
  bundles/org.openhab.binding.speedtest/src/main/java/org/openhab/binding/speedtest/internal/SpeedtestBindingConstants.java
  bundles/org.openhab.binding.speedtest/src/main/java/org/openhab/binding/speedtest/internal/SpeedtestHandler.java
  bundles/org.openhab.binding.speedtest/src/main/java/org/openhab/binding/speedtest/internal/SpeedtestHandlerFactory.java
  bundles/org.openhab.binding.speedtest/src/main/resources/OH-INF/i18n/speedtest.properties
  bundles/org.openhab.binding.speedtest/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.speedtest/src/main/resources/OH-INF/update/instructions.xml
Labels: enhancement

#15505 Set explicit timeout for http request
  bundles/org.openhab.binding.bondhome/src/main/java/org/openhab/binding/bondhome/internal/api/BondHttpApi.java
  bundles/org.openhab.binding.chatgpt/src/main/java/org/openhab/binding/chatgpt/internal/ChatGPTHandler.java
  bundles/org.openhab.binding.electroluxair/src/main/java/org/openhab/binding/electroluxair/internal/api/ElectroluxDeltaAPI.java
  bundles/org.openhab.binding.energidataservice/src/main/java/org/openhab/binding/energidataservice/internal/ApiController.java
  bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/api/FreeboxOsIconProvider.java
  bundles/org.openhab.binding.gardena/src/main/java/org/openhab/binding/gardena/internal/GardenaSmartImpl.java
  bundles/org.openhab.binding.generacmobilelink/src/main/java/org/openhab/binding/generacmobilelink/internal/handler/GeneracMobileLinkAccountHandler.java
  bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/GatewayWebTargets.java
  bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/HDPowerViewWebTargets.java
  bundles/org.openhab.binding.icalendar/src/main/java/org/openhab/binding/icalendar/internal/handler/PullJob.java
  bundles/org.openhab.binding.juicenet/src/main/java/org/openhab/binding/juicenet/internal/api/JuiceNetApi.java
  bundles/org.openhab.binding.kostalinverter/src/main/java/org/openhab/binding/kostalinverter/internal/secondgeneration/SecondGenerationConfigurationHandler.java
  bundles/org.openhab.binding.liquidcheck/src/main/java/org/openhab/binding/liquidcheck/internal/discovery/LiquidCheckDiscoveryService.java
  bundles/org.openhab.binding.liquidcheck/src/main/java/org/openhab/binding/liquidcheck/internal/httpclient/LiquidCheckHttpClient.java
  bundles/org.openhab.binding.mcd/src/main/java/org/openhab/binding/mcd/internal/handler/McdBridgeHandler.java
  bundles/org.openhab.binding.mcd/src/main/java/org/openhab/binding/mcd/internal/handler/SensorThingHandler.java
  bundles/org.openhab.binding.meater/src/main/java/org/openhab/binding/meater/internal/api/MeaterRestAPI.java
  bundles/org.openhab.binding.mercedesme/src/main/java/org/openhab/binding/mercedesme/internal/handler/VehicleHandler.java
  bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/MieleGatewayCommunicationController.java
  bundles/org.openhab.binding.mybmw/src/main/java/org/openhab/binding/mybmw/internal/handler/MyBMWProxy.java
  bundles/org.openhab.binding.myq/src/main/java/org/openhab/binding/myq/internal/handler/MyQAccountHandler.java
  bundles/org.openhab.binding.ojelectronics/src/main/java/org/openhab/binding/ojelectronics/internal/services/UpdateService.java
  bundles/org.openhab.binding.plex/src/main/java/org/openhab/binding/plex/internal/handler/PlexApiConnector.java
  bundles/org.openhab.binding.radiothermostat/src/main/java/org/openhab/binding/radiothermostat/internal/communication/RadioThermostatConnector.java
  bundles/org.openhab.binding.renault/src/main/java/org/openhab/binding/renault/internal/api/MyRenaultHttpSession.java
  bundles/org.openhab.binding.semsportal/src/main/java/org/openhab/binding/semsportal/internal/PortalHandler.java
  bundles/org.openhab.binding.sensibo/src/main/java/org/openhab/binding/sensibo/internal/handler/SensiboAccountHandler.java
  bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/api/TapoCloudConnector.java
  bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/constants/TapoBindingSettings.java
  bundles/org.openhab.binding.tellstick/src/main/java/org/openhab/binding/tellstick/internal/local/TelldusLocalDeviceController.java
  bundles/org.openhab.binding.verisure/src/main/java/org/openhab/binding/verisure/internal/VerisureSession.java
  bundles/org.openhab.binding.vizio/src/main/java/org/openhab/binding/vizio/internal/communication/VizioCommunicator.java
Labels: additional testing preferred

#15779 [neeo] Removes extra NEEO from thread name
  bundles/org.openhab.io.neeo/src/main/java/org/openhab/io/neeo/internal/NeeoApi.java
Labels: bug, regression

#15289 [pushover] Add support for Expiring Messages
  bundles/org.openhab.binding.pushover/README.md
  bundles/org.openhab.binding.pushover/src/main/java/org/openhab/binding/pushover/internal/actions/PushoverActions.java
  bundles/org.openhab.binding.pushover/src/main/java/org/openhab/binding/pushover/internal/connection/PushoverMessageBuilder.java
  bundles/org.openhab.binding.pushover/src/main/java/org/openhab/binding/pushover/internal/handler/PushoverAccountHandler.java
  bundles/org.openhab.binding.pushover/src/main/resources/OH-INF/i18n/pushover.properties
  bundles/org.openhab.binding.pushover/src/test/java/org/openhab/binding/pushover/internal/actions/PushoverActionsTest.java
Labels: enhancement

#15792 [ekey] Update documentation
  bundles/org.openhab.binding.ekey/README.md
Labels: documentation

#15802 [jdbc] Upgrade MySQL Connector/J to 8.1.0
  bundles/org.openhab.persistence.jdbc/README.md
  bundles/org.openhab.persistence.jdbc/pom.xml
  bundles/org.openhab.persistence.jdbc/src/main/feature/feature.xml
  bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/JdbcConfiguration.java
Labels: enhancement

#15807 [energidataservice] Adjust filter for Elnet Midt
  bundles/org.openhab.binding.energidataservice/src/main/java/org/openhab/binding/energidataservice/internal/api/DatahubTariffFilterFactory.java
Labels: enhancement

#15808 [netatmo] Add and correct webhook events
  bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/api/data/EventType.java
Labels: bug

#15745 Upgrade json to 20231013
  bundles/org.openhab.binding.ambientweather/pom.xml
  bundles/org.openhab.binding.ambientweather/src/main/feature/feature.xml
  bundles/org.openhab.binding.dbquery/pom.xml
  bundles/org.openhab.binding.mercedesme/pom.xml
  bundles/org.openhab.binding.volumio/pom.xml
  bundles/org.openhab.io.openhabcloud/pom.xml
  bundles/org.openhab.io.openhabcloud/src/main/feature/feature.xml
  bundles/org.openhab.persistence.influxdb/pom.xml
Labels: security, additional testing preferred

#15814 [miio] readme hyperlink fix
  bundles/org.openhab.binding.miio/README.base.md
  bundles/org.openhab.binding.miio/README.md
  bundles/org.openhab.binding.miio/src/test/java/org/openhab/binding/miio/internal/ReadmeHelper.java
Labels: documentation

#15820 [kaleidescape] Register connection in Kaleidescape System log
  bundles/org.openhab.binding.kaleidescape/src/main/java/org/openhab/binding/kaleidescape/internal/KaleidescapeBindingConstants.java
  bundles/org.openhab.binding.kaleidescape/src/main/java/org/openhab/binding/kaleidescape/internal/handler/KaleidescapeHandler.java
Labels: enhancement

#13643 [GPIO] Update GPIO binding to fix issues and provide new functionality
  bundles/org.openhab.binding.gpio/README.md
  bundles/org.openhab.binding.gpio/src/main/java/org/openhab/binding/gpio/internal/ChannelConfigurationException.java
  bundles/org.openhab.binding.gpio/src/main/java/org/openhab/binding/gpio/internal/GPIOBindingConstants.java
  bundles/org.openhab.binding.gpio/src/main/java/org/openhab/binding/gpio/internal/InvalidPullUpDownException.java
  bundles/org.openhab.binding.gpio/src/main/java/org/openhab/binding/gpio/internal/configuration/GPIOConfiguration.java
  bundles/org.openhab.binding.gpio/src/main/java/org/openhab/binding/gpio/internal/configuration/GPIOInputConfiguration.java
  bundles/org.openhab.binding.gpio/src/main/java/org/openhab/binding/gpio/internal/configuration/GPIOOutputConfiguration.java
  bundles/org.openhab.binding.gpio/src/main/java/org/openhab/binding/gpio/internal/configuration/PigpioConfiguration.java
  bundles/org.openhab.binding.gpio/src/main/java/org/openhab/binding/gpio/internal/handler/ChannelHandler.java
  bundles/org.openhab.binding.gpio/src/main/java/org/openhab/binding/gpio/internal/handler/PigpioDigitalInputHandler.java
  bundles/org.openhab.binding.gpio/src/main/java/org/openhab/binding/gpio/internal/handler/PigpioDigitalOutputHandler.java
  bundles/org.openhab.binding.gpio/src/main/java/org/openhab/binding/gpio/internal/handler/PigpioRemoteHandler.java
  bundles/org.openhab.binding.gpio/src/main/resources/OH-INF/i18n/gpio.properties
  bundles/org.openhab.binding.gpio/src/main/resources/OH-INF/thing/pigpio-remote.xml
Labels: enhancement

#15826 [ecovacs] Fix typo in README.md
  bundles/org.openhab.binding.ecovacs/README.md
Labels: documentation
