Repository openhab/openhab-addons, pull requests merged in 2023-04, with the labels that each got.

#14656 [tapocontrol] Color values must be int, not decimal
  bundles/org.openhab.binding.tapocontrol/README.md
  bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/constants/TapoThingConstants.java
  bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/device/TapoLightStrip.java
  bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/device/TapoSmartBulb.java
  bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/device/TapoUniversalDevice.java
  bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/structures/TapoDeviceInfo.java
  bundles/org.openhab.binding.tapocontrol/src/test/java/org/openhab/binding/tapocontrol/internal/device/TapoUniversalDevice.java
  bundles/org.openhab.binding.tapocontrol/src/test/java/org/openhab/binding/tapocontrol/internal/structures/TapoDeviceInfo.java
Labels: bug

#14734 [groovyscripting] Update Groovy to 4.0.11
  bundles/org.openhab.automation.groovyscripting/README.md
  bundles/org.openhab.automation.groovyscripting/pom.xml
Labels: enhancement

#14737 [doorbird] Add audio sink information to README
  bundles/org.openhab.binding.doorbird/README.md
Labels: documentation

#14657 [deutschebahn] Fix spelling and remove empty white image
  bundles/org.openhab.binding.deutschebahn/README.md
  bundles/org.openhab.binding.deutschebahn/doc/Abfahrten_HannoverHBF.png
Labels: documentation

#14748 [fsinternetradio] Add device "Technisat VIOLA 2 C IR" as an supported radio
  bundles/org.openhab.binding.fsinternetradio/README.md
Labels: documentation

#14741 [solarwatt] Add smart heater device support
  bundles/org.openhab.binding.solarwatt/README.md
  bundles/org.openhab.binding.solarwatt/src/main/java/org/openhab/binding/solarwatt/internal/SolarwattBindingConstants.java
  bundles/org.openhab.binding.solarwatt/src/main/java/org/openhab/binding/solarwatt/internal/SolarwattHandlerFactory.java
  bundles/org.openhab.binding.solarwatt/src/main/java/org/openhab/binding/solarwatt/internal/discovery/SolarwattDevicesDiscoveryService.java
  bundles/org.openhab.binding.solarwatt/src/main/java/org/openhab/binding/solarwatt/internal/domain/model/SmartHeater.java
  bundles/org.openhab.binding.solarwatt/src/main/java/org/openhab/binding/solarwatt/internal/factory/EnergyManagerDevicesFactory.java
  bundles/org.openhab.binding.solarwatt/src/main/resources/OH-INF/i18n/solarwatt.properties
  bundles/org.openhab.binding.solarwatt/src/main/resources/OH-INF/thing/thing-types.xml
Labels: enhancement

#14751 [zway] Add a link to detailed instruction on Z-Wave.Me Support site
  bundles/org.openhab.binding.zway/README.md
Labels: documentation

#9913 [speedtest] Binding for Ookla's Speedtest - Initial contribution
  CODEOWNERS
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.speedtest/NOTICE
  bundles/org.openhab.binding.speedtest/README.md
  bundles/org.openhab.binding.speedtest/pom.xml
  bundles/org.openhab.binding.speedtest/src/main/feature/feature.xml
  bundles/org.openhab.binding.speedtest/src/main/java/org/openhab/binding/speedtest/internal/SpeedtestBindingConstants.java
  bundles/org.openhab.binding.speedtest/src/main/java/org/openhab/binding/speedtest/internal/SpeedtestConfiguration.java
  bundles/org.openhab.binding.speedtest/src/main/java/org/openhab/binding/speedtest/internal/SpeedtestHandler.java
  bundles/org.openhab.binding.speedtest/src/main/java/org/openhab/binding/speedtest/internal/SpeedtestHandlerFactory.java
  bundles/org.openhab.binding.speedtest/src/main/java/org/openhab/binding/speedtest/internal/dto/ResultContainer.java
  bundles/org.openhab.binding.speedtest/src/main/java/org/openhab/binding/speedtest/internal/dto/ResultsContainerServerList.java
  bundles/org.openhab.binding.speedtest/src/main/resources/OH-INF/addon/addon.xml
  bundles/org.openhab.binding.speedtest/src/main/resources/OH-INF/i18n/speedtest.properties
  bundles/org.openhab.binding.speedtest/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/pom.xml
Labels: new binding

#14722 [gardena] Improve GardenaSmartImpl initialization order
  bundles/org.openhab.binding.gardena/src/main/java/org/openhab/binding/gardena/internal/GardenaSmartImpl.java
Labels: bug

#14624 [knx] Improve config description for GAs
  bundles/org.openhab.binding.knx/src/main/resources/OH-INF/config/channelConfig.xml
  bundles/org.openhab.binding.knx/src/main/resources/OH-INF/i18n/knx.properties
Labels: enhancement

#14724 Adapt to ColorUtil changes in core
  bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/handler/LightThingHandler.java
  bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/handler/SensorThingHandler.java
  bundles/org.openhab.binding.dmx/src/test/java/org/openhab/binding/dmx/internal/handler/ColorThingHandlerTest.java
  bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/dpt/ValueDecoder.java
  bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/dpt/ValueEncoder.java
  bundles/org.openhab.binding.knx/src/test/java/org/openhab/binding/knx/internal/dpt/DPTTest.java
  bundles/org.openhab.binding.mqtt.generic/src/test/java/org/openhab/binding/mqtt/generic/ChannelStateTests.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/component/JSONSchemaLightTests.java
  bundles/org.openhab.binding.tradfri/src/test/java/org/openhab/binding/tradfri/internal/TradfriColorTest.java
  bundles/org.openhab.binding.webthing/src/test/java/org/openhab/binding/webthing/internal/link/WebthingChannelLinkTest.java
Labels: enhancement

#14762 Disable mielecloud tests
  itests/org.openhab.binding.mielecloud.tests/src/main/java/org/openhab/binding/mielecloud/internal/config/ConfigFlowTest.java
Labels: test

#14638 [generacmobilelink] Major rewrite of the Generac MobileLink Binding
  bundles/org.openhab.binding.generacmobilelink/README.md
  bundles/org.openhab.binding.generacmobilelink/pom.xml
  bundles/org.openhab.binding.generacmobilelink/src/main/feature/feature.xml
  bundles/org.openhab.binding.generacmobilelink/src/main/java/org/openhab/binding/generacmobilelink/internal/GeneracMobileLinkBindingConstants.java
  bundles/org.openhab.binding.generacmobilelink/src/main/java/org/openhab/binding/generacmobilelink/internal/config/GeneracMobileLinkGeneratorConfiguration.java
  bundles/org.openhab.binding.generacmobilelink/src/main/java/org/openhab/binding/generacmobilelink/internal/discovery/GeneracMobileLinkDiscoveryService.java
  bundles/org.openhab.binding.generacmobilelink/src/main/java/org/openhab/binding/generacmobilelink/internal/dto/Account.java
  bundles/org.openhab.binding.generacmobilelink/src/main/java/org/openhab/binding/generacmobilelink/internal/dto/Apparatus.java
  bundles/org.openhab.binding.generacmobilelink/src/main/java/org/openhab/binding/generacmobilelink/internal/dto/ApparatusDetail.java
  bundles/org.openhab.binding.generacmobilelink/src/main/java/org/openhab/binding/generacmobilelink/internal/dto/ApparatusInfo.java
  bundles/org.openhab.binding.generacmobilelink/src/main/java/org/openhab/binding/generacmobilelink/internal/dto/GeneratorStatusDTO.java
  bundles/org.openhab.binding.generacmobilelink/src/main/java/org/openhab/binding/generacmobilelink/internal/dto/GeneratorStatusResponseDTO.java
  bundles/org.openhab.binding.generacmobilelink/src/main/java/org/openhab/binding/generacmobilelink/internal/dto/LoginRequestDTO.java
  bundles/org.openhab.binding.generacmobilelink/src/main/java/org/openhab/binding/generacmobilelink/internal/dto/SelfAssertedResponse.java
  bundles/org.openhab.binding.generacmobilelink/src/main/java/org/openhab/binding/generacmobilelink/internal/dto/SignInConfig.java
  bundles/org.openhab.binding.generacmobilelink/src/main/java/org/openhab/binding/generacmobilelink/internal/factory/GeneracMobileLinkHandlerFactory.java
  bundles/org.openhab.binding.generacmobilelink/src/main/java/org/openhab/binding/generacmobilelink/internal/handler/GeneracMobileLinkAccountHandler.java
  bundles/org.openhab.binding.generacmobilelink/src/main/java/org/openhab/binding/generacmobilelink/internal/handler/GeneracMobileLinkGeneratorHandler.java
  bundles/org.openhab.binding.generacmobilelink/src/main/resources/OH-INF/addon/addon.xml
  bundles/org.openhab.binding.generacmobilelink/src/main/resources/OH-INF/i18n/generacmobilelink.properties
  bundles/org.openhab.binding.generacmobilelink/src/main/resources/OH-INF/thing/thing-types.xml
Labels: enhancement

#14765 [Netatmo] Fix duplicate id on single home
  bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/CommonInterface.java
  bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/capability/AlarmEventCapability.java
  bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/capability/CameraCapability.java
  bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/capability/HomeCapability.java
  bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/capability/HomeSecurityThingCapability.java
  bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/capability/PersonCapability.java
  bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/capability/PresenceCapability.java
Labels: bug, regression

#14668 [Yeelight] Support of ceil26 and ceiling11 devices
  bundles/org.openhab.binding.yeelight/README.md
  bundles/org.openhab.binding.yeelight/src/main/java/org/openhab/binding/yeelight/internal/discovery/YeelightDiscoveryService.java
  bundles/org.openhab.binding.yeelight/src/main/java/org/openhab/binding/yeelight/internal/lib/device/DeviceFactory.java
  bundles/org.openhab.binding.yeelight/src/main/java/org/openhab/binding/yeelight/internal/lib/enums/DeviceType.java
  bundles/org.openhab.binding.yeelight/src/main/java/org/openhab/binding/yeelight/internal/lib/services/DeviceManager.java
Labels: enhancement

#14616 [eKey] Add sourceIp in cases of NAT (Kubernetes deployments)
  bundles/org.openhab.binding.ekey/README.md
  bundles/org.openhab.binding.ekey/src/main/java/org/openhab/binding/ekey/internal/EkeyConfiguration.java
  bundles/org.openhab.binding.ekey/src/main/java/org/openhab/binding/ekey/internal/api/EkeyUdpPacketReceiver.java
  bundles/org.openhab.binding.ekey/src/main/java/org/openhab/binding/ekey/internal/handler/EkeyHandler.java
  bundles/org.openhab.binding.ekey/src/main/resources/OH-INF/i18n/ekey.properties
  bundles/org.openhab.binding.ekey/src/main/resources/OH-INF/thing/thing-types.xml
Labels: enhancement

#14371 [Documentation] Markdown improvements t to z
  bundles/org.openhab.binding.tacmi/README.md
  bundles/org.openhab.binding.tado/README.md
  bundles/org.openhab.binding.tankerkoenig/README.md
  bundles/org.openhab.binding.tapocontrol/README.md
  bundles/org.openhab.binding.telegram/README.md
  bundles/org.openhab.binding.teleinfo/README.md
  bundles/org.openhab.binding.tellstick/README.md
  bundles/org.openhab.binding.tesla/README.md
  bundles/org.openhab.binding.tibber/README.md
  bundles/org.openhab.binding.tivo/README.md
  bundles/org.openhab.binding.touchwand/README.md
  bundles/org.openhab.binding.tplinkrouter/README.md
  bundles/org.openhab.binding.tplinksmarthome/README.md
  bundles/org.openhab.binding.tr064/README.md
  bundles/org.openhab.binding.tradfri/README.md
  bundles/org.openhab.binding.twitter/README.md
  bundles/org.openhab.binding.unifi/README.md
  bundles/org.openhab.binding.unifiedremote/README.md
  bundles/org.openhab.binding.upb/README.md
  bundles/org.openhab.binding.upnpcontrol/README.md
  bundles/org.openhab.binding.urtsi/README.md
  bundles/org.openhab.binding.valloxmv/README.md
  bundles/org.openhab.binding.valloxmv/README_DEV.md
  bundles/org.openhab.binding.vdr/README.md
  bundles/org.openhab.binding.vektiva/README.md
  bundles/org.openhab.binding.velbus/README.md
  bundles/org.openhab.binding.venstarthermostat/README.md
  bundles/org.openhab.binding.ventaair/README.md
  bundles/org.openhab.binding.verisure/README.md
  bundles/org.openhab.binding.vesync/README.md
  bundles/org.openhab.binding.vigicrues/README.md
  bundles/org.openhab.binding.vitotronic/README.md
  bundles/org.openhab.binding.vizio/README.md
  bundles/org.openhab.binding.volvooncall/README.md
  bundles/org.openhab.binding.warmup/README.md
  bundles/org.openhab.binding.weathercompany/README.md
  bundles/org.openhab.binding.weatherunderground/README.md
  bundles/org.openhab.binding.webexteams/README.md
  bundles/org.openhab.binding.webthing/README.md
  bundles/org.openhab.binding.wemo/README.md
  bundles/org.openhab.binding.wifiled/README.md
  bundles/org.openhab.binding.windcentrale/README.md
  bundles/org.openhab.binding.wlanthermo/README.md
  bundles/org.openhab.binding.wled/README.md
  bundles/org.openhab.binding.wolfsmartset/README.md
  bundles/org.openhab.binding.wundergroundupdatereceiver/README.md
  bundles/org.openhab.binding.xmltv/README.md
  bundles/org.openhab.binding.xmppclient/README.md
  bundles/org.openhab.binding.yamahamusiccast/README.md
  bundles/org.openhab.binding.yamahareceiver/README.md
  bundles/org.openhab.binding.yeelight/README.md
  bundles/org.openhab.binding.yioremote/README.md
  bundles/org.openhab.binding.zoneminder/README.md
  bundles/org.openhab.binding.zway/README.md
Labels: documentation

#14752 [boschshc] Enhance device associations in discovery
  bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/discovery/ThingDiscoveryService.java
Labels: enhancement, regression

#14781 [boschshc] Add support for Thermostat SilentMode
  bundles/org.openhab.binding.boschshc/README.md
  bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/devices/BoschSHCBindingConstants.java
  bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/devices/thermostat/ThermostatHandler.java
  bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/services/silentmode/SilentModeService.java
  bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/services/silentmode/SilentModeState.java
  bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/services/silentmode/dto/SilentModeServiceState.java
  bundles/org.openhab.binding.boschshc/src/main/resources/OH-INF/i18n/boschshc.properties
  bundles/org.openhab.binding.boschshc/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/devices/thermostat/ThermostatHandlerTest.java
  bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/services/silentmode/SilentModeStateTest.java
Labels: enhancement

#14788 [Tapocontrol] Restore child device querying
  bundles/org.openhab.binding.tapocontrol/pom.xml
  bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/api/TapoDeviceConnector.java
  bundles/org.openhab.binding.tapocontrol/src/main/resources/OH-INF/addon/addon.xml
Labels: bug, regression

#14791 [mielecloud] Fix failing integration tests
  itests/org.openhab.binding.mielecloud.tests/src/main/java/org/openhab/binding/mielecloud/internal/config/ConfigFlowTest.java
  itests/org.openhab.binding.mielecloud.tests/src/main/java/org/openhab/binding/mielecloud/internal/util/AbstractConfigFlowTest.java
  itests/org.openhab.binding.mielecloud.tests/src/main/java/org/openhab/binding/mielecloud/internal/util/WebsiteCrawler.java
Labels: test

#14798 [jrubyscripting] Update README.md
  bundles/org.openhab.automation.jrubyscripting/README.md
Labels: documentation, patch

#14784 [Netatmo] Fix remaining warnings at Room startup
  bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/capability/RoomCapability.java
Labels: bug, regression

#14772 [knx] Improve rounding when encoding DPT 232.60000
  bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/client/AbstractKNXClient.java
  bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/dpt/ValueDecoder.java
  bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/dpt/ValueEncoder.java
  bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/handler/DeviceThingHandler.java
  bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/handler/IPBridgeThingHandler.java
  bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/handler/SerialBridgeThingHandler.java
  bundles/org.openhab.binding.knx/src/test/java/org/openhab/binding/knx/internal/dpt/DPTTest.java
Labels: enhancement

#14807 [windcentrale] Discover windmills when account goes online
  bundles/org.openhab.binding.windcentrale/src/main/java/org/openhab/binding/windcentrale/internal/WindcentraleDiscoveryService.java
  bundles/org.openhab.binding.windcentrale/src/main/java/org/openhab/binding/windcentrale/internal/handler/WindcentraleAccountHandler.java
  bundles/org.openhab.binding.windcentrale/src/main/java/org/openhab/binding/windcentrale/internal/listener/ThingStatusListener.java
Labels: enhancement

#14745 [boschindego] Implement OAuth2 authorization
  bundles/org.openhab.binding.boschindego/README.md
  bundles/org.openhab.binding.boschindego/src/main/java/org/openhab/binding/boschindego/internal/BoschIndegoBindingConstants.java
  bundles/org.openhab.binding.boschindego/src/main/java/org/openhab/binding/boschindego/internal/BoschIndegoHandlerFactory.java
  bundles/org.openhab.binding.boschindego/src/main/java/org/openhab/binding/boschindego/internal/IndegoController.java
  bundles/org.openhab.binding.boschindego/src/main/java/org/openhab/binding/boschindego/internal/IndegoDeviceController.java
  bundles/org.openhab.binding.boschindego/src/main/java/org/openhab/binding/boschindego/internal/IndegoSession.java
  bundles/org.openhab.binding.boschindego/src/main/java/org/openhab/binding/boschindego/internal/config/BoschIndegoConfiguration.java
  bundles/org.openhab.binding.boschindego/src/main/java/org/openhab/binding/boschindego/internal/console/BoschIndegoCommandExtension.java
  bundles/org.openhab.binding.boschindego/src/main/java/org/openhab/binding/boschindego/internal/discovery/IndegoDiscoveryService.java
  bundles/org.openhab.binding.boschindego/src/main/java/org/openhab/binding/boschindego/internal/dto/response/Mower.java
  bundles/org.openhab.binding.boschindego/src/main/java/org/openhab/binding/boschindego/internal/handler/BoschAccountHandler.java
  bundles/org.openhab.binding.boschindego/src/main/java/org/openhab/binding/boschindego/internal/handler/BoschIndegoHandler.java
  bundles/org.openhab.binding.boschindego/src/main/resources/OH-INF/i18n/boschindego.properties
  bundles/org.openhab.binding.boschindego/src/main/resources/OH-INF/thing/thing-types.xml
Labels: enhancement, (potentially) not backward compatible

#14808 [knx] Adapt to ColorUtil changes in core
  bundles/org.openhab.binding.knx/src/test/java/org/openhab/binding/knx/internal/dpt/DPTTest.java
Labels: test

#14812 [boschindego] Implement OAuth2 authorization
  bundles/org.openhab.binding.boschindego/README.md
  bundles/org.openhab.binding.boschindego/pom.xml
  bundles/org.openhab.binding.boschindego/src/main/java/org/openhab/binding/boschindego/internal/BoschIndegoBindingConstants.java
  bundles/org.openhab.binding.boschindego/src/main/java/org/openhab/binding/boschindego/internal/BoschIndegoHandlerFactory.java
  bundles/org.openhab.binding.boschindego/src/main/java/org/openhab/binding/boschindego/internal/IndegoController.java
  bundles/org.openhab.binding.boschindego/src/main/java/org/openhab/binding/boschindego/internal/IndegoDeviceController.java
  bundles/org.openhab.binding.boschindego/src/main/java/org/openhab/binding/boschindego/internal/IndegoSession.java
  bundles/org.openhab.binding.boschindego/src/main/java/org/openhab/binding/boschindego/internal/config/BoschIndegoConfiguration.java
  bundles/org.openhab.binding.boschindego/src/main/java/org/openhab/binding/boschindego/internal/console/BoschIndegoCommandExtension.java
  bundles/org.openhab.binding.boschindego/src/main/java/org/openhab/binding/boschindego/internal/discovery/IndegoDiscoveryService.java
  bundles/org.openhab.binding.boschindego/src/main/java/org/openhab/binding/boschindego/internal/dto/response/Mower.java
  bundles/org.openhab.binding.boschindego/src/main/java/org/openhab/binding/boschindego/internal/handler/BoschAccountHandler.java
  bundles/org.openhab.binding.boschindego/src/main/java/org/openhab/binding/boschindego/internal/handler/BoschIndegoHandler.java
  bundles/org.openhab.binding.boschindego/src/main/resources/OH-INF/i18n/boschindego.properties
  bundles/org.openhab.binding.boschindego/src/main/resources/OH-INF/thing/thing-types.xml
Labels: enhancement, patch

#14799 [radiothermostat] Add message display channel and improve ThingActions
  bundles/org.openhab.binding.radiothermostat/README.md
  bundles/org.openhab.binding.radiothermostat/src/main/java/org/openhab/binding/radiothermostat/internal/RadioThermostatBindingConstants.java
  bundles/org.openhab.binding.radiothermostat/src/main/java/org/openhab/binding/radiothermostat/internal/RadioThermostatThingActions.java
  bundles/org.openhab.binding.radiothermostat/src/main/java/org/openhab/binding/radiothermostat/internal/communication/RadioThermostatConnector.java
  bundles/org.openhab.binding.radiothermostat/src/main/java/org/openhab/binding/radiothermostat/internal/handler/RadioThermostatHandler.java
  bundles/org.openhab.binding.radiothermostat/src/main/resources/OH-INF/i18n/radiothermostat.properties
  bundles/org.openhab.binding.radiothermostat/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.radiothermostat/src/main/resources/OH-INF/update/instructions.xml
Labels: enhancement

#14821 [mimictts] Fix addon.xml info
  bundles/org.openhab.voice.mimictts/src/main/resources/OH-INF/addon/addon.xml
Labels: bug

#14825 [map][scale] Fix localization
  bundles/org.openhab.transform.map/src/main/java/org/openhab/transform/map/internal/MapTransformationService.java
  bundles/org.openhab.transform.scale/src/main/java/org/openhab/transform/scale/internal/ScaleTransformationService.java
Labels: bug

#14842 Upgrade maven-surefire-plugin to 3.0.0
  pom.xml
Labels: infrastructure

#14846 [renault] update default Kamereon API Key
  bundles/org.openhab.binding.renault/src/main/java/org/openhab/binding/renault/internal/RenaultConfiguration.java
  bundles/org.openhab.binding.renault/src/main/resources/OH-INF/thing/thing-types.xml
Labels: enhancement

#14857 [boschindego] Fix Java 11 backport
  bundles/org.openhab.binding.boschindego/src/main/java/org/openhab/binding/boschindego/internal/IndegoController.java
Labels: bug, patch, regression

#14851 [knx] Add list of DPTs documenting implementation status
  bundles/org.openhab.binding.knx/doc/dpt.txt
Labels: enhancement

#14827 [deconz] Update the roller shutter status
  bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/handler/LightThingHandler.java
  bundles/org.openhab.binding.deconz/src/test/resources/org/openhab/binding/deconz/windowcovering.json
Labels: bug

#14848 [smartmeter] Remove copy-paste-error, as this binding doesn't play sounds
  bundles/org.openhab.binding.smartmeter/README.md
Labels: documentation

#14809 [chatgpt] Initial contribution of the ChatGPT binding
  CODEOWNERS
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.chatgpt/NOTICE
  bundles/org.openhab.binding.chatgpt/README.md
  bundles/org.openhab.binding.chatgpt/pom.xml
  bundles/org.openhab.binding.chatgpt/src/main/feature/feature.xml
  bundles/org.openhab.binding.chatgpt/src/main/java/org/openhab/binding/chatgpt/internal/ChatGPTBindingConstants.java
  bundles/org.openhab.binding.chatgpt/src/main/java/org/openhab/binding/chatgpt/internal/ChatGPTChannelConfiguration.java
  bundles/org.openhab.binding.chatgpt/src/main/java/org/openhab/binding/chatgpt/internal/ChatGPTConfiguration.java
  bundles/org.openhab.binding.chatgpt/src/main/java/org/openhab/binding/chatgpt/internal/ChatGPTHandler.java
  bundles/org.openhab.binding.chatgpt/src/main/java/org/openhab/binding/chatgpt/internal/ChatGPTHandlerFactory.java
  bundles/org.openhab.binding.chatgpt/src/main/java/org/openhab/binding/chatgpt/internal/ChatGPTModelOptionProvider.java
  bundles/org.openhab.binding.chatgpt/src/main/java/org/openhab/binding/chatgpt/internal/dto/ChatResponse.java
  bundles/org.openhab.binding.chatgpt/src/main/resources/OH-INF/addon/addon.xml
  bundles/org.openhab.binding.chatgpt/src/main/resources/OH-INF/i18n/chatgpt.properties
  bundles/org.openhab.binding.chatgpt/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/pom.xml
Labels: new binding

#14824 [senechome] Add additional system states
  bundles/org.openhab.binding.senechome/src/main/java/org/openhab/binding/senechome/internal/SenecSystemStatus.java
Labels: enhancement

#14822 [openwebnet] Fix for dimmer blocked after two OFF are received
  bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/handler/OpenWebNetLightingHandler.java
Labels: bug

#14850 [rollershutterposition] Correct documentation
  bundles/org.openhab.transform.rollershutterposition/README.md
Labels: documentation

#14810 [mqtt][tradfri][webthing] Adapt to ColorUtil changes in core
  bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/values/ColorValue.java
  bundles/org.openhab.binding.mqtt.generic/src/test/java/org/openhab/binding/mqtt/generic/ChannelStateTests.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/component/AbstractComponentTests.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/component/DefaultSchemaLightTests.java
  bundles/org.openhab.binding.tradfri/src/test/java/org/openhab/binding/tradfri/internal/TradfriColorTest.java
  bundles/org.openhab.binding.webthing/src/test/java/org/openhab/binding/webthing/internal/link/WebthingChannelLinkTest.java
Labels: test

#14868 [robonect] Improve job type configuration
  bundles/org.openhab.binding.robonect/src/main/resources/OH-INF/config/config.xml
  bundles/org.openhab.binding.robonect/src/main/resources/OH-INF/i18n/robonect.properties
Labels: enhancement

#14871 [hue] Fix NUPnP discovery
  bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/discovery/HueBridgeNupnpDiscovery.java
  bundles/org.openhab.binding.hue/src/main/resources/OH-INF/addon/addon.xml
  itests/org.openhab.binding.hue.tests/src/main/java/org/openhab/binding/hue/internal/discovery/HueBridgeNupnpDiscoveryOSGITest.java
Labels: bug

#14829 [boschindego] Add device properties
  bundles/org.openhab.binding.boschindego/src/main/java/org/openhab/binding/boschindego/internal/BoschIndegoBindingConstants.java
  bundles/org.openhab.binding.boschindego/src/main/java/org/openhab/binding/boschindego/internal/IndegoController.java
  bundles/org.openhab.binding.boschindego/src/main/java/org/openhab/binding/boschindego/internal/IndegoDeviceController.java
  bundles/org.openhab.binding.boschindego/src/main/java/org/openhab/binding/boschindego/internal/IndegoTypeDatabase.java
  bundles/org.openhab.binding.boschindego/src/main/java/org/openhab/binding/boschindego/internal/discovery/IndegoDiscoveryService.java
  bundles/org.openhab.binding.boschindego/src/main/java/org/openhab/binding/boschindego/internal/dto/response/DevicePropertiesResponse.java
  bundles/org.openhab.binding.boschindego/src/main/java/org/openhab/binding/boschindego/internal/dto/serialization/InstantDeserializer.java
  bundles/org.openhab.binding.boschindego/src/main/java/org/openhab/binding/boschindego/internal/handler/BoschAccountHandler.java
  bundles/org.openhab.binding.boschindego/src/main/java/org/openhab/binding/boschindego/internal/handler/BoschIndegoHandler.java
  bundles/org.openhab.binding.boschindego/src/main/resources/OH-INF/thing/thing-types.xml
Labels: enhancement

#14602 [AirQuality] Enhance API error handling
  bundles/org.openhab.binding.airquality/src/main/java/org/openhab/binding/airquality/internal/AirQualityException.java
  bundles/org.openhab.binding.airquality/src/main/java/org/openhab/binding/airquality/internal/api/ApiBridge.java
  bundles/org.openhab.binding.airquality/src/main/java/org/openhab/binding/airquality/internal/api/Appreciation.java
  bundles/org.openhab.binding.airquality/src/main/java/org/openhab/binding/airquality/internal/api/dto/AirQualityData.java
  bundles/org.openhab.binding.airquality/src/main/java/org/openhab/binding/airquality/internal/api/dto/AirQualityResponse.java
  bundles/org.openhab.binding.airquality/src/main/java/org/openhab/binding/airquality/internal/api/dto/ResponseRoot.java
  bundles/org.openhab.binding.airquality/src/main/java/org/openhab/binding/airquality/internal/discovery/AirQualityDiscoveryService.java
  bundles/org.openhab.binding.airquality/src/main/java/org/openhab/binding/airquality/internal/handler/AirQualityBridgeHandler.java
  bundles/org.openhab.binding.airquality/src/main/java/org/openhab/binding/airquality/internal/handler/AirQualityStationHandler.java
Labels: enhancement

#14872 [ipcamera] Fix servlet exceptions due to non unique names
  bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/servlet/IpCameraServlet.java
Labels: bug

#14874 [jdbc] Upgrade MySQL Connector/J to 8.0.33
  bundles/org.openhab.persistence.jdbc/README.md
  bundles/org.openhab.persistence.jdbc/src/main/feature/feature.xml
  bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/JdbcConfiguration.java
Labels: enhancement, security

#14884 [transform.exec] Fix service whitelisting
  bundles/org.openhab.transform.exec/src/main/java/org/openhab/transform/exec/internal/ExecTransformationWhitelistWatchService.java
Labels: bug, regression

#14893 [jdbc] Upgrade MySQL Connector/J to 8.0.33
  bundles/org.openhab.persistence.jdbc/pom.xml
Labels: bug, regression

#14897 [sleepiq] Restore type adapter for LocalDate
  bundles/org.openhab.binding.sleepiq/src/main/java/org/openhab/binding/sleepiq/internal/api/dto/SleepDataSession.java
  bundles/org.openhab.binding.sleepiq/src/main/java/org/openhab/binding/sleepiq/internal/api/impl/GsonGenerator.java
  bundles/org.openhab.binding.sleepiq/src/main/java/org/openhab/binding/sleepiq/internal/api/impl/typeadapters/LocalDateTypeAdapter.java
Labels: bug

#14903 [easee] Fix start/stop due to changed API
  bundles/org.openhab.binding.easee/README.md
  bundles/org.openhab.binding.easee/src/main/java/org/openhab/binding/easee/internal/EaseeBindingConstants.java
  bundles/org.openhab.binding.easee/src/main/java/org/openhab/binding/easee/internal/model/CustomResponseTransformer.java
Labels: enhancement

#14875 [knx] Fix decoding of DPT 242.600 and add tests
  bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/client/SerialTransportAdapter.java
  bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/dpt/ValueDecoder.java
  bundles/org.openhab.binding.knx/src/test/java/org/openhab/binding/knx/internal/dpt/DPTTest.java
Labels: bug

#14906 [zoneminder] Add support for setting the server run state
  bundles/org.openhab.binding.zoneminder/README.md
  bundles/org.openhab.binding.zoneminder/src/main/java/org/openhab/binding/zoneminder/internal/ZmBindingConstants.java
  bundles/org.openhab.binding.zoneminder/src/main/java/org/openhab/binding/zoneminder/internal/dto/RunStateDTO.java
  bundles/org.openhab.binding.zoneminder/src/main/java/org/openhab/binding/zoneminder/internal/dto/RunStatesDTO.java
  bundles/org.openhab.binding.zoneminder/src/main/java/org/openhab/binding/zoneminder/internal/handler/ZmBridgeHandler.java
  bundles/org.openhab.binding.zoneminder/src/main/resources/OH-INF/i18n/zoneminder.properties
  bundles/org.openhab.binding.zoneminder/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.zoneminder/src/main/resources/OH-INF/update/instructions.xml
Labels: enhancement
