Repository openhab/openhab-addons, pull requests merged in 2023-01, with the labels that each got.

#14123 [netatmo] Adding the ability to append a postfix to registered webhook.
  bundles/org.openhab.binding.netatmo/README.md
  bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/config/ApiHandlerConfiguration.java
  bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/ApiBridgeHandler.java
  bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/servlet/WebhookServlet.java
  bundles/org.openhab.binding.netatmo/src/main/resources/OH-INF/config/config.xml
  bundles/org.openhab.binding.netatmo/src/main/resources/OH-INF/i18n/netatmo.properties
Labels: enhancement

#14131 [luxtronikheatpump] Update URL to Loxwiki
  bundles/org.openhab.binding.luxtronikheatpump/README.md
Labels: documentation

#14140 [netatmo] Adding the ability to append a postfix to registered webhook.
  bundles/org.openhab.binding.netatmo/README.md
  bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/config/ApiHandlerConfiguration.java
  bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/ApiBridgeHandler.java
  bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/servlet/WebhookServlet.java
  bundles/org.openhab.binding.netatmo/src/main/resources/OH-INF/config/config.xml
  bundles/org.openhab.binding.netatmo/src/main/resources/OH-INF/i18n/netatmo.properties
Labels: enhancement

#14136 [chromecast] Improve documentation
  bundles/org.openhab.binding.chromecast/README.md
Labels: documentation

#14135 [jsscripting] Cache openhab-js injection to improve performance
  bundles/org.openhab.automation.jsscripting/pom.xml
  bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/GraalJSScriptEngineFactory.java
  bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/OpenhabGraalJSScriptEngine.java
  bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/ScriptExtensionModuleProvider.java
  bundles/org.openhab.automation.jsscripting/src/main/resources/OH-INF/config/config.xml
  bundles/org.openhab.automation.jsscripting/src/main/resources/OH-INF/i18n/jsscripting.properties
Labels: enhancement

#14121 [homematic] Add hints about using docker
  bundles/org.openhab.binding.homematic/README.md
Labels: documentation

#14146 [shelly] Fix typo
  bundles/org.openhab.binding.shelly/README.md
Labels: documentation

#14142 [jsscripting] Fix regressions from #14135 & Log stack on `IllegalArgumentException`
  bundles/org.openhab.automation.jsscripting/README.md
  bundles/org.openhab.automation.jsscripting/pom.xml
  bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/DebuggingGraalScriptEngine.java
  bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/OpenhabGraalJSScriptEngine.java
Labels: bug, regression

#14150 [bondhome] Implement missing 'Light' device type
  bundles/org.openhab.binding.bondhome/README.md
  bundles/org.openhab.binding.bondhome/src/main/feature/feature.xml
  bundles/org.openhab.binding.bondhome/src/main/java/org/openhab/binding/bondhome/internal/BondHomeBindingConstants.java
  bundles/org.openhab.binding.bondhome/src/main/java/org/openhab/binding/bondhome/internal/api/BondDeviceType.java
  bundles/org.openhab.binding.bondhome/src/main/resources/OH-INF/binding/binding.xml
  bundles/org.openhab.binding.bondhome/src/main/resources/OH-INF/i18n/bondhome.properties
  bundles/org.openhab.binding.bondhome/src/main/resources/OH-INF/thing/Light.xml
Labels: enhancement

#13889 [neohub] Recover faster if NeoHub produces empty responses
  bundles/org.openhab.binding.neohub/src/main/java/org/openhab/binding/neohub/internal/NeoHubException.java
  bundles/org.openhab.binding.neohub/src/main/java/org/openhab/binding/neohub/internal/NeoHubHandler.java
  bundles/org.openhab.binding.neohub/src/main/java/org/openhab/binding/neohub/internal/NeoHubSocket.java
  bundles/org.openhab.binding.neohub/src/main/java/org/openhab/binding/neohub/internal/NeoHubSocketBase.java
  bundles/org.openhab.binding.neohub/src/main/java/org/openhab/binding/neohub/internal/NeoHubWebSocket.java
  bundles/org.openhab.binding.neohub/src/test/java/org/openhab/binding/neohub/test/NeoHubJsonTests.java
  bundles/org.openhab.binding.neohub/src/test/java/org/openhab/binding/neohub/test/NeoHubProtocolTests.java
Labels: enhancement

#14046 [homekit] Add additional troubleshooting steps for homekit
  bundles/org.openhab.io.homekit/README.md
Labels: documentation

#14161 [hueemulation] Fix tests after core change
  bundles/org.openhab.io.hueemulation/src/test/java/org/openhab/io/hueemulation/internal/rest/mocks/DummyMetadataRegistry.java
Labels: test

#14166 [jsscripting] Update docs for code caching
  bundles/org.openhab.automation.jsscripting/README.md
  bundles/org.openhab.automation.jsscripting/doc/settings.png
Labels: documentation

#14076 [renault] Add new channels 'batterystatusupdated' and 'locked'
  bundles/org.openhab.binding.renault/README.md
  bundles/org.openhab.binding.renault/doc/sitemap.png
  bundles/org.openhab.binding.renault/src/main/java/org/openhab/binding/renault/internal/RenaultBindingConstants.java
  bundles/org.openhab.binding.renault/src/main/java/org/openhab/binding/renault/internal/api/Car.java
  bundles/org.openhab.binding.renault/src/main/java/org/openhab/binding/renault/internal/api/MyRenaultHttpSession.java
  bundles/org.openhab.binding.renault/src/main/java/org/openhab/binding/renault/internal/api/exceptions/RenaultActionException.java
  bundles/org.openhab.binding.renault/src/main/java/org/openhab/binding/renault/internal/handler/RenaultHandler.java
  bundles/org.openhab.binding.renault/src/main/resources/OH-INF/i18n/renault.properties
  bundles/org.openhab.binding.renault/src/main/resources/OH-INF/thing/thing-types.xml
Labels: enhancement

#14165 Exclude 3rdparty directories from license header generation
  pom.xml
Labels: infrastructure

#14168 [ecobee] Make more channels advanced
  bundles/org.openhab.binding.ecobee/src/main/resources/OH-INF/thing/thing-types.xml
Labels: enhancement

#14169 [homekit] properly expose services from dummy accessories
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/DummyHomekitAccessory.java
Labels: bug

#14164 [sonos] Correct identification of tuneIn started from Alexa
  bundles/org.openhab.binding.sonos/src/main/java/org/openhab/binding/sonos/internal/handler/ZonePlayerHandler.java
Labels: bug

#14156 [paradoxalarm] Fix namespaces for tests
  bundles/org.openhab.binding.paradoxalarm/src/test/java/org/openhab/binding/paradoxalarm/internal/Main.java
  bundles/org.openhab.binding.paradoxalarm/src/test/java/org/openhab/binding/paradoxalarm/internal/MainMethodArgParser.java
  bundles/org.openhab.binding.paradoxalarm/src/test/java/org/openhab/binding/paradoxalarm/internal/TestCreateCommandPayload.java
  bundles/org.openhab.binding.paradoxalarm/src/test/java/org/openhab/binding/paradoxalarm/internal/TestEncryptionHandler.java
  bundles/org.openhab.binding.paradoxalarm/src/test/java/org/openhab/binding/paradoxalarm/internal/TestGetBytes.java
  bundles/org.openhab.binding.paradoxalarm/src/test/java/org/openhab/binding/paradoxalarm/internal/TestParadoxUtil.java
  bundles/org.openhab.binding.paradoxalarm/src/test/resources/simplelogger.properties
Labels: test

#14171 Fix incorrectly formatted license headers
  bundles/org.openhab.binding.mycroft/src/main/java/org/openhab/binding/mycroft/internal/MycroftHandlerFactory.java
  bundles/org.openhab.binding.souliss/src/main/java/org/openhab/binding/souliss/internal/handler/TypicalCommonMethods.java
Labels: infrastructure

#14158 [chromecast] Fix thing go offline after stop command
  bundles/org.openhab.binding.chromecast/src/main/java/org/openhab/binding/chromecast/internal/ChromecastAudioSink.java
  bundles/org.openhab.binding.chromecast/src/main/java/org/openhab/binding/chromecast/internal/ChromecastCommander.java
  bundles/org.openhab.binding.chromecast/src/main/java/org/openhab/binding/chromecast/internal/ChromecastEventReceiver.java
Labels: bug

#13941 [miio] add support Xiaomi Smart Air Purifier 4 Pro zhimi.airp.vb4
  bundles/org.openhab.binding.miio/README.md
  bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/MiIoDevices.java
  bundles/org.openhab.binding.miio/src/main/resources/OH-INF/i18n/basic.properties
  bundles/org.openhab.binding.miio/src/main/resources/database/zhimi.airp.vb4-miot.json
Labels: enhancement

#14122 [doorbird] Add audiosink
  bundles/org.openhab.binding.doorbird/src/main/java/org/openhab/binding/doorbird/internal/DoorbirdHandlerFactory.java
  bundles/org.openhab.binding.doorbird/src/main/java/org/openhab/binding/doorbird/internal/api/DoorbirdAPI.java
  bundles/org.openhab.binding.doorbird/src/main/java/org/openhab/binding/doorbird/internal/audio/ConvertedInputStream.java
  bundles/org.openhab.binding.doorbird/src/main/java/org/openhab/binding/doorbird/internal/audio/DoorbirdAudioSink.java
  bundles/org.openhab.binding.doorbird/src/main/java/org/openhab/binding/doorbird/internal/handler/DoorbellHandler.java
Labels: enhancement

#14170 [ecobee] Fix issue with UTC and local dates
  bundles/org.openhab.binding.ecobee/src/main/java/org/openhab/binding/ecobee/internal/EcobeeBindingConstants.java
  bundles/org.openhab.binding.ecobee/src/main/java/org/openhab/binding/ecobee/internal/api/EcobeeApi.java
  bundles/org.openhab.binding.ecobee/src/main/java/org/openhab/binding/ecobee/internal/dto/thermostat/InstantDeserializer.java
  bundles/org.openhab.binding.ecobee/src/main/java/org/openhab/binding/ecobee/internal/dto/thermostat/LocalDateTimeDeserializer.java
  bundles/org.openhab.binding.ecobee/src/main/java/org/openhab/binding/ecobee/internal/dto/thermostat/RuntimeDTO.java
  bundles/org.openhab.binding.ecobee/src/main/java/org/openhab/binding/ecobee/internal/dto/thermostat/ThermostatDTO.java
  bundles/org.openhab.binding.ecobee/src/main/java/org/openhab/binding/ecobee/internal/dto/thermostat/WeatherDTO.java
  bundles/org.openhab.binding.ecobee/src/main/java/org/openhab/binding/ecobee/internal/dto/thermostat/WeatherForecastDTO.java
  bundles/org.openhab.binding.ecobee/src/main/java/org/openhab/binding/ecobee/internal/handler/EcobeeThermostatBridgeHandler.java
  bundles/org.openhab.binding.ecobee/src/main/java/org/openhab/binding/ecobee/internal/handler/EcobeeUtils.java
Labels: bug

#14187 Fix Markdown warnings in README.md
  bundles/org.openhab.automation.jrubyscripting/README.md
  bundles/org.openhab.binding.amazondashbutton/README.md
  bundles/org.openhab.binding.digitalstrom/README.md
  bundles/org.openhab.binding.dwdunwetter/README.md
  bundles/org.openhab.binding.homematic/README.md
  bundles/org.openhab.binding.mihome/README.md
  bundles/org.openhab.binding.modbus/README.md
  bundles/org.openhab.binding.nibeuplink/README.md
  bundles/org.openhab.binding.powermax/README.md
  bundles/org.openhab.binding.rfxcom/README.md
  bundles/org.openhab.binding.russound/README.md
  bundles/org.openhab.binding.solaredge/README.md
  bundles/org.openhab.binding.sonyaudio/README.md
  bundles/org.openhab.binding.tacmi/README.md
  bundles/org.openhab.binding.teleinfo/README.md
  bundles/org.openhab.binding.velux/README.md
  bundles/org.openhab.binding.wolfsmartset/README.md
  bundles/org.openhab.binding.yamahareceiver/README.md
  bundles/org.openhab.io.homekit/README.md
  bundles/org.openhab.transform.jinja/README.md
  bundles/org.openhab.transform.regex/README.md
  bundles/org.openhab.transform.scale/README.md
  bundles/org.openhab.transform.xpath/README.md
  bundles/org.openhab.voice.googlestt/README.md
Labels: documentation

#14196 [velux] Documentation improvements
  bundles/org.openhab.binding.velux/README.md
  bundles/org.openhab.binding.velux/doc/conf/rules/velux.rules
  bundles/org.openhab.binding.velux/doc/conf/things/velux.things
  bundles/org.openhab.binding.velux/doc/items.md
  bundles/org.openhab.binding.velux/doc/rules.md
  bundles/org.openhab.binding.velux/doc/sitemaps.md
  bundles/org.openhab.binding.velux/doc/things.md
Labels: documentation

#14191 [chromecast] Fix for NPE when playerState is null
  bundles/org.openhab.binding.chromecast/src/main/java/org/openhab/binding/chromecast/internal/ChromecastStatusUpdater.java
Labels: bug

#14182 [astro] Add moon accuracy tests
  bundles/org.openhab.binding.astro/src/test/java/org/openhab/binding/astro/internal/calc/MoonCalcTest.java
Labels: test

#14173 Upgrade maven-javadoc-plugin to release 3.2.0
  pom.xml
Labels: infrastructure

#14201 [squeezebox] Add new channels for additional tags
  bundles/org.openhab.binding.squeezebox/README.md
  bundles/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/SqueezeBoxBindingConstants.java
  bundles/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/discovery/SqueezeBoxPlayerDiscoveryParticipant.java
  bundles/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/handler/SqueezeBoxNotificationListener.java
  bundles/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/handler/SqueezeBoxPlayerEventListener.java
  bundles/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/handler/SqueezeBoxPlayerHandler.java
  bundles/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/handler/SqueezeBoxServerHandler.java
  bundles/org.openhab.binding.squeezebox/src/main/resources/OH-INF/thing/thing-types.xml
Labels: enhancement

#14203 [gardena] Fix server ping timeout logic
  bundles/org.openhab.binding.gardena/src/main/java/org/openhab/binding/gardena/internal/GardenaSmartWebSocket.java
Labels: bug

#14155 [bondhome] Add raw speed channel
  bundles/org.openhab.binding.bondhome/src/main/java/org/openhab/binding/bondhome/internal/BondHomeBindingConstants.java
  bundles/org.openhab.binding.bondhome/src/main/java/org/openhab/binding/bondhome/internal/handler/BondDeviceHandler.java
  bundles/org.openhab.binding.bondhome/src/main/resources/OH-INF/i18n/bondhome.properties
  bundles/org.openhab.binding.bondhome/src/main/resources/OH-INF/thing/ChannelGroups.xml
  bundles/org.openhab.binding.bondhome/src/main/resources/OH-INF/thing/Channels.xml
Labels: enhancement

#14055 [homekit] Add support for TV accessory
  bundles/org.openhab.io.homekit/README.md
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitAccessoryType.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitCharacteristicType.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitTaggedItem.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/AbstractHomekitAccessoryImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitAccessoryFactory.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitCharacteristicFactory.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitInputSourceImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitMetadataCharacteristicFactory.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitTelevisionImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitTelevisionSpeakerImpl.java
Labels: enhancement

#14213 [homematic] Fix updating enum config values
  bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/handler/HomematicThingHandler.java
Labels: bug

#14209 [homekit] Implement IrrigationSystem Accessory
  bundles/org.openhab.io.homekit/README.md
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitAccessoryType.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitCharacteristicType.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitAccessoryFactory.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitIrrigationSystemImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitMetadataCharacteristicFactory.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitValveImpl.java
Labels: enhancement

#14120 [mimictts] Fix ssml and playing from audiosinks using the audio servlet
  bundles/org.openhab.voice.mimictts/README.md
  bundles/org.openhab.voice.mimictts/src/main/java/org/openhab/voice/mimic/internal/AutoDeleteFileAudioStream.java
  bundles/org.openhab.voice.mimictts/src/main/java/org/openhab/voice/mimic/internal/MimicConfiguration.java
  bundles/org.openhab.voice.mimictts/src/main/java/org/openhab/voice/mimic/internal/MimicTTSService.java
  bundles/org.openhab.voice.mimictts/src/main/resources/OH-INF/config/config.xml
  bundles/org.openhab.voice.mimictts/src/main/resources/OH-INF/i18n/mimictts.properties
Labels: bug, enhancement

#14217 [gree] Allow wider temperature range
  bundles/org.openhab.binding.gree/src/main/java/org/openhab/binding/gree/internal/GreeBindingConstants.java
  bundles/org.openhab.binding.gree/src/main/java/org/openhab/binding/gree/internal/GreeException.java
  bundles/org.openhab.binding.gree/src/main/java/org/openhab/binding/gree/internal/discovery/GreeDeviceFinder.java
  bundles/org.openhab.binding.gree/src/main/java/org/openhab/binding/gree/internal/handler/GreeAirDevice.java
Labels: bug

#14199 [miele] Improve multicast implementation
  bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/MieleBridgeHandler.java
Labels: enhancement

#14219 [gree] Fix thing-type min state
  bundles/org.openhab.binding.gree/src/main/resources/OH-INF/thing/thing-types.xml
Labels: bug, regression

#14174 [knx] Fix javadoc errors
  bundles/org.openhab.binding.knx/pom.xml
  bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/KNXBindingConstants.java
  bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/client/BusMessageListener.java
  bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/config/DeviceConfig.java
  bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/handler/IPBridgeThingHandler.java
  bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/handler/SerialBridgeThingHandler.java
  bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/i18n/KNXTranslationProvider.java
Labels: documentation

#14228 [influxdb] Add docs for usage of self-signed certs
  bundles/org.openhab.persistence.influxdb/README.md
Labels: documentation

#14238 [rrd4j] Avoid IAE thrown if e.g. invalid start/end time given
  bundles/org.openhab.persistence.rrd4j/src/main/java/org/openhab/persistence/rrd4j/internal/RRD4jPersistenceService.java
Labels: bug

#14249 [unifi] Various stability improvements
  bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/api/UniFiCommunicationException.java
  bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/api/UniFiController.java
  bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/api/UniFiControllerRequest.java
  bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/api/cache/UniFiCache.java
  bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/api/cache/UniFiControllerCache.java
  bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/api/dto/UniFiClient.java
  bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/api/dto/UniFiPortTuple.java
  bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/api/dto/UniFiSwitchPorts.java
  bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/api/dto/UniFiUnknownClient.java
  bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/api/dto/UniFiWiredClient.java
  bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/api/dto/UniFiWirelessClient.java
  bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/handler/UniFiClientThingHandler.java
  bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/handler/UniFiControllerThingHandler.java
  bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/handler/UniFiPoePortThingHandler.java
  bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/handler/UniFiThingDiscoveryService.java
  bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/handler/UniFiWlanThingHandler.java
  bundles/org.openhab.binding.unifi/src/main/resources/OH-INF/i18n/unifi.properties
Labels: bug

#14027 Fix build after core changes
  bundles/org.openhab.binding.wundergroundupdatereceiver/src/test/java/org/openhab/binding/wundergroundupdatereceiver/internal/WundergroundUpdateReceiverDiscoveryServiceTest.java
Labels: awaiting other PR

#14224 [jeelink] Fixed wrong TX22 rain value
  bundles/org.openhab.binding.jeelink/src/main/java/org/openhab/binding/jeelink/internal/lacrosse/LaCrosseTemperatureSensorHandler.java
  bundles/org.openhab.binding.jeelink/src/main/java/org/openhab/binding/jeelink/internal/lacrosse/LgwSensorHandler.java
  bundles/org.openhab.binding.jeelink/src/main/java/org/openhab/binding/jeelink/internal/lacrosse/Tx22ReadingConverter.java
  bundles/org.openhab.binding.jeelink/src/main/java/org/openhab/binding/jeelink/internal/util/StringUtils.java
Labels: bug

#14248 [nuvo] Publish ALLOFF event for use in source rules
  bundles/org.openhab.binding.nuvo/README.md
  bundles/org.openhab.binding.nuvo/src/main/java/org/openhab/binding/nuvo/internal/NuvoBindingConstants.java
  bundles/org.openhab.binding.nuvo/src/main/java/org/openhab/binding/nuvo/internal/handler/NuvoHandler.java
Labels: enhancement

#14230 [mqtt.homeassistant] add support for Number and Select components
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/ComponentFactory.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/Number.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/Select.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/component/NumberTests.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/component/SelectTests.java
Labels: enhancement

#14253 [gree] Remove unneeded i18n entry addon.gree.label
  bundles/org.openhab.binding.gree/src/main/resources/OH-INF/i18n/gree.properties
  bundles/org.openhab.binding.gree/src/main/resources/OH-INF/i18n/gree_de.properties
  bundles/org.openhab.binding.gree/src/main/resources/OH-INF/i18n/gree_hu.properties
Labels: translation

#14254 Update README.md
  bundles/org.openhab.binding.homeconnect/README.md
Labels: documentation

#14172 [dominoswiss] Fix Bridge-Loading with OH3_3 and OH3_4
  bundles/org.openhab.binding.dominoswiss/src/main/java/org/openhab/binding/dominoswiss/internal/EGateHandler.java
Labels: bug

#14236 [Tibber] Added "today" API channel
  bundles/org.openhab.binding.tibber/README.md
  bundles/org.openhab.binding.tibber/src/main/java/org/openhab/binding/tibber/internal/TibberBindingConstants.java
  bundles/org.openhab.binding.tibber/src/main/java/org/openhab/binding/tibber/internal/handler/TibberHandler.java
  bundles/org.openhab.binding.tibber/src/main/java/org/openhab/binding/tibber/internal/handler/TibberPriceConsumptionHandler.java
  bundles/org.openhab.binding.tibber/src/main/resources/OH-INF/i18n/tibber.properties
  bundles/org.openhab.binding.tibber/src/main/resources/OH-INF/thing/thing-types.xml
Labels: enhancement

#14245 [evcc] Adjust to breaking API change & Add new channel
  bundles/org.openhab.binding.evcc/README.md
  bundles/org.openhab.binding.evcc/src/main/java/org/openhab/binding/evcc/internal/EvccBindingConstants.java
  bundles/org.openhab.binding.evcc/src/main/java/org/openhab/binding/evcc/internal/EvccHandler.java
  bundles/org.openhab.binding.evcc/src/main/java/org/openhab/binding/evcc/internal/api/dto/Loadpoint.java
  bundles/org.openhab.binding.evcc/src/main/java/org/openhab/binding/evcc/internal/api/dto/Result.java
  bundles/org.openhab.binding.evcc/src/main/java/org/openhab/binding/evcc/internal/api/dto/Status.java
  bundles/org.openhab.binding.evcc/src/main/resources/OH-INF/i18n/evcc.properties
  bundles/org.openhab.binding.evcc/src/main/resources/OH-INF/thing/thing-types.xml
Labels: enhancement

#14266 [openwebnet] Updated section in README on shutter position with info on the automatic calibration
  bundles/org.openhab.binding.openwebnet/README.md
Labels: documentation

#14265 [Netatmo] Preserving outside temperature minimal ranges for dynamic channels
  bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/capability/MeasureCapability.java
Labels: bug

#14281 [jdbc] Perform upsert on conflict like the default for MySQL (PostgreSQL >=9.5)
  bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/db/JdbcPostgresqlDAO.java
Labels: bug

#14277 [tibber] Add accumulatedReward channel
  bundles/org.openhab.binding.tibber/README.md
  bundles/org.openhab.binding.tibber/src/main/java/org/openhab/binding/tibber/internal/TibberBindingConstants.java
  bundles/org.openhab.binding.tibber/src/main/java/org/openhab/binding/tibber/internal/handler/TibberHandler.java
  bundles/org.openhab.binding.tibber/src/main/resources/OH-INF/i18n/tibber.properties
  bundles/org.openhab.binding.tibber/src/main/resources/OH-INF/thing/thing-types.xml
Labels: enhancement

#14272 [rotel] Fix reader thread handling
  bundles/org.openhab.binding.rotel/src/main/java/org/openhab/binding/rotel/internal/communication/RotelConnector.java
  bundles/org.openhab.binding.rotel/src/main/java/org/openhab/binding/rotel/internal/communication/RotelIpConnector.java
  bundles/org.openhab.binding.rotel/src/main/java/org/openhab/binding/rotel/internal/communication/RotelSerialConnector.java
  bundles/org.openhab.binding.rotel/src/main/java/org/openhab/binding/rotel/internal/communication/RotelSimuConnector.java
Labels: bug

#14240 [mqtt.homeassistant] Mark disabled by default components as advanced channels
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/ComponentChannel.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/AbstractComponent.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/Vacuum.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/config/dto/AbstractChannelConfiguration.java
Labels: enhancement

#14234 [mqtt.homeassistant] add support for DeviceTrigger component
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/ComponentFactory.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/DeviceTrigger.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/component/AbstractComponentTests.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/component/DeviceTriggerTests.java
Labels: enhancement

#14233 [mqtt.homeassistant] support command_template for fan components
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/Fan.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/component/FanTests.java
Labels: enhancement

#14226 [homekit] fix restarted on network interface change
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitImpl.java
Labels: bug

#14163 [wemo] Fix stability issues
  bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/WemoBindingConstants.java
  bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/WemoHandlerFactory.java
  bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/handler/WemoBaseThingHandler.java
  bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/handler/WemoCoffeeHandler.java
  bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/handler/WemoCrockpotHandler.java
  bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/handler/WemoDimmerHandler.java
  bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/handler/WemoHandler.java
  bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/handler/WemoHolmesHandler.java
  bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/handler/WemoInsightHandler.java
  bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/handler/WemoLightHandler.java
  bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/handler/WemoMakerHandler.java
  bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/handler/WemoMotionHandler.java
  bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/handler/WemoSwitchHandler.java
  itests/org.openhab.binding.wemo.tests/src/main/java/org/openhab/binding/wemo/internal/handler/test/WemoHandlerOSGiTest.java
  itests/org.openhab.binding.wemo.tests/src/main/java/org/openhab/binding/wemo/internal/handler/test/WemoInsightHandlerTest.java
Labels: bug

#14270 (MyBMW] command "horn-blow" not "horn-low"
  bundles/org.openhab.binding.mybmw/README.md
Labels: documentation

#14284 [unifi] Guest wifi vouchers
  bundles/org.openhab.binding.unifi/README.md
  bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/UniFiBindingConstants.java
  bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/UniFiVoucherChannelConfig.java
  bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/api/UniFiController.java
  bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/api/cache/UniFiControllerCache.java
  bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/api/cache/UniFiVoucherCache.java
  bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/api/dto/UniFiSite.java
  bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/api/dto/UniFiVoucher.java
  bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/api/util/UniFiVoucherInstanceCreator.java
  bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/handler/UniFiSiteThingHandler.java
  bundles/org.openhab.binding.unifi/src/main/resources/OH-INF/config/config.xml
  bundles/org.openhab.binding.unifi/src/main/resources/OH-INF/thing/thing-types.xml
Labels: enhancement

#14251 [openhabcloud] Reconnection Fixes
  bundles/org.openhab.io.openhabcloud/src/main/java/org/openhab/io/openhabcloud/internal/CloudClient.java
  bundles/org.openhab.io.openhabcloud/src/main/java/org/openhab/io/openhabcloud/internal/CloudService.java
Labels: bug

#14273 [tibber] Fix NPE on server issues
  bundles/org.openhab.binding.tibber/src/main/java/org/openhab/binding/tibber/internal/handler/TibberHandler.java
Labels: bug

#14274 [homematic] HUMIDITY and CONTROL_MODE as standard channels
  bundles/org.openhab.binding.homematic/src/main/resources/homematic/standard-datapoints.properties
Labels: enhancement

#14225 [velux] Do not use new API on Somfy devices
  bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/handler/ChannelActuatorPosition.java
  bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/things/VeluxProductPosition.java
Labels: bug

#13693 [fmiweather] HIRLAM → HARMONIE weather model
  bundles/org.openhab.binding.fmiweather/README.md
  bundles/org.openhab.binding.fmiweather/src/main/java/org/openhab/binding/fmiweather/internal/client/ForecastRequest.java
  bundles/org.openhab.binding.fmiweather/src/main/java/org/openhab/binding/fmiweather/internal/discovery/CitiesOfFinland.java
  bundles/org.openhab.binding.fmiweather/src/test/java/org/openhab/binding/fmiweather/FMIRequestTest.java
  bundles/org.openhab.binding.fmiweather/src/test/java/org/openhab/binding/fmiweather/FMIResponseParsingMultiplePlacesTest.java
  bundles/org.openhab.binding.fmiweather/src/test/resources/org/openhab/binding/fmiweather/forecast_multiple_places.xml
Labels: bug, additional testing preferred

#14132 [astro] Add option to force event to occur
  bundles/org.openhab.binding.astro/README.md
  bundles/org.openhab.binding.astro/src/main/java/org/openhab/binding/astro/internal/config/AstroChannelConfig.java
  bundles/org.openhab.binding.astro/src/main/java/org/openhab/binding/astro/internal/job/Job.java
  bundles/org.openhab.binding.astro/src/main/java/org/openhab/binding/astro/internal/util/DateTimeUtils.java
  bundles/org.openhab.binding.astro/src/main/resources/OH-INF/config/config.xml
  bundles/org.openhab.binding.astro/src/main/resources/OH-INF/i18n/astro.properties
  bundles/org.openhab.binding.astro/src/test/java/org/openhab/binding/astro/internal/job/JobTest.java
Labels: enhancement

#14283 [unifi] Added channels name and hostname to client things.
  bundles/org.openhab.binding.unifi/README.md
  bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/UniFiBindingConstants.java
  bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/api/cache/UniFiCache.java
  bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/api/cache/UniFiClientCache.java
  bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/api/dto/UniFiClient.java
  bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/handler/UniFiClientThingHandler.java
  bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/handler/UniFiSiteThingHandler.java
  bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/handler/UniFiThingDiscoveryService.java
  bundles/org.openhab.binding.unifi/src/main/resources/OH-INF/config/config.xml
  bundles/org.openhab.binding.unifi/src/main/resources/OH-INF/i18n/unifi.properties
  bundles/org.openhab.binding.unifi/src/main/resources/OH-INF/thing/thing-types.xml
Labels: enhancement

#14290 [shelly] Cancel the init job when the thing handler is disposed
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/handler/ShellyBaseHandler.java
Labels: bug

#14296 [influxdb] Fix re-connection issues
  bundles/org.openhab.persistence.influxdb/src/main/java/org/openhab/persistence/influxdb/InfluxDBPersistenceService.java
Labels: bug

#13944 [jrubyscripting] allow disabling dependency tracking
  bundles/org.openhab.automation.jrubyscripting/README.md
  bundles/org.openhab.automation.jrubyscripting/src/main/java/org/openhab/automation/jrubyscripting/internal/JRubyScriptEngineConfiguration.java
  bundles/org.openhab.automation.jrubyscripting/src/main/java/org/openhab/automation/jrubyscripting/internal/JRubyScriptEngineFactory.java
  bundles/org.openhab.automation.jrubyscripting/src/main/resources/OH-INF/config/config.xml
  bundles/org.openhab.automation.jrubyscripting/src/main/resources/OH-INF/i18n/jruby.properties
Labels: enhancement

#14300 [tesla] Fix account going offline every few seconds
  bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/handler/TeslaAccountHandler.java
Labels: bug

#14308 [orbitbhyve] Fix for NumberFormatException when parsing json object
  bundles/org.openhab.binding.orbitbhyve/src/main/java/org/openhab/binding/orbitbhyve/internal/model/OrbitBhyveDevice.java
Labels: bug
