Repository openhab/openhab-addons, pull requests merged in 2023-07, with the labels that each got.

#15109 [mactts] Add LRU cache
  bundles/org.openhab.voice.mactts/README.md
  bundles/org.openhab.voice.mactts/src/main/java/org/openhab/voice/mactts/internal/MacTTSAudioStream.java
  bundles/org.openhab.voice.mactts/src/main/java/org/openhab/voice/mactts/internal/MacTTSService.java
  bundles/org.openhab.voice.mactts/src/test/java/org/openhab/voice/mactts/internal/TTSServiceMacOSTest.java
Labels: enhancement

#15059 [ipcamera] Fix discovery crashes when networks have access rights issues in docker
  bundles/org.openhab.binding.ipcamera/README.md
  bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/IpCameraDiscoveryService.java
  bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/onvif/OnvifDiscovery.java
Labels: bug

#15116 [sonos] Support for more audio streams through the HTTP audio servlet
  bundles/org.openhab.binding.sonos/src/main/java/org/openhab/binding/sonos/internal/SonosAudioSink.java
Labels: enhancement

#15122 [upnpcontrol] Support for more audio streams through the HTTP audio s…
  bundles/org.openhab.binding.upnpcontrol/src/main/java/org/openhab/binding/upnpcontrol/internal/audiosink/UpnpAudioSink.java
Labels: enhancement

#15138 [intesis] Add configurable polling interval
  bundles/org.openhab.binding.intesis/README.md
  bundles/org.openhab.binding.intesis/src/main/java/org/openhab/binding/intesis/internal/IntesisBindingConstants.java
  bundles/org.openhab.binding.intesis/src/main/java/org/openhab/binding/intesis/internal/api/IntesisHomeHttpApi.java
  bundles/org.openhab.binding.intesis/src/main/java/org/openhab/binding/intesis/internal/config/IntesisBoxConfiguration.java
  bundles/org.openhab.binding.intesis/src/main/java/org/openhab/binding/intesis/internal/config/IntesisHomeConfiguration.java
  bundles/org.openhab.binding.intesis/src/main/java/org/openhab/binding/intesis/internal/handler/IntesisBoxHandler.java
  bundles/org.openhab.binding.intesis/src/main/java/org/openhab/binding/intesis/internal/handler/IntesisHomeHandler.java
  bundles/org.openhab.binding.intesis/src/main/resources/OH-INF/thing/thing-types.xml
Labels: enhancement

#15156 [jdbc] stabilize timescale db type replacement
  bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/db/JdbcTimescaledbDAO.java
Labels: bug

#15167 [comfoair] extend UoM support, add semantic tags & update state descriptions
  bundles/org.openhab.binding.comfoair/README.md
  bundles/org.openhab.binding.comfoair/src/main/java/org/openhab/binding/comfoair/internal/ComfoAirCommandType.java
  bundles/org.openhab.binding.comfoair/src/main/java/org/openhab/binding/comfoair/internal/ComfoAirSerialConnector.java
  bundles/org.openhab.binding.comfoair/src/main/java/org/openhab/binding/comfoair/internal/datatypes/DataTypeRPM.java
  bundles/org.openhab.binding.comfoair/src/main/java/org/openhab/binding/comfoair/internal/datatypes/DataTypeTemperature.java
  bundles/org.openhab.binding.comfoair/src/main/java/org/openhab/binding/comfoair/internal/datatypes/DataTypeTime.java
  bundles/org.openhab.binding.comfoair/src/main/java/org/openhab/binding/comfoair/internal/datatypes/DataTypeVolt.java
  bundles/org.openhab.binding.comfoair/src/main/resources/OH-INF/i18n/comfoair.properties
  bundles/org.openhab.binding.comfoair/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.comfoair/src/main/resources/OH-INF/update/instructions.xml
Labels: enhancement

#15172 [avmfritz] Fix wrong system channel types
  bundles/org.openhab.binding.avmfritz/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.avmfritz/src/main/resources/OH-INF/update/instructions.xml
Labels: bug

#15176 [energidataservice] Remove obsoleted texts and update description
  bundles/org.openhab.binding.energidataservice/src/main/resources/OH-INF/i18n/energidataservice.properties
  bundles/org.openhab.binding.energidataservice/src/main/resources/OH-INF/thing/channel-types.xml
Labels: bug, regression

#15177 [hydrawise] Fixes occasional connection issues
  bundles/org.openhab.binding.hydrawise/src/main/java/org/openhab/binding/hydrawise/internal/api/graphql/HydrawiseGraphQLClient.java
Labels: bug

#15161 [kaleidescape] Fix image channel MIME type
  bundles/org.openhab.binding.kaleidescape/src/main/java/org/openhab/binding/kaleidescape/internal/handler/KaleidescapeMessageHandler.java
Labels: bug

#15162 [nuvo] Fix image channel MIME type
  bundles/org.openhab.binding.nuvo/src/main/java/org/openhab/binding/nuvo/internal/handler/NuvoHandler.java
Labels: bug

#15188 [comfoair] Update README to latest changes
  bundles/org.openhab.binding.comfoair/README.md
Labels: documentation, regression

#15186 [modbus.helioseasycontrols] Updated README.md (UoM, fixed links)
  bundles/org.openhab.binding.modbus.helioseasycontrols/README.md
Labels: documentation

#15180 [chromecast] Support for more audio streams through the audio servlet
  bundles/org.openhab.binding.chromecast/src/main/java/org/openhab/binding/chromecast/internal/ChromecastAudioSink.java
  bundles/org.openhab.binding.chromecast/src/main/java/org/openhab/binding/chromecast/internal/action/ChromecastActions.java
  bundles/org.openhab.binding.chromecast/src/main/java/org/openhab/binding/chromecast/internal/factory/ChromecastHandlerFactory.java
  bundles/org.openhab.binding.chromecast/src/main/java/org/openhab/binding/chromecast/internal/handler/ChromecastHandler.java
Labels: enhancement

#14525 [volumio] Initial contribution
  CODEOWNERS
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.volumio/NOTICE
  bundles/org.openhab.binding.volumio/README.md
  bundles/org.openhab.binding.volumio/pom.xml
  bundles/org.openhab.binding.volumio/src/main/feature/feature.xml
  bundles/org.openhab.binding.volumio/src/main/java/org/openhab/binding/volumio/internal/VolumioBindingConstants.java
  bundles/org.openhab.binding.volumio/src/main/java/org/openhab/binding/volumio/internal/VolumioConfiguration.java
  bundles/org.openhab.binding.volumio/src/main/java/org/openhab/binding/volumio/internal/VolumioHandler.java
  bundles/org.openhab.binding.volumio/src/main/java/org/openhab/binding/volumio/internal/VolumioHandlerFactory.java
  bundles/org.openhab.binding.volumio/src/main/java/org/openhab/binding/volumio/internal/VolumioService.java
  bundles/org.openhab.binding.volumio/src/main/java/org/openhab/binding/volumio/internal/discovery/VolumioDiscoveryParticipant.java
  bundles/org.openhab.binding.volumio/src/main/java/org/openhab/binding/volumio/internal/mapping/VolumioCommands.java
  bundles/org.openhab.binding.volumio/src/main/java/org/openhab/binding/volumio/internal/mapping/VolumioData.java
  bundles/org.openhab.binding.volumio/src/main/java/org/openhab/binding/volumio/internal/mapping/VolumioEvents.java
  bundles/org.openhab.binding.volumio/src/main/java/org/openhab/binding/volumio/internal/mapping/VolumioServiceTypes.java
  bundles/org.openhab.binding.volumio/src/main/resources/OH-INF/addon/addon.xml
  bundles/org.openhab.binding.volumio/src/main/resources/OH-INF/i18n/volumio.properties
  bundles/org.openhab.binding.volumio/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/pom.xml
Labels: new binding

#15193 [jsscripting] Implement NodeJS-like parameter handling for timer polyfills
  bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/threading/ThreadsafeTimers.java
  bundles/org.openhab.automation.jsscripting/src/main/resources/node_modules/@jsscripting-globals.js
Labels: enhancement

#15199 [amplipi] Support for more audio streams through the HTTP audio servlet
  bundles/org.openhab.binding.amplipi/src/main/java/org/openhab/binding/amplipi/internal/audio/PAAudioSink.java
Labels: enhancement

#15192 [kodi] Support for more audio streams through the HTTP audio servlet
  bundles/org.openhab.binding.kodi/src/main/java/org/openhab/binding/kodi/internal/KodiAudioSink.java
  bundles/org.openhab.binding.kodi/src/main/java/org/openhab/binding/kodi/internal/handler/KodiHandler.java
Labels: enhancement

#15187 [electroluxair] Update to changed API
  bundles/org.openhab.binding.electroluxair/README.md
  bundles/org.openhab.binding.electroluxair/src/main/java/org/openhab/binding/electroluxair/internal/ElectroluxAirBindingConstants.java
  bundles/org.openhab.binding.electroluxair/src/main/java/org/openhab/binding/electroluxair/internal/api/ElectroluxDeltaAPI.java
  bundles/org.openhab.binding.electroluxair/src/main/java/org/openhab/binding/electroluxair/internal/dto/ElectroluxPureA9DTO.java
  bundles/org.openhab.binding.electroluxair/src/main/java/org/openhab/binding/electroluxair/internal/handler/ElectroluxAirBridgeHandler.java
  bundles/org.openhab.binding.electroluxair/src/main/java/org/openhab/binding/electroluxair/internal/handler/ElectroluxAirHandler.java
  bundles/org.openhab.binding.electroluxair/src/main/resources/OH-INF/i18n/electroluxair.properties
  bundles/org.openhab.binding.electroluxair/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.electroluxair/src/main/resources/OH-INF/update/instructions.xml
Labels: enhancement

#15051 [shelly] Add support for Shelly Wall Dimmer US and Wall Display
  bundles/org.openhab.binding.shelly/README.md
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/ShellyBindingConstants.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api/ShellyDeviceProfile.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api1/Shelly1ApiJsonDTO.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api1/Shelly1CoIoTVersion1.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api1/Shelly1HttpApi.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api2/Shelly2ApiClient.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api2/Shelly2ApiJsonDTO.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api2/Shelly2ApiRpc.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api2/Shelly2RpctInterface.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/config/ShellyThingConfiguration.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/discovery/ShellyThingCreator.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/handler/ShellyComponents.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/handler/ShellyDeviceListener.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/handler/ShellyRelayHandler.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/handler/ShellyThingInterface.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/provider/ShellyChannelDefinitions.java
  bundles/org.openhab.binding.shelly/src/main/resources/OH-INF/config/config2.xml
  bundles/org.openhab.binding.shelly/src/main/resources/OH-INF/i18n/shelly.properties
  bundles/org.openhab.binding.shelly/src/main/resources/OH-INF/thing/shellyGen1_relay.xml
  bundles/org.openhab.binding.shelly/src/main/resources/OH-INF/thing/shellyGen2_relay.xml
  bundles/org.openhab.binding.shelly/src/main/resources/OH-INF/thing/shellyGen2_sensor.xml
  bundles/org.openhab.binding.shelly/src/main/resources/scripts/oh-blu-scanner.js
Labels: enhancement

#14565 [picotts] Add LRU cache
  bundles/org.openhab.voice.picotts/README.md
  bundles/org.openhab.voice.picotts/src/main/java/org/openhab/voice/picotts/internal/PicoTTSAudioStream.java
  bundles/org.openhab.voice.picotts/src/main/java/org/openhab/voice/picotts/internal/PicoTTSService.java
Labels: enhancement

#15202 [energidataservice] Fix documentation of history/cache
  bundles/org.openhab.binding.energidataservice/README.md
Labels: documentation

#15208 [googletts] Replace custom TTS cache with common TTS cache
  bundles/org.openhab.voice.googletts/README.md
  bundles/org.openhab.voice.googletts/src/main/java/org/openhab/voice/googletts/internal/GoogleCloudAPI.java
  bundles/org.openhab.voice.googletts/src/main/java/org/openhab/voice/googletts/internal/GoogleTTSConfig.java
  bundles/org.openhab.voice.googletts/src/main/java/org/openhab/voice/googletts/internal/GoogleTTSService.java
  bundles/org.openhab.voice.googletts/src/main/resources/OH-INF/config/config.xml
  bundles/org.openhab.voice.googletts/src/main/resources/OH-INF/i18n/googletts.properties
Labels: enhancement

#15006 [astro] Update README.md
  bundles/org.openhab.binding.astro/README.md
Labels: documentation

#15212 [Netatmo] Binding doesn't work if no persons are defined
  bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/api/dto/HomeData.java
Labels: bug

#15197 [netatmo] Add siren_tampered notification
  bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/api/data/EventType.java
Labels: enhancement

#15196 [heos] Support for more audio streams through the HTTP audio servlet
  bundles/org.openhab.binding.heos/src/main/java/org/openhab/binding/heos/internal/api/HeosAudioSink.java
Labels: enhancement

#15222 [Freeboxos] Add background discovery service managing capability
  bundles/org.openhab.binding.freeboxos/README.md
  bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/config/FreeboxOsConfiguration.java
  bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/discovery/FreeboxOsDiscoveryService.java
  bundles/org.openhab.binding.freeboxos/src/main/resources/OH-INF/config/bridge-config.xml
Labels: enhancement, regression

#14561 [voicerss] Add LRU cache
  bundles/org.openhab.voice.voicerss/README.md
  bundles/org.openhab.voice.voicerss/src/main/java/org/openhab/voice/voicerss/internal/VoiceRSSRawAudioStream.java
  bundles/org.openhab.voice.voicerss/src/main/java/org/openhab/voice/voicerss/internal/VoiceRSSTTSService.java
  bundles/org.openhab.voice.voicerss/src/main/java/org/openhab/voice/voicerss/internal/cloudapi/CachedVoiceRSSCloudImpl.java
  bundles/org.openhab.voice.voicerss/src/main/java/org/openhab/voice/voicerss/internal/cloudapi/VoiceRSSCloudAPI.java
  bundles/org.openhab.voice.voicerss/src/main/java/org/openhab/voice/voicerss/internal/cloudapi/VoiceRSSCloudImpl.java
  bundles/org.openhab.voice.voicerss/src/test/java/org/openhab/voice/voicerss/internal/VoiceRSSTTSServiceTest.java
Labels: enhancement

#15201 [allplay] Support for more audio streams through the HTTP audio servlet
  bundles/org.openhab.binding.allplay/src/main/java/org/openhab/binding/allplay/internal/AllPlayAudioSink.java
Labels: enhancement

#15121 [freebox] Support for more audio streams through the HTTP audio servlet
  bundles/org.openhab.binding.freebox/src/main/java/org/openhab/binding/freebox/internal/FreeboxAirPlayAudioSink.java
Labels: enhancement

#15117 [onkyo] Support for more audio streams through the HTTP audio servlet
  bundles/org.openhab.binding.onkyo/src/main/java/org/openhab/binding/onkyo/internal/OnkyoHandlerFactory.java
  bundles/org.openhab.binding.onkyo/src/main/java/org/openhab/binding/onkyo/internal/handler/OnkyoAudioSink.java
  bundles/org.openhab.binding.onkyo/src/main/java/org/openhab/binding/onkyo/internal/handler/OnkyoHandler.java
  bundles/org.openhab.binding.onkyo/src/main/java/org/openhab/binding/onkyo/internal/handler/OnkyoUpnpHandler.java
Labels: enhancement

#14564 [mimictts] Add LRU cache
  bundles/org.openhab.voice.mimictts/README.md
  bundles/org.openhab.voice.mimictts/src/main/java/org/openhab/voice/mimic/internal/AutoDeleteFileAudioStream.java
  bundles/org.openhab.voice.mimictts/src/main/java/org/openhab/voice/mimic/internal/InputStreamAudioStream.java
  bundles/org.openhab.voice.mimictts/src/main/java/org/openhab/voice/mimic/internal/MimicConfiguration.java
  bundles/org.openhab.voice.mimictts/src/main/java/org/openhab/voice/mimic/internal/MimicTTSService.java
  bundles/org.openhab.voice.mimictts/src/main/resources/OH-INF/config/config.xml
  bundles/org.openhab.voice.mimictts/src/main/resources/OH-INF/i18n/mimictts.properties
Labels: enhancement

#15165 [androidtv] Adds additional checks for parser
  bundles/org.openhab.binding.androidtv/src/main/java/org/openhab/binding/androidtv/internal/protocol/shieldtv/ShieldTVMessageParser.java
Labels: bug, regression

#14797 [MyNice] Addition of Courtesy Light Channel
  bundles/org.openhab.binding.mynice/README.md
  bundles/org.openhab.binding.mynice/src/main/java/org/openhab/binding/mynice/internal/MyNiceBindingConstants.java
  bundles/org.openhab.binding.mynice/src/main/java/org/openhab/binding/mynice/internal/MyNiceHandlerFactory.java
  bundles/org.openhab.binding.mynice/src/main/java/org/openhab/binding/mynice/internal/config/CourtesyConfiguration.java
  bundles/org.openhab.binding.mynice/src/main/java/org/openhab/binding/mynice/internal/discovery/MyNiceDiscoveryService.java
  bundles/org.openhab.binding.mynice/src/main/java/org/openhab/binding/mynice/internal/handler/GateHandler.java
  bundles/org.openhab.binding.mynice/src/main/java/org/openhab/binding/mynice/internal/handler/It4WifiConnector.java
  bundles/org.openhab.binding.mynice/src/main/java/org/openhab/binding/mynice/internal/handler/It4WifiHandler.java
  bundles/org.openhab.binding.mynice/src/main/java/org/openhab/binding/mynice/internal/xml/dto/Properties.java
  bundles/org.openhab.binding.mynice/src/main/java/org/openhab/binding/mynice/internal/xml/dto/T4Command.java
  bundles/org.openhab.binding.mynice/src/main/resources/OH-INF/i18n/mynice.properties
  bundles/org.openhab.binding.mynice/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.mynice/src/main/resources/OH-INF/update/instructions.xml
Labels: bug, enhancement

#15168 [Telegram] Log when cameras do not support BASIC auth support.
  bundles/org.openhab.binding.telegram/src/main/java/org/openhab/binding/telegram/internal/action/TelegramActions.java
Labels: bug

#15191 [Openuv] Providing an iconserver
  bundles/org.openhab.binding.openuv/README.md
  bundles/org.openhab.binding.openuv/src/main/java/org/openhab/binding/openuv/internal/AlertLevel.java
  bundles/org.openhab.binding.openuv/src/main/java/org/openhab/binding/openuv/internal/OpenUVException.java
  bundles/org.openhab.binding.openuv/src/main/java/org/openhab/binding/openuv/internal/OpenUVIconProvider.java
  bundles/org.openhab.binding.openuv/src/main/java/org/openhab/binding/openuv/internal/discovery/OpenUVDiscoveryService.java
  bundles/org.openhab.binding.openuv/src/main/java/org/openhab/binding/openuv/internal/handler/OpenUVBridgeHandler.java
  bundles/org.openhab.binding.openuv/src/main/java/org/openhab/binding/openuv/internal/handler/OpenUVReportHandler.java
  bundles/org.openhab.binding.openuv/src/main/java/org/openhab/binding/openuv/internal/json/OpenUVResult.java
  bundles/org.openhab.binding.openuv/src/main/resources/OH-INF/i18n/openuv.properties
  bundles/org.openhab.binding.openuv/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.openuv/src/main/resources/icon/ozone.svg
  bundles/org.openhab.binding.openuv/src/main/resources/icon/uv-alarm.svg
  bundles/org.openhab.binding.openuv/src/main/resources/icon/uv-index-1.svg
  bundles/org.openhab.binding.openuv/src/main/resources/icon/uv-index-10.svg
  bundles/org.openhab.binding.openuv/src/main/resources/icon/uv-index-11.svg
  bundles/org.openhab.binding.openuv/src/main/resources/icon/uv-index-2.svg
  bundles/org.openhab.binding.openuv/src/main/resources/icon/uv-index-3.svg
  bundles/org.openhab.binding.openuv/src/main/resources/icon/uv-index-4.svg
  bundles/org.openhab.binding.openuv/src/main/resources/icon/uv-index-5.svg
  bundles/org.openhab.binding.openuv/src/main/resources/icon/uv-index-6.svg
  bundles/org.openhab.binding.openuv/src/main/resources/icon/uv-index-7.svg
  bundles/org.openhab.binding.openuv/src/main/resources/icon/uv-index-8.svg
  bundles/org.openhab.binding.openuv/src/main/resources/icon/uv-index-9.svg
  bundles/org.openhab.binding.openuv/src/main/resources/icon/uv-index.svg
Labels: enhancement

#14485 [netatmo] Add Siren capability to Presence Outdoor Camera
  bundles/org.openhab.binding.netatmo/README.md
  bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/NetatmoBindingConstants.java
  bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/api/ApiError.java
  bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/api/NetatmoException.java
  bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/api/SecurityApi.java
  bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/api/data/ModuleType.java
  bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/api/data/NetatmoConstants.java
  bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/api/dto/HomeStatusModule.java
  bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/ApiBridgeHandler.java
  bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/CommonInterface.java
  bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/capability/Capability.java
  bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/capability/PresenceCapability.java
  bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/capability/SecurityCapability.java
  bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/channelhelper/PresenceChannelHelper.java
  bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/channelhelper/SirenChannelHelper.java
  bundles/org.openhab.binding.netatmo/src/main/resources/OH-INF/i18n/netatmo.properties
  bundles/org.openhab.binding.netatmo/src/main/resources/OH-INF/thing/channels.xml
  bundles/org.openhab.binding.netatmo/src/main/resources/OH-INF/thing/security.xml
  bundles/org.openhab.binding.netatmo/src/main/resources/OH-INF/update/instructions.xml
Labels: enhancement, additional testing preferred

#15223 [rrd4j] Improve event handling
  bundles/org.openhab.persistence.rrd4j/src/main/java/org/openhab/persistence/rrd4j/internal/RRD4jPersistenceService.java
Labels: bug

#15205 [shelly] Add support for Shelly Plus Mini series, Pro EM-50 and various bug fixes
  bundles/org.openhab.binding.shelly/README.md
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/ShellyBindingConstants.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/ShellyHandlerFactory.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api/ShellyDeviceProfile.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api2/Shelly2ApiClient.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api2/Shelly2ApiJsonDTO.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api2/Shelly2ApiRpc.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/discovery/ShellyThingCreator.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/handler/ShellyComponents.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/handler/ShellyRelayHandler.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/provider/ShellyChannelDefinitions.java
  bundles/org.openhab.binding.shelly/src/main/resources/OH-INF/addon/addon.xml
  bundles/org.openhab.binding.shelly/src/main/resources/OH-INF/i18n/shelly.properties
  bundles/org.openhab.binding.shelly/src/main/resources/OH-INF/thing/shellyGen1_relay.xml
  bundles/org.openhab.binding.shelly/src/main/resources/OH-INF/thing/shellyGen2_relay.xml
Labels: bug, enhancement

#15146 [androidtv] Adds CLI Interface
  bundles/org.openhab.binding.androidtv/README.md
  bundles/org.openhab.binding.androidtv/src/main/java/org/openhab/binding/androidtv/internal/console/AndroidTVCommandExtension.java
Labels: enhancement

#15184 [androidtv] Adds additional i18n support to ConnectionManagers
  bundles/org.openhab.binding.androidtv/src/main/java/org/openhab/binding/androidtv/internal/AndroidTVHandler.java
  bundles/org.openhab.binding.androidtv/src/main/java/org/openhab/binding/androidtv/internal/AndroidTVHandlerFactory.java
  bundles/org.openhab.binding.androidtv/src/main/java/org/openhab/binding/androidtv/internal/AndroidTVTranslationProvider.java
  bundles/org.openhab.binding.androidtv/src/main/java/org/openhab/binding/androidtv/internal/protocol/googletv/GoogleTVConnectionManager.java
  bundles/org.openhab.binding.androidtv/src/main/java/org/openhab/binding/androidtv/internal/protocol/shieldtv/ShieldTVConnectionManager.java
  bundles/org.openhab.binding.androidtv/src/main/resources/OH-INF/i18n/androidtv.properties
Labels: enhancement, regression

#15174 [androidtv] Moves Shim PKI to AndroidTVPKI and adds Trusted CA Certificate functions
  bundles/org.openhab.binding.androidtv/src/main/java/org/openhab/binding/androidtv/internal/protocol/googletv/GoogleTVConnectionManager.java
  bundles/org.openhab.binding.androidtv/src/main/java/org/openhab/binding/androidtv/internal/utils/AndroidTVPKI.java
Labels: enhancement, regression

#13815 [asuswrt] Initial contribution - new binding to get informations from Asus-Routers
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.asuswrt/NOTICE
  bundles/org.openhab.binding.asuswrt/README.md
  bundles/org.openhab.binding.asuswrt/pom.xml
  bundles/org.openhab.binding.asuswrt/src/main/feature/feature.xml
  bundles/org.openhab.binding.asuswrt/src/main/java/org/openhab/binding/asuswrt/internal/AsuswrtDiscoveryService.java
  bundles/org.openhab.binding.asuswrt/src/main/java/org/openhab/binding/asuswrt/internal/AsuswrtHandlerFactory.java
  bundles/org.openhab.binding.asuswrt/src/main/java/org/openhab/binding/asuswrt/internal/api/AsuswrtConnector.java
  bundles/org.openhab.binding.asuswrt/src/main/java/org/openhab/binding/asuswrt/internal/api/AsuswrtCookie.java
  bundles/org.openhab.binding.asuswrt/src/main/java/org/openhab/binding/asuswrt/internal/api/AsuswrtHttpClient.java
  bundles/org.openhab.binding.asuswrt/src/main/java/org/openhab/binding/asuswrt/internal/constants/AsuswrtBindingConstants.java
  bundles/org.openhab.binding.asuswrt/src/main/java/org/openhab/binding/asuswrt/internal/constants/AsuswrtBindingSettings.java
  bundles/org.openhab.binding.asuswrt/src/main/java/org/openhab/binding/asuswrt/internal/constants/AsuswrtErrorConstants.java
  bundles/org.openhab.binding.asuswrt/src/main/java/org/openhab/binding/asuswrt/internal/helpers/AsuswrtErrorHandler.java
  bundles/org.openhab.binding.asuswrt/src/main/java/org/openhab/binding/asuswrt/internal/helpers/AsuswrtUtils.java
  bundles/org.openhab.binding.asuswrt/src/main/java/org/openhab/binding/asuswrt/internal/structures/AsuswrtClientInfo.java
  bundles/org.openhab.binding.asuswrt/src/main/java/org/openhab/binding/asuswrt/internal/structures/AsuswrtClientList.java
  bundles/org.openhab.binding.asuswrt/src/main/java/org/openhab/binding/asuswrt/internal/structures/AsuswrtConfiguration.java
  bundles/org.openhab.binding.asuswrt/src/main/java/org/openhab/binding/asuswrt/internal/structures/AsuswrtCredentials.java
  bundles/org.openhab.binding.asuswrt/src/main/java/org/openhab/binding/asuswrt/internal/structures/AsuswrtInterfaceList.java
  bundles/org.openhab.binding.asuswrt/src/main/java/org/openhab/binding/asuswrt/internal/structures/AsuswrtIpInfo.java
  bundles/org.openhab.binding.asuswrt/src/main/java/org/openhab/binding/asuswrt/internal/structures/AsuswrtRouterInfo.java
  bundles/org.openhab.binding.asuswrt/src/main/java/org/openhab/binding/asuswrt/internal/structures/AsuswrtTraffic.java
  bundles/org.openhab.binding.asuswrt/src/main/java/org/openhab/binding/asuswrt/internal/structures/AsuswrtUsage.java
  bundles/org.openhab.binding.asuswrt/src/main/java/org/openhab/binding/asuswrt/internal/things/AsuswrtClient.java
  bundles/org.openhab.binding.asuswrt/src/main/java/org/openhab/binding/asuswrt/internal/things/AsuswrtInterface.java
  bundles/org.openhab.binding.asuswrt/src/main/java/org/openhab/binding/asuswrt/internal/things/AsuswrtRouter.java
  bundles/org.openhab.binding.asuswrt/src/main/resources/OH-INF/addon/addon.xml
  bundles/org.openhab.binding.asuswrt/src/main/resources/OH-INF/i18n/asuswrt.properties
  bundles/org.openhab.binding.asuswrt/src/main/resources/OH-INF/thing/channels.xml
  bundles/org.openhab.binding.asuswrt/src/main/resources/OH-INF/thing/client.xml
  bundles/org.openhab.binding.asuswrt/src/main/resources/OH-INF/thing/interface.xml
  bundles/org.openhab.binding.asuswrt/src/main/resources/OH-INF/thing/router.xml
  bundles/pom.xml
Labels: new binding

#15228 [pollyTTS] Replace custom TTS cache with common TTS cache
  bundles/org.openhab.voice.pollytts/README.md
  bundles/org.openhab.voice.pollytts/src/main/java/org/openhab/voice/pollytts/internal/PollyTTSAudioStream.java
  bundles/org.openhab.voice.pollytts/src/main/java/org/openhab/voice/pollytts/internal/PollyTTSService.java
  bundles/org.openhab.voice.pollytts/src/main/java/org/openhab/voice/pollytts/internal/cloudapi/CachedPollyTTSCloudImpl.java
  bundles/org.openhab.voice.pollytts/src/main/java/org/openhab/voice/pollytts/internal/cloudapi/PollyTTSCloudImpl.java
  bundles/org.openhab.voice.pollytts/src/main/resources/OH-INF/config/config.xml
  bundles/org.openhab.voice.pollytts/src/main/resources/OH-INF/i18n/pollytts.properties
Labels: enhancement

#15115 [openwebnet] add date time synchronization feature for bus_gateway Things
  bundles/org.openhab.binding.openwebnet/README.md
  bundles/org.openhab.binding.openwebnet/pom.xml
  bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/handler/OpenWebNetBridgeHandler.java
  bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/handler/config/OpenWebNetBusBridgeConfig.java
  bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/i18n/openwebnet.properties
  bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/thing/BusGateway.xml
Labels: enhancement

#15244 [energidataservice] Update tariff filter for Nord Energi Net
  bundles/org.openhab.binding.energidataservice/src/main/java/org/openhab/binding/energidataservice/internal/api/DatahubTariffFilterFactory.java
Labels: bug, regression

#15073 [ipcamera] FIX: TAPO branded cameras require xAddr port to be different
  bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/Ffmpeg.java
  bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/InstarHandler.java
  bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/handler/IpCameraHandler.java
  bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/onvif/OnvifConnection.java
Labels: bug

#15246 [energidataservice] Extend and simplify date query offset support
  bundles/org.openhab.binding.energidataservice/README.md
  bundles/org.openhab.binding.energidataservice/src/main/java/org/openhab/binding/energidataservice/internal/api/DatahubTariffFilterFactory.java
  bundles/org.openhab.binding.energidataservice/src/main/java/org/openhab/binding/energidataservice/internal/api/DateQueryParameter.java
  bundles/org.openhab.binding.energidataservice/src/main/java/org/openhab/binding/energidataservice/internal/config/DatahubPriceConfiguration.java
  bundles/org.openhab.binding.energidataservice/src/main/java/org/openhab/binding/energidataservice/internal/handler/EnergiDataServiceHandler.java
  bundles/org.openhab.binding.energidataservice/src/main/resources/OH-INF/config/config.xml
  bundles/org.openhab.binding.energidataservice/src/main/resources/OH-INF/i18n/energidataservice.properties
Labels: enhancement, regression

#15247 [shelly][hotfix] Fix relay id for devices with more than 1 power meter, fix 4Pro init, various other fixes
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/ShellyBindingConstants.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api2/Shelly2ApiClient.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api2/Shelly2ApiRpc.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/handler/ShellyComponents.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/handler/ShellyRelayHandler.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/provider/ShellyChannelDefinitions.java
  bundles/org.openhab.binding.shelly/src/main/resources/OH-INF/i18n/shelly.properties
  bundles/org.openhab.binding.shelly/src/main/resources/OH-INF/thing/shellyGen1_sensor.xml
Labels: bug, regression

#15248 [openwebnet] Backward support for CU configurations with where="0"
  bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/handler/OpenWebNetThermoregulationHandler.java
Labels: bug, regression

#15252 [androidtv] Fixes log flooding from protocol error
  bundles/org.openhab.binding.androidtv/src/main/java/org/openhab/binding/androidtv/internal/protocol/googletv/GoogleTVConnectionManager.java
  bundles/org.openhab.binding.androidtv/src/main/java/org/openhab/binding/androidtv/internal/protocol/googletv/GoogleTVMessageParser.java
Labels: bug

#15250 [openwebnet] Binding documentation update for OH4 release
  bundles/org.openhab.binding.openwebnet/README.md
  bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/i18n/openwebnet.properties
  bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/thing/BusAlarmZone.xml
  bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/thing/BusAutomation.xml
  bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/thing/BusAux.xml
  bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/thing/BusBasicScenarioControl.xml
  bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/thing/BusCENPlusScenarioControl.xml
  bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/thing/BusCENScenarioControl.xml
  bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/thing/BusDimmer.xml
  bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/thing/BusDryContactIR.xml
  bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/thing/BusEnergyMeter.xml
  bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/thing/BusOnOffSwitch.xml
  bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/thing/BusThermoCentralUnit.xml
  bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/thing/BusThermoSensor.xml
  bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/thing/BusThermoZone.xml
  bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/thing/ZBAutomation.xml
  bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/thing/ZBDimmer.xml
  bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/thing/ZBOnOffSwitch.xml
  bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/thing/ZBOnOffSwitch2Units.xml
  bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/thing/channels.xml
Labels: documentation

#15018 [mqtt.ruuvigateway] Re-enable itests after core change
  itests/org.openhab.binding.mqtt.ruuvigateway.tests/itest.bndrun
  itests/org.openhab.binding.mqtt.ruuvigateway.tests/src/main/java/org/openhab/binding/mqtt/ruuvigateway/RuuviGatewayTest.java
  itests/pom.xml
Labels: test

#15261 [avmfritz] Fix update instructions
  bundles/org.openhab.binding.avmfritz/src/main/resources/OH-INF/thing/bridge-types.xml
  bundles/org.openhab.binding.avmfritz/src/main/resources/OH-INF/thing/thing-types.xml
Labels: bug, awaiting other PR, regression

#15272 [velbus] Fix multiple channel status in one packet
  bundles/org.openhab.binding.velbus/src/main/java/org/openhab/binding/velbus/internal/handler/VelbusSensorHandler.java
Labels: bug

#15269 [openwebnet] Fix update of Thermo Central Unit atLeastOneProbeX channels and refactoring
  bundles/org.openhab.binding.openwebnet/pom.xml
  bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/handler/OpenWebNetThermoregulationHandler.java
Labels: bug

#15257 [openwebnet] Fix README for Sitemap AUX configuration to the correct mapping
  bundles/org.openhab.binding.openwebnet/README.md
Labels: documentation

#15277 [rrd4j] Fix database start time
  bundles/org.openhab.persistence.rrd4j/src/main/java/org/openhab/persistence/rrd4j/internal/RRD4jPersistenceService.java
Labels: bug

#15258 [androidtv] Fix log flood when physical device is not online
  bundles/org.openhab.binding.androidtv/src/main/java/org/openhab/binding/androidtv/internal/AndroidTVHandler.java
Labels: bug, regression

#15280 [miele] Update default translations
  bundles/org.openhab.binding.miele/src/main/resources/OH-INF/i18n/miele.properties
Labels: bug, regression

#15114 [mqtt] Dynamically change accepted item-type for Number channels
  bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/internal/handler/GenericMQTTThingHandler.java
  bundles/org.openhab.binding.mqtt.generic/src/test/java/org/openhab/binding/mqtt/generic/internal/handler/ThingChannelConstants.java
Labels: enhancement

#15287 [jrubyscripting] Update README
  bundles/org.openhab.automation.jrubyscripting/README.md
Labels: documentation

#15286 [transform.vat] Provide example in JavaScript
  bundles/org.openhab.transform.vat/README.md
Labels: documentation

#15283 [jsonpath] Fix exception when input string is empty
  bundles/org.openhab.transform.jsonpath/src/main/java/org/openhab/transform/jsonpath/internal/JSonPathTransformationService.java
Labels: bug

#15297 [knx] Refactor manufacturer map
  bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/KNXBindingConstants.java
  bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/client/DeviceInspector.java
  bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/handler/Manufacturer.java
  bundles/org.openhab.binding.knx/src/main/resources/manufacturer.properties
Labels: enhancement

#15292 [nuvo] Include NuvoNet source favorites in zone `favorite` channel
  bundles/org.openhab.binding.nuvo/README.md
  bundles/org.openhab.binding.nuvo/src/main/java/org/openhab/binding/nuvo/internal/NuvoBindingConstants.java
  bundles/org.openhab.binding.nuvo/src/main/java/org/openhab/binding/nuvo/internal/communication/NuvoEnum.java
  bundles/org.openhab.binding.nuvo/src/main/java/org/openhab/binding/nuvo/internal/handler/NuvoHandler.java
Labels: enhancement

#14557 [paradoxalarm] Implement zone bypass command and additional zone states
  bundles/org.openhab.binding.paradoxalarm/README.md
  bundles/org.openhab.binding.paradoxalarm/src/main/java/org/openhab/binding/paradoxalarm/internal/communication/EvoCommunicator.java
  bundles/org.openhab.binding.paradoxalarm/src/main/java/org/openhab/binding/paradoxalarm/internal/communication/MemoryMap.java
  bundles/org.openhab.binding.paradoxalarm/src/main/java/org/openhab/binding/paradoxalarm/internal/communication/Response.java
  bundles/org.openhab.binding.paradoxalarm/src/main/java/org/openhab/binding/paradoxalarm/internal/communication/ZoneCommandRequest.java
  bundles/org.openhab.binding.paradoxalarm/src/main/java/org/openhab/binding/paradoxalarm/internal/communication/crypto/EncryptionHandler.java
  bundles/org.openhab.binding.paradoxalarm/src/main/java/org/openhab/binding/paradoxalarm/internal/communication/messages/Command.java
  bundles/org.openhab.binding.paradoxalarm/src/main/java/org/openhab/binding/paradoxalarm/internal/communication/messages/PartitionCommand.java
  bundles/org.openhab.binding.paradoxalarm/src/main/java/org/openhab/binding/paradoxalarm/internal/communication/messages/partition/PartitionCommand.java
  bundles/org.openhab.binding.paradoxalarm/src/main/java/org/openhab/binding/paradoxalarm/internal/communication/messages/partition/PartitionCommandPayload.java
  bundles/org.openhab.binding.paradoxalarm/src/main/java/org/openhab/binding/paradoxalarm/internal/communication/messages/zone/ZoneCommand.java
  bundles/org.openhab.binding.paradoxalarm/src/main/java/org/openhab/binding/paradoxalarm/internal/communication/messages/zone/ZoneCommandPayload.java
  bundles/org.openhab.binding.paradoxalarm/src/main/java/org/openhab/binding/paradoxalarm/internal/discovery/ParadoxDiscoveryService.java
  bundles/org.openhab.binding.paradoxalarm/src/main/java/org/openhab/binding/paradoxalarm/internal/handlers/ParadoxAlarmBindingConstants.java
  bundles/org.openhab.binding.paradoxalarm/src/main/java/org/openhab/binding/paradoxalarm/internal/handlers/ParadoxPanelHandler.java
  bundles/org.openhab.binding.paradoxalarm/src/main/java/org/openhab/binding/paradoxalarm/internal/handlers/ParadoxPartitionHandler.java
  bundles/org.openhab.binding.paradoxalarm/src/main/java/org/openhab/binding/paradoxalarm/internal/handlers/ParadoxZoneHandler.java
  bundles/org.openhab.binding.paradoxalarm/src/main/java/org/openhab/binding/paradoxalarm/internal/model/Partition.java
  bundles/org.openhab.binding.paradoxalarm/src/main/java/org/openhab/binding/paradoxalarm/internal/model/Zone.java
  bundles/org.openhab.binding.paradoxalarm/src/main/java/org/openhab/binding/paradoxalarm/internal/model/ZoneState.java
  bundles/org.openhab.binding.paradoxalarm/src/main/java/org/openhab/binding/paradoxalarm/internal/model/ZoneStateFlags.java
  bundles/org.openhab.binding.paradoxalarm/src/main/java/org/openhab/binding/paradoxalarm/internal/parsers/EvoParser.java
  bundles/org.openhab.binding.paradoxalarm/src/main/java/org/openhab/binding/paradoxalarm/internal/util/ParadoxUtil.java
  bundles/org.openhab.binding.paradoxalarm/src/main/resources/OH-INF/i18n/paradoxalarm.properties
  bundles/org.openhab.binding.paradoxalarm/src/main/resources/OH-INF/thing/zone.xml
  bundles/org.openhab.binding.paradoxalarm/src/test/java/org/openhab/binding/paradoxalarm/internal/TestCreateCommandPayload.java
  bundles/org.openhab.binding.paradoxalarm/src/test/java/org/openhab/binding/paradoxalarm/internal/TestEncryptionHandler.java
  bundles/org.openhab.binding.paradoxalarm/src/test/java/org/openhab/binding/paradoxalarm/internal/TestGetBytes.java
  bundles/org.openhab.binding.paradoxalarm/src/test/java/org/openhab/binding/paradoxalarm/internal/TestParadoxUtil.java
Labels: enhancement, community approved

#15305 [googletts] Avoid UnsupportedOperationException during dispose
  bundles/org.openhab.voice.googletts/src/main/java/org/openhab/voice/googletts/internal/GoogleTTSService.java
Labels: bug

#15302 [enocean] Fix unusable bundle after a refactoring about null annotation
  bundles/org.openhab.binding.enocean/src/main/java/org/openhab/binding/enocean/internal/eep/A5_20/A5_20_04.java
  bundles/org.openhab.binding.enocean/src/main/java/org/openhab/binding/enocean/internal/eep/D2_03/D2_03_0A.java
  bundles/org.openhab.binding.enocean/src/main/java/org/openhab/binding/enocean/internal/eep/D2_06/D2_06_01.java
  bundles/org.openhab.binding.enocean/src/main/java/org/openhab/binding/enocean/internal/eep/D2_06/D2_06_50.java
  bundles/org.openhab.binding.enocean/src/main/java/org/openhab/binding/enocean/internal/eep/EEP.java
  bundles/org.openhab.binding.enocean/src/main/java/org/openhab/binding/enocean/internal/eep/F6_01/F6_01_01.java
  bundles/org.openhab.binding.enocean/src/main/java/org/openhab/binding/enocean/internal/eep/F6_02/F6_02_01.java
  bundles/org.openhab.binding.enocean/src/main/java/org/openhab/binding/enocean/internal/eep/F6_02/F6_02_02.java
  bundles/org.openhab.binding.enocean/src/main/java/org/openhab/binding/enocean/internal/handler/EnOceanBaseSensorHandler.java
  bundles/org.openhab.binding.enocean/src/main/java/org/openhab/binding/enocean/internal/handler/EnOceanBridgeHandler.java
  bundles/org.openhab.binding.enocean/src/main/java/org/openhab/binding/enocean/internal/messages/responses/BaseResponse.java
  bundles/org.openhab.binding.enocean/src/main/java/org/openhab/binding/enocean/internal/messages/responses/RDBaseIdResponse.java
  bundles/org.openhab.binding.enocean/src/main/java/org/openhab/binding/enocean/internal/messages/responses/RDLearnedClientsResponse.java
  bundles/org.openhab.binding.enocean/src/main/java/org/openhab/binding/enocean/internal/messages/responses/RDRepeaterResponse.java
  bundles/org.openhab.binding.enocean/src/main/java/org/openhab/binding/enocean/internal/messages/responses/RDVersionResponse.java
  bundles/org.openhab.binding.enocean/src/main/java/org/openhab/binding/enocean/internal/messages/responses/SMACKTeachInResponse.java
  bundles/org.openhab.binding.enocean/src/main/java/org/openhab/binding/enocean/internal/transceiver/EnOceanTransceiver.java
Labels: bug, critical

#15308 [jsscripting] Fix timerId not returned by JS timer methods
  bundles/org.openhab.automation.jsscripting/src/main/resources/node_modules/@jsscripting-globals.js
Labels: bug

#15306 [plex] Use https for local connections
  bundles/org.openhab.binding.plex/src/main/java/org/openhab/binding/plex/internal/handler/PlexApiConnector.java
  bundles/org.openhab.binding.plex/src/main/java/org/openhab/binding/plex/internal/handler/PlexServerHandler.java
Labels: enhancement

#15307 [freeboxos] Enhance freeplug data interpretation
  bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/api/rest/FreeplugManager.java
  bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/handler/FreeplugHandler.java
Labels: bug

#15169 [hue] Fix reconnection, parallel commands, trigger channels, and light level formula
  bundles/org.openhab.binding.hue/doc/readme_v2.md
  bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/connection/Clip2Bridge.java
  bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/dto/clip2/Button.java
  bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/dto/clip2/LightLevel.java
  bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/dto/clip2/Resource.java
  bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/Clip2BridgeHandler.java
  bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/Clip2ThingHandler.java
Labels: bug

#15284 [shelly] Fix Plus/Pro Auth support
  bundles/org.openhab.binding.shelly/README.md
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/ShellyBindingConstants.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api/ShellyApiResult.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api/ShellyHttpClient.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api2/Shelly2ApiClient.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api2/Shelly2ApiJsonDTO.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api2/Shelly2ApiRpc.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api2/Shelly2RpcSocket.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/handler/ShellyBaseHandler.java
  bundles/org.openhab.binding.shelly/src/main/resources/OH-INF/thing/shellyGen2_relay.xml
Labels: bug

#15319 [digitalstrom] Fix `StringIndexOutOfBoundsException`
  bundles/org.openhab.binding.digitalstrom/src/main/java/org/openhab/binding/digitalstrom/internal/lib/serverconnection/impl/HttpTransportImpl.java
Labels: bug, critical

#15320 [bluetooth] Fix `ArrayStoreException`
  bundles/org.openhab.binding.bluetooth/src/main/java/org/openhab/binding/bluetooth/BluetoothUtils.java
Labels: bug, critical, patch

#15334 [dscalarm] Fix icon reference in documentation example
  bundles/org.openhab.binding.dscalarm/README.md
Labels: documentation

#15336 [jsscripting] Upgrade openhab-js to fix cached library injection
  bundles/org.openhab.automation.jsscripting/pom.xml
Labels: bug

#15331 [androidtv] Removes unnecessary null checks
  bundles/org.openhab.binding.androidtv/src/main/java/org/openhab/binding/androidtv/internal/protocol/googletv/GoogleTVConnectionManager.java
  bundles/org.openhab.binding.androidtv/src/main/java/org/openhab/binding/androidtv/internal/protocol/shieldtv/ShieldTVConnectionManager.java
  bundles/org.openhab.binding.androidtv/src/main/resources/OH-INF/i18n/androidtv.properties
  bundles/org.openhab.binding.androidtv/src/main/resources/OH-INF/thing/thing-types.xml
Labels: regression

#15338 [sonos] Fixes DTS Typo
  bundles/org.openhab.binding.sonos/src/main/java/org/openhab/binding/sonos/internal/handler/ZonePlayerHandler.java
Labels: bug, regression

#15316 [hue] Reintroduce LK Wiser dimmer work-around for API v2
  bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/Clip2ThingHandler.java
Labels: bug

#15329 [enocean] Fix disposal of running tasks
  bundles/org.openhab.binding.enocean/src/main/java/org/openhab/binding/enocean/internal/handler/EnOceanBaseActuatorHandler.java
  bundles/org.openhab.binding.enocean/src/main/java/org/openhab/binding/enocean/internal/handler/EnOceanBaseSensorHandler.java
  bundles/org.openhab.binding.enocean/src/main/java/org/openhab/binding/enocean/internal/handler/EnOceanBridgeHandler.java
  bundles/org.openhab.binding.enocean/src/main/java/org/openhab/binding/enocean/internal/handler/EnOceanClassicDeviceHandler.java
  bundles/org.openhab.binding.enocean/src/main/java/org/openhab/binding/enocean/internal/transceiver/EnOceanTransceiver.java
Labels: bug, critical

#15294 [myStrom] Add energy consumption since last API call channel for MyStrom Plug
  bundles/org.openhab.binding.mystrom/README.md
  bundles/org.openhab.binding.mystrom/src/main/java/org/openhab/binding/mystrom/internal/MyStromBindingConstants.java
  bundles/org.openhab.binding.mystrom/src/main/java/org/openhab/binding/mystrom/internal/MyStromPlugHandler.java
  bundles/org.openhab.binding.mystrom/src/main/resources/OH-INF/i18n/mystrom.properties
  bundles/org.openhab.binding.mystrom/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.mystrom/src/main/resources/OH-INF/update/instructions.xml
Labels: enhancement

#15317 [androidtv] Adds gtvEnabled Option
  bundles/org.openhab.binding.androidtv/README.md
  bundles/org.openhab.binding.androidtv/src/main/java/org/openhab/binding/androidtv/internal/AndroidTVBindingConstants.java
  bundles/org.openhab.binding.androidtv/src/main/java/org/openhab/binding/androidtv/internal/AndroidTVHandler.java
  bundles/org.openhab.binding.androidtv/src/main/java/org/openhab/binding/androidtv/internal/protocol/googletv/GoogleTVConfiguration.java
  bundles/org.openhab.binding.androidtv/src/main/resources/OH-INF/i18n/androidtv.properties
  bundles/org.openhab.binding.androidtv/src/main/resources/OH-INF/thing/thing-types.xml
Labels: enhancement
