Repository openhab/openhab-addons, pull requests merged in 2023-12, with the labels that each got.

#15981 [solax] Update README.md
  bundles/org.openhab.binding.solax/README.md
Labels: documentation

#15907 [grundfosalpha] Initial contribution
  CODEOWNERS
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.bluetooth.bluez/src/main/java/org/openhab/binding/bluetooth/bluez/internal/BlueZBridgeHandler.java
  bundles/org.openhab.binding.bluetooth.grundfosalpha/NOTICE
  bundles/org.openhab.binding.bluetooth.grundfosalpha/README.md
  bundles/org.openhab.binding.bluetooth.grundfosalpha/pom.xml
  bundles/org.openhab.binding.bluetooth.grundfosalpha/src/main/feature/feature.xml
  bundles/org.openhab.binding.bluetooth.grundfosalpha/src/main/java/org/openhab/binding/bluetooth/grundfosalpha/internal/GrundfosAlphaBindingConstants.java
  bundles/org.openhab.binding.bluetooth.grundfosalpha/src/main/java/org/openhab/binding/bluetooth/grundfosalpha/internal/GrundfosAlphaDiscoveryParticipant.java
  bundles/org.openhab.binding.bluetooth.grundfosalpha/src/main/java/org/openhab/binding/bluetooth/grundfosalpha/internal/GrundfosAlphaHandler.java
  bundles/org.openhab.binding.bluetooth.grundfosalpha/src/main/java/org/openhab/binding/bluetooth/grundfosalpha/internal/GrundfosAlphaHandlerFactory.java
  bundles/org.openhab.binding.bluetooth.grundfosalpha/src/main/resources/OH-INF/i18n/bluetooth.properties
  bundles/org.openhab.binding.bluetooth.grundfosalpha/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.bluetooth.grundfosalpha/src/test/java/org/openhab/binding/bluetooth/grundfosalpha/internal/GrundfosAlphaHandlerTest.java
  bundles/pom.xml
Labels: new binding

#15905 [hue] Fix multiple state updates (API v2)
  bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/api/dto/clip2/Resource.java
  bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/api/dto/clip2/helper/Setters.java
  bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/Clip2BridgeHandler.java
  bundles/org.openhab.binding.hue/src/test/java/org/openhab/binding/hue/internal/clip2/SettersTest.java
Labels: bug

#15984 [hue] Use auto update policy 'veto' for light channels (API v2)
  bundles/org.openhab.binding.hue/src/main/resources/OH-INF/i18n/hue.properties
  bundles/org.openhab.binding.hue/src/main/resources/OH-INF/thing/Clip2Thing.xml
  bundles/org.openhab.binding.hue/src/main/resources/OH-INF/thing/channels.xml
Labels: enhancement

#15997 [squeezebox] Add UoM support for time channels
  bundles/org.openhab.binding.squeezebox/README.md
  bundles/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/handler/SqueezeBoxPlayerHandler.java
  bundles/org.openhab.binding.squeezebox/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.squeezebox/src/main/resources/OH-INF/update/instructions.xml
Labels: enhancement

#15730 [knx] Fix IOOB exception with missing DPT in number channels
  bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/dpt/DPTUnits.java
  bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/handler/DeviceThingHandler.java
  bundles/org.openhab.binding.knx/src/test/java/org/openhab/binding/knx/internal/dpt/DPTTest.java
Labels: bug, awaiting feedback

#15999 [hue] Fix edge cases for broken lights
  bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/api/dto/clip2/OnState.java
  bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/api/dto/clip2/Resource.java
  bundles/org.openhab.binding.hue/src/test/java/org/openhab/binding/hue/internal/clip2/OnStateDimmingEdgeCaseTest.java
Labels: bug

#16020 [hue] Improve handling of unknown resource ID (API v2)
  bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/Clip2ThingHandler.java
  bundles/org.openhab.binding.hue/src/main/resources/OH-INF/i18n/hue.properties
Labels: enhancement

#16029 [tesla] Fix location with firmware 2023.38.x
  bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/handler/TeslaAccountHandler.java
Labels: bug

#16024 [synop] Enhance error handling when no value is provided for windDirection
  bundles/org.openhab.binding.synopanalyzer/src/main/java/org/openhab/binding/synopanalyzer/internal/handler/SynopAnalyzerHandler.java
  bundles/org.openhab.binding.synopanalyzer/src/main/java/org/openhab/binding/synopanalyzer/internal/synop/Synop.java
  bundles/org.openhab.binding.synopanalyzer/src/main/java/org/openhab/binding/synopanalyzer/internal/synop/WindDirections.java
Labels: bug

#16030 [tesla] Hide refresh token in the UI as it is considered a secret
  bundles/org.openhab.binding.tesla/src/main/resources/OH-INF/thing/account.xml
Labels: enhancement

#16013 [Jellyfin] Fix how refresh is handled
  bundles/org.openhab.binding.jellyfin/README.md
  bundles/org.openhab.binding.jellyfin/pom.xml
  bundles/org.openhab.binding.jellyfin/src/main/java/org/openhab/binding/jellyfin/internal/handler/JellyfinClientHandler.java
Labels: enhancement

#15410 [opensprinkler] Fix Program names and add new features for firmware 2.2.0
  bundles/org.openhab.binding.opensprinkler/README.md
  bundles/org.openhab.binding.opensprinkler/pom.xml
  bundles/org.openhab.binding.opensprinkler/src/main/java/org/openhab/binding/opensprinkler/internal/OpenSprinklerBindingConstants.java
  bundles/org.openhab.binding.opensprinkler/src/main/java/org/openhab/binding/opensprinkler/internal/OpenSprinklerState.java
  bundles/org.openhab.binding.opensprinkler/src/main/java/org/openhab/binding/opensprinkler/internal/api/OpenSprinklerApi.java
  bundles/org.openhab.binding.opensprinkler/src/main/java/org/openhab/binding/opensprinkler/internal/api/OpenSprinklerApiFactory.java
  bundles/org.openhab.binding.opensprinkler/src/main/java/org/openhab/binding/opensprinkler/internal/api/OpenSprinklerHttpApiV100.java
  bundles/org.openhab.binding.opensprinkler/src/main/java/org/openhab/binding/opensprinkler/internal/api/OpenSprinklerHttpApiV219.java
  bundles/org.openhab.binding.opensprinkler/src/main/java/org/openhab/binding/opensprinkler/internal/api/OpenSprinklerHttpApiV220.java
  bundles/org.openhab.binding.opensprinkler/src/main/java/org/openhab/binding/opensprinkler/internal/handler/OpenSprinklerDeviceHandler.java
  bundles/org.openhab.binding.opensprinkler/src/main/resources/OH-INF/i18n/opensprinkler.properties
  bundles/org.openhab.binding.opensprinkler/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.opensprinkler/src/main/resources/OH-INF/update/instructions.xml
Labels: bug, enhancement

#16032 [tesla] Fix "jumping" location updates
  bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/TeslaChannelSelectorProxy.java
Labels: bug

#15743 [neohub] Avoid too frequent requests to hub
  bundles/org.openhab.binding.neohub/src/main/java/org/openhab/binding/neohub/internal/NeoHubHandler.java
  bundles/org.openhab.binding.neohub/src/main/java/org/openhab/binding/neohub/internal/NeoHubSocket.java
  bundles/org.openhab.binding.neohub/src/main/java/org/openhab/binding/neohub/internal/NeoHubSocketBase.java
  bundles/org.openhab.binding.neohub/src/main/java/org/openhab/binding/neohub/internal/NeoHubWebSocket.java
Labels: bug

#15986 [pilight] Add option to disable background discovery for a given pilight bridge thing
  bundles/org.openhab.binding.pilight/README.md
  bundles/org.openhab.binding.pilight/src/main/java/org/openhab/binding/pilight/internal/PilightBridgeConfiguration.java
  bundles/org.openhab.binding.pilight/src/main/java/org/openhab/binding/pilight/internal/discovery/PilightDeviceDiscoveryService.java
  bundles/org.openhab.binding.pilight/src/main/java/org/openhab/binding/pilight/internal/handler/PilightBridgeHandler.java
  bundles/org.openhab.binding.pilight/src/main/resources/OH-INF/i18n/pilight.properties
  bundles/org.openhab.binding.pilight/src/main/resources/OH-INF/thing/bridge.xml
Labels: enhancement

#16035 [denon] Add discovery method for Denon receiver
  bundles/org.openhab.binding.denonmarantz/src/main/resources/OH-INF/addon/addon.xml
Labels: enhancement, regression

#16016 [openwebnet] Update label pattern in items example
  bundles/org.openhab.binding.openwebnet/README.md
Labels: documentation

#15962 [openwebnet] updated links in README
  bundles/org.openhab.binding.openwebnet/README.md
Labels: documentation

#16021 [boschshc] Add support for motion detector illuminance sensor
  bundles/org.openhab.binding.boschshc/README.md
  bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/devices/BoschSHCBindingConstants.java
  bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/devices/motiondetector/MotionDetectorHandler.java
  bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/services/illuminance/IlluminanceService.java
  bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/services/illuminance/dto/IlluminanceServiceState.java
  bundles/org.openhab.binding.boschshc/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.boschshc/src/main/resources/OH-INF/update/binding.xml
  bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/devices/motiondetector/MotionDetectorHandlerTest.java
Labels: enhancement

#15875 [mqtt.homeassistant] Improve Cover support
  bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/values/RollershutterValue.java
  bundles/org.openhab.binding.mqtt.generic/src/test/java/org/openhab/binding/mqtt/generic/values/ValueTests.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/AbstractComponent.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/Cover.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/Light.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/component/CoverTests.java
Labels: enhancement

#16018 [hue] Fix scene channel updates (API v2)
  bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/Clip2BridgeHandler.java
  bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/Clip2ThingHandler.java
Labels: bug

#16053 [deconz] Fix discovery methods
  bundles/org.openhab.binding.deconz/src/main/resources/OH-INF/addon/addon.xml
Labels: bug, regression

#15753 [sonyprojector] Add new channel to send infrared remote commands
  bundles/org.openhab.binding.sonyprojector/README.md
  bundles/org.openhab.binding.sonyprojector/src/main/java/org/openhab/binding/sonyprojector/internal/SonyProjectorBindingConstants.java
  bundles/org.openhab.binding.sonyprojector/src/main/java/org/openhab/binding/sonyprojector/internal/SonyProjectorCommandDescriptionOptionProvider.java
  bundles/org.openhab.binding.sonyprojector/src/main/java/org/openhab/binding/sonyprojector/internal/SonyProjectorHandlerFactory.java
  bundles/org.openhab.binding.sonyprojector/src/main/java/org/openhab/binding/sonyprojector/internal/SonyProjectorModel.java
  bundles/org.openhab.binding.sonyprojector/src/main/java/org/openhab/binding/sonyprojector/internal/communication/SonyProjectorAspect.java
  bundles/org.openhab.binding.sonyprojector/src/main/java/org/openhab/binding/sonyprojector/internal/communication/SonyProjectorCalibrationPreset.java
  bundles/org.openhab.binding.sonyprojector/src/main/java/org/openhab/binding/sonyprojector/internal/communication/SonyProjectorConnector.java
  bundles/org.openhab.binding.sonyprojector/src/main/java/org/openhab/binding/sonyprojector/internal/communication/SonyProjectorInput.java
  bundles/org.openhab.binding.sonyprojector/src/main/java/org/openhab/binding/sonyprojector/internal/communication/SonyProjectorItem.java
  bundles/org.openhab.binding.sonyprojector/src/main/java/org/openhab/binding/sonyprojector/internal/communication/sdcp/SonyProjectorSdcpConnector.java
  bundles/org.openhab.binding.sonyprojector/src/main/java/org/openhab/binding/sonyprojector/internal/communication/sdcp/SonyProjectorSdcpSimuConnector.java
  bundles/org.openhab.binding.sonyprojector/src/main/java/org/openhab/binding/sonyprojector/internal/communication/serial/SonyProjectorSerialConnector.java
  bundles/org.openhab.binding.sonyprojector/src/main/java/org/openhab/binding/sonyprojector/internal/handler/SonyProjectorHandler.java
  bundles/org.openhab.binding.sonyprojector/src/main/resources/OH-INF/i18n/sonyprojector.properties
  bundles/org.openhab.binding.sonyprojector/src/main/resources/OH-INF/thing/channels.xml
  bundles/org.openhab.binding.sonyprojector/src/main/resources/OH-INF/thing/ethernet.xml
  bundles/org.openhab.binding.sonyprojector/src/main/resources/OH-INF/thing/serial.xml
  bundles/org.openhab.binding.sonyprojector/src/main/resources/OH-INF/thing/serialoverip.xml
  bundles/org.openhab.binding.sonyprojector/src/main/resources/OH-INF/update/instructions.xml
Labels: enhancement

#16042 [knx] New modifier to set mainGA write-only
  bundles/org.openhab.binding.knx/README.md
  bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/channel/GroupAddressConfiguration.java
  bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/handler/DeviceThingHandler.java
Labels: enhancement

#16043 [monopriceaudio] Add support for 4 zone model
  bundles/org.openhab.binding.monopriceaudio/README.md
  bundles/org.openhab.binding.monopriceaudio/src/main/java/org/openhab/binding/monopriceaudio/internal/MonopriceAudioBindingConstants.java
  bundles/org.openhab.binding.monopriceaudio/src/main/java/org/openhab/binding/monopriceaudio/internal/MonopriceAudioHandlerFactory.java
  bundles/org.openhab.binding.monopriceaudio/src/main/java/org/openhab/binding/monopriceaudio/internal/communication/AmplifierModel.java
  bundles/org.openhab.binding.monopriceaudio/src/main/java/org/openhab/binding/monopriceaudio/internal/handler/MonopriceAudioHandler.java
  bundles/org.openhab.binding.monopriceaudio/src/main/resources/OH-INF/i18n/monopriceaudio.properties
  bundles/org.openhab.binding.monopriceaudio/src/main/resources/OH-INF/thing/monoprice4.xml
Labels: enhancement

#16058 [knx] Refine GA documentation
  bundles/org.openhab.binding.knx/README.md
Labels: documentation

#16059 [rrd4j] Reliably get the latest value, if the filter end date is set to "now"
  bundles/org.openhab.persistence.rrd4j/src/main/java/org/openhab/persistence/rrd4j/internal/RRD4jPersistenceService.java
Labels: bug, regression

#15963 [openweathermap] Add support for persisting OneCall API forecasts
  bundles/org.openhab.binding.openweathermap/README.md
  bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/handler/OpenWeatherMapOneCallHandler.java
  bundles/org.openhab.binding.openweathermap/src/main/resources/OH-INF/config/config.xml
  bundles/org.openhab.binding.openweathermap/src/main/resources/OH-INF/i18n/openweathermap.properties
  bundles/org.openhab.binding.openweathermap/src/main/resources/OH-INF/thing/channel-types.xml
  bundles/org.openhab.binding.openweathermap/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.openweathermap/src/main/resources/OH-INF/update/instructions.xml
Labels: enhancement

#16062 [jsscripting] Upgrade openhab-js to 4.7.0
  bundles/org.openhab.automation.jsscripting/README.md
  bundles/org.openhab.automation.jsscripting/pom.xml
Labels: enhancement

#14998 [opensprinkler] Make http connection more resilient
  bundles/org.openhab.binding.opensprinkler/README.md
  bundles/org.openhab.binding.opensprinkler/src/main/java/org/openhab/binding/opensprinkler/internal/OpenSprinklerBindingConstants.java
  bundles/org.openhab.binding.opensprinkler/src/main/java/org/openhab/binding/opensprinkler/internal/api/OpenSprinklerHttpApiV100.java
  bundles/org.openhab.binding.opensprinkler/src/main/java/org/openhab/binding/opensprinkler/internal/config/OpenSprinklerHttpInterfaceConfig.java
  bundles/org.openhab.binding.opensprinkler/src/main/resources/OH-INF/i18n/opensprinkler.properties
  bundles/org.openhab.binding.opensprinkler/src/main/resources/OH-INF/thing/thing-types.xml
Labels: enhancement, awaiting feedback

#14028 [opengarage] Add door transition status support
  bundles/org.openhab.binding.opengarage/README.md
  bundles/org.openhab.binding.opengarage/src/main/java/org/openhab/binding/opengarage/internal/OpenGarageBindingConstants.java
  bundles/org.openhab.binding.opengarage/src/main/java/org/openhab/binding/opengarage/internal/OpenGarageConfiguration.java
  bundles/org.openhab.binding.opengarage/src/main/java/org/openhab/binding/opengarage/internal/OpenGarageHandler.java
  bundles/org.openhab.binding.opengarage/src/main/java/org/openhab/binding/opengarage/internal/OpenGarageWebTargets.java
  bundles/org.openhab.binding.opengarage/src/main/resources/OH-INF/i18n/opengarage.properties
  bundles/org.openhab.binding.opengarage/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.opengarage/src/main/resources/OH-INF/update/instructions.xml
Labels: enhancement, awaiting feedback

#15234 [nikobus] Update README.md
  bundles/org.openhab.binding.nikobus/README.md
Labels: documentation

#14241 [mqtt.homeassistant] Add support for Update component
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/DiscoverComponents.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/ComponentFactory.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/Update.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/handler/HomeAssistantThingHandler.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/resources/OH-INF/config/homeassistant-thing-config.xml
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/resources/OH-INF/i18n/mqtt.properties
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/resources/OH-INF/thing/homeassistant-thing.xml
Labels: enhancement

#16066 [mqtt.espmilighthub] use ColorUtil instead of deprecated HSBType.fromXY
  bundles/org.openhab.binding.mqtt.espmilighthub/src/main/java/org/openhab/binding/mqtt/espmilighthub/internal/handler/EspMilightHubHandler.java
Labels: bug

#13801 [mqtt.espmilighthub] Use system channel types for color temp and brightness
  bundles/org.openhab.binding.mqtt.espmilighthub/README.md
  bundles/org.openhab.binding.mqtt.espmilighthub/src/main/java/org/openhab/binding/mqtt/espmilighthub/internal/EspMilightHubBindingConstants.java
  bundles/org.openhab.binding.mqtt.espmilighthub/src/main/java/org/openhab/binding/mqtt/espmilighthub/internal/EspMilightStateDescriptionProvider.java
  bundles/org.openhab.binding.mqtt.espmilighthub/src/main/java/org/openhab/binding/mqtt/espmilighthub/internal/handler/EspMilightHubHandler.java
  bundles/org.openhab.binding.mqtt.espmilighthub/src/main/resources/OH-INF/i18n/mqtt.properties
  bundles/org.openhab.binding.mqtt.espmilighthub/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.mqtt.espmilighthub/src/main/resources/OH-INF/update/instructions.xml
Labels: enhancement, (potentially) not backward compatible

#16064 [neato] Fix things file example in Readme
  bundles/org.openhab.binding.neato/README.md
Labels: documentation

#16056 [netatmo] Ensure to close all scheduled jobs
  bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/ApiBridgeHandler.java
  bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/CommonInterface.java
  bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/capability/CapabilityMap.java
  bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/capability/ParentUpdateCapability.java
  bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/capability/RefreshCapability.java
Labels: bug

#16031 addoninfo for new add-on suggestion finder "process"
  bundles/org.openhab.binding.deconz/src/main/resources/OH-INF/addon/addon.xml
  bundles/org.openhab.binding.knx/src/main/resources/OH-INF/addon/addon.xml
  bundles/org.openhab.binding.mqtt/src/main/resources/OH-INF/addon/addon.xml
  bundles/org.openhab.binding.onewire/src/main/resources/OH-INF/addon/addon.xml
  bundles/org.openhab.persistence.influxdb/src/main/resources/OH-INF/addon/addon.xml
  bundles/org.openhab.persistence.jdbc/src/main/resources/OH-INF/addon/addon-mariadb.xml
  bundles/org.openhab.persistence.jdbc/src/main/resources/OH-INF/addon/addon-mysql.xml
  bundles/org.openhab.persistence.jdbc/src/main/resources/OH-INF/addon/addon-postgresql.xml
  bundles/org.openhab.persistence.mongodb/src/main/resources/OH-INF/addon/addon.xml
Labels: enhancement, awaiting other PR

#16033 [knx] Add discovery service
  bundles/org.openhab.binding.knx/README.md
  bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/discovery/KNXnetDiscoveryService.java
  bundles/org.openhab.binding.knx/src/main/resources/OH-INF/thing/ip.xml
Labels: enhancement

#15727 [knx] Add integration tests
  bundles/org.openhab.binding.knx/doc/dpt.txt
  bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/dpt/DPTUtil.java
  bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/dpt/ValueDecoder.java
  bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/dpt/ValueEncoder.java
  bundles/org.openhab.binding.knx/src/test/java/org/openhab/binding/knx/internal/client/DummyClient.java
  bundles/org.openhab.binding.knx/src/test/java/org/openhab/binding/knx/internal/client/DummyKNXNetworkLink.java
  bundles/org.openhab.binding.knx/src/test/java/org/openhab/binding/knx/internal/client/DummyProcessListener.java
  bundles/org.openhab.binding.knx/src/test/java/org/openhab/binding/knx/internal/dpt/DPTTest.java
  bundles/org.openhab.binding.knx/src/test/java/org/openhab/binding/knx/internal/itests/Back2BackTest.java
Labels: enhancement, test

#16070 [energidataservice] Add UoM support for energy prices
  bundles/org.openhab.binding.energidataservice/README.md
  bundles/org.openhab.binding.energidataservice/src/main/java/org/openhab/binding/energidataservice/internal/handler/EnergiDataServiceHandler.java
  bundles/org.openhab.binding.energidataservice/src/main/resources/OH-INF/thing/channel-groups.xml
  bundles/org.openhab.binding.energidataservice/src/main/resources/OH-INF/thing/channel-types.xml
  bundles/org.openhab.binding.energidataservice/src/main/resources/OH-INF/thing/thing-service.xml
  bundles/org.openhab.binding.energidataservice/src/main/resources/OH-INF/update/instructions.xml
Labels: enhancement

#16038 [hue] Re-create missing scene channel (API v2)
  bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/HueBindingConstants.java
  bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/Clip2ThingHandler.java
Labels: bug

#15613 [ipcamera] Fix Hikvision cameras stay offline when a 401 reply is given with no www-authenticate header
  bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/MyNettyAuthHandler.java
Labels: bug

#16017 [smgw] Initial contribution
  CODEOWNERS
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.smgw/NOTICE
  bundles/org.openhab.binding.smgw/README.md
  bundles/org.openhab.binding.smgw/pom.xml
  bundles/org.openhab.binding.smgw/src/main/feature/feature.xml
  bundles/org.openhab.binding.smgw/src/main/java/org/openhab/binding/smgw/internal/SmgwBindingConstants.java
  bundles/org.openhab.binding.smgw/src/main/java/org/openhab/binding/smgw/internal/SmgwConfiguration.java
  bundles/org.openhab.binding.smgw/src/main/java/org/openhab/binding/smgw/internal/SmgwHandler.java
  bundles/org.openhab.binding.smgw/src/main/java/org/openhab/binding/smgw/internal/SmgwHandlerFactory.java
  bundles/org.openhab.binding.smgw/src/main/resources/OH-INF/addon/addon.xml
  bundles/org.openhab.binding.smgw/src/main/resources/OH-INF/i18n/smgw.properties
  bundles/org.openhab.binding.smgw/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/pom.xml
Labels: new binding

#16055 [knx] Metadata for discovery
  bundles/org.openhab.binding.knx/src/main/resources/OH-INF/addon/addon.xml
Labels: awaiting other PR

#15696 [govee] New Govee LAN-API Binding
  CODEOWNERS
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.govee/NOTICE
  bundles/org.openhab.binding.govee/README.md
  bundles/org.openhab.binding.govee/doc/channel-setup1.png
  bundles/org.openhab.binding.govee/doc/channel-setup2.png
  bundles/org.openhab.binding.govee/doc/channel-setup3.png
  bundles/org.openhab.binding.govee/doc/device-settings.png
  bundles/org.openhab.binding.govee/doc/govee-lights.png
  bundles/org.openhab.binding.govee/doc/ui-example.png
  bundles/org.openhab.binding.govee/pom.xml
  bundles/org.openhab.binding.govee/src/main/feature/feature.xml
  bundles/org.openhab.binding.govee/src/main/java/org/openhab/binding/govee/internal/CommunicationManager.java
  bundles/org.openhab.binding.govee/src/main/java/org/openhab/binding/govee/internal/GoveeBindingConstants.java
  bundles/org.openhab.binding.govee/src/main/java/org/openhab/binding/govee/internal/GoveeConfiguration.java
  bundles/org.openhab.binding.govee/src/main/java/org/openhab/binding/govee/internal/GoveeDiscoveryService.java
  bundles/org.openhab.binding.govee/src/main/java/org/openhab/binding/govee/internal/GoveeHandler.java
  bundles/org.openhab.binding.govee/src/main/java/org/openhab/binding/govee/internal/GoveeHandlerFactory.java
  bundles/org.openhab.binding.govee/src/main/java/org/openhab/binding/govee/internal/model/Color.java
  bundles/org.openhab.binding.govee/src/main/java/org/openhab/binding/govee/internal/model/ColorData.java
  bundles/org.openhab.binding.govee/src/main/java/org/openhab/binding/govee/internal/model/DiscoveryData.java
  bundles/org.openhab.binding.govee/src/main/java/org/openhab/binding/govee/internal/model/DiscoveryMsg.java
  bundles/org.openhab.binding.govee/src/main/java/org/openhab/binding/govee/internal/model/DiscoveryResponse.java
  bundles/org.openhab.binding.govee/src/main/java/org/openhab/binding/govee/internal/model/EmptyValueQueryStatusData.java
  bundles/org.openhab.binding.govee/src/main/java/org/openhab/binding/govee/internal/model/GenericGoveeData.java
  bundles/org.openhab.binding.govee/src/main/java/org/openhab/binding/govee/internal/model/GenericGoveeMsg.java
  bundles/org.openhab.binding.govee/src/main/java/org/openhab/binding/govee/internal/model/GenericGoveeRequest.java
  bundles/org.openhab.binding.govee/src/main/java/org/openhab/binding/govee/internal/model/StatusData.java
  bundles/org.openhab.binding.govee/src/main/java/org/openhab/binding/govee/internal/model/StatusMsg.java
  bundles/org.openhab.binding.govee/src/main/java/org/openhab/binding/govee/internal/model/StatusResponse.java
  bundles/org.openhab.binding.govee/src/main/java/org/openhab/binding/govee/internal/model/ValueIntData.java
  bundles/org.openhab.binding.govee/src/main/java/org/openhab/binding/govee/internal/model/ValueStringData.java
  bundles/org.openhab.binding.govee/src/main/resources/OH-INF/addon/addon.xml
  bundles/org.openhab.binding.govee/src/main/resources/OH-INF/config/config.xml
  bundles/org.openhab.binding.govee/src/main/resources/OH-INF/i18n/govee.properties
  bundles/org.openhab.binding.govee/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.govee/src/test/java/org/openhab/binding/govee/internal/GoveeDiscoveryTest.java
  bundles/org.openhab.binding.govee/src/test/java/org/openhab/binding/govee/internal/GoveeSerializeTest.java
  bundles/pom.xml
Labels: new binding

#16077 [wemo] Fix discovery methods
  bundles/org.openhab.binding.wemo/src/main/resources/OH-INF/addon/addon.xml
Labels: bug, regression

#16083 Resolve runbundles for logback upgrade
  itests/org.openhab.automation.groovyscripting.tests/itest.bndrun
  itests/org.openhab.automation.jsscriptingnashorn.tests/itest.bndrun
  itests/org.openhab.binding.avmfritz.tests/itest.bndrun
  itests/org.openhab.binding.feed.tests/itest.bndrun
  itests/org.openhab.binding.hue.tests/itest.bndrun
  itests/org.openhab.binding.max.tests/itest.bndrun
  itests/org.openhab.binding.mielecloud.tests/itest.bndrun
  itests/org.openhab.binding.modbus.tests/itest.bndrun
  itests/org.openhab.binding.mqtt.homeassistant.tests/itest.bndrun
  itests/org.openhab.binding.mqtt.homie.tests/itest.bndrun
  itests/org.openhab.binding.mqtt.ruuvigateway.tests/itest.bndrun
  itests/org.openhab.binding.ntp.tests/itest.bndrun
  itests/org.openhab.binding.systeminfo.tests/itest.bndrun
  itests/org.openhab.binding.tradfri.tests/itest.bndrun
  itests/org.openhab.binding.wemo.tests/itest.bndrun
  itests/org.openhab.persistence.mapdb.tests/itest.bndrun
Labels: awaiting other PR

#16080 [opensprinkler] Fix excessive WARN in logs due to wifi dropouts, and current displays as 0
  bundles/org.openhab.binding.opensprinkler/src/main/java/org/openhab/binding/opensprinkler/internal/api/OpenSprinklerHttpApiV100.java
  bundles/org.openhab.binding.opensprinkler/src/main/resources/OH-INF/thing/thing-types.xml
Labels: bug

#16088 [surepetcare] Fix `NullReferenceException`
  bundles/org.openhab.binding.surepetcare/src/main/java/org/openhab/binding/surepetcare/internal/discovery/SurePetcareDiscoveryService.java
Labels: bug, critical

#16087 [surepetcare] Fix `DateTimeParseException`
  bundles/org.openhab.binding.surepetcare/src/main/java/org/openhab/binding/surepetcare/internal/utils/GsonZonedDateTimeTypeAdapter.java
  bundles/org.openhab.binding.surepetcare/src/test/java/org/openhab/binding/surepetcare/internal/data/SurePetcareTopologyTest.java
Labels: bug, additional testing preferred

#16092 [heos] Minor doc update
  bundles/org.openhab.binding.heos/README.md
Labels: documentation

#16084 [asuswrt] Support router discovery and add-on suggestion using UPnP
  bundles/org.openhab.binding.asuswrt/README.md
  bundles/org.openhab.binding.asuswrt/src/main/feature/feature.xml
  bundles/org.openhab.binding.asuswrt/src/main/java/org/openhab/binding/asuswrt/internal/AsuswrtDiscoveryParticipant.java
  bundles/org.openhab.binding.asuswrt/src/main/java/org/openhab/binding/asuswrt/internal/constants/AsuswrtBindingConstants.java
  bundles/org.openhab.binding.asuswrt/src/main/resources/OH-INF/addon/addon.xml
  bundles/org.openhab.binding.asuswrt/src/main/resources/OH-INF/thing/router.xml
Labels: enhancement

#16081 [ipcamera] Remove channels and stop checking IO status when camera does not support IO
  bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/HikvisionHandler.java
  bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/IpCameraBindingConstants.java
  bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/handler/IpCameraHandler.java
Labels: enhancement

#16106 [jssscripting] Fix JS Quantity to Java QuantityType conversion
  bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/OpenhabGraalJSScriptEngine.java
Labels: bug

#16026 [netatmo] Enable home being both energy and security
  bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/api/dto/NAHomeStatus.java
  bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/deserialization/NADeserializer.java
  bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/capability/EnergyCapability.java
  bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/capability/SecurityCapability.java
  bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/channelhelper/SecurityChannelHelper.java
Labels: bug

#16129 [mqtt.homeassistant] Update README
  bundles/org.openhab.binding.mqtt.homeassistant/README.md
Labels: documentation

#16089 [enocean] Addon suggestion finder xml
  bundles/org.openhab.binding.enocean/src/main/resources/OH-INF/addon/addon.xml
Labels: enhancement

#16132 [jdbc] Upgrade MySQL Connector/J to 8.2.0
  bundles/org.openhab.persistence.jdbc/README.md
  bundles/org.openhab.persistence.jdbc/pom.xml
  bundles/org.openhab.persistence.jdbc/src/main/feature/feature.xml
  bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/JdbcConfiguration.java
Labels: enhancement

#16131 [chatgpt] Fix ConfigOptionProvider
  bundles/org.openhab.binding.chatgpt/src/main/java/org/openhab/binding/chatgpt/internal/ChatGPTBindingConstants.java
  bundles/org.openhab.binding.chatgpt/src/main/java/org/openhab/binding/chatgpt/internal/ChatGPTModelOptionProvider.java
Labels: bug

#16028 [boschshc] Add user defined states
  bundles/org.openhab.binding.boschshc/README.md
  bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/devices/BoschSHCBindingConstants.java
  bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/devices/BoschSHCHandlerFactory.java
  bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/devices/bridge/BoschHttpClient.java
  bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/devices/bridge/BridgeHandler.java
  bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/devices/bridge/ScenarioHandler.java
  bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/devices/bridge/dto/UserDefinedState.java
  bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/devices/userdefinedstate/UserStateHandler.java
  bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/discovery/ThingDiscoveryService.java
  bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/serialization/BoschServiceDataDeserializer.java
  bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/services/dto/BoschSHCServiceState.java
  bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/services/userstate/UserStateService.java
  bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/services/userstate/dto/UserStateServiceState.java
  bundles/org.openhab.binding.boschshc/src/main/resources/OH-INF/config/configs.xml
  bundles/org.openhab.binding.boschshc/src/main/resources/OH-INF/i18n/boschshc.properties
  bundles/org.openhab.binding.boschshc/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/devices/bridge/BoschHttpClientTest.java
  bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/devices/bridge/BridgeHandlerTest.java
  bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/devices/bridge/LongPollingTest.java
  bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/devices/bridge/ScenarioHandlerTest.java
  bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/devices/bridge/dto/UserDefinedStateTest.java
  bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/devices/userdefinedstate/UserStateHandlerTest.java
  bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/discovery/ThingDiscoveryServiceTest.java
  bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/services/dto/BoschSHCServiceStateTest.java
  bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/services/userstate/dto/UserStateServiceStateTest.java
Labels: enhancement

#16152 [amazonechocontrol] Fix Servlet exceptions due to non-unique names
  bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/AccountServlet.java
Labels: bug

#16157 [milight] Fix for failing to increas animation speed
  bundles/org.openhab.binding.milight/src/main/java/org/openhab/binding/milight/internal/handler/MilightV6RGBCWWWHandler.java
  bundles/org.openhab.binding.milight/src/main/java/org/openhab/binding/milight/internal/handler/MilightV6RGBWHandler.java
Labels: bug

#16148 [luxtronikheatpump] add missing channel to readme
  bundles/org.openhab.binding.luxtronikheatpump/README.md
  bundles/org.openhab.binding.luxtronikheatpump/src/main/java/org/openhab/binding/luxtronikheatpump/internal/enums/HeatpumpType.java
  bundles/org.openhab.binding.luxtronikheatpump/src/main/resources/OH-INF/i18n/luxtronikheatpump.properties
Labels: documentation

#16093 [boschshc] Support for Door/Window Contact II
  bundles/org.openhab.binding.boschshc/README.md
  bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/devices/BoschSHCBindingConstants.java
  bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/devices/BoschSHCHandlerFactory.java
  bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/devices/windowcontact/WindowContact2Handler.java
  bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/discovery/ThingDiscoveryService.java
  bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/services/bypass/BypassService.java
  bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/services/bypass/dto/BypassConfiguration.java
  bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/services/bypass/dto/BypassServiceState.java
  bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/services/bypass/dto/BypassState.java
  bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/services/communicationquality/CommunicationQualityService.java
  bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/services/communicationquality/dto/CommunicationQualityServiceState.java
  bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/services/communicationquality/dto/CommunicationQualityState.java
  bundles/org.openhab.binding.boschshc/src/main/resources/OH-INF/i18n/boschshc.properties
  bundles/org.openhab.binding.boschshc/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/devices/windowcontact/WindowContact2HandlerTest.java
  bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/services/bypass/dto/BypassStateTest.java
  bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/services/communicationquality/dto/CommunicationQualityStateTest.java
Labels: enhancement

#16150 [shelly] Fix WebSocketServerFactory ClassNotFoundException
  bundles/org.openhab.binding.shelly/pom.xml
Labels: bug

#16141 [sonos] prevent logging unsupported device
  bundles/org.openhab.binding.sonos/src/main/java/org/openhab/binding/sonos/internal/SonosBindingConstants.java
  bundles/org.openhab.binding.sonos/src/main/java/org/openhab/binding/sonos/internal/discovery/ZonePlayerDiscoveryParticipant.java
Labels: bug

#16161 [boschshc] Fix options for channels with Switch items
  bundles/org.openhab.binding.boschshc/src/main/resources/OH-INF/i18n/boschshc.properties
  bundles/org.openhab.binding.boschshc/src/main/resources/OH-INF/thing/thing-types.xml
Labels: bug

#16146 [wled] Fix Playlist and Preset detection when missing bri values
  bundles/org.openhab.binding.wled/src/main/java/org/openhab/binding/wled/internal/api/WledApiV0110.java
Labels: bug
