Repository openhab/openhab-addons, pull requests merged in 2023-05, with the labels that each got.

#14900 [mapdb] Make serialization asynchronous
  bundles/org.openhab.persistence.mapdb/src/main/java/org/openhab/persistence/mapdb/internal/MapDbPersistenceService.java
  itests/org.openhab.persistence.mapdb.tests/src/main/java/org/openhab/persistence/mapdb/MapDbPersistenceServiceOSGiTest.java
Labels: bug

#14888 [influxdb] Write asynchronously to database and improve performance
  bundles/org.openhab.persistence.influxdb/src/main/java/org/openhab/persistence/influxdb/InfluxDBPersistenceService.java
  bundles/org.openhab.persistence.influxdb/src/main/java/org/openhab/persistence/influxdb/internal/InfluxDBRepository.java
  bundles/org.openhab.persistence.influxdb/src/main/java/org/openhab/persistence/influxdb/internal/ItemToStorePointCreator.java
  bundles/org.openhab.persistence.influxdb/src/main/java/org/openhab/persistence/influxdb/internal/influx1/InfluxDB1RepositoryImpl.java
  bundles/org.openhab.persistence.influxdb/src/main/java/org/openhab/persistence/influxdb/internal/influx2/InfluxDB2RepositoryImpl.java
  bundles/org.openhab.persistence.influxdb/src/test/java/org/openhab/persistence/influxdb/InfluxDBPersistenceServiceTest.java
  bundles/org.openhab.persistence.influxdb/src/test/java/org/openhab/persistence/influxdb/ItemToStorePointCreatorTest.java
Labels: bug, community approved

#14873 [ecovacs] Allow loading device descriptions from a user file
  bundles/org.openhab.binding.ecovacs/README.md
  bundles/org.openhab.binding.ecovacs/src/main/java/org/openhab/binding/ecovacs/internal/api/impl/EcovacsApiImpl.java
  bundles/org.openhab.binding.ecovacs/src/main/resources/devices/supported_device_list.json
Labels: enhancement, regression

#14879 [sensebox] Fix NPE after parsing invalid data
  bundles/org.openhab.binding.sensebox/src/main/java/org/openhab/binding/sensebox/internal/SenseBoxAPIConnection.java
Labels: bug

#14919 [hue] Fix discovery label consistency
  bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/HueBindingConstants.java
  bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/discovery/HueBridgeMDNSDiscoveryParticipant.java
  bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/discovery/HueBridgeNupnpDiscovery.java
  itests/org.openhab.binding.hue.tests/src/main/java/org/openhab/binding/hue/internal/discovery/HueBridgeNupnpDiscoveryOSGITest.java
Labels: bug

#14914 [hue] Restore UPnP discovery for old bridges
  bundles/org.openhab.binding.hue/src/main/feature/feature.xml
  bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/HueBindingConstants.java
  bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/discovery/HueBridgeMDNSDiscoveryParticipant.java
  bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/discovery/HueBridgeUPNPDiscoveryParticipant.java
  itests/org.openhab.binding.hue.tests/itest.bndrun
Labels: bug

#14922 [tesla] Adapt binding to changed API from Tesla backend
  bundles/org.openhab.binding.tesla/README.md
  bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/TeslaBindingConstants.java
  bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/TeslaChannelSelectorProxy.java
  bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/handler/TeslaAccountHandler.java
  bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/handler/TeslaVehicleHandler.java
  bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/protocol/VehicleData.java
Labels: bug, critical

#14793 [FolderWatcher] Formatting and write out of abbreviations in Docs
  bundles/org.openhab.binding.folderwatcher/README.md
Labels: documentation

#14925 [Folderwatcher] AWS S3 bucket thing status fix
  bundles/org.openhab.binding.folderwatcher/src/main/java/org/openhab/binding/folderwatcher/internal/api/S3Actions.java
  bundles/org.openhab.binding.folderwatcher/src/main/java/org/openhab/binding/folderwatcher/internal/handler/S3BucketWatcherHandler.java
Labels: bug, regression

#14661 [iCloud] Fix things reappearing in inbox
  bundles/org.openhab.binding.icloud/src/main/java/org/openhab/binding/icloud/internal/discovery/ICloudDeviceDiscovery.java
  bundles/org.openhab.binding.icloud/src/main/java/org/openhab/binding/icloud/internal/handler/ICloudDeviceHandler.java
  bundles/org.openhab.binding.icloud/src/main/java/org/openhab/binding/icloud/internal/handler/dto/json/response/ICloudDeviceInformation.java
  bundles/org.openhab.binding.icloud/src/test/java/org/openhab/binding/icloud/TestICloud.java
Labels: bug

#14921 [solarwatt] Update README.md
  bundles/org.openhab.binding.solarwatt/README.md
Labels: documentation

#14924 [tesla] Adapt binding to changed API from Tesla backend
  bundles/org.openhab.binding.tesla/README.md
  bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/TeslaBindingConstants.java
  bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/TeslaChannelSelectorProxy.java
  bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/TeslaHandlerFactory.java
  bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/discovery/TeslaVehicleDiscoveryService.java
  bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/handler/TeslaAccountHandler.java
  bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/handler/TeslaEventEndpoint.java
  bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/handler/TeslaSSOHandler.java
  bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/handler/TeslaVehicleHandler.java
  bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/handler/ThingWebClientUtil.java
  bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/handler/VehicleListener.java
  bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/protocol/VehicleConfig.java
  bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/protocol/VehicleData.java
  bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/throttler/TimeProvider.java
  bundles/org.openhab.binding.tesla/src/main/resources/OH-INF/i18n/tesla.properties
  bundles/org.openhab.binding.tesla/src/main/resources/OH-INF/thing/channels.xml
  bundles/org.openhab.binding.tesla/src/main/resources/OH-INF/thing/vehicle.xml
Labels: bug, patch

#14373 [avmfritz] Add light blub color temperature support
  bundles/org.openhab.binding.avmfritz/README.md
  bundles/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/AVMFritzBindingConstants.java
  bundles/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/handler/AVMFritzBaseThingHandler.java
  bundles/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/hardware/FritzAhaWebInterface.java
  bundles/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/hardware/callbacks/FritzAhaSetColorTemperatureCallback.java
  bundles/org.openhab.binding.avmfritz/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.avmfritz/src/main/resources/OH-INF/update/instructions.xml
Labels: enhancement

#14720 [anthem] Add channel, refactor parser, add tests
  bundles/org.openhab.binding.anthem/README.md
  bundles/org.openhab.binding.anthem/src/main/java/org/openhab/binding/anthem/internal/AnthemBindingConstants.java
  bundles/org.openhab.binding.anthem/src/main/java/org/openhab/binding/anthem/internal/handler/AnthemCommand.java
  bundles/org.openhab.binding.anthem/src/main/java/org/openhab/binding/anthem/internal/handler/AnthemCommandParser.java
  bundles/org.openhab.binding.anthem/src/main/java/org/openhab/binding/anthem/internal/handler/AnthemHandler.java
  bundles/org.openhab.binding.anthem/src/main/java/org/openhab/binding/anthem/internal/handler/AnthemUpdate.java
  bundles/org.openhab.binding.anthem/src/main/java/org/openhab/binding/anthem/internal/handler/PropertyUpdate.java
  bundles/org.openhab.binding.anthem/src/main/java/org/openhab/binding/anthem/internal/handler/StateUpdate.java
  bundles/org.openhab.binding.anthem/src/main/resources/OH-INF/i18n/anthem.properties
  bundles/org.openhab.binding.anthem/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.anthem/src/main/resources/OH-INF/update/instructions.xml
  bundles/org.openhab.binding.anthem/src/test/java/org/openhab/binding/anthem/internal/handler/AnthemCommandParserTest.java
Labels: enhancement

#14790 [tapocontrol] Moved error messages to i18n
  bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/api/TapoCloudConnector.java
  bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/api/TapoDeviceConnector.java
  bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/api/TapoDeviceHttpApi.java
  bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/constants/TapoErrorCode.java
  bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/constants/TapoErrorConstants.java
  bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/constants/TapoErrorType.java
  bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/device/TapoDevice.java
  bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/helpers/TapoErrorHandler.java
  bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/structures/TapoEnergyData.java
  bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/structures/TapoLightEffect.java
  bundles/org.openhab.binding.tapocontrol/src/main/resources/OH-INF/i18n/tapocontrol.properties
Labels: enhancement, i18n

#14819 [openwebnet] Add a time stamp when an alarm zone event occurs
  bundles/org.openhab.binding.openwebnet/README.md
  bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/OpenWebNetBindingConstants.java
  bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/handler/OpenWebNetAlarmHandler.java
  bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/i18n/openwebnet.properties
  bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/thing/BusAlarmZone.xml
  bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/thing/channels.xml
  bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/update/update.xml
Labels: enhancement

#14920 [sonos] Add support for Era 100 and Era 300
  bundles/org.openhab.binding.sonos/README.md
  bundles/org.openhab.binding.sonos/src/main/java/org/openhab/binding/sonos/internal/SonosBindingConstants.java
  bundles/org.openhab.binding.sonos/src/main/resources/OH-INF/i18n/sonos.properties
  bundles/org.openhab.binding.sonos/src/main/resources/OH-INF/thing/Era100.xml
  bundles/org.openhab.binding.sonos/src/main/resources/OH-INF/thing/Era300.xml
Labels: enhancement

#14944 [nuvo] Fix ALLOFF event to source button channels
  bundles/org.openhab.binding.nuvo/src/main/java/org/openhab/binding/nuvo/internal/handler/NuvoHandler.java
Labels: bug, regression

#14918 [hue] Fix NUPnP discovery
  bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/discovery/HueBridgeNupnpDiscovery.java
  itests/org.openhab.binding.hue.tests/src/main/java/org/openhab/binding/hue/internal/discovery/HueBridgeNupnpDiscoveryOSGITest.java
Labels: bug, patch

#14357 [openwebnet] Improve shutterRun calibration
  bundles/org.openhab.binding.openwebnet/README.md
  bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/handler/OpenWebNetAutomationHandler.java
  bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/handler/OpenWebNetBridgeHandler.java
  bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/handler/OpenWebNetThingHandler.java
  bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/i18n/openwebnet.properties
Labels: enhancement

#14953 [MQTT] Fix a typo in the README
  bundles/org.openhab.binding.mqtt.generic/README.md
Labels: documentation

#14909 [ipcamera] Fix orphan ffmpeg process after stopping stream URL
  bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/servlet/CameraServlet.java
Labels: bug

#14913 [rrd4j] Write asynchronously to database
  bundles/org.openhab.persistence.rrd4j/src/main/java/org/openhab/persistence/rrd4j/internal/RRD4jPersistenceService.java
Labels: bug, additional testing preferred

#14811 [Meteoalerte] Add an IconProvider
  bundles/org.openhab.binding.meteoalerte/README.md
  bundles/org.openhab.binding.meteoalerte/src/main/java/org/openhab/binding/meteoalerte/internal/MeteoAlertIconProvider.java
  bundles/org.openhab.binding.meteoalerte/src/main/java/org/openhab/binding/meteoalerte/internal/MeteoAlerteBindingConstants.java
  bundles/org.openhab.binding.meteoalerte/src/main/java/org/openhab/binding/meteoalerte/internal/MeteoAlerteHandlerFactory.java
  bundles/org.openhab.binding.meteoalerte/src/main/java/org/openhab/binding/meteoalerte/internal/handler/MeteoAlerteHandler.java
  bundles/org.openhab.binding.meteoalerte/src/main/java/org/openhab/binding/meteoalerte/internal/json/ApiResponse.java
  bundles/org.openhab.binding.meteoalerte/src/main/java/org/openhab/binding/meteoalerte/internal/json/Parameters.java
  bundles/org.openhab.binding.meteoalerte/src/main/java/org/openhab/binding/meteoalerte/internal/json/Record.java
  bundles/org.openhab.binding.meteoalerte/src/main/java/org/openhab/binding/meteoalerte/internal/json/ResponseFieldDTO.java
  bundles/org.openhab.binding.meteoalerte/src/main/resources/OH-INF/i18n/meteoalerte.properties
  bundles/org.openhab.binding.meteoalerte/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.meteoalerte/src/main/resources/OH-INF/update/instructions.xml
  bundles/org.openhab.binding.meteoalerte/src/main/resources/icon/avalanches.svg
  bundles/org.openhab.binding.meteoalerte/src/main/resources/icon/canicule.svg
  bundles/org.openhab.binding.meteoalerte/src/main/resources/icon/grand-froid.svg
  bundles/org.openhab.binding.meteoalerte/src/main/resources/icon/inondation.svg
  bundles/org.openhab.binding.meteoalerte/src/main/resources/icon/meteo_france.svg
  bundles/org.openhab.binding.meteoalerte/src/main/resources/icon/neige.svg
  bundles/org.openhab.binding.meteoalerte/src/main/resources/icon/orage.svg
  bundles/org.openhab.binding.meteoalerte/src/main/resources/icon/pluie-inondation.svg
  bundles/org.openhab.binding.meteoalerte/src/main/resources/icon/vague-submersion.svg
  bundles/org.openhab.binding.meteoalerte/src/main/resources/icon/vent.svg
  bundles/org.openhab.binding.meteoalerte/src/main/resources/picto/avalanches.svg
  bundles/org.openhab.binding.meteoalerte/src/main/resources/picto/canicule.svg
  bundles/org.openhab.binding.meteoalerte/src/main/resources/picto/grand-froid.svg
  bundles/org.openhab.binding.meteoalerte/src/main/resources/picto/inondation.svg
  bundles/org.openhab.binding.meteoalerte/src/main/resources/picto/neige.svg
  bundles/org.openhab.binding.meteoalerte/src/main/resources/picto/orage.svg
  bundles/org.openhab.binding.meteoalerte/src/main/resources/picto/pluie-inondation.svg
  bundles/org.openhab.binding.meteoalerte/src/main/resources/picto/vague-submersion.svg
  bundles/org.openhab.binding.meteoalerte/src/main/resources/picto/vent.svg
Labels: enhancement

#14966 [dynamodb] Changes required after API changes in core framework
  bundles/org.openhab.persistence.dynamodb/src/main/java/org/openhab/persistence/dynamodb/internal/DynamoDBPersistenceService.java
  bundles/org.openhab.persistence.dynamodb/src/main/java/org/openhab/persistence/dynamodb/internal/DynamoDBQueryUtils.java
  bundles/org.openhab.persistence.dynamodb/src/test/java/org/openhab/persistence/dynamodb/internal/BaseIntegrationTest.java
Labels: bug, test

#14512 [miio] Update readme wrt unsupported devices
  bundles/org.openhab.binding.miio/README.base.md
  bundles/org.openhab.binding.miio/README.md
  bundles/org.openhab.binding.miio/src/main/resources/OH-INF/i18n/miio.properties
  bundles/org.openhab.binding.miio/src/main/resources/OH-INF/thing/unsupportedThing.xml
Labels: documentation

#14950 [boschindego] Refactor OAuth2 implementation
  bundles/org.openhab.binding.boschindego/src/main/java/org/openhab/binding/boschindego/internal/AuthorizationController.java
  bundles/org.openhab.binding.boschindego/src/main/java/org/openhab/binding/boschindego/internal/AuthorizationListener.java
  bundles/org.openhab.binding.boschindego/src/main/java/org/openhab/binding/boschindego/internal/AuthorizationProvider.java
  bundles/org.openhab.binding.boschindego/src/main/java/org/openhab/binding/boschindego/internal/IndegoController.java
  bundles/org.openhab.binding.boschindego/src/main/java/org/openhab/binding/boschindego/internal/IndegoDeviceController.java
  bundles/org.openhab.binding.boschindego/src/main/java/org/openhab/binding/boschindego/internal/handler/BoschAccountHandler.java
  bundles/org.openhab.binding.boschindego/src/main/java/org/openhab/binding/boschindego/internal/handler/BoschIndegoHandler.java
  bundles/org.openhab.binding.boschindego/src/main/resources/OH-INF/i18n/boschindego.properties
Labels: enhancement, regression

#14980 [ecobee] Delete oauth service and access token when thing removed
  bundles/org.openhab.binding.ecobee/src/main/java/org/openhab/binding/ecobee/internal/handler/EcobeeAccountBridgeHandler.java
Labels: bug

#13936 [monopriceaudio] Add support for additional amplifiers
  bundles/org.openhab.binding.monopriceaudio/README.md
  bundles/org.openhab.binding.monopriceaudio/src/main/java/org/openhab/binding/monopriceaudio/internal/MonopriceAudioBindingConstants.java
  bundles/org.openhab.binding.monopriceaudio/src/main/java/org/openhab/binding/monopriceaudio/internal/MonopriceAudioHandlerFactory.java
  bundles/org.openhab.binding.monopriceaudio/src/main/java/org/openhab/binding/monopriceaudio/internal/communication/AmplifierModel.java
  bundles/org.openhab.binding.monopriceaudio/src/main/java/org/openhab/binding/monopriceaudio/internal/communication/MonopriceAudioCommand.java
  bundles/org.openhab.binding.monopriceaudio/src/main/java/org/openhab/binding/monopriceaudio/internal/communication/MonopriceAudioConnector.java
  bundles/org.openhab.binding.monopriceaudio/src/main/java/org/openhab/binding/monopriceaudio/internal/communication/MonopriceAudioDefaultConnector.java
  bundles/org.openhab.binding.monopriceaudio/src/main/java/org/openhab/binding/monopriceaudio/internal/communication/MonopriceAudioIpConnector.java
  bundles/org.openhab.binding.monopriceaudio/src/main/java/org/openhab/binding/monopriceaudio/internal/communication/MonopriceAudioReaderThread.java
  bundles/org.openhab.binding.monopriceaudio/src/main/java/org/openhab/binding/monopriceaudio/internal/communication/MonopriceAudioSerialConnector.java
  bundles/org.openhab.binding.monopriceaudio/src/main/java/org/openhab/binding/monopriceaudio/internal/communication/MonopriceAudioZone.java
  bundles/org.openhab.binding.monopriceaudio/src/main/java/org/openhab/binding/monopriceaudio/internal/configuration/MonopriceAudioThingConfiguration.java
  bundles/org.openhab.binding.monopriceaudio/src/main/java/org/openhab/binding/monopriceaudio/internal/dto/MonopriceAudioZoneDTO.java
  bundles/org.openhab.binding.monopriceaudio/src/main/java/org/openhab/binding/monopriceaudio/internal/handler/MonopriceAudioHandler.java
  bundles/org.openhab.binding.monopriceaudio/src/main/resources/OH-INF/addon/addon.xml
  bundles/org.openhab.binding.monopriceaudio/src/main/resources/OH-INF/i18n/monopriceaudio.properties
  bundles/org.openhab.binding.monopriceaudio/src/main/resources/OH-INF/thing/dax88.xml
  bundles/org.openhab.binding.monopriceaudio/src/main/resources/OH-INF/thing/monoprice.xml
  bundles/org.openhab.binding.monopriceaudio/src/main/resources/OH-INF/thing/monoprice70.xml
  bundles/org.openhab.binding.monopriceaudio/src/main/resources/OH-INF/thing/xantech.xml
Labels: enhancement

#14501 [systeminfo] Use AbstractStorageBasedTypeProvider
  bundles/org.openhab.binding.systeminfo/src/main/java/org/openhab/binding/systeminfo/internal/SysteminfoThingTypeProvider.java
  bundles/org.openhab.binding.systeminfo/src/main/java/org/openhab/binding/systeminfo/internal/handler/SysteminfoHandler.java
  itests/org.openhab.binding.systeminfo.tests/src/main/java/org/openhab/binding/systeminfo/test/SysteminfoOSGiTest.java
Labels: enhancement

#14961 [rrd4j] Do not create RRD file when querying data
  bundles/org.openhab.persistence.rrd4j/src/main/java/org/openhab/persistence/rrd4j/internal/RRD4jPersistenceService.java
Labels: bug

#14956 [remoteopenhab] Use AbstractStorageBasedTypeProvider
  bundles/org.openhab.binding.remoteopenhab/src/main/java/org/openhab/binding/remoteopenhab/internal/RemoteopenhabChannelTypeProvider.java
Labels: enhancement

#14985 [jsscripting] Allow configuring from add-on page
  bundles/org.openhab.automation.jsscripting/src/main/resources/OH-INF/addon/addon.xml
Labels: enhancement

#14933 [goecharger] Avoid potential NullPointerException
  bundles/org.openhab.binding.goecharger/src/main/java/org/openhab/binding/goecharger/internal/handler/GoEChargerHandler.java
  bundles/org.openhab.binding.goecharger/src/main/java/org/openhab/binding/goecharger/internal/handler/GoEChargerV2Handler.java
Labels: bug

#14728 [ipcamera] Add Reolink API support
  bundles/org.openhab.binding.ipcamera/README.md
  bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/CameraConfig.java
  bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/FoscamHandler.java
  bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/IpCameraBindingConstants.java
  bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/ReolinkHandler.java
  bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/ReolinkState.java
  bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/handler/IpCameraHandler.java
  bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/onvif/OnvifConnection.java
  bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/onvif/OnvifDiscovery.java
  bundles/org.openhab.binding.ipcamera/src/main/resources/OH-INF/i18n/ipcamera.properties
  bundles/org.openhab.binding.ipcamera/src/main/resources/OH-INF/thing/thing-types.xml
Labels: enhancement

#14959 [influxdb] Implement ModifiablePersistenceService
  bundles/org.openhab.persistence.influxdb/src/main/java/org/openhab/persistence/influxdb/InfluxDBPersistenceService.java
  bundles/org.openhab.persistence.influxdb/src/main/java/org/openhab/persistence/influxdb/internal/InfluxDBRepository.java
  bundles/org.openhab.persistence.influxdb/src/main/java/org/openhab/persistence/influxdb/internal/influx1/InfluxDB1RepositoryImpl.java
  bundles/org.openhab.persistence.influxdb/src/main/java/org/openhab/persistence/influxdb/internal/influx2/InfluxDB2RepositoryImpl.java
  bundles/org.openhab.persistence.influxdb/src/test/java/org/openhab/persistence/influxdb/ItemToStorePointCreatorTest.java
Labels: enhancement

#14507 [harmonyhub] Use AbstractStorageBasedTypeProvider
  bundles/org.openhab.binding.harmonyhub/src/main/java/org/openhab/binding/harmonyhub/internal/HarmonyHubDynamicTypeProvider.java
  bundles/org.openhab.binding.harmonyhub/src/main/java/org/openhab/binding/harmonyhub/internal/HarmonyHubHandlerFactory.java
  bundles/org.openhab.binding.harmonyhub/src/main/java/org/openhab/binding/harmonyhub/internal/handler/HarmonyDeviceHandler.java
  bundles/org.openhab.binding.harmonyhub/src/main/java/org/openhab/binding/harmonyhub/internal/handler/HarmonyHubHandler.java
Labels: enhancement

#14981 Upgrade SAT to 0.14
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitCharacteristicFactory.java
  bundles/org.openhab.io.homekit/src/main/resources/OH-INF/addon/addon.xml
  bundles/org.openhab.io.hueemulation/src/main/resources/OH-INF/addon/addon.xml
  bundles/org.openhab.io.imperihome/src/main/resources/OH-INF/addon/addon.xml
  bundles/org.openhab.io.metrics/src/main/resources/OH-INF/addon/addon.xml
  bundles/org.openhab.io.neeo/src/main/resources/OH-INF/addon/addon.xml
  bundles/org.openhab.io.openhabcloud/src/main/resources/OH-INF/addon/addon.xml
  pom.xml
Labels: infrastructure

#14987 [jdbc] Fix addon-info
  bundles/org.openhab.persistence.jdbc/src/main/resources/OH-INF/addon/addon-derby.xml
  bundles/org.openhab.persistence.jdbc/src/main/resources/OH-INF/addon/addon-h2.xml
  bundles/org.openhab.persistence.jdbc/src/main/resources/OH-INF/addon/addon-hsqldb.xml
  bundles/org.openhab.persistence.jdbc/src/main/resources/OH-INF/addon/addon-mariadb.xml
  bundles/org.openhab.persistence.jdbc/src/main/resources/OH-INF/addon/addon-mysql.xml
  bundles/org.openhab.persistence.jdbc/src/main/resources/OH-INF/addon/addon-postgresql.xml
  bundles/org.openhab.persistence.jdbc/src/main/resources/OH-INF/addon/addon-sqlite.xml
Labels: bug

#14988 [voicerss] Fix service-id in addon.xml
  bundles/org.openhab.voice.voicerss/src/main/resources/OH-INF/addon/addon.xml
Labels: bug

#14989 [hue] Fix `NullPointerException` in NUPnP discovery
  bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/discovery/HueBridgeNupnpDiscovery.java
Labels: bug

#13287 [liquidcheck] Initial contribution
  CODEOWNERS
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.liquidcheck/NOTICE
  bundles/org.openhab.binding.liquidcheck/README.md
  bundles/org.openhab.binding.liquidcheck/pom.xml
  bundles/org.openhab.binding.liquidcheck/src/main/feature/feature.xml
  bundles/org.openhab.binding.liquidcheck/src/main/java/org/openhab/binding/liquidcheck/internal/LiquidCheckBindingConstants.java
  bundles/org.openhab.binding.liquidcheck/src/main/java/org/openhab/binding/liquidcheck/internal/LiquidCheckConfiguration.java
  bundles/org.openhab.binding.liquidcheck/src/main/java/org/openhab/binding/liquidcheck/internal/LiquidCheckHandler.java
  bundles/org.openhab.binding.liquidcheck/src/main/java/org/openhab/binding/liquidcheck/internal/LiquidCheckHandlerFactory.java
  bundles/org.openhab.binding.liquidcheck/src/main/java/org/openhab/binding/liquidcheck/internal/discovery/LiquidCheckDiscoveryService.java
  bundles/org.openhab.binding.liquidcheck/src/main/java/org/openhab/binding/liquidcheck/internal/httpclient/LiquidCheckHttpClient.java
  bundles/org.openhab.binding.liquidcheck/src/main/java/org/openhab/binding/liquidcheck/internal/json/AccessPoint.java
  bundles/org.openhab.binding.liquidcheck/src/main/java/org/openhab/binding/liquidcheck/internal/json/CommData.java
  bundles/org.openhab.binding.liquidcheck/src/main/java/org/openhab/binding/liquidcheck/internal/json/Context.java
  bundles/org.openhab.binding.liquidcheck/src/main/java/org/openhab/binding/liquidcheck/internal/json/Device.java
  bundles/org.openhab.binding.liquidcheck/src/main/java/org/openhab/binding/liquidcheck/internal/json/Expansion.java
  bundles/org.openhab.binding.liquidcheck/src/main/java/org/openhab/binding/liquidcheck/internal/json/Header.java
  bundles/org.openhab.binding.liquidcheck/src/main/java/org/openhab/binding/liquidcheck/internal/json/LiquidCheckSystem.java
  bundles/org.openhab.binding.liquidcheck/src/main/java/org/openhab/binding/liquidcheck/internal/json/Measure.java
  bundles/org.openhab.binding.liquidcheck/src/main/java/org/openhab/binding/liquidcheck/internal/json/Model.java
  bundles/org.openhab.binding.liquidcheck/src/main/java/org/openhab/binding/liquidcheck/internal/json/Payload.java
  bundles/org.openhab.binding.liquidcheck/src/main/java/org/openhab/binding/liquidcheck/internal/json/Pump.java
  bundles/org.openhab.binding.liquidcheck/src/main/java/org/openhab/binding/liquidcheck/internal/json/Raw.java
  bundles/org.openhab.binding.liquidcheck/src/main/java/org/openhab/binding/liquidcheck/internal/json/Security.java
  bundles/org.openhab.binding.liquidcheck/src/main/java/org/openhab/binding/liquidcheck/internal/json/Station.java
  bundles/org.openhab.binding.liquidcheck/src/main/java/org/openhab/binding/liquidcheck/internal/json/Wifi.java
  bundles/org.openhab.binding.liquidcheck/src/main/resources/OH-INF/addon/addon.xml
  bundles/org.openhab.binding.liquidcheck/src/main/resources/OH-INF/i18n/liquidcheck.properties
  bundles/org.openhab.binding.liquidcheck/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.liquidcheck/src/test/java/org/openhab/binding/liquidcheck/internal/json/ResponseTest.java
  bundles/org.openhab.binding.liquidcheck/src/test/resources/CommandResponseExample.json
  bundles/org.openhab.binding.liquidcheck/src/test/resources/PollingResponseExample.json
  bundles/pom.xml
Labels: new binding

#15000 [vizio] Update app list URLs
  bundles/org.openhab.binding.vizio/README.md
Labels: documentation

#14972 [tapocontrol] LightEffects for L530 can now be set
  bundles/org.openhab.binding.tapocontrol/README.md
  bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/api/TapoDeviceConnector.java
  bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/constants/TapoBindingSettings.java
  bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/constants/TapoThingConstants.java
  bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/device/TapoDevice.java
  bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/device/TapoSmartBulb.java
  bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/structures/TapoLightEffect.java
  bundles/org.openhab.binding.tapocontrol/src/main/resources/OH-INF/i18n/tapocontrol.properties
  bundles/org.openhab.binding.tapocontrol/src/main/resources/OH-INF/thing/L530.xml
Labels: enhancement

#14589 [sonnen] Update to API V2 of vendor and add PowerMeter
  bundles/org.openhab.binding.sonnen/README.md
  bundles/org.openhab.binding.sonnen/src/main/java/org/openhab/binding/sonnen/internal/SonnenBindingConstants.java
  bundles/org.openhab.binding.sonnen/src/main/java/org/openhab/binding/sonnen/internal/SonnenConfiguration.java
  bundles/org.openhab.binding.sonnen/src/main/java/org/openhab/binding/sonnen/internal/SonnenHandler.java
  bundles/org.openhab.binding.sonnen/src/main/java/org/openhab/binding/sonnen/internal/communication/SonnenJSONCommunication.java
  bundles/org.openhab.binding.sonnen/src/main/java/org/openhab/binding/sonnen/internal/communication/SonnenJsonDataDTO.java
  bundles/org.openhab.binding.sonnen/src/main/java/org/openhab/binding/sonnen/internal/communication/SonnenJsonPowerMeterDataDTO.java
  bundles/org.openhab.binding.sonnen/src/main/resources/OH-INF/i18n/sonnen.properties
  bundles/org.openhab.binding.sonnen/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.sonnen/src/main/resources/OH-INF/update/instructions.xml
Labels: enhancement

#14877 [mqtt.espmilighthub] Fix things do not come ONLINE if MQTT Client Status Topic not supplied.
  bundles/org.openhab.binding.mqtt.espmilighthub/README.md
  bundles/org.openhab.binding.mqtt.espmilighthub/src/main/java/org/openhab/binding/mqtt/espmilighthub/internal/handler/EspMilightHubHandler.java
Labels: bug

#15008 [caddx] Update README.md
  bundles/org.openhab.binding.caddx/README.md
Labels: documentation

#15002 [danfossairunit] Add UoM support for rotational speed channels
  bundles/org.openhab.binding.danfossairunit/README.md
  bundles/org.openhab.binding.danfossairunit/src/main/java/org/openhab/binding/danfossairunit/internal/DanfossAirUnit.java
  bundles/org.openhab.binding.danfossairunit/src/main/java/org/openhab/binding/danfossairunit/internal/DanfossAirUnitBindingConstants.java
  bundles/org.openhab.binding.danfossairunit/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.danfossairunit/src/main/resources/OH-INF/update/instructions.xml
  bundles/org.openhab.binding.danfossairunit/src/test/java/org/openhab/binding/danfossairunit/internal/DanfossAirUnitTest.java
Labels: enhancement

#15009 [influxdb] support restoring unit for dimension items
  bundles/org.openhab.persistence.influxdb/src/main/java/org/openhab/persistence/influxdb/internal/InfluxDBStateConvertUtils.java
  bundles/org.openhab.persistence.influxdb/src/test/java/org/openhab/persistence/influxdb/internal/InfluxDBStateConvertUtilsTest.java
Labels: enhancement

#15011 [airthings] Adapt channels to new dimention for Radon measurements
  bundles/org.openhab.binding.bluetooth.airthings/README.md
  bundles/org.openhab.binding.bluetooth.airthings/src/main/java/org/openhab/binding/bluetooth/airthings/internal/AirthingsWavePlusHandler.java
Labels: (potentially) not backward compatible

#15013 [airthings] Fix thing types
  bundles/org.openhab.binding.bluetooth.airthings/src/main/resources/OH-INF/thing/airthings.xml
  bundles/org.openhab.binding.bluetooth.airthings/src/main/resources/OH-INF/update/update.xml
Labels: bug, regression

#14983 [evcc] Adjust to API changes & Add new channels for evcc 0.117.0
  bundles/org.openhab.binding.evcc/README.md
  bundles/org.openhab.binding.evcc/src/main/java/org/openhab/binding/evcc/internal/EvccBindingConstants.java
  bundles/org.openhab.binding.evcc/src/main/java/org/openhab/binding/evcc/internal/EvccHandler.java
  bundles/org.openhab.binding.evcc/src/main/java/org/openhab/binding/evcc/internal/api/EvccAPI.java
  bundles/org.openhab.binding.evcc/src/main/java/org/openhab/binding/evcc/internal/api/dto/Loadpoint.java
  bundles/org.openhab.binding.evcc/src/main/java/org/openhab/binding/evcc/internal/api/dto/Result.java
  bundles/org.openhab.binding.evcc/src/main/java/org/openhab/binding/evcc/internal/api/dto/Status.java
  bundles/org.openhab.binding.evcc/src/main/resources/OH-INF/i18n/evcc.properties
  bundles/org.openhab.binding.evcc/src/main/resources/OH-INF/thing/thing-types.xml
Labels: enhancement

#14532 [shelly] Support for Plus Smoke, Plus Plug-S/IT/UK/US, Plus Dimmer US, Pro 3EM; fix Gen1 sensor initialization
  bundles/org.openhab.binding.shelly/README.md
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/ShellyBindingConstants.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api/ShellyApiInterface.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api/ShellyDeviceProfile.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api1/Shelly1ApiJsonDTO.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api1/Shelly1CoIoTProtocol.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api1/Shelly1CoIoTVersion2.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api1/Shelly1CoapHandler.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api1/Shelly1HttpApi.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api2/Shelly2ApiClient.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api2/Shelly2ApiJsonDTO.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api2/Shelly2ApiRpc.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/discovery/ShellyThingCreator.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/handler/ShellyBaseHandler.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/handler/ShellyComponents.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/handler/ShellyRelayHandler.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/handler/ShellyThingInterface.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/manager/ShellyManagerActionPage.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/provider/ShellyChannelDefinitions.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/util/ShellyUtils.java
  bundles/org.openhab.binding.shelly/src/main/resources/OH-INF/i18n/shelly.properties
  bundles/org.openhab.binding.shelly/src/main/resources/OH-INF/thing/shellyGen1_relay.xml
  bundles/org.openhab.binding.shelly/src/main/resources/OH-INF/thing/shellyGen1_sensor.xml
  bundles/org.openhab.binding.shelly/src/main/resources/OH-INF/thing/shellyGen2_relay.xml
  bundles/org.openhab.binding.shelly/src/main/resources/OH-INF/thing/shellyGen2_sensor.xml
Labels: bug, enhancement
