Repository openhab/openhab-addons, pull requests merged in 2024-11, with the labels that each got.

#17659 [mqtt.homeassistant] Add missing climate properties
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/Climate.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/component/ClimateTests.java
Labels: enhancement

#17269 [shelly] fix NumberFormatException on Shelly2RelayStatus.timerDuration
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api2/Shelly2ApiJsonDTO.java
Labels: bug

#17691 [org.openhab.transform.jsonpath] Fix dead link
  bundles/org.openhab.transform.jsonpath/README.md
Labels: documentation

#17689 [shelly] Fix timeDuration handling in DTOs
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api2/Shelly2ApiClient.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api2/Shelly2ApiJsonDTO.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/handler/ShellyBaseHandler.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/util/ShellyUtils.java
Labels: bug

#17696 [shelly] Fix suggestion finder
  bundles/org.openhab.binding.shelly/src/main/resources/OH-INF/addon/addon.xml
Labels: bug

#17697 [siemensrds] Fix setting of target temperature
  bundles/org.openhab.binding.siemensrds/src/main/java/org/openhab/binding/siemensrds/internal/RdsHandler.java
Labels: bug

#17687 [network] Modify iOS port knock to use a valid mDNS packet
  bundles/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/utils/NetworkUtils.java
Labels: enhancement

#17333 [ecovacs] Fix expired token handling for XML-over-MQTT models
  bundles/org.openhab.binding.ecovacs/src/main/java/org/openhab/binding/ecovacs/internal/api/impl/dto/response/portal/AbstractPortalIotCommandResponse.java
  bundles/org.openhab.binding.ecovacs/src/main/java/org/openhab/binding/ecovacs/internal/api/impl/dto/response/portal/PortalIotCommandJsonResponse.java
  bundles/org.openhab.binding.ecovacs/src/main/java/org/openhab/binding/ecovacs/internal/api/impl/dto/response/portal/PortalIotCommandXmlResponse.java
Labels: bug

#17688 [ism8] Add channel types for heat pumps
  bundles/org.openhab.binding.ism8/README.md
  bundles/org.openhab.binding.ism8/src/main/java/org/openhab/binding/ism8/internal/util/Ism8DomainMap.java
  bundles/org.openhab.binding.ism8/src/main/java/org/openhab/binding/ism8/server/DataPointFactory.java
  bundles/org.openhab.binding.ism8/src/main/java/org/openhab/binding/ism8/server/DataPointIntegerValue.java
  bundles/org.openhab.binding.ism8/src/main/java/org/openhab/binding/ism8/server/DataPointLongValue.java
  bundles/org.openhab.binding.ism8/src/main/java/org/openhab/binding/ism8/server/DataPointValue.java
  bundles/org.openhab.binding.ism8/src/main/resources/OH-INF/i18n/ism8.properties
  bundles/org.openhab.binding.ism8/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.ism8/src/test/java/org/openhab/binding/ism8/internal/util/Ism8DomainMapTest.java
Labels: enhancement, additional testing preferred

#17661 [netatmo] Webhook events are dispatched but group id is missing
  bundles/org.openhab.binding.netatmo/README.md
  bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/api/data/ModuleType.java
  bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/CommonInterface.java
  bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/DeviceHandler.java
  bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/ModuleHandler.java
  bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/capability/CameraCapability.java
  bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/capability/Capability.java
  bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/capability/PersonCapability.java
  bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/servlet/WebhookServlet.java
Labels: bug

#17702 [unifi] Provide LED channel for access point
  bundles/org.openhab.binding.unifi/README.md
  bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/UniFiBindingConstants.java
  bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/api/UniFiController.java
  bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/api/dto/UniFiDevice.java
  bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/handler/UniFiAccessPointThingHandler.java
  bundles/org.openhab.binding.unifi/src/main/resources/OH-INF/i18n/unifi.properties
  bundles/org.openhab.binding.unifi/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.unifi/src/main/resources/OH-INF/update/thing-updates.xml
Labels: enhancement

#17715 [samsungtv] Fix for incorrect PowerState
  bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/handler/SamsungTvHandler.java
Labels: bug

#17699 [snmp] make use of openHAB network configuration
  bundles/org.openhab.binding.snmp/src/main/java/org/openhab/binding/snmp/internal/SnmpServiceImpl.java
Labels: enhancement

#17538 [linky] Yet another website underlaying API modification
  bundles/org.openhab.binding.linky/README.md
  bundles/org.openhab.binding.linky/pom.xml
  bundles/org.openhab.binding.linky/src/main/java/org/openhab/binding/linky/internal/LinkyException.java
  bundles/org.openhab.binding.linky/src/main/java/org/openhab/binding/linky/internal/LinkyHandlerFactory.java
  bundles/org.openhab.binding.linky/src/main/java/org/openhab/binding/linky/internal/api/EnedisHttpApi.java
  bundles/org.openhab.binding.linky/src/main/java/org/openhab/binding/linky/internal/dto/PrmDetail.java
  bundles/org.openhab.binding.linky/src/main/java/org/openhab/binding/linky/internal/dto/PrmInfo.java
  bundles/org.openhab.binding.linky/src/main/java/org/openhab/binding/linky/internal/handler/LinkyHandler.java
  bundles/org.openhab.binding.linky/src/main/resources/OH-INF/thing/thing-types.xml
Labels: bug

#17663 [electroluxappliance] Initial contribution
  CODEOWNERS
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.electroluxappliance/NOTICE
  bundles/org.openhab.binding.electroluxappliance/README.md
  bundles/org.openhab.binding.electroluxappliance/pom.xml
  bundles/org.openhab.binding.electroluxappliance/src/main/feature/feature.xml
  bundles/org.openhab.binding.electroluxappliance/src/main/java/org/openhab/binding/electroluxappliance/internal/ElectroluxApplianceBindingConstants.java
  bundles/org.openhab.binding.electroluxappliance/src/main/java/org/openhab/binding/electroluxappliance/internal/ElectroluxApplianceBridgeConfiguration.java
  bundles/org.openhab.binding.electroluxappliance/src/main/java/org/openhab/binding/electroluxappliance/internal/ElectroluxApplianceConfiguration.java
  bundles/org.openhab.binding.electroluxappliance/src/main/java/org/openhab/binding/electroluxappliance/internal/ElectroluxApplianceException.java
  bundles/org.openhab.binding.electroluxappliance/src/main/java/org/openhab/binding/electroluxappliance/internal/api/ElectroluxGroupAPI.java
  bundles/org.openhab.binding.electroluxappliance/src/main/java/org/openhab/binding/electroluxappliance/internal/discovery/ElectroluxApplianceDiscoveryService.java
  bundles/org.openhab.binding.electroluxappliance/src/main/java/org/openhab/binding/electroluxappliance/internal/dto/AirPurifierStateDTO.java
  bundles/org.openhab.binding.electroluxappliance/src/main/java/org/openhab/binding/electroluxappliance/internal/dto/ApplianceDTO.java
  bundles/org.openhab.binding.electroluxappliance/src/main/java/org/openhab/binding/electroluxappliance/internal/dto/ApplianceInfoDTO.java
  bundles/org.openhab.binding.electroluxappliance/src/main/java/org/openhab/binding/electroluxappliance/internal/dto/ApplianceStateDTO.java
  bundles/org.openhab.binding.electroluxappliance/src/main/java/org/openhab/binding/electroluxappliance/internal/dto/WashingMachineStateDTO.java
  bundles/org.openhab.binding.electroluxappliance/src/main/java/org/openhab/binding/electroluxappliance/internal/handler/ElectroluxAirPurifierHandler.java
  bundles/org.openhab.binding.electroluxappliance/src/main/java/org/openhab/binding/electroluxappliance/internal/handler/ElectroluxApplianceBridgeHandler.java
  bundles/org.openhab.binding.electroluxappliance/src/main/java/org/openhab/binding/electroluxappliance/internal/handler/ElectroluxApplianceHandler.java
  bundles/org.openhab.binding.electroluxappliance/src/main/java/org/openhab/binding/electroluxappliance/internal/handler/ElectroluxApplianceHandlerFactory.java
  bundles/org.openhab.binding.electroluxappliance/src/main/java/org/openhab/binding/electroluxappliance/internal/handler/ElectroluxWashingMachineHandler.java
  bundles/org.openhab.binding.electroluxappliance/src/main/java/org/openhab/binding/electroluxappliance/internal/listener/TokenUpdateListener.java
  bundles/org.openhab.binding.electroluxappliance/src/main/resources/OH-INF/addon/addon.xml
  bundles/org.openhab.binding.electroluxappliance/src/main/resources/OH-INF/i18n/electroluxappliance.properties
  bundles/org.openhab.binding.electroluxappliance/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/pom.xml
Labels: new binding

#17724 [nanoleaf] Suppress ipv6 addr in controller discovery
  bundles/org.openhab.binding.nanoleaf/README.md
  bundles/org.openhab.binding.nanoleaf/src/main/java/org/openhab/binding/nanoleaf/internal/discovery/NanoleafMDNSDiscoveryParticipant.java
Labels: enhancement

#17726 [solax] Fix the parsing of total consumption channel X3-Hybrid-G4
  bundles/org.openhab.binding.solax/src/main/java/org/openhab/binding/solax/internal/model/local/X3HybridG4Data.java
  bundles/org.openhab.binding.solax/src/test/java/org/openhab/binding/solax/internal/local/parsers/TestX3HybridG4Parser.java
Labels: bug, community approved

#17723 [lutron] Added device discovery for DivaSmartDimmer and PaddleSwitchPico
  bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/discovery/LeapDeviceDiscoveryService.java
Labels: enhancement

#17692 [shelly] Add support for Shelly Plus RGBW PM
  bundles/org.openhab.binding.shelly/README.md
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/ShellyBindingConstants.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/ShellyHandlerFactory.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api/ShellyDeviceProfile.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api2/Shelly2ApiClient.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api2/Shelly2ApiJsonDTO.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api2/Shelly2ApiRpc.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/discovery/ShellyThingCreator.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/handler/ShellyComponents.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/handler/ShellyLightHandler.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/provider/ShellyChannelDefinitions.java
  bundles/org.openhab.binding.shelly/src/main/resources/OH-INF/i18n/shelly.properties
  bundles/org.openhab.binding.shelly/src/main/resources/OH-INF/thing/shellyGen2_lights.xml
Labels: enhancement

#17685 [avmfritz] Fix incorrect state of dimmable bulb
  bundles/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/handler/AVMFritzBaseThingHandler.java
  bundles/org.openhab.binding.avmfritz/src/test/java/org/openhab/binding/avmfritz/internal/dto/AVMFritzDeviceListModelTest.java
Labels: bug

#17679 [energidataservice] Fix @ActionOutput annotations
  bundles/org.openhab.binding.energidataservice/src/main/java/org/openhab/binding/energidataservice/internal/action/EnergiDataServiceActions.java
  bundles/org.openhab.binding.energidataservice/src/main/resources/OH-INF/i18n/energidataservice.properties
Labels: additional testing preferred

#17732 [ipcamera] ONVIF events are processed faster, and adds a choice of what event method will be used.
  bundles/org.openhab.binding.ipcamera/README.md
  bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/CameraConfig.java
  bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/Helper.java
  bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/ReolinkHandler.java
  bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/handler/IpCameraHandler.java
  bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/onvif/OnvifCodec.java
  bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/onvif/OnvifConnection.java
  bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/servlet/CameraServlet.java
  bundles/org.openhab.binding.ipcamera/src/main/resources/OH-INF/i18n/ipcamera.properties
  bundles/org.openhab.binding.ipcamera/src/main/resources/OH-INF/thing/thing-types.xml
Labels: enhancement

#17731 [awattar] Fix last hour not being considered for best price
  bundles/org.openhab.binding.awattar/src/main/java/org/openhab/binding/awattar/internal/handler/AwattarBestPriceHandler.java
  bundles/org.openhab.binding.awattar/src/main/java/org/openhab/binding/awattar/internal/handler/AwattarBridgeHandler.java
  bundles/org.openhab.binding.awattar/src/main/java/org/openhab/binding/awattar/internal/handler/TimeRange.java
  bundles/org.openhab.binding.awattar/src/test/java/org/openhab/binding/awattar/internal/handler/AwattarBridgeHandlerTest.java
Labels: bug

#17745 [awattar] Fix last hour not being considered for best price
  bundles/org.openhab.binding.awattar/src/main/java/org/openhab/binding/awattar/internal/handler/AwattarBestpriceHandler.java
  bundles/org.openhab.binding.awattar/src/main/java/org/openhab/binding/awattar/internal/handler/AwattarBridgeHandler.java
  bundles/org.openhab.binding.awattar/src/main/java/org/openhab/binding/awattar/internal/handler/TimeRange.java
  bundles/org.openhab.binding.awattar/src/test/java/org/openhab/binding/awattar/internal/handler/AwattarBridgeHandlerTest.java
Labels: bug

#17743 [radiothermostat] Add next scheduled set point channels
  bundles/org.openhab.binding.radiothermostat/README.md
  bundles/org.openhab.binding.radiothermostat/pom.xml
  bundles/org.openhab.binding.radiothermostat/src/main/java/org/openhab/binding/radiothermostat/internal/RadioThermostatBindingConstants.java
  bundles/org.openhab.binding.radiothermostat/src/main/java/org/openhab/binding/radiothermostat/internal/handler/RadioThermostatHandler.java
  bundles/org.openhab.binding.radiothermostat/src/main/java/org/openhab/binding/radiothermostat/internal/util/RadioThermostatSchedule.java
  bundles/org.openhab.binding.radiothermostat/src/main/java/org/openhab/binding/radiothermostat/internal/util/RadioThermostatScheduleJson.java
  bundles/org.openhab.binding.radiothermostat/src/main/resources/OH-INF/addon/addon.xml
  bundles/org.openhab.binding.radiothermostat/src/main/resources/OH-INF/i18n/radiothermostat.properties
  bundles/org.openhab.binding.radiothermostat/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.radiothermostat/src/main/resources/OH-INF/update/instructions.xml
Labels: enhancement

#17750 [mercedesme] Add vin automatically to discovered vehicle
  bundles/org.openhab.binding.mercedesme/src/main/java/org/openhab/binding/mercedesme/internal/discovery/MercedesMeDiscoveryService.java
  bundles/org.openhab.binding.mercedesme/src/main/java/org/openhab/binding/mercedesme/internal/handler/AccountHandler.java
Labels: bug

#17748 [mercedesme] AdBlue channel for combustion vehicles
  bundles/org.openhab.binding.mercedesme/README.md
  bundles/org.openhab.binding.mercedesme/src/main/java/org/openhab/binding/mercedesme/internal/Constants.java
  bundles/org.openhab.binding.mercedesme/src/main/java/org/openhab/binding/mercedesme/internal/handler/VehicleHandler.java
  bundles/org.openhab.binding.mercedesme/src/main/java/org/openhab/binding/mercedesme/internal/utils/Mapper.java
  bundles/org.openhab.binding.mercedesme/src/main/resources/OH-INF/i18n/mercedesme.properties
  bundles/org.openhab.binding.mercedesme/src/main/resources/OH-INF/thing/range-channel-types.xml
  bundles/org.openhab.binding.mercedesme/src/main/resources/OH-INF/thing/range-conv-channel-group.xml
  bundles/org.openhab.binding.mercedesme/src/main/resources/OH-INF/thing/thing-combustion.xml
  bundles/org.openhab.binding.mercedesme/src/main/resources/OH-INF/update/instructions.xml
  bundles/org.openhab.binding.mercedesme/src/test/java/org/openhab/binding/mercedesme/internal/handler/VehicleHandlerTest.java
  bundles/org.openhab.binding.mercedesme/src/test/resources/proto-json/MB-Combustion.json
Labels: enhancement

#17727 [ipobserver] Add channel rainTotal
  bundles/org.openhab.binding.ipobserver/src/main/java/org/openhab/binding/ipobserver/internal/IpObserverBindingConstants.java
  bundles/org.openhab.binding.ipobserver/src/main/java/org/openhab/binding/ipobserver/internal/IpObserverHandler.java
  bundles/org.openhab.binding.ipobserver/src/main/resources/OH-INF/i18n/ipobserver.properties
  bundles/org.openhab.binding.ipobserver/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.ipobserver/src/main/resources/OH-INF/update/instructions.xml
Labels: enhancement

#17736 [ipobserver] Fix absolute pressure not updating
  bundles/org.openhab.binding.ipobserver/src/main/java/org/openhab/binding/ipobserver/internal/IpObserverHandler.java
Labels: bug

#17738 [ism8] Extend example sitemap
  bundles/org.openhab.binding.ism8/README.md
Labels: documentation

#17677 [plugwiseha] Improve connection stability
  bundles/org.openhab.binding.plugwiseha/src/main/java/org/openhab/binding/plugwiseha/internal/api/model/PlugwiseHAController.java
  bundles/org.openhab.binding.plugwiseha/src/main/java/org/openhab/binding/plugwiseha/internal/api/model/PlugwiseHAControllerRequest.java
  bundles/org.openhab.binding.plugwiseha/src/main/java/org/openhab/binding/plugwiseha/internal/api/model/converter/DateTimeConverter.java
  bundles/org.openhab.binding.plugwiseha/src/main/java/org/openhab/binding/plugwiseha/internal/api/model/dto/ActuatorFunctionalityThermostat.java
  bundles/org.openhab.binding.plugwiseha/src/main/java/org/openhab/binding/plugwiseha/internal/api/model/dto/DomainObjects.java
  bundles/org.openhab.binding.plugwiseha/src/main/java/org/openhab/binding/plugwiseha/internal/api/model/dto/Log.java
  bundles/org.openhab.binding.plugwiseha/src/main/java/org/openhab/binding/plugwiseha/internal/api/model/dto/Module.java
  bundles/org.openhab.binding.plugwiseha/src/main/java/org/openhab/binding/plugwiseha/internal/api/model/dto/Service.java
  bundles/org.openhab.binding.plugwiseha/src/main/java/org/openhab/binding/plugwiseha/internal/discovery/PlugwiseHADiscoveryService.java
  bundles/org.openhab.binding.plugwiseha/src/main/java/org/openhab/binding/plugwiseha/internal/handler/PlugwiseHAApplianceHandler.java
  bundles/org.openhab.binding.plugwiseha/src/main/java/org/openhab/binding/plugwiseha/internal/handler/PlugwiseHAZoneHandler.java
  bundles/org.openhab.binding.plugwiseha/src/main/resources/OH-INF/config/config.xml
Labels: enhancement

#17410 [zway] Remove org.apache.commons.net.util.SubnetUtils
  bundles/org.openhab.binding.zway/src/main/java/org/openhab/binding/zway/internal/discovery/ZWayBridgeDiscoveryService.java
Labels: enhancement

#17759 [ism8] Fix example, regression
  bundles/org.openhab.binding.ism8/README.md
Labels: regression

#17766 [metrics] Fix link to json example
  bundles/org.openhab.io.metrics/README.md
Labels: documentation

#17769 [yamahareceiver] Assign proper read timeouts
  bundles/org.openhab.binding.yamahareceiver/src/main/java/org/openhab/binding/yamahareceiver/internal/protocol/xml/XMLConnection.java
Labels: bug

#17764 Fix `DateTimeType` tests
  bundles/org.openhab.binding.dbquery/src/test/java/org/openhab/binding/dbquery/internal/Value2StateConverterTest.java
  bundles/org.openhab.binding.fineoffsetweatherstation/src/test/java/org/openhab/binding/fineoffsetweatherstation/internal/service/FineOffsetDataParserTest.java
  bundles/org.openhab.binding.knx/src/test/java/org/openhab/binding/knx/internal/dpt/DPTTest.java
  bundles/org.openhab.binding.mybmw/src/test/java/org/openhab/binding/mybmw/internal/dto/vehicle/VehicleStateContainerTest.java
Labels: test

#17740 [meteofrance] Documentation enhancements and more
  bundles/org.openhab.binding.meteofrance/README.md
  bundles/org.openhab.binding.meteofrance/src/main/java/org/openhab/binding/meteofrance/internal/db/DepartmentDbService.java
  bundles/org.openhab.binding.meteofrance/src/main/java/org/openhab/binding/meteofrance/internal/dto/MeteoFrance.java
  bundles/org.openhab.binding.meteofrance/src/main/java/org/openhab/binding/meteofrance/internal/handler/MeteoFranceBridgeHandler.java
  bundles/org.openhab.binding.meteofrance/src/main/java/org/openhab/binding/meteofrance/internal/handler/RainForecastHandler.java
Labels: bug

#17774 [linky] Thing goes OFFLINE once again
  bundles/org.openhab.binding.linky/src/main/java/org/openhab/binding/linky/internal/api/EnedisHttpApi.java
Labels: bug

#17770 [Onkyo] Set "CurrentURIMetaData" for "SetAVTransportURI" action (#17755)
  bundles/org.openhab.binding.onkyo/src/main/java/org/openhab/binding/onkyo/internal/handler/OnkyoAudioSink.java
  bundles/org.openhab.binding.onkyo/src/main/java/org/openhab/binding/onkyo/internal/handler/OnkyoUpnpHandler.java
  bundles/org.openhab.binding.onkyo/src/main/java/org/openhab/binding/onkyo/internal/handler/URIMetaDataProcessor.java
  bundles/org.openhab.binding.onkyo/src/test/java/org/openhab/binding/onkyo/internal/handler/URIMetaDataProcessorTest.java
Labels: bug

#17778 [govee] Improvements to color temperature channel
  bundles/org.openhab.binding.govee/src/main/resources/OH-INF/thing/thing-types.xml
Labels: enhancement

#17776 [avmfritz] Improvements to color temperature channel
  bundles/org.openhab.binding.avmfritz/src/main/resources/OH-INF/thing/channel-types.xml
Labels: enhancement

#17772 [hueemulation] Change uniqueid to make the earlier octets more unique to fix Alexa …
  bundles/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/ConfigStore.java
  bundles/org.openhab.io.hueemulation/src/test/java/org/openhab/io/hueemulation/internal/rest/ItemUIDtoHueIDMappingTests.java
Labels: bug

#17782 [solarman] Fix missing URL decoding in test
  bundles/org.openhab.binding.solarman/src/test/java/org/openhab/binding/solarman/internal/DefinitionParserTest.java
Labels: test

#15367 [metOfficeDataHub] Initial contribution
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.metofficedatahub/NOTICE
  bundles/org.openhab.binding.metofficedatahub/README.md
  bundles/org.openhab.binding.metofficedatahub/pom.xml
  bundles/org.openhab.binding.metofficedatahub/src/main/feature/feature.xml
  bundles/org.openhab.binding.metofficedatahub/src/main/java/org/openhab/binding/metofficedatahub/internal/MetOfficeDataHubBindingConstants.java
  bundles/org.openhab.binding.metofficedatahub/src/main/java/org/openhab/binding/metofficedatahub/internal/MetOfficeDataHubBridgeConfiguration.java
  bundles/org.openhab.binding.metofficedatahub/src/main/java/org/openhab/binding/metofficedatahub/internal/MetOfficeDataHubBridgeHandler.java
  bundles/org.openhab.binding.metofficedatahub/src/main/java/org/openhab/binding/metofficedatahub/internal/MetOfficeDataHubHandlerFactory.java
  bundles/org.openhab.binding.metofficedatahub/src/main/java/org/openhab/binding/metofficedatahub/internal/MetOfficeDataHubSiteConfiguration.java
  bundles/org.openhab.binding.metofficedatahub/src/main/java/org/openhab/binding/metofficedatahub/internal/MetOfficeDataHubSiteHandler.java
  bundles/org.openhab.binding.metofficedatahub/src/main/java/org/openhab/binding/metofficedatahub/internal/MetOfficeDelayedExecutor.java
  bundles/org.openhab.binding.metofficedatahub/src/main/java/org/openhab/binding/metofficedatahub/internal/PollManager.java
  bundles/org.openhab.binding.metofficedatahub/src/main/java/org/openhab/binding/metofficedatahub/internal/api/AuthTokenException.java
  bundles/org.openhab.binding.metofficedatahub/src/main/java/org/openhab/binding/metofficedatahub/internal/api/I18Exception.java
  bundles/org.openhab.binding.metofficedatahub/src/main/java/org/openhab/binding/metofficedatahub/internal/api/IConnectionStatusListener.java
  bundles/org.openhab.binding.metofficedatahub/src/main/java/org/openhab/binding/metofficedatahub/internal/api/IRateLimiterListener.java
  bundles/org.openhab.binding.metofficedatahub/src/main/java/org/openhab/binding/metofficedatahub/internal/api/ISiteResponseListener.java
  bundles/org.openhab.binding.metofficedatahub/src/main/java/org/openhab/binding/metofficedatahub/internal/api/JwtTokenHeader.java
  bundles/org.openhab.binding.metofficedatahub/src/main/java/org/openhab/binding/metofficedatahub/internal/api/JwtTokenPayload.java
  bundles/org.openhab.binding.metofficedatahub/src/main/java/org/openhab/binding/metofficedatahub/internal/api/LookupWrapper.java
  bundles/org.openhab.binding.metofficedatahub/src/main/java/org/openhab/binding/metofficedatahub/internal/api/RequestLimiter.java
  bundles/org.openhab.binding.metofficedatahub/src/main/java/org/openhab/binding/metofficedatahub/internal/api/ResponseDataProcessor.java
  bundles/org.openhab.binding.metofficedatahub/src/main/java/org/openhab/binding/metofficedatahub/internal/api/SiteApi.java
  bundles/org.openhab.binding.metofficedatahub/src/main/java/org/openhab/binding/metofficedatahub/internal/api/SiteApiAuthentication.java
  bundles/org.openhab.binding.metofficedatahub/src/main/java/org/openhab/binding/metofficedatahub/internal/dto/responses/SiteApiFeature.java
  bundles/org.openhab.binding.metofficedatahub/src/main/java/org/openhab/binding/metofficedatahub/internal/dto/responses/SiteApiFeatureCollection.java
  bundles/org.openhab.binding.metofficedatahub/src/main/java/org/openhab/binding/metofficedatahub/internal/dto/responses/SiteApiFeaturePoint.java
  bundles/org.openhab.binding.metofficedatahub/src/main/java/org/openhab/binding/metofficedatahub/internal/dto/responses/SiteApiFeatureProperties.java
  bundles/org.openhab.binding.metofficedatahub/src/main/java/org/openhab/binding/metofficedatahub/internal/dto/responses/SiteApiTimeSeries.java
  bundles/org.openhab.binding.metofficedatahub/src/main/java/org/openhab/binding/metofficedatahub/internal/dto/responses/SiteApiTypedResponseObject.java
  bundles/org.openhab.binding.metofficedatahub/src/main/resources/OH-INF/addon/addon.xml
  bundles/org.openhab.binding.metofficedatahub/src/main/resources/OH-INF/i18n/metofficedatahub.properties
  bundles/org.openhab.binding.metofficedatahub/src/main/resources/OH-INF/thing/channel-types.xml
  bundles/org.openhab.binding.metofficedatahub/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.metofficedatahub/src/main/test/org/openhab/binding/metofficedatahub/internal/api/SiteApiAuthenticationTest.java
  bundles/org.openhab.binding.metofficedatahub/src/main/test/org/openhab/binding/metofficedatahub/internal/dto/responses/2022-09-siteDailyResponse.json
  bundles/org.openhab.binding.metofficedatahub/src/main/test/org/openhab/binding/metofficedatahub/internal/dto/responses/2022-09-siteHourlyResponse.json
  bundles/org.openhab.binding.metofficedatahub/src/main/test/org/openhab/binding/metofficedatahub/internal/dto/responses/SiteApiFeatureCollectionTest.java
  bundles/pom.xml
Labels: new binding

#17784 [dbquery] Fix thing action annotation
  bundles/org.openhab.binding.dbquery/src/main/java/org/openhab/binding/dbquery/action/DBQueryActions.java
Labels: bug

#17761 [verisure] Fix broken cloud authentication
  bundles/org.openhab.binding.verisure/src/main/java/org/openhab/binding/verisure/internal/VerisureBindingConstants.java
  bundles/org.openhab.binding.verisure/src/main/java/org/openhab/binding/verisure/internal/VerisureSession.java
  bundles/org.openhab.binding.verisure/src/main/java/org/openhab/binding/verisure/internal/handler/VerisureSmartLockThingHandler.java
Labels: bug

#16329 [kermi] Initial contribution
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.modbus.kermi/README.md
  bundles/org.openhab.binding.modbus.kermi/pom.xml
  bundles/org.openhab.binding.modbus.kermi/src/main/java/org/openhab/binding/modbus/kermi/internal/KermiBindingConstants.java
  bundles/org.openhab.binding.modbus.kermi/src/main/java/org/openhab/binding/modbus/kermi/internal/KermiConfiguration.java
  bundles/org.openhab.binding.modbus.kermi/src/main/java/org/openhab/binding/modbus/kermi/internal/KermiHandlerFactory.java
  bundles/org.openhab.binding.modbus.kermi/src/main/java/org/openhab/binding/modbus/kermi/internal/dto/AlarmDTO.java
  bundles/org.openhab.binding.modbus.kermi/src/main/java/org/openhab/binding/modbus/kermi/internal/dto/ChargingCircuitDTO.java
  bundles/org.openhab.binding.modbus.kermi/src/main/java/org/openhab/binding/modbus/kermi/internal/dto/DataConverter.java
  bundles/org.openhab.binding.modbus.kermi/src/main/java/org/openhab/binding/modbus/kermi/internal/dto/EnergySourceDTO.java
  bundles/org.openhab.binding.modbus.kermi/src/main/java/org/openhab/binding/modbus/kermi/internal/dto/PowerDTO.java
  bundles/org.openhab.binding.modbus.kermi/src/main/java/org/openhab/binding/modbus/kermi/internal/dto/PvDTO.java
  bundles/org.openhab.binding.modbus.kermi/src/main/java/org/openhab/binding/modbus/kermi/internal/dto/StateDTO.java
  bundles/org.openhab.binding.modbus.kermi/src/main/java/org/openhab/binding/modbus/kermi/internal/dto/WorkHoursDTO.java
  bundles/org.openhab.binding.modbus.kermi/src/main/java/org/openhab/binding/modbus/kermi/internal/handler/KermiXcenterThingHandler.java
  bundles/org.openhab.binding.modbus.kermi/src/main/java/org/openhab/binding/modbus/kermi/internal/modbus/Data.java
  bundles/org.openhab.binding.modbus.kermi/src/main/java/org/openhab/binding/modbus/kermi/internal/modbus/KermiModbusConstans.java
  bundles/org.openhab.binding.modbus.kermi/src/main/java/org/openhab/binding/modbus/kermi/internal/modbus/Parser.java
  bundles/org.openhab.binding.modbus.kermi/src/main/resources/OH-INF/i18n/kermi.properties
  bundles/org.openhab.binding.modbus.kermi/src/main/resources/OH-INF/thing/bridge-kermi-xcenter.xml
  bundles/org.openhab.binding.modbus.kermi/src/main/resources/OH-INF/thing/xcenter-alarm-channel-groups.xml
  bundles/org.openhab.binding.modbus.kermi/src/main/resources/OH-INF/thing/xcenter-alarm-channel-types.xml
  bundles/org.openhab.binding.modbus.kermi/src/main/resources/OH-INF/thing/xcenter-charging-circuit-channel-groups.xml
  bundles/org.openhab.binding.modbus.kermi/src/main/resources/OH-INF/thing/xcenter-charging-circuit-channel-types.xml
  bundles/org.openhab.binding.modbus.kermi/src/main/resources/OH-INF/thing/xcenter-energy-source-channel-groups.xml
  bundles/org.openhab.binding.modbus.kermi/src/main/resources/OH-INF/thing/xcenter-energy-source-channel-types.xml
  bundles/org.openhab.binding.modbus.kermi/src/main/resources/OH-INF/thing/xcenter-power-channel-groups.xml
  bundles/org.openhab.binding.modbus.kermi/src/main/resources/OH-INF/thing/xcenter-power-channel-types.xml
  bundles/org.openhab.binding.modbus.kermi/src/main/resources/OH-INF/thing/xcenter-pv-modulation-channel-groups.xml
  bundles/org.openhab.binding.modbus.kermi/src/main/resources/OH-INF/thing/xcenter-pv-modulation-channel-types.xml
  bundles/org.openhab.binding.modbus.kermi/src/main/resources/OH-INF/thing/xcenter-state-channel-groups.xml
  bundles/org.openhab.binding.modbus.kermi/src/main/resources/OH-INF/thing/xcenter-state-channel-types.xml
  bundles/org.openhab.binding.modbus.kermi/src/main/resources/OH-INF/thing/xcenter-workhours-channel-groups.xml
  bundles/org.openhab.binding.modbus.kermi/src/main/resources/OH-INF/thing/xcenter-workhours-channel-types.xml
  bundles/org.openhab.binding.modbus.kermi/src/test/java/org/openhab/binding/modbus/kermi/internal/dto/StateDTOTest.java
  bundles/pom.xml
Labels: new binding

#17792 [homewizard] Fix `NumberFormatException`
  bundles/org.openhab.binding.homewizard/src/main/java/org/openhab/binding/homewizard/internal/dto/DataPayload.java
  bundles/org.openhab.binding.homewizard/src/test/java/org/openhab/binding/homewizard/internal/dto/P1PayloadTest.java
Labels: bug, regression

#17797 [knx] Readme: Troubleshooting, Logger, kBerry
  bundles/org.openhab.binding.knx/README.md
Labels: documentation

#17780 [tplinksmarthome] Improve color temperature channel
  bundles/org.openhab.binding.tplinksmarthome/README.md
  bundles/org.openhab.binding.tplinksmarthome/src/main/java/org/openhab/binding/tplinksmarthome/internal/TPLinkSmartHomeHandlerFactory.java
  bundles/org.openhab.binding.tplinksmarthome/src/main/java/org/openhab/binding/tplinksmarthome/internal/TPLinkStateDescriptionProvider.java
  bundles/org.openhab.binding.tplinksmarthome/src/main/java/org/openhab/binding/tplinksmarthome/internal/device/BulbDevice.java
  bundles/org.openhab.binding.tplinksmarthome/src/main/java/org/openhab/binding/tplinksmarthome/internal/handler/SmartHomeHandler.java
  bundles/org.openhab.binding.tplinksmarthome/src/main/resources/OH-INF/i18n/tplinksmarthome.properties
  bundles/org.openhab.binding.tplinksmarthome/src/main/resources/OH-INF/thing/KB130.xml
  bundles/org.openhab.binding.tplinksmarthome/src/main/resources/OH-INF/thing/KL120.xml
  bundles/org.openhab.binding.tplinksmarthome/src/main/resources/OH-INF/thing/KL125.xml
  bundles/org.openhab.binding.tplinksmarthome/src/main/resources/OH-INF/thing/KL130.xml
  bundles/org.openhab.binding.tplinksmarthome/src/main/resources/OH-INF/thing/KL135.xml
  bundles/org.openhab.binding.tplinksmarthome/src/main/resources/OH-INF/thing/KL400.xml
  bundles/org.openhab.binding.tplinksmarthome/src/main/resources/OH-INF/thing/KL430.xml
  bundles/org.openhab.binding.tplinksmarthome/src/main/resources/OH-INF/thing/LB120.xml
  bundles/org.openhab.binding.tplinksmarthome/src/main/resources/OH-INF/thing/LB130.xml
  bundles/org.openhab.binding.tplinksmarthome/src/main/resources/OH-INF/thing/LB230.xml
  bundles/org.openhab.binding.tplinksmarthome/src/main/resources/OH-INF/thing/channels.xml
  bundles/org.openhab.binding.tplinksmarthome/src/main/resources/OH-INF/update/instructions.xml
  bundles/org.openhab.binding.tplinksmarthome/src/test/java/org/openhab/binding/tplinksmarthome/internal/TPLinkSmartHomeHandlerFactoryTest.java
  bundles/org.openhab.binding.tplinksmarthome/src/test/java/org/openhab/binding/tplinksmarthome/internal/handler/SmartHomeHandlerTest.java
Labels: enhancement

#17779 [tapocontrol] Improve color temperature channel
  bundles/org.openhab.binding.tapocontrol/README.md
  bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/TapoControlHandlerFactory.java
  bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/TapoStateDescriptionProvider.java
  bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/constants/TapoThingConstants.java
  bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/devices/wifi/bulb/TapoBulbHandler.java
  bundles/org.openhab.binding.tapocontrol/src/main/resources/OH-INF/i18n/tapocontrol.properties
  bundles/org.openhab.binding.tapocontrol/src/main/resources/OH-INF/thing/L530.xml
  bundles/org.openhab.binding.tapocontrol/src/main/resources/OH-INF/thing/L630.xml
  bundles/org.openhab.binding.tapocontrol/src/main/resources/OH-INF/thing/channelgroups.xml
  bundles/org.openhab.binding.tapocontrol/src/main/resources/OH-INF/thing/channels.xml
  bundles/org.openhab.binding.tapocontrol/src/main/resources/OH-INF/update/instructions.xml
Labels: enhancement

#17777 [deconz] Improve color temperature channel
  bundles/org.openhab.binding.deconz/README.md
  bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/handler/LightThingHandler.java
  bundles/org.openhab.binding.deconz/src/main/resources/OH-INF/i18n/deconz.properties
  bundles/org.openhab.binding.deconz/src/main/resources/OH-INF/thing/group-thing-types.xml
  bundles/org.openhab.binding.deconz/src/main/resources/OH-INF/thing/light-thing-types.xml
  bundles/org.openhab.binding.deconz/src/main/resources/OH-INF/update/update.xml
Labels: enhancement

#17754 [amazonechocontrol] Improve color temperature channel
  bundles/org.openhab.binding.amazonechocontrol/README.md
  bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/smarthome/HandlerColorTemperatureController.java
  bundles/org.openhab.binding.amazonechocontrol/src/main/resources/OH-INF/i18n/amazonechocontrol.properties
  bundles/org.openhab.binding.amazonechocontrol/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.amazonechocontrol/src/main/resources/OH-INF/update/instructions.xml
Labels: enhancement

#17737 [plugwiseha] Add 5 boiler related channels
  bundles/org.openhab.binding.plugwiseha/README.md
  bundles/org.openhab.binding.plugwiseha/src/main/java/org/openhab/binding/plugwiseha/internal/PlugwiseHABindingConstants.java
  bundles/org.openhab.binding.plugwiseha/src/main/java/org/openhab/binding/plugwiseha/internal/api/model/dto/Appliance.java
  bundles/org.openhab.binding.plugwiseha/src/main/java/org/openhab/binding/plugwiseha/internal/api/model/dto/Appliances.java
  bundles/org.openhab.binding.plugwiseha/src/main/java/org/openhab/binding/plugwiseha/internal/api/model/dto/CumulativeLog.java
  bundles/org.openhab.binding.plugwiseha/src/main/java/org/openhab/binding/plugwiseha/internal/api/model/dto/CumulativeLogs.java
  bundles/org.openhab.binding.plugwiseha/src/main/java/org/openhab/binding/plugwiseha/internal/api/model/dto/Location.java
  bundles/org.openhab.binding.plugwiseha/src/main/java/org/openhab/binding/plugwiseha/internal/api/model/dto/Locations.java
  bundles/org.openhab.binding.plugwiseha/src/main/java/org/openhab/binding/plugwiseha/internal/api/model/dto/PointLog.java
  bundles/org.openhab.binding.plugwiseha/src/main/java/org/openhab/binding/plugwiseha/internal/api/model/dto/PointLogs.java
  bundles/org.openhab.binding.plugwiseha/src/main/java/org/openhab/binding/plugwiseha/internal/api/xml/PlugwiseHAXStream.java
  bundles/org.openhab.binding.plugwiseha/src/main/java/org/openhab/binding/plugwiseha/internal/handler/PlugwiseHAApplianceHandler.java
  bundles/org.openhab.binding.plugwiseha/src/main/resources/OH-INF/i18n/plugwiseha.properties
  bundles/org.openhab.binding.plugwiseha/src/main/resources/OH-INF/thing/channels.xml
  bundles/org.openhab.binding.plugwiseha/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.plugwiseha/src/main/resources/OH-INF/update/instructions.xml
  bundles/org.openhab.binding.plugwiseha/src/main/resources/domain_objects.xslt
Labels: enhancement

#17808 [hydrawise] Update documentation
  bundles/org.openhab.binding.hydrawise/README.md
Labels: documentation

#17795 [growatt] Enhance support for SPF inverters
  bundles/org.openhab.binding.growatt/README.md
  bundles/org.openhab.binding.growatt/src/main/java/org/openhab/binding/growatt/internal/GrowattBindingConstants.java
  bundles/org.openhab.binding.growatt/src/main/java/org/openhab/binding/growatt/internal/GrowattChannels.java
  bundles/org.openhab.binding.growatt/src/main/java/org/openhab/binding/growatt/internal/dto/GrottDevice.java
  bundles/org.openhab.binding.growatt/src/main/java/org/openhab/binding/growatt/internal/dto/GrottValues.java
  bundles/org.openhab.binding.growatt/src/main/java/org/openhab/binding/growatt/internal/handler/GrowattInverterHandler.java
  bundles/org.openhab.binding.growatt/src/main/resources/OH-INF/i18n/growatt.properties
  bundles/org.openhab.binding.growatt/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.growatt/src/main/resources/OH-INF/update/instructions.xml
  bundles/org.openhab.binding.growatt/src/test/java/org/openhab/binding/growatt/test/GrowattTest.java
  bundles/org.openhab.binding.growatt/src/test/resources/mid.json
  bundles/org.openhab.binding.growatt/src/test/resources/spf.json
Labels: enhancement

#17806 [irobot] Update documentation regarding button names
  bundles/org.openhab.binding.irobot/README.md
Labels: documentation

#17818 [metOfficeDataHub] Minor documentation Updates
  bundles/org.openhab.binding.metofficedatahub/README.md
Labels: documentation

#17810 [growatt] Enhancements for MID inverter and Smart Meter
  bundles/org.openhab.binding.growatt/README.md
  bundles/org.openhab.binding.growatt/src/main/java/org/openhab/binding/growatt/internal/GrowattChannels.java
  bundles/org.openhab.binding.growatt/src/main/java/org/openhab/binding/growatt/internal/dto/GrottValues.java
  bundles/org.openhab.binding.growatt/src/main/resources/OH-INF/i18n/growatt.properties
  bundles/org.openhab.binding.growatt/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.growatt/src/main/resources/OH-INF/update/instructions.xml
  bundles/org.openhab.binding.growatt/src/test/java/org/openhab/binding/growatt/test/GrowattTest.java
Labels: enhancement

#17822 Update bnd to 7.1.0
  itests/org.openhab.automation.groovyscripting.tests/itest.bndrun
  itests/org.openhab.automation.jsscriptingnashorn.tests/itest.bndrun
  itests/org.openhab.binding.astro.tests/itest.bndrun
  itests/org.openhab.binding.avmfritz.tests/itest.bndrun
  itests/org.openhab.binding.feed.tests/itest.bndrun
  itests/org.openhab.binding.hue.tests/itest.bndrun
  itests/org.openhab.binding.max.tests/itest.bndrun
  itests/org.openhab.binding.mielecloud.tests/itest.bndrun
  itests/org.openhab.binding.modbus.tests/itest.bndrun
  itests/org.openhab.binding.mqtt.homeassistant.tests/itest.bndrun
  itests/org.openhab.binding.mqtt.homie.tests/itest.bndrun
  itests/org.openhab.binding.mqtt.ruuvigateway.tests/itest.bndrun
  itests/org.openhab.binding.ntp.tests/itest.bndrun
  itests/org.openhab.binding.systeminfo.tests/itest.bndrun
  itests/org.openhab.binding.tradfri.tests/itest.bndrun
  itests/org.openhab.binding.wemo.tests/itest.bndrun
  itests/org.openhab.persistence.mapdb.tests/itest.bndrun
  pom.xml
Labels: infrastructure

#17824 [linky] Filter on dates when building the report requested from console
  bundles/org.openhab.binding.linky/src/main/java/org/openhab/binding/linky/internal/handler/LinkyHandler.java
Labels: bug

#17794 [freeboxos] Internationalize thing actions
  bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/action/ActivePlayerActions.java
  bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/action/CallActions.java
  bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/action/FreeplugActions.java
  bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/action/HostActions.java
  bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/action/PlayerActions.java
  bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/action/RepeaterActions.java
  bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/action/ServerActions.java
  bundles/org.openhab.binding.freeboxos/src/main/resources/OH-INF/i18n/freeboxos.properties
Labels: i18n

#17760 [ism8] Prevent sending for read-only channel types
  bundles/org.openhab.binding.ism8/src/main/java/org/openhab/binding/ism8/internal/Ism8Handler.java
  bundles/org.openhab.binding.ism8/src/main/resources/OH-INF/thing/thing-types.xml
Labels: enhancement

#17742 [ism8] Allow linking switch-r to Contact items
  bundles/org.openhab.binding.ism8/README.md
  bundles/org.openhab.binding.ism8/src/main/java/org/openhab/binding/ism8/internal/util/Ism8DomainMap.java
  bundles/org.openhab.binding.ism8/src/main/java/org/openhab/binding/ism8/server/DataPointBool.java
  bundles/org.openhab.binding.ism8/src/test/java/org/openhab/binding/ism8/internal/Ism8HandlerTest.java
  bundles/org.openhab.binding.ism8/src/test/java/org/openhab/binding/ism8/internal/util/Ism8DomainMapTest.java
Labels: enhancement
