Repository openhab/openhab-addons, pull requests merged in 2024-04, with the labels that each got.

#16510 [lutron] update instructions for LEAP authentication
  bundles/org.openhab.binding.lutron/doc/leapnotes.md
Labels: documentation

#16597 [upnpcontrol] Catch IAE when Album Art URI is invalid
  bundles/org.openhab.binding.upnpcontrol/src/main/java/org/openhab/binding/upnpcontrol/internal/handler/UpnpRendererHandler.java
Labels: bug

#16501 [boschshc] Add support for Dimmer
  bundles/org.openhab.binding.boschshc/README.md
  bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/devices/BoschSHCBindingConstants.java
  bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/devices/BoschSHCHandlerFactory.java
  bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/devices/lightcontrol/DimmerHandler.java
  bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/discovery/ThingDiscoveryService.java
  bundles/org.openhab.binding.boschshc/src/main/resources/OH-INF/i18n/boschshc.properties
  bundles/org.openhab.binding.boschshc/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/devices/lightcontrol/DimmerHandlerTest.java
Labels: enhancement

#16594 Allow for compiling with Java 21
  pom.xml
Labels: enhancement

#16531 [tado] Change humidity and heatingPower channels to QuantityType
  bundles/org.openhab.binding.tado/README.md
  bundles/org.openhab.binding.tado/src/main/java/org/openhab/binding/tado/internal/adapter/TadoZoneStateAdapter.java
  bundles/org.openhab.binding.tado/src/main/resources/OH-INF/i18n/tado.properties
  bundles/org.openhab.binding.tado/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.tado/src/main/resources/OH-INF/update/instructions.xml
Labels: enhancement

#15893 [mqtt.homie] build a per-thing thing type
  bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/MqttChannelStateDescriptionProvider.java
  bundles/org.openhab.binding.mqtt.homie/src/main/java/org/openhab/binding/mqtt/homie/generic/internal/MqttBindingConstants.java
  bundles/org.openhab.binding.mqtt.homie/src/main/java/org/openhab/binding/mqtt/homie/generic/internal/MqttThingHandlerFactory.java
  bundles/org.openhab.binding.mqtt.homie/src/main/java/org/openhab/binding/mqtt/homie/internal/handler/HomieThingHandler.java
  bundles/org.openhab.binding.mqtt.homie/src/main/java/org/openhab/binding/mqtt/homie/internal/homie300/Device.java
  bundles/org.openhab.binding.mqtt.homie/src/main/java/org/openhab/binding/mqtt/homie/internal/homie300/Node.java
  bundles/org.openhab.binding.mqtt.homie/src/main/java/org/openhab/binding/mqtt/homie/internal/homie300/Property.java
  bundles/org.openhab.binding.mqtt.homie/src/main/resources/OH-INF/config/homie-channel-config.xml
  bundles/org.openhab.binding.mqtt.homie/src/main/resources/OH-INF/thing/homie-channels.xml
  bundles/org.openhab.binding.mqtt.homie/src/test/java/org/openhab/binding/mqtt/homie/internal/handler/HomieThingHandlerTests.java
  itests/org.openhab.binding.mqtt.homie.tests/src/main/java/org/openhab/binding/mqtt/homie/HomieImplementationTest.java
Labels: enhancement

#16601 Update Cloud Connector installation procedure
  bundles/org.openhab.io.openhabcloud/README.md
Labels: documentation

#16604 [jdbc] Provide better MySQL datatype for `DateTimeType`
  bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/db/JdbcMysqlDAO.java
Labels: bug

#16436 [hue] Improve color setting
  bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/api/dto/clip2/Resource.java
  bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/api/dto/clip2/helper/Setters.java
Labels: bug

#16611 [Senec] Add request timeout
  bundles/org.openhab.binding.senechome/src/main/java/org/openhab/binding/senechome/internal/SenecHomeApi.java
Labels: bug

#16608 [miio] Add Roborock S7/S7MaxV mop mode
  bundles/org.openhab.binding.miio/README.base.md
  bundles/org.openhab.binding.miio/README.md
  bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/MiIoCommand.java
  bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/handler/MiIoVacuumHandler.java
  bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/robot/RobotCababilities.java
  bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/robot/StatusDTO.java
  bundles/org.openhab.binding.miio/src/main/resources/OH-INF/i18n/miio.properties
  bundles/org.openhab.binding.miio/src/main/resources/OH-INF/thing/vacuumThing.xml
Labels: enhancement

#16550 [lutron] Implement button press notifications for Picos from LEAP
  bundles/org.openhab.binding.lutron/README.md
  bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/handler/BaseKeypadHandler.java
  bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/handler/LeapBridgeHandler.java
  bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/handler/PicoKeypadHandler.java
  bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/protocol/leap/LeapMessageParser.java
  bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/protocol/leap/LeapMessageParserCallbacks.java
  bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/protocol/leap/Request.java
  bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/protocol/leap/dto/ButtonEvent.java
  bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/protocol/leap/dto/ButtonStatus.java
Labels: enhancement

#16619 [hue] Fix potential NPE when new battery devices are added to bridge
  bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/api/dto/clip2/Power.java
Labels: bug

#16618 [lifx] Add support for new LIFX products
  bundles/org.openhab.binding.lifx/README.md
  bundles/org.openhab.binding.lifx/src/main/java/org/openhab/binding/lifx/internal/LifxProduct.java
Labels: enhancement

#16616 [siemensrds] Remove r.H. from humidity state description pattern
  bundles/org.openhab.binding.siemensrds/src/main/resources/OH-INF/thing/thing-types.xml
Labels: enhancement

#16620 [intesis] Session Handling improved
  bundles/org.openhab.binding.intesis/src/main/java/org/openhab/binding/intesis/internal/handler/IntesisHomeHandler.java
Labels: bug, regression

#16621 [miele] Provide unit hint for water consumption channel
  bundles/org.openhab.binding.miele/src/main/resources/OH-INF/thing/channeltypes.xml
Labels: enhancement

#16507 [knx] Add JaCoCo test-coverage
  bundles/org.openhab.binding.knx/pom.xml
Labels: test

#16614 Provide unit hints for humidity/noise/volume channels
  bundles/org.openhab.binding.airq/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.airvisualnode/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.amazonechocontrol/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.ambientweather/src/main/resources/OH-INF/thing/channels.xml
  bundles/org.openhab.binding.avmfritz/src/main/resources/OH-INF/thing/channel-types.xml
  bundles/org.openhab.binding.bluetooth.airthings/src/main/resources/OH-INF/thing/airthings.xml
  bundles/org.openhab.binding.bluetooth.blukii/src/main/resources/OH-INF/thing/blukii.xml
  bundles/org.openhab.binding.bluetooth.ruuvitag/src/main/resources/OH-INF/thing/ruuvitag.xml
  bundles/org.openhab.binding.boschshc/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.bticinosmarther/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.daikin/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.deconz/src/main/resources/OH-INF/thing/sensor-channel-types.xml
  bundles/org.openhab.binding.draytonwiser/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.ecobee/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.electroluxair/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.fineoffsetweatherstation/src/main/resources/OH-INF/thing/gateway.xml
  bundles/org.openhab.binding.fmiweather/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.foobot/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.freeboxos/src/main/resources/OH-INF/thing/channel-types.xml
  bundles/org.openhab.binding.gardena/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.groheondus/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.ipobserver/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.jeelink/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.konnected/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.livisismarthome/src/main/resources/OH-INF/thing/channels.xml
  bundles/org.openhab.binding.mihome/src/main/resources/OH-INF/thing/channel.xml
  bundles/org.openhab.binding.modbus.helioseasycontrols/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.modbus.stiebeleltron/src/main/resources/OH-INF/thing/heatpump-channel-types.xml
  bundles/org.openhab.binding.mqtt.ruuvigateway/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.nest/src/main/resources/OH-INF/thing/sdm-channels.xml
  bundles/org.openhab.binding.netatmo/src/main/resources/OH-INF/thing/channels.xml
  bundles/org.openhab.binding.omnilink/src/main/resources/OH-INF/thing/humidity-sensor.xml
  bundles/org.openhab.binding.onewire/src/main/resources/OH-INF/thing/common.xml
  bundles/org.openhab.binding.openthermgateway/src/main/resources/OH-INF/thing/channels.xml
  bundles/org.openhab.binding.openweathermap/src/main/resources/OH-INF/thing/channel-types.xml
  bundles/org.openhab.binding.plugwise/src/main/resources/OH-INF/thing/channel.xml
  bundles/org.openhab.binding.radiothermostat/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.robonect/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.sensibo/src/main/resources/OH-INF/thing/channels.xml
  bundles/org.openhab.binding.sensorcommunity/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.shelly/src/main/resources/OH-INF/thing/shellyGen1_sensor.xml
  bundles/org.openhab.binding.siemensrds/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.somfytahoma/src/main/resources/OH-INF/thing/channels.xml
  bundles/org.openhab.binding.somneo/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.tellstick/src/main/resources/OH-INF/thing/sensor.xml
  bundles/org.openhab.binding.valloxmv/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.venstarthermostat/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.ventaair/src/main/resources/OH-INF/thing/channels.xml
  bundles/org.openhab.binding.verisure/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.vesync/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.weathercompany/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.weatherunderground/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.wundergroundupdatereceiver/src/main/resources/OH-INF/thing/channel-types.xml
  bundles/org.openhab.binding.yamahamusiccast/src/main/resources/OH-INF/thing/thing-types.xml
Labels: enhancement

#16637 [jrubyscripting] Fix an error in received_command example
  bundles/org.openhab.automation.jrubyscripting/README.md
Labels: documentation

#16623 [tibber] Add two channels: consumption and production for current hour
  bundles/org.openhab.binding.tibber/README.md
  bundles/org.openhab.binding.tibber/src/main/java/org/openhab/binding/tibber/internal/TibberBindingConstants.java
  bundles/org.openhab.binding.tibber/src/main/java/org/openhab/binding/tibber/internal/handler/TibberHandler.java
  bundles/org.openhab.binding.tibber/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.tibber/src/main/resources/OH-INF/update/instructions.xml
Labels: enhancement

#16631 [telegram] Functionality added to delete a Query
  bundles/org.openhab.binding.telegram/README.md
  bundles/org.openhab.binding.telegram/src/main/java/org/openhab/binding/telegram/internal/action/TelegramActions.java
Labels: enhancement

#16634 [energidataservice] Update tariff filter for Radius
  bundles/org.openhab.binding.energidataservice/src/main/java/org/openhab/binding/energidataservice/internal/api/DatahubTariffFilterFactory.java
Labels: enhancement

#16645 [deutschebahn] Fix example and update links
  bundles/org.openhab.binding.deutschebahn/README.md
Labels: documentation

#16643 [mybmw] Fix images not loading anymore
  bundles/org.openhab.binding.mybmw/README.md
  bundles/org.openhab.binding.mybmw/src/main/java/org/openhab/binding/mybmw/internal/utils/ImageProperties.java
  bundles/org.openhab.binding.mybmw/src/main/resources/OH-INF/i18n/mybmw.properties
  bundles/org.openhab.binding.mybmw/src/main/resources/OH-INF/thing/image-channel-types.xml
  bundles/org.openhab.binding.mybmw/src/main/resources/OH-INF/thing/thing-bev.xml
  bundles/org.openhab.binding.mybmw/src/main/resources/OH-INF/thing/thing-bev_rex.xml
  bundles/org.openhab.binding.mybmw/src/main/resources/OH-INF/thing/thing-conv.xml
  bundles/org.openhab.binding.mybmw/src/main/resources/OH-INF/thing/thing-phev.xml
  bundles/org.openhab.binding.mybmw/src/main/resources/OH-INF/update/thing-update.xml
Labels: bug

#16646 [harmonyhub] Fix NumberFormatException when selecting hue scene
  bundles/org.openhab.binding.harmonyhub/pom.xml
  bundles/org.openhab.binding.harmonyhub/src/main/java/org/openhab/binding/harmonyhub/internal/handler/HarmonyHubHandler.java
Labels: bug

#16644 [boschindego] Bypass WAF by using app user-agent
  bundles/org.openhab.binding.boschindego/src/main/java/org/openhab/binding/boschindego/internal/IndegoController.java
Labels: enhancement

#16636 [network] Fix NumberFormatException for ping when locale has comma as decimal separator
  bundles/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/utils/LatencyParser.java
Labels: bug

#16640 [netatmo] IllegalArgumentException for DoorTags
  bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/channelhelper/DoorTagChannelHelper.java
Labels: bug

#16651 [energidataservice] Improve error handling for action `calculatePrice`
  bundles/org.openhab.binding.energidataservice/README.md
  bundles/org.openhab.binding.energidataservice/src/main/java/org/openhab/binding/energidataservice/internal/action/EnergiDataServiceActions.java
  bundles/org.openhab.binding.energidataservice/src/test/java/org/openhab/binding/energidataservice/internal/action/EnergiDataServiceActionsTest.java
Labels: enhancement, (potentially) not backward compatible

#16650 [tr064] Enable fourth WiFi channel and improvements
  bundles/org.openhab.binding.tr064/README.md
  bundles/org.openhab.binding.tr064/src/main/resources/channels.xml
Labels: enhancement

#16649 [energidataservice] Restrict CO₂ emission datasets to price area DK1/DK2
  bundles/org.openhab.binding.energidataservice/README.md
  bundles/org.openhab.binding.energidataservice/src/main/java/org/openhab/binding/energidataservice/internal/ApiController.java
  bundles/org.openhab.binding.energidataservice/src/main/java/org/openhab/binding/energidataservice/internal/handler/EnergiDataServiceHandler.java
Labels: bug, regression

#16605 [openwebnet] Thermo: added support for HOLIDAY/VACATION central unit modes
  bundles/org.openhab.binding.openwebnet/README.md
  bundles/org.openhab.binding.openwebnet/pom.xml
  bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/OpenWebNetBindingConstants.java
  bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/handler/OpenWebNetThermoregulationHandler.java
  bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/i18n/openwebnet.properties
  bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/thing/BusThermoCentralUnit.xml
  bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/thing/channels.xml
  bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/update/update.xml
Labels: enhancement

#16630 [orbitbhyve] Fix handling of multiple sprinkler controllers
  bundles/org.openhab.binding.orbitbhyve/src/main/java/org/openhab/binding/orbitbhyve/internal/handler/OrbitBhyveBridgeHandler.java
  bundles/org.openhab.binding.orbitbhyve/src/main/java/org/openhab/binding/orbitbhyve/internal/handler/OrbitBhyveSprinklerHandler.java
Labels: bug

#16653 [energidataservice] Adjust retry policy for extended spot price unavailability
  bundles/org.openhab.binding.energidataservice/src/main/java/org/openhab/binding/energidataservice/internal/ApiController.java
  bundles/org.openhab.binding.energidataservice/src/main/java/org/openhab/binding/energidataservice/internal/handler/EnergiDataServiceHandler.java
  bundles/org.openhab.binding.energidataservice/src/main/java/org/openhab/binding/energidataservice/internal/retry/RetryPolicyFactory.java
Labels: bug

#16626 [openwebnet] Thermo: fix update zone setPoint when local offset is in use
  bundles/org.openhab.binding.openwebnet/README.md
  bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/handler/OpenWebNetThermoregulationHandler.java
Labels: bug

#16654 [energidataservice] Fix tariff time series when spot prices are unavailable
  bundles/org.openhab.binding.energidataservice/src/main/java/org/openhab/binding/energidataservice/internal/handler/EnergiDataServiceHandler.java
Labels: bug

#16383 [miio] add suppoprt Mijia Omni Robot Vacuum-Mop dreame.vacuum.p2114o
  bundles/org.openhab.binding.miio/README.md
  bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/MiIoDevices.java
  bundles/org.openhab.binding.miio/src/main/resources/OH-INF/i18n/basic.properties
  bundles/org.openhab.binding.miio/src/main/resources/database/dreame.vacuum.p2114o-miot.json
Labels: enhancement

#16652 [openwebnet] Thermo: new channels and README updates
  bundles/org.openhab.binding.openwebnet/README.md
  bundles/org.openhab.binding.openwebnet/doc/BTI_F411_2.jpg
  bundles/org.openhab.binding.openwebnet/doc/BTI_NT4695.jpg
  bundles/org.openhab.binding.openwebnet/doc/F454_gateway.png
  bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/OpenWebNetBindingConstants.java
  bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/handler/OpenWebNetThermoregulationHandler.java
  bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/i18n/openwebnet.properties
  bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/thing/BusThermoZone.xml
  bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/thing/channels.xml
  bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/update/update.xml
Labels: enhancement

#13703 [freeathomesystem] Initial contribution
  CODEOWNERS
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.freeathomesystem/NOTICE
  bundles/org.openhab.binding.freeathomesystem/README.md
  bundles/org.openhab.binding.freeathomesystem/pom.xml
  bundles/org.openhab.binding.freeathomesystem/src/main/feature/feature.xml
  bundles/org.openhab.binding.freeathomesystem/src/main/java/org/openhab/binding/freeathomesystem/internal/FreeAtHomeSystemBindingConstants.java
  bundles/org.openhab.binding.freeathomesystem/src/main/java/org/openhab/binding/freeathomesystem/internal/FreeAtHomeSystemDiscoveryService.java
  bundles/org.openhab.binding.freeathomesystem/src/main/java/org/openhab/binding/freeathomesystem/internal/FreeAtHomeSystemHandlerFactory.java
  bundles/org.openhab.binding.freeathomesystem/src/main/java/org/openhab/binding/freeathomesystem/internal/configuration/FreeAtHomeBridgeHandlerConfiguration.java
  bundles/org.openhab.binding.freeathomesystem/src/main/java/org/openhab/binding/freeathomesystem/internal/configuration/FreeAtHomeDeviceHandlerConfiguration.java
  bundles/org.openhab.binding.freeathomesystem/src/main/java/org/openhab/binding/freeathomesystem/internal/datamodel/FreeAtHomeDatapoint.java
  bundles/org.openhab.binding.freeathomesystem/src/main/java/org/openhab/binding/freeathomesystem/internal/datamodel/FreeAtHomeDatapointGroup.java
  bundles/org.openhab.binding.freeathomesystem/src/main/java/org/openhab/binding/freeathomesystem/internal/datamodel/FreeAtHomeDeviceChannel.java
  bundles/org.openhab.binding.freeathomesystem/src/main/java/org/openhab/binding/freeathomesystem/internal/datamodel/FreeAtHomeDeviceDescription.java
  bundles/org.openhab.binding.freeathomesystem/src/main/java/org/openhab/binding/freeathomesystem/internal/handler/FreeAtHomeBridgeHandler.java
  bundles/org.openhab.binding.freeathomesystem/src/main/java/org/openhab/binding/freeathomesystem/internal/handler/FreeAtHomeDeviceHandler.java
  bundles/org.openhab.binding.freeathomesystem/src/main/java/org/openhab/binding/freeathomesystem/internal/handler/FreeAtHomeDeviceStateListener.java
  bundles/org.openhab.binding.freeathomesystem/src/main/java/org/openhab/binding/freeathomesystem/internal/type/FreeAtHomeChannelTypeProvider.java
  bundles/org.openhab.binding.freeathomesystem/src/main/java/org/openhab/binding/freeathomesystem/internal/type/FreeAtHomeChannelTypeProviderImpl.java
  bundles/org.openhab.binding.freeathomesystem/src/main/java/org/openhab/binding/freeathomesystem/internal/type/FreeAtHomeThingTypeProvider.java
  bundles/org.openhab.binding.freeathomesystem/src/main/java/org/openhab/binding/freeathomesystem/internal/type/FreeAtHomeThingTypeProviderImpl.java
  bundles/org.openhab.binding.freeathomesystem/src/main/java/org/openhab/binding/freeathomesystem/internal/util/FidTranslationUtils.java
  bundles/org.openhab.binding.freeathomesystem/src/main/java/org/openhab/binding/freeathomesystem/internal/util/FreeAtHomeGeneralException.java
  bundles/org.openhab.binding.freeathomesystem/src/main/java/org/openhab/binding/freeathomesystem/internal/util/FreeAtHomeHttpCommunicationException.java
  bundles/org.openhab.binding.freeathomesystem/src/main/java/org/openhab/binding/freeathomesystem/internal/util/PIdContainerClass.java
  bundles/org.openhab.binding.freeathomesystem/src/main/java/org/openhab/binding/freeathomesystem/internal/util/PidTranslationUtils.java
  bundles/org.openhab.binding.freeathomesystem/src/main/java/org/openhab/binding/freeathomesystem/internal/util/UidUtils.java
  bundles/org.openhab.binding.freeathomesystem/src/main/java/org/openhab/binding/freeathomesystem/internal/valuestateconverter/BinaryValueStateConverter.java
  bundles/org.openhab.binding.freeathomesystem/src/main/java/org/openhab/binding/freeathomesystem/internal/valuestateconverter/BooleanValueStateConverter.java
  bundles/org.openhab.binding.freeathomesystem/src/main/java/org/openhab/binding/freeathomesystem/internal/valuestateconverter/DecimalValueStateConverter.java
  bundles/org.openhab.binding.freeathomesystem/src/main/java/org/openhab/binding/freeathomesystem/internal/valuestateconverter/ShuttercontrolValueStateConverter.java
  bundles/org.openhab.binding.freeathomesystem/src/main/java/org/openhab/binding/freeathomesystem/internal/valuestateconverter/ValueStateConverter.java
  bundles/org.openhab.binding.freeathomesystem/src/main/resources/OH-INF/addon/addon.xml
  bundles/org.openhab.binding.freeathomesystem/src/main/resources/OH-INF/i18n/freeathomesystem.properties
  bundles/org.openhab.binding.freeathomesystem/src/main/resources/OH-INF/thing/bridge-type.xml
  bundles/org.openhab.binding.freeathomesystem/src/main/resources/OH-INF/thing/thing-type.xml
  bundles/pom.xml
Labels: new binding

#16672 [CI] Add Java 21 compiling to J17 and native J21
  .github/workflows/ci-build.yml
Labels: infrastructure

#16675 [Renault] Fix retrieval of cockpit/odometer information
  bundles/org.openhab.binding.renault/src/main/java/org/openhab/binding/renault/internal/api/MyRenaultHttpSession.java
Labels: bug

#16680 [jdbc] Reduce the default character limit for `VARCHAR` columns in MySQL
  bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/db/JdbcMariadbDAO.java
  bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/db/JdbcMysqlDAO.java
Labels: bug

#16671 [openweathermap] Added "version" example to thing configuration and description.
  bundles/org.openhab.binding.openweathermap/README.md
Labels: documentation

#16656 [energidataservice] Introduce console command for history persistence
  bundles/org.openhab.binding.energidataservice/README.md
  bundles/org.openhab.binding.energidataservice/src/main/java/org/openhab/binding/energidataservice/internal/ApiController.java
  bundles/org.openhab.binding.energidataservice/src/main/java/org/openhab/binding/energidataservice/internal/EnergiDataServiceBindingConstants.java
  bundles/org.openhab.binding.energidataservice/src/main/java/org/openhab/binding/energidataservice/internal/PriceComponent.java
  bundles/org.openhab.binding.energidataservice/src/main/java/org/openhab/binding/energidataservice/internal/PriceListParser.java
  bundles/org.openhab.binding.energidataservice/src/main/java/org/openhab/binding/energidataservice/internal/action/EnergiDataServiceActions.java
  bundles/org.openhab.binding.energidataservice/src/main/java/org/openhab/binding/energidataservice/internal/api/DatahubTariffFilter.java
  bundles/org.openhab.binding.energidataservice/src/main/java/org/openhab/binding/energidataservice/internal/api/DateQueryParameter.java
  bundles/org.openhab.binding.energidataservice/src/main/java/org/openhab/binding/energidataservice/internal/console/EnergiDataServiceCommandExtension.java
  bundles/org.openhab.binding.energidataservice/src/main/java/org/openhab/binding/energidataservice/internal/handler/EnergiDataServiceHandler.java
  bundles/org.openhab.binding.energidataservice/src/test/java/org/openhab/binding/energidataservice/internal/PriceListParserTest.java
Labels: enhancement

#16689 [denonmarantz] Interrupt running job on handler disposal
  bundles/org.openhab.binding.denonmarantz/src/main/java/org/openhab/binding/denonmarantz/internal/DenonMarantzStateChangedListener.java
  bundles/org.openhab.binding.denonmarantz/src/main/java/org/openhab/binding/denonmarantz/internal/handler/DenonMarantzHandler.java
Labels: bug

#15894 [saicismart] Initial contribution
  CODEOWNERS
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.saicismart/NOTICE
  bundles/org.openhab.binding.saicismart/README.md
  bundles/org.openhab.binding.saicismart/pom.xml
  bundles/org.openhab.binding.saicismart/src/main/feature/feature.xml
  bundles/org.openhab.binding.saicismart/src/main/java/org/openhab/binding/saicismart/internal/ChargeStateUpdater.java
  bundles/org.openhab.binding.saicismart/src/main/java/org/openhab/binding/saicismart/internal/SAICiSMARTBindingConstants.java
  bundles/org.openhab.binding.saicismart/src/main/java/org/openhab/binding/saicismart/internal/SAICiSMARTBridgeConfiguration.java
  bundles/org.openhab.binding.saicismart/src/main/java/org/openhab/binding/saicismart/internal/SAICiSMARTBridgeHandler.java
  bundles/org.openhab.binding.saicismart/src/main/java/org/openhab/binding/saicismart/internal/SAICiSMARTHandler.java
  bundles/org.openhab.binding.saicismart/src/main/java/org/openhab/binding/saicismart/internal/SAICiSMARTHandlerFactory.java
  bundles/org.openhab.binding.saicismart/src/main/java/org/openhab/binding/saicismart/internal/SAICiSMARTVehicleConfiguration.java
  bundles/org.openhab.binding.saicismart/src/main/java/org/openhab/binding/saicismart/internal/VehicleDiscovery.java
  bundles/org.openhab.binding.saicismart/src/main/java/org/openhab/binding/saicismart/internal/VehicleStateUpdater.java
  bundles/org.openhab.binding.saicismart/src/main/java/org/openhab/binding/saicismart/internal/exceptions/ChargingStatusAPIException.java
  bundles/org.openhab.binding.saicismart/src/main/java/org/openhab/binding/saicismart/internal/exceptions/VehicleStatusAPIException.java
  bundles/org.openhab.binding.saicismart/src/main/resources/OH-INF/addon/addon.xml
  bundles/org.openhab.binding.saicismart/src/main/resources/OH-INF/config/bridge-config.xml
  bundles/org.openhab.binding.saicismart/src/main/resources/OH-INF/config/thing-config.xml
  bundles/org.openhab.binding.saicismart/src/main/resources/OH-INF/thing/bridge-ismart.xml
  bundles/org.openhab.binding.saicismart/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/pom.xml
Labels: new binding

#16691 [openwebnet] add sendMessage rule actions to send generic OWN messages on the BUS
  bundles/org.openhab.binding.openwebnet/README.md
  bundles/org.openhab.binding.openwebnet/pom.xml
  bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/actions/OpenWebNetBridgeActions.java
  bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/actions/OpenWebNetCENActions.java
  bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/handler/OpenWebNetBridgeHandler.java
  bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/handler/OpenWebNetThermoregulationHandler.java
  bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/serial/SerialPortAdapter.java
  bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/i18n/openwebnet.properties
Labels: enhancement

#16657 [mapdb] Explicitly set date format for serialization
  bundles/org.openhab.persistence.mapdb/src/main/java/org/openhab/persistence/mapdb/internal/MapDbPersistenceService.java
  bundles/org.openhab.persistence.mapdb/src/test/java/org/openhab/persistence/mapdb/StateTypeAdapterTest.java
Labels: bug

#16668 [denonmarantz] Update README.md
  bundles/org.openhab.binding.denonmarantz/README.md
Labels: documentation

#16693 [dynamodb] Optimize consumed read capacity
  bundles/org.openhab.persistence.dynamodb/README.md
  bundles/org.openhab.persistence.dynamodb/src/main/java/org/openhab/persistence/dynamodb/internal/DynamoDBQueryUtils.java
Labels: enhancement

#16695 [airq] Add note about JVM cryptographic strength policy
  bundles/org.openhab.binding.airq/README.md
Labels: documentation

#16559 [hue] Fix JUnit tests for revised ColorUtil
  bundles/org.openhab.binding.hue/src/test/java/org/openhab/binding/hue/internal/handler/HueLightHandlerTest.java
Labels: test

#16641 [mqtt] Treat incoming empty string as NULL for enum
  bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/values/TextValue.java
Labels: enhancement

#16694 [airq] Improve error handling
  bundles/org.openhab.binding.airq/src/main/java/org/openhab/binding/airq/internal/AirqEmptyResonseException.java
  bundles/org.openhab.binding.airq/src/main/java/org/openhab/binding/airq/internal/AirqException.java
  bundles/org.openhab.binding.airq/src/main/java/org/openhab/binding/airq/internal/AirqHandler.java
  bundles/org.openhab.binding.airq/src/main/java/org/openhab/binding/airq/internal/AirqPasswordIncorrectException.java
Labels: enhancement

#16687 [mybmw] revert the changes for 16642 as BMW seems to have reverted the changes in the API
  bundles/org.openhab.binding.mybmw/README.md
  bundles/org.openhab.binding.mybmw/src/main/java/org/openhab/binding/mybmw/internal/utils/ImageProperties.java
  bundles/org.openhab.binding.mybmw/src/main/resources/OH-INF/i18n/mybmw.properties
  bundles/org.openhab.binding.mybmw/src/main/resources/OH-INF/thing/image-channel-types.xml
  bundles/org.openhab.binding.mybmw/src/main/resources/OH-INF/thing/thing-bev.xml
  bundles/org.openhab.binding.mybmw/src/main/resources/OH-INF/thing/thing-bev_rex.xml
  bundles/org.openhab.binding.mybmw/src/main/resources/OH-INF/thing/thing-conv.xml
  bundles/org.openhab.binding.mybmw/src/main/resources/OH-INF/thing/thing-phev.xml
  bundles/org.openhab.binding.mybmw/src/main/resources/OH-INF/update/thing-update.xml
Labels: bug, regression

#15661 [velbus] New functionality and bug fix
  bundles/org.openhab.binding.velbus/README.md
  bundles/org.openhab.binding.velbus/src/main/java/org/openhab/binding/velbus/internal/VelbusBindingConstants.java
  bundles/org.openhab.binding.velbus/src/main/java/org/openhab/binding/velbus/internal/VelbusColorChannel.java
  bundles/org.openhab.binding.velbus/src/main/java/org/openhab/binding/velbus/internal/VelbusHandlerFactory.java
  bundles/org.openhab.binding.velbus/src/main/java/org/openhab/binding/velbus/internal/VelbusModuleAddress.java
  bundles/org.openhab.binding.velbus/src/main/java/org/openhab/binding/velbus/internal/VelbusPacketListener.java
  bundles/org.openhab.binding.velbus/src/main/java/org/openhab/binding/velbus/internal/VelbusVirtualColorChannel.java
  bundles/org.openhab.binding.velbus/src/main/java/org/openhab/binding/velbus/internal/discovery/VelbusThingDiscoveryService.java
  bundles/org.openhab.binding.velbus/src/main/java/org/openhab/binding/velbus/internal/handler/VelbusBlindsHandler.java
  bundles/org.openhab.binding.velbus/src/main/java/org/openhab/binding/velbus/internal/handler/VelbusBridgeHandler.java
  bundles/org.openhab.binding.velbus/src/main/java/org/openhab/binding/velbus/internal/handler/VelbusDimmerHandler.java
  bundles/org.openhab.binding.velbus/src/main/java/org/openhab/binding/velbus/internal/handler/VelbusRelayHandler.java
  bundles/org.openhab.binding.velbus/src/main/java/org/openhab/binding/velbus/internal/handler/VelbusRelayWithInputHandler.java
  bundles/org.openhab.binding.velbus/src/main/java/org/openhab/binding/velbus/internal/handler/VelbusSensorHandler.java
  bundles/org.openhab.binding.velbus/src/main/java/org/openhab/binding/velbus/internal/handler/VelbusSensorWithAlarmClockHandler.java
  bundles/org.openhab.binding.velbus/src/main/java/org/openhab/binding/velbus/internal/handler/VelbusTemperatureSensorHandler.java
  bundles/org.openhab.binding.velbus/src/main/java/org/openhab/binding/velbus/internal/handler/VelbusThermostatHandler.java
  bundles/org.openhab.binding.velbus/src/main/java/org/openhab/binding/velbus/internal/handler/VelbusThingHandler.java
  bundles/org.openhab.binding.velbus/src/main/java/org/openhab/binding/velbus/internal/handler/VelbusVMB4ANHandler.java
  bundles/org.openhab.binding.velbus/src/main/java/org/openhab/binding/velbus/internal/handler/VelbusVMB7INHandler.java
  bundles/org.openhab.binding.velbus/src/main/java/org/openhab/binding/velbus/internal/handler/VelbusVMBDALIHandler.java
  bundles/org.openhab.binding.velbus/src/main/java/org/openhab/binding/velbus/internal/handler/VelbusVMBELHandler.java
  bundles/org.openhab.binding.velbus/src/main/java/org/openhab/binding/velbus/internal/handler/VelbusVMBELOHandler.java
  bundles/org.openhab.binding.velbus/src/main/java/org/openhab/binding/velbus/internal/handler/VelbusVMBGPHandler.java
  bundles/org.openhab.binding.velbus/src/main/java/org/openhab/binding/velbus/internal/handler/VelbusVMBGPOHandler.java
  bundles/org.openhab.binding.velbus/src/main/java/org/openhab/binding/velbus/internal/handler/VelbusVMBMeteoHandler.java
  bundles/org.openhab.binding.velbus/src/main/java/org/openhab/binding/velbus/internal/handler/VelbusVMBPIROHandler.java
  bundles/org.openhab.binding.velbus/src/main/java/org/openhab/binding/velbus/internal/packets/VelbusDaliRequestPacket.java
  bundles/org.openhab.binding.velbus/src/main/java/org/openhab/binding/velbus/internal/packets/VelbusRelayPacket.java
  bundles/org.openhab.binding.velbus/src/main/java/org/openhab/binding/velbus/internal/packets/VelbusSetColorPacket.java
  bundles/org.openhab.binding.velbus/src/main/java/org/openhab/binding/velbus/internal/packets/VelbusSetDimPacket.java
  bundles/org.openhab.binding.velbus/src/main/java/org/openhab/binding/velbus/internal/packets/VelbusSetScenePacket.java
  bundles/org.openhab.binding.velbus/src/main/resources/OH-INF/config/config.xml
  bundles/org.openhab.binding.velbus/src/main/resources/OH-INF/i18n/velbus.properties
  bundles/org.openhab.binding.velbus/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.velbus/src/main/resources/OH-INF/update/instructions.xml
Labels: enhancement

#16681 [netatmo] Presence sub events were not updated
  bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/api/dto/Event.java
  bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/api/dto/HomeEvent.java
  bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/api/dto/Snapshot.java
  bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/capability/CameraCapability.java
  bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/capability/PersonCapability.java
  bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/channelhelper/EventCameraChannelHelper.java
  bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/channelhelper/EventChannelHelper.java
Labels: bug

#16700 [freeboxos] Handle null WifiInformation in Access Point Manager
  bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/api/rest/APManager.java
  bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/handler/WifiStationHandler.java
Labels: bug

#16679 [netatmo] Fix Live Picture not always available
  bundles/org.openhab.binding.netatmo/README.md
  bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/api/dto/WebhookEvent.java
  bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/capability/CameraCapability.java
  bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/channelhelper/CameraChannelHelper.java
  bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/utils/ChannelTypeUtils.java
Labels: bug

#16684 [netatmo] Correction of Last-Event group
  bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/channelhelper/EventChannelHelper.java
Labels: bug

#16703 [netatmo] Fix error introduced in #16681
  bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/capability/HomeSecurityThingCapability.java
  bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/channelhelper/EventCameraChannelHelper.java
Labels: bug, regression

#16692 [denonmarantz] Improve discovery
  bundles/org.openhab.binding.denonmarantz/src/main/feature/feature.xml
  bundles/org.openhab.binding.denonmarantz/src/main/java/org/openhab/binding/denonmarantz/internal/DenonMarantzBindingConstants.java
  bundles/org.openhab.binding.denonmarantz/src/main/java/org/openhab/binding/denonmarantz/internal/discovery/DenonMarantzMDNSDiscoveryParticipant.java
  bundles/org.openhab.binding.denonmarantz/src/main/java/org/openhab/binding/denonmarantz/internal/discovery/DenonMarantzUpnpDiscoveryParticipant.java
Labels: enhancement

#16706 [tivo] Add missing irCommand state options
  bundles/org.openhab.binding.tivo/src/main/resources/OH-INF/i18n/tivo.properties
  bundles/org.openhab.binding.tivo/src/main/resources/OH-INF/thing/thing-types.xml
Labels: enhancement

#16705 [openweathermap] Prepare for shutdown of One Call API version 2.5
  bundles/org.openhab.binding.openweathermap/README.md
  bundles/org.openhab.binding.openweathermap/src/main/resources/OH-INF/config/config.xml
  bundles/org.openhab.binding.openweathermap/src/main/resources/OH-INF/i18n/openweathermap.properties
Labels: documentation

#16254 [pulseaudio] Declare pulseaudio module per audio stream
  bundles/org.openhab.binding.pulseaudio/README.md
  bundles/org.openhab.binding.pulseaudio/src/main/java/org/openhab/binding/pulseaudio/internal/ConvertedInputStream.java
  bundles/org.openhab.binding.pulseaudio/src/main/java/org/openhab/binding/pulseaudio/internal/PulseAudioAudioSink.java
  bundles/org.openhab.binding.pulseaudio/src/main/java/org/openhab/binding/pulseaudio/internal/PulseAudioAudioSource.java
  bundles/org.openhab.binding.pulseaudio/src/main/java/org/openhab/binding/pulseaudio/internal/PulseaudioBindingConstants.java
  bundles/org.openhab.binding.pulseaudio/src/main/java/org/openhab/binding/pulseaudio/internal/PulseaudioClient.java
  bundles/org.openhab.binding.pulseaudio/src/main/java/org/openhab/binding/pulseaudio/internal/PulseaudioSimpleProtocolStream.java
  bundles/org.openhab.binding.pulseaudio/src/main/java/org/openhab/binding/pulseaudio/internal/cli/Parser.java
  bundles/org.openhab.binding.pulseaudio/src/main/java/org/openhab/binding/pulseaudio/internal/handler/PulseaudioHandler.java
  bundles/org.openhab.binding.pulseaudio/src/main/java/org/openhab/binding/pulseaudio/internal/items/Module.java
  bundles/org.openhab.binding.pulseaudio/src/main/java/org/openhab/binding/pulseaudio/internal/items/SimpleProtocolTCPModule.java
  bundles/org.openhab.binding.pulseaudio/src/main/resources/OH-INF/i18n/pulseaudio.properties
  bundles/org.openhab.binding.pulseaudio/src/main/resources/OH-INF/thing/sink.xml
  bundles/org.openhab.binding.pulseaudio/src/main/resources/OH-INF/thing/source.xml
Labels: enhancement
