Repository openhab/openhab-addons, pull requests merged in 2024-05, with the labels that each got.

#16696 [airq] Add Hydrogen Sulfide (H₂S)
  bundles/org.openhab.binding.airq/README.md
  bundles/org.openhab.binding.airq/src/main/java/org/openhab/binding/airq/internal/AirqHandler.java
  bundles/org.openhab.binding.airq/src/main/resources/OH-INF/i18n/airq.properties
  bundles/org.openhab.binding.airq/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.airq/src/main/resources/OH-INF/update/update.xml
Labels: enhancement

#16698 [airq] Add health/performance channels in percent, add UoM, refine unit hints and state patterns, make item labels consistent
  bundles/org.openhab.binding.airq/README.md
  bundles/org.openhab.binding.airq/src/main/java/org/openhab/binding/airq/internal/AirqHandler.java
  bundles/org.openhab.binding.airq/src/main/resources/OH-INF/i18n/airq.properties
  bundles/org.openhab.binding.airq/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.airq/src/main/resources/OH-INF/update/update.xml
Labels: enhancement

#16701 Add Buttongrid README examples
  bundles/org.openhab.binding.benqprojector/README.md
  bundles/org.openhab.binding.epsonprojector/README.md
  bundles/org.openhab.binding.oppo/README.md
  bundles/org.openhab.binding.panasonicbdp/README.md
  bundles/org.openhab.binding.roku/README.md
  bundles/org.openhab.binding.tivo/README.md
  bundles/org.openhab.binding.vizio/README.md
Labels: documentation

#16715 Fix maven-javadoc-plugin upgrade
  pom.xml
Labels: infrastructure, regression

#16721 [tivo] fix README
  bundles/org.openhab.binding.tivo/README.md
Labels: documentation, regression

#16720 [kaleidescape] Add Buttongrid example and command channel
  bundles/org.openhab.binding.kaleidescape/README.md
  bundles/org.openhab.binding.kaleidescape/src/main/java/org/openhab/binding/kaleidescape/internal/KaleidescapeBindingConstants.java
  bundles/org.openhab.binding.kaleidescape/src/main/java/org/openhab/binding/kaleidescape/internal/handler/KaleidescapeHandler.java
  bundles/org.openhab.binding.kaleidescape/src/main/resources/OH-INF/i18n/kaleidescape.properties
  bundles/org.openhab.binding.kaleidescape/src/main/resources/OH-INF/thing/channels.xml
  bundles/org.openhab.binding.kaleidescape/src/main/resources/OH-INF/update/instructions.xml
Labels: enhancement

#15478 [haywardomnilogic] Added support ColorLogic V2 Lights, Updated Chlor Enable, Alert, Error, Status
  bundles/org.openhab.binding.haywardomnilogic/README.md
  bundles/org.openhab.binding.haywardomnilogic/src/main/java/org/openhab/binding/haywardomnilogic/internal/HaywardBindingConstants.java
  bundles/org.openhab.binding.haywardomnilogic/src/main/java/org/openhab/binding/haywardomnilogic/internal/HaywardHandlerFactory.java
  bundles/org.openhab.binding.haywardomnilogic/src/main/java/org/openhab/binding/haywardomnilogic/internal/HaywardThingHandler.java
  bundles/org.openhab.binding.haywardomnilogic/src/main/java/org/openhab/binding/haywardomnilogic/internal/discovery/HaywardDiscoveryService.java
  bundles/org.openhab.binding.haywardomnilogic/src/main/java/org/openhab/binding/haywardomnilogic/internal/handler/HaywardBackyardHandler.java
  bundles/org.openhab.binding.haywardomnilogic/src/main/java/org/openhab/binding/haywardomnilogic/internal/handler/HaywardBowHandler.java
  bundles/org.openhab.binding.haywardomnilogic/src/main/java/org/openhab/binding/haywardomnilogic/internal/handler/HaywardChlorinatorHandler.java
  bundles/org.openhab.binding.haywardomnilogic/src/main/java/org/openhab/binding/haywardomnilogic/internal/handler/HaywardColorLogicHandler.java
  bundles/org.openhab.binding.haywardomnilogic/src/main/java/org/openhab/binding/haywardomnilogic/internal/handler/HaywardFilterHandler.java
  bundles/org.openhab.binding.haywardomnilogic/src/main/java/org/openhab/binding/haywardomnilogic/internal/handler/HaywardHeaterHandler.java
  bundles/org.openhab.binding.haywardomnilogic/src/main/java/org/openhab/binding/haywardomnilogic/internal/handler/HaywardPumpHandler.java
  bundles/org.openhab.binding.haywardomnilogic/src/main/java/org/openhab/binding/haywardomnilogic/internal/handler/HaywardRelayHandler.java
  bundles/org.openhab.binding.haywardomnilogic/src/main/java/org/openhab/binding/haywardomnilogic/internal/handler/HaywardVirtualHeaterHandler.java
  bundles/org.openhab.binding.haywardomnilogic/src/main/resources/OH-INF/i18n/haywardomnilogic.properties
  bundles/org.openhab.binding.haywardomnilogic/src/main/resources/OH-INF/thing/backyard.xml
  bundles/org.openhab.binding.haywardomnilogic/src/main/resources/OH-INF/thing/bow.xml
  bundles/org.openhab.binding.haywardomnilogic/src/main/resources/OH-INF/thing/bridge.xml
  bundles/org.openhab.binding.haywardomnilogic/src/main/resources/OH-INF/thing/chlorinator.xml
  bundles/org.openhab.binding.haywardomnilogic/src/main/resources/OH-INF/thing/colorlogic.xml
  bundles/org.openhab.binding.haywardomnilogic/src/main/resources/OH-INF/thing/filter.xml
  bundles/org.openhab.binding.haywardomnilogic/src/main/resources/OH-INF/thing/heater.xml
  bundles/org.openhab.binding.haywardomnilogic/src/main/resources/OH-INF/thing/pump.xml
  bundles/org.openhab.binding.haywardomnilogic/src/main/resources/OH-INF/thing/relay.xml
  bundles/org.openhab.binding.haywardomnilogic/src/main/resources/OH-INF/thing/virtualHeater.xml
  bundles/org.openhab.binding.haywardomnilogic/src/main/resources/OH-INF/update/instructions.xml
Labels: enhancement

#16714 [hue] Fix migration of API v1 legacy data to new v2 things
  bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/console/HueCommandExtension.java
  bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/discovery/Clip2ThingDiscoveryService.java
  bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/Clip2BridgeHandler.java
Labels: bug

#16725 [jeelink] Add support for emt7110 energy meter
  bundles/org.openhab.binding.jeelink/README.md
  bundles/org.openhab.binding.jeelink/src/main/java/org/openhab/binding/jeelink/internal/JeeLinkBindingConstants.java
  bundles/org.openhab.binding.jeelink/src/main/java/org/openhab/binding/jeelink/internal/SensorDefinition.java
  bundles/org.openhab.binding.jeelink/src/main/java/org/openhab/binding/jeelink/internal/config/EMT7110SensorConfig.java
  bundles/org.openhab.binding.jeelink/src/main/java/org/openhab/binding/jeelink/internal/emt7110/Emt7110Reading.java
  bundles/org.openhab.binding.jeelink/src/main/java/org/openhab/binding/jeelink/internal/emt7110/Emt7110ReadingConverter.java
  bundles/org.openhab.binding.jeelink/src/main/java/org/openhab/binding/jeelink/internal/emt7110/Emt7110SensorDefinition.java
  bundles/org.openhab.binding.jeelink/src/main/java/org/openhab/binding/jeelink/internal/emt7110/Emt7110SensorHandler.java
  bundles/org.openhab.binding.jeelink/src/main/resources/OH-INF/i18n/jeelink.properties
  bundles/org.openhab.binding.jeelink/src/main/resources/OH-INF/thing/thing-types.xml
Labels: enhancement

#14316 [onkyo] Add channel for changing the Audyssey EQ Mode
  bundles/org.openhab.binding.onkyo/README.md
  bundles/org.openhab.binding.onkyo/src/main/java/org/openhab/binding/onkyo/internal/OnkyoBindingConstants.java
  bundles/org.openhab.binding.onkyo/src/main/java/org/openhab/binding/onkyo/internal/eiscp/EiscpCommand.java
  bundles/org.openhab.binding.onkyo/src/main/java/org/openhab/binding/onkyo/internal/handler/OnkyoHandler.java
  bundles/org.openhab.binding.onkyo/src/main/resources/OH-INF/i18n/onkyo.properties
  bundles/org.openhab.binding.onkyo/src/main/resources/OH-INF/thing/channel-groups.xml
  bundles/org.openhab.binding.onkyo/src/main/resources/OH-INF/thing/channels.xml
  bundles/org.openhab.binding.onkyo/src/main/resources/OH-INF/update/instructions.xml
Labels: enhancement

#16584 [airgradient] Initial contribution
  CODEOWNERS
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.airgradient/NOTICE
  bundles/org.openhab.binding.airgradient/README.md
  bundles/org.openhab.binding.airgradient/doc/airgradient_sensors.png
  bundles/org.openhab.binding.airgradient/pom.xml
  bundles/org.openhab.binding.airgradient/src/main/feature/feature.xml
  bundles/org.openhab.binding.airgradient/src/main/java/org/openhab/binding/airgradient/internal/AirGradientBindingConstants.java
  bundles/org.openhab.binding.airgradient/src/main/java/org/openhab/binding/airgradient/internal/AirGradientHandlerFactory.java
  bundles/org.openhab.binding.airgradient/src/main/java/org/openhab/binding/airgradient/internal/communication/AirGradientCommunicationException.java
  bundles/org.openhab.binding.airgradient/src/main/java/org/openhab/binding/airgradient/internal/communication/JsonParserHelper.java
  bundles/org.openhab.binding.airgradient/src/main/java/org/openhab/binding/airgradient/internal/communication/PrometheusParserHelper.java
  bundles/org.openhab.binding.airgradient/src/main/java/org/openhab/binding/airgradient/internal/communication/RESTHelper.java
  bundles/org.openhab.binding.airgradient/src/main/java/org/openhab/binding/airgradient/internal/communication/RemoteAPIController.java
  bundles/org.openhab.binding.airgradient/src/main/java/org/openhab/binding/airgradient/internal/config/AirGradientAPIConfiguration.java
  bundles/org.openhab.binding.airgradient/src/main/java/org/openhab/binding/airgradient/internal/config/AirGradientLocationConfiguration.java
  bundles/org.openhab.binding.airgradient/src/main/java/org/openhab/binding/airgradient/internal/discovery/AirGradientLocationDiscoveryService.java
  bundles/org.openhab.binding.airgradient/src/main/java/org/openhab/binding/airgradient/internal/discovery/AirGradientMDNSDiscoveryParticipant.java
  bundles/org.openhab.binding.airgradient/src/main/java/org/openhab/binding/airgradient/internal/handler/AirGradientAPIHandler.java
  bundles/org.openhab.binding.airgradient/src/main/java/org/openhab/binding/airgradient/internal/handler/AirGradientLocalHandler.java
  bundles/org.openhab.binding.airgradient/src/main/java/org/openhab/binding/airgradient/internal/handler/AirGradientLocationHandler.java
  bundles/org.openhab.binding.airgradient/src/main/java/org/openhab/binding/airgradient/internal/handler/MeasureHelper.java
  bundles/org.openhab.binding.airgradient/src/main/java/org/openhab/binding/airgradient/internal/handler/PollEventListener.java
  bundles/org.openhab.binding.airgradient/src/main/java/org/openhab/binding/airgradient/internal/model/LedMode.java
  bundles/org.openhab.binding.airgradient/src/main/java/org/openhab/binding/airgradient/internal/model/Measure.java
  bundles/org.openhab.binding.airgradient/src/main/java/org/openhab/binding/airgradient/internal/prometheus/PrometheusMetric.java
  bundles/org.openhab.binding.airgradient/src/main/java/org/openhab/binding/airgradient/internal/prometheus/PrometheusTextParser.java
  bundles/org.openhab.binding.airgradient/src/main/resources/OH-INF/addon/addon.xml
  bundles/org.openhab.binding.airgradient/src/main/resources/OH-INF/i18n/airgradient.properties
  bundles/org.openhab.binding.airgradient/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.airgradient/src/test/java/org/openhab/binding/airgradient/internal/AirGradientHandlerFactoryTest.java
  bundles/org.openhab.binding.airgradient/src/test/java/org/openhab/binding/airgradient/internal/handler/AirGradientAPIHandlerTest.java
  bundles/org.openhab.binding.airgradient/src/test/java/org/openhab/binding/airgradient/internal/handler/AirGradientLocationHandlerTest.java
  bundles/org.openhab.binding.airgradient/src/test/java/org/openhab/binding/airgradient/internal/handler/RemoteApiControllerTest.java
  bundles/org.openhab.binding.airgradient/src/test/java/org/openhab/binding/airgradient/internal/prometheus/PrometheusMetricTest.java
  bundles/pom.xml
Labels: new binding

#16670 [serial] Update README.md
  bundles/org.openhab.binding.serial/README.md
Labels: documentation

#16704 [energidataservice] Introduce a trigger channel to announce the availability of day-ahead prices
  bundles/org.openhab.binding.energidataservice/README.md
  bundles/org.openhab.binding.energidataservice/src/main/java/org/openhab/binding/energidataservice/internal/EnergiDataServiceBindingConstants.java
  bundles/org.openhab.binding.energidataservice/src/main/java/org/openhab/binding/energidataservice/internal/handler/EnergiDataServiceHandler.java
  bundles/org.openhab.binding.energidataservice/src/main/resources/OH-INF/i18n/energidataservice.properties
  bundles/org.openhab.binding.energidataservice/src/main/resources/OH-INF/thing/channel-groups.xml
  bundles/org.openhab.binding.energidataservice/src/main/resources/OH-INF/thing/channel-types.xml
  bundles/org.openhab.binding.energidataservice/src/main/resources/OH-INF/thing/thing-service.xml
  bundles/org.openhab.binding.energidataservice/src/main/resources/OH-INF/update/instructions.xml
Labels: enhancement

#11718 [smaenergymeter] Fix handling of broadcast frames
  bundles/org.openhab.binding.smaenergymeter/README.md
  bundles/org.openhab.binding.smaenergymeter/src/main/java/org/openhab/binding/smaenergymeter/internal/SMAEnergyMeterHandlerFactory.java
  bundles/org.openhab.binding.smaenergymeter/src/main/java/org/openhab/binding/smaenergymeter/internal/configuration/EnergyMeterConfig.java
  bundles/org.openhab.binding.smaenergymeter/src/main/java/org/openhab/binding/smaenergymeter/internal/discovery/SMAEnergyMeterDiscoveryService.java
  bundles/org.openhab.binding.smaenergymeter/src/main/java/org/openhab/binding/smaenergymeter/internal/handler/EnergyMeter.java
  bundles/org.openhab.binding.smaenergymeter/src/main/java/org/openhab/binding/smaenergymeter/internal/handler/SMAEnergyMeterHandler.java
  bundles/org.openhab.binding.smaenergymeter/src/main/java/org/openhab/binding/smaenergymeter/internal/packet/DefaultPacketListenerRegistry.java
  bundles/org.openhab.binding.smaenergymeter/src/main/java/org/openhab/binding/smaenergymeter/internal/packet/PacketListener.java
  bundles/org.openhab.binding.smaenergymeter/src/main/java/org/openhab/binding/smaenergymeter/internal/packet/PacketListenerRegistry.java
  bundles/org.openhab.binding.smaenergymeter/src/main/java/org/openhab/binding/smaenergymeter/internal/packet/PayloadHandler.java
  bundles/org.openhab.binding.smaenergymeter/src/main/resources/OH-INF/i18n/smaenergymeter.properties
  bundles/org.openhab.binding.smaenergymeter/src/main/resources/OH-INF/thing/energyMeter.xml
Labels: bug, (potentially) not backward compatible

#16160 [transformation][exec] allow spaces in parameters by enclosing in single quotes
  bundles/org.openhab.transform.exec/README.md
  bundles/org.openhab.transform.exec/src/main/java/org/openhab/transform/exec/internal/ExecTransformationService.java
Labels: enhancement

#16743 [jablotron] Migrate to v2.2 API
  bundles/org.openhab.binding.jablotron/src/main/java/org/openhab/binding/jablotron/JablotronBindingConstants.java
  bundles/org.openhab.binding.jablotron/src/main/java/org/openhab/binding/jablotron/internal/handler/JablotronBridgeHandler.java
Labels: bug

#16663 [ipcamera] Fix Reolink Duo Floodlight whiteLED Channel
  bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/ReolinkHandler.java
Labels: bug

#16625 [shelly] Support for Shelly Plus HT Gen3
  bundles/org.openhab.binding.shelly/README.md
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/ShellyBindingConstants.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api/ShellyDeviceProfile.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api2/Shelly2ApiClient.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api2/Shelly2ApiRpc.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/discovery/ShellyDiscoveryParticipant.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/discovery/ShellyThingCreator.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/handler/ShellyBaseHandler.java
  bundles/org.openhab.binding.shelly/src/main/resources/OH-INF/i18n/shelly.properties
  bundles/org.openhab.binding.shelly/src/main/resources/OH-INF/thing/shellyGen2_sensor.xml
Labels: enhancement

#16744 [shelly] Enable use of analog input with Shelly Plus Add-on
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api2/Shelly2ApiClient.java
Labels: enhancement

#15921 [openwebnet] add support for lights general/area/group events and Things
  bundles/org.openhab.binding.openwebnet/README.md
  bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/OpenWebNetBindingConstants.java
  bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/OpenWebNetHandlerFactory.java
  bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/discovery/OpenWebNetDeviceDiscoveryService.java
  bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/handler/LightAutomHandlersMap.java
  bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/handler/OpenWebNetAlarmHandler.java
  bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/handler/OpenWebNetAutomationHandler.java
  bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/handler/OpenWebNetAuxiliaryHandler.java
  bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/handler/OpenWebNetBridgeHandler.java
  bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/handler/OpenWebNetEnergyHandler.java
  bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/handler/OpenWebNetGenericHandler.java
  bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/handler/OpenWebNetLightingGroupHandler.java
  bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/handler/OpenWebNetLightingHandler.java
  bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/handler/OpenWebNetScenarioBasicHandler.java
  bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/handler/OpenWebNetScenarioHandler.java
  bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/handler/OpenWebNetThermoregulationHandler.java
  bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/handler/OpenWebNetThingHandler.java
  bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/i18n/openwebnet.properties
  bundles/org.openhab.binding.openwebnet/src/main/resources/OH-INF/thing/BusLightGroup.xml
  bundles/org.openhab.binding.openwebnet/src/test/java/org/openhab/binding/openwebnet/internal/handler/OwnIdTest.java
Labels: enhancement

#16277 [danfossairunit] Add support for suggestion finder
  bundles/org.openhab.binding.danfossairunit/src/main/resources/OH-INF/addon/addon.xml
Labels: enhancement

#16762 Fix build
  bom/openhab-addons/pom.xml
Labels: critical

#16759 [denonmarantz] Add UoM support for volume dB channels
  bundles/org.openhab.binding.denonmarantz/README.md
  bundles/org.openhab.binding.denonmarantz/src/main/java/org/openhab/binding/denonmarantz/internal/DenonMarantzState.java
  bundles/org.openhab.binding.denonmarantz/src/main/java/org/openhab/binding/denonmarantz/internal/connector/DenonMarantzConnector.java
  bundles/org.openhab.binding.denonmarantz/src/main/java/org/openhab/binding/denonmarantz/internal/xml/adapters/VolumeAdapter.java
  bundles/org.openhab.binding.denonmarantz/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.denonmarantz/src/main/resources/OH-INF/update/instructions.xml
Labels: enhancement

#16767 [denonmarantz] Improve README
  bundles/org.openhab.binding.denonmarantz/README.md
Labels: documentation

#16769 [deconz] Fix color conversion
  bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/handler/LightThingHandler.java
Labels: bug

#16739 [dsmr] Fix delivery demand labels
  bundles/org.openhab.binding.dsmr/src/main/resources/OH-INF/i18n/dsmr.properties
  bundles/org.openhab.binding.dsmr/src/main/resources/OH-INF/thing/channeltypes_electricity.xml
  bundles/org.openhab.binding.dsmr/src/main/resources/OH-INF/thing/meter_device_emucs_v1_0.xml
  bundles/org.openhab.binding.dsmr/src/main/resources/OH-INF/thing/meter_electricity_emucs_v1_0.xml
  bundles/org.openhab.binding.dsmr/src/main/resources/OH-INF/update/instructions.xml
Labels: bug, regression

#16664 [gridbox] Initial contribution
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.gridbox/NOTICE
  bundles/org.openhab.binding.gridbox/README.md
  bundles/org.openhab.binding.gridbox/pom.xml
  bundles/org.openhab.binding.gridbox/src/main/feature/feature.xml
  bundles/org.openhab.binding.gridbox/src/main/java/org/openhab/binding/gridbox/internal/GridBoxBindingConstants.java
  bundles/org.openhab.binding.gridbox/src/main/java/org/openhab/binding/gridbox/internal/GridBoxConfiguration.java
  bundles/org.openhab.binding.gridbox/src/main/java/org/openhab/binding/gridbox/internal/GridBoxHandler.java
  bundles/org.openhab.binding.gridbox/src/main/java/org/openhab/binding/gridbox/internal/GridBoxHandlerFactory.java
  bundles/org.openhab.binding.gridbox/src/main/java/org/openhab/binding/gridbox/internal/api/GridBoxApi.java
  bundles/org.openhab.binding.gridbox/src/main/java/org/openhab/binding/gridbox/internal/model/Battery.java
  bundles/org.openhab.binding.gridbox/src/main/java/org/openhab/binding/gridbox/internal/model/BatterySummary.java
  bundles/org.openhab.binding.gridbox/src/main/java/org/openhab/binding/gridbox/internal/model/EvChargingStation.java
  bundles/org.openhab.binding.gridbox/src/main/java/org/openhab/binding/gridbox/internal/model/EvChargingStationSummary.java
  bundles/org.openhab.binding.gridbox/src/main/java/org/openhab/binding/gridbox/internal/model/HeatPump.java
  bundles/org.openhab.binding.gridbox/src/main/java/org/openhab/binding/gridbox/internal/model/LiveData.java
  bundles/org.openhab.binding.gridbox/src/main/resources/OH-INF/addon/addon.xml
  bundles/org.openhab.binding.gridbox/src/main/resources/OH-INF/i18n/gridbox.properties
  bundles/org.openhab.binding.gridbox/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.gridbox/src/test/java/org/openhab/binding/gridbox/GridBoxApiTest.java
  bundles/pom.xml
Labels: new binding

#16751 [somfytahoma] force the gateway discovery if the LAN mode is not working
  bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/handler/SomfyTahomaBridgeHandler.java
Labels: bug

#16775 [ipcamera] Add new AI object detection alarms for Foscam cameras
  bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/FoscamHandler.java
  bundles/org.openhab.binding.ipcamera/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.ipcamera/src/main/resources/OH-INF/update/instructions.xml
Labels: enhancement

#16676 Upgrade Karaf from 4.4.5 to 4.4.6
  bundles/org.openhab.binding.http/pom.xml
  bundles/org.openhab.persistence.dynamodb/pom.xml
  itests/org.openhab.automation.groovyscripting.tests/itest.bndrun
  itests/org.openhab.automation.jsscriptingnashorn.tests/itest.bndrun
  itests/org.openhab.binding.astro.tests/itest.bndrun
  itests/org.openhab.binding.avmfritz.tests/itest.bndrun
  itests/org.openhab.binding.feed.tests/itest.bndrun
  itests/org.openhab.binding.hue.tests/itest.bndrun
  itests/org.openhab.binding.max.tests/itest.bndrun
  itests/org.openhab.binding.mielecloud.tests/itest.bndrun
  itests/org.openhab.binding.modbus.tests/itest.bndrun
  itests/org.openhab.binding.mqtt.homeassistant.tests/itest.bndrun
  itests/org.openhab.binding.mqtt.homie.tests/itest.bndrun
  itests/org.openhab.binding.mqtt.ruuvigateway.tests/itest.bndrun
  itests/org.openhab.binding.ntp.tests/itest.bndrun
  itests/org.openhab.binding.systeminfo.tests/itest.bndrun
  itests/org.openhab.binding.tradfri.tests/itest.bndrun
  itests/org.openhab.binding.wemo.tests/itest.bndrun
  itests/org.openhab.persistence.mapdb.tests/itest.bndrun
  pom.xml
Labels: security, infrastructure

#16780 [homeconnect] Remove duplicate warning
  bundles/org.openhab.binding.homeconnect/README.md
Labels: documentation

#16504 [PJLinkDevice] audio/video mute
  bundles/org.openhab.binding.pjlinkdevice/src/main/java/org/openhab/binding/pjlinkdevice/internal/PJLinkDeviceBindingConstants.java
  bundles/org.openhab.binding.pjlinkdevice/src/main/java/org/openhab/binding/pjlinkdevice/internal/PJLinkDeviceHandler.java
  bundles/org.openhab.binding.pjlinkdevice/src/main/java/org/openhab/binding/pjlinkdevice/internal/device/command/mute/MuteQueryResponse.java
  bundles/org.openhab.binding.pjlinkdevice/src/main/resources/OH-INF/i18n/pjLinkDevice.properties
  bundles/org.openhab.binding.pjlinkdevice/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.pjlinkdevice/src/main/resources/OH-INF/update/instructions.xml
Labels: enhancement

#11895 [samsungtv] Frame TV Fixes, Improvements and New Channels
  bundles/org.openhab.binding.samsungtv/NOTICE
  bundles/org.openhab.binding.samsungtv/README.md
  bundles/org.openhab.binding.samsungtv/pom.xml
  bundles/org.openhab.binding.samsungtv/src/main/feature/feature.xml
  bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/SamsungTvAppWatchService.java
  bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/SamsungTvBindingConstants.java
  bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/SamsungTvHandlerFactory.java
  bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/SamsungTvTlsTrustManagerProvider.java
  bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/Utils.java
  bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/WakeOnLanUtility.java
  bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/WolSend.java
  bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/config/SamsungTvConfiguration.java
  bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/discovery/SamsungTvDiscoveryParticipant.java
  bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/handler/SamsungTvHandler.java
  bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/protocol/KeyCode.java
  bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/protocol/KnownAppId.java
  bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/protocol/RemoteController.java
  bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/protocol/RemoteControllerException.java
  bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/protocol/RemoteControllerLegacy.java
  bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/protocol/RemoteControllerWebSocket.java
  bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/protocol/RemoteControllerWebsocketCallback.java
  bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/protocol/WebSocketArt.java
  bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/protocol/WebSocketBase.java
  bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/protocol/WebSocketRemote.java
  bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/protocol/WebSocketV2.java
  bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/service/DataConverters.java
  bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/service/MainTVServerService.java
  bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/service/MediaRendererService.java
  bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/service/RemoteControllerService.java
  bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/service/SamsungTvUtils.java
  bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/service/ServiceFactory.java
  bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/service/SmartThingsApiService.java
  bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/service/api/EventListener.java
  bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/service/api/SamsungTvService.java
  bundles/org.openhab.binding.samsungtv/src/main/resources/OH-INF/addon/addon.xml
  bundles/org.openhab.binding.samsungtv/src/main/resources/OH-INF/config/config.xml
  bundles/org.openhab.binding.samsungtv/src/main/resources/OH-INF/i18n/samsungtv.properties
  bundles/org.openhab.binding.samsungtv/src/main/resources/OH-INF/i18n/samsungtv_de.properties
  bundles/org.openhab.binding.samsungtv/src/main/resources/OH-INF/i18n/samsungtv_hu.properties
  bundles/org.openhab.binding.samsungtv/src/main/resources/OH-INF/i18n/samsungtv_it.properties
  bundles/org.openhab.binding.samsungtv/src/main/resources/OH-INF/thing/channel-types.xml
  bundles/org.openhab.binding.samsungtv/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.samsungtv/src/main/resources/OH-INF/update/instructions.xml
Labels: enhancement

#16713 [French Govt Energy Data] New binding
  CODEOWNERS
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.frenchgovtenergydata/NOTICE
  bundles/org.openhab.binding.frenchgovtenergydata/README.md
  bundles/org.openhab.binding.frenchgovtenergydata/pom.xml
  bundles/org.openhab.binding.frenchgovtenergydata/src/main/feature/feature.xml
  bundles/org.openhab.binding.frenchgovtenergydata/src/main/java/org/openhab/binding/frenchgovtenergydata/internal/FrenchGovtEnergyDataBindingConstants.java
  bundles/org.openhab.binding.frenchgovtenergydata/src/main/java/org/openhab/binding/frenchgovtenergydata/internal/FrenchGovtEnergyDataHandlerFactory.java
  bundles/org.openhab.binding.frenchgovtenergydata/src/main/java/org/openhab/binding/frenchgovtenergydata/internal/dto/BaseTariff.java
  bundles/org.openhab.binding.frenchgovtenergydata/src/main/java/org/openhab/binding/frenchgovtenergydata/internal/dto/HpHcTariff.java
  bundles/org.openhab.binding.frenchgovtenergydata/src/main/java/org/openhab/binding/frenchgovtenergydata/internal/dto/Tariff.java
  bundles/org.openhab.binding.frenchgovtenergydata/src/main/java/org/openhab/binding/frenchgovtenergydata/internal/handler/BaseTariffHandler.java
  bundles/org.openhab.binding.frenchgovtenergydata/src/main/java/org/openhab/binding/frenchgovtenergydata/internal/handler/HpHcTariffHandler.java
  bundles/org.openhab.binding.frenchgovtenergydata/src/main/java/org/openhab/binding/frenchgovtenergydata/internal/handler/TariffHandler.java
  bundles/org.openhab.binding.frenchgovtenergydata/src/main/resources/OH-INF/addon/addon.xml
  bundles/org.openhab.binding.frenchgovtenergydata/src/main/resources/OH-INF/i18n/frenchgovtenergydata.properties
  bundles/org.openhab.binding.frenchgovtenergydata/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/pom.xml
Labels: new binding

#16787 [samsungtv] Fix `IllegalStateException` on sourceName command
  bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/service/MainTVServerService.java
Labels: bug, additional testing preferred, regression

#16768 [radiothermostat] Add discovery-methods
  bundles/org.openhab.binding.radiothermostat/src/main/resources/OH-INF/addon/addon.xml
Labels: enhancement

#16792 [freeboxos] FreeboxOsIconProvider should only provide icons for its own icon set
  bundles/org.openhab.binding.freeboxos/pom.xml
  bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/FreeboxOsIconProvider.java
  bundles/org.openhab.binding.freeboxos/src/main/resources/OH-INF/i18n/freeboxos.properties
Labels: bug

#16799 [solarforecast] Fix documentation typo
  bundles/org.openhab.binding.solarforecast/README.md
Labels: documentation

#16801 [snmp] Upgrade SNMP4J and fix AUTH_NO_PRIV
  bundles/org.openhab.binding.snmp/pom.xml
  bundles/org.openhab.binding.snmp/src/main/java/org/openhab/binding/snmp/internal/SnmpServiceImpl.java
Labels: bug

#16800 [denonmarantz] Provide channels icons and semantic tags
  bundles/org.openhab.binding.denonmarantz/src/main/resources/OH-INF/i18n/denonmarantz.properties
  bundles/org.openhab.binding.denonmarantz/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.denonmarantz/src/main/resources/OH-INF/update/instructions.xml
Labels: enhancement

#16748 [denonmarantz] Add HTTP protocol support for newer receivers
  bundles/org.openhab.binding.denonmarantz/README.md
  bundles/org.openhab.binding.denonmarantz/src/main/java/org/openhab/binding/denonmarantz/internal/connector/http/DenonMarantzHttpConnector.java
  bundles/org.openhab.binding.denonmarantz/src/main/java/org/openhab/binding/denonmarantz/internal/exception/HttpCommunicationException.java
  bundles/org.openhab.binding.denonmarantz/src/main/java/org/openhab/binding/denonmarantz/internal/handler/DenonMarantzHandler.java
  bundles/org.openhab.binding.denonmarantz/src/main/java/org/openhab/binding/denonmarantz/internal/xml/dto/commands/CommandRx.java
Labels: enhancement

#16781 [androidtv] Upgrade Bouncy Castle to 1.78
  bundles/org.openhab.binding.androidtv/pom.xml
Labels: security

#16628 [Ephemeris] Binding to make the bridge with core Ephemeris functions
  CODEOWNERS
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.ephemeris/NOTICE
  bundles/org.openhab.binding.ephemeris/README.md
  bundles/org.openhab.binding.ephemeris/pom.xml
  bundles/org.openhab.binding.ephemeris/src/main/feature/feature.xml
  bundles/org.openhab.binding.ephemeris/src/main/java/org/openhab/binding/ephemeris/internal/EphemerisBindingConstants.java
  bundles/org.openhab.binding.ephemeris/src/main/java/org/openhab/binding/ephemeris/internal/EphemerisException.java
  bundles/org.openhab.binding.ephemeris/src/main/java/org/openhab/binding/ephemeris/internal/EphemerisHandlerFactory.java
  bundles/org.openhab.binding.ephemeris/src/main/java/org/openhab/binding/ephemeris/internal/configuration/DaysetConfiguration.java
  bundles/org.openhab.binding.ephemeris/src/main/java/org/openhab/binding/ephemeris/internal/configuration/FileConfiguration.java
  bundles/org.openhab.binding.ephemeris/src/main/java/org/openhab/binding/ephemeris/internal/discovery/EphemerisDiscoveryService.java
  bundles/org.openhab.binding.ephemeris/src/main/java/org/openhab/binding/ephemeris/internal/handler/BaseEphemerisHandler.java
  bundles/org.openhab.binding.ephemeris/src/main/java/org/openhab/binding/ephemeris/internal/handler/CustomHandler.java
  bundles/org.openhab.binding.ephemeris/src/main/java/org/openhab/binding/ephemeris/internal/handler/DaysetHandler.java
  bundles/org.openhab.binding.ephemeris/src/main/java/org/openhab/binding/ephemeris/internal/handler/HolidayHandler.java
  bundles/org.openhab.binding.ephemeris/src/main/java/org/openhab/binding/ephemeris/internal/handler/JollydayHandler.java
  bundles/org.openhab.binding.ephemeris/src/main/java/org/openhab/binding/ephemeris/internal/handler/WeekendHandler.java
  bundles/org.openhab.binding.ephemeris/src/main/java/org/openhab/binding/ephemeris/internal/providers/EphemerisDescriptionProvider.java
  bundles/org.openhab.binding.ephemeris/src/main/resources/OH-INF/addon/addon.xml
  bundles/org.openhab.binding.ephemeris/src/main/resources/OH-INF/i18n/ephemeris.properties
  bundles/org.openhab.binding.ephemeris/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/pom.xml
Labels: new binding

#16065 [salus] Initial contribution
  CODEOWNERS
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.salus/NOTICE
  bundles/org.openhab.binding.salus/README.md
  bundles/org.openhab.binding.salus/pom.xml
  bundles/org.openhab.binding.salus/src/main/feature/feature.xml
  bundles/org.openhab.binding.salus/src/main/java/org/openhab/binding/salus/internal/SalusBindingConstants.java
  bundles/org.openhab.binding.salus/src/main/java/org/openhab/binding/salus/internal/SalusHandlerFactory.java
  bundles/org.openhab.binding.salus/src/main/java/org/openhab/binding/salus/internal/discovery/CloudDiscovery.java
  bundles/org.openhab.binding.salus/src/main/java/org/openhab/binding/salus/internal/handler/CloudApi.java
  bundles/org.openhab.binding.salus/src/main/java/org/openhab/binding/salus/internal/handler/CloudBridgeConfig.java
  bundles/org.openhab.binding.salus/src/main/java/org/openhab/binding/salus/internal/handler/CloudBridgeHandler.java
  bundles/org.openhab.binding.salus/src/main/java/org/openhab/binding/salus/internal/handler/DeviceHandler.java
  bundles/org.openhab.binding.salus/src/main/java/org/openhab/binding/salus/internal/handler/It600Handler.java
  bundles/org.openhab.binding.salus/src/main/java/org/openhab/binding/salus/internal/rest/AuthToken.java
  bundles/org.openhab.binding.salus/src/main/java/org/openhab/binding/salus/internal/rest/Device.java
  bundles/org.openhab.binding.salus/src/main/java/org/openhab/binding/salus/internal/rest/DeviceProperty.java
  bundles/org.openhab.binding.salus/src/main/java/org/openhab/binding/salus/internal/rest/GsonMapper.java
  bundles/org.openhab.binding.salus/src/main/java/org/openhab/binding/salus/internal/rest/HttpClient.java
  bundles/org.openhab.binding.salus/src/main/java/org/openhab/binding/salus/internal/rest/HttpSalusApiException.java
  bundles/org.openhab.binding.salus/src/main/java/org/openhab/binding/salus/internal/rest/RestClient.java
  bundles/org.openhab.binding.salus/src/main/java/org/openhab/binding/salus/internal/rest/RetryHttpClient.java
  bundles/org.openhab.binding.salus/src/main/java/org/openhab/binding/salus/internal/rest/SalusApi.java
  bundles/org.openhab.binding.salus/src/main/java/org/openhab/binding/salus/internal/rest/SalusApiException.java
  bundles/org.openhab.binding.salus/src/main/resources/OH-INF/addon/addon.xml
  bundles/org.openhab.binding.salus/src/main/resources/OH-INF/i18n/salus.properties
  bundles/org.openhab.binding.salus/src/main/resources/OH-INF/thing/it600.xml
  bundles/org.openhab.binding.salus/src/main/resources/OH-INF/thing/salus-bridge.xml
  bundles/org.openhab.binding.salus/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.salus/src/test/java/org/openhab/binding/salus/internal/discovery/CloudDiscoveryTest.java
  bundles/org.openhab.binding.salus/src/test/java/org/openhab/binding/salus/internal/rest/DeviceTest.java
  bundles/org.openhab.binding.salus/src/test/java/org/openhab/binding/salus/internal/rest/GsonMapperTest.java
  bundles/org.openhab.binding.salus/src/test/java/org/openhab/binding/salus/internal/rest/RetryHttpClientTest.java
  bundles/org.openhab.binding.salus/src/test/java/org/openhab/binding/salus/internal/rest/SalusApiTest.java
  bundles/org.openhab.binding.salus/src/test/resources/logback-test.xml
  bundles/pom.xml
Labels: new binding

#16814 [solarforecast] Fix ForecastSolar Plane default values in documentation.
  bundles/org.openhab.binding.solarforecast/README.md
Labels: documentation

#16491 [iotawatt] Initial contribution
  CODEOWNERS
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.iotawatt/NOTICE
  bundles/org.openhab.binding.iotawatt/README.md
  bundles/org.openhab.binding.iotawatt/pom.xml
  bundles/org.openhab.binding.iotawatt/src/main/feature/feature.xml
  bundles/org.openhab.binding.iotawatt/src/main/java/org/openhab/binding/iotawatt/internal/IoTaWattBindingConstants.java
  bundles/org.openhab.binding.iotawatt/src/main/java/org/openhab/binding/iotawatt/internal/IoTaWattConfiguration.java
  bundles/org.openhab.binding.iotawatt/src/main/java/org/openhab/binding/iotawatt/internal/IoTaWattHandlerFactory.java
  bundles/org.openhab.binding.iotawatt/src/main/java/org/openhab/binding/iotawatt/internal/client/IoTaWattClient.java
  bundles/org.openhab.binding.iotawatt/src/main/java/org/openhab/binding/iotawatt/internal/client/IoTaWattClientCommunicationException.java
  bundles/org.openhab.binding.iotawatt/src/main/java/org/openhab/binding/iotawatt/internal/client/IoTaWattClientConfigurationException.java
  bundles/org.openhab.binding.iotawatt/src/main/java/org/openhab/binding/iotawatt/internal/client/IoTaWattClientException.java
  bundles/org.openhab.binding.iotawatt/src/main/java/org/openhab/binding/iotawatt/internal/client/IoTaWattClientInterruptedException.java
  bundles/org.openhab.binding.iotawatt/src/main/java/org/openhab/binding/iotawatt/internal/handler/FetchDataServiceProvider.java
  bundles/org.openhab.binding.iotawatt/src/main/java/org/openhab/binding/iotawatt/internal/handler/HttpClientProvider.java
  bundles/org.openhab.binding.iotawatt/src/main/java/org/openhab/binding/iotawatt/internal/handler/IoTaWattClientProvider.java
  bundles/org.openhab.binding.iotawatt/src/main/java/org/openhab/binding/iotawatt/internal/handler/IoTaWattHandler.java
  bundles/org.openhab.binding.iotawatt/src/main/java/org/openhab/binding/iotawatt/internal/model/IoTaWattChannelType.java
  bundles/org.openhab.binding.iotawatt/src/main/java/org/openhab/binding/iotawatt/internal/model/StatusResponse.java
  bundles/org.openhab.binding.iotawatt/src/main/java/org/openhab/binding/iotawatt/internal/service/DeviceHandlerCallback.java
  bundles/org.openhab.binding.iotawatt/src/main/java/org/openhab/binding/iotawatt/internal/service/FetchDataService.java
  bundles/org.openhab.binding.iotawatt/src/main/resources/OH-INF/addon/addon.xml
  bundles/org.openhab.binding.iotawatt/src/main/resources/OH-INF/i18n/iotawatt.properties
  bundles/org.openhab.binding.iotawatt/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.iotawatt/src/test/java/org/openhab/binding/iotawatt/internal/client/IoTaWattClientTest.java
  bundles/org.openhab.binding.iotawatt/src/test/java/org/openhab/binding/iotawatt/internal/model/IoTaWattChannelTypeTest.java
  bundles/org.openhab.binding.iotawatt/src/test/java/org/openhab/binding/iotawatt/internal/service/FetchDataServiceTest.java
  bundles/org.openhab.binding.iotawatt/src/test/resources/apiResponses/device-status-response.json
  bundles/pom.xml
Labels: new binding

#16746 [shelly] Various small fixes for BLU HT, Range Extender, Plus 10V, TRV set temp
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api/ShellyApiInterface.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api1/Shelly1HttpApi.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api2/Shelly2ApiRpc.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/discovery/ShellyThingCreator.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/handler/ShellyBaseHandler.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/handler/ShellyComponents.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/handler/ShellyRelayHandler.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/provider/ShellyChannelDefinitions.java
  bundles/org.openhab.binding.shelly/src/main/resources/OH-INF/config/config2.xml
  bundles/org.openhab.binding.shelly/src/main/resources/scripts/oh-blu-scanner.js
Labels: bug

#16591 [persistence.jpa] Upgrade openjpa and derby
  bundles/org.openhab.persistence.jpa/pom.xml
  bundles/org.openhab.persistence.jpa/src/main/java/org/openhab/persistence/jpa/internal/JpaPersistenceService.java
  bundles/org.openhab.persistence.jpa/src/main/java/org/openhab/persistence/jpa/internal/model/JpaPersistentItem.java
Labels: enhancement, additional testing preferred

#16754 [basicprofiles] Initial contribution
  bom/openhab-addons/pom.xml
  bundles/org.openhab.transform.basicprofiles/NOTICE
  bundles/org.openhab.transform.basicprofiles/README.md
  bundles/org.openhab.transform.basicprofiles/pom.xml
  bundles/org.openhab.transform.basicprofiles/src/main/feature/feature.xml
  bundles/org.openhab.transform.basicprofiles/src/main/java/org/openhab/transform/basicprofiles/internal/BasicProfilesConstants.java
  bundles/org.openhab.transform.basicprofiles/src/main/java/org/openhab/transform/basicprofiles/internal/config/DebounceCountingStateProfileConfig.java
  bundles/org.openhab.transform.basicprofiles/src/main/java/org/openhab/transform/basicprofiles/internal/config/DebounceTimeStateProfileConfig.java
  bundles/org.openhab.transform.basicprofiles/src/main/java/org/openhab/transform/basicprofiles/internal/config/RoundStateProfileConfig.java
  bundles/org.openhab.transform.basicprofiles/src/main/java/org/openhab/transform/basicprofiles/internal/config/StateFilterProfileConfig.java
  bundles/org.openhab.transform.basicprofiles/src/main/java/org/openhab/transform/basicprofiles/internal/config/ThresholdStateProfileConfig.java
  bundles/org.openhab.transform.basicprofiles/src/main/java/org/openhab/transform/basicprofiles/internal/config/TimeRangeCommandProfileConfig.java
  bundles/org.openhab.transform.basicprofiles/src/main/java/org/openhab/transform/basicprofiles/internal/factory/BasicProfilesFactory.java
  bundles/org.openhab.transform.basicprofiles/src/main/java/org/openhab/transform/basicprofiles/internal/profiles/AbstractTriggerProfile.java
  bundles/org.openhab.transform.basicprofiles/src/main/java/org/openhab/transform/basicprofiles/internal/profiles/DebounceCountingStateProfile.java
  bundles/org.openhab.transform.basicprofiles/src/main/java/org/openhab/transform/basicprofiles/internal/profiles/DebounceTimeStateProfile.java
  bundles/org.openhab.transform.basicprofiles/src/main/java/org/openhab/transform/basicprofiles/internal/profiles/GenericCommandTriggerProfile.java
  bundles/org.openhab.transform.basicprofiles/src/main/java/org/openhab/transform/basicprofiles/internal/profiles/GenericToggleSwitchTriggerProfile.java
  bundles/org.openhab.transform.basicprofiles/src/main/java/org/openhab/transform/basicprofiles/internal/profiles/InvertStateProfile.java
  bundles/org.openhab.transform.basicprofiles/src/main/java/org/openhab/transform/basicprofiles/internal/profiles/RoundStateProfile.java
  bundles/org.openhab.transform.basicprofiles/src/main/java/org/openhab/transform/basicprofiles/internal/profiles/StateFilterProfile.java
  bundles/org.openhab.transform.basicprofiles/src/main/java/org/openhab/transform/basicprofiles/internal/profiles/ThresholdStateProfile.java
  bundles/org.openhab.transform.basicprofiles/src/main/java/org/openhab/transform/basicprofiles/internal/profiles/TimeRangeCommandProfile.java
  bundles/org.openhab.transform.basicprofiles/src/main/resources/OH-INF/addon/addon.xml
  bundles/org.openhab.transform.basicprofiles/src/main/resources/OH-INF/config/debounce.xml
  bundles/org.openhab.transform.basicprofiles/src/main/resources/OH-INF/config/generic-command.xml
  bundles/org.openhab.transform.basicprofiles/src/main/resources/OH-INF/config/round.xml
  bundles/org.openhab.transform.basicprofiles/src/main/resources/OH-INF/config/state-filter.xml
  bundles/org.openhab.transform.basicprofiles/src/main/resources/OH-INF/config/threshold.xml
  bundles/org.openhab.transform.basicprofiles/src/main/resources/OH-INF/config/time-range-command.xml
  bundles/org.openhab.transform.basicprofiles/src/main/resources/OH-INF/config/toggle-switch.xml
  bundles/org.openhab.transform.basicprofiles/src/main/resources/OH-INF/i18n/basicprofiles.properties
  bundles/org.openhab.transform.basicprofiles/src/test/java/org/openhab/transform/basicprofiles/internal/factory/BasicProfilesFactoryTest.java
  bundles/org.openhab.transform.basicprofiles/src/test/java/org/openhab/transform/basicprofiles/internal/profiles/DebounceCountingStateProfileTest.java
  bundles/org.openhab.transform.basicprofiles/src/test/java/org/openhab/transform/basicprofiles/internal/profiles/GenericCommandTriggerProfileTest.java
  bundles/org.openhab.transform.basicprofiles/src/test/java/org/openhab/transform/basicprofiles/internal/profiles/GenericToggleSwitchTriggerProfileTest.java
  bundles/org.openhab.transform.basicprofiles/src/test/java/org/openhab/transform/basicprofiles/internal/profiles/InvertStateProfileTest.java
  bundles/org.openhab.transform.basicprofiles/src/test/java/org/openhab/transform/basicprofiles/internal/profiles/RoundStateProfileTest.java
  bundles/org.openhab.transform.basicprofiles/src/test/java/org/openhab/transform/basicprofiles/internal/profiles/StateFilterProfileTest.java
  bundles/org.openhab.transform.basicprofiles/src/test/java/org/openhab/transform/basicprofiles/internal/profiles/ThresholdStateProfileTest.java
  bundles/pom.xml
Labels: new transform

#16770 [boschshc] Support for Smart Water Alarm
  bundles/org.openhab.binding.boschshc/README.md
  bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/console/BoschShcCommandExtension.java
  bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/devices/BoschSHCBindingConstants.java
  bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/devices/BoschSHCHandler.java
  bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/devices/BoschSHCHandlerFactory.java
  bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/devices/bridge/BridgeHandler.java
  bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/devices/bridge/dto/Message.java
  bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/devices/bridge/dto/MessageCode.java
  bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/devices/camera/CameraHandler.java
  bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/devices/waterleakage/WaterLeakageSensorHandler.java
  bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/discovery/ThingDiscoveryService.java
  bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/serialization/BoschServiceDataDeserializer.java
  bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/services/cameranotification/CameraNotificationState.java
  bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/services/cameranotification/dto/CameraNotificationServiceState.java
  bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/services/dto/EnabledDisabledState.java
  bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/services/privacymode/dto/PrivacyModeServiceState.java
  bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/services/waterleakagesensor/WaterLeakageSensorService.java
  bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/services/waterleakagesensor/dto/WaterLeakageSensorServiceState.java
  bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/services/waterleakagesensor/dto/WaterLeakageState.java
  bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/services/waterleakagesensorcheck/WaterLeakageSensorCheckService.java
  bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/services/waterleakagesensorcheck/dto/WaterLeakageSensorCheckServiceState.java
  bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/services/waterleakagesensortilt/WaterLeakageSensorTiltService.java
  bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/services/waterleakagesensortilt/dto/WaterLeakageSensorTiltServiceState.java
  bundles/org.openhab.binding.boschshc/src/main/resources/OH-INF/i18n/boschshc.properties
  bundles/org.openhab.binding.boschshc/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/devices/bridge/BridgeHandlerTest.java
  bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/devices/camera/CameraHandlerTest.java
  bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/devices/waterleakage/WaterLeakageSensorHandlerTest.java
  bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/services/cameranotification/CameraNotificationStateTest.java
  bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/services/dto/EnabledDisabledStateTest.java
Labels: enhancement

#16822 [tapocontrol] bugfix cloud connection error
  bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/api/TapoCloudConnector.java
  bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/api/protocol/aes/SecurePassthrough.java
  bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/api/protocol/klap/KlapProtocol.java
  bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/api/protocol/passthrough/PassthroughProtocol.java
  bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/dto/TapoRequest.java
Labels: bug

#16790 [hdpowerview] Support SDDP addon suggestion finder
  bundles/org.openhab.binding.hdpowerview/src/main/resources/OH-INF/addon/addon.xml
Labels: enhancement

#16794 [epsonprojector] Support SDDP addon suggestion finder
  bundles/org.openhab.binding.epsonprojector/src/main/resources/OH-INF/addon/addon.xml
  bundles/org.openhab.binding.sonyprojector/src/main/resources/OH-INF/addon/addon.xml
Labels: enhancement

#16820 [haywardomnilogic] Fixed chlorinator bug
  bundles/org.openhab.binding.haywardomnilogic/README.md
  bundles/org.openhab.binding.haywardomnilogic/src/main/java/org/openhab/binding/haywardomnilogic/internal/handler/HaywardChlorinatorHandler.java
Labels: bug, regression
