Repository openhab/openhab-addons, pull requests merged in 2024-09, with the labels that each got.

#17313 [serial] Support chaining transformations without an intersection symbol
  bundles/org.openhab.binding.serial/README.md
  bundles/org.openhab.binding.serial/src/main/java/org/openhab/binding/serial/internal/SerialHandlerFactory.java
  bundles/org.openhab.binding.serial/src/main/java/org/openhab/binding/serial/internal/channel/ChannelConfig.java
  bundles/org.openhab.binding.serial/src/main/java/org/openhab/binding/serial/internal/channel/DeviceChannel.java
  bundles/org.openhab.binding.serial/src/main/java/org/openhab/binding/serial/internal/channel/DeviceChannelFactory.java
  bundles/org.openhab.binding.serial/src/main/java/org/openhab/binding/serial/internal/channel/DimmerChannel.java
  bundles/org.openhab.binding.serial/src/main/java/org/openhab/binding/serial/internal/channel/NumberChannel.java
  bundles/org.openhab.binding.serial/src/main/java/org/openhab/binding/serial/internal/channel/RollershutterChannel.java
  bundles/org.openhab.binding.serial/src/main/java/org/openhab/binding/serial/internal/channel/StringChannel.java
  bundles/org.openhab.binding.serial/src/main/java/org/openhab/binding/serial/internal/channel/SwitchChannel.java
  bundles/org.openhab.binding.serial/src/main/java/org/openhab/binding/serial/internal/handler/SerialDeviceHandler.java
  bundles/org.openhab.binding.serial/src/main/java/org/openhab/binding/serial/internal/transform/CascadedValueTransformationImpl.java
  bundles/org.openhab.binding.serial/src/main/java/org/openhab/binding/serial/internal/transform/NoOpValueTransformation.java
  bundles/org.openhab.binding.serial/src/main/java/org/openhab/binding/serial/internal/transform/SingleValueTransformation.java
  bundles/org.openhab.binding.serial/src/main/java/org/openhab/binding/serial/internal/transform/ValueTransformation.java
  bundles/org.openhab.binding.serial/src/main/java/org/openhab/binding/serial/internal/transform/ValueTransformationProvider.java
  bundles/org.openhab.binding.serial/src/main/resources/OH-INF/i18n/serial.properties
  bundles/org.openhab.binding.serial/src/main/resources/OH-INF/thing/thing-types.xml
Labels: enhancement

#17290 [mqtt.generic] Support chaining transformations without an intersection symbol
  bundles/org.openhab.binding.mqtt.generic/README.md
  bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/AbstractMQTTThingHandler.java
  bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/AvailabilityTracker.java
  bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/ChannelConfig.java
  bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/ChannelConfigBuilder.java
  bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/ChannelState.java
  bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/ChannelStateTransformation.java
  bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/TransformationServiceProvider.java
  bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/internal/MqttThingHandlerFactory.java
  bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/internal/handler/GenericMQTTThingHandler.java
  bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/internal/handler/GenericThingConfiguration.java
  bundles/org.openhab.binding.mqtt.generic/src/main/resources/OH-INF/config/color-channel-config.xml
  bundles/org.openhab.binding.mqtt.generic/src/main/resources/OH-INF/config/dimmer-channel-config.xml
  bundles/org.openhab.binding.mqtt.generic/src/main/resources/OH-INF/config/number-channel-config.xml
  bundles/org.openhab.binding.mqtt.generic/src/main/resources/OH-INF/config/rollershutter-channel-config.xml
  bundles/org.openhab.binding.mqtt.generic/src/main/resources/OH-INF/config/string-channel-config.xml
  bundles/org.openhab.binding.mqtt.generic/src/main/resources/OH-INF/config/switch-channel-config.xml
  bundles/org.openhab.binding.mqtt.generic/src/main/resources/OH-INF/config/trigger-channel-config.xml
  bundles/org.openhab.binding.mqtt.generic/src/main/resources/OH-INF/i18n/mqtt.properties
  bundles/org.openhab.binding.mqtt.generic/src/main/resources/OH-INF/thing/generic-thing.xml
  bundles/org.openhab.binding.mqtt.generic/src/test/java/org/openhab/binding/mqtt/generic/ChannelStateTests.java
  bundles/org.openhab.binding.mqtt.generic/src/test/java/org/openhab/binding/mqtt/generic/ChannelStateTransformationTests.java
  bundles/org.openhab.binding.mqtt.generic/src/test/java/org/openhab/binding/mqtt/generic/internal/handler/GenericThingHandlerTests.java
  bundles/org.openhab.binding.mqtt.generic/src/test/java/org/openhab/binding/mqtt/generic/internal/handler/ThingChannelConstants.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/generic/internal/MqttThingHandlerFactory.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/ComponentChannel.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/DiscoverComponents.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/AbstractComponent.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/ComponentFactory.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/handler/HomeAssistantThingHandler.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/AbstractHomeAssistantTests.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/component/AbstractComponentTests.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/handler/HomeAssistantThingHandlerTests.java
  bundles/org.openhab.binding.mqtt.homie/src/main/java/org/openhab/binding/mqtt/homie/generic/internal/MqttThingHandlerFactory.java
  itests/org.openhab.binding.mqtt.homeassistant.tests/src/main/java/org/openhab/binding/mqtt/homeassistant/DiscoverComponentsTest.java
  itests/org.openhab.binding.mqtt.homeassistant.tests/src/main/java/org/openhab/binding/mqtt/homeassistant/HomeAssistantMQTTImplementationTest.java
Labels: enhancement

#17360 [nikohomecontrol] fix basic alarm
  bundles/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/protocol/nhc2/NikoHomeControlCommunication2.java
Labels: bug

#17306 [modbus] Support chaining transformations without an intersection symbol
  bundles/org.openhab.binding.modbus/README.md
  bundles/org.openhab.binding.modbus/src/main/java/org/openhab/binding/modbus/internal/CascadedValueTransformationImpl.java
  bundles/org.openhab.binding.modbus/src/main/java/org/openhab/binding/modbus/internal/ModbusTransformation.java
  bundles/org.openhab.binding.modbus/src/main/java/org/openhab/binding/modbus/internal/SingleValueTransformation.java
  bundles/org.openhab.binding.modbus/src/main/java/org/openhab/binding/modbus/internal/ValueTransformation.java
  bundles/org.openhab.binding.modbus/src/main/java/org/openhab/binding/modbus/internal/config/ModbusDataConfiguration.java
  bundles/org.openhab.binding.modbus/src/main/java/org/openhab/binding/modbus/internal/handler/ModbusDataThingHandler.java
  bundles/org.openhab.binding.modbus/src/main/resources/OH-INF/i18n/modbus.properties
  bundles/org.openhab.binding.modbus/src/main/resources/OH-INF/thing/thing-data.xml
  bundles/org.openhab.binding.modbus/src/test/java/org/openhab/binding/modbus/internal/CascadedValueTransformationImplTest.java
  bundles/org.openhab.binding.modbus/src/test/java/org/openhab/binding/modbus/internal/ModbusTransformationTest.java
  bundles/org.openhab.binding.modbus/src/test/java/org/openhab/binding/modbus/internal/SingleValueTransformationTest.java
Labels: enhancement

#17371 [kaleidescape] Support discovery of Strato V
  bundles/org.openhab.binding.kaleidescape/README.md
  bundles/org.openhab.binding.kaleidescape/src/main/feature/feature.xml
  bundles/org.openhab.binding.kaleidescape/src/main/java/org/openhab/binding/kaleidescape/internal/KaleidescapeBindingConstants.java
  bundles/org.openhab.binding.kaleidescape/src/main/java/org/openhab/binding/kaleidescape/internal/communication/KaleidescapeStatusCodes.java
  bundles/org.openhab.binding.kaleidescape/src/main/java/org/openhab/binding/kaleidescape/internal/discovery/KaleidescapeDiscoveryParticipant.java
  bundles/org.openhab.binding.kaleidescape/src/main/java/org/openhab/binding/kaleidescape/internal/discovery/KaleidescapeDiscoveryService.java
Labels: enhancement

#17379 [solarman] Sync inverter definition files from upstream.
  bundles/org.openhab.binding.solarman/README.md
  bundles/org.openhab.binding.solarman/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.solarman/src/main/resources/definitions/deye_2mppt.yaml
  bundles/org.openhab.binding.solarman/src/main/resources/definitions/deye_4mppt.yaml
  bundles/org.openhab.binding.solarman/src/main/resources/definitions/deye_hybrid.yaml
  bundles/org.openhab.binding.solarman/src/main/resources/definitions/deye_sg04lp3.yaml
  bundles/org.openhab.binding.solarman/src/main/resources/definitions/hyd-zss-hp-3k-6k.yaml
  bundles/org.openhab.binding.solarman/src/main/resources/definitions/kstar_hybrid.yaml
  bundles/org.openhab.binding.solarman/src/main/resources/definitions/sofar_g3hyd.yaml
  bundles/org.openhab.binding.solarman/src/main/resources/definitions/sofar_hyd3k-6k-es.yaml
  bundles/org.openhab.binding.solarman/src/main/resources/definitions/sofar_lsw3.yaml
  bundles/org.openhab.binding.solarman/src/main/resources/definitions/solis_3p-4g.yaml
  bundles/org.openhab.binding.solarman/src/main/resources/definitions/solis_hybrid.yaml
  bundles/org.openhab.binding.solarman/src/main/resources/definitions/solis_s6-gr1p.yaml
Labels: enhancement

#17377 [tplinksmarthome] Add new device: EP25
  bundles/org.openhab.binding.tplinksmarthome/README.md
  bundles/org.openhab.binding.tplinksmarthome/src/main/java/org/openhab/binding/tplinksmarthome/internal/TPLinkSmartHomeThingType.java
  bundles/org.openhab.binding.tplinksmarthome/src/main/resources/OH-INF/i18n/tplinksmarthome.properties
  bundles/org.openhab.binding.tplinksmarthome/src/main/resources/OH-INF/thing/EP25.xml
Labels: enhancement

#16387 [warmup] Fixes & Enhancements
  bundles/org.openhab.binding.warmup/README.md
  bundles/org.openhab.binding.warmup/src/main/java/org/openhab/binding/warmup/internal/WarmupBindingConstants.java
  bundles/org.openhab.binding.warmup/src/main/java/org/openhab/binding/warmup/internal/action/WarmupActions.java
  bundles/org.openhab.binding.warmup/src/main/java/org/openhab/binding/warmup/internal/api/MyWarmupApi.java
  bundles/org.openhab.binding.warmup/src/main/java/org/openhab/binding/warmup/internal/discovery/WarmupDiscoveryService.java
  bundles/org.openhab.binding.warmup/src/main/java/org/openhab/binding/warmup/internal/handler/RoomHandler.java
  bundles/org.openhab.binding.warmup/src/main/java/org/openhab/binding/warmup/internal/handler/WarmupThingHandler.java
  bundles/org.openhab.binding.warmup/src/main/java/org/openhab/binding/warmup/internal/model/auth/AuthRequestDTO.java
  bundles/org.openhab.binding.warmup/src/main/java/org/openhab/binding/warmup/internal/model/auth/AuthRequestDataDTO.java
  bundles/org.openhab.binding.warmup/src/main/java/org/openhab/binding/warmup/internal/model/auth/AuthResponseDTO.java
  bundles/org.openhab.binding.warmup/src/main/java/org/openhab/binding/warmup/internal/model/auth/AuthResponseDataDTO.java
  bundles/org.openhab.binding.warmup/src/main/java/org/openhab/binding/warmup/internal/model/auth/AuthResponseStatusDTO.java
  bundles/org.openhab.binding.warmup/src/main/java/org/openhab/binding/warmup/internal/model/query/DeviceDTO.java
  bundles/org.openhab.binding.warmup/src/main/java/org/openhab/binding/warmup/internal/model/query/LocationDTO.java
  bundles/org.openhab.binding.warmup/src/main/java/org/openhab/binding/warmup/internal/model/query/QueryDataDTO.java
  bundles/org.openhab.binding.warmup/src/main/java/org/openhab/binding/warmup/internal/model/query/QueryResponseDTO.java
  bundles/org.openhab.binding.warmup/src/main/java/org/openhab/binding/warmup/internal/model/query/RoomDTO.java
  bundles/org.openhab.binding.warmup/src/main/java/org/openhab/binding/warmup/internal/model/query/UserDTO.java
  bundles/org.openhab.binding.warmup/src/main/resources/OH-INF/addon/addon.xml
  bundles/org.openhab.binding.warmup/src/main/resources/OH-INF/i18n/warmup.properties
  bundles/org.openhab.binding.warmup/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.warmup/src/main/resources/OH-INF/update/warmup.xml
Labels: enhancement

#17283 [goecharger] Update README.md
  bundles/org.openhab.binding.goecharger/README.md
Labels: documentation

#17017 [tesla] Update README.md remove hardcoded units
  bundles/org.openhab.binding.tesla/README.md
Labels: documentation

#17133 [smartmeter] Fix Undelivered IOException
  bundles/org.openhab.binding.smartmeter/src/main/java/org/openhab/binding/smartmeter/SmartMeterConfiguration.java
  bundles/org.openhab.binding.smartmeter/src/main/java/org/openhab/binding/smartmeter/internal/MeterDevice.java
  bundles/org.openhab.binding.smartmeter/src/main/java/org/openhab/binding/smartmeter/internal/MeterDeviceFactory.java
  bundles/org.openhab.binding.smartmeter/src/main/java/org/openhab/binding/smartmeter/internal/MeterValue.java
  bundles/org.openhab.binding.smartmeter/src/main/java/org/openhab/binding/smartmeter/internal/ObisCode.java
  bundles/org.openhab.binding.smartmeter/src/main/java/org/openhab/binding/smartmeter/internal/SmartMeterChannelTypeProvider.java
  bundles/org.openhab.binding.smartmeter/src/main/java/org/openhab/binding/smartmeter/internal/SmartMeterHandler.java
  bundles/org.openhab.binding.smartmeter/src/main/java/org/openhab/binding/smartmeter/internal/conformity/Conformity.java
  bundles/org.openhab.binding.smartmeter/src/main/java/org/openhab/binding/smartmeter/internal/conformity/negate/NegateHandler.java
  bundles/org.openhab.binding.smartmeter/src/main/java/org/openhab/binding/smartmeter/internal/iec62056/MeterReader.java
  bundles/org.openhab.binding.smartmeter/src/main/java/org/openhab/binding/smartmeter/internal/iec62056/SerialConnector.java
  bundles/org.openhab.binding.smartmeter/src/main/java/org/openhab/binding/smartmeter/internal/iec62056/UnitConversion.java
  bundles/org.openhab.binding.smartmeter/src/main/java/org/openhab/binding/smartmeter/internal/sml/SmlFileDebugOutput.java
  bundles/org.openhab.binding.smartmeter/src/main/java/org/openhab/binding/smartmeter/internal/sml/SmlSerialConnector.java
  bundles/org.openhab.binding.smartmeter/src/test/java/org/openhab/binding/smartmeter/MockMeterReaderConnector.java
  bundles/org.openhab.binding.smartmeter/src/test/java/org/openhab/binding/smartmeter/TestMeterReading.java
  bundles/org.openhab.binding.smartmeter/src/test/java/org/openhab/binding/smartmeter/TestNegateBit.java
Labels: bug

#17386 [lifx] Add support for new LIFX products
  bundles/org.openhab.binding.lifx/src/main/java/org/openhab/binding/lifx/internal/LifxProduct.java
Labels: enhancement

#17388 [ipcamera]Add missing motion detection topic for VivoTek FD9388-HTV cameras
  bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/onvif/OnvifConnection.java
Labels: enhancement

#17174 [fenecon] Initial contribution
  CODEOWNERS
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.fenecon/NOTICE
  bundles/org.openhab.binding.fenecon/README.md
  bundles/org.openhab.binding.fenecon/pom.xml
  bundles/org.openhab.binding.fenecon/src/main/feature/feature.xml
  bundles/org.openhab.binding.fenecon/src/main/java/org/openhab/binding/fenecon/internal/FeneconBindingConstants.java
  bundles/org.openhab.binding.fenecon/src/main/java/org/openhab/binding/fenecon/internal/FeneconConfiguration.java
  bundles/org.openhab.binding.fenecon/src/main/java/org/openhab/binding/fenecon/internal/FeneconHandler.java
  bundles/org.openhab.binding.fenecon/src/main/java/org/openhab/binding/fenecon/internal/FeneconHandlerFactory.java
  bundles/org.openhab.binding.fenecon/src/main/java/org/openhab/binding/fenecon/internal/api/BatteryPower.java
  bundles/org.openhab.binding.fenecon/src/main/java/org/openhab/binding/fenecon/internal/api/FeneconController.java
  bundles/org.openhab.binding.fenecon/src/main/java/org/openhab/binding/fenecon/internal/api/FeneconResponse.java
  bundles/org.openhab.binding.fenecon/src/main/java/org/openhab/binding/fenecon/internal/api/GridPower.java
  bundles/org.openhab.binding.fenecon/src/main/java/org/openhab/binding/fenecon/internal/api/State.java
  bundles/org.openhab.binding.fenecon/src/main/java/org/openhab/binding/fenecon/internal/exception/FeneconAuthenticationException.java
  bundles/org.openhab.binding.fenecon/src/main/java/org/openhab/binding/fenecon/internal/exception/FeneconCommunicationException.java
  bundles/org.openhab.binding.fenecon/src/main/java/org/openhab/binding/fenecon/internal/exception/FeneconException.java
  bundles/org.openhab.binding.fenecon/src/main/resources/OH-INF/addon/addon.xml
  bundles/org.openhab.binding.fenecon/src/main/resources/OH-INF/i18n/fenecon.properties
  bundles/org.openhab.binding.fenecon/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.fenecon/src/test/java/org/openhab/binding/fenecon/internal/FeneconBindingConstantsTest.java
  bundles/org.openhab.binding.fenecon/src/test/java/org/openhab/binding/fenecon/internal/api/BatteryPowerTest.java
  bundles/org.openhab.binding.fenecon/src/test/java/org/openhab/binding/fenecon/internal/api/GridPowerTest.java
  bundles/org.openhab.binding.fenecon/src/test/java/org/openhab/binding/fenecon/internal/api/StateTest.java
  bundles/pom.xml
Labels: new binding

#17387 [kaleidescape] Improve volume event handling
  bundles/org.openhab.binding.kaleidescape/README.md
  bundles/org.openhab.binding.kaleidescape/src/main/java/org/openhab/binding/kaleidescape/internal/KaleidescapeBindingConstants.java
  bundles/org.openhab.binding.kaleidescape/src/main/java/org/openhab/binding/kaleidescape/internal/configuration/KaleidescapeThingConfiguration.java
  bundles/org.openhab.binding.kaleidescape/src/main/java/org/openhab/binding/kaleidescape/internal/handler/KaleidescapeHandler.java
  bundles/org.openhab.binding.kaleidescape/src/main/java/org/openhab/binding/kaleidescape/internal/handler/KaleidescapeMessageHandler.java
  bundles/org.openhab.binding.kaleidescape/src/main/resources/OH-INF/config/config.xml
  bundles/org.openhab.binding.kaleidescape/src/main/resources/OH-INF/i18n/kaleidescape.properties
Labels: enhancement

#17099 [bluetooth.hdpowerview] New binding using Bluetooth Low Energy
  CODEOWNERS
  bundles/org.openhab.binding.bluetooth.hdpowerview/NOTICE
  bundles/org.openhab.binding.bluetooth.hdpowerview/README.md
  bundles/org.openhab.binding.bluetooth.hdpowerview/pom.xml
  bundles/org.openhab.binding.bluetooth.hdpowerview/src/main/feature/feature.xml
  bundles/org.openhab.binding.bluetooth.hdpowerview/src/main/java/org/openhab/binding/bluetooth/hdpowerview/internal/ShadeBindingConstants.java
  bundles/org.openhab.binding.bluetooth.hdpowerview/src/main/java/org/openhab/binding/bluetooth/hdpowerview/internal/discovery/ShadeDiscoveryParticipant.java
  bundles/org.openhab.binding.bluetooth.hdpowerview/src/main/java/org/openhab/binding/bluetooth/hdpowerview/internal/factory/ShadeHandlerFactory.java
  bundles/org.openhab.binding.bluetooth.hdpowerview/src/main/java/org/openhab/binding/bluetooth/hdpowerview/internal/shade/ShadeConfiguration.java
  bundles/org.openhab.binding.bluetooth.hdpowerview/src/main/java/org/openhab/binding/bluetooth/hdpowerview/internal/shade/ShadeDataReader.java
  bundles/org.openhab.binding.bluetooth.hdpowerview/src/main/java/org/openhab/binding/bluetooth/hdpowerview/internal/shade/ShadeDataWriter.java
  bundles/org.openhab.binding.bluetooth.hdpowerview/src/main/java/org/openhab/binding/bluetooth/hdpowerview/internal/shade/ShadeHandler.java
  bundles/org.openhab.binding.bluetooth.hdpowerview/src/main/resources/OH-INF/i18n/bluetooth.properties
  bundles/org.openhab.binding.bluetooth.hdpowerview/src/main/resources/OH-INF/thing/thing.xml
  bundles/org.openhab.binding.bluetooth.hdpowerview/src/test/java/org/openhab/binding/bluetooth/hdpowerview/test/ShadeTests.java
  bundles/org.openhab.binding.bluetooth/src/main/resources/OH-INF/addon/addon.xml
  bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/database/ShadeCapabilitiesDatabase.java
  bundles/pom.xml
  features/openhab-addons/src/main/resources/footer.xml
Labels: new binding

#17189 [openweathermap] Fix `NullPointerException`
  bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/OpenWeatherMapBindingConstants.java
  bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/config/OpenWeatherMapAPIConfiguration.java
  bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/config/OpenWeatherMapAirPollutionConfiguration.java
  bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/config/OpenWeatherMapLocationConfiguration.java
  bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/config/OpenWeatherMapOneCallConfiguration.java
  bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/config/OpenWeatherMapWeatherAndForecastConfiguration.java
  bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/connection/OpenWeatherMapConnection.java
  bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/dto/OpenWeatherMapOneCallHistAPIData.java
  bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/dto/base/Precipitation.java
  bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/handler/AbstractOpenWeatherMapHandler.java
  bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/handler/OpenWeatherMapAirPollutionHandler.java
  bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/handler/OpenWeatherMapOneCallHandler.java
  bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/handler/OpenWeatherMapOneCallHistoryHandler.java
  bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/handler/OpenWeatherMapWeatherAndForecastHandler.java
  bundles/org.openhab.binding.openweathermap/src/test/java/org/openhab/binding/openweathermap/internal/DataUtil.java
  bundles/org.openhab.binding.openweathermap/src/test/java/org/openhab/binding/openweathermap/internal/TestObjectsUtil.java
  bundles/org.openhab.binding.openweathermap/src/test/java/org/openhab/binding/openweathermap/internal/handler/OpenWeatherMapOneCallHistoryHandlerTest.java
  bundles/org.openhab.binding.openweathermap/src/test/resources/history_v2_5.json
  bundles/org.openhab.binding.openweathermap/src/test/resources/history_v3_0.json
Labels: bug

#17317 [jdbc] Add Oracle DB support
  bundles/org.openhab.persistence.jdbc/README.md
  bundles/org.openhab.persistence.jdbc/pom.xml
  bundles/org.openhab.persistence.jdbc/src/main/feature/feature.xml
  bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/JdbcConfiguration.java
  bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/db/JdbcBaseDAO.java
  bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/db/JdbcOracleDAO.java
  bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/utils/StringUtilsExt.java
  bundles/org.openhab.persistence.jdbc/src/main/resources/OH-INF/addon/addon-oracle.xml
  bundles/org.openhab.persistence.jdbc/src/main/resources/OH-INF/config/config.xml
Labels: enhancement

#17152 [flume] Initial contribution
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.flume/NOTICE
  bundles/org.openhab.binding.flume/README.md
  bundles/org.openhab.binding.flume/pom.xml
  bundles/org.openhab.binding.flume/src/main/feature/feature.xml
  bundles/org.openhab.binding.flume/src/main/java/org/openhab/binding/flume/internal/FlumeBindingConstants.java
  bundles/org.openhab.binding.flume/src/main/java/org/openhab/binding/flume/internal/FlumeBridgeConfig.java
  bundles/org.openhab.binding.flume/src/main/java/org/openhab/binding/flume/internal/FlumeDeviceConfig.java
  bundles/org.openhab.binding.flume/src/main/java/org/openhab/binding/flume/internal/FlumeHandlerFactory.java
  bundles/org.openhab.binding.flume/src/main/java/org/openhab/binding/flume/internal/actions/FlumeDeviceActions.java
  bundles/org.openhab.binding.flume/src/main/java/org/openhab/binding/flume/internal/api/FlumeApi.java
  bundles/org.openhab.binding.flume/src/main/java/org/openhab/binding/flume/internal/api/FlumeApiException.java
  bundles/org.openhab.binding.flume/src/main/java/org/openhab/binding/flume/internal/api/dto/FlumeApiCurrentFlowRate.java
  bundles/org.openhab.binding.flume/src/main/java/org/openhab/binding/flume/internal/api/dto/FlumeApiDevice.java
  bundles/org.openhab.binding.flume/src/main/java/org/openhab/binding/flume/internal/api/dto/FlumeApiGetToken.java
  bundles/org.openhab.binding.flume/src/main/java/org/openhab/binding/flume/internal/api/dto/FlumeApiQueryBucket.java
  bundles/org.openhab.binding.flume/src/main/java/org/openhab/binding/flume/internal/api/dto/FlumeApiQueryWaterUsage.java
  bundles/org.openhab.binding.flume/src/main/java/org/openhab/binding/flume/internal/api/dto/FlumeApiRefreshToken.java
  bundles/org.openhab.binding.flume/src/main/java/org/openhab/binding/flume/internal/api/dto/FlumeApiToken.java
  bundles/org.openhab.binding.flume/src/main/java/org/openhab/binding/flume/internal/api/dto/FlumeApiTokenPayload.java
  bundles/org.openhab.binding.flume/src/main/java/org/openhab/binding/flume/internal/api/dto/FlumeApiUsageAlert.java
  bundles/org.openhab.binding.flume/src/main/java/org/openhab/binding/flume/internal/config/FlumeCloudConnectorConfig.java
  bundles/org.openhab.binding.flume/src/main/java/org/openhab/binding/flume/internal/discovery/FlumeDiscoveryService.java
  bundles/org.openhab.binding.flume/src/main/java/org/openhab/binding/flume/internal/handler/FlumeBridgeHandler.java
  bundles/org.openhab.binding.flume/src/main/java/org/openhab/binding/flume/internal/handler/FlumeDeviceHandler.java
  bundles/org.openhab.binding.flume/src/main/java/org/openhab/binding/flume/utils/JsonInstantSerializer.java
  bundles/org.openhab.binding.flume/src/main/java/org/openhab/binding/flume/utils/JsonLocalDateTimeSerializer.java
  bundles/org.openhab.binding.flume/src/main/resources/OH-INF/addon/addon.xml
  bundles/org.openhab.binding.flume/src/main/resources/OH-INF/i18n/flume.properties
  bundles/org.openhab.binding.flume/src/main/resources/OH-INF/thing/flume-cloud-connector.xml
  bundles/org.openhab.binding.flume/src/main/resources/OH-INF/thing/flume-device.xml
  bundles/pom.xml
Labels: new binding

#17335 [solarforecast] Add manual update feature
  bundles/org.openhab.binding.solarforecast/README.md
  bundles/org.openhab.binding.solarforecast/src/main/java/org/openhab/binding/solarforecast/internal/actions/SolarForecast.java
  bundles/org.openhab.binding.solarforecast/src/main/java/org/openhab/binding/solarforecast/internal/actions/SolarForecastActions.java
  bundles/org.openhab.binding.solarforecast/src/main/java/org/openhab/binding/solarforecast/internal/forecastsolar/ForecastSolarObject.java
  bundles/org.openhab.binding.solarforecast/src/main/java/org/openhab/binding/solarforecast/internal/solcast/SolcastObject.java
  bundles/org.openhab.binding.solarforecast/src/main/java/org/openhab/binding/solarforecast/internal/solcast/handler/SolcastPlaneHandler.java
  bundles/org.openhab.binding.solarforecast/src/main/resources/OH-INF/config/sc-plane-config.xml
  bundles/org.openhab.binding.solarforecast/src/main/resources/OH-INF/i18n/solarforecast.properties
  bundles/org.openhab.binding.solarforecast/src/test/java/org/openhab/binding/solarforecast/SolcastTest.java
Labels: enhancement

#17373 [androidTV] fix version parsing for newer Philips TV models
  bundles/org.openhab.binding.androidtv/src/main/java/org/openhab/binding/androidtv/internal/protocol/philipstv/service/TvChannelService.java
  bundles/org.openhab.binding.androidtv/src/main/java/org/openhab/binding/androidtv/internal/protocol/philipstv/service/model/channel/AvailableTvChannelsDTO.java
  bundles/org.openhab.binding.androidtv/src/test/java/org/openhab/binding/androidtv/internal/protocol/philipstv/service/PhilipsTvChannelTest.java
Labels: bug

#17299 [senechome] Fix `ArrayIndexOutOfBoundsException` when less than 4 packs
  bundles/org.openhab.binding.senechome/src/main/java/org/openhab/binding/senechome/internal/SenecHomeApi.java
  bundles/org.openhab.binding.senechome/src/main/java/org/openhab/binding/senechome/internal/SenecHomeHandler.java
  bundles/org.openhab.binding.senechome/src/main/java/org/openhab/binding/senechome/internal/SenecSystemStatus.java
  bundles/org.openhab.binding.senechome/src/main/java/org/openhab/binding/senechome/internal/SenecWallboxStatus.java
  bundles/org.openhab.binding.senechome/src/main/java/org/openhab/binding/senechome/internal/dto/SenecHomeBattery.java
  bundles/org.openhab.binding.senechome/src/main/java/org/openhab/binding/senechome/internal/dto/SenecHomeEnergy.java
  bundles/org.openhab.binding.senechome/src/main/java/org/openhab/binding/senechome/internal/dto/SenecHomeGrid.java
  bundles/org.openhab.binding.senechome/src/main/java/org/openhab/binding/senechome/internal/dto/SenecHomePower.java
  bundles/org.openhab.binding.senechome/src/main/java/org/openhab/binding/senechome/internal/dto/SenecHomeResponse.java
  bundles/org.openhab.binding.senechome/src/main/java/org/openhab/binding/senechome/internal/dto/SenecHomeStatistics.java
  bundles/org.openhab.binding.senechome/src/main/java/org/openhab/binding/senechome/internal/dto/SenecHomeTemperature.java
  bundles/org.openhab.binding.senechome/src/main/java/org/openhab/binding/senechome/internal/dto/SenecHomeWallbox.java
Labels: bug

#17367 [netatmo] Fix doorbell channels flapping
  bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/api/data/ChannelGroup.java
  bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/api/dto/HomeEvent.java
  bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/ApiBridgeHandler.java
  bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/capability/CameraCapability.java
  bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/capability/PersonCapability.java
  bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/channelhelper/EventCameraChannelHelper.java
  bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/channelhelper/EventChannelHelper.java
  bundles/org.openhab.binding.netatmo/src/main/resources/OH-INF/i18n/netatmo.properties
Labels: bug

#17295 [melcloud] Improve null handling
  bundles/org.openhab.binding.melcloud/src/main/java/org/openhab/binding/melcloud/internal/MelCloudBindingConstants.java
  bundles/org.openhab.binding.melcloud/src/main/java/org/openhab/binding/melcloud/internal/MelCloudHandlerFactory.java
  bundles/org.openhab.binding.melcloud/src/main/java/org/openhab/binding/melcloud/internal/api/MelCloudConnection.java
  bundles/org.openhab.binding.melcloud/src/main/java/org/openhab/binding/melcloud/internal/api/dto/Area.java
  bundles/org.openhab.binding.melcloud/src/main/java/org/openhab/binding/melcloud/internal/api/dto/Device.java
  bundles/org.openhab.binding.melcloud/src/main/java/org/openhab/binding/melcloud/internal/api/dto/DeviceProps.java
  bundles/org.openhab.binding.melcloud/src/main/java/org/openhab/binding/melcloud/internal/api/dto/DeviceStatus.java
  bundles/org.openhab.binding.melcloud/src/main/java/org/openhab/binding/melcloud/internal/api/dto/Floor.java
  bundles/org.openhab.binding.melcloud/src/main/java/org/openhab/binding/melcloud/internal/api/dto/HeatpumpDeviceStatus.java
  bundles/org.openhab.binding.melcloud/src/main/java/org/openhab/binding/melcloud/internal/api/dto/ListDevicesResponse.java
  bundles/org.openhab.binding.melcloud/src/main/java/org/openhab/binding/melcloud/internal/api/dto/LoginClientResponse.java
  bundles/org.openhab.binding.melcloud/src/main/java/org/openhab/binding/melcloud/internal/api/dto/LoginData.java
  bundles/org.openhab.binding.melcloud/src/main/java/org/openhab/binding/melcloud/internal/api/dto/Preset.java
  bundles/org.openhab.binding.melcloud/src/main/java/org/openhab/binding/melcloud/internal/api/dto/QuantizedCoordinates.java
  bundles/org.openhab.binding.melcloud/src/main/java/org/openhab/binding/melcloud/internal/api/dto/Structure.java
  bundles/org.openhab.binding.melcloud/src/main/java/org/openhab/binding/melcloud/internal/api/dto/WeatherObservation.java
  bundles/org.openhab.binding.melcloud/src/main/java/org/openhab/binding/melcloud/internal/config/AcDeviceConfig.java
  bundles/org.openhab.binding.melcloud/src/main/java/org/openhab/binding/melcloud/internal/config/AccountConfig.java
  bundles/org.openhab.binding.melcloud/src/main/java/org/openhab/binding/melcloud/internal/config/HeatpumpDeviceConfig.java
  bundles/org.openhab.binding.melcloud/src/main/java/org/openhab/binding/melcloud/internal/discovery/MelCloudDiscoveryService.java
  bundles/org.openhab.binding.melcloud/src/main/java/org/openhab/binding/melcloud/internal/exceptions/MelCloudCommException.java
  bundles/org.openhab.binding.melcloud/src/main/java/org/openhab/binding/melcloud/internal/exceptions/MelCloudLoginException.java
  bundles/org.openhab.binding.melcloud/src/main/java/org/openhab/binding/melcloud/internal/handler/MelCloudAccountHandler.java
  bundles/org.openhab.binding.melcloud/src/main/java/org/openhab/binding/melcloud/internal/handler/MelCloudDeviceHandler.java
  bundles/org.openhab.binding.melcloud/src/main/java/org/openhab/binding/melcloud/internal/handler/MelCloudHeatpumpDeviceHandler.java
Labels: bug

#17327 [map] Add a way to customize inline-map delimiters
  bundles/org.openhab.transform.map/README.md
  bundles/org.openhab.transform.map/src/main/java/org/openhab/transform/map/internal/MapTransformationService.java
  bundles/org.openhab.transform.map/src/main/resources/OH-INF/config/mapProfile.xml
  bundles/org.openhab.transform.map/src/main/resources/OH-INF/i18n/map.properties
  bundles/org.openhab.transform.map/src/test/java/org/openhab/transform/map/internal/MapTransformationServiceTest.java
Labels: enhancement

#17157 [homekit] Adjust default ranges for some characteristics
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitCharacteristicFactory.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitLightSensorImpl.java
Labels: enhancement

#17350 [miio] Fix parsing error clear record
  bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/handler/MiIoVacuumHandler.java
  bundles/org.openhab.binding.miio/src/test/java/org/openhab/binding/miio/internal/handler/MiIoVacuumHandlerTest.java
Labels: bug

#17397 [netatmo] Switching siren channel of the Presence to Read-Only
  bundles/org.openhab.binding.netatmo/README.md
  bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/api/SecurityApi.java
  bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/api/data/ModuleType.java
  bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/capability/PresenceCapability.java
  bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/capability/SecurityCapability.java
  bundles/org.openhab.binding.netatmo/src/main/resources/OH-INF/thing/security.xml
  bundles/org.openhab.binding.netatmo/src/main/resources/OH-INF/update/instructions.xml
Labels: bug

#17401 [fronius] Fix warning box in README
  bundles/org.openhab.binding.fronius/README.md
Labels: documentation

#17399 [mqtt.homeassistant] Implement template schema lights
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/HomeAssistantChannelTransformation.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/AbstractRawSchemaLight.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/JSONSchemaLight.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/Light.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/TemplateSchemaLight.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/component/TemplateSchemaLightTests.java
Labels: enhancement

#17403 [jdbc] Fix error in addon info for Oracle
  bundles/org.openhab.persistence.jdbc/src/main/resources/OH-INF/addon/addon-oracle.xml
  bundles/org.openhab.persistence.jdbc/src/main/resources/OH-INF/i18n/jdbc.properties
  features/openhab-addons-external/src/main/resources/conf/jdbc.cfg
Labels: bug, regression

#16753 [sunsynk] Initial contribution
  CODEOWNERS
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.sunsynk/NOTICE
  bundles/org.openhab.binding.sunsynk/README.md
  bundles/org.openhab.binding.sunsynk/pom.xml
  bundles/org.openhab.binding.sunsynk/src/main/feature/feature.xml
  bundles/org.openhab.binding.sunsynk/src/main/java/org/openhab/binding/sunsynk/internal/SunSynkBindingConstants.java
  bundles/org.openhab.binding.sunsynk/src/main/java/org/openhab/binding/sunsynk/internal/api/AccountController.java
  bundles/org.openhab.binding.sunsynk/src/main/java/org/openhab/binding/sunsynk/internal/api/DeviceController.java
  bundles/org.openhab.binding.sunsynk/src/main/java/org/openhab/binding/sunsynk/internal/api/dto/APIdata.java
  bundles/org.openhab.binding.sunsynk/src/main/java/org/openhab/binding/sunsynk/internal/api/dto/Battery.java
  bundles/org.openhab.binding.sunsynk/src/main/java/org/openhab/binding/sunsynk/internal/api/dto/Client.java
  bundles/org.openhab.binding.sunsynk/src/main/java/org/openhab/binding/sunsynk/internal/api/dto/Daytemps.java
  bundles/org.openhab.binding.sunsynk/src/main/java/org/openhab/binding/sunsynk/internal/api/dto/Daytempsreturn.java
  bundles/org.openhab.binding.sunsynk/src/main/java/org/openhab/binding/sunsynk/internal/api/dto/Details.java
  bundles/org.openhab.binding.sunsynk/src/main/java/org/openhab/binding/sunsynk/internal/api/dto/Grid.java
  bundles/org.openhab.binding.sunsynk/src/main/java/org/openhab/binding/sunsynk/internal/api/dto/Inverter.java
  bundles/org.openhab.binding.sunsynk/src/main/java/org/openhab/binding/sunsynk/internal/api/dto/RealTimeInData.java
  bundles/org.openhab.binding.sunsynk/src/main/java/org/openhab/binding/sunsynk/internal/api/dto/Settings.java
  bundles/org.openhab.binding.sunsynk/src/main/java/org/openhab/binding/sunsynk/internal/api/dto/SettingsCommand.java
  bundles/org.openhab.binding.sunsynk/src/main/java/org/openhab/binding/sunsynk/internal/api/dto/SunSynkLogin.java
  bundles/org.openhab.binding.sunsynk/src/main/java/org/openhab/binding/sunsynk/internal/api/dto/TokenRefresh.java
  bundles/org.openhab.binding.sunsynk/src/main/java/org/openhab/binding/sunsynk/internal/api/exception/SunSynkAuthenticateException.java
  bundles/org.openhab.binding.sunsynk/src/main/java/org/openhab/binding/sunsynk/internal/api/exception/SunSynkDeviceControllerException.java
  bundles/org.openhab.binding.sunsynk/src/main/java/org/openhab/binding/sunsynk/internal/api/exception/SunSynkGetStatusException.java
  bundles/org.openhab.binding.sunsynk/src/main/java/org/openhab/binding/sunsynk/internal/api/exception/SunSynkInverterDiscoveryException.java
  bundles/org.openhab.binding.sunsynk/src/main/java/org/openhab/binding/sunsynk/internal/api/exception/SunSynkSendCommandException.java
  bundles/org.openhab.binding.sunsynk/src/main/java/org/openhab/binding/sunsynk/internal/api/exception/SunSynkTokenException.java
  bundles/org.openhab.binding.sunsynk/src/main/java/org/openhab/binding/sunsynk/internal/config/SunSynkAccountConfig.java
  bundles/org.openhab.binding.sunsynk/src/main/java/org/openhab/binding/sunsynk/internal/config/SunSynkInverterConfig.java
  bundles/org.openhab.binding.sunsynk/src/main/java/org/openhab/binding/sunsynk/internal/discovery/SunSynkAccountDiscoveryService.java
  bundles/org.openhab.binding.sunsynk/src/main/java/org/openhab/binding/sunsynk/internal/handler/SunSynkAccountHandler.java
  bundles/org.openhab.binding.sunsynk/src/main/java/org/openhab/binding/sunsynk/internal/handler/SunSynkHandlerFactory.java
  bundles/org.openhab.binding.sunsynk/src/main/java/org/openhab/binding/sunsynk/internal/handler/SunSynkInverterHandler.java
  bundles/org.openhab.binding.sunsynk/src/main/resources/OH-INF/addon/addon.xml
  bundles/org.openhab.binding.sunsynk/src/main/resources/OH-INF/i18n/sunsynk.properties
  bundles/org.openhab.binding.sunsynk/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/pom.xml
Labels: new binding

#17402 [mqtt.homeassistant] Fully implement Fan component
  bundles/org.openhab.binding.mqtt.homeassistant/README.md
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/Fan.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/component/FanTests.java
Labels: enhancement

#17352 [nikohomecontrol] Add console commands
  bundles/org.openhab.binding.nikohomecontrol/README.md
  bundles/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/NikoHomeControlBindingConstants.java
  bundles/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/NikoHomeControlHandlerFactory.java
  bundles/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/console/NikoHomeControlCommandExtension.java
  bundles/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/discovery/NikoHomeControlBridgeDiscoveryService.java
  bundles/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/handler/NikoHomeControlBridgeHandler.java
  bundles/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/handler/NikoHomeControlBridgeHandler1.java
  bundles/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/handler/NikoHomeControlBridgeHandler2.java
  bundles/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/protocol/NikoHomeControlDiscover.java
  bundles/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/protocol/nhc2/NikoHomeControlCommunication2.java
Labels: enhancement

#17411 [hue] Apply 'autoUpdatePolicy=veto' on more channels
  bundles/org.openhab.binding.hue/src/main/resources/OH-INF/thing/Clip2Thing.xml
  bundles/org.openhab.binding.hue/src/main/resources/OH-INF/thing/channels.xml
Labels: enhancement

#15846 [wifiled] Support LED's that demand seperate white and color updates
  bundles/org.openhab.binding.wifiled/src/main/java/org/openhab/binding/wifiled/internal/handler/AbstractWiFiLEDDriver.java
  bundles/org.openhab.binding.wifiled/src/main/java/org/openhab/binding/wifiled/internal/handler/ClassicWiFiLEDDriver.java
Labels: enhancement, additional testing preferred

#17413 [pihole] Add channels for gravity
  bundles/org.openhab.binding.pihole/README.md
  bundles/org.openhab.binding.pihole/src/main/java/org/openhab/binding/pihole/internal/PiHoleBindingConstants.java
  bundles/org.openhab.binding.pihole/src/main/java/org/openhab/binding/pihole/internal/PiHoleHandler.java
  bundles/org.openhab.binding.pihole/src/main/java/org/openhab/binding/pihole/internal/PiHoleHandlerFactory.java
  bundles/org.openhab.binding.pihole/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.pihole/src/main/resources/OH-INF/update/gravity.xml
Labels: enhancement

#12434 [knx] Allow decoding of KNX Data Secure frames
  bundles/org.openhab.binding.knx/README.md
  bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/KNXBindingConstants.java
  bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/client/AbstractKNXClient.java
  bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/client/CustomManagementClientImpl.java
  bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/client/CustomManagementProceduresImpl.java
  bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/client/CustomSecureManagement.java
  bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/client/IPClient.java
  bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/client/SerialClient.java
  bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/config/BridgeConfiguration.java
  bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/config/IPBridgeConfiguration.java
  bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/handler/IPBridgeThingHandler.java
  bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/handler/KNXBridgeBaseThingHandler.java
  bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/handler/SerialBridgeThingHandler.java
  bundles/org.openhab.binding.knx/src/main/resources/OH-INF/i18n/knx.properties
  bundles/org.openhab.binding.knx/src/main/resources/OH-INF/thing/ip.xml
  bundles/org.openhab.binding.knx/src/main/resources/OH-INF/thing/serial.xml
  bundles/org.openhab.binding.knx/src/test/java/org/openhab/binding/knx/internal/client/DummyClient.java
  bundles/org.openhab.binding.knx/src/test/java/org/openhab/binding/knx/internal/handler/KNXBridgeBaseThingHandlerTest.java
  bundles/org.openhab.binding.knx/src/test/java/org/openhab/binding/knx/internal/security/KNXSecurityTest.java
  bundles/org.openhab.binding.knx/src/test/resources/misc/openhab6-minimal-ipif.knxkeys
  bundles/org.openhab.binding.knx/src/test/resources/misc/openhab6-minimal-sipif.knxkeys
  bundles/org.openhab.binding.knx/src/test/resources/misc/openhab6-minimal-sipr.knxkeys
  bundles/org.openhab.binding.knx/src/test/resources/misc/openhab6.knxkeys
Labels: enhancement

#17424 [jsscripting] Upgrade to openhab-js 5.6.0
  bundles/org.openhab.automation.jsscripting/README.md
  bundles/org.openhab.automation.jsscripting/pom.xml
Labels: enhancement

#17421 [unifi] Fix `NullPointerException`
  bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/handler/UniFiPoePortThingHandler.java
Labels: bug

#17390 [homematic] Fix `NullPointerException` in discovery
  bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/discovery/HomematicDeviceDiscoveryService.java
  bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/handler/HomematicBridgeHandler.java
Labels: bug

#17423 [kaleidescape] Add movie end time and music title channels
  bundles/org.openhab.binding.kaleidescape/README.md
  bundles/org.openhab.binding.kaleidescape/src/main/java/org/openhab/binding/kaleidescape/internal/KaleidescapeBindingConstants.java
  bundles/org.openhab.binding.kaleidescape/src/main/java/org/openhab/binding/kaleidescape/internal/handler/KaleidescapeHandler.java
  bundles/org.openhab.binding.kaleidescape/src/main/java/org/openhab/binding/kaleidescape/internal/handler/KaleidescapeMessageHandler.java
  bundles/org.openhab.binding.kaleidescape/src/main/resources/OH-INF/i18n/kaleidescape.properties
  bundles/org.openhab.binding.kaleidescape/src/main/resources/OH-INF/thing/channels.xml
  bundles/org.openhab.binding.kaleidescape/src/main/resources/OH-INF/update/instructions.xml
Labels: enhancement

#17427 [miio] add Xiaomi Robot Vacuum X10 (dreame.vacuum.r2209)
  bundles/org.openhab.binding.miio/README.md
  bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/MiIoDevices.java
  bundles/org.openhab.binding.miio/src/main/resources/OH-INF/i18n/basic.properties
  bundles/org.openhab.binding.miio/src/main/resources/database/dreame.vacuum.r2209-miot.json
Labels: enhancement

#17428 [groovyscripting] Update Groovy to 4.0.23
  bundles/org.openhab.automation.groovyscripting/README.md
  bundles/org.openhab.automation.groovyscripting/pom.xml
Labels: enhancement

#17430 [gce] Fix `NullPointerException`
  bundles/org.openhab.binding.gce/src/main/java/org/openhab/binding/gce/internal/handler/Ipx800DeviceConnector.java
Labels: bug

#17394 [smaenergymeter] Fix `IllegalStateException`
  bundles/org.openhab.binding.smaenergymeter/src/main/java/org/openhab/binding/smaenergymeter/internal/SMAEnergyMeterHandlerFactory.java
  bundles/org.openhab.binding.smaenergymeter/src/main/java/org/openhab/binding/smaenergymeter/internal/discovery/SMAEnergyMeterDiscoveryService.java
  bundles/org.openhab.binding.smaenergymeter/src/main/java/org/openhab/binding/smaenergymeter/internal/handler/EnergyMeter.java
  bundles/org.openhab.binding.smaenergymeter/src/main/java/org/openhab/binding/smaenergymeter/internal/handler/SMAEnergyMeterHandler.java
  bundles/org.openhab.binding.smaenergymeter/src/main/java/org/openhab/binding/smaenergymeter/internal/packet/DefaultPacketListenerRegistry.java
  bundles/org.openhab.binding.smaenergymeter/src/main/java/org/openhab/binding/smaenergymeter/internal/packet/PacketListener.java
Labels: bug

#17440 [hue] Room / Zone Things no longer re-appear in Inbox
  bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/Clip2ThingHandler.java
Labels: bug

#17447 [mqtt.homeassistant] Remove channels for no-longer-configured components
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/HaID.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/handler/HomeAssistantThingHandler.java
Labels: enhancement

#17449 [rrd4j] Avoid RrdDb.getRrdDef calls
  bundles/org.openhab.persistence.rrd4j/src/main/java/org/openhab/persistence/rrd4j/internal/RRD4jPersistenceService.java
Labels: enhancement

#17448 [netatmo] Prevent `IndexOutOfBoundsException`
  bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/api/SecurityApi.java
  bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/capability/SecurityCapability.java
Labels: bug

#17452 [mqtt.homeassistant] Include the details of JSON syntax errors when parsing fails
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/config/dto/AbstractChannelConfiguration.java
Labels: enhancement

#16298 [fpp] Initial contribution
  CODEOWNERS
  bundles/org.openhab.binding.mqtt.fpp/NOTICE
  bundles/org.openhab.binding.mqtt.fpp/README.md
  bundles/org.openhab.binding.mqtt.fpp/pom.xml
  bundles/org.openhab.binding.mqtt.fpp/src/main/feature/feature.xml
  bundles/org.openhab.binding.mqtt.fpp/src/main/java/org/openhab/binding/mqtt/fpp/internal/ConfigOptions.java
  bundles/org.openhab.binding.mqtt.fpp/src/main/java/org/openhab/binding/mqtt/fpp/internal/FPPBindingConstants.java
  bundles/org.openhab.binding.mqtt.fpp/src/main/java/org/openhab/binding/mqtt/fpp/internal/FPPHandlerFactory.java
  bundles/org.openhab.binding.mqtt.fpp/src/main/java/org/openhab/binding/mqtt/fpp/internal/FPPStatus.java
  bundles/org.openhab.binding.mqtt.fpp/src/main/java/org/openhab/binding/mqtt/fpp/internal/dto/FPPCurrentPlaylist.java
  bundles/org.openhab.binding.mqtt.fpp/src/main/java/org/openhab/binding/mqtt/fpp/internal/dto/FPPNextPlaylist.java
  bundles/org.openhab.binding.mqtt.fpp/src/main/java/org/openhab/binding/mqtt/fpp/internal/dto/FPPPlaylist.java
  bundles/org.openhab.binding.mqtt.fpp/src/main/java/org/openhab/binding/mqtt/fpp/internal/dto/FPPScheduler.java
  bundles/org.openhab.binding.mqtt.fpp/src/main/java/org/openhab/binding/mqtt/fpp/internal/handler/FPPPlayerHandler.java
  bundles/org.openhab.binding.mqtt.fpp/src/main/resources/OH-INF/config/config.xml
  bundles/org.openhab.binding.mqtt.fpp/src/main/resources/OH-INF/i18n/mqtt.properties
  bundles/org.openhab.binding.mqtt.fpp/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/pom.xml
  features/openhab-addons/src/main/resources/footer.xml
Labels: new binding

#17453 [nibeuplink] Remove binding
  CODEOWNERS
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.nibeuplink/NOTICE
  bundles/org.openhab.binding.nibeuplink/README.md
  bundles/org.openhab.binding.nibeuplink/pom.xml
  bundles/org.openhab.binding.nibeuplink/src/main/feature/feature.xml
  bundles/org.openhab.binding.nibeuplink/src/main/java/org/openhab/binding/nibeuplink/internal/AtomicReferenceTrait.java
  bundles/org.openhab.binding.nibeuplink/src/main/java/org/openhab/binding/nibeuplink/internal/NibeUplinkBindingConstants.java
  bundles/org.openhab.binding.nibeuplink/src/main/java/org/openhab/binding/nibeuplink/internal/NibeUplinkHandlerFactory.java
  bundles/org.openhab.binding.nibeuplink/src/main/java/org/openhab/binding/nibeuplink/internal/callback/AbstractUplinkCommandCallback.java
  bundles/org.openhab.binding.nibeuplink/src/main/java/org/openhab/binding/nibeuplink/internal/command/GenericStatusUpdate.java
  bundles/org.openhab.binding.nibeuplink/src/main/java/org/openhab/binding/nibeuplink/internal/command/Login.java
  bundles/org.openhab.binding.nibeuplink/src/main/java/org/openhab/binding/nibeuplink/internal/command/NibeUplinkCommand.java
  bundles/org.openhab.binding.nibeuplink/src/main/java/org/openhab/binding/nibeuplink/internal/command/UpdateSetting.java
  bundles/org.openhab.binding.nibeuplink/src/main/java/org/openhab/binding/nibeuplink/internal/config/NibeUplinkConfiguration.java
  bundles/org.openhab.binding.nibeuplink/src/main/java/org/openhab/binding/nibeuplink/internal/connector/CommunicationStatus.java
  bundles/org.openhab.binding.nibeuplink/src/main/java/org/openhab/binding/nibeuplink/internal/connector/StatusUpdateListener.java
  bundles/org.openhab.binding.nibeuplink/src/main/java/org/openhab/binding/nibeuplink/internal/connector/UplinkWebInterface.java
  bundles/org.openhab.binding.nibeuplink/src/main/java/org/openhab/binding/nibeuplink/internal/handler/ChannelProvider.java
  bundles/org.openhab.binding.nibeuplink/src/main/java/org/openhab/binding/nibeuplink/internal/handler/ChannelUtil.java
  bundles/org.openhab.binding.nibeuplink/src/main/java/org/openhab/binding/nibeuplink/internal/handler/GenericHandler.java
  bundles/org.openhab.binding.nibeuplink/src/main/java/org/openhab/binding/nibeuplink/internal/handler/NibeUplinkHandler.java
  bundles/org.openhab.binding.nibeuplink/src/main/java/org/openhab/binding/nibeuplink/internal/handler/UplinkBaseHandler.java
  bundles/org.openhab.binding.nibeuplink/src/main/java/org/openhab/binding/nibeuplink/internal/handler/UplinkPolling.java
  bundles/org.openhab.binding.nibeuplink/src/main/java/org/openhab/binding/nibeuplink/internal/model/ChannelGroup.java
  bundles/org.openhab.binding.nibeuplink/src/main/java/org/openhab/binding/nibeuplink/internal/model/ConfigurationException.java
  bundles/org.openhab.binding.nibeuplink/src/main/java/org/openhab/binding/nibeuplink/internal/model/DataResponse.java
  bundles/org.openhab.binding.nibeuplink/src/main/java/org/openhab/binding/nibeuplink/internal/model/DataResponseTransformer.java
  bundles/org.openhab.binding.nibeuplink/src/main/java/org/openhab/binding/nibeuplink/internal/model/GenericDataResponse.java
  bundles/org.openhab.binding.nibeuplink/src/main/java/org/openhab/binding/nibeuplink/internal/model/ValidationException.java
  bundles/org.openhab.binding.nibeuplink/src/main/resources/OH-INF/addon/addon.xml
  bundles/org.openhab.binding.nibeuplink/src/main/resources/OH-INF/config/config.xml
  bundles/org.openhab.binding.nibeuplink/src/main/resources/OH-INF/i18n/nibeuplink.properties
  bundles/org.openhab.binding.nibeuplink/src/main/resources/OH-INF/i18n/nibeuplink_de.properties
  bundles/org.openhab.binding.nibeuplink/src/main/resources/OH-INF/thing/base-channel-groups.xml
  bundles/org.openhab.binding.nibeuplink/src/main/resources/OH-INF/thing/f1145-channel-groups.xml
  bundles/org.openhab.binding.nibeuplink/src/main/resources/OH-INF/thing/f1145-thing.xml
  bundles/org.openhab.binding.nibeuplink/src/main/resources/OH-INF/thing/f1155-channel-groups.xml
  bundles/org.openhab.binding.nibeuplink/src/main/resources/OH-INF/thing/f1155-thing.xml
  bundles/org.openhab.binding.nibeuplink/src/main/resources/OH-INF/thing/f730-channel-groups.xml
  bundles/org.openhab.binding.nibeuplink/src/main/resources/OH-INF/thing/f730-thing.xml
  bundles/org.openhab.binding.nibeuplink/src/main/resources/OH-INF/thing/f750-channel-groups.xml
  bundles/org.openhab.binding.nibeuplink/src/main/resources/OH-INF/thing/f750-thing.xml
  bundles/org.openhab.binding.nibeuplink/src/main/resources/OH-INF/thing/readonly-channel-types.xml
  bundles/org.openhab.binding.nibeuplink/src/main/resources/OH-INF/thing/readwrite-channel-types.xml
  bundles/org.openhab.binding.nibeuplink/src/main/resources/OH-INF/thing/vvm310-channel-groups.xml
  bundles/org.openhab.binding.nibeuplink/src/main/resources/OH-INF/thing/vvm310-thing.xml
  bundles/org.openhab.binding.nibeuplink/src/main/resources/OH-INF/thing/vvm320-channel-groups.xml
  bundles/org.openhab.binding.nibeuplink/src/main/resources/OH-INF/thing/vvm320-thing.xml
  bundles/pom.xml
Labels: enhancement

#17460 [solax] Update README.md
  bundles/org.openhab.binding.solax/README.md
Labels: documentation

#17412 [mqtt.homeassistant] Update Jinjava to 2.7.3
  bundles/org.openhab.binding.mqtt.homeassistant/pom.xml
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/feature/feature.xml
  bundles/org.openhab.transform.jinja/pom.xml
  bundles/org.openhab.transform.jinja/src/main/feature/feature.xml
  features/openhab-addons/src/main/resources/footer.xml
  itests/org.openhab.binding.mqtt.homeassistant.tests/itest.bndrun
Labels: bug

#17458 [smsmodem] Update README.md with devices
  bundles/org.openhab.binding.smsmodem/README.md
Labels: documentation

#17454 [samsungtv] Fix `NullPointerException`
  bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/service/SmartThingsApiService.java
Labels: bug

#17463 [benqprojector] Set autoUpdatePolicy for directcmd channel
  bundles/org.openhab.binding.benqprojector/README.md
  bundles/org.openhab.binding.benqprojector/src/main/resources/OH-INF/thing/thing-types.xml
Labels: enhancement

#17464 [epsonprojector] Set autoUpdatePolicy for keycode channel
  bundles/org.openhab.binding.epsonprojector/README.md
  bundles/org.openhab.binding.epsonprojector/src/main/resources/OH-INF/thing/thing-types.xml
Labels: enhancement

#17462 [atlona] Set autoUpdatePolicy for WriteOnly channels
  bundles/org.openhab.binding.atlona/src/main/resources/OH-INF/thing/thing-types.xml
Labels: enhancement

#17465 [nuvo] Set autoUpdatePolicy for WriteOnly channels
  bundles/org.openhab.binding.nuvo/README.md
  bundles/org.openhab.binding.nuvo/src/main/resources/OH-INF/thing/channels.xml
Labels: enhancement

#17467 [panasonicbdp] Set autoUpdatePolicy for button channel
  bundles/org.openhab.binding.panasonicbdp/README.md
  bundles/org.openhab.binding.panasonicbdp/src/main/resources/OH-INF/thing/bdplayer.xml
  bundles/org.openhab.binding.panasonicbdp/src/main/resources/OH-INF/thing/uhdplayer.xml
Labels: enhancement

#17466 [oppo] Set autoUpdatePolicy for remote_button channel
  bundles/org.openhab.binding.oppo/README.md
  bundles/org.openhab.binding.oppo/src/main/resources/OH-INF/thing/channels.xml
Labels: enhancement

#17468 [roku] Set autoUpdatePolicy for button channel
  bundles/org.openhab.binding.roku/README.md
  bundles/org.openhab.binding.roku/src/main/resources/OH-INF/thing/roku.xml
Labels: enhancement

#17469 [tivo] Set autoUpdatePolicy for WriteOnly channels
  bundles/org.openhab.binding.tivo/README.md
  bundles/org.openhab.binding.tivo/src/main/resources/OH-INF/thing/thing-types.xml
Labels: enhancement

#17470 [vizio] Set autoUpdatePolicy for button channel
  bundles/org.openhab.binding.vizio/README.md
  bundles/org.openhab.binding.vizio/src/main/resources/OH-INF/thing/vizio.xml
Labels: enhancement

#17435 [mqtt.homeassistant] implement iif and is_defined jinja function and filters
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/generic/internal/MqttThingHandlerFactory.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/HomeAssistantChannelTransformation.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/HomeAssistantJinjaFunctionLibrary.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/HomeAssistantChannelTransformationTests.java
Labels: enhancement

#17457 [modbus] Discard data if transformation failed
  bundles/org.openhab.binding.modbus/src/main/java/org/openhab/binding/modbus/internal/ModbusTransformation.java
  bundles/org.openhab.binding.modbus/src/test/java/org/openhab/binding/modbus/internal/ModbusTransformationTest.java
Labels: enhancement

#17368 [samsungtv] Add artOrientatation channel
  bundles/org.openhab.binding.samsungtv/README.md
  bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/SamsungTvBindingConstants.java
  bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/config/SamsungTvConfiguration.java
  bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/handler/SamsungTvHandler.java
  bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/protocol/WebSocketArt.java
  bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/service/RemoteControllerService.java
  bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/service/SmartThingsApiService.java
  bundles/org.openhab.binding.samsungtv/src/main/resources/OH-INF/config/config.xml
  bundles/org.openhab.binding.samsungtv/src/main/resources/OH-INF/thing/channel-types.xml
  bundles/org.openhab.binding.samsungtv/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.samsungtv/src/main/resources/OH-INF/update/instructions.xml
Labels: enhancement

#17400 [mqtt.homeassistant] Fix jinja usage in availability templates
  bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/AbstractMQTTThingHandler.java
  bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/AvailabilityTracker.java
  bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/internal/handler/GenericMQTTThingHandler.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/ComponentChannel.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/AbstractComponent.java
  bundles/org.openhab.binding.mqtt.homie/src/main/java/org/openhab/binding/mqtt/homie/internal/handler/HomieThingHandler.java
Labels: bug

#17365 [emotiva] Fix missing data in source channels
  bundles/org.openhab.binding.emotiva/src/main/java/org/openhab/binding/emotiva/internal/EmotivaBindingConstants.java
  bundles/org.openhab.binding.emotiva/src/main/java/org/openhab/binding/emotiva/internal/EmotivaCommandHelper.java
  bundles/org.openhab.binding.emotiva/src/main/java/org/openhab/binding/emotiva/internal/EmotivaProcessorHandler.java
  bundles/org.openhab.binding.emotiva/src/main/java/org/openhab/binding/emotiva/internal/EmotivaProcessorState.java
  bundles/org.openhab.binding.emotiva/src/main/java/org/openhab/binding/emotiva/internal/EmotivaUdpReceivingService.java
  bundles/org.openhab.binding.emotiva/src/main/java/org/openhab/binding/emotiva/internal/EmotivaUdpSendingService.java
  bundles/org.openhab.binding.emotiva/src/main/java/org/openhab/binding/emotiva/internal/InputStateOptionProvider.java
  bundles/org.openhab.binding.emotiva/src/main/java/org/openhab/binding/emotiva/internal/dto/EmotivaSubscriptionRequest.java
  bundles/org.openhab.binding.emotiva/src/main/java/org/openhab/binding/emotiva/internal/dto/EmotivaUnsubscribeDTO.java
  bundles/org.openhab.binding.emotiva/src/main/java/org/openhab/binding/emotiva/internal/protocol/EmotivaControlRequest.java
  bundles/org.openhab.binding.emotiva/src/main/java/org/openhab/binding/emotiva/internal/protocol/EmotivaSubscriptionTags.java
  bundles/org.openhab.binding.emotiva/src/test/java/org/openhab/binding/emotiva/internal/EmotivaCommandHelperTest.java
  bundles/org.openhab.binding.emotiva/src/test/java/org/openhab/binding/emotiva/internal/EmotivaProcessorStateTest.java
  bundles/org.openhab.binding.emotiva/src/test/java/org/openhab/binding/emotiva/internal/dto/EmotivaSubscriptionRequestTest.java
  bundles/org.openhab.binding.emotiva/src/test/java/org/openhab/binding/emotiva/internal/dto/EmotivaUnsubscriptionTest.java
  bundles/org.openhab.binding.emotiva/src/test/java/org/openhab/binding/emotiva/internal/protocol/EmotivaControlRequestTest.java
Labels: bug

#17472 [pushbullet] Add link and file push type support
  bundles/org.openhab.binding.pushbullet/README.md
  bundles/org.openhab.binding.pushbullet/src/main/java/org/openhab/binding/pushbullet/internal/PushbulletBindingConstants.java
  bundles/org.openhab.binding.pushbullet/src/main/java/org/openhab/binding/pushbullet/internal/PushbulletConfiguration.java
  bundles/org.openhab.binding.pushbullet/src/main/java/org/openhab/binding/pushbullet/internal/PushbulletHandlerFactory.java
  bundles/org.openhab.binding.pushbullet/src/main/java/org/openhab/binding/pushbullet/internal/PushbulletHttpClient.java
  bundles/org.openhab.binding.pushbullet/src/main/java/org/openhab/binding/pushbullet/internal/action/PushbulletActions.java
  bundles/org.openhab.binding.pushbullet/src/main/java/org/openhab/binding/pushbullet/internal/exception/PushbulletApiException.java
  bundles/org.openhab.binding.pushbullet/src/main/java/org/openhab/binding/pushbullet/internal/exception/PushbulletAuthenticationException.java
  bundles/org.openhab.binding.pushbullet/src/main/java/org/openhab/binding/pushbullet/internal/handler/PushbulletHandler.java
  bundles/org.openhab.binding.pushbullet/src/main/java/org/openhab/binding/pushbullet/internal/model/InstantDeserializer.java
  bundles/org.openhab.binding.pushbullet/src/main/java/org/openhab/binding/pushbullet/internal/model/Push.java
  bundles/org.openhab.binding.pushbullet/src/main/java/org/openhab/binding/pushbullet/internal/model/PushError.java
  bundles/org.openhab.binding.pushbullet/src/main/java/org/openhab/binding/pushbullet/internal/model/PushRequest.java
  bundles/org.openhab.binding.pushbullet/src/main/java/org/openhab/binding/pushbullet/internal/model/PushResponse.java
  bundles/org.openhab.binding.pushbullet/src/main/java/org/openhab/binding/pushbullet/internal/model/PushType.java
  bundles/org.openhab.binding.pushbullet/src/main/java/org/openhab/binding/pushbullet/internal/model/UploadRequest.java
  bundles/org.openhab.binding.pushbullet/src/main/java/org/openhab/binding/pushbullet/internal/model/UploadResponse.java
  bundles/org.openhab.binding.pushbullet/src/main/java/org/openhab/binding/pushbullet/internal/model/User.java
  bundles/org.openhab.binding.pushbullet/src/main/resources/OH-INF/addon/addon.xml
  bundles/org.openhab.binding.pushbullet/src/main/resources/OH-INF/i18n/pushbullet.properties
  bundles/org.openhab.binding.pushbullet/src/main/resources/OH-INF/thing/thing-types.xml
Labels: enhancement

#17479 [wemo] Disable wemo itest to fix build issue
  itests/org.openhab.binding.wemo.tests/src/main/java/org/openhab/binding/wemo/internal/handler/test/WemoMakerHandlerOSGiTest.java
Labels: test

#17483 Remove space before colon
  bundles/org.openhab.binding.androiddebugbridge/README.md
  bundles/org.openhab.binding.ephemeris/README.md
  bundles/org.openhab.binding.loxone/README.md
  bundles/org.openhab.binding.mycroft/README.md
  bundles/org.openhab.binding.mynice/README.md
  bundles/org.openhab.binding.netatmo/README.md
  bundles/org.openhab.binding.nikobus/README.md
  bundles/org.openhab.binding.openuv/README.md
  bundles/org.openhab.binding.openwebnet/README.md
  bundles/org.openhab.binding.smsmodem/README.md
  bundles/org.openhab.binding.sncf/README.md
  bundles/org.openhab.binding.synopanalyzer/README.md
  bundles/org.openhab.binding.teleinfo/README.md
  bundles/org.openhab.binding.vektiva/README.md
  bundles/org.openhab.binding.vigicrues/README.md
  bundles/org.openhab.binding.xmltv/README.md
  bundles/org.openhab.binding.yamahamusiccast/README.md
  bundles/org.openhab.io.openhabcloud/README.md
  bundles/org.openhab.transform.scale/README.md
  bundles/org.openhab.voice.mimictts/README.md
Labels: documentation

#17480 Make Markdown code block languages consistent
  bundles/org.openhab.automation.groovyscripting/README.md
  bundles/org.openhab.automation.jsscriptingnashorn/README.md
  bundles/org.openhab.binding.amazonechocontrol/README.md
  bundles/org.openhab.binding.argoclima/README.md
  bundles/org.openhab.binding.avmfritz/README.md
  bundles/org.openhab.binding.bigassfan/README.md
  bundles/org.openhab.binding.daikin/README.md
  bundles/org.openhab.binding.dbquery/README.md
  bundles/org.openhab.binding.emotiva/README.md
  bundles/org.openhab.binding.fenecon/README.md
  bundles/org.openhab.binding.flume/README.md
  bundles/org.openhab.binding.globalcache/README.md
  bundles/org.openhab.binding.growatt/README.md
  bundles/org.openhab.binding.hdpowerview/README.md
  bundles/org.openhab.binding.hue/README.md
  bundles/org.openhab.binding.hue/doc/readme_v1.md
  bundles/org.openhab.binding.hue/doc/readme_v2.md
  bundles/org.openhab.binding.icloud/README.md
  bundles/org.openhab.binding.insteon/README.md
  bundles/org.openhab.binding.loxone/README.md
  bundles/org.openhab.binding.mercedesme/README.md
  bundles/org.openhab.binding.miele/README.md
  bundles/org.openhab.binding.nanoleaf/README.md
  bundles/org.openhab.binding.network/README.md
  bundles/org.openhab.binding.oceanic/README.md
  bundles/org.openhab.binding.onkyo/README.md
  bundles/org.openhab.binding.pioneeravr/README.md
  bundles/org.openhab.binding.pulseaudio/README.md
  bundles/org.openhab.binding.radiobrowser/README.md
  bundles/org.openhab.binding.solarman/README.md
  bundles/org.openhab.binding.telegram/README.md
  bundles/org.openhab.binding.velux/README.md
  bundles/org.openhab.binding.yamahareceiver/README.md
  bundles/org.openhab.transform.jsonpath/README.md
  bundles/org.openhab.transform.regex/README.md
  bundles/org.openhab.transform.xpath/README.md
  bundles/org.openhab.voice.pipertts/README.md
  bundles/org.openhab.voice.rustpotterks/README.md
  bundles/org.openhab.voice.voskstt/README.md
Labels: documentation
