Repository openhab/openhab-addons, pull requests merged in 2024-12, with the labels that each got.

#17753 [mercedesme] Websocket decoupling
  bundles/org.openhab.binding.mercedesme/src/main/java/org/openhab/binding/mercedesme/internal/handler/AccountHandler.java
  bundles/org.openhab.binding.mercedesme/src/main/java/org/openhab/binding/mercedesme/internal/handler/VehicleHandler.java
  bundles/org.openhab.binding.mercedesme/src/main/java/org/openhab/binding/mercedesme/internal/server/MBWebsocket.java
  bundles/org.openhab.binding.mercedesme/src/test/java/org/openhab/binding/mercedesme/internal/handler/ThingCallbackListener.java
  bundles/org.openhab.binding.mercedesme/src/test/java/org/openhab/binding/mercedesme/internal/handler/VehicleHandlerTest.java
Labels: enhancement

#17830 [knx] Upgrade calimero-device to 2.6-rc1
  bundles/org.openhab.binding.knx/pom.xml
Labels: bug

#17831 [mqtt.homeassistant] Implement Device Tracker
  bundles/org.openhab.binding.mqtt.homeassistant/README.md
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/ComponentChannelType.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/AbstractComponent.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/ComponentFactory.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/DeviceTracker.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/resources/OH-INF/i18n/mqtt.properties
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/resources/OH-INF/thing/homeassistant-channels.xml
  bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/component/DeviceTrackerTests.java
Labels: enhancement

#15296 [veSync] 131 and Vital Purifiers base support
  bundles/org.openhab.binding.vesync/README.md
  bundles/org.openhab.binding.vesync/src/main/java/org/openhab/binding/vesync/internal/VeSyncConstants.java
  bundles/org.openhab.binding.vesync/src/main/java/org/openhab/binding/vesync/internal/VeSyncHandlerFactory.java
  bundles/org.openhab.binding.vesync/src/main/java/org/openhab/binding/vesync/internal/api/IHttpClientProvider.java
  bundles/org.openhab.binding.vesync/src/main/java/org/openhab/binding/vesync/internal/api/VeSyncV2ApiHelper.java
  bundles/org.openhab.binding.vesync/src/main/java/org/openhab/binding/vesync/internal/dto/requests/VeSyncProtocolConstants.java
  bundles/org.openhab.binding.vesync/src/main/java/org/openhab/binding/vesync/internal/dto/requests/VeSyncRequest.java
  bundles/org.openhab.binding.vesync/src/main/java/org/openhab/binding/vesync/internal/dto/requests/VeSyncRequestManagedDeviceBypassV2.java
  bundles/org.openhab.binding.vesync/src/main/java/org/openhab/binding/vesync/internal/dto/requests/VeSyncRequestV1Command.java
  bundles/org.openhab.binding.vesync/src/main/java/org/openhab/binding/vesync/internal/dto/requests/VeSyncRequestV1ManagedDeviceDetails.java
  bundles/org.openhab.binding.vesync/src/main/java/org/openhab/binding/vesync/internal/dto/requests/VeSyncRequestV1SetLevel.java
  bundles/org.openhab.binding.vesync/src/main/java/org/openhab/binding/vesync/internal/dto/requests/VeSyncRequestV1SetMode.java
  bundles/org.openhab.binding.vesync/src/main/java/org/openhab/binding/vesync/internal/dto/requests/VeSyncRequestV1SetStatus.java
  bundles/org.openhab.binding.vesync/src/main/java/org/openhab/binding/vesync/internal/dto/responses/VeSyncV2BypassPurifierStatus.java
  bundles/org.openhab.binding.vesync/src/main/java/org/openhab/binding/vesync/internal/dto/responses/VeSyncV2Ver2BypassHumidifierStatus.java
  bundles/org.openhab.binding.vesync/src/main/java/org/openhab/binding/vesync/internal/dto/responses/VeSyncV2Ver2BypassPurifierStatus.java
  bundles/org.openhab.binding.vesync/src/main/java/org/openhab/binding/vesync/internal/dto/responses/v1/VeSyncV1AirPurifierDeviceDetailsResponse.java
  bundles/org.openhab.binding.vesync/src/main/java/org/openhab/binding/vesync/internal/handlers/VeSyncBaseDeviceHandler.java
  bundles/org.openhab.binding.vesync/src/main/java/org/openhab/binding/vesync/internal/handlers/VeSyncBridgeHandler.java
  bundles/org.openhab.binding.vesync/src/main/java/org/openhab/binding/vesync/internal/handlers/VeSyncDeviceAirHumidifierHandler.java
  bundles/org.openhab.binding.vesync/src/main/java/org/openhab/binding/vesync/internal/handlers/VeSyncDeviceAirPurifierHandler.java
  bundles/org.openhab.binding.vesync/src/main/java/org/openhab/binding/vesync/internal/handlers/VeSyncDeviceHumidifierMetadata.java
  bundles/org.openhab.binding.vesync/src/main/java/org/openhab/binding/vesync/internal/handlers/VeSyncDeviceMetadata.java
  bundles/org.openhab.binding.vesync/src/main/java/org/openhab/binding/vesync/internal/handlers/VeSyncDevicePurifierMetadata.java
  bundles/org.openhab.binding.vesync/src/main/resources/OH-INF/i18n/vesync.properties
  bundles/org.openhab.binding.vesync/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.vesync/src/main/resources/OH-INF/update/air-humidifier-instructions.xml
  bundles/org.openhab.binding.vesync/src/main/resources/OH-INF/update/air-purifier-instructions.xml
Labels: enhancement

#17451 [myuplink] Initial contribution
  CODEOWNERS
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.myuplink/NOTICE
  bundles/org.openhab.binding.myuplink/README.md
  bundles/org.openhab.binding.myuplink/pom.xml
  bundles/org.openhab.binding.myuplink/src/main/feature/feature.xml
  bundles/org.openhab.binding.myuplink/src/main/java/org/openhab/binding/myuplink/internal/AtomicReferenceTrait.java
  bundles/org.openhab.binding.myuplink/src/main/java/org/openhab/binding/myuplink/internal/MyUplinkBindingConstants.java
  bundles/org.openhab.binding.myuplink/src/main/java/org/openhab/binding/myuplink/internal/MyUplinkHandlerFactory.java
  bundles/org.openhab.binding.myuplink/src/main/java/org/openhab/binding/myuplink/internal/Utils.java
  bundles/org.openhab.binding.myuplink/src/main/java/org/openhab/binding/myuplink/internal/command/AbstractCommand.java
  bundles/org.openhab.binding.myuplink/src/main/java/org/openhab/binding/myuplink/internal/command/AbstractPagingCommand.java
  bundles/org.openhab.binding.myuplink/src/main/java/org/openhab/binding/myuplink/internal/command/AbstractWriteCommand.java
  bundles/org.openhab.binding.myuplink/src/main/java/org/openhab/binding/myuplink/internal/command/JsonResultProcessor.java
  bundles/org.openhab.binding.myuplink/src/main/java/org/openhab/binding/myuplink/internal/command/MyUplinkCommand.java
  bundles/org.openhab.binding.myuplink/src/main/java/org/openhab/binding/myuplink/internal/command/account/GetSystems.java
  bundles/org.openhab.binding.myuplink/src/main/java/org/openhab/binding/myuplink/internal/command/account/Login.java
  bundles/org.openhab.binding.myuplink/src/main/java/org/openhab/binding/myuplink/internal/command/device/GetPoints.java
  bundles/org.openhab.binding.myuplink/src/main/java/org/openhab/binding/myuplink/internal/command/device/GetSmartHomeMode.java
  bundles/org.openhab.binding.myuplink/src/main/java/org/openhab/binding/myuplink/internal/command/device/SetPoints.java
  bundles/org.openhab.binding.myuplink/src/main/java/org/openhab/binding/myuplink/internal/command/device/SetPointsAdvanced.java
  bundles/org.openhab.binding.myuplink/src/main/java/org/openhab/binding/myuplink/internal/command/device/SetSmartHomeMode.java
  bundles/org.openhab.binding.myuplink/src/main/java/org/openhab/binding/myuplink/internal/config/MyUplinkConfiguration.java
  bundles/org.openhab.binding.myuplink/src/main/java/org/openhab/binding/myuplink/internal/connector/CommunicationStatus.java
  bundles/org.openhab.binding.myuplink/src/main/java/org/openhab/binding/myuplink/internal/connector/WebInterface.java
  bundles/org.openhab.binding.myuplink/src/main/java/org/openhab/binding/myuplink/internal/discovery/MyUplinkDiscoveryService.java
  bundles/org.openhab.binding.myuplink/src/main/java/org/openhab/binding/myuplink/internal/handler/ChannelProvider.java
  bundles/org.openhab.binding.myuplink/src/main/java/org/openhab/binding/myuplink/internal/handler/DynamicChannelProvider.java
  bundles/org.openhab.binding.myuplink/src/main/java/org/openhab/binding/myuplink/internal/handler/MyUplinkAccountHandler.java
  bundles/org.openhab.binding.myuplink/src/main/java/org/openhab/binding/myuplink/internal/handler/MyUplinkBridgeHandler.java
  bundles/org.openhab.binding.myuplink/src/main/java/org/openhab/binding/myuplink/internal/handler/MyUplinkGenericDeviceHandler.java
  bundles/org.openhab.binding.myuplink/src/main/java/org/openhab/binding/myuplink/internal/handler/MyUplinkThingHandler.java
  bundles/org.openhab.binding.myuplink/src/main/java/org/openhab/binding/myuplink/internal/handler/StatusHandler.java
  bundles/org.openhab.binding.myuplink/src/main/java/org/openhab/binding/myuplink/internal/model/ConfigurationException.java
  bundles/org.openhab.binding.myuplink/src/main/java/org/openhab/binding/myuplink/internal/model/GenericResponseTransformer.java
  bundles/org.openhab.binding.myuplink/src/main/java/org/openhab/binding/myuplink/internal/model/ResponseTransformer.java
  bundles/org.openhab.binding.myuplink/src/main/java/org/openhab/binding/myuplink/internal/model/SmartHomeModeResponseTransformer.java
  bundles/org.openhab.binding.myuplink/src/main/java/org/openhab/binding/myuplink/internal/model/ValidationException.java
  bundles/org.openhab.binding.myuplink/src/main/java/org/openhab/binding/myuplink/internal/provider/ChannelFactory.java
  bundles/org.openhab.binding.myuplink/src/main/java/org/openhab/binding/myuplink/internal/provider/MyUplinkChannelTypeProvider.java
  bundles/org.openhab.binding.myuplink/src/main/resources/OH-INF/addon/addon.xml
  bundles/org.openhab.binding.myuplink/src/main/resources/OH-INF/config/config.xml
  bundles/org.openhab.binding.myuplink/src/main/resources/OH-INF/i18n/myuplink.properties
  bundles/org.openhab.binding.myuplink/src/main/resources/OH-INF/thing/readonly-channel-types.xml
  bundles/org.openhab.binding.myuplink/src/main/resources/OH-INF/thing/readwrite-channel-types.xml
  bundles/org.openhab.binding.myuplink/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.myuplink/src/test/java/org/openhab/binding/myuplink/internal/discovery/MyUplinkDiscoveryServiceTest.java
  bundles/org.openhab.binding.myuplink/src/test/java/org/openhab/binding/myuplink/internal/provider/ChannelFactoryTest.java
  bundles/pom.xml
Labels: new binding

#16516 [huesync] Initial contribution
  CODEOWNERS
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.huesync/NOTICE
  bundles/org.openhab.binding.huesync/README.md
  bundles/org.openhab.binding.huesync/doc/device_registration.png
  bundles/org.openhab.binding.huesync/pom.xml
  bundles/org.openhab.binding.huesync/src/main/feature/feature.xml
  bundles/org.openhab.binding.huesync/src/main/java/org/openhab/binding/huesync/internal/HdmiChannels.java
  bundles/org.openhab.binding.huesync/src/main/java/org/openhab/binding/huesync/internal/HueSyncConstants.java
  bundles/org.openhab.binding.huesync/src/main/java/org/openhab/binding/huesync/internal/api/dto/device/HueSyncDevice.java
  bundles/org.openhab.binding.huesync/src/main/java/org/openhab/binding/huesync/internal/api/dto/device/HueSyncDeviceCapabilitiesInfo.java
  bundles/org.openhab.binding.huesync/src/main/java/org/openhab/binding/huesync/internal/api/dto/device/HueSyncDeviceDetailed.java
  bundles/org.openhab.binding.huesync/src/main/java/org/openhab/binding/huesync/internal/api/dto/device/HueSyncDeviceDetailedUpdateInfo.java
  bundles/org.openhab.binding.huesync/src/main/java/org/openhab/binding/huesync/internal/api/dto/device/HueSyncDeviceDetailedWifiInfo.java
  bundles/org.openhab.binding.huesync/src/main/java/org/openhab/binding/huesync/internal/api/dto/execution/HueSyncExecution.java
  bundles/org.openhab.binding.huesync/src/main/java/org/openhab/binding/huesync/internal/api/dto/execution/HueSyncExecutionGame.java
  bundles/org.openhab.binding.huesync/src/main/java/org/openhab/binding/huesync/internal/api/dto/execution/HueSyncExecutionMusic.java
  bundles/org.openhab.binding.huesync/src/main/java/org/openhab/binding/huesync/internal/api/dto/execution/HueSyncExecutionVideo.java
  bundles/org.openhab.binding.huesync/src/main/java/org/openhab/binding/huesync/internal/api/dto/hdmi/HueSyncHdmi.java
  bundles/org.openhab.binding.huesync/src/main/java/org/openhab/binding/huesync/internal/api/dto/hdmi/HueSyncHdmiConnectionInfo.java
  bundles/org.openhab.binding.huesync/src/main/java/org/openhab/binding/huesync/internal/api/dto/registration/HueSyncRegistration.java
  bundles/org.openhab.binding.huesync/src/main/java/org/openhab/binding/huesync/internal/api/dto/registration/HueSyncRegistrationRequest.java
  bundles/org.openhab.binding.huesync/src/main/java/org/openhab/binding/huesync/internal/config/HueSyncConfiguration.java
  bundles/org.openhab.binding.huesync/src/main/java/org/openhab/binding/huesync/internal/connection/HueSyncAuthenticationResult.java
  bundles/org.openhab.binding.huesync/src/main/java/org/openhab/binding/huesync/internal/connection/HueSyncConnection.java
  bundles/org.openhab.binding.huesync/src/main/java/org/openhab/binding/huesync/internal/connection/HueSyncDeviceConnection.java
  bundles/org.openhab.binding.huesync/src/main/java/org/openhab/binding/huesync/internal/connection/HueSyncTrustManagerProvider.java
  bundles/org.openhab.binding.huesync/src/main/java/org/openhab/binding/huesync/internal/discovery/HueSyncDiscoveryParticipant.java
  bundles/org.openhab.binding.huesync/src/main/java/org/openhab/binding/huesync/internal/exceptions/HueSyncApiException.java
  bundles/org.openhab.binding.huesync/src/main/java/org/openhab/binding/huesync/internal/exceptions/HueSyncConnectionException.java
  bundles/org.openhab.binding.huesync/src/main/java/org/openhab/binding/huesync/internal/exceptions/HueSyncException.java
  bundles/org.openhab.binding.huesync/src/main/java/org/openhab/binding/huesync/internal/exceptions/HueSyncTaskException.java
  bundles/org.openhab.binding.huesync/src/main/java/org/openhab/binding/huesync/internal/factory/HueSyncHandlerFactory.java
  bundles/org.openhab.binding.huesync/src/main/java/org/openhab/binding/huesync/internal/handler/HueSyncHandler.java
  bundles/org.openhab.binding.huesync/src/main/java/org/openhab/binding/huesync/internal/handler/tasks/HueSyncRegistrationTask.java
  bundles/org.openhab.binding.huesync/src/main/java/org/openhab/binding/huesync/internal/handler/tasks/HueSyncUpdateTask.java
  bundles/org.openhab.binding.huesync/src/main/java/org/openhab/binding/huesync/internal/handler/tasks/HueSyncUpdateTaskResult.java
  bundles/org.openhab.binding.huesync/src/main/java/org/openhab/binding/huesync/internal/i18n/HueSyncLocalizer.java
  bundles/org.openhab.binding.huesync/src/main/resources/OH-INF/addon/addon.xml
  bundles/org.openhab.binding.huesync/src/main/resources/OH-INF/config/config.xml
  bundles/org.openhab.binding.huesync/src/main/resources/OH-INF/i18n/huesync.properties
  bundles/org.openhab.binding.huesync/src/main/resources/OH-INF/thing/channel-types.xml
  bundles/org.openhab.binding.huesync/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/pom.xml
Labels: new binding

#17805 [gpstracker] Fix handling ambigious region names
  bundles/org.openhab.binding.gpstracker/src/main/java/org/openhab/binding/gpstracker/internal/profile/GPSTrackerTriggerSwitchProfile.java
Labels: bug

#17362 [basicprofiles] Add support for functions (DELTA, MEDIAN, AVG, STDDEV, MIN, MAX) in State Filter
  bundles/org.openhab.transform.basicprofiles/README.md
  bundles/org.openhab.transform.basicprofiles/src/main/java/org/openhab/transform/basicprofiles/internal/profiles/StateFilterProfile.java
  bundles/org.openhab.transform.basicprofiles/src/test/java/org/openhab/transform/basicprofiles/internal/profiles/StateFilterProfileTest.java
Labels: enhancement

#17835 [vesync] SCA error catches
  bundles/org.openhab.binding.vesync/src/main/java/org/openhab/binding/vesync/internal/handlers/VeSyncBaseDeviceHandler.java
Labels: regression

#17833 Add missing code owners
  CODEOWNERS
Labels: infrastructure

#17681 [wiz] Initial contribution
  CODEOWNERS
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.wiz/NOTICE
  bundles/org.openhab.binding.wiz/README.md
  bundles/org.openhab.binding.wiz/pom.xml
  bundles/org.openhab.binding.wiz/src/main/feature/feature.xml
  bundles/org.openhab.binding.wiz/src/main/java/org/openhab/binding/wiz/internal/WizBindingConstants.java
  bundles/org.openhab.binding.wiz/src/main/java/org/openhab/binding/wiz/internal/WizHandlerFactory.java
  bundles/org.openhab.binding.wiz/src/main/java/org/openhab/binding/wiz/internal/WizStateDescriptionProvider.java
  bundles/org.openhab.binding.wiz/src/main/java/org/openhab/binding/wiz/internal/config/WizDeviceConfiguration.java
  bundles/org.openhab.binding.wiz/src/main/java/org/openhab/binding/wiz/internal/discovery/WizDiscoveryService.java
  bundles/org.openhab.binding.wiz/src/main/java/org/openhab/binding/wiz/internal/entities/ColorRequestParam.java
  bundles/org.openhab.binding.wiz/src/main/java/org/openhab/binding/wiz/internal/entities/ColorTemperatureRequestParam.java
  bundles/org.openhab.binding.wiz/src/main/java/org/openhab/binding/wiz/internal/entities/DimmingRequestParam.java
  bundles/org.openhab.binding.wiz/src/main/java/org/openhab/binding/wiz/internal/entities/ErrorResponseResult.java
  bundles/org.openhab.binding.wiz/src/main/java/org/openhab/binding/wiz/internal/entities/FanModeRequestParam.java
  bundles/org.openhab.binding.wiz/src/main/java/org/openhab/binding/wiz/internal/entities/FanReverseRequestParam.java
  bundles/org.openhab.binding.wiz/src/main/java/org/openhab/binding/wiz/internal/entities/FanSpeedRequestParam.java
  bundles/org.openhab.binding.wiz/src/main/java/org/openhab/binding/wiz/internal/entities/FanStateRequestParam.java
  bundles/org.openhab.binding.wiz/src/main/java/org/openhab/binding/wiz/internal/entities/FirstBeatResponseParam.java
  bundles/org.openhab.binding.wiz/src/main/java/org/openhab/binding/wiz/internal/entities/ModelConfigResult.java
  bundles/org.openhab.binding.wiz/src/main/java/org/openhab/binding/wiz/internal/entities/Param.java
  bundles/org.openhab.binding.wiz/src/main/java/org/openhab/binding/wiz/internal/entities/PulseRequestParam.java
  bundles/org.openhab.binding.wiz/src/main/java/org/openhab/binding/wiz/internal/entities/RegistrationRequestParam.java
  bundles/org.openhab.binding.wiz/src/main/java/org/openhab/binding/wiz/internal/entities/SceneRequestParam.java
  bundles/org.openhab.binding.wiz/src/main/java/org/openhab/binding/wiz/internal/entities/SpeedRequestParam.java
  bundles/org.openhab.binding.wiz/src/main/java/org/openhab/binding/wiz/internal/entities/StateRequestParam.java
  bundles/org.openhab.binding.wiz/src/main/java/org/openhab/binding/wiz/internal/entities/SystemConfigResult.java
  bundles/org.openhab.binding.wiz/src/main/java/org/openhab/binding/wiz/internal/entities/WizRequest.java
  bundles/org.openhab.binding.wiz/src/main/java/org/openhab/binding/wiz/internal/entities/WizResponse.java
  bundles/org.openhab.binding.wiz/src/main/java/org/openhab/binding/wiz/internal/entities/WizSyncState.java
  bundles/org.openhab.binding.wiz/src/main/java/org/openhab/binding/wiz/internal/enums/WizColorMode.java
  bundles/org.openhab.binding.wiz/src/main/java/org/openhab/binding/wiz/internal/enums/WizLightMode.java
  bundles/org.openhab.binding.wiz/src/main/java/org/openhab/binding/wiz/internal/enums/WizMethodType.java
  bundles/org.openhab.binding.wiz/src/main/java/org/openhab/binding/wiz/internal/enums/WizModuleType.java
  bundles/org.openhab.binding.wiz/src/main/java/org/openhab/binding/wiz/internal/handler/WizHandler.java
  bundles/org.openhab.binding.wiz/src/main/java/org/openhab/binding/wiz/internal/handler/WizMediator.java
  bundles/org.openhab.binding.wiz/src/main/java/org/openhab/binding/wiz/internal/handler/WizMediatorImpl.java
  bundles/org.openhab.binding.wiz/src/main/java/org/openhab/binding/wiz/internal/runnable/WizUpdateReceiverRunnable.java
  bundles/org.openhab.binding.wiz/src/main/java/org/openhab/binding/wiz/internal/utils/NetworkUtils.java
  bundles/org.openhab.binding.wiz/src/main/java/org/openhab/binding/wiz/internal/utils/ValidationUtils.java
  bundles/org.openhab.binding.wiz/src/main/java/org/openhab/binding/wiz/internal/utils/WizColorConverter.java
  bundles/org.openhab.binding.wiz/src/main/java/org/openhab/binding/wiz/internal/utils/WizPacketConverter.java
  bundles/org.openhab.binding.wiz/src/main/java/org/openhab/binding/wiz/internal/utils/WizResponseDeserializer.java
  bundles/org.openhab.binding.wiz/src/main/resources/OH-INF/addon/addon.xml
  bundles/org.openhab.binding.wiz/src/main/resources/OH-INF/config/config.xml
  bundles/org.openhab.binding.wiz/src/main/resources/OH-INF/i18n/wiz.properties
  bundles/org.openhab.binding.wiz/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/pom.xml
Labels: new binding

#17842 [vesync] Core 300S Updates
  bundles/org.openhab.binding.vesync/README.md
  bundles/org.openhab.binding.vesync/src/main/java/org/openhab/binding/vesync/internal/handlers/VeSyncDeviceAirPurifierHandler.java
Labels: enhancement

#17845 Add UoM support for RSSI channels
  bundles/org.openhab.binding.airgradient/README.md
  bundles/org.openhab.binding.airgradient/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.airgradient/src/main/resources/OH-INF/update/update.xml
  bundles/org.openhab.binding.bluetooth/README.md
  bundles/org.openhab.binding.bluetooth/src/main/resources/OH-INF/thing/channels.xml
  bundles/org.openhab.binding.bluetooth/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.bluetooth/src/main/resources/OH-INF/update/update.xml
  bundles/org.openhab.binding.draytonwiser/README.md
  bundles/org.openhab.binding.draytonwiser/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.draytonwiser/src/main/resources/OH-INF/update/update.xml
  bundles/org.openhab.binding.mqtt.ruuvigateway/README.md
  bundles/org.openhab.binding.mqtt.ruuvigateway/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.mqtt.ruuvigateway/src/main/resources/OH-INF/update/update.xml
  bundles/org.openhab.binding.surepetcare/README.md
  bundles/org.openhab.binding.surepetcare/src/main/java/org/openhab/binding/surepetcare/internal/handler/SurePetcareDeviceHandler.java
  bundles/org.openhab.binding.surepetcare/src/main/resources/OH-INF/thing/things.xml
  bundles/org.openhab.binding.surepetcare/src/main/resources/OH-INF/update/update.xml
  itests/org.openhab.binding.mqtt.ruuvigateway.tests/src/main/java/org/openhab/binding/mqtt/ruuvigateway/RuuviGatewayTest.java
Labels: enhancement

#17851 [mqtt.homeassistant] Fix thing consistency for existing things when a device adds or removes components
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/DiscoverComponents.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/discovery/HomeAssistantDiscovery.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/handler/HomeAssistantThingHandler.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/discovery/HomeAssistantDiscoveryTests.java
  itests/org.openhab.binding.mqtt.homeassistant.tests/src/main/java/org/openhab/binding/mqtt/homeassistant/HomeAssistantMQTTImplementationTest.java
Labels: bug

#17849 Normalize thread names (2)
  bundles/org.openhab.binding.broadlink/src/main/java/org/openhab/binding/broadlink/internal/discovery/DiscoveryProtocol.java
  bundles/org.openhab.binding.broadlink/src/main/java/org/openhab/binding/broadlink/internal/socket/BroadlinkSocket.java
  bundles/org.openhab.binding.cm11a/src/main/java/org/openhab/binding/cm11a/internal/X10Interface.java
  bundles/org.openhab.binding.denonmarantz/src/main/java/org/openhab/binding/denonmarantz/internal/connector/telnet/DenonMarantzTelnetClientThread.java
  bundles/org.openhab.binding.digiplex/src/main/java/org/openhab/binding/digiplex/internal/DigiplexBindingConstants.java
  bundles/org.openhab.binding.digiplex/src/main/java/org/openhab/binding/digiplex/internal/handler/DigiplexBridgeHandler.java
  bundles/org.openhab.binding.doorbird/src/main/java/org/openhab/binding/doorbird/internal/listener/DoorbirdUdpListener.java
  bundles/org.openhab.binding.fineoffsetweatherstation/src/main/java/org/openhab/binding/fineoffsetweatherstation/internal/discovery/FineOffsetGatewayDiscoveryService.java
  bundles/org.openhab.binding.globalcache/src/main/java/org/openhab/binding/globalcache/internal/handler/GlobalCacheHandler.java
  bundles/org.openhab.binding.ihc/src/main/java/org/openhab/binding/ihc/internal/ws/IhcClient.java
  bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/Ffmpeg.java
  bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/IpCameraBindingConstants.java
  bundles/org.openhab.binding.lirc/src/main/java/org/openhab/binding/lirc/internal/connector/LIRCStreamReader.java
  bundles/org.openhab.binding.loxone/src/main/java/org/openhab/binding/loxone/internal/LxServerHandler.java
  bundles/org.openhab.binding.magentatv/src/main/java/org/openhab/binding/magentatv/internal/network/MagentaTVPoweroffListener.java
  bundles/org.openhab.binding.meteostick/src/main/java/org/openhab/binding/meteostick/internal/handler/MeteostickBridgeHandler.java
  bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/discovery/MiIoDiscovery.java
  bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/transport/MiIoAsyncCommunication.java
  bundles/org.openhab.binding.mpd/src/main/java/org/openhab/binding/mpd/internal/MPDBindingConstants.java
  bundles/org.openhab.binding.mpd/src/main/java/org/openhab/binding/mpd/internal/protocol/MPDConnectionThread.java
  bundles/org.openhab.binding.mynice/src/main/java/org/openhab/binding/mynice/internal/MyNiceBindingConstants.java
  bundles/org.openhab.binding.mynice/src/main/java/org/openhab/binding/mynice/internal/handler/It4WifiConnector.java
  bundles/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/NetworkBindingConstants.java
  bundles/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/dhcp/DHCPPacketListenerServer.java
  bundles/org.openhab.binding.nibeheatpump/src/main/java/org/openhab/binding/nibeheatpump/internal/NibeHeatPumpBindingConstants.java
  bundles/org.openhab.binding.nibeheatpump/src/main/java/org/openhab/binding/nibeheatpump/internal/connection/SerialConnector.java
  bundles/org.openhab.binding.nibeheatpump/src/main/java/org/openhab/binding/nibeheatpump/internal/connection/SimulatorConnector.java
  bundles/org.openhab.binding.nibeheatpump/src/main/java/org/openhab/binding/nibeheatpump/internal/connection/UDPConnector.java
  bundles/org.openhab.binding.nobohub/src/main/java/org/openhab/binding/nobohub/internal/connection/HubCommunicationThread.java
  bundles/org.openhab.binding.oceanic/src/main/java/org/openhab/binding/oceanic/internal/handler/SerialOceanicThingHandler.java
  bundles/org.openhab.binding.onkyo/src/main/java/org/openhab/binding/onkyo/internal/OnkyoConnection.java
  bundles/org.openhab.binding.pioneeravr/src/main/java/org/openhab/binding/pioneeravr/internal/protocol/StreamAvrConnection.java
  bundles/org.openhab.binding.playstation/src/main/java/org/openhab/binding/playstation/internal/PS4Handler.java
  bundles/org.openhab.binding.playstation/src/main/java/org/openhab/binding/playstation/internal/PlayStationBindingConstants.java
  bundles/org.openhab.binding.rme/src/main/java/org/openhab/binding/rme/internal/handler/SerialThingHandler.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/manager/ShellyManagerCache.java
  bundles/org.openhab.binding.smsmodem/src/3rdparty/java/org/smslib/MessageReader.java
  bundles/org.openhab.binding.smsmodem/src/3rdparty/java/org/smslib/Modem.java
  bundles/org.openhab.binding.smsmodem/src/main/java/org/openhab/binding/smsmodem/internal/SMSModemBindingConstants.java
  bundles/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/handler/SqueezeBoxServerHandler.java
  bundles/org.openhab.binding.teleinfo/src/main/java/org/openhab/binding/teleinfo/internal/serial/TeleinfoReceiveThread.java
  bundles/org.openhab.binding.touchwand/src/main/java/org/openhab/binding/touchwand/internal/discovery/TouchWandControllerDiscoveryService.java
  bundles/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/upnp/HueEmulationConfigWithRuntime.java
Labels: enhancement

#17852 [mqtt.homeassistant] Implement Tag Scanner
  bundles/org.openhab.binding.mqtt.homeassistant/README.md
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/ComponentFactory.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/Tag.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/component/TagTests.java
Labels: enhancement

#17853 [mqtt.homeassistant] Implement Humidifier
  bundles/org.openhab.binding.mqtt.homeassistant/README.md
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/ComponentChannelType.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/Climate.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/ComponentFactory.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/Humidifier.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/resources/OH-INF/i18n/mqtt.properties
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/resources/OH-INF/thing/homeassistant-channels.xml
  bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/component/HumidifierTests.java
Labels: enhancement

#17859 [mqtt.homeassistant] Implement WaterHeater
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/generic/internal/MqttThingHandlerFactory.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/ComponentChannelType.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/DiscoverComponents.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/AbstractComponent.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/Climate.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/ComponentFactory.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/WaterHeater.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/handler/HomeAssistantThingHandler.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/resources/OH-INF/i18n/mqtt.properties
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/resources/OH-INF/thing/homeassistant-channels.xml
  bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/HomeAssistantChannelTransformationTests.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/component/AbstractComponentTests.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/component/WaterHeaterTests.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/handler/HomeAssistantThingHandlerTests.java
  itests/org.openhab.binding.mqtt.homeassistant.tests/src/main/java/org/openhab/binding/mqtt/homeassistant/DiscoverComponentsTest.java
  itests/org.openhab.binding.mqtt.homeassistant.tests/src/main/java/org/openhab/binding/mqtt/homeassistant/HomeAssistantMQTTImplementationTest.java
Labels: enhancement

#17854 [dsmr] Fix IllegalStateException in rfc2217 connector
  bundles/org.openhab.binding.dsmr/src/main/java/org/openhab/binding/dsmr/internal/device/connector/DSMRErrorStatus.java
  bundles/org.openhab.binding.dsmr/src/main/java/org/openhab/binding/dsmr/internal/device/connector/DSMRSerialConnector.java
Labels: bug

#17860 [groovyscripting] Prevent CNFE for scoped classes unavailable to the class loader
  bundles/org.openhab.automation.groovyscripting/src/main/java/org/openhab/automation/groovyscripting/internal/GroovyScriptEngineFactory.java
Labels: bug, critical, regression

#17858 [mqtt.homeassistant] Update Jinjava to 2.7.4
  bundles/org.openhab.binding.mqtt.homeassistant/pom.xml
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/feature/feature.xml
  bundles/org.openhab.transform.jinja/pom.xml
  bundles/org.openhab.transform.jinja/src/main/feature/feature.xml
  features/openhab-addons/src/main/resources/footer.xml
  itests/org.openhab.binding.mqtt.homeassistant.tests/itest.bndrun
Labels: bug

#17856 [wiz] Enable addon finder support
  bundles/org.openhab.binding.wiz/src/main/resources/OH-INF/addon/addon.xml
Labels: enhancement

#17582 [tesla] Add null annotations
  bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/TeslaChannelSelectorProxy.java
  bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/discovery/TeslaVehicleDiscoveryService.java
  bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/handler/TeslaAccountHandler.java
  bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/handler/TeslaEventEndpoint.java
  bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/handler/TeslaSSOHandler.java
  bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/handler/TeslaVehicleHandler.java
  bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/handler/VehicleListener.java
  bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/protocol/ChargeState.java
  bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/protocol/ClimateState.java
  bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/protocol/DriveState.java
  bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/protocol/GUIState.java
  bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/protocol/Vehicle.java
  bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/protocol/VehicleConfig.java
  bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/protocol/VehicleData.java
  bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/protocol/VehicleState.java
  bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/protocol/dto/ChargeState.java
  bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/protocol/dto/ClimateState.java
  bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/protocol/dto/DriveState.java
  bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/protocol/dto/Event.java
  bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/protocol/dto/GUIState.java
  bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/protocol/dto/SoftwareUpdate.java
  bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/protocol/dto/Vehicle.java
  bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/protocol/dto/VehicleConfig.java
  bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/protocol/dto/VehicleData.java
  bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/protocol/dto/VehicleState.java
  bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/protocol/dto/sso/AuthorizationCodeExchangeRequest.java
  bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/protocol/dto/sso/AuthorizationCodeExchangeResponse.java
  bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/protocol/dto/sso/RefreshTokenRequest.java
  bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/protocol/dto/sso/TokenExchangeRequest.java
  bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/protocol/dto/sso/TokenResponse.java
  bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/throttler/AbstractChannelThrottler.java
  bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/throttler/AbstractMultiRateChannelThrottler.java
  bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/throttler/ChannelThrottler.java
  bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/throttler/QueueChannelThrottler.java
  bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/throttler/Rate.java
  bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/throttler/ScheduledChannelThrottler.java
  bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/throttler/TimeProvider.java
Labels: enhancement

#17871 [ntp] Remove obsoleted integration tests
  itests/org.openhab.binding.ntp.tests/src/main/java/org/openhab/binding/ntp/test/NtpOSGiTest.java
Labels: test, regression

#17872 [robonect] Simplify `DateTimeType` handling
  bundles/org.openhab.binding.robonect/src/main/java/org/openhab/binding/robonect/internal/handler/RobonectHandler.java
  bundles/org.openhab.binding.robonect/src/test/java/org/openhab/binding/robonect/internal/handler/RobonectHandlerTest.java
Labels: test, regression

#17878 [hue] Friends of Hue sensors show as online
  bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/api/dto/clip2/enums/ZigbeeStatus.java
  bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/Clip2ThingHandler.java
Labels: bug

#17867 [wiz] Correct units for RSSI
  bundles/org.openhab.binding.wiz/src/main/java/org/openhab/binding/wiz/internal/handler/WizHandler.java
  bundles/org.openhab.binding.wiz/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.wiz/src/main/resources/OH-INF/update/instructions.xml
Labels: bug, regression

#17877 [freeboxos] Add missing thing actions for active player
  bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/action/ActivePlayerActions.java
Labels: bug

#17525 [amazonechocontrol] Improve documentation
  bundles/org.openhab.binding.amazonechocontrol/README.md
Labels: documentation

#17880 [mqtt.homeassistant] Document new channels from #17659
  bundles/org.openhab.binding.mqtt.homeassistant/README.md
Labels: documentation

#17905 [hue] Recognise `grouped_motion` and `smart_scene` resources
  bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/api/dto/clip2/enums/ResourceType.java
  bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/Clip2ThingHandler.java
  bundles/org.openhab.binding.hue/src/test/java/org/openhab/binding/hue/internal/clip2/Clip2DtoTest.java
  bundles/org.openhab.binding.hue/src/test/resources/grouped_motion.json
Labels: enhancement

#17902 [miio] Add support for Xiaomi Robot Vacuum X20+
  bundles/org.openhab.binding.miio/README.md
  bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/MiIoDevices.java
  bundles/org.openhab.binding.miio/src/main/resources/OH-INF/i18n/basic.properties
  bundles/org.openhab.binding.miio/src/main/resources/database/xiaomi.vacuum.c102gl-miot.json
Labels: enhancement

#17924 [bondhome] Catch null host exception in discovery service
  bundles/org.openhab.binding.bondhome/src/main/java/org/openhab/binding/bondhome/internal/api/BondHttpApi.java
Labels: bug

#17904 [insteon] Convert legacy threads to use scheduler service
  bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/InsteonLegacyBinding.java
  bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/device/LegacyDevice.java
  bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/device/LegacyPollManager.java
  bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/device/LegacyRequestManager.java
  bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/device/PollManager.java
  bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/device/RequestManager.java
  bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/transport/LegacyDriver.java
  bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/transport/LegacyPort.java
  bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/transport/Port.java
Labels: bug

#17895 [mqtt.homeassistant] Implement regex_findall and regex_findall_index Jinja filters
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/HomeAssistantChannelTransformation.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/HomeAssistantJinjaFunctionLibrary.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/HomeAssistantChannelTransformationTests.java
Labels: enhancement

#17916 [tibber] Add price_level to today_prices and tomorrow_prices
  bundles/org.openhab.binding.tibber/README.md
  bundles/org.openhab.binding.tibber/src/main/java/org/openhab/binding/tibber/internal/handler/TibberPriceConsumptionHandler.java
Labels: enhancement

#17844 [VeSync] Add support for wifi outlets
  bundles/org.openhab.binding.vesync/README.md
  bundles/org.openhab.binding.vesync/src/main/java/org/openhab/binding/vesync/internal/VeSyncBridgeConfiguration.java
  bundles/org.openhab.binding.vesync/src/main/java/org/openhab/binding/vesync/internal/VeSyncConstants.java
  bundles/org.openhab.binding.vesync/src/main/java/org/openhab/binding/vesync/internal/VeSyncHandlerFactory.java
  bundles/org.openhab.binding.vesync/src/main/java/org/openhab/binding/vesync/internal/api/VeSyncV2ApiHelper.java
  bundles/org.openhab.binding.vesync/src/main/java/org/openhab/binding/vesync/internal/discovery/VeSyncDiscoveryService.java
  bundles/org.openhab.binding.vesync/src/main/java/org/openhab/binding/vesync/internal/dto/requests/VeSyncProtocolConstants.java
  bundles/org.openhab.binding.vesync/src/main/java/org/openhab/binding/vesync/internal/dto/requests/VeSyncRequestGetOutletStatus.java
  bundles/org.openhab.binding.vesync/src/main/java/org/openhab/binding/vesync/internal/dto/requests/VeSyncRequestManagedDeviceBypassV2.java
  bundles/org.openhab.binding.vesync/src/main/java/org/openhab/binding/vesync/internal/dto/responses/VeSyncV2BypassEnergyHistory.java
  bundles/org.openhab.binding.vesync/src/main/java/org/openhab/binding/vesync/internal/dto/responses/VeSyncV2BypassOutletStatus.java
  bundles/org.openhab.binding.vesync/src/main/java/org/openhab/binding/vesync/internal/handlers/VeSyncBridgeHandler.java
  bundles/org.openhab.binding.vesync/src/main/java/org/openhab/binding/vesync/internal/handlers/VeSyncDeviceOutletHandler.java
  bundles/org.openhab.binding.vesync/src/main/resources/OH-INF/i18n/vesync.properties
  bundles/org.openhab.binding.vesync/src/main/resources/OH-INF/thing/thing-types.xml
Labels: enhancement

#17899 [androidtv] Improve documentation with hint and potential troubleshooting
  bundles/org.openhab.binding.androidtv/README.md
Labels: documentation

#17898 [nest] Update README pub/sub instructions
  bundles/org.openhab.binding.nest/README.md
Labels: documentation

#17925 [roku] Check for ECP Limited Mode
  bundles/org.openhab.binding.roku/README.md
  bundles/org.openhab.binding.roku/src/main/java/org/openhab/binding/roku/internal/RokuLimitedModeException.java
  bundles/org.openhab.binding.roku/src/main/java/org/openhab/binding/roku/internal/communication/RokuCommunicator.java
  bundles/org.openhab.binding.roku/src/main/java/org/openhab/binding/roku/internal/handler/RokuHandler.java
  bundles/org.openhab.binding.roku/src/main/resources/OH-INF/i18n/roku.properties
Labels: enhancement

#17922 [insteon] Use shared jetty http client
  bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/InsteonHandlerFactory.java
  bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/InsteonLegacyBinding.java
  bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/device/InsteonModem.java
  bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/handler/InsteonBridgeHandler.java
  bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/handler/InsteonLegacyNetworkHandler.java
  bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/transport/HubIOStream.java
  bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/transport/IOStream.java
  bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/transport/LegacyDriver.java
  bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/transport/LegacyPort.java
  bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/transport/Port.java
Labels: enhancement

#17933 [mqtt.homeassistant] Fix components with an empty name
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/AbstractComponent.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/component/ClimateTests.java
Labels: bug

#17901 [guntamatic] Add channel groups
  bundles/org.openhab.binding.guntamatic/README.md
  bundles/org.openhab.binding.guntamatic/src/main/java/org/openhab/binding/guntamatic/internal/GuntamaticBindingConstants.java
  bundles/org.openhab.binding.guntamatic/src/main/java/org/openhab/binding/guntamatic/internal/GuntamaticChannelTypeProvider.java
  bundles/org.openhab.binding.guntamatic/src/main/java/org/openhab/binding/guntamatic/internal/GuntamaticDynamicTypeProvider.java
  bundles/org.openhab.binding.guntamatic/src/main/java/org/openhab/binding/guntamatic/internal/GuntamaticHandler.java
  bundles/org.openhab.binding.guntamatic/src/main/java/org/openhab/binding/guntamatic/internal/GuntamaticHandlerFactory.java
  bundles/org.openhab.binding.guntamatic/src/main/resources/OH-INF/i18n/guntamatic.properties
  bundles/org.openhab.binding.guntamatic/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.guntamatic/src/main/resources/OH-INF/update/update.xml
Labels: enhancement, (potentially) not backward compatible

#17932 [tado.doc] Updated tado binding documentation for tado X
  bundles/org.openhab.binding.tado/README.md
Labels: documentation

#17942 [deconz] Support QuantityType commands
  bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/handler/GroupThingHandler.java
  bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/handler/LightThingHandler.java
Labels: bug

#17943 [lifx] Fix QuantityType command
  bundles/org.openhab.binding.lifx/src/main/java/org/openhab/binding/lifx/internal/util/LifxMessageUtil.java
Labels: enhancement

#17946 [tplinksmarthome] Support QuantityType Color Temperature command
  bundles/org.openhab.binding.tplinksmarthome/src/main/java/org/openhab/binding/tplinksmarthome/internal/device/BulbDevice.java
Labels: bug

#17947 [shelly] Support QuantityType Color Temperature command
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/handler/ShellyLightHandler.java
Labels: bug

#17948 [hue] Improve QuantityType Color Temperature command
  bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/api/dto/clip2/helper/Setters.java
Labels: enhancement

#17944 [tapocontrol] Support QuantityType Color Temperature command
  bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/devices/wifi/bulb/TapoBulbHandler.java
  bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/devices/wifi/lightstrip/TapoLightStripHandler.java
Labels: bug

#17919 [amazonechocontrol] Support QuantityType Color Temperature command
  bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/smarthome/HandlerColorTemperatureController.java
Labels: bug

#17680 [miio] Add support for Smart Air Purifier 4 Lite zhimi.airp.rmb1
  bundles/org.openhab.binding.miio/README.md
  bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/MiIoDevices.java
  bundles/org.openhab.binding.miio/src/main/resources/OH-INF/i18n/basic.properties
  bundles/org.openhab.binding.miio/src/main/resources/database/zhimi.airp.rmb1-miot.json
  bundles/org.openhab.binding.miio/src/main/resources/misc/device_names.json
Labels: enhancement

#17957 [freeathome] Fix not updating values of room temperature devices
  bundles/org.openhab.binding.freeathome/src/main/java/org/openhab/binding/freeathome/internal/FreeAtHomeBindingConstants.java
  bundles/org.openhab.binding.freeathome/src/main/java/org/openhab/binding/freeathome/internal/FreeAtHomeDiscoveryService.java
  bundles/org.openhab.binding.freeathome/src/main/java/org/openhab/binding/freeathome/internal/FreeAtHomeHandlerFactory.java
  bundles/org.openhab.binding.freeathome/src/main/java/org/openhab/binding/freeathome/internal/configuration/FreeAtHomeBridgeHandlerConfiguration.java
  bundles/org.openhab.binding.freeathome/src/main/java/org/openhab/binding/freeathome/internal/configuration/FreeAtHomeDeviceHandlerConfiguration.java
  bundles/org.openhab.binding.freeathome/src/main/java/org/openhab/binding/freeathome/internal/datamodel/FreeAtHomeDatapoint.java
  bundles/org.openhab.binding.freeathome/src/main/java/org/openhab/binding/freeathome/internal/datamodel/FreeAtHomeDatapointGroup.java
  bundles/org.openhab.binding.freeathome/src/main/java/org/openhab/binding/freeathome/internal/datamodel/FreeAtHomeDeviceChannel.java
  bundles/org.openhab.binding.freeathome/src/main/java/org/openhab/binding/freeathome/internal/datamodel/FreeAtHomeDeviceDescription.java
  bundles/org.openhab.binding.freeathome/src/main/java/org/openhab/binding/freeathome/internal/handler/FreeAtHomeBridgeHandler.java
  bundles/org.openhab.binding.freeathome/src/main/java/org/openhab/binding/freeathome/internal/handler/FreeAtHomeDeviceHandler.java
  bundles/org.openhab.binding.freeathome/src/main/java/org/openhab/binding/freeathome/internal/handler/FreeAtHomeDeviceStateListener.java
  bundles/org.openhab.binding.freeathome/src/main/java/org/openhab/binding/freeathome/internal/type/FreeAtHomeChannelTypeProvider.java
  bundles/org.openhab.binding.freeathome/src/main/java/org/openhab/binding/freeathome/internal/type/FreeAtHomeChannelTypeProviderImpl.java
  bundles/org.openhab.binding.freeathome/src/main/java/org/openhab/binding/freeathome/internal/type/FreeAtHomeThingTypeProvider.java
  bundles/org.openhab.binding.freeathome/src/main/java/org/openhab/binding/freeathome/internal/type/FreeAtHomeThingTypeProviderImpl.java
  bundles/org.openhab.binding.freeathome/src/main/java/org/openhab/binding/freeathome/internal/util/FidTranslationUtils.java
  bundles/org.openhab.binding.freeathome/src/main/java/org/openhab/binding/freeathome/internal/util/FreeAtHomeGeneralException.java
  bundles/org.openhab.binding.freeathome/src/main/java/org/openhab/binding/freeathome/internal/util/FreeAtHomeHttpCommunicationException.java
  bundles/org.openhab.binding.freeathome/src/main/java/org/openhab/binding/freeathome/internal/util/PIdContainerClass.java
  bundles/org.openhab.binding.freeathome/src/main/java/org/openhab/binding/freeathome/internal/util/PidTranslationUtils.java
  bundles/org.openhab.binding.freeathome/src/main/java/org/openhab/binding/freeathome/internal/util/UidUtils.java
  bundles/org.openhab.binding.freeathome/src/main/java/org/openhab/binding/freeathome/internal/valuestateconverter/BinaryValueStateConverter.java
  bundles/org.openhab.binding.freeathome/src/main/java/org/openhab/binding/freeathome/internal/valuestateconverter/BooleanValueStateConverter.java
  bundles/org.openhab.binding.freeathome/src/main/java/org/openhab/binding/freeathome/internal/valuestateconverter/DecimalValueStateConverter.java
  bundles/org.openhab.binding.freeathome/src/main/java/org/openhab/binding/freeathome/internal/valuestateconverter/ShuttercontrolValueStateConverter.java
  bundles/org.openhab.binding.freeathome/src/main/java/org/openhab/binding/freeathome/internal/valuestateconverter/ValueStateConverter.java
Labels: bug

#17812 [govee] Fix brightness vs. color synchronization
  bundles/org.openhab.binding.govee/README.md
  bundles/org.openhab.binding.govee/src/main/java/org/openhab/binding/govee/internal/CommunicationManager.java
  bundles/org.openhab.binding.govee/src/main/java/org/openhab/binding/govee/internal/GoveeBindingConstants.java
  bundles/org.openhab.binding.govee/src/main/java/org/openhab/binding/govee/internal/GoveeConfiguration.java
  bundles/org.openhab.binding.govee/src/main/java/org/openhab/binding/govee/internal/GoveeDiscoveryService.java
  bundles/org.openhab.binding.govee/src/main/java/org/openhab/binding/govee/internal/GoveeHandler.java
  bundles/org.openhab.binding.govee/src/main/java/org/openhab/binding/govee/internal/GoveeHandlerFactory.java
  bundles/org.openhab.binding.govee/src/main/java/org/openhab/binding/govee/internal/GoveeStateDescriptionProvider.java
  bundles/org.openhab.binding.govee/src/main/resources/OH-INF/config/config.xml
  bundles/org.openhab.binding.govee/src/main/resources/OH-INF/i18n/govee.properties
  bundles/org.openhab.binding.govee/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.govee/src/main/resources/OH-INF/update/instructions.xml
  bundles/org.openhab.binding.govee/src/test/java/org/openhab/binding/govee/internal/GoveeHandlerMock.java
  bundles/org.openhab.binding.govee/src/test/java/org/openhab/binding/govee/internal/GoveeSerializeGoveeHandlerTest.java
Labels: bug

#17960 [jrubyscripting] Remove Compilable implementation
  bundles/org.openhab.automation.jrubyscripting/src/main/java/org/openhab/automation/jrubyscripting/internal/JRubyEngineWrapper.java
Labels: bug

#17963 [pulseaudio] Markdown documentation fixes
  bundles/org.openhab.binding.pulseaudio/README.md
Labels: documentation

#17967 [pihole] Fix enableBlocking action
  bundles/org.openhab.binding.pihole/src/main/java/org/openhab/binding/pihole/internal/rest/JettyAdminService.java
Labels: bug

#17971 [network] Fix last-seen channel being set to `UNDEF` at startup
  bundles/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/handler/NetworkHandler.java
Labels: bug

#17733 [openaitts] OpenAI Text-to-Speech initial contribution
  CODEOWNERS
  bom/openhab-addons/pom.xml
  bundles/org.openhab.voice.openaitts/NOTICE
  bundles/org.openhab.voice.openaitts/README.md
  bundles/org.openhab.voice.openaitts/pom.xml
  bundles/org.openhab.voice.openaitts/src/main/feature/feature.xml
  bundles/org.openhab.voice.openaitts/src/main/java/org/openhab/voice/openaitts/internal/OpenAITTSConfiguration.java
  bundles/org.openhab.voice.openaitts/src/main/java/org/openhab/voice/openaitts/internal/OpenAITTSConstants.java
  bundles/org.openhab.voice.openaitts/src/main/java/org/openhab/voice/openaitts/internal/OpenAITTSService.java
  bundles/org.openhab.voice.openaitts/src/main/java/org/openhab/voice/openaitts/internal/OpenAITTSVoice.java
  bundles/org.openhab.voice.openaitts/src/main/resources/OH-INF/addon/addon.xml
  bundles/org.openhab.voice.openaitts/src/main/resources/OH-INF/config/config.xml
  bundles/org.openhab.voice.openaitts/src/main/resources/OH-INF/i18n/openaitts.properties
  bundles/pom.xml
Labels: new voice

#17965 [upnpcontrol] Fix `IllegalArgumentException` when downloading album art
  bundles/org.openhab.binding.upnpcontrol/src/main/java/org/openhab/binding/upnpcontrol/internal/handler/UpnpRendererHandler.java
Labels: bug

#17927 [tapocontrol] Add Smart Switches S210 and S220
  bundles/org.openhab.binding.tapocontrol/README.md
  bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/TapoControlHandlerFactory.java
  bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/constants/TapoThingConstants.java
  bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/devices/rf/TapoChildDeviceHandler.java
  bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/devices/rf/smartswitch/TapoSmartSwitchHandler.java
  bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/devices/wifi/hub/TapoHubHandler.java
  bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/discovery/TapoChildDiscoveryService.java
  bundles/org.openhab.binding.tapocontrol/src/main/resources/OH-INF/thing/S210.xml
  bundles/org.openhab.binding.tapocontrol/src/main/resources/OH-INF/thing/S220.xml
Labels: enhancement

#17980 [mqtt.generic] Fix ClassCastException when receiving ON/OFF on a dimmer channel
  bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/values/PercentageValue.java
  bundles/org.openhab.binding.mqtt.generic/src/test/java/org/openhab/binding/mqtt/generic/values/ValueTests.java
Labels: bug

#17981 [insteon] Fix legacy backward compatibility
  bundles/org.openhab.binding.insteon/README.md
  bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/discovery/InsteonLegacyDiscoveryService.java
  bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/handler/InsteonDeviceHandler.java
  bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/handler/InsteonLegacyDeviceHandler.java
  bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/handler/InsteonLegacyNetworkHandler.java
Labels: bug, (potentially) not backward compatible

#17983 [tesla] Fix `NumberFormatException`
  bundles/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/protocol/dto/VehicleData.java
Labels: bug, additional testing preferred

#17977 [insteon] Fix led command stack overflow error
  bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/device/feature/CommandHandler.java
Labels: bug

#17987 [insteon] Add led brightness on level channel parameter
  bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/device/feature/CommandHandler.java
  bundles/org.openhab.binding.insteon/src/main/resources/OH-INF/config/config.xml
  bundles/org.openhab.binding.insteon/src/main/resources/OH-INF/i18n/insteon.properties
  bundles/org.openhab.binding.insteon/src/main/resources/OH-INF/thing/channels.xml
  bundles/org.openhab.binding.insteon/src/main/resources/device-features.xml
Labels: enhancement

#17973 [tellstick] Update async-http-client to version 2.12.4
  bundles/org.openhab.binding.tellstick/pom.xml
Labels: security

#17990 [persistence.jpa] Upgrade Apache Derby to 10.17.1.0
  bundles/org.openhab.persistence.jpa/pom.xml
Labels: enhancement, additional testing preferred

#17993 [pipertts] Fix library load on windows
  bundles/org.openhab.voice.pipertts/README.md
  bundles/org.openhab.voice.pipertts/pom.xml
  bundles/org.openhab.voice.pipertts/src/main/java/org/openhab/voice/pipertts/internal/PiperTTSService.java
Labels: bug

#16969 [livisismarthome] Add support for rebooting the smart home controller
  bundles/org.openhab.binding.livisismarthome/README.md
  bundles/org.openhab.binding.livisismarthome/src/main/java/org/openhab/binding/livisismarthome/internal/LivisiBindingConstants.java
  bundles/org.openhab.binding.livisismarthome/src/main/java/org/openhab/binding/livisismarthome/internal/client/LivisiClient.java
  bundles/org.openhab.binding.livisismarthome/src/main/java/org/openhab/binding/livisismarthome/internal/client/api/entity/action/ActionParamsDTO.java
  bundles/org.openhab.binding.livisismarthome/src/main/java/org/openhab/binding/livisismarthome/internal/client/api/entity/action/RestartActionDTO.java
  bundles/org.openhab.binding.livisismarthome/src/main/java/org/openhab/binding/livisismarthome/internal/handler/LivisiBridgeHandler.java
  bundles/org.openhab.binding.livisismarthome/src/main/java/org/openhab/binding/livisismarthome/internal/handler/LivisiDeviceHandler.java
  bundles/org.openhab.binding.livisismarthome/src/main/resources/OH-INF/i18n/livisismarthome.properties
  bundles/org.openhab.binding.livisismarthome/src/main/resources/OH-INF/thing/bridge.xml
  bundles/org.openhab.binding.livisismarthome/src/main/resources/OH-INF/thing/channels.xml
Labels: enhancement

#16489 [netatmo] API limit reached handling
  bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/NetatmoBindingConstants.java
  bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/config/ApiHandlerConfiguration.java
  bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/config/ConfigurationLevel.java
  bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/ApiBridgeHandler.java
  bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/capability/AlarmEventCapability.java
  bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/capability/CameraCapability.java
  bundles/org.openhab.binding.netatmo/src/main/resources/OH-INF/i18n/netatmo.properties
Labels: bug, awaiting feedback, additional testing preferred, work in progress

#17929 [mqtt.generic] create the proper item type for channels with units
  bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/values/NumberValue.java
  bundles/org.openhab.binding.mqtt.generic/src/test/java/org/openhab/binding/mqtt/generic/values/ValueTests.java
Labels: bug

#17997 [basicprofiles] Fix delta state filter handling of negative values
  bundles/org.openhab.transform.basicprofiles/src/main/java/org/openhab/transform/basicprofiles/internal/profiles/StateFilterProfile.java
  bundles/org.openhab.transform.basicprofiles/src/test/java/org/openhab/transform/basicprofiles/internal/profiles/StateFilterProfileTest.java
Labels: bug

#18006 [epsonprojector] Add retrieval of source list
  bundles/org.openhab.binding.epsonprojector/README.md
  bundles/org.openhab.binding.epsonprojector/src/main/java/org/openhab/binding/epsonprojector/internal/EpsonProjectorBindingConstants.java
  bundles/org.openhab.binding.epsonprojector/src/main/java/org/openhab/binding/epsonprojector/internal/EpsonProjectorDevice.java
  bundles/org.openhab.binding.epsonprojector/src/main/java/org/openhab/binding/epsonprojector/internal/EpsonProjectorHandlerFactory.java
  bundles/org.openhab.binding.epsonprojector/src/main/java/org/openhab/binding/epsonprojector/internal/EpsonStateDescriptionOptionProvider.java
  bundles/org.openhab.binding.epsonprojector/src/main/java/org/openhab/binding/epsonprojector/internal/configuration/EpsonProjectorConfiguration.java
  bundles/org.openhab.binding.epsonprojector/src/main/java/org/openhab/binding/epsonprojector/internal/handler/EpsonProjectorHandler.java
  bundles/org.openhab.binding.epsonprojector/src/main/resources/OH-INF/i18n/epsonprojector.properties
  bundles/org.openhab.binding.epsonprojector/src/main/resources/OH-INF/thing/thing-types.xml
Labels: enhancement

#17938 [xmpp] Add action for sending a group message
  bundles/org.openhab.binding.xmppclient/src/main/java/org/openhab/binding/xmppclient/internal/action/XMPPActions.java
  bundles/org.openhab.binding.xmppclient/src/main/java/org/openhab/binding/xmppclient/internal/client/XMPPClient.java
  bundles/org.openhab.binding.xmppclient/src/main/java/org/openhab/binding/xmppclient/internal/handler/XMPPClientConfiguration.java
  bundles/org.openhab.binding.xmppclient/src/main/java/org/openhab/binding/xmppclient/internal/handler/XMPPClientHandler.java
  bundles/org.openhab.binding.xmppclient/src/main/resources/OH-INF/thing/thing-types.xml
Labels: enhancement

#17908 [mqtt.homeassistant] Remove newStyleChannels temporary back-compat
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/DiscoverComponents.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/HaID.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/AbstractComponent.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/AbstractRawSchemaLight.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/AlarmControlPanel.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/BinarySensor.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/Button.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/Camera.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/Climate.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/ComponentFactory.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/Cover.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/DefaultSchemaLight.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/DeviceTracker.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/DeviceTrigger.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/Event.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/Fan.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/Humidifier.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/JSONSchemaLight.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/Light.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/Lock.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/Number.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/Scene.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/Select.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/Sensor.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/Switch.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/Tag.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/TemplateSchemaLight.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/Text.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/Update.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/Vacuum.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/Valve.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/WaterHeater.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/discovery/HomeAssistantDiscovery.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/handler/HomeAssistantThingHandler.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/component/AbstractComponentTests.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/component/AlarmControlPanelDeprecatedTests.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/component/AlarmControlPanelTests.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/component/BinarySensorTests.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/component/ClimateTests.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/component/DefaultSchemaLightTests.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/component/DeviceTriggerTests.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/component/FanTests.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/component/JSONSchemaLightTests.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/component/SensorTests.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/component/TemplateSchemaLightTests.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/component/VacuumTests.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/handler/HomeAssistantThingHandlerTests.java
  itests/org.openhab.binding.mqtt.homeassistant.tests/src/main/java/org/openhab/binding/mqtt/homeassistant/DiscoverComponentsTest.java
  itests/org.openhab.binding.mqtt.homeassistant.tests/src/main/java/org/openhab/binding/mqtt/homeassistant/HomeAssistantMQTTImplementationTest.java
Labels: (potentially) not backward compatible
