Repository openhab/openhab-addons, pull requests merged in 2024-02, with the labels that each got.

#16324 [modbus.studer] Some little markdown and grammar corrections
  bundles/org.openhab.binding.modbus.studer/README.md
Labels: documentation

#16337 [knx] Correctly support state sub-types for DPTs
  bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/channel/KNXChannel.java
  bundles/org.openhab.binding.knx/src/test/java/org/openhab/binding/knx/internal/channel/KNXChannelTest.java
Labels: bug

#16352 [digitalstrom] Fix initialization of temperature control devices
  bundles/org.openhab.binding.digitalstrom/src/main/java/org/openhab/binding/digitalstrom/internal/lib/manager/impl/TemperatureControlManager.java
Labels: bug

#16319 [growatt] Suggest addon to be installed
  bundles/org.openhab.binding.growatt/README.md
  bundles/org.openhab.binding.growatt/src/main/resources/OH-INF/addon/addon.xml
Labels: enhancement

#16328 [teleinfo] Enable background discovery
  bundles/org.openhab.binding.teleinfo/src/main/java/org/openhab/binding/teleinfo/internal/TeleinfoDiscoveryService.java
Labels: enhancement

#16332 [ipcamera] Improve online/offline detection for ONVIF cameras
  bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/handler/IpCameraHandler.java
  bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/onvif/OnvifConnection.java
Labels: enhancement

#16361 [groovyscripting] Described a way for code reuse
  bundles/org.openhab.automation.groovyscripting/README.md
Labels: documentation

#16343 [plex] add ratingKey channels
  bundles/org.openhab.binding.plex/README.md
  bundles/org.openhab.binding.plex/src/main/java/org/openhab/binding/plex/internal/PlexBindingConstants.java
  bundles/org.openhab.binding.plex/src/main/java/org/openhab/binding/plex/internal/dto/MediaContainer.java
  bundles/org.openhab.binding.plex/src/main/java/org/openhab/binding/plex/internal/dto/PlexSession.java
  bundles/org.openhab.binding.plex/src/main/java/org/openhab/binding/plex/internal/handler/PlexPlayerHandler.java
  bundles/org.openhab.binding.plex/src/main/resources/OH-INF/i18n/plex.properties
  bundles/org.openhab.binding.plex/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.plex/src/main/resources/OH-INF/update/instructions.xml
Labels: enhancement

#16356 [hue] Fix `NullPointerException`
  bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/HueLightHandler.java
Labels: bug

#16365 [jsonpath] Upgrade dependencies and some cleanup
  bundles/org.openhab.transform.jsonpath/pom.xml
  bundles/org.openhab.transform.jsonpath/src/main/java/org/openhab/transform/jsonpath/internal/JSonPathTransformationService.java
  bundles/org.openhab.transform.jsonpath/src/main/java/org/openhab/transform/jsonpath/internal/profiles/JSonPathTransformationProfile.java
  bundles/org.openhab.transform.jsonpath/src/main/java/org/openhab/transform/jsonpath/internal/profiles/JSonPathTransformationProfileFactory.java
  bundles/org.openhab.transform.jsonpath/src/main/resources/readme.txt
  bundles/org.openhab.transform.jsonpath/src/test/java/org/openhab/transform/jsonpath/internal/JSonPathTransformationServiceTest.java
Labels: enhancement, security

#16335 [shelly] Support for Shelly Plus Mini Gen 3 series of devices, Shelly Plus UNI
  bundles/org.openhab.binding.shelly/README.md
  bundles/org.openhab.binding.shelly/pom.xml
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/ShellyBindingConstants.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api/ShellyDeviceProfile.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api2/Shelly2ApiJsonDTO.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/discovery/ShellyDiscoveryParticipant.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/discovery/ShellyThingCreator.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/handler/ShellyBaseHandler.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/manager/ShellyManagerPage.java
  bundles/org.openhab.binding.shelly/src/main/resources/OH-INF/config/configblu.xml
  bundles/org.openhab.binding.shelly/src/main/resources/OH-INF/i18n/shelly.properties
  bundles/org.openhab.binding.shelly/src/main/resources/OH-INF/thing/shellyBlu.xml
Labels: enhancement

#16111 [Audio] Fix PCM format and use PipedAudioStream in sources
  bundles/org.openhab.binding.pulseaudio/src/main/java/org/openhab/binding/pulseaudio/internal/PulseAudioAudioSource.java
  bundles/org.openhab.binding.pulseaudio/src/main/java/org/openhab/binding/pulseaudio/internal/handler/PulseaudioHandler.java
  bundles/org.openhab.voice.googlestt/src/main/java/org/openhab/voice/googlestt/internal/GoogleSTTService.java
  bundles/org.openhab.voice.rustpotterks/src/main/java/org/openhab/voice/rustpotterks/internal/RustpotterKSService.java
  bundles/org.openhab.voice.voskstt/src/main/java/org/openhab/voice/voskstt/internal/VoskSTTService.java
  bundles/org.openhab.voice.watsonstt/src/main/java/org/openhab/voice/watsonstt/internal/WatsonSTTService.java
Labels: enhancement

#16357 [boschshc] Add support for Smoke Detector II
  bundles/org.openhab.binding.boschshc/README.md
  bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/devices/BoschSHCBindingConstants.java
  bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/devices/BoschSHCHandlerFactory.java
  bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/devices/smokedetector/SmokeDetector2Handler.java
  bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/discovery/ThingDiscoveryService.java
  bundles/org.openhab.binding.boschshc/src/main/resources/OH-INF/i18n/boschshc.properties
  bundles/org.openhab.binding.boschshc/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/devices/smokedetector/SmokeDetector2HandlerTest.java
Labels: enhancement

#16360 [rrd4j] Improve querying the RRD4jPersistenceService
  bundles/org.openhab.persistence.rrd4j/src/main/java/org/openhab/persistence/rrd4j/internal/RRD4jPersistenceService.java
Labels: enhancement

#16376 [openwebnet] Replace gnu.io dependency with serial transport
  bundles/org.openhab.binding.openwebnet/pom.xml
  bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/discovery/UsbGatewayDiscoveryService.java
  bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/handler/OpenWebNetBridgeHandler.java
  bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/handler/OpenWebNetLightingHandler.java
  bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/serial/SerialPortAdapter.java
  bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/serial/SerialPortEventAdapter.java
  bundles/org.openhab.binding.openwebnet/src/main/java/org/openhab/binding/openwebnet/internal/serial/SerialPortProviderAdapter.java
Labels: enhancement

#16371 [shelly] Fix blu gateway script to prevent crash
  bundles/org.openhab.binding.shelly/src/main/resources/scripts/oh-blu-scanner.js
Labels: bug

#16377 [growatt] Correct battery display channel unit from 'one' to 'volt'
  bundles/org.openhab.binding.growatt/src/main/java/org/openhab/binding/growatt/internal/GrowattChannels.java
  bundles/org.openhab.binding.growatt/src/main/resources/OH-INF/i18n/growatt.properties
  bundles/org.openhab.binding.growatt/src/main/resources/OH-INF/thing/thing-types.xml
Labels: bug

#16364 [knx] Fix dimmer channels
  bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/channel/KNXChannel.java
  bundles/org.openhab.binding.knx/src/test/java/org/openhab/binding/knx/internal/channel/KNXChannelTest.java
Labels: bug, regression

#16315 [network] Improve threading
  bundles/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/PresenceDetection.java
  bundles/org.openhab.binding.network/src/test/java/org/openhab/binding/network/internal/PresenceDetectionTest.java
Labels: bug, additional testing preferred, regression

#16380 [miio] Fix date parsing issue last cleaning details
  bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/handler/MiIoVacuumHandler.java
Labels: bug

#16384 [miio] Fix sending empty command for feature channels
  bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/handler/MiIoVacuumHandler.java
Labels: bug

#16388 [miio] Fix last cleaning details wrong start and end missing issue
  bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/handler/MiIoVacuumHandler.java
Labels: bug

#16391 [shelly] Re-adding Shelly Plus10V to list of supported things
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/ShellyBindingConstants.java
Labels: bug

#16270 [Meteostick] Add windvane calibration
  bundles/org.openhab.binding.meteostick/README.md
  bundles/org.openhab.binding.meteostick/src/main/java/org/openhab/binding/meteostick/internal/MeteostickBindingConstants.java
  bundles/org.openhab.binding.meteostick/src/main/java/org/openhab/binding/meteostick/internal/MeteostickHandlerFactory.java
  bundles/org.openhab.binding.meteostick/src/main/java/org/openhab/binding/meteostick/internal/handler/MeteostickSensorHandler.java
  bundles/org.openhab.binding.meteostick/src/main/resources/OH-INF/i18n/meteostick.properties
  bundles/org.openhab.binding.meteostick/src/main/resources/OH-INF/thing/thing-types.xml
Labels: enhancement

#16216 [dolbycp] Add new binding for Dolby Digital Cinema Processor CP750
  CODEOWNERS
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.dolbycp/NOTICE
  bundles/org.openhab.binding.dolbycp/README.md
  bundles/org.openhab.binding.dolbycp/pom.xml
  bundles/org.openhab.binding.dolbycp/src/main/feature/feature.xml
  bundles/org.openhab.binding.dolbycp/src/main/java/org/openhab/binding/dolbycp/internal/DolbyCPBindingConstants.java
  bundles/org.openhab.binding.dolbycp/src/main/java/org/openhab/binding/dolbycp/internal/DolbyCPConfiguration.java
  bundles/org.openhab.binding.dolbycp/src/main/java/org/openhab/binding/dolbycp/internal/DolbyCPHandler.java
  bundles/org.openhab.binding.dolbycp/src/main/java/org/openhab/binding/dolbycp/internal/DolbyCPHandlerFactory.java
  bundles/org.openhab.binding.dolbycp/src/main/resources/OH-INF/addon/addon.xml
  bundles/org.openhab.binding.dolbycp/src/main/resources/OH-INF/i18n/dolbycp.properties
  bundles/org.openhab.binding.dolbycp/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/pom.xml
Labels: new binding, additional testing preferred

#16402 [knx] Add tests for DPT 9 and DPT 14
  bundles/org.openhab.binding.knx/src/test/java/org/openhab/binding/knx/internal/itests/Back2BackTest.java
Labels: test

#16395 [knx] Fix scale when sending DPT 7.002 or DPT 7.003
  bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/dpt/ValueEncoder.java
  bundles/org.openhab.binding.knx/src/test/java/org/openhab/binding/knx/internal/dpt/DPTTest.java
  bundles/org.openhab.binding.knx/src/test/java/org/openhab/binding/knx/internal/itests/Back2BackTest.java
Labels: bug

#16068 [nuvo] Display album art from MPS4
  bundles/org.openhab.binding.nuvo/README.md
  bundles/org.openhab.binding.nuvo/src/main/java/org/openhab/binding/nuvo/internal/NuvoBindingConstants.java
  bundles/org.openhab.binding.nuvo/src/main/java/org/openhab/binding/nuvo/internal/handler/NuvoHandler.java
Labels: enhancement

#16411 [radiothermostat] Add units to README
  bundles/org.openhab.binding.radiothermostat/README.md
Labels: documentation

#16090 [ipcamera] Addon info for suggestions
  bundles/org.openhab.binding.ipcamera/src/main/resources/OH-INF/addon/addon.xml
Labels: enhancement

#16397 [solarmax] Improve binding with respect to channel Current Power Generated
  bundles/org.openhab.binding.solarmax/MaxComm_Protokollbeschreibung_DE.pdf
  bundles/org.openhab.binding.solarmax/src/main/java/org/openhab/binding/solarmax/internal/SolarMaxChannel.java
  bundles/org.openhab.binding.solarmax/src/main/java/org/openhab/binding/solarmax/internal/connector/SolarMaxData.java
Labels: bug

#16109 [govee] Addon info for suggestions
  bundles/org.openhab.binding.govee/src/main/resources/OH-INF/addon/addon.xml
Labels: enhancement

#16399 [lgwebos] Increase limit to 5MB for Websocket text message
  bundles/org.openhab.binding.lgwebos/src/main/java/org/openhab/binding/lgwebos/internal/LGWebOSHandlerFactory.java
Labels: bug

#16336 [shelly] New channel group ncurrent for 3EM
  bundles/org.openhab.binding.shelly/README.md
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/ShellyBindingConstants.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api1/Shelly1ApiJsonDTO.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api1/Shelly1CoIoTVersion2.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api1/Shelly1CoapHandler.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/handler/ShellyComponents.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/provider/ShellyChannelDefinitions.java
  bundles/org.openhab.binding.shelly/src/main/resources/OH-INF/i18n/shelly.properties
  bundles/org.openhab.binding.shelly/src/main/resources/OH-INF/thing/shellyGen1_relay.xml
Labels: enhancement

#16413 [shelly] Support for Shelly BLU H&T
  bundles/org.openhab.binding.shelly/README.md
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/ShellyBindingConstants.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api/ShellyDeviceProfile.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api2/Shelly2ApiJsonDTO.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api2/ShellyBluApi.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/discovery/ShellyThingCreator.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/handler/ShellyBluSensorHandler.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/provider/ShellyChannelDefinitions.java
  bundles/org.openhab.binding.shelly/src/main/resources/OH-INF/i18n/shelly.properties
  bundles/org.openhab.binding.shelly/src/main/resources/OH-INF/thing/shellyBlu.xml
  bundles/org.openhab.binding.shelly/src/main/resources/scripts/oh-blu-scanner.js
Labels: enhancement

#16421 [knx] Fix KNX dimmer channels
  bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/channel/KNXChannel.java
  bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/channel/TypeColor.java
  bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/channel/TypeDimmer.java
  bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/channel/TypeRollershutter.java
  bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/handler/DeviceThingHandler.java
  bundles/org.openhab.binding.knx/src/test/java/org/openhab/binding/knx/internal/channel/KNXChannelTest.java
Labels: bug, regression

#16196 [homematic] Add Authentication
  bundles/org.openhab.binding.homematic/README.md
  bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/common/AuthenticationHandler.java
  bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/common/HomematicConfig.java
  bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/communicator/AbstractHomematicGateway.java
  bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/communicator/CcuGateway.java
  bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/communicator/HomematicGatewayFactory.java
  bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/communicator/client/XmlRpcClient.java
  bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/handler/HomematicBridgeHandler.java
  bundles/org.openhab.binding.homematic/src/main/resources/OH-INF/i18n/homematic.properties
  bundles/org.openhab.binding.homematic/src/main/resources/OH-INF/thing/bridge.xml
Labels: enhancement

#16075 [insteon] Mask password when logged
  bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/handler/InsteonNetworkHandler.java
Labels: enhancement

#15130 [sungrow] Initial contribution
  CODEOWNERS
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.modbus.sungrow/NOTICE
  bundles/org.openhab.binding.modbus.sungrow/README.md
  bundles/org.openhab.binding.modbus.sungrow/doc/WiNet-S_Modbus.PNG
  bundles/org.openhab.binding.modbus.sungrow/pom.xml
  bundles/org.openhab.binding.modbus.sungrow/src/main/java/org/openhab/binding/modbus/sungrow/internal/ConversionConstants.java
  bundles/org.openhab.binding.modbus.sungrow/src/main/java/org/openhab/binding/modbus/sungrow/internal/ModbusSungrowBindingConstants.java
  bundles/org.openhab.binding.modbus.sungrow/src/main/java/org/openhab/binding/modbus/sungrow/internal/ModbusSungrowHandlerFactory.java
  bundles/org.openhab.binding.modbus.sungrow/src/main/java/org/openhab/binding/modbus/sungrow/internal/SungrowInverterConfiguration.java
  bundles/org.openhab.binding.modbus.sungrow/src/main/java/org/openhab/binding/modbus/sungrow/internal/SungrowInverterHandler.java
  bundles/org.openhab.binding.modbus.sungrow/src/main/java/org/openhab/binding/modbus/sungrow/internal/SungrowInverterRegisters.java
  bundles/org.openhab.binding.modbus.sungrow/src/main/resources/OH-INF/config/config.xml
  bundles/org.openhab.binding.modbus.sungrow/src/main/resources/OH-INF/i18n/sungrow.properties
  bundles/org.openhab.binding.modbus.sungrow/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.modbus.sungrow/src/test/java/org/openhab/binding/modbus/sungrow/internal/SungrowInverterRegistersTest.java
  bundles/pom.xml
Labels: new binding

#16424 [roku] Add discoveryMethods
  bundles/org.openhab.binding.roku/src/main/resources/OH-INF/addon/addon.xml
Labels: enhancement

#16426 [shelly] Fix missing starting head tag in manager web ui
  bundles/org.openhab.binding.shelly/src/main/resources/sniplets/header.html
Labels: bug

#15965 [PiperTTS] Initial contribution
  CODEOWNERS
  bom/openhab-addons/pom.xml
  bundles/org.openhab.voice.pipertts/NOTICE
  bundles/org.openhab.voice.pipertts/README.md
  bundles/org.openhab.voice.pipertts/pom.xml
  bundles/org.openhab.voice.pipertts/src/main/feature/feature.xml
  bundles/org.openhab.voice.pipertts/src/main/java/org/openhab/voice/pipertts/internal/PiperTTSConfiguration.java
  bundles/org.openhab.voice.pipertts/src/main/java/org/openhab/voice/pipertts/internal/PiperTTSConstants.java
  bundles/org.openhab.voice.pipertts/src/main/java/org/openhab/voice/pipertts/internal/PiperTTSService.java
  bundles/org.openhab.voice.pipertts/src/main/resources/OH-INF/addon/addon.xml
  bundles/org.openhab.voice.pipertts/src/main/resources/OH-INF/config/config.xml
  bundles/org.openhab.voice.pipertts/src/main/resources/OH-INF/i18n/pipertts.properties
  bundles/pom.xml
Labels: new voice

#16392 [radiobrowser] Initial contribution
  CODEOWNERS
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.radiobrowser/NOTICE
  bundles/org.openhab.binding.radiobrowser/README.md
  bundles/org.openhab.binding.radiobrowser/pom.xml
  bundles/org.openhab.binding.radiobrowser/src/main/feature/feature.xml
  bundles/org.openhab.binding.radiobrowser/src/main/java/org/openhab/binding/radiobrowser/internal/RadioBrowserBindingConstants.java
  bundles/org.openhab.binding.radiobrowser/src/main/java/org/openhab/binding/radiobrowser/internal/RadioBrowserConfiguration.java
  bundles/org.openhab.binding.radiobrowser/src/main/java/org/openhab/binding/radiobrowser/internal/RadioBrowserHandler.java
  bundles/org.openhab.binding.radiobrowser/src/main/java/org/openhab/binding/radiobrowser/internal/RadioBrowserHandlerFactory.java
  bundles/org.openhab.binding.radiobrowser/src/main/java/org/openhab/binding/radiobrowser/internal/RadioBrowserStateDescriptionProvider.java
  bundles/org.openhab.binding.radiobrowser/src/main/java/org/openhab/binding/radiobrowser/internal/api/ApiException.java
  bundles/org.openhab.binding.radiobrowser/src/main/java/org/openhab/binding/radiobrowser/internal/api/RadioBrowserApi.java
  bundles/org.openhab.binding.radiobrowser/src/main/java/org/openhab/binding/radiobrowser/internal/api/RadioBrowserJson.java
  bundles/org.openhab.binding.radiobrowser/src/main/resources/OH-INF/addon/addon.xml
  bundles/org.openhab.binding.radiobrowser/src/main/resources/OH-INF/i18n/radiobrowser.properties
  bundles/org.openhab.binding.radiobrowser/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/pom.xml
Labels: new binding

#16430 [ipp] Fix minor typos in README
  bundles/org.openhab.binding.ipp/README.md
Labels: documentation

#16438 [epsonprojector] Add A/V standby power status
  bundles/org.openhab.binding.epsonprojector/src/main/java/org/openhab/binding/epsonprojector/internal/enums/PowerStatus.java
Labels: enhancement

#16440 [jrubyscripting] Update README
  bundles/org.openhab.automation.jrubyscripting/README.md
Labels: documentation

#16422 [melcloud] Adjust to new API limits
  bundles/org.openhab.binding.melcloud/README.md
  bundles/org.openhab.binding.melcloud/src/main/java/org/openhab/binding/melcloud/internal/handler/MelCloudAccountHandler.java
  bundles/org.openhab.binding.melcloud/src/main/resources/OH-INF/thing/acDevice.xml
  bundles/org.openhab.binding.melcloud/src/main/resources/OH-INF/thing/heatpumpDevice.xml
Labels: bug

#14206 [ism8] Add UoM support
  bundles/org.openhab.binding.ism8/README.md
  bundles/org.openhab.binding.ism8/src/main/java/org/openhab/binding/ism8/internal/Ism8BindingConstants.java
  bundles/org.openhab.binding.ism8/src/main/java/org/openhab/binding/ism8/internal/Ism8Handler.java
  bundles/org.openhab.binding.ism8/src/main/java/org/openhab/binding/ism8/internal/util/Ism8DomainMap.java
  bundles/org.openhab.binding.ism8/src/main/java/org/openhab/binding/ism8/server/DataPointBase.java
  bundles/org.openhab.binding.ism8/src/main/java/org/openhab/binding/ism8/server/DataPointBool.java
  bundles/org.openhab.binding.ism8/src/main/java/org/openhab/binding/ism8/server/DataPointLongValue.java
  bundles/org.openhab.binding.ism8/src/main/java/org/openhab/binding/ism8/server/DataPointScaling.java
  bundles/org.openhab.binding.ism8/src/main/java/org/openhab/binding/ism8/server/DataPointValue.java
  bundles/org.openhab.binding.ism8/src/main/java/org/openhab/binding/ism8/server/IDataPoint.java
  bundles/org.openhab.binding.ism8/src/main/java/org/openhab/binding/ism8/server/Server.java
  bundles/org.openhab.binding.ism8/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.ism8/src/test/java/org/openhab/binding/ism8/internal/Ism8HandlerTest.java
  bundles/org.openhab.binding.ism8/src/test/java/org/openhab/binding/ism8/internal/util/Ism8DomainMapTest.java
Labels: enhancement, (potentially) not backward compatible

#16453 [knx] Fix DPT 6.020 and 8.010
  bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/dpt/DPTUtil.java
  bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/dpt/ValueDecoder.java
  bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/dpt/ValueEncoder.java
  bundles/org.openhab.binding.knx/src/test/java/org/openhab/binding/knx/internal/dpt/DPTTest.java
  bundles/org.openhab.binding.knx/src/test/java/org/openhab/binding/knx/internal/itests/Back2BackTest.java
Labels: bug

#16452 [knx] Add list of supported DPTs
  bundles/org.openhab.binding.knx/README.md
Labels: documentation

#16418 [mybmw] Improve data refresh handling
  bundles/org.openhab.binding.mybmw/README.md
  bundles/org.openhab.binding.mybmw/src/main/java/org/openhab/binding/mybmw/internal/MyBMWConstants.java
  bundles/org.openhab.binding.mybmw/src/main/java/org/openhab/binding/mybmw/internal/handler/RemoteServiceExecutor.java
  bundles/org.openhab.binding.mybmw/src/main/java/org/openhab/binding/mybmw/internal/handler/VehicleHandler.java
  bundles/org.openhab.binding.mybmw/src/main/resources/OH-INF/config/thing-config.xml
  bundles/org.openhab.binding.mybmw/src/main/resources/OH-INF/i18n/mybmw.properties
  bundles/org.openhab.binding.mybmw/src/main/resources/OH-INF/thing/ev-vehicle-update-group.xml
  bundles/org.openhab.binding.mybmw/src/main/resources/OH-INF/thing/thing-bev.xml
  bundles/org.openhab.binding.mybmw/src/main/resources/OH-INF/thing/thing-bev_rex.xml
  bundles/org.openhab.binding.mybmw/src/main/resources/OH-INF/thing/thing-conv.xml
  bundles/org.openhab.binding.mybmw/src/main/resources/OH-INF/thing/thing-phev.xml
  bundles/org.openhab.binding.mybmw/src/main/resources/OH-INF/thing/vehicle-update-channel-types.xml
  bundles/org.openhab.binding.mybmw/src/main/resources/OH-INF/thing/vehicle-update-group.xml
  bundles/org.openhab.binding.mybmw/src/main/resources/OH-INF/update/thing-update.xml
  bundles/org.openhab.binding.mybmw/src/test/resources/responses/BEV2/charging_sessions.json
  bundles/org.openhab.binding.mybmw/src/test/resources/responses/BEV2/charging_statistics.json
  bundles/org.openhab.binding.mybmw/src/test/resources/responses/BEV2/vehicles_base.json
  bundles/org.openhab.binding.mybmw/src/test/resources/responses/BEV4/charging_sessions.json
  bundles/org.openhab.binding.mybmw/src/test/resources/responses/BEV4/charging_statistics.json
  bundles/org.openhab.binding.mybmw/src/test/resources/responses/BEV5/charging_sessions.json
  bundles/org.openhab.binding.mybmw/src/test/resources/responses/BEV5/charging_statistics.json
  bundles/org.openhab.binding.mybmw/src/test/resources/responses/PHEV/charging_sessions.json
  bundles/org.openhab.binding.mybmw/src/test/resources/responses/PHEV/charging_statistics.json
Labels: enhancement

#15060 [boschshc] Add command to list SHC device mappings
  bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/console/BoschShcCommandExtension.java
  bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/devices/bridge/BridgeHandler.java
  bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/devices/bridge/dto/Device.java
  bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/devices/bridge/dto/PublicInformation.java
  bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/devices/bridge/dto/Scenario.java
  bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/devices/bridge/dto/SoftwareUpdateState.java
  bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/devices/bridge/dto/SubscribeResult.java
  bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/devices/bridge/dto/UserDefinedState.java
  bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/discovery/ThingDiscoveryService.java
  bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/console/BoschShcCommandExtensionTest.java
Labels: enhancement

#16443 [nuvo] Add source menu channel
  bundles/org.openhab.binding.nuvo/README.md
  bundles/org.openhab.binding.nuvo/src/main/java/org/openhab/binding/nuvo/internal/NuvoBindingConstants.java
  bundles/org.openhab.binding.nuvo/src/main/java/org/openhab/binding/nuvo/internal/handler/NuvoHandler.java
  bundles/org.openhab.binding.nuvo/src/main/resources/OH-INF/i18n/nuvo.properties
  bundles/org.openhab.binding.nuvo/src/main/resources/OH-INF/thing/channels.xml
  bundles/org.openhab.binding.nuvo/src/main/resources/OH-INF/update/update.xml
Labels: enhancement

#16464 [Voice] Fix google and watson speech-to-text services PCM format support
  bundles/org.openhab.voice.googlestt/src/main/java/org/openhab/voice/googlestt/internal/GoogleSTTService.java
  bundles/org.openhab.voice.watsonstt/src/main/java/org/openhab/voice/watsonstt/internal/WatsonSTTService.java
Labels: bug, regression

#16461 [fineoffsetweatherstation] Implement new Measurand `free-heap-size`
  bundles/org.openhab.binding.fineoffsetweatherstation/README.md
  bundles/org.openhab.binding.fineoffsetweatherstation/src/main/java/org/openhab/binding/fineoffsetweatherstation/internal/FineOffsetWeatherStationBindingConstants.java
  bundles/org.openhab.binding.fineoffsetweatherstation/src/main/java/org/openhab/binding/fineoffsetweatherstation/internal/domain/Measurand.java
  bundles/org.openhab.binding.fineoffsetweatherstation/src/main/java/org/openhab/binding/fineoffsetweatherstation/internal/domain/MeasureType.java
  bundles/org.openhab.binding.fineoffsetweatherstation/src/main/resources/OH-INF/i18n/fineoffsetweatherstation.properties
  bundles/org.openhab.binding.fineoffsetweatherstation/src/main/resources/OH-INF/thing/gateway.xml
  bundles/org.openhab.binding.fineoffsetweatherstation/src/test/java/org/openhab/binding/fineoffsetweatherstation/internal/service/FineOffsetDataParserTest.java
Labels: enhancement

#16465 [jythonscripting] Upgrade to Jython 2.7.3
  bundles/org.openhab.automation.jythonscripting/README.md
  bundles/org.openhab.automation.jythonscripting/pom.xml
Labels: enhancement

#16350 [openweathermap] Add daily moon channels to OneCall Thing
  bundles/org.openhab.binding.openweathermap/README.md
  bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/OpenWeatherMapBindingConstants.java
  bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/dto/onecall/Daily.java
  bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/handler/OpenWeatherMapOneCallHandler.java
  bundles/org.openhab.binding.openweathermap/src/main/resources/OH-INF/i18n/openweathermap.properties
  bundles/org.openhab.binding.openweathermap/src/main/resources/OH-INF/thing/channel-types.xml
  bundles/org.openhab.binding.openweathermap/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.openweathermap/src/main/resources/OH-INF/update/instructions.xml
Labels: enhancement
