Repository openhab/openhab-addons, pull requests merged in 2024-06, with the labels that each got.

#16828 [volumio] Fix some commands not working
  bundles/org.openhab.binding.volumio/src/main/java/org/openhab/binding/volumio/internal/mapping/VolumioCommands.java
Labels: bug

#16807 [salus] Add support for AWS
  bundles/org.openhab.binding.salus/NOTICE
  bundles/org.openhab.binding.salus/README.md
  bundles/org.openhab.binding.salus/pom.xml
  bundles/org.openhab.binding.salus/src/main/java/org/openhab/binding/salus/internal/SalusApi.java
  bundles/org.openhab.binding.salus/src/main/java/org/openhab/binding/salus/internal/SalusBindingConstants.java
  bundles/org.openhab.binding.salus/src/main/java/org/openhab/binding/salus/internal/SalusHandlerFactory.java
  bundles/org.openhab.binding.salus/src/main/java/org/openhab/binding/salus/internal/aws/handler/AwsCloudBridgeConfig.java
  bundles/org.openhab.binding.salus/src/main/java/org/openhab/binding/salus/internal/aws/handler/AwsCloudBridgeHandler.java
  bundles/org.openhab.binding.salus/src/main/java/org/openhab/binding/salus/internal/aws/http/Authentication.java
  bundles/org.openhab.binding.salus/src/main/java/org/openhab/binding/salus/internal/aws/http/AuthenticationHelper.java
  bundles/org.openhab.binding.salus/src/main/java/org/openhab/binding/salus/internal/aws/http/AuthenticationResultResponse.java
  bundles/org.openhab.binding.salus/src/main/java/org/openhab/binding/salus/internal/aws/http/AwsSalusApi.java
  bundles/org.openhab.binding.salus/src/main/java/org/openhab/binding/salus/internal/aws/http/ChallengeResponse.java
  bundles/org.openhab.binding.salus/src/main/java/org/openhab/binding/salus/internal/aws/http/CogitoCredentials.java
  bundles/org.openhab.binding.salus/src/main/java/org/openhab/binding/salus/internal/aws/http/CognitoError.java
  bundles/org.openhab.binding.salus/src/main/java/org/openhab/binding/salus/internal/aws/http/CognitoGson.java
  bundles/org.openhab.binding.salus/src/main/java/org/openhab/binding/salus/internal/aws/http/GetCredentialsForIdentityResponse.java
  bundles/org.openhab.binding.salus/src/main/java/org/openhab/binding/salus/internal/aws/http/GetIdResponse.java
  bundles/org.openhab.binding.salus/src/main/java/org/openhab/binding/salus/internal/aws/http/InitiateAuthRequest.java
  bundles/org.openhab.binding.salus/src/main/java/org/openhab/binding/salus/internal/aws/http/InstantDeserializer.java
  bundles/org.openhab.binding.salus/src/main/java/org/openhab/binding/salus/internal/aws/http/RespondToAuthChallengeRequest.java
  bundles/org.openhab.binding.salus/src/main/java/org/openhab/binding/salus/internal/cloud/handler/CloudBridgeConfig.java
  bundles/org.openhab.binding.salus/src/main/java/org/openhab/binding/salus/internal/cloud/handler/CloudBridgeHandler.java
  bundles/org.openhab.binding.salus/src/main/java/org/openhab/binding/salus/internal/cloud/rest/AuthToken.java
  bundles/org.openhab.binding.salus/src/main/java/org/openhab/binding/salus/internal/cloud/rest/HttpSalusApi.java
  bundles/org.openhab.binding.salus/src/main/java/org/openhab/binding/salus/internal/discovery/SalusDiscovery.java
  bundles/org.openhab.binding.salus/src/main/java/org/openhab/binding/salus/internal/handler/AbstractBridgeConfig.java
  bundles/org.openhab.binding.salus/src/main/java/org/openhab/binding/salus/internal/handler/AbstractBridgeHandler.java
  bundles/org.openhab.binding.salus/src/main/java/org/openhab/binding/salus/internal/handler/CloudApi.java
  bundles/org.openhab.binding.salus/src/main/java/org/openhab/binding/salus/internal/handler/DeviceHandler.java
  bundles/org.openhab.binding.salus/src/main/java/org/openhab/binding/salus/internal/handler/It600Handler.java
  bundles/org.openhab.binding.salus/src/main/java/org/openhab/binding/salus/internal/rest/AbstractSalusApi.java
  bundles/org.openhab.binding.salus/src/main/java/org/openhab/binding/salus/internal/rest/Device.java
  bundles/org.openhab.binding.salus/src/main/java/org/openhab/binding/salus/internal/rest/GsonMapper.java
  bundles/org.openhab.binding.salus/src/main/java/org/openhab/binding/salus/internal/rest/HttpClient.java
  bundles/org.openhab.binding.salus/src/main/java/org/openhab/binding/salus/internal/rest/RestClient.java
  bundles/org.openhab.binding.salus/src/main/java/org/openhab/binding/salus/internal/rest/RetryHttpClient.java
  bundles/org.openhab.binding.salus/src/main/java/org/openhab/binding/salus/internal/rest/exceptions/AuthSalusApiException.java
  bundles/org.openhab.binding.salus/src/main/java/org/openhab/binding/salus/internal/rest/exceptions/HttpSalusApiException.java
  bundles/org.openhab.binding.salus/src/main/java/org/openhab/binding/salus/internal/rest/exceptions/SalusApiException.java
  bundles/org.openhab.binding.salus/src/main/java/org/openhab/binding/salus/internal/rest/exceptions/UnsuportedSalusApiException.java
  bundles/org.openhab.binding.salus/src/main/resources/OH-INF/i18n/salus.properties
  bundles/org.openhab.binding.salus/src/main/resources/OH-INF/thing/aws-salus-bridge.xml
  bundles/org.openhab.binding.salus/src/main/resources/OH-INF/thing/it600.xml
  bundles/org.openhab.binding.salus/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.salus/src/test/java/org/openhab/binding/salus/internal/cloud/rest/HttpSalusApiTest.java
  bundles/org.openhab.binding.salus/src/test/java/org/openhab/binding/salus/internal/discovery/SalusDiscoveryTest.java
  bundles/org.openhab.binding.salus/src/test/java/org/openhab/binding/salus/internal/rest/DeviceTest.java
  bundles/org.openhab.binding.salus/src/test/java/org/openhab/binding/salus/internal/rest/GsonMapperTest.java
  bundles/org.openhab.binding.salus/src/test/java/org/openhab/binding/salus/internal/rest/RetryHttpClientTest.java
Labels: enhancement

#16815 [ecotouch] Adding Warmwater Hystersis
  bundles/org.openhab.binding.ecotouch/README.md
  bundles/org.openhab.binding.ecotouch/src/main/java/org/openhab/binding/ecotouch/internal/EcoTouchTags.java
  bundles/org.openhab.binding.ecotouch/src/main/resources/OH-INF/i18n/ecotouch.properties
  bundles/org.openhab.binding.ecotouch/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.ecotouch/src/main/resources/OH-INF/update/instructions.xml
Labels: enhancement

#16802 [epsonprojector] Add SDDP discovery
  bundles/org.openhab.binding.epsonprojector/README.md
  bundles/org.openhab.binding.epsonprojector/src/main/feature/feature.xml
  bundles/org.openhab.binding.epsonprojector/src/main/java/org/openhab/binding/epsonprojector/internal/discovery/EpsonProjectorDiscoveryParticipant.java
Labels: enhancement

#16845 [jdbc] Fix state and timestamp being discarded on `store` with alias
  bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/JdbcPersistenceService.java
Labels: bug

#16803 [snmp] SNMP v3 fixes and improvements
  bundles/org.openhab.binding.snmp/README.md
  bundles/org.openhab.binding.snmp/pom.xml
  bundles/org.openhab.binding.snmp/src/main/java/org/openhab/binding/snmp/internal/SnmpService.java
  bundles/org.openhab.binding.snmp/src/main/java/org/openhab/binding/snmp/internal/SnmpServiceImpl.java
  bundles/org.openhab.binding.snmp/src/main/java/org/openhab/binding/snmp/internal/SnmpTargetHandler.java
  bundles/org.openhab.binding.snmp/src/main/java/org/openhab/binding/snmp/internal/config/SnmpTargetConfiguration.java
  bundles/org.openhab.binding.snmp/src/main/java/org/openhab/binding/snmp/internal/types/SnmpPrivProtocol.java
  bundles/org.openhab.binding.snmp/src/main/resources/OH-INF/i18n/snmp.properties
  bundles/org.openhab.binding.snmp/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.snmp/src/test/java/org/openhab/binding/snmp/internal/AbstractSnmpTargetHandlerTest.java
Labels: enhancement, community approved

#16838 [systeminfo] Reduce code complexity as well garbage collection
  bundles/org.openhab.binding.systeminfo/src/main/java/org/openhab/binding/systeminfo/internal/SystemInfoBindingConstants.java
  bundles/org.openhab.binding.systeminfo/src/main/java/org/openhab/binding/systeminfo/internal/SystemInfoHandlerFactory.java
  bundles/org.openhab.binding.systeminfo/src/main/java/org/openhab/binding/systeminfo/internal/SystemInfoThingTypeProvider.java
  bundles/org.openhab.binding.systeminfo/src/main/java/org/openhab/binding/systeminfo/internal/discovery/SystemInfoDiscoveryService.java
  bundles/org.openhab.binding.systeminfo/src/main/java/org/openhab/binding/systeminfo/internal/handler/SystemInfoHandler.java
  bundles/org.openhab.binding.systeminfo/src/main/resources/OH-INF/thing/computer.xml
Labels: enhancement

#16848 [benqprojector] Add SDDP discovery and missing menu options
  bundles/org.openhab.binding.benqprojector/README.md
  bundles/org.openhab.binding.benqprojector/src/main/feature/feature.xml
  bundles/org.openhab.binding.benqprojector/src/main/java/org/openhab/binding/benqprojector/internal/discovery/BenqProjectorDiscoveryParticipant.java
  bundles/org.openhab.binding.benqprojector/src/main/java/org/openhab/binding/benqprojector/internal/discovery/BenqProjectorDiscoveryService.java
  bundles/org.openhab.binding.benqprojector/src/main/resources/OH-INF/addon/addon.xml
  bundles/org.openhab.binding.benqprojector/src/main/resources/OH-INF/i18n/benqprojector.properties
  bundles/org.openhab.binding.benqprojector/src/main/resources/OH-INF/thing/thing-types.xml
Labels: enhancement

#16832 [atlona] Replace discovery service with core SDDP discovery
  bundles/org.openhab.binding.atlona/README.md
  bundles/org.openhab.binding.atlona/src/main/feature/feature.xml
  bundles/org.openhab.binding.atlona/src/main/java/org/openhab/binding/atlona/internal/discovery/AtlonaDiscovery.java
  bundles/org.openhab.binding.atlona/src/main/java/org/openhab/binding/atlona/internal/discovery/AtlonaDiscoveryParticipant.java
  bundles/org.openhab.binding.atlona/src/main/resources/OH-INF/addon/addon.xml
Labels: enhancement

#16854 [govee] docs: remove device type
  bundles/org.openhab.binding.govee/README.md
Labels: documentation

#16842 [senechome] Add additional states
  bundles/org.openhab.binding.senechome/src/main/java/org/openhab/binding/senechome/internal/SenecSystemStatus.java
Labels: enhancement

#16859 [energidataservice] Fix UoM in documentation example
  bundles/org.openhab.binding.energidataservice/README.md
Labels: documentation

#16860 [epsonprojector] Incorporate review suggestions from other PRs
  bundles/org.openhab.binding.epsonprojector/src/main/java/org/openhab/binding/epsonprojector/internal/discovery/EpsonProjectorDiscoveryParticipant.java
  bundles/org.openhab.binding.epsonprojector/src/main/java/org/openhab/binding/epsonprojector/internal/discovery/EpsonProjectorDiscoveryService.java
  bundles/org.openhab.binding.epsonprojector/src/main/resources/OH-INF/addon/addon.xml
  bundles/org.openhab.binding.epsonprojector/src/main/resources/OH-INF/i18n/epsonprojector.properties
  bundles/org.openhab.binding.epsonprojector/src/main/resources/OH-INF/thing/thing-types.xml
Labels: regression

#16857 [mqtt] Fix certificate pinning
  bundles/org.openhab.binding.mqtt/src/main/java/org/openhab/binding/mqtt/handler/BrokerHandler.java
  bundles/org.openhab.binding.mqtt/src/main/java/org/openhab/binding/mqtt/internal/ssl/Pin.java
Labels: bug

#16853 [hdpowerview] Improvements to SDDP discovery
  bundles/org.openhab.binding.hdpowerview/src/main/feature/feature.xml
  bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/discovery/HDPowerViewHubDiscoveryParticipantSddp.java
  bundles/org.openhab.binding.hdpowerview/src/main/resources/OH-INF/addon/addon.xml
Labels: enhancement

#16819 [solarforecast] wait 1 hour after http 429 error
  bundles/org.openhab.binding.solarforecast/src/main/java/org/openhab/binding/solarforecast/internal/SolarForecastHandlerFactory.java
  bundles/org.openhab.binding.solarforecast/src/main/java/org/openhab/binding/solarforecast/internal/forecastsolar/handler/ForecastSolarBridgeHandler.java
  bundles/org.openhab.binding.solarforecast/src/main/java/org/openhab/binding/solarforecast/internal/forecastsolar/handler/ForecastSolarPlaneHandler.java
  bundles/org.openhab.binding.solarforecast/src/main/java/org/openhab/binding/solarforecast/internal/utils/Utils.java
  bundles/org.openhab.binding.solarforecast/src/main/resources/OH-INF/i18n/solarforecast.properties
  bundles/org.openhab.binding.solarforecast/src/test/java/org/openhab/binding/solarforecast/CallbackMock.java
  bundles/org.openhab.binding.solarforecast/src/test/java/org/openhab/binding/solarforecast/ForecastSolarTest.java
Labels: bug

#16846 [icloud] Use device.Id instead of device.DiscoveryId to fix playsound
  bundles/org.openhab.binding.icloud/src/main/java/org/openhab/binding/icloud/internal/handler/ICloudDeviceHandler.java
Labels: bug

#16855 [boschshc] Bump Bouncy Castle Dependencies to 1.78.1
  bundles/org.openhab.binding.boschshc/pom.xml
Labels: security

#16863 [androidtv] Bump bouncy castle to 1.78.1
  bundles/org.openhab.binding.androidtv/pom.xml
Labels: enhancement

#16851 [airgradient] Support configuration of devices for firmware v3.1.1 and later
  bundles/org.openhab.binding.airgradient/README.md
  bundles/org.openhab.binding.airgradient/src/main/java/org/openhab/binding/airgradient/internal/AirGradientBindingConstants.java
  bundles/org.openhab.binding.airgradient/src/main/java/org/openhab/binding/airgradient/internal/communication/RESTHelper.java
  bundles/org.openhab.binding.airgradient/src/main/java/org/openhab/binding/airgradient/internal/communication/RemoteAPIController.java
  bundles/org.openhab.binding.airgradient/src/main/java/org/openhab/binding/airgradient/internal/handler/AirGradientLocalHandler.java
  bundles/org.openhab.binding.airgradient/src/main/java/org/openhab/binding/airgradient/internal/handler/ConfigurationHelper.java
  bundles/org.openhab.binding.airgradient/src/main/java/org/openhab/binding/airgradient/internal/handler/DynamicChannelHelper.java
  bundles/org.openhab.binding.airgradient/src/main/java/org/openhab/binding/airgradient/internal/handler/MeasureHelper.java
  bundles/org.openhab.binding.airgradient/src/main/java/org/openhab/binding/airgradient/internal/model/LocalConfiguration.java
  bundles/org.openhab.binding.airgradient/src/main/java/org/openhab/binding/airgradient/internal/model/Measure.java
  bundles/org.openhab.binding.airgradient/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.airgradient/src/test/java/org/openhab/binding/airgradient/internal/handler/AirGradientLocationHandlerTest.java
  bundles/org.openhab.binding.airgradient/src/test/java/org/openhab/binding/airgradient/internal/handler/RemoteApiControllerTest.java
Labels: enhancement

#16864 [nibeheatpump] Updated NibeGW readme
  bundles/org.openhab.binding.nibeheatpump/contrib/NibeGW/Arduino/README.md
Labels: documentation

#16849 [sonyprojector] Add discovery through SDDP
  bundles/org.openhab.binding.sonyprojector/README.md
  bundles/org.openhab.binding.sonyprojector/src/main/feature/feature.xml
  bundles/org.openhab.binding.sonyprojector/src/main/java/org/openhab/binding/sonyprojector/internal/communication/SonyProjectorItem.java
  bundles/org.openhab.binding.sonyprojector/src/main/java/org/openhab/binding/sonyprojector/internal/communication/sdcp/SonyProjectorSdcpConnector.java
  bundles/org.openhab.binding.sonyprojector/src/main/java/org/openhab/binding/sonyprojector/internal/configuration/SonyProjectorEthernetConfiguration.java
  bundles/org.openhab.binding.sonyprojector/src/main/java/org/openhab/binding/sonyprojector/internal/configuration/SonyProjectorSerialConfiguration.java
  bundles/org.openhab.binding.sonyprojector/src/main/java/org/openhab/binding/sonyprojector/internal/configuration/SonyProjectorSerialOverIpConfiguration.java
  bundles/org.openhab.binding.sonyprojector/src/main/java/org/openhab/binding/sonyprojector/internal/discovery/SonyProjectorDiscoveryParticipant.java
  bundles/org.openhab.binding.sonyprojector/src/main/java/org/openhab/binding/sonyprojector/internal/handler/SonyProjectorHandler.java
  bundles/org.openhab.binding.sonyprojector/src/main/resources/OH-INF/addon/addon.xml
Labels: enhancement

#16866 [MQTT] Fix state description
  bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/values/DateTimeValue.java
  bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/values/NumberValue.java
  bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/values/PercentageValue.java
  bundles/org.openhab.binding.mqtt.generic/src/test/java/org/openhab/binding/mqtt/generic/values/ValueTests.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/component/SensorTests.java
Labels: bug

#16840 [salus] Salus auth
  bundles/org.openhab.binding.salus/NOTICE
  bundles/org.openhab.binding.salus/pom.xml
  bundles/org.openhab.binding.salus/src/main/java/org/openhab/binding/salus/internal/aws/http/AwsSalusApi.java
  bundles/org.openhab.binding.salus/src/main/java/org/openhab/binding/salus/internal/aws/http/AwsSigner.java
  bundles/org.openhab.binding.salus/src/test/java/org/openhab/binding/salus/internal/aws/http/AwsSignerTest.java
Labels: work in progress

#16861 [tado] Add mDNS discovery
  bundles/org.openhab.binding.tado/README.md
  bundles/org.openhab.binding.tado/src/main/java/org/openhab/binding/tado/internal/discovery/TadoDiscoveryParticipant.java
  bundles/org.openhab.binding.tado/src/main/resources/OH-INF/i18n/tado.properties
Labels: enhancement

#16868 [verisure] Fix NPE (#16867)
  bundles/org.openhab.binding.verisure/src/main/java/org/openhab/binding/verisure/internal/dto/VerisureAlarmsDTO.java
Labels: bug

#16850 [amberelectric] Initial contribution
  CODEOWNERS
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.amberelectric/NOTICE
  bundles/org.openhab.binding.amberelectric/README.md
  bundles/org.openhab.binding.amberelectric/pom.xml
  bundles/org.openhab.binding.amberelectric/src/main/feature/feature.xml
  bundles/org.openhab.binding.amberelectric/src/main/java/org/openhab/binding/amberelectric/internal/AmberElectricBindingConstants.java
  bundles/org.openhab.binding.amberelectric/src/main/java/org/openhab/binding/amberelectric/internal/AmberElectricCommunicationException.java
  bundles/org.openhab.binding.amberelectric/src/main/java/org/openhab/binding/amberelectric/internal/AmberElectricConfiguration.java
  bundles/org.openhab.binding.amberelectric/src/main/java/org/openhab/binding/amberelectric/internal/AmberElectricHandler.java
  bundles/org.openhab.binding.amberelectric/src/main/java/org/openhab/binding/amberelectric/internal/AmberElectricHandlerFactory.java
  bundles/org.openhab.binding.amberelectric/src/main/java/org/openhab/binding/amberelectric/internal/AmberElectricWebTargets.java
  bundles/org.openhab.binding.amberelectric/src/main/java/org/openhab/binding/amberelectric/internal/api/CurrentPrices.java
  bundles/org.openhab.binding.amberelectric/src/main/java/org/openhab/binding/amberelectric/internal/api/Sites.java
  bundles/org.openhab.binding.amberelectric/src/main/resources/OH-INF/addon/addon.xml
  bundles/org.openhab.binding.amberelectric/src/main/resources/OH-INF/i18n/amberelectric.properties
  bundles/org.openhab.binding.amberelectric/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/pom.xml
Labels: new binding

#16786 [mffan] Initial contribution
  CODEOWNERS
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.mffan/NOTICE
  bundles/org.openhab.binding.mffan/README.md
  bundles/org.openhab.binding.mffan/pom.xml
  bundles/org.openhab.binding.mffan/src/main/feature/feature.xml
  bundles/org.openhab.binding.mffan/src/main/java/org/openhab/binding/mffan/internal/MfFanBindingConstants.java
  bundles/org.openhab.binding.mffan/src/main/java/org/openhab/binding/mffan/internal/MfFanConfiguration.java
  bundles/org.openhab.binding.mffan/src/main/java/org/openhab/binding/mffan/internal/MfFanHandlerFactory.java
  bundles/org.openhab.binding.mffan/src/main/java/org/openhab/binding/mffan/internal/api/FanRestApi.java
  bundles/org.openhab.binding.mffan/src/main/java/org/openhab/binding/mffan/internal/api/RestApiException.java
  bundles/org.openhab.binding.mffan/src/main/java/org/openhab/binding/mffan/internal/api/ShadowBufferDto.java
  bundles/org.openhab.binding.mffan/src/main/java/org/openhab/binding/mffan/internal/handler/MfFanHandler.java
  bundles/org.openhab.binding.mffan/src/main/resources/OH-INF/addon/addon.xml
  bundles/org.openhab.binding.mffan/src/main/resources/OH-INF/i18n/mffan.properties
  bundles/org.openhab.binding.mffan/src/main/resources/OH-INF/thing/mffan.xml
  bundles/pom.xml
Labels: new binding

#16865 [hdpowerview] Improve Gen 1/2 discovery label
  bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/GatewayWebTargets.java
  bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/discovery/HDPowerViewHubMDNSDiscoveryParticipant.java
  bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/discovery/HDPowerViewSddpDiscoveryParticipant.java
  bundles/org.openhab.binding.hdpowerview/src/main/resources/OH-INF/i18n/hdpowerview.properties
Labels: enhancement

#16831 [pegelonline] Initial contribution
  CODEOWNERS
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.pegelonline/NOTICE
  bundles/org.openhab.binding.pegelonline/README.md
  bundles/org.openhab.binding.pegelonline/doc/Marburg.png
  bundles/org.openhab.binding.pegelonline/pom.xml
  bundles/org.openhab.binding.pegelonline/src/main/feature/feature.xml
  bundles/org.openhab.binding.pegelonline/src/main/java/org/openhab/binding/pegelonline/internal/PegelOnlineBindingConstants.java
  bundles/org.openhab.binding.pegelonline/src/main/java/org/openhab/binding/pegelonline/internal/PegelOnlineHandlerFactory.java
  bundles/org.openhab.binding.pegelonline/src/main/java/org/openhab/binding/pegelonline/internal/config/PegelOnlineConfiguration.java
  bundles/org.openhab.binding.pegelonline/src/main/java/org/openhab/binding/pegelonline/internal/discovery/PegelDiscovery.java
  bundles/org.openhab.binding.pegelonline/src/main/java/org/openhab/binding/pegelonline/internal/dto/Measure.java
  bundles/org.openhab.binding.pegelonline/src/main/java/org/openhab/binding/pegelonline/internal/dto/Station.java
  bundles/org.openhab.binding.pegelonline/src/main/java/org/openhab/binding/pegelonline/internal/dto/Water.java
  bundles/org.openhab.binding.pegelonline/src/main/java/org/openhab/binding/pegelonline/internal/handler/PegelOnlineHandler.java
  bundles/org.openhab.binding.pegelonline/src/main/java/org/openhab/binding/pegelonline/internal/utils/Utils.java
  bundles/org.openhab.binding.pegelonline/src/main/resources/OH-INF/addon/addon.xml
  bundles/org.openhab.binding.pegelonline/src/main/resources/OH-INF/i18n/pegelonline.properties
  bundles/org.openhab.binding.pegelonline/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.pegelonline/src/test/java/org/openhab/binding/pegelonline/internal/handler/CallbackMock.java
  bundles/org.openhab.binding.pegelonline/src/test/java/org/openhab/binding/pegelonline/internal/handler/PegelTest.java
  bundles/org.openhab.binding.pegelonline/src/test/java/org/openhab/binding/pegelonline/internal/util/FileReader.java
  bundles/org.openhab.binding.pegelonline/src/test/resources/measure.json
  bundles/org.openhab.binding.pegelonline/src/test/resources/rivers.json
  bundles/org.openhab.binding.pegelonline/src/test/resources/stations.json
  bundles/pom.xml
Labels: new binding

#16880 [openwebnet] Fix tables in README
  bundles/org.openhab.binding.openwebnet/README.md
Labels: documentation

#16882 [tellstick] Fix NPE (#16869)
  bundles/org.openhab.binding.tellstick/src/main/java/org/openhab/binding/tellstick/internal/local/TelldusLocalBridgeHandler.java
  bundles/org.openhab.binding.tellstick/src/main/java/org/openhab/binding/tellstick/internal/local/TelldusLocalDeviceController.java
Labels: bug

#16834 [nikohomecontrol] Alarm systems
  bundles/org.openhab.binding.nikohomecontrol/README.md
  bundles/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/NikoHomeControlBindingConstants.java
  bundles/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/NikoHomeControlHandlerFactory.java
  bundles/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/discovery/NikoHomeControlDiscoveryService.java
  bundles/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/handler/NikoHomeControlAccessHandler.java
  bundles/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/handler/NikoHomeControlAlarmConfig.java
  bundles/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/handler/NikoHomeControlAlarmHandler.java
  bundles/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/handler/NikoHomeControlMeterHandler.java
  bundles/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/protocol/NhcAlarm.java
  bundles/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/protocol/NhcAlarmEvent.java
  bundles/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/protocol/NikoHomeControlCommunication.java
  bundles/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/protocol/NikoHomeControlConstants.java
  bundles/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/protocol/nhc2/NhcAlarm2.java
  bundles/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/protocol/nhc2/NhcDevice2.java
  bundles/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/protocol/nhc2/NhcMqttConnection2.java
  bundles/org.openhab.binding.nikohomecontrol/src/main/java/org/openhab/binding/nikohomecontrol/internal/protocol/nhc2/NikoHomeControlCommunication2.java
  bundles/org.openhab.binding.nikohomecontrol/src/main/resources/OH-INF/i18n/nikohomecontrol.properties
  bundles/org.openhab.binding.nikohomecontrol/src/main/resources/OH-INF/thing/thing-types.xml
Labels: enhancement

#16884 [shelly] Update README regarding discovery of BLU devices
  bundles/org.openhab.binding.shelly/README.md
Labels: documentation

#16886 [pegelonline] fix junit status race condition
  bundles/org.openhab.binding.pegelonline/src/test/java/org/openhab/binding/pegelonline/internal/handler/PegelTest.java
Labels: test

#16891 [emotiva] Remove discovery-methods because of missing listen port support in scanBroadcast
  bundles/org.openhab.binding.emotiva/src/main/resources/OH-INF/addon/addon.xml
Labels: bug, regression

#16889 [energidataservice] Provide JavaScript example for persisting total price
  bundles/org.openhab.binding.energidataservice/README.md
Labels: documentation

#16879 [bluetooth.airthings] Add support for Airthings Wave Radon
  bundles/org.openhab.binding.bluetooth.airthings/README.md
  bundles/org.openhab.binding.bluetooth.airthings/src/main/java/org/openhab/binding/bluetooth/airthings/internal/AirthingsBindingConstants.java
  bundles/org.openhab.binding.bluetooth.airthings/src/main/java/org/openhab/binding/bluetooth/airthings/internal/AirthingsDataParser.java
  bundles/org.openhab.binding.bluetooth.airthings/src/main/java/org/openhab/binding/bluetooth/airthings/internal/AirthingsDiscoveryParticipant.java
  bundles/org.openhab.binding.bluetooth.airthings/src/main/java/org/openhab/binding/bluetooth/airthings/internal/AirthingsHandlerFactory.java
  bundles/org.openhab.binding.bluetooth.airthings/src/main/java/org/openhab/binding/bluetooth/airthings/internal/AirthingsWaveRadonHandler.java
  bundles/org.openhab.binding.bluetooth.airthings/src/main/resources/OH-INF/i18n/bluetooth.properties
  bundles/org.openhab.binding.bluetooth.airthings/src/main/resources/OH-INF/thing/airthings.xml
  bundles/org.openhab.binding.bluetooth.airthings/src/test/java/org/openhab/binding/bluetooth/airthings/AirthingsParserTest.java
Labels: enhancement

#14072 [nibeheatpump] Fix serial params
  bundles/org.openhab.binding.nibeheatpump/contrib/NibeGW/RasPi/nibegw.c
Labels: bug

#16902 [hue] API v1: retry once on timeout for GET requests to the bridge
  bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/connection/HueBridge.java
Labels: enhancement

#16917 [jellyfin] Add support for 10.9.x Jellyfin Servers
  bundles/org.openhab.binding.jellyfin/pom.xml
Labels: enhancement

#15166 [WhisperSTT] Initial contribution
  CODEOWNERS
  bom/openhab-addons/pom.xml
  bundles/org.openhab.voice.whisperstt/NOTICE
  bundles/org.openhab.voice.whisperstt/README.md
  bundles/org.openhab.voice.whisperstt/pom.xml
  bundles/org.openhab.voice.whisperstt/src/main/feature/feature.xml
  bundles/org.openhab.voice.whisperstt/src/main/java/org/openhab/voice/whisperstt/internal/WhisperConfigOptionProvider.java
  bundles/org.openhab.voice.whisperstt/src/main/java/org/openhab/voice/whisperstt/internal/WhisperSTTConfiguration.java
  bundles/org.openhab.voice.whisperstt/src/main/java/org/openhab/voice/whisperstt/internal/WhisperSTTConstants.java
  bundles/org.openhab.voice.whisperstt/src/main/java/org/openhab/voice/whisperstt/internal/WhisperSTTService.java
  bundles/org.openhab.voice.whisperstt/src/main/java/org/openhab/voice/whisperstt/internal/utils/VAD.java
  bundles/org.openhab.voice.whisperstt/src/main/resources/OH-INF/addon/addon.xml
  bundles/org.openhab.voice.whisperstt/src/main/resources/OH-INF/config/config.xml
  bundles/org.openhab.voice.whisperstt/src/main/resources/OH-INF/i18n/whisperstt.properties
  bundles/pom.xml
Labels: new voice

#16927 [ephemeris] Clean up i18n entries
  bundles/org.openhab.binding.ephemeris/src/main/resources/OH-INF/i18n/ephemeris.properties
Labels: i18n

#16871 [awattar] Add tests and improve code
  bundles/org.openhab.binding.awattar/src/main/java/org/openhab/binding/awattar/internal/AwattarBestPriceResult.java
  bundles/org.openhab.binding.awattar/src/main/java/org/openhab/binding/awattar/internal/AwattarBestpriceConfiguration.java
  bundles/org.openhab.binding.awattar/src/main/java/org/openhab/binding/awattar/internal/AwattarBindingConstants.java
  bundles/org.openhab.binding.awattar/src/main/java/org/openhab/binding/awattar/internal/AwattarBridgeConfiguration.java
  bundles/org.openhab.binding.awattar/src/main/java/org/openhab/binding/awattar/internal/AwattarConsecutiveBestPriceResult.java
  bundles/org.openhab.binding.awattar/src/main/java/org/openhab/binding/awattar/internal/AwattarNonConsecutiveBestPriceResult.java
  bundles/org.openhab.binding.awattar/src/main/java/org/openhab/binding/awattar/internal/AwattarPrice.java
  bundles/org.openhab.binding.awattar/src/main/java/org/openhab/binding/awattar/internal/AwattarUtil.java
  bundles/org.openhab.binding.awattar/src/main/java/org/openhab/binding/awattar/internal/handler/AwattarBestpriceHandler.java
  bundles/org.openhab.binding.awattar/src/main/java/org/openhab/binding/awattar/internal/handler/AwattarBridgeHandler.java
  bundles/org.openhab.binding.awattar/src/main/java/org/openhab/binding/awattar/internal/handler/AwattarHandlerFactory.java
  bundles/org.openhab.binding.awattar/src/main/java/org/openhab/binding/awattar/internal/handler/AwattarPriceHandler.java
  bundles/org.openhab.binding.awattar/src/main/java/org/openhab/binding/awattar/internal/handler/TimeRange.java
  bundles/org.openhab.binding.awattar/src/test/java/org/openhab/binding/awattar/internal/handler/AwattarBridgeHandlerTest.java
  bundles/org.openhab.binding.awattar/src/test/resources/org/openhab/binding/awattar/internal/handler/api_response.json
Labels: enhancement

#16922 [voice] Allow speech-to-text services to emit empty error events
  bundles/org.openhab.voice.googlestt/src/main/java/org/openhab/voice/googlestt/internal/GoogleSTTService.java
  bundles/org.openhab.voice.voskstt/src/main/java/org/openhab/voice/voskstt/internal/VoskSTTService.java
  bundles/org.openhab.voice.watsonstt/README.md
  bundles/org.openhab.voice.watsonstt/src/main/java/org/openhab/voice/watsonstt/internal/WatsonSTTConfiguration.java
  bundles/org.openhab.voice.watsonstt/src/main/java/org/openhab/voice/watsonstt/internal/WatsonSTTService.java
  bundles/org.openhab.voice.watsonstt/src/main/resources/OH-INF/config/config.xml
  bundles/org.openhab.voice.watsonstt/src/main/resources/OH-INF/i18n/watsonstt.properties
Labels: enhancement

#16931 [mffan] Regenerate the i18n file
  bundles/org.openhab.binding.mffan/src/main/resources/OH-INF/i18n/mffan.properties
Labels: i18n

#16897 [mercedesme] Refactor code and fix test
  bundles/org.openhab.binding.mercedesme/src/main/java/org/openhab/binding/mercedesme/internal/handler/AccountHandler.java
  bundles/org.openhab.binding.mercedesme/src/main/java/org/openhab/binding/mercedesme/internal/handler/VehicleHandler.java
  bundles/org.openhab.binding.mercedesme/src/test/java/org/openhab/binding/mercedesme/StatusTests.java
  bundles/org.openhab.binding.mercedesme/src/test/java/org/openhab/binding/mercedesme/internal/handler/AccountHandlerMock.java
  bundles/org.openhab.binding.mercedesme/src/test/java/org/openhab/binding/mercedesme/internal/handler/VehicleHandlerTest.java
Labels: enhancement, additional testing preferred

#16935 [jsscripting] Upgrade openhab-js to 5.2.0
  bundles/org.openhab.automation.jsscripting/README.md
  bundles/org.openhab.automation.jsscripting/pom.xml
Labels: enhancement

#16841 [smaenergymeter] Make sure that energy meter packets are not queued up.
  bundles/org.openhab.binding.smaenergymeter/README.md
  bundles/org.openhab.binding.smaenergymeter/src/main/java/org/openhab/binding/smaenergymeter/internal/discovery/SMAEnergyMeterDiscoveryService.java
  bundles/org.openhab.binding.smaenergymeter/src/main/java/org/openhab/binding/smaenergymeter/internal/handler/SMAEnergyMeterHandler.java
  bundles/org.openhab.binding.smaenergymeter/src/main/java/org/openhab/binding/smaenergymeter/internal/packet/DefaultPacketListenerRegistry.java
  bundles/org.openhab.binding.smaenergymeter/src/main/java/org/openhab/binding/smaenergymeter/internal/packet/FilteringPayloadHandler.java
  bundles/org.openhab.binding.smaenergymeter/src/main/java/org/openhab/binding/smaenergymeter/internal/packet/PacketListener.java
  bundles/org.openhab.binding.smaenergymeter/src/main/java/org/openhab/binding/smaenergymeter/internal/packet/ThrottlingPayloadHandler.java
Labels: bug

#16938 [openhabcloud] Enhanced Notification Actions
  bundles/org.openhab.io.openhabcloud/src/main/java/org/openhab/io/openhabcloud/NotificationAction.java
  bundles/org.openhab.io.openhabcloud/src/main/java/org/openhab/io/openhabcloud/internal/CloudClient.java
  bundles/org.openhab.io.openhabcloud/src/main/java/org/openhab/io/openhabcloud/internal/CloudService.java
  bundles/org.openhab.io.openhabcloud/src/main/java/org/openhab/io/openhabcloud/internal/actions/BaseNotificationActionHandler.java
  bundles/org.openhab.io.openhabcloud/src/main/java/org/openhab/io/openhabcloud/internal/actions/NotificationActionTypeProvider.java
  bundles/org.openhab.io.openhabcloud/src/main/java/org/openhab/io/openhabcloud/internal/actions/NotificationModuleHandlerFactory.java
  bundles/org.openhab.io.openhabcloud/src/main/java/org/openhab/io/openhabcloud/internal/actions/SendBroadcastNotificationActionHandler.java
  bundles/org.openhab.io.openhabcloud/src/main/java/org/openhab/io/openhabcloud/internal/actions/SendNotificationActionHandler.java
Labels: work in progress

#16941 [openhabcloud] Update README for new notification features
  bundles/org.openhab.io.openhabcloud/README.md
Labels: documentation

#16496 [inmemory] Default persistence strategy Forecast
  bundles/org.openhab.persistence.inmemory/README.md
  bundles/org.openhab.persistence.inmemory/src/main/java/org/openhab/persistence/inmemory/internal/InMemoryPersistenceService.java
Labels: enhancement

#16898 [bosesoundtouch] Fix parsing of metadata fields
  bundles/org.openhab.binding.bosesoundtouch/src/main/java/org/openhab/binding/bosesoundtouch/internal/XMLResponseHandler.java
  bundles/org.openhab.binding.bosesoundtouch/src/main/java/org/openhab/binding/bosesoundtouch/internal/XMLResponseProcessor.java
  bundles/org.openhab.binding.bosesoundtouch/src/test/java/org/openhab/binding/bosesoundtouch/internal/XMLResponseProcessorTest.java
  bundles/org.openhab.binding.bosesoundtouch/src/test/resources/NowPlayingUpdate.xml
Labels: bug, additional testing preferred

#16914 [livisismarthome] Add support for the indoor siren device
  bundles/org.openhab.binding.livisismarthome/README.md
  bundles/org.openhab.binding.livisismarthome/src/main/java/org/openhab/binding/livisismarthome/internal/LivisiBindingConstants.java
  bundles/org.openhab.binding.livisismarthome/src/main/java/org/openhab/binding/livisismarthome/internal/client/LivisiClient.java
  bundles/org.openhab.binding.livisismarthome/src/main/java/org/openhab/binding/livisismarthome/internal/client/api/entity/action/ActionParamsDTO.java
  bundles/org.openhab.binding.livisismarthome/src/main/java/org/openhab/binding/livisismarthome/internal/client/api/entity/action/StateActionSetterDTO.java
  bundles/org.openhab.binding.livisismarthome/src/main/java/org/openhab/binding/livisismarthome/internal/client/api/entity/capability/CapabilityDTO.java
  bundles/org.openhab.binding.livisismarthome/src/main/java/org/openhab/binding/livisismarthome/internal/client/api/entity/capability/CapabilityStateDTO.java
  bundles/org.openhab.binding.livisismarthome/src/main/java/org/openhab/binding/livisismarthome/internal/client/api/entity/event/EventPropertiesDTO.java
  bundles/org.openhab.binding.livisismarthome/src/main/java/org/openhab/binding/livisismarthome/internal/handler/LivisiBridgeHandler.java
  bundles/org.openhab.binding.livisismarthome/src/main/java/org/openhab/binding/livisismarthome/internal/handler/LivisiDeviceHandler.java
  bundles/org.openhab.binding.livisismarthome/src/main/resources/OH-INF/thing/SIR.xml
  bundles/org.openhab.binding.livisismarthome/src/main/resources/OH-INF/thing/channels.xml
Labels: enhancement

#16876 [teslapowerwall] Initial contribution
  CODEOWNERS
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.teslapowerwall/NOTICE
  bundles/org.openhab.binding.teslapowerwall/README.md
  bundles/org.openhab.binding.teslapowerwall/pom.xml
  bundles/org.openhab.binding.teslapowerwall/src/main/feature/feature.xml
  bundles/org.openhab.binding.teslapowerwall/src/main/java/org/openhab/binding/teslapowerwall/internal/TeslaPowerwallAuthenticationException.java
  bundles/org.openhab.binding.teslapowerwall/src/main/java/org/openhab/binding/teslapowerwall/internal/TeslaPowerwallBindingConstants.java
  bundles/org.openhab.binding.teslapowerwall/src/main/java/org/openhab/binding/teslapowerwall/internal/TeslaPowerwallCommunicationException.java
  bundles/org.openhab.binding.teslapowerwall/src/main/java/org/openhab/binding/teslapowerwall/internal/TeslaPowerwallConfiguration.java
  bundles/org.openhab.binding.teslapowerwall/src/main/java/org/openhab/binding/teslapowerwall/internal/TeslaPowerwallHandler.java
  bundles/org.openhab.binding.teslapowerwall/src/main/java/org/openhab/binding/teslapowerwall/internal/TeslaPowerwallHandlerFactory.java
  bundles/org.openhab.binding.teslapowerwall/src/main/java/org/openhab/binding/teslapowerwall/internal/TeslaPowerwallTlsTrustManagerProvider.java
  bundles/org.openhab.binding.teslapowerwall/src/main/java/org/openhab/binding/teslapowerwall/internal/TeslaPowerwallWebTargets.java
  bundles/org.openhab.binding.teslapowerwall/src/main/java/org/openhab/binding/teslapowerwall/internal/api/BatterySOE.java
  bundles/org.openhab.binding.teslapowerwall/src/main/java/org/openhab/binding/teslapowerwall/internal/api/GridStatus.java
  bundles/org.openhab.binding.teslapowerwall/src/main/java/org/openhab/binding/teslapowerwall/internal/api/MeterAggregates.java
  bundles/org.openhab.binding.teslapowerwall/src/main/java/org/openhab/binding/teslapowerwall/internal/api/Operations.java
  bundles/org.openhab.binding.teslapowerwall/src/main/java/org/openhab/binding/teslapowerwall/internal/api/SystemStatus.java
  bundles/org.openhab.binding.teslapowerwall/src/main/resources/OH-INF/addon/addon.xml
  bundles/org.openhab.binding.teslapowerwall/src/main/resources/OH-INF/i18n/teslapowerwall.properties
  bundles/org.openhab.binding.teslapowerwall/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/pom.xml
Labels: new binding

#16948 Add JRuby examples in READMEs
  bundles/org.openhab.binding.deconz/README.md
  bundles/org.openhab.binding.dmx/README.md
  bundles/org.openhab.binding.energidataservice/README.md
  bundles/org.openhab.binding.homematic/README.md
  bundles/org.openhab.binding.mail/README.md
  bundles/org.openhab.binding.omnilink/README.md
  bundles/org.openhab.binding.openwebnet/README.md
  bundles/org.openhab.transform.vat/README.md
Labels: documentation

#16942 [openhabcloud] Further README improvements
  bundles/org.openhab.io.openhabcloud/README.md
  bundles/org.openhab.io.openhabcloud/doc/configuration.png
Labels: documentation

#14263 [siemenshvac] Initial contribution
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.siemenshvac/NOTICE
  bundles/org.openhab.binding.siemenshvac/README.md
  bundles/org.openhab.binding.siemenshvac/doc/Albatros.jpg
  bundles/org.openhab.binding.siemenshvac/doc/Diagram.png
  bundles/org.openhab.binding.siemenshvac/pom.xml
  bundles/org.openhab.binding.siemenshvac/src/3rdparty/java/com/google/gson/typeadapters/RuntimeTypeAdapterFactory.java
  bundles/org.openhab.binding.siemenshvac/src/main/feature/feature.xml
  bundles/org.openhab.binding.siemenshvac/src/main/java/org/openhab/binding/siemenshvac/internal/constants/SiemensHvacBindingConstants.java
  bundles/org.openhab.binding.siemenshvac/src/main/java/org/openhab/binding/siemenshvac/internal/converter/ConverterException.java
  bundles/org.openhab.binding.siemenshvac/src/main/java/org/openhab/binding/siemenshvac/internal/converter/ConverterFactory.java
  bundles/org.openhab.binding.siemenshvac/src/main/java/org/openhab/binding/siemenshvac/internal/converter/ConverterTypeException.java
  bundles/org.openhab.binding.siemenshvac/src/main/java/org/openhab/binding/siemenshvac/internal/converter/TypeConverter.java
  bundles/org.openhab.binding.siemenshvac/src/main/java/org/openhab/binding/siemenshvac/internal/converter/type/AbstractTypeConverter.java
  bundles/org.openhab.binding.siemenshvac/src/main/java/org/openhab/binding/siemenshvac/internal/converter/type/CalendarTypeConverter.java
  bundles/org.openhab.binding.siemenshvac/src/main/java/org/openhab/binding/siemenshvac/internal/converter/type/CheckboxTypeConverter.java
  bundles/org.openhab.binding.siemenshvac/src/main/java/org/openhab/binding/siemenshvac/internal/converter/type/DateTimeTypeConverter.java
  bundles/org.openhab.binding.siemenshvac/src/main/java/org/openhab/binding/siemenshvac/internal/converter/type/EnumTypeConverter.java
  bundles/org.openhab.binding.siemenshvac/src/main/java/org/openhab/binding/siemenshvac/internal/converter/type/NumericTypeConverter.java
  bundles/org.openhab.binding.siemenshvac/src/main/java/org/openhab/binding/siemenshvac/internal/converter/type/RadioTypeConverter.java
  bundles/org.openhab.binding.siemenshvac/src/main/java/org/openhab/binding/siemenshvac/internal/converter/type/SchedulerTypeConverter.java
  bundles/org.openhab.binding.siemenshvac/src/main/java/org/openhab/binding/siemenshvac/internal/converter/type/StringTypeConverter.java
  bundles/org.openhab.binding.siemenshvac/src/main/java/org/openhab/binding/siemenshvac/internal/converter/type/TimeOfDayTypeConverter.java
  bundles/org.openhab.binding.siemenshvac/src/main/java/org/openhab/binding/siemenshvac/internal/discovery/SiemenesHvacDiscoveryParticipant.java
  bundles/org.openhab.binding.siemenshvac/src/main/java/org/openhab/binding/siemenshvac/internal/discovery/SiemensHvacDeviceDiscoveryService.java
  bundles/org.openhab.binding.siemenshvac/src/main/java/org/openhab/binding/siemenshvac/internal/factory/SiemensHvacHandlerFactory.java
  bundles/org.openhab.binding.siemenshvac/src/main/java/org/openhab/binding/siemenshvac/internal/handler/SiemensHvacBridgeConfig.java
  bundles/org.openhab.binding.siemenshvac/src/main/java/org/openhab/binding/siemenshvac/internal/handler/SiemensHvacBridgeThingHandler.java
  bundles/org.openhab.binding.siemenshvac/src/main/java/org/openhab/binding/siemenshvac/internal/handler/SiemensHvacHandlerImpl.java
  bundles/org.openhab.binding.siemenshvac/src/main/java/org/openhab/binding/siemenshvac/internal/metadata/SiemensHvacMetadata.java
  bundles/org.openhab.binding.siemenshvac/src/main/java/org/openhab/binding/siemenshvac/internal/metadata/SiemensHvacMetadataDataPoint.java
  bundles/org.openhab.binding.siemenshvac/src/main/java/org/openhab/binding/siemenshvac/internal/metadata/SiemensHvacMetadataDevice.java
  bundles/org.openhab.binding.siemenshvac/src/main/java/org/openhab/binding/siemenshvac/internal/metadata/SiemensHvacMetadataLanguage.java
  bundles/org.openhab.binding.siemenshvac/src/main/java/org/openhab/binding/siemenshvac/internal/metadata/SiemensHvacMetadataMenu.java
  bundles/org.openhab.binding.siemenshvac/src/main/java/org/openhab/binding/siemenshvac/internal/metadata/SiemensHvacMetadataPointChild.java
  bundles/org.openhab.binding.siemenshvac/src/main/java/org/openhab/binding/siemenshvac/internal/metadata/SiemensHvacMetadataRegistry.java
  bundles/org.openhab.binding.siemenshvac/src/main/java/org/openhab/binding/siemenshvac/internal/metadata/SiemensHvacMetadataRegistryImpl.java
  bundles/org.openhab.binding.siemenshvac/src/main/java/org/openhab/binding/siemenshvac/internal/metadata/SiemensHvacMetadataUser.java
  bundles/org.openhab.binding.siemenshvac/src/main/java/org/openhab/binding/siemenshvac/internal/network/SiemensHvacCallback.java
  bundles/org.openhab.binding.siemenshvac/src/main/java/org/openhab/binding/siemenshvac/internal/network/SiemensHvacConnector.java
  bundles/org.openhab.binding.siemenshvac/src/main/java/org/openhab/binding/siemenshvac/internal/network/SiemensHvacConnectorImpl.java
  bundles/org.openhab.binding.siemenshvac/src/main/java/org/openhab/binding/siemenshvac/internal/network/SiemensHvacRequestHandler.java
  bundles/org.openhab.binding.siemenshvac/src/main/java/org/openhab/binding/siemenshvac/internal/network/SiemensHvacRequestListener.java
  bundles/org.openhab.binding.siemenshvac/src/main/java/org/openhab/binding/siemenshvac/internal/type/SiemensHvacChannelGroupTypeProvider.java
  bundles/org.openhab.binding.siemenshvac/src/main/java/org/openhab/binding/siemenshvac/internal/type/SiemensHvacChannelGroupTypeProviderImpl.java
  bundles/org.openhab.binding.siemenshvac/src/main/java/org/openhab/binding/siemenshvac/internal/type/SiemensHvacChannelTypeProvider.java
  bundles/org.openhab.binding.siemenshvac/src/main/java/org/openhab/binding/siemenshvac/internal/type/SiemensHvacChannelTypeProviderImpl.java
  bundles/org.openhab.binding.siemenshvac/src/main/java/org/openhab/binding/siemenshvac/internal/type/SiemensHvacConfigDescriptionProvider.java
  bundles/org.openhab.binding.siemenshvac/src/main/java/org/openhab/binding/siemenshvac/internal/type/SiemensHvacConfigDescriptionProviderImpl.java
  bundles/org.openhab.binding.siemenshvac/src/main/java/org/openhab/binding/siemenshvac/internal/type/SiemensHvacException.java
  bundles/org.openhab.binding.siemenshvac/src/main/java/org/openhab/binding/siemenshvac/internal/type/SiemensHvacThingTypeProvider.java
  bundles/org.openhab.binding.siemenshvac/src/main/java/org/openhab/binding/siemenshvac/internal/type/SiemensHvacThingTypeProviderImpl.java
  bundles/org.openhab.binding.siemenshvac/src/main/java/org/openhab/binding/siemenshvac/internal/type/UidUtils.java
  bundles/org.openhab.binding.siemenshvac/src/main/resources/OH-INF/addon/addon.xml
  bundles/org.openhab.binding.siemenshvac/src/main/resources/OH-INF/i18n/siemenshvac.properties
  bundles/org.openhab.binding.siemenshvac/src/main/resources/OH-INF/thing/ozw.xml
  bundles/org.openhab.binding.siemenshvac/src/test/java/org/openhab/binding/siemenshvac/internal/type/UidUtilsTest.java
  bundles/pom.xml
Labels: new binding

#16960 [energidataservice] Add language tab for Rule DSL examples
  bundles/org.openhab.binding.energidataservice/README.md
Labels: documentation
