Repository openhab/openhab-addons, pull requests merged in 2024-07, with the labels that each got.

#16972 [sonyprojector] Fix decoding of mac address
  bundles/org.openhab.binding.sonyprojector/src/main/java/org/openhab/binding/sonyprojector/internal/communication/sdcp/SonyProjectorSdcpConnector.java
Labels: bug

#16976 [sonyprojector] Fix edge case in mac address decoding
  bundles/org.openhab.binding.sonyprojector/src/main/java/org/openhab/binding/sonyprojector/internal/communication/sdcp/SonyProjectorSdcpConnector.java
Labels: bug

#16973 [mail] Fix documentation bug
  bundles/org.openhab.binding.mail/README.md
Labels: documentation

#16977 [jpa] Fix return value for UoM items
  bundles/org.openhab.persistence.jpa/src/main/java/org/openhab/persistence/jpa/internal/JpaHistoricItem.java
Labels: bug

#16978 [mongodb] Fix handling of GroupItems on restore
  bundles/org.openhab.persistence.mongodb/src/main/java/org/openhab/persistence/mongodb/internal/MongoDBTypeConversions.java
Labels: bug

#16943 [homeconnect] Update README.md
  bundles/org.openhab.binding.homeconnect/README.md
Labels: documentation

#16986 [growatt] Annotate ThingActions implementation as a Component
  bundles/org.openhab.binding.growatt/src/main/java/org/openhab/binding/growatt/internal/action/GrowattActions.java
Labels: bug

#16987 Upgrade maven-deploy-plugin to 3.1.2
  pom.xml
Labels: infrastructure

#16999 [jsscripting] Fix notification builder examples
  bundles/org.openhab.automation.jsscripting/README.md
Labels: documentation

#16998 [openhabcloud] Change severity to tag in README
  bundles/org.openhab.io.openhabcloud/README.md
Labels: documentation

#16997 [openhabcloud] Update JRuby examples and minor changes to JS examples
  bundles/org.openhab.io.openhabcloud/README.md
Labels: documentation

#16947 [growatt] Improved and extended documentation examples
  bundles/org.openhab.binding.growatt/README.md
Labels: documentation

#16994 [meater] Fix broken cloud communication
  bundles/org.openhab.binding.meater/src/main/java/org/openhab/binding/meater/internal/api/MeaterRestAPI.java
  bundles/org.openhab.binding.meater/src/main/java/org/openhab/binding/meater/internal/handler/MeaterBridgeHandler.java
Labels: bug

#16981 [energidataservice] Enrich examples with JavaScript versions
  bundles/org.openhab.binding.energidataservice/README.md
Labels: documentation

#16944 [homeconnect] Update README.md
  bundles/org.openhab.binding.homeconnect/README.md
Labels: documentation

#17002 [energidataservice] Add missing JRuby examples
  bundles/org.openhab.binding.energidataservice/README.md
Labels: documentation

#17003 [energidataservice] Increase consistency between examples
  bundles/org.openhab.binding.energidataservice/README.md
Labels: documentation

#17005 [energidataservice] Fix JRuby tabs
  bundles/org.openhab.binding.energidataservice/README.md
Labels: documentation, regression

#17009 [shelly] Fixes Gen1 initialization when thing is defined in .things
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/handler/ShellyBaseHandler.java
Labels: bug

#17004 [jrubyscripting] Upgrade to JRuby 9.4.8.0
  bundles/org.openhab.automation.jrubyscripting/pom.xml
Labels: enhancement

#16945 [homeconnect] Update README.md
  bundles/org.openhab.binding.homeconnect/README.md
Labels: documentation

#16989 Fix logging statements
  bundles/org.openhab.binding.digiplex/src/main/java/org/openhab/binding/digiplex/internal/handler/DigiplexBridgeHandler.java
  bundles/org.openhab.binding.pentair/src/main/java/org/openhab/binding/pentair/internal/handler/PentairIntelliFloHandler.java
  bundles/org.openhab.binding.sonyaudio/src/main/java/org/openhab/binding/sonyaudio/internal/protocol/SonyAudioClientSocket.java
  bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/api/protocol/aes/SecurePasstroughCipher.java
Labels: bug

#17024 [homematic] Update README.md
  bundles/org.openhab.binding.homematic/README.md
Labels: documentation

#17025 [argoclima] Editorial fixes in README.md
  bundles/org.openhab.binding.argoclima/README.md
Labels: documentation

#17011 [shelly] Revise fix for Gen1 initialization problem for manually created Things
  bundles/org.openhab.binding.shelly/README.md
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api/ShellyDeviceProfile.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api2/Shelly2ApiRpc.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/handler/ShellyBaseHandler.java
Labels: bug

#17032 [awattar] Fix price handler refresh
  bundles/org.openhab.binding.awattar/src/main/java/org/openhab/binding/awattar/internal/handler/AwattarPriceHandler.java
Labels: bug

#17031 [homekit] Implement all AccessoryInformationService characteristics
  bundles/org.openhab.io.homekit/README.md
  bundles/org.openhab.io.homekit/pom.xml
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitChangeListener.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitCharacteristicType.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/AbstractHomekitAccessoryImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitAccessoryFactory.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitAirQualitySensorImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitBasicFanImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitBatteryImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitCarbonDioxideSensorImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitCarbonMonoxideSensorImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitCharacteristicFactory.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitContactSensorImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitDoorImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitFanImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitFaucetImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitFilterMaintenanceImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitGarageDoorOpenerImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitHeaterCoolerImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitHumiditySensorImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitInputSourceImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitIrrigationSystemImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitLeakSensorImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitLightSensorImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitLightbulbImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitLockImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitMetadataCharacteristicFactory.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitMicrophoneImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitMotionSensorImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitOccupancySensorImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitOutletImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitSecuritySystemImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitSlatImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitSmartSpeakerImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitSmokeSensorImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitSpeakerImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitSwitchImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitTelevisionImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitTemperatureSensorImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitThermostatImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitValveImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitWindowCoveringImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitWindowImpl.java
Labels: enhancement

#16970 [jsscripting] Implement `javax.script.Compilable`
  bundles/org.openhab.automation.jsscripting/pom.xml
  bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/DebuggingGraalScriptEngine.java
  bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/OpenhabGraalJSScriptEngine.java
  bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/scriptengine/DelegatingScriptEngineWithInvocableAndCompilableAndAutocloseable.java
  bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/scriptengine/InvocationInterceptingScriptEngineWithInvocableAndCompilableAndAutoCloseable.java
  bundles/org.openhab.automation.jsscripting/suppressions.properties
Labels: enhancement

#17015 [shelly] Fix thing type descriptions for Plus Mini series
  bundles/org.openhab.binding.shelly/README.md
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/ShellyBindingConstants.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/discovery/ShellyThingCreator.java
  bundles/org.openhab.binding.shelly/src/main/resources/OH-INF/i18n/shelly.properties
Labels: bug

#17022 [jsscripting] Add info about npm requiring path
  bundles/org.openhab.automation.jsscripting/README.md
Labels: documentation

#17023 [openhabcloud] Update Notification Docs
  bundles/org.openhab.io.openhabcloud/README.md
  bundles/org.openhab.io.openhabcloud/doc/notifications.png
Labels: documentation

#16877 [aWattar] Add inverted best price
  bundles/org.openhab.binding.awattar/README.md
  bundles/org.openhab.binding.awattar/src/main/java/org/openhab/binding/awattar/internal/AwattarBestPriceConfiguration.java
  bundles/org.openhab.binding.awattar/src/main/java/org/openhab/binding/awattar/internal/handler/AwattarBestPriceHandler.java
  bundles/org.openhab.binding.awattar/src/main/java/org/openhab/binding/awattar/internal/handler/AwattarHandlerFactory.java
  bundles/org.openhab.binding.awattar/src/main/resources/OH-INF/config/config.xml
  bundles/org.openhab.binding.awattar/src/main/resources/OH-INF/i18n/awattar.properties
  bundles/org.openhab.binding.awattar/src/main/resources/OH-INF/i18n/awattar_de.properties
  bundles/org.openhab.binding.awattar/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.awattar/src/test/java/org/openhab/binding/awattar/internal/handler/AwattarBridgeHandlerTest.java
Labels: enhancement

#17042 [http] Properly escape + character in query string
  bundles/org.openhab.binding.http/src/main/java/org/openhab/binding/http/internal/HttpThingHandler.java
  bundles/org.openhab.binding.http/src/main/java/org/openhab/binding/http/internal/Util.java
  bundles/org.openhab.binding.http/src/main/java/org/openhab/binding/http/internal/http/RefreshingUrlCache.java
  bundles/org.openhab.binding.http/src/test/java/org/openhab/binding/http/UtilTest.java
Labels: bug

#17044 [nuvo] Fix display of album art for streaming media
  bundles/org.openhab.binding.nuvo/src/main/java/org/openhab/binding/nuvo/internal/communication/NuvoDefaultConnector.java
  bundles/org.openhab.binding.nuvo/src/main/java/org/openhab/binding/nuvo/internal/communication/NuvoIpConnector.java
  bundles/org.openhab.binding.nuvo/src/main/java/org/openhab/binding/nuvo/internal/handler/NuvoHandler.java
Labels: bug

#17001 [mercedesme] take end of charge weekday into account
  bundles/org.openhab.binding.mercedesme/src/main/java/org/openhab/binding/mercedesme/internal/Constants.java
  bundles/org.openhab.binding.mercedesme/src/main/java/org/openhab/binding/mercedesme/internal/handler/VehicleHandler.java
  bundles/org.openhab.binding.mercedesme/src/main/java/org/openhab/binding/mercedesme/internal/server/MBWebsocket.java
  bundles/org.openhab.binding.mercedesme/src/main/resources/OH-INF/thing/charge-channel-types.xml
  bundles/org.openhab.binding.mercedesme/src/test/java/org/openhab/binding/mercedesme/internal/handler/VehicleHandlerTest.java
  bundles/org.openhab.binding.mercedesme/src/test/resources/proto-json/MB-BEV-EQA-Charging-Weekday-Underrun.json
  bundles/org.openhab.binding.mercedesme/src/test/resources/proto-json/MB-BEV-EQA-Charging-Weekday.json
Labels: bug

#17047 [mongodb] Disable failing MongoDBPersistenceServiceTest
  bundles/org.openhab.persistence.mongodb/src/test/java/org/openhab/persistence/mongodb/internal/MongoDBPersistenceServiceTest.java
Labels: test

#16975 [enocean] Fix temperature values for D2_50 eep
  bundles/org.openhab.binding.enocean/src/main/java/org/openhab/binding/enocean/internal/eep/D2_50/D2_50.java
Labels: bug

#17049 [mongodb] Fixes #17046 CI Build fails on new systems - complaining CPU does not support AVX
  bundles/org.openhab.persistence.mongodb/src/test/java/org/openhab/persistence/mongodb/internal/DataCreationHelper.java
  bundles/org.openhab.persistence.mongodb/src/test/java/org/openhab/persistence/mongodb/internal/MongoDBPersistenceServiceTest.java
Labels: test

#17054 [rrd4j] Fix unit retrieval for group items
  bundles/org.openhab.persistence.rrd4j/src/main/java/org/openhab/persistence/rrd4j/internal/RRD4jPersistenceService.java
Labels: bug

#17038 [homekit] fix optional characteristics
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/AbstractHomekitAccessoryImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitAirQualitySensorImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitBasicFanImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitBatteryImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitCarbonDioxideSensorImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitCarbonMonoxideSensorImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitContactSensorImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitDoorImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitFanImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitFaucetImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitFilterMaintenanceImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitGarageDoorOpenerImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitHeaterCoolerImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitHumiditySensorImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitInputSourceImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitIrrigationSystemImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitLeakSensorImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitLightSensorImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitLightbulbImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitLockImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitMicrophoneImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitMotionSensorImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitOccupancySensorImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitOutletImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitSecuritySystemImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitSlatImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitSmartSpeakerImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitSmokeSensorImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitSpeakerImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitSwitchImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitTelevisionImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitTelevisionSpeakerImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitTemperatureSensorImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitThermostatImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitValveImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitWindowCoveringImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitWindowImpl.java
Labels: bug, regression

#17056 [homekit] Allow configuring thermostat modes via metadata
  bundles/org.openhab.io.homekit/README.md
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitCharacteristicType.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/AbstractHomekitAccessoryImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/AbstractHomekitPositionAccessoryImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitAccessoryFactory.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitAccessoryGroupImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitAirQualitySensorImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitBasicFanImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitBatteryImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitCarbonDioxideSensorImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitCarbonMonoxideSensorImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitCharacteristicFactory.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitContactSensorImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitDoorImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitFanImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitFaucetImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitFilterMaintenanceImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitGarageDoorOpenerImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitHeaterCoolerImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitHumiditySensorImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitInputSourceImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitIrrigationSystemImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitLeakSensorImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitLightSensorImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitLightbulbImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitLockImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitMetadataCharacteristicFactory.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitMicrophoneImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitMotionSensorImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitOccupancySensorImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitOutletImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitSecuritySystemImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitSlatImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitSmartSpeakerImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitSmokeSensorImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitSpeakerImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitSwitchImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitTelevisionImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitTelevisionSpeakerImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitTemperatureSensorImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitThermostatImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitValveImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitWindowCoveringImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitWindowImpl.java
Labels: enhancement

#17061 Fix i18n entry matching the add-on name for voice add-ons
  bundles/org.openhab.voice.googlestt/src/main/resources/OH-INF/i18n/googlestt.properties
  bundles/org.openhab.voice.googletts/src/main/resources/OH-INF/i18n/googletts.properties
  bundles/org.openhab.voice.mactts/src/main/resources/OH-INF/i18n/mactts.properties
  bundles/org.openhab.voice.marytts/src/main/resources/OH-INF/i18n/marytts.properties
  bundles/org.openhab.voice.mimictts/src/main/resources/OH-INF/i18n/mimictts.properties
  bundles/org.openhab.voice.picotts/src/main/resources/OH-INF/i18n/picotts.properties
  bundles/org.openhab.voice.pollytts/src/main/resources/OH-INF/i18n/pollytts.properties
  bundles/org.openhab.voice.voicerss/src/main/resources/OH-INF/i18n/voicerss.properties
  bundles/org.openhab.voice.voskstt/src/main/resources/OH-INF/i18n/voskstt.properties
  bundles/org.openhab.voice.watsonstt/src/main/resources/OH-INF/i18n/watsonstt.properties
Labels: i18n

#17057 [denonmarantz] Fix blocking initialization
  bundles/org.openhab.binding.denonmarantz/src/main/java/org/openhab/binding/denonmarantz/internal/handler/DenonMarantzHandler.java
Labels: bug

#17062 Fix i18n entry matching the add-on name for io add-ons
  bundles/org.openhab.io.homekit/src/main/resources/OH-INF/i18n/homekit.properties
  bundles/org.openhab.io.hueemulation/src/main/resources/OH-INF/i18n/hueemulation.properties
  bundles/org.openhab.io.metrics/src/main/resources/OH-INF/i18n/metrics.properties
  bundles/org.openhab.io.neeo/src/main/resources/OH-INF/i18n/neeo.properties
  bundles/org.openhab.io.openhabcloud/src/main/resources/OH-INF/i18n/openhabcloud.properties
Labels: i18n

#17059 [homekit] Fix temperature unit conversion for min/max/step
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitCharacteristicFactory.java
Labels: bug

#17082 [freeboxos] Fix macAddress property when discovering a server
  bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/discovery/FreeboxOsDiscoveryService.java
Labels: bug

#17081 [freeboxos] Fix creation of properties and dynamic channels at init
  bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/handler/ApiConsumerHandler.java
Labels: bug

#17030 [sensibo] Fix channel provider throwing exception
  bundles/org.openhab.binding.sensibo/src/main/java/org/openhab/binding/sensibo/internal/CallbackChannelsTypeProvider.java
  bundles/org.openhab.binding.sensibo/src/main/java/org/openhab/binding/sensibo/internal/handler/SensiboSkyHandler.java
  bundles/org.openhab.binding.sensibo/src/main/java/org/openhab/binding/sensibo/internal/model/SensiboModel.java
  bundles/org.openhab.binding.sensibo/src/test/java/org/openhab/binding/sensibo/internal/SensiboModelTest.java
  bundles/org.openhab.binding.sensibo/src/test/java/org/openhab/binding/sensibo/internal/handler/SensiboSkyHandlerTest.java
  bundles/org.openhab.binding.sensibo/src/test/resources/get_pod_details_response_valter.json
Labels: bug

#17048 [govee] Fix invalid status response handling
  bundles/org.openhab.binding.govee/src/main/java/org/openhab/binding/govee/internal/CommunicationManager.java
  bundles/org.openhab.binding.govee/src/main/java/org/openhab/binding/govee/internal/GoveeHandler.java
  bundles/org.openhab.binding.govee/src/test/java/org/openhab/binding/govee/internal/GoveeHandlerMock.java
  bundles/org.openhab.binding.govee/src/test/java/org/openhab/binding/govee/internal/GoveeSerializeGoveeHandlerTest.java
Labels: bug

#17053 [shelly][hotfix] Fix initialization of BLU Motion device
  bundles/org.openhab.binding.shelly/README.md
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api/ShellyDeviceProfile.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/handler/ShellyBaseHandler.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/provider/ShellyChannelDefinitions.java
Labels: bug, community approved

#16956 [teslascope] Initial contribution
  CODEOWNERS
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.teslascope/NOTICE
  bundles/org.openhab.binding.teslascope/README.md
  bundles/org.openhab.binding.teslascope/pom.xml
  bundles/org.openhab.binding.teslascope/src/main/feature/feature.xml
  bundles/org.openhab.binding.teslascope/src/main/java/org/openhab/binding/teslascope/internal/TeslascopeAuthenticationException.java
  bundles/org.openhab.binding.teslascope/src/main/java/org/openhab/binding/teslascope/internal/TeslascopeBindingConstants.java
  bundles/org.openhab.binding.teslascope/src/main/java/org/openhab/binding/teslascope/internal/TeslascopeCommunicationException.java
  bundles/org.openhab.binding.teslascope/src/main/java/org/openhab/binding/teslascope/internal/TeslascopeConfiguration.java
  bundles/org.openhab.binding.teslascope/src/main/java/org/openhab/binding/teslascope/internal/TeslascopeHandler.java
  bundles/org.openhab.binding.teslascope/src/main/java/org/openhab/binding/teslascope/internal/TeslascopeHandlerFactory.java
  bundles/org.openhab.binding.teslascope/src/main/java/org/openhab/binding/teslascope/internal/TeslascopeWebTargets.java
  bundles/org.openhab.binding.teslascope/src/main/java/org/openhab/binding/teslascope/internal/api/ChargeState.java
  bundles/org.openhab.binding.teslascope/src/main/java/org/openhab/binding/teslascope/internal/api/ClimateState.java
  bundles/org.openhab.binding.teslascope/src/main/java/org/openhab/binding/teslascope/internal/api/DetailedInformation.java
  bundles/org.openhab.binding.teslascope/src/main/java/org/openhab/binding/teslascope/internal/api/DriveState.java
  bundles/org.openhab.binding.teslascope/src/main/java/org/openhab/binding/teslascope/internal/api/VehicleState.java
  bundles/org.openhab.binding.teslascope/src/main/resources/OH-INF/addon/addon.xml
  bundles/org.openhab.binding.teslascope/src/main/resources/OH-INF/i18n/teslascope.properties
  bundles/org.openhab.binding.teslascope/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/pom.xml
Labels: new binding

#17108 [deconz] Fix tests. Fix #17104
  bundles/org.openhab.binding.deconz/src/test/java/org/openhab/binding/deconz/DeconzTest.java
Labels: bug, test, regression

#17063 [jrubyscripting] Generate proper i18n file
  bundles/org.openhab.automation.jrubyscripting/src/main/resources/OH-INF/i18n/jruby.properties
  bundles/org.openhab.automation.jrubyscripting/src/main/resources/OH-INF/i18n/jruby_de.properties
  bundles/org.openhab.automation.jrubyscripting/src/main/resources/OH-INF/i18n/jruby_hu.properties
  bundles/org.openhab.automation.jrubyscripting/src/main/resources/OH-INF/i18n/jruby_it.properties
  bundles/org.openhab.automation.jrubyscripting/src/main/resources/OH-INF/i18n/jrubyscripting.properties
Labels: work in progress, i18n

#17067 [aWATTar] Fix countdown and remaining channels
  bundles/org.openhab.binding.awattar/src/main/java/org/openhab/binding/awattar/internal/handler/AwattarBestPriceHandler.java
Labels: bug

#17084 [homekit] Use characteristic factory for TemperatureSensor
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitTemperatureSensorImpl.java
Labels: enhancement

#17091 [sensibo] Fix potential API throttling at binding start
  bundles/org.openhab.binding.sensibo/src/main/java/org/openhab/binding/sensibo/internal/dto/pods/GetPodsRequest.java
  bundles/org.openhab.binding.sensibo/src/main/java/org/openhab/binding/sensibo/internal/handler/SensiboAccountHandler.java
  bundles/org.openhab.binding.sensibo/src/test/java/org/openhab/binding/sensibo/internal/handler/SensiboAccountHandlerTest.java
  bundles/org.openhab.binding.sensibo/src/test/resources/get_pods_response.json
Labels: bug

#17106 [tesla] Update README.md correct channel name
  bundles/org.openhab.binding.tesla/README.md
Labels: documentation

#17107 [bluetooth.bluez] Handle UnsatisfiedLinkError on Windows (and macOS)
  bundles/org.openhab.binding.bluetooth.bluez/src/main/java/org/openhab/binding/bluetooth/bluez/internal/DeviceManagerFactory.java
Labels: bug

#17115 [bluetooth.bluez] Sync bluez-dbus-osgi to version 0.1.4
  bundles/org.openhab.binding.bluetooth.bluez/NOTICE
  bundles/org.openhab.binding.bluetooth.bluez/src/main/feature/feature.xml
  features/openhab-addons/src/main/resources/footer.xml
Labels: infrastructure

#17117 [bluetooth.grundfosalpha] Add to footer.xml
  features/openhab-addons/src/main/resources/footer.xml
Labels: bug, infrastructure

#17068 [aWATTar] Schedule API update more then once per day
  bundles/org.openhab.binding.awattar/README.md
  bundles/org.openhab.binding.awattar/src/main/java/org/openhab/binding/awattar/internal/handler/AwattarBridgeHandler.java
Labels: enhancement

#17060 [homekit] Synthesize Thermostat.TargetTemperature in some cases
  bundles/org.openhab.io.homekit/README.md
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitAccessoryFactory.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitThermostatImpl.java
Labels: bug

#17128 [homekit] use java, not xtend, for code fences in README
  bundles/org.openhab.io.homekit/README.md
Labels: documentation

#17026 [boschshc] Support for Smart Relay
  bundles/org.openhab.binding.boschshc/README.md
  bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/console/BoschShcCommandExtension.java
  bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/devices/BoschSHCBindingConstants.java
  bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/devices/BoschSHCHandler.java
  bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/devices/BoschSHCHandlerFactory.java
  bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/devices/bridge/BridgeHandler.java
  bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/devices/relay/RelayHandler.java
  bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/discovery/ThingDiscoveryService.java
  bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/services/AbstractStatelessBoschSHCDeviceService.java
  bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/services/impulseswitch/ImpulseSwitchService.java
  bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/services/impulseswitch/dto/ImpulseSwitchServiceState.java
  bundles/org.openhab.binding.boschshc/src/main/resources/OH-INF/i18n/boschshc.properties
  bundles/org.openhab.binding.boschshc/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/devices/AbstractBoschSHCDeviceHandlerTest.java
  bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/devices/AbstractBoschSHCHandlerTest.java
  bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/devices/AbstractPowerSwitchHandlerTest.java
  bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/devices/relay/RelayHandlerTest.java
Labels: enhancement, additional testing preferred, work in progress

#17055 [solax] Support for Solax EV charger via direct(local) data retrieval
  bundles/org.openhab.binding.solax/README.md
  bundles/org.openhab.binding.solax/src/main/java/org/openhab/binding/solax/internal/SolaxBindingConstants.java
  bundles/org.openhab.binding.solax/src/main/java/org/openhab/binding/solax/internal/SolaxHandlerFactory.java
  bundles/org.openhab.binding.solax/src/main/java/org/openhab/binding/solax/internal/connectivity/rawdata/local/LocalConnectRawDataBean.java
  bundles/org.openhab.binding.solax/src/main/java/org/openhab/binding/solax/internal/handlers/AbstractSolaxHandler.java
  bundles/org.openhab.binding.solax/src/main/java/org/openhab/binding/solax/internal/handlers/SolaxLocalAccessAbstractHandler.java
  bundles/org.openhab.binding.solax/src/main/java/org/openhab/binding/solax/internal/handlers/SolaxLocalAccessChargerHandler.java
  bundles/org.openhab.binding.solax/src/main/java/org/openhab/binding/solax/internal/handlers/SolaxLocalAccessInverterHandler.java
  bundles/org.openhab.binding.solax/src/main/java/org/openhab/binding/solax/internal/model/InverterType.java
  bundles/org.openhab.binding.solax/src/main/java/org/openhab/binding/solax/internal/model/local/CommonLocalDeviceData.java
  bundles/org.openhab.binding.solax/src/main/java/org/openhab/binding/solax/internal/model/local/EvChargerData.java
  bundles/org.openhab.binding.solax/src/main/java/org/openhab/binding/solax/internal/model/local/LocalData.java
  bundles/org.openhab.binding.solax/src/main/java/org/openhab/binding/solax/internal/model/local/RawDataParser.java
  bundles/org.openhab.binding.solax/src/main/java/org/openhab/binding/solax/internal/model/local/X1BoostAirMiniData.java
  bundles/org.openhab.binding.solax/src/main/java/org/openhab/binding/solax/internal/model/local/X1HybridG4Data.java
  bundles/org.openhab.binding.solax/src/main/java/org/openhab/binding/solax/internal/model/local/X3HybridG4Data.java
  bundles/org.openhab.binding.solax/src/main/java/org/openhab/binding/solax/internal/model/local/X3MicOrProG2Data.java
  bundles/org.openhab.binding.solax/src/main/java/org/openhab/binding/solax/internal/model/local/evchargers/EvChargerDataParser.java
  bundles/org.openhab.binding.solax/src/main/java/org/openhab/binding/solax/internal/model/local/inverters/X1BoostAirMiniDataParser.java
  bundles/org.openhab.binding.solax/src/main/java/org/openhab/binding/solax/internal/model/local/inverters/X1HybridG4DataParser.java
  bundles/org.openhab.binding.solax/src/main/java/org/openhab/binding/solax/internal/model/local/inverters/X3HybridG4DataParser.java
  bundles/org.openhab.binding.solax/src/main/java/org/openhab/binding/solax/internal/model/local/inverters/X3MicOrProG2DataParser.java
  bundles/org.openhab.binding.solax/src/main/java/org/openhab/binding/solax/internal/util/ByteUtil.java
  bundles/org.openhab.binding.solax/src/main/resources/OH-INF/i18n/solax.properties
  bundles/org.openhab.binding.solax/src/main/resources/OH-INF/thing/channel_types.xml
  bundles/org.openhab.binding.solax/src/main/resources/OH-INF/thing/localConnectEVCharger.xml
  bundles/org.openhab.binding.solax/src/test/java/org/openhab/binding/solax/internal/local/AbstractParserTest.java
  bundles/org.openhab.binding.solax/src/test/java/org/openhab/binding/solax/internal/local/parsers/TestEVChargerParser.java
  bundles/org.openhab.binding.solax/src/test/java/org/openhab/binding/solax/internal/local/parsers/TestX1BoostAirMiniDataParser.java
  bundles/org.openhab.binding.solax/src/test/java/org/openhab/binding/solax/internal/local/parsers/TestX1HybridG4Parser.java
  bundles/org.openhab.binding.solax/src/test/java/org/openhab/binding/solax/internal/local/parsers/TestX3HybridG4Parser.java
  bundles/org.openhab.binding.solax/src/test/java/org/openhab/binding/solax/internal/local/parsers/TestX3MicOrProG2Parser.java
  bundles/org.openhab.binding.solax/src/test/java/org/openhab/binding/solax/internal/util/TestByteUtil.java
Labels: enhancement

#17136 [homekit] Fix thermostats with auto mode and only target temperature
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitThermostatImpl.java
Labels: bug, regression

#17134 [homekit] Automatically assume valid enum values when linking to Switch/Contact
  bundles/org.openhab.io.homekit/README.md
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitChangeListener.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitCharacteristicFactory.java
Labels: enhancement

#17110 [http] Improve escaping of URLs
  bundles/org.openhab.binding.http/README.md
  bundles/org.openhab.binding.http/src/main/java/org/openhab/binding/http/internal/Util.java
  bundles/org.openhab.binding.http/src/test/java/org/openhab/binding/http/UtilTest.java
Labels: enhancement

#17138 [homekit] Support UP/DOWN for WindowCoverings
  bundles/org.openhab.io.homekit/README.md
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/HomekitTaggedItem.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/AbstractHomekitPositionAccessoryImpl.java
Labels: enhancement

#17142 [homekit] Don't pre-fill enums from switches if metadata has enum values
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitCharacteristicFactory.java
Labels: enhancement

#17124 [freeboxos] Fix websocket registration
  bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/api/rest/WebSocketManager.java
Labels: bug

#17072 [sensibo] Add test for Accept-Encoding header
  bundles/org.openhab.binding.sensibo/src/test/java/org/openhab/binding/sensibo/internal/handler/SensiboAccountHandlerTest.java
Labels: test

#17095 [freeboxos] Avoid partial discovery
  bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/discovery/FreeboxOsDiscoveryService.java
Labels: bug

#17141 [homekit] Support lock optional characteristics on GarageDoorOpener
  bundles/org.openhab.io.homekit/README.md
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitCharacteristicFactory.java
Labels: enhancement

#17148 [jsscripting] ThreadsafeTimers: Add overrides for double for setTimeout/setInterval
  bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/threading/ThreadsafeTimers.java
Labels: enhancement

#17151 [homekit] Fix duplicate name characteristic errors
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/AbstractHomekitAccessoryImpl.java
Labels: bug

#17145 [aWATTar] fix handle wrong null check
  bundles/org.openhab.binding.awattar/src/main/java/org/openhab/binding/awattar/internal/handler/AwattarBridgeHandler.java
  bundles/org.openhab.binding.awattar/src/test/java/org/openhab/binding/awattar/internal/handler/AwattarBridgeHandlerRefreshTest.java
Labels: bug, regression

#17087 [daikin] Add demand control support for ac_unit
  bundles/org.openhab.binding.daikin/README.md
  bundles/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/DaikinBindingConstants.java
  bundles/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/DaikinWebTargets.java
  bundles/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/api/DemandControl.java
  bundles/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/api/Enums.java
  bundles/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/handler/DaikinAcUnitHandler.java
  bundles/org.openhab.binding.daikin/src/main/resources/OH-INF/i18n/daikin.properties
  bundles/org.openhab.binding.daikin/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.daikin/src/main/resources/OH-INF/update/update.xml
  bundles/org.openhab.binding.daikin/src/test/java/org/openhab/binding/daikin/internal/api/ControlInfoTest.java
  bundles/org.openhab.binding.daikin/src/test/java/org/openhab/binding/daikin/internal/api/DemandControlTest.java
Labels: enhancement

#17097 [freeboxos] Fix systeminfo group for active-player thing type
  bundles/org.openhab.binding.freeboxos/src/main/resources/OH-INF/i18n/freeboxos.properties
  bundles/org.openhab.binding.freeboxos/src/main/resources/OH-INF/thing/player-channel-groups.xml
  bundles/org.openhab.binding.freeboxos/src/main/resources/OH-INF/thing/player-thing-type.xml
  bundles/org.openhab.binding.freeboxos/src/main/resources/OH-INF/update/instructions.xml
Labels: bug

#17123 [bluetooth.bluez] Bump bluez-dbus-osgi to version 0.2.0
  bundles/org.openhab.binding.bluetooth.bluez/NOTICE
  bundles/org.openhab.binding.bluetooth.bluez/src/main/feature/feature.xml
  features/openhab-addons/src/main/resources/footer.xml
Labels: enhancement

#17175 [ism8] Fix broken image in docs
  bundles/org.openhab.binding.ism8/README.md
Labels: documentation

#17178 [freeboxos] Fix handling of REFRESH command for connectivity channels
  bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/handler/ApiConsumerHandler.java
  bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/handler/HostHandler.java
  bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/handler/VmHandler.java
Labels: bug

#17171 [jsscripting] Fix console logger name & timer identifier missing for UI scripts
  bundles/org.openhab.automation.jsscripting/src/main/resources/node_modules/@jsscripting-globals.js
Labels: bug, regression

#17161 [freeboxos] Fix triggering of event firmware_updated
  bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/handler/FreeDeviceIntf.java
Labels: bug

#17180 [shelly] Fix `NullPointerExceptions`
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api/ShellyDeviceProfile.java
Labels: bug

#17159 [dbquery] Fix dependency issues and bump to newer version libs
  bundles/org.openhab.binding.dbquery/pom.xml
  bundles/org.openhab.binding.dbquery/src/main/resources/OH-INF/thing/influx2-bridge.xml
  bundles/org.openhab.binding.dbquery/src/test/java/org/openhab/binding/dbquery/internal/Value2StateConverterTest.java
  bundles/org.openhab.binding.dbquery/src/test/java/org/openhab/binding/dbquery/internal/domain/QueryResultJSONEncoderTest.java
Labels: bug

#17167 [shelly] Fix BLU Discovery when Shelly Cloud Bluetooth Gateway is enabled
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api/ShellyApiInterface.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api1/Shelly1HttpApi.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api2/Shelly2ApiJsonDTO.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api2/Shelly2ApiRpc.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api2/ShellyBluApi.java
Labels: bug

#17181 [homekit] Fix invertedness of GarageDoorOpener characteristics
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitCharacteristicFactory.java
Labels: bug, regression

#17158 [mqtt.generic] Add optional stopCommandTopic for rollershutters
  bundles/org.openhab.binding.mqtt.generic/README.md
  bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/ChannelConfig.java
  bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/ChannelConfigBuilder.java
  bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/ChannelState.java
  bundles/org.openhab.binding.mqtt.generic/src/main/resources/OH-INF/config/rollershutter-channel-config.xml
  bundles/org.openhab.binding.mqtt.generic/src/main/resources/OH-INF/i18n/mqtt.properties
  bundles/org.openhab.binding.mqtt.generic/src/test/java/org/openhab/binding/mqtt/generic/ChannelStateTests.java
Labels: enhancement

#16835 [solarman] Initial contribution
  CODEOWNERS
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.solarman/NOTICE
  bundles/org.openhab.binding.solarman/README.md
  bundles/org.openhab.binding.solarman/pom.xml
  bundles/org.openhab.binding.solarman/src/main/feature/feature.xml
  bundles/org.openhab.binding.solarman/src/main/java/org/openhab/binding/solarman/internal/DefinitionParser.java
  bundles/org.openhab.binding.solarman/src/main/java/org/openhab/binding/solarman/internal/SolarmanBindingConstants.java
  bundles/org.openhab.binding.solarman/src/main/java/org/openhab/binding/solarman/internal/SolarmanHandlerFactory.java
  bundles/org.openhab.binding.solarman/src/main/java/org/openhab/binding/solarman/internal/SolarmanLoggerConfiguration.java
  bundles/org.openhab.binding.solarman/src/main/java/org/openhab/binding/solarman/internal/SolarmanLoggerHandler.java
  bundles/org.openhab.binding.solarman/src/main/java/org/openhab/binding/solarman/internal/channel/BaseChannelConfig.java
  bundles/org.openhab.binding.solarman/src/main/java/org/openhab/binding/solarman/internal/channel/SolarmanChannelManager.java
  bundles/org.openhab.binding.solarman/src/main/java/org/openhab/binding/solarman/internal/defmodel/InverterDefinition.java
  bundles/org.openhab.binding.solarman/src/main/java/org/openhab/binding/solarman/internal/defmodel/Parameter.java
  bundles/org.openhab.binding.solarman/src/main/java/org/openhab/binding/solarman/internal/defmodel/ParameterItem.java
  bundles/org.openhab.binding.solarman/src/main/java/org/openhab/binding/solarman/internal/defmodel/Request.java
  bundles/org.openhab.binding.solarman/src/main/java/org/openhab/binding/solarman/internal/defmodel/Validation.java
  bundles/org.openhab.binding.solarman/src/main/java/org/openhab/binding/solarman/internal/modbus/CRC16Modbus.java
  bundles/org.openhab.binding.solarman/src/main/java/org/openhab/binding/solarman/internal/modbus/SolarmanLoggerConnection.java
  bundles/org.openhab.binding.solarman/src/main/java/org/openhab/binding/solarman/internal/modbus/SolarmanLoggerConnector.java
  bundles/org.openhab.binding.solarman/src/main/java/org/openhab/binding/solarman/internal/modbus/SolarmanV5Protocol.java
  bundles/org.openhab.binding.solarman/src/main/java/org/openhab/binding/solarman/internal/modbus/exception/SolarmanAuthenticationException.java
  bundles/org.openhab.binding.solarman/src/main/java/org/openhab/binding/solarman/internal/modbus/exception/SolarmanConnectionException.java
  bundles/org.openhab.binding.solarman/src/main/java/org/openhab/binding/solarman/internal/modbus/exception/SolarmanException.java
  bundles/org.openhab.binding.solarman/src/main/java/org/openhab/binding/solarman/internal/modbus/exception/SolarmanProtocolException.java
  bundles/org.openhab.binding.solarman/src/main/java/org/openhab/binding/solarman/internal/typeprovider/ChannelUtils.java
  bundles/org.openhab.binding.solarman/src/main/java/org/openhab/binding/solarman/internal/typeprovider/SolarmanChannelTypeProvider.java
  bundles/org.openhab.binding.solarman/src/main/java/org/openhab/binding/solarman/internal/updater/SolarmanChannelUpdater.java
  bundles/org.openhab.binding.solarman/src/main/java/org/openhab/binding/solarman/internal/updater/SolarmanProcessResult.java
  bundles/org.openhab.binding.solarman/src/main/java/org/openhab/binding/solarman/internal/util/StreamUtils.java
  bundles/org.openhab.binding.solarman/src/main/resources/OH-INF/addon/addon.xml
  bundles/org.openhab.binding.solarman/src/main/resources/OH-INF/config/datetime-channel-config.xml
  bundles/org.openhab.binding.solarman/src/main/resources/OH-INF/config/dynamic-channel-config.xml
  bundles/org.openhab.binding.solarman/src/main/resources/OH-INF/config/number-channel-config.xml
  bundles/org.openhab.binding.solarman/src/main/resources/OH-INF/config/string-channel-config.xml
  bundles/org.openhab.binding.solarman/src/main/resources/OH-INF/i18n/solarman.properties
  bundles/org.openhab.binding.solarman/src/main/resources/OH-INF/thing/channels.xml
  bundles/org.openhab.binding.solarman/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.solarman/src/main/resources/definitions/deye_2mppt.yaml
  bundles/org.openhab.binding.solarman/src/main/resources/definitions/deye_4mppt.yaml
  bundles/org.openhab.binding.solarman/src/main/resources/definitions/deye_hybrid.yaml
  bundles/org.openhab.binding.solarman/src/main/resources/definitions/deye_sg04lp3.yaml
  bundles/org.openhab.binding.solarman/src/main/resources/definitions/deye_string.yaml
  bundles/org.openhab.binding.solarman/src/main/resources/definitions/kstar_hybrid.yaml
  bundles/org.openhab.binding.solarman/src/main/resources/definitions/sofar_g3hyd.yaml
  bundles/org.openhab.binding.solarman/src/main/resources/definitions/sofar_hyd3k-6k-es.yaml
  bundles/org.openhab.binding.solarman/src/main/resources/definitions/sofar_lsw3.yaml
  bundles/org.openhab.binding.solarman/src/main/resources/definitions/sofar_wifikit.yaml
  bundles/org.openhab.binding.solarman/src/main/resources/definitions/solis_1p8k-5g.yaml
  bundles/org.openhab.binding.solarman/src/main/resources/definitions/solis_hybrid.yaml
  bundles/org.openhab.binding.solarman/src/main/resources/definitions/zcs_azzurro-ktl-v3.yaml
  bundles/org.openhab.binding.solarman/src/test/java/org/openhab/binding/solarman/internal/DefinitionParserTest.java
  bundles/org.openhab.binding.solarman/src/test/java/org/openhab/binding/solarman/internal/modbus/SolarmanV5ProtocolTest.java
  bundles/pom.xml
Labels: new binding

#17086 [freeboxos] Change default HTTPS port
  bundles/org.openhab.binding.freeboxos/README.md
  bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/config/FreeboxOsConfiguration.java
  bundles/org.openhab.binding.freeboxos/src/main/resources/OH-INF/config/bridge-config.xml
  bundles/org.openhab.binding.freeboxos/src/main/resources/OH-INF/i18n/freeboxos.properties
Labels: bug
