Repository openhab/openhab-addons, pull requests merged in 2024-08, with the labels that each got.

#17160 [boschshc] Handle relay mode changes during initialization
  bundles/org.openhab.binding.boschshc/README.md
  bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/devices/relay/RelayHandler.java
  bundles/org.openhab.binding.boschshc/src/main/resources/OH-INF/i18n/boschshc.properties
  bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/devices/AbstractBatteryPoweredDeviceHandlerTest.java
  bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/devices/AbstractBoschSHCHandlerTest.java
  bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/devices/AbstractPowerSwitchHandlerTest.java
  bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/devices/AbstractPowerSwitchHandlerWithPowerMeterTest.java
  bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/devices/relay/RelayHandlerTest.java
Labels: enhancement

#17185 [denonmarantz] Fix clearing Now Playing channels
  bundles/org.openhab.binding.denonmarantz/src/main/java/org/openhab/binding/denonmarantz/internal/connector/http/DenonMarantzHttpConnector.java
Labels: bug, community approved

#17163 [shelly] Fix thing re-init after power cycle for firmware update
  bundles/org.openhab.binding.shelly/README.md
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api2/Shelly2ApiJsonDTO.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api2/Shelly2ApiRpc.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/handler/ShellyBaseHandler.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/handler/ShellyManagerInterface.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/handler/ShellyThingInterface.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/manager/ShellyManagerActionPage.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/manager/ShellyManagerOtaPage.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/manager/ShellyManagerOverviewPage.java
  bundles/org.openhab.binding.shelly/src/main/resources/OH-INF/i18n/shelly.properties
Labels: bug, community approved

#17088 [freeboxos] Remove macAddress as thing configuration parameter
  bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/handler/ApiConsumerHandler.java
  bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/handler/ApiConsumerIntf.java
  bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/handler/FreeplugHandler.java
  bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/handler/HostHandler.java
  bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/handler/PlayerHandler.java
  bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/handler/RepeaterHandler.java
  bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/handler/ServerHandler.java
  bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/handler/VmHandler.java
  bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/handler/WifiStationHandler.java
  bundles/org.openhab.binding.freeboxos/src/main/resources/OH-INF/config/player-config.xml
  bundles/org.openhab.binding.freeboxos/src/main/resources/OH-INF/config/repeater-config.xml
  bundles/org.openhab.binding.freeboxos/src/main/resources/OH-INF/config/server-config.xml
  bundles/org.openhab.binding.freeboxos/src/main/resources/OH-INF/config/vm-config.xml
  bundles/org.openhab.binding.freeboxos/src/main/resources/OH-INF/i18n/freeboxos.properties
  bundles/org.openhab.binding.freeboxos/src/main/resources/OH-INF/thing/server-thing-type.xml
Labels: bug

#17203 [freeboxos] Fix enabling/disabling of Mac OS file sharing
  bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/api/rest/AfpManager.java
Labels: bug

#17166 [shelly] Add support for various Gen3 devices (Plus 1/1PM, Mini 1/PM/1PM, Dimmer 0110, i4)
  bundles/org.openhab.binding.shelly/README.md
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api/ShellyDeviceProfile.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/discovery/ShellyThingCreator.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/handler/ShellyBaseHandler.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/handler/ShellyComponents.java
  bundles/org.openhab.binding.shelly/src/main/resources/OH-INF/config/config2.xml
  bundles/org.openhab.binding.shelly/src/test/java/org/openhab/binding/shelly/internal/discovery/ShellyThingCreatorTest.java
Labels: enhancement

#17204 [lutron] Fix Pico buttons for non-LEAP bridges
  bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/handler/PicoKeypadHandler.java
Labels: bug

#17144 [homekit] Support multiple values per enum mapping
  bundles/org.openhab.io.homekit/README.md
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/AbstractHomekitAccessoryImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/AbstractHomekitPositionAccessoryImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitAirQualitySensorImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitCarbonDioxideSensorImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitCarbonMonoxideSensorImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitCharacteristicFactory.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitContactSensorImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitFilterMaintenanceImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitHeaterCoolerImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitIrrigationSystemImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitLeakSensorImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitLockImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitOccupancySensorImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitSecuritySystemImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitSlatImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitSmartSpeakerImpl.java
  bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitSmokeSensorImpl.java
Labels: enhancement

#17172 [awattar] Add TimeSeries support
  bundles/org.openhab.binding.awattar/README.md
  bundles/org.openhab.binding.awattar/src/main/java/org/openhab/binding/awattar/internal/handler/AwattarBridgeHandler.java
  bundles/org.openhab.binding.awattar/src/main/resources/OH-INF/config/config.xml
  bundles/org.openhab.binding.awattar/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.awattar/src/main/resources/OH-INF/update/update.xml
  bundles/org.openhab.binding.awattar/src/test/java/org/openhab/binding/awattar/internal/handler/AwattarBridgeHandlerRefreshTest.java
  bundles/org.openhab.binding.awattar/src/test/java/org/openhab/binding/awattar/internal/handler/AwattarBridgeHandlerTest.java
Labels: enhancement

#17217 [freeboxos] Sending a remote key to player generates an IAE
  bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/api/rest/PlayerManager.java
Labels: bug

#17198 [freeboxos] Use rpm as unit for fan sensors
  bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/handler/ServerHandler.java
  bundles/org.openhab.binding.freeboxos/src/main/resources/OH-INF/thing/channel-types.xml
Labels: enhancement

#17218 [freeboxos] Enhance state display pattern for uptime
  bundles/org.openhab.binding.freeboxos/src/main/resources/OH-INF/thing/channel-types.xml
Labels: enhancement

#17223 [freeboxos] Fix start/stop audio sink
  bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/handler/ApiConsumerHandler.java
  bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/handler/HostHandler.java
Labels: bug

#17224 [freeboxos] Remove veto policy on key-code channel
  bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/handler/PlayerHandler.java
  bundles/org.openhab.binding.freeboxos/src/main/resources/OH-INF/thing/channel-types.xml
Labels: enhancement

#17119 [samsungtv] Adjust logging when TV is off
  bundles/org.openhab.binding.samsungtv/src/main/java/org/openhab/binding/samsungtv/internal/handler/SamsungTvHandler.java
Labels: bug

#16600 [mqtt] Simplify homeassistant thing types, and use AbstractStorageBasedTypeProvider
  bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/MqttChannelTypeProvider.java
  bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/tools/ChildMap.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/generic/internal/MqttBindingConstants.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/generic/internal/MqttThingHandlerFactory.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/ComponentChannel.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/ComponentChannelType.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/DiscoverComponents.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/HaID.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/AbstractComponent.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/AbstractRawSchemaLight.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/AlarmControlPanel.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/BinarySensor.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/Button.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/Camera.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/Climate.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/ComponentFactory.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/Cover.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/DefaultSchemaLight.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/DeviceTrigger.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/Fan.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/JSONSchemaLight.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/Light.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/Lock.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/Number.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/Scene.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/Select.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/Sensor.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/Switch.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/Update.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/Vacuum.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/discovery/HomeAssistantDiscovery.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/handler/HomeAssistantThingHandler.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/resources/OH-INF/config/homeassistant-channel-config.xml
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/resources/OH-INF/i18n/mqtt.properties
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/resources/OH-INF/thing/homeassistant-channels.xml
  bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/AbstractHomeAssistantTests.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/component/AbstractComponentTests.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/component/BinarySensorTests.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/component/SensorTests.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/component/SwitchTests.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/handler/HomeAssistantThingHandlerTests.java
  bundles/org.openhab.binding.mqtt.homie/src/main/java/org/openhab/binding/mqtt/homie/internal/handler/HomieThingHandler.java
  bundles/org.openhab.binding.mqtt.homie/src/main/java/org/openhab/binding/mqtt/homie/internal/homie300/Node.java
  bundles/org.openhab.binding.mqtt.homie/src/test/java/org/openhab/binding/mqtt/homie/internal/handler/HomieThingHandlerTests.java
  itests/org.openhab.binding.mqtt.homeassistant.tests/src/main/java/org/openhab/binding/mqtt/homeassistant/DiscoverComponentsTest.java
  itests/org.openhab.binding.mqtt.homeassistant.tests/src/main/java/org/openhab/binding/mqtt/homeassistant/HomeAssistantMQTTImplementationTest.java
Labels: enhancement

#17236 [freeboxos] Better fix for WEB socket registration
  bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/api/rest/FreeboxOsSession.java
  bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/api/rest/WebSocketManager.java
Labels: enhancement

#17226 [freeboxos] Fix actions to make them available in DSL rules
  bundles/org.openhab.binding.freeboxos/README.md
  bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/action/ActivePlayerActions.java
  bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/action/CallActions.java
  bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/action/FreeplugActions.java
  bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/action/HostActions.java
  bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/action/PlayerActions.java
  bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/action/RepeaterActions.java
  bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/action/ServerActions.java
Labels: bug

#17238 [freeboxos] Fix thing status handling when rebooting the player
  bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/handler/ActivePlayerHandler.java
  bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/handler/ApiConsumerHandler.java
  bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/handler/HostHandler.java
  bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/handler/RepeaterHandler.java
  bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/handler/VmHandler.java
  bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/handler/WifiStationHandler.java
  bundles/org.openhab.binding.freeboxos/src/main/resources/OH-INF/i18n/freeboxos.properties
Labels: bug

#17237 [freeboxos] Avoid useless API requests (server/player)
  bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/FreeboxOsBindingConstants.java
  bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/handler/ActivePlayerHandler.java
  bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/handler/ApiConsumerHandler.java
  bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/handler/ApiConsumerIntf.java
  bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/handler/HostHandler.java
  bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/handler/RepeaterHandler.java
  bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/handler/RevolutionHandler.java
  bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/handler/ServerHandler.java
  bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/handler/VmHandler.java
  bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/handler/WifiStationHandler.java
Labels: enhancement

#17190 [boschshc] Fix NPE during deserialization, make long polling more robust
  bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/devices/bridge/LongPolling.java
  bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/devices/bridge/dto/UserDefinedState.java
  bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/serialization/BoschServiceDataDeserializer.java
  bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/devices/bridge/LongPollingTest.java
  bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/devices/bridge/dto/UserDefinedStateTest.java
  bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/serialization/BoschServiceDataDeserializerTest.java
  bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/services/dto/BoschSHCServiceStateTest.java
Labels: bug

#17244 [freeboxos] Fix media playing
  bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/api/rest/MediaReceiverManager.java
  bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/api/rest/RestManager.java
  bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/handler/ApiConsumerHandler.java
Labels: bug

#17222 [nuvo] Add image size configurations
  bundles/org.openhab.binding.nuvo/README.md
  bundles/org.openhab.binding.nuvo/src/main/java/org/openhab/binding/nuvo/internal/NuvoBindingConstants.java
  bundles/org.openhab.binding.nuvo/src/main/java/org/openhab/binding/nuvo/internal/NuvoHandlerFactory.java
  bundles/org.openhab.binding.nuvo/src/main/java/org/openhab/binding/nuvo/internal/configuration/NuvoBindingConfiguration.java
  bundles/org.openhab.binding.nuvo/src/main/java/org/openhab/binding/nuvo/internal/handler/NuvoHandler.java
  bundles/org.openhab.binding.nuvo/src/main/resources/OH-INF/addon/addon.xml
  bundles/org.openhab.binding.nuvo/src/main/resources/OH-INF/i18n/nuvo.properties
Labels: enhancement

#17199 [freeboxos] Reduce log level for discovery warnings to debug
  bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/discovery/FreeboxOsDiscoveryService.java
Labels: enhancement

#17201 [freeboxos] Enhance log warning when handling channel command fails
  bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/api/ApiHandler.java
  bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/api/PermissionException.java
  bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/handler/ApiConsumerHandler.java
Labels: enhancement

#17240 [mqtt.homeassistant] Fix color lights that don't specify color_mode: true
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/JSONSchemaLight.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/Light.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/component/JSONSchemaLightTests.java
Labels: bug

#17219 [freeboxos] Add FTTH and xDSL line status
  bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/FreeboxOsBindingConstants.java
  bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/api/rest/ConnectionManager.java
  bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/handler/ServerHandler.java
  bundles/org.openhab.binding.freeboxos/src/main/resources/OH-INF/i18n/freeboxos.properties
  bundles/org.openhab.binding.freeboxos/src/main/resources/OH-INF/thing/channel-types.xml
  bundles/org.openhab.binding.freeboxos/src/main/resources/OH-INF/thing/server-channel-groups.xml
  bundles/org.openhab.binding.freeboxos/src/main/resources/OH-INF/thing/server-thing-type.xml
  bundles/org.openhab.binding.freeboxos/src/main/resources/OH-INF/update/instructions.xml
Labels: enhancement

#17251 [rollershutterposition] Fix addon id
  bundles/org.openhab.transform.rollershutterposition/src/main/resources/OH-INF/addon/addon.xml
Labels: bug

#17254 [freeboxos] Avoid a call to the lcd API when not required
  bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/handler/RevolutionHandler.java
Labels: bug

#17257 [freeboxos] Get server AirPlay capabilities
  bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/handler/ServerHandler.java
Labels: enhancement

#17188 [tibber] Only open websocket if live channels are linked
  bundles/org.openhab.binding.tibber/src/main/java/org/openhab/binding/tibber/internal/handler/TibberHandler.java
Labels: enhancement

#17261 [freeboxos] Fix category for lcd-brightness channel type
  bundles/org.openhab.binding.freeboxos/src/main/resources/OH-INF/thing/channel-types.xml
Labels: bug

#17260 [freeboxos] Add channels in group xdsl
  bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/FreeboxOsBindingConstants.java
  bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/api/rest/ConnectionManager.java
  bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/handler/ServerHandler.java
  bundles/org.openhab.binding.freeboxos/src/main/resources/OH-INF/i18n/freeboxos.properties
  bundles/org.openhab.binding.freeboxos/src/main/resources/OH-INF/thing/channel-types.xml
  bundles/org.openhab.binding.freeboxos/src/main/resources/OH-INF/thing/server-channel-groups.xml
  bundles/org.openhab.binding.freeboxos/src/main/resources/OH-INF/update/instructions.xml
Labels: enhancement

#16907 [wled] Fix brightness inconsistency + power on
  bundles/org.openhab.binding.wled/src/main/java/org/openhab/binding/wled/internal/WLedHelper.java
  bundles/org.openhab.binding.wled/src/main/java/org/openhab/binding/wled/internal/api/WledApiV084.java
  bundles/org.openhab.binding.wled/src/main/java/org/openhab/binding/wled/internal/handlers/WLedSegmentHandler.java
Labels: bug

#17272 [freeboxos] Fix phone and calls configuration
  bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/config/LandlineConfiguration.java
  bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/config/PhoneConfigurationBuilder.java
  bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/discovery/FreeboxOsDiscoveryService.java
  bundles/org.openhab.binding.freeboxos/src/main/resources/OH-INF/config/phone-config.xml
  bundles/org.openhab.binding.freeboxos/src/main/resources/OH-INF/i18n/freeboxos.properties
  bundles/org.openhab.binding.freeboxos/src/main/resources/OH-INF/thing/phone-thing-type.xml
Labels: bug

#17270 [ecovacs] Fix typo in ecovacs folder name
  bundles/org.openhab.binding.ecovacs/README.md
Labels: documentation

#17274 [freeboxos] Fix command handling for DECT thing type
  bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/api/rest/PhoneManager.java
Labels: bug

#17277 [wled] Fix: FX and Palettes channel StateDescriptionProvider handling
  bundles/org.openhab.binding.wled/src/main/java/org/openhab/binding/wled/internal/handlers/WLedSegmentHandler.java
Labels: bug

#17116 [telegram] Fix log spamming when transient network issue occurs
  bundles/org.openhab.binding.telegram/src/main/java/org/openhab/binding/telegram/internal/TelegramHandler.java
Labels: bug

#17287 [freeboxos] Add translatable labels for discovered things
  bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/config/PhoneConfigurationBuilder.java
  bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/discovery/FreeboxOsDiscoveryService.java
  bundles/org.openhab.binding.freeboxos/src/main/resources/OH-INF/i18n/freeboxos.properties
Labels: enhancement

#17291 [ambientweather] Fix minor formatting errors
  bundles/org.openhab.binding.ambientweather/README.md
Labels: documentation

#17292 [exec] Support transformation chaining and refactor using ChannelTransformation
  bundles/org.openhab.binding.exec/README.md
  bundles/org.openhab.binding.exec/src/main/java/org/openhab/binding/exec/internal/handler/ExecHandler.java
  bundles/org.openhab.binding.exec/src/main/resources/OH-INF/i18n/exec.properties
  bundles/org.openhab.binding.exec/src/main/resources/OH-INF/thing/thing-types.xml
Labels: enhancement

#17279 [freeboxos] First big update of README
  bundles/org.openhab.binding.freeboxos/README.md
  bundles/org.openhab.binding.freeboxos/src/main/resources/OH-INF/config/host-config.xml
  bundles/org.openhab.binding.freeboxos/src/main/resources/OH-INF/config/player-config.xml
  bundles/org.openhab.binding.freeboxos/src/main/resources/OH-INF/config/repeater-config.xml
  bundles/org.openhab.binding.freeboxos/src/main/resources/OH-INF/config/server-config.xml
  bundles/org.openhab.binding.freeboxos/src/main/resources/OH-INF/config/vm-config.xml
  bundles/org.openhab.binding.freeboxos/src/main/resources/OH-INF/config/wifi-host-config.xml
  bundles/org.openhab.binding.freeboxos/src/main/resources/OH-INF/i18n/freeboxos.properties
  bundles/org.openhab.binding.freeboxos/src/main/resources/OH-INF/thing/home-thing-type.xml
  bundles/org.openhab.binding.freeboxos/src/main/resources/OH-INF/thing/host-channel-groups.xml
  bundles/org.openhab.binding.freeboxos/src/main/resources/OH-INF/thing/server-channel-groups.xml
Labels: documentation

#16980 [hue] Add support for enabling automations
  bundles/org.openhab.binding.hue/doc/readme_v2.md
  bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/HueBindingConstants.java
  bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/api/dto/clip2/Event.java
  bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/api/dto/clip2/MetaData.java
  bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/api/dto/clip2/Resource.java
  bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/api/dto/clip2/enums/CategoryType.java
  bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/api/dto/clip2/enums/ContentType.java
  bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/connection/Clip2Bridge.java
  bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/Clip2BridgeHandler.java
  bundles/org.openhab.binding.hue/src/main/resources/OH-INF/i18n/hue.properties
  bundles/org.openhab.binding.hue/src/main/resources/OH-INF/thing/bridge.xml
  bundles/org.openhab.binding.hue/src/main/resources/OH-INF/thing/channels.xml
  bundles/org.openhab.binding.hue/src/test/java/org/openhab/binding/hue/internal/clip2/Clip2DtoTest.java
  bundles/org.openhab.binding.hue/src/test/java/org/openhab/binding/hue/internal/clip2/SettersTest.java
  bundles/org.openhab.binding.hue/src/test/resources/behavior_instance.json
Labels: enhancement

#17289 [boschshc] Fix NPE during deserialization, make long polling more robust (#17190)
  bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/devices/bridge/LongPolling.java
  bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/devices/bridge/dto/UserDefinedState.java
  bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/serialization/BoschServiceDataDeserializer.java
  bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/devices/bridge/LongPollingTest.java
  bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/devices/bridge/dto/UserDefinedStateTest.java
  bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/serialization/BoschServiceDataDeserializerTest.java
  bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/services/dto/BoschSHCServiceStateTest.java
Labels: bug, patch

#17300 [map] Support inline map
  bundles/org.openhab.transform.map/README.md
  bundles/org.openhab.transform.map/src/main/java/org/openhab/transform/map/internal/MapTransformationService.java
  bundles/org.openhab.transform.map/src/test/java/org/openhab/transform/map/internal/MapTransformationServiceTest.java
Labels: enhancement

#17259 [freeboxos] Add unitHint on few channel types
  bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/handler/ServerHandler.java
  bundles/org.openhab.binding.freeboxos/src/main/resources/OH-INF/i18n/freeboxos.properties
  bundles/org.openhab.binding.freeboxos/src/main/resources/OH-INF/thing/channel-types.xml
Labels: enhancement

#17288 [http] Support chaining transformations without an intersection symbol
  bundles/org.openhab.binding.http/README.md
  bundles/org.openhab.binding.http/src/main/java/org/openhab/binding/http/internal/config/HttpChannelConfig.java
  bundles/org.openhab.binding.http/src/main/resources/OH-INF/config/config.xml
  bundles/org.openhab.binding.http/src/main/resources/OH-INF/i18n/http.properties
Labels: enhancement

#17202 [airq] Fix occasional stalling of sensor value updates and refactoring
  bundles/org.openhab.binding.airq/src/main/java/org/openhab/binding/airq/internal/AirqHandler.java
Labels: bug

#17304 [senechome] sync states with latest senec GUI FW 0967
  bundles/org.openhab.binding.senechome/src/main/java/org/openhab/binding/senechome/internal/SenecSystemStatus.java
Labels: enhancement

#17309 [freeboxos] Change default timeout to 10s
  bundles/org.openhab.binding.freeboxos/README.md
  bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/FreeboxOsHandlerFactory.java
  bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/api/ApiHandler.java
  bundles/org.openhab.binding.freeboxos/src/main/resources/OH-INF/addon/addon.xml
Labels: bug

#16996 [solarforecast] Avoid past data updates
  bundles/org.openhab.binding.solarforecast/src/main/java/org/openhab/binding/solarforecast/internal/forecastsolar/ForecastSolarObject.java
  bundles/org.openhab.binding.solarforecast/src/main/java/org/openhab/binding/solarforecast/internal/solcast/SolcastObject.java
  bundles/org.openhab.binding.solarforecast/src/test/java/org/openhab/binding/solarforecast/ForecastSolarTest.java
  bundles/org.openhab.binding.solarforecast/src/test/java/org/openhab/binding/solarforecast/SolcastTest.java
Labels: bug

#17314 [mail] Support chaining transformations without an intersection symbol
  bundles/org.openhab.binding.mail/README.md
  bundles/org.openhab.binding.mail/src/main/java/org/openhab/binding/mail/internal/config/POP3IMAPContentChannelConfig.java
  bundles/org.openhab.binding.mail/src/main/resources/OH-INF/i18n/mail.properties
  bundles/org.openhab.binding.mail/src/main/resources/OH-INF/thing/thing-types.xml
Labels: enhancement

#17318 [sonos] Ignore Sonos Boost at discovery
  bundles/org.openhab.binding.sonos/src/main/java/org/openhab/binding/sonos/internal/SonosXMLParser.java
  bundles/org.openhab.binding.sonos/src/test/java/org/openhab/binding/sonos/internal/SonosXMLParserTest.java
Labels: enhancement

#17312 [roku] Add device communcation logging
  bundles/org.openhab.binding.roku/src/main/java/org/openhab/binding/roku/internal/communication/RokuCommunicator.java
Labels: enhancement

#17221 [salus] Add `running-state` channel for it600
  bundles/org.openhab.binding.salus/DEV_README.md
  bundles/org.openhab.binding.salus/README.md
  bundles/org.openhab.binding.salus/src/main/java/org/openhab/binding/salus/internal/SalusBindingConstants.java
  bundles/org.openhab.binding.salus/src/main/java/org/openhab/binding/salus/internal/aws/handler/AwsCloudBridgeHandler.java
  bundles/org.openhab.binding.salus/src/main/java/org/openhab/binding/salus/internal/cloud/handler/CloudBridgeHandler.java
  bundles/org.openhab.binding.salus/src/main/java/org/openhab/binding/salus/internal/handler/It600Handler.java
  bundles/org.openhab.binding.salus/src/main/resources/OH-INF/i18n/salus.properties
  bundles/org.openhab.binding.salus/src/main/resources/OH-INF/thing/it600.xml
  bundles/org.openhab.binding.salus/src/main/resources/OH-INF/update/it600-running-state.xml
  bundles/org.openhab.binding.salus/src/test/java/org/openhab/binding/salus/internal/ReverseEngineerProtocol.java
Labels: enhancement

#17310 [freeboxos] Avoid useless API requests (phone)
  bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/handler/DectHandler.java
  bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/handler/FxsHandler.java
Labels: enhancement

#17302 [hue] Support dynamic add/delete of scenes
  bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/Clip2ThingHandler.java
Labels: enhancement

#17324 [electroluxair] Remove deprecated binding
  CODEOWNERS
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.electroluxair/NOTICE
  bundles/org.openhab.binding.electroluxair/README.md
  bundles/org.openhab.binding.electroluxair/doc/electrolux_pure_a9.png
  bundles/org.openhab.binding.electroluxair/pom.xml
  bundles/org.openhab.binding.electroluxair/src/main/feature/feature.xml
  bundles/org.openhab.binding.electroluxair/src/main/java/org/openhab/binding/electroluxair/internal/ElectroluxAirBindingConstants.java
  bundles/org.openhab.binding.electroluxair/src/main/java/org/openhab/binding/electroluxair/internal/ElectroluxAirBridgeConfiguration.java
  bundles/org.openhab.binding.electroluxair/src/main/java/org/openhab/binding/electroluxair/internal/ElectroluxAirConfiguration.java
  bundles/org.openhab.binding.electroluxair/src/main/java/org/openhab/binding/electroluxair/internal/ElectroluxAirException.java
  bundles/org.openhab.binding.electroluxair/src/main/java/org/openhab/binding/electroluxair/internal/api/ElectroluxDeltaAPI.java
  bundles/org.openhab.binding.electroluxair/src/main/java/org/openhab/binding/electroluxair/internal/discovery/ElectroluxAirDiscoveryService.java
  bundles/org.openhab.binding.electroluxair/src/main/java/org/openhab/binding/electroluxair/internal/dto/ElectroluxPureA9DTO.java
  bundles/org.openhab.binding.electroluxair/src/main/java/org/openhab/binding/electroluxair/internal/handler/ElectroluxAirBridgeHandler.java
  bundles/org.openhab.binding.electroluxair/src/main/java/org/openhab/binding/electroluxair/internal/handler/ElectroluxAirHandler.java
  bundles/org.openhab.binding.electroluxair/src/main/java/org/openhab/binding/electroluxair/internal/handler/ElectroluxAirHandlerFactory.java
  bundles/org.openhab.binding.electroluxair/src/main/resources/OH-INF/addon/addon.xml
  bundles/org.openhab.binding.electroluxair/src/main/resources/OH-INF/i18n/electroluxair.properties
  bundles/org.openhab.binding.electroluxair/src/main/resources/OH-INF/i18n/electroluxair_fr.properties
  bundles/org.openhab.binding.electroluxair/src/main/resources/OH-INF/i18n/electroluxair_it.properties
  bundles/org.openhab.binding.electroluxair/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.electroluxair/src/main/resources/OH-INF/update/instructions.xml
  bundles/pom.xml
Labels: enhancement

#17294 [evcc] Fix unit hints missing for percentage channels
  bundles/org.openhab.binding.evcc/src/main/resources/OH-INF/thing/thing-types.xml
Labels: bug

#17331 [openhabcloud] Add the missing configuration parameter for NOT_EXTENDED actions
  bundles/org.openhab.io.openhabcloud/src/main/java/org/openhab/io/openhabcloud/internal/actions/NotificationActionTypeProvider.java
Labels: bug

#13495 [HomeWizard] Add support for Energy Socket and Watermeter products
  bundles/org.openhab.binding.homewizard/README.md
  bundles/org.openhab.binding.homewizard/src/main/java/org/openhab/binding/homewizard/internal/DataPayload.java
  bundles/org.openhab.binding.homewizard/src/main/java/org/openhab/binding/homewizard/internal/HomeWizardBindingConstants.java
  bundles/org.openhab.binding.homewizard/src/main/java/org/openhab/binding/homewizard/internal/HomeWizardConfiguration.java
  bundles/org.openhab.binding.homewizard/src/main/java/org/openhab/binding/homewizard/internal/HomeWizardDeviceHandler.java
  bundles/org.openhab.binding.homewizard/src/main/java/org/openhab/binding/homewizard/internal/HomeWizardEnergySocketHandler.java
  bundles/org.openhab.binding.homewizard/src/main/java/org/openhab/binding/homewizard/internal/HomeWizardHandlerFactory.java
  bundles/org.openhab.binding.homewizard/src/main/java/org/openhab/binding/homewizard/internal/HomeWizardP1MeterHandler.java
  bundles/org.openhab.binding.homewizard/src/main/java/org/openhab/binding/homewizard/internal/HomeWizardStatefulDeviceHandler.java
  bundles/org.openhab.binding.homewizard/src/main/java/org/openhab/binding/homewizard/internal/HomeWizardWaterMeterHandler.java
  bundles/org.openhab.binding.homewizard/src/main/java/org/openhab/binding/homewizard/internal/StatePayload.java
  bundles/org.openhab.binding.homewizard/src/main/resources/OH-INF/i18n/homewizard.properties
  bundles/org.openhab.binding.homewizard/src/main/resources/OH-INF/thing/thing-types.xml
Labels: enhancement, additional testing preferred

#17149 [daikin] Update channels immediately after a successful API command
  bundles/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/DaikinWebTargets.java
  bundles/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/api/Enums.java
  bundles/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/handler/DaikinAcUnitHandler.java
  bundles/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/handler/DaikinAirbaseUnitHandler.java
  bundles/org.openhab.binding.daikin/src/main/java/org/openhab/binding/daikin/internal/handler/DaikinBaseHandler.java
  bundles/org.openhab.binding.daikin/src/main/resources/OH-INF/thing/thing-types.xml
Labels: enhancement

#17206 [homematic] Fixed #16940: Spaces in URLs are not allowed
  bundles/org.openhab.binding.homematic/README.md
  bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/handler/HomematicBridgeHandler.java
  bundles/org.openhab.binding.homematic/src/test/java/org/openhab/binding/homematic/internal/handler/HomematicBridgeHandlerMock.java
  bundles/org.openhab.binding.homematic/src/test/java/org/openhab/binding/homematic/internal/handler/HomematicBridgeHandlerTest.java
Labels: bug

#17323 [basicprofiles] Add inequality comparisons to State Filter profile
  bundles/org.openhab.transform.basicprofiles/README.md
  bundles/org.openhab.transform.basicprofiles/src/main/java/org/openhab/transform/basicprofiles/internal/config/StateFilterProfileConfig.java
  bundles/org.openhab.transform.basicprofiles/src/main/java/org/openhab/transform/basicprofiles/internal/factory/BasicProfilesFactory.java
  bundles/org.openhab.transform.basicprofiles/src/main/java/org/openhab/transform/basicprofiles/internal/profiles/StateFilterProfile.java
  bundles/org.openhab.transform.basicprofiles/src/main/resources/OH-INF/config/state-filter.xml
  bundles/org.openhab.transform.basicprofiles/src/main/resources/OH-INF/i18n/basicprofiles.properties
  bundles/org.openhab.transform.basicprofiles/src/test/java/org/openhab/transform/basicprofiles/internal/profiles/StateFilterProfileTest.java
Labels: enhancement

#17267 [mercedesme] Fix trip channel type id
  bundles/org.openhab.binding.mercedesme/src/main/resources/OH-INF/thing/thing-combustion.xml
  bundles/org.openhab.binding.mercedesme/src/main/resources/OH-INF/thing/thing-hybrid.xml
  bundles/org.openhab.binding.mercedesme/src/main/resources/OH-INF/thing/trip-conv-group.xml
  bundles/org.openhab.binding.mercedesme/src/main/resources/OH-INF/thing/trip-hybrid-group.xml
  bundles/org.openhab.binding.mercedesme/src/main/resources/OH-INF/update/instructions.xml
Labels: bug

#17239 [visualcrossing] Initial contribution
  CODEOWNERS
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.visualcrossing/NOTICE
  bundles/org.openhab.binding.visualcrossing/README.md
  bundles/org.openhab.binding.visualcrossing/docs/Day_01.items
  bundles/org.openhab.binding.visualcrossing/docs/Day_02.items
  bundles/org.openhab.binding.visualcrossing/docs/Day_03.items
  bundles/org.openhab.binding.visualcrossing/docs/Day_04.items
  bundles/org.openhab.binding.visualcrossing/docs/Day_05.items
  bundles/org.openhab.binding.visualcrossing/docs/Day_06.items
  bundles/org.openhab.binding.visualcrossing/docs/Day_07.items
  bundles/org.openhab.binding.visualcrossing/docs/Day_08.items
  bundles/org.openhab.binding.visualcrossing/docs/Day_09.items
  bundles/org.openhab.binding.visualcrossing/docs/Day_10.items
  bundles/org.openhab.binding.visualcrossing/docs/Day_11.items
  bundles/org.openhab.binding.visualcrossing/docs/Day_12.items
  bundles/org.openhab.binding.visualcrossing/docs/Day_13.items
  bundles/org.openhab.binding.visualcrossing/docs/Day_14.items
  bundles/org.openhab.binding.visualcrossing/docs/Day_15.items
  bundles/org.openhab.binding.visualcrossing/docs/only_days.items
  bundles/org.openhab.binding.visualcrossing/pom.xml
  bundles/org.openhab.binding.visualcrossing/src/main/feature/feature.xml
  bundles/org.openhab.binding.visualcrossing/src/main/java/org/openhab/binding/visualcrossing/internal/TypeBuilder.java
  bundles/org.openhab.binding.visualcrossing/src/main/java/org/openhab/binding/visualcrossing/internal/VisualCrossingBindingConstants.java
  bundles/org.openhab.binding.visualcrossing/src/main/java/org/openhab/binding/visualcrossing/internal/VisualCrossingConfiguration.java
  bundles/org.openhab.binding.visualcrossing/src/main/java/org/openhab/binding/visualcrossing/internal/VisualCrossingHandler.java
  bundles/org.openhab.binding.visualcrossing/src/main/java/org/openhab/binding/visualcrossing/internal/VisualCrossingHandlerFactory.java
  bundles/org.openhab.binding.visualcrossing/src/main/java/org/openhab/binding/visualcrossing/internal/WeatherCrossingActions.java
  bundles/org.openhab.binding.visualcrossing/src/main/java/org/openhab/binding/visualcrossing/internal/api/VisualCrossingApi.java
  bundles/org.openhab.binding.visualcrossing/src/main/java/org/openhab/binding/visualcrossing/internal/api/VisualCrossingApiException.java
  bundles/org.openhab.binding.visualcrossing/src/main/java/org/openhab/binding/visualcrossing/internal/api/VisualCrossingAuthException.java
  bundles/org.openhab.binding.visualcrossing/src/main/java/org/openhab/binding/visualcrossing/internal/api/VisualCrossingRateException.java
  bundles/org.openhab.binding.visualcrossing/src/main/java/org/openhab/binding/visualcrossing/internal/api/dto/Cost.java
  bundles/org.openhab.binding.visualcrossing/src/main/java/org/openhab/binding/visualcrossing/internal/api/dto/CurrentConditions.java
  bundles/org.openhab.binding.visualcrossing/src/main/java/org/openhab/binding/visualcrossing/internal/api/dto/Day.java
  bundles/org.openhab.binding.visualcrossing/src/main/java/org/openhab/binding/visualcrossing/internal/api/dto/Hour.java
  bundles/org.openhab.binding.visualcrossing/src/main/java/org/openhab/binding/visualcrossing/internal/api/dto/WeatherResponse.java
  bundles/org.openhab.binding.visualcrossing/src/main/java/org/openhab/binding/visualcrossing/internal/api/rest/ApiClient.java
  bundles/org.openhab.binding.visualcrossing/src/main/java/org/openhab/binding/visualcrossing/internal/api/rest/HttpVisualCrossingApiException.java
  bundles/org.openhab.binding.visualcrossing/src/main/java/org/openhab/binding/visualcrossing/internal/api/rest/RestClient.java
  bundles/org.openhab.binding.visualcrossing/src/main/java/org/openhab/binding/visualcrossing/internal/api/rest/RetryHttpClient.java
  bundles/org.openhab.binding.visualcrossing/src/main/resources/OH-INF/addon/addon.xml
  bundles/org.openhab.binding.visualcrossing/src/main/resources/OH-INF/i18n/visualcrossing.properties
  bundles/org.openhab.binding.visualcrossing/src/main/resources/OH-INF/thing/channel-types.xml
  bundles/org.openhab.binding.visualcrossing/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.visualcrossing/src/test/java/org/openhab/binding/visualcrossing/internal/api/VisualCrossingApiTest.java
  bundles/org.openhab.binding.visualcrossing/src/test/java/org/openhab/binding/visualcrossing/internal/api/VisualCrossingApiTestConst.java
  bundles/pom.xml
Labels: new binding

#17344 [Tibber] Improve connection logic
  bundles/org.openhab.binding.tibber/src/main/java/org/openhab/binding/tibber/internal/handler/TibberHandler.java
Labels: enhancement

#17347 [visualcrossing] Fix missing dimension
  bundles/org.openhab.binding.visualcrossing/docs/Day_01.items
  bundles/org.openhab.binding.visualcrossing/docs/Day_02.items
  bundles/org.openhab.binding.visualcrossing/docs/Day_03.items
  bundles/org.openhab.binding.visualcrossing/docs/Day_04.items
  bundles/org.openhab.binding.visualcrossing/docs/Day_05.items
  bundles/org.openhab.binding.visualcrossing/docs/Day_06.items
  bundles/org.openhab.binding.visualcrossing/docs/Day_07.items
  bundles/org.openhab.binding.visualcrossing/docs/Day_08.items
  bundles/org.openhab.binding.visualcrossing/docs/Day_09.items
  bundles/org.openhab.binding.visualcrossing/docs/Day_10.items
  bundles/org.openhab.binding.visualcrossing/docs/Day_11.items
  bundles/org.openhab.binding.visualcrossing/docs/Day_12.items
  bundles/org.openhab.binding.visualcrossing/docs/Day_13.items
  bundles/org.openhab.binding.visualcrossing/docs/Day_14.items
  bundles/org.openhab.binding.visualcrossing/docs/Day_15.items
  bundles/org.openhab.binding.visualcrossing/src/main/resources/OH-INF/thing/channel-types.xml
Labels: bug, regression

#17332 [AirGradient] Convert from AbstractDiscoveryService to AbstractThingHandlerDiscoveryService
  bundles/org.openhab.binding.airgradient/src/main/java/org/openhab/binding/airgradient/internal/discovery/AirGradientLocationDiscoveryService.java
Labels: bug

#17169 [aWATTar] add aWATTar API class
  bundles/org.openhab.binding.awattar/src/main/java/org/openhab/binding/awattar/internal/AwattarPrice.java
  bundles/org.openhab.binding.awattar/src/main/java/org/openhab/binding/awattar/internal/api/AwattarApi.java
  bundles/org.openhab.binding.awattar/src/main/java/org/openhab/binding/awattar/internal/handler/AwattarBestPriceHandler.java
  bundles/org.openhab.binding.awattar/src/main/java/org/openhab/binding/awattar/internal/handler/AwattarBridgeHandler.java
  bundles/org.openhab.binding.awattar/src/main/resources/OH-INF/i18n/awattar.properties
  bundles/org.openhab.binding.awattar/src/test/java/org/openhab/binding/awattar/internal/api/AwattarApiTest.java
  bundles/org.openhab.binding.awattar/src/test/java/org/openhab/binding/awattar/internal/handler/AwattarBridgeHandlerRefreshTest.java
  bundles/org.openhab.binding.awattar/src/test/java/org/openhab/binding/awattar/internal/handler/AwattarBridgeHandlerTest.java
  bundles/org.openhab.binding.awattar/src/test/resources/org/openhab/binding/awattar/internal/api/api_response.json
Labels: enhancement

#17346 [basicprofile] Fix statefilter check against item's value on the rhs
  bundles/org.openhab.transform.basicprofiles/src/main/java/org/openhab/transform/basicprofiles/internal/profiles/StateFilterProfile.java
  bundles/org.openhab.transform.basicprofiles/src/test/java/org/openhab/transform/basicprofiles/internal/profiles/StateFilterProfileTest.java
Labels: bug, regression
