Repository openhab/openhab-addons, pull requests merged in 2025-03, with the labels that each got.

#18323 [somfytahoma] Fix getting last history event
  bundles/org.openhab.binding.jablotron/README.md
  bundles/org.openhab.binding.jablotron/src/main/java/org/openhab/binding/jablotron/JablotronBindingConstants.java
  bundles/org.openhab.binding.jablotron/src/main/java/org/openhab/binding/jablotron/internal/handler/JablotronAlarmHandler.java
  bundles/org.openhab.binding.jablotron/src/main/java/org/openhab/binding/jablotron/internal/handler/JablotronBridgeHandler.java
  bundles/org.openhab.binding.jablotron/src/main/java/org/openhab/binding/jablotron/internal/handler/JablotronJa100FHandler.java
  bundles/org.openhab.binding.jablotron/src/main/java/org/openhab/binding/jablotron/internal/model/JablotronAccessTokenData.java
  bundles/org.openhab.binding.jablotron/src/main/java/org/openhab/binding/jablotron/internal/model/JablotronAccessTokenResponse.java
  bundles/org.openhab.binding.jablotron/src/main/java/org/openhab/binding/jablotron/internal/model/JablotronHistoryDataEvent.java
  bundles/org.openhab.binding.jablotron/src/main/resources/OH-INF/thing/oasis.xml
  bundles/org.openhab.binding.jablotron/src/main/resources/OH-INF/update/update.xml
Labels: bug

#18348 [insteon] Update console commands documentation
  bundles/org.openhab.binding.insteon/README.md
Labels: documentation

#18343 [tapocontrol] Accept more commands on dimmer/color channels
  bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/devices/wifi/lightstrip/TapoLightStripHandler.java
Labels: enhancement

#18346 [casokitchen] Adjust flaky test
  bundles/org.openhab.binding.casokitchen/src/test/java/org/openhab/binding/caso/internal/TestHandler.java
Labels: test, regression

#18352 [homewizard] Fix for incorrect thing type id for kWh meter
  bundles/org.openhab.binding.homewizard/src/main/java/org/openhab/binding/homewizard/internal/devices/HomeWizardEnergyMeterMeasurementPayload.java
  bundles/org.openhab.binding.homewizard/src/main/java/org/openhab/binding/homewizard/internal/devices/p1_meter/HomeWizardP1MeterMeasurementPayload.java
  bundles/org.openhab.binding.homewizard/src/main/java/org/openhab/binding/homewizard/internal/devices/plug_in_battery/HomeWizardPlugInBatteryMeasurementPayload.java
  bundles/org.openhab.binding.homewizard/src/main/java/org/openhab/binding/homewizard/internal/devices/water_meter/HomeWizardWaterMeterHandler.java
  bundles/org.openhab.binding.homewizard/src/main/java/org/openhab/binding/homewizard/internal/devices/water_meter/HomeWizardWaterMeterMeasurementPayload.java
  bundles/org.openhab.binding.homewizard/src/main/resources/OH-INF/i18n/homewizard.properties
  bundles/org.openhab.binding.homewizard/src/main/resources/OH-INF/thing/hwe-kwh.xml
  bundles/org.openhab.binding.homewizard/src/test/java/org/openhab/binding/homewizard/internal/devices/water_meter/HomeWizardWaterMeterMeasurementPayloadTest.java
Labels: bug, regression

#18342 [mercedesme] New authorization process
  bundles/org.openhab.binding.mercedesme/README.md
  bundles/org.openhab.binding.mercedesme/doc/OH-Step0.png
  bundles/org.openhab.binding.mercedesme/doc/OH-Step1.png
  bundles/org.openhab.binding.mercedesme/doc/OH-Step2.png
  bundles/org.openhab.binding.mercedesme/doc/OH-Step3.png
  bundles/org.openhab.binding.mercedesme/src/main/java/org/openhab/binding/mercedesme/internal/Constants.java
  bundles/org.openhab.binding.mercedesme/src/main/java/org/openhab/binding/mercedesme/internal/MercedesMeHandlerFactory.java
  bundles/org.openhab.binding.mercedesme/src/main/java/org/openhab/binding/mercedesme/internal/config/AccountConfiguration.java
  bundles/org.openhab.binding.mercedesme/src/main/java/org/openhab/binding/mercedesme/internal/dto/TokenResponse.java
  bundles/org.openhab.binding.mercedesme/src/main/java/org/openhab/binding/mercedesme/internal/handler/AccountHandler.java
  bundles/org.openhab.binding.mercedesme/src/main/java/org/openhab/binding/mercedesme/internal/handler/VehicleHandler.java
  bundles/org.openhab.binding.mercedesme/src/main/java/org/openhab/binding/mercedesme/internal/server/AuthServer.java
  bundles/org.openhab.binding.mercedesme/src/main/java/org/openhab/binding/mercedesme/internal/server/AuthService.java
  bundles/org.openhab.binding.mercedesme/src/main/java/org/openhab/binding/mercedesme/internal/server/AuthServlet.java
  bundles/org.openhab.binding.mercedesme/src/main/java/org/openhab/binding/mercedesme/internal/server/MBWebsocket.java
  bundles/org.openhab.binding.mercedesme/src/main/java/org/openhab/binding/mercedesme/internal/utils/Utils.java
  bundles/org.openhab.binding.mercedesme/src/main/resources/OH-INF/config/bridge-config.xml
  bundles/org.openhab.binding.mercedesme/src/main/resources/OH-INF/i18n/mercedesme.properties
  bundles/org.openhab.binding.mercedesme/src/test/java/org/openhab/binding/mercedesme/StatusTests.java
  bundles/org.openhab.binding.mercedesme/src/test/java/org/openhab/binding/mercedesme/internal/handler/AccountHandlerMock.java
  bundles/org.openhab.binding.mercedesme/src/test/java/org/openhab/binding/mercedesme/internal/handler/VehicleHandlerTest.java
  bundles/org.openhab.binding.mercedesme/src/test/resources/json/TokenResponse.json
Labels: enhancement

#18337 [ipcamera] Add reboot action for Reolink ipcamera
  bundles/org.openhab.binding.ipcamera/README.md
  bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/IpCameraActions.java
  bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/ReolinkHandler.java
  bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/handler/IpCameraHandler.java
Labels: enhancement

#18309 [shelly] Improve smoke sensor wake-up period handling
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/handler/ShellyBaseHandler.java
Labels: enhancement

#17978 [jsscripting] Add example how to hide notifications again
  bundles/org.openhab.automation.jsscripting/README.md
Labels: documentation, awaiting other PR

#18370 [modbus.sunspec] Fix acc32 and uint32
  bundles/org.openhab.binding.modbus.sunspec/src/main/java/org/openhab/binding/modbus/sunspec/internal/parser/AbstractBaseParser.java
Labels: bug

#18372 [smartthings] Correct the link to the compatible devices
  bundles/org.openhab.binding.smartthings/README.md
Labels: documentation

#18347 [squeezebox] Fix properties for manually configured Things
  bundles/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/SqueezeBoxAudioSink.java
  bundles/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/SqueezeBoxBindingConstants.java
  bundles/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/SqueezeBoxHandlerFactory.java
  bundles/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/config/SqueezeBoxPlayerConfig.java
  bundles/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/discovery/SqueezeBoxPlayerDiscoveryService.java
  bundles/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/discovery/SqueezeBoxServerDiscoveryParticipant.java
  bundles/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/handler/SqueezeBoxNotificationListener.java
  bundles/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/handler/SqueezeBoxNotificationPlayer.java
  bundles/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/handler/SqueezeBoxPlayerEventListener.java
  bundles/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/handler/SqueezeBoxPlayerHandler.java
  bundles/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/handler/SqueezeBoxPlayerPlayState.java
  bundles/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/handler/SqueezeBoxPlayerState.java
  bundles/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/handler/SqueezeBoxServerHandler.java
  bundles/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/model/Favorite.java
  bundles/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/utils/HttpUtils.java
  bundles/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/utils/SqueezeBoxCommunicationException.java
  bundles/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/utils/SqueezeBoxNotAuthorizedException.java
  bundles/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/utils/SqueezeBoxTimeoutException.java
  bundles/org.openhab.binding.squeezebox/src/main/resources/OH-INF/i18n/squeezebox.properties
  bundles/org.openhab.binding.squeezebox/src/main/resources/OH-INF/thing/thing-types.xml
Labels: bug

#18375 [fronius] Fix bridge config update not properly handled
  bundles/org.openhab.binding.fronius/src/main/java/org/openhab/binding/fronius/internal/handler/FroniusBaseThingHandler.java
  bundles/org.openhab.binding.fronius/src/main/java/org/openhab/binding/fronius/internal/handler/FroniusBridgeHandler.java
  bundles/org.openhab.binding.fronius/src/main/java/org/openhab/binding/fronius/internal/handler/FroniusSymoInverterHandler.java
Labels: bug

#18349 [unifi] Make request timeout configurable
  bundles/org.openhab.binding.unifi/README.md
  bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/UniFiControllerThingConfig.java
  bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/api/UniFiController.java
  bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/api/UniFiControllerRequest.java
  bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/handler/UniFiControllerThingHandler.java
  bundles/org.openhab.binding.unifi/src/main/resources/OH-INF/config/config.xml
  bundles/org.openhab.binding.unifi/src/main/resources/OH-INF/i18n/unifi.properties
Labels: enhancement

#18335 [unifi] Add network thing
  bundles/org.openhab.binding.unifi/README.md
  bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/UniFiBindingConstants.java
  bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/UniFiNetworkThingConfig.java
  bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/UniFiThingHandlerFactory.java
  bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/api/UniFiController.java
  bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/api/cache/UniFiControllerCache.java
  bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/api/cache/UniFiNetworkCache.java
  bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/api/dto/UniFiClient.java
  bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/api/dto/UniFiNetwork.java
  bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/api/util/UniFiNetworkInstanceCreator.java
  bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/handler/UniFiNetworkThingHandler.java
  bundles/org.openhab.binding.unifi/src/main/java/org/openhab/binding/unifi/internal/handler/UniFiThingDiscoveryService.java
  bundles/org.openhab.binding.unifi/src/main/resources/OH-INF/config/config.xml
  bundles/org.openhab.binding.unifi/src/main/resources/OH-INF/i18n/unifi.properties
  bundles/org.openhab.binding.unifi/src/main/resources/OH-INF/thing/thing-types.xml
Labels: enhancement

#18369 [bambulab] Initial contribution
  CODEOWNERS
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.bambulab/NOTICE
  bundles/org.openhab.binding.bambulab/README.md
  bundles/org.openhab.binding.bambulab/pom.xml
  bundles/org.openhab.binding.bambulab/src/main/feature/feature.xml
  bundles/org.openhab.binding.bambulab/src/main/java/org/openhab/binding/bambulab/internal/BambuLabBindingConstants.java
  bundles/org.openhab.binding.bambulab/src/main/java/org/openhab/binding/bambulab/internal/BambuLabHandlerFactory.java
  bundles/org.openhab.binding.bambulab/src/main/java/org/openhab/binding/bambulab/internal/PrinterActions.java
  bundles/org.openhab.binding.bambulab/src/main/java/org/openhab/binding/bambulab/internal/PrinterConfiguration.java
  bundles/org.openhab.binding.bambulab/src/main/java/org/openhab/binding/bambulab/internal/PrinterHandler.java
  bundles/org.openhab.binding.bambulab/src/main/resources/OH-INF/addon/addon.xml
  bundles/org.openhab.binding.bambulab/src/main/resources/OH-INF/i18n/bambulab.properties
  bundles/org.openhab.binding.bambulab/src/main/resources/OH-INF/thing/channel-types.xml
  bundles/org.openhab.binding.bambulab/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.bambulab/src/test/java/org/openhab/binding/bambulab/internal/PrinterActionsTest.java
  bundles/org.openhab.binding.bambulab/src/test/java/org/openhab/binding/bambulab/internal/PrinterHandlerTest.java
  bundles/org.openhab.binding.pihole/src/main/java/org/openhab/binding/pihole/internal/PiHoleHandler.java
  bundles/pom.xml
Labels: new binding

#18390 [plex] Document the `user` channel
  bundles/org.openhab.binding.plex/README.md
Labels: documentation

#18395 [solarforecast] Bugfix channel typo
  bundles/org.openhab.binding.solarforecast/src/main/resources/OH-INF/update/instructions.xml
Labels: bug, regression

#18394 [jrubyscripting] Disallow Process.exec
  bundles/org.openhab.automation.jrubyscripting/src/main/java/org/openhab/automation/jrubyscripting/internal/JRubyScriptEngineConfiguration.java
Labels: bug

#18399 Replace GH Action from tj-actions by custom code
  .github/workflows/ci-build.yml
Labels: security, infrastructure

#18400 [easee] Fixing incorrect channel name in example
  bundles/org.openhab.binding.easee/README.md
Labels: documentation

#18354 [tado] OAuth RFC-8628 authentication (deadline 2025-03-15)
  bundles/org.openhab.binding.tado/README.md
  bundles/org.openhab.binding.tado/src/main/java/org/openhab/binding/tado/internal/api/HomeApiFactory.java
  bundles/org.openhab.binding.tado/src/main/java/org/openhab/binding/tado/internal/auth/OAuthorizerV2.java
  bundles/org.openhab.binding.tado/src/main/java/org/openhab/binding/tado/internal/config/TadoHomeConfig.java
  bundles/org.openhab.binding.tado/src/main/java/org/openhab/binding/tado/internal/handler/TadoHandlerFactory.java
  bundles/org.openhab.binding.tado/src/main/java/org/openhab/binding/tado/internal/handler/TadoHomeHandler.java
  bundles/org.openhab.binding.tado/src/main/java/org/openhab/binding/tado/internal/servlet/TadoAuthenticationServlet.java
  bundles/org.openhab.binding.tado/src/main/java/org/openhab/binding/tado/swagger/codegen/api/ApiException.java
  bundles/org.openhab.binding.tado/src/main/java/org/openhab/binding/tado/swagger/codegen/api/client/HomeApi.java
  bundles/org.openhab.binding.tado/src/main/resources/OH-INF/i18n/tado.properties
  bundles/org.openhab.binding.tado/src/main/resources/OH-INF/thing/thing-types.xml
Labels: enhancement

#18406 [jsscripting] Upgrade openhab-js to 5.9.0
  bundles/org.openhab.automation.jsscripting/README.md
  bundles/org.openhab.automation.jsscripting/pom.xml
Labels: enhancement

#18420 [tado] fix regression
  bundles/org.openhab.binding.tado/src/main/java/org/openhab/binding/tado/internal/handler/TadoHandlerFactory.java
Labels: bug, regression

#18421 [jsscripting] Upgrade GraalJS to 24.2.0
  bundles/org.openhab.automation.jsscripting/bnd.bnd
  bundles/org.openhab.automation.jsscripting/pom.xml
  bundles/org.openhab.automation.jsscripting/src/main/feature/feature.xml
Labels: enhancement

#18414 [danfossairunit] Use serial number as valid Thing ID in discovery
  bundles/org.openhab.binding.danfossairunit/src/main/java/org/openhab/binding/danfossairunit/internal/DanfossAirUnitBindingConstants.java
  bundles/org.openhab.binding.danfossairunit/src/main/java/org/openhab/binding/danfossairunit/internal/DanfossAirUnitCommunicationController.java
  bundles/org.openhab.binding.danfossairunit/src/main/java/org/openhab/binding/danfossairunit/internal/discovery/DanfossAirUnitDiscoveryService.java
  bundles/org.openhab.binding.danfossairunit/src/main/java/org/openhab/binding/danfossairunit/internal/handler/DanfossAirUnitHandler.java
  bundles/org.openhab.binding.danfossairunit/src/main/resources/OH-INF/thing/thing-types.xml
Labels: enhancement

#18384 [danfossairunit] Improve time zone handling
  bundles/org.openhab.binding.danfossairunit/README.md
  bundles/org.openhab.binding.danfossairunit/src/main/java/org/openhab/binding/danfossairunit/internal/DanfossAirUnit.java
  bundles/org.openhab.binding.danfossairunit/src/main/java/org/openhab/binding/danfossairunit/internal/DanfossAirUnitConfiguration.java
  bundles/org.openhab.binding.danfossairunit/src/main/java/org/openhab/binding/danfossairunit/internal/DanfossAirUnitHandlerFactory.java
  bundles/org.openhab.binding.danfossairunit/src/main/java/org/openhab/binding/danfossairunit/internal/FixedTimeZoneProvider.java
  bundles/org.openhab.binding.danfossairunit/src/main/java/org/openhab/binding/danfossairunit/internal/handler/DanfossAirUnitHandler.java
  bundles/org.openhab.binding.danfossairunit/src/main/resources/OH-INF/i18n/danfossairunit.properties
  bundles/org.openhab.binding.danfossairunit/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.danfossairunit/src/test/java/org/openhab/binding/danfossairunit/internal/DanfossAirUnitTest.java
Labels: enhancement

#18398 [danfossairunit] Add defrost status channel
  bundles/org.openhab.binding.danfossairunit/README.md
  bundles/org.openhab.binding.danfossairunit/src/main/java/org/openhab/binding/danfossairunit/internal/Channel.java
  bundles/org.openhab.binding.danfossairunit/src/main/java/org/openhab/binding/danfossairunit/internal/Commands.java
  bundles/org.openhab.binding.danfossairunit/src/main/java/org/openhab/binding/danfossairunit/internal/DanfossAirUnit.java
  bundles/org.openhab.binding.danfossairunit/src/main/resources/OH-INF/i18n/danfossairunit.properties
  bundles/org.openhab.binding.danfossairunit/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.danfossairunit/src/main/resources/OH-INF/update/instructions.xml
Labels: enhancement

#14119 [tacmi] Support JSON-Api
  bundles/org.openhab.binding.tacmi/README.md
  bundles/org.openhab.binding.tacmi/src/main/java/org/openhab/binding/tacmi/internal/TACmiBindingConstants.java
  bundles/org.openhab.binding.tacmi/src/main/java/org/openhab/binding/tacmi/internal/TACmiHandlerFactory.java
  bundles/org.openhab.binding.tacmi/src/main/java/org/openhab/binding/tacmi/internal/json/Config.java
  bundles/org.openhab.binding.tacmi/src/main/java/org/openhab/binding/tacmi/internal/json/TACmiJsonHandler.java
  bundles/org.openhab.binding.tacmi/src/main/java/org/openhab/binding/tacmi/internal/json/obj/Data.java
  bundles/org.openhab.binding.tacmi/src/main/java/org/openhab/binding/tacmi/internal/json/obj/Header.java
  bundles/org.openhab.binding.tacmi/src/main/java/org/openhab/binding/tacmi/internal/json/obj/IO.java
  bundles/org.openhab.binding.tacmi/src/main/java/org/openhab/binding/tacmi/internal/json/obj/JsonResponse.java
  bundles/org.openhab.binding.tacmi/src/main/java/org/openhab/binding/tacmi/internal/json/obj/Value.java
  bundles/org.openhab.binding.tacmi/src/main/resources/OH-INF/i18n/tacmi.properties
  bundles/org.openhab.binding.tacmi/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.tacmi/src/test/java/org/openhab/binding/tacmi/internal/json/obj/test/DeSer.java
  bundles/org.openhab.binding.tacmi/src/test/resources/ex.json
Labels: enhancement

#18389 [vizio] Add semantic tag to Active App channel
  bundles/org.openhab.binding.vizio/src/main/resources/OH-INF/thing/vizio.xml
  bundles/org.openhab.binding.vizio/src/main/resources/OH-INF/update/update.xml
  bundles/org.openhab.binding.vizio/src/main/resources/db/apps.json
Labels: enhancement

#18314 [lgwebos] Add semantic tag to Channel and Application channels
  bundles/org.openhab.binding.lgwebos/src/main/resources/OH-INF/i18n/lgwebos.properties
  bundles/org.openhab.binding.lgwebos/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.lgwebos/src/main/resources/OH-INF/update/update.xml
Labels: enhancement, awaiting other PR

#18388 [tivo] Add semantic tag to channelSet and channelForce channels
  bundles/org.openhab.binding.tivo/README.md
  bundles/org.openhab.binding.tivo/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.tivo/src/main/resources/OH-INF/update/update.xml
Labels: enhancement

#18387 [roku] Add semantic tag to Active App and Active Channel channels
  bundles/org.openhab.binding.roku/src/main/resources/OH-INF/thing/roku.xml
  bundles/org.openhab.binding.roku/src/main/resources/OH-INF/update/update.xml
Labels: enhancement

#18419 [somfytahoma] Fix exception when invalid event history response received
  bundles/org.openhab.binding.jablotron/src/main/java/org/openhab/binding/jablotron/internal/handler/JablotronBridgeHandler.java
Labels: bug

#18315 [daikin] Add semantic tags to channels
  bundles/org.openhab.binding.daikin/src/main/resources/OH-INF/i18n/daikin.properties
  bundles/org.openhab.binding.daikin/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.daikin/src/main/resources/OH-INF/update/update.xml
Labels: enhancement

#18324 [danfossairunit] Add semantic tags
  bundles/org.openhab.binding.danfossairunit/src/main/resources/OH-INF/i18n/danfossairunit.properties
  bundles/org.openhab.binding.danfossairunit/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.danfossairunit/src/main/resources/OH-INF/update/instructions.xml
Labels: enhancement

#18415 [wundergroundupdatereceiver] Fix parsing of dateutc query parameter
  bundles/org.openhab.binding.wundergroundupdatereceiver/src/main/java/org/openhab/binding/wundergroundupdatereceiver/internal/WundergroundUpdateReceiverHandler.java
  bundles/org.openhab.binding.wundergroundupdatereceiver/src/test/java/org/openhab/binding/wundergroundupdatereceiver/internal/WundergroundUpdateReceiverDiscoveryServiceTest.java
  bundles/org.openhab.binding.wundergroundupdatereceiver/src/test/java/org/openhab/binding/wundergroundupdatereceiver/internal/WundergroundUpdateReceiverServletTest.java
Labels: bug

#18413 [jrubyscripting] Update README.md
  bundles/org.openhab.automation.jrubyscripting/README.md
Labels: documentation

#18444 [satel] Discovery fix for roller shutter things, other minor changes
  bundles/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/discovery/SatelDeviceDiscoveryService.java
  bundles/org.openhab.binding.satel/src/test/java/org/openhab/binding/satel/internal/discovery/SatelDeviceDiscoveryServiceTest.java
  bundles/org.openhab.binding.satel/src/test/java/org/openhab/binding/satel/internal/handler/SatelEventLogHandlerTest.java
Labels: bug

#18447 [omnilink] Update system time channel after setting time
  bundles/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/internal/handler/OmnilinkBridgeHandler.java
Labels: bug

#18397 [jrubyscripting] Add "dummy" openHAB gem to environment
  bundles/org.openhab.automation.jrubyscripting/src/main/java/org/openhab/automation/jrubyscripting/internal/JRubyScriptEngineConfiguration.java
Labels: enhancement

#18451 Improve GitHub Actions
  .github/workflows/ci-build.yml
Labels: infrastructure

#18436 [jablotron] fix improper JSON response parsing
  bundles/org.openhab.binding.jablotron/src/main/java/org/openhab/binding/jablotron/internal/handler/JablotronBridgeHandler.java
Labels: bug

#18374 [jrubyscripting] Add JRuby REPL and other utilities inside karaf console
  bundles/org.openhab.automation.jrubyscripting/pom.xml
  bundles/org.openhab.automation.jrubyscripting/src/main/java/org/openhab/automation/jrubyscripting/internal/JRubyConsoleCommandExtension.java
  bundles/org.openhab.automation.jrubyscripting/src/main/java/org/openhab/automation/jrubyscripting/internal/JRubyScriptEngineConfiguration.java
  bundles/org.openhab.automation.jrubyscripting/src/main/java/org/openhab/automation/jrubyscripting/internal/JRubyScriptEngineFactory.java
  bundles/org.openhab.automation.jrubyscripting/src/main/java/org/openhab/automation/jrubyscripting/internal/watch/JRubyDependencyTracker.java
  bundles/org.openhab.automation.jrubyscripting/src/main/java/org/openhab/automation/jrubyscripting/internal/watch/JRubyScriptFileWatcher.java
  bundles/org.openhab.automation.jrubyscripting/src/main/resources/OH-INF/config/config.xml
  bundles/org.openhab.automation.jrubyscripting/src/main/resources/OH-INF/i18n/jrubyscripting.properties
Labels: enhancement

#14578 [pushsafer] Add latest parameter answeroptions and answerforce
  bundles/org.openhab.binding.pushsafer/README.md
  bundles/org.openhab.binding.pushsafer/src/main/java/org/openhab/binding/pushsafer/internal/PushsaferBindingConstants.java
  bundles/org.openhab.binding.pushsafer/src/main/java/org/openhab/binding/pushsafer/internal/config/PushsaferAccountConfiguration.java
  bundles/org.openhab.binding.pushsafer/src/main/java/org/openhab/binding/pushsafer/internal/connection/PushsaferMessageBuilder.java
  bundles/org.openhab.binding.pushsafer/src/main/java/org/openhab/binding/pushsafer/internal/handler/PushsaferAccountHandler.java
  bundles/org.openhab.binding.pushsafer/src/main/resources/OH-INF/config/config.xml
  bundles/org.openhab.binding.pushsafer/src/main/resources/OH-INF/i18n/pushsafer.properties
  bundles/org.openhab.binding.pushsafer/src/main/resources/OH-INF/i18n/pushsafer_de.properties
Labels: enhancement, i18n

#18437 [emotiva] Tag group handler and bugfixes.
  bundles/org.openhab.binding.emotiva/README.md
  bundles/org.openhab.binding.emotiva/src/main/java/org/openhab/binding/emotiva/internal/EmotivaBindingConstants.java
  bundles/org.openhab.binding.emotiva/src/main/java/org/openhab/binding/emotiva/internal/EmotivaConfiguration.java
  bundles/org.openhab.binding.emotiva/src/main/java/org/openhab/binding/emotiva/internal/EmotivaInputStateOptionProvider.java
  bundles/org.openhab.binding.emotiva/src/main/java/org/openhab/binding/emotiva/internal/EmotivaProcessorHandler.java
  bundles/org.openhab.binding.emotiva/src/main/java/org/openhab/binding/emotiva/internal/EmotivaProcessorState.java
  bundles/org.openhab.binding.emotiva/src/main/java/org/openhab/binding/emotiva/internal/EmotivaSubscriptionTagGroupHandler.java
  bundles/org.openhab.binding.emotiva/src/main/java/org/openhab/binding/emotiva/internal/protocol/EmotivaControlCommands.java
  bundles/org.openhab.binding.emotiva/src/main/java/org/openhab/binding/emotiva/internal/protocol/EmotivaControlRequest.java
  bundles/org.openhab.binding.emotiva/src/main/java/org/openhab/binding/emotiva/internal/protocol/EmotivaSubscriptionTagGroup.java
  bundles/org.openhab.binding.emotiva/src/main/java/org/openhab/binding/emotiva/internal/protocol/EmotivaSubscriptionTags.java
  bundles/org.openhab.binding.emotiva/src/main/resources/OH-INF/config/config.xml
  bundles/org.openhab.binding.emotiva/src/main/resources/OH-INF/i18n/emotiva.properties
  bundles/org.openhab.binding.emotiva/src/test/java/org/openhab/binding/emotiva/internal/EmotivaInputStateOptionProviderTest.java
  bundles/org.openhab.binding.emotiva/src/test/java/org/openhab/binding/emotiva/internal/EmotivaSubscriptionTagGroupHandlerTest.java
  bundles/org.openhab.binding.emotiva/src/test/java/org/openhab/binding/emotiva/internal/protocol/AbstractEmotivaControlTest.java
  bundles/org.openhab.binding.emotiva/src/test/java/org/openhab/binding/emotiva/internal/protocol/EmotivaControlCommandsTest.java
  bundles/org.openhab.binding.emotiva/src/test/java/org/openhab/binding/emotiva/internal/protocol/EmotivaControlRequestTest.java
Labels: bug

#18464 [insteon] Fix scene channels not responding after modem db reload
  bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/handler/InsteonBaseThingHandler.java
  bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/handler/InsteonSceneHandler.java
Labels: bug

#18465 [insteon] Improve modem db default controller group support
  bundles/org.openhab.binding.insteon/README.md
  bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/device/InsteonScene.java
  bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/device/LinkManager.java
  bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/device/database/LinkDB.java
  bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/device/database/ModemDB.java
  bundles/org.openhab.binding.insteon/src/main/resources/OH-INF/thing/scene.xml
Labels: enhancement

#18454 [danfossairunit] Ensure immediate channel update after item linking
  bundles/org.openhab.binding.danfossairunit/src/main/java/org/openhab/binding/danfossairunit/internal/handler/DanfossAirUnitHandler.java
Labels: bug

#18472 [jdbc] Upgrade Yank to 3.5.0
  bundles/org.openhab.persistence.jdbc/pom.xml
  bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/JdbcPersistenceService.java
  bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/db/JdbcBaseDAO.java
Labels: enhancement
