Repository openhab/openhab-addons, pull requests merged in 2025-09, with the labels that each got.

#19274 Resolve after jmdns upgrade
  itests/org.openhab.binding.hue.tests/itest.bndrun
  itests/org.openhab.binding.tradfri.tests/itest.bndrun
Labels: awaiting other PR

#19122 [openaitts] Add new voices, model and configuration
  bundles/org.openhab.voice.openaitts/src/main/java/org/openhab/voice/openaitts/internal/OpenAITTSConfiguration.java
  bundles/org.openhab.voice.openaitts/src/main/java/org/openhab/voice/openaitts/internal/OpenAITTSService.java
  bundles/org.openhab.voice.openaitts/src/main/resources/OH-INF/config/config.xml
  bundles/org.openhab.voice.openaitts/src/main/resources/OH-INF/i18n/openaitts.properties
Labels: enhancement

#19194 [tibber] Add energy price and taxes
  bundles/org.openhab.binding.tibber/README.md
  bundles/org.openhab.binding.tibber/src/main/java/org/openhab/binding/tibber/internal/TibberBindingConstants.java
  bundles/org.openhab.binding.tibber/src/main/java/org/openhab/binding/tibber/internal/handler/TibberHandler.java
  bundles/org.openhab.binding.tibber/src/main/resources/OH-INF/i18n/tibber.properties
  bundles/org.openhab.binding.tibber/src/main/resources/OH-INF/thing/channel-types.xml
  bundles/org.openhab.binding.tibber/src/main/resources/OH-INF/thing/price-group.xml
  bundles/org.openhab.binding.tibber/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.tibber/src/main/resources/OH-INF/update/instructions.xml
  bundles/org.openhab.binding.tibber/src/main/resources/graphql/prices.graphql
  bundles/org.openhab.binding.tibber/src/test/java/org/openhab/binding/tibber/internal/TestActions.java
  bundles/org.openhab.binding.tibber/src/test/java/org/openhab/binding/tibber/internal/TestPriceCalculator.java
  bundles/org.openhab.binding.tibber/src/test/resources/price-query-response.json
Labels: enhancement

#19172 [jdbc] Update dependencies
  bundles/org.openhab.persistence.jdbc/README.md
  bundles/org.openhab.persistence.jdbc/pom.xml
  bundles/org.openhab.persistence.jdbc/src/main/feature/feature.xml
  bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/JdbcConfiguration.java
Labels: enhancement

#19095 [ipcamera] Fix Reolink needs changes to JSON formatting to work in newer firmwares
  bundles/org.openhab.binding.ipcamera/src/main/java/org/openhab/binding/ipcamera/internal/ReolinkHandler.java
Labels: bug

#19284 [homematic] Adjust warning if current value is out of range
  bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/communicator/parser/CcuParamsetDescriptionParser.java
  bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/communicator/parser/CommonRpcParser.java
  bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/communicator/parser/GetParamsetDescriptionParser.java
  bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/handler/HomematicThingHandler.java
  bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/model/HmDatapoint.java
Labels: bug

#19272 [mercedesme] Bugfix charge program selection
  bundles/org.openhab.binding.mercedesme/src/main/java/org/openhab/binding/mercedesme/internal/handler/VehicleHandler.java
Labels: bug

#17972 [network] Fix discovery performance causing a slow openHAB start
  bundles/org.openhab.binding.network/README.md
  bundles/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/NetworkBindingConfiguration.java
  bundles/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/NetworkBindingConstants.java
  bundles/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/NetworkHandlerFactory.java
  bundles/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/PresenceDetection.java
  bundles/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/PresenceDetectionValue.java
  bundles/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/WakeOnLanPacketSender.java
  bundles/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/discovery/NetworkDiscoveryService.java
  bundles/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/handler/NetworkHandler.java
  bundles/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/handler/SpeedTestHandler.java
  bundles/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/utils/LatencyParser.java
  bundles/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/utils/NetworkUtils.java
  bundles/org.openhab.binding.network/src/main/resources/OH-INF/addon/addon.xml
  bundles/org.openhab.binding.network/src/main/resources/OH-INF/i18n/network.properties
  bundles/org.openhab.binding.network/src/test/java/org/openhab/binding/network/internal/PresenceDetectionTest.java
  bundles/org.openhab.binding.network/src/test/java/org/openhab/binding/network/internal/discovery/DiscoveryTest.java
  bundles/org.openhab.binding.network/src/test/java/org/openhab/binding/network/internal/handler/NetworkHandlerTest.java
  bundles/org.openhab.binding.network/src/test/java/org/openhab/binding/network/internal/utils/LatencyParserTest.java
Labels: bug

#16205 [serial] Add TCP and binary protocol support
  bundles/org.openhab.binding.serial/README.md
  bundles/org.openhab.binding.serial/src/main/java/org/openhab/binding/serial/internal/SerialBindingConstants.java
  bundles/org.openhab.binding.serial/src/main/java/org/openhab/binding/serial/internal/SerialHandlerFactory.java
  bundles/org.openhab.binding.serial/src/main/java/org/openhab/binding/serial/internal/channel/ChannelConfig.java
  bundles/org.openhab.binding.serial/src/main/java/org/openhab/binding/serial/internal/channel/DeviceChannel.java
  bundles/org.openhab.binding.serial/src/main/java/org/openhab/binding/serial/internal/channel/DeviceChannelFactory.java
  bundles/org.openhab.binding.serial/src/main/java/org/openhab/binding/serial/internal/handler/CommonBridgeConfiguration.java
  bundles/org.openhab.binding.serial/src/main/java/org/openhab/binding/serial/internal/handler/CommonBridgeHandler.java
  bundles/org.openhab.binding.serial/src/main/java/org/openhab/binding/serial/internal/handler/SerialBridgeConfiguration.java
  bundles/org.openhab.binding.serial/src/main/java/org/openhab/binding/serial/internal/handler/SerialBridgeHandler.java
  bundles/org.openhab.binding.serial/src/main/java/org/openhab/binding/serial/internal/handler/SerialDeviceHandler.java
  bundles/org.openhab.binding.serial/src/main/java/org/openhab/binding/serial/internal/handler/TcpBridgeConfiguration.java
  bundles/org.openhab.binding.serial/src/main/java/org/openhab/binding/serial/internal/handler/TcpBridgeHandler.java
  bundles/org.openhab.binding.serial/src/main/java/org/openhab/binding/serial/internal/handler/TcpServerBridgeConfiguration.java
  bundles/org.openhab.binding.serial/src/main/java/org/openhab/binding/serial/internal/handler/TcpServerBridgeHandler.java
  bundles/org.openhab.binding.serial/src/main/resources/OH-INF/addon/addon.xml
  bundles/org.openhab.binding.serial/src/main/resources/OH-INF/i18n/serial.properties
  bundles/org.openhab.binding.serial/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.serial/src/test/java/org/openhab/binding/serial/internal/ByteBufferInputStream.java
  bundles/org.openhab.binding.serial/src/test/java/org/openhab/binding/serial/internal/MockupBridgeHandler.java
  bundles/org.openhab.binding.serial/src/test/java/org/openhab/binding/serial/internal/SerialBindingHandlerTest.java
Labels: enhancement

#19296 Extend dependabot: ftpupload
  .github/dependabot.yml
Labels: infrastructure, dependencies

#19289 [linky] Fix new url schema for getMeasures() related to September Enedis changes to WebAPI
  bundles/org.openhab.binding.linky/src/main/java/org/openhab/binding/linky/internal/api/EnedisHttpApi.java
  bundles/org.openhab.binding.linky/src/main/java/org/openhab/binding/linky/internal/handler/BridgeRemoteEnedisWebHandler.java
  bundles/org.openhab.binding.linky/src/main/java/org/openhab/binding/linky/internal/handler/ThingLinkyRemoteHandler.java
Labels: bug

#19325 [zwavejs] Add unit conversion
  bundles/org.openhab.binding.zwavejs/src/main/java/org/openhab/binding/zwavejs/internal/conversion/BaseMetadata.java
Labels: bug

#19330 [knx] Fix test warning
  bundles/org.openhab.binding.knx/src/test/java/org/openhab/binding/knx/internal/itests/Back2BackTest.java
Labels: test

#19242 [shelly] Improve Shelly Manager for offline devices
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/manager/ShellyManagerOverviewPage.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/manager/ShellyManagerPage.java
Labels: enhancement

#19191 [zwavejs] Add RollerShutter support
  bundles/org.openhab.binding.zwavejs/README.md
  bundles/org.openhab.binding.zwavejs/pom.xml
  bundles/org.openhab.binding.zwavejs/src/main/java/org/openhab/binding/zwavejs/internal/BindingConstants.java
  bundles/org.openhab.binding.zwavejs/src/main/java/org/openhab/binding/zwavejs/internal/config/ZwaveJSChannelConfiguration.java
  bundles/org.openhab.binding.zwavejs/src/main/java/org/openhab/binding/zwavejs/internal/conversion/BaseMetadata.java
  bundles/org.openhab.binding.zwavejs/src/main/java/org/openhab/binding/zwavejs/internal/conversion/ChannelMetadata.java
  bundles/org.openhab.binding.zwavejs/src/main/java/org/openhab/binding/zwavejs/internal/handler/ZwaveJSBridgeHandler.java
  bundles/org.openhab.binding.zwavejs/src/main/java/org/openhab/binding/zwavejs/internal/handler/ZwaveJSNodeHandler.java
  bundles/org.openhab.binding.zwavejs/src/main/java/org/openhab/binding/zwavejs/internal/type/ZwaveJSTypeGeneratorImpl.java
  bundles/org.openhab.binding.zwavejs/src/main/java/org/openhab/binding/zwavejs/internal/type/ZwaveJSTypeGeneratorResult.java
  bundles/org.openhab.binding.zwavejs/src/main/java/org/openhab/binding/zwavejs/internal/type/capabilities/ColorCapability.java
  bundles/org.openhab.binding.zwavejs/src/main/java/org/openhab/binding/zwavejs/internal/type/capabilities/RollerShutterCapability.java
  bundles/org.openhab.binding.zwavejs/src/main/resources/OH-INF/config/channel-config.xml
  bundles/org.openhab.binding.zwavejs/src/main/resources/OH-INF/i18n/zwavejs.properties
  bundles/org.openhab.binding.zwavejs/src/test/java/org/openhab/binding/zwavejs/internal/handler/ZwaveJSBridgeHandlerTest.java
  bundles/org.openhab.binding.zwavejs/src/test/java/org/openhab/binding/zwavejs/internal/handler/ZwaveJSNodeHandlerRollerShutterStateTest.java
  bundles/org.openhab.binding.zwavejs/src/test/java/org/openhab/binding/zwavejs/internal/handler/ZwaveJSNodeHandlerTest.java
  bundles/org.openhab.binding.zwavejs/src/test/java/org/openhab/binding/zwavejs/internal/handler/mock/ZwaveJSBridgeHandlerMock.java
  bundles/org.openhab.binding.zwavejs/src/test/java/org/openhab/binding/zwavejs/internal/handler/mock/ZwaveJSNodeHandlerMock.java
  bundles/org.openhab.binding.zwavejs/src/test/java/org/openhab/binding/zwavejs/internal/type/ZwaveJSTypeGeneratorTest.java
  bundles/org.openhab.binding.zwavejs/src/test/java/org/openhab/binding/zwavejs/internal/type/capabilities/RollerShutterCapabilityTest.java
  bundles/org.openhab.binding.zwavejs/src/test/resources/json/event_node_60_dimmer.json
  bundles/org.openhab.binding.zwavejs/src/test/resources/json/event_node_60_refresh.json
  bundles/org.openhab.binding.zwavejs/src/test/resources/json/event_node_60_switch_down.json
  bundles/org.openhab.binding.zwavejs/src/test/resources/json/event_node_60_switch_up.json
  bundles/org.openhab.binding.zwavejs/src/test/resources/json/store_4.json
Labels: enhancement

#19344 [fronius] Fix config API authentication for firmware >= 1.38.6
  bundles/org.openhab.binding.fronius/src/main/java/org/openhab/binding/fronius/internal/api/FroniusBatteryControl.java
  bundles/org.openhab.binding.fronius/src/main/java/org/openhab/binding/fronius/internal/api/FroniusConfigAuthUtil.java
  bundles/org.openhab.binding.fronius/src/main/java/org/openhab/binding/fronius/internal/handler/FroniusSymoInverterHandler.java
Labels: bug

#19326 [boschshc] Add support for presence simulation
  bundles/org.openhab.binding.boschshc/README.md
  bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/console/BoschShcCommandExtension.java
  bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/devices/BoschSHCBindingConstants.java
  bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/devices/BoschSHCHandler.java
  bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/devices/BoschSHCHandlerFactory.java
  bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/devices/presence/PresenceSimulationHandler.java
  bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/discovery/ThingDiscoveryService.java
  bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/services/presence/PresenceSimulationConfigurationService.java
  bundles/org.openhab.binding.boschshc/src/main/java/org/openhab/binding/boschshc/internal/services/presence/dto/PresenceSimulationConfigurationServiceState.java
  bundles/org.openhab.binding.boschshc/src/main/resources/OH-INF/i18n/boschshc.properties
  bundles/org.openhab.binding.boschshc/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.boschshc/src/test/java/org/openhab/binding/boschshc/internal/devices/presence/PresenceSimulationHandlerTest.java
Labels: enhancement

#19310 [astro] Various refactoring/fixes
  bundles/org.openhab.binding.astro/src/main/java/org/openhab/binding/astro/internal/AstroHandlerFactory.java
  bundles/org.openhab.binding.astro/src/main/java/org/openhab/binding/astro/internal/action/AstroActions.java
  bundles/org.openhab.binding.astro/src/main/java/org/openhab/binding/astro/internal/calc/MoonCalc.java
  bundles/org.openhab.binding.astro/src/main/java/org/openhab/binding/astro/internal/calc/SeasonCalc.java
  bundles/org.openhab.binding.astro/src/main/java/org/openhab/binding/astro/internal/calc/SunCalc.java
  bundles/org.openhab.binding.astro/src/main/java/org/openhab/binding/astro/internal/calc/SunZodiacCalc.java
  bundles/org.openhab.binding.astro/src/main/java/org/openhab/binding/astro/internal/discovery/AstroDiscoveryService.java
  bundles/org.openhab.binding.astro/src/main/java/org/openhab/binding/astro/internal/handler/AstroThingHandler.java
  bundles/org.openhab.binding.astro/src/main/java/org/openhab/binding/astro/internal/handler/MoonHandler.java
  bundles/org.openhab.binding.astro/src/main/java/org/openhab/binding/astro/internal/handler/SunHandler.java
  bundles/org.openhab.binding.astro/src/main/java/org/openhab/binding/astro/internal/job/AbstractJob.java
  bundles/org.openhab.binding.astro/src/main/java/org/openhab/binding/astro/internal/job/CompositeJob.java
  bundles/org.openhab.binding.astro/src/main/java/org/openhab/binding/astro/internal/job/DailyJobMoon.java
  bundles/org.openhab.binding.astro/src/main/java/org/openhab/binding/astro/internal/job/DailyJobSun.java
  bundles/org.openhab.binding.astro/src/main/java/org/openhab/binding/astro/internal/job/EventJob.java
  bundles/org.openhab.binding.astro/src/main/java/org/openhab/binding/astro/internal/job/Job.java
  bundles/org.openhab.binding.astro/src/main/java/org/openhab/binding/astro/internal/job/PositionalJob.java
  bundles/org.openhab.binding.astro/src/main/java/org/openhab/binding/astro/internal/job/PublishPlanetJob.java
  bundles/org.openhab.binding.astro/src/main/java/org/openhab/binding/astro/internal/job/SunPhaseJob.java
  bundles/org.openhab.binding.astro/src/main/java/org/openhab/binding/astro/internal/model/Moon.java
  bundles/org.openhab.binding.astro/src/main/java/org/openhab/binding/astro/internal/model/MoonDistance.java
  bundles/org.openhab.binding.astro/src/main/java/org/openhab/binding/astro/internal/model/MoonPhase.java
  bundles/org.openhab.binding.astro/src/main/java/org/openhab/binding/astro/internal/model/MoonPhaseName.java
  bundles/org.openhab.binding.astro/src/main/java/org/openhab/binding/astro/internal/model/Planet.java
  bundles/org.openhab.binding.astro/src/main/java/org/openhab/binding/astro/internal/model/Radiation.java
  bundles/org.openhab.binding.astro/src/main/java/org/openhab/binding/astro/internal/model/Range.java
  bundles/org.openhab.binding.astro/src/main/java/org/openhab/binding/astro/internal/model/Season.java
  bundles/org.openhab.binding.astro/src/main/java/org/openhab/binding/astro/internal/model/SeasonName.java
  bundles/org.openhab.binding.astro/src/main/java/org/openhab/binding/astro/internal/model/Sun.java
  bundles/org.openhab.binding.astro/src/main/java/org/openhab/binding/astro/internal/model/SunPhase.java
  bundles/org.openhab.binding.astro/src/main/java/org/openhab/binding/astro/internal/model/SunZodiac.java
  bundles/org.openhab.binding.astro/src/main/java/org/openhab/binding/astro/internal/model/Zodiac.java
  bundles/org.openhab.binding.astro/src/main/java/org/openhab/binding/astro/internal/util/DateTimeUtils.java
  bundles/org.openhab.binding.astro/src/main/java/org/openhab/binding/astro/internal/util/PropertyUtils.java
  bundles/org.openhab.binding.astro/src/test/java/org/openhab/binding/astro/internal/calc/MoonCalcTest.java
  bundles/org.openhab.binding.astro/src/test/java/org/openhab/binding/astro/internal/calc/SunCalcTest.java
  bundles/org.openhab.binding.astro/src/test/java/org/openhab/binding/astro/internal/job/JobTest.java
  bundles/org.openhab.binding.astro/src/test/java/org/openhab/binding/astro/internal/model/SunTest.java
  bundles/org.openhab.binding.astro/src/test/java/org/openhab/binding/astro/internal/util/DateTimeUtilsTest.java
  itests/org.openhab.binding.astro.tests/src/main/java/org/openhab/binding/astro/handler/test/AstroCommandTest.java
  itests/org.openhab.binding.astro.tests/src/main/java/org/openhab/binding/astro/handler/test/AstroValidConfigurationTest.java
  itests/org.openhab.binding.astro.tests/src/main/java/org/openhab/binding/astro/test/AstroStateTest.java
Labels: test

#19328 [zwavejs] Add notification channel
  bundles/org.openhab.binding.zwavejs/README.md
  bundles/org.openhab.binding.zwavejs/src/main/java/org/openhab/binding/zwavejs/internal/BindingConstants.java
  bundles/org.openhab.binding.zwavejs/src/main/java/org/openhab/binding/zwavejs/internal/api/ZWaveJSClient.java
  bundles/org.openhab.binding.zwavejs/src/main/java/org/openhab/binding/zwavejs/internal/api/dto/Args.java
  bundles/org.openhab.binding.zwavejs/src/main/java/org/openhab/binding/zwavejs/internal/api/dto/Event.java
  bundles/org.openhab.binding.zwavejs/src/main/java/org/openhab/binding/zwavejs/internal/conversion/BaseMetadata.java
  bundles/org.openhab.binding.zwavejs/src/main/java/org/openhab/binding/zwavejs/internal/handler/ZwaveJSBridgeHandler.java
  bundles/org.openhab.binding.zwavejs/src/main/java/org/openhab/binding/zwavejs/internal/type/ZwaveJSTypeGeneratorImpl.java
  bundles/org.openhab.binding.zwavejs/src/test/java/org/openhab/binding/zwavejs/internal/handler/ZwaveJSBridgeHandlerTest.java
  bundles/org.openhab.binding.zwavejs/src/test/java/org/openhab/binding/zwavejs/internal/handler/ZwaveJSNodeHandlerTest.java
  bundles/org.openhab.binding.zwavejs/src/test/java/org/openhab/binding/zwavejs/internal/type/ZwaveJSTypeGeneratorTest.java
  bundles/org.openhab.binding.zwavejs/src/test/resources/json/event_node_186_notification.json
Labels: enhancement

#19361 [opengarage] Fix warnings, use gson to parse json to simplify code
  bundles/org.openhab.binding.opengarage/src/main/java/org/openhab/binding/opengarage/internal/OpenGarageCommunicationException.java
  bundles/org.openhab.binding.opengarage/src/main/java/org/openhab/binding/opengarage/internal/OpenGarageHandler.java
  bundles/org.openhab.binding.opengarage/src/main/java/org/openhab/binding/opengarage/internal/OpenGarageWebTargets.java
  bundles/org.openhab.binding.opengarage/src/main/java/org/openhab/binding/opengarage/internal/api/ControllerVariables.java
  bundles/org.openhab.binding.opengarage/src/main/java/org/openhab/binding/opengarage/internal/api/Enums.java
Labels: enhancement

#19117 [roborock] Initial contribution
  CODEOWNERS
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.roborock/NOTICE
  bundles/org.openhab.binding.roborock/README.md
  bundles/org.openhab.binding.roborock/pom.xml
  bundles/org.openhab.binding.roborock/src/main/feature/feature.xml
  bundles/org.openhab.binding.roborock/src/main/java/org/openhab/binding/roborock/internal/RoborockAccountConfiguration.java
  bundles/org.openhab.binding.roborock/src/main/java/org/openhab/binding/roborock/internal/RoborockAccountHandler.java
  bundles/org.openhab.binding.roborock/src/main/java/org/openhab/binding/roborock/internal/RoborockBindingConstants.java
  bundles/org.openhab.binding.roborock/src/main/java/org/openhab/binding/roborock/internal/RoborockException.java
  bundles/org.openhab.binding.roborock/src/main/java/org/openhab/binding/roborock/internal/RoborockHandlerFactory.java
  bundles/org.openhab.binding.roborock/src/main/java/org/openhab/binding/roborock/internal/RoborockVacuumConfiguration.java
  bundles/org.openhab.binding.roborock/src/main/java/org/openhab/binding/roborock/internal/RoborockVacuumHandler.java
  bundles/org.openhab.binding.roborock/src/main/java/org/openhab/binding/roborock/internal/RoborockWebTargets.java
  bundles/org.openhab.binding.roborock/src/main/java/org/openhab/binding/roborock/internal/api/dto/GetCleanRecord.java
  bundles/org.openhab.binding.roborock/src/main/java/org/openhab/binding/roborock/internal/api/dto/GetConsumables.java
  bundles/org.openhab.binding.roborock/src/main/java/org/openhab/binding/roborock/internal/api/dto/GetDndTimer.java
  bundles/org.openhab.binding.roborock/src/main/java/org/openhab/binding/roborock/internal/api/dto/GetNetworkInfo.java
  bundles/org.openhab.binding.roborock/src/main/java/org/openhab/binding/roborock/internal/api/dto/GetStatus.java
  bundles/org.openhab.binding.roborock/src/main/java/org/openhab/binding/roborock/internal/api/dto/Home.java
  bundles/org.openhab.binding.roborock/src/main/java/org/openhab/binding/roborock/internal/api/dto/HomeData.java
  bundles/org.openhab.binding.roborock/src/main/java/org/openhab/binding/roborock/internal/api/dto/Login.java
  bundles/org.openhab.binding.roborock/src/main/java/org/openhab/binding/roborock/internal/api/enums/ConsumablesType.java
  bundles/org.openhab.binding.roborock/src/main/java/org/openhab/binding/roborock/internal/api/enums/FanModeType.java
  bundles/org.openhab.binding.roborock/src/main/java/org/openhab/binding/roborock/internal/api/enums/RobotCapabilities.java
  bundles/org.openhab.binding.roborock/src/main/java/org/openhab/binding/roborock/internal/api/enums/StatusType.java
  bundles/org.openhab.binding.roborock/src/main/java/org/openhab/binding/roborock/internal/api/enums/VacuumErrorType.java
  bundles/org.openhab.binding.roborock/src/main/java/org/openhab/binding/roborock/internal/discovery/RoborockVacuumDiscoveryService.java
  bundles/org.openhab.binding.roborock/src/main/java/org/openhab/binding/roborock/internal/util/ProtocolUtils.java
  bundles/org.openhab.binding.roborock/src/main/java/org/openhab/binding/roborock/internal/util/SchedulerTask.java
  bundles/org.openhab.binding.roborock/src/main/resources/OH-INF/addon/addon.xml
  bundles/org.openhab.binding.roborock/src/main/resources/OH-INF/i18n/roborock.properties
  bundles/org.openhab.binding.roborock/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/pom.xml
Labels: new binding

#19365 Fix tests when having spaces in path
  pom.xml
Labels: regression
