Repository openhab/openhab-addons, pull requests merged in 2025-01, with the labels that each got.

#18004 [knx] Allow color temperatures specified in mired
  bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/dpt/ValueEncoder.java
  bundles/org.openhab.binding.knx/src/test/java/org/openhab/binding/knx/internal/dpt/DPTTest.java
Labels: enhancement

#18014 [mqtt.homeassistant] Fix build
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/AbstractComponent.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/component/ClimateTests.java
Labels: regression

#18021 [mqtt.homeassistant] Re-fix null component name
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/AbstractComponent.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/component/SwitchTests.java
Labels: bug, regression

#18024 [energidataservice] Improve rule example for calculating totals
  bundles/org.openhab.binding.energidataservice/README.md
Labels: documentation

#17950 [ahawastecollection] Add support for Christmas Tree collection
  bundles/org.openhab.binding.ahawastecollection/src/main/java/org/openhab/binding/ahawastecollection/internal/CollectionDate.java
Labels: bug

#18034 [enocean] Fix `NullPointerException`
  bundles/org.openhab.binding.enocean/src/main/java/org/openhab/binding/enocean/internal/handler/EnOceanBaseSensorHandler.java
Labels: bug

#18016 [solarman] Fix issue openhab/openhab-addons#17959 where new channels could not be added in the Web UI
  bundles/org.openhab.binding.solarman/src/main/java/org/openhab/binding/solarman/internal/SolarmanLoggerMode.java
  bundles/org.openhab.binding.solarman/src/main/java/org/openhab/binding/solarman/internal/modbus/SolarmanProtocolFactory.java
  bundles/org.openhab.binding.solarman/src/main/resources/OH-INF/config/datetime-channel-config.xml
  bundles/org.openhab.binding.solarman/src/main/resources/OH-INF/config/dynamic-channel-config.xml
  bundles/org.openhab.binding.solarman/src/main/resources/OH-INF/config/number-channel-config.xml
  bundles/org.openhab.binding.solarman/src/main/resources/OH-INF/config/string-channel-config.xml
  bundles/org.openhab.binding.solarman/src/main/resources/OH-INF/i18n/solarman.properties
  bundles/org.openhab.binding.solarman/src/main/resources/OH-INF/thing/channels.xml
  bundles/org.openhab.binding.solarman/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.solarman/src/test/java/org/openhab/binding/solarman/internal/DefinitionParserTest.java
Labels: bug

#17958 [insteon] Add modem database backup restore console commands
  bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/InsteonBindingConstants.java
  bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/command/DebugCommand.java
  bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/command/InsteonCommand.java
  bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/command/ModemCommand.java
  bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/command/SceneCommand.java
  bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/device/InsteonDevice.java
  bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/device/InsteonModem.java
  bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/device/database/DatabaseRecord.java
  bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/device/database/LinkDB.java
  bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/device/database/LinkDBReader.java
  bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/device/database/LinkDBWriter.java
  bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/device/database/ModemDB.java
  bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/device/database/ModemDBReader.java
  bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/device/database/ModemDBRecord.java
  bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/device/database/ModemDBWriter.java
Labels: enhancement

#18031 [insteon] Fix x10 device message handling
  bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/device/BaseDevice.java
  bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/device/InsteonDevice.java
  bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/device/InsteonModem.java
  bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/device/X10Address.java
  bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/device/feature/MessageDispatcher.java
Labels: bug

#18042 Upgrade plugins
  pom.xml
Labels: infrastructure

#18039 [broadlink] Update README
  bundles/org.openhab.binding.broadlink/README.md
Labels: documentation

#18009 [benqprojector] Fix response processing for newer projectors
  bundles/org.openhab.binding.benqprojector/README.md
  bundles/org.openhab.binding.benqprojector/src/main/java/org/openhab/binding/benqprojector/internal/BenqProjectorBindingConstants.java
  bundles/org.openhab.binding.benqprojector/src/main/java/org/openhab/binding/benqprojector/internal/BenqProjectorDevice.java
  bundles/org.openhab.binding.benqprojector/src/main/java/org/openhab/binding/benqprojector/internal/connector/BenqProjectorConnector.java
  bundles/org.openhab.binding.benqprojector/src/main/java/org/openhab/binding/benqprojector/internal/connector/BenqProjectorSerialConnector.java
  bundles/org.openhab.binding.benqprojector/src/main/java/org/openhab/binding/benqprojector/internal/connector/BenqProjectorTcpConnector.java
Labels: bug

#18049 [insteon] Fix legacy all link broadcast message not processed
  bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/InsteonLegacyBinding.java
  bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/device/LegacyDevice.java
Labels: bug

#18051 [insteon] Add device refresh all command parameter
  bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/command/DeviceCommand.java
Labels: enhancement

#18050 [insteon] Fix scene channel state updates
  bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/InsteonBindingConstants.java
  bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/handler/InsteonSceneHandler.java
Labels: bug

#18064 Fix JavaDoc output directory
  pom.xml
Labels: infrastructure, regression

#18066 [speedtest] Fix speedtest thing going offline when image not available
  bundles/org.openhab.binding.speedtest/src/main/java/org/openhab/binding/speedtest/internal/SpeedtestHandler.java
  bundles/org.openhab.binding.speedtest/src/main/java/org/openhab/binding/speedtest/internal/dto/ResultContainer.java
Labels: bug

#18058 [basicprofiles] Add a table-of-contents at top of README.md
  bundles/org.openhab.transform.basicprofiles/README.md
Labels: documentation

#18059 [roku] Add End Time and Media Progress channels
  bundles/org.openhab.binding.roku/README.md
  bundles/org.openhab.binding.roku/src/main/java/org/openhab/binding/roku/internal/RokuBindingConstants.java
  bundles/org.openhab.binding.roku/src/main/java/org/openhab/binding/roku/internal/handler/RokuHandler.java
  bundles/org.openhab.binding.roku/src/main/resources/OH-INF/i18n/roku.properties
  bundles/org.openhab.binding.roku/src/main/resources/OH-INF/thing/roku.xml
  bundles/org.openhab.binding.roku/src/main/resources/OH-INF/update/update.xml
Labels: enhancement

#18068 [mqtt.homie] Disable another unstable test
  itests/org.openhab.binding.mqtt.homie.tests/src/main/java/org/openhab/binding/mqtt/homie/HomieImplementationTest.java
Labels: test

#18069 [wemo] Disable another unstable test
  itests/org.openhab.binding.wemo.tests/src/main/java/org/openhab/binding/wemo/internal/handler/test/WemoMakerHandlerOSGiTest.java
Labels: test

#18030 [jrubyscripting] Minor updates, add short examples at the top of README.md
  bundles/org.openhab.automation.jrubyscripting/README.md
Labels: documentation

#18075 [insteon] Fix imeter solo product first record location
  bundles/org.openhab.binding.insteon/src/main/resources/device-products.xml
Labels: bug

#18087 [insteon] Fix device request failure handling
  bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/device/BaseDevice.java
  bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/device/InsteonDevice.java
  bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/handler/InsteonBaseThingHandler.java
  bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/handler/InsteonThingHandler.java
Labels: bug

#18079 [netatmo] Make configuration link clickable in Main UI
  bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/ApiBridgeHandler.java
  bundles/org.openhab.binding.netatmo/src/main/resources/OH-INF/i18n/netatmo.properties
Labels: enhancement

#18094 [Freeathome] Some more fixes
  bundles/org.openhab.binding.freeathome/src/main/java/org/openhab/binding/freeathome/internal/datamodel/FreeAtHomeDatapoint.java
  bundles/org.openhab.binding.freeathome/src/main/java/org/openhab/binding/freeathome/internal/datamodel/FreeAtHomeDatapointGroup.java
  bundles/org.openhab.binding.freeathome/src/main/java/org/openhab/binding/freeathome/internal/datamodel/FreeAtHomeDeviceChannel.java
Labels: bug

#18105 [surepetcare] API change pet weight
  bundles/org.openhab.binding.surepetcare/README.md
  bundles/org.openhab.binding.surepetcare/src/main/java/org/openhab/binding/surepetcare/internal/handler/SurePetcarePetHandler.java
Labels: bug

#18113 [ecobee] Fix setting vacation hold temperatures and ignore unrealistic actual temperature
  bundles/org.openhab.binding.ecobee/src/main/java/org/openhab/binding/ecobee/internal/function/CreateVacationFunction.java
  bundles/org.openhab.binding.ecobee/src/main/java/org/openhab/binding/ecobee/internal/handler/EcobeeThermostatBridgeHandler.java
Labels: bug

#18115 [mercedesme] Add missing status parameter for web socket error
  bundles/org.openhab.binding.mercedesme/src/main/java/org/openhab/binding/mercedesme/internal/server/MBWebsocket.java
Labels: bug

#18117 [basicprofiles] Support double quoted strings in state filter
  bundles/org.openhab.transform.basicprofiles/README.md
  bundles/org.openhab.transform.basicprofiles/src/main/java/org/openhab/transform/basicprofiles/internal/profiles/StateFilterProfile.java
  bundles/org.openhab.transform.basicprofiles/src/test/java/org/openhab/transform/basicprofiles/internal/profiles/StateFilterProfileTest.java
Labels: enhancement

#18095 [insteon] Add modem list features and product data console commands
  bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/command/ModemCommand.java
Labels: enhancement

#18086 [energidataservice] Update tariff filter for Netselskabet Elværk
  bundles/org.openhab.binding.energidataservice/src/main/resources/OH-INF/config/config.xml
  bundles/org.openhab.binding.energidataservice/src/main/resources/OH-INF/i18n/energidataservice.properties
  bundles/org.openhab.binding.energidataservice/src/main/resources/filters/grid_tariffs.yaml
Labels: enhancement

#18131 [fronius] Verify battery control time of use successfully set
  bundles/org.openhab.binding.fronius/src/main/java/org/openhab/binding/fronius/internal/api/FroniusBatteryControl.java
  bundles/org.openhab.binding.fronius/src/main/java/org/openhab/binding/fronius/internal/api/dto/inverter/PostConfigResponse.java
Labels: enhancement

#18141 Fix table of content tag
  bundles/org.openhab.binding.modbus/README.md
  bundles/org.openhab.persistence.dynamodb/README.md
Labels: documentation

#17816 [shelly] Re-Add/Fix Shelly Plus UNI support
  bundles/org.openhab.binding.shelly/README.md
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/ShellyBindingConstants.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/discovery/ShellyThingCreator.java
  bundles/org.openhab.binding.shelly/src/main/resources/OH-INF/i18n/shelly.properties
  bundles/org.openhab.binding.shelly/src/main/resources/OH-INF/thing/shellyGen2_relay.xml
  bundles/org.openhab.binding.shelly/src/test/java/org/openhab/binding/shelly/internal/discovery/ShellyThingCreatorTest.java
Labels: bug, (potentially) not backward compatible

#18136 [insteon] Limit device request failure condition
  bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/device/BaseDevice.java
Labels: bug

#18135 [insteon] Remove iolinc event button feature
  bundles/org.openhab.binding.insteon/src/main/resources/device-types.xml
Labels: bug

#18146 [bluetooth.bluez] update to dbus version 0.3.1
  bundles/org.openhab.binding.bluetooth.bluez/pom.xml
  bundles/org.openhab.binding.bluetooth.bluez/src/main/feature/feature.xml
  features/openhab-addons/src/main/resources/footer.xml
Labels: bug, regression

#18027 [easee] speedup command processing
  bundles/org.openhab.binding.easee/README.md
  bundles/org.openhab.binding.easee/src/main/java/org/openhab/binding/easee/internal/EaseeBindingConstants.java
  bundles/org.openhab.binding.easee/src/main/java/org/openhab/binding/easee/internal/config/EaseeConfiguration.java
  bundles/org.openhab.binding.easee/src/main/java/org/openhab/binding/easee/internal/connector/WebInterface.java
  bundles/org.openhab.binding.easee/src/main/resources/OH-INF/config/config.xml
  bundles/org.openhab.binding.easee/src/main/resources/OH-INF/i18n/easee.properties
Labels: enhancement

#18153 [mybmw] Fix charging statistics URL
  bundles/org.openhab.binding.mybmw/src/main/java/org/openhab/binding/mybmw/internal/handler/auth/MyBMWTokenController.java
  bundles/org.openhab.binding.mybmw/src/main/java/org/openhab/binding/mybmw/internal/handler/auth/Token.java
  bundles/org.openhab.binding.mybmw/src/main/java/org/openhab/binding/mybmw/internal/handler/backend/MyBMWHttpProxy.java
  bundles/org.openhab.binding.mybmw/src/main/java/org/openhab/binding/mybmw/internal/utils/BimmerConstants.java
Labels: bug

#18154 [roku] Add rule examples for starting apps
  bundles/org.openhab.binding.roku/README.md
Labels: documentation

#17869 [shelly]Add Shelly Plug S Gen3
  bundles/org.openhab.binding.shelly/README.md
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/discovery/ShellyThingCreator.java
Labels: enhancement

#18165 [shelly] Correct doc for Pro EM-50
  bundles/org.openhab.binding.shelly/README.md
Labels: documentation

#18133 [luxtronikheatpump] Adjust previously unknown channels with new information
  bundles/org.openhab.binding.luxtronikheatpump/README.md
  bundles/org.openhab.binding.luxtronikheatpump/src/main/java/org/openhab/binding/luxtronikheatpump/internal/ChannelUpdaterJob.java
  bundles/org.openhab.binding.luxtronikheatpump/src/main/java/org/openhab/binding/luxtronikheatpump/internal/enums/HeatpumpChannel.java
  bundles/org.openhab.binding.luxtronikheatpump/src/main/resources/OH-INF/i18n/luxtronikheatpump.properties
  bundles/org.openhab.binding.luxtronikheatpump/src/main/resources/OH-INF/thing/channels.xml
  bundles/org.openhab.binding.luxtronikheatpump/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.luxtronikheatpump/src/main/resources/OH-INF/update/instructions.xml
Labels: enhancement

#18167 [shelly] Support for Shelly Plus 2PM Gen3 and Plus 2PM UL
  bundles/org.openhab.binding.shelly/README.md
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/discovery/ShellyThingCreator.java
Labels: enhancement

#18088 [basicprofiles] Fix handling of multiple `$DELTA` conditions
  bundles/org.openhab.transform.basicprofiles/src/main/java/org/openhab/transform/basicprofiles/internal/profiles/StateFilterProfile.java
  bundles/org.openhab.transform.basicprofiles/src/test/java/org/openhab/transform/basicprofiles/internal/profiles/StateFilterProfileTest.java
Labels: bug

#18121 [basicprofiles] Fix regular comparison of Percent Quantity interpreted as $DELTA_PERCENT check
  bundles/org.openhab.transform.basicprofiles/README.md
  bundles/org.openhab.transform.basicprofiles/src/main/java/org/openhab/transform/basicprofiles/internal/profiles/StateFilterProfile.java
  bundles/org.openhab.transform.basicprofiles/src/test/java/org/openhab/transform/basicprofiles/internal/profiles/StateFilterProfileTest.java
Labels: enhancement

#18175 Provide unit hints for rpm channels
  bundles/org.openhab.binding.comfoair/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.danfossairunit/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.haywardomnilogic/src/main/resources/OH-INF/thing/filter.xml
  bundles/org.openhab.binding.haywardomnilogic/src/main/resources/OH-INF/thing/pump.xml
Labels: enhancement

#18078 [jellyfin] Make configuration link clickable in Main UI
  bundles/org.openhab.binding.jellyfin/src/main/java/org/openhab/binding/jellyfin/internal/handler/JellyfinServerHandler.java
Labels: enhancement

#18181 [bluetooth.bluez] Fix `NullPointerException`
  bundles/org.openhab.binding.bluetooth.bluez/src/main/java/org/openhab/binding/bluetooth/bluez/internal/BlueZBluetoothDevice.java
Labels: bug

#18185 [bluetooth.bluez] Fix `NullPointerException`
  bundles/org.openhab.binding.bluetooth.bluez/src/main/java/org/openhab/binding/bluetooth/bluez/internal/BlueZBluetoothDevice.java
Labels: bug, regression

#18191 [lifx] Add support for new LIFX products
  bundles/org.openhab.binding.lifx/README.md
  bundles/org.openhab.binding.lifx/src/main/java/org/openhab/binding/lifx/internal/LifxProduct.java
Labels: enhancement

#18195 Add chapter headings for examples
  bundles/org.openhab.binding.benqprojector/README.md
  bundles/org.openhab.binding.epsonprojector/README.md
  bundles/org.openhab.binding.kaleidescape/README.md
  bundles/org.openhab.binding.monopriceaudio/README.md
  bundles/org.openhab.binding.nuvo/README.md
  bundles/org.openhab.binding.oppo/README.md
  bundles/org.openhab.binding.panasonicbdp/README.md
  bundles/org.openhab.binding.radiothermostat/README.md
  bundles/org.openhab.binding.roku/README.md
  bundles/org.openhab.binding.tasmotaplug/README.md
  bundles/org.openhab.binding.tivo/README.md
  bundles/org.openhab.binding.vizio/README.md
Labels: documentation

#18198 [jrubyscripting] Update to JRuby 9.4.10.0
  bundles/org.openhab.automation.jrubyscripting/pom.xml
Labels: enhancement

#18125 [radoneye] Add decay channel for HW v2 and simplify the code
  bundles/org.openhab.binding.bluetooth.radoneye/README.md
  bundles/org.openhab.binding.bluetooth.radoneye/src/main/java/org/openhab/binding/bluetooth/radoneye/internal/AbstractRadoneyeHandler.java
  bundles/org.openhab.binding.bluetooth.radoneye/src/main/java/org/openhab/binding/bluetooth/radoneye/internal/RadoneyeBindingConstants.java
  bundles/org.openhab.binding.bluetooth.radoneye/src/main/java/org/openhab/binding/bluetooth/radoneye/internal/RadoneyeDataParser.java
  bundles/org.openhab.binding.bluetooth.radoneye/src/main/java/org/openhab/binding/bluetooth/radoneye/internal/RadoneyeDiscoveryParticipant.java
  bundles/org.openhab.binding.bluetooth.radoneye/src/main/java/org/openhab/binding/bluetooth/radoneye/internal/RadoneyeHandler.java
  bundles/org.openhab.binding.bluetooth.radoneye/src/main/resources/OH-INF/i18n/bluetooth.properties
  bundles/org.openhab.binding.bluetooth.radoneye/src/main/resources/OH-INF/thing/radoneye.xml
  bundles/org.openhab.binding.bluetooth.radoneye/src/main/resources/OH-INF/update/instructions.xml
  bundles/org.openhab.binding.bluetooth.radoneye/src/test/java/org/openhab/binding/bluetooth/radoneye/RadoneyeParserTest.java
Labels: enhancement
