Repository openhab/openhab-addons, pull requests merged in 2025-05, with the labels that each got.

#18629 [GHA] Fix rebuild using label rebuild
  .github/workflows/ci-build.yml
  .github/workflows/rebuild.yml
Labels: bug, infrastructure, regression

#18592 [stiebeleltron] Update README.md
  bundles/org.openhab.binding.modbus.stiebeleltron/README.md
Labels: documentation

#18463 [senseenergy] Address reconnect issues on failure
  bundles/org.openhab.binding.senseenergy/src/main/java/org/openhab/binding/senseenergy/internal/actions/SenseEnergyMonitorActions.java
  bundles/org.openhab.binding.senseenergy/src/main/java/org/openhab/binding/senseenergy/internal/api/SenseEnergyApi.java
  bundles/org.openhab.binding.senseenergy/src/main/java/org/openhab/binding/senseenergy/internal/api/SenseEnergyApiException.java
  bundles/org.openhab.binding.senseenergy/src/main/java/org/openhab/binding/senseenergy/internal/api/SenseEnergyDatagram.java
  bundles/org.openhab.binding.senseenergy/src/main/java/org/openhab/binding/senseenergy/internal/api/SenseEnergyWebSocket.java
  bundles/org.openhab.binding.senseenergy/src/main/java/org/openhab/binding/senseenergy/internal/api/SenseEnergyWebSocketListener.java
  bundles/org.openhab.binding.senseenergy/src/main/java/org/openhab/binding/senseenergy/internal/handler/SenseEnergyBridgeHandler.java
  bundles/org.openhab.binding.senseenergy/src/main/java/org/openhab/binding/senseenergy/internal/handler/SenseEnergyMonitorHandler.java
  bundles/org.openhab.binding.senseenergy/src/main/resources/OH-INF/i18n/senseenergy.properties
Labels: enhancement

#18637 [nest] Change examples to prevent secret scan false positives
  bundles/org.openhab.binding.nest/README.md
Labels: documentation

#18636 [groovyscripting] Upgrade Groovy to 4.0.26
  bundles/org.openhab.automation.groovyscripting/README.md
  bundles/org.openhab.automation.groovyscripting/pom.xml
Labels: enhancement

#18640 [boschshc] Update pairing documentation for Smart Home Controller II
  bundles/org.openhab.binding.boschshc/README.md
Labels: documentation

#18646 [bambulab] Fix `JsonMappingException` by upgrading JBambuAPI
  bundles/org.openhab.binding.bambulab/pom.xml
Labels: bug

#18655 [tuya] Handle RefreshType requests on Channels
  bundles/org.openhab.binding.tuya/src/main/java/org/openhab/binding/tuya/internal/handler/TuyaDeviceHandler.java
Labels: enhancement

#18652 [tuya] Fix typo, regen translations
  bundles/org.openhab.binding.tuya/src/main/resources/OH-INF/i18n/tuya.properties
  bundles/org.openhab.binding.tuya/src/main/resources/OH-INF/thing/thing-types.xml
Labels: enhancement

#18653 [tuya] Fix to allow for Channels whose DPs have string values
  bundles/org.openhab.binding.tuya/src/main/java/org/openhab/binding/tuya/internal/util/SchemaDp.java
Labels: enhancement

#18624 [avmfritz] Support alias product names
  bundles/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/AVMFritzBindingConstants.java
  bundles/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/dto/AVMFritzBaseModel.java
  bundles/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/handler/AVMFritzBaseBridgeHandler.java
  bundles/org.openhab.binding.avmfritz/src/test/java/org/openhab/binding/avmfritz/internal/dto/AVMFritzDeviceListModelTest.java
Labels: bug

#18648 Revert upgrade of JUnit to 5.12.1
  itests/org.openhab.automation.groovyscripting.tests/itest.bndrun
  itests/org.openhab.automation.jsscriptingnashorn.tests/itest.bndrun
  itests/org.openhab.binding.astro.tests/itest.bndrun
  itests/org.openhab.binding.avmfritz.tests/itest.bndrun
  itests/org.openhab.binding.feed.tests/itest.bndrun
  itests/org.openhab.binding.hue.tests/itest.bndrun
  itests/org.openhab.binding.max.tests/itest.bndrun
  itests/org.openhab.binding.mielecloud.tests/itest.bndrun
  itests/org.openhab.binding.modbus.tests/itest.bndrun
  itests/org.openhab.binding.mqtt.homeassistant.tests/itest.bndrun
  itests/org.openhab.binding.mqtt.homie.tests/itest.bndrun
  itests/org.openhab.binding.mqtt.ruuvigateway.tests/itest.bndrun
  itests/org.openhab.binding.ntp.tests/itest.bndrun
  itests/org.openhab.binding.systeminfo.tests/itest.bndrun
  itests/org.openhab.binding.tradfri.tests/itest.bndrun
  itests/org.openhab.persistence.mapdb.tests/itest.bndrun
Labels: awaiting other PR

#18661 [tuya] Fix Thing ID in documentation
  bundles/org.openhab.binding.tuya/README.md
Labels: documentation

#18659 [pythonscripting] Fix helper lib deployment on Windows
  bundles/org.openhab.automation.pythonscripting/src/main/java/org/openhab/automation/pythonscripting/internal/PythonScriptEngine.java
  bundles/org.openhab.automation.pythonscripting/src/main/java/org/openhab/automation/pythonscripting/internal/PythonScriptEngineFactory.java
Labels: bug, regression

#18666 [powermax] Correct Equipment tags
  bundles/org.openhab.binding.powermax/src/main/resources/OH-INF/thing/ip.xml
  bundles/org.openhab.binding.powermax/src/main/resources/OH-INF/thing/serial.xml
Labels: enhancement

#18471 [froniuswattpilot] Initial contribution
  CODEOWNERS
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.froniuswattpilot/NOTICE
  bundles/org.openhab.binding.froniuswattpilot/README.md
  bundles/org.openhab.binding.froniuswattpilot/pom.xml
  bundles/org.openhab.binding.froniuswattpilot/src/main/feature/feature.xml
  bundles/org.openhab.binding.froniuswattpilot/src/main/java/org/openhab/binding/froniuswattpilot/internal/FroniusWattpilotBindingConstants.java
  bundles/org.openhab.binding.froniuswattpilot/src/main/java/org/openhab/binding/froniuswattpilot/internal/FroniusWattpilotConfiguration.java
  bundles/org.openhab.binding.froniuswattpilot/src/main/java/org/openhab/binding/froniuswattpilot/internal/FroniusWattpilotHandler.java
  bundles/org.openhab.binding.froniuswattpilot/src/main/java/org/openhab/binding/froniuswattpilot/internal/FroniusWattpilotHandlerFactory.java
  bundles/org.openhab.binding.froniuswattpilot/src/main/java/org/openhab/binding/froniuswattpilot/internal/FroniusWattpilotMDNSDiscoveryServiceParticipant.java
  bundles/org.openhab.binding.froniuswattpilot/src/main/resources/OH-INF/addon/addon.xml
  bundles/org.openhab.binding.froniuswattpilot/src/main/resources/OH-INF/i18n/froniuswattpilot.properties
  bundles/org.openhab.binding.froniuswattpilot/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/pom.xml
Labels: new binding

#18632 [GHA] Adapt rebuild
  .github/workflows/ci-build.yml
  .github/workflows/rebuild.yml
Labels: bug, infrastructure, regression

#18671 [pythonscripting] Fix python timedelta to java duration mapping
  bundles/org.openhab.automation.pythonscripting/pom.xml
  bundles/org.openhab.automation.pythonscripting/src/main/java/org/openhab/automation/pythonscripting/internal/PythonScriptEngine.java
Labels: bug, regression

#18672 [weatherunderground] Fix equipment tag
  bundles/org.openhab.binding.weatherunderground/src/main/resources/OH-INF/thing/bridge.xml
Labels: regression

#18631 [freeathome] Add Wireless Blind Actuator support, Improve connection handling
  bundles/org.openhab.binding.freeathome/src/main/java/org/openhab/binding/freeathome/internal/configuration/FreeAtHomeBridgeHandlerConfiguration.java
  bundles/org.openhab.binding.freeathome/src/main/java/org/openhab/binding/freeathome/internal/datamodel/FreeAtHomeDeviceChannel.java
  bundles/org.openhab.binding.freeathome/src/main/java/org/openhab/binding/freeathome/internal/handler/FreeAtHomeBridgeHandler.java
  bundles/org.openhab.binding.freeathome/src/main/java/org/openhab/binding/freeathome/internal/handler/FreeAtHomeDeviceHandler.java
  bundles/org.openhab.binding.freeathome/src/main/java/org/openhab/binding/freeathome/internal/util/FidTranslationUtils.java
  bundles/org.openhab.binding.freeathome/src/main/java/org/openhab/binding/freeathome/internal/util/FreeAtHomeHttpCommunicationException.java
  bundles/org.openhab.binding.freeathome/src/main/resources/OH-INF/addon/addon.xml
  bundles/org.openhab.binding.freeathome/src/main/resources/OH-INF/i18n/freeathome.properties
  bundles/org.openhab.binding.freeathome/src/main/resources/OH-INF/thing/bridge-type.xml
Labels: enhancement

#18647 [avmfritz] Support new devices
  bundles/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/AVMFritzBindingConstants.java
  bundles/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/discovery/AVMFritzDiscoveryService.java
  bundles/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/dto/AVMFritzBaseModel.java
  bundles/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/handler/AVMFritzBaseBridgeHandler.java
  bundles/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/handler/AVMFritzBaseThingHandler.java
  bundles/org.openhab.binding.avmfritz/src/main/resources/OH-INF/i18n/avmfritz.properties
  bundles/org.openhab.binding.avmfritz/src/main/resources/OH-INF/thing/thing-types.xml
  itests/org.openhab.binding.avmfritz.tests/src/main/java/org/openhab/binding/avmfritz/internal/discovery/AVMFritzDiscoveryServiceOSGiTest.java
Labels: enhancement, additional testing preferred

#18635 [jsscriptingnashorn] Upgrade Nashorn to 15.6
  bundles/org.openhab.automation.jsscriptingnashorn/pom.xml
Labels: enhancement

#18482 [deconz] Cross update color & color temperature channels
  bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/handler/LightThingHandler.java
  bundles/org.openhab.binding.deconz/src/main/resources/OH-INF/thing/group-thing-types.xml
  bundles/org.openhab.binding.deconz/src/main/resources/OH-INF/thing/light-thing-types.xml
  bundles/org.openhab.binding.deconz/src/main/resources/OH-INF/thing/sensor-channel-types.xml
  bundles/org.openhab.binding.deconz/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.deconz/src/test/java/org/openhab/binding/deconz/LightsTest.java
  bundles/org.openhab.binding.deconz/src/test/resources/org/openhab/binding/deconz/colortemperature-sparse.json
  bundles/org.openhab.binding.deconz/src/test/resources/org/openhab/binding/deconz/extended_ct.json
  bundles/org.openhab.binding.deconz/src/test/resources/org/openhab/binding/deconz/extended_hsb.json
  bundles/org.openhab.binding.deconz/src/test/resources/org/openhab/binding/deconz/extended_xy.json
Labels: enhancement

#18644 [energidataservice] Fix `DAY_AHEAD_AVAILABLE` event
  bundles/org.openhab.binding.energidataservice/src/main/java/org/openhab/binding/energidataservice/internal/handler/EnergiDataServiceHandler.java
  bundles/org.openhab.binding.energidataservice/src/main/java/org/openhab/binding/energidataservice/internal/provider/ElectricityPriceProvider.java
  bundles/org.openhab.binding.energidataservice/src/test/java/org/openhab/binding/energidataservice/internal/provider/ElectricityPriceProviderTest.java
Labels: bug, regression

#18541 [harmonyhub] Add semantic tags
  bundles/org.openhab.binding.harmonyhub/src/main/resources/OH-INF/thing/thing-types.xml
Labels: enhancement

#18665 [openweathermap] fix update instructions
  bundles/org.openhab.binding.openweathermap/src/main/resources/OH-INF/update/instructions.xml
Labels: bug, regression

#18512 [tado] Add semantic tags
  bundles/org.openhab.binding.tado/src/main/resources/OH-INF/thing/thing-types.xml
Labels: enhancement

#18341 [hue] Add semantic tags
  bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/Clip2ThingHandler.java
  bundles/org.openhab.binding.hue/src/main/resources/OH-INF/thing/bridge.xml
  bundles/org.openhab.binding.hue/src/main/resources/OH-INF/thing/channels.xml
Labels: enhancement

#18607 [emby] Initial contribution
  CODEOWNERS
  bom/openhab-addons/pom.xml
  bundles/org.openhab.binding.emby/NOTICE
  bundles/org.openhab.binding.emby/README.md
  bundles/org.openhab.binding.emby/pom.xml
  bundles/org.openhab.binding.emby/src/main/feature/feature.xml
  bundles/org.openhab.binding.emby/src/main/java/org/openhab/binding/emby/internal/EmbyBindingConstants.java
  bundles/org.openhab.binding.emby/src/main/java/org/openhab/binding/emby/internal/EmbyBridgeConfiguration.java
  bundles/org.openhab.binding.emby/src/main/java/org/openhab/binding/emby/internal/EmbyBridgeListener.java
  bundles/org.openhab.binding.emby/src/main/java/org/openhab/binding/emby/internal/EmbyDeviceConfiguration.java
  bundles/org.openhab.binding.emby/src/main/java/org/openhab/binding/emby/internal/EmbyEventListener.java
  bundles/org.openhab.binding.emby/src/main/java/org/openhab/binding/emby/internal/EmbyHandlerFactory.java
  bundles/org.openhab.binding.emby/src/main/java/org/openhab/binding/emby/internal/discovery/EmbyBridgeDiscoveryService.java
  bundles/org.openhab.binding.emby/src/main/java/org/openhab/binding/emby/internal/discovery/EmbyClientDiscoveryService.java
  bundles/org.openhab.binding.emby/src/main/java/org/openhab/binding/emby/internal/handler/EmbyActions.java
  bundles/org.openhab.binding.emby/src/main/java/org/openhab/binding/emby/internal/handler/EmbyBridgeHandler.java
  bundles/org.openhab.binding.emby/src/main/java/org/openhab/binding/emby/internal/handler/EmbyDeviceHandler.java
  bundles/org.openhab.binding.emby/src/main/java/org/openhab/binding/emby/internal/model/EmbyNowPlayingCurrentProgram.java
  bundles/org.openhab.binding.emby/src/main/java/org/openhab/binding/emby/internal/model/EmbyNowPlayingItem.java
  bundles/org.openhab.binding.emby/src/main/java/org/openhab/binding/emby/internal/model/EmbyPlayState.java
  bundles/org.openhab.binding.emby/src/main/java/org/openhab/binding/emby/internal/model/EmbyPlayStateModel.java
  bundles/org.openhab.binding.emby/src/main/java/org/openhab/binding/emby/internal/model/EmbyPlayingPostJsonModel.java
  bundles/org.openhab.binding.emby/src/main/java/org/openhab/binding/emby/internal/protocol/EmbyClientSocket.java
  bundles/org.openhab.binding.emby/src/main/java/org/openhab/binding/emby/internal/protocol/EmbyClientSocketEventListener.java
  bundles/org.openhab.binding.emby/src/main/java/org/openhab/binding/emby/internal/protocol/EmbyConnection.java
  bundles/org.openhab.binding.emby/src/main/java/org/openhab/binding/emby/internal/protocol/EmbyDeviceEncoder.java
  bundles/org.openhab.binding.emby/src/main/java/org/openhab/binding/emby/internal/protocol/EmbyHTTPUtils.java
  bundles/org.openhab.binding.emby/src/main/java/org/openhab/binding/emby/internal/protocol/EmbyHttpRetryExceeded.java
  bundles/org.openhab.binding.emby/src/main/java/org/openhab/binding/emby/internal/util/EmbyThrottle.java
  bundles/org.openhab.binding.emby/src/main/resources/OH-INF/addon/addon.xml
  bundles/org.openhab.binding.emby/src/main/resources/OH-INF/i18n/emby.properties
  bundles/org.openhab.binding.emby/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/pom.xml
Labels: new binding

#18688 [jsscripting] Upgrade openhab-js to 5.11.0
  bundles/org.openhab.automation.jsscripting/README.md
  bundles/org.openhab.automation.jsscripting/pom.xml
Labels: enhancement

#18658 [mqtt.awtrixlight] Add LWT support and improve ThingStatus handling
  bundles/org.openhab.binding.mqtt.awtrixlight/src/main/java/org/openhab/binding/mqtt/awtrixlight/internal/AwtrixLightBindingConstants.java
  bundles/org.openhab.binding.mqtt.awtrixlight/src/main/java/org/openhab/binding/mqtt/awtrixlight/internal/Helper.java
  bundles/org.openhab.binding.mqtt.awtrixlight/src/main/java/org/openhab/binding/mqtt/awtrixlight/internal/handler/AwtrixLightAppHandler.java
  bundles/org.openhab.binding.mqtt.awtrixlight/src/main/java/org/openhab/binding/mqtt/awtrixlight/internal/handler/AwtrixLightBridgeHandler.java
  bundles/org.openhab.binding.mqtt.awtrixlight/src/main/resources/OH-INF/i18n/mqtt.properties
  bundles/org.openhab.binding.mqtt.awtrixlight/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.mqtt.awtrixlight/src/main/resources/OH-INF/update/awtrix-app-updates.xml
  bundles/org.openhab.binding.mqtt.awtrixlight/src/main/resources/OH-INF/update/awtrix-clock-updates.xml
Labels: enhancement

#18481 [tado] Support multiple homes & accounts, and bug fixes
  bundles/org.openhab.binding.tado/README.md
  bundles/org.openhab.binding.tado/src/main/java/org/openhab/binding/tado/internal/TadoBindingConstants.java
  bundles/org.openhab.binding.tado/src/main/java/org/openhab/binding/tado/internal/config/TadoHomeConfig.java
  bundles/org.openhab.binding.tado/src/main/java/org/openhab/binding/tado/internal/handler/TadoHandlerFactory.java
  bundles/org.openhab.binding.tado/src/main/java/org/openhab/binding/tado/internal/handler/TadoHomeHandler.java
  bundles/org.openhab.binding.tado/src/main/java/org/openhab/binding/tado/internal/servlet/TadoAuthenticationServlet.java
  bundles/org.openhab.binding.tado/src/main/resources/OH-INF/i18n/tado.properties
  bundles/org.openhab.binding.tado/src/main/resources/OH-INF/thing/thing-types.xml
Labels: enhancement

#18540 [astro] Add semantic tags
  bundles/org.openhab.binding.astro/src/main/resources/OH-INF/thing/channels.xml
  bundles/org.openhab.binding.astro/src/main/resources/OH-INF/thing/moon.xml
  bundles/org.openhab.binding.astro/src/main/resources/OH-INF/thing/sun.xml
Labels: enhancement

#18657 [tuya] Order Channels using DP order in schemas
  bundles/org.openhab.binding.tuya/src/main/java/org/openhab/binding/tuya/internal/TuyaBindingConstants.java
  bundles/org.openhab.binding.tuya/src/main/java/org/openhab/binding/tuya/internal/handler/TuyaDeviceHandler.java
Labels: enhancement

#18650 [ecovacs] Fix spot area cleaning for X2 and newer
  bundles/org.openhab.binding.ecovacs/src/main/java/org/openhab/binding/ecovacs/internal/api/commands/SpotAreaCleaningCommand.java
Labels: bug

#18524 [mqtt.homeassistant] Use a thing action for updates, instead of a config action
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/generic/internal/MqttThingHandlerFactory.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/actions/HomeAssistantUpdateThingActions.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/handler/HomeAssistantThingHandler.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/resources/OH-INF/config/homeassistant-thing-config.xml
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/resources/OH-INF/i18n/mqtt.properties
  bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/component/AbstractComponentTests.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/handler/HomeAssistantThingHandlerTests.java
Labels: enhancement

#18706 [insteon] Set device type for usb adapter as plm network bridge
  bundles/org.openhab.binding.insteon/src/main/java/org/openhab/binding/insteon/internal/device/InsteonModem.java
  bundles/org.openhab.binding.insteon/src/main/resources/device-products.xml
Labels: enhancement

#18679 [linktap] Add communication timeout configuration parameter
  bundles/org.openhab.binding.linktap/README.md
  bundles/org.openhab.binding.linktap/src/main/java/org/openhab/binding/linktap/configuration/LinkTapBridgeConfiguration.java
  bundles/org.openhab.binding.linktap/src/main/java/org/openhab/binding/linktap/internal/LinkTapBindingConstants.java
  bundles/org.openhab.binding.linktap/src/main/java/org/openhab/binding/linktap/internal/LinkTapBridgeHandler.java
  bundles/org.openhab.binding.linktap/src/main/java/org/openhab/binding/linktap/internal/LinkTapHandler.java
  bundles/org.openhab.binding.linktap/src/main/java/org/openhab/binding/linktap/internal/TransactionProcessor.java
  bundles/org.openhab.binding.linktap/src/main/java/org/openhab/binding/linktap/protocol/http/JettyTraceListener.java
  bundles/org.openhab.binding.linktap/src/main/java/org/openhab/binding/linktap/protocol/http/WebServerApi.java
  bundles/org.openhab.binding.linktap/src/main/resources/OH-INF/i18n/linktap.properties
  bundles/org.openhab.binding.linktap/src/main/resources/OH-INF/thing/thing-types.xml
Labels: enhancement

#18721 [upnpcontrol] Discover child devices
  bundles/org.openhab.binding.upnpcontrol/src/main/java/org/openhab/binding/upnpcontrol/internal/discovery/UpnpControlDiscoveryParticipant.java
Labels: enhancement

#18727 [amberelectric] Fix nem-time channel
  bundles/org.openhab.binding.amberelectric/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.amberelectric/src/main/resources/OH-INF/update/instructions.xml
Labels: bug

#18716 [amberelectric] Add support for forecasts, add site data to Thing properties
  bundles/org.openhab.binding.amberelectric/README.md
  bundles/org.openhab.binding.amberelectric/src/main/java/org/openhab/binding/amberelectric/internal/AmberElectricConfiguration.java
  bundles/org.openhab.binding.amberelectric/src/main/java/org/openhab/binding/amberelectric/internal/AmberElectricHandler.java
  bundles/org.openhab.binding.amberelectric/src/main/java/org/openhab/binding/amberelectric/internal/AmberElectricWebTargets.java
  bundles/org.openhab.binding.amberelectric/src/main/java/org/openhab/binding/amberelectric/internal/api/CurrentPrices.java
  bundles/org.openhab.binding.amberelectric/src/main/java/org/openhab/binding/amberelectric/internal/api/Sites.java
  bundles/org.openhab.binding.amberelectric/src/main/resources/OH-INF/i18n/amberelectric.properties
  bundles/org.openhab.binding.amberelectric/src/main/resources/OH-INF/thing/thing-types.xml
Labels: enhancement

#18724 [shelly] Fix for Shelly Pro 1CB
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api2/Shelly2ApiRpc.java
Labels: bug

#18601 [mqtt.homeassistant] Use GraalPy and import actual Home Assistant templating code
  bundles/org.openhab.binding.mqtt.homeassistant/.gitignore
  bundles/org.openhab.binding.mqtt.homeassistant/DEVELOPMENT.md
  bundles/org.openhab.binding.mqtt.homeassistant/NOTICE
  bundles/org.openhab.binding.mqtt.homeassistant/bnd.bnd
  bundles/org.openhab.binding.mqtt.homeassistant/noEmbedDependencies.profile
  bundles/org.openhab.binding.mqtt.homeassistant/pom.xml
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/feature/feature.xml
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/generic/internal/MqttThingHandlerFactory.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/ComponentChannel.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/DiscoverComponents.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/HomeAssistantChannelTransformation.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/HomeAssistantJinjaFunctionLibrary.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/HomeAssistantPythonBridge.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/AbstractComponent.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/ComponentFactory.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/Event.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/Fan.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/component/TemplateSchemaLight.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/handler/HomeAssistantThingHandler.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/python/homeassistant/components/mqtt/const.py
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/python/homeassistant/components/mqtt/models.py
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/python/homeassistant/exceptions.py
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/python/homeassistant/helpers/config_validation.py
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/python/homeassistant/helpers/template.py
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/python/homeassistant/util/__init__.py
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/python/homeassistant/util/dt.py
  bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/AbstractHomeAssistantTests.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/HomeAssistantChannelTransformationTests.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/component/AbstractComponentTests.java
  bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/handler/HomeAssistantThingHandlerTests.java
  itests/org.openhab.binding.mqtt.homeassistant.tests/itest.bndrun
  itests/org.openhab.binding.mqtt.homeassistant.tests/src/main/java/org/openhab/binding/mqtt/homeassistant/DiscoverComponentsTest.java
  itests/org.openhab.binding.mqtt.homeassistant.tests/src/main/java/org/openhab/binding/mqtt/homeassistant/HomeAssistantMQTTImplementationTest.java
Labels: bug

#18731 [teslapowerwall] Fix regression in last PR
  bundles/org.openhab.binding.teslapowerwall/src/main/java/org/openhab/binding/teslapowerwall/internal/api/SystemStatus.java
Labels: regression
