Repository openhab/openhab-addons, pull requests merged in 2025-04, with the labels that each got.

#18408 [venstarthermostat] Add semantic tags to channels
  bundles/org.openhab.binding.venstarthermostat/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.venstarthermostat/src/main/resources/OH-INF/update/instructions.xml
Labels: enhancement

#18470 [danfossairunit] Provide additional properties
  bundles/org.openhab.binding.danfossairunit/src/main/java/org/openhab/binding/danfossairunit/internal/DanfossAirUnit.java
  bundles/org.openhab.binding.danfossairunit/src/main/java/org/openhab/binding/danfossairunit/internal/DanfossAirUnitBindingConstants.java
  bundles/org.openhab.binding.danfossairunit/src/main/java/org/openhab/binding/danfossairunit/internal/DanfossAirUnitHandlerFactory.java
  bundles/org.openhab.binding.danfossairunit/src/main/java/org/openhab/binding/danfossairunit/internal/discovery/DanfossAirUnitDiscoveryService.java
  bundles/org.openhab.binding.danfossairunit/src/main/java/org/openhab/binding/danfossairunit/internal/handler/DanfossAirUnitHandler.java
  bundles/org.openhab.binding.danfossairunit/src/main/java/org/openhab/binding/danfossairunit/internal/protocol/Parameter.java
  bundles/org.openhab.binding.danfossairunit/src/test/java/org/openhab/binding/danfossairunit/internal/DanfossAirUnitTest.java
Labels: enhancement

#18493 [bluetooth.daikinmodoka] Adapt test to core change
  bundles/org.openhab.binding.bluetooth.daikinmadoka/src/test/java/org/openhab/binding/bluetooth/daikinmadoka/handler/DummyThing.java
Labels: test

#18496 [energidataservice] Add tariff filter for Forsyning Elnet
  bundles/org.openhab.binding.energidataservice/src/main/resources/OH-INF/config/config.xml
  bundles/org.openhab.binding.energidataservice/src/main/resources/OH-INF/i18n/energidataservice.properties
  bundles/org.openhab.binding.energidataservice/src/main/resources/filters/grid_tariffs.yaml
Labels: enhancement

#17250 [enocean] Eltako FJ62 support
  bundles/org.openhab.binding.enocean/README.md
  bundles/org.openhab.binding.enocean/src/main/java/org/openhab/binding/enocean/internal/eep/EEPType.java
  bundles/org.openhab.binding.enocean/src/main/java/org/openhab/binding/enocean/internal/eep/F6_00/F6_00_00_EltakoFJ62.java
  bundles/org.openhab.binding.enocean/src/main/resources/OH-INF/i18n/enocean.properties
  bundles/org.openhab.binding.enocean/src/main/resources/OH-INF/thing/Rollershutter.xml
Labels: enhancement

#18490 [sbus] Add support for STOP command
  bundles/org.openhab.binding.sbus/README.md
  bundles/org.openhab.binding.sbus/pom.xml
  bundles/org.openhab.binding.sbus/src/main/java/org/openhab/binding/sbus/handler/SbusSwitchHandler.java
  bundles/org.openhab.binding.sbus/src/main/resources/OH-INF/thing/thing-types.xml
Labels: enhancement

#18509 [asuswrt] Fixed issue where reconnectJob does not try to reconnect (#18456)
  bundles/org.openhab.binding.asuswrt/src/main/java/org/openhab/binding/asuswrt/internal/api/AsuswrtConnector.java
Labels: bug

#18516 [growatt] Add semantic tags
  bundles/org.openhab.binding.growatt/src/main/resources/OH-INF/thing/thing-types.xml
Labels: enhancement

#18520 [growatt] Add unit hint on frequency channel
  bundles/org.openhab.binding.growatt/src/main/resources/OH-INF/thing/thing-types.xml
Labels: enhancement

#18491 [satel] Add event log details for event description 10
  bundles/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/util/DeviceNameResolver.java
  bundles/org.openhab.binding.satel/src/main/java/org/openhab/binding/satel/internal/util/EventLogReader.java
  bundles/org.openhab.binding.satel/src/test/java/org/openhab/binding/satel/internal/util/DeviceNameResolverTest.java
  bundles/org.openhab.binding.satel/src/test/java/org/openhab/binding/satel/internal/util/EventLogReaderTest.java
Labels: enhancement

#18532 [epsonprojector] Add semantic tags
  bundles/org.openhab.binding.epsonprojector/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.epsonprojector/src/main/resources/OH-INF/update/instructions.xml
Labels: enhancement

#18531 [benqprojector] Add semantic tags
  bundles/org.openhab.binding.benqprojector/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.benqprojector/src/main/resources/OH-INF/update/instructions.xml
Labels: enhancement

#18529 [jrubyscripting] Move console instance check from Java to Ruby code
  bundles/org.openhab.automation.jrubyscripting/pom.xml
  bundles/org.openhab.automation.jrubyscripting/src/main/java/org/openhab/automation/jrubyscripting/internal/JRubyConsoleCommandExtension.java
Labels: bug

#18404 [jrubyscripting] Support using Gemfile with Bundler
  bundles/org.openhab.automation.jrubyscripting/src/main/java/org/openhab/automation/jrubyscripting/internal/JRubyConsoleCommandExtension.java
  bundles/org.openhab.automation.jrubyscripting/src/main/java/org/openhab/automation/jrubyscripting/internal/JRubyScriptEngineConfiguration.java
  bundles/org.openhab.automation.jrubyscripting/src/main/java/org/openhab/automation/jrubyscripting/internal/JRubyScriptEngineFactory.java
  bundles/org.openhab.automation.jrubyscripting/src/main/java/org/openhab/automation/jrubyscripting/internal/watch/BidiSetBag.java
  bundles/org.openhab.automation.jrubyscripting/src/main/java/org/openhab/automation/jrubyscripting/internal/watch/JRubyScriptFileWatcher.java
  bundles/org.openhab.automation.jrubyscripting/src/main/resources/OH-INF/config/config.xml
  bundles/org.openhab.automation.jrubyscripting/src/main/resources/OH-INF/i18n/jrubyscripting.properties
Labels: enhancement

#18393 [wled] Fix + Improve brightness and RGBW segment handling
  bundles/org.openhab.binding.wled/src/main/java/org/openhab/binding/wled/internal/WLedHelper.java
  bundles/org.openhab.binding.wled/src/main/java/org/openhab/binding/wled/internal/api/WledApi.java
  bundles/org.openhab.binding.wled/src/main/java/org/openhab/binding/wled/internal/api/WledApiV0110.java
  bundles/org.openhab.binding.wled/src/main/java/org/openhab/binding/wled/internal/api/WledApiV084.java
  bundles/org.openhab.binding.wled/src/main/java/org/openhab/binding/wled/internal/handlers/WLedSegmentHandler.java
Labels: bug

#18539 [jrubyscripting] Update README.md
  bundles/org.openhab.automation.jrubyscripting/README.md
Labels: documentation

#18555 [jrubyscripting] Upgrade to JRuby 10.0.0.0
  bundles/org.openhab.automation.jrubyscripting/pom.xml
Labels: enhancement

#18530 [enphase] Fix for reading production values for newer enphase software versions.
  bundles/org.openhab.binding.enphase/src/main/java/org/openhab/binding/enphase/internal/dto/PdmEnergyDTO.java
  bundles/org.openhab.binding.enphase/src/main/java/org/openhab/binding/enphase/internal/handler/EnvoyBridgeHandler.java
  bundles/org.openhab.binding.enphase/src/main/java/org/openhab/binding/enphase/internal/handler/EnvoyConnector.java
  bundles/org.openhab.binding.enphase/src/main/java/org/openhab/binding/enphase/internal/handler/EnvoyEntrezConnector.java
Labels: enhancement

#18498 [shelly] Fix BLU package cycle fix
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api2/ShellyBluApi.java
Labels: bug

#18534 [lgwebos] Add semantic equipment tag
  bundles/org.openhab.binding.lgwebos/src/main/resources/OH-INF/thing/thing-types.xml
Labels: enhancement

#18535 [daikin] Add semantic equipment tag
  bundles/org.openhab.binding.daikin/src/main/resources/OH-INF/thing/thing-types.xml
Labels: enhancement

#18553 [tasmotaplug] Add semantic tags
  bundles/org.openhab.binding.tasmotaplug/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.tasmotaplug/src/main/resources/OH-INF/update/update.xml
Labels: enhancement

#18562 [jsscripting] Fix bundled resources not found on windows
  bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/OpenhabGraalJSScriptEngine.java
Labels: bug, regression

#18559 [lgtvserial] Make refresh interval configurable
  bundles/org.openhab.binding.lgtvserial/README.md
  bundles/org.openhab.binding.lgtvserial/src/main/java/org/openhab/binding/lgtvserial/internal/handler/LgTvSerialHandler.java
  bundles/org.openhab.binding.lgtvserial/src/main/resources/OH-INF/config/config.xml
  bundles/org.openhab.binding.lgtvserial/src/main/resources/OH-INF/i18n/lgtvserial.properties
Labels: enhancement

#18556 Add equipment tags
  bundles/org.openhab.binding.monopriceaudio/src/main/resources/OH-INF/thing/dax88.xml
  bundles/org.openhab.binding.monopriceaudio/src/main/resources/OH-INF/thing/monoprice.xml
  bundles/org.openhab.binding.monopriceaudio/src/main/resources/OH-INF/thing/monoprice4.xml
  bundles/org.openhab.binding.monopriceaudio/src/main/resources/OH-INF/thing/monoprice70.xml
  bundles/org.openhab.binding.monopriceaudio/src/main/resources/OH-INF/thing/xantech.xml
  bundles/org.openhab.binding.nuvo/src/main/resources/OH-INF/thing/channels.xml
  bundles/org.openhab.binding.radiothermostat/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.tivo/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.vizio/src/main/resources/OH-INF/thing/vizio.xml
Labels: enhancement

#18550 [kaleidescape] Add semantic tags and format time channels
  bundles/org.openhab.binding.kaleidescape/README.md
  bundles/org.openhab.binding.kaleidescape/src/main/resources/OH-INF/thing/channels.xml
  bundles/org.openhab.binding.kaleidescape/src/main/resources/OH-INF/update/instructions.xml
Labels: enhancement

#18552 [roku] Add semantic tags and format time channels
  bundles/org.openhab.binding.roku/README.md
  bundles/org.openhab.binding.roku/src/main/resources/OH-INF/thing/roku.xml
  bundles/org.openhab.binding.roku/src/main/resources/OH-INF/update/update.xml
Labels: enhancement

#18554 [oppo] Add semantic tags and format time display channel
  bundles/org.openhab.binding.oppo/README.md
  bundles/org.openhab.binding.oppo/src/main/resources/OH-INF/i18n/oppo.properties
  bundles/org.openhab.binding.oppo/src/main/resources/OH-INF/thing/channels.xml
  bundles/org.openhab.binding.oppo/src/main/resources/OH-INF/update/update.xml
Labels: enhancement

#18519 [siemensrds] Allow special characters in login credentials
  bundles/org.openhab.binding.siemensrds/src/main/java/org/openhab/binding/siemensrds/internal/RdsCloudHandler.java
Labels: bug

#18570 [homematic] Fix HM-IP long press button handling
  bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/communicator/virtual/ButtonVirtualDatapointHandler.java
  bundles/org.openhab.binding.homematic/src/test/java/org/openhab/binding/homematic/internal/communicator/virtual/ButtonDatapointTest.java
Labels: bug

#18575 [nuvo] Format Track time channels
  bundles/org.openhab.binding.nuvo/README.md
  bundles/org.openhab.binding.nuvo/src/main/resources/OH-INF/thing/channels.xml
  bundles/org.openhab.binding.nuvo/src/main/resources/OH-INF/update/update.xml
Labels: enhancement

#18572 [wemo] Delete integration tests
  CODEOWNERS
  itests/org.openhab.binding.wemo.tests/NOTICE
  itests/org.openhab.binding.wemo.tests/itest.bndrun
  itests/org.openhab.binding.wemo.tests/pom.xml
  itests/org.openhab.binding.wemo.tests/src/main/java/org/openhab/binding/wemo/internal/discovery/test/WemoDiscoveryOSGiTest.java
  itests/org.openhab.binding.wemo.tests/src/main/java/org/openhab/binding/wemo/internal/discovery/test/WemoDiscoveryParticipantTest.java
  itests/org.openhab.binding.wemo.tests/src/main/java/org/openhab/binding/wemo/internal/discovery/test/WemoLinkDiscoveryServiceOSGiTest.java
  itests/org.openhab.binding.wemo.tests/src/main/java/org/openhab/binding/wemo/internal/handler/test/WemoHandlerOSGiTest.java
  itests/org.openhab.binding.wemo.tests/src/main/java/org/openhab/binding/wemo/internal/handler/test/WemoInsightHandlerTest.java
  itests/org.openhab.binding.wemo.tests/src/main/java/org/openhab/binding/wemo/internal/handler/test/WemoLightHandlerOSGiTest.java
  itests/org.openhab.binding.wemo.tests/src/main/java/org/openhab/binding/wemo/internal/handler/test/WemoMakerHandlerOSGiTest.java
  itests/org.openhab.binding.wemo.tests/src/main/java/org/openhab/binding/wemo/internal/test/GenericWemoLightOSGiTestParent.java
  itests/org.openhab.binding.wemo.tests/src/main/java/org/openhab/binding/wemo/internal/test/GenericWemoOSGiTest.java
  itests/pom.xml
Labels: test

#18578 [bluetooth.bluegiga] Fix NoSuchElementException during initialization
  bundles/org.openhab.binding.bluetooth.bluegiga/src/main/java/org/openhab/binding/bluetooth/bluegiga/handler/BlueGigaBridgeHandler.java
Labels: bug

#18579 Maven Build: Validate Thing-type XML against schema
  pom.xml
  src/thing-type-xml-validation-catalog.xml
Labels: infrastructure

#18522 [gardena] Add semantic tags
  bundles/org.openhab.binding.gardena/src/main/resources/OH-INF/thing/bridge.xml
  bundles/org.openhab.binding.gardena/src/main/resources/OH-INF/thing/thing-types.xml
Labels: enhancement

#18510 [hdpowerview] Add semantic tags
  bundles/org.openhab.binding.bluetooth.hdpowerview/src/main/java/org/openhab/binding/bluetooth/hdpowerview/internal/shade/ShadeHandler.java
  bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/database/ShadeCapabilitiesDatabase.java
  bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/handler/HDPowerViewShadeHandler.java
  bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/handler/ShadeThingHandler.java
  bundles/org.openhab.binding.hdpowerview/src/main/resources/OH-INF/thing/bridge.xml
  bundles/org.openhab.binding.hdpowerview/src/main/resources/OH-INF/thing/channels.xml
  bundles/org.openhab.binding.hdpowerview/src/main/resources/OH-INF/thing/repeater.xml
  bundles/org.openhab.binding.hdpowerview/src/main/resources/OH-INF/thing/shade.xml
Labels: enhancement

#18474 [jdbc] Upgrade MySQL Connector/J to 9.2.0
  bundles/org.openhab.persistence.jdbc/README.md
  bundles/org.openhab.persistence.jdbc/pom.xml
  bundles/org.openhab.persistence.jdbc/src/main/feature/feature.xml
  bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/JdbcConfiguration.java
Labels: enhancement

#18565 [bluetooth.hdpowerview] Set equipment tags dynamically
  bundles/org.openhab.binding.bluetooth.hdpowerview/src/main/java/org/openhab/binding/bluetooth/hdpowerview/internal/shade/ShadeHandler.java
Labels: enhancement

#18538 [miele] Add semantic equipment tags
  bundles/org.openhab.binding.miele/src/main/resources/OH-INF/thing/coffeemachine.xml
  bundles/org.openhab.binding.miele/src/main/resources/OH-INF/thing/dishwasher.xml
  bundles/org.openhab.binding.miele/src/main/resources/OH-INF/thing/fridge.xml
  bundles/org.openhab.binding.miele/src/main/resources/OH-INF/thing/fridgefreezer.xml
  bundles/org.openhab.binding.miele/src/main/resources/OH-INF/thing/hob.xml
  bundles/org.openhab.binding.miele/src/main/resources/OH-INF/thing/hood.xml
  bundles/org.openhab.binding.miele/src/main/resources/OH-INF/thing/oven.xml
  bundles/org.openhab.binding.miele/src/main/resources/OH-INF/thing/tumbledryer.xml
  bundles/org.openhab.binding.miele/src/main/resources/OH-INF/thing/washingmachine.xml
  bundles/org.openhab.binding.miele/src/main/resources/OH-INF/thing/xgw3000.xml
Labels: enhancement

#18581 Improve XML schema validation
  pom.xml
Labels: infrastructure

#18582 [danfossairunit] Add operation channels
  bundles/org.openhab.binding.danfossairunit/README.md
  bundles/org.openhab.binding.danfossairunit/src/main/java/org/openhab/binding/danfossairunit/internal/Channel.java
  bundles/org.openhab.binding.danfossairunit/src/main/java/org/openhab/binding/danfossairunit/internal/ChannelGroup.java
  bundles/org.openhab.binding.danfossairunit/src/main/java/org/openhab/binding/danfossairunit/internal/DanfossAirUnit.java
  bundles/org.openhab.binding.danfossairunit/src/main/java/org/openhab/binding/danfossairunit/internal/protocol/Parameter.java
  bundles/org.openhab.binding.danfossairunit/src/main/resources/OH-INF/i18n/danfossairunit.properties
  bundles/org.openhab.binding.danfossairunit/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.danfossairunit/src/main/resources/OH-INF/update/instructions.xml
Labels: enhancement

#18504 [danfossairunit] Add semantic equipment tag
  bundles/org.openhab.binding.danfossairunit/src/main/resources/OH-INF/thing/thing-types.xml
Labels: enhancement

#18545 [homeconnect] Add semantic tags
  bundles/org.openhab.binding.homeconnect/src/main/resources/OH-INF/thing/thing-types.xml
Labels: enhancement

#18584 [mqtt.homeassistant] Clear internal data when stopping
  bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/handler/HomeAssistantThingHandler.java
Labels: bug

#18542 [icalendar] Add semantic tags
  bundles/org.openhab.binding.icalendar/src/main/resources/OH-INF/thing/thing-types.xml
Labels: enhancement

#18543 [ntp] Add semantic tags
  bundles/org.openhab.binding.ntp/src/main/resources/OH-INF/thing/thing-types.xml
Labels: enhancement

#18546 [solarforecast] Add semantic tags
  bundles/org.openhab.binding.solarforecast/src/main/resources/OH-INF/thing/channel-types.xml
  bundles/org.openhab.binding.solarforecast/src/main/resources/OH-INF/thing/fs-plane-type.xml
  bundles/org.openhab.binding.solarforecast/src/main/resources/OH-INF/thing/fs-site-type.xml
  bundles/org.openhab.binding.solarforecast/src/main/resources/OH-INF/thing/sc-plane-type.xml
  bundles/org.openhab.binding.solarforecast/src/main/resources/OH-INF/thing/sc-site-type.xml
Labels: enhancement

#18547 [hpprinter] Add semantic tags
  bundles/org.openhab.binding.hpprinter/src/main/resources/OH-INF/thing/channel-types.xml
  bundles/org.openhab.binding.hpprinter/src/main/resources/OH-INF/thing/thing-printer.xml
Labels: enhancement

#18589 [energidataservice] Fix `NullPointerException`
  bundles/org.openhab.binding.energidataservice/src/main/java/org/openhab/binding/energidataservice/internal/provider/cache/SpotPriceSubscriptionCache.java
Labels: bug

#18514 [siemensrds] Add semantic tags
  bundles/org.openhab.binding.siemensrds/src/main/resources/OH-INF/thing/thing-types.xml
Labels: enhancement

#18513 [velux] Add semantic tags
  bundles/org.openhab.binding.velux/src/main/resources/OH-INF/thing/bridge.xml
  bundles/org.openhab.binding.velux/src/main/resources/OH-INF/thing/channels.xml
  bundles/org.openhab.binding.velux/src/main/resources/OH-INF/thing/thing-type-actuator.xml
  bundles/org.openhab.binding.velux/src/main/resources/OH-INF/thing/thing-type-rollershutter.xml
  bundles/org.openhab.binding.velux/src/main/resources/OH-INF/thing/thing-type-vshutter.xml
  bundles/org.openhab.binding.velux/src/main/resources/OH-INF/thing/thing-type-window.xml
Labels: enhancement

#18511 [neohub] Add semantic tags
  bundles/org.openhab.binding.neohub/src/main/resources/OH-INF/thing/thing-types.xml
Labels: enhancement

#18518 [openthermgateway] Add semantic tags
  bundles/org.openhab.binding.openthermgateway/src/main/resources/OH-INF/thing/boiler.xml
  bundles/org.openhab.binding.openthermgateway/src/main/resources/OH-INF/thing/channels.xml
  bundles/org.openhab.binding.openthermgateway/src/main/resources/OH-INF/thing/openthermgateway.xml
  bundles/org.openhab.binding.openthermgateway/src/main/resources/OH-INF/thing/ventilationheatrecovery.xml
Labels: enhancement

#14926 [Folderwatcher] Add Azure blob storage containers monitoring support
  bundles/org.openhab.binding.folderwatcher/README.md
  bundles/org.openhab.binding.folderwatcher/src/main/java/org/openhab/binding/folderwatcher/internal/FolderWatcherBindingConstants.java
  bundles/org.openhab.binding.folderwatcher/src/main/java/org/openhab/binding/folderwatcher/internal/FolderWatcherHandlerFactory.java
  bundles/org.openhab.binding.folderwatcher/src/main/java/org/openhab/binding/folderwatcher/internal/api/AzureActions.java
  bundles/org.openhab.binding.folderwatcher/src/main/java/org/openhab/binding/folderwatcher/internal/api/auth/AWS4SignerBase.java
  bundles/org.openhab.binding.folderwatcher/src/main/java/org/openhab/binding/folderwatcher/internal/api/auth/Azure4SignerForAuthorizationHeader.java
  bundles/org.openhab.binding.folderwatcher/src/main/java/org/openhab/binding/folderwatcher/internal/api/auth/AzureSignerBase.java
  bundles/org.openhab.binding.folderwatcher/src/main/java/org/openhab/binding/folderwatcher/internal/api/auth/SignerBase.java
  bundles/org.openhab.binding.folderwatcher/src/main/java/org/openhab/binding/folderwatcher/internal/config/AzureBlobWatcherConfiguration.java
  bundles/org.openhab.binding.folderwatcher/src/main/java/org/openhab/binding/folderwatcher/internal/handler/AzureBlobWatcherHandler.java
  bundles/org.openhab.binding.folderwatcher/src/main/resources/OH-INF/i18n/folderwatcher.properties
  bundles/org.openhab.binding.folderwatcher/src/main/resources/OH-INF/thing/thing-types.xml
Labels: enhancement

#18596 [GHA] Allow rebuild using label rebuild
  .github/workflows/ci-build.yml
  .github/workflows/rebuild.yml
Labels: infrastructure

#18548 [openweathermap] Add semantic tags
  bundles/org.openhab.binding.openweathermap/src/main/resources/OH-INF/thing/bridge-types.xml
  bundles/org.openhab.binding.openweathermap/src/main/resources/OH-INF/thing/channel-types.xml
Labels: enhancement

#18593 [rrd4j] Fix matching archive start date selection
  bundles/org.openhab.persistence.rrd4j/src/main/java/org/openhab/persistence/rrd4j/internal/RRD4jPersistenceService.java
Labels: bug, regression

#18571 [wemo] Refactor HTTP handling and improve port probing reliability
  bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/ApiController.java
  bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/WemoBindingConstants.java
  bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/WemoHandlerFactory.java
  bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/discovery/WemoLinkDiscoveryService.java
  bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/exception/MissingHostException.java
  bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/exception/WemoException.java
  bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/handler/WemoBaseThingHandler.java
  bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/handler/WemoCoffeeHandler.java
  bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/handler/WemoCrockpotHandler.java
  bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/handler/WemoDimmerHandler.java
  bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/handler/WemoHandler.java
  bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/handler/WemoHolmesHandler.java
  bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/handler/WemoInsightHandler.java
  bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/handler/WemoLightHandler.java
  bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/handler/WemoMakerHandler.java
  bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/handler/WemoMotionHandler.java
  bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/handler/WemoSwitchHandler.java
  bundles/org.openhab.binding.wemo/src/main/java/org/openhab/binding/wemo/internal/http/WemoHttpCall.java
Labels: enhancement

#18469 [emotiva] Fix keep alive when adding devices manually
  bundles/org.openhab.binding.emotiva/README.md
  bundles/org.openhab.binding.emotiva/src/main/java/org/openhab/binding/emotiva/internal/EmotivaBindingConstants.java
  bundles/org.openhab.binding.emotiva/src/main/java/org/openhab/binding/emotiva/internal/EmotivaProcessorHandler.java
  bundles/org.openhab.binding.emotiva/src/main/java/org/openhab/binding/emotiva/internal/EmotivaUdpBroadcastService.java
  bundles/org.openhab.binding.emotiva/src/main/java/org/openhab/binding/emotiva/internal/EmotivaUdpReceivingService.java
  bundles/org.openhab.binding.emotiva/src/main/java/org/openhab/binding/emotiva/internal/EmotivaUdpSendingService.java
  bundles/org.openhab.binding.emotiva/src/main/java/org/openhab/binding/emotiva/internal/dto/EmotivaBarNotifyDTO.java
  bundles/org.openhab.binding.emotiva/src/main/java/org/openhab/binding/emotiva/internal/protocol/EmotivaDataType.java
  bundles/org.openhab.binding.emotiva/src/main/java/org/openhab/binding/emotiva/internal/protocol/EmotivaSubscriptionTags.java
  bundles/org.openhab.binding.emotiva/src/main/java/org/openhab/binding/emotiva/internal/protocol/EmotivaXmlUtils.java
  bundles/org.openhab.binding.emotiva/src/main/resources/OH-INF/i18n/emotiva.properties
Labels: bug

#18597 [openweathermap] Fix visibility channels
  bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/handler/OpenWeatherMapOneCallHandler.java
  bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/handler/OpenWeatherMapOneCallHistoryHandler.java
  bundles/org.openhab.binding.openweathermap/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.openweathermap/src/main/resources/OH-INF/update/instructions.xml
Labels: bug

#18594 [enocean] Fix rollershutter open completely
  bundles/org.openhab.binding.enocean/src/main/java/org/openhab/binding/enocean/internal/eep/A5_3F/A5_3F_7F_EltakoFSB.java
Labels: bug

#18174 [shelly] Add support for Shelly BLU Gateway Gen3
  bundles/org.openhab.binding.shelly/README.md
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/discovery/ShellyThingCreator.java
Labels: enhancement

#18608 Improve XML schema validation
  bundles/pom.xml
  bundles/skipXmlValidation.marker
  pom.xml
Labels: infrastructure

#18484 [lutron] Provides device location and names during discovery
  bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/discovery/LeapDeviceDiscoveryService.java
  bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/handler/LeapBridgeHandler.java
  bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/protocol/leap/LeapMessageParser.java
  bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/protocol/leap/LeapMessageParserCallbacks.java
  bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/protocol/leap/Request.java
  bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/protocol/leap/dto/Device.java
  bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/protocol/leap/dto/LeapRequest.java
  bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/protocol/leap/dto/Zone.java
  bundles/org.openhab.binding.lutron/src/main/java/org/openhab/binding/lutron/internal/protocol/leap/dto/ZoneExpanded.java
Labels: enhancement

#18621 [pythonscripting] Add documentation polish
  bundles/org.openhab.automation.pythonscripting/README.md
Labels: documentation

#18612 [teslascope] Provide additional functionality
  bundles/org.openhab.binding.teslascope/README.md
  bundles/org.openhab.binding.teslascope/src/main/java/org/openhab/binding/teslascope/internal/TeslascopeBindingConstants.java
  bundles/org.openhab.binding.teslascope/src/main/java/org/openhab/binding/teslascope/internal/TeslascopeHandler.java
  bundles/org.openhab.binding.teslascope/src/main/java/org/openhab/binding/teslascope/internal/TeslascopeWebTargets.java
  bundles/org.openhab.binding.teslascope/src/main/java/org/openhab/binding/teslascope/internal/api/ChargeState.java
  bundles/org.openhab.binding.teslascope/src/main/java/org/openhab/binding/teslascope/internal/api/ClimateState.java
  bundles/org.openhab.binding.teslascope/src/main/java/org/openhab/binding/teslascope/internal/api/DetailedInformation.java
  bundles/org.openhab.binding.teslascope/src/main/java/org/openhab/binding/teslascope/internal/api/DriveState.java
  bundles/org.openhab.binding.teslascope/src/main/java/org/openhab/binding/teslascope/internal/api/VehicleState.java
  bundles/org.openhab.binding.teslascope/src/main/resources/OH-INF/i18n/teslascope.properties
  bundles/org.openhab.binding.teslascope/src/main/resources/OH-INF/thing/thing-types.xml
  bundles/org.openhab.binding.teslascope/src/main/resources/OH-INF/update/instructions.xml
Labels: enhancement

#18611 [shelly] Add support for Pro 1CB
  bundles/org.openhab.binding.shelly/README.md
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/ShellyBindingConstants.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api/ShellyDeviceProfile.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api2/Shelly2ApiClient.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api2/Shelly2ApiJsonDTO.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/api2/Shelly2ApiRpc.java
  bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/discovery/ShellyThingCreator.java
  bundles/org.openhab.binding.shelly/src/main/resources/OH-INF/i18n/shelly.properties
  bundles/org.openhab.binding.shelly/src/main/resources/OH-INF/thing/shellyGen2_relay.xml
  bundles/org.openhab.binding.shelly/src/test/java/org/openhab/binding/shelly/internal/discovery/ShellyThingCreatorTest.java
Labels: enhancement
