Repository openhab/openhab-addons, pull requests merged in 2025-10, with the labels that each got.

#19395 [icloud] Adds possible need to log in on icloud.com to README.md
  bundles/org.openhab.binding.icloud/README.md
Labels: documentation

#19424 [frenchgovtenergydata] Fix `IllegalArgumentException` for thing type `tempo`
  bundles/org.openhab.binding.frenchgovtenergydata/src/main/java/org/openhab/binding/frenchgovtenergydata/internal/dto/BaseTariff.java
  bundles/org.openhab.binding.frenchgovtenergydata/src/main/java/org/openhab/binding/frenchgovtenergydata/internal/dto/HpHcTariff.java
  bundles/org.openhab.binding.frenchgovtenergydata/src/main/java/org/openhab/binding/frenchgovtenergydata/internal/dto/TempoTariff.java
  bundles/org.openhab.binding.frenchgovtenergydata/src/main/java/org/openhab/binding/frenchgovtenergydata/internal/handler/BaseTariffHandler.java
  bundles/org.openhab.binding.frenchgovtenergydata/src/main/java/org/openhab/binding/frenchgovtenergydata/internal/handler/HpHcTariffHandler.java
  bundles/org.openhab.binding.frenchgovtenergydata/src/main/java/org/openhab/binding/frenchgovtenergydata/internal/handler/TempoTariffHandler.java
Labels: bug

#19409 [ring] Fix `HttpResponseException`: HTTP protocol violation
  bundles/org.openhab.binding.ring/src/main/java/org/openhab/binding/ring/internal/RingHandlerFactory.java
Labels: bug

#19423 [OpenWeatherMap] Add unitHint for ChannelType definitions with ItemType 'Number:Dimensionless'
  bundles/org.openhab.binding.openweathermap/src/main/resources/OH-INF/thing/channel-types.xml
Labels: enhancement

#19163 [avmfritz] Add hint for renaming product brand from FRITZ!DECT to FRITZ!SMART
  bundles/org.openhab.binding.avmfritz/README.md
Labels: documentation

#19355 [freeboxos] Fix synchronization problems
  bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/api/ApiHandler.java
  bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/api/rest/FreeboxOsSession.java
  bundles/org.openhab.binding.freeboxos/src/main/java/org/openhab/binding/freeboxos/internal/api/rest/LoginManager.java
Labels: bug
